### ISSUE TITLE
Get the current font.

### ISSUE THREAD

**Issue by patrick-kidger** [typst/typst#1003]
### Description

Following on from https://github.com/typst/typst/discussions/998: there doesn't seem to be any way to get the current font.

### Use Case

So that another font can be appended to the font list, without needing to manually know which font is currently being used. (In the above link, when looking to add a fallback font that supports emojis.)

**Comment by LaurenzV** [comment]
Also related to #763. It would in general be nice if there were some generalized mechanism to get the current value of settable parameters of functions.

**Comment by AzazKamaz** [comment]
It would be also useful to have some way to get font metrics. It would give a way to (for example) know where overline and underline is by default and offset it from there (as for now overline offset sets it from baseline so we can't just "move overline 2pt up")

This is more than just get previously set rule, with metrics it's also some evaluation

**Comment by laurmaedje** [comment]
Closing in favor of #763. Retrieving font metrics could be a separate feature request.
