### ISSUE TITLE
`ast` is not renamed properly

### ISSUE THREAD

**Issue by johanvx** [typst/typst#1004]
### Description

In the change log of Release v0.3.0, there's a breaking change:

> Renamed a few symbols: What was previous `dot.op` is now just `dot` and the basic `dot` is `dot.basic`. The same applies to `ast` and `tilde`.

So here's a quick test with `typst 0.3.0 (5100046a)`:

```
$ dot quad dot.op quad dot.basic \
  ast quad ast.op quad ast.basic \
  tilde quad tilde.op quad tilde.basic $
```

![`ast` is `ast.basic` but not `ast.op`](https://user-images.githubusercontent.com/61529310/234771870-fcfdfb59-19f0-411a-930c-63cd80deb18d.png)

Obviously, `ast` is not `ast.op` but still `ast.basic`.

### Reproduction URL

https://typst.app/project/p_wljzwejY3F1sbYv2BvpF

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by SUPERCILEX** [comment]
Shucks, I'll take a look tomorrow.

**Comment by SUPERCILEX** [comment]
Oh lol, looks like I moved op up but then put basic above it 🤦‍♂️https://github.com/typst/typst/pull/747/files#diff-26cd7513b13aae27516e0e017d9cd5f3ae7b40684bb8312249f775cb2804b67eR68
