### ISSUE TITLE
new project not creating with "&" in title

### ISSUE THREAD

**Issue by P-R-O-O-F** [typst/typst#1007]
### Description

The problem happened on Opera and Chrome, when i was creating a project , if i put "&" in my title the creation windows closed and i had the blank page from the index again.  my title was "mémoire m1 : ballande france & associé" 

### OS

Windows

**Comment by zouharvi** [comment]
Could not reproduce in Firefox 112 on Ubuntu.

**Comment by Enivex** [comment]
> Could not reproduce in Firefox 112 on Ubuntu.

@reknih said on Discord that a fix was deploying, I just think he hasn't closed the issue yet
