### ISSUE TITLE
UTF-8 BOM encoding not supported

### ISSUE THREAD

**Issue by retsyo** [typst/typst#1010]
### Description

I use [typst-x86_64-pc-windows-msvc.zip](https://github.com/typst/typst/releases/download/v0.3.0/typst-x86_64-pc-windows-msvc.zip) from https://github.com/typst/typst/releases/tag/v0.3.0 on my windows 10 64 bits to compile `bug.typ`, which is saved in UTF8-BOM encoding, with `typst c bug.typ`. 

However, 2 pages are created and the 1st one is empty, what is the problem? Thanks

<pre>

#set page(
  paper: "a4",
  margin: (x: 1.8cm, y: 1.5cm),
)

#set par(first-line-indent: 2em, justify: false)
#show par: set block(spacing: 0.65em)

Adding `rbx` to `rcx` gives
the desired result.

```rust
fn main() {
    println!("Hello World!");
}
```
测试`python`
```python
def fac(i):
    if i<=1:
        return 1
    else:
        return fac(i-1) + fac(i+1)

for i in range(10):
    print(fac(i))
</pre>

![bug](https://user-images.githubusercontent.com/7960913/234883410-6cb9890f-819d-4e97-aaf4-584b4d2500ef.png)




### Reproduction URL

_No response_

### Operating system

_No response_

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Typst does not expect the BOM, which probably ends up on the first page invisibly. Can you save without BOM?

**Comment by laurmaedje** [comment]
No idea whether this should be supported. Do common other programming languages support this?

**Comment by retsyo** [comment]
I think it is common to support BOM, as far as I know, the following program language supports BOM
- rust, where typst is born from
- C via gcc
- cpp via g++
- csharp via csc from microsoft
- freebasic
- go
- lua
- perl
