### ISSUE TITLE
Separating adjacent lists by two or more blank lines

### ISSUE THREAD

**Issue by 0ip** [typst/typst#1015]
### Description

Right now, placing a single blank line between two expected adjacent lists results in a single "wide" (or "non-tight") list, with large spaces between items. This behavior resembles the one seen in Markdown, but it has disadvantages.

```
- a
- b

- x
- y
```
^ This notation results in a single list instead of two independent ones, with large gaps.

Perhaps we could make Typst recognize *two or more* blank lines as a separator for two adjacent lists, so that...

```
- a
- b


- x
- y
```
...results in two lists, not one, without the need to use unwieldy syntax.

### Use Case

As a user, I want to be able to create separate lists without having them automatically merged into a single list. This feature enables me to write them in a more organic fashion and improves the readability of Typst documents.

**Comment by SUPERCILEX** [comment]
That feels a little too dependent on spacing to me, but maybe it's the right approach. In the meantime, you can put a `#hide("")` between them.

**Comment by laurmaedje** [comment]
I agree that two blank lines are a bit too surprising in terms of syntax.
