### ISSUE TITLE
Selectors only work on inherent fields, not on set rule or default fields

### ISSUE THREAD

**Issue by rapiz1** [typst/typst#1024]
### Description

![image](https://user-images.githubusercontent.com/20105061/235075716-7029012a-d05a-49c0-b830-7e7f8248137c.png)

```
#show text.where(style: "normal"): it => [
  #set text(fill: red)
  #it
]

#text(style: "normal")[
  Hello, World
]

#show text: it => [
  #set text(fill: red)
  #it
]

#text(style: "normal")[
  Hello, World
]
```

The first "Hello, World" should also be red.

### Operating system

Web app

### Typst version

- [ ] I am using the latest version of Typst

**Comment by RubixDev** [comment]
Another example of effectively the same thing: a filtered show rule does not respect default values. (the box should be rendered in every case)

![image](https://github.com/typst/typst/assets/35602040/1ceded6f-43b1-40a9-bfa9-a2be52fa8fd2)

````typ
#show raw.where(block: false): box.with(fill: luma(220), inset: (x: 3pt, y: 0pt), outset: (y: 3pt), radius: 2pt)

This is `fn main() {}` some text.

This is ```rust fn main() {}``` some text.

This is #raw("fn main() {}") some text.

This is #raw("fn main() {}", block: false) some text.

This is #raw("fn main() {}", lang: "rust") some text.

This is #raw("fn main() {}", lang: "rust", block: false) some text.
````
