### ISSUE TITLE
Support some math symbols needed in algebra

### ISSUE THREAD

**Issue by txtxj** [typst/typst#1025]
### Description

Hello, I am using typst to write some formulas related to algebraic logic, and find that I can't enter the symbol $\not \models$.

There is a related symbol called `models` $\models$, but putting `not` directly in front of it doesn't output the symbol I want.

If such a symbol were to be added, I think it could be named `models.not` .

---

And another thing, in typst, I can enter `AA BB CC DD` to input $\mathbb{ABCD}$ (mathbb in latex), whitch is really useful in algebraic logic.

But there doesn't  seem to be a way to input $\mathcal{ABCD}$ (mathcal in latex), whitch is also useful in algebraic logic.

### Use Case

The symbol and font are useful in algebraic logic formulas.

**Comment by PgBiel** [comment]
Regarding the first request: `cancel(models)`  (you might need to add some `space` around it for it to look good for now, while #1023 isn't merged)

Regarding the second: you're looking for `$ cal(A) cal(B) cal(C) cal(D) $`

**Comment by txtxj** [comment]
Thank you for your reply.

**Comment by Enivex** [comment]
You can always input unicode characters with an escape sequence, even if they don't have a name

In this case, use \u{22ad}, provided the font you're using has it (Stix Two Math does at least)

$\u{22ad}$

![image](https://user-images.githubusercontent.com/2191754/235139854-a52ba1a0-6d31-4f41-9a33-25591b4d8e34.png)
