### ISSUE TITLE
 Right-Justify Numerals in ordered lists

### ISSUE THREAD

**Issue by ParadaCarleton** [typst/typst#1037]
### Description

[The standard way to align numerals is to right-justify them](https://ux.stackexchange.com/questions/13795/is-there-a-standard-to-left-justify-text-and-right-justify-numeric-values), so that lists should look like:
```
 1.
 2.  
...
10.
```
(Note the space at the start of the first two.)

This keeps the periods aligned, and also means that numbers can move to the left each time a new digit is added. When left-justifying instead, it's possible for numbers to get too long and overlap with the body text. Typst seems to use the opposite convention; it'd be nice to either switch or to have an option for switching (`align` seems not to work for this case).

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
I guess I didn't consider this for #988 (I chose left as the default). I should be making a follow-up PR to fix this (and have the default alignment be to the right). However, I also think there should be an option to control the marker / number alignment on lists and enums, such as `enum(number-align: right)` and `list(marker-align: left)`. @laurmaedje thoughts?

**Comment by laurmaedje** [comment]
Didn't consider this before and I'm not sure about how lists work in RTL scripts, but probably the alignment shouldn't be `right`, but rather `end`.

**Comment by PgBiel** [comment]
> but probably the alignment shouldn't be `right`, but rather `end`.

Oh, right, I forgot this was possible haha! I'll see if I can spin up a quick PR for this. :+1:

**Comment by PgBiel** [comment]
Okay, so, it seems that `end` aligning (by default, at least) can cause some possibly unexpected spacing changes... Is this something we wish?

Before / After:
![image](https://user-images.githubusercontent.com/9021226/235315245-5dace26a-b7a3-4602-bc47-39c40fab7203.png) 
![image](https://user-images.githubusercontent.com/9021226/235315260-a8c50264-4705-4c98-b173-382965394477.png)

**Comment by laurmaedje** [comment]
We should check what LaTeX does

**Comment by PgBiel** [comment]
Okay, LaTeX also seems to default to end-align:
![image](https://user-images.githubusercontent.com/9021226/235316119-f57b8a17-3cb5-4b90-9a03-abb2a7bf20f0.png)

However, I still don't quite get why right/end-align made the numbers come closer to the items (the spacing was apparently reduced(?) for some reason)... I tried changing the default for `body-indent`, but that seemed to change `indent` too somehow... I'll take a look
But it definitely seems that we should be doing end-align by default in the end

**Comment by laurmaedje** [comment]
If `end` and `right` behave differently for LTR direction that is indeed weird.

**Comment by PgBiel** [comment]
> If `end` and `right` behave differently for LTR direction that is indeed weird.

Sorry, they behave the same! I meant to say `right` in the context of LTR specifically. (Honestly, I should have just said `end`, lol.)

End align seems to push things further even when there's no apparent reason to, is what I'm observing. However, maybe that isn't a problem? (But one can see that LaTeX's default spacing is larger than the resulting end-align spacing)

**Comment by laurmaedje** [comment]
I think the dot is overhanging because of text overhang (see #261 for overhang discussion). It's totally stupid and simply shouldn't happen here, of course.

**Comment by PgBiel** [comment]
> I think the dot is overhanging because of text overhang (see #261 for overhang discussion). It's totally stupid and simply shouldn't happen here, of course.

Okay, that actually makes sense - from my observations, enumeration numbers ending with e.g. parentheses, or even the letters in the images I sent, didn't have their spacing affected. So this is probably the dot's fault, indeed. I wonder if there's any way to work around this?

**Comment by laurmaedje** [comment]
You can disable text overhang on the number cell with a style as a temporary fix: `cell.styled(TextElem::set_overhang(false))`

**Comment by PgBiel** [comment]
Great, thanks!
