### ISSUE TITLE
Offical lanague grammar specification? (Neovim, and other editors)

### ISSUE THREAD

**Issue by SeniorMars** [typst/typst#104]
Hello, I just made https://github.com/SeniorMars/typst.nvim which has nothing, but I plan to work on it this week. However, before I started, I wanted to know if there was an official grammar for typst? I found this:

https://github.com/typst/typst/blob/main/tools/support/typst.tmLanguage.json, but it would be beneficial if there was one.

I plan to first work on a tree-sitter grammar, which will probably be very useful for many editors.

**Comment by marekholly** [comment]
[This](https://www.user.tu-berlin.de/laurmaedje/programmable-markup-language-for-typesetting.pdf) should help you. Grammar is specified in Appendix A.

**Comment by SeniorMars** [comment]
Hello, would it be possible to let me see a prominent example of a document using this format? I want to make sure I'm parsing everything right.

**Comment by LaurenzV** [comment]
> [This](https://www.user.tu-berlin.de/laurmaedje/programmable-markup-language-for-typesetting.pdf) should help you. Grammar is specified in Appendix A.

Keep in mind that I think this might already be somewhat out-of-date.

**Comment by laurmaedje** [comment]
Yeah, the thesis is out of date and the textmate grammar is not so great. The only true source is the parser.

**Comment by SeniorMars** [comment]
I heard that 

> [This](https://www.user.tu-berlin.de/laurmaedje/programmable-markup-language-for-typesetting.pdf) should help you. Grammar is specified in Appendix A.

This was written in typst, but I need help finding the code. Is it possible to share it for reference?

**Comment by SeniorMars** [comment]
Hello, is my parsing correct? The docs are a bit ambiguous https://typst.app/docs/reference/types/function/

```
================================================================================
Weird Function Calls
================================================================================

#emph[Hello]
#list[A][B]
#list([A], [B])
#enum(start: 2)[A][B]

--------------------------------------------------------------------------------

(source_file
 (function_call
  (identifier))
 (content_block)
 (function_call
  (identifier))
 (content_block)
 (content_block)
 (function_call
  (identifier)
  (parameters
   (parameter
    (expression
     (content_block)))
   (parameter
    (expression
     (content_block)))))
 (function_call
  (identifier)
  (parameters
   (parameter
    (default_parameter
     (identifier)
     (expression
      (int_literal))))))
 (content_block)
(content_block))
```

**Comment by reknih** [comment]
Tracked in #118
