### ISSUE TITLE
Output PDF mangles copied text for "ft"

### ISSUE THREAD

**Issue by jamesWalker55** [typst/typst#1040]
### Description

The output PDF of typst renders text correctly, however when copying text from the PDF I am unable to copy the text "ft".

Example typst file:

```
after
```

Here is a screenshot of the output PDF:

![image](https://user-images.githubusercontent.com/30405220/235308364-887f6ba9-c24d-4e9a-86ee-73fc22564738.png)

And this is the copied text from the PDF:

```
aer
```

### Operating system

Windows

### Typst version

- [x] I am using the latest version of Typst

**Comment by hanako-eo** [comment]
Hmm, I think it's probably because the 'ft' are tied letter.

**Comment by hanako-eo** [comment]
https://en.wikipedia.org/wiki/Ligature_(writing)
