### ISSUE TITLE
Smartquotes aren't displayed correctly in the outline

### ISSUE THREAD

**Issue by tretre91** [typst/typst#1041]
### Description

When using smartquotes in a heading, if the right quote is followed by any character, then it doesn't display correctly in the outline.

For example:
```typst
= This "works"
= This "doesn't" work, "works"
= "does" "not" "work" either

= 'works'
= 'does not work'.

#outline()

#set text(lang: "fr")

#outline()

#set text(lang: "de")

#outline()
```

produces:

![smartquotes_bug](https://user-images.githubusercontent.com/63788850/235311554-9c97b21a-755a-4ffc-9c25-4a657ab31810.png)

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Good catch @chris-02. The whole thing isn't handled ideally, but the fix seems sensible. Would you mind making a PR?
