### ISSUE TITLE
Underline doesn't apply to inline math

### ISSUE THREAD

**Issue by matthewelmer** [typst/typst#1043]
### Description

The following code:
```typst
#show link: underline
#show link: set text(rgb("#800000"))
#let tbar = $med |$  // Default spacing for "|" is -nasty-
#let dda = $dot.double(upright(a))$
+ *What does the "Bootstrap" part of "Bootstrap Particle Filter" refer to?* \
  The best you're gonna get is page 126 of #link("REDACTED")[S#dda;rkk#dda;'s book]: "_The bootstrap filter_
  (Gordon et al., 1993) is a variation of SIR where the dynamic model $p(bold(x)_k tbar bold(x)_(k-1))$ is
  used as the importance distribution."
```
produces the following output:
![image](https://user-images.githubusercontent.com/26128847/235340144-ce8fadc2-1516-4bb3-8691-25a4c9a2e41a.png)

I presume this is due to the fact that they're technically math characters, but it's the only way I could figure out how to insert umlauts. I propose that
- a pure-text method of inserting umlaut characters be introduced, and
- that math characters be treated consistently with link style

### Operating system

Linux

### Typst version

- [x] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
You can use :
- the direct Unicode character "ä"
- its Unicode escape sequence `\u{e4}`
- an "a" followed by a Unicode combining diaresis (umlaut) `a\u{308}`

Still, math should probably respect the underline.

**Comment by matthewelmer** [comment]
Oh! I had no idea you could do option 2 or 3! I didn't want to do the first option, since I like to avoid copy pasting from random websites to get the symbols I need.

If I may make a suggestion, I think it would be helpful to have options 2 and 3 more prominent within the documentation. Perhaps add an "accents" subsection to the "text" section ([just like the "math" section has](https://typst.app/docs/reference/math/accent/)), so that if someone wants accents in text mode, it's just as easy to find as it currently is for math mode.

**Comment by Enivex** [comment]
In the meantime you can replace underline with a box having a stroke on the bottom as a workaround. (Though that doesn't work through a newline)

**Comment by sbatial** [comment]
I find myself needing colored underlines in math mode from time to time.

I'm open to trying to add that functionality as soon as I'd get to it. 
To not blindly jump in I'd like to ask if the reason it isn't added yet is more because it didn't come up yet or whether it is due to a technical difference in rendering math to PDF?

I suspect/fear the latter... 😅

**Comment by laurmaedje** [comment]
No technical reason for that, just didn't come up yet. :)

**Comment by sbatial** [comment]
Oh. That gives me much more hope for the implementation. 

I feared needing to understand pdf rendering to even attempt implementing that.

**Comment by lf-** [comment]
fyi @mcmuffin6o, there is probably a character picker built into your OS that can do this! In KDE there's KCharSelect, macOS has "Character Viewer", Windows has "Character Map". It is kind of a pain in the butt though. There's also various ways of getting a "compose key" for your computer for faster unicode typing.

**Comment by mcmuffin6o** [comment]
@lf- KCharSelect is exactly what I needed! Thank you so much!

p.s. it works in Cinnamon just fine (in case any fellow Cinnamon enjoyers were curious)

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/typst/issues/2200
