### ISSUE TITLE
Fix MATLAB highlighting in `raw`

### ISSUE THREAD

**Issue by mcmuffin6o** [typst/typst#1045]
### Description

`raw` fails to properly tokenize/color MATLAB code when single quotes are used (as when transposing an array):
![image](https://user-images.githubusercontent.com/26128847/235349631-02addb80-8736-4085-9709-8df01c62cb26.png)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by reknih** [comment]
Blocked by a missing Syntect update #771.

**Comment by laurmaedje** [comment]
Syntect updated landed.
