### ISSUE TITLE
Add support for `.yaml` bib files.

### ISSUE THREAD

**Issue by emme1444** [typst/typst#1048]
### Description

Thanks for this set of awesome tools! I've found myself quickly diving into the ecosystem over the past few days. However, something just slightly annoyed me about the Hayagriva bibliography system. I noticed that while I could load `.yml` files i could not load `.yaml` files. **Am I missing something? Is this intentional?** I traced it down in the source code to the following line.

https://github.com/typst/typst/blob/ecd589a84f24cb0639bb20057d070bf0d9ec4899/library/src/meta/bibliography.rs#L622

I could make a quick PR which would just alter the line to look like the following.

```rust
        "yml" | "yaml" => hayagriva::io::from_yaml_str(src).map_err(format_hayagriva_error),
```

**Is there anything else I need to think about before making this change?**

As far as I understand this is not related to Hayagriva itself. Though I only very quickly took a look at the code over at [typst/hayagriva](https://github.com/typst/hayagriva), it seems as though it is not interested in the file extension as it simply defaults to the yaml format internally.

PS: I didn't really know what categoory of issue to create.

### Use Case

I don't have a strong case, I guess. Though I wouldn't say this is strongly related to the _compiler_.

**Comment by PgBiel** [comment]
I think this warrants a PR.
