### ISSUE TITLE
blockquote

### ISSUE THREAD

**Issue by 1268** [typst/typst#105]
HTML has a Block Quotation element:

https://developer.mozilla.org/docs/Web/HTML/Element/blockquote

looks like LaTeX supports it as well:

https://wikibooks.org/wiki/LaTeX/Paragraph_Formatting#Quoting_text

does Typst have some syntax for this?

**Comment by 4cq2** [comment]
looks like LaTeX supports it as well:

https://wikibooks.org/wiki/LaTeX/Paragraph_Formatting#Quoting_text

**Comment by 4cq2** [comment]
As a workaround, looks like you can use a `rect`:

~~~
#rect(
   fill: gray,
   stroke: black
)[hello world]
~~~

or a `box`:

~~~
#box(
   fill: gray,
   inset: 5pt,
   stroke: black
)[hello world]
~~~

- https://typst.app/docs/reference/layout/box
- https://typst.app/docs/reference/visualize/rect

**Comment by 4cq2** [comment]
As a workaround, looks like you can use a `rect`:

~~~
#rect(fill: gray)[hello world]
~~~

or a `box`:

~~~
#box(
   fill: gray,
   inset: 5pt,
)[hello world]
~~~

or a `block`:

~~~
#block(
   fill: gray,
   inset: 5pt,
)[hello world]
~~~

- https://typst.app/docs/reference/layout/block
- https://typst.app/docs/reference/layout/box
- https://typst.app/docs/reference/visualize/rect

**Comment by joleeee** [comment]
Won't this be natively supported?

**Comment by 4cq2** [comment]
I think `rect` is simple enough, but if other people agree I can reopen the issue

**Comment by laurmaedje** [comment]
We'll probably add a standard (block)quote at some point.

**Comment by tingerrr** [comment]
I'll take a crack at this, and thought about the following design:

```typst
quote(
  // whether or not this is a block quote or an inline quote, useful for show rules
  block: bool,

  // source content (not sure where to display this, but it seems sensible as a
  // link to wrap the quote in? maybe a url instead?)
  source: content,

  // whether or not smartquotes should be added around the body, easy to set once
  quotes: bool,

  // the author, is displayed similar to the example in <blockquote>, or behind an
  // inline quote
  author: content,

  // the quote body
  body,            
)

// scoped functions for granular show and set rules
quote.body(block: bool, quotes: bool, body) // how should this behave for blocks
quote.author(position: align, body)         // are positions sensible similar to caption?
quote.source(position: align, body)         // if source is a url, then this can be removed
```

The default appearance is an interesting topic, I think. Block quotes in emails come to mind, but don't fit at all for anything I could come up for inline quoting. But I think inline quoting would be an important feature.

> quotes
> > nested quote etc

And in a separate PR, this could be extended to include familiar syntax sugar like `>` if that's desired. Not sure about inline, though?

I also tried the examples linked on the LaTeX documentation and tried them in a blank Overleaf project and got very weird results. Not sure what behavior or choices should be taken from LaTeX on that front.

**Comment by laurmaedje** [comment]
Do we really need the scoped functions? That seems like a lot more than for other standard elements.

**Comment by tingerrr** [comment]
> Do we really need the scoped functions? That seems like a lot more than for other standard elements.

I thought of this as mainly a mechanism to easily set the style of a quote, like so:
```typst
#set quote.author: strong
#set quote.body: empth
```

**Comment by laurmaedje** [comment]
I think having to add an extra scoped element for almost every field isn't a good solution long-term. If we think that having this easily modified without a full show rule is important, I believe we need a more general mechanism.
