### ISSUE TITLE
Wrong SVG line thickness in PDF Export

### ISSUE THREAD

**Issue by johannes-wolf** [typst/typst#1063]
### Description

When using SVG (created via Inkscape) lines are rendered super heavy in PDF output. Rastered rendering of the Web-App looks fine.

SVG:
![op-25-1-inversion](https://user-images.githubusercontent.com/519002/235486966-72e56051-d7a0-4524-a4a6-65e9221e6e37.svg)

PDF Rendering:
![grafik](https://user-images.githubusercontent.com/519002/235487019-ddbe9135-8228-41bc-8d0b-8a874bcadd29.png)

Web-App Rendering:
![grafik](https://user-images.githubusercontent.com/519002/235487091-3b8d1699-fb7b-4269-b8dd-26978d178d15.png)

Hand editing the SVG and lowering all `stroke-width` attributes works as a workaround.

### Reproduction URL

https://typst.app/project/r3WnZVT7F94NiikElL2ylN

### Operating system

Web app, Windows, Linux, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
Minimally reproducible example:
```
<svg width="100" height="30" version="1.1" xmlns="http://www.w3.org/2000/svg">
    <rect width="100" height="100" fill="white"></rect>
    <g transform="scale(.1 .1)">
        <line x1="0" x2="100" y1="150" y2="150" stroke="#000" stroke-width="5"/>
    </g>
</svg>
```

What it should look like:
<img width="403" alt="image" src="https://github.com/typst/typst/assets/47084093/f928ec9f-b5f4-4f74-a790-84b991133730">

What it actually looks like:
<img width="951" alt="image" src="https://github.com/typst/typst/assets/47084093/a47bdaf4-765b-4a01-ae03-604b8449d5e6">

Looks to me like the `stroke-width` property is not affected by the scale, even though it should.

**Comment by laurmaedje** [comment]
Fixed thanks to https://github.com/typst/svg2pdf/pull/30

**Comment by MrPixelized** [comment]
Would it be possible to add (back) a way to make the stroke width scale-invariant? I have a bunch of abstract line-drawn SVG icons that I want to render in different sizes, but with a consistent stroke width.

**Comment by LaurenzV** [comment]
The proper way would be to implement the corresponding SVG feature upstream: https://github.com/RazrFalcon/resvg/issues/737
