### ISSUE TITLE
CJK Fonts Bug

### ISSUE THREAD

**Issue by ghost** [typst/typst#1071]
### Description

As for the Chinese character '门', when using a bold font, it renders the font in Japanese, which is very strange:
<img width="816" alt="image" src="https://user-images.githubusercontent.com/45538642/235662461-a5d99639-7937-4b15-9c1d-418c22791117.png">

I use chrome on macOS, and I think this is a font fallback bug of typst. I hope you can fix it when you have time, thank you!

### Reproduction URL

https://typst.app/project/w5uIp-NI9DQxoyG3dmCskI

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by lingyaochu** [comment]
I tried to delete `#show heading:` from the file and finally got the correct result.
![image](https://user-images.githubusercontent.com/43592045/235899604-6853d924-cfd2-4cb1-968b-4c23db795d35.png)
