### ISSUE TITLE
Add typst-cli to crates.io

### ISSUE THREAD

**Issue by SeniorMars** [typst/typst#108]
typst-cli should be able to be installed from `cargo install typst-cli`, but typst-cli is not on crates.io. Could you add support?

**Comment by AntoniosBarotsis** [comment]
If this is something the maintainers want, I could draft a PR that adds this to the existing release workflow.

**Comment by leo848** [comment]
If it is desired to add this install method, I would go a step further and also add the required metadata to support installing via [cargo-binstall](https://github.com/cargo-bins/cargo-binstall).
After having followed the steps described in the crate's [SUPPORT.md](https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md) file, this would provide one of the simplest and most ergonomic ways to install the typst cli without long compile times.

**Comment by laurmaedje** [comment]
I looked into publishing to crates.io, but a first problem was that the CLI embeds fonts, which would need to be part of the package, but crates.io limits package sizes to 10MB.

**Comment by AntoniosBarotsis** [comment]
*I doubt that this is possible but just making sure*, would it be possible to use something like [upx](https://github.com/upx/upx)? I'm guessing not for crates.io but for binstall maybe?

**Comment by leo848** [comment]
> I looked into publishing to crates.io, but a first problem was that the CLI embeds fonts, which would need to be part of the package, but crates.io limits package sizes to 10MB.

Could the fonts potentially be downloaded on first use, if they aren't found in the directories where they normally belong? If that would be an option, the fonts could be ignored for crates.io upload and then only provided on use. Alternatively, a warning could be displayed stating the fonts could not be found, recommending a manual download to ensure proper usability.

**Comment by LaurenzV** [comment]
@laurmaedje This can be closed, right?
