### ISSUE TITLE
Cannot center display math in numbered list

### ISSUE THREAD

**Issue by 3nt3** [typst/typst#1080]
Intended result:
![](https://imgur.com/q4LWbS6.png)

Actual result:
![](https://imgur.com/vIknRnc.png)

Code (minimal example
```typst
+ _Berechne die Wahrscheinlichkeit $P(X = 6)$_
  $ P(X=2) + P(X=4) + P(X=6) = 1 $
```

As a workaround you can add `#box(width: 1fr)` somewhere so it will look correct

**Comment by reknih** [comment]
Duplicate of #529
