### ISSUE TITLE
`eval` directly in content/math mode without string concatenation

### ISSUE THREAD

**Issue by genericusername3** [typst/typst#1083]
### Description

I'd like there to be a way to use something similar to `eval` that interprets its inputs as math mode instead of as a code block, maybe this could be implemented with an additional optional parameter to `eval`.

Currently, one can do this either by using the regular `eval` and surrounding the passed string with `$`, in which case escaping the string itself becomes a problem, or by building the equation from the functions in `math`, which is unwieldy and impractical.

### Use Case

One could want to generate math contents procedurally input without having to manually construct the equation body, e.g. for an iterative sequence:

```typst
#{
  let prev_x = 3;
  for n in range(10) {
    let x = 2 - 1 / prev_x;

    eval("x_(#n) = 2 - 1 / x_(#(n - 1)) = #x", math: true);

    // alternatively, without local variable access in `eval`
    // regular `eval` also doesn't do that, but this makes it less "safe" imo
    eval("x_(" + repr(n) + ") = 2 - 1 / x_(" + repr(n - 1) + ") = " + repr(x), math: true);

    [\ ];

    prev_x = x;
  }
}
```

instead of, e.g.

```typst
#{
  let prev_x = 3;
  for n in range(10) {
    let x = 2 - 1 / prev_x;
    
    eval("$x_(" + repr(n) + ") = 2 - 1 / x_(" + repr(n - 1) + ") = " + repr(x) + "$");
    [\ ];

    prev_x = x;
  }
}
```

or, unwieldily,

```typst
#{
  let prev_x = 3;
  for n in range(10) {
    let x = 2 - 1 / prev_x;
    
    math.equation(
      [#math.attach([x], b: repr(n)) = 2 - #math.frac([1], math.attach([x], b: repr(n - 1))) =  #repr(x)]
    );
    [\ ];

    prev_x = x;
  }
}

**Comment by laurmaedje** [comment]
Your example would best be written like this:
```
#{
  let prev_x = 3;
  for n in range(10) {
    let x = 2 - 1 / prev_x;
    $x_#n = 2 - 1 / x_#(n - 1) = #x$
    [\ ]
    prev_x = x;
  }
}
```

If you use multi-letter variable names instead of "n" and "x", you can also remove the hashtag in front of them.

That said, I can imagine having a `mode: "code" | "content" | "math"` argument. However, I'm wondering what you mean with "escaping the string itself becomes a problem".

**Comment by laurmaedje** [comment]
Unescaped dollar signs are not valid inside of math at the parser level, so just giving `eval` a math option wouldn't solve this. Is it really a problem though? I wouldn't expect to be able to do anything with eval that I can't write in normal syntax.

**Comment by laurmaedje** [comment]
I have implemented a `mode` parameter: https://github.com/typst/typst/commit/f52c39c388c2e3e38be0022fda6d78b12f0a9544
