### ISSUE TITLE
Inline Image Support

### ISSUE THREAD

**Issue by szsoftware** [typst/typst#1084]
Hi there,

thanks for the great project and greetings from Berlin too.

Is there inlining image data support, let's say as base64 or similar, or did I miss something?

I would like to produce documents on the fly without storing imagedata in filesystem after being generated or fetched from somewhere.

Many thanks in advance and keep going with this promising project!

**Comment by arj0019** [comment]
This is an interesting functionality that I would like to implement.

What data formats would you like to see supported?

**Comment by szsoftware** [comment]
Hey there,

sorry for the late reply.

The data formats should primarily be aligned with LaTeX's [https://ctan.org/pkg/inline-images](https://ctan.org/pkg/inline-images)

At least PNG, and JPEG, as far as I know.

SVG would be superpower, but probably this is still covered by Typst?

Have a good time and keep going!

**Comment by szsoftware** [comment]
Wow, cool. Thank you so much!

**Comment by DUOLabs333** [comment]
@LucaCiucci This helped a lot. I will note that usually you can leave out the format, as Typst will automatically recognize the format from the bytes.

**Comment by LucaCiucci** [comment]
@DUOLabs333 oh cool, I didn't know this!
