### ISSUE TITLE
Some translated SVG images render slow

### ISSUE THREAD

**Issue by ghost** [typst/typst#1086]
### Description

When the example svg shown [here](https://github.com/typst/typst/issues/368) is included into the pdf using typst, it renders much slower and requires more cpu (tested with different pdf viewers) than an exported svg to pdf using for example chrome or edge (using ctrl+p, then print to pdf).

This is not really a bug since the output looks as expected, but it would be nice if the produced code would render faster (probably the code generation is less good).

Here are the two output files:

[typst_svg_to_pdf.pdf](https://github.com/typst/typst/files/11381459/typst_svg_to_pdf.pdf)
[edge_svg_to_pdf_export.pdf](https://github.com/typst/typst/files/11381462/edge_svg_to_pdf_export.pdf)

This is also seen with other svg figures (for example from lilypond), not just with the given svg figure.

The behaviour can be seen especially with Firefox (pdf.js) and SumatraPDF. It seems the runtime depend on the SVG figures included. Some render quite slow, some quite fast (I try to add more examples).

**Update**: it seems, the biggest slow down appears, **when fonts are included** (texts are currently drawn as paths). A single zoom in the document takes 10 seconds to render then (tested with svg images from lillypond).
Related: https://github.com/typst/typst/issues/689, https://github.com/typst/typst/issues/371

### Use Case

Including PDFs would not slow down the PDF browsing that much and the overall PDF viewing experience would be better (assuming an SVG was included)

**Comment by LaurenzV** [comment]
SVG conversion has been improved by a lot now, and I don't seem to be able to reproduce the slow rendering issue with the newest version, so I will close this. Feel free to comment again if you are still encountering issues and I will look into it.
