### ISSUE TITLE
Set table column alignment with an array

### ISSUE THREAD

**Issue by songololo** [typst/typst#1087]
### Description

There currently appears to be no way to set the individual column alignment for a table without resorting to fairly complex approaches.

e.g.
```
#table(
    columns: (auto, auto),
    align: (x, y) => (center, left).at(x),
   [center text], [left text],
)
```

### Use Case

It would be simpler and more intuitive to be able to use this pattern:
```
#table(
    columns: (auto, auto),
    align: (center, left),
   [center text], [left text],
)
```

**Comment by arj0019** [comment]
This would be a great feature.
