### ISSUE TITLE
Typst errors out due to old libc on Ubuntu 20.04.5 LTS

### ISSUE THREAD

**Issue by SaadiSave** [typst/typst#109]
# Problem

```text
❯ typst --version
typst: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by typst)
typst: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by typst)
typst: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by typst)
typst: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by typst)
```

# Platform

I am running Ubuntu 20.04.5 LTS (released 2020-04-24, latest patch 2022-09-01), with glibc version 2.31 (released 2020-02-01):

```text
❯ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

```text
❯ ldd --version    
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

# Possible solutions

1. Build binary on slightly older Linux version in CI, e.g. Debian 11 or Ubuntu 20.04/18.04 LTS.
2. Compile using musl target

`(2)` is ideal since musl can be embedded into the binary, providing maximum portability by compiling a static binary with no runtime dependencies. That means it can theoretically run on 10 year old linux too.

# Workarounds

1. Compile from source
2. Upload to crates.io, then `cargo install typst` (Same effect as `(1)`)

I will explore these solutions later this week, or perhaps the next, because I have my uni exams. This issue is similar to https://github.com/JuliaLang/juliaup/pull/334

**Comment by SaadiSave** [comment]
Update about solution `(2)`

Compiling with the following command:

```text
❯ RUSTFLAGS="-Ctarget-feature=+crt-static" cargo build -p typst-cli --release --target x86_64-unknown-linux-musl
```
`target-feature=+crt-static` enables static compilation completely

Produces the following binary:

```text
❯ ldd target/x86_64-unknown-linux-musl/release/typst
	statically linked

❯ du target/x86_64-unknown-linux-musl/release/typst
25264	target/x86_64-unknown-linux-musl/release/typst
```

After adding `lto=fat`:

```text
❯ RUSTFLAGS="-Ctarget-feature=+crt-static -Cembed-bitcode=yes -Clto=fat" cargo build -p typst-cli --release --target x86_64-unknown-linux-musl
```

The binary size is reduced to 19.9 MB

```text
❯ du target/x86_64-unknown-linux-musl/release/typst   
19892	target/x86_64-unknown-linux-musl/release/typst
```

Will soon submit a PR with these changes (without lto initially)

**Comment by reknih** [comment]
Also the issue behind #141

**Comment by michidk** [comment]
This makes the release binaries completely useless, right?

```
typst: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by typst)
typst: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by typst)
typst: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by typst)
typst: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by typst)
```

This blocks me from implementing the typst (vscode) devcontainer feature properly: https://github.com/michidk/devcontainers-features/tree/main/src/typst
Right now I have to install typst by compiling from source (or by using homebrew as temp fix), but this makes building the devcontainers rather slow. Would be nice if I could just download the binary and be done with it.

**Comment by SaadiSave** [comment]
Should I make the PR then?

**Comment by michidk** [comment]
@SaadiSave I just created one (https://github.com/typst/typst/pull/816). Feel free to comment on it!

**Comment by AlistairKeiller** [comment]
Now that the binaries are musl, is this ready to close?

**Comment by SaadiSave** [comment]
Yes, everything works correctly on my system now

**Comment by ameresv** [comment]
Hi! I have a question. I am a newbie both in typst and Ubuntu. I want to install it in my Ubuntu 22.04.3; however, I do not know which procedure have to follow to do that. Can you help me, please?
