### ISSUE TITLE
Embedded rasterized images in SVG files not shown correctly

### ISSUE THREAD

**Issue by cristobaltapia** [typst/typst#1095]
### Description

Hi, I am experiencing the following problem. If I add an SVG image with an embedded rasterized image (e.g. a rasterized contour plot from matplotlib), the image is not placed in the correct position. 

```typ
#image("./test.svg", width: 100mm)
```
![Screenshot-2023-05-04-095408](https://user-images.githubusercontent.com/7276493/236143564-27fa626f-de0d-4876-88c5-8d26ff404ccb.png)

Strangely enough, in the webapp it works correctly. I am using v0.3.0 in Linux (Ubuntu 22.04).

### Reproduction URL

https://typst.app/project/r2p7L79xQmaeGJyhCZ7SD-

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by cristobaltapia** [comment]
Small update. With version 0.4 the problem is still there, but manifests a bit different:

![Screenshot-2023-06-01-102347](https://github.com/typst/typst/assets/7276493/05ce1f25-9c22-47e7-9e63-c354909bfe7e)

**Comment by LaurenzV** [comment]
Will be fixed once [this PR](https://github.com/typst/svg2pdf/pull/34) gets merged and upstreamed.

**Comment by cristobaltapia** [comment]
That looks amazing! Thanks for doing all that work!
