### ISSUE TITLE
Leaving a shared project is only possible from grid view

### ISSUE THREAD

**Issue by Enivex** [typst/typst#1099]
### Description

I'd like to be able to remove projects from under "Shared with me".

I do not think this is currently possible. The delete symbol is obviously gone, since they're read-only, but there should be a way to simply remove them.
![image](https://user-images.githubusercontent.com/2191754/236198075-e2755c56-e107-4996-9ed2-11b3e60b4217.png)

### Use Case

After clicking on a bunch of shared documents my interface is cluttered with projects I'd like to remove. This seems like a basic feature to have.

**Comment by reknih** [comment]
Done

**Comment by Enivex** [comment]
@reknih the button currently only appears when the projects are displayed as a grid, and not as a table.

![image](https://github.com/typst/typst/assets/2191754/c767616b-4908-4ca6-a19c-13f60eb23765)

![image](https://github.com/typst/typst/assets/2191754/8d68594a-d1e0-42e4-bdf0-c8c85a657ce7)

**Comment by reknih** [comment]
Sorry for the oversight!
