### ISSUE TITLE
Rect does not wrap contents completely

### ISSUE THREAD

**Issue by Kreijstal** [typst/typst#1101]
### Description

rect does not fill the contents
consider the example
```
#set page(
  width: auto,
  height:auto,
  margin: (x: 0cm,y:1pt),
)
#rect(fill:blue,width:auto,height:auto,inset:0pt,"hello")
```

![grafik](https://user-images.githubusercontent.com/2415206/236210767-3626e94e-88b2-49d2-ae40-cab49603e801.png)
Hello is not wrapped completely on rect.

### Operating system

Web app

### Typst version

- [x] I am using the latest version of Typst

**Comment by Enivex** [comment]
This is not a bug, the relevant setting here is https://typst.app/docs/reference/text/text/#parameters--top-edge

I believe the default is "cap-height", which matches the height of uppercase

![image](https://user-images.githubusercontent.com/2191754/236217226-dfcbda80-fcbb-4b6b-8ce4-cea2a346731b.png)

You can change it to "ascender" instead, but then it'll be "too tall"
`#rect(fill:blue,width:auto,height:auto,inset:0pt,text(top-edge: "ascender", "Hello hello."))`
![image](https://user-images.githubusercontent.com/2191754/236218117-e63b840f-25e0-49e1-ae8f-be51754bd7d4.png)

You could argue that there should be an additional option that actually finds the exact height of the text, but it'd likely be very computationally expensive.

**Comment by Enivex** [comment]
This is actually a duplicate

https://github.com/typst/typst/issues/469

**Comment by Enivex** [comment]
See above
