### ISSUE TITLE
Make default values clearer in the documentation

### ISSUE THREAD

**Issue by Enivex** [typst/typst#1102]
I realized this because of https://github.com/typst/typst/issues/1101

Nowhere in https://typst.app/docs/reference/text/text/#parameters--top-edge is it mentioned what the actual default is. This is fairly ubiquitous throughout the documentation. Sometimes the default is mentioned in the description, such as https://typst.app/docs/reference/layout/block/#parameters--above, but more often than not it's not.

**Comment by laurmaedje** [comment]
Will add it. Wasn't originally there because I didn't want to do it manually and the infrastructure for generating it automatically wasn't there, but now it should be quite simple to autogenerate.
