### ISSUE TITLE
Broken OpenType slanted fractions

### ISSUE THREAD

**Issue by Gewi413** [typst/typst#1105]
### Description

When using text with `#set text(fractions:true)`, but not rendering fractions, the output doesn't behave too well
```
#set text(fractions: true)
1 20 333333 1/4 1/5/5 6/ /7
```
renders as
![image](https://user-images.githubusercontent.com/41789317/236301199-14c8b599-c16e-4970-9888-7f4586283920.png)

whereas it should look like (or something similar)
![image](https://user-images.githubusercontent.com/41789317/236301255-f8f6de76-9b87-4f09-9ca1-6c43804474a9.png)

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Can't change anything about how the OpenType feature works, but I added a note to the docs that advises against enabling this property globally.
