### ISSUE TITLE
Regex Replace Broken/Changed ?

### ISSUE THREAD

**Issue by ondohotola** [typst/typst#1108]
### Description

I use RCS for version control in a single user environment.

On `typst 0.3.0 (6ad14f55)` 

```typst
#let revision = "$Revision: 1.29 $"
#let revision = revision.replace(regex("\$\w+:\s+(\d+\.\d+)\s+\$"),"$1")
```
produces `$1` whereas on 

`typst 0.3.0 (021694de)`

same produces the expected `1.29`.

If that's a change in behaviour, how would I get the new version to extract the Revision Number?

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by ondohotola** [comment]
Ah, ok, thank you.

The joys of nightly builds :-)-O

I'll wait for it to be fixed then.

**Comment by Enivex** [comment]
What you actually want is
```
#let revision = "$Revision: 1.29 $"
#revision.match(regex("\$\w+:\s+(\d+\.\d+)\s+\$")).captures.first()
```
and this works in the dev version as well.

(If you absolutely want to use replace for some reason, then #revision.replace(regex("\$\w+:\s+(\d+\.\d+)\s+\$"),m => {m.captures.first()}) works in the dev version)

**Comment by Enivex** [comment]
By the way:
````
#let revision = "$Revision: 1.29 $"
#revision.trim(regex("\D"))
````
is much easier

**Comment by ondohotola** [comment]
Thank you very much.

That's what you get when you let an elderly Gynecologist dabble in regular expressions :-)-O

**Comment by PgBiel** [comment]
> It seems like PR #944 introduced this "regression". (commit [be3c4d7](https://github.com/typst/typst/commit/be3c4d7876f11d70eab60b8c3ae6199b7fd035fe))

Actually, from local testing, the commit that introduced this regression(/breaking change, if intentional) was 519e8a7b4c41debf7c0a9ef0ea4ebdc09995451a (@laurmaedje 's refactor of the PR).

**Comment by laurmaedje** [comment]
I didn't do this intentionally, but also wasn't aware that this was supported before. It seems to be behaviour of the regex crate. Not sure whether we want it. In general, I'm not a fan of magic string syntax and now you can just do it with a replacer function that accesses the captures.
