### ISSUE TITLE
Add Script Capital L (U+2112, Laplace symbol)

### ISSUE THREAD

**Issue by RamtinTJB** [typst/typst#1112]
### Description

The [Script Capital L](https://www.compart.com/en/unicode/U+2112) symbol is missing from the symbol collection of Typst. Please add it to the symbol collection.

### Use Case

It can be useful in writing Laplace transforms for differential equations.

**Comment by Enivex** [comment]
It's `$ cal(L) $`. Though it might look different depending on the font.

**Comment by laurmaedje** [comment]
> It's $ cal(L) $.

This is the correct way to do it.

**Comment by tani** [comment]
Excuse me, in unicode (and of course mathematical usage), we mathematician distinct the ℘ (script capital) and 𝒫 (mathematical script capital). For example, we specially use ℘ to represent the Weierstrass function (see the below link please). Further, in LaTeX and HTML provides the special command `\wp` and `&wp;` (**W**eierstrass **P**). I would like to ask you to reopen the issue to use ℘ and other Script Capital fonts.

https://www.compart.com/en/unicode/U+1D4AB

**Comment by Enivex** [comment]
> Excuse me, in unicode (and of course mathematical usage), we mathematician distinct the ℘ (script capital) and 𝒫 (mathematical script capital). For example, we specially use ℘ to represent the Weierstrass function (see the below link please). Further, in LaTeX and HTML provides the special command `\wp` and `&wp;` (**W**eierstrass **P**). I would like to ask you to reopen the issue to use ℘ and other Script Capital fonts.
> 
> https://www.compart.com/en/unicode/search?q=script+capital#characters

Create a new issue

**Comment by tani** [comment]
Script Capital that is specifically addressed in this table (https://www.compart.com/en/unicode/block/U+2100) has the following aliases

| Alphabet | Script Capital  | Mathematical Script Capital | HTML Alias            | Ascr-like HTML Entity |
|------|-----------------|-----------------------------|-----------------------|-----------------------|
| A    | N/A             | U+1D49C (𝒜)                 | N/A                   | `&Ascr;`              |
| B    | U+212C (ℬ)      | N/A                         | `&Bernoullis;`        | `&Bscr;`              |
| C    | N/A             | U+1D49E (𝒞)                 | N/A                   | `&Cscr;`              |
| D    | N/A             | U+1D49F (𝒟)                 | N/A                   | `&Dscr;`              |
| E    | U+2130 (ℰ)      | N/A                         | `&expectation;`       | `&Escr;`              |
| F    | U+2131 (ℱ)      | N/A                         | `&Fouriertrf;`        | `&Fscr;`              |
| G    | N/A             | U+1D4A2 (𝒢)                 | N/A                   | `&Gscr;`              |
| H    | U+210B (ℋ)      | N/A                         | `&HilbertSpace;`      | `&Hscr;`              |
| I    | U+2110 (ℐ)      | N/A                         | `&Iscr;`              | `&Iscr;`              |
| J    | N/A             | U+1D4A5 (𝒥)                 | N/A                   | `&Jscr;`              |
| K    | N/A             | U+1D4A6 (𝒦)                 | N/A                   | `&Kscr;`              |
| L    | U+2112 (ℒ)      | N/A                         | `&Laplacetrf;`        | `&Lscr;`              |
| M    | U+2133 (ℳ)      | N/A                         | `&Mscr;`              | `&Mscr;`              |
| N    | N/A             | U+1D4A9 (𝒩)                 | N/A                   | `&Nscr;`              |
| O    | N/A             | U+1D4AA (𝒪)                 | N/A                   | `&Oscr;`              |
| P    | U+2118 (℘)      | U+1D4AB (𝒫)                 | `&wp;`                | `&Pscr;`              |
| Q    | N/A             | U+1D4AC (𝒬)                 | N/A                   | `&Qscr;`              |
| R    | U+211B (ℛ)      | N/A                         | `&Rscr;`              | `&Rscr;`              |
| S    | N/A             | U+1D4AE (𝒮)                 | N/A                   | `&Sscr;`              |
| T    | N/A             | U+1D4AF (𝒯)                 | N/A                   | `&Tscr;`              |
| U    | N/A             | U+1D4B0 (𝒰)                 | N/A                   | `&Uscr;`              |
| V    | N/A             | U+1D4B1 (𝒱)                 | N/A                   | `&Vscr;`              |
| W    | N/A             | U+1D4B2 (𝒲)                 | N/A                   | `&Wscr;`              |
| X    | N/A             | U+1D4B3 (𝒳)                 | N/A                   | `&Xscr;`              |
| Y    | N/A             | U+1D4B4 (𝒴)                 | N/A                   | `&Yscr;`              |
| Z    | N/A             | U+1D4B5 (𝒵)                 | N/A                   | `&Zscr;`              |

It is preferable to handle properly named symbols in the form `wp` in typst as well.

**Comment by Enivex** [comment]
> Script Capital that is specifically addressed in this table (https://www.compart.com/en/unicode/block/U+2100) has the following aliases
> 
> | Alphabet | Script Capital  | Mathematical Script Capital | HTML Alias            | Ascr-like HTML Entity |
> |------|-----------------|-----------------------------|-----------------------|-----------------------|
> | A    | N/A             | U+1D49C (𝒜)                 | N/A                   | `&Ascr;`              |
> | B    | U+212C (ℬ)      | N/A                         | `&Bernoullis;`        | `&Bscr;`              |
> | C    | N/A             | U+1D49E (𝒞)                 | N/A                   | `&Cscr;`              |
> | D    | N/A             | U+1D49F (𝒟)                 | N/A                   | `&Dscr;`              |
> | E    | U+2130 (ℰ)      | N/A                         | `&expectation;`       | `&Escr;`              |
> | F    | U+2131 (ℱ)      | N/A                         | `&Fouriertrf;`        | `&Fscr;`              |
> | G    | N/A             | U+1D4A2 (𝒢)                 | N/A                   | `&Gscr;`              |
> | H    | U+210B (ℋ)      | N/A                         | `&HilbertSpace;`      | `&Hscr;`              |
> | I    | U+2110 (ℐ)      | N/A                         | `&Iscr;`              | `&Iscr;`              |
> | J    | N/A             | U+1D4A5 (𝒥)                 | N/A                   | `&Jscr;`              |
> | K    | N/A             | U+1D4A6 (𝒦)                 | N/A                   | `&Kscr;`              |
> | L    | U+2112 (ℒ)      | N/A                         | `&Laplacetrf;`        | `&Lscr;`              |
> | M    | U+2133 (ℳ)      | N/A                         | `&Mscr;`              | `&Mscr;`              |
> | N    | N/A             | U+1D4A9 (𝒩)                 | N/A                   | `&Nscr;`              |
> | O    | N/A             | U+1D4AA (𝒪)                 | N/A                   | `&Oscr;`              |
> | P    | U+2118 (℘)      | U+1D4AB (𝒫)                 | `&wp;`                | `&Pscr;`              |
> | Q    | N/A             | U+1D4AC (𝒬)                 | N/A                   | `&Qscr;`              |
> | R    | U+211B (ℛ)      | N/A                         | `&Rscr;`              | `&Rscr;`              |
> | S    | N/A             | U+1D4AE (𝒮)                 | N/A                   | `&Sscr;`              |
> | T    | N/A             | U+1D4AF (𝒯)                 | N/A                   | `&Tscr;`              |
> | U    | N/A             | U+1D4B0 (𝒰)                 | N/A                   | `&Uscr;`              |
> | V    | N/A             | U+1D4B1 (𝒱)                 | N/A                   | `&Vscr;`              |
> | W    | N/A             | U+1D4B2 (𝒲)                 | N/A                   | `&Wscr;`              |
> | X    | N/A             | U+1D4B3 (𝒳)                 | N/A                   | `&Xscr;`              |
> | Y    | N/A             | U+1D4B4 (𝒴)                 | N/A                   | `&Yscr;`              |
> | Z    | N/A             | U+1D4B5 (𝒵)                 | N/A                   | `&Zscr;`              |
> 
> It is preferable to handle properly named symbols in the form `wp` in typst as well.
> Further, the duplicated symbols are P only.

All of them, minus the Weierstrass P, are accessible through `cal()`

**Comment by tani** [comment]
Yes, you are right.

**Comment by chinuckb** [comment]
> It's `$ cal(L) $`. Though it might look different depending on the font.

This helped me. Thank you
