### ISSUE TITLE
Add text watermark when exporting PDF

### ISSUE THREAD

**Issue by siu91** [typst/typst#1115]
### Description

There are some internal documents, which are for the use of internal company employees only, and may not be used for any commercial purposes or non-company activities. So you want to add a watermark when exporting PDF。

### Use Case

using the command line：
typst compile path/to/source.typ path/to/output.pdf -w “my-pdf”

**Comment by Enivex** [comment]
This feature already exists. You can set a background,band watermarks is one suggested use.

https://typst.app/docs/reference/layout/page/#parameters--background
