### ISSUE TITLE
Reserved words

### ISSUE THREAD

**Issue by StrangeGirlMurph** [typst/typst#1123]
### Description

There should be a list of reserved words that typst uses which can't be used as variable names and there should be a better error message for corresponding errors.

I will just post a screenshot here with an example. I am busy...
![image](https://user-images.githubusercontent.com/62220780/236631492-e871ac5b-6299-405a-9eca-88539ae77feb.png)

### Use Case

I didn't know that "as" was part of the reserved words. I still don't know what it's used for. I can't find anything about it in the docs. That's why I had no idea why `#let as = ...` wasn't working. A better error message would help a lot + better docs.

**Comment by laurmaedje** [comment]
New error message:
![image](https://github.com/typst/typst/assets/17899797/aef28cf7-ff8b-4ac9-914a-a1b90cbaa620)
