### ISSUE TITLE
surprising rect height behavior in grid "cell"

### ISSUE THREAD

**Issue by waynr** [typst/typst#113]
In https://typst.app/docs/reference/visualize/rect/ I see the definition of height being:

> The rectangle's height, relative to its parent container.

Yet the following code seems to suggest that the grid elements don't count as parent containers of the rectangles since each row takes up 100% of the height of the page:

```
#let cell = rect.with(
	inset: 8pt,
	width: 100%,
	stroke: none,
	radius: 6pt
)

#grid(
	columns: (2fr, 1fr),
	rows: (10pt, auto),
	cell(height: 100%)["meow"],
	cell(height: 100%)["meow"],
	cell(height: 100%)["meow"],
	cell(height: 100%)["meow"],
)
```

ie without adding any page breaks or other content, compiling this document results in a 2-page pdf with a single row of `"meow"`s on each.

...thinking about this a little more, I guess this has to do with the `auto` in  

```
	rows: (10pt, auto),
```

This makes sense, but it's kind of unintuitive since `auto` seems to be the default (eg if i remove that setting from the grid, i still get a two-page pdf).

I guess this is kind of my own mistake, but I'll continue filing the issue anyway in case anyone else encounters it in the future.

That being said, maybe there is also some kind of more intuitive behavior in this case. What seems to be happening is that when the grid `rows` is set to `auto` it defers to the content of the tallest row element to determine the height of the row, but the rectangle itself is trying to only take up the maximum height of its parent container. It's not intuitive in this context that the parent container is the page. Maybe the more intuitive behavior would be for the `rect` to detect that its actual immediate parent is a grid cell with a row height set to `auto` act as if the `rect` `height` parameter wasn't event set :thinking:

**Comment by laurmaedje** [comment]
I don't really see a good alternative here for auto rows. They are "transparent" for relative sizing. Closing this for now.

**Comment by valpackett** [comment]
I think this behavior might be new-ish??

Check this out:
https://github.com/elegaanz/vercanard/blob/main/demo.pdf

Building that template right now it's not like that, the grid ends up on the second page due to the box being `height: 100%`.

So not even the whole grid itself counts as a parent container?
