### ISSUE TITLE
Show rule for math symbols breaks from 0.2.0 -> 0.3.0

### ISSUE THREAD

**Issue by thygesteffensen** [typst/typst#1130]
### Description

I want to add space around some symbols to make equations more readable. The first line in the image below is the desired result, and the second line is the default output:
![image](https://user-images.githubusercontent.com/31892312/236667073-9bd0ba24-5f55-4327-83f4-3c9dc45f2cf9.png)

This is achieved by: 
```typ
#show math.tack: it => {$#h(1em)#it#h(1em)$}

$
    a tack b
$
```

This is working using version 0.2.0 of the compiler, but in version 0.3.0 the following error is emitted:
```
error: expected function, label, string, regular expression, or selector, found symbol
  ┌─ example.typ:1:8
  │
1 │ #show math.tack: it => {$#h(1em)#it#h(1em)$}
```

---
I don't see this in the list over breaking chances going from 0.2.0 to 0.3.0, but it might be related to:
> * Fixed hiding and show rules in math

_Thanks for creating Typst - it's awesome :rocket:_

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
That was unintentional!

**Comment by sitandr** [comment]
I used `git bisect` to detect that it was broken in the last commit before 0.3.0, 39dfa33059293251f1e2890f9b3d0e3dc178ed03. There are lots of changes there, but hope that helps. It was the issue I thought was intentional and marked it as a feature request in my #1051.
