### ISSUE TITLE
New file synced with main.typ

### ISSUE THREAD

**Issue by RilDev** [typst/typst#1131]
### Description

When I create a new file, it is synced to `main.typ`.
If I edit one, the other is edited as well.

Reproduction step:
- click on the + sign to add a new file.
- edit the new file.
- check `main.typ`.

![Kapture 2023-05-07 at 12 34 54](https://user-images.githubusercontent.com/13135150/236672777-5a41edff-c546-446f-bd1c-db923c991021.gif)

NOTE: reloading the page fixed the issue for me.

### Browsers

Chrome

### OS

macOS

**Comment by reknih** [comment]
I have fixed this issue, the change is rolling out.
