### ISSUE TITLE
suggestion: compile export to png

### ISSUE THREAD

**Issue by lino-levan** [typst/typst#1150]
### Description

Typst looks super cool, but, the main blocker to my adoption of the tool is that there isn't an easy way (as far as I can see) to export a `.typ` file to a `.png` (or other image format). It seems to me that this feature would not be a huge lift from a technical perspective as it already exists in testing (ref: https://github.com/typst/typst/blob/b6a241cad232d920154986781c6f09d83dc1b6f6/tests/src/tests.rs#LL785C11-L785C11).

After a conversation on the discord:
- There's probably a good reason to why this isn't in the core CLI already
- There might be a concern regarding how to split pages (but in my opinion, that's easily solvable by one flag with a good default)

### Use Case

My current configuration with alternative tools involves exporting the format as an image. This would allow me to adopt Typst over alternatives in my workflow.

I'd be willing to open a PR if desired. Thanks!

**Comment by laurmaedje** [comment]
A PR would be welcome. There's already one, but it has gone stale. Regarding the page split, what would be your proposed flag?

**Comment by lino-levan** [comment]
Not sure what the name should be, but that's a bikeshedding topic. Something like `--merge-pages` would be my proposal. I'll open a PR.

**Comment by lino-levan** [comment]
> Would't a simpler solution be a pipe to imagemagick?

Sorry, could you clarify?

**Comment by owiecc** [comment]
See #410 You should be able to do something like this: 

`typst compile file.typ /dev/stdout | convert - -crop ... result.png`

**Comment by reknih** [comment]
Typst already contains a renderer for the web app and test case images. Only the CLI interface for this is missing.
