### ISSUE TITLE
Control PDF viewer using DDE commands

### ISSUE THREAD

**Issue by Holt59** [typst/typst#1152]
### Description

With some LaTeX compiler, it is possible to configure external viewer (e.g. SumatraPDF) to redirect to the source file when performing a specific action (e.g. Ctrl+Click).

It would be nice if there were such option in `typst` with `watch` and `compile` so that one could configure the viewer to redirect appropriately.

### Use Case

No specific use-case, it would be a nice feature in general.

**Comment by reknih** [comment]
SumatraPDF realizes this [by supporting Dynamic Data Exchange (DDE) commands](https://www.sumatrapdfreader.org/docs/LaTeX-integration) which a TeX editor plugin would issue based on user interaction and [SyncTeX](https://tex.stackexchange.com/questions/118489/what-exactly-is-synctex) data.

DDE is a Windows-only technology and as far as I can see, only [Sumatra](https://www.sumatrapdfreader.org/docs/DDE-Commands) and [Adobe Acrobat](https://opensource.adobe.com/dc-acrobat-sdk-docs/library/interapp/IAC_DevApp_DDE_Support.html) support it. Adobe even discourages from using this technology. There is no standard or de-facto standard for the set of supported DDE commands, so an implementation would need to tightly couple with a particular reader.

For these reasons, we won't be implementing this.
