### ISSUE TITLE
Issues with the APA citation style

### ISSUE THREAD

**Issue by heigren** [typst/typst#1161]
### Description

The APA citation and bibliography style does not produce the correct output.

Given the following BibLaTeX file:

```
@inbook{EX-INBOOK,
   author = {Lastname, Firstname},
   title = {Title of the chapter},
   booktitle = {Title of the book},
   editor = {Editor, Firstname},
   publisher = {Great Publisher},
   pages = {185--206},
   doi = {10.1000/123456789},
   year = {2022},
   type = {Book Section}
}

@article{EX-ART,
    author = {Article, Firstname},
    title = {{A long and convoluted title: A literature review}},
    year = {2016},
    journal = {{Journal of Testing Citations}},
    volume = {9},
    number = {3},
    pages = {{225--245}},
    doi = {10.1000/123456789},
}
```

The result from Typst (using the web app) is shown in the picture below.
![Result from Typst](https://github.com/typst/typst/assets/726720/f5e8df6a-fd77-4f42-9be5-7dd6e7a3ddd8)

This is the expected result, here produced using Overleaf:
![Expected result](https://github.com/typst/typst/assets/726720/b5da721b-a95d-4ac7-9137-c4a017962e89)

From my testing it seems that the main issues are with the delimiter in the in-text citation and the section of a book in the bibliography. I haven't tested all possible types, so I am not certain. 

### Reproduction URL

https://typst.app/project/pgPDyDevci-vCyL4quTOxW

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by rkuijt** [comment]
Adding the following issues with APA (7th edition) formatting as well:

**Missing comma between the last author and year**
Expected: `(Beeblebrox, 2021)`
Got: `(Beeblebrox 2021)`

**Multiple references should be merged within single parentheses, separated by a semicolon ...**
... in the same order in which they will appear in your reference list (i.e. alphabetical order, then oldest to newest for works by the same author)
Expected: `(Beeblebrox, 2021; Dent, 2015)`
Got: `(Dent 2015) (Beeblebrox 2021)`

Formatting source: https://libguides.jcu.edu.au/apa/authors

**Comment by cherryblossom000** [comment]
Another issue: if a URL has an access date, there should be no parentheses:
> *Title*. Retrieved May 26, 2023, from https://example.com

Currently, using the Hayagriva format doesn't even show the retrieved date if there is a `date` property for the source. Using BibTeX sort of works except the formatting is incorrect:
> *Title*. (Retrieved May 26, 2023, from https://example.com)

**Comment by PlayerNameHere** [comment]
Looking at `typst`'s source code [here](https://github.com/typst/typst/blob/08b49291bc876d948bfd2c90cb05796efc1254a6/library/src/meta/bibliography.rs#LL264C25-L264C25), APA citations fall back to the `chicago-author-date` style, since Hayagriva itself doesn't seem to implement the citation format for APA. `chicago-author-date` is close to APA, but it is different at the end of the day.

**Comment by neumannjan** [comment]
I put together a quick hacky function that allows you to cite in proper APA style, both in the standard way as well as without parentheses. Additionally, it allows you to print just the author's name if you need.

The example below

```lua
#apacite("example", "exampleNoDate", "example")

#apacite("example", brackets: false)

#apacite("example", date: false, brackets: false)
```

will render like this (with an appropriate bibliography file):
<img width="600" alt="image" src="https://github.com/typst/typst/assets/7883957/260aa785-61da-452e-b38f-4c33492e26ce">

This is the function:

```lua
#let apacite(..authors, brackets: true, date: true) = {
    if brackets [(] else []
    authors.pos().map(a => {
        show regex(" \d+"): v => {
            if date {
                if brackets [,#v] else {
                    show " ": vv => []
                    [ (#v)]
                }
            } else []
        }
        show ", n.d.": v => {
            if date {
                if brackets [#v] else [ (n.d.)]
            } else []
        }
        cite(a, brackets: false, style: "chicago-author-date")
    }).join("; ", last: "; ")
    if brackets [)] else []
}
```

**Comment by gertminov** [comment]
I would like to offer another incredibly hacky solution.
By modifying [hayagriva](https://github.com/typst/hayagriva), the bibliography management tool that acctually produces the citation string, you can get pretty close to APA style citations  (comma after names, "et al." with 3 or more authors and "&" instead of "and" with 2 authors), while still using the build in citation functionality.  
I know very little rust, so I just modified the chicago-author-date citation style.

If you are on windows you can download i precompiled version of typst 0.7.0 from my repo, but i also included instructions to build typst with the modified hayagriva yourself

https://github.com/gertminov/hayagriva

**Comment by Zollerboy1** [comment]
I have started a PR over at typst/hayagriva#63 that implements the APA citation style. If this PR gets merged, it should be a matter of a few minutes to get this style working for Typst as well. I know this doesn't solve all the problems mentioned in this issue, but it solves the most pressing ones (I hope).

**Comment by reknih** [comment]
Typst 0.9.0 now uses the same style definitions as Zotero for APA and all other styles. This fixes the issues here.
