### ISSUE TITLE
CLI: Output Diagnostics in Unix-Style Format

### ISSUE THREAD

**Issue by erikwastaken** [typst/typst#1168]
### Description

Allow users to have the CLI report diagnostics in a short format like `chap1.typ:15:10: error message` instead of the arguably prettier standard output.

This could be controlled by a command line argument or an environment variable, not sure, which option would be better.

### Use Case

This format is easier to parse and supported out of the box by common tools like vim. The current standard output via codespan-reporting contains ANSI escape sequences for things like style and color that are not handled well by tools expecting plain text.

Codespan already supports this kind of output by using `ColorChoice::Never` for the writer and `display_style: term::DisplayStyle::Short`.

I'd be happy to try my hand at a pull request if this is something that you think would provide value.

**Comment by alerque** [comment]
This sounds like a great idea to encourage 3rd party tooling like editor integration.

I suspect JSON would probably be a more broadly usable way to wrap the output in a machine readable format.

**Comment by erikwastaken** [comment]
Thanks! There are two reasons why I opted for the format `chap1.typ:15:10: error message`

1. it's a common short form for compiler messages; Cargo emits this format, as well, when you specify the option `--message-format short`. I believe it's how the original C compiler emitted errors.
2.  it's supported by `codespan-reporting` out of the box, which is the library that is used by Typst for diagnostics (unless I severely misread the source code)

JSON is an interesting suggestion, but it does seem like a much larger effort to implement and might be better served by piping the compiler output into a secondary tool.

**Comment by laurmaedje** [comment]
Feel free to make a PR with this!
