### ISSUE TITLE
Integration with other languages

### ISSUE THREAD

**Issue by VarLad** [typst/typst#117]
For the programming part, I wonder with I can use other programming languages with Typst directly. 
Is there a way to add support?

**Comment by owiecc** [comment]
This would ba amazing. You could share the code, evaluate it on the fly and display the resulting data and figures. This way there is no copy/paste/wrong version errors. Your document becomes a lab notebook. 

As an example. the [Algorithms for optimization book](https://algorithmsbook.com/optimization/) was entirely [written in Julia](https://www.youtube.com/watch?v=ofWy5kaZU3g).

**Comment by Moelf** [comment]
@owiecc , to be fair, that one eventually is "just" using TeX.

But I do think integration with other languages, especially Julia (I'm biased) for the computation block would be extremely useful, given many scientists looking at `typst` probably don't use Rust for their interactive daily science inquiry

**Comment by ParadaCarleton** [comment]
Agreed on the Julia front. Julia notation for mathematics is amazingly beautiful; the whole language is designed from the ground-up for this specific use case. Hell, I often find it more intuitive than the mathematical notation itself, to the point where I'll try and get away with replacing equations with code blocks in papers.

**Comment by ParadaCarleton** [comment]
You might be interested in talking to the people at Quarto, Jupyter, or Pluto.jl (who have experience integrating Julia into scientific notebooks).

**Comment by PhyX-Meow** [comment]
Also it will be great if we have tikz picture blocks. Although tikz is ugly and very hard to use, compare to other plotting libraries,
it has it's advantages that has no replacement, eg. fine output fitting scientific articles, math mode in label, arrows, commutative diagrams etc. So since we cannot write a replacement of tikz, make it possible to integrate tikz into typst would be great.

**Comment by jason-s** [comment]
see also #962

**Comment by Enivex** [comment]
> So since we cannot write a replacement of tikz

I see no reason why a replacement for tikz cannot be written in typst. There is already an attempt in the (very) early stages

https://github.com/johannes-wolf/typst-canvas

**Comment by fenjalien** [comment]
@VarLad Just to clarify: do you mean running code, from a different language, within a `.typ` file at compile time, or compiling a `.typ` file using a different programming language?

**Comment by ParadaCarleton** [comment]
If I can offer one suggestion—right now, my favorite thing about Typst is how interactive and responsive it is. I can write Typst code and immediately see the results while I edit, which is great for teaching students how to code in it or for collaborating with colleagues so they can see exactly what I’m doing as I type.

Currently, the only notebook that can do this (as far as I’m aware of) is [Pluto.jl](https://github.com/fonsp/Pluto.jl), which is also fully reactive— If I can offer one suggestion—right now, my favorite thing about Typst is how interactive and responsive it is. I can write Typst code and immediately see the results while I edit, which is great for teaching students how to code in it or for collaborating with colleagues so they can see exactly what I’m doing as I type.

Currently, the only other notebook I’m aware of that can do this is [Pluto.jl](https://github.com/fonsp/Pluto.jl), which is also fully reactive—changing a single block immediately updates all the blocks that depend on it, and *only* those blocks, giving you a promise of no-hidden-state. This lets you quickly edit an earlier part of your code, without having to rerun the whole thing from scratch just to check the output will still work.

Ideally, being able to embed Pluto blocks inside a Typst notebook would be like a dream come true for me 😄

**Comment by laurmaedje** [comment]
Closing this as WebAssembly plugins and `typst query` has been implemented. See https://github.com/typst/typst/issues/1056 for more details.
