### ISSUE TITLE
Incorrect capitalization of citation title with .bib file

### ISSUE THREAD

**Issue by CronJorian** [typst/typst#1172]
### Description

As can be seen in the picture, the title property of the `@book` entry in my .bib file is false.
The _A_ of "Duden Wirtschaft von A bis Z" is written lowercase whereas it should be in uppercase.

![image](https://github.com/typst/typst/assets/44020029/7632e950-77d0-4345-8466-fef6a430e900)

This applies for all 4 citation styles. I did only test this with a .bib file.
Using typst version `0.3.0`

This is the entry of my bibliography for reference:

```bib
@book{pollertDudenWirtschaftBis2016,
  title = {{Duden Wirtschaft von A bis Z: Grundlagenwissen f\"ur Schule und Studium, Beruf und Alltag}},
  shorttitle = {{Duden Wirtschaft von A bis Z}},
  author = {Pollert, Achim and Kirchner, Bernd and Pollert, Marc Constantin and Bauer, Michael},
  year = {2016},
  series = {{Duden}},
  edition = {6. Auflage},
  publisher = {{Dudenverlag}},
  address = {{Berlin}},
  abstract = {Die Vorauflage dieses soliden Nachschlagewerkes sollte ersetzt werden, da neue Begriffe wie IBAN, TTIP etc. aufgenommen wurden und statistische Daten aktualisiert sowie rechtliche \"Anderungen eingearbeitet wurden. Unterteilt in 12 Kapitel werden wichtige Begriffe aus der Wirtschaft in alphabetischer Reihenfolge gelistet und definiert. Ein direkter Zugriff auf die Erl\"auterungen ist \"uber das Stichwortverzeichnis im Anhang m\"oglich. In dem Buch kann man wunderbar bl\"attern und bleibt so beim einen oder anderen Artikel oder bei einer Grafik h\"angen. (2 A,S)},
  isbn = {978-3-411-70966-3},
  langid = {german},
  file = {}
}
```

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Should be fixed by https://github.com/typst/hayagriva/commit/8ccd1497d52249b1d595a9c3b321cc733bdfe51d. Hayagriva is also already updated, so you can try it with Typst's main branch.
