### ISSUE TITLE
`translate` element

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#1174]
### Description

I suggest adding a `translate` function that returns content based on the current language.

`translate` accepts a [dictionary](https://typst.app/docs/reference/types/dictionary/) whoes keys are language codes and values are [content](https://typst.app/docs/reference/types/content/) translated into the corresponding language. For example:
```typst
#translate((
  en: "Theorem",
  de: "Theorem",
  fr: "Théorème",
  es: "Teorema",
))
```
returns the content corresponding to the current language.

Alternatively, `translate` accepts a [function](https://typst.app/docs/reference/types/function/) that takes the current language and region as two strings and returns content:
```typst
#translate((lang, region) => {
  if lang == "en" and region == "us" [Internationalization]
  else if lang == "en" and region == "gb" [Internationalisation]
  else if lang == "de" [Internationalisierung]
  else if lang == "fr" [Internationalisation]
  else if lang == "es" [Internacionalización]
  else { panic("Unknown language") }
})
```

### Use Case

Such a feature would be useful when creating macro-like functions.

In the following example, taken from https://typst.app/docs/reference/meta/counter/, the word "Theorem" is untranslated if the function is used in a non-English context.
```typst
#let c = counter("theorem")
#let theorem(it) = block[
  #c.step()
  *Theorem #c.display():* #it
]
```

Although it is uncommon to use multiple languages within the same document, you may want to reuse certain functions in multiple documents, which are not all written in the same language. In this case, a `translate` function would be very appreciated.

**Comment by imbrem** [comment]
Prior art on this: https://projectfluent.org/

If we go this way, it makes sense to do it properly.

**Comment by laurmaedje** [comment]
Resolved by https://github.com/typst/typst/pull/3497.
