### ISSUE TITLE
Provide grammars and LSP

### ISSUE THREAD

**Issue by GoldsteinE** [typst/typst#118]
As far as I understand, there’s currently no support for editors other than typst.app. Some things that could improve this situation:
1. Providing a TextMate grammar, which is not very powerful, but supported by a wide range of editors and tooling.
2. Providing a TreeSitter grammar, which is supported primarily by Neovim and allows for advanced editor integration.
3. Providing a full-fledged LSP, which is supported by basically everyone and allows for all sorts of IDE-like features.

**Comment by SeniorMars** [comment]
I'm working on number 2.

**Comment by LaurenzV** [comment]
TextMate grammar can be found [here](https://github.com/typst/typst/tree/main/tools/support)

**Comment by KaranAhlawat** [comment]
>     2. Providing a TreeSitter grammar, which is supported primarily by Neovim and allows for advanced editor integration.

Also supported by Emacs, Helix, and a couple of other editors :)

**Comment by KiruyaMomochi** [comment]
Just found that typst.app compiles files locally. 

Does this mean we can have a VS Code extension that not only 
1. works in [VS Code for the Web](https://code.visualstudio.com/docs/editor/vscode-web), but also
2. compiles document **in almost real-time through WebAssembly**?

And if it's true, I finally can use <github.dev> to write my paper without downloading anything, and collaborate with others.

That is _fantastic_.

**Comment by reknih** [comment]
We've got an LSP at [nvarner/typst-lsp](https://github.com/nvarner/typst-lsp) and an (admittedly a bit outdated) TextMate grammar here. @SeniorMars can you share a link to your WIP Tree Sitter grammar? Once we collected that here, we'll close this issue, any further issues shall be filed on the respective projects.

**Comment by laurmaedje** [comment]
There's also @frozolotl's grammar here: https://github.com/frozolotl/tree-sitter-typst

**Comment by RubixDev** [comment]
@reknih, the tree-sitter grammar from @SeniorMars can be found here: https://github.com/SeniorMars/tree-sitter-typst

**Comment by laurmaedje** [comment]
As there are multiple grammars and a third-party LSP, I'm going to close this.

**Comment by GoldsteinE** [comment]
Are there plans on blessing some solutions as official-ish (while keeping them community-maintained)? Right now there’s a naming problem: for example, nixpkgs currently includes `typst-lsp`, which may be not ideal if another project with that name emerges. Blessing one `typst-lsp` and one `tree-sitter-typst` as official would resolve the issue “what to include by default” and “what gets priority while reserving names”.

**Comment by laurmaedje** [comment]
I think its a little early for that, but I can imagine that in the medium term. Also depends on what the maintainers of these projects want and plan.

**Comment by SeniorMars** [comment]
I agree. While my grammar right now has more stars - it is nowhere complete, I think we should wait until they become feature-proof.

**Comment by uben0** [comment]
I am writing a TreeSitter grammar that took me several months to come by, but it is not finished. Nonetheless, it seems more advanced than the two evoked earlier.

https://gitlab.com/uben0/tree-sitter-typst

**Comment by frozolotl** [comment]
> I am writing a TreeSitter grammar that took me several months to come by, yet, it is not finished.
> 
> Nonetheless, it seems more advanced than the two evoked earlier, as it parses correctly more tricky cases.
> 
> https://gitlab.com/uben0/tree-sitter-typst
It seems the repository is set to private.

> As mentioned in the README, two issues remain, and I need help resolving them. I am looking at you @SeniorMars 👀
> 
> Sincerely, it seems like the TreeSitter tool is not meant for that kind of language. It feels like this idea of having optional `;` to terminate an inline expression is terrible design. Having it mandatory would solve everything.
> 
> Difficult cases:
> 
> ```
> #a._ b _
> ```
Here I'm not sure what the issue would be iih.

> ```
> #if a {} elseeee {}
> ```
This one should be solved by providing `word`: https://github.com/frozolotl/tree-sitter-typst/blob/master/grammar.js#L29

> ```
> #{
>    2
>    + 2
> }
> ```
In my grammar, I haven't implemented binary operators yet, but I believe this should just be a case of only allowing trivia that isn't a newline. For instance, [here](https://github.com/frozolotl/tree-sitter-typst/blob/master/grammar.js#L648-L656) I differ between trivia that allow newlines and those that do not.

**Comment by uben0** [comment]
@frozolotl Thanks for the feedback! I'll test the possible fixes and keep this response updated.

By the way, `#a._ b _` is valid code (it compiles without error) and should have the following tree:
```scm
(source_file
    (ident)
    (text)
    (emphasis
        (text)))
```

**Comment by uben0** [comment]
@frozolotl Can I use parts of your code in the grammar I am writing ? I'm thinking about the regex for XID_Continue without `_`. If yes, do you have conditions?

**Comment by frozolotl** [comment]
> @frozolotl Can I use parts of your code in the grammar I am writing ? I'm thinking about the regex for XID_Continue without `_`. If yes, do you have conditions?

You are allowed to use all the code in [frozolotl/tree-sitter-typst](https://github.com/frozolotl/tree-sitter-typst) under the condition given in the [LICENSE](https://github.com/frozolotl/tree-sitter-typst/blob/master/LICENSE).
The license shouldn't be difficult to read and GitHub does provide a summary at the top, though that one is not legally binding.

I would prefer that we kept this conversation and other ones not related to this issue somewhere else, though. So, if you want to discuss [my tree-sitter grammar](https://github.com/frozolotl/tree-sitter-typst), you should do that there. Alternatively, you can contact me on via [email](mailto:frozolotl@protonmail.com), via [matrix](https://matrix.to/#/@frozolotl:matrix.org), or on discord (`@frozolotl`, or [the typst discord](https://discord.gg/2uDybryKPe)).
