### ISSUE TITLE
Custom alignment in block equations 

### ISSUE THREAD

**Issue by dvdvgt** [typst/typst#1187]
### Description

There are cases where the default left alignment (?) in block equations does not fit the requirements. It would be nice to be able to specify a custom alignment, similar to how it is possible with the `table` function (<https://typst.app/docs/reference/layout/table/#parameters--align>). This could be done by adding a new parameter to block equations such that a function can be passed as argument, which in turn is passed the column number and returns an [alignment](https://typst.app/docs/reference/layout/align/#parameters--alignment):

```
equation(block: true, align: x => (left, left, right).at(x))[
  ...
]
```

Of course, I am happy to hear and discuss alternative solutions for this from you!

### Use Case

Take this minimal example

```
#let eq = $<=>& #h(4em)$

$
eq A + B &= C + D \
eq C + D + F &= Y + K
$
```

which looks like this:

![image](https://github.com/typst/typst/assets/40773635/d491c245-ae5d-4c0c-8df3-d4511c8d4747)

Notice that the alignment in the second column (left of the equality) is left aligned, which does not look like one would expect – it should be right aligned.

**Comment by laurmaedje** [comment]
Since #936, the alignment alternates between left and right, so that your example becomes this:
```
$
<=> & #h(4em) & A + B     &= C + D \
<=> & #h(4em) & C + D + F &= Y + K
$
```
Note that there hasn't been a release since this was merged.
