### ISSUE TITLE
Another smart quotes bug when touching other characters

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#1200]
### Description

```
"0" "abc" '0' 'abc' \
"0"s "abc"s '0's 'abc's \
s"0" s"abc" s'0' s'abc' \
s"0"s s"abc"s s'0's s'abc's \
```

![image](https://github.com/typst/typst/assets/9490724/aec181b5-9519-49b9-86e7-cc2d5fd4732d)

**Comment by Enivex** [comment]
I'd argue that some of these would never appear naturally in text, and therefore aren't bugs per se. Smart quotes will always have edge cases like this because it's fundamentally ambiguous what the user means.

**Comment by SUPERCILEX** [comment]
The case I care about is appending an `s` to the quotes to pluralize them.

~~But what do you mean? Why can't smart quotes work as a very simple stack machine:~~
- ~~If the current value on the stack doesn't match my quote type, push my quote type as an opening on the stack.~~
- ~~If the current value on the stack matches, pop the stack and use a closing quote.~~

Nevermind, forgot that `'` can appear solo which breaks stack algorithms. That's a bummer.

Not sure what that means for this issue then, but it does feel like the current behavior is a little wonky.

**Comment by MDLC01** [comment]
A similar problem occurs when an apostrophe is followed immediately by quotes, which is somewhat common in french:
```typst
#set text(lang: "fr")
Une "histoire" \
L'"histoire"

// Of course, we have the same problem if the language is set to english.
#set text(lang: "en")
Une "histoire" \
L'"histoire"
```
![Une « histoire » // L’"histoire // Une “histoire” // L’"histoire"](https://github.com/typst/typst/assets/57839069/b9677ee2-c41d-4bca-8fd6-7cd74fac0331)

**Comment by laurmaedje** [comment]
Similar to https://github.com/typst/typst/issues/1343, I'm unsure if we can do anything about this without introducing any ad-hoc special cases.

**Comment by laurmaedje** [comment]
I've opened https://github.com/typst/typst/pull/3422 to make the `#quote` function smarter (closing https://github.com/typst/typst/issues/3260) so that ambigious cases can be expressed with it instead of smartquotes. 

Since it's very unclear how smartquotes could be made smarter in a sane way, I'm going to close this issue as non-actionable. If someone knows of a suitable algorithm, feel free to chime in.

**Comment by hurzl** [comment]
Excepting punctuation like the slash from breaking smartquotes would be insane?

**Comment by laurmaedje** [comment]
> Excepting punctuation like the slash from breaking smartquotes would be insane?

Such a comment is not constructive. If you believe the algorithm can be improved, please do make your point, but then it would helpful to explain what exact change you propose and why it doesn't have any unintended consequences.

**Comment by hurzl** [comment]
I propose to not breaking smartquotes when preceded by a slash. And/or other punctuation.

**Comment by laurmaedje** [comment]
https://github.com/typst/typst/pull/4849

**Comment by thjbdvlt** [comment]
> A similar problem occurs when an apostrophe is followed immediately by quotes, which is somewhat common in french:
> 
> ```typst
> #set text(lang: "fr")
> Une "histoire" \
> L'"histoire"
> 
> // Of course, we have the same problem if the language is set to english.
> #set text(lang: "en")
> Une "histoire" \
> L'"histoire"
> ```
> 
> ![Une « histoire » // L’"histoire // Une “histoire” // L’"histoire"](https://private-user-images.githubusercontent.com/57839069/271991792-b9677ee2-c41d-4bca-8fd6-7cd74fac0331.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjQzODksIm5iZiI6MTcyODIyNDA4OSwicGF0aCI6Ii81NzgzOTA2OS8yNzE5OTE3OTItYjk2NzdlZTItYzQxZC00YmNhLThmZDYtN2NkNzRmYWMwMzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE0MTQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NGM4NGFiNjIwODEzNDc2ZGQxZmYwMTBhM2E5Y2FmMWIyM2QzYjZkNjNjNWUwYmJhMWZhZWRmOGE0MDU1ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Fwoheb1ztgTtEeeelZYw5tRRd2Pyfk-ONMAhLrrdivI)

@MDLC01 
Have you found a work around for this? I'm facing this issue and don't know what to do. This case is VERY frequent in my texts and makes typst unusable for french academic text, in my opinion.

**Comment by MDLC01** [comment]
You can use the [`quote`](https://typst.app/docs/reference/model/quote/) function.
In general, the handling of smart quotes will be improved with 0.12 (to be released soon). In particular, `L'"histoire"` will be rendered properly.

**Comment by thjbdvlt** [comment]
Thank you! That's great :)
