### ISSUE TITLE
math.op spacing with bar

### ISSUE THREAD

**Issue by StrangeGirlMurph** [typst/typst#1202]
### Description

`P_n = {f in K[Y] bar deg(f) <= n}` renders as
![image](https://github.com/typst/typst/assets/62220780/7c483315-0123-4e85-94ef-11c811a87905)
but should instead be
![image](https://github.com/typst/typst/assets/62220780/7f12b558-fe04-4278-a2ed-b862ceb24c9f)
like it is automatically with numbers for example
![image](https://github.com/typst/typst/assets/62220780/69f8777e-1826-4418-a9e4-990ad60c8d9b)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
This is not a bug. You're using the delimiter, but the symbol you want is actually \u{2223} (divides)

`$P_n = {f in K[Y] divides deg(f) <= n}$`

yields

![image](https://github.com/typst/typst/assets/2191754/ec1c94b6-8dae-4c9a-b4cb-592283d42cd4)

**Comment by StrangeGirlMurph** [comment]
Hmm okay thank you. A bit confusing that it still works with numbers just like on would expect though.
