### ISSUE TITLE
Zombie sessions

### ISSUE THREAD

**Issue by binarynoise** [typst/typst#1205]
### Description

Sometimes the web app becomes unresponsive or the compiler keeps crashing or some other weird behaviour happens and I need to reload the page.
After that I always get zombie sessions: the app thinks I am editing the file 3 times, but I only have one tab open.
How do I get rid of them?

![grafik](https://github.com/typst/typst/assets/50302352/63ad8514-bedd-4ebf-b98f-2aa2a5bcefab)

### Browsers

Firefox

### OS

Windows, Linux

Btw.: where is the source for the web-app?

**Comment by PgBiel** [comment]
> Btw.: where is the source for the web-app?

It is closed-source.

**Comment by laurmaedje** [comment]
Fixed.
