### ISSUE TITLE
Non Block Raw crosses table line

### ISSUE THREAD

**Issue by JL710** [typst/typst#1223]
### Description

This appeared today. When using raw in a table, words won't be splitted even if they will cross lines. I guess this is a Bug? 

(Sorry if this is a duplicate, I did not find an issue that contained this error)

```
#table(columns: 2, 
  [`isidfiasdasdasdasdadsasdasdasdadasasddasdasdas`], 
  [#lorem(9)]
)
```

![Screenshot 2023-05-16 184817](https://github.com/typst/typst/assets/76447362/a3def6a5-f561-4ede-9eb4-07736fc2b4f5)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
It happens without `table` as well, see https://github.com/typst/typst/issues/862
