### ISSUE TITLE
Incorrect let binding crashes compiler

### ISSUE THREAD

**Issue by Rob2309** [typst/typst#1232]
### Description

```typst
#let 5 = 6
```

When calling `typst::ide::tooltip()` on the `let` of the above statement, the compiler will crash with
`thread 'main' panicked at 'internal error: entered unreachable code', [...]\src\eval\mod.rs:1402:18`.

I hope I did not miss any open issues for this bug.

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
See also #1213
