### ISSUE TITLE
Template storage

### ISSUE THREAD

**Issue by S201900** [typst/typst#1233]
### Description

I don't think there's any feature allowing the storage of a custom template in the template gallery of the typst web app for later use. This could come handy !

### Use Case

With the inclusion of this feature, users would have the convenient ability to store their personalized templates in the existing gallery. This functionality empowers them to access and utilize their custom templates whenever desired, ensuring an efficient usage.

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/typst/issues/1803, as that would be the way to enable custom templates in the web app.
