### ISSUE TITLE
Wrong block spacing comparison with different font sizes when specified in em

### ISSUE THREAD

**Issue by AzazKamaz** [typst/typst#1238]
### Description

When font sizes are different and blocks have spacing specified in `em` it compares just spacing value without taking into account font size.

```
#grid(
  columns: (1fr, 1fr),
  {
    text(size: 40pt, block(below: 1em, "BIG"))
    text(size: 20pt, block(above: 1em, "SMALL"))
  },
  {
    text(size: 40pt, block(below: 1em, "BIG"))
    text(size: 20pt, block(above: 1.1em, "SMALL"))
  }
)
```

<img width="450" alt="Screenshot 2023-05-17 at 17 59 33" src="https://github.com/typst/typst/assets/12931951/9bc432ed-de71-4c5f-9ad8-6185f6e9ea06">

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
I'm guessing this might be the culprit behind some other layout issues as well?
