### ISSUE TITLE
embedded SVG text should be selectable. 

### ISSUE THREAD

**Issue by taylorh140** [typst/typst#1239]
### Description

I notice that when an svg is embedded. It is a vector graphic but all the text that was in the original is no longer selectable. (e.g. I cannot copy text from it). This inserts a clear distinction between typst raw output vs typst -> svg -> typst output. but mostly its a little inconvenient.

### Use Case

For functional documents copy and paste reduces translation errors. This is part of the reason that embedding a svg/pdf is preferable to raster formats. Allowing text to be selectable from embedded vector graphics would make the svg embedding more useful.

**Comment by hcsch** [comment]
I agree that selectable text in embedded vector images would be nice, but if that is added it would be great to make that an opt-in/opt-out feature. Selectable text in a diagram with paragraphs wrapped around it would for example mess up the paragraph's text when trying to copy just that, so making some graphics like diagrams have non-selectable text, and other graphics like external tables have selectable text would be desirable, I think.

**Comment by mhdadk** [comment]
Is there any update on this? This would be a really useful feature to have.

**Comment by LaurenzV** [comment]
Unfortunately not, I've been wanting to work on this but it does take some effort and I haven't had the time. :/

**Comment by mhdadk** [comment]
> Unfortunately not, I've been wanting to work on this but it does take some effort and I haven't had the time. :/

No problem at all. Typst is already incredible as it is, and I'm very grateful for your work so far. This is more of a "nice-to-have" at the moment for me.

**Comment by LaurenzV** [comment]
Happy to say that that text preservation has been implemented upstream, so the odds are good that we can have this in Typst as well by the next release.

**Comment by taylorh140** [comment]
Just checked if this has changed in 0.11.1? 
 - It doesn't seem to have. typst 0.11.1 (50115102)
Keep open.

**Comment by laurmaedje** [comment]
Yeah, 0.11.1 was just a patch release. This will be part of the next proper release, 0.12.

**Comment by UtsavDayal** [comment]
During the latest release, this has eradicated the only simple way of producing unselectable text.  @hcsch is right. There are instances where this functionality needs to be toggled off. Is there a plan to make it configurable? This will also address: https://github.com/typst/typst/issues/2249

**Comment by LaurenzV** [comment]
I opened a PR: https://github.com/typst/typst/pull/5390
