### ISSUE TITLE
Process exits successfully when building a non existing file

### ISSUE THREAD

**Issue by SamK** [typst/typst#1241]
### Description

When trying to compile a file that does not exist, the typst command exits with a return code of `0`. It should not.

### Environment:

```
# docker run ghcr.io/typst/typst:v0.3.0 typst --version
typst 0.3.0 (unknown hash)
# docker --version
Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.2
# uname -a
Linux system76-pc 6.2.6-76060206-generic #202303130630~1679424972~22.04~4a8cde1~dev-Ubuntu SMP PREEMPT_DY x86_64 x86_64 x86_64 GNU/Linux
# lsb_release -d
Description:    Ubuntu 22.04.2 LTS
```

As of now, the issue also occurs with `ghcr.io/typst/typst:latest`.

### How to reproduce the issue

```
# docker run ghcr.io/typst/typst:v0.3.0 typst compile not-here.typ
error: file not found (searched at not-here.typ).
# echo $?
```

### Expected result
The exit code should not be 0.
A reasonable value would be `2` (meaning `ENOENT`, meaning the famous "no such file or directory").

### Actual result
The exit code is `0`

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
I fixed the exit code, but didn't use `2` because it seemed [to mean something else](https://tldp.org/LDP/abs/html/exitcodes.html). I checked what `gcc` does in this case and it yields just `1`, so I picked that.
