### ISSUE TITLE
Cannot place alignment points inside limits

### ISSUE THREAD

**Issue by Triton171** [typst/typst#1244]
### Description

It's quite common to reference theorems / assumptions that are used above (in)equalities. Currently, this does not seem to be possible without breaking the alignment. When the alignment point is inside the `limits` function, it seems to be ignored (but without raising an error):
````
$
integral_a^b integral_c^d f(x,y) dif x dif y
limits(&=)^"Fubini" integral_([a,b] times [c,d]) f(x,y) dif cal(L)^2(x,y) \
&= dots
$
````
![image](https://github.com/typst/typst/assets/16193831/85054ae0-3969-4d52-9089-52f2aabe79ce)

Placing the alignment point outside the `limits` function works but this aligns the superscript instead of the equal sign (because the superscript is wider):
````
$
integral_a^b integral_c^d f(x,y) dif x dif y
&limits(=)^"Fubini" integral_([a,b] times [c,d]) f(x,y) dif cal(L)^2(x,y) \
&= dots
$
````
![image](https://github.com/typst/typst/assets/16193831/b608b696-8e4b-4432-9b8a-0616c799e3a7)

I think the behavior in the second version is reasonable but the first version should correctly align the equal sign (or throw an error if this isn't possible / desirable for some reason). If you'd accept a PR, I can try to find a fix for this (any advice on how to approach it would also be helpful in that case).

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
From memory, I believe this is consistent with the behavior in LaTeX. I think allowing alignment inside function calls is a can of worms.

There are a few ways to work around this. One is to make the text take up no space in the layout, and then add horizontal space around the equal sign manually.

**Comment by Enivex** [comment]
```$
integral_a^b integral_c^d f(x,y) dif x dif y quad  &limits(=)^(#box(width:0pt)[Fubini]) quad integral_([a,b] times [c,d]) f(x,y) dif cal(L)^2(x,y) \
&= dots
$
```

![rendered.png](https://github.com/typst/typst/assets/2191754/9c0204c9-b899-4584-b342-b8f7458c8433)

**Comment by Triton171** [comment]
You're right, the behavior is the same in LaTex. I didn't know that `#box(width: 0pt, ...)` can be used to work around this issue similarly to how `\mathclap{...}` works in LaTex, that's a neat trick. I played around with it a bit and it's actually pretty straightforward to automatically add the spacing around the equal sign:
````
#let alignbase(body, superscript) = style(styles => {
  let totalwidth = measure($limits(body)^superscript$, styles).width
  let bodywidth = measure(body, styles).width
  let overlapwidth = (totalwidth - bodywidth) / 2 + 2pt
  let superscriptwidth = measure(superscript, styles).width
  $#h(overlapwidth, weak: true)
  // The nested box ensures that the superscript is not broken into multiple lines
  &limits(body)^(#box(width:0pt, align(center, box(width: superscriptwidth, superscript))))
  #h(overlapwidth, weak: true)$
})

$
integral_a^b integral_c^d f(x,y) dif x dif y
alignbase(=, "Fubini") integral_([a,b] times [c,d]) f(x,y) dif cal(L)^2(x,y) \
&= dots
$
````
![image](https://github.com/typst/typst/assets/16193831/1f347ab6-bef6-4e8c-ace3-3d0f41d8a3eb)

Thanks a lot for the help, I'll close this issue.

**Comment by tedzards509** [comment]
> ```
> #let alignbase(body, superscript) = style(styles => {
>   let totalwidth = measure($limits(body)^superscript$, styles).width
>   let bodywidth = measure(body, styles).width
>   let overlapwidth = (totalwidth - bodywidth) / 2 + 2pt
>   let superscriptwidth = measure(superscript, styles).width
>   $#h(overlapwidth, weak: true)
>   // The nested box ensures that the superscript is not broken into multiple lines
>   &limits(body)^(#box(width:0pt, align(center, box(width: superscriptwidth, superscript))))
>   #h(overlapwidth, weak: true)$
> })

`style` appears to be deprecated by `context` as of 0.13. This should work in 0.13:
```typ
#let alignbase(body, superscript) = (context {
  let totalwidth = measure($limits(body)^superscript$).width
  let bodywidth = measure(body).width
  let overlapwidth = (totalwidth - bodywidth) / 2 + 2pt
  let superscriptwidth = measure(superscript).width
  $#h(overlapwidth, weak: true)
  // The nested box ensures that the superscript is not broken into multiple lines
  &limits(body)^(#box(width:0pt, align(center, box(width: superscriptwidth, superscript))))
  #h(overlapwidth, weak: true)$
})
```
