### ISSUE TITLE
Autocomplete / Suggestion list in #cite() like for @

### ISSUE THREAD

**Issue by boyen-cell** [typst/typst#1245]
### Description

It'd be quite if #cite() would also have the autocomplete/suggestion list that @ has, such that one doesn't have to either type the citation key by hand or copy-paste it in there (or – how I currently do it – write @, use the suggestion list, then highlight the cite-key and @-symbol, CTRL+SHIFT+W to launch a autohotkey script that writes #cite(brackets: false, "{CITEKEY}") ).

### Use Case

Makes regular use of #cite() much easier and doesn't require user to know or copy-paste cite-keys all the time.

**Comment by reknih** [comment]
Shipped in Typst 0.9.0.
