### ISSUE TITLE
Link: how to open new tab and then jump to the target link

### ISSUE THREAD

**Issue by zeyuanyin** [typst/typst#1247]
### Description

The current `link` can only jump to the link at the current tab, how to automatically open new tab and then jump to the target link.

This is similar to the function `target="_blank"` in HTML

`<a href="https://www.google.com/" target="_blank">Visit Google Website</a>` 

### Use Case

For example, if there are a lot of links in someone's resume, people who click the link do not want to shut down the resume page.

**Comment by Enivex** [comment]
Middle click typically opens links in a new tab.

**Comment by laurmaedje** [comment]
No idea if PDF even supports that.

**Comment by reknih** [comment]
Is this about the final PDF or the preview panel in the web app?

**Comment by zeyuanyin** [comment]
@reknih This is about the final PDF if I open it in the web app.  It seems the issue of the pdf itself.
