### ISSUE TITLE
Multiple errors are not traced correctly

### ISSUE THREAD

**Issue by jonathan-hellwig** [typst/typst#125]
When combining multiple errors, the CLI tool outputs incorrect error messages.
## Minimal example
test.typ:
```
$
#set
```
### Command:
`typst --watch test.typ`

### Actual Output:
```
watching test.typ
writing to test.pdf

[10:40:51] compiled with errors

error: expected identifier
  ┌─ test.typ:2:4
  │
2 │ #set
  │     ^

error: expected dollar sign
  ┌─ test.typ:2:4
  │
2 │ #set
  │     ^

```
### Expected Output
```
watching test.typ
writing to test.pdf

[10:40:51] compiled with errors
error: expected dollar sign
  ┌─ test.typ:1:1
  │
1 │ $
  │  ^
error: expected identifier
  ┌─ test.typ:2:4
  │
2 │ #set
  │     ^

```

**Comment by laurmaedje** [comment]
It parses the `#set` as part of the equation, so the errors in themselves are correct although not necessarily as clear as they could be. It would probably be clearer with #572, closing in favor of that.
