### ISSUE TITLE
Text Stretch does not work

### ISSUE THREAD

**Issue by ludwig-austermann** [typst/typst#1250]
### Description

The code
```typst
Hello\
#text(stretch: 10%)[Hello]\
#text(stretch: 500%)[Hello]
```
produces the same output:
- svg: ![SVG](https://github.com/typst/typst/assets/12214171/9944906e-c2fd-4388-b57d-8ced6faa7f42)
- pdf: ![PDF](https://github.com/typst/typst/assets/12214171/8b3eebef-3f23-436e-96e1-4e3c921679d3)

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
1. It only accepts numbers between 50% and 200%
2. You need to use a font family that actually has different font widths (a condensed version for instance)

**Comment by ludwig-austermann** [comment]
Ok thanks, I see.
I actually confused stretch with the tracking argument, maybe we could add a remark to spacing argument documentation on how this is called.

**Comment by PgBiel** [comment]
I'm guessing that adding a warning (when warnings are implemented) would be useful here (as this clearly seems a bit confusing the way it is)

**Comment by Enivex** [comment]
> I'm guessing that adding a warning (when warnings are implemented) would be useful here when specifying things out of the 50%-200% range (as this clearly seems a bit confusing the way it is)

I'm fairly sure it'll clamp the input to that range, but a warning would probably be warranted.
