### ISSUE TITLE
Example for overhang property of text doesn't actually illustrate what it claims to

### ISSUE THREAD

**Issue by Enivex** [typst/typst#1252]
![image](https://github.com/typst/typst/assets/2191754/9e7b46f7-4d4e-4090-9d49-af8974363e60)

There is no hyphen in the first paragraph. I can reproduce the (probably) intended behavior by adding `#set page(width: 200pt)` at he top

![image](https://github.com/typst/typst/assets/2191754/71c83c34-5ba4-4436-bdcf-5e577dfefa39)

**Comment by laurmaedje** [comment]
Once again, due to the default font switch probably. Missed a few things :(
