### ISSUE TITLE
Insertion order for dictionary is not maintained on removal

### ISSUE THREAD

**Issue by edhebi** [typst/typst#1258]
### Description

The documentation on dictionaries states that iteration (`for` loops, `keys`, `pairs`, ...) happens in insertion order. This is true except for the remove method, which **does not** maintain insertion order.

Having looked at the sources a bit, this is a matter of using `IndexMap::swap_remove` (aka `IndexMap::remove`) vs `IndexMap::shift_remove`). As the names suggest, `swap_remove` doesn't maintain order but is a single swap in $O(1)$ whereas `shift_remove` has to shift down the element to maintain order, resulting in $O(N)$.

I'm honestly not sure if the perf difference is measurable considering the average side of dictionaries in typst, but I'm also not sure we care that much about insertion order. In any case this is either a language bug or a documentation bug, and might be worth discussing.

### Reproduction URL

https://typst.app/project/rvDH4aDLb81YXrUPakmTr-

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
It's worth noting that the order is predictable even after removal. The removed element is swapped with the last element in the dictionary.

**Comment by PgBiel** [comment]
Imo both options of removal should be made available somehow (one might or might not care about the dictionary's order, and this can make a difference in hot code). Not sure which one the default should be, though (perhaps the one that preserves the order, as its behavior would be more predictable).

**Comment by laurmaedje** [comment]
That's unfortunate. I had kinda hoped that IndexMap would just handle that without O(n) slowdown. I'm wondering what Python does, since it also guarantees order.

**Comment by edhebi** [comment]
[This SO answer](https://stackoverflow.com/questions/39980323/are-dictionaries-ordered-in-python-3-6) has some details.

It looks like it's mostly the same as `IndexMap` but allowing empty slots up to some threshold. The actual resize when it does happen would  be amortized $O(1)$ the same way `Vec::push` is amortized $O(1)$
