### ISSUE TITLE
Add calc.exp and calc.ln

### ISSUE THREAD

**Issue by Enivex** [typst/typst#1260]
### Description

See title.

Alternatively, the default bases of pow and log could become calc.e (but I'm sure someone would disagree with this)

### Use Case

Because the current syntax of calc.pow(calc.e,x) and calc.log(x,base: calc.e) is needlessly complicated for functions that are used as often as this.

**Comment by Mafii** [comment]
I think this has been implemented in #1299 and released as part of v0.5.0, right? So this issue could be closed :)
