### ISSUE TITLE
code block in figure should not be centered

### ISSUE THREAD

**Issue by slashformotion** [typst/typst#1269]
### Description

```
#figure(caption: "but... why ?",
  raw("print('hi mom')
print('hello world')")
)
```

render as 
![image](https://github.com/typst/typst/assets/45801817/d44fafd2-ce83-4d4f-bb1e-1a511d2ba70e)

when it should render as

![image](https://github.com/typst/typst/assets/45801817/49f04272-af84-471b-882b-462ef93e433f)

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Fixed with #1034 (a new release will come out shortly with this fix!).

**Comment by slashformotion** [comment]
looks its gonna be soon https://github.com/typst/typst/commit/f692a5efc62bf95f57d123895b7dce55d2eb9741

**Comment by epbuennig** [comment]
A regression has reintroduced this issue on the web app (`v0.4.0`).
