### ISSUE TITLE
Markdown cross compilation

### ISSUE THREAD

**Issue by d4ckard** [typst/typst#127]
Are there any plans to build a tool to cross-compile markdown documents into `.typ` files?

This would be enormously helpful to transition from a markdown based note-taking workflow to typst.

Ignoring inline HTML, it seems to me that most markdown specifications offer only a subset of typst's features.
This assumption has the side effect of making it impossible to express all of typst's features in plain markdown, making
cross compilation from typst to markdown more complex.

**Comment by C284974** [comment]
This might be a job for [pandoc](https://pandoc.org/), which could integrate typst into its long list of serialization/deserialization markup languages.  

Although, there might be some merit in having a built-in tool.  Although, there is some large differences in different implementations of markdown, despite how simple it is.  You can see a list of many markdown implementations on the front page of pandoc's site, for instance.

**Comment by jgm** [comment]
Pandoc 3.1.2 (released today) can convert from markdown to typst.

**Comment by dei-layborer** [comment]
This is fantastic news.  Is there any documentation for what features are supported?  For example, would it be possible to use Typst-specific features (especially the more "coding"-like ones) in a file with Markdown text formatting and have pandoc convert everything properly?

**Comment by jgm** [comment]
Well, you can insert typst code in "raw blocks":
````
# My markdown document

```{=typst}
#let foob(x) = { x + x }
#foob
```

*more markdown here*

````

**Comment by jgm** [comment]
Also raw inline:

```
this is `raw #(2 + 3) typst`{=typst}
```
