### ISSUE TITLE
Link line wrapping behaves differently in v0.4.0

### ISSUE THREAD

**Issue by MikeRomaa** [typst/typst#1271]
### Description

Seems as though the link line wrapping no longer respects the block width in release 0.4.0. In previous versions it would break the links with dashes, but it doesn't do that anymore.
```
#columns(
    2,
    gutter: 0.4in,
    text(size: 10pt)[
        #bibliography("paper.bib", style: "chicago-author-date", title: none)
    ],
)
```

![image](https://github.com/typst/typst/assets/19419678/09b5ea0d-88cb-45e2-b565-bcc588ae3b65)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
As a workaround you can do
`#let mylink(url) = link(url,url.replace("/", "/" + str(sym.zws)).replace("-", "-"+ str(sym.zws)).replace(".", "."+ str(sym.zws)).replace("?", "?"+ str(sym.zws)))`
(feel free to add even more symbols)
and then rather write `#mylink("url goes here")` instead of just the url.

**Comment by laurmaedje** [comment]
The URL is probably generated by the bibliography function, but a regex show rule could probably achieve the same thing.

**Comment by WouterBesse** [comment]
A solution I came to with the help of Enivex, Léo and PgSuper on Discord seems to work for me. It might be a bit ugly, but for a quick fix in the meanwhile, it works!

```
#let breaklink(url) = link(url, for c in url [#c.replace(c,c+sym.zws)])

#show regex("https://[^\s]+"): url => {
  breaklink(url.text)
}

#show regex("http://[^\s]+"): url => {
  breaklink(url.text)
}

#bibliography("bib.bib")
```

It works by adding a zero-width space to the end of every letter it displays in the URL, whilst keeping the actual URL destination unchanged.

**Comment by reknih** [comment]
Typst 0.9.0 now ships with a dedicated URL linebreak algorithm that should produce nice breaks and fix these overflows.
