### ISSUE TITLE
Incorrect baseline for union.big and sect.big (and possibly others?) in some fonts

### ISSUE THREAD

**Issue by Enivex** [typst/typst#1272]
### Description

```
#show math.equation : set text(font: "Stix Two Math", fallback: false)
$
|K| = union.big_(p=0)^oo K_p times Delta^p \u{29f8} tilde
$

$
|K| = sect.big_(p=0)^oo K_p times Delta^p \u{29f8} tilde
$
```
yields

![image](https://github.com/typst/typst/assets/2191754/ddf845e9-2215-40e2-a088-0635fae4c8af)

The same (system) font in latex (lualatex + unicode-math) has correct baseline

![image](https://github.com/typst/typst/assets/2191754/8728ee66-700f-42d2-add5-6fbaf16ee9ae)

Other fonts, like New Computer Modern, displays correctly in typst

```
#show math.equation : set text(font: "New Computer Modern Math", fallback: false)

$
|K| = union.big_(p=0)^oo K_p times Delta^p \u{29f8} tilde
$

$
|K| = sect.big_(p=0)^oo K_p times Delta^p \u{29f8} tilde
$
```

![image](https://github.com/typst/typst/assets/2191754/1a4fc02e-1acf-4d8a-b2af-7cf94bdeca80)

### Typst version

- [X] I am using the latest version of Typst

**Comment by damaxwell** [comment]
This was addressed in #1735 and should be closed.
