### ISSUE TITLE
Pagination issue with footnotes

### ISSUE THREAD

**Issue by tianze0926** [typst/typst#1275]
### Description

Pagination can get wrong as the number of footnotes increases. And it seems to be related to lists.

#### Example 1

https://typst.app/project/rvacXiEHBYRbLdhixlBK9l

| Page 1 | Page 2 | Page 3 |
|-|-|-|
|![image](https://github.com/typst/typst/assets/66857124/a07d1f58-7b2a-410a-aff3-da02f3d64c25)|![image](https://github.com/typst/typst/assets/66857124/6b1a1b5d-0888-4b4a-ac5c-506fbeb60cca)|![image](https://github.com/typst/typst/assets/66857124/6bebc1b6-678a-4af4-9974-2043c597a4b3)|

#### Example 2

https://typst.app/project/rbNHbg2L_EyxcFYUc5bSKZ

| Page 1 | Page 2 |
|-|-|
|![image](https://github.com/typst/typst/assets/66857124/1ca24e14-f235-4360-b2d8-9a5ba1e0ac68)|![image](https://github.com/typst/typst/assets/66857124/86238175-4995-4f29-a6ae-7a239551406f)|

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Seems to only happen for footnotes in lists (and possibly other blocks). The interaction between non-paragraph blocks and footnotes is still a bit janky.

**Comment by tianze0926** [comment]
I just updated a second example where footnotes in page 1 (10, 11, 12) showed up in page 2.

**Comment by cyp0633** [comment]
I also encountered the problem. It seems that the problem may occur even if there's no list in the article. Please see the bottom of the page 2.

[Example link](https://typst.app/project/rh8mEGSrpSu3hQ75RHEHBM)

<img width="391" alt="Page 2" src="https://github.com/typst/typst/assets/16500188/ec304d68-2b42-478f-8e0b-e3e3b4798d7d">

<img width="530" alt="Page 1" src="https://github.com/typst/typst/assets/16500188/93c3f7c4-1b79-44ea-a94d-9f8b27f8c265">

**Comment by p4perf4ce** [comment]
I also found the same issue while trying to replicate `IEEEtran.cls`'s `\thanks` command. The example can be found in this [link](https://typst.app/project/r2wOu8WTWd2fE_flGAWnBR).

```
#footnote(numbering: it => "")[
#grid(columns: (1fr, 1fr))[
#par(justify: true, first-line-indent: 1em)[
_This paragraph of the first footnote will contain the date on which you
submitted your paper for review. It will also contain support information,
including sponsor and financial support acknowledgment. For example,
“This work was supported in part by the U.S. Department of Commerce
under Grant 123456.”_

_The next few paragraphs should contain the authors’ current affiliations, including current address and e-mail. For example, First A. Author is with the National Institute of Standards and Technology, Boulder, CO
80305 USA (e-mail: author\@boulder.nist.gov)._

_Second B. Author Jr. was with Rice University, Houston, TX 77005
USA. He is now with the Department of Physics, Colorado State University, Fort Collins, CO 80523 USA (e-mail: author\@lamar.colostate.edu).
Third C. Author is with the Electrical Engineering Department, University of Colorado, Boulder, CO 80309 USA, on leave from the
National Research Institute for Metals, Tsukuba, Japan (e-mail: author\@nrim.go.jp)_
]
]
]
```

**Comment by KronosTheLate** [comment]
I am using footnotes both in tables, in lists, and just in text. A single one seemes fine, but it does not take long before I get empty pages containing only a footnote, meaning that the footnote is on another page than the reference to it.

**Comment by laurmaedje** [comment]
I fixed a bunch of bugs related to footnote positioning. That should prevent empty pages as shown in your examples. 

That being said, footnotes can still not affect the layout of the blocks they are contained in. As a result, the invariant "footnote marker and entry are always on the same page" isn't always upheld (in particular, not when the block that contains the footnote is long and breaks across pages). Instead the footnote(s) will pile up on the page after. This is currently hard to fix, but I intend to improve it in the medium term. 

As the concrete issues discussed here a fixed, I'm gonna close this bug. We can open a new one for the somewhat lacking upholding of the marker-entry invariant.

**Comment by KronosTheLate** [comment]
Nice. Thanks for your work
