### ISSUE TITLE
Uploaded non-binary files are empty until refresh

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#1280]
### Description

![perf](https://github.com/typst/typst/assets/9490724/44af4d2b-c3df-4b42-8b9a-93e9531ad819)

I'm trying to use this svg, but it fails to parse. I tried running it through a sanitizer but no dice.

The error is "failed to parse svg: missing root node"

**Comment by LaurenzV** [comment]
Are you using the web app or are you doing it locally? It seems to work fine for me locally, but I do have the same issue in the web app. In fact, it seems like any svg files fail to parse for me? It might just be a temporary bug, though, I'm not sure. When I click on the svg file in the web app it also doesn't show me its contents.

**Comment by SUPERCILEX** [comment]
Yep, in the web app. And yes! A refresh fixes it. Super weird.

**Comment by SUPERCILEX** [comment]
cc @reknih

**Comment by LaurenzV** [comment]
Must be a new bug as a result of the folder update. @Enivex Can you add the web app tag?
