### ISSUE TITLE
image should support PDF

### ISSUE THREAD

**Issue by jech** [typst/typst#1283]
### Description

Image currently groks PNG, JPEG, GIF and SVG.  It would be helpful if it supported (single-page) PDF in addition to the above.

### Use Case

I usually use lualatex for typesetting, whose preferred image format is PDF.  I'm currently trying to write my next document in typst, and I've found out that I cannot easily include the images that I've prepared, many of which are in PDF format.

**Comment by PgBiel** [comment]
Duplicate of https://github.com/typst/typst/issues/145
