### ISSUE TITLE
Typst does *not* use "no" hyphenation rules with "nb" language code

### ISSUE THREAD

**Issue by jakobrs** [typst/typst#1289]
### Description

Norwegian has three ISO 639-1 language codes:

- `no`: Norwegian (macrolanguage)
- `nb`: Norwegian Bokmål
- `nn`: Norwegian Nynorsk

For localisation it is necessary to specify either `nb` or `nn`, because the `no` language code is not specific enough to determine which spellings[^1] to use.

[^1]: This also affects some other aspects of the written language, but spelling is the most important one in this case

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
I [bumped](https://github.com/typst/typst/commit/53a896f049d45a8e9a225ceacd56da07854aa973) hypher, so this should work now.
