### ISSUE TITLE
Implement Outline for PDF

### ISSUE THREAD

**Issue by qjcg** [typst/typst#129]
Generated PDFs currently have no document outline.

Outlines are helpful for quickly navigating documents, and it would be great if typst would add support for them.

**Comment by clarkmcc** [comment]
Are you referring to something other than [this](https://typst.app/docs/reference/meta/outline/)?

**Comment by clarkmcc** [comment]
Oh I see, you're looking for a clickable outline. Something interactive. That's the piece Typst is missing today, correct?

**Comment by qjcg** [comment]
Correct, an interactive outline at the document level (distinct from the page-level outline currently provided by the `outline` function).

**Comment by laurmaedje** [comment]
True, didn't know about this issue. Manual bookmarks would be a separate feature request.
