### ISSUE TITLE
Allow syntax support using for other languages and character sets

### ISSUE THREAD

**Issue by RustyStriker** [typst/typst#1290]
### Description

Allow to use other character sets to describe document data, mathematical symbols(so `$ phi $` would be `$ פי $`  when turned to the Hebrew char set) and more(ideally support for most used character sets)

### Use Case

When writing using a different character set, every time i need to write a symbol or something similar, i need to switch layout, which slows down the typing and feels cumbersome and annoying.

**Comment by Enivex** [comment]
You can use a show rule here

(Man that was annoying having to deal with copying right-to-left text 😅)

![image](https://github.com/typst/typst/assets/2191754/9bef19ad-9c19-40ba-9acb-4a40bf3d979b)

**Comment by RustyStriker** [comment]
this is an interesting feature, it will be very useful thank you.

**Comment by laurmaedje** [comment]
While I can see the appeal, this would introduce _a lot_ of complexity and reduce interoperability between code written in different "dialects".
