### ISSUE TITLE
User-level common folder for template reuse

### ISSUE THREAD

**Issue by aditya-sengupta** [typst/typst#1291]
### Description

I'd like behaviour similar to LaTeX's predefined + user-definable .cls/.sty files at a user/root level, so they can be automatically imported into any project. I tried to do this by putting a `template.typ` at `~/.typst/template.typ` and importing from there, but `#import` seems to only look at relative paths and not absolute ones. So this could be resolved for users that want it by allowing for absolute imports. 

### Use Case

This wold allow reusable templates like LaTeX's (article, book, chapter, etc) without having to copy template files or long preambles from other projects.

**Comment by aditya-sengupta** [comment]
I'd appreciate more explicit support for compiling locally as well, so the
user doesn't have to be in charge of managing their own symlinks and/or so
there's a standard way to install a system-wide template, if that'd be
possible!

**Comment by PgBiel** [comment]
> I'd appreciate more explicit support for compiling locally as well, so the user doesn't have to be in charge of managing their own symlinks and/or so there's a standard way to install a system-wide template, if that'd be possible!

Yeah, I believe a `TYPST_PATH` env var or config of sorts could solve this.

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/typst/issues/1803
