### ISSUE TITLE
Backspace does not work sometimes in vim (insert) mode.

### ISSUE THREAD

**Issue by matthiasGmayer** [typst/typst#1293]
### Description

Typing backspace doesn't do anything in vim insert mode if the cursor is in front of a '\_' or a '#'.
For example, typing 'x_' and then backspace or '#' and then backspace in a project.

### Browsers

Firefox

### OS

Linux

**Comment by Enivex** [comment]
Is this possibly related to this https://github.com/typst/typst/issues/1229 ?

**Comment by matthiasGmayer** [comment]
As far as I can tell no. The web app is not frozen, I can still type. The only thing that does not work is the backspace.
It is also easily reproducible on my end (i.e. everytime I type _ I can use backspace).
Although it could be that it happens on other syntax errors as well, I am not sure.

**Comment by Voark** [comment]
Happens to me as well, I just have to manually select the text and delete it.

**Comment by HakonHarnes** [comment]
Happens to me as well, only in vim insert mode. A minimal example is: 

```
//
  ^ cursor here - can only delete the second forward slash
```

After deleting the second forward slash there is a syntax error, and I'm unable to delete the first forward slash using backspace. The text has to be manually selected to delete it.

**Comment by yl4070** [comment]
I speculate this issue is related to the Vim implementation, I assume it uses a 3rd party library, since I've experienced this issue on Hackmd as well.

**Comment by laurmaedje** [comment]
We use https://github.com/replit/codemirror-vim

**Comment by wzunknown** [comment]
met the same bug. backspace doesn't work when there is a error. any update here?

**Comment by laurmaedje** [comment]
I made some changes, which seem to fix this in my testing. Please tell me if this is still an issue.

**Comment by unmovingcastle** [comment]
I can now delete normally after hashtag, underscore, left parenthesis, thanks so much for the fix!

Mac

Firefox
