### ISSUE TITLE
Represent different headers in different pages.

### ISSUE THREAD

**Issue by jerrita** [typst/typst#1296]
### Description

Hi there, 

I am currently facing a vexing problem. My school requires a separate header on each page, where we need a fixed string on every even page and a chapter title on odd pages.

I've tried this:
```typst
set page(numbering: "1", 
  number-align: center,
  header: [
    #set align(center)
    #set text(fs_5, font: f_songti, fill: header_color)
    #locate(loc => {
      let now_page = counter(page).at(loc).at(0)
      if now_page % 2 == 0 {
        #now_chaper_numbering_and_caption
      } else {
        "重庆邮电大学本科毕业设计（论文）"
      }
    })
    #v(-1em)
    #line(length: 100%, stroke: 1pt + header_color)
  ],
  header-ascent: 30%)
```

However, some issues are arising. Firstly, the typist does not have a `MOD` or `&` operator. Furthermore, retrieving the chapter numbering and caption in that position(#1082) seems to be difficult.

I also attempted to use a global variable to store it, like this:

```typst
let now_chaper_numbering_and_caption = ""
show heading: it => [
    #if it.level == 1 {
        now_chaper_numbering_and_caption = it
    }
    #it
]
```

but `error: variables from outside the function are read-only and cannot be modified`.

Perhaps there is a better solution to this problem. Best wishes.

### Use Case

Same as description.

**Comment by LaurenzV** [comment]
To calculate the modulus, you can do `calc.mod(now_page, 2)`.

**Comment by Enivex** [comment]
> However, some issues are arising. Firstly, the typist does not have a MOD or & operator. 

https://typst.app/docs/reference/calculate/rem/

**Comment by laurmaedje** [comment]
You can also use `calc.even()`. Accessing the current heading counter should simply be a matter of doing `counter(heading).at(loc)` and if you need the full title you can use [`query`](https://typst.app/docs/reference/meta/query/).

**Comment by Enivex** [comment]
```
#set heading(numbering: "1.1")

#set page(numbering: "1", 
  number-align: center,
  header: [
    #locate(loc => {
      if calc.even(counter(page).at(loc).at(0)) {
        counter(heading).display()
        " "
        query(selector(heading.where(level: 1)).before(loc),loc).last().body
      } else {
        "重庆邮电大学本科毕业设计（论文）"
      }
    })
    #v(-1em)
    #line(length: 100%, stroke: 1pt)
  ],
  header-ascent: 30%)
```

This should work

**Comment by bouleusis** [comment]
> ```
> #set heading(numbering: "1.1")
> 
> #set page(numbering: "1", 
>   number-align: center,
>   header: [
>     #locate(loc => {
>       if calc.even(counter(page).at(loc).at(0)) {
>         counter(heading).display()
>         " "
>         query(selector(heading.where(level: 1)).before(loc),loc).last().body
>       } else {
>         "重庆邮电大学本科毕业设计（论文）"
>       }
>     })
>     #v(-1em)
>     #line(length: 100%, stroke: 1pt)
>   ],
>   header-ascent: 30%)
> ```
> 
> This should work

Yes, that works. But I want alternative alignment on even/odd pages. 
Best regards.
