### ISSUE TITLE
The colon after a figure number should respect regional spacing rules

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#1303]
### Description

Some languages, like french, add a no-break space before the colon.[^1][^2][^3]

[^1]: https://en.wikipedia.org/wiki/Colon_(punctuation)#Spacing_and_parentheses
[^2]: https://fr.wikipedia.org/wiki/Deux-points#Typographie (french)
[^3]: A narrow no-break space (U+202F) in some regions.

In the example bellow, Typst does not insert such a space before the colon, even though the language is set to french.
```typst
#set text(lang: "fr")
#figure([Ceci n'est pas une figure], caption: [Une figure])
```
![Ceci n’est pas une figure // Figure 1: Une figure](https://github.com/typst/typst/assets/57839069/11a14db6-9046-4601-a33b-d06acf46c547)

### Use Case

The main goal of this feature is to increase internationalization and reduce the need for boilerplate `set` rules like the one in the workaround bellow.

### Workaround

The `separator` field on `figure.caption`, added in 0.8.0, lets you do the following:
```typst
#set figure.caption(separator: [ : ])
```

**Comment by Omikhleia** [comment]
Greetings,
IMHO, there are two different things at stakes here:
1. Which "sign" is used after some numbered item.
1. Automatically handling the adequate punctuation spacing "rules"[^1] for French: no only in captions with colons as shown here, but at other places where this is normally required, even in running text:
   - Inside primary quotes (see also #1194) `«»`, and sometimes secondary quotes `‹›` when these are used.[^2]
   - Before colons
   - Before "high" punctuations (`;!?`) but with a number of exceptions.

[^1]: Or rather "good typography practice".
[^2]: French from France doesn't use the single "guillemets", but they (used to) occur in French from Switzerland, for instance.

Regarding the first point, it could be argued that this is a matter of styling (so the "default" here is a colon, but some books may call for other strategies: a dot, an em-dash, etc.)

Regarding the second point, without entering into all the details, the "good practice" varies here between French from France, from Canada or Switzerland regarding the width of those (non-breakable) spaces and their actual variability in justified content...
I don't know the position of Typst regarding good typography in non-English documents, and many commercial or professional solutions do not implement it perfectly... This being said:
 - Babel for LaTeX eventually got it quite right (though I do remember when it wasn't the case yet until the early 1990s, and we had to use custom packages or hacked versions of Babel after its inception, until it was eventually nicely implemented!)
 - SILE eventually has it quite right too... or so I hope! (_Disclaimer: I implemented the current logic there in 2021_).

**Comment by MDLC01** [comment]
Maybe a first step would be to add a `separator` argument to `figure` and other functions where this problem arises.

**Comment by Omikhleia** [comment]
> Maybe a first step would be to add a `separator` argument to `figure` and other functions where this problem arises.

So this issue could be split in two:
- Being able to customize separators is one small thing (and it would have to be made a global settings--I don't know Typst enough, but having to do it on each figure as seems implied would be tedious).
- Having proper automated French typesetting rules is another game.
 
(Being French, I am certainly biased towards what should come "first" in a typesetting system :smile_cat:)

**Comment by MDLC01** [comment]
> * Being able to customize separators is one small thing (and it would have to be made a global settings--I don't know Typst enough, but having to do it on each figure as seems implied would be tedious).

Well, if it is a function parameter, you can customize it globally using a [set rule](https://typst.app/docs/reference/styling/#set-rules).

**Comment by abramchikd** [comment]
In my university I have to use em-dashes in captions instead of colons. I couldn't find an easy way to achieve this. Adding the separator parameter would be great

**Comment by abramchikd** [comment]
I'll try and make a PR with this feature in a weak

**Comment by laurmaedje** [comment]
Relevant work on related things: #1704

**Comment by abramchikd** [comment]
I created a PR to add the separator field https://github.com/typst/typst/pull/1791
