### ISSUE TITLE
Page header font is incorrect if page is raw text

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#1305]
### Description

```
#show raw: set text(font: "Fira Code")
#set page(header: [Test ==])

`==`
```

![image](https://github.com/typst/typst/assets/9490724/a5b05040-9ea5-4470-aa16-1519095e4e7b)

```
#show raw: set text(font: "Fira Code")
#set page(header: [Test ==])

a`==`
```

![image](https://github.com/typst/typst/assets/9490724/87e5083e-80b3-4f32-b9e9-018645363b4e)

---

I can't repro this with the discord bot, so maybe this was already fixed?

**Comment by PgBiel** [comment]
Probably the same as #1127
