### ISSUE TITLE
Combining grid/table rows and columns

### ISSUE THREAD

**Issue by Bahnschrift** [typst/typst#131]
It would be helpful to have the ability to combine the rows and columns of grids and tables to produce an output similar to the [latex example](https://www.overleaf.com/learn/latex/Tables) below:
![image](https://user-images.githubusercontent.com/31170809/226890366-62db75f6-4507-4ed2-bc3f-1ecb7134b86b.png)

Sorry if this is already a feature, I searched through the documentation and test cases and wasn't able to find anything.

**Comment by waynr** [comment]
Oh yeah, here's a screenshot of the PDF rendered by typst using my example code above:
![2023-03-22-071755_1134x416_scrot](https://user-images.githubusercontent.com/1441126/226916099-7b28e9b7-83b1-410e-9328-56afd00f720c.png)

**Comment by Bahnschrift** [comment]
Thank you! This seems like a great workaround.
I'll leave this issue open for the devs to decide whether this should become feature, or remain as something that requires workarounds like this.

**Comment by waynr** [comment]
> I'll leave this issue open for the devs to decide whether this should become feature, or remain as something that requires workarounds like this.

I see it as less of a workaround and more of the right way to do it. Ideally, you probably want something that you can [import as a module](https://typst.app/docs/reference/scripting/) (see the modules section) that was written by someone else so you don't have to write it yourself but as far as I can tell there is no module distribution system for Typst (yet). I imagine that is going to be a big desire for users of this tool...

**Comment by waynr** [comment]
> As far as I can see, you're relying on those two "1fr, 1fr, 1fr" to happen to align. That'll work for that particular table, but not in general; consider "1fr, auto" to make the 2nd column as skinny as possible.

Ah, thanks for the advice! I just threw this together real quick so I wasn't paying much attention to detail :)

**Comment by PgBiel** [comment]
Just to add to this that I made a library in pure typst that makes this (and more) possible: https://github.com/PgBiel/typst-tablex

I'm still panning out the bugs (there are a few), but it should be mostly usable in its current state.

In the future, I hope to be able to port most of that library's functionalities to typst itself. For now, that'll do, though!
