### ISSUE TITLE
Slightly "Off" Typesetting of `norm`

### ISSUE THREAD

**Issue by ParadaCarleton** [typst/typst#1310]
### Description

It feels a bit weird having the norm bars be different lengths here: 
![image](https://github.com/typst/typst/assets/71727937/29d2f9dd-3e98-4021-8a3f-6ba3ebbcfae8)

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
I don't think this a bug really. Delimiter sizing is partially down to the font, and sometimes it's down to personal preference. You can disable scaling by using

` lr(norm(A^(-1)),size: #0%)` or  `lr(||A^(-1)||,size: #0%) `

I can also mention https://github.com/typst/typst/issues/611 which makes the difference more pronounced than it needs to be (this is a problem with New Computer Modern Math, not typst)

**Comment by ParadaCarleton** [comment]
> I don't think this a bug really. Delimiter sizing is partially down to the font, and sometimes it's down to personal preference. You can disable scaling by using

I mostly just flagged it because I didn't know what else to label it as from the options I got :sweat_smile: more of an improvement that could be made to rendering: Scaling all bars/parentheses on the same line to a common size, if the size is similar, would probably make this look better.

**Comment by r0uv3n** [comment]
> I do wish it was possible to disable scaling by default though.

I think this is possible via
`#set math.lr(size:0%)`.

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/typst/issues/360
