### ISSUE TITLE
Parametric length expressions

### ISSUE THREAD

**Issue by Nabav** [typst/typst#1311]
### Description

Assume I want a `box` with the `height` that can be set by a variable and a unit. It is now possible to pass constants with some units as arguments of type `length`. Please add a function that returns `length` with user arguments for `value` and `unit`.

### Use Case

The use case for me is to create an `enum` numbered list in 2 columns using `box`, whose height is flexible by the number of items of a list.

**Comment by laurmaedje** [comment]
You can create a length from a number with multiplication: `10 * 2pt == 20pt`.

**Comment by Nabav** [comment]
Thanks a lot.
