### ISSUE TITLE
Expose more page properties on `location` objects

### ISSUE THREAD

**Issue by PgBiel** [typst/typst#1321]
### Description

Currently, using `locate` or `query` in Typst enables access to `location` objects, which point to some location in the document; in particular, they provide the number of the page which contains said location. I'd like to propose some means of getting more information about said page, such as its total width / height and its margins, or even all properties we might be able to extract from the page (such as other parameters given to `set page`).

This seems like it would be somewhat doable by mimicking the approach currently used for page numbering, using frame metadata which is appended on page's `layout` function. Perhaps we could add more metadata there, maybe through some sort of `PageMetadata` struct or similar.

I guess being able to `query` pages could also work for that effect, but that could possibly have other implications.

### Use Case

Sometimes it is necessary to determine e.g. the margin of a page to do certain more complex calculations with location objects (they are in relation to the entire page - including margins -, while functions like `layout` provide info not based on margins). That would also properly enable being able to properly place things in the margin. Could also be useful to get other info from the particular page, including its dimensions, its header (if possible) etc.

**Comment by laurmaedje** [comment]
Closing in favor of #763.
