### ISSUE TITLE
Table project view is missing "See more" button

### ISSUE THREAD

**Issue by albertosantini** [typst/typst#1329]
### Description

When I set `View projects as a table`, only 5 items are displayed.
When I set `View projects as a grid`, all the projects are displayed.

### Browsers

Microsoft Edge

### OS

Windows

**Comment by Enivex** [comment]
There is a See More button at the bottom of the list.

(You can also collapse or uncollapse the grid)

**Comment by Enivex** [comment]
> I am sorry, but I don't see any `See more` button at the bottom of the list.
> <img alt="image" width="1055" src="https://user-images.githubusercontent.com/328179/241261948-55a0cd72-d86e-4458-a05d-66cce65b54ab.png">

Okay, that's presumably a bug then.

**Comment by laurmaedje** [comment]
Is this still a problem? I cannot reproduce it.

**Comment by albertosantini** [comment]
It seems the issue is there.

From scratch I create 7 projects:

Grid view

<img width="1027" alt="image" src="https://github.com/typst/typst/assets/328179/45014c02-8597-46fa-bd53-eb5fb246bbd4">

Table view

<img width="1034" alt="image" src="https://github.com/typst/typst/assets/328179/ab5a5b9a-9222-495b-9a56-96a6df229380">
