### ISSUE TITLE
Parenthesized function names make functions go undeclared

### ISSUE THREAD

**Issue by frozolotl** [typst/typst#1345]
### Description

The following code will give an error "unknown variable":
```typ
let (fn-name)(arg) = arg
#fn-name("a")
```
Removing the call to `fn-name` will cause the document to be accepted by the compiler however.

This bug is caused by the following lines:
https://github.com/typst/typst/blob/main/src/syntax/parser.rs#L971-L974
https://github.com/typst/typst/blob/main/src/syntax/parser.rs#L951

### Typst version

- [X] I am using the latest version of Typst

**Comment by Leedehai** [comment]
Maybe a dumb question: why would one want to add a parenthesis around the function name in the first place?

**Comment by laurmaedje** [comment]
I think they are saying that the let binding shouldn't be accepted at all rather than it failing on use.
