### ISSUE TITLE
footnote.entry can't work

### ISSUE THREAD

**Issue by Zuttergutao** [typst/typst#1348]
### Description

I used the footnote.entry to define the footnote format. however, the example provided in the manual did not work in my environment.

![image](https://github.com/typst/typst/assets/40693240/c8eabf4c-2551-4ff5-90e5-09eec06af641)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Zuttergutao** [comment]
I tried to put `#set footnote.entry(indent: 0em)`  at the beginning of the file, it works.

**Comment by laurmaedje** [comment]
It only works at the beginning of the file because the footnote style must be uniform for the whole flow of content. Perhaps this restriction can be lifted in the future, but as of know it can't.

**Comment by Zuttergutao** [comment]
Thanks!
