### ISSUE TITLE
Interface to compute with values in tables (as seen in Org Mode)

### ISSUE THREAD

**Issue by sirinath** [typst/typst#1349]
### Description

Ability to write formulas over lists and tables.

Ability to label calculated or constant values for later reference with perhaps type information.

### Use Case

There are times the result of one calculation will the the input of another.

So the ability to tag or label and refer to document elements so they can be used in further calculation.

I might need to refer to list elements of a particular list, column or row or cell or range of a table, paragraphs, secentaces, headers, special tagged or labeled values, etc. to generate other elements or part of the document.

**Comment by Enivex** [comment]
If I understood your question correctly this is already possible by using queries.

**Comment by sirinath** [comment]
@Enivex Can you give a pointer where I can readd more on this.

**Comment by Enivex** [comment]
> @Enivex Can you give a pointer where I can readd more on this.

https://typst.app/docs/reference/meta/

**Comment by sirinath** [comment]
What I had mind was something like this: https://orgmode.org/worg/org-tutorials/org-spreadsheet-intro.html

**Comment by Enivex** [comment]
> What I had mind was something like this: https://orgmode.org/worg/org-tutorials/org-spreadsheet-intro.html

Are you talking about the syntax, or the functionality?

**Comment by sirinath** [comment]
Both.

Need not be exactly like org mode but should have a Spreadsheet like feel, but not limited to tables. Maybe it can be done though queries but this will not have the spreadsheet feel. 

Another alternative your be MS Prower FX (https://learn.microsoft.com/en-us/power-platform/power-fx/overview)

**Comment by laurmaedje** [comment]
Spreadsheet functionality is out of the scope for the compiler, but can be implemented in user code. Could be a package.
