### ISSUE TITLE
Expressions in function parameters are accepted by the compiler

### ISSUE THREAD

**Issue by frozolotl** [typst/typst#1351]
### Description

The following code is accepted by the compiler:
```typ
#let foo((test: "bar")) = {}
```
To my knowledge, this function can't be called, without the compiler throwing an error.

I would expect this code to not be accepted at all, even without calling it.

To solve this, it might be enough to just switch the `false` to `true`.
https://github.com/typst/typst/blob/main/src/syntax/parser.rs#L1250

### Typst version

- [X] I am using the latest version of Typst

**Comment by Leedehai** [comment]
FYI I just tried flipping the `false` to `true` at https://github.com/typst/typst/blob/2dc0478ffe283f2433cbb58cf75d4f5f156fe74c/crates/typst-syntax/src/parser.rs#L1316 but the compiler still accepts `#let foo((test: "bar")) = {}` without error :)
