### ISSUE TITLE
Calling `outline` in document show rule does not work.

### ISSUE THREAD

**Issue by inetbowser** [typst/typst#1354]
### Description

When trying to compile following code, the compiler errors out with:
```
error: bibliography does not contain this key
   ┌─ main.typ:11:17
   │
11 │ = This is a test @helloworld
   │                  ^^^^^^^^^^^

```

When removing the `outline` call everything works fine.

EDIT: Code also compiles when removing only the citation in the heading (and leaving the `outline` call).

### Code to reproduce
`main.typ`
```typ
#let template(doc) = {
  outline()
  doc
}

#show: doc => template(doc)

= This is a test @helloworld
blabla @helloworld

= Biblio
#bibliography("refs.bib")
```

`refs.bib`
```bibtex
@misc{helloworld,
	author = {God},
	url = {https://templeos.org/}
}
```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
Probably the same issue as https://github.com/typst/typst/issues/785

**Comment by inetbowser** [comment]
I see, closing this issue then, as #785 covers it already.
