### ISSUE TITLE
NumberingKind for Korean numbering systems

### ISSUE THREAD

**Issue by BasixKOR** [typst/typst#1358]
### Description

Hi!

I've noticed typst supports Japanese and Chinese numbering, so I was wondering if we could do the same for Korean system too.

Some system I can think of for now:

- 가: 가, 나, 다, 라, 마, 바, 사, 아, 자, 차, 카, 타, 파, 하
- ㄱ: ㄱ, ㄴ, ㄷ, ㄹ, ㅁ, ㅂ, ㅅ, ㅇ, ㅈ, ㅊ, ㅋ, ㅌ, ㅍ, ㅎ

There are also their own Unicode variants: ㈀, ㈎, ㉠, ㉮ but I think it's safe to ignore those for now.

Would you consider adding those to `#numbering()` too? Thanks!

### Use Case

This system is commonly used for official Korean documents (such as the government) and can be seen in Korean books as well. I think they are quite common to come by in Korean resources, typically used in conjunction with Arabic numerals.

**Comment by reknih** [comment]
I think this would be a great addition! Do these numerals work exactly like Arabic numberals in terms of how numbers are written out 0-10? If not, I think that the implementation should best be handled by a Korean-speaker.
