### ISSUE TITLE
CLI compilation error using command 

### ISSUE THREAD

**Issue by Alistair99** [typst/typst#136]
When compiling the rust source code using command: cargo build -p typst-cli --release
the following error occurred:
error: Permission denied (os error 13) at path "/home/alistair/typst/typst-22-03-21-2/targetdjGuyy"

I had just updated my rust installation to rustc 1.68.0 (2c8cc3432 2023-03-06)

**Comment by reknih** [comment]
Did this issue persist? Can you provide more information on your configuration, i.e. what permissions your file has and which command you ran?

**Comment by laurmaedje** [comment]
Seems like a problem with your local file system, not Typst itself.
