### ISSUE TITLE
Cannot enter a single space in a formula

### ISSUE THREAD

**Issue by txtxj** [typst/typst#1364]
### Description

For example:

```
#table(columns: (auto),
  $$, $$
)
```

In order to align the formulas between lines in the edit window, I may need to insert a single space between the formula symbols

When I try to insert a single space into the middle of the first pair of `$`, it apparently turns into inserting two spaces, which is no problem. Then it turns into this:

```
#table(columns: (auto),
  $  $, $$
)
```

Then I try to delete one space.

If I delete the first space, the second space will be deleted as well. This is no problem.

But when I delete the second space, something wrong happens. It turns to this:

```
#table(columns: (auto),
  $, $$
)
```

Both spaces are removed, and the `$` symbol on the right side is also removed.

I also tried cutting off a space by Ctrl+X, but the result is the same as above.

### Browsers

Chrome

### OS

Windows

**Comment by txtxj** [comment]
I tried to enclose the `$$` in `[]` and the problem still exists.

**Comment by laurmaedje** [comment]
The behaviour when deleting the second space is buggy. `$ $` and `$  $` should be equivalent, but if you really need `$ $`, you can type it somewhere else and copy-paste it.

**Comment by laurmaedje** [comment]
Fixed.
