### ISSUE TITLE
lr does not work with left bracket at the end.

### ISSUE THREAD

**Issue by lecarrera-tec** [typst/typst#1366]
### Description

Problem:
$lr([4/5, +oo[)$

error: expected closing paren
   ┌─ 2023-S1-Examen2.typ:41:26
   │
41 │   $lr(union lr([4/5, +oo[)$
   │                           ^

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
You have to escape the left bracket because it will match with the following right bracket otherwise. Boils down to the same thing as #896.
