### ISSUE TITLE
Basic Floating

### ISSUE THREAD

**Issue by Andonome** [typst/typst#137]
Right now, an image at the end of a grid column enters the next column.  Would it be possible to acheive basic floating with a `#float` command which moves the target image (or anything else) to the top of the next grid, but continue placing the text in the first column?

It would also be good to have a command which lays the object outside of any current grids, so that a wide image could 'float' to the top or bottom of the next page.

Example of issue:

![image](https://user-images.githubusercontent.com/52453904/226908167-58247099-b5ad-42a9-82f4-59ee9ae41c3a.png)

**Comment by giannissc** [comment]
I have a more complete proposal for floating on #553

**Comment by Enivex** [comment]
This has recently been implemented, so I'll close this issue.

**Comment by awillenbuecher-xq-tec** [comment]
> This has recently been implemented, so I'll close this issue.

Could you please give us a link, or a hint how to get floating figures now?

**Comment by Enivex** [comment]
> > This has recently been implemented, so I'll close this issue.
> 
> Could you please give us a link, or a hint how to get floating figures now?

To be clear, it's on main, so it should be in 0.7. You can try it right now if you compile the cli

**Comment by awillenbuecher-xq-tec** [comment]
> To be clear, it's on main, so it should be in 0.7. You can try it right now if you compile the cli

I did (`typst 0.6.0 (f197a447)`), but I still don't know how to use this feature, or even the name of the function. All I can find is the `#float` function, but that's for converting values to floating-point.

**Comment by Enivex** [comment]
https://github.com/typst/typst/commit/78f96f844bc54c5385c1efda0b5faad3c49fa79b

You can look at the tests to see how it's used.

Obviously there'll be actual documentation once 0.7 is released

**Comment by awillenbuecher-xq-tec** [comment]
Thank you!
As an example for anyone else looking for this feature:
```
#figure(
  placement: top,  // must be `auto`, `top`, or `bottom`
  caption: [A Floating Figure],
  image("figure.svg", width: 80%),
)
```
