### ISSUE TITLE
Nested footnotes gives incorrect number order

### ISSUE THREAD

**Issue by landry-r** [typst/typst#1376]
### Description

When creating nested footnote, they are created with the wrong order, all the no-nested first, then nested what give a weird display.

Hey, it this a bug#footnote[it's 1] ?
That the footnotes#footnote[it's 2#footnote[should be 3]] are not in the correct order#footnote[should be 4]

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
That's unfortunately a known limitation of how things work currently. I can't do much about it right now, but I'm sure we can fix it down the road as the layout system improves.
