### ISSUE TITLE
Smart Quotes Break when start of the string has both Double and Single Quotes

### ISSUE THREAD

**Issue by devanlooches** [typst/typst#1379]
### Description

# Smart Quotes seem to work correctly when... 
- The string is surrounded only by double quotes or only by single quotes
- When the whole string is surrounded by double quotes and a smaller section is surrounded by single quotes
# Smart Quotes don't seem to work correctly when...
- The start of the string is both double and single quotes.
# Example:
Writing `"'This is a quote from a book and it is character dialogue'" (100).` results in:
<img width="331" alt="image" src="https://github.com/typst/typst/assets/50296057/f15edf74-1c3c-492e-8d74-c24b982bf612">

If only part of the quote is in single quotes like so: 
`"This is a quote from a book. 'Here is the speaking part'" (100).`
It seems correct:
<img width="319" alt="image" src="https://github.com/typst/typst/assets/50296057/8444c749-d425-46e7-8bfb-98484f654cfb">

# Hacky Workaround:

`"#sym.quote.single.l#h(-2pt) This is a quote from a book and it is character dialogue'#sym.quote.double.r (105).`
Results in:
<img width="326" alt="image" src="https://github.com/typst/typst/assets/50296057/a019bb0c-9fa3-42b1-91ee-3f54247437dd">

### Operating system

macOS

### Typst version

- [x] I am using the latest version of Typst

**Comment by alerque** [comment]
Just for completeness, another direction that doesn't work is with the nested quote part coming first. In that case the failure mode seems the same as if the quote is the whole thing:

```typst
"'This is a quote from a book.' Here not the speaking part" (100).
```

So it isn't the "whole quote" that is a problem, it is when it *start out* the quote.

**Comment by alerque** [comment]
c.f. #1433 for more smart quote discussion.

**Comment by devanlooches** [comment]
> Just for completeness, another direction that doesn't work is with the nested quote part coming first. In that case the failure mode seems the same as if the quote is the whole thing:
> 
> ```
> "'This is a quote from a book.' Here not the speaking part" (100).
> ```
> 
> So it isn't the "whole quote" that is a problem, it is when it _start out_ the quote.

Yes I did realize this shortly after posting the issue. Thank you for clarifying.
