### ISSUE TITLE
l-r parantheses matching too greedy

### ISSUE THREAD

**Issue by Mc-Zen** [typst/typst#1381]
Well, this looks awkward :D
```
#let ket(arg) = { math.lr(sym.bar + $arg$ + sym.angle.r) }


$ cos theta.alt/2 |0 angle.r-sin theta.alt/2 |1 angle.r $
$ cos theta.alt/2 ket(0) - sin theta.alt/2 ket(1) $
```
![image](https://github.com/typst/typst/assets/52877387/37a9a313-bf01-43b2-80a9-527e0158c47b)

It can be solved by declaring a dedicated `ket` command, but still a bit unexpected.

**Comment by Enivex** [comment]
There's something strange going on here, because it only seems to happen if | is used, not if you write bar.v or \u{7c}

**Comment by laurmaedje** [comment]
Because only actual Unicode symbols and syntax shorthands participate in the auto-matching and auto-scaling. Symbol notation and escape sequence don't, without explicit `lr`.

**Comment by user202729** [comment]
```
$ |0⟩ + 1/2 |1⟩ $ // good

$ |0 angle.r + 1/2 |1 angle.r $ // bad

$ \|0 angle.r + 1/2 |1 angle.r $  // good
```

Since the workaround is pretty easy (add a `\`) and it does match as expected if you use all Unicode symbols I wouldn't consider this a bug.

**Comment by negamartin** [comment]
> Because only actual Unicode symbols and syntax shorthands participate in the auto-matching and auto-scaling. Symbol notation and escape sequence don't, without explicit `lr`.

Why is that so?

**Comment by laurmaedje** [comment]
Automatic fence matching was removed in https://github.com/typst/typst/commit/fe402759c03eb93cefc2879e751b8e732891bd3e because of false positives like this.
