### ISSUE TITLE
First blank line in content block is not stripped

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#1382]
### Description

Create a paper from the IEEE template:
![image](https://github.com/typst/typst/assets/9490724/ca9fbce6-6c46-49cd-baab-d413adae65cb)

The spacing after the em dash is incorrect. If the abstract is changed from
```
  abstract: [
    The process...
  ],
```

to

```
  abstract: [The process...
  ],
```

then the spacing is fixed:
![image](https://github.com/typst/typst/assets/9490724/4939a60c-7e99-4409-afd8-0081c6661731)

which is clearly annoying as a way to format code. Thus, the first blank line in a content block should be stripped.

### Typst version

- [ ] I am using the latest version of Typst

**Comment by rpitasky** [comment]
I'd like to take a stab at this.

**Comment by laurmaedje** [comment]
This is intentional, but you can get rid of it by putting `#h(0pt, weak: true)` into the template, after the dash.

**Comment by laurmaedje** [comment]
> Hmmm, then I guess the template should be updated.

Fair enough.

**Comment by rpitasky** [comment]
This really smells like a bug; formatting in your Typst code shouldn't affect formatting in the output so subtly, in my opinion. This is the sort of thing people spend hours hunting for, and the "intended" fix (in my opinion) looks rather ugly- In general, I think it's undesirable that people would have to sacrifice the look of their Typst code to get the formatting they want.

**Comment by laurmaedje** [comment]
So, you propose to not strip leading whitespace (e.g. `[  hello]`), but if there is a leading linebreak, strip that + following indent)?

**Comment by SUPERCILEX** [comment]
I personally think all leading whitespace should be stripped. If you want to add a line break, use `\`. If you want to add horizontal space, that's where `h` comes in. The template should be the one in charge of spacing, so extra prefix/suffix whitespace in the argument is an edge IMO.

**Comment by laurmaedje** [comment]
> I personally think all leading whitespace should be stripped.

That would have problematic consequences: For instance, `#([Name1], [Name2].join[ and ])` and `[Hello] + [ ] + [World!]` wouldn't work correctly anymore. 

Note that leading and trailing whitespace _is_ stripped, but not at the parser level for a single content block, but at the layout level for a full content flow. While this requires explicitly getting rid of the spacing in templates in the rare case, it makes it simple to compose spaces like any other content.

> If you want to add horizontal space, that's where h comes in. 

If you want arbitrary horizontal space yes, but not if you want a space character that copy-pastes as a space character and has the width of a space character.

**Comment by SUPERCILEX** [comment]
Hmmm, those are compelling examples.

> So, you propose to not strip leading whitespace (e.g. [  hello]), but if there is a leading linebreak, strip that + following indent)?

This would improve the UX for this specific case, but I'm not sure it's worth it. Or at least, having different behavior based on whitespace feels wrong. So maybe we just update the template and call it a day?

**Comment by laurmaedje** [comment]
> This would improve the UX for this specific case, but I'm not sure it's worth it. Or at least, having different behavior based on whitespace feels wrong.

My thoughts, exactly.

**Comment by DVDTSB** [comment]
I am slightly late, but I fully agree with

>  If you want to add a line break, use `\`. If you want to add horizontal space, that's where `h` comes in. The template should be the one in charge of spacing, so extra prefix/suffix whitespace in the argument is an edge IMO.

Regarding:
>That would have problematic consequences: For instance,` #([Name1], [Name2]).join[ and ]` and `[Hello] + [ ] + [World!]` wouldn't work correctly anymore.

Instead of `[Hello] + [ ] + [World!]` you can use `"Hello"+" "+"World!"` and instead of `([Name1], [Name2]).join[ and ]` you could use `([Name1], [Name2]).join(" and ")`.
I think content blocks should be optimised for content writting, not for replacing strings. Also I think using something like `.join(" bla bla ")` makes more sense considering other programming languages , instead of using `.join[ bla bla ]`.

**Comment by laurmaedje** [comment]
> Instead of [Hello] + [ ] + [World!] you can use "Hello"+" "+"World!" and instead of ([Name1], [Name2]).join[ and ] you could use ("Name1", "Name2").join(" and "). Also I think using something like .join(" bla bla ") makes more sense considering other programming languages , instead of using .join[ bla bla ].

I respectfully disagree. Other programming languages don't have a dedicated content type, so of course you use strings, but in Typst I think content blocks should generally be preferred over strings where possible. They are more flexible (you can join on anything after all: text, spacing, images, etc.)

Overall, I think changing this would fix a relatively rare issue at the cost of introducing a lot of inconsistency. As such, I'm going to close this.
