### ISSUE TITLE
Doesn't is hyphenated as does-n't in english

### ISSUE THREAD

**Issue by Enivex** [typst/typst#1389]
### Description

```typst
#set text(lang:"en",hyphenate:true)
#block(width:10pt)[doesn't]
```
yields

![image](https://github.com/typst/typst/assets/2191754/cd939687-dbab-4c85-929f-97a1700a7661)

Note that doesn't shouldn't have any hyphenation points, here's the word with \usepackage{showhyphens} in LaTeX

![image](https://github.com/typst/typst/assets/2191754/e06d3b54-dfab-4bff-8c5f-4200d995ab80)

### Typst version

- [X] I am using the latest version of Typst

**Comment by nino** [comment]
Providing an additional example, useful for testing edge cases:

```typst
#set text(lang:"en",hyphenate:true)
#block(width: 10pt)[You're]
#block(width: 10pt)["You're]
```

yields

![CleanShot 2023-11-03 at 15 59 56@2x](https://github.com/typst/typst/assets/125832/46534191-7586-4bb5-86df-ff06cf081630)

So the `"` seems to make "You're" hyphenatable.

**Comment by Enivex** [comment]
<img width="1251" alt="Screenshot 2023-11-25 204456" src="https://github.com/typst/typst/assets/2191754/44c39afd-56a5-4f39-b136-7ff1720c0f53">

Another example of strange hyphenation. Should also be releated to the lack of lefthyphenmin and righthyphenmin, as described in https://github.com/typst/typst/issues/1941#issuecomment-1693037879

**Comment by laurmaedje** [comment]
Typst does respect the hyphenmins. The problem is rather that it hyphenates the wrong strings. Rather than hyphenating proper words, it hyphenates anything between two break opportunities. This means the input to the hyphenation here is "(Onenote)", which the hyphenator doesn't deal with well. Still a bug that needs fixing of course. Just wanted to point that out.

**Comment by Enivex** [comment]
> Typst does respect the hyphenmins. The problem is rather that it hyphenates the wrong strings. Rather than hyphenating proper words, it hyphenates anything between two break opportunities. This means the input to the hyphenation here is "(Onenote)", which the hyphenator doesn't deal with well. Still a bug that needs fixing of course. Just wanted to point that out.

I see! I just parroted that from the other issue since it sounded like a plausible explanation.
