### ISSUE TITLE
Two-page layout

### ISSUE THREAD

**Issue by arctic-penguin** [typst/typst#139]
Is it possible yet to customize layout for left and right pages separately? I couldn't find it in the docs.

**Comment by Kaes3kuch3n** [comment]
I guess you could use something like this to determine if the current page number is even or odd:

```
#locate(loc => {
  let currentPageNum = counter(page).at(loc).first()
  if calc.even(currentPageNumber) {
    // Right page layout rules
    ...
  } else {
    // Left page layout rules
    ...
  }
})
```

(Haven't tried it out though)

**Comment by taylorh140** [comment]
i tried
```
#set page(header:[
  #locate(loc => {
  let currentPageNum = counter(page).at(loc).first()
    if calc.even(currentPageNum) {
      // Right page layout rules
      set page(margin: (left:1in))
    } else {
      // Left page layout rules
      set page(margin: (right:1in))
    }
  })
]
)



#lorem(254)
#pagebreak()
#lorem(2324)
```
but it didnt work.

**Comment by laurmaedje** [comment]
There is now `#set page(margin: (inside: .., outside: ..))` which does this. There is also `#pagebreak(to: "odd")` to jump to the next odd or even page. Headers can be customized based on the page number with locate.
