### ISSUE TITLE
calc.cos(90deg) != 0

### ISSUE THREAD

**Issue by fenjalien** [typst/typst#1390]
### Description

To reproduce:
```
#calc.cos(90deg)
```
![image](https://github.com/typst/typst/assets/34489450/1429feee-e8ed-4943-bf9e-531f1eaebb59)

Expected output: 0

My current work around is to use `round` to 16 digits.

### Reproduction URL

https://typst.app/project/rW5cemVXv_UxcPYJ97Q6Lb

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by user202729** [comment]
Python:

```
In [1]: import math

In [2]: math.cos(math.pi/2)
Out[2]: 6.123233995736766e-17
```

I'd say this is not a bug.

**Comment by xkevio** [comment]
It's just a floating point error, https://0.30000000000000004.com/
