### ISSUE TITLE
Add syntax highlighting for Zig

### ISSUE THREAD

**Issue by knarkzel** [typst/typst#1393]
### Description

Currently, when trying to add syntax highlighting for Zig it doesn't work. I can try adding it myself and send a pull request.

### Use Case

Zig users.

**Comment by knarkzel** [comment]
Where should I look to implement this? :smile:

**Comment by Enivex** [comment]
Have you checked that it doesn't already work on main? A lot of new syntax highlighting was added recently, but it won't hit until 0.5

**Comment by laurmaedje** [comment]
Zig is already supported on main.
