### ISSUE TITLE
Optional chaining / null safety

### ISSUE THREAD

**Issue by Gewi413** [typst/typst#1394]
### Description

[Typescript](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) and [Kotlin](https://kotlinlang.org/docs/null-safety.html#safe-calls) provide "Optional chaining" / "Safe calls" to remove multiple null / none checks using `?.` instead of `.`.
[Rust](https://doc.rust-lang.org/std/option/) has a similar feature in it's Option and `?` operator

This would supplement `.at(default: )` parameter to worry less about whether a value exists or is none.

### Use Case

Let's say we have this hypothetical structure of our document `#let structure = (headings: ([= foo], [= bar]), pars: (…))`
Now we want to read the first heading's body using `structure.at("headings", default: ()).at(0, default: none).body` and the footnotes using `structure.at("footnotes", default: ()).at(0, default: none).body`. However we do not have any footnotes in this structure and the code and it wont compile as `none.body` doesn't exist. So we add a small check to return none earlier
```
let temp = structure.at("footnotes", default: ()).at(0, default: none)
if temp == none { return none }
return temp.body
```
Using the `?.` operator would however condense it down to `return structure?.at("footnotes", default: none)?.at(0, default: none)?.body`. And we wouldn't need to know that our next call expects an array in the dictionary at. (possibly `default: none` if the call is a null-safe one)

Currently this can be solved natively using something like `#let maybe(object, function) = if object != none { function(object) } else { none }`, but this will need more nested calls and lambdas

**Comment by laurmaedje** [comment]
At this time, I don't think such an operator would pull it's weight. If someone comes up with a nice general design in the future, maybe we can reconsider.
