### ISSUE TITLE
Custom Aliases / Macros?

### ISSUE THREAD

**Issue by atzlt** [typst/typst#1407]
### Description

Add the feature of defining custom aliases / macros for symbols, and _being able to reuse_ the configuration.

### Use Case

I'm not sure if this violates the philosophy of typst, and I'm really new here. But the naming of symbols frustrates me.

In LaTeX I'm used to define aliases for various symbols to improve readability. (For example, if you mean "the boundary of A" you probably don't want `\partial A`. I would `\def\boundary{\partial}` and use `\boundary A` instead.) This also provides a way to add shorthands (I almost always `\def\eps{\varepsilon}`, which saves a lot of typing.)

I don't see any way to do the similar things in typst. If there is, please tell me.

**Comment by LaurenzV** [comment]
Does this do what you want to achieve?
```
#let eps = sym.epsilon
#let boundary = sym.diff

$ eps $
$ boundary A $
```

**Comment by atzlt** [comment]
Yes, thanks!

**Comment by Vivdaddy** [comment]
This unfortunately does not work if I have many subfiles which I import from. For example, if you have a separate file for Introduction, Methods, Proofs etc. Then, if you include each subfile in the main document, the aliases do not work in each subfile. Is there a way I can define my aliases in one place such that for every subfile of a project it remains active?

**Comment by LaurenzV** [comment]
Not easily, I think, you'd have to create a new file where you define the alias and then include that file in all your subfiles.
