### ISSUE TITLE
Add syntax highlighting for assembly

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#1408]

**Comment by owiecc** [comment]
For which architecture? There is no one assembly language.

**Comment by SUPERCILEX** [comment]
Sure, but there are common patterns:
- `;` is a comment
- The first word without a `:` is an instruction, otherwise it's a label
- Numbers can be highlighted
- And maybe non-first-word-not-numbers can be highlighted a different color

That's probably good enough to look better than plain text.

**Comment by lucifer1004** [comment]
Assembly is already supported in v0.5, so maybe this can be closed? @reknih
