### ISSUE TITLE
support BibLaTeX extended name format

### ISSUE THREAD

**Issue by rudolfsg** [typst/typst#1418]
### Description

BibLaTeX extended name format is currently incorrectly parsed. It seems enabled by default in the zotero [better biblatex plugin](https://github.com/retorquere/zotero-better-bibtex/issues/566)  so I'd expect quite a few people run into this. 

**Steps to reproduce**
.bib file:
```bib
@inproceedings{Hasselt2016,
  author    = {family=Hasselt, given=Hado P., prefix=van useprefix=false and Guez, Arthur and Hessel, Matteo and Mnih, Volodymyr and Silver, David},
  title     = {Learning Values across Many Orders of Magnitude},
  booktitle = {Advances in Neural Information Processing Systems},
  date      = {2016},
  pages     = {4287--4295},
  url       = {http://papers.nips.cc/paper/6076-learning-values-across-many-orders-of-magnitude},
  urldate   = {2017-06-07}
}
```
.typ file:
```typ
Citation: #cite("Hasselt2016")

#bibliography("test.bib", style: "apa")
```
Output:
![image](https://github.com/typst/typst/assets/40721528/3b37f352-7adc-421e-8ef5-5e4b89e18d8a)

### Operating system

Linux

### Typst version

- [ ] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Needs to be fixed in https://github.com/typst/biblatex

**Comment by quachpas** [comment]
I implemented support for the default nameparts (given, family, prefix, and suffix) in typst/biblatex#48.
It seems to work well from my limited testing. I'd be happy to further refine the implementation if needed, I'm not particularly good at Rust.
