### ISSUE TITLE
Support different titles and counters in figures

### ISSUE THREAD

**Issue by teenjuna** [typst/typst#142]
Basically it's a feature request with two parts:

1. Support renaming the word `Figure` to something else
2. Support using a custom counter 

Motivation: I want to be able to use figures with both images and tables, and have different counters for them. I also want to change the titles for these figures (like `Image 1 - <caption>` instead of `Figure 1: <caption>` for images).

I think it can be achieved with additional arguments:
```
#let imagecnt = counter("image")
#figure( 
    image("img.png"),
    caption: [Some caption],
    counter: imagecnt,
    title: [Image],
    separator: [--],
)
```

Then it would be easy to wrap this in a function:
```
#let imagecnt = counter("image")
#let imagefig(src, width: 100%, caption: none) = {
     figure( 
         image("img.png", width: width),
         caption: caption,
         counter: imagecnt,
         title: [Image],
         separator: [--],
    )
}
```

It's also important that labels support these custom titles. Then working with images is very easy:
```
See @lab // -> See Image 1
#imagefig("img.png", caption: "Some caption") <lab>
```

**Comment by reknih** [comment]
Closed via #491
