### ISSUE TITLE
SVGs with `foreignObject` don't render correctly

### ISSUE THREAD

**Issue by natexcvi** [typst/typst#1421]
### Description

Text in [Mermaid](https://mermaid.js.org) graphs exported as SVG does not appear to be rendered at all.

<img width="1124" alt="Screenshot 2023-06-05 at 23 45 53" src="https://github.com/typst/typst/assets/62808031/aae538c0-04c6-42bd-a65b-5da64e9e7603">

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
Could you maybe upload the SVG here for reproduction purposes?

**Comment by LaurenzV** [comment]
Okay, nevermind, here is an example:
![mermaid](https://github.com/typst/typst/assets/47084093/e0c701d7-44a6-4f8d-aa4c-2113c31d0a84)

**Comment by natexcvi** [comment]
I've discovered that the text is rendered if I set `htmlLabels` to false in the Mermaid directives prior to exporting, which should probably help narrow down the scope.

**Comment by LaurenzV** [comment]
Yeah, I also think it's because of the HTML. Unfortunately, the upstream crate we use for parsing the SVG (resvg) doesn't support this either, so not sure if this issue is going to be fixed anytime soon.

**Comment by iamkroot** [comment]
+1 for SVGs from https://diagrams.net aka draw.io :(

**Comment by LaurenzV** [comment]
Could you send an example?

**Comment by iamkroot** [comment]
![HW2-christians drawio](https://github.com/typst/typst/assets/29517049/61980c38-cc1a-4bb2-bcb7-4d1d8a649ee2)
This one doesn't render any text inside typst

**Comment by LaurenzV** [comment]
Are you using the newest version? It does show text for me in the web app (allow the "Text is not SVG" should obviously not be there).
<img width="656" alt="image" src="https://github.com/typst/typst/assets/47084093/13900577-3ad1-4b16-b3c4-cf48bde5fa92">
**

**Comment by LaurenzV** [comment]
To circumvent that issue, make sure that you "Convert labels to SVG" when exporting your drawing.

<img width="400" alt="image" src="https://github.com/typst/typst/assets/47084093/971fa8b3-e854-4092-81d3-e46840d95ecd">

**Comment by iamkroot** [comment]
> To circumvent that issue, make sure that you "Convert labels to SVG" when exporting your drawing.
> <img alt="image" width="400" src="https://user-images.githubusercontent.com/47084093/271707812-971fa8b3-e854-4092-81d3-e46840d95ecd.png">

@LaurenzV of course, that option allows the text to be displayed (see the second sentence in my original comment). I was referring to the SVGs being broken when using the default settings on draw.io
(I'm using typst 0.8.0 btw)

**Comment by LaurenzV** [comment]
When I include it, it does render text but it contains that weird "Text is not SVG" on the bottom.

<img width="496" alt="image" src="https://github.com/typst/typst/assets/47084093/d07bf82f-d531-40d7-880f-b615f5765aae">

I'm afraid "Convert labels to SVG" is the way to go for now.

**Comment by LaurenzV** [comment]
> @LaurenzV of course, that option allows the text to be displayed (see the second sentence in my original comment). I was referring to the SVGs being broken when using the default settings on draw.io
(I'm using typst 0.8.0 btw)

Yeah, sorry about that, I only saw that after posting it, that's why I deleted it. 😅

**Comment by drbartling** [comment]
Created a discussion for some workarounds for the time being:
https://github.com/typst/typst/discussions/3090

I think this can be generalized to SVG->PDF->SVG for use cases other than mermaid diagrams.

**Comment by LaurenzV** [comment]
Here is some general context as to what is going on with those SVGs and why we can't really fix it from our side: https://github.com/typst/svg2pdf/issues/57#issuecomment-1927114818

So for now the best option is to generate the graphics as a PDF, convert that to SVG (using some tool) and then embed that SVG. Instead of directly generating an SVG using the tool.

**Comment by LaurenzV** [comment]
Since there isn't much we can do about this, we've decided to close this issue. However, typst will now emit a warning when embedding an SVG with `foreignObject`, so hopefully this will prevent unexpected surprises in the future.

**Comment by SasooXD** [comment]
> 
> I also noticed that, I exported to pdf and then used a pdf to svg converter, like described above.
>
Right. Thank you.

**Comment by cben** [comment]
tip: per [this mermaid comment](https://github.com/mermaid-js/mermaid/issues/2102#issuecomment-2940417795), you may need to disable htmlLabels on two levels (to affect text on both nodes and edges):
```
%%{ init: { "htmlLabels": false, "flowchart": { "htmlLabels": false } } }%%
```

**Comment by artemious3** [comment]
The text in draw.io diagrams became visible after I loaded and reexported SVG in Inkscape.

**Comment by Prolyxo** [comment]
> Apparently draw.io has now removed the "text settings" option (or at least I don't see it anymore), which means that I can't currently use SVGs diagrams from draw.io in my Typst papers. Are there any other workaround to fix this?

In draw.io _V28.2.5_, **"convert labels to SVG" option has been shifted from export menu to right panel under "text tab"**.
I just **`ctrl+A` to select all > Then click on "Text" tab menu in right panel > then check option "convert labels to SVG"**.

No `foreignObject` anymore in Typst _0.14.0_ ! :)

For more explanations and workaround : https://www.drawio.com/doc/faq/svg-export-text-problems

**Comment by LaurenzV** [comment]
Since the most recent version, you can embed PDFs directly, so that might be the best option for draw.io.

**Comment by yueneiqi** [comment]
> Since the most recent version, you can embed PDFs directly, so that might be the best option for draw.io.

Thanks! Here is how I do it, based on  [reference](https://github.com/typst/typst/discussions/3090):
`mmdc -i in.mmd -o out.pdf --pdfFit`, `--pdfFit` scales PDF to fit chart.
