### ISSUE TITLE
#heading(outlined: false) should not appear in PDF outline

### ISSUE THREAD

**Issue by cherryblossom000** [typst/typst#1422]
### Description

`#heading(outlined: false)` allows you to exclude a heading from the outline generated by `#outline()`. I think this should also exclude it from the outline in the PDF.

### Use Case

I’m making some slides with [typst-slides](https://github.com/andreasKroepelin/typst-slides) and I have a final ‘References’ section. The references span over multiple pages, but I would like to have each page have a `= References` heading, with only the first one being included in the PDF outline.

My current workaround is to do `#text(1.4em, weight: "bold")[References]`.

**Comment by PgBiel** [comment]
While I initially agree with your proposal (and it is very quick to implement this), I think this requires some thought. In particular, doing this would exclude the `Contents` heading from the TOC. Is this something we are okay with?

Perhaps there should be a separate parameter for being bookmarked, such as `bookmark: auto` defaulting to the same as the `outlined` option, and `bookmark: true/false` overriding that (in particular, TOC's `Contents` would default to `bookmark: true`, if this is desirable). Then, this proposal would go hand-in-hand with #1226.

**Comment by cherryblossom000** [comment]
That’s a good point. I didn’t think about the `Contents` heading.

I think the `bookmark` parameter you’ve described would be a good solution.

**Comment by ModProg** [comment]
To add to this problem, in case one has dynamic slides, one needs to switch between heading and text:
```rs
locate(loc => if subslide.at(loc).first() == 1 {
    heading(text(color)[#slide-info.title])
} else {
    text(color, size: 27pt, weight: 700)[#slide-info.title]
})
```

With this implemented, I'd expect typst-slides could implement this without hacks like this that break as soon as one changes the heading style with set rules. (related this could more reliably be worked around using https://github.com/typst/typst/issues/763)

**Comment by LoganTann** [comment]
Are there any workarounds to prevent them to appear in the PDF outline ?

**Comment by cherryblossom000** [comment]
@LoganTann please see [my original issue comment](https://github.com/typst/typst/issues/1422#issue-1742983300):

> My current workaround is to do `#text(1.4em, weight: "bold")[References]`.

**Comment by cherryblossom000** [comment]
More specifically, these are heading levels to text sizes:

| Level | Size (em) |
| ---: | --: |
| 1 | 1.4 |
| 1 | 1.4 |
| 1 | 1.4 |
| 1 | 1.4 |
| 1 | 1.4 |


Source:
https://github.com/typst/typst/blob/c0c03812d08bc833b8a2477c594d762f43a0c95b/library/src/meta/heading.rs#L135-L154

**Comment by cherryblossom000** [comment]
More specifically, for level 1 headings the size is 1.4em, for level 2 headings the size is 1.2em, and for all other heading levels the size is 1em.

https://github.com/typst/typst/blob/c0c03812d08bc833b8a2477c594d762f43a0c95b/library/src/meta/heading.rs#L135-L154

**Comment by ModProg** [comment]
@cherryblossom000 I think you have a typo here

> More specifically, these are heading levels to text sizes:
> Level 	Size (em)
> 1 	1.4
> 1 	1.4
> 1 	1.4
> 1 	1.4
> 1 	1.4

**Comment by cherryblossom000** [comment]
@ModProg My bad, must have accidentally sent that comment. I was going to do a table but then changed my mind.
