### ISSUE TITLE
rondom generator?

### ISSUE THREAD

**Issue by ondohotola** [typst/typst#1429]
### Description

I have a few years back designed a little stamp using LuaLaTeX, with a bit of realism, by way of slightly rotating the box in both directions, make ing the edges just a little smudgy. Then I like to vary the location and rotation of the stamp just a little bit so that it doesn't look printed if you compare two papers.

Is there or will there be a random number generator?

### Use Case

I can of course try and circumvent this with a Makefile, but there might be other uses for a RNG.

**Comment by laurmaedje** [comment]
Duplicate of #984 (while that one has a specific design proposal, it is also a suitable place to discuss this feature request in general).

**Comment by ondohotola** [comment]
thanks
