### ISSUE TITLE
Using more than one & marker in maths code breaks alignment

### ISSUE THREAD

**Issue by 20k** [typst/typst#1432]
### Description

```
$ diff_t W &= &1/3 W (alpha K - diff_i beta^i) + beta^i diff_i W \

diff_t cYij &= &dkbk cYij + 2 cY_"k(i" diff_"j)" beta^k - 2/3 cYij dkbk - 2 alpha cAij^"TF" + M_1 \

diff_t K &= &dkbk K - tilde(gamma)^"mn" C_"mn" + alpha cA^"mn" cA_"mn" + 1/3 alpha K^2 \

diff_t cAij &= &dkbk cAij + 2 cA_"k(i" diff_"j)" beta^k -2/3 cAij dkbk + alpha K cAij - 2 alpha cA_"im" cA^m_"   j" + (sillyR^mod_"ij" - C_"mn")^"TF" \

diff_t cGi &= &dkbk cGi + 2/3 cGi dkbk - cG^k diff_k beta^i + cY^"mn" diff_m diff_n beta^i + 1/3 cY^"im" diff_m diff_n beta^n $
```

This appears to have started rendering incorrectly recently when I re-checked my project, and produces this:

![incorrectrendering](https://github.com/typst/typst/assets/755197/db4b707b-0267-4050-b32c-adfd15700bca)

Deleting the second & in the following code:

```
$ diff_t W &= 1/3 W (alpha K - diff_i beta^i) + beta^i diff_i W \

diff_t cYij &= dkbk cYij + 2 cY_"k(i" diff_"j)" beta^k - 2/3 cYij dkbk - 2 alpha cAij^"TF" + M_1 \

diff_t K &= dkbk K - tilde(gamma)^"mn" C_"mn" + alpha cA^"mn" cA_"mn" + 1/3 alpha K^2 \

diff_t cAij &= dkbk cAij + 2 cA_"k(i" diff_"j)" beta^k -2/3 cAij dkbk + alpha K cAij - 2 alpha cA_"im" cA^m_"   j" + (sillyR^mod_"ij" - C_"mn")^"TF" \

diff_t cGi &= dkbk cGi + 2/3 cGi dkbk - cG^k diff_k beta^i + cY^"mn" diff_m diff_n beta^i + 1/3 cY^"im" diff_m diff_n beta^n
$
```

Correctly renders this:
![fixedformatting](https://github.com/typst/typst/assets/755197/9d786beb-126d-46c3-99f0-9bf3b27f5559)

I'm not 100% clear when this started happening, but multiple &s-per-line in this project now all seem to be broken and cause a lot of misalignment like this. It seems to be aligning the right hand side of the equations for some reason, and I'm wondering if its related to the implicit & change

For a more egregious example:

```
$ #let sillyG = $𝒢$

 & M_1 &= sigma beta_"i(" sillyG_"j)" - 1/5 cYij beta^k sillyG_k \

&M_2 &= 2/3 (beta^k_",k" - 2 alpha K) cGi - 2 Theta(lambda^i) lambda^i sillyG^i\

&lambda^i &= 2/3 (beta^k_",k" - 2 alpha K) - beta^hati_(\,hati) - 2/5 alpha cA_hati^(" " hati) \

& Theta(x) &"= Heaviside step function" \

&sigma &= 4/5  $
```

![formatty](https://github.com/typst/typst/assets/755197/e6cd85d1-b6ab-4277-bcd3-9953489ec575)

### Browsers

Chrome

### OS

Windows

**Comment by PgBiel** [comment]
This is because alignment now alternates between left and right alignment (introduced in #936). To cancel the effect, add another `&` to the second alignment marker, i.e. write `&&1/3`, `&&dkbk` etc. instead of `&1/3`, `&dkbk`, since it alternates. (It wasn't previously possible to use right alignment, that's why this was introduced. It is now more consistent with LaTeX and other engines.)

**Comment by 20k** [comment]
I see, this seems slightly confusing - perhaps another symbol here might have been a more readable choice, but I guess this isn't a bug then
