### ISSUE TITLE
Footnotes create extra blank pages when used inside columns

### ISSUE THREAD

**Issue by gtrogers** [typst/typst#1433]
### Description

When using footnotes inside two columns mode it seems to create extra pagebreaks or blank pages.

The following example results in a pagebreak between the title and the columns and an extra blank page at the end of the generated PDF.

## Example
```
= Test
#columns(2)[
== Some Lorem
#lorem(500)
== Something with a footnote
Hello world#footnote[This is a test] one two three four.
== Some More
#lorem(200)
#colbreak()
Another#footnote[Blah blah blah]
#colbreak()
]
```

Loving typst by the way, thanks to everyone involved for the great work!

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
I pushed a fix for footnotes in columns. This will remove the first blank page from your issue. The last blank page seems correct as you have an explicit `colbreak()` there.

**Comment by gtrogers** [comment]
Fantastic, thanks!
