### ISSUE TITLE
Webapp report incoherent syntax errors 

### ISSUE THREAD

**Issue by CypherDC** [typst/typst#1438]
### Description

**Explanation :**

While declaring arrays of dictionaries, Typst sometimes reports (nonsensical) syntaxical errors. These errors are not solved by undoing the modification which caused them, but can be solved simply by adding/removing whitespaces close to it.

**Reproduction steps :**

Step 1 : Write the following code in a blank file in a blank project, no issues will show :
```
#let doc_history = (
  ( date : [03/03/2022], revision : [1.00], history : [Création] ),
  ( date : [07/06/2023], revision : [1.01], history : [Trying to replicate a bug] )
)
```

Step 2 : Add a single whitespace in the last entry of the second elements, several errors will show : 
```
#let doc_history = (
  ( date : [03/03/2022], revision : [1.00], history : [Création] ),
  ( date : [07/06/2023], revision : [1.01], history : [ Trying to replicate a bug] )
)
```

> 

Step 3 : Remove the whitespace , errors will persist : 
```
#let doc_history = (
  ( date : [03/03/2022], revision : [1.00], history : [Création] ),
  ( date : [07/06/2023], revision : [1.01], history : [Trying to replicate a bug] )
)
```

Step 4 : Remove a whitespace in front of any key (like 'history'), errors will disappear :
```
#let doc_history = (
  ( date : [03/03/2022], revision : [1.00], history : [Création] ),
  ( date : [07/06/2023], revision : [1.01],history : [Trying to replicate a bug] )
)
```

**Other context :** 
 The issue looks like a bug with the way whitespaces are parsed. Typist compiler crashed once (got the 'The Complier crashed' message) while I was trying to reproduce the bug, but not after, it may be unrelated.

** Screenshot :**
![Typst_error_list](https://github.com/typst/typst/assets/135984150/0ef20f11-598f-437c-a9a0-11993d28beb5)

[edit 2023-06-08_18:43 : forget to remove a whitespace in Step 4 ; corrected]

### Browsers

Chrome

### OS

Windows

**Comment by CypherDC** [comment]
Update as of 2023-06-14 : bug is still present, despite the change to version 5.0.

**Comment by laurmaedje** [comment]
Can't reproduce this anymore.
