### ISSUE TITLE
Widow and orphan prevention can unnecessarily move text into next column

### ISSUE THREAD

**Issue by zylthinking** [typst/typst#1445]
### Description

The following code will put fault in the 2nd column and put the correct in both columns

```

#let split_2_columns(text) = {
    layout(size => style(styles => {
        let (height,) = measure(
            block(width: size.width - 22pt, text),
            styles,
        );

        block(
            width: size.width,
            height: height,
            columns(2, gutter: 11pt, text)
        )
    }))
}

#let s = [
    This research was funded by the
    In recent years, deep learning has
    increasingly been used to solve a
    variety of problems, what is the fuck with y.
]

// fault
#split_2_columns()[
    #set par(justify: true)
    #s
]

//correct
#split_2_columns()[
    #set par(justify: false)
    #s
]

```

### Operating system

linux

### Typst version

- [x] I am using the latest version of Typst
YES

**Comment by zylthinking** [comment]
another found:
```
#let split_2_columns(content) = {
    layout(size => style(styles => {
        let sz = measure(
            block(width: size.width - 22pt, content),
            styles,
        );

        block(
            width: sz.width,  // ------------------- replace it size.width causes problems
            height: sz.height,
            columns(2, gutter: 11pt,  content)
        )
    }))
}

```
sz.width = 431.6pt
size.width = 453.6pt 

In my system

**Comment by zylthinking** [comment]
So, the  if (sz.width - gutter) < size.width - 22pt {
      put text to 2nd column
} else {
    put text to both columns
}

**Comment by laurmaedje** [comment]
The reason for this is Typst's widow and orphan preventation. Without justification, your text fits into four lines, two in the first and two in the second. With justification enabled, spaces can be shrinked a bit and now the text suddenyl fits into three lines. To prevent a single line from being alone, Typst forces all three to be together. Because together they don't fit into the first column, they are moved into the second (where they also don't fit in this case).

**Comment by zylthinking** [comment]
But how to explain `width: 654.0pt` is different with `655.0pt`, both are huge enough to fit in the column height.
654pt will put the text in 1st column
while, 655.0 pt will put the text in 2nd column.

And because 453.6pt will also put the text in 2nd column, I belive  there is some width ( 453.6pt  < x < 654pt), which will begin to put the text from 2nd to 1st column.

```
#let split_2_columns(content) = {
    layout(size => style(styles => {
        let sz = measure(
            block(width: size.width - 22pt, content),
            styles,
        );

        block(
            width: 654.0pt, // 655.0pt  is different
            height: sz.height,
            columns(2, gutter: 0pt,  content)
        )
    }))
}
```

**Comment by laurmaedje** [comment]
Minimized:
```typ
#block(height: 30pt, fill: aqua, columns(2, lorem(19)))
```
