### ISSUE TITLE
Hot reloading support for the `watch` command

### ISSUE THREAD

**Issue by figsoda** [typst/typst#1447]
The current `watch` command updates the pdf whenever something changes, but users have to manually refresh their pdf browser to keep up with the changes. [typst-live](https://github.com/ItsEthra/typst-live) implements something similar, it would be nice if the feature is integrated into the `typst` cli, and the `watch` command would have an option to run a web server that does hot reloading. One thing typst-live doesn't do well enough IMO is that it refreshes the page completely, maybe the updates can be more seemingless if things are updated in place instead. I'm not sure if this is possible with pdfs, but this should be more trivial for the potential [html backend](https://github.com/typst/typst/issues/721)

**Comment by Enivex** [comment]
>manually refresh their pdf browser to keep up with the changes

A decent pdf viewer will already do this

**Comment by figsoda** [comment]
Is there some way to do that with firefox?

**Comment by Enivex** [comment]
> Is there some way to do that with firefox?

I do not know. But this is something that should be changed on the firefox side and not the typst side.

If you're on windows I can recommend sumatrapdf

**Comment by figsoda** [comment]
thanks for the help, I'm not on windows but I will figure something out or fall back to typst-live

**Comment by leo848** [comment]
On GNU/Linux with an X server I can recommend `xreader`. It is installed by default in most user-friendly distributions and I've never had any issue with it.

**Comment by stevenskevin** [comment]
KDE's default document viewer, [Okular](https://okular.kde.org/), supports automatic refresh too.

**Comment by BirnadinErick** [comment]
Zathura in Linux does this. Use it instead of browsers. And u can't hot reload without Javascript, this may add overhead of hosting a server.
