### ISSUE TITLE
Edition/version system to support breaking changes with backward compatibility

### ISSUE THREAD

**Issue by kovaxis** [typst/typst#1448]
### Description

Hello, I've been really enjoying the Typst web app and compiler, nice work!

I suggest adding an edition/version system, such that marking a Typst document with an edition (or version) ensures that it compiles the same across any future Typst version.

I imagine something like the Rust edition system.

NOTE: I do not suggest adding it now, only adding it before the first stable version of Typst.

### Use Case

With the recent update, I noticed that there are breaking changes. Thankfully, I don't need to recompile any older Typst documents, and I understand that Typst is currently in Beta and therefore everything is experimental.

However, if this happened once Typst was stable, I would worry that my documents no longer compile with the Typst changes, or worse, that they compile but have hidden typesetting issues. It would stop me from updating Typst if there were any breaking changes.

I would not like for Typst to stagnate after `1.0` (or whatever the first stable version is), and accumulate cruft like Latex did. So I suggest an edition system as a middle point. Of course, it would be great to introduce this edition system before the first edition, so as to not "default" to the oldest edition.

**Comment by laurmaedje** [comment]
Thanks for the suggestion! We can consider something like this once we reach stable, but that's still a longer while out. Since this issue isn't really actionable, I'll close it.
