### ISSUE TITLE
"Reconnected" or similar message after losing connection to webapp

### ISSUE THREAD

**Issue by negamartin** [typst/typst#1449]
### Description

After losing and regaining connection to the webapp, show a message along the lines of "Reconnected, your changes are being saved".

### Use Case

When connection to the webapp is lost, a message along the lines of "Disconnected, your changes are not being saved until the connection is restablished" is shown. However, no matching message like "Connected again" is shown, instead the message just disappears. This leaves me feeling not sure if my edits were saved, or if the message just expired.

It's a small improvement, I would like to receive some solid feedback that the connection was restablished and my data is safe.

**Comment by laurmaedje** [comment]
The web app shows "last synced 10 minutes ago" or similar message in the top right corner. If that isn't visible, the changes should be synced. We'll consider adding a message like you propose in addition.

**Comment by negamartin** [comment]
Glad to see the app improving!
