### ISSUE TITLE
Documentation: inconsistent tense/mood

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#1457]
### Description

Across documentation, both indicative ("does") and imperative ("do") are used to describe functions and methods.

For example, in [the documentation for the `at` method of `content`](https://typst.app/docs/reference/types/content/#methods-at), both forms are used in the same paragraph:
> <ins>Access</ins> the specified field on the content. <ins>Returns</ins> the default value if the field does not exist or <ins>fails</ins> with an error if no default value was specified.

This inconsistency is present throughout the documentation, and it does not seem that one form is predominant.

The sooner a clear decision is taken, the fewer updates to the documentation will be required.

### What to choose?

I do not have a personal preference, but since documentation is often embedded as Rust documentation comments, and [Rust tends to use third person indicative for documentation](https://github.com/rust-lang/rfcs/blob/master/text/0505-api-comment-conventions.md#formatting),[^1] perhaps following this convention would be the most reasonable solution.

[^1]: It should be noted that the linked RFC only applies to the Rust standard library, but it is common across Rust projects outside of the standard library to use third person indicative.

### Reproduction URL

https://typst.app/docs/reference/

**Comment by laurmaedje** [comment]
I'm fine with following the Rust way. I actually tried doing that, but I'm very used to the other form, so it didn't end up happening.
