### ISSUE TITLE
Equation numbers

### ISSUE THREAD

**Issue by luciandf** [typst/typst#146]
Hello, is there a way to write numbered equations like it is common in scientific papers and automatically update these numbers as equations are inserted or removed? Also is it possible to reference these equations like it is possible for Figures and bibliography?

this looks so promising!

**Comment by arctic-penguin** [comment]
https://typst.app/docs/reference/math/equation/ 

parameter: `numbering`, see example.

**Comment by luciandf** [comment]
ooo that's good! I love it! thank you

**Comment by NinZeige** [comment]
Thanks @arctic-penguin , but is there any way to reset the number? Just like we do it in latex by `\setcounter{equation}{0}`

**Comment by arctic-penguin** [comment]
@NinZeige 
```
#counter(math.equation).update(1)
```

There seems to be a bug. To have the next equation be numbered "(1)", you would have to set the counter to 0, but the function expects a positive integer.

I would recommend you file that as a bug.
