### ISSUE TITLE
Include uncited references

### ISSUE THREAD

**Issue by ModProg** [typst/typst#1462]
### Description

Idea would be to just have a parameter on `bibliography` e.g. `include-unused` that can either be `true` to show all uncited references or a list of strings with references to include. Default would be `false`.

This would match `\nocite{...}`  in `LaTeX`.

### Use Case

Including references that don't have a concrete use.

**Comment by ModProg** [comment]
Workaround:
```rs
#{
    set text(size: 0pt)
    for ref in ("a", "b", "c", ...) { 
        cite(ref)
    }
}
```

**Comment by HROMANO** [comment]
The workaround doesn't work for "chicago-notes" style as they appear as footnotes.

**Comment by reknih** [comment]
This is supported with `cite`'s [`form` attribute](https://typst.app/docs/reference/meta/cite/#parameters-form) set to `none`. Alternatively, all entries in a bibliography file can be included by using the [`full` attribute](https://typst.app/docs/reference/meta/bibliography/#parameters-full) on bibliography.
