### ISSUE TITLE
Ctrl-Z in web app undoes other people's latest changes

### ISSUE THREAD

**Issue by PgBiel** [typst/typst#1470]
### Description

When working with multiple people at once in the web app, if you press Ctrl-Z, you will undo the latest change done by anyone on the document, not _your_ latest change (which would be more consistent and predictable in general). For example, I'll often be working with other people in a document, and suddenly my latest code disappears because someone made a typo and they pressed Ctrl-Z, which undid my code (more recent), not their typo.

Ctrl-Z should, ideally, be restricted to your own changes, especially because it'll be almost impossible to make sure your change is the latest when multiple people are typing at the same time.
With that said, I can see how it would be useful to undo possible damage done by other people too. That could, however, be a separate keybind or button - or even just be restricted to a future version control feature.

### Browsers

Firefox, Chrome

**Comment by binarynoise** [comment]
My idea would be a normal `Ctrl+z` and a no-matter-who-did-it "power" `Ctrl+Shift+z` to have both

**Comment by laurmaedje** [comment]
Ctrl + Shift + Z is already bound to redo, at least on my keyboard layout (German).

**Comment by PgBiel** [comment]
Perhaps `Ctrl + Alt + Z `?

**Comment by laurmaedje** [comment]
Fixed. There is no no-matter-who-did-it power now, but I also don't think it's really useful.
