### ISSUE TITLE
Factorial should take precedence over fractions

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#1475]
### Description

The equation `f(x) / 2` gets implicitly parenthesized as `(f(x)) / 2` when rendered. This is a great feature, which should be extended to factorials: currently, `n! / 2` is implicitly parenthesized as `n (! / 2)`, which is very likely not to be what the user wants.

`n! / 2` is rendered as
![image](https://github.com/typst/typst/assets/57839069/fbf1f0e6-5d63-4fd6-9df8-27413d008606)
but I expected
![image](https://github.com/typst/typst/assets/57839069/cb84f421-cc58-4ac8-a2d9-81998b636b70)

### Workaround

The current workaround is to add explicit parentheses: `(n!) / 2`.

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
As someone who has faced this before, I agree this would be very nice to have in general, as this usage of fractions is very common in the math world (though I have no idea how feasible it is to implement).

**Comment by MDLC01** [comment]
> I have no idea how feasible it is to implement

I don't know much about the compiler internals either, but a similar effect has already been achieved for function-like stuff: `f(x) / y` is parenthesized as `(f(x)) / y`, but `f (x) / y` is parenthesized as `f ((x) / y)`.

**Comment by bluebear94** [comment]
I’ll take a look at this.
