### ISSUE TITLE
Option to ignore "bibliography does not contain this key" errors

### ISSUE THREAD

**Issue by boyen-cell** [typst/typst#1481]
### Description

Problem:
I don't want to have to re-upload my .bib file every time I found and want to write about a source that's not yet in the current .bib file in typst.

### Use Case

It could be helpful if the compiler wouldn't stop creating the document when a bibliography key isn't recognized. This could be toggle in one of the menus or some #function. It should still give out a warning but instead of not rendering the PDF It would be nice if it would render it anyway and output `CITEKEY NOT FOUND [name of citekey]` (maybe highlighted in grey) instead of the usual citation output.

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/typst/issues/4035
