### ISSUE TITLE
Redo shortcut (ctrl + shift + z) not triggering redo action

### ISSUE THREAD

**Issue by thygesteffensen** [typst/typst#1482]
### Description

When pressing (ctrl +z) the undo action is performed.
When pressing (ctrl + shift + z) the redo action is _not_  performed. 

Selecting the action from `Edit` -> `Redo` applies the action as expected.

According to https://keyboardchecker.com/ my keyboard and browswer registers the (ctrl + shift + z) presses :) 

### Browsers

Microsoft Edge

### OS

Windows

**Comment by laurmaedje** [comment]
Should be fixed.
