### ISSUE TITLE
Add LSP implementation to support autocompletion in IDE

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#1488]
### Description

I'm currently using `coc-texlab` plugin for `coc.nvim` plugin in Neovim to enable autocompletion (and renaming) for `lualatex` compatable syntax (LaTeX + LuaTeX macros). For example, tsserver from TypeScript is a great LS, which is so great, that I can't even describe it. One thing I particularly like is the values that can be used with custom type (it suggests only valid values):

<details><summary>code</summary>

```typescript
type a = 'alpha' | 'beta'

let b: a = ''
```

</details>

![image](https://github.com/typst/typst/assets/37143421/48183066-e59c-492e-a2cb-0f475b8c81ea)

Here is an example of optional arguments. LS will suggest all the available arguments the function takes:

<details><summary>text function definition</summary>

```typescript
type content = any
type stringarray = any
type integerstring = any
type ratio = any
type arraydictionary = any
type length = any
type autostring = any
type color = any
type relative_length = any
type lengthstring = any
type nonestring = any
type autoboolean = any
type autodirection = any
type noneinteger = any

type TextType = {
  font?: stringarray
  fallback?: boolean
  style?: string
  weight?: integerstring
  stretch?: ratio
  size?: length
  fill?: color
  tracking?: length
  spacing?: relative_length
  baseline?: length
  overhang?: boolean
  top_edge?: lengthstring
  bottom_edge?: lengthstring
  lang?: string
  region?: nonestring
  dir?: autodirection
  hyphenate?: autoboolean
  kerning?: boolean
  alternates?: boolean
  stylistic_set?: noneinteger
  ligatures?: boolean
  discretionary_ligatures?: boolean
  historical_ligatures?: boolean
  number_type?: autostring
  number_width?: autostring
  slashed_zero?: boolean
  fractions?: boolean
  features?: arraydictionary
  content?: content
}

function text(text: TextType): content {}
```

</details>

![image](https://github.com/typst/typst/assets/37143421/0e61f8e9-3279-4bbe-80ac-75d987bf0fef)

### Use Case

It would be great to have LSP implementation for Typst to make the process of making Typst documents even easier and faster. It will eliminate tight dependency to the documentation (fewer times you use autocompletion instead of looking up the docs, the less time is wasted).

**Comment by PgBiel** [comment]
Is this close to what you are looking for? https://github.com/nvarner/typst-lsp

**Comment by Andrew15-5** [comment]
Yes, I will check it out later today.

**Comment by Andrew15-5** [comment]
I'm using `vim-plug` (plugin manager in Neovim) and I was able to add and use `typst-lsp` like this:

```vim
" Plug the neccessary plugins in init.vim.
let g:config_dir = $HOME . '/.config/nvim'
let g:plug_dir = g:config_dir . '/autoload'
call plug#begin(g:plug_dir . '/plugged')
  " Typst syntax highlighting
  Plug 'kaarmu/typst.vim'
  " Lua package manager (for installing Typst LSP server)
  Plug 'williamboman/mason.nvim'
  Plug 'williamboman/mason-lspconfig.nvim'
  Plug 'neovim/nvim-lspconfig'
call plug#end()

" Install typst-lsp on Neovim open if not already installed and restart coc.nvim if current buffer is Typst file.
" Typst LSP
lua <<EOF
local package = "typst-lsp"
local mason_registry = require("mason-registry")
if not mason_registry.is_installed(package) then
  mason_registry.get_package(package):install():on("closed", vim.schedule_wrap(function()
    print("Package " .. package .. " installed")
    if vim.bo.filetype == "typst" then
      vim.cmd("CocRestart")
    end
  end))
end
EOF
```

I can't comment on the usefulness/ease of use of the LSP server, but from what I've tried it is pretty good (to say the least).

I also found a formatter: https://github.com/astrale-sharp/typst-fmt/. It is not perfect, but it is much better, than manual formatting.

P.S. `NVIM v0.7.2`. Also note that `typst-lsp` command is only available through Neovim shell commands, but not outside Neovim.
