### ISSUE TITLE
Pixels per Inch option for PNG export actually parses as Pixels per Point

### ISSUE THREAD

**Issue by stignarnia** [typst/typst#1491]
### Description

Basically the title, if I use --ppi 4 it interprets the input as 4 PPP = 288 PPI

You can either change the option name to PPP or change the way it's parsed

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Yes, it shouldn't be renamed. The internals should be switched to PPI instead.

**Comment by Akylzhan** [comment]
> Yes, it shouldn't be renamed. The internals should be switched to PPI instead.

I was thinking about just multiplying PPI by 72 and passing it to the render function this way
