### ISSUE TITLE
SVG visible in preview but not in downloaded version

### ISSUE THREAD

**Issue by thygesteffensen** [typst/typst#1492]
### Description

I can see in the docs that supporting SVG is ongoing. I could not find a similar issue where the SVG is missing, but some issues where the SVG is distorted existed. 

---

Using the web editor, the preview shows the SVG as expected, but the SVG is "missing" from the downloaded pdf. I have tried multiple viewers, Firefox, Edge, Adobe, and Document Viewer on Ubuntu - all are missing the figure.

The behaviour is the same using version 0.5.0 locally. The generated pdf does not contain the SVG. However, outputting to a png will result in the SVG being present.

### Reproduction URL

https://typst.app/project/psw-8nMLAfeU9KOjSBBXZA

### Browsers

Microsoft Edge

### OS

Windows

**Comment by LaurenzV** [comment]
It's known that there are currently issues with exporting SVGs. Could you send the SVG itself that you are having issues with? It also seems like the link is inaccessible.

**Comment by thygesteffensen** [comment]
I have attached the SVG. It is a SVG with a nested image of a SVG :) 
![Temp drawio](https://github.com/typst/typst/assets/31892312/22452747-61be-4de2-a1a7-f02f5e7ec798)

**Comment by LaurenzV** [comment]
Will be fixed once [this PR](https://github.com/typst/svg2pdf/pull/34) gets merged and upstreamed.
