### ISSUE TITLE
Vertical spacing after heading causes `first-line-indent` to break

### ISSUE THREAD

**Issue by paulkre** [typst/typst#1493]
### Description

When setting `first-line-indent` with

```typst
#set par(first-line-indent: 1.8em)
```

and adding vertical spacing to headings with

```typst
#show heading: it => {
  it.body
  v(1em)
}
```

the first paragraph after a heading will be indented, which is undesirable.

Unfortunately, I could not find any convenient commands like `\noindent` to solve this. The only way seems to be wrapping the first paragraph of every section in a block like this:

```typ
#[
#set par(first-line-indent: 0pt)
...
]
```

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by reitermarkus** [comment]
I had a similar problem, I used `block` as a workaround, e.g. in your example

```
block[#it.body]
```

**Comment by reitermarkus** [comment]
Or simply use `it` instead of `it.body` in this case?

**Comment by Astavie** [comment]
it seems this has already been fixed?

**Comment by laurmaedje** [comment]
If using `it.body` in this way, the heading becomes indistinguishable from a normal paragraph for Typst. Even if we consider that a bug, it's covered by #311, so I'm going to close this.
