### ISSUE TITLE
Add capability to import a template from a repository.

### ISSUE THREAD

**Issue by Meistermagier** [typst/typst#1509]
### Description

Enable the ability to import templates from external GitHub repositories. This feature will allow users to effortlessly distribute their custom templates, share them with others, and simplify the process of importing templates without the need for manual copying and pasting.

### Use Case

As a user of the Typst app, I want the ability to import templates from GitHub repositories. By integrating this feature, I can easily access a wide range of pre-defined templates created by other users. This saves me time and effort in manually recreating or copy-pasting templates, while also fostering collaboration and knowledge-sharing within the Typst community.

**Comment by clbarnes** [comment]
Could we bless an existing project scaffolding tool, e.g. [cookiecutter](https://www.cookiecutter.io/) or [copier](https://copier.readthedocs.io/)? Then template creators have a format to converge on which can easily be used by local authors, and the app can just use that in the backend. I suppose something which can easily be used in the frontend as well as the backend might be preferable.

**Comment by laurmaedje** [comment]
We have plans to support templates in the form of packages, integrated with the web app. We do not plan to allow import directly from GitHub. The reason are similar to the package management itself, see https://github.com/typst/typst/issues/1554 for more details.
