### ISSUE TITLE
Monospaced fonts ignore consecutive whitespaces

### ISSUE THREAD

**Issue by ufoscout** [typst/typst#1516]
### Description

When using a monospaced font, a single whitespace is rendered no matter how many whitespaces are present in the source.
I don't see other reasons to use a monospaced font if not to achieve some kind of vertical alignment, but this is not possible since whitespaces are ignored

### Reproduction URL

https://typst.app/project/rzmNZxwnTmsS4iNJuAOSfx

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
What you're looking for is raw().

**Comment by ufoscout** [comment]
@Enivex I tried `raw()` but it does not allow me to set the font I want. Can it be done?

**Comment by Enivex** [comment]
> @Enivex I tried `raw()` but it does not allow me to set the font I want. Can it be done?

Yes.

`#show raw: set text(font: "my font family here")`

**Comment by ufoscout** [comment]
@Enivex thanks! I owe you a beer. I was lost through the documentation for hours :(
