### ISSUE TITLE
Add "slanted equal" math comparison symbols (⩽ ⩾)

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#1521]
### Description

Add symbols `⩽`, `⩾` to `sym` module. Perhaps, `#sym.(lt|gt).eq.slant` (or `sl`, `slanted`) as the equivalent of `$\leqslant \geqslant \nleqslant \ngeqslant$` (![image](https://github.com/typst/typst/assets/37143421/92071151-bfca-498f-a63a-bdfa9b52958a)). Note that "not" symbols don't exist, because I didn't find them and I can't select them in PDF. If it's not possible, then at least `⩽⩾` would be nice. I found these code points:

```text
U+2A7D-U+2A84
U+2A93-U+2A98
U+2A9B-U+2A9C
U+2AF9-U+2AFA

misc:
U+29E3-U+29E5
U+2AA8-U+2AA9
```

### Use Case

These are the missing symbols. Since there is already a big verity of them, why not add a bit more to make the `sym` module more complete? I saw these symbols in the wild (and we probably used them in the school). I personally use them all the time in LaTeX math mode. Furthermore, I think we can all agree that they look more neat than the non-slanted alternatives.

P.S. Even my favorite mono font, Fira Code, uses these symbols as ligatures for `<=` and `>=`.

**Comment by laurmaedje** [comment]
Fixed via https://github.com/typst/typst/commit/1928154e695a0e4655d1574e171e54e0d00b3f6a

**Comment by Andrew15-5** [comment]
Thank you!
