### ISSUE TITLE
Documentation, outline function: broken link 

### ISSUE THREAD

**Issue by deining** [typst/typst#1527]
Just came across a broken link in the docu page for the [outline](https://typst.app/docs/reference/meta/outline/) function: 

![grafik](https://github.com/typst/typst/assets/18169566/07bb4ec5-df04-42fb-9aed-1b9c0be595cf)

If wanted, I am willing to author a PR for this. Are the sources of the docu pages are publicily availabe?

**Comment by laurmaedje** [comment]
This was already fixed in https://github.com/typst/typst/commit/7049a4563403e653f5c1f816da3dfd9025c6787a, but the web page only updates with the next release.
