### ISSUE TITLE
Have `page` counter set pdf metadata

### ISSUE THREAD

**Issue by ModProg** [typst/typst#1531]
### Description

If I generate a typst document with page `1` twice it sets only the number in the footer: 
[play.pdf](https://github.com/andreasKroepelin/typst-slides/files/11787468/play.pdf)

But with latex I can have the same number on multiple pages in the metadata as well, e.g. in this file:
https://github.com/pdfpc/pdfpc/releases/latest/download/pdfpc-demo.pdf

### Use Case

This is for example used by `pdfpc` to handle overlays in slides, but it is also generally useful to have the number in your pdf viewer match with the number shown in the pdf.

**Comment by Easyoakland** [comment]
As an example in latex one can use:
```latex
% Don't count pages in this environment
\newcounter{nopage}
\newenvironment{nopage}
{\clearpage\stepcounter{nopage}\addtocounter{page}{-1}
  \renewcommand{\thepage}{\arabic{page}.\arabic{nopage}}%
  \thispagestyle{empty}}
{\clearpage\setcounter{nopage}{0}}
```
and later use with
```latex
\begin{nopage}
    \tableofcontents
    \thispagestyle{empty}
    \cleardoublepage
\end{nopage}
```
to alter the page counting

**Comment by Easyoakland** [comment]
The below is a demonstration that shows that latex allows setting this number to an arbitrary Unicode value (including negatives, letters, and emojis):
```latex
\documentclass[12pt, a4paper]{article}

% GEOMETRY
\usepackage[
    headheight=15pt,
]{geometry}

% HYPERLINKS
\usepackage{hyperref}
\hypersetup{
    colorlinks=true,
    linktoc=all,
    linkcolor=blue,
}

% HEADERS and FOOTERS
\usepackage{lastpage}
\usepackage{fancyhdr}
    \pagestyle{fancy}
    \rfoot{\thepage \ of \pageref{LastPage}}
\usepackage{etoolbox}  % Define chapter page to use fancy
    \patchcmd{\chapter}{\thispagestyle{plain}}{\thispagestyle{fancy}}{}{}

\newenvironment{scoped}{}{}

\begin{document}

\begin{scoped}
    \renewcommand{\thepage}{👍 123\_page}
    \thispagestyle{empty} % Can't include the unicode at the bottom of the page.
    Weird numbered page.
    \cleardoublepage
\end{scoped}

Normal counter again.
\cleardoublepage

\addtocounter{page}{-1000000}
Very negative valued page numbering.
\cleardoublepage

\begin{scoped}
    \renewcommand{\thepage}{∑ ∫ π² ∞ ⪋}
    \thispagestyle{empty} % Can't include the unicode at the bottom of the page.
    more weird page numbering
    \cleardoublepage
\end{scoped}
\end{document}
```

**Comment by ModProg** [comment]
Yes, this is especially useful for documents that have, e.g., a preamble using roman numbers, but Arabic numbers for the body.

**Comment by laurmaedje** [comment]
Implemented in https://github.com/typst/typst/pull/1933
