### ISSUE TITLE
Old-style text figures (hanging numbers) not working for certain fonts.

### ISSUE THREAD

**Issue by daniel-gonzalez-cedre** [typst/typst#1533]
### Description

Using `#set text(font: "Palatino", number-type: "old-style", fallback: false)` at the top of the document, the text `In order to 1234567890` should render with old-style numerals, but instead they look the same as if `number-type: "lining"` had been set. There are no compiler errors, and there is certainly _some_ version of Palatino that is being loaded, since all of the characters render.

I have a system-installed version of Palatino (macOS Ventura 13.4), and I verified that it has support for old-style figures (`U+0030` through `U+0039`). I also tried copying the `Palatino.ttf` file to a local directory for my project and running `typst --font-path ./local_font_dir watch mydocument.typ`, but the document renders the same.

Please see the screenshot below: the top line is rendered with LaTeX using `\usepackage{mathpazo}[osf]` and is the style I'm trying to replicate, while the bottom line is rendered with Typst.
<img width="256" alt="osf" src="https://github.com/typst/typst/assets/39937561/7cd611d5-3d2b-4b7a-8b4b-6e520187a68d">

This was discussed today on the Discord. It also seems like there is no way to detect which version of a font Typst is loading (e.g., local, system, Typst-included). I should also note that old-style numerals do seem to be working for the default Typst font.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Thanks for investigating @mkorje! Based on this, I'll close as it's not a Typst issue.

**Comment by daniel-gonzalez-cedre** [comment]
thanks so much for looking into this @mkorje, this is great information

**Comment by adamkrellenstein** [comment]
yeah thank you!
