### ISSUE TITLE
Add more color modification functions.

### ISSUE THREAD

**Issue by DVDTSB** [typst/typst#1534]
### Description

Add HSV to colors. It would be very usefull to have HSV so you could change the hue or saturation of a color.

### Use Case

You could have something like `color.set_saturation(100%)`, or `color.get_saturation()`.

**Comment by DVDTSB** [comment]
#1326

**Comment by DVDTSB** [comment]
#61

**Comment by DVDTSB** [comment]
#1332

**Comment by laurmaedje** [comment]
HSV is now available and saturate/desaturate, too.
