### ISSUE TITLE
Support for unbreakable spaces

### ISSUE THREAD

**Issue by s-d-m** [typst/typst#1538]
### Description

Unbreakable spaces are spaces where a layout engine should not put a line or page break.

Latex uses the character "~" to denote such a space. Maybe the same character can be used, and an escape sequence could be provided for the cases where ~ is what the user wants to type. Or maybe a function?

### Use Case

A typical example of where this is used is when typing numbers or identifiers. For example, when writing "Hey, I just met you! And this is craaazy! So here is my number (+ 385 99 3445 87), so call me maybe", a layout engine should be advised not to write the beginning of the phone number in one line, and the end on the next one.

**Comment by laurmaedje** [comment]
The `~` character also means unbreakable space in Typst.

**Comment by s-d-m** [comment]
Then, either I am blind, or the documentation should be improved with a
section about unbreakable space. I couldn't find it when I looked for it.

On Wednesday, 21 June 2023, Laurenz ***@***.***> wrote:
> The ~ character also means unbreakable space in Typst.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci5.googleusercontent.com/proxy/JxPTPSI5hwhCxgVSCPKnt16tVwkJpcYBTr7HgW9crHSdjDOTDtuElxemdAkqUiHV3Za3lHQWtegNcoTmrv5CTRNW91knjYxjqVFGzGL5ifFEL_9ckqrO5AKc-dZh8zhZho69Z2JeLnPRXocEDVhFiy6mKkf5CoyL890Pb3w5FQBTe1-P25uZeKOFmHLq9lA4fJ1cbLGU_OAyPrTvem0mtKFolQPZwiVh7XYGIVzSOuLEoKreUQ=s0-d-e1-ft#https://github.com/notifications/beacon/ACG6LUC4S3UOOD2BSOGIZYLXMKNXZA5CNFSM6AAAAAAZN3EXLWWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTS7MLATK.gif>Message
ID: ***@***.***>

**Comment by MDLC01** [comment]
On the [General Symbols page](https://typst.app/docs/reference/symbols/sym/), `space.nobreak` clearly indicates that `~` can be used as a shorthand. Although I agree that this is not necessarily where you would search for it in the first place.

![No Break Space. Name: space.nobreak. Escape: \u{00A0}. Shorthand: ~.](https://github.com/typst/typst/assets/57839069/f25da930-db6e-4a15-88a7-3142708655e2)

**Comment by laurmaedje** [comment]
It is also listed as one of the examples in "Symbol shorthand" on the [syntax page](https://typst.app/docs/reference/syntax/). I'm going to close this issue, but if there's another obvious place where it should be listed in your opinion, feel free to say so.

**Comment by s-d-m** [comment]
I am not sure if the documentation should be improved anymore. The keywords
I typed in the search bar were "unbreakable space" and "non breaking space"
which didn't return a result. I didn't think of searching for "no break
space".
I understand improving the search engine is out of scope and would distract
from the goal of the project.
Let's just close this.

On Wednesday, 21 June 2023, Laurenz ***@***.***> wrote:
> It is also listed as one of the examples in "Symbol shorthand" on the
syntax page. I'm going to close this issue, but if there's another obvious
place where it should be listed in your opinion, feel free to say so.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.<
https://ci5.googleusercontent.com/proxy/170oqitL5yHowEVqpjr6IEoQAeu2GqT0DnV--PbiChUIOZEAEMZooBRIEin2vcycf8VkrzOoHRwbg4_VsYOgZR8Kzvau_f0K1ebFxi3g35QqeBXIXcQboht7D8l0vsx7-HA7G4ceg2UBQrgC6_dKgJz9DgBgfxyFJJAvRHTNnIVocbbZ7MPbB0OmpeswPTWrHwpcjGAyWANDWTYduQuGwUmoJ0iJTbhWAA8p5DJb1f5Wr-vHhg=s0-d-e1-ft#https://github.com/notifications/beacon/ACG6LUFCYCT777OA4QXIW6TXMLH23A5CNFSM6AAAAAAZN3EXLWWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTS7M6RUW.gif>Message
ID: ***@***.***>

**Comment by wlupton** [comment]
I know that this is an old (and closed) issue, but I wanted to note that I too had difficulty finding out that `~` is a non-breaking space (it's several decades since I last used LaTeX and I'd forgotten that TeX/LaTeX use it).

I *did* see it listed as a symbol shorthand (at https://typst.app/docs/reference/syntax) but when I went to https://typst.app/docs/reference/symbols/sym I didn't see it, and searching for "nobreak" doesn't directly find it (you have to click).

So I'd suggest that symbols with shortcut support should be listed directly at the top of the https://typst.app/docs/reference/symbols/sym page (there are probably only a very small number of symbols that have such shortcuts?). I'd be happy to create a PR (in `docs/reference/details.yml`, right?). LMK.

**Comment by laurmaedje** [comment]
A symbol shorthand list will be available with the next update.

**Comment by reknih** [comment]
![Symbols category page](https://github.com/typst/typst/assets/3874949/81166dcd-26a8-4cad-ba2b-b94471643563)

It will look a little something like this

**Comment by laurmaedje** [comment]
@wlupton It looks like this now:
![image](https://github.com/typst/typst/assets/17899797/86a796a0-a508-4f6f-b4cf-b8091f3361c0)

**Comment by MDLC01** [comment]
This page does not appear when searching for "shorthand" in the search, and the "Shorthands" section is not listed on the right of the page ("ON THIS PAGE").

**Comment by NicoWeio** [comment]
I hope you don't mind me using this existing issue for a clarifying question:

Is it intentional that writing a non-breaking space directly, i. e. `Hello World`, does not have any effect, whereas entering symbols like `ϑ` directly just works?

**Comment by laurmaedje** [comment]
I suppose we could restrict it to just normal spaces and normal newline sequences. Right now, all thing for which Rusts `is_whitespace` returns `true` are handled equivalently.

**Comment by janosh** [comment]
perhaps this issue was closed prematurely. i'm looking for a thinner non-breaking space than `~` to separate a value from it's units. `$thin$` looks much better than `~` but breaks at line ends.

```typ
Molecular dynamics at 300$thin$K or 600~K.
```

![Screenshot 2024-04-10 at 12 55 28](https://github.com/typst/typst/assets/30958850/c29e7121-3f3a-4b08-80bf-abf3fbeb71d7)

**Comment by laurmaedje** [comment]
Try `space.nobreak.narrow` / `\u{202F}`.

**Comment by janosh** [comment]
thanks, that works great! not just for units, also for [large number formatting](https://github.com/typst/typst/issues/3269#issuecomment-2032612522)

**Comment by Ownezx** [comment]
For anyone like me who finds this thread but does not not know how to access the symbol with less boiler plate, #3197 shows a convenient method to use it:
```
#show "_": sym.space.nobreak.narrow
Weight: 3_456_g, Size: 54_cm
```

**Comment by rugk** [comment]
I am also wondering how to find the shorthand docs for unbreakable spaces. [The page screenshotted here](https://github.com/typst/typst/issues/1538#issuecomment-1671017797) does not seem to exist like this or I cannot find it. [The symbols page](https://typst.app/docs/reference/symbols/sym/) only lists the symbols and only on click he shorthand of the symbol clicked upon. I cannot see a heading "shorthands"/a list of all "shorthands" here?

**Edit:** Ah, for everyne as dumb as me. [It's on the page above](https://typst.app/docs/reference/symbols/).
