### ISSUE TITLE
Smartquotes break on the introduction of a linebreak

### ISSUE THREAD

**Issue by mizukarada** [typst/typst#1540]
### Description
Smartquotes break on the introduction of a linebreak

### Reproduction
```typst
"test"#linebreak()"test"

"test"\
"test"
```

Preview:

<img width="168" alt="Untitled" src="https://github.com/typst/typst/assets/111034657/85412a23-8177-44d6-9039-f17ef0e48758">

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
Duplicate of https://github.com/typst/typst/issues/1106
