### ISSUE TITLE
Make footnotes referenceable / reusable

### ISSUE THREAD

**Issue by Enivex** [typst/typst#1543]
If I create a footnote
`#footnote("Hello World")<label>`
it's occasionally useful to reuse the same footnote several times. Currently, if you do `@label` you'll get the error "cannot reference footnote". I propose that this should instead reuse the same footnote.

This is already easily possible with queries, but it would be nicer if that wouldn't be necessary.

```
#set page(paper: "a7")
#let refnote(ref) = locate(loc => {
  query(ref,loc).first()
})


Hello#footnote("First footnote")

#lorem(20)#footnote("Second footnote")<test>
#lorem(8)#footnote("Third footnote") #lorem(8)

Here I reuse the second footnote#refnote(<test>)
```

![image](https://github.com/typst/typst/assets/2191754/9d0b6d7c-fe21-4bea-a10a-a86493ff3a14)

(This came up in https://discord.com/channels/1054443721975922748/1121036038022910063/1121036038022910063 )

**Comment by laurmaedje** [comment]
Seems useful and should be easy to support.

**Comment by MDLC01** [comment]
I can take a look at this

**Comment by Enivex** [comment]
@PgBiel 

What does this improve over the simpler workaround I already demonstrated?

**Comment by PgBiel** [comment]
> @PgBiel 
> 
> 
> 
> What does this improve over the simpler workaround I already demonstrated? It already seems to work perfectly

Sorry, I updated my comment. Just meant to share another workaround attempt we had done over Discord, in case this could be insightful in any way, but yours is clearly much cleaner, hehe.

**Comment by rugk** [comment]
I am sorry, but I came here because I searched for this feature. Is there any docs for it or do I miss sth.? https://typst.app/docs/reference/model/footnote/ does not mention the word "reuse".

**Comment by MDLC01** [comment]
The second paragraph in the Example section mentions this feature
