### ISSUE TITLE
File path restrictions

### ISSUE THREAD

**Issue by SliceOfArdath** [typst/typst#1544]
### Description

We propose two changes:
- Make all (valid) paths canon
- Implement a permission flag system for vm::locate(), that describes what paths are or are not allowed. Permissions would be the following:
  - Global, allowing paths that start from the filesystem's root, instead of world::root() (disabled by default)
  - FileRelative, allowing paths starting from the file invoking locate (enabled)
  - Upwards, allowing paths containing ../ as a component.

This issue is related to #1536, which already partly implements this. As such, I ask if the proposed change is acceptable, so that I would propose it as a separate PR (removing the writing part, according to #1056)

### Use Case

The purpose is to, if not stop, at least limit predatory file accesses, as described in #219.

**Comment by laurmaedje** [comment]
Thanks for starting the design discussion! My first remarks:

- What do you mean by "Make all (valid) paths canon"? I don't really follow.
- I'm wondering whether the permission handling is best located in the `Vm` or perhaps rather in a `World` implementation, in this case, specifically in the CLI's `SystemWorld`. This way, the `World` can truly ensure that no forbidden file access happens instead of trusting Typst to not ask for that file.
- You propose three different permission levels. Why exactly these? I don't fully understand each of these and their specific purpose. An alternative design we had discussed was a `--fs` flag with a glob to specify allowed paths. We'd also need to settle on a good default, of course.

**Comment by SliceOfArdath** [comment]
Hi! Thanks for the consideration!
> What do you mean by "Make all (valid) paths canon"? I don't really follow.

What I meant was that path.canonicalize should always be called before filesystem operations (reading the file, but also writing the path to systemworld::sources). What this means in practice, is just adding one line to systemworld::resolve (as far as i'm aware at least, cf commit 30fe21a6, main.rs, line 634).
Why do that? this change was originally meant for a cross-origin checker i did not mention (as we only have one origin, `root`)

> I'm wondering whether the permission handling is best located in the Vm or perhaps rather in a World implementation, in this case, specifically in the CLI's SystemWorld. This way, the World can truly ensure that no forbidden file access happens instead of trusting Typst to not ask for that file.

that's a good point! I just put it in `Vm` because of vm::locate, which already did, in spirit, what i wanted to work on (aka, convert the path, and add the right prefix to it (root or the typst file calling it). I think that one is for you to call.

> You propose three different permission levels. Why exactly these? I don't fully understand each of these and their specific purpose. An alternative design we had discussed was a --fs flag with a glob to specify allowed paths. We'd also need to settle on a good default, of course.

The assumption I made for this proposition, is the following: `root`is an allowed directory. This means that any an all `read` accesses within will be "legal". Therefore, if we are to prevent accesses outside of `root`, all accesses made will be legal.
This explain the first Global and Upwards. FileRelative is explained by a second assumption: In some future, there may be more than one `root` (for example, if we are to add a .typ package manager). As permissions would be tied to their own `root`, the idea was to enable finer-grained control of what to allow. 
The idea made much more sense in the original PR (that included a codebase to allow writing), but would still make sense if we restricted the file types (ie; the FileRelative permissions may be different for accessing  `.typ` file and a `.png`file.

There was, with this (though i did not mention it in the original issue), one last potential addition: Cross-Origin checking. This would only make sense if we did add multiple roots, obviously. The point was simply to check if the file access was done in the right root (and would come with a special flag, to override that check).

**Comment by laurmaedje** [comment]
> that's a good point! I just put it in Vm because of vm::locate, which already did, in spirit, what i wanted to work on (aka, convert the path, and add the right prefix to it (root or the typst file calling it). I think that one is for you to call.

Then, I'd be in favor of putting it into the World. Just a heads up: I will probably rework the `World` a bit while working on package management in the compiler.

> The assumption I made for this proposition, is the following: `root` is an allowed directory.

Is that necessarily the case? By default, the root is the directory the main file is in. Thus, if you compile a file directly in your home directory, your whole home directory would be legal in that design.

To me the concept of multiple root makes limited sense or, at least, only in the form of packages, which at the top-level could only access what's in them. Functions in the package that are called from a main file should probably resolve paths relative to the calling file (see also: https://github.com/typst/typst/issues/971#issuecomment-1604814460)

**Comment by SliceOfArdath** [comment]
> Is that necessarily the case? By default, the root is the directory the main file is in. Thus, if you compile a file directly in your home directory, your whole home directory would be legal in that design.

I thought this made the most sense, do you have any idea of *what* should be legal in such a case?

**Comment by laurmaedje** [comment]
I don't know honestly. I just know that some people on Discord voiced concerns regarding this. I think restricting things to be in their respective root (project or package) is definitely a good first step and is, in fact, what quite naturally arose from my package management implementation.

I removed `TYPST_ROOT` in my package management branch and instead have the default root always be the parent of the compiled file. Within a package, the root is different (and absolute paths, too, as a result). So the result is quite similar to what you said before with multiple roots. I plan to publish/merge this code today or tomorrow.

**Comment by SliceOfArdath** [comment]
i think so! thanks!

**Comment by laurmaedje** [comment]
Great, then I'm closing this!
