### ISSUE TITLE
Length to str conversion

### ISSUE THREAD

**Issue by SliceOfArdath** [typst/typst#1545]
### Description

Convert a length to a string.

I assume we'd convert the floating-point part as a regular float, and then add the trailing unit.

One could add the unit itself as a parameter to the str(..) call, to allow the user more control over their conversions.

### Use Case

logging positions of generated content (though dependent on RFC 5), and any kind of string manipulations on length.

**Comment by PgBiel** [comment]
> Yes that would work! Though the documentation says:
> 
> > This function is for debugging purposes. Its output should not be considered stable and may change at any time!
> 
> 
> 
> So I don't think the two of them (that is str(l) and repr(l)) fulfill quite the same needs?

Hm. I guess that's a valid point, so maybe str(length) should just return its current repr output.

**Comment by user202729** [comment]
If https://github.com/typst/typst/pull/790 were merged you can also do `l.cm()+"cm"` or something.

**Comment by laurmaedje** [comment]
#790 was merged.
