### ISSUE TITLE
Provide Apple Silicon binary

### ISSUE THREAD

**Issue by Allaman** [typst/typst#156]
Hi, thanks for this promising project!

I think, the title says it all. It would be cool to not depend on the build tools if you are running Apple Silicon

Thanks

**Comment by finnatsea** [comment]
+1 for this

**Comment by frewsxcv** [comment]
I am not a developer, but you could open a pull request to change these lines to include macOS ARM:

https://github.com/typst/typst/blob/045a109600fa9127d22259287bbde62234cadb44/.github/workflows/release.yml#L13-L25

**Comment by dei-layborer** [comment]
I wouldn't complain, of course, but the binary provided under "releases" works fine on a Silicon Mac.

**Comment by Allaman** [comment]
@dei-layborer thanks for the hint, you are right. Even more, the binary, despite its name, runs as kind "Apple" and not "Intel".  
Maybe, the naming of the release should reflect this?

**Comment by reknih** [comment]
![Terminal screenshot identifying the Typst binary as x86_64](https://user-images.githubusercontent.com/3874949/229882214-59c7086b-aa1d-4b25-957f-c59f9ef8b74b.png)

No, it's an Intel binary. The problem is that it's hard to obtain an ARM GitHub runner.

**Comment by Allaman** [comment]
You are absolutely right @reknih. I started typst from my path (compiled from source) and not the one from releases, leading to my false statement before 🤦

**Comment by laurmaedje** [comment]
Apple Silicon binaries have been available for a while thanks to https://github.com/typst/typst/pull/847
