### ISSUE TITLE
Unitless zero

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#1562]
### Description

When specifying a null [`length`], [`angle`], [`ratio`], [`relative length`] or [`fraction`], it would be great to be able not to specify the unit (`em`, `pt`, `deg`, `%`, `fr`, etc.), just like in CSS.

For example, the two following pieces of code would be equivalent:
```typst
#pad(rest: 1em, left: 0pt)[…]
```
```typst
#pad(rest: 1em, left: 0)[…]
```

### Use Case

Making—at least in my opinion—Typst code cleaner.

### Is it worth implementing?

I have to admit I am not convinced this feature is worth implementing given that it does not seem trivial to do, and it is far from fundamental to improve the user experience.  Also, it is somewhat rare to have to specify, e.g., a null length.

I think a way it could be achieved is by having `zero` be its own type, that can be used in place of a [`integer`], [`float`], [`length`], [`angle`], [`ratio`], [`relative length`] or [`fraction`].

If it is decided that this feature should be added, I would be willing to try and do it myself.

[`integer`]: https://typst.app/docs/reference/types/integer/
[`float`]: https://typst.app/docs/reference/types/float/
[`length`]: https://typst.app/docs/reference/types/length/
[`angle`]: https://typst.app/docs/reference/types/angle/
[`ratio`]: https://typst.app/docs/reference/types/ratio/
[`relative length`]: https://typst.app/docs/reference/types/relative-length/
[`fraction`]: https://typst.app/docs/reference/types/fraction/

**Comment by laurmaedje** [comment]
I'm not really convinced that this increases clarity. It slightly shortens the input syntax at the cost of more type system complexity. It could also lead to problems with properties that can be either number or length, with different meaning (e.g. `grid.columns`).

**Comment by MDLC01** [comment]
I'm closing this issue as not planned since it has not received any update for 2 months.

**Comment by AndreKR** [comment]
At the very least there should be an official recommendation which unit 0 should have. I'd very much prefer to allow 0 to not have a unit or have a separate keyword for it.

**Comment by MDLC01** [comment]
I think Typst represents lengths in points + ems internally. So `0pt` (or `0em`, or even `0pt + 0em`) is what you want for lengths.
But if your zero has a different dimension, of course you should use a different unit.

The problem with adding a keyword is that it would stay ambiguous because the compiler needs to know the dimension.
