### ISSUE TITLE
Missing syntax hightlighting for GraphQL

### ISSUE THREAD

**Issue by JuliusFreudenberger** [typst/typst#1563]
### Description

Since #771 there should be support for GraphQL syntax highlighting. There is a submodule for it in https://github.com/sharkdp/bat/tree/master/assets/syntaxes/02_Extra. However, the syntect binary is lacking GraphQL. I checked this using 
```bash
zlib-flate -uncompress < syntect.bin > syntect
grep GraphQL syntect
```
Therefore, GraphQL-Raw code is not highlighted. Julia, for which the syntax highlighting was also added in the same PR (see [this comment](https://github.com/typst/typst/pull/771#issuecomment-1546811612)), is present in the binary (grep reports `grep: syntect: binary file matches`) and also correctly highlighted.

Test document (just needs to include a raw block with graphql code:
```typst
#raw(lang: "graphql","
query hero {
  hero {
    name
    height
  }
}
")
```

Typst Version: typst 0.5.0 (3a8b9cce)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
Hmm, weird, I wonder if it was excluded on purpose or unintentionally. Maybe @lucifer1004 can shed some light on this?

**Comment by lucifer1004** [comment]
I'll look into it.

**Comment by lucifer1004** [comment]
Sorry, it was my fault. A few submodules were not correctly pulled when I built the `syntect.bin` file last time.

**Comment by JuliusFreudenberger** [comment]
Thanks for the quick fix! This is now working as I expected.

Perhaps a more automatic workflow could help here in the long run? Especially when new languages are added upstream.

**Comment by lucifer1004** [comment]
That is the ideal way, but the workflow can be somewhat dirty since we also need to exclude some syntaxes for the moment (see https://github.com/typst/typst/issues/1565#issuecomment-1605511340). Thus we need to check whether an excluded syntax becomes usable each time.
