### ISSUE TITLE
Add detailed YAML syntax error reporting

### ISSUE THREAD

**Issue by reknih** [typst/typst#1578]
### Description

Add more reporting (`93:expected comma`) to YAML parsing errors.

### Use Case

Right now, the error message makes fixing malformed YAML hard.

**Comment by laurmaedje** [comment]
The error nowadays is "Failed to parse YAML (did not find expected ',' or ']' at line 4 column 1, while parsing a flow sequence at line 3 column 5)", which is as good as it gets without https://github.com/typst/typst/issues/563
