### ISSUE TITLE
Inserted hyphen after opening parentheses

### ISSUE THREAD

**Issue by reknih** [typst/typst#1579]
### Description

From user feedback: I've put text inside brackets (just like this), and due to the justify setting, Typst aligned it like this:

```
lorem ipsum blabla text bla
other text blablabla blab (-
bracket content) blablabla
lorem ipsum blabla bla text
```

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by lolstork** [comment]
Recreation on latest Typst web app:

https://typst.app/project/rnjcKDAIfohdpt-RrchhpJ

Notably, the issue only occurs when there is no whitespace before the opening parentheses. It is very finicky and disappears with essentially any change in spacing.

**Comment by laurmaedje** [comment]
Duplicate of https://github.com/typst/typst/issues/1579
