### ISSUE TITLE
Subscript is too low for the fraction

### ISSUE THREAD

**Issue by awav** [typst/typst#1582]
### Description

The subscript adheres to a lower position adjacent to the parentheses surrounding fraction equations, compared to its placement in the LaTeX version. This causes it to hang too low.

Overleaf version:
<img width="235" alt="overleaf-eq" src="https://github.com/typst/typst/assets/24483645/102b2cd9-3643-4a67-bebf-370641e43851">

Typst version:
<img width="235" alt="typst-eq" src="https://github.com/typst/typst/assets/24483645/d2b29cc9-8ae6-4e08-a574-ab72c39ef6de">

### Reproduction URL

https://typst.app/project/rH4r93CN7_U_Lw6KbgFHGv

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
I do not believe the same font is being used in both pictures

**Comment by Enivex** [comment]
> Both fonts are "Times".

The parentheses are different.

Are you using LuaTeX/XeTeX and the unicode -math package?

**Comment by awav** [comment]
I used pdfLaTeX, here is a link to the overleaf https://www.overleaf.com/read/sskgsdhqvsbb. Here is how it looks with unicode-math and LuaLaTeX:

<img width="243" alt="overleaf-eq-unicode" src="https://github.com/typst/typst/assets/24483645/5da231c3-7533-439a-bdf3-c107ccb434a2">
