### ISSUE TITLE
Allow definition of structure for dictionary arguments to a function

### ISSUE THREAD

**Issue by Beiri22** [typst/typst#1583]
### Description

Take the [margin parameter of the page function](https://typst.app/docs/reference/layout/page/#parameters-margin). There is a specific structure / set of fields expected (top, bottom ...) but there is no code completion, because this structure might not be defined. Maybe there is something like an interface to specify the dict; or a way to define it inline, like:

```
#set mypage(margins: (top, bottom, left, right))
```

### Use Case

Provide code completion for structured dict parameters. Also check if parameters are valid.

**Comment by user202729** [comment]
related to https://github.com/typst/typst/issues/317

**Comment by laurmaedje** [comment]
Closing in favor of #317
