### ISSUE TITLE
Fractions with `dif` are misaligned

### ISSUE THREAD

**Issue by FeldrinH** [typst/typst#1585]
### Description

Fractions that use `dif` seem to have a blank space in front of the text, which makes the dividing line between the fractions look off-center.

For example
```typst
$ (dif y) / (dif x) $
```
renders like this (magenta lines added by me):
![image](https://github.com/typst/typst/assets/5256211/240e4b83-53a3-4527-b8d0-89ed0656ca8a)

### Reproduction URL

https://typst.app/project/rqMTrmSd__lEhKV80R3Lqm

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
This is not a bug. It's simply a case of dy being narrower than dx. You'll see the exact same behavior in LaTeX

**Comment by bluebear94** [comment]
I’ve dug into this and it seems to be caused by `frac` layout ignoring interaction rules in its components. `dif` is implemented as a thin horizontal space followed by a _d_, and this issue persists even if we call `with_weak(true)` on the space.

**Comment by laurmaedje** [comment]
It's not specifically `frac` that ignores it, but more than math mode in general ignores the `weak` property. :/
