### ISSUE TITLE
App should provide standard shortcuts for commenting

### ISSUE THREAD

**Issue by ynx0** [typst/typst#1587]
### Description

Currently, shortcuts for commenting are non-standard, at least on a US keyboard layout. Standard shortcuts are <kbd>CommandOrCtrl+/</kbd> and <kbd>CommandOrCtrl+Shift+/</kbd> for line and block comments.

### Use Case

Makes for smoother UX by tapping into existing muscle memory.

**Comment by laurmaedje** [comment]
`Cmd/Ctrl + /` for line comments now works. For block comments, the situation wasn't as clear cut and, in the end, I went for the platform-dependent shortcuts VS code uses: `Cmd+Alt+/` on macOS, `Shift+Alt+A` on Windows, and `Ctrl+Shift+A` on Linux.
