### ISSUE TITLE
Typst uses a lot of RAM, gets killed before document creation

### ISSUE THREAD

**Issue by ju6ge** [typst/typst#1591]
### Description

Hi,

I am running into an issue where `typst` can not complete building a document. The problem is that it quickly fills my 32GB of RAM and then gets killed by the kernel.

I have a lot of plots that I have generated and want to put into a report pdf. 

Any thoughts?

Kind regards,
Felix

### Typst version

- [x] I am using the latest version of Typst

**Comment by Dherse** [comment]
I will just comment on this: from experience, this is caused by having a `state` storing the results of a `query` or a function leading to exponential growth in memory usage.
