### ISSUE TITLE
Add ability to add list of specific fallback fonts (like LaTeX)

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#1596]
### Description

Maybe add `array` of `string` to `text(fallback: boolean)` ([docs](https://typst.app/docs/reference/text/text/#parameters-fallback)). This way you can either disable (`false`) fallback fonts, enable automatic font substitution (`true`), or define which fonts you prefer to be used instead of default (`("Noto Color Emoji", "Noto Sans CJK JP")`). I have this setup in LuaLaTeX:

```latex
\usepackage{luacode}
\begin{luacode*}
luaotfload.add_fallback("FallbackFonts", {
  "Noto Color Emoji:mode=harf",
  "Noto Sans CJK JP:"
})
\end{luacode*}
\usepackage{fontspec}
\setmainfont{Liberation Serif}[RawFeature={fallback=FallbackFonts}]
\setmonofont[Scale=0.9]{Fira Code}[RawFeature={fallback=FallbackFonts}] % 0.9 because Fira Code looks bigger than other fonts.
```

When I use bold for non default font characters, it doesn't work for some reason. So, to make bold CJK characters, I either have to make **them all** bold, or make it as default font.

If I Typst and write CJK chars, then it uses "AR PL UKai" (UKaiCN) insead of desired "Noto Sans CJK JP" and this also disables bold CJK chars (because it seems `AR PL UKai` doesn't support bold). If Typst were to use my selected fonts, then it also probably would be able to make CJK chars bold.

### Use Case

This feature provides essential document styling setting — selection of specific fonts to use. Some people probably have technical requirements to follow, without the feature this couldn't be done.

**Comment by Enivex** [comment]
You can already provide a list of fonts, which will fall back in the provided order

**Comment by Andrew15-5** [comment]
Right, I thought I saw something like this. I guess I forgot. Thank you for the answer.

https://typst.app/docs/reference/text/text/#parameters-font
