### ISSUE TITLE
package manager: smarter local search 

### ISSUE THREAD

**Issue by astrale-sharp** [typst/typst#1599]
### Description

`#import "@preview/eval_compute:0.0.1" : *`
`file not found, searched at @preview/eval_compute:0.0.1`

My file exists at eval_compute and it's version is 0.0.1, it would be ince if the manager could find it

### Typst version

- [X] I am using the latest version of Typst

**Comment by astrale-sharp** [comment]
Maybe I just messed something up I get 
```
error: file not found (searched at @local/eval_compute:0.0.1)
  ┌─ test.typ:2:8
  │
2 │ #import "@local/eval_compute:0.0.1" : *
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
while I have a package at ~.local/share/typst/packages/local/eval_compute-0.0.1

**Comment by laurmaedje** [comment]
the `file not found` error seems like it does not attempt to load it as a package at all, but just as a file. are you sure that you are using the latest compiler version from main?

**Comment by astrale-sharp** [comment]
I can't believe i made a mistake so silly, ofc you're right x)
