### ISSUE TITLE
Citation with multiple keys through reference markup

### ISSUE THREAD

**Issue by HPDell** [typst/typst#1606]
### Description

Currently, the reference syntax supports only a single key (as said in the comment of `CiteElem`). But the case with multiple citations in one place is quite common in academic writing. I was wondering whether it is possible to use the semicolon `;` to support multiple citation entries. 

The syntax looks like this: `@label1;label2`.

This syntax does not conflict with others because the semicolon marker is only used in the following modes:

- Math args (see line 460 in `parser.rs`)
- Code expressions (see lines 534 and 576 in `parser.rs`)
- Import items (see line 1094 in `parser.rs`)

To collaborate with #1139 , this syntax can be limited to normal cite mode. Because the proposed title, author and year mode citation usually happens alone. Even if several citations of these modes happens together, the users can take care by themselves, for example

```typst
In =@lewis50 and =@FosterGorr86, a fantasy novel ...

+@lewis50 and +@FosterGorr86 proposed a novel ...

In -@lewis50 and -@FosterGorr86, a fantasy novel ...
```

I think this feature will be extremely useful. 

### Use Case

Source code:

``` typst
The method of spatial adaptive filtering (SAF) 
has also been proposed to handle spatially varying 
relationships @FosterGorr-1986;GorrOlligs-1994.
```

Expected output:

The method of spatial adaptive filtering (SAF) has also been proposed to handle spatially varying relationships (Foster and Gorr 1986; Gorr and Olligschlaeger 1994).

**Comment by Enivex** [comment]
Why not just merge consecutive citations? I.e. make `@label1 @label2` equivalent to `cite("label1,"label1")`?

No need for introducing another symbol

**Comment by HPDell** [comment]
> Why not just merge consecutive citations? I.e. make `@label1 @label2` equivalent to `cite("label1,"label1")`?
> 
> No need for introducing another symbol
> 
> (Plus sometimes you do actually want to write a semicolon after a citation, which would require an escape character with your proposal.)

Hi,

Thanks for your reply. If `@label1 @label2` can be parsed to `cite("label1", "label1")`, it is no doubt a creative improvement. But is it a easy work to make this change?

By the way, if users want to write a semicolon after a citation, I think they can just append a space after the semicolon

```
@label1; some other text
```

If they really don't want the space, an escape character is another alternative choice.

**Comment by laurmaedje** [comment]
> Why not just merge consecutive citations?

I also considered that. Could be good. Is there a possibility that people do _not_ want to merge? How would we disambiguate then?

**Comment by Enivex** [comment]
> > Why not just merge consecutive citations?
> 
> I also considered that. Could be good. Is there a possibility that people do _not_ want to merge? How would we disambiguate then?

I can't really think of one, but maybe I lack imagination.

In the rare event you could always fall back to the plain cite("label1") cite("label2"). (Unless you want those to merge as well.)

**Comment by laurmaedje** [comment]
We could do it at the content level instead of the parser level and only merge citations. Then, however, `#cite("label1") #cite("label2")` would be merged too.

**Comment by HPDell** [comment]
> We could do it at the content level instead of the parser level and only merge citations. Then, however, `#cite("label1") #cite("label2")` would be merged too. @laurmaedje 

I'm afraid this is not what users want. If this is the case, I would prefer to use `;` to split labels, because the following two lines are equalevant

```
@label1;label2
#cite("label1", "label2")
``` 

That is, markers separated by `;` are mapped to the values of the variadic parameter. And can leave users to use `#cite()` to do more manual controls. 

Overall, I still persist in using `;` to implement multiple keys in reference.

**Comment by Enivex** [comment]
> > We could do it at the content level instead of the parser level and only merge citations. Then, however, `#cite("label1") #cite("label2")` would be merged too. @laurmaedje 
> 
> I'm afraid this is not what users want. If this is the case, I would prefer to use `;` to split labels, because the following two lines are equalevant
> 
> ```
> @label1;label2
> #cite("label1", "label2")
> ``` 
> 
> That is, markers separated by `;` are mapped to the values of the variadic parameter. And can leave users to use `#cite()` to do more manual controls. 
> 
> Overall, I still persist in using `;` to implement multiple keys in reference. 

I feel like this customization should be done as options to cite, not by forcing people to add semicolons . You likely want consistent behavior throughout your document. By always merging consecutive citations, typst can do automatic sorting for instance. Then it's up to you to choose to have it displayed as if they were separate citations in the end.

**Comment by HPDell** [comment]
> > > We could do it at the content level instead of the parser level and only merge citations. Then, however, `#cite("label1") #cite("label2")` would be merged too. @laurmaedje
> > 
> > 
> > I'm afraid this is not what users want. If this is the case, I would prefer to use `;` to split labels, because the following two lines are equalevant
> > ```
> > @label1;label2
> > #cite("label1", "label2")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That is, markers separated by `;` are mapped to the values of the variadic parameter. And can leave users to use `#cite()` to do more manual controls.
> > Overall, I still persist in using `;` to implement multiple keys in reference.
> 
> I feel like this customization should be done as options to cite, not by forcing people to add semicolons . You likely want consistent behavior throughout your document. By always merging consecutive citations, typst can do automatic sorting for instance. Then it's up to you to choose to have it displayed as if they were separate citations in the end.

I agree with you that consistent behaviour is really necessary and helpful. But please imagine the following case

```
#cite("label1") #cite("label2")
#cite("label1", "label2")
```

What's the difference between these two lines if Typst merges consecutive citations? I guess you definitely want the two lines to perform differently by using the two different forms, for example, to meet special and uncommon requirements. It would be a good idea to merge consecutive citations if the `#cite` function only supports a single label. However, if multiple labels are allowed, an "equivalent" mark is necessary. 

So what really matters is how to design a markup to allow multiple arguments for the syntax, rather than just deal with multiple citations. I mean, maybe in the feature, some other marks are designed to be translated into some functions, and the translated functions support a variadic parameter, the semicolon still can be used to declare values of that variadic parameter. 

Maybe the semicolon solution is not the best one. It doesn't matter what symbol is used here. I choose this one just because it is seldom used in Typst currently. But please do consider the equivalent mark for the variadic parameter.

**Comment by ModProg** [comment]
Wondering if it would be enough to differentiate by having a space between the labels or not, i.e. `@a@b` expands to `#cite("a", "b")`, while `@a @b` expands to `#cite("a") #cite("b")`.

This kind of white space sensitivity already exists in typst, e.g. for function calls:
```typ
#hide [hello]
#hide[hi]
```
expands to

> hello

**Comment by Enivex** [comment]
@a@b

This is very hard to read, especially with many references. I do not see a reason why it should be "easy" to get the wrong behavior. In almost all cases what the user wants is to nicely display merged citations.

**Comment by Fabioni** [comment]
is it possible to allow `#cite(@label1, @label2)`, this would enable smart completion and combining of multiple citations.

**Comment by HPDell** [comment]
> Wondering if it would be enough to differentiate by having a space between the labels or not, i.e. `@a@b` expands to `#cite("a", "b")`, while `@a @b` expands to `#cite("a") #cite("b")`.
> 
> This kind of white space sensitivity already exists in typst, e.g. for function calls:
> 
> ```typst
> #hide [hello]
> #hide[hi]
> ```
> 
> expands to
> 
> > hello

I suggest such ambiguity can be avoid by using the `()`. For example, 

```typst
(@a @b)  ->  #cite("a", "b")
@a @b -> #cite("a") #cite("b")
```

And in Typst, `()` is used to create an array. By writing `(@a @b)`, we can suppose the users want to create an array of citations. What the Typst needs to do is render such a citation array as a multi-key citation. And it also looks natural.

**Comment by Enivex** [comment]
() is used for both arrays and dictionaries, but only in code mode. In markup they're literal parentheses, which would make this problematic.

**Comment by HPDell** [comment]
> () is used for both arrays and dictionaries, but only in code mode. In markup they're literal parentheses, which would make this problematic.
> 
> I maintain that there's no real ambiguity here. There's no reason why merged citations couldn't be displayed identically to separate ones if that's what the user desires.

I agree now. It could cover 99% cases. I noticed that Typst is going to support CSL. I bet CSL could cover the other 1% cases.

**Comment by reknih** [comment]
Typst now merges adjacent cites automatically if the CSL style requires it.

**Comment by superlopuh** [comment]
What is the API for this? I couldn't find it in the docs of the cite function, and have no idea where to start for CSL styles.

**Comment by PgBiel** [comment]
Hey @superlopuh, just write two adjacent citations, as seen in the [cite docs example:](https://typst.app/docs/reference/model/cite/)

```typ
@abc @def 
```

If you need further help, feel free to ask in our [forum](https://forum.typst.app) or Discord (you can join via the [Typst website](https://typst.app))!
