### ISSUE TITLE
Display tables or figures across two columns when two column layout is set globally

### ISSUE THREAD

**Issue by abcvav** [typst/typst#1612]
### Description

Like this article does, place a table across two columns.
![image](https://github.com/typst/typst/assets/47599849/0fd80714-71db-4eb2-be84-a55e30fe4dcd)

### Use Case

Need to place a relatively wide table that cannot fit in a single column

**Comment by Enivex** [comment]
Duplicate of https://github.com/typst/typst/issues/553
