### ISSUE TITLE
Misaligned Matrix/Vector Brackets

### ISSUE THREAD

**Issue by ParadaCarleton** [typst/typst#1617]
### Description

The lack of alignment looks a bit weird to me:
![image](https://github.com/typst/typst/assets/71727937/15f21bb3-ee53-4d50-9a0a-1ff3852c8799)

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
If you want them to align I'd go with a 4x1 matrix instead of a vector. It's more cramped because it looks better in isolation.

**Comment by user202729** [comment]
it seems to make sense to "insert" a strut into each alignment cell like TeX does.

The problem is even more pronounced if there are more rows.

![image](https://github.com/typst/typst/assets/25191436/cc211ae2-f3e2-4e96-b3c6-b4cffad309ce)

**Comment by Enter-tainer** [comment]
```typ
$
mat(a,b;c,d)mat(x;y)=
x mat(a;c)+y mat(b;d)=
mat(a x+b y;c x+d y)
$
```

looks like this which doesn't look good
![image](https://github.com/typst/typst/assets/25521218/243bfe43-c210-41bf-9677-a0f778371ea9)

While latex looks like this:

$$ 
\begin{bmatrix} a & b \\\\ c & d \end{bmatrix}\begin{bmatrix} x \\\\ y \end{bmatrix} = x\begin{bmatrix} a \\\\ c \end{bmatrix} + y\begin{bmatrix} b \\\\ d \end{bmatrix} = \begin{bmatrix} ax + by \\\\ cx + dy \end{bmatrix}
 $$

**Comment by Enter-tainer** [comment]
There are 2 thing different:

1. it looks like there is a minimal height limit in latex: note the [a, c] is not that small in latex
2. typst stretches [ax + by, cx + dy] too high. In latex it's smaller

**Comment by Enter-tainer** [comment]
LaTeX set a minimal height for each matrix cell, it is the same as a invisible `(`

**Comment by Enter-tainer** [comment]
You may want to try https://typst.app/universe/package/natrix . It somehow "fix"es this bug. The root cause is that LaTeX will pad the height of each matrix cell to a certain minimal height and typst doesn't do it at this moment. I will also try fix this in rust.
