### ISSUE TITLE
Add support for European Portuguese variant

### ISSUE THREAD

**Issue by RuiL1904** [typst/typst#1618]
### Description

Portuguese is currently supported, but in its Brazilian variant. I think it's worth adding an European variant.
Some words are different between them. Some examples (Brazilian vs European):
- Sumário vs Índice
- Seção vs Secção

### Use Case

This would be a useful feature for those people who want to write in European Portuguese (mainly people living or born in Portugal).

**Comment by RuiL1904** [comment]
I can take care of this feature, if the team decides it can be implemented. I only need guidance regarding on how to name each variant.

**Comment by chicoferreira** [comment]
I've made a pull request https://github.com/typst/typst/pull/1619 that fixes this by setting the text region to `PT`, the `ISO 3166-1 alpha-2` code for Portugal.

```typst
#set text(lang: "pt", region: "PT")
```
