### ISSUE TITLE
Can rounded box be clipped accroding to it's actual shape?

### ISSUE THREAD

**Issue by PixelLantern** [typst/typst#1621]
### Description

  **_As we can set a box's radius, can we clip it's content accroding to it's actual shape?_**
using a scaled image with white background, we can simulate expected rounded-rectangle-shape clipping effect
<img width="817" alt="1" src="https://github.com/typst/typst/assets/83463735/75c4626d-512f-4af8-930e-f4cd127827b5">
<img width="1054" alt="2" src="https://github.com/typst/typst/assets/83463735/68d35d8a-0331-48b5-8085-702d8bd6d42c">

### Use Case

We can use this feature to create a image in rounded rectangle shape, just like the effect below
<img width="413" alt="3" src="https://github.com/typst/typst/assets/83463735/c5e75dd3-ad63-4173-b494-b024c0c1dcf1">

**Comment by laurmaedje** [comment]
It doesn't work at the moment, but you're totally right that it should.

**Comment by LaurenzV** [comment]
Related: #737

**Comment by virtualritz** [comment]
That would then also allow clipping of images with other shapes, ideally SVG or the like, at some stage, right?

At the moment, I just want to clip a picture against a circle, e.g.:

```typst
let photoBlock = circle(radius: 4cm, image("portrait.jpg"))
```

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/2338
