### ISSUE TITLE
Support absolute path with `image` function

### ISSUE THREAD

**Issue by FirelightFlagboy** [typst/typst#1625]
### Description

Typst version: `0.5.0 (3a8b9cce)`

I have the following input file

```typst
#figure([#image("/images/foobar.png")])
```

In the folder `/images` I have the file `foobar.png`

But when I run the following command in `/out` as the working dir (where the input file is located)

```shell
typst compile input.typ input.pdf
```

I got the error

```txt
error: file not found (searched at /out/images/foobar.png)
  ┌─ input.typ:1:16
  │
1 │ #figure([#image("/images/foobar.png")])
  │        
```

I'm expected `typst` to find the image under `/images`

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Path handling was reworked a bit since 0.5, would be interesting to see whether it works with  the `main` compiler.

**Comment by laurmaedje** [comment]
Your project root seems to be in `out`. You can configure that with `--root` (see https://github.com/typst/typst/issues/1664#issuecomment-1622395258). If it's still not working then, feel free to comment here / reopen the issue.
