### ISSUE TITLE
Allow writing to auxiliary files.

### ISSUE THREAD

**Issue by Beiri22** [typst/typst#1629]
### Description

I really want to switch from latex to typst. One of my latex templates outputs some metadata to a yaml file while compiling. As you support yaml-import and nested data structures, it might be a small step to allow an object to be exported to a yaml, csv, json, ... file.

What do you think?

### Use Case

You could output information to third party software.

**Comment by user202729** [comment]
see also https://github.com/typst/typst/issues/1056

**Comment by Beiri22** [comment]
@user202729 Writing to files seems only a side topic there. I've done some prototyping and implemented a write_yaml function and would be interested, what the maintainers / team members think of it... https://github.com/Beiri22/typst/tree/writeyaml

**Comment by laurmaedje** [comment]
I'm not in favor of supporting file system writing, see also my response here: #1536

**Comment by Beiri22** [comment]
Thank you for the link. For me it's a very specific case, where I output document metadata for the next processing step. My main goal was to transform typst values to yaml.

**Comment by laurmaedje** [comment]
For that a tracing system that you pipe into some file should work fine.

**Comment by Beiri22** [comment]
Might be, but a structured export of the metadata in form of YAML is way easier and less error prone with serde, than formatting it manually via tracing. As it's not a core function, I could live happily with the option to just write a plugin for that function, that i only use locally...

**Comment by laurmaedje** [comment]
YAML -> string conversion would definitely be a separate feature request from file writing and one I wouldn't be opposed to. There, we'd just need to figure out the best design to allow easy YAML loading from file, from string, and encoding to string.

**Comment by Beiri22** [comment]
That seems like a good first step to go, that does not interfere with any further decisions regarding the interoperability.

**Comment by laurmaedje** [comment]
Closing this as not planned. I created a new issue for debug output via `trace` or similar: https://github.com/typst/typst/issues/1669
