### ISSUE TITLE
Syntax Highlighting in Visual Studio Code

### ISSUE THREAD

**Issue by yolonir** [typst/typst#163]
Hey Typst team, amazing project, love it!
I wonder how can I use language highlighting presented in your tutorials in other editors? 
VSCode in this example

**Comment by CGMossa** [comment]
Currently, there are two pathways for this.

## Provided tools

See https://github.com/typst/typst/tree/main/tools/support
i.e. the `tools/support` folder in the repo.
To use this, you need to use Command palette and click this.
![image](https://user-images.githubusercontent.com/1063624/227037367-0168a8e0-9398-4dbe-9480-fc16695cf980.png)
Then navigate to the folder and select the `tools/support` folder.

This should yield a `Typst` extension (almost silently) and it looks like this:
![image](https://user-images.githubusercontent.com/1063624/227037656-c360e680-22f4-47e7-b8ef-fa5e7ff619b8.png)

You can find it under installed extensions.

This is what it does: 

![image](https://user-images.githubusercontent.com/1063624/227037558-6ebb0001-0ee2-46d8-8899-744c2c9655f6.png)

The *second* way will have to be in another post..

**Comment by CGMossa** [comment]
Another way, a community member has already started the churn and the overwhelmingly sought after work of providing an LSP for typst (plus vscode plugin), by mining typst-repo, and more. See here for it https://github.com/nvarner/typst-lsp

@nvarner I wish you good luck with it!

**Comment by osequi** [comment]
> This should yield a `Typst` extension (almost silently) and it looks like this: ![image](https://user-images.githubusercontent.com/1063624/227037656-c360e680-22f4-47e7-b8ef-fa5e7ff619b8.png)
> 

Tried both in VSCodium and VSCode but nothing happens. no extension shows up.

**Comment by osequi** [comment]
Ok, it works, the docs (https://github.com/typst/typst/issues/163#issuecomment-1480257515) were a bit unclear.

After  the step: "Then navigate to the folder and select the tools/support folder." nothing will happen, the extension will be silently installed, and the extension description tab won't pop-up, as the doc suggested to me.

Thanks :D

**Comment by gdalle** [comment]
Would it make sense to add these instructions to the official docs? I think the existence of this barebones VSCode plugin is a great argument to increase adoption

**Comment by CGMossa** [comment]
Someone is making a real plug in. I'd like to give them a chance to put it together and then make that the official recommendation.

**Comment by yolonir** [comment]
Nice! Thank you!

**Comment by CGMossa** [comment]
Please note that I'm in no way part of the team. I'm just giving my community member review. It helps other projects, but I could be both factually wrong, and my opinions may be opposite of the typst team.

**Comment by CGMossa** [comment]
With that said, I urge everyone that are interested, or may help out, to this https://github.com/nvarner/typst-lsp/discussions/15
