### ISSUE TITLE
Url are not handled the same way between the app and the generated pdf

### ISSUE THREAD

**Issue by FirelightFlagboy** [typst/typst#1630]
### Description

Hello,

I've the following document

```typst
#link("https://archive.softwareheritage.org/browse/origin/directory/?origin_url=https://github.com/Scille/parsec-cloud")[https://archive.softwareheritage.org/browse/origin/directory/?origin\_url\=https://github.com/Scille/parsec-cloud]
```

On the live render of the webapp the link behave correctly and direct me to <https://archive.softwareheritage.org/browse/origin/directory/?origin_url=https://github.com/Scille/parsec-cloud>

But on the generated PDF the link is broken into multiple part:

| Text part | Url |
| --- | --- | 
| `https://archive.softwareheritage.org/browse/origin/directory/?origin` | <https://archive.softwareheritage.org/browse/origin/directory/?origin> |
| `_url=` | <https://archive.softwareheritage.org/browse/origin/directory/?origin_url=https://github.com/Scille/parsec-cloud> |
| `https://github.com/Scille/parsec-cloud` | <https://github.com/Scille/parsec-cloud> |

### Reproduction URL

https://typst.app/project/pOVFVZcyhWlQ-mAnYnYGSi

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Strange. 

If you don't pass an explicit body to the link (instead using the automatic version) it works:
```
#link("https://archive.softwareheritage.org/browse/origin/directory/?origin_url=https://github.com/Scille/parsec-cloud")`
```

**Comment by laurmaedje** [comment]
Likely duplicate of https://github.com/typst/typst/issues/2587. If not, feel free to reopen.
