### ISSUE TITLE
Ability to handle raw svg strings with #image

### ISSUE THREAD

**Issue by taylorh140** [typst/typst#1638]
### Description

a way of feeding raw images into typst to be rendered. 
so to make things compatible (no breaks) you could introduce a type to the image function where the default is "path"

#image("./File.jpg")
but you could also say explicitly:
#image("./File.jpg",from:"path")

or you could use raw svg
#image("<svg ....>",from:"svg")

### Use Case

I can use svg generated from plugins and display it.

**Comment by laurmaedje** [comment]
Duplicate of #1084.
