### ISSUE TITLE
fully qualified names, at least for std

### ISSUE THREAD

**Issue by ModProg** [typst/typst#1639]
### Description

In rust and probably also other languages with relative imports, you can have fully qualified names, i.e.
```rs
::std::result::Result
```
That work even if someone were to define something named `std`.

While I'm not sure typst needs fqn, it should at least have a way to access functions from the std prelude in a way that cannot be overridden by someone defining a function named the same.

e.g. `std.figure` or `std.calc.abs`. The `std` name I'm not set on. To prevent overriding this we could make `std` a keyword/reserved name like `crate`, `super`, `self` in rust.

### Use Case

Have access to std methods even when someone, e.g., names a variable `numbering`.

**Comment by user202729** [comment]
remember that variables from one module are local to that module unless you explicitly import it. So if you name it like that it's your own problem (you can backup a `std_numbering` variable), and if someone else name it like that you can simply import only the names you need from that package.

**Comment by ModProg** [comment]
Yes, this only really comes into effect when using `*` imports, or if you create clashing names yourself or work together with others that do so.

Also, I think it would be enough to just have a `std` module containing everything in the prelude as well, because the "fully qualified" e.g., in Rust is only really needed in the context of macros, so very much not relevant here.

**Comment by PgBiel** [comment]
I was thinking that making it a keyword you can't override sounds more appropriate, and probably easier to implement (perhaps using `Scopes.base`?). Without that we'd have to either voluntarily define it on every `Scopes` (although that doesn't sound like the end of the world, but not sure if that could break anything), or define it on the `Library` itself (which is overall less reliable than just having the compiler guarantee `std` is always the standard library itself). I could take a shot at implementing this depending on the route we choose (I'm currently leaning towards keyword).

**Comment by emilyyyylime** [comment]
Not to mention accessing library functions in maths mode! (I just did)
