### ISSUE TITLE
Hexadecimal parsing is buggy with number suffixes

### ISSUE THREAD

**Issue by TomBinford** [typst/typst#1641]
### Description

Parsing numbers in `Lexer` with a `0x` prefix admits all alphanumeric characters, not just [0-9A-Fa-f]. This doesn't play well with number suffixes:
```
#box(stroke: 0x10pt, [b #sym.zws])
```
errors with 
```
error: invalid hexadecimal number: 0x10pt
  ┌─ ..\test.typ:1:13
  │
1 │ #box(stroke: 0x10pt, [b #sym.zws])
  │              ^^^^^^
```
Fixing this for `pt` is easy, but we should also think about `cm` and `deg` et al. that start with valid hex characters.

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by user202729** [comment]
what should the expected behavior be? I don't think it's reasonable to parse it as 16pt -- not that anyone would need such a feature, I think. Although if you really want you can write `0x10 * 1pt`.

**Comment by laurmaedje** [comment]
Number suffixes aren't supported for hexadecimal numbers. It's intentional that it allows everything alphanumeric because it arguably creates a better error message than stopping at the >f letter and leaving whatever comes after as a mess to the lexer that generates more errors.
