### ISSUE TITLE
regex with unicode section names inside typst not worked well.

### ISSUE THREAD

**Issue by Yoxem** [typst/typst#1644]
### Description

Because according to w3c's standard, between the CJK characters and non-CJK characters, there should be a spacing. So I have made a "dirty" spacing-adding function to Typst. (I hope that feature can be add in Typst.)

the pseudo code for regex is [CJKV Char, Hangul, Kanas, Bopomofo] + [chars excluding punctuation, CJKV Char, Hangul, Kanas, Bopomofo] triggers spacing adding.

However, the boundary in red circles have no spacing. Is it a bug?

the ![generated pdf](https://github.com/typst/typst/files/11929338/cjk.pdf) and its screenshot:

![image](https://github.com/typst/typst/assets/184107/c1796096-15e5-47e2-bb35-4381209965f7)

code

```
#set text(
    font : "Noto Sans CJK TC",
    size : 14pt,
)

#let CJKNonCJKSpacing = 0.2em

#show regex("[\p{Han}\p{Hiragana}\p{Katakana}\p{Hangul}\p{Bopomofo}\p{Punctuation}][^\p{Han}\p{Hiragana}\p{Katakana}\p{Hangul}\p{Bopomofo}\p{Punctuation}]") : it => {
    text[#it.text.first()#box(width: CJKNonCJKSpacing,"")#it.text.last()]
}

#show regex("[^\p{Han}\p{Hiragana}\p{Katakana}\p{Hangul}\p{Bopomofo}\p{Punctuation}][\p{Han}\p{Hiragana}\p{Katakana}\p{Hangul}\p{Bopomofo}\p{Punctuation}]") : it => {
    text[#it.text.first()#box(width: CJKNonCJKSpacing,"")#it.text.last()]
}

tests of cjk spacing with font "Noto Sans CJK TC"

Taiwanese (Hokkien) : 「我kah意Typst這ê排版系統，誠趣味。」

Trad. Mandarin: 晶晶體是一種English和Chinese混用的語言使用style。

Simp. Mandarin: 抗议者举着Friedman公式的a4白纸。

Japanese: 「私はLinux Mintが好きです。」「でもArch Linuxはよくないか？」

Korean: 1839년에, 쿠바에서 20마일 떨어진 곳에서 53명의 흑인 노예들이 라 아미스타드 노예선을 장악하다.

```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
I think it doesn't work for cases where there is just a single CJK glyph because then one rule prevents the other one from matching through its transformation.

**Comment by laurmaedje** [comment]
The regex engine will probably not change. It's the main Rust regex engine and PCRE is a C library.
