### ISSUE TITLE
MDPI Template

### ISSUE THREAD

**Issue by flavio20002** [typst/typst#1646]
### Description

If i visit the website https://typst.app/ it seems that an MDI template with sidenotes is available (https://typst.app/assets/images/mdpi-large.png) , but in the web app is not shown. The dept-news templtes it's similar, but the articles are positioned without sync with the text in the main column.
Can you help me to create such a template, with sidenote? Similar to Kaobook (https://github.com/fmarotta/kaobook) or Tufte Latex (https://www.ctan.org/pkg/tufte-latex).
Thanks in advance

### Use Case

Write a book with a two columns style (one for the main text, one for figures, sidenotes, etc.)

**Comment by fredguth** [comment]
Hey @flavio20002 I am interested in building a Tufte-asque template with Typst.  Right now I am trying to figure out how to put references in the margin. You can ping me here or at Typst discord.

**Comment by flavio20002** [comment]
Hi, sure. I can create a question on Discord and we can speak about it there. I will tag you.

**Comment by sfermigier** [comment]
Indeed, it would be great if the two templates that are "advertised" on the home page (MDPI and Oxford) could be made available, as they are (IMHO) better looking that IEEE and AMS.

**Comment by laurmaedje** [comment]
- @JamesxX has ported some of the templates, including the MDPI and [submitted them to Typst Universe](https://github.com/typst/packages/pull/806) (merge still pending).

- Moreover, with the success of Typst Universe, we don't currently have plains to provide more first-party templates and will likely remove these specific template illustrations when we update the home page (which we _want_ to do soon, we'll see ...), so I'll close this.
