### ISSUE TITLE
Missing equation numbering hint is outdated when labelling and referencing equations

### ISSUE THREAD

**Issue by thygesteffensen** [typst/typst#1654]
### Description

When the numbering for an equation is not set, the error hint is:
![image](https://github.com/typst/typst/assets/31892312/fe4f2f7b-ad19-4beb-8c7c-0a6cc9f0c7a7)

However, shouldn't it be: `#set math.equation(numbering: "1.")` since:
![image](https://github.com/typst/typst/assets/31892312/22bf4d07-1469-4594-a3e7-346d79a67d06)

A side note: the rendering of inline code does not seem to work, and copying from the hint is difficult to do before the popup disappears :) 

### Browsers

Microsoft Edge

### OS

Windows

**Comment by tingerrr** [comment]
Fixed by #2012.

**Comment by laurmaedje** [comment]
The inline code rendering should also be fixed.
