### ISSUE TITLE
Share dialog "revoke link" broken in some case

### ISSUE THREAD

**Issue by Heinenen** [typst/typst#1656]
### Description

Setup: 
* Open a project
* Press on "Share" button in upper right corner
* Create both a read-only and a read-write link
* Revoke both

Both links remain active, despite the message "Share linked revoked" and the link-field going back to it's original content ("Create read-only link" instead of the actual link).

Closing and reopening the share-dialog doesn't change the visuals of the dialog.
Closing and reopening the project and the share-dialog makes both links reappear.

I could reproduce the error in a second project.

In a third project, when only creating a read-only link and revoking it worked as expected.

### Browsers

Firefox

### OS

Linux

**Comment by laurmaedje** [comment]
Fixed.
