### ISSUE TITLE
Colorbar from matplotlib rendered incorrectly from svg

### ISSUE THREAD

**Issue by fredboy18400** [typst/typst#1659]
### Description

I created a figure in matplotlib using a colorbar.
If I use a rendered png, typst fills the colorbar correctly – using an svg the colorbar is empty.
The plot is created using this part of a code:
```
fig, ax = plt.subplots(1, 1, figsize=(6, 5))
tri = plt.tricontourf(x, y, E, levels=100, cmap='viridis')
ax.tricontour(x, y, E, levels=5, colors='w', linewidths=0.5)
E_ticks = np.linspace(200000, 700000, 6)
cbar = fig.colorbar(tri, ax=ax, ticks = E_ticks)
```

### Reproduction URL

https://typst.app/project/rxLP6YY0iUbfaJJQKuOQbB

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
Will be fixed once [this PR](https://github.com/typst/svg2pdf/pull/34) gets merged and upstreamed.
