### ISSUE TITLE
Function array to args

### ISSUE THREAD

**Issue by pauladam94** [typst/typst#1660]
### Description

The `pos` function is very useful for the `Args` type. It permits to have an array to handle.
It will be very powerful and useful to have a function that does the opposite.
Function the converts an array into an args.

The other possibility, to resolve this issue, is to permit to pass array instead of Args type in every function.

### Use Case

I suppose in this example that we have the `to_args` function that have this signature `to_args(Array) -> Args`
```
// We get n title into a array (we don't know how many there is)
#let a = ("first-title", "second-title", "third-title", )

// We want to make a list out of them
#list(a.to_args())
```

For this use case, i redo my self the list function to layout the element of the array.

**Comment by Dherse** [comment]
Isn't that just doing `#list(..a)`?

**Comment by laurmaedje** [comment]
I've added it to the syntax reference and improved the arguments documentation a bit: https://github.com/typst/typst/commit/8bf0bb5da9fc5b849ebe870037d59d52f88aea47

(Note that the updated docs will only be deployed with the next release)
