### ISSUE TITLE
Linebreaking fails with some characters

### ISSUE THREAD

**Issue by gfpj** [typst/typst#1661]
### Description

The following examples are simple to break because there is always a space between the characters.
Unfortunately, only some of the examples work as expected and with others the linebreaking fails completely, resulting in one line that goes until paperwidth.

```typst
#set text(lang: "en")
#set par(justify: true)

#{
	for _ in range(1000) {
		//"a " // linebreaking works!
		//"0 " // linebreaking works!
		//"- " // linebreaking works!
		//"€ " // linebreaking works!
		//"= " // linebreaking works!
		//"% " // linebreaking works!
		//"! a " // linebreaking works!
		
		//"? " // linebreaking does NOT work!
		//". " // linebreaking does NOT work!
		//"— " // linebreaking does NOT work!
		//": " // linebreaking does NOT work!
		"! " // linebreaking does NOT work!
	}
}
```

Not sure if there is a real use cases for this but I have found this when looking for another ~~bug~~, ~~where the start of the next line is indented using a space, which was considered to be fixed but still happens for some characters.~~
Edit: this was because the whitespace came from a string, like `"  "`, and whitespace is [not trimmed](https://github.com/typst/typst/issues/1387) in strings.

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Probably, line breaks are not allowed between these symbols by Unicode and the problem is just that Typst never hard-wraps if there is no allowed line break for over the length of the line. Similar issues occur with URLs and very long words in small table cells.

**Comment by laurmaedje** [comment]
Related: https://github.com/typst/typst/issues/674

**Comment by gfpj** [comment]
Just found a workaround:

```typst
#set text(lang: "en")
#set par(justify: true)

#{
	for _ in range(1000) {
		"! " + str(sym.zws) // linebreaking does work now!
	}
}
```
