### ISSUE TITLE
Access denied when importing files from a parent directory, even if `typst` is executed from that directory

### ISSUE THREAD

**Issue by SkiFire13** [typst/typst#1664]
### Description

I'm developing a library for `typst` and would like to keep a bunch of examples in a `examples`  subfolder, which I also use for quick and dirty testing. The directory structure is roughly like this:

```
- lib.typ
- examples/
  - example.typ
```

For reproducing the issue it's enough for `examples/example.typ` to contain the line `#import "../lib.typ": *`

This didn't happen with typst v0.5.0

I can see why this may be a privacy issue if I compile `example.typ` from inside `examples`, but the problem arises even I compile from the root directory containing `lib.typ`.

Unfortunately I would prefer to both keep the `lib.typ` in the root (for quick access when e.g. importing it through a git submodule) and the examples in their own directory (to not clutter the root with `.typ` files other than the library itself)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This is working as intended as the root defaults to being right next to the compiled file. You can change that by passing `--root .` if you are in the parent directory. Then absolute paths in Typst files are relative to the parent directory and `../` is allowed. (Everything within the `--root` is ok, everything else isn't for security.)

**Comment by SkiFire13** [comment]
Thanks, somehow I missed the `--root` parameter and was expecting the root to always be `.`

**Comment by DUOLabs333** [comment]
I tried this, but I couldn't get it to work: if `header.typ` is in `..`, I can't access anything in `../header.typ` even with `typst compile --root .`.

**Comment by laurmaedje** [comment]
I'm not sure about typst-lap (it is unofficial), but it is not really maintained anyway. For local setups I would recommend switching to [tinymist](https://github.com/Myriad-Dreamin/tinymist).

**Comment by DUOLabs333** [comment]
Thanks for the suggestion! Switching to `tinymist` and specifying `root_dir` works perfectly.
