### ISSUE TITLE
Support for (web) font embeds

### ISSUE THREAD

**Issue by dei-layborer** [typst/typst#1671]
### Description

It would be cool if the web app, at least (don't know how hard this'd be for the offline compiler) could support CSS-based font embeds.  The most common example of course is Google Fonts, but that's not the only option (coollabs.io has a mirror of Google Fonts, for example).  It's a common enough resource, while hopefully minimizing the overhead for the web app itself; at the least, you wouldn't have to store local copies.

Maybe a package could do it?  I'm not remotely familiar enough with Rust to implement such a thing, and I of course don't know if external packages are allowed to make external requests like that.

### Use Case

Some way to select from Google Fonts versus the catalogue currently available.  There are probably multiple ways this could work, whether something based on the existing ``import`` framework or a totally new function.

**Comment by laurmaedje** [comment]
In case you are not aware, you can upload fonts into your project to use them (just through their name like built-in fonts).

**Comment by dei-layborer** [comment]
That's good to know, thanks!  I think remote embeds _could_ still be worthwhile (if for no other reason than saving the user a step or two), but definitely understand it's a low priority :)

Out of curiosity, does the package framework allow for pulling in external content like that in the web app?

**Comment by laurmaedje** [comment]
No, the document and the packages can't pull external resources by design. That would be a security risk and a reproducibility problem.

**Comment by dei-layborer** [comment]
Yeah, definitely don't blame y'all for that one.  Anyway, just something to think about (or not :) ).

**Comment by laurmaedje** [comment]
I'm going to close this then. I understand the motivation, but the complications and risks of loading external resources are too large in my opinion. With font upload, there is a good alternative.
