### ISSUE TITLE
The certificate for https://typst.app/ appears expired

### ISSUE THREAD

**Issue by Easyoakland** [typst/typst#1673]
### Description

https://typst.app/ gives a certificate which expires Thu, 06 Jul 2023 23:59:59 GMT when visited. That appears to be > 2 hours ago.

### Reproduction URL

https://typst.app/

### Browsers

Firefox, Chrome, Microsoft Edge

**Comment by laurmaedje** [comment]
We're sorry about the downtime, it's back up. We've identified the cause so that it won't happen again.
