### ISSUE TITLE
Document the `#[` syntax

### ISSUE THREAD

**Issue by Easyoakland** [typst/typst#1674]
### Description

I found that the magic incantation of `#[ /*scoped set rules*/ ]` works but the only place I could find any information about this syntax after grepping all markdown in the repo is [here](https://typst.app/docs/reference/styling/). In that location it doesn't explain what `#[` means. Somewhere in the docs there should be an explanation for that syntax. It looks like it is called a "block" which I guess is different from a "content block" (`[ /* content */ ]`) or "code block" (`{ /* content */ }`) (which are explained)?

### Use Case

Anyone who wants to scope set rules will have to similarly guess what this syntax means until the docs are updated.

**Comment by laurmaedje** [comment]
It's just a normal content block. Any kind of expression can come after `#`, a literal (`#1` or `#true`), a block (`#{1+2}` or `#[*Markup*]`), a function call etc. Content as well as code blocks scope set and show rules.

But I agree that the documentation on this could be improved.

**Comment by Easyoakland** [comment]
Then what does the `#` symbol mean in this context? As I understand it, `#` means there is code without requiring writing a code block. This doesn't seem to follow that meaning.

**Comment by user202729** [comment]
If you write `text [ other text ] more text`, then the `[` and `]` are interpreted as **text** thus literal brackets are typesetted.

If you write `text #[ other text ]`, the `[` and `]` are interpreted as **code**, which creates a block. the part inside `[...]` are again interpreted as text.

You can also write `text #{ let a=[other text] ; a } more text`.

**Comment by lynn** [comment]
How I think about it is: the parser has a "text mode" and a "code mode".

For example in text mode = means "header" but in code mode it means "assignment", and so on.

In text mode, `#` means "enter code mode for the following expression, and add its result to the text".

In code mode, `[abc]` means "parse `abc` in text mode and evaluate it into a `content` value".

**Comment by user202729** [comment]
indeed, https://typst.app/docs/reference/syntax/ already (correctly) calls them "markup" and "code mode" respectively.

**Comment by laurmaedje** [comment]
A [relevant section](https://typst.app/docs/reference/syntax/#modes) has been added to the docs a while ago.
