### ISSUE TITLE
Can't import packages through proxy?

### ISSUE THREAD

**Issue by HROMANO** [typst/typst#1678]
### Description

I am behind a proxy at work and when I try to import some package in a typist file like:

```
#import "@preview/acrostiche:0.0.1": *
```

I get:

```
error: failed to load package (network failed)
  ┌─ \essai.typ:5:8
  │
5 │ #import "@preview/acrostiche:0.0.1": *
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

(I tried with different packages).

Env variables `http_proxy` and `https_proxy` are correctly set (`pip` for python is working for example).

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by reknih** [comment]
As I see it, `ureq` (the crate we use for HTTP requests in the CLI) does not automatically check these environment variables. We'll have to manually do that and create a Proxy if necessary.

**Comment by Dherse** [comment]
I second this, I am working on a containerized, decently safe, benchmarking system for typst that uses a proxy to be (somewhat) secure, and this is breaking it :(

**Comment by 123marvin123** [comment]
Any update on this issue? I believe this is a major problem when using typst behind a corporate proxy.

**Comment by zicklag** [comment]
I'm not sure how to set it up with `ureq`, but `reqwest` support the proxy out of the box, which is useful. It's a bigger package, though, which I'm assuming is why you're using `ureq`.

**Comment by laurmaedje** [comment]
Yeah reqwest is heavier and pulls in an async runtime. I looked a bit for ureq and there is a configurable interface for proxies, but I wasn't able to figure out so far how you set it up to pull the proxy information from the environment.

**Comment by zicklag** [comment]
I'll take a look at it real quick. I've done a couple proxy PRs for different projects before. I also have the need to trust a custom CA certificate, so I'll try to include that, too if you're open to it.

I think reading a `TYPST_CERT` environment variable is probably appropriate for the cert, similar to the `DENO_CERT` environment variable used by deno.

**Comment by laurmaedje** [comment]
Sounds good, a PR would be appreciated! If Deno does it that way, I guess we can too. Could you link to some relevant explanation/discussion/PR for Deno? That would be helpful.

**Comment by zicklag** [comment]
Here's a PR! https://github.com/typst/typst/pull/2006

In order to make sure the certificate setting was visible in the CLI, I made it an optional CLI argument that can also be set with an environment variable.

As for Deno, here's the discussion: https://github.com/denoland/deno/issues/6355.

**Comment by laurmaedje** [comment]
Should be fixed by https://github.com/typst/typst/pull/2006
