### ISSUE TITLE
Problems with overlapping integral subscripts

### ISSUE THREAD

**Issue by ts-26a** [typst/typst#1685]
### Description

# Code

```
$integral_0^1$\
$integral_0^1$
```

# Typst
![image](https://github.com/typst/typst/assets/65473848/8b88a495-44d9-4c92-bc64-1d5c58d1e9ae)

# Latex
![image](https://github.com/typst/typst/assets/65473848/4f570b7b-a91e-4665-9329-54648c3f3a7a)

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Duplicate of https://github.com/typst/typst/issues/1028

**Comment by laurmaedje** [comment]
The problem is with inline equations. They do not respect paragraph leading enough (part of it is intentional to get even line spacing, but it's too much in some cases). For block equations it's fine:
```
$ integral_0^1 $
$ integral_0^1 $
```
