### ISSUE TITLE
Ability to manipulate arbitrary typst markup code from the current document

### ISSUE THREAD

**Issue by neunenak** [typst/typst#1686]
### Description

I would like there to be a way to specify that a given chunk of typst markup code from the current document should be rendered verbatim as code text, while still functioning exactly the same way as it normally would at its current location in the document. I'm not sure exactly what this should look like. Some thoughts:

* a specific function that takes arbitrary markup as input, and sets that text to a variable, but otherwise acts as a no-op as far as the markup it surrounds is concerned
* improvements to the `eval` function that make it possible to be aware of variables currently in scope, variables sourced from packages or other files, etc.

### Use Case

This feature strikes me as useful for the niche-but-real use case of typesetting documents that themselves talk about typst as a system, or document a given typst package. For example, in my leipzig-gloss package, I have the following documentation:

(from https://code.everydayimshuflin.com/greg/typst-lepizig-glossing/src/branch/master/leipzig-gloss-examples.typ#L62-L86 )

    As a first example, here is a gloss of a text in Georgian, along with the Typst code used to generate it:

    #gloss(
        header_text: [from "Georgian and the Unaccusative Hypothesis", Alice Harris, 1982],
        source_text: ([ბავშვ-ი], [ატირდა]),
        transliteration: ([bavšv-i], [aṭirda]),
        morphemes: ([child-#smallcaps[nom]], [3S/cry/#smallcaps[incho]/II]),
        translation: [The child burst out crying],
    )

    #codeblock[
    ```typst
    #gloss(
        header_text: [from "Georgian and the Unaccusative Hypothesis", Alice Harris, 1982],
        source_text: ([ბავშვ-ი], [ატირდა]),
        transliteration: ([bavšv-i], [aṭirda]),
        morphemes: ([child-#smallcaps[nom]], [3S/cry/#smallcaps[incho]/II]),
        translation: [The child burst out crying],
    )
    ```
    ]

Note that I need to write the same markup twice - once when I use it to emit output, and once so that it shows up in a syntax-highlighted code block. It's easy for this duplicate markup to get out of sync when I change something. I cannot use the `eval` function because I'm importing the `gloss` function from another `.typ` file and that doesn't work with `eval` as currently constructed.

**Comment by lynn** [comment]
To me it sounds like the best approach is to fix `eval`. I can't really imagine an API for this otherwise.

**Comment by user202729** [comment]
as a "workaround" for the `eval` problem (that it doesn't take the current context into consideration) maybe fix with `#let demo(x) = {eval('#import gloss;' + x.text) ; codeblock(x.text)}` then `demo(``` ... ```)` or something.

Fixing `eval` would make `eval` implicitly dependent on the current context, thus not pure. Some thoughts are needed (e.g. Python's `eval` implicitly takes current context into account, but also allow passing explicit dictionary of context. Maybe we can allow the latter mode here?)

**Comment by neunenak** [comment]
Trying to perform an import in `eval`'d code doesn't work:

```
typst compile leipzig-gloss-examples.typ
error: cannot access file system from here
   ┌─ /leipzig-gloss-examples.typ:42:9
   │
42 │     eval("import \"leipzig-gloss.typ\": gloss; " + x.text)
   │          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by laurmaedje** [comment]
One problem with given access to the scope is that it's not clear which scope. In your example, you want to write an abstraction to show some code and eval it, but then, even if we supported access to the context, `eval` would have the context of your abstraction function, not of `gloss`'s callsite.

**Comment by user202729** [comment]
Indeed, Python has some complicated rules for "`eval`-wrapper functions". (`sys._getframe(i)`)

**Comment by neunenak** [comment]
> One problem with given access to the scope is that it's not clear which scope. In your example, you want to write an abstraction to show some code and eval it, but then, even if we supported access to the context, `eval` would have the context of your abstraction function, not of `gloss`'s callsite.

This makes me think that trying to solve this problem by changing how `eval` works is the wrong solution; I don't really want to eval anything, what I want is for a typst document to be able to access part of its own source code as a string.

**Comment by user202729** [comment]
https://github.com/typst/typst/issues/298

Theoretically:

```
#let gloss(x) = {
  x;
  codeblock(read(x.sourcefile)[x.firstline:x.lastline])  // or: codeblock(x.sourcecode);
}

#gloss[
  content...
]
```

Good idea? Not sure. But this one is rather unlikely to break anything.

Dynamically-constructed content blocks remains a bit of a challenge though.

**Comment by laurmaedje** [comment]
> How about eval(code, scope: (gloss: gloss))?

That's something I've considered and I like it in principle.

**Comment by laurmaedje** [comment]
With the `scope` argument now available, I think we can close this.
