### ISSUE TITLE
Incremental Build Support

### ISSUE THREAD

**Issue by sirinath** [typst/typst#1687]
### Description

Can the compiler be made to have incremental build support please.

As the input is edited the output keeps changing accordingly.

### Use Case

This will help improve live preview features in the future.

**Comment by PgBiel** [comment]
This is already supported; see the code for `typst watch` for inspiration (https://github.com/typst/typst/blob/main/crates/typst-cli/src/watch.rs).

**Comment by reknih** [comment]
This feature is already supported
