### ISSUE TITLE
set + where rules

### ISSUE THREAD

**Issue by ModProg** [typst/typst#1688]
### Description

Allow specifying a `.where` on `set` calls.

E.g.
```typc
set heading(supplement: [Chapter]).where(level: 1)
```

This obviously needs some recursion protection, e.g. one should maybe not be able to set the value one is matching on:
```typc
set heading(level: 2).where(level: 1) // could be allowed
set heading(level: 1).where(level: 1) // dosn't make sense
```

But this could also be caused by a multistep circly:

```typc
set heading(numbering: "1", supplement: [A]).where(level: 1)
set heading(level: 1, supplement: [B]).where(numbering: "1")
```

### Use Case

Being able to set e.g. level specific supplements without needing to use a closure

**Comment by laurmaedje** [comment]
The intended way is `show heading.where(level: 1): set heading(supplement: [Chapter])`. This is unfortunately a bit buggy though at the moment: https://github.com/typst/typst/issues/2459.
