### ISSUE TITLE
Inaccurate documentation on table's stroke property

### ISSUE THREAD

**Issue by OctarineSourcerer** [typst/typst#169]
In the [documentation for table](https://typst.app/docs/reference/layout/table), it claims the `stroke` property can be one of:
- none
- length
- color
- stroke

However, trying to provide a stroke as detailed in [Rectangle's documentation](https://typst.app/docs/reference/visualize/rect/#parameters--stroke) (which is where the "stroke" button links to) with the following code:
```
table(
    columns: 3,
    [], [two], [three],
    [uno], [dos], [tres],
    stroke: (top: 2pt + red, rest: none))
```
results in the following error:
![image](https://user-images.githubusercontent.com/6842867/227024844-dd1853b5-dcbe-4198-97e7-7ef346fb933a.png)

Is it the case that the table function cannot take a full stroke as its `stroke` property? If so, the documentation shouldn't have `stroke` as one of the types it can take.

**Comment by tv42** [comment]
I ended up triggering this trying to make Tufte-style tables (e.g. https://simplexct.com/data-ink-ratio-tables).

Though even with passing a dict to stroke, I don't see a great way to control the lines drawn; the stroke applies to all cells, and I want to make exceptions. I haven't found anything letting me easily control stroke e.g. by row, just for header row, or so on. And trying to construct that myself would mean reimplementing the column alignment logic that `table` does?

**Comment by tv42** [comment]
For Tufte-style tables, I think all that would be needed would be for stroke to be able to be a function just like fill and align can be. It'd be even better if the function also could access the number of rows & columns, so one could handle a "summary row" at end specially.

**Comment by waynr** [comment]
For individual cell or row strokes i use a rectangle wrapping the cell or row with `inset` and `outset` set to `0pt`, as in the example in this comment: https://github.com/typst/typst/issues/131#issuecomment-1479547933

**Comment by OctarineSourcerer** [comment]
I agree that making Tufte-style tables would be brilliant, and that stroke would need to be more powerful to achieve this. But it's also not quite this issue, which is rather tight in scope.

So I've made an issue here! https://github.com/typst/typst/issues/226
Anyone who's versed in making Tufte tables, please go here and put in your thoughts; I've not written a complete spec at all as I don't have a copy of Tufte's works.

**Comment by laurmaedje** [comment]
There is a `table-strokes` branch, but I didn't get it done in time for the beta launch.

**Comment by cds-internationalist** [comment]
I'm coming up against this issue as well - it looks like the error message has changed a little, but the documentation is still unclear/inaccurate.

Table is able to accept _one_ type of stroke dictionary, but not as documented rectangle (where the stroke tag links). In particular, the color property cannot be described using "color" as per the stroke property in the rectangle function but must be described using "paint" as per the the stroke property in the _line_ function.

Table will still not accept a dictionary describing the stroke for each side of a _rectangle_. It seems like there are competing definitions for "stroke" here that may need to be clarified?

**Comment by laurmaedje** [comment]
The "color" thing is a docs issue, it was globally renamed to "paint" because it could also be something like a pattern in the future.
