### ISSUE TITLE
Spaces in dictionary parse as the non-erroneous errors

### ISSUE THREAD

**Issue by jeffa5** [typst/typst#1690]
### Description

Trying to parse the below input with the Typst Rust library (from main: 0e8492eac1606edba86748c4de547a2c758cd232)

```
#((d: 2 ,))
```

produces the following AST:

```
Markup: 11 [
    Hashtag: "#",
    Parenthesized: 10 [
        LeftParen: "(",
        Dict: 8 [
            LeftParen: "(",
            Named: 4 [
                Ident: "d",
                Colon: ":",
                Space: " ",
                Int: "2",
            ],
            Error: " " (expected named or keyed pair, found space),
            Comma: ",",
            RightParen: ")",
        ],
        RightParen: ")",
    ],
]
```

and calling `.erroneous()` on the node returned from `parse()` returns false (no error in the node).

A couple of questions:
1. Should the parsing be more tolerant of the space in this position?
2. If it is an error, why is the `.erroneous()` call not returning true?

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by bluebear94** [comment]
I think the error node is coming from `validate_dict`, which doesn’t ignore space tokens.

**Comment by jeffa5** [comment]
I believe this is fixed now
