### ISSUE TITLE
ACM conference template

### ISSUE THREAD

**Issue by wangjq4214** [typst/typst#1698]
### Description

Is it possible to add an **ACM** conference template?

I want to use **typest** instead of **overleaf** for ACM conference submissions.

### Use Case

Add an **ACM** conference template.

**Comment by femtomc** [comment]
I wish I could somehow put a bounty on this via GitHub.

**Comment by krusche** [comment]
Would be awesome. The existing IEEE template is quite simple and does not include the typical aspects that are needed for conferences.

**Comment by benjaminfjones** [comment]
I’m not the author of the ACM template below, but wanted to point it out in case it’s useful to anyone coming across this issue

https://gist.github.com/vtta/d6268ba81ebfdd1dc573db4b72df8436

**Comment by domoritz** [comment]
@vtta might be willing to make a pull request when they are done

**Comment by laurmaedje** [comment]
With the existence and success of Typst Universe, we don't have plans to create any more first-party templates at the moment.

**Comment by laurmaedje** [comment]
I absolutely agree that availability of templates is a necessary (but sadly far from sufficient) step towards publisher acceptance.

The thing is that our capacity is limited and there are many important things to work on --- both for academia and beyond. We think right now it makes the most sense for us to focus on compiler improvements and leave templates to the community. Us having to create and maintain many templates would slow down compiler development. 

We think that this plan has so far worked out quite well. There are many templates available by now. No one has created an ACM one yet, but if it's desired enough I think it's only a matter of time / a motivated person learning about the desire for it for it to happen.

Note that this is only the current state of things. All of this might change once we have more development capacity.

**Comment by Amejonah1200** [comment]
> Note that this is only the current state of things. All of this might change once we have more development capacity.

So, we might still hope for a first-party integration for ACM templates?

**Comment by femtomc** [comment]
> The thing is that our capacity is limited and there are many important things to work on --- both for academia and beyond. We think right now it makes the most sense for us to focus on compiler improvements and leave templates to the community. Us having to create and maintain many templates would slow down compiler development.

All good, thanks for the reply and the logic! Makes total sense.

**Comment by reknih** [comment]
> So, we might still hope for a first-party integration for ACM templates?

There is nothing that our templates can do that third-party templates could not. Hence, you will arguabely get a better (and better maintained) template from someone with more experience publishing in ACM venues under their belt than from us. If our company grows and there are still no ACM, or other popular publisher, templates, we will consider creating them, but do not expect that in the immediate term.

We are considering creating a venue (forum thread or similar) where people who request templates can connect with template authors to coordinate supply and demand a bit, though.

**Comment by reknih** [comment]
@femtomc 

> I wish I could somehow put a bounty on this via GitHub.

Several prolific Typst contributors and template authors have GitHub Sponsorship accounts. A non-exhaustive list would be @Dherse @PgBiel @SUPERCILEX @johannes-wolf @JamesxX, you can find more in the contributors list and on Universe. I am sure that one of them would be happy to make a deal!

**Comment by vtta** [comment]
Done： https://github.com/typst/packages/pull/2219

**Comment by Amejonah1200** [comment]
> Done： https://github.com/typst/packages/pull/2219

Thank you very much!

**Comment by infinitymdm** [comment]
@Amejonah1200 Whose approval are you looking for? ACM or Typst?

**Comment by vtta** [comment]
> > Done： [typst/packages#2219](https://github.com/typst/packages/pull/2219)
> 
> Thank you very much! [@vtta](https://github.com/vtta) is it offically approved tho or it doesn't matter as long as it _looks_ like it?

I don't think ACM would approve third party works.
The template is made in accordance to styles specified in SOSP call for papers and passes the automatic style checks during submission.
As far as I can tell it looks nearly the same as other ones generated using Latex.
