### ISSUE TITLE
Line positioning inside rect and block not working as intended

### ISSUE THREAD

**Issue by Beiri22** [typst/typst#1701]
### Description

```
#rect(height: 5cm, width: 5cm, stroke: (dash: "dotted"))[
        #line(start: (50%, 0%), end: (50%, 100%))
        #line(start: (0%, -50%), end: (100%, -50%)) // not at 50%!
        #place(top+center, "oben")
        #place(bottom+center, "unten")
        #place(left+horizon, "links")
        #place(right+horizon, "rechts")
    ]
```

looks like:

![Bildschirmfoto vom 2023-07-12 12-33-12](https://github.com/typst/typst/assets/8210233/b4134446-25c6-4020-a7ee-1655e6ee12c1)

should result in two centered lines 

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Beiri22** [comment]
When aligning the latter, is gets worse: see https://typst.app/project/rIX10R9wCIS4_7kGcCKjTG

**Comment by ljgago** [comment]
This offset is because the line is an element with width and height, and the second line starts after the first line.

If you wrap the line in a place function, you will have the expected behavior.

```js
#rect(height: 5cm, width: 5cm, stroke: (dash: "dotted"))[
        #place(line(start: (50%, 0%), end: (50%, 100%)))
        #place(line(start: (0%, 50%), end: (100%, 50%))) // now at 50%!
        #place(top+center, "oben")
        #place(bottom+center, "unten")
        #place(left+horizon, "links")
        #place(right+horizon, "rechts")
    ]
```

The place function is relative to the parent and removes the width and height of the children element (you can test it with the measure function)

**Comment by Beiri22** [comment]
Thank you, that works perfectly. As I started with lines I had noticed that their stroke width does not move adjacent content away, so that I assumed, lines take no space.

**Comment by Beiri22** [comment]
done..
