### ISSUE TITLE
Unhelpful error message when calling cite() with key variable

### ISSUE THREAD

**Issue by raphCode** [typst/typst#1702]
### Description

I receive an unhelpful / unactionable error message when doing this:
- defining a custom citation function that eventually calls `cite(key)` where `key` is a variable
- calling the custom function so that an invalid key is passed to `cite(key)`

The error message is missing a traceback / stacktrace, so don't know which call site of the custom function is the culprit.

Consider this simple example:
```
#let foo(key) = cite(key)

#foo("invalid")
#foo("valid")

#bibliography("bib.yaml")
```
The error message only indicates that a bibliography key cannot be found, but not:
- which one
- how the execution reached this point (missing stacktrace)
```
error: bibliography does not contain this key
   ┌─ /test.typ:1
   │
 1 │   cite(key)
   │   ^^^^^^^^^
```

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by tingerrr** [comment]
Resolved as of ab5dd2a1c.
