### ISSUE TITLE
Add date-brackets option to cite()

### ISSUE THREAD

**Issue by travlake** [typst/typst#1703]
### Description

Most economics and finance papers cite articles using the "Astley and Morris (2006)" format instead of "(Astley and Morris 2006)" or "Astley and Morris 2006".

A simple way to make this possible without a fully customizable citation/bibliography would be to add a date-brackets boolean parameter to the cite function, or perhaps change "brackets" to have multiple options ("all", "date", "none"). 

### Use Case

Using Typst to write economics or finance papers while following the citation conventions of those fields.

**Comment by JKRhb** [comment]
I'd say this issue is already covered by #658 (and partly by #1139), however, I really like your proposed solution! :)

**Comment by Fanisting** [comment]
As an economic student, I totally agree with the suggestion.

**Comment by reknih** [comment]
You can now use the "author", "year", and "prose" forms of citations using the [`form` attribute](https://typst.app/docs/reference/meta/cite/#parameters-form) on `cite` in Typst 0.9.0.

**Comment by cbr9** [comment]
> We added over 80 citation styles to Typst. [Refer to the docs](https://typst.app/docs/reference/meta/bibliography/#parameters-style) to find a good match.
> 
> Alternatively, you can also now use the "author", "year", and "prose" forms of citations using the [`form` attribute](https://typst.app/docs/reference/meta/cite/#parameters-form) on `cite` in Typst 0.9.0. To use `"prose"` for all citations, write `#set cite(form: "prose")`

Would it be possible to include a form similar to prose, but without parentheses around the year? This would be useful when the citation is already included within a set of parentheses, to avoid double parenthesis.
