### ISSUE TITLE
Place function doesn't respect the parent relative position

### ISSUE THREAD

**Issue by ljgago** [typst/typst#1705]
### Description

The place function has a strange behavior with the bottom align after the [Basic floating placement](https://github.com/typst/typst/commit/78f96f844bc54c5385c1efda0b5faad3c49fa79b) commit (on main branch) and it doesn't work as before.

When using the place function with bottom align, for example with line elements, these elements fall the bottom position and they don't respect the relative position of the parent.

Example:

```js
#let graph-1 = box(
  width: 30pt,
  height: 30pt,
  place(
    bottom, {
      place(rect(width: 30pt, height: 30pt))
      place(dx: 5pt, dy: 5pt, line(start: (0pt, 0pt), end: (20pt, 0pt), stroke: red + 3pt))
      place(dx: 5pt, dy: 5pt, line(start: (0pt, 0pt), end: (0pt, 20pt), stroke: blue))
      place(dx: 5pt, dy: 5pt, line(start: (20pt, 0pt), end: (20pt, 20pt), stroke: yellow))
      place(dx: 5pt, dy: 5pt, line(start: (0pt, 20pt), end: (20pt, 20pt), stroke: green))
  })
)

#let graph-2 = box(
  width: 30pt,
  height: 30pt,
  place(
    bottom, {
      place(rect(width: 30pt, height: 30pt))
      place(dx: 5pt, dy: 5pt, {
        place(line(start: (0pt, 0pt), end: (20pt, 0pt), stroke: red + 3pt))
        place(line(start: (0pt, 0pt), end: (0pt, 20pt), stroke: blue))
        place(line(start: (20pt, 0pt), end: (20pt, 20pt), stroke: yellow))
        place(line(start: (0pt, 20pt), end: (20pt, 20pt), stroke: green))
      })
  })
)

Graph 1: #graph-1
\ \
Graph 2: #graph-2
```

Expected result (before `Basic floating placement` commit):

![image](https://github.com/typst/typst/assets/1047559/5540c55a-316d-4dd1-9de8-d06fa6ce0481)

Wrong result (after `Basic floating placement` commit):

![image](https://github.com/typst/typst/assets/1047559/b7cbd828-9d61-4e90-a1e9-6b0bc277d9d4)

Could it be that with these new changes I need something else to get the expected behavior?

### Operating system

Linux

### Typst version

- [x] I am using the main branch of Typst

**Comment by laurmaedje** [comment]
Seems like a created a bug in the process of implementing floats.
