### ISSUE TITLE
Improved TYPST_FONT_PATHS documentation

### ISSUE THREAD

**Issue by jgclark** [typst/typst#1708]
_Originally posted by @luochen1990 in https://github.com/typst/typst/issues/649#issuecomment-1507317901_:

> Hoping for a more detailed description about this ENV variable,  e.g.   WHAT is the expected seperator when there is more than one path;   Which directory level should this PATH point to,  'xxx/share/fonts/opentype/SourceCodePro-Black.otf'  or  'xxx/share/fonts/opentype'  or 'xxx/share/fonts' ?

I found I had the same question when trying to resolve font issues. The online documentation only mentions this env var in a brief CHANGELOG note.

**Comment by istudyatuni** [comment]
Seems like comma is used as separator

[clap::Arg::env](https://docs.rs/clap/latest/clap/struct.Arg.html#method.env)

[clap::Arg::value_delimiter](https://docs.rs/clap/latest/clap/struct.Arg.html#method.value_delimiter)

**Comment by OctarineSourcerer** [comment]
It may also be a good idea to place the details of this in the output of `typst fonts --help`, as that's somewhere people might look should their fonts not work as expected. 

I've found that running `TYPST_FONT_PATHS='~/.fonts/FontBase' typst fonts` allowed me to see fonts activated in FontBase, though it's worth notn that `fc-list ':' family` showed me all such fonts without needing to set possible environment variables.

**Comment by cderv** [comment]
> Seems like comma is used as separator

Doesn't it suppose `value_delimiter` to be used and set ?  Currently it is not, so not sure it is split
https://github.com/typst/typst/blob/897447e8593f00971de3a966d3fb23cf2b1e0f92/crates/typst-cli/src/args.rs#L116-L123

Maybe the env var should allow to provide several paths to search
