### ISSUE TITLE
Capitalization in bibliography

### ISSUE THREAD

**Issue by HROMANO** [typst/typst#1709]
### Description

I'm using "chicago-notes" formatting for bibliography.

All titles of references have the first words letter capitalized. Though it may be the rule in english, it looks really weird and hard to read for french titles (and probably other languages).

There should be no such formatting of titles in bibliography (or at least a way to disable it).

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Related: https://github.com/typst/typst/issues/805 and https://github.com/typst/typst/issues/1172

**Comment by zouharvi** [comment]
Usually in LaTeX one is able to protect capitalization by using `{}`, e.g.:

```
@article{foo,
   title={{MS-COCO}: {A} dataset for ...},
   ...
}
```

Is there an equivalent in Typst? The curly brackets don't work.

**Comment by laurmaedje** [comment]
We fixed a bug with hayagrivas BibTeX conversion, so the `{}` should work now when using a `.bib` file. For hayagriva's `.yml` file, you can use the `sentence-case` and `title-case` overrides or set `verbatim: true` on your fields.

**Comment by binarynoise** [comment]
Will there be a way to specify `verbatim: true` for whole files or bibliographies?

**Comment by laurmaedje** [comment]
We'll rethink this alongside CSL support. I'm not super happy with the verbatim field overall.

**Comment by reknih** [comment]
Title and sentence case folding is now suppressed for non-English locales (set with `#set text(lang: "es")`). Furthermore, you can use [the brace syntax](https://github.com/typst/hayagriva/blob/main/docs/file-format.md#formattable-string) proposed above to exclude segments of a string from case folding.
