### ISSUE TITLE
Join multiple citations when using `@label` syntax.

### ISSUE THREAD

**Issue by ModProg** [typst/typst#1712]
### Description

Make `@a@b@c` the same as `#cite("a", "b", "c")` i.e., join them depending on the citation style to, e.g., `[32, 33, 4]`.

### Use Case

Citing multiple source at once, avoiding having to either write the explicit function call or accept the additional brackets.

**Comment by laurmaedje** [comment]
Duplicate of https://github.com/typst/typst/issues/1606
