### ISSUE TITLE
Allow `cite` to collect multiple entries to a range.

### ISSUE THREAD

**Issue by ModProg** [typst/typst#1713]
### Description

If there are multiple references for some topic, it could make sense instead of listing them all to specify a range in the citation, when using the numeric style.

The links in such a joined citation `[1 - 4, 7 – 10, 22]` should go to the numbers shown, i.e. to `1`,  `4`, `7, `10`, and `22` respectively.

### Use Case

Given a bib:
```yaml
a: #...
b: #...
#...
f: #...
```

when a user specifies `#cite("a", "b", "c", "f")` this could expand to `[1-3, 6]`, assuming all entries were referenced in order prior.

**Comment by bluebear94** [comment]
Would this also apply if the entries were referenced in a different order such as `#cite("a", "f", "c", "b")`?

**Comment by ModProg** [comment]
> Would this also apply if the entries were referenced in a different order such as `#cite("a", "f", "c", "b")`?

that is a good question, it mainly depends on their order in the bibliography, as that needs to match in order to even have consecutive numbers. Not sure if the order in the cite should be enforced or if resorting could be applied when useful.

**Comment by bluebear94** [comment]
I don’t want to have to sort the cite entries manually by the order in which they would appear in the bibliography. I’d rather have the entries sorted by reference number by default in styles that use them.

**Comment by bluebear94** [comment]
`hayagriva` is capable of formatting citations for multiple entries at a time, but Typst only passes one entry cited to each call of `Database::citation`. I’ll have to look more into it.

**Comment by NuraliMedeu** [comment]
Is it possible to define custom rules to show 2 citations separately and 3 or more consecutive citations in a range? For instance, cite("two", "three") would be rendered as [2][3], but cite("two", "three", "four") would be rendered as [2-4].

**Comment by reknih** [comment]
Typst 0.9.0 now merges adjacent `cite`s if the CSL style requests it.
