### ISSUE TITLE
Add jj keybinding to exit insert mode

### ISSUE THREAD

**Issue by Ricolxwz** [typst/typst#1719]
### Description

Please add jj keybindings to exit insert mode

### Use Case

Please add jj keybindings to exit insert mode

**Comment by andreasKroepelin** [comment]
I do not think it is a good idea to start implementing everyone's custom vim keybindings in the webapp. Maybe some day there will be the possibility to configure the keybindings as a user.

**Comment by laurmaedje** [comment]
I have never used vim keybindings, so I don't know, but if "jj" is non-standard then we can indeed not support it as default. Maybe we'll support custom keybindings at some point.
