### ISSUE TITLE
Line break splits up German abbreviation "bzw."

### ISSUE THREAD

**Issue by realpixelcode** [typst/typst#1721]
### Description

The compiler unexpectedly wrongly splits up the German abbreviation `bzw.` (“beziehungsweise”) into two syllables:

```
blablabla b-
zw. blabla
```

Example:

```
Es sei $G = (V,E)$ ein zusammenhängender Graph – wie bisher. $(G,g)$ heißt gewichteter Graph (bzw. bewerteter Graph).
```

Settings: `set par(justify: true, linebreaks: "optimized")`

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by frozolotl** [comment]
> Is this with the language set to German?

It appears so.
Here's some code to replicate that issue:
```typ
#set page(paper: "a7")
#set text(lang: "de")
#set par(justify: true)

Es sei $G = (V,E)$ ein zusammenhängender Graph – wie bisher. $(G,g)$ heißt gewichteter Graph (bzw. bewerteter Graph).
```

**Comment by gfpj** [comment]
Probably the `(` is counted as the word start and thus `(b` are two "letters" and now prefix and suffix are of length 2 which allows for a word split.
The algorithm seems to miss checking for vocals (after splitting, prefix and suffix must have at least one vocal char).
