### ISSUE TITLE
Parse SVG from string

### ISSUE THREAD

**Issue by Beiri22** [typst/typst#1723]
### Description

When parsing SVG from a string, you could utilize the full postential: Using string manipulation on SVG source code. Dynamically create SVG images inside the document.

**Comment by laurmaedje** [comment]
In SVG, there is currentColor (which isn't currently supported by Typst), but I'm not aware of any other mechanism for parameterization. How would this work on the SVG side even if Typst supported it?

**Comment by laurmaedje** [comment]
Perhaps an alternative would be to support parsing SVGs from strings (which is planned) and then doing this with string manipulation.

**Comment by Beiri22** [comment]
String manipulation with regex or similar replacement would do the job neatly. As I saw in the code, the svg is first loaded into memory and then parsed. So with a parameter for a replacer function you could intercept the process in the normal image function. But, of cause, this would make no sense with binary image files. So maybe the approach to have a general function to load a file to string, would be a nice add-on. Could be used to later parse parts of the string from yaml, json, ... to the structured objects (see #1647) or to parse the svg.

**Comment by Beiri22** [comment]
Hi @laurmaedje,

if the image element function would not only take a str as required parameter for its path, but either:
-> A string that is interpreted as path
AND 
-> a dictionary with format and data

this would neatly integrate with the current implementation.

I'm willing to implement it; but is there any documentation on how different types of arguments are realized?
I saw `#[fold]` and the `cast`-Macro. Can you give me a hint?

**Comment by Beiri22** [comment]
I wasn't yet on discord, but just read the discussion. In my opinion the topic switches on the channel are disrupting. So `image.decode()` would be a new element function with all the implementation? You also need the format as parameter, because the file name is missing that currently is used to determine the format. You would have to maintain a lot of duplicate implementation. Looking at my previous proposal: a parameter that is `path: string | Dict<format: string, data: bytes>` - in the same function.It could be applied to csv, image, json, yaml,... It will not break with old code and be as easy for the default case. It would avoid duplicate implementation. The encoder functions would in that case be placed inside encode.* namespace / module. As you only encode data, not images, this seems reasonable to me.

**Comment by laurmaedje** [comment]
It wouldn't be a new element function, just an alternative constructor for the same element. The only hassle is dealing with the duplicate constructor arguments. This is still a bit of an unsolved problem though that could probably be fixed with an extension to the proc macro. In this case, a dictionary for the same function _would_ work. I'm not totally decided yet, but I would like things to be parallel for images and data types and the pairing `csv.decode`/`csv.encode` is a lot clearer to me than `csv((data: ..))`/`encode.csv`.

**Comment by Beiri22** [comment]
You're right. When we are only talking of a second constructor, I agree. With the duplicate arguments you refer to the declaration of width, height, alt and fit in lines 53-64? Doesn't seem so heavy to me...

**Comment by laurmaedje** [comment]
Yeah, that's what I mean. The constructor would have to take all these arguments and only add the respective field to the image element if present. Expanding the `#[element]` proc macro should show it's done in the generated constructor. It should be parallel to that.

**Comment by laurmaedje** [comment]
Yes, there was still a bit of discussion on Discords about the exact API, in particular of `json` vs `json.read`, but other than that I think we're good to go.

**Comment by Beiri22** [comment]
Just came up with another use case of this implementation: You can dynamically create SVG and parse it as image, so this could be a nice basis for some kind of canvas component.

**Comment by Beiri22** [comment]
@laurmaedje It seems as if its not possible right now to have two functions named `image()` and `image.decode()` similtanously, because of the naming conflict between module and function name. The same will affect json/decode and the other functions you mentioned earlier. Do you have any idea on how to solve this?

**Comment by laurmaedje** [comment]
This is solved by function scopes. Instead of defining a module with the same name, the function itself is the scope. You can take a look at the `OutlineElem` in `typst-library/src/meta/outline.rs` to see how it works.

**Comment by Beiri22** [comment]
Thank you, that works. Do you have some kind of developer documentation for all those tricks and principles?

**Comment by laurmaedje** [comment]
Not yet unfortunately. But the Discord is always very helpful.

**Comment by Beiri22** [comment]
Ok. btw. the PR has been updated :-)
