### ISSUE TITLE
No connection to editing api

### ISSUE THREAD

**Issue by carlobrok** [typst/typst#1725]
### Description

I'm trying to load my project and it takes a long while. Firefox seems to have issues connecting with the editing api (see screenshot). I tested it in Edge too, no problems yet.

![grafik](https://github.com/typst/typst/assets/44724164/6a4708c4-8b41-4ab2-97be-604f52902012)

### Reproduction URL

https://typst.app/project/p8xNdwRe-OsNXgdW9M6WGP

### Browsers

Firefox

### OS

Windows

**Comment by Qottmann** [comment]
Same problem with Firefox on windows throughout yesterday 😢

**Comment by laurmaedje** [comment]
We're working on it. The problem arises because one backend service (the collaboration server) overloads the main backend API sometimes. We've started tracking more metrics and are trying to find out what exactly is happening.

**Comment by laurmaedje** [comment]
We have made significant improvements to both back- and frontend. In particular, the error in the original screenshot can't happen anymore because we do not use `hocuspocus` anymore.
