### ISSUE TITLE
Reassign `in` in math mode

### ISSUE THREAD

**Issue by user202729** [typst/typst#1727]
### Description

These are the normal meanings of `in` in Typst:

```
$1 in 2$  // typeset "1 ∈ 2"
#{ math.in }  // typeset "∈"

#{ 1 in (1, 2) }  // returns true
```

Can I reassign it in math mode?

```
#let in0="hello"
$1 in0 2$

// #let in="hello" // cannot
```

### Use Case

See above.

**Comment by sitandr** [comment]
It may be generally a good idea to use show rules when possible for editing symbol appearance, like adding limits or spacing. But this approach will help there too.

`in` is a key word (used in `for` and check for inclusion), so redefining it will lead to ambiguous behaviour. I'm almost sure it is not worth to allow such variables. However, you can "rewrite" the math symbol:

```
#show math.in: "hello"

$a in b$
```

_Important note_: in the scope that show rule is used, **all** `in` symbols will be replaced with `hello` and I _don't know_ any obvious way to _"save it for later"_ (that would probably change when it becomes possible to cancel show rules). So be careful with that approach!

**Comment by laurmaedje** [comment]
As stated, reassigning `in` isn't possible because it is a keyword. The show rule is a good alternative here.
