### ISSUE TITLE
Example never show up on firefox

### ISSUE THREAD

**Issue by slashformotion** [typst/typst#1737]
### Description

![image](https://github.com/typst/typst/assets/45801817/177e8e0d-7475-4fa7-9721-1e82865c9935)

Even if the exemple is unfolded, the `opacity` property stay at 0.

### Browsers

Firefox

### OS

Linux

**Comment by laurmaedje** [comment]
Do you have JavaScript enabled? The opacity is modified through a script.

**Comment by slashformotion** [comment]
I think javascript is enabled in my firefox config. Other sites would break without it. 

I installed chromium and got this (no extensions, default config)
![image](https://github.com/typst/typst/assets/45801817/b748a590-cd36-4597-8682-110aab9ee76c)

**Comment by slashformotion** [comment]
Interestingly, it works on qutebrowser (<https://qutebrowser.org/>)
![image](https://github.com/typst/typst/assets/45801817/de012174-9920-4120-8aea-2a3b1fe94a70)

**Comment by mattfbacon** [comment]
1. Can be fixed with the following CSS:

```css
[aria-expanded="true"] .folding {
  opacity: 1 !important;
}
```

2. No JS or CSS should be needed for this, because the `<details>` element exists.

**Comment by laurmaedje** [comment]
I switched it to use `<details>` and JS. The `::marker` can't really be styled in a lot of ways, so I hid it and put the arrow thing into `<summary>`.

**Comment by mattfbacon** [comment]
Yeah, the ::marker is quite limited, but you can work around that with CSS:

https://jsfiddle.net/frLdvhgk/1/

**Comment by laurmaedje** [comment]
> Yeah, the ::marker is quite limited, but you can work around that with CSS

Yep, that's pretty close to what I did.
