### ISSUE TITLE
Loading project forever

### ISSUE THREAD

**Issue by fengyuli-dev** [typst/typst#174]
<img width="395" alt="image" src="https://user-images.githubusercontent.com/76980494/227050832-aefca43e-7aa5-4547-9723-6775de8f6d55.png">

I always get stuck on this page. No way to really use your product!

**Comment by namespaceYcZ** [comment]
Same problem.
Can not download either.

**Comment by teenjuna** [comment]
Folks, this is related to the huge flow of new users trying it out. I think devs will scale the servers at some point

**Comment by reknih** [comment]
We have improved the reliability of our servers over the last weeks. This includes loading projects, collaborating, and saving changes. Now, you should be able to load a project pretty quickly.

We also now back up your changes on the browser automatically to prevent data loss even if the connection is bad or if Typst becomes unavailable.

I am very sorry for the inconvenience and hope you'll try the app again!

**Comment by lcnbr** [comment]
I am also now experiencing this issue..

**Comment by lcnbr** [comment]
I get:

Errors while initializing: We could not connect to the server. Try again to continue.

**Comment by wenzhengzeng** [comment]
I meet the same issue

**Comment by laurmaedje** [comment]
@wenzhengzeng We had an outage. The service is back up.
