### ISSUE TITLE
Define a function that only works in math mode?

### ISSUE THREAD

**Issue by user202729** [typst/typst#1749]
### Description

Currently if you want to define a new function (#262, #432, #997) (or symbols) you can do

```
#let func(something) = something
$func(1+2=3)$
```

but then `func` will also be accessible in normal mode as well.

Is there a way to define the function to be only visible in math mode? Like the built-in  `math.*` functions and symbols.

### Use Case

I think some explicit scoping could be useful. (another reason is #1727 perhaps.)

**Comment by PgBiel** [comment]
I think it's better to just wrap your function's output in a math equation. For example, the following function will always result in math mode content (thus, technically, always being inside math mode):

`#let func(x) = $#x + 5$`

Note that the `math.*` functions are also accessible from outside math mode (just under the `math` scope). If you're seeking for a way to create your own scopes, you can either define the function in a separate file and import it (e.g. in `mymath.typ`, then `#import "mymath.typ"` will make `mymath` available for usage), or wait for the implementation of separate proposals regarding ways to create scopes within typst itself (e.g. something like `scope { ... }`).

**Comment by user202729** [comment]
No, what I mean is that doing something like `#let math.func(x) = ...`, such that
* in math mode it is directly accessible as `func(x)`
* in normal mode you must write `math.func(x)` in order to access it

**Comment by laurmaedje** [comment]
Extending the math module isn't really possible because modules are immutable. Is it so bad to have the functions in the global scope? Or perhaps, if you have very many, only import them in files where you need them?
