### ISSUE TITLE
Vim syntax

### ISSUE THREAD

**Issue by 4cq2** [typst/typst#175]
I think it would be helpful if Typst had a Vim syntax file, or at least could have a link to a recommended syntax file. Here are some examples:

https://github.com/vim/vim/tree/master/runtime/syntax

**Comment by marcelarie** [comment]
This would be awesome.

**Comment by 4cq2** [comment]
here is what I came up with:

~~~vim
syntax match typ_func /#\?\w\+(\@=/
highlight typ_func guifg=#4b69c6

syntax region typ_heading start=/^= / end=/$/
highlight typ_heading guifg=#19181f gui=bold

syntax match typ_num /\d\+%\?/
highlight typ_num guifg=#b60157

syntax region typ_str start=/"/ end=/"/
highlight typ_str guifg=#298e0d
~~~

based on the colors here:

- https://typst.app/docs/reference/meta/heading
- https://typst.app/docs/reference/visualize/image

code is probably terrible, but maybe will help someone.

**Comment by 4cq2** [comment]
here is what I came up with:

https://github.com/4cq2/blog/tree/main/2023-03/typst

based on the colors here:

- https://typst.app/docs/reference/meta/heading
- https://typst.app/docs/reference/visualize/image

code is probably terrible, but maybe will help someone.

**Comment by yingmanwumen** [comment]
I think it would be awsome if there is a coc.nvim plugin that supports typst syntax.

**Comment by 4cq2** [comment]
closing this because I have discovered some significant problems with Typst. I really like the project, but until some of the issues are fixed its not really in a usable state for me. I deleted the syntax file I was working on, here is the last version if its helpful:

https://github.com/4cq2/blog/tree/8af7aa06/2023-03/typst

**Comment by 4cq2** [comment]
https://github.com/typst/typst/issues/279

**Comment by user202729** [comment]
Searching around someone has a repository: [kaarmu/typst.vim: Vim plugin for Typst](https://github.com/kaarmu/typst.vim)

Currently only the syntax and `:make` is working, I only need the syntax anyway so it's enough.
