### ISSUE TITLE
Change the style of the figure caption

### ISSUE THREAD

**Issue by justlorain** [typst/typst#1750]
### Description

I wonder if there is a way that I can change the caption style of the figure.
Example:
From `Figure 1: A curious figure.` to `Fig. 1. A curious figure.`
But now it seems impossible to change the caption style.
```
#figure(
  image("glacier.jpg", width: 80%),
  caption: [A curious figure.],
) <glacier>
```

### Use Case

Can adapt to different meeting template requirements.

**Comment by justlorain** [comment]
> 

It works! Thanks for your answer.

**Comment by laurmaedje** [comment]
There is also a pull request for simpler customization of just the caption: #1704.

**Comment by Meuhor** [comment]
> You can change how a figure is displayed with a show rule (see [figure docs](https://typst.app/docs/reference/meta/figure/#modifying-appearance)). This also allows you to change how the caption is displayed.
> 
> For example:
> 
> ```typst
> #show figure.where(kind: image): it => align(center)[
>     #block(below: 0.65em, it.body)
>     Fig. #it.counter.display("1.") #it.caption
> ]
> ```
> 
> I think changing just the caption like you wanted is currently not possible.

Thanks for your answer. However, I found this solution works on "typst 0.1.0 (b3faef4b)" but not on "typst 0.8.0 (360cc9b9)"(the latest release binary). The newer edition adds both "Fig. 1.“(with right counter value followed by a dot) and the default caption prefix "Figure 1"(without a dot followed) before the caption string, for example the caption becomes "Fig. 1.: Figure 1: CaptionString". I only test this two version and only on windows host.

**Comment by AStarySky** [comment]
Change `#it.caption` to `#it.caption.value` will do the work
```typst
#show figure.where(kind: image): it => align(center)[
    #block(below: 0.65em, it.body)
    Fig. #it.counter.display("1.") #it.caption.value
]
```

**Comment by rzehumat** [comment]
Hello, I used @AStarySky 's solution in code (changing `#show` to `show`)

> Change `#it.caption` to `#it.caption.value` will do the work
> 
> #show figure.where(kind: image): it => align(center)[
>     #block(below: 0.65em, it.body)
>     Fig. #it.counter.display("1.") #it.caption.value
> ]

but I got `error: caption does not have field "value"`.

It worked to me when I changed `value` to `body`
```typst
  show figure.where(kind: image): it => align(center)[
    #block(below: 0.65em, it.body)
    Fig. #it.counter.display("1.") #it.caption.body
  ]
```

Unfortunately, this did not change the `Figure` word appearing inside List of Figures, generated by 
```typst
  outline(
    title: [List of figures],
    target: figure.where(kind: image)
  )
```

Could anyone help with this, please?

**Comment by rzehumat** [comment]
EDIT: Sorry for the confusion. It actually seems to be as simple as

```typ
#show figure.where(kind: image): set figure(supplement: [Fig.])
```

Taken from Typst forum: https://forum.typst.app/t/how-to-rename-a-specific-figure-kinds-supplement/716/2
