### ISSUE TITLE
Support for double struck numbers and lower case letters

### ISSUE THREAD

**Issue by SolidTux** [typst/typst#1757]
### Description

Add support for all double struck letters and numbers. They can be found in the Unicode block [Mathematical Alphanumeric Symbols](https://en.wikipedia.org/wiki/Mathematical_Alphanumeric_Symbols).

Uppercase letters are available in `sym`, but numbers and lowercase letters are not.

### Use Case

The main usecase would probably be the double struck 1 for the identity matrix. But in general having the possibility to reach more characters would be nice to have.

**Comment by Enivex** [comment]
Was this closed by accident?

**Comment by SolidTux** [comment]
No, I realized that I was stupid and there already is the `math.bb` function that does exactly that.

Am 20. Juli 2023 14:12:29 MESZ schrieb Enivex ***@***.***>:
>Was this closed by accident?
>
