### ISSUE TITLE
Backup downloads empty zip folder

### ISSUE THREAD

**Issue by Mc-Zen** [typst/typst#1761]
### Description

The _backup_ feature ceased working. The downloaded zip is empty. 

### Browsers

Microsoft Edge

### OS

Windows

**Comment by thygesteffensen** [comment]
It seems to be a Windows-related problem. You can unzip it with 7zip or `unzip` in Linux (Tried Ubuntu).
It is not as user-friendly, but you can still backup your projects :)

**Comment by Mc-Zen** [comment]
Yeah, you're right, with 7zip it works. There seems to be a folder named "_" inside the zip which contains the files. 

It used to be alright in the windows explorer though, last time I backed up when it worked was June 23rd.

**Comment by laurmaedje** [comment]
Fixed.
