### ISSUE TITLE
Minus sign rendered differently when using numbers from variables in math mode

### ISSUE THREAD

**Issue by abenthy** [typst/typst#1762]
### Description

When rendering a negative number in math mode using Typst 0.6.0

```
$-2.5$
```
**Output:**
![direct](https://github.com/typst/typst/assets/1838515/542fa6ca-0418-42c1-a454-5a62e1362ed4)

the minus sign looks different to the same code when using a variable:
```
#let x = -2.5
$#x$
```
**Output:**
![varibale](https://github.com/typst/typst/assets/1838515/9bcdb7c7-9cf8-4c1a-89c9-ff0d91e35eb2)

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by abenthy** [comment]
Someone on the Discord channel was so kind to provide a workaround which fixes the problem:

```
#show math.equation: it => { show "-": sym.minus; it }
```

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/2318
