### ISSUE TITLE
Fedora official version for Fedora

### ISSUE THREAD

**Issue by abramchikd** [typst/typst#1763]
### Description

Please add distribution that can be install via dnf

### Use Case

For Fedora users

**Comment by PgBiel** [comment]
I think it's probably better to request this to the Fedora distro maintainers/packagers. The Nix flake file in the repo is kind of an exception as Nix is a pretty different beast (and is distro-independent, etc.), but distro packaging is usually taken care of by the distro maintainers. Of course, would be nice if we could get in touch with someone responsible for Fedora packaging to get this going though.

**Comment by PgBiel** [comment]
Note that you can also use dnf to install rustup, run `rustup toolchain install stable`, and then run the command below to install the Typst CLI, on any distro:
```sh
cargo install --git https://github.com/typst/typst.git --tag 0.6.0
```
(Replace 0.6.0 with the latest version at the time.)

**Comment by 9SMTM6** [comment]
Its very rare for developers to directly support their own packages. Every linux distribution has their own rules, and since developers mostly need to test the current developement versions they're usually not using that package anyways.

I think this issue ought to be closed?

**Comment by alerque** [comment]
Yup, this should be brought up in Fedora somewhere, whatever venue packagers hang out in. Then when a package exists a PR mentioning it in the docs here.
