### ISSUE TITLE
Weird behaviour with Source Han Sans SC

### ISSUE THREAD

**Issue by GrandArth** [typst/typst#1766]
### Description

My template (slightly modified from web app):
```
// The project function defines how your document looks.
// It takes your content and some metadata and formats it.
// Go ahead and customize it to your liking!
#let project(title: "", authors: (), date: none, body) = {
  // Set the document's basic properties.
  set document(author: authors, title: title)
  set page(numbering: "1", number-align: center,
  paper: "a5",
  margin: (x: 1.5cm, y: 0.5cm)
  )

  // Save heading and body font families in variables.
  let body-font = "Source Han Serif SC"
  let sans-font = "Source Han Sans SC"

  // Set body font family.
  show heading: set text(font: sans-font)
  set text(font: body-font, lang: "zh")
  show raw: set text(font: "Sarasa Mono SC")
  set heading(numbering: "I – a - 1")


  // Title row.
  align(center)[
    #block(text(font: sans-font, weight: "bold", 1.75em ,lang: "zh")[#title])
    #v(1em, weak: true)
    #date
  ]

  // Author information.
  pad(
    top: 0.5em,
    bottom: 0.5em,
    x: 2em,
    grid(
      columns: (1fr,) * calc.min(3, authors.len()),
      gutter: 1em,
      ..authors.map(author => align(center, strong(author))),
    ),
  )

  // Main body.
  set par(justify: true)

  body
}
```

my main file:
```
#import "Template.typ": *



// // Take a look at the file `template.typ` in the file panel
// // to customize this template and discover how it works.
#show: project.with(
  title: "研究报告",
  authors: (
    "KyNSyZsgV0o8A-fSirq",
  ),
  date: "July 21, 2023",
)


Main Text 主文本
```

What i Get:
![image](https://github.com/typst/typst/assets/30680793/8a0f009b-fa95-4291-8679-b217eef69bf5)
The title is clearly using a serif font

Both fonts are installed on my system (win10, typst 0.6.0).

Any idea what is causing the problem?
(These fonts can be download from Adobe's SourceHan repo)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Julian-Wassmann** [comment]
This happened because the compiler didn't found the specified sans font. In this case, the compiler uses a default font as a fallback, which is a serif font.
My guess is that the name from the specified font is slightly different than the installed font. To check this, run `.\typst.exe fonts`. Search for your font and make sure the spelling is exactly the same as in the template file. For example, the "Source Han Sans" font from this [repo](https://github.com/adobe-fonts/source-han-sans/tree/release) is named "Source Han Sans SC VF". You need to add " VF" and it should work.

**Comment by GrandArth** [comment]
I see, I will check it out ASAPThx!Sent from my iPhoneOn Jul 22, 2023, at 03:29, Julian Waßmann ***@***.***> wrote:﻿
This happened because the compiler didn't found the specified sans font. In this case, the compiler uses a default font as a fallback, which is a serif font.
My guess is that the name from the specified font is slightly different than the installed font. To check this, run .\typst.exe fonts. Search for your font and make sure the spelling is exactly the same as in the template file. For example, the "Source Han Sans" font from this repo is named "Source Han Sans SC VF". You need to add " VF" and it should work.

**Comment by GrandArth** [comment]
> This happened because the compiler didn't found the specified sans font. In this case, the compiler uses a default font as a fallback, which is a serif font. My guess is that the name from the specified font is slightly different than the installed font. To check this, run `.\typst.exe fonts`. Search for your font and make sure the spelling is exactly the same as in the template file. For example, the "Source Han Sans" font from this [repo](https://github.com/adobe-fonts/source-han-sans/tree/release) is named "Source Han Sans SC VF". You need to add " VF" and it should work.

Did a fresh font installation with https://github.com/adobe-fonts/source-han-sans/releases/tag/2.004R
Checked that terminal output with `typst fonts` contains:
```
Sitka Text
Snap ITC
Source Han Sans
Source Han Sans SC
Source Han Serif
Source Han Serif SC
STCaiyun
```
Tried other fonts, and all work fine.

The above serif font is not the fallback font, the fallback font looks like this:
![image](https://github.com/typst/typst/assets/30680793/27ced083-aba1-4921-ad5c-dccb188c2a2f)
(Created by typing a random string in `sans-font`)

It seems that the problem only occurs with `Source Han Sans SC`

**Comment by GrandArth** [comment]
After assigning both fonts to `Source Han Sans SC` like:
```
  // Save heading and body font families in variables.
  let body-font = "Source Han Sans SC"
  // let body-font = "No Font Test"
  // let body-font = "Adobe Caslon Pro"
  // let body-font = "LXGW Wenkai"
  // let body-font = "FZNewShusong-Z10s"
  // let sans-font = "Sarasa Gothic CL"
  let sans-font = "Source Han Sans SC"
```

I get the proper output:
![image](https://github.com/typst/typst/assets/30680793/3aac8b65-cb56-4273-9804-e80e1fda73fd)

It seems like there is something wrong with the config file (or how the compiler deal with it), the compiler obviously can find the font.

**Comment by Julian-Wassmann** [comment]
Sorry, I was a bit confused which exact font you downloaded. Did you used the [release page](https://github.com/adobe-fonts/source-han-serif/tree/release#downloading-source-han-serif) and downloaded "Simplified Chinese" under "Language-specific OTFs", then installed the regular and bold OTFs?

I installed the Simplified Chinese font myself (regular and bold, both Sans and Serif). In Typst, I get the expected output, wich looks like this:
![Screenshot 2023-07-22 at 13-27-40 研究报告 - main pdf](https://github.com/typst/typst/assets/114947141/dd76dbab-114a-45a9-b996-67be4656de4f)
Using:
```
let body-font = "Source Han Serif SC"
let sans-font = "Source Han Sans SC"
```
Title and headings are using the Sans font (bold). Date, author and the main text are using the Serif font. The output is equivalent to what you have specified in the template.

Does your output look the same with the same settings? If this is the case, can you please explain, what you consider as a bug?

**Comment by GrandArth** [comment]
Thx for the testing. 

I am currently unable to conduct further examination on this problem. I will come back to this thread and check it out ASAP

**Comment by GrandArth** [comment]
> Sorry, I was a bit confused which exact font you downloaded. Did you used the [release page](https://github.com/adobe-fonts/source-han-serif/tree/release#downloading-source-han-serif) and downloaded "Simplified Chinese" under "Language-specific OTFs", then installed the regular and bold OTFs?
> 
> I installed the Simplified Chinese font myself (regular and bold, both Sans and Serif). In Typst, I get the expected output, wich looks like this: ![Screenshot 2023-07-22 at 13-27-40 研究报告 - main pdf](https://user-images.githubusercontent.com/114947141/255326969-dd76dbab-114a-45a9-b996-67be4656de4f.png) Using:
> 
> ```
> let body-font = "Source Han Serif SC"
> let sans-font = "Source Han Sans SC"
> ```
> 
> Title and headings are using the Sans font (bold). Date, author and the main text are using the Serif font. The output is equivalent to what you have specified in the template.
> 
> Does your output look the same with the same settings? If this is the case, can you please explain, what you consider as a bug?
Weird.
I am using the exact config and fonts, but I get this instead:
![image](https://github.com/typst/typst/assets/30680793/7f2e3ba3-75f4-432b-b915-ea3eab6a4ffe)

```

let body-font = "Source Han Serif SC"
let sans-font = "Source Han Sans SC"
  // Title row.
  align(center)[
    #block(text(font: sans-font, weight: "bold", 1.75em ,lang: "zh")[#title])
    #v(1em, weak: true)
    #date
  ]
```

**Comment by GrandArth** [comment]
I just confirmed that this is not a typst problem, this is a VS CODE problem.

With the same file, the screenshot from VSCode shows the weird serif result, but any other reader (firefox, edge) displays the right result.
