### ISSUE TITLE
Deviation between a literal `||` and a string `"||"` when used with `math.lr`

### ISSUE THREAD

**Issue by emilyyyylime** [typst/typst#1769]
### Description

The following code:
```typ
$
  lr(|| a^2 / 2 ||)
$
```
correctly renders with scaled delimiters
![image](https://github.com/typst/typst/assets/40892795/7a72ab38-ec65-490c-b69e-bf47f059cbd9)

However, with this slightly altered code:
```typ
$
  lr("||" a^2 / 2 "||")
$
```
does not properly scale the delimiters
![image](https://github.com/typst/typst/assets/40892795/20fce4f6-2d83-4f81-ac9e-ef7c732e0e94)

This is in contradiction with the behaviour of other delimiters, such as `[` / `"["` or `|` / `"|"`

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
> This is in contradiction with the behaviour of other delimiters, such as [ / "[" or | / "|"

I would consider this the incorrect behavior instead.

**Comment by emilyyyylime** [comment]
> I would consider this the incorrect behavior instead.

Why's that? This makes it significantly harder to use `lr` in scripts, whereas currently I can just use `math.lr[#left #content #right]`

**Comment by laurmaedje** [comment]
The reason is that `||` is just a math mode shorthand for `‖` (the Unicode codepoint U+2016 Double Vertical Line). In strings, everything is interpreted literally and in normal content `||` is not a shorthand, it only works in math (just like `->` for instance). You can write either `$||$` or `sym.bar.double`. Example:
```
#let left = $||$
#let right = $||$
#math.lr[#left $x/2$ #right]
```

**Comment by emilyyyylime** [comment]
Thanks, that makes sense.
