### ISSUE TITLE
Use a more extensive set of syntect grammars

### ISSUE THREAD

**Issue by ModProg** [typst/typst#177]
The builtin synctect grammars are pretty limited (e.g. `toml` is missing).

For my own projects, I found that `bat` collected a more comprehensive set of syntaxes: https://github.com/sharkdp/bat/tree/master/assets/syntaxes (they get compiled to `/assets/syntaxes.bin`

**Comment by reknih** [comment]
Notably, we are also missing TypeScript and Swift at the moment.

**Comment by sharkdp** [comment]
> For my own projects, I found that `bat` collected a more comprehensive set of syntaxes: https://github.com/sharkdp/bat/tree/master/assets/syntaxes (they get compiled to `/assets/syntaxes.bin`

See also: https://github.com/sharkdp/bat/issues/919

**Comment by laurmaedje** [comment]
Implemented in https://github.com/typst/typst/pull/771
