### ISSUE TITLE
100% CPU Usage on the Typst Homepage

### ISSUE THREAD

**Issue by frozolotl** [typst/typst#1770]
### Description

After some inactivity on https://typst.app/ while logged in, one CPU core is being utilized at 100%.
Reloading the page seems to solve the issue temporarily.

I profiled it using Firefox Profiler on two separate occasions:
- [a few seconds](https://share.firefox.dev/3Oplx4s)
- [more than two minutes, might take longer to load](https://share.firefox.dev/3K3FvPF)

### Browsers

Firefox

### OS

Linux

**Comment by laurmaedje** [comment]
I have fixed a React render loop which was probably the cause of this. If you still experience this, please reopen.
