### ISSUE TITLE
Wrong auto completion hint for `for loop (with key)`

### ISSUE THREAD

**Issue by Julian-Wassmann** [typst/typst#1778]
### Description

In the web app, when typing in `#for`, two auto completion hints for the for loop are shown:
![grafik](https://github.com/typst/typst/assets/114947141/59c3305c-da47-458f-981d-ce156cb530f6)

Choosing `for loop (with key)` will create this code:
```
#for key, value in (a: 1, b: 2) {
  
}
```

But it is missing the parentheses around `key, value`. It should be:
```
#for (key, value) in (a: 1, b: 2) {
  
}
```

**Comment by laurmaedje** [comment]
Yeah, this syntax is outdated ...
