### ISSUE TITLE
Customization of strokes and radii in page breaks

### ISSUE THREAD

**Issue by andrewragy** [typst/typst#1781]
### Description

I would like to customise these strokes in breakables such as blocks and tables: 
![Screenshot_20230723_160634_edit_234255646680398](https://github.com/typst/typst/assets/39835161/e403086a-64c3-444f-8edc-025a68955664)

Customization of radii would be great, too!

### Use Case

In publishing it is common for the strokes in the above image to be omitted entirely.

**Comment by Enivex** [comment]
Duplicate of https://github.com/typst/typst/issues/735
