### ISSUE TITLE
Customizable Monospace font

### ISSUE THREAD

**Issue by 9SMTM6** [typst/typst#1784]
### Description

AFAICT the monospace font is not currently customizable.

The included font is perfectly acceptable for me, however it was a bit surprising to me when I was unable to set the font, and also stuff such as ligatures in pseudocode will be unavailable this way.

There are probably alternatives for these, such as unicode symbols, as far as they are available in your font, or images, but these may have other issues and are difficult to pick up and use.

I understand that perhaps the current monospace font has additional features to be used in math etc, perhaps splitting these per usage, and letting us costomize only specific use-cases such as raw code would suffice.

If I missed a way to set the monospace font, I'm sorry, though in that case the documentation ought to be improved, I've searched for a decent amount of time.

### Use Case

* fully customize typesetting
* ligatures in pseudocode
* parity with TeX
* probably more, thats what I want to use this for.

**Comment by Enivex** [comment]
It is customizable

`#show raw: set text(font: "name goes here")`

**Comment by 9SMTM6** [comment]
Thanks for the fast feedback.

It mostly works too. But there's still some weirdness going on that I don't understand. After some experimentation it appears though that this is a more fundamental issue where OpenType settings are handled weirdly.

[Heres an example](https://typst.app/project/rsXz5XcFR-VBsM58WrHU80). It seems that the first invocation of #set text wins in terms of OpenType features regardless of what comes after, though defaults of different fonts overwrite this... also code sets different defaults for the fonts. Really weird, if you know whats going on I'd appreciate if you could formulate this, as I feel like I still don't entirely get it.

**Comment by 9SMTM6** [comment]
So, @Enivex , for Inconsolata Ligatures seem to be set with `dlig`. If you enable this feature, then the `>=` in raw code also gets changed, regardless of the explicit setting. Not the `=>`, I've found no setting that makes this a ligature in raw, no idea why.

The `calt`feature for Inconsolata, which enables ligatures for `Fira Code` also influences that setting for the following `Fira Code`, also despite the explicit setting when setting that font.

**Comment by 9SMTM6** [comment]
NVM, I've seen the code that causes these additional issues. I will create a PR where a unified discussion of the remaining issues here and #1783 can be discussed. Dunno if its going to be finished this evening.
