### ISSUE TITLE
SVG with embeded jpg/png not rendered in png export

### ISSUE THREAD

**Issue by Enter-tainer** [typst/typst#1785]
### Description

Inspired by  https://github.com/typst/typst/pull/1729#issuecomment-1647935742, I notice that typst disble default features for resvg. Therefore SVG with embeded jpg/png will not get rendered in png export. Note that the pdf export works fine.

Desired behavior:

<img width="368" alt="image" src="https://github.com/typst/typst/assets/25521218/f05a26e8-ba3c-4921-afd8-c054d9322b41">

PNG export behavior:

<img width="478" alt="image" src="https://github.com/typst/typst/assets/25521218/d2daa7a7-3471-4c3c-be86-9cdba844c743">

### Reproduction URL

https://typst.app/project/r7PeXxeBvdW4JfhPt2HVrd

### Operating system

Web app, Windows, Linux, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
I don't the exact reason why default features are disabled. However if we want to fix this we can simply enable these features.

**Comment by Dherse** [comment]
@LaurenzV that's sounds like something for the SVG guru 🙏

**Comment by LaurenzV** [comment]
> I don't know the exact reason why default features are disabled. I just find this behavior interesting but i don't know if whether the current behavior is intended or not. However if we want to fix this we can simply enable these features.

Not sure why either, it did work before, my guess is that it was accidentally changed while refactoring the crate structure. I created a PR.
