### ISSUE TITLE
Complete function name repertoir

### ISSUE THREAD

**Issue by OptimisticPeach** [typst/typst#1787]
### Description

The following functions aren't part of Typst's default math function names:
```
arsinh
arcosh
artanh
csch
sech
coth
arcsch
arsech
arcoth

arccsc
arcsec
arccot

erf
```

I hence propose adding them (similar to how `sin` is recognized).

### Use Case

These functions are pretty useful in trigonometry (hyperbolic, euclidean, and spherical).

These functions, although uncommon, are very unlikely to clash with other functions because they are well established.

**Comment by OptimisticPeach** [comment]
> By the way, it's arsinh (and so on), not arcsinh

Just edited to fix that, thanks!

> You can easily add these yourself with op().

This _is_ true, however notice that we currently have `arcsin` but no `arsinh`, similarly we have `csc` but no `csch`. It's a matter of being complete -- if `sinh`/`cosh`/`tanh` weren't part of the standard function library, I wouldn't be mentioning this. But they are, so parity at least with regards to circular trig functions would be natural.

**Comment by laurmaedje** [comment]
There has been a lot of discussion about operators on Discord and I've come to the conclusion that a fully consistent set of operators is really hard to reach without baking in tons of operators. There's always one more operator to make things complete for one particular field. The current set is not designed to be ultimately consistent, but to covers most operators that are used often.
