### ISSUE TITLE
Equivalent of \allowbreak

### ISSUE THREAD

**Issue by hobbeshunter** [typst/typst#1788]
Hi,
is there an equivalent of the LaTex command \allowbreak that indicates that a word may break there but without hyphen?

**Comment by laurmaedje** [comment]
Looks like this is answered/solved. If not, feel free to reopen.

**Comment by hobbeshunter** [comment]
Hi,
thanks for the answer. Unfortunately this workaround doesn't really work for me. The pdf viewer I tried (Firefox, Adobe on Windows) convert the zero width space to a normal space on copy-pasting from the pdf. Which is ugly in my case.

**Comment by antonWetzel** [comment]
(Based on my limited knowledge of the pdf format)
I think in a pdf to have a linebreak there must be some break, so a programm to copy the content will copy some seperation.

To spellcheck I used [Pandoc](https://pandoc.org/MANUAL.html) and converted with `pandoc <input_file>.typ --wrap=none -t plain -o <output_file>.txt` to a version with only text-content (plus math in latex style).
Maybe you can copy-paste from the plain text version.
