### ISSUE TITLE
Get list of formatted lines from `raw` block

### ISSUE THREAD

**Issue by platformer** [typst/typst#1799]
### Description

`raw` block elements should have a property called `formatted-lines` (or something similar) that returns a list of content values, where each value is a line from the `raw` block with complete formatting and highlighting.

### Use Case

The main use case is for formatting `raw` text with line numbers. One common way to do this is to use `raw`'s `text` property to get the text as a string, split the string on newlines, and layout the lines in a `table` while re-calling `raw` on each line. This is a simple and intuitive solution, but it breaks formatting for languages with contextual syntax highlighting (e.g. Typst itself).

Another solution is to use a 2-column `grid` to layout line numbers alongside the complete, unchanged `raw` block. This isn't prone to the same syntax highlighting issue, but it is less simple and more fragile than using a `table`. It is also less flexible if one is trying to add other features such as indent guides or the ability to highlight entire lines of code. Using a table is the more semantic solution.

Ultimately, having access to a list of formatted lines would be the most flexible API.

**Comment by jneug** [comment]
I think this would be nice to do  more with code blocks. Native support for line numbers still seems like a hood idea, but this would allow package authors to get creative. 

Perhaps it would align better with the naming scheme of other elements to call the attribute `children` and have an element function `raw.line`, similar to enums?

**Comment by platformer** [comment]
I recently noticed #2341 was merged. I haven't got the chance to try it, but I think it pretty much resolves this issue? In which case this issue should be safe to close.

**Comment by Dherse** [comment]
Closed by #2341
