### ISSUE TITLE
Number formatting with trailing/leading zeroes

### ISSUE THREAD

**Issue by tv42** [typst/typst#180]
Let's say I have an "ugly" number like 12.4102174, read via `json` or from `#calc.log` or whatever. I don't see a way to display it to the user as e.g. 12.410, with the trailing zero.

`#math.round` is not the answer: `#calc.round(12.4102174, digits: 3)` = `12.41`.

This is especially useful for e.g. currency, nobody expects to see a cost of $5.1, they expect $5.10

I also have a list of hours tracked by 30 minute granularity, so e.g. 1.0, 1.5, 4.0, and would like to always display the `.0` for alignment and uniformity.

**Comment by 4cq2** [comment]
closest looks like `str`, but no control of precision:

https://typst.app/docs/reference/construct/str

**Comment by user202729** [comment]
Seems easy enough...

```
#let format(number, precision) = {
  assert(precision>0)
  let s = str(calc.round(number, digits: precision))
  let after_dot = s.find(regex("\..*"))
  if after_dot==none {
    s=s+"."
    after_dot="."
  }
  for i in range(precision - after_dot.len()+1){
    s=s+"0"
  }
  s
}

#format(12.4102174, 3)

#format(12.4102174, 2)

#format(12, 2)

#format(12, 3)
```

**Comment by Beiri22** [comment]
Seems perfectly suited for an in-built function by the name toFixed() :-)

**Comment by tv42** [comment]
For what it's worth, here's my current workaround, based on the earlier comment, but avoiding that tight loop because I'm and OCD programmer:

```typst
#let formatNumber(number, precision) = {
  assert(precision > 0)
  let s = str(calc.round(number, digits: precision))
  let tail = s.find(regex("\\..*"))
  let pad = if tail == none {
    s = s + "."
    precision
  } else {
    precision - tail.len() + 1
  }
  s + pad * "0"
}
```

**Comment by muja** [comment]
I added a delimiter option for thousands delimiters. I also rewrote so it works without regex.

```
#let format_currency(number) = {
  let precision = 2
  let decimal_delim = "."
  let thousands_delim = ","

  let value = str(calc.round(number, digits: precision))
  let integer = str(calc.floor(number))

  if integer == value {
    value += ".00"
  }

  let from_dot = value.slice(integer.len())
  while from_dot.len() < precision + 1 {
    from_dot += "0"
  }

  let cursor = 3
  while integer.len() > cursor {
    integer = integer.slice(0, integer.len() - cursor) + thousands_delim + integer.slice(integer.len() - cursor, integer.len())
    cursor += thousands_delim.len() + 3
  }
  integer + from_dot
}
```

**Comment by Caellian** [comment]
@muja Didn't work with negative numbers like the regex solution.

**Comment by muja** [comment]
@Caellian you can add this to the start of the function so it works with negative numbers (wasn't in my use case):

```
  if number < 0 {
    return "-" + format(calc.abs(number), precision: precision, decimal_delim: decimal_delim, thousands_delim: thousands_delim)
  }
```

**Comment by laurmaedje** [comment]
I'll close this in favor of https://github.com/typst/typst/issues/3269, which had a bit more detail and discussion.
