### ISSUE TITLE
Error not showing in web app

### ISSUE THREAD

**Issue by dipamsen** [typst/typst#1802]
### Description

With CeTZ, using the cli the following code gives an error:

```ts
#import "@preview/cetz:0.0.1"

#cetz.canvas({
  import cetz.draw: *

  set text(6em) // ERROR

  circle((0, 0), radius: 2, name: "c")
})
```

![image](https://github.com/typst/typst/assets/59444569/39282126-613d-477f-8d12-6f37e17c2f0e)

However the same does not give any error in the web app - it says "Your document contains no errors", but editing the app does not update the output. (See reproduction URL) Also on refreshing the page, the output doesn't show up, but no errors are logged. 

### Reproduction URL

https://typst.app/project/rv_ZFycy2QvR5C2TrhBdmg

### Browsers

Chrome

### OS

Windows

**Comment by Enivex** [comment]
Same with tablex

```
#import "@preview/tablex:0.0.4": tablex

#tablex(
  map-cols: (i,cells) => none,
  [Hello world]
)
```
leads to

```
error: panicked with: "Tablex error: 'map-cols' returned something that isn't an array."
     ┌─ @preview/tablex:0.0.4\tablex.typ:2239:17
     │
2239 │             panic("Tablex error: 'map-cols' returned something that isn't an array.")
     │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

help: error occurred in this call of function `apply-maps`
     ┌─ @preview/tablex:0.0.4\tablex.typ:2500:26
     │
2500 │           let mapped_grid = apply-maps(
     │ ╭───────────────────────────^
2501 │ │             grid: table_grid,
2502 │ │             hlines: hlines,
2503 │ │             vlines: vlines,
     · │
2507 │ │             map-cols: map-cols
2508 │ │         )
     │ ╰─────────^
```

but the web app claims that "Your document contains no errors.", while also not outputing anything.

Is this for any panic() in a package?

**Comment by laurmaedje** [comment]
Fixed.
