### ISSUE TITLE
Citation uses same number for different entries when style is given for one citation

### ISSUE THREAD

**Issue by thygesteffensen** [typst/typst#1805]
### Description

The citation style is IEEE, but I wanted to reference the title and author for a single citation, and I thought I could achieve this by specifying `style` for that single citation. E.g., 

```typ
@glacier-melt

@distress

#cite("distress", style: "chicago-author-title")

@arrgh

@mcintosh_anxiety

@issue201

#bibliography("works.bib")
```
However, the given Typst document compiles to:
![image](https://github.com/typst/typst/assets/31892312/22beeefb-0444-410a-8a14-0b3055644a55)

*Notice*  that the `1` and `2` are used twice each for different entries. Removing `style: "chicago-author-title"` from line 5 "fixes" the wrong numbering.

The odd behaviour occurs when the specified style differs from the overall style, i.e. in the example, if it is anything but `numerical`.

[works.txt](https://github.com/typst/typst/files/12170759/works.txt) _I have attracted `works.bib` as `works.txt` - It's the one used in the documentation examples._

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by bluebear94** [comment]
## Code analysis

The numerical citation style (`hayagriva::style::Numerical`) keeps track of the numbers used for entries. This information is mutated whenever a citation is generated for a work that was not cited before.

Whenever the citation style of a `cite` element is different from that of the previous `cite` elem, the ‘current citation style’ object is replaced ([`meta/bibliography.rs` in `typst-library`](https://github.com/typst/typst/blob/main/crates/typst-library/src/meta/bibliography.rs#L499)), losing the information about the numbers that have been used.

**Comment by joeldierkes** [comment]
A quick and dirty fix is to specify the items, that occur doubled, in one style *before* the broken references are used. This results in the right numbering in the overall document.

Combining it with `hide` and `place` results in an invisible reference that can be placed at the beginning of the document:
```markdown
#hide[
  #place(center, dx: 0mm)[
    @netwok
    @issue
    ...
  ]
]

...
```

**Comment by reknih** [comment]
Citation numbers will now always be assigned, no matter if the style prints them. To print an author, however, use the new [`form` attribute](https://typst.app/docs/reference/meta/cite/#parameters-form) with `"author"` to get an author listing that matches your style.
