### ISSUE TITLE
Ligatures seem to break smallcaps

### ISSUE THREAD

**Issue by lf-** [typst/typst#1807]
### Description

When using a font with a ligature covering part of a word set in smallcaps, the ligature seems to force rendering into the regular mode. I am not sure if this is a New Computer Modern exclusive bug (or indeed a bug in New Computer Modern itself) or a bug in the compiler.

![image](https://github.com/typst/typst/assets/6652840/09999ad7-7d0c-4764-8f17-b95a228784f1)

Repro:

```
#set text(font: "New Computer Modern")
#smallcaps[Left]
```

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by bluebear94** [comment]
It doesn’t happen with other fonts supporting small caps such as Linux Libertine, Noto Serif, or even the other New Computer Modern fonts.

**Comment by alerque** [comment]
I believe this is a bug in the font, not in the typesetter. I tried it out in SILE as well and got the same results, and as @bluebear1 said it also works properly with other fonts in SILE, just not that one.

```sile
\begin{document}
\font[family="New Computer Modern"]
\font[features="+smcp"]{Left}
\end{document}
```

**Comment by lf-** [comment]
Hmmm. However, is this because SILE and Typst are holding the font the same specific wrong way that is causing this problem? I want to figure out if we can get a better reproduction that is more useful to the font author.

It looks like this happens with *specifically* NewCM08-Book, with `liga` and `smcp` set. It's reproducible on https://opentype.dev if you put it into there.

**Comment by lf-** [comment]
I have emailed the font author. I'll post back here when I get a reply.

**Comment by alerque** [comment]
Having ligatures enabled or not is up to the font, and optionally up to the font to provide a feature flag to alow the shaping engine to enable/disable them. If the +smcp feature flag is on and it doesn't have a small cap ligature it shouldn't be providing a lower case one, that's something the font is telling the shaper to do. Typst isn't doing anything weird here.

**Comment by lf-** [comment]
I have confirmed that this is most likely a font bug:

![Screenshot_20230730_135901](https://github.com/typst/typst/assets/6652840/7bd5097f-aca5-4533-b73a-25b58aae16aa)

I am not sure how the font author needs to fix it, but I have forwarded this reproduction to him. I don't know how to make these tables mutually exclusive such that ligatures and small caps are not on at the same time; or should the font have a fake ligated pair replacing the ligated pair (probably not since it would break tracking/kerning adjustment)? I am not sure.

**Comment by laurmaedje** [comment]
I'm going to close as it doesn't seem to be a problem on our side from what I've gathered.

**Comment by lf-** [comment]
The bug is that the ligature table is above the smallcaps table in the font, so the characters get ligated before they become smallcaps, rather than the other way around. It's a very easy fix for the font author, and I'll PR the updated font version when a fixed version is released :) Definitely not your bug.
