### ISSUE TITLE
Start index for array enumerate method

### ISSUE THREAD

**Issue by Nabav** [typst/typst#1808]
### Description

Inspired by Python's `enumerate` method, I would like to ask adding the optional `start` argument (defaults to `0`), to the array [enumerate](https://typst.app/docs/reference/types/array/#methods-enumerate) method to let the user to start enumerating from an index other than zero.

### Use Case

In some applications starting from index `1` is very convenient.

**Comment by Enivex** [comment]
Enumerate already has a start argument

**Comment by Enivex** [comment]
I should not have closed this. Reopened.

**Comment by laurmaedje** [comment]
https://github.com/typst/typst/pull/1818
