### ISSUE TITLE
Nested Enumerations with align(horizon) bug 

### ISSUE THREAD

**Issue by Dragoncraft89** [typst/typst#181]
Commit: 045a109600fa9127d22259287bbde62234cadb44

In the below code, the first item (Foo) is printed above the corresponding numeration (1.)
```
#set align(horizon)

+ Foo
  + Bar
+ Baz
```

**Comment by taooceros** [comment]
This also happens to unordered list

```
#show block: set align(horizon)

- s#linebreak()aa#linebreak()bbbbbb

```
