### ISSUE TITLE
Example for linebreaks property of text is identical for both "simple" and "optimized"

### ISSUE THREAD

**Issue by tom-kuca** [typst/typst#1820]
The example image for linebreaks looks the same for both `optimized` and `simple` unless I'm missing some pixel-size differences. It should demonstrate the difference.

![screenshot-2023-07-29-12:16:07](https://github.com/typst/typst/assets/171436/76a053b8-0317-4543-b5bf-d54f4aa08f7b)

**Comment by gfpj** [comment]
I think the following example would solve it:

```typst
#set page(width: 190pt)
#set par(linebreaks: "simple", justify: true)
Some texts are frustratingly
challenging to break in a
visually pleasing way. This
very aesthetic example is one
of them.

#set par(linebreaks: "optimized", justify: true)
Some texts are frustratingly
challenging to break in a
visually pleasing way. This
very aesthetic example is one
of them.
```
