### ISSUE TITLE
Text outside rect when justified

### ISSUE THREAD

**Issue by rodarima** [typst/typst#1825]
### Description

The following MRE
```
#set page(width: 21cm, height: 10cm)

#set par(justify: true)
#rect(lorem(100))

#set text(overhang: false)
#rect(lorem(100))
```
with typst 0.6.0 (66df130c) causes the text to be placed outside the rect in both cases:

![bugrect](https://github.com/typst/typst/assets/3866127/14de7642-5380-45d9-a3e1-7e99d50115f7)

### Reproduction URL

https://typst.app/project/rgaWV7-74WImlCRdwgDc5U

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by bluebear94** [comment]
This also happens only for `linebreaks: "optimized"`.
