### ISSUE TITLE
`#typst` command similar to `\LaTeX`

### ISSUE THREAD

**Issue by NicoWeio** [typst/typst#1830]
### Description

This should return the typst branding, similar to how `\LaTeX` gives

![](https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/LaTeX_logo.svg/2048px-LaTeX_logo.svg.png)

### Use Case

This would make for a neat way to brag about using typst in one's documents. 

There might be good reasons against this, I just wanted to put this idea out there.

**Comment by frozolotl** [comment]
"Typst" is not really supposed to be formatted in a special way, so it's not really necessary to include such a feature.

See the [Brand Guidelines](https://typst.app/legal/brand/).

**Comment by laurmaedje** [comment]
See above.
