### ISSUE TITLE
datetime not represented in methods_on ?

### ISSUE THREAD

**Issue by Beiri22** [typst/typst#1835]
### Description

Hello.

Is it intended, that the Type datetime and its methods are not represented in the function `methods_on()` in crates/typst/src/eval/methods.rs ?

### Typst version

- [ ] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Probably an oversight.

**Comment by laurmaedje** [comment]
Yes, it's just a matter of doing it. I actually have a local branch that does this. It's not quite finished though.
