### ISSUE TITLE
Native QR code support

### ISSUE THREAD

**Issue by jneug** [typst/typst#1837]
### Description

These days, QR codes are a common addition to print  and digital media. It would be nice for Typst to support native creation of QR codes from strings via a `#qrcode( data )` function. 

### Use Case

There are a lot of use cases. For URLs in print documents, a QR code could point to the mentioned website. As a teacher, I often use QR codes to hide hints or solutions the students can scan during work.

**Comment by Beiri22** [comment]
Do you have a schedule for qasm plugins somewhere?

**Comment by Beiri22** [comment]
Sounds great. I hope there will be some developer documentation- at least for the wasm-plugin-interface- ;-)

**Comment by laurmaedje** [comment]
See #1555

**Comment by Beiri22** [comment]
I will have a look at the plugin system once it's merged.

**Comment by Enivex** [comment]
> I will have a look at the plugin system once it's merged. QR-Codes, however, will only be possible with the #1810 functionality, since a plugin seems to return only pure data, so content elements.

The QR code could be created using typst drawing commands instead of an image

**Comment by ramkumarkb** [comment]
@jneug - Please see the discussion under https://github.com/typst/typst/discussions/1643

**Comment by astrale-sharp** [comment]
@Enivex , it could be a package even if it uses WebAssembly plugins!

**Comment by Enivex** [comment]
> @Enivex , it could be a package even if it uses WebAssembly plugins!

I know, I'm just saying that in theory it could be created in pure typst.

**Comment by BlueskyFR** [comment]
Would incremental compilation mean that the QR code is not rerendered each time a new character is typed?

**Comment by laurmaedje** [comment]
Yes

**Comment by laurmaedje** [comment]
WebAssembly plugins have been merged.
