### ISSUE TITLE
Missing translation in bibliography content

### ISSUE THREAD

**Issue by carlobrok** [typst/typst#1838]
### Description

I created a bibliography using

```
set text(font: doc_font, lang: "de", overhang: false, size: 12pt)
// [....]
bibliography(bib)
```

The title is translated properly, but the "(accessed: ...)" for online references is not.

![grafik](https://github.com/typst/typst/assets/44724164/0447b2ba-51fb-4356-970f-6d721043ecec)

### Reproduction URL

https://typst.app/project/p8xNdwRe-OsNXgdW9M6WGP

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by extua** [comment]
This is an issue with the citation styles in [hayagriva](https://github.com/typst/hayagriva). What style are you using?

**Comment by flavio20002** [comment]
Workaround:

    #{
        show "accessed": [zugegriffen]
        bibliography(bib)
    }

**Comment by carlobrok** [comment]
@extua I'm using the default IEEE style. 

Thanks for the workaround @flavio20002. But the date is still in American format..

**Comment by laurmaedje** [comment]
This will be fixed once we have migrated hayagriva to CSL.

**Comment by jannisko** [comment]
@carlobrok I'm using a pretty dirty workaround for this for now:

For `apa`
```
#{
  show regex("\d{4}, (January|Febuary|March|April|May|June|July|August|September|October|November|December) \d{1,2}"): it => {
    let (year, rest) = it.text.split(",")
    let (month, day) = rest.trim(" ").split(" ")
    let month_map = (
      "January": "Januar", "Febuary": "Februar", "March": "März",
      "April": "April", "May": "Mai", "June": "Juni", "July": "Juli",
      "August": "August", "September": "September", "October": "October", "November": "November", "December": "Dezember"
    )
    let month = month_map.at(month)
    [#[#day].#month #year]
  }

  bibliography("sources.bib", style: "apa")
}
```

For `ieee`
```
#{
  show "Accessed": "Zugegriffen"
  show regex("(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\.? \d{1,2}, \d{4}"): it => {
    let (month, day, year) = it.text.split(" ")
    let month_map = (
      "Jan.": "Jan.", "Feb.": "Feb.", "Mar.": "März",
      "Apr.": "Apr.", "May": "Mai", "Jun.": "Jun.", "Jul.": "Jul.",
      "Aug.": "Aug.", "Sep.": "Sep.", "Oct.": "Oct.", "Nov.": "Nov.", "Dec.": "Dez."
    )
    let month = month_map.at(month)
    let day = day.replace(",", ".")
    [#day #month #year]
  }

  bibliography("sources.bib", style: "ieee")
}
```

**Comment by reknih** [comment]
Typst 0.9.0 will use CSL locales to localize the terms in your bibliography to about 30 languages. Use `#set text(lang: "pt", region: "BR")` to change the language.
