### ISSUE TITLE
\jobname for Typst

### ISSUE THREAD

**Issue by jneug** [typst/typst#1839]
### Description

I use a consistent naming scheme for my files, that includes some meta data about the document. For example:

```
2023-08-01_IV.3_Report_A.typ
```

If a Typst file had access to the filename (similar to LaTeX' `\jobname`), this information could directly be used in the document.

### Use Case

This would help with template development, by allowing users to automatically add dates or other information to the output.

**Comment by user202729** [comment]
Worth noting LaTeX's `jobname` is not always identical to the file name which causes some headache.

The disadvantage is that the same document may compile differently depends on the file name the document is stored in. But considering that renaming a dependency file already change the behavior of `#import` this could be reasonable.

Another alternative is #295 which also satisfy that use case but requires some command-line scripting to pass the file name in the argument.

**Comment by laurmaedje** [comment]
I think I prefer some way to pass parameters through the CLI. Would that suffice for your use case?

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/typst/issues/295
