### ISSUE TITLE
[Feature Request] WaveDrom support

### ISSUE THREAD

**Issue by capvor** [typst/typst#184]
Digital Timing Diagram is most useful in electron industry.

I think [WaveDrom](https://wavedrom.com/) support is a great feature.

**Comment by ollelogdahl** [comment]
I created a small example how this could be implemented. It's not pretty or complete, but it might help you along:
[test.txt](https://github.com/typst/typst/files/11051067/test.txt)

**Comment by laurmaedje** [comment]
I would agree that this is out of scope for the core, but seems like a thing that could be in the package manager once it exists.

**Comment by capvor** [comment]
@laurmaedje @ollelogdahl 

My idea is that don't need typst to parse code, just pass code to the WaveDrom application to get the generated svg image, and insert it into the document.

Mermaid support (https://github.com/typst/typst/issues/161) can also be implemented in this way.

**Comment by ollelogdahl** [comment]
> @laurmaedje @ollelogdahl 
> 
> My idea is that don't need typst to parse code, just pass code to [wavedrom-cli](https://github.com/wavedrom/cli) to get the generated svg image, and insert it into the document.
> 
> Mermaid support (https://github.com/typst/typst/issues/161) can also be implemented in this way.

That is one solution. One trade-back of this, which i find pretty big, is that text-styling doesn't get preserved. You see, i think that one of the powers is using the same font, size, color, styling in both the text and figures.
