### ISSUE TITLE
Different output from x² and x^2

### ISSUE THREAD

**Issue by Kyuuhachi** [typst/typst#1840]
### Description

Unicode superscripts and math superscripts have different spacing.
![image](https://github.com/typst/typst/assets/1547062/ec2de2d5-fa33-4780-bf3a-1564b3122abb)

The difference is even more startling when writing sin² x:
![image](https://github.com/typst/typst/assets/1547062/2a5f5cf8-6554-4dd4-999f-1ebd3bf4b59d)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
Duplicate https://github.com/typst/typst/issues/592
