### ISSUE TITLE
Datetime creation function today(offset) incorrect

### ISSUE THREAD

**Issue by Beiri22** [typst/typst#1842]
### Description

The system world does save the datetime of today in a OnceCell once and reuses it. The offset provided to the function is only evaluated in the first run and ignored in all future runs.

### Typst version

- [ ] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
It is reset here: https://github.com/typst/typst/blob/1c7105ba82048e74563e6aad3a824bb53dae1663/crates/typst-cli/src/world.rs#L100

For the web app, it is indeed wrong though.

**Comment by laurmaedje** [comment]
Ah, I understand. That makes sense.
