### ISSUE TITLE
Add a CLI option to customize where fonts are searched for first

### ISSUE THREAD

**Issue by TheLukeGuy** [typst/typst#1846]
### Description

Currently, fonts are searched for in the order of "system → embedded in the Typst executable → user-specified additional font paths" as determined by [this method](https://github.com/typst/typst/blob/77cc05b121bef5a7feb62345d19d9c693415d7cd/crates/typst-cli/src/fonts.rs#L69-L79). I believe it should be possible to modify this order using a CLI option so that if there are duplicate versions of the same font, it's easier to prioritize one version over the others.

I'm unsure what the best design for such a CLI option would be, but some options include:
- An option for specifying the entire order, e.g., `--font-search-order user,system,embedded` (colons could also work in place of commas)
- An option that can be used multiple times to specify the *next* highest priority, e.g., `--prioritize-fonts user --prioritize-fonts embedded`
- Separate flags that let you specify which source should be searched first, e.g., `--prioritize-user-fonts` and `--prioritize-embedded-fonts`

I'm willing to implement this feature and PR if this is something that would fit into Typst.

### Use Case

There are occasionally multiple variations of the same font and you might, for instance, have one variation of a font installed on your system and another inside of a `fonts` directory in your Typst project that you include with the `--font-path` option. Currently, if you want to use the variation in the `fonts` directory, you're completely out of luck.

More specifically, I use the [Berkeley Mono](https://berkeleygraphics.com/typefaces/berkeley-mono/) typeface both for coding and for some documents written in Typst. When you download the typeface, you can pick whether you want ligatures and which `0`/`7` style you want. For coding, I have the typeface installed system-wide without ligatures and with one specific `0` style. However, with documents I'm writing in Typst, I want to use ligatures and a different `0` style. In order to do this, I either need to temporarily uninstall the font system-wide or run Typst in a separate environment that doesn't have access to my system fonts.

**Comment by laurmaedje** [comment]
Perhaps we should just change the default order? I think fonts specified via `--font-path` should definitely have precedence over any other fonts. Not sure what the ideal order for system and embedded fonts is.

I'd prefer not to add more configuration options unless absolutely necessary.

**Comment by TheLukeGuy** [comment]
That would solve the problem perfectly too, I think giving `--font-path` precedence is more intuitive anyway.

**Comment by laurmaedje** [comment]
Feel free to make a PR for that!
