### ISSUE TITLE
Spacing with Heading, Parbreak and List

### ISSUE THREAD

**Issue by antonWetzel** [typst/typst#1850]
### Description

The Kombination `Heading + Parbreak + List` has more spacing as only `Heading + List`, but `Heading + Parbreak + Text` has the same spacing as `Heading + Parbreak + Text`.

![a](https://github.com/typst/typst/assets/59712243/fba60da7-1229-4d80-94da-ddf9e0dca36b)
- First line is with lists
- Second line is with normal text
- First three columns are without a `Parbreak`
- Last three columns are with `Parbreak`

The difference is not large, but I think the spacing around the heading should not be changed by a `Parbreak`

### Reproduction URL

https://typst.app/project/ru4Vv4rYzptdpeFjgduVbI

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
The cause isn't the heading, but the list. If there isn't a paragraph break in front of it, the list gets `above` spacing of `par.leading`, to attach itself to the preceding paragraph. Opened https://github.com/typst/typst/pull/4396.
