### ISSUE TITLE
Feature request: improved `datetime` constructor behavior

### ISSUE THREAD

**Issue by ntjess** [typst/typst#1859]
### Description

Thanks for adding `datetime` utilities!

Can it be extended to consider the following scenario?

```typst
let date = datetime.today()

for ii in range(15) {
  date = datetime(year: date.year(), month: date.month() + ii, day: date.day())
  date.display()
}
```

I would hope this displays every month, and increments the year when months are $\geq 13$. However, months simply cap at 12. At the very least, it would be more intuitive what is happening if there was a `panic` on months greater than 12 (similar to how 0 is not allowed, and subtraction could also apply here).

It's simple enough to handle this in local code, but the challenge becomes larger with day increments flowing into months.

### Use Case

It is common, especially in tables with many dates, to have a fixed increment of dates appear. This would be a great way of programmatically handling that case. Even better if [`datetime.timedelta`](https://docs.python.org/3/library/datetime.html#timedelta-objects) or something similar made date arithmetic more strongly supported.

Note that python's `timedelta` doesn't allow incrementing months, since the amount of time is undefined. But, they do allow incrementing days, years, etc. Not sure if this caveat matters as much for typst's audience 🤷

**Comment by PgBiel** [comment]
Try something like this:

```
let date = datetime.today()
let month = date.month()

for ii in range(15) {
  let date = datetime(year: date.year() + calc.floor((month + ii) / 12), month: calc.rem(month + ii, 12) + 1, day: calc.min(28, date.day()))
  date.display() + [\ ]
}
```

**Comment by ntjess** [comment]
Right, it's certainly possible. My comment was more about modifying the `datetime` constructor to either `panic` on values >12 (as it does with a value of 0), or do this conversion behind the scenes.

**Comment by ntjess** [comment]
> day: calc.min(28, date.day())

Consider the case where `day()` started at 30, this would cause the day to be truncated, so more complex logic would be needed here as well

**Comment by PgBiel** [comment]
I think introducing some form of duration arithmetic mechanism would probably be more appropriate. A proper API for that would have to be discussed, however.



> > day: calc.min(28, date.day())
> 
> Consider the case where `day()` started at 30, this would cause the day to be truncated, so more complex logic would be needed here as well

Yes, I went with the least effort approach there. For a full solution, you'd need something like
`let max-days = (31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31)`
and then, inside the loop
`let new-month = calc.rem(month + ii, 12) + 1`
`let new-day = calc.min(max-days[new-month - 1], date.day())`

I agree some more convenient API would be better, however.

**Comment by laurmaedje** [comment]
There is an open PR that does something like this: https://github.com/typst/typst/pull/1843

**Comment by mattfbacon** [comment]
Yeah, adding a duration to a datetime (one of the features added by #1843) is much better than (re)implementing datetime logic. Very easy to make a mistake or forget a nuance.

**Comment by laurmaedje** [comment]
A duration type was merged.
