### ISSUE TITLE
abstract bug in ams template, preview won't display

### ISSUE THREAD

**Issue by jadebarclay** [typst/typst#1869]
### Description

Won't display preview until I delete line 194 from the ams `template.typ` file or put `"abstract"` instead of `abstract` at line 194.
With `abstract: true` or `abstract: false` it only displays preview if I delete/edit line 194, and always includes the abstract title and no abstract content either way.
![image](https://github.com/typst/typst/assets/65600156/ae001ea5-1b7a-4382-879c-014a7ad778ff)

This error first appeared when I had 3 names 2 spaces in the `authors: name:` yaml. It couldn't render the preview then either, and highlighted line 194 "cannot join content with boolean"
![image](https://github.com/typst/typst/assets/65600156/3c8eb8cd-2108-42d1-bd59-fc632253c6f7)

After I deleted/edited line 194 in the template, it displayed the preview with the full name and didn't have the "expecting keyed pair" error anymore. But if I undelete line 194 or remove the "" it won't preview and the "cannot join content with boolean" error returns.

Browser is Brave.

### Reproduction URL

https://typst.app/project/p_saVqxe2Ud8xahZw1fYjg

### Browsers

Chrome

### OS

Windows

**Comment by laurmaedje** [comment]
The idea is to write something like `abstract: [My Abstract Text ...]` and not `abstract: true`. The argument should contain the abstract's text and if it is a boolean instead, things go wrong.

**Comment by mattfbacon** [comment]
FYI, attempting to view the project gives "You do not have sufficient permissions".

**Comment by jadebarclay** [comment]
Sorry -- this should work https://typst.app/project/wxStrpRMmctFGAbY-DLEoS

**Comment by jadebarclay** [comment]
Ohhh... That makes sense. Just like pandoc without the 'abstract-section' lua filter. Thanks for the help!
