### ISSUE TITLE
Add line-height text parameter

### ISSUE THREAD

**Issue by nawordar** [typst/typst#1875]
### Description

Please add an equivalent to the CSS's [`line-height`](https://developer.mozilla.org/en-US/docs/Web/CSS/line-height) property to the `text` function. For example:

```
text(line-height: 1.5, lorem(30))

#set text(line-height: 1.5)
#lorem(30)
```

### Use Case

Some style guides require setting line height.

**Comment by Mc-Zen** [comment]
Hi, this is possible through [`par()`](https://typst.app/docs/reference/layout/par/) with the `leading` parameter

**Comment by nawordar** [comment]
Thank you
