### ISSUE TITLE
Allow setting a placeholder for an `image`

### ISSUE THREAD

**Issue by dsosec** [typst/typst#1877]
### Description

Currently, the [`image()`-function](https://typst.app/docs/reference/visualize/image/) returns an error, if the specified image is not found. This makes it difficult to make templates, which include certain images, but which are only available later on.

The image function should include a "placeholder" property, which takes a content as parameter, which is rendered only if the image is not found at the specified path.

The syntax should be as follows:

```
image("path/to/image.png", width: 100%, placeholder: [Make sure to add an image before submission.])
```

### Use Case

Users would be able to create documents and templates, where the document itself does not need to be modified to add an image to it. An image file only needs to be placed in the corresponding path for it to be rendered.

Otherwise, lacking an image file would mean the document fails to compile, rather than to display a placeholder.

**Comment by ondohotola** [comment]
I do something like

```typst
#let display = false
#align(center)[
   #figure(
      if (display) { image("image.jpg") }
      else { square(size: 5em, stroke: 2pt) },
      caption: if (display) {[Image]} else {[Image (obfuscated)]},
   ) <image>
]
```

**Comment by T0mstone** [comment]
If we really were to implement this, I would prefer a separate function that checks whether a file exists,
with which you can then make your own wrapper to `image`.

I'm not sure whether it's even a good idea tho. Making document output filesystem-dependent feels kind of wrong to me.

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/typst/issues/2025
