### ISSUE TITLE
Selectors composing and/or with before/after fail silently

### ISSUE THREAD

**Issue by damaxwell** [typst/typst#1881]
### Description

The following query
```
locate( loc => {
  query(heading.before(loc).or(figure.before(loc)), loc)
}
```
will always return nothing, even if there are headings or figures before the query.

The issue is that although `Introspector::query` has special code to handle `Before`/`After` cases (along special code for `Locate`), for all other selectors, including the logical ones, `Introspector::query` essentially punts to `Selector::matches`, which silently fails with `false` for `Before/After`.  So a `Before`/`After` nested behind an `And`/`Or` gets lost.

One way to fix this would be to keep the code already present in `Introspector::query` (and thereby keep the the efficient special cases for `Logical`, `Before` and `After`) but treat `And`/`Or` separately creating something like a "RealizedSelector" that for any of its (possibly deeply) nested  `Before`/`After` cases, caches the end/start index of the location to be matched against so that it can match element-wise and then combined normally like other selectors for the logical cases.

I could give this a shot, with the proviso that the PR would need a critical going over since I'm less than familiar with the introspection side of things and what performance hits matter and which don't.

### Typst version

- [ ] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This also came up on Discord very recently. Couldn't we fix it by simply handling And/Or through querying all their parts and then doing intersection/union? Equality can be checked through the element's location since it is unique.

**Comment by damaxwell** [comment]
Union seemed like a hassle since you also want to preserve ordering and can't just chain together the responses. This also seemed less efficient compared what `Selector::match` does, but my intuition may be wrong.

**Comment by laurmaedje** [comment]
Since all subqueries have the same order (the document order), fairly efficient union and intersection implementations should be possible. I think it might actually be more efficient than the what matches did.

**Comment by damaxwell** [comment]
I have a draft of the thing I proposed; it was straight forward. It's not polished, but tests pass. I could submit it as a draft as a straw man for comparison.

**Comment by laurmaedje** [comment]
Sure, we can compare both ways.

**Comment by damaxwell** [comment]
Oh, I think maybe I see the concern. There's a cache for queries. So when you defer And/Or to Selector::match currently you no longer take advantage of the cache. Hmm. I think what I've got is no worse than what's there now, and addresses the issue. But I see that it does not maximally take advantage of the cache.
