### ISSUE TITLE
Retrieve compiler version programmatically

### ISSUE THREAD

**Issue by 0ip** [typst/typst#1893]
### Description

I would like to be able to programmatically access the version of my typst compiler to be able to automatically insert this information into my document. For example like that: `#typst.version`.

### Use Case
Example: Insertion of the version string in the footer of a document: "Compiled with Typst 0.7.0".

**Comment by user202729** [comment]
This can be hacked together with #295 and some scripting, but built-in can't hurt.

There's also the argument "you want the compilation to be reproducible" against this feature, but different Typst versions are "incompatible" anyway.

For comparison: Python `sys.version`, Lua `_VERSION`.

**Comment by edgarogh** [comment]
This can also be useful when some non-essential visual features are only available starting from a specific version. I had this issue with `outline.entry` recently, which was only available in the IDE and standalone builds, but couldn't be used in VSCode with the extension. A `#show outline.entry: ... if ...` would've been a good compromise (well, only if `outline.entry` is lazily evaluated).

However, comparing software versions isn't very fun, so for my use-case, a higher-level function specifically designed to check if Typst's version is higher than a given one would be easier to work with than a string representation, although the initial use-case for having a displayable version still stands.
