### ISSUE TITLE
Clashing doc of `datetime.today`

### ISSUE THREAD

**Issue by LingkKang** [typst/typst#1895]
### Description

As stated on [Datetime Function – Typst Documentation](https://typst.app/docs/reference/construct/datetime/), `datetime.today()` function returns a `datetime` datatype:

```
datetime.today(offset: auto integer) -> datetime
```

And according to the doc on [diplay method](https://typst.app/docs/reference/types/datetime/#methods-display), datetime type should be displayed as `[year]-[month]-[day] [hour]:[minute]:[second]`. This is not the real result on latest Typst.

So why does the `datetime.today().display()` not print out current time? 

Why don't let `datetime.today()` just return a `date`?

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by OverHash** [comment]
`datetime.today()` returns a `Datetime::Date`, not a `Datetime::Datetime` (see [the source](https://github.com/typst/typst/blob/88bcb8769a07d1bad57b77fa9443b598fd1a6b61/crates/typst-cli/src/world.rs#L135-L149)). A `Datetime::Date` has a default display method of `[year]-[month]-[day]`).

I think the docs are pretty clear on this -- it says that `.today()` returns **the current date** (but does not say that it returns the time as well).

**Comment by PgBiel** [comment]
> Why don't let `datetime.today()` just return a `date`?

The type name is `datetime` regardless of whether or not it contains just `date`, just `time`, or both. In this case, it's returning a `datetime` with the time fields set to `none`. In other words, just because it's a `datetime`, doesn't mean it has both `date` and `time` (it's just the type's name).

**Comment by LingkKang** [comment]
Sure, now I understand.

Many thanks @OverHash and @PgBiel !
