### ISSUE TITLE
Support for logical page numbering

### ISSUE THREAD

**Issue by xkevio** [typst/typst#1899]
### Description

Logical page numbering supports the distinction between different page numberings, i.e. the beginning of a document (ToC, etc.) might use Roman numerals and will then switch to Arabic numerals.

This is then reflected in the reader's own page counter so that you can skip to page 2 and it will take you to the logical page with the Arabic numeral 2, which might have a completely different physical page number.
![image](https://github.com/typst/typst/assets/13004777/76115b86-f801-40b0-af1d-a84c6c99f2c1)

### Use Case

It can be congruent with the page numbers in an actual printed document. Furthermore, many academic templates make that distinction -- especially with title page & ToC vs. actual content.

**Comment by reknih** [comment]
Refer to section 12.4.2 of the PDF 1.7 spec ("Page Labels")

**Comment by andreasKroepelin** [comment]
This is also relevant for presentation slides where multiple PDF pages can belong to one slide when using overlays.

**Comment by mattfbacon** [comment]
I am interested in this for book typesetting with a table of contents and colophon.

**Comment by xkevio** [comment]
> I am interested in this for book typesetting with a table of contents and colophon.

I am currently working on it and will make a PR soon ^^
