### ISSUE TITLE
Will typst consider to support generating word(.docx) format?

### ISSUE THREAD

**Issue by drriguz** [typst/typst#190]
Hi,
I'm new to typst, I'm trying to find a tool for writing books that supports both pdf and word.
Currently I find [Quarto](https://quarto.org/) that meets my requirement.

What is the vision for typst? Will we consider to add other formats support except pdf?
Or just like Latex, pdf will be the final output?

Thanks!

**Comment by Enivex** [comment]
docx doesn't really serve the same role as pdf

I would suggest looking into https://github.com/jgm/pandoc/ if you want to produce word documents. They already have latex support, and seem to be planning to add typst support .

**Comment by drriguz** [comment]
> docx doesn't really serve the same role as pdf
> 
> I would suggest looking into https://github.com/jgm/pandoc/ if you want to produce word documents. They already have latex support, and seem to be planning to add typst support .

yeah, I've tried pandoc before. Also, Quarto uses pandoc. The problem is that generated docx and pdf are not consistent. Many publishers only accept docx format, that's the only reason that I want docx

**Comment by Dewyer** [comment]
Currently the compiler can't support any export formats that manage their own layout, ex: HTML. Word .docx files would probably fit this category and as such be dependent on the same compiler refactor that would allow HTML generation.

**Comment by drriguz** [comment]
Thanks, I agree. It will be nice if users can create their own output and reuse the compiler of typst, will that be hard(for both  typst and users)?

**Comment by fecet** [comment]
Hi, I am curious about typest, but I noticed that it does not have many of the essential features that quarto offers, such as markdown and tex math support. As a quarto user, what aspects of typest appeal to you?

**Comment by drriguz** [comment]
> Hi, I am curious about typest, but I noticed that it does not have many of the essential features that quarto offers, such as markdown and tex math support. As a quarto user, what aspects of typest appeal to you?

The most interesting thing that I think typest has is the ability of embedding code to control the output, which is hard to achive by Quarto.
Another similar approach I know is [PyLatex](https://jeltef.github.io/PyLaTeX/current/examples/basic.html), which uses python to "generate" a Latex file, but it uses standard python syntax and it's really hard to migrate from markdown to it.

**Comment by fecet** [comment]
> > Hi, I am curious about typest, but I noticed that it does not have many of the essential features that quarto offers, such as markdown and tex math support. As a quarto user, what aspects of typest appeal to you?
> 
> The most interesting thing that I think typest has is the ability of embedding code to control the output, which is hard to achive by Quarto. Another similar approach I know is [PyLatex](https://jeltef.github.io/PyLaTeX/current/examples/basic.html), which uses python to "generate" a Latex file, but it uses standard python syntax and it's really hard to migrate from markdown to it.

Thanks! Quarto was my favourite, but its develop seems a little slow, typst is indeed quite promise and exciting at this point.

**Comment by laurmaedje** [comment]
We plan to support HTML and via pandoc that could generate docx. Direct output to docx is not planned.

**Comment by jadebarclay** [comment]
> yeah, I've tried pandoc before. Also, Quarto uses pandoc. The problem is that generated docx and pdf are not consistent. Many publishers only accept docx format, that's the only reason that I want docx

In Quarto, you can make the pdf and docx consistent by changing the docx reference template (default mainfont for body: Latin Modern Roman, sansfont for headings: Latin Modern Sans) 

`quarto pandoc -o custom-reference-doc.docx \   --print-default-data-file reference.docx`
https://quarto.org/docs/output-formats/ms-word-templates.html

**Comment by drriguz** [comment]
Good news! Quarto 1.4 provides `typst` as a new output format.  Source: https://github.com/cscheid/2023-posit-conf-talk/blob/main/talk.qmd
