### ISSUE TITLE
Break/continue don't work while destructuring

### ISSUE THREAD

**Issue by TheLukeGuy** [typst/typst#1906]
### Description

If you try to use `break` or `continue` inside an expression whose result will be destructured, the code will fail to compile with "cannot (break|continue) outside of loop".

For example, this...
```typc
for num in (1, 2, 3) {
  let (word, roman) = if num == 1 {
    ("one", "I")
  } else if num == 2 {
    ("two", "II")
  } else {
    continue
  }
  [#word = #roman \ ]
}
```
...fails to compile with the following error:
```
error: cannot continue outside of loop
  ┌─ /broken.typ:7:4
  │
7 │     continue
  │     ^^^^^^^^
```

If the code is changed slightly to remove the destructuring, it compiles as expected:

<details>
  <summary>Similar code without destructuring that compiles successfully</summary>

  ```typc
  for num in (1, 2, 3) {
    let info = if num == 1 {
      ("one", "I")
    } else if num == 2 {
      ("two", "II")
    } else {
      continue
    }
    [#info.at(0) = #info.at(1) \ ]
  }
  ```

</details>

I would expect the first code example to compile correctly and for the `continue` statement to move the control flow to the head of the next loop iteration, bypassing the destructuring entirely. This is the same behavior as other languages like Rust.

<details>
  <summary>Equivalent Rust code that compiles successfully</summary>

  ```rust
  for num in [1, 2, 3] {
    let (word, roman) = if num == 1 {
      ("one", "I")
    } else if num == 2 {
      ("two", "II")
    } else {
      continue
    };
    println!("{word} = {roman}");
  }
  ```

</details>

### Reproduction URL

https://typst.app/project/r16rCxR4Yrog2lV1xgZkQj

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by bluebear94** [comment]
The issue is actually that `continue` returns a value of `none`, so your code tries to destructure `none` into a list.

Right now, `break` and `continue` are implemented by setting the `flow` field on the current `Vm`; perhaps these features would better be implemented as a return value; i.e. the return type from the various `evals` would look like

```rust
pub type EvalResult<T> = Result<T, EvalError>;
pub enum EvalError {
    Err(Box<Vec<SourceDiagnostic>>),
    ControlFlow(FlowEvent),
}
```

or perhaps

```rust
pub type EvalResult<T> = SourceResult<Result<T, FlowEvent>>;
```

**Comment by laurmaedje** [comment]
> perhaps these features would better be implemented as a return value; i.e. the return type from the various evals would look like

They were originally, but that doesn't play well with joining and set rules. The following test has some examples:
https://github.com/typst/typst/blob/2f81089995c87efdbce6c94bb29647cd1f213cfd/tests/typ/compiler/break-continue.typ#L115-L126

**Comment by laurmaedje** [comment]
There are still related errors like `#while true { if break {} }` which says `expected boolean, found none`, but it's less clear cut whether that should be considered a bug or just how the language works. It might be possible to switch to a return-based design if it properly accomodates set rules and joining. (Right now, propagating a break is manual and joining just works whereas in that design propagating would be the default and joining and set rules would need to take extra care. I remember that I tried implementing this, but I'm not sure anymore what exactly failed.)
