### ISSUE TITLE
Typst v0.7.0 breaking change for syntree package

### ISSUE THREAD

**Issue by MalteJanz** [typst/typst#1907]
## Description
After upgrading Typst from version v0.6.0 to v0.7.0 I noticed that my syntax tree lines were all over the place.

Used Package: https://github.com/typst/packages/tree/main/packages/preview/syntree/0.1.0

I haven't figured out the exact change that caused this problem, but I suspect it might be something that changed the behavior of the `place` or `measure` functions, or the line display in PDFs in general.

## Before (v0.6.0):
![image](https://github.com/typst/typst/assets/18661391/a90eff7e-7c29-4c3f-b566-fa8ec1042d5e)

## After (v0.7.0):
![image](https://github.com/typst/typst/assets/18661391/fe47d5cc-19a2-4157-9bf6-c09b8855bab8)

## Typst code
```typst
#import "@preview/syntree:0.1.0": syntree

#figure(
  caption: [Vereinfachter Syntaxbaum zu ...],
  syntree(
    nonterminal: (font: "Linux Biolinum"),
    terminal: (fill: blue),
    "[twig_block 
        [name my_block]
        [inner_twig
          [div_tag 
            [inner_tag
              [attribute
                [name class]
                [string
                  my-block-div
                  [twig_expression additional_class]
                ]
              ]
            ]
            [children
              [text hello]
            ]
          ]
        ]
      ]"
  )
) <valid_twig_example_tree>
```

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
Yeah, iirc the behaviour of `place` was changed. I think before it was always relative to the whole page, now it is only relative to the parent container.

**Comment by MalteJanz** [comment]
That would make sense. A notice for a breaking change in the [changelog](https://typst.app/docs/changelog/) would be nice then, because it only says:

> - Fixed positioning of [placed elements](https://typst.app/docs/reference/layout/place/) in containers

And how do you guys plan to handle breaking changes regarding the new package system? I guess the package would need to specify it's supported Typst version somehow. It is currently unclear to me which packages work on 0.7.0 and which only work on older versions🤔.

~Anyways I guess I need to forward this issue to the [package Repo](https://github.com/typst/packages) then? Or where are issues regarding specific packages collected 🙈 ?~ NVM I found the repository of the package and will create a issue there. Just another note: that repo link is also kind of hidden in the `typst.toml` file and it would be nice to have a link for that in the [package list](https://typst.app/docs/packages/)

**Comment by LaurenzV** [comment]
> That would make sense. A notice for a breaking change in the [changelog](https://typst.app/docs/changelog/) would be nice then, because it only says:

Yeah, I think they missed that.

> And how do you guys plan to handle breaking changes regarding the new package system? I guess the package would need to specify it's supported Typst version somehow. It is currently unclear to me which packages work on 0.7.0 and which only work on older versions🤔.

I'm not part of the founders' team, so I can't give you a definite answer. But they are aware that the current package system is very bare-bones and a lot of features are missing, they just wanted to get a working prototype out as quickly as possible. I'm sure that version locking (and a lot of other improvements to the package manageemnt system) will be implemented in the future once they have more resources. :)

**Comment by Enivex** [comment]
The old behavior of place was never the intended one, so to some extent it could be considered a bug fix. Though it's obviously unfortunate when things that rely on this behavior breaks.

**Comment by laurmaedje** [comment]
> A notice for a breaking change in the [changelog](https://typst.app/docs/changelog/) would be nice then, ...

Yeah, sorry about that, I forgot to add the "Breaking change" label.

> And how do you guys plan to handle breaking changes regarding the new package system? I guess the package would need to specify it's supported Typst version somehow. It is currently unclear to me which packages work on 0.7.0 and which only work on older versions🤔.

I don't see how a package could specify which _future_ versions it is compatible with, since they are not there yet when the package is released. Having a minimum required Typst version field would certainly be possible though.

I'm afraid there will be some ecosystem churn while we're making breaking changes in the future. For the web app, we'll definitely add an option to select which compiler version you want to use, so that people can upgrade individual projects when it suits them. (Automated?) migration hints would also be possible, but I'm not sure whether we'll have the resources to spend time on that.

**Comment by MalteJanz** [comment]
Thank you guys for the clarification.

>  don't see how a package could specify which future versions it is compatible with, since they are not there yet when the package is released. Having a minimum required Typst version field would certainly be possible though.

Yes, that's a tough problem but it's solvable with semantic versioning and strictly following it. So a package could specify it supports version `1.2.3  :=  >=1.2.3, <2.0.0` (just like Rust's crate dependencies) and each bug fix oder minor update (which only adds new features) are compatible. But I guess you guys need a stable version 1 first 😃.

Just my ideas for now, either:
- let the package creator specify for which typst version he tested the package version and show that on your package listing page: https://typst.app/docs/packages/ . This would help new users, who want to find a working package.
- move all packages under a new subfolder for typst 0.6 and let the creators publish new versions to a typst 0.7 folder and so on. This would help if you expect many breaking changes and your release schedule isn't too often

I will close this issue now, because the package itself needs an update.

Related issue for the package: https://github.com/lynn/typst-syntree/issues/1
