### ISSUE TITLE
Duplicated figure counter for customized figures in in #place blocks

### ISSUE THREAD

**Issue by Wowu** [typst/typst#1910]
### Description

I used sample customized figure from documentation: https://typst.app/docs/reference/meta/figure/#modifying-appearance

```typst
#show figure: it => align(center)[
  #it.caption |
  #emph[
    #it.supplement
    #it.counter.display(it.numbering)
  ]
  #v(10pt, weak: true)
  #it.body
]
```

Then I added 3 figures, with a single figure in a place block:

```typst
#outline(target: figure)

#figure(caption: "Sample figure 1", text("Figure content."))

#place[
  #figure(caption: "Sample figure 2", text("Figure content."))
]

#figure(caption: "Sample figure 3", text("Figure content."))
```

Displayed counters are wrong (`Figure 2.` is displayed two times), `#outline` displays them correctly though.

<img width="521" alt="image" src="https://github.com/typst/typst/assets/6865958/a34f746d-f6e9-4b9f-879d-ff713a59596e">

### Reproduction URL

https://typst.app/project/rQrYcfNZdQKjJ79KmAMxDK

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by bluebear94** [comment]
The counter display elements for Figures 2 and 3 are assigned the same location during realization. No idea what’s going on.

**Comment by bluebear94** [comment]
The problem in this example seems to be that

* Figures 1 and 3 are realized, but Figure 2 is not realized yet because it’s in a `place` block
* Figure 1 is laid out, causing the resulting frames to be visited by the locator
* Then Figure 2 is laid out, causing it to be realized when Figure 3’s frames have not yet been visited by the locator.

**Comment by laurmaedje** [comment]
Minimal example:
```
#show figure: it => it.counter.display()
#figure(none)
#block(figure(none))
#figure(none)
```
I have a hard time replicating this with plain (non-element) counters.

**Comment by Zheoni** [comment]
Also happens with a custom `#show figure.caption`. Here's an example: https://typst.app/project/rYEf1zXqjt_gB_UNPcoL4K
