### ISSUE TITLE
Write once variables

### ISSUE THREAD

**Issue by Beiri22** [typst/typst#1913]
### Description

As far as I understand, regular global variables cannot be set from functions, because this would 
allow for some kind of race conditions and ordering problems. But frequently Users do only set a value once inside a document. A state with update and display logic seem fairly heavy for this use case. So I thought about allowing to set those variables exactly once, as long as they are `none`. A second attempt would throw an error.

What do you think of that?

### Use Case

You have to set some globally available state at document begin (maybe inside the template), but don't want to use the display-function everytime you use it.

**Comment by Beiri22** [comment]
You could just check for `none` - but in the use case of global settings they should be set at start and used later, so "safe by design" ;-)

**Comment by laurmaedje** [comment]
That still requires evaluation to proceed in a certain order. I think most things currently done with state should switch to set rules once custom elements are available. Retrieving values from a set rule still requires context and is thus not completely freely scriptable, but it's much cleaner than states.

**Comment by Beiri22** [comment]
I have done a few experiments in a local checkout. As the captured variables are copied to the local scope, it's not trivial to implement it. Also the main problem for me was, that using a state and updating that state does create pagebreak (weak) where it shouldn't. So if #1346 will be solved, I could easily switch to states.

As for now, states seem cleaner to me; but if you like, please give an example, how you would use the custom elements as replacement for states.

**Comment by Beiri22** [comment]
Oh yes, and see #1928
