### ISSUE TITLE
regex within ends-with function does not match as expected

### ISSUE THREAD

**Issue by extua** [typst/typst#1914]
### Description

This typst function is supposed to match a string ending in numbers 10-19.

```typst
#let ending-onex(eleven-number) = {
  if eleven-number.ends-with(regex("1[0-9]")) {
    show: eleven-number + " ends in the pattern 1[0-9]"
  }
  else {
    show:  eleven-number + " does not end in the pattern 1[0-9]"
  }
}
```

Here's what I get passing in different variations:

```typst
#ending-onex("typst13") // typst13 ends in the pattern 1[0-9]

#ending-onex("typst113") // typst113 does not end in the pattern 1[0-9]

#ending-onex("typst1113") // typst1113 ends in the pattern 1[0-9]

#ending-onex("typst213") // typst213 ends in the pattern 1[0-9]

#ending-onex("typst2113") // typst2113 does not end in the pattern 1[0-9]
```

All of these _should_ match. Is it a problem with my regex?

The line which defines regex matching in `ends-with` is here:

https://github.com/typst/typst/blob/2f81089995c87efdbce6c94bb29647cd1f213cfd/crates/typst/src/eval/str.rs#L118

I encountered this issue while writing the [nth package](https://github.com/typst/packages/pull/78) and used `contains(regex(".*1[0-9]")` as a workaround.

### Reproduction URL

https://typst.app/project/wZNPvqu7mWsM1JlOz_X8DK

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Probably the ends_with implementation is flawed and the regex crate doesn't report overlapping matches.
