### ISSUE TITLE
Does it support to merge cells in table?

### ISSUE THREAD

**Issue by MaoSonglin** [typst/typst#192]
![image](https://user-images.githubusercontent.com/22848222/227127949-2a5f0193-b6e3-4e63-a3fc-bcf323e11a63.png)
I'd like add a table with layout like before, but I can find solution in docs.

**Comment by k12ish** [comment]
Thank you for writing an issue!

I think this issue is similar to #131, which involves merging cells horizontally. I'm not sure how I'd merge cells vertically however.

Hope that helps!

**Comment by laurmaedje** [comment]
Let's track it over #131.

**Comment by antoniprzybylik** [comment]
@MaoSonglin 
I think that this can help you: https://github.com/PgBiel/typst-tablex

Look at this example:
```typst
#import "@preview/tablex:0.0.9": tablex, colspanx, rowspanx

#tablex(
  columns: 3,
  colspanx(2)[a], (),  [b],
  [c], rowspanx(2)[d], [ed],
  [f], (),             [g]
)
```

**Comment by Hammerklavier-cn** [comment]
Typst's native table already supports merging cells

```typst
#table(
  columns: 3,
  table.header([], [h1], [h2]),
  [r1], table.cell(colspan: 2)[c1, c2],
  ....
)
```

You can also merge cells vertically by replacing `colspan` with `rowspan`.
