### ISSUE TITLE
A "plus minus" in math mode.

### ISSUE THREAD

**Issue by water-mizuu** [typst/typst#1924]
### Description

In LaTeX, we can use ± by typing `\pm`. In math mode, I don't think there's an option for this glyph. For now I am using `underline(plus)`

### Use Case

Math and typing algebra.

**Comment by freundTech** [comment]
In math mode you can write
`plus.minus`.

Outside of math mode you can get it with `#sym.plus.minus`.

You can find a [list of supported symbols here](https://typst.app/docs/reference/symbols/sym/).

**Comment by water-mizuu** [comment]
Ah, thank you! That makes sense why I can't find it. I'm closing this issue now.

**Comment by wmstack** [comment]
There seems to be an issue with the `plus.minus` symbol. It is very off centre with respect to what's expected in LaTeX:
| Typst | LaTeX |
|--------|--------|
|<img width="471" alt="image" src="https://github.com/user-attachments/assets/71484169-036a-4872-83c2-d0b42731ea0c"> |<img width="795" alt="image" src="https://github.com/user-attachments/assets/cfbe0536-3571-4795-ad7b-5a021a7eef09">|
| `plus.minus` is very uncentered | `\pm` is somewhat centered |
