### ISSUE TITLE
Diagnostic-format short  linux file name stray slash

### ISSUE THREAD

**Issue by KillTheMule** [typst/typst#1937]
### Description

When using ` --diagnostic-format short`, the name of the file producing an error seems to start with a `/` on linux, see this shell session:

```sh
~/typst$typst compile --diagnostic-format short ./kl4_1.typ
/kl4_1.typ:1:21: error: unknown variable: width
```
While this gives enough of an idea of the file involved, it confuses the heck out of (neo-)vim, e.g. when using https://github.com/kaarmu/typst.vim, and probably everything else that automatically tries to determine the file, because that's just the wrong path. It should be either `kl4_1.typ` or `./kl4_1.typ` or maybe the full path.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Thanks for the report, that's the result of a more recent changes. The display path is the path in Typst's "virtual" project file system. I think the sanest way would be to print the path relative the CLI's working direcitory.

**Comment by KillTheMule** [comment]
> I think the sanest way would be to print the path relative the CLI's working direcitory.

Sounds fine to me :+1:
