### ISSUE TITLE
Disallow word break on the word `C++`

### ISSUE THREAD

**Issue by JCGoran** [typst/typst#1941]
### Description

When using the word `C++` in content which is justified, the word can get broken as `C+\n+`, as shown in this example:

```plaintext
#set par(justify: true)
#set page(margin: (left: 10cm, right: 5cm))
Python Cython Rust Mathematica C++
```

This renders as:
![image](https://github.com/typst/typst/assets/25671271/110ed35a-2119-4a1c-911a-b33606d6173b)

A workaround I use involves wrapping the word in a `box` (or adding `#show "C++" : name => box(name)` so it works without modifying the content):

```plaintext
#set par(justify: true)
#set page(margin: (left: 10cm, right: 5cm))
Python Cython Rust Mathematica #box[C++]
```

which looks about right:
![image](https://github.com/typst/typst/assets/25671271/36638e9b-15d2-48ee-ac17-bb159d90ebd2)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by T0mstone** [comment]
I think you can do this with a show rule:
```
#show "C++": box
```

**Comment by Enivex** [comment]
Wrapping it in a box is the correct solution here. I don't view this as a bug.

**Comment by JCGoran** [comment]
> Wrapping it in a box is the correct solution here. I don't view this as a bug. C++ is not an English word.

Understandable, but it's still the name of a well-known programming language, and having it typeset incorrectly — especially in another markup/programming language — in certain edge cases seems a bit strange. Of course, if there isn't a precedent for it (i.e. there aren't similar exceptions for non-word strings), I'm all for using the `box` workaround, and consequently closing this as resolved.

**Comment by gfpj** [comment]
When we assume the following example

```typst
#set text(lang: "en")
#set par(justify: true)
#set page(margin: (left: 10cm, right: 5cm))
Python Cython Rust Mathematica C++
```

we can say for sure, this is a bug. There are two problems:
1) it seems, typst does not recognize `lefthyphenmin` and `righthyphenmin` like TeX does. In the example above we would have `righthyphenmin=1` which is probably not a good value.
2) hyphenation between `+` and `+` is unexpected.
Now, one could say: "we just use the same hyhenation patterns like TeX" does, which is correct. But the TeX patterns are created under the assumptions of `lefthyphenmin` and `righthyphenmin` and only work good if this is checked manually.

Solution: Typst should check `lefthyphenmin` and `righthyphenmin`. There are other issues where this is the same underlying problem.

**Comment by laurmaedje** [comment]
Copying my response from https://github.com/typst/typst/issues/1389:

Typst does respect the hyphenmins. The problem is rather that it hyphenates the wrong strings. Rather than hyphenating proper words, it hyphenates anything between two break opportunities. Sometimes that happens to not be a proper word and the hyphenator doesn't deal well with that. Still a bug that needs fixing of course. Just wanted to point that out.

**Comment by laurmaedje** [comment]
Looking at this again, there is actually no hyphenation at all going on here and hyphenmins do not come into play at all (there are no hyphens after all). There is simply a Unicode linebreak opportunity between two pluses according to UAX #14. Not much we can do from our side. (I don't really want to start accumulating hacky exceptions to UAX #14.)

**Comment by Caellian** [comment]
For future reference, if you want to avoid having to wrap it with box everywhere, use:
```typst
#show "C++": box[C++]
```
