### ISSUE TITLE
Consider parsing YAML integer keys

### ISSUE THREAD

**Issue by edgarogh** [typst/typst#1945]
### Description

As stated [in the docs](https://typst.app/docs/reference/data-loading/yaml/), Typst's `yaml` function completely ignores integer keys when parsing mappings.

According to the spec, this is valid:
```yaml
values:
  0: "zero"
  1: "one"
  2: "two"
```

Due to the fact that Typst dictionaries only support string keys, the integer keys would have to be rendered as a string, probably in decimal. This causes a small loss of information, but it's still better than throwing away entire mappings just because Typst wants keys to be strings internally.

### Use Case

I'm parsing files that follow a very specific specification (a subset of yaml) for another tool. Ideally, I'd like to avoid requiring any preprocessing on the yaml files, as this would add a lot of friction to my library.

**Comment by laurmaedje** [comment]
Fixed via #1935.
