### ISSUE TITLE
[FEATURE] columns(tight : bool, ...)

### ISSUE THREAD

**Issue by astrale-sharp** [typst/typst#1949]
### Description

I'd like the option for the columns automatically break to be tight.

right now if I use this code 
```
#set page(width: 200pt, height : 100pt)
#columns(2, lorem(15))
```
I get 
![image](https://github.com/typst/typst/assets/53686698/fd1a82cd-edc2-445e-a96a-3d945ad664ff)

when I'd like something with this:
![image](https://github.com/typst/typst/assets/53686698/a0b6cc33-3c54-40f6-9320-3129673c877b)

### Use Case

.

**Comment by PgBiel** [comment]
Possible duplicate of https://github.com/typst/typst/issues/466

**Comment by astrale-sharp** [comment]
Absolutlt, thank you!
