### ISSUE TITLE
Hanging-indent doesn't work correctly for lists inside term lists

### ISSUE THREAD

**Issue by Enivex** [typst/typst#1955]
### Description

The following

```
#set page("a7")
/ Hello:
  - #lorem(20)
  - World
```
results in
![image](https://github.com/typst/typst/assets/2191754/027a3393-ceae-4737-aafa-591ecd952d2a)

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
I can add that this is related to `hang-indent`. It doesn't seem like the lines that include the bullet points are indented at all.

**Comment by laurmaedje** [comment]
I think this was fixed.
