### ISSUE TITLE
Nested show rule slows down compiler (20-25x slowdown)

### ISSUE THREAD

**Issue by BlueskyFR** [typst/typst#1958]
### Description

The compilation takes from 1 to 2 seconds for the example below when typing text at the end.

It seems related to the nested show rule : it only happens when both `heading` and `par()` are present.
It may be because the nested show rule brakes memoization in some way?

> if you remove the justify paragraphs, it still becomes a bit slower (because memoization doesn't work properly with nested show rules), but you just don't notice it that much because the compilation from scratch is still pretty fast - @lauuuuuuuuu on Discord

A fix seems to be moving the heading show rule outside the function

You can try this in the web app to see it in effect

The first compilation is always of about 1s while subsequent one are slowed by around 20-25x with the bug

```rust
#show: body => {
  show heading: it => it.body
  
  body
}

#set par(justify: true)

#lorem(10000)

Try typing text here and watch how long the pdf preview takes to refresh
```

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by BlueskyFR** [comment]
@laurmaedje it did not assign to this issue idk why

**Comment by LaurenzV** [comment]
The issue in general seems to be that nested show rules don't work properly with memoization (even though none of the show rules applies). Consider this document for example:

```
#lorem(30000)

Try typing text here and watch 
how long thaa pdf preview takes to refresh
```

The first compilation takes around 115ms when running with `typst watch`, all subsequent compilations only take around 70ms.

While in the following code:
```
#show: body => {
  show heading: it => it.body
  body
}

#lorem(30000)

Try typing text here and watch 
how long thaa pdf preview takes to refresh df sd
```

The first compilation takes around 115ms as well, but subsequent compilations take even longer around 140ms. The reason why above it is even worse is that justifying paragraphs seems to be a very expensive operation, so the lack of memoization becomes even more apparent.

**Comment by laurmaedje** [comment]
For those that are interested what happened here: 

The heading show rule is defined by a closure that can capture its environment. This closure becomes part of the style context Typst uses for the remaining document. This mean that when the closure changes, the cached results for the document become invalidated. 

Of course, this closure shouldn't change if you just type in the body of the document though. Here comes the problem: Typst determines what a closure captures by walking the syntax tree of its body and finding variables that are referenced. This capturing code was at fault here. It saw the `body` in `it.body` and then proceeded to capture the `body` variable from the top-level show rule. As a result, the closure _did_ change for every thing you type. 

Had it really used the `body` variable, that would also been correct behaviour. But it didn't. The fix in https://github.com/typst/typst/commit/b7430f6da01550d8388d6a3bcccf0ef0aca9130c fixes the faulty logic in the closure capturing code.

**Comment by Myriad-Dreamin** [comment]
@laurmaedje maybe reopen it? though unfortunately.

**Comment by LaurenzV** [comment]
Why? Isn't this fixed already?

**Comment by laurmaedje** [comment]
@Myriad-Dreamin I'm also interested why this should be reopened. If it's because of the bug with capturing that was later discovered: Fixing that didn't mean regressing this. Originally closures captured too much (hence the slowdown), and then briefly too little (the bug). But now it should be correct.
