### ISSUE TITLE
list (non-tight) spacing requires blank line between list elements

### ISSUE THREAD

**Issue by dvdvgt** [typst/typst#1959]
### Description

# Description
List have the settable option `spacing` which specifies the spacing between list elements of non-tight lists. Judging by the ![documentation](https://typst.app/docs/reference/layout/list/) it seems to be canonical to not separate each list elements with a blank line. Yet, list spacing is not applied unless two list elements are separated by a blank line.

# Example

```
#set list(spacing: 1cm, tight: false)
- 1
- 2
- 3
- 4
```

<img width="299" alt="image" src="https://github.com/typst/typst/assets/40773635/9dbfe701-0f3f-4ea7-916f-f772cb7a524d">

```
#set list(spacing: 1cm, tight: false)

- 1

- 2
- 3
- 4
```

<img width="415" alt="image" src="https://github.com/typst/typst/assets/40773635/f1c9d147-25b2-43a5-9636-a19562a70a9a">

(tested on the main branch on commit 2f810899)

# Expected behaviour

This seems inconsistent to me. Either you need to separate all list elements by a blank line for the custom spacing to apply, or none. Needing to separate one or more seems weird to me. I would have expected the spacing to be applied in the first example as well (the one with no separating blank lines).

What are your thoughts on this?

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
The idea is that a tight list (no blank lines) has exactly the normal line spacing while a wide (non-tight) list has custom spacing. But it has caused quite a lot of confusion, so I'm open to changing how list spacing and tight/non-tight works.

**Comment by dvdvgt** [comment]
> The idea is that a tight list (no blank lines) has exactly the normal line spacing while a wide (non-tight) list has custom spacing. But it has caused quite a lot of confusion, so I'm open to changing how list spacing and tight/non-tight works.

We could just apply the ["`auto`"](https://typst.app/docs/reference/layout/list/#parameters-spacing) spacing to all lists (regardless of separating blank lines), unless set otherwise. Thereby, one would lose the ability to have both tight and non-tight lists simultaneously without using `#set` in between. I am not sure if this feature is even used too often, however.

If we choose to keep both tight and wide (non-tight) lists, I would at least advocate for forcing blank lines in between each list element of wide lists. I find this to be more consistent.

**Comment by laurmaedje** [comment]
I'm not sure whether tightness really depends on the document or rather on the specific list. I tend to use tight lists if the items are words, phrases or short sentences and wide lists if the items are one or even multiple paragraphs.
