### ISSUE TITLE
Feature Request: Allow Import Template from Outer Folder Again

### ISSUE THREAD

**Issue by ivaquero** [typst/typst#1960]
### Description

This is not a new feature. Importing template from outer folder is allowed before 0.7.0. But now when doing this (using `--root`), it says

```console
error: input file must be contained in project root.
```

https://github.com/nvarner/typst-lsp/issues/255

### Use Case

In the following scenarios, modifying a template can be a tedious job

- When more than one projects use the same template
- When a template consists of more than one file

**Comment by frozolotl** [comment]
This is intentional behavior to increase the security against rogue packages.

The intended way of sharing code between multiple projects locally is to use [local packages](https://github.com/typst/packages#local-packages). See the link on how to use them.

**Comment by ivaquero** [comment]
Thanks for your answer. I will try this.

**Comment by laurmaedje** [comment]
> This is intentional behavior to increase the security against rogue packages.

Mini-nit: It's not so much against rogue _packages_ (as these are completely encapsulated) and more against potentially rogue _documents_ downloaded from somewhere.

Local packages are the way to go for sharing between arbitrary projects but you can also use `--root ..` (or even `--root ../..`) to increase the scope of what Typst consider the "project", so to speak.

**Comment by PgBiel** [comment]
As an addendum, you can use `--root` with your project's top-level directory if you are sharing templates among multiple typst "sub-projects", for instance.

(You can also abuse the feature and use `--root /` to access any file in the system, but I would recommend against that, as it'd allow any code you run to read any file in your system and, thus, possibly append its contents to the document without your knowledge.)

**Comment by ivaquero** [comment]
This works. Thank you!

**Comment by ivaquero** [comment]
> Local packages are the way to go for sharing between arbitrary projects but you can also use --root .. (or even --root ../..) to increase the scope of what Typst considers the "project", so to speak.

This works, thank you!
