### ISSUE TITLE
Non-breaking space character not parsed if inserted via a show rule

### ISSUE THREAD

**Issue by owiecc** [typst/typst#1972]
### Description

This `~` is converted to a non-breaking space:
```
The~Beatles
```

This `~` is **not** converted to a non-breaking space:
```typst
#show "The ": "The~"
The Beatles
```
instead the `~` character is inserted verbatim. 

### Reproduction URL

https://typst.app/project/rk83Dz-2jRGi2tAkmmd7OG

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by frozolotl** [comment]
This is intended behavior. Strings, such as `"The~"` are always entered verbatim.
You really want to insert content:
```typ
#show "The ": [The~]
The Beatles
```

Within content blocks (enclosed in `[…]`), you can use all the usual typst markup syntax.

**Comment by laurmaedje** [comment]
This is indeed working as intended.

**Comment by owiecc** [comment]
Then, I think, the docs should be more explicit about this. The [styling section](https://typst.app/docs/reference/styling/) refers to text transforms: 

> Text: show "Text": .. 
>  Style, transform or replace text.

and gives only this example: 

```typst
#show "badly": "great"
```

**Comment by laurmaedje** [comment]
Fair enough. We should update it to make that clear that arbitrary content can be on the right hand side (like for any other show rule).
