### ISSUE TITLE
Short and beautiful rendering of DOIs.

### ISSUE THREAD

**Issue by internettechnik** [typst/typst#1974]
### Description

It is NOT necessary to render https://doi.org/19.1145/1357054.1357273 for bibliography entries.
Only the number 19.1145/1357054.1357273 (with clickable link) is sufficient.

### Use Case

The biblio-entries would be shorter and better readable. PDFs would still provide clickable links.

**Comment by Enivex** [comment]
This is covered by https://github.com/typst/typst/issues/942

**Comment by laurmaedje** [comment]
As this is probably typically something the citation style defines, I would agree that it is covered by #942.

**Comment by internettechnik** [comment]
```typst
// workaround: keeps link in pdf intact, but replaces https://doi.org/ with DOI
show "https://doi.org/": w => { // handle DOIs
  	[DOI:]+str.from-unicode(160) // 160 A0 nbsp
}
```
