### ISSUE TITLE
Support for formatting within bibliography entries inside *.bib files

### ISSUE THREAD

**Issue by internettechnik** [typst/typst#1975]
### Description

Bibliography would look even nicer, if entries would support typst formatting:

- For example superscript: 
    - 7#super[th] International Conference on ... 
- For example non-breaking spaces with tilde `~`:
   - In Proc.~26th Annual Conference ...   

(Note: LaTeX did support use of formatting within bib entries, such as \nth{2} )

### Use Case

Users would get a more beautiful and much better readable bibliographies.

**Comment by Enivex** [comment]
https://github.com/typst/typst/issues/942

(This would then easily be achievable with eval())

**Comment by wangzcl** [comment]
@Enivex 

> (This would then easily be achievable with eval())

I am using typst and I met this problem. Could you please give an example of how to use `eval` in `.bib` files? Here is my bibliography, and I want the "2" in "CO2" to be subscribed:

```
@article{shaughnessy2021,
  title = {Machine Learning Deciphers CO2 Sequestration and Subsurface Flowpaths from Stream Chemistry},
  author = {Shaughnessy, Andrew R. and Gu, Xin and Wen, Tao and Brantley, Susan L.},
  year = {2021},
  month = jun,
  journal = {Hydrology and Earth System Sciences},
  volume = {25},
  number = {6},
  pages = {3397--3409},
  publisher = {Copernicus GmbH},
  issn = {1027-5606},
  doi = {10.5194/hess-25-3397-2021},
  urldate = {2023-10-13},
  langid = {english}
}
```

**Comment by Enivex** [comment]
> @Enivex 
> 
> > (This would then easily be achievable with eval())
> 
> I am using typst and I met this problem. Could you please give an example of how to use `eval` in `.bib` files? Here is my bibliography, and I want the "2" in "CO2" to be subscribed:
> 
> ```
> @article{shaughnessy2021,
>   title = {Machine Learning Deciphers CO2 Sequestration and Subsurface Flowpaths from Stream Chemistry},
>   author = {Shaughnessy, Andrew R. and Gu, Xin and Wen, Tao and Brantley, Susan L.},
>   year = {2021},
>   month = jun,
>   journal = {Hydrology and Earth System Sciences},
>   volume = {25},
>   number = {6},
>   pages = {3397--3409},
>   publisher = {Copernicus GmbH},
>   issn = {1027-5606},
>   doi = {10.5194/hess-25-3397-2021},
>   urldate = {2023-10-13},
>   langid = {english}
> }
> ```

I said that it would be possible _if_ we had that. We don't, but in your specific case you have two options:

- Use the unicode character ₂ (U+2082)
- Use math

**Comment by wangzcl** [comment]
> > @Enivex
> > > (This would then easily be achievable with eval())
> > 
> > 
> > I am using typst and I met this problem. Could you please give an example of how to use `eval` in `.bib` files? Here is my bibliography, and I want the "2" in "CO2" to be subscribed:
> > ```
> > @article{shaughnessy2021,
> >   title = {Machine Learning Deciphers CO2 Sequestration and Subsurface Flowpaths from Stream Chemistry},
> >   author = {Shaughnessy, Andrew R. and Gu, Xin and Wen, Tao and Brantley, Susan L.},
> >   year = {2021},
> >   month = jun,
> >   journal = {Hydrology and Earth System Sciences},
> >   volume = {25},
> >   number = {6},
> >   pages = {3397--3409},
> >   publisher = {Copernicus GmbH},
> >   issn = {1027-5606},
> >   doi = {10.5194/hess-25-3397-2021},
> >   urldate = {2023-10-13},
> >   langid = {english}
> > }
> > ```
> 
> I said that it would be possible _if_ we had that. We don't, but in your specific case you have two options:
> 
> * Use the unicode character ₂ (U+2082)
> * Use math

Wow, sorry for my misunderstanding. Thank you for your reply! (It seems that math environment `$$` does not work in bibliography, but the unicode works).

**Comment by YDX-2147483647** [comment]
There's a “native” way to do this. According to [hyagriva docs](https://github.com/typst/hayagriva/blob/926a215b34a7d5acbdbca903f8f80b03830323b8/docs/file-format.md?plain=1#L441-L442), we can include [mathematical markup evaluated by Typst](https://typst.app/docs/reference/syntax/#modes) by wrapping it in dollars.

```typst
#show bibliography: body => {
  show math.equation: set text(font: (
    name: "Libertinus Serif",
    covers: regex("."),
  ))
  body
}

#bibliography("ref.bib", full: true)
```

```bibtex
@article{key,
  title = {A$#super[super]$},
}
```

<img width="300" alt="Image" src="https://github.com/user-attachments/assets/87474a00-87b8-49dc-80db-ee4529784328" />

However, the default font in math equations is _New Computer Modern Math_, and we have to override it.
When overriding it, [`covers`](https://typst.app/docs/reference/text/text/#parameters-font) is necessary, or Typst will try to extract math metrics from the first font without `covers`, and raise warnings like _current font does not support math_.

**Comment by jonas-schulze** [comment]
My research group has a shared BibTeX (no BibLaTeX) database that I would like to re-use for Typst. Here, `~` only ever occurs as a non-breaking space, so this works fine:

```typ
// Translate non-breaking spaces from LaTeX to Typst.
#show bibliography: body => {
  show "~": [~]
  body
}
```

I also tried to be agnostic to escaping, i.e., ignoring `\~`, but failed. The following also captures `A\~{}B` even though it should not:

```typ
#show bibliography: body => {
  show regex("[^\\\\]~"): it => {
    it.text.slice(0, -1)
    [~]
  }
  body
}
```
