### ISSUE TITLE
Support short captions (titles) appearing in list of Tables/Listings/Figures

### ISSUE THREAD

**Issue by internettechnik** [typst/typst#1976]
### Description

Support for long AND (optional) short captions for figures. Often, longer captions (whole sentences explaining a figure) are needed. 

In LaTeX figures could have long and short captions/titles. The short one was shown in the List of Figures, the long one directly (beneath) a figure.

### Use Case

Table of Contents, List of Figures, List of Tables, List of Listings would look much better.

**Comment by Enivex** [comment]
Duplicate of https://github.com/typst/typst/issues/1295
