### ISSUE TITLE
Add reverse method on strings

### ISSUE THREAD

**Issue by owiecc** [typst/typst#1983]
### Description

A reverse method on strings would be nice to have: 
```typst
#"ax̂e".rev()
```
doing the same as:
```typst
#"ax̂e".clusters().rev().join()
```
producing `ex̂a`

### Use Case

Reversing strings.

**Comment by owiecc** [comment]
Maybe add a [good first issue](https://github.com/typst/typst/labels/good%20first%20issue) label?

**Comment by xkevio** [comment]
This can be closed, I should have used the way "Closes" in my PR before it got merged so this would have happened automatically.

**Comment by Enivex** [comment]
Resolved by https://github.com/typst/typst/pull/2013
