### ISSUE TITLE
Umlauts with \u \U for ü Ü ...

### ISSUE THREAD

**Issue by Proliecan** [typst/typst#1984]
### Description

Latex has this nice syntax where it renders all `"u`s as `ü`s.
As of now, typst does to my knowledge not include any way to write umlauts without having them on the keyboard.
A possible syntax to enable that could be `\u` for `ü`, `\s` for `ß` and so on.

### Use Case

This way, Users who don't have umlauts on their keyboard can still write German stuff fast and without too much distractions -- just like with LaTex.

**Comment by Enivex** [comment]
Duplicate https://github.com/typst/typst/issues/833
