### ISSUE TITLE
Ability to Have 1 Document Different Media Types and Uses

### ISSUE THREAD

**Issue by sirinath** [typst/typst#1991]
### Description

Currently, there are many screen sizes (landscape, portrait, wide screen), device types, display system (screens, printout, projects, tvs), and uses like article, presentation, handout, speaker notes, etc.

It will be great if there is a way to have 1 document and create custom version without reediting it. Certain items may get reorganised and the layout may change also items may get omitted or added. All this need to be done without duplication within the document too.

### Use Case

Produce best option for:
- printouts
- different screen sizes
- presentation
- handouts
- speaker notes
- publishing 

This way one can have one master document from which one can generate reach variation.

**Comment by laurmaedje** [comment]
You can achieve something like this by having a variable that defines your output kind and then having `if` conditions to customize parts of your document based on this. #295 could also be relevant for passing in the output kind. If you want something beyond that, you would need to be more specific. As is, this issue isn't really actionable.

**Comment by sirinath** [comment]
What I had in mind is something similar to (1) style sheets and (3) media queries with (3) passed parameters.

**Comment by laurmaedje** [comment]
Different style sheets can be realized as different functions with different show and set rules. Media queries aren't really that applicable at the moment, but if you know the page size in advance, you can realize them with normal if.

**Comment by sirinath** [comment]
Media queries in the sense I want to generate multiple from one master document for multiple purposes and sizes.

One use case is to have one document which has:
- hand out for talk
- slides
- cue cards / speaker notes for slides
In one document.

**Comment by laurmaedje** [comment]
Yeah, I understand. You can do that with `if`.
