### ISSUE TITLE
Incorrect counter values in `counter` documentation

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#1993]
https://typst.app/docs/reference/meta/counter/#time-travel:

![image](https://github.com/typst/typst/assets/37143421/73c1372a-c6cd-4584-8fed-eec47d186cc3)

![image](https://github.com/typst/typst/assets/37143421/bef11262-1c05-40dd-96ac-b429f7b82617)

`1`, `4` and `6` should be `0`, `3` and `5` respectively. Otherwise, instead of clearing things up, it only confuses the reader even more.

**Comment by laurmaedje** [comment]
good catch, this broke when counters changed at some point. you could make a PR if you'd like to. the relevant file is `crates/typst-library/src/meta/counter.rs`.

**Comment by Andrew15-5** [comment]
Bruh: https://github.com/typst/typst/actions/runs/5977192017/job/16216617180?pr=2002

![image](https://github.com/typst/typst/assets/37143421/ce36a1fa-ff9f-4e1d-8c3a-cfe696d50082)

Is this supposed to happen?

**Comment by xkevio** [comment]
> Bruh: https://github.com/typst/typst/actions/runs/5977192017/job/16216617180?pr=2002
> 
> ![image](https://user-images.githubusercontent.com/37143421/263305518-ce36a1fa-ff9f-4e1d-8c3a-cfe696d50082.png)
> 
> @laurmaedje, is this supposed to happen?

This is now fixed if you synchronize your PR branch.

**Comment by Andrew15-5** [comment]
So was it a bug then? Because I applied the patch on top of the latest `main` commit.

**Comment by xkevio** [comment]
Rust updated to 1.72 which introduced formatting for `let .. else` statements and the CI checked for those but it hadn't been applied to all instances in Typst yet.

**Comment by Andrew15-5** [comment]
M'kay.

**Comment by Andrew15-5** [comment]
Fixed in #2002.
