### ISSUE TITLE
Wrong formatting of page number

### ISSUE THREAD

**Issue by AdrienVannson** [typst/typst#1994]
### Description

If we compile the following document:
```
#set page(numbering: "1", number-align: center)

*A*
```
The page number is displayed in bold, which is not expected.

The bug appears both on the online IDE and with the nightly version (the code from the `main` branch of the github repository)

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Duplicate of https://github.com/typst/typst/issues/241

**Comment by AdrienVannson** [comment]
I didn't see this issue when searching, sorry for the duplicate.

**Comment by PgBiel** [comment]
it's fine
