### ISSUE TITLE
Incorrect link in `integer` documentation

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#1995]
https://typst.app/docs/reference/types/integer/:

> You can convert a value to an integer with the [float](https://typst.app/docs/reference/construct/float/) function.

A value? A what value? Any number?

I assumed that `float` is a value (number), so I probably can convert `float` to an `integer` with... `float()`...

It should link to [`int()`](https://typst.app/docs/reference/construct/int/) instead.

**Comment by Andrew15-5** [comment]
I'm not sure what you are talking about, since there are no `docs/types.md` in the repo and there is only one place with `You can convert a value to an integer` and it refers to the correct function:

https://github.com/typst/typst/blob/a8d3ab3fb0f65f733695ed03a2869726a98cffd7/docs/reference/types.md?plain=1#L49

**Comment by PgBiel** [comment]
Sorry, I didn't remember the exact path of the `types.md`. Indeed, it is inside the `reference` subfolder.

> and it refers to the correct function

This suggests to me that it was fixed very recently, and thus not yet released, explaining why it's wrong in the website. Indeed, it was fixed by this PR https://github.com/typst/typst/pull/1894. So you should be able to close this issue now :D

**Comment by Andrew15-5** [comment]
2 weeks ago? How frequently does the website's content updates? Once per release?

**Comment by PgBiel** [comment]
> 2 weeks ago? How frequently does the website's content updates? Once per release?

usually, yes

hotfixes can be made, but they're rare

**Comment by laurmaedje** [comment]
To give a bit of background: To deploy fixes immediately they would need to be backported to the previous release. We can't deploy the full changed documentation because there might be many unreleased changes in it.

**Comment by Andrew15-5** [comment]
So it's the nature of revision control system: there might be doc commits for which implementation is not yet committed.
