### ISSUE TITLE
Hyperbolic functions shouldn't take angles as input

### ISSUE THREAD

**Issue by Enivex** [typst/typst#1998]
### Description

Currently the hyperbolic functions accept angles as inputs

https://typst.app/docs/reference/calculate/cosh/
https://typst.app/docs/reference/calculate/sinh/
https://typst.app/docs/reference/calculate/tanh/

"Calculates the hyperbolic cosine of an angle. When called with an integer or a float, they will be interpreted as radians."

While _technically_ the number can be interpreted as something called the [hyperbolic angle](https://en.wikipedia.org/wiki/Hyperbolic_angle), this is connected to the areas for hyperbolas, and not the length of circular arcs (like the angles you are familiar with). It's therefore senseless to accept degrees as input for these functions.

(As an aside, this is why the hyperbolic inverse function is _ar_|cosh (for area) and not _arc_|cos (for arcus))

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Fixed via https://github.com/typst/typst/pull/2072
