### ISSUE TITLE
delim not work in function mat

### ISSUE THREAD

**Issue by Grobycn** [typst/typst#200]
Hi, according to https://typst.app/docs/reference/math/mat/, matrix can have different delimiter.
But it seems not work. No matter what delim is, the delimiter is always parentheses.

See my toy project:
https://typst.app/project/rNVhi8iHmSDRa5_V9sYpNB

**Comment by jgm** [comment]
I'm having the same issue. To be more specific, my expectation was that
```
mat(delim: "[", 1, 2; 3, 4)
```
would give me a square-bracket-delimited matrix, but no matter what I use for delim I get parentheses.

I see that 'delim' is a "set parameter," and I know I can use `#set` to adjust it globally (or locally for a section of the document).  But other "set parameters" I have seen can also be specified in the command itself, e.g. you can say

```
#heading(numbering: "a.", [hi])
```
so my expectation was that it would work this way for `mat` as well.  Is it a bug?

**Comment by Enivex** [comment]
This works, but surely there has to be a better way

#let matrix = math.mat(..((1, 2),(3, 4)), delim: "|")
$ matrix $

**Comment by jgm** [comment]
Excellent -- I'm satisfied with that workaround.

**Comment by Enivex** [comment]
`$ mat(#(math.alpha, math.beta), #(3,4), delim: "[") $`

**Comment by jgm** [comment]
Thanks.  My interest is in converting particular formulas for jgm/texmath -- so global `#set` won't work. I'll use this workaround for matrices that have non parentheses delimiters.

**Comment by laurmaedje** [comment]
Forgot to handle named arguments with the semicolon syntax.
