### ISSUE TITLE
Unable to revoke link

### ISSUE THREAD

**Issue by BlueskyFR** [typst/typst#2001]
### Description

I create a read + write link that I shared to someone, but after revoking it 3 times it still works!

I tried to access it while logged out (from a private browsing window) and it still works.

It is a security issue that needs to be fixed asap IMO 👀

### Browsers

Chrome

### OS

Linux

**Comment by laurmaedje** [comment]
Fixed.

**Comment by BlueskyFR** [comment]
Perfect, thanks!
