### ISSUE TITLE
Missing parameter names in `outline.entry` definition in documentation

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2003]
https://typst.app/docs/reference/meta/outline/#outline-entry-parameters:

![image](https://github.com/typst/typst/assets/37143421/41a7aa25-569e-46e0-a041-68b0ddcb7fef)

`crates/typst-library/src/meta/outline.rs`

Should have parameter names:

![image](https://github.com/typst/typst/assets/37143421/2b058207-c954-4c17-8b66-1c863e84d146)

**Comment by PgBiel** [comment]
I believe this is because the parameters all positional and required, so that is actually how you call the outline.entry function (you use `outline.entry(a, b, c, d)` instead of `outline.entry(level: 5, element: ..., ....)`).

I agree this isn't ideal though. Not sure but we could try to find a way to have the named parameters be required.

**Comment by Andrew15-5** [comment]
> this is because the parameters all positional and required

The fact is that you only see data types, but in order for the documentation to be readable, reader have to know what actually they need to pass to the function with the shown data types.

So, if the parameters are provided without names (in a source file), then it's better to say about this right there in the documentation, but names of the "things" that the function (`outline.entry`) needs should be present (in the definition in the documentation).

**Comment by laurmaedje** [comment]
The names are present down below in the explanations (which are in the same order). 

Ideally, if we switched from positional/named to required/optional arguments, that issue would go away.

**Comment by laurmaedje** [comment]
Hacking in required named parameters isn't the way to go in my opinion. We should rather concretize how we can switch to required/optional as the distinction.

**Comment by PgBiel** [comment]
Valid. That's still gonna require a bit of discussion, but I don't think this issue is the appropriate place for it. We should perhaps just leave a link here to an actual issue on the subject instead.

**Comment by Andrew15-5** [comment]
> The names are present down below in the explanations (which are in the same order).

Yes, but that's the thing. You see function definition with no parameter names (only their types), but below you can see all the missing names. Usually (in the same documentation), you can visually map each parameter in definition and its description below. In this case, you can't.

I'm just speaking from the perspective of the reader: this function breaks the usual assumption of the Typst doc page (even on the same page! `outline`/`outline.entry`), if you know what I mean.

**Comment by Andrew15-5** [comment]
About "positional/named" and "required/optional", I don't even want to touch it. It's kinda makes wonders with super slick (IMO) `func(a: 234, b: dfsa, content)`/`func(content, a: 234, b: dfsa)`/`func(a: 234, b: dfsa)[any content]`, but it also feels strange when creating functions with default values (you have to name parameter, but you don't if there is no default value). It's very unique and has pros and cons, so it's up to you to make all the heave thinking.

**Comment by Andrew15-5** [comment]
Just found another example: https://typst.app/docs/reference/layout/enum/#enum-item-parameters.

**Comment by laurmaedje** [comment]
It is always for positional parameters, so also e.g. for calc functions. The idea is that you can see from the signature whether it is positional or named.

**Comment by laurmaedje** [comment]
I would classify this as "working as intended" because the section at the top shows how you would call the function.
