### ISSUE TITLE
Support for Russian GOST bibliography/citation style

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2005]
### Description

I don't know why we had to create a separate bibliography style, but "it is what it is". I found a good implementation of it for `biblatex` (LaTeX): https://ctan.org/pkg/biblatex-gost. And I've used it like this:

```latex
\usepackage[style=gost-numeric]{biblatex}
```

I'm not sure how accurate it is since there are many rules in the spec and this is what I don't want to deep my toes in. But as far as I've tried — no problem. (Although some people will require a slightly different style which is "theirs standard" and you can't do anything about it.)

If there would be a possibility to use something like `#show bibliography: it => ...` where you can access any field/value of any bibliography entry, then this would be a huge step forward (you can also sort entries, i.e. make the whole bibliography from scratch).

I'm still not familiar with Rust (yet) and I don't know how to add a new style myself (I didn't find anything useful using `rg <style name>`).

### Use Case

This will allow for creation of (if not all, then) the majority of documents that have to have a GOST style bibliography.

Thankfully, `cite` can be customized to some extent (`#show cite: it => strong(it)`), but using `#set cite(style: "numerical")` is already GOST compatible, AFAIK. Hence, `cite()` doesn't need as much attention as `bibliography()`.

**Comment by xkevio** [comment]
Ideally, Typst will support [CSL](https://citationstyles.org/) in the future meaning you can fully customize your desired citation style.
Their implementation is still very much work in progress though.

**Comment by Andrew15-5** [comment]
Wow, I've heard of CSL a couple of times, but never actually understood what is it and how to use it. I think I should find a minute to do this.

Are you talking about https://github.com/zotero/citeproc-rs?

**Comment by xkevio** [comment]
Unfortunately, `citeproc-rs` isn't maintained or used even by Zotero. Typst will use its own implementation: https://github.com/typst/citationberg

**Comment by Andrew15-5** [comment]
Haha, meme right away. It was created only this summer? Then it's too soon to hope for some beta releases, I guess.

**Comment by Andrew15-5** [comment]
Are there any hacks/workarounds right now? Using only Typst? Using only Rust? Both?

The easiest and the tidiest method is copy-pasting everything yourself and making sure you didn't mess up any space/delimiter or whatever (this is what I did in LaTeX before committing to use any bib package). This also implies, that I need to make custom `cite` function because there are no citations this way. I can only put labels next to every hard-coded bibliography entry, which will probably help a lot with making custom `cite` function.

**Comment by xkevio** [comment]
There isn't that much you can do short of choosing the closest style and replacing stuff with `show`-rules and regex I think.

**Comment by Andrew15-5** [comment]
And how would I make such show rules? I can't use replace on `content` (`#show bibliography: it => it.replace(",", " ---")`) and I can't convert content to string, only use `repr` which outputs completely different information. `regex` only works on strings, right?

**Comment by laurmaedje** [comment]
There is also a PR for making customization easier in Typst: https://github.com/typst/typst/pull/1249

**Comment by xkevio** [comment]
> And how would I make such show rules? I can't use replace on `content` (`#show bibliography: it => it.replace(",", " ---")`) and I can't convert content to string, only use `repr` which outputs completely different information. `regex` only works on strings, right?

To keep the `show`-rules scoped, I would do the following for example:
```
#[
  #show "Available": "Доступный"
  #bibliography("sources.yml")
]
```

This is a basic example, I don't know how far that can get you. Or, look at the PR @laurmaedje just mentioned.

**Comment by Andrew15-5** [comment]
Oh, ok, thanks. `regex` also works (`#show regex(""): "replace"`), so the regex hell path is now also unlocked. Now that I think about it, I can also extend this with `#show regex(""): match => { ... }`. But I don't think I want to go this way.

**Comment by Andrew15-5** [comment]
> `#bibliography("sources.yml")`

Bold of you to assume, that I already switched from bib format. :) I was going to, but since I still won't be able to style everything correctly, I just gave up (for now).

**Comment by Andrew15-5** [comment]
I wanted to ask here, but still the main issue is different from all the consequences (that I need to go through), I asked it in discussions: #2007. It also can potentially generate a lot of comments that would be kinda of topic over here.

**Comment by reknih** [comment]
`"gost-r-705-2008-numeric"` is now a supported style. You can obtain other GOST styles from the [CSL style repo](https://github.com/citation-style-language/styles) and upload them to your project.

**Comment by Andrew15-5** [comment]
Yes, I've seen this, but haven't tested yet.

**Comment by Andrew15-5** [comment]
I've opened a PR over there: https://github.com/citation-style-language/styles/pull/6765. Assuming it will be merged, When, and will you update your copy of this style in the Typst binary?

**Comment by Andrew15-5** [comment]
Unfortunately, I don't really have my own "test" bibliography files (that has a lot of different fields set), so I can't fully appreciate or compare to some of my hard-coded bibliography. But from the look of it, I think ["we're happy"](https://www.youtube.com/watch?v=qY2Vx8-yOsQ). Thanks!
