### ISSUE TITLE
Add example and clarification for `clip` parameter of `box`/`block`

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2011]
https://typst.app/docs/reference/layout/box/#parameters-clip:
https://typst.app/docs/reference/layout/block/#parameters-clip:

> `clip` [`boolean`](https://typst.app/docs/reference/types/boolean) _Settable_
Whether to clip the content inside the box/block.
Default: `false`

I have 2 issues:
- there is no example (with a result) that shows how exactly can/should you use this parameter,
- therefore (perhaps) reader can't even understand what does it mean: is it to attach something to something else (?) or is it to cut something off in some way? (["to clip" in Oxford Dictionary](https://www.oxfordlearnersdictionaries.com/definition/english/clip_2)).

Maybe these issues exist because of `clip` not working (as intended/at all): #737, #1621. Regardless, the clarification + example should be present in the documentation of `box` and `block` to remove any confusion when reading the documentation. At the very least, the example should be added.

**Comment by laurmaedje** [comment]
It is working partly, just the radius is currently ignored.

**Comment by Andrew15-5** [comment]
Doesn't this mean that there should be a tracking issue for the ignored radius?

**Comment by laurmaedje** [comment]
Was fixed a long time ago: https://github.com/typst/typst/issues/2533

**Comment by Andrew15-5** [comment]
Oh, sorry, I thought your last message was new. It's over 1 year old.
