### ISSUE TITLE
`justify: true` will make newlines in raw code

### ISSUE THREAD

**Issue by aberter0x3f** [typst/typst#2019]
### Description

Commit hash: 7bdf1f57b09ea605045254013a8200373451baf0

I tried to compile a previously written document after updating the typst version, and found that the formatting in some code blocks was broken.

`justify: true` will make newlines in raw code.

```typ
#set par(justify: true)

\```cpp
int main() {
  printf("Hello world\n");
  return 0;
}
\```
```

Since markdown does not support enclosing three backtick substrings in a code block, a backslash is added before the three backticks in the above code.

The final rendered code has some redundant newlines added:

```
int main() {
printf("Hello
world\n");
return
0;
}
```

I tried the release 0.7.0 version and the web app and everything behaves fine, but not in the latest commit.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by AltGr** [comment]
Confirming the issue; I worked around it using
```
#show raw: txt => {
    set par(justify:false)
    txt
}
```

**Comment by laurmaedje** [comment]
Note that this can be simplified to `#show raw.where(block: true): set par(justify: false)`.

**Comment by NeillJohnston** [comment]
Did some digging and found that #1821 is the culprit, removing that bit makes code blocks work again. If I'm understanding things right, the (broken) old justification didn't work due to something which is likely a bug in upstream crate icu4x. So if icu4x fixes that, then the fix in this repo can get reverted and this issue just goes away.

Should ask though, is it intended for justification to be able to affect code blocks in the first place?

**Comment by bluebear94** [comment]
The bug occurs because I assumed that newlines could only occur at the beginning of the paragraph, when this wasn’t the case (such as with code blocks). This patch fixes the behavior:

```diff
diff --git a/crates/typst-library/src/layout/par.rs b/crates/typst-library/src/layout/par.rs
index d3cd6cbf..1e11c454 100644
--- a/crates/typst-library/src/layout/par.rs
+++ b/crates/typst-library/src/layout/par.rs
@@ -904,6 +904,7 @@ fn linebreak_optimized<'a>(vt: &Vt, p: &'a Preparation<'a>, width: Abs) -> Vec<L
         pred: usize,
         total: Cost,
         line: Line<'a>,
+        mandatory_linebreak: bool,
     }
 
     // Cost parameters.
@@ -919,6 +920,7 @@ fn linebreak_optimized<'a>(vt: &Vt, p: &'a Preparation<'a>, width: Abs) -> Vec<L
         pred: 0,
         total: 0.0,
         line: line(vt, p, 0..0, false, false),
+        mandatory_linebreak: true,
     }];
 
     let em = TextElem::size_in(p.styles);
@@ -934,7 +936,7 @@ fn linebreak_optimized<'a>(vt: &Vt, p: &'a Preparation<'a>, width: Abs) -> Vec<L
             let start = pred.line.end;
 
             // Fix for https://github.com/unicode-org/icu4x/issues/3811
-            if i > 0 {
+            if !pred.mandatory_linebreak {
                 if let Some(s_pred) = table.get(i + 1) {
                     let next_start = s_pred.line.end;
                     if !p.bidi.text[start..next_start]
@@ -1024,7 +1026,12 @@ fn linebreak_optimized<'a>(vt: &Vt, p: &'a Preparation<'a>, width: Abs) -> Vec<L
 
             // If this attempt is better than what we had before, take it!
             if best.as_ref().map_or(true, |best| best.total >= total) {
-                best = Some(Entry { pred: i, total, line: attempt });
+                best = Some(Entry {
+                    pred: i,
+                    total,
+                    line: attempt,
+                    mandatory_linebreak: mandatory,
+                });
             }
         }
```

but if we have to keep piling on kludges after one another, we might as well get the original problem solved on icu4x’s side.

**Comment by laurmaedje** [comment]
@bluebear94 why do we need specific code in linebreak_optimized at all? can't we revert your fix and just patch the linebreak iterator, so that it behaves as if icu4x wasn't broken?

**Comment by bluebear94** [comment]
@laurmaedje Yeah, your idea looks like the best bet.
