### ISSUE TITLE
Show rule gets called for non-existent labels

### ISSUE THREAD

**Issue by freundTech** [typst/typst#2026]
### Description

For some reason show rules seem to be called for non-existent labels.

Take the following code:
```typst
#show <label>: it => [
    #let number = counter(<label>).at(it.location()).first()

    #number
]

a <label>
b <label>
```

The document expectedly outputs
```
1
2
```

Now add another line to read or include a file:
```typst
#show <label>: it => [
    #let number = counter(<label>).at(it.location()).first()

    #number
    #include "file-" + str(number) + ".typ"
]

a <label>
b <label>
```

Now compilation fails with `error: file not found (searched at /home/.../file-0.typ)`
Notice the `0` in the name.

Compilation now only works if `file-0.typ`, `file-1.typ` and `file-2.typ` exist. However, the content of `type-0.typ` will never be rendered.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by freundTech** [comment]
Some more experimentation using
```typst
#show label("label"): it => [
    #let number = counter(<label>).at(it.location()).first()

    #number
    #read(it.text + str(number))
]

a <label>
b <label>
```

This tries to access the files `a0`, `b0`, `b1`, `b2` in this order.

**Comment by laurmaedje** [comment]
This is similar to how there were problems with locate. In the first iteration of the introspection loop, all counters resolve to zero. For locate, there is an error-catching mechanism, but not for show rules.
