### ISSUE TITLE
Add a zip function

### ISSUE THREAD

**Issue by owiecc** [typst/typst#2027]
### Description

Zip, as a method on an array, is nice because you can easily chain it: 
```typst
#let left = (2, 4, 5)
#let right = (3, 2, 6)

#left.map(x => x + 1).zip(right).map(
  ((a, b)) => a + b
)
```
But zip feels wrong when used as the first operation in the chain:
```typst
#left.zip(right).map(
  ((a, b)) => a + b
)
```
I suggest a zip function: 
```typst
#let zip(a, b) = a.zip(b)
```
so that we can write this: 
```typst
#zip(left, right).map(
    ((a, b)) => a + b
)
```

### Use Case

Zipping two arrays together.

**Comment by laurmaedje** [comment]
> But zip feels wrong when used as the first operation in the chain.

Might I ask why?

If we add this, then I'm very much in favor of it being a method an not a free-standing function.

**Comment by owiecc** [comment]
It makes one array being somehow elevated. The zip function does an operation on *two* inputs and, to me, the `zip(x, y)` just feels correct. The `x.zip(y)` looks like a curried version of `zip(x, y)` with the original missing.

**Comment by PgBiel** [comment]
I think it'd be better to just consider the more general feature of being able to `type.method(self, parameters)`, which would allow you to `array.zip(x, y)`.

**Comment by xkevio** [comment]
As has been said, you can define it yourself to work it that way so it would be a bit unnecessary to add another way to call an already existing function into Typst itself. Additionally, your suggestion is mostly personal preference -- many functional-inspired languages use it as a method precisely for chaining.

**Comment by laurmaedje** [comment]
Ok, I forgot that `zip` as a method already exists. As @PgBiel pointed out, with the upcoming type system changes, you will be able to write `array.zip(a, b)` as an alternative to `a.zip(b)` (because method calls will just become syntax sugar for calling type-scoped functions).

Given that, I am going to close this. A free-standing `zip` function in the global scope would be duplicate for unclear benefit.

**Comment by owiecc** [comment]
`array.zip(a, b)` is a perfect solution for this. Will wait for the new type system changes.

**Comment by Dherse** [comment]
As an aside @laurmaedje when this happens, could `zip` be made variadic, such that it can have more than one array zipped together at "the same level", currently: `a.zip(b).zip(c)` gives an array of `((a, b), c)` with a variadic version (which could already be created), it would become the imo much more reasonable `a.zip(b, c)` which gives an array of `(a, b, c)`

**Comment by laurmaedje** [comment]
@Dherse Such a PR should indeed be independent of the type system changes, so feel free to send a PR whenever.
