### ISSUE TITLE
Specify user-defined hyphenation patterns at compiler runtime

### ISSUE THREAD

**Issue by lenni-fivi** [typst/typst#2029]
### Description

I am currently running into an issue where words in table headers are becoming too large to fit, and are not hyphenated:
![grafik](https://github.com/typst/typst/assets/114594564/e5d3e1b5-7c5e-4c54-ad49-04eb9e1111f2)

<details>
<summary>test.typ</summary>

```
#set text(lang: "de")
#table(
    columns: 5,
    [*Leistungswirtschaftliche Strategie*], [*Finanzwirtschaftliche Strategie*], [*Soziale Strategie*], [*Informationsstrategie*], [*Langes Wort*]
)
```
</details>

As the words in this example are very niche and rarely used, I wouldn't expect them to be featured in typst's hyphenation library. However, I'd like to manually specify the hyphenation patterns for these words.

With latex (babel) I can use the `\hyphenation` command to specify custom hyphenation patterns at runtime, e.g. `\hyphenation{fi-nanz-wirt-schaft-lich}`, see https://tex.stackexchange.com/a/27895

Currently, I'm manually marking a single breaking point using an explicit `-`:
![grafik](https://github.com/typst/typst/assets/114594564/55fd7494-fbd5-4605-af27-baa21817d40d)

Which works ok. However, I have to do this
 - manually every time I use one of those words
 - manually guess the "best" breaking point
 - re-evaluate my hyphenation every time I change something about surrounding layout

I wasn't able to find a character which I could use to mark possible breaking points, as latex's `\-` would do.
I think adding something like this would be a good interim solution, however I would love seeing a command like latex's `\hyphenation` in the long run.

### Use Case

Improve hyphenation when using rarely used words that are not featured in the hyphenation library.

**Comment by Enivex** [comment]
Unicode has a character precisely for this purpose, `\u{ad}` (there may also be a shorthand for it in typst). You can use show rules to introduce it in your words.

eg:

`#show "word": "wo\u{ad}rd"`

**Comment by freundTech** [comment]
You can use a soft hyphen using `-?` or `#sym.hyph.soft`
If you prefer keeping your hyphenations in one place you can use show rules at the top of you document like this:
```
­#show "Informationsstrategie": [Informations-?strategie]
```

**Comment by lenni-fivi** [comment]
This seems like a good solution. 
I'd suggest mentioning this feature in the docs, maybe somewhere along with the language / hyphenation documentation. 

Thanks a lot!

**Comment by ghost** [comment]
None of the comments shows the actual problem here. The author misses `hyphenate: true`. The words in the example are simple to hyphenate by the default patterns. If you add `hyphenate: true`, it works like requested:

```typst
#set text(lang: "de")
#table(
    columns: 5,
    [*Leistungswirtschaftliche Strategie*], [*Finanzwirtschaftliche Strategie*], [*Soziale Strategie*], [*Informationsstrategie*], [*Langes Wort*]
)

#set text(lang: "de", hyphenate: true)
#table(
    columns: 5,
    [*Leistungswirtschaftliche Strategie*], [*Finanzwirtschaftliche Strategie*], [*Soziale Strategie*], [*Informationsstrategie*], [*Langes Wort*]
)
```

<img width="637" height="193" alt="Image" src="https://github.com/user-attachments/assets/eabed9a5-e163-437d-a08f-aceaddda77cf" />
