### ISSUE TITLE
csv, json, xml, ... functions for strings instead of files

### ISSUE THREAD

**Issue by freundTech** [typst/typst#2038]
### Description

Currently you can only use the data loading functions to load data from a file. Sometimes one might want to parse a csv, json, xml, ... string though.

### Use Case

In my case I have a json file generated by an external program that contains an xml string in one field.
This would probably also be useful for wasm plugins that want to send structured data between typst and the plugin.

**Comment by Beiri22** [comment]
As far as I know the string functions are already merged into main branch and should be part of the next release.

**Comment by Beiri22** [comment]
See #1935

**Comment by freundTech** [comment]
Great. Thanks!
