### ISSUE TITLE
`\today` latex alternative to set date and time

### ISSUE THREAD

**Issue by Tazeg** [typst/typst#204]
Hello, is there something to insert date and time in the document ? this is done in latex with `\today`.

**Comment by Andonome** [comment]
There is a [pull request](https://github.com/typst/typst/pull/211) open for displaying the date, although I don't know how much it can do.

**Comment by tv42** [comment]
My use case: A template that takes input like "2023-04-01" and can output "April 1, 2023".

**Comment by Andonome** [comment]
@tv42  - This sounds like two separate commands.

1. Something to take the `\jobname` ('file name')
2. Date commands to read a format.

**Comment by Enivex** [comment]
https://github.com/typst/typst/pull/435
