### ISSUE TITLE
`hide` function does not work with lines and paths

### ISSUE THREAD

**Issue by ntjess** [typst/typst#2040]
### Description

```typst
#set page(height: auto, width: auto, margin: 0pt)
#set text(size: 2em)

#hide[
  This is some text

  #table(rows: 2, columns: 2)[a][b][c][d]
]

This is more text
```

This should hide all content before "this is more text", but here is the result:

![image](https://github.com/typst/typst/assets/23620506/346be2e5-1d5b-43fc-af6f-3ee1f3245776)

Is this desired behavior?

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by jounathaen** [comment]
The hide function also does not work with images:
```typ
#hide(image("myimage.svg"))
```
still shows the image

**Comment by Enter-tainer** [comment]
> The hide function also does not work with images:
> 
> ```typst
> #hide(image("myimage.svg"))
> ```
> 
> still shows the image

Which typst version are you using? This is not reproduceable in latest main and v0.10.0

**Comment by Enter-tainer** [comment]
```
#hide[#image("/assets/files/docs.svg")]
```

yields

```
<svg class="typst-doc" viewBox="0 0 595.2764999999999 841.89105" width="595.2764999999999" height="841.89105" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:h5="http://www.w3.org/1999/xhtml">
    <g/>
</svg>

```

**Comment by Enter-tainer** [comment]
```diff
❯ git diff crates/typst/src/model/table.rs
diff --git a/crates/typst/src/model/table.rs b/crates/typst/src/model/table.rs
index 33920445..5882d54e 100644
--- a/crates/typst/src/model/table.rs
+++ b/crates/typst/src/model/table.rs
@@ -185,8 +185,11 @@ impl Layout for TableElem {
             styles,
             self.span(),
         );
-
-        Ok(layouter.layout(engine)?.fragment)
+        let mut frag = layouter.layout(engine)?.fragment;
+        for frame in &mut frag {
+            frame.meta(styles, false);
+        }
+        Ok(frag)
     }
 }
```

This should fix the grid thing

**Comment by Enter-tainer** [comment]
I feels like hide should be redesigned. Maybe we should left hide to export or we should enfore the call to `meta`. Otherwise it's very easy to miss `frame.meta`s. idk when should it be called but it seems that many `layout` impls doesn't call it.

**Comment by Enter-tainer** [comment]
And this fix the hide for lines
```diff
❯ git diff crates/typst/src/visualize/line.rs
diff --git a/crates/typst/src/visualize/line.rs b/crates/typst/src/visualize/line.rs
index 12ec4473..94841d39 100644
--- a/crates/typst/src/visualize/line.rs
+++ b/crates/typst/src/visualize/line.rs
@@ -89,6 +89,7 @@ impl Layout for LineElem {
         let mut frame = Frame::soft(target);
         let shape = Geometry::Line(delta.to_point()).stroked(stroke);
         frame.push(start.to_point(), FrameItem::Shape(shape, self.span()));
+        frame.meta(styles, false);
         Ok(Fragment::frame(frame))
     }
 }
```

**Comment by Enter-tainer** [comment]
anyother broken hides?

**Comment by laurmaedje** [comment]
> I feels like hide should be redesigned. 

Definitely. I just don't know how. :/

**Comment by jounathaen** [comment]
> > The hide function also does not work with images:
> > ```typst
> > #hide(image("myimage.svg"))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > still shows the image
> 
> Which typst version are you using? This is not reproduceable in latest main and v0.10.0

Ah, it tested it again, and it turns out: It hides it if the aspect ratio of the image is unchanged, but 
`#hide(image(width: 5cm, height: 1cm, "myimage.svg"))` prevents the hiding, I just left that out to make the example above easier but that is apparently relevant.   :sweat_smile: 

I've updated the comment above and attached the svg
(I'm using v0.10.0 btw)

**Comment by Enter-tainer** [comment]
ty, i will try and update my pr

**Comment by Enter-tainer** [comment]
> Definitely. I just don't know how. :/

It is possible to make `hide` produce a `GroupItem` where `hide: true` then we can ignore this kide of group when export?

**Comment by laurmaedje** [comment]
> It is possible to make hide produce a GroupItem where hide: true then we can ignore this kind of group when export?

While that is a viable approach, I chose not to do this originally because it means that hide forces it's own layout container. Currently, for instance, a few hidden words of a paragraph can have a linebreak within them. This wouldn't be possible anymore.

**Comment by Enter-tainer** [comment]
if it is not possible, can we add such attribute to a fragment? so they are not necessarily grouped

**Comment by laurmaedje** [comment]
I don't think that helps. Fragment (at least the non-math one) is just a Vec<Frame> over multiple regions. So it also groups.

**Comment by laurmaedje** [comment]
> I feels like hide should be redesigned.

@Enter-tainer I've pushed https://github.com/typst/typst/commit/50741209a8f4c5e91d35281eb44b7425b3d022b2, which should make things at least a bit more robust. The link & hide metadata is now applied in a few select places where styles are already manually managed (flow, par, math) and not for each content leaf individually (line, polygon, image, text, etc.)
