### ISSUE TITLE
A way to ignore return values of functions that you do not need

### ISSUE THREAD

**Issue by Beiri22** [typst/typst#2043]
### Description

Take the following function that removes one element from an array and returns the result:
```
#let doSomeTest(x) = {
    x.remove(1);
    x
}

#doSomeTest((1,2,3,4))
```

it fails becaus it cannot join integer with array. As far as I know, you have to place the return of remove into a variable to fix the error like

```
#let doSomeTest(x) = {
    let unused = x.remove(1);
    x
}

#doSomeTest((1,2,3,4))
```

Is there any trick? In pure rust, the placement of semicolon decides if the value is returned... 

### Use Case

Make code more readable.

**Comment by laurmaedje** [comment]
The cleanest and intended way is `let _ = x.remove(1)`. I think that's fine honestly, I wouldn't say that the placement of a tiny semicolon is any clearer, even if shorter.

**Comment by Myriad-Dreamin** [comment]
Is it expected?

```js
#let doSomeTest(x) = {
    x.remove(1);
    return x
}

#repr(doSomeTest((1,2,3,4))) // -> (1, 3, 4)
```

**Comment by Beiri22** [comment]
>> let _ = x.remove(1)

I think this would be ok. We might place a hint to that somewhere in the documentation.

>> return

I'm so into rust, that i did not think about explicitly calling return...
