### ISSUE TITLE
Math: Dot parsing depends on space being after it.

### ISSUE THREAD

**Issue by astrale-sharp** [typst/typst#2044]
### Description

This dot is parsed as text `$step(phi.alt. )$`
This one is parsed as a field access dot: `$step(phi.alt.)$`

Bug? encountered while trying to fix my formatter .

I think both should be parsed as field access and if you wan't text, you write `phi.alt .` instead.

I would be interested to fix it.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This is actually intended. In markup, `Hello #world.` should just access the `world` variable at the end of a sentence, instead of giving an error about a missing field. In math, it works the same.

**Comment by laurmaedje** [comment]
Okay, so this is only half intended. The parenthesis thing is a bug. The first one is working as intended.

**Comment by astrale-sharp** [comment]
Fair enough, what should the second be then, a Text(".") followed by RighParen ?

**Comment by laurmaedje** [comment]
Yep.

**Comment by astrale-sharp** [comment]
I'll take a stab at it!

**Comment by astrale-sharp** [comment]
I always get a really hard time contributing to the parser, it's so hard to pinpoint where something is happening! advices, anyone? (@Marmare314 ? 🙄)

**Comment by laurmaedje** [comment]
The problem is in this line: https://github.com/typst/typst/blob/bcab77052422baaa29b57b62f14a19af8cc87225/crates/typst-syntax/src/parser.rs#L265

We check for MathIdent or Text, but "(" is also text, so we should check whether the actual text is_ident.
