### ISSUE TITLE
Better support for polylux overlay slides

### ISSUE THREAD

**Issue by Beiri22** [typst/typst#2045]
### Description

On each polylux slide, content can be placed on different subslides by defining ranges, so that one frame will be iterated multiples times. By now this uses a constant maximum limit of iterations, because typst support lacks here.

### Use Case

You got two counters:
- subslide-number
- number-of-repetitions for that frame

Now you do the following:
```
  repetitions.update(1) // to run at least one time
  subslide.update(1) // this is the first subslide

  while(subslide<=repetitions) {
    body // render out body, this updates the repetition counter based on the real overlay numbers used in the body
    pagebreak()
    subslide.step();
  }
```

As both, repetitions and subslide, are state or counter, you need a location or use display() to use the value. The location needs to wrap the whole while loop. But then, the "repetitions.at(loc).first()" will not update after the first loop iteration.
The current way of doing this seems non-optimal to me:
```
  repetitions.update(1) // to run at least one time
  subslide.update(1) // this is the first subslide

  for _ in range(some-max-repetitions-const) {
    locate( loc => {
      let curr-subslide = subslide.at(loc).first()
      if curr-subslide <= repetitions.at(loc).first() {
        if curr-subslide > 1 { pagebreak(weak: true) }
        body
      }
    })
    subslide.step()
  }
```

Do you have any idea?

**Comment by andreasKroepelin** [comment]
Did you open the issue here on purpose or was this meant to go in the polylux repository?

**Comment by Beiri22** [comment]
On purpose. May we achieve compiler support...

**Comment by Enivex** [comment]
I don't think increasing the iteration limit is going to happen.

**Comment by laurmaedje** [comment]
@Enivex This are different iterations than Typst's introspection iterations. Polylux uses iteration for the slide uncovering and has an unrelated limit.

**Comment by Beiri22** [comment]
@laurmaedje There must be some way to allow overlays without a hack like this. I'm not sure if there is something like updating the location mid-function; or having some kind of lightweight state without history, or extended support for changing state whilst in a locate / display - context or something else. 

In my opinion polylux / presentations is a relevant use case for typst. I ask you to think about it; and help to bringt this issue forward in discussion and implementation.

**Comment by andreasKroepelin** [comment]
Thanks for making me think about it again! After just a few minutes, I came up with a rather simple solution. We have to show the body once anyway (every slide has at least one subslide), after that we know the number of repetitions and can use it in a for-loop. Done.

I'll open a PR for Polylux soon.

**Comment by Beiri22** [comment]
Theoretically it could be possible to use dynamic overlay numbers(vars), right? I don't think that is the common case, but should be possible. So maybe we let this discussion open, though... Just for a few ideas...

**Comment by andreasKroepelin** [comment]
I'm not sure I understand what you mean.

**Comment by Beiri22** [comment]
With the dictionary syntax (beginning:, until:) would it possible to supply the system values that change from one run to the next? If so, how do we deal with that? Or how could we avoid it...

**Comment by andreasKroepelin** [comment]
Still not clear to me what kind of issue you're pointing at.
But I really think this is a Polylux-internal thing now so let's not discuss it here.

**Comment by Beiri22** [comment]
You re right, we discuss it internally
