### ISSUE TITLE
Inconsistencies between eval's math mode and math blocks

### ISSUE THREAD

**Issue by bluerosegarden** [typst/typst#2055]
### Description

The following input should be the same:

```
#eval(mode: "math", "f(a) = cases(a + b\, space space x >= 3,a + b\, space space x = 5)")
$f(a) = cases(a + b\, space space x >= 3,a + b\, space space x = 5)$
```
but the f isn't rendered as a function in eval's math mode, instead it's rendered as a variable:

![image](https://github.com/typst/typst/assets/134471273/6f7cb23c-80f7-44aa-b018-109da9865cb9)

I'm unsure if there are any other inconsistencies that exist, but I can try hunting them down if needed.

Also, this may or may not be a bug but I might as well ask here: there a way to set eval's math mode as a block as opposed to inline (which is the default)? I couldn't figure it out. The docs say inputting a space works when using the normal $ math block, but doing that in eval results in an error about unexpected spaces.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by freundTech** [comment]
It seems to work fine, when explicitly wrapping it in a `math.equation`:
```typst
#math.equation(eval(mode: "math", "f(a) = cases(a + b\, space space x >= 3,a + b\, space space x = 5)"))
```

Then you can also pass the block parameter:
```typst
#math.equation(eval(mode: "math", "f(a) = cases(a + b\, space space x >= 3,a + b\, space space x = 5)"), block: true)
```

I don't know if this is intended.

**Comment by bluerosegarden** [comment]
> #math.equation

Thank you, that does solve my issue for the moment! But the bug(?) still stands. If it is intended, it's a little imo counterintuitive and deserves a mention on the math (or at least the eval) page

**Comment by laurmaedje** [comment]
Yeah, that's clearly a bug. `eval` returns a sequence that doesn't make sense if not wrapped in an equation. `eval` should add an extra equation around it.

**Comment by laurmaedje** [comment]
Fixed via https://github.com/typst/typst/pull/2081
