### ISSUE TITLE
Incorrect links for "PARAMETER OF"  in documentation search results

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2061]
![image](https://github.com/typst/typst/assets/37143421/6a3eb5ff-59c3-4145-af31-76660f57d832)

This links to https://typst.app/docs/reference/types/array/#map-parameters-mapper. But `id` `map-parameters-mapper` doesn't exist. Instead, it should link this: https://typst.app/docs/reference/types/array/#methods-map-parameters-mapper.

Same with parameter of insert: https://typst.app/docs/reference/types/dictionary/#insert-parameters-key should be replaced with https://typst.app/docs/reference/types/dictionary/#methods-insert-parameters-key.

So the issue is with all "PARAMETER OF <something>" links.

**Comment by laurmaedje** [comment]
It's probably only broken for method parameters, not for normal functions. Since methods are currently being reworked to functions in type scopes, I would fix it together with that.

**Comment by laurmaedje** [comment]
This is fixed now.
