### ISSUE TITLE
Problematic edge-case for Interleaved RTL and LTR text on the edge of a line.

### ISSUE THREAD

**Issue by emilyyyylime** [typst/typst#2063]
### Description

With this markup
```
#box(width: 6cm)[
Some Israeli cities are: 'ירושלים', 'תל-אביב', 'בית שמש'
]
```
The following is generated with the Typst-Renderer bot on the Discord:
![Image of unpleasant generated output.](https://github.com/typst/typst/assets/40892795/6f940fe3-251b-4785-8251-0b1abd84b175)
Here, interestingly, the behaviour differs from if a line break were to be inserted explicitly:
```
#box(width: 6cm)[
Some Israeli cities are: 'ירושלים', \ 'תל-אביב', 'בית שמש'
]
```
![Image of more desirable output.](https://github.com/typst/typst/assets/40892795/76de4d70-9bc8-4a27-b3a5-eff2fcc8cf1b)

The latter output is much more appealing to my eyes as a Native RTL language speaker, and I would expect it to occur even through the markup of the first.

### Typst version

- [X] I am using the latest version of Typst

**Comment by emilyyyylime** [comment]
Also, sadly the quotes seem to be incorrectly detected as well, but perhaps that deserves its own issue.

**Comment by laurmaedje** [comment]
Hmm, I wonder whether we are doing something wrong with BiDi or whether the BiDi algorithm is just bad in this case.

**Comment by emilyyyylime** [comment]
I suspect the bidi algorithm's at fault here, this particular problem seems quite familiar. I would, however, still like some nice workaround if possible, perhaps even "hard" ltr and rtl envs in which punctuation always binds as with the direction

**Comment by laurmaedje** [comment]
Is `#set text(dir: rtl)` not enough?

**Comment by emilyyyylime** [comment]
Nope, that doesn't do anything
Unless you mean around the whole block, in which case that significantly changes the markup from my desired result

**Comment by laurmaedje** [comment]
But what would "hard RTL" be other than setting the BiDi base dir? Disabling BiDi entirely? I thought setting the base dir to RTL _will_ render punctuation in RTL.

**Comment by emilyyyylime** [comment]
I don't think using `text(dir: rtl)` inline sets the base dir. I think only applies once a new line starts

**Comment by emilyyyylime** [comment]
I found this issue again. I came to the conclusion that this is a downfall of the BiDi algorithm after checking what my browser does. To work around this one can use `#text(dir: rtl)['ירושלים'], #text(dir: rtl)['תל-אביב'], #text(dir: rtl)['בית שמש']` (or #text(dir: rtl)['ירושלים', 'תל-אביב', 'בית שמש'] depending on semantics. Alias recommended).
The incorrect smart quotes however I would consider an issue with a minimal reproducible case of `"אחד", "שתיים"` within a LTR context or `"This"` within a RTL context. Should I open a new issue?

**Comment by laurmaedje** [comment]
Yes, best open a new issue and IIUC this one can be closed then?
