### ISSUE TITLE
Read access to variables in special cases

### ISSUE THREAD

**Issue by Beiri22** [typst/typst#2064]
### Description

```
#let template(body) = [
  #let something = "var123"; 
  #body
]

#template([
  //This variable could be readable here...:
  #something
])

//#show: template
//This variable could be passed readable by show rule: #something
```

### Use Case

This would allow templates to pass variables or local functions to its body.

**Comment by laurmaedje** [comment]
There is the problem that the evaluation order is different. `body` is an argument to `template`, so it will be fully evaluated before `template` itself runs.

**Comment by Beiri22** [comment]
I see, that makes it impossible with the current system. But, what do you think, is the usecase relevant? The easy solution would be to allow for lazy content arguments; but I cannot oversee if that would break the system...

**Comment by laurmaedje** [comment]
I do see the use case. Perhaps set rules on custom elements could fill that gap?

**Comment by user202729** [comment]
Just use a lambda I think?

```
#let template(body) = [
  #let something = "var123"; 
  #body(something)
]

#template(something => [
  //This variable could be readable here...:
  #something
])

//#show: template
//This variable could be passed readable by show rule: #something
```

**Comment by Beiri22** [comment]
> Just use a lambda I think?

This is nice. I have not thought about lambdas. Unfortunately, it does not work with the show rule

**Comment by laurmaedje** [comment]
Closing in favor of #763 in combination with #2607 (or rather types), which will make this kind of data flow possible.
