### ISSUE TITLE
Prime symbols can be attached as limits

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#2070]
### Description

Prime symbols can be attached as limits instead of always being attached as exponents.

Not sure if this is a bug or the intended behavior.

```typst
$ lim' $
$ lim'' $
$ lim''' $
$ lim'''' $
$ lim''''' $
```

![lim with prime symbols above instead of as exponents](https://github.com/typst/typst/assets/57839069/29669b32-685d-4f81-a47d-9c15545d2b58)

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
This is intentional, since lim has..well..limits.

**Comment by laurmaedje** [comment]
While it may seem somewhat weird, it is consistent with how things generally work, so I would refrain from adding more special cases.

**Comment by laurmaedje** [comment]
On second thought, I sort of agree with @MDLC01. While a prime is as a normal attachment, that feels like an implementation detail to me and attaching it as a limit is probably almost never what the user wanted.

**Comment by jassler** [comment]
To extend on this (and reference #3299), should the exponent and subscript behave similarly for comparators? I.e., should the `2` in `>^2` and `>_2` be rendered above and below the `>` or next to it?

**Comment by Enivex** [comment]
> To extend on this (and reference #3299), should the exponent and subscript behave similarly for comparators? I.e., should the `2` in `>^2` and `>_2` be rendered above and below the `>` or next to it?

That's the difference between limits and scripts.
