### ISSUE TITLE
Blocks with `breakable: false` inside a grid can overflow page margins

### ISSUE THREAD

**Issue by christopher-l** [typst/typst#2073]
### Description

Usually, when a `block` is set to `breakable: false`, it will be moved to the next page in case a page break would split the block. The same situation inside a `grid` will just print the block content over the page margins.

Minimal example document:
```
#lorem(650)

#grid(
    block(breakable: false)[#lorem(100)]
)
```

### Reproduction URL

https://typst.app/project/rURuGWTCiIYyNFoBObeOTT

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by kdog3682** [comment]
I have experienced this error as well.

`#set page(width: 200pt, height: 100pt, background: rect(fill: white, width: 100%, height: 100%))

#let dialogue-table(..args) = {
  let opts = args.named()
  let gap = 5pt
  let items = args.pos()
  let stroke = 0.3pt
  let stroke = 0.3pt
  let align = center + horizon
  let align=auto

  let mapper((a,b)) = {
    let Speaker = text(weight: "bold", a)
    let inset = (x: 0pt, top: 0pt, bottom: 10pt)
    let Content = b
    return (Speaker, Content)
    // let Content = box(inset: inset, align(alignment.left, b))
  }
  let contents = items.map(mapper).flatten()
  
   // grid(row-gutter: 30pt, column-gutter: gap, columns: 2, ..contents)
   table(row-gutter: 10pt, column-gutter: gap, columns: 2, stroke: stroke, align: align, inset: 0pt, ..contents)
}
#let sam-content-1 = [
  howdy \
  from \
  
  sam
]
#{
  let item1 = ("sam", block(breakable: false, sam-content-1))
  dialogue-table(item1, item1)
}`

I was expecting the item to break to the next page, but insteaad, it seems to clip off.

**Comment by laurmaedje** [comment]
Doesn't happen anymore as of Typst 0.11.
