### ISSUE TITLE
Outdated documentation on floating figures in Typst vs. LaTeX?

### ISSUE THREAD

**Issue by NicoWeio** [typst/typst#2074]
The documentation still says
https://github.com/typst/typst/blob/87c0a5171af2e374cd6b0a0bd6d8d9531aaf796c/docs/guides/guide-for-latex-users.md?plain=1#L573-L578
but 78f96f844bc54c5385c1efda0b5faad3c49fa79b has been merged and released in 0.7.0. Doesn't that change the situation outlined in the aforementioned bullet point?

**Comment by laurmaedje** [comment]
Yeah, it's a bit outdated. We'll update the LaTeX guide soon.

**Comment by NicoWeio** [comment]
For future reference: This was fixed in f90701e132679f8372e8a32171dd013646c7f276.
