### ISSUE TITLE
Incomplete deletion of selected code lines for `[$  $]`

### ISSUE THREAD

**Issue by Deep0Thinking** [typst/typst#2080]
### Description

I encountered this issue while attempting to delete some empty rows in the forms of  `[$  $]` within a `#table`. I then isolated the root cause:

```typst
[$  $]
[$  $]
[$  $]
[$  $]
```

Once you **select** the code from `line 2` to `line 3` in the code block above with your cursor, then press `delete`, the code block will become:

```typst
[$  $]
[$[$  $]
```

But the expected change should be:

```typst
[$  $]
[$  $]
```

### Browsers

Firefox, Chrome, Safari, Microsoft Edge

### OS

macOS

**Comment by laurmaedje** [comment]
Fixed.
