### ISSUE TITLE
window can't run typst

### ISSUE THREAD

**Issue by yujiahan2018** [typst/typst#2087]
### Description

I'm from [https://github.com/typst/typst/releases/tag/v0.7.0](https://github.com/typst/typst/releases/tag/v0.7.0) to download the Windows Version (as shown)：

![image](https://github.com/typst/typst/assets/40731243/382fdd73-2556-4f04-82e7-349698f7638e)
![image](https://github.com/typst/typst/assets/40731243/5b6e3475-d5ff-40cf-9d16-4615e7634d94)

，Double-click typst.exe, there is no response, what is the reason?

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
What you downloaded contains the CLI (Command-Line Interface) app, not a graphical app (Typst doesn't have a dedicated graphical desktop application currently). It is meant to be used from your terminal / CMD.exe.

If you do not wish to use the terminal, what you can do is either use the [Typst web application (official)](https://typst.app), the Typst LSP extension for the Visual Studio Code app (unofficial), or use something like [typstudio (unofficial, beta)](https://github.com/Cubxity/typstudio).
