### ISSUE TITLE
String and regex show rules with a function should pass a match dict, rather than content

### ISSUE THREAD

**Issue by emilyyyylime** [typst/typst#2093]
### Description

Like the dict returned by `str.match`

### Use Case

```
#show regex("(?i)hello (\w+)"): m => "goodbye " + m.captures.at(1)
```

**Comment by laurmaedje** [comment]
That would hurt the common case, e.g. `show regex(".."): underline`. And you can always store the regex in a variable and run it again over the matched text.

**Comment by emilyyyylime** [comment]
I see, that is rather a problem. I do still think however, that easy access to the captures without having to jump through hoops is really missing. This might be odd but perhaps we could return content with a captures field?

**Comment by laurmaedje** [comment]
It could work. I did think of something like this before, but I'm not sure anymore whether I just didn't implement it or whether I ran into problems.

**Comment by JamesxX** [comment]
Quick bump and subscription to this issue, as I'm running into a problem that would necessitate a similar solution.

**Comment by tingerrr** [comment]
> This might be odd but perhaps we could return content with a captures field?

I think this should actually work once types and elements are one and the same thing, this could just be a regex capture type for show rules, which by default displays its inner content, but carries the captures around.

**Comment by laurmaedje** [comment]
@JamesxX Since you can always rematch the regex on the matched text, this shouldn't be blocking anything?

**Comment by JamesxX** [comment]
@laurmaedje I'm working on regex for parsing chemical formulae, which has quite context dependent capture groups, some of which will match the same text, but parts need to be treated differently by surrounding text. Encompassing all of these cases in nested show rules is certainly possible, just a lot less pretty and a lot more difficult than it would be with capture groups.

**Comment by laurmaedje** [comment]
@JamesxX I don't mean nested show rules, I mean calling the [`str.match`](https://typst.app/docs/reference/foundations/str/#definitions-match) function on the matched text. Like this:
```typ
#let re = regex("(\d+).(\d+).")
#show re: it => {
  let (d, m) = it.text.match(re).captures
  [#d;th day of the #m;th month]
}

The 29.10. is a date. 
// -> The 29th day of the 10th month is a date.
```

**Comment by laurmaedje** [comment]
I think the solution with rematching is such a minor inconvenience that it's not worth adding a new feature for this, so I'll close this.

**Comment by emilyyyylime** [comment]
I don't know, this is still kind of a pain point for me, having to factor out the regex and introduce a block where it wouldn't otherwise be necessary just feels like too much overhead. That said, perhaps these are all symptoms of trying to match a DOM (for lack of a better term) against a regex, which of course is designed for matching linear text. Maybe the correct solution would involve a more structural pattern definition such as the selectors=destructuring concept that has been discussed a number of times—but I don't see that coming anytime soon unfortunately
