### ISSUE TITLE
`flags` argument for `regex`

### ISSUE THREAD

**Issue by emilyyyylime** [typst/typst#2094]

**Comment by laurmaedje** [comment]
A description would be helpful. I'm assuming you mean flags like case sensitive? Those should be available for configuration within the string. See https://docs.rs/regex

**Comment by emilyyyylime** [comment]
Yes, that is what I mean. I'm aware flags *can* be changed inline, but most Regex implementations provide an api to set flags explicitly at construction time

**Comment by laurmaedje** [comment]
I don't really see the point of duplicating that to be honest. Do you have a specific motivation?

**Comment by laurmaedje** [comment]
In fact, I think it's quite nice that the regex string itself is self-contained.

**Comment by emilyyyylime** [comment]
But what harm is it to add another option

**Comment by laurmaedje** [comment]
I generally dislike having multiple options if one isn't clearly more general than the other. It needs more docs, API surface, people need to be aware of both options when reading code, etc. This might all not be too bad in this case, but it's a general design philosophy. If there's a clear benefit, I'm open to adding it, but I don't really see the motivation so far.

**Comment by emilyyyylime** [comment]
I think it helps keep the noise in regex to a minimum — Regex can already be quite information dense; especially without lookarounds — consider for example `regex('(?i)hello')` or maybe `regex('[aA]')` as opposed to for example `regex('hello', flags: "i")` or `regex('a', insensitive: true)`, respectively (there are multiple APIs we could choose; I am in favour of the latter as it helps with understanding even for people not familiar with regex)
I just find the latter two much more approachable for understanding

**Comment by laurmaedje** [comment]
My opinion on this hasn't really changed, so I'll close this.

**Comment by DUOLabs333** [comment]
For those wondering how you would, for example, make a particular regex case-insensitive, prefix it with `(?i)` (eg, matching both uppercase and lowercase vowels would be `(?i)[aeiou]`.
