### ISSUE TITLE
Incorrect page numbering when using #pagebreak(to)

### ISSUE THREAD

**Issue by Zheoni** [typst/typst#2095]
### Description

When using `#pagebreak(to)` in combination with a change in page numbering with a `set` rule, the (maybe) inserted empty page uses the incorrect page numbering.

This is a minimal example:
```typ
#set page(height: 5cm, numbering: none)
= This page should not be numbered
#lorem(20)

#pagebreak(weak: true, to: "odd")

#set page(numbering: "1")
#counter(page).update(1)

= This page should
#lorem(20)
```

![image](https://github.com/typst/typst/assets/38019254/a8a03b5e-9a14-4218-9417-c29caa2e2def)

The empty page has a page number when it should not.

This is in `typst 0.7.0 (da8367e1)` in windows. I got it from winget.

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/2182
