### ISSUE TITLE
Large compilation time when including a lot of images

### ISSUE THREAD

**Issue by maucejo** [typst/typst#2096]
### Description

I post this issue after posting a feedback on Typst for writing scientific papers on Discord.

As indicated in the post, I observed that Typst compilation time increases drastically when there are a lot of svg images in the document. In my experiment, to compile a 56 page document with 40 svg files, it took : 
-  75 seconds (compilation from scratch)
- 63 seconds (incremental compilation)

However, when replacing all the images by boxes, I obtain:
- 13 seconds (compilation from scratch)
- 286 ms (incremental compilation)

I don't know if this issue has already been reported. 

I hope that this feddback can help to improve Typst, because I love it !

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Wow, that is indeed really slow. I will try to find out whether caching is not working correctly.

**Comment by maucejo** [comment]
> Wow, that is indeed really slow. I will try to find out whether caching is not working correctly.

I can share my document if it can help, but it will be in several weeks, when the paper will be published.

**Comment by laurmaedje** [comment]
That would be very helpful.

**Comment by LaurenzV** [comment]
Incremental rendering for documents with many SVGs has been improved in a recent update, so I'm gonna close this.
