### ISSUE TITLE
Can't use `function` for `heading` `numbering` if `level` is greater than `1`

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2101]
### Description

This is ok:

```typ
#heading(numbering: it => it)[]
#heading(level: 1, numbering: it => it)[]
```

Compiler error:

```typ
#heading(level: 2, numbering: it => it)[]
```

I've checked the documentation and I don't see any warnings that this wouldn't work. Either add a note about this, or this is a bug.

---

I was using it like this: `#heading(numbering: it => none)[]` and wanted to pass a level, but suddenly got an error. Then I've checked, and I can actually pass `none` directly and therefore don't need to decrease heading counter. But this removes the nested indent in `outline` (with `it => none` the indent is present, but the number is missing, which is what I want).

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by freundTech** [comment]
This is a bit of a quirk due to the fact that numberings use varargs arguments. 
Look at the `numbering` function:
```typst
numbering("1.", 3)   // 3.
numbering("1.", 3, 7)  // 3.7.
```

Your custom numbering function must also accept a variable amount of arguments. This is done like this:
```typst
#set heading(numbering: (..n) => {
  // use n.pos().at(x) to access level x+1
}
```

If the level is fixed like in your example you can also accept a fixed number of arguments like this:
```typst
#heading(level: 2, numbering: (n1, n2) => none)[]
```

**Comment by Andrew15-5** [comment]
https://typst.app/docs/reference/meta/outline/:

> How to indent the outline's entries.
>
> `auto`: Indents the numbering of the nested entry with the title of its parent entry. This only has an effect if the entries are numbered (e.g., via [heading numbering](https://typst.app/docs/reference/meta/heading/#parameters-numbering)).

Ok, I've found everything that I wanted, including that I used `true` instead of `auto`. But now the question is what is `auto` exactly? The documentation doesn't say that.

But I've found a solution to my problem:

```typ
#set outline(indent: it => for _ in range(it) { h(1em) }) // I'm guessing `auto` is an alias for `1em`
#let unnumbered-heading(name, ..args) = {
  heading(numbering: none, name, ..args)
}
```

**Comment by Andrew15-5** [comment]
@freundTech, I guess it is kinda understanding, if I dig deep:

https://typst.app/docs/reference/meta/heading/#parameters-numbering:

![image](https://github.com/typst/typst/assets/37143421/fa45e44f-2a1b-4b37-9905-07a45162ac03)

https://typst.app/docs/reference/meta/numbering/:

![image](https://github.com/typst/typst/assets/37143421/489f1b82-67dc-400b-ae47-ebd0b330be61)

---

But the problem is more to do with the error:

```
error: unexpected argument
   ┌─ /file.typ:42:21
   │
42 │   heading(numbering: it => it, name, ..args)
   │                      ^^
```

Like, what does it say? How `it` is unexpected, when with `level: 1` everything works? The function has to get _some_ arguments, right? So maybe change the error to be more user-friendly?

**Comment by Enivex** [comment]
It's unexpected because the way it's written you can receive only a single argument.

**Comment by laurmaedje** [comment]
The diagnostic is bad, you can open a separate issue about that.
