### ISSUE TITLE
#sym.arrow.r.squiggly after \ will produce a tofu symbol

### ISSUE THREAD

**Issue by fourdim** [typst/typst#2105]
### Description

Enter this in a.typ:

```typst
a. Form #sym.arrow.r.squiggly (Form #sym.subset Form) \
#sym.arrow.r.squiggly (aaa)
```

will give

![image](https://github.com/nvarner/typst-lsp/assets/59462000/f7052449-6a4b-4b97-a9a6-9d58c75d98f6)

**Expected behavior**

Get from typst.app

![image](https://github.com/Enter-tainer/typst-preview/assets/59462000/4bbdaeb8-a936-4b17-8073-1fabe11cf212)
**Package/Software version:**
Typst: nightly version https://github.com/typst/typst#073effc7
OS: Arch Linux x86_64

I cannot reproduce it on the typst.app.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
I was able to reproduce it on the web app, but not consistently so. It happens with other symbols as well, in particular those that require two or more modifiers

**Comment by Enter-tainer** [comment]
nit picking: this looks more like a tofu symbol. sym.times.square should be a square

**Comment by laurmaedje** [comment]
This is indeed a [tofu](https://fonts.google.com/knowledge/glossary/tofu) symbol, not a times square. Since you're using the symbol outside of math mode, the text font is used and that font doesn't have the symbol. 

On the web app, the symbol appears because it does a last resort fallback to "Fira Math" (which is probably not available on your system). Last resort fallback is somewhat unpredictable, so it's a bit random that is picks that one over New CM Math.

The wonderous thing now is, why it does not fall back to New CM Math on your system. Do you know whether your binary has the default fonts embedded? If so, it _should_ be able to find New CM Math.

**Comment by fourdim** [comment]
The weird thing is the first one #sym.arrow.r.squiggly is shown properly. It means that the system does have this font.

**Comment by laurmaedje** [comment]
Oh, right, I didn't see that. That's super weird.

**Comment by T0mstone** [comment]
I have this issue as well, this time with `sym.arrow.long`. It works when in a new paragraph, but not when directly after `\`.

**Comment by Enter-tainer** [comment]
This also happens for certain chinese fonts. Only reproduceable on windows. Possibly related to fonts

```
#linebreak()中文
```
[tofu.pdf](https://github.com/typst/typst/files/13810356/tofu.pdf)
![image](https://github.com/typst/typst/assets/25521218/122545d6-c186-4f16-a9de-0583b17f0b87)

**Comment by Enter-tainer** [comment]
When chinese is correctly displayed, the ShapedGlyph looks like this
```
                ShapedGlyph {
                    font: Font(KaiTi, Normal-400-FontStretch(1000)),
                    glyph_id: 1123,
                    x_advance: 1.0em,
                    x_offset: 0.0em,
                    y_offset: 0.0em,
                    adjustability: Adjustability {
                        stretchability: (
                            0.0em,
                            0.0em,
                        ),
                        shrinkability: (
                            0.0em,
                            0.0em,
                        ),
                    },
                    range: 0..3,
                    safe_to_break: true,
                    c: '中',
                    span: (
                        Span(
                            21110623253300,
                        ),
                        0,
                    ),
                    is_justifiable: true,
                    script: Han,
                },
```

When it becomes tofu, it looks like this:
```
            glyphs: [
                ShapedGlyph {
                    font: Font(Linux Libertine, Normal-400-FontStretch(1000)),
                    glyph_id: 0,
                    x_advance: 0.5em,
                    x_offset: 0.0em,
                    y_offset: 0.0em,
                    adjustability: Adjustability {
                        stretchability: (
                            0.0em,
                            0.0em,
                        ),
                        shrinkability: (
                            0.0em,
                            0.0em,
                        ),
                    },
                    range: 1..4,
                    safe_to_break: true,
                    c: '中',
                    span: (
                        Span(
                            35184372088832,
                        ),
                        1,
                    ),
                    is_justifiable: true,
                    script: Han,
                },
```

It looks like `#linebreak` is changing the font?

**Comment by Enter-tainer** [comment]
Without linebreak:
```
[crates\typst\src\layout\inline\shaping.rs:672] &selection = Some(
    Font(Linux Libertine, Normal-400-FontStretch(1000)),
)
[crates\typst\src\layout\inline\shaping.rs:672] text = "中文"
[crates\typst\src\layout\inline\shaping.rs:672] &selection = Some(
    Font(Segoe UI Emoji, Normal-400-FontStretch(1000)),
)
[crates\typst\src\layout\inline\shaping.rs:672] text = "中文"
[crates\typst\src\layout\inline\shaping.rs:672] &selection = Some(
    Font(KaiTi, Normal-400-FontStretch(1000)),
)
```

with linebreak:
```
[crates\typst\src\layout\inline\shaping.rs:672] &selection = Some(
    Font(Linux Libertine, Normal-400-FontStretch(1000)),
)
[crates\typst\src\layout\inline\shaping.rs:672] text = "\n中文"
[crates\typst\src\layout\inline\shaping.rs:672] &selection = Some(
    Font(Segoe UI Emoji, Normal-400-FontStretch(1000)),
)
[crates\typst\src\layout\inline\shaping.rs:672] text = "\n中文"
[crates\typst\src\layout\inline\shaping.rs:672] &selection = None
[crates\typst\src\layout\inline\shaping.rs:672] text = "\n中文"
```

**Comment by Enter-tainer** [comment]
It seems to be the '\n' at the begining of the string is preventing font selection. Any idea to fix this? @laurmaedje

**Comment by Enter-tainer** [comment]
Okay I think it is this: https://github.com/typst/typst/blob/main/crates/typst/src/text/font/book.rs#L96

> Find the fonts that contain the text's first char ...

And the first char is \n
