### ISSUE TITLE
Incorporate scope `show`/`set` rules in `metadata` output

### ISSUE THREAD

**Issue by ntjess** [typst/typst#2108]
### Description

Not sure if this is a bug or a feature, but consider the following document:

```typst
#let mr(..args) = [#metadata(rect(..args))<rect>]
#mr(width: 5em, height: 5em, stroke: black)

#mr(width: 5em, height: 5em, stroke: black)

#set rect(stroke: rgb(255, 0, 0))
#show rect: it => it

#mr(width: 5em, height: 5em, fill: yellow)
#show rect: it => [Completely overridden!]
#mr(width: 5em, height: 5em, fill: yellow)
```

It would be ideal if the output of `typst query file.typ "<rect>"` could capture whatever content is about to be shown, not just what is passed directly. This allows the metadata to more accurately reflect what is actually present in the document. Currently, neither `show` rules or `set` rules are incorporated.

### Operating system

Web app, Windows, Linux, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
I think a more ideal approach would be to be able to query the rectangle itself (and, thus, all elements); I acknowledge this would currently not be a very simple feat, however.

**Comment by laurmaedje** [comment]
I'll close this because it too fundamentally at odds with how things work, so it's not feasible.
