### ISSUE TITLE
Text from SVG image doesn't appear  

### ISSUE THREAD

**Issue by mort95342** [typst/typst#2114]
### Description

My SVG image is supposed to look like this
![Michelson_setup](https://github.com/typst/typst/assets/144808007/df88cdde-0ab2-4a90-9473-4ef4325c16b9)

However, inserting it looks like this:
![image](https://github.com/typst/typst/assets/144808007/fe5ef1ed-b86d-44ab-a60e-629dfe663e3b)

File attached here:

Code:

#figure(image("/Images/Michelson_setup.svg"),
caption: [Michelson Interferometer.]) <fig:Michelson>

### Reproduction URL

https://typst.app/project/pSC-QZ6ZYaeUyv76CO4BUi

### Browsers

Microsoft Edge

### OS

Windows

**Comment by Enivex** [comment]
> It is a duplicate, but I think of #2051. It should be fixed in the next release.

I can't keep track of all the ways text doesn't show up in svgs 😂
