### ISSUE TITLE
[BUG] Localhost link on e-mail confirmation

### ISSUE THREAD

**Issue by Daniel-Boll** [typst/typst#212]
<h1 align="center">
[BUG] Localhost link on e-mail confirmation
  <img alt="Typst" src="https://user-images.githubusercontent.com/17899797/226108480-722b770e-6313-40d7-84f2-26bebb55a281.png">
</h1>

## Description:

I received the e-mail confirmation for my account on typst, but I noticed that the link included in the e-mail is a localhost link with port 7090.

## Expected behavior:

The e-mail confirmation message should include a valid link that allows the user to confirm their account and access the typst website.

## Actual behavior:

The e-mail confirmation message includes a localhost link with port 7090, which is not a valid link for confirming the user's account or accessing the typst website.

## Additional information:

Browser: Brave Browser 111.1.49.120
Mailer: Protonmail

Please let me know if you need any further information from me to resolve this issue.

Best regards,
Daniel Boll. 🎴

**Comment by laurmaedje** [comment]
This was a one-time mistake after a long day of email issues. Sorry about that.
