### ISSUE TITLE
`read()` gets wrong relative path when used in a Typst package

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2126]
### Description

I have something like this in a local Typst package:

```typ
#let include-code(path, lang: auto) = {
  if lang == auto {
    lang = path.split(".").at(-1)
  }
  assert(
    type(lang) == "string",
    message: "'lang' must be a \"string\" or \"auto\"",
  )
  raw(read(path), lang: lang, block: true)
}
```

But when I do:

```typ
#import "@local/package:0.0.1": include-code
#include-code("code.file")
```

The compiler searches in the package's relative directory (where the function is defined and executed). Instead, it should use the default relative path to where the function is called. This means I can't access my files in `$PWD`, only files where the package is located.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by LuxxxLucy** [comment]
Related #1185 #199 #971

Quick workaround for now would be loading the data outside of the pkg and then passing the data into the pkg library
