### ISSUE TITLE
Text in SVG patterns is ignored

### ISSUE THREAD

**Issue by LaurenzV** [typst/typst#2131]
### Description

Consider the following SVG:

```
<svg id="svg1" viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
    <title>Text child</title>

    <pattern id="patt1" patternUnits="userSpaceOnUse" width="40" height="25"
             patternTransform="skewX(10)">
        <text id="rect2" x="2" y="20" font-size="20">Text</text>
    </pattern>
    <rect id="rect3" x="20" y="20" width="160" height="160" rx="20" ry="20"
          fill="url(#patt1)" stroke="darkblue"/>
</svg>
```

Including it in Typst results in the following output:
<img width="417" alt="image" src="https://github.com/typst/typst/assets/47084093/8e244e44-790b-4d7d-b9b2-cad5f239b179">

While it should look more like this:
<img width="620" alt="image" src="https://github.com/typst/typst/assets/47084093/e2adba3f-ca24-4661-b6a9-0ae5784267d5">

It seems to be some kind of font issue again (even though the SVG doesn't actually use any specific fonts...). If I replace the following snippet

https://github.com/typst/typst/blob/68fc6f5bc090ca787ede21c55ec6c7f83d86ce34/crates/typst/src/image.rs#L314-L315

with 
```rs
let mut fontdb = fontdb::Database::new();
fontdb.load_system_fonts();
let mut referenced = BTreeMap::<EcoString, Option<EcoString>>::new();
```

it seems to work again, at least on my computer. 

Note that this issue is not a regression, it also appears in previous versions of Typst.

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Perhaps the traversal that finds all text elements never reaches the pattern.

**Comment by LaurenzV** [comment]
Looks like it. It also doen't work when putting the text into a clip path. Will investigate.
