### ISSUE TITLE
Too complex example for custom footer in page setup

### ISSUE THREAD

**Issue by Beiri22** [typst/typst#2132]
### Description

The example for Custom footer with page numbers is 
```
#set page(
  footer: locate(loc => {
    let page-num = counter(page)
      .at(loc)
      .first()

    let page-total = counter(page)
      .final(loc)
      .first()

    strong[
      American Society of Proceedings
    ]
    h(1fr)
    [#page-num/#page-total]
  })
)

This page has a custom footer.
```

Af far as I know, you just need: ```counter(page).display("1/1", both: true)```

Putting it to:
```
#set page(
  footer: [
    *American Society of Proceedings*
    #h(1fr)
    #counter(page).display("1/1", both: true)
  ]
)

This page has a custom footer.
```

### Typst version

- [ x] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
You are right.

**Comment by Beiri22** [comment]
Would you add the simple solution to contrast different approaches or would you replace it?

**Comment by laurmaedje** [comment]
I would just replace it.

**Comment by Beiri22** [comment]
can you reproduce the circle-example with ```counter(page).display()```?

**Comment by laurmaedje** [comment]
I guess you could, but I don't think it would be clearer in that case. And we do want to show both ways somewhere in the guide.

**Comment by Beiri22** [comment]
It works:
```
#set page(
  footer: [
    *Fun Typography Club*
    #h(1fr)
    #counter(page).display(page-num => {
      let circles = (
        box(circle(
          radius: 2pt,
          fill: navy,
        )),
      ) * page-num
      box(
        inset: (bottom: 1pt),
        circles.join(h(1pt))
      )
    })
  ]
)
```

Maybe set those examples next to each other ;-) In some manuals I have seen some tab-like example boxes, so that only one is shown, but you can choose which variant ... ?

**Comment by laurmaedje** [comment]
I applied both your simplifications. Thanks!
