### ISSUE TITLE
Add ability to print anything to stdout (debugging)

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2137]
### Description

Since Typst has a pretty powerful coding side, you can do a lot of stuff with arrays, strings etc. What I've found is the lack of debugging functions. I was looking for `print`, but only found `assert` and `panic`. Using `panic` for debugging is truly cursed. So I was wondering if we can get an easy `print`/`println`/`log` function. And maybe only enable them when a special option/flag is used in the CLI (`--debug` or use the `-v`). It's much simpler than #1669.

### Use Case

Print array or boolean or integer or content that is being generated somewhere or even in the loop. In v0.8 you can only print to the output file (if possible) or be a madman and use `panic`/`assert` (nooo!!!).

**Comment by laurmaedje** [comment]
I know that you've linked #1669 and said that this proposal is much simpler, but this is exactly what #1669 is about. Whether it's called `print`, `log` or `trace` is a question of design, but the feature is what that issue was about.

**Comment by Andrew15-5** [comment]
Wait, I thought that `trace` is for printing a stack frame/callback stack (like Python and other PL). This is why I specifically said about stdout and just printing anything.

**Comment by laurmaedje** [comment]
`trace` is probably a bad name, `log` would be a better one. but it's only meant for printing.
