### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by zouharvi** [typst/typst#214]
Thanks for the amazing project! My sentiment about it is [pretty clear](https://twitter.com/zouharvi/status/1638870887028989953). I wanted to inquire whether there is a way to sponsor this project financially.

I understand that it may be tricky to set it up, since this project is sponsored by EU/city of Berlin.

**Comment by GroophyLifefor** [comment]
It can be better in `Discussions` than Issues.

**Comment by zouharvi** [comment]
Good point, thanks. Started [here](https://github.com/typst/typst/discussions/252).
