### ISSUE TITLE
Use winget-releaser GitHub Action to automate new versions publishing to the Windows Package Manager

### ISSUE THREAD

**Issue by PuntitOwO** [typst/typst#2140]
It seems that every [Typst related PR in winget-pkgs](https://github.com/microsoft/winget-pkgs/pulls?q=Typst) was made manually.
Would it make sense to automate this process? I think it would be possible to create or use a GitHub Action like [winget-releaser](https://github.com/vedantmgoyal2009/winget-releaser) that would automatically create a PR in winget-pkgs repo for every new Typst release. This would make it easier to keep the Typst package up to date in winget.

**Comment by laurmaedje** [comment]
Perhaps such an automation could live in a separate repository? Generally, we don't manage packages in package managers ourselves (and that's a good thing because I wouldn't know how to maintain such an action, etc.)

**Comment by laurmaedje** [comment]
This is out of scope for the Typst project itself.
