### ISSUE TITLE
Wrong file extension while exporting

### ISSUE THREAD

**Issue by dwpeng** [typst/typst#2147]
### Description

While exporting a not pdf but svg or png format, and don't pass the output filename, the ouput file extension is always `pdf`. Is there anything wrong.

The relative code as following

```rust
// https://github.com/typst/typst/blob/main/crates/typst-cli/src/compile.rs#L24
pub fn output(&self) -> PathBuf {
  self.output
      .clone()
      .unwrap_or_else(|| self.common.input.with_extension("pdf"))
}
```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
What command are you trying to run exactly?

**Comment by dwpeng** [comment]
> What command are you trying to run exactly? (The complete line)
Thanks for your replay.

I using the following command, the output file is `code.pdf`,
```sh
typst c code.typ -f png
```
But if I pass the output filename like this
```sh
typst c code.typ -f png code.png
```
the output file's extension is correct. Maybe it is not a bug, but I think that when I want to export a `png` or `svg` format file, the output file‘s extension should be as same as the `f` arg passed.

**Comment by Enter-tainer** [comment]
typst compile main.typ results-{n}.svg should work.

**Comment by PgBiel** [comment]
> > What command are you trying to run exactly? (The complete line)
> > Thanks for your reply.
> 
> I using the following command, the output file is `code.pdf`,
> 
> ```shell
> typst c code.typ -f png
> ```
> 
> But if I pass the output filename like this
> 
> ```shell
> typst c code.typ -f png code.png
> ```
> 
> the output file's extension is correct. Maybe it is not a bug, but I think that when I want to export a `png` or `svg` format file, the output file‘s extension should be as same as the `f` arg passed.

Oh I see. I'd consider this to be a bug, in the sense that it definitely shouldn't just append `.pdf` (it should either append the correct extension or error straight away).

**Comment by laurmaedje** [comment]
Fixed via https://github.com/typst/typst/pull/2166
