### ISSUE TITLE
Convenient syntax for nested import

### ISSUE THREAD

**Issue by ntjess** [typst/typst#2148]
### Description

It would be highly convenient to allow full folders to exist as local packages:

```typ
#import "@local/my-templates/proposal/nsf.typ": *
```

Currently, this results in the following error:
```
error: `templates/proposal/nsf` is not a valid package name
```

### Use Case

I have one templates folder with several options:
```
templates
├───slides
|   ├───dark.typ
|   └───light.typ
└───proposal
    ├───nsf.typ
    └───sbir.typ
```
Currently, the best workaround is to use a relative import:
```typ
#import "../../../templates/slides/dark.typ": *
```

This is not ideal because (1) it is sensitive to the location of the main document and (2) requires typst to be run with `--root` to work.

I would love to symlink this folder to `typst/packages/local` and access it as a "package" to increase reusability. Even if I were to "publish" `templates` as a package to make this happen, it would still require "flattening" each template into something individually accessible since only one entrypoint can be specified:

```typ
#import "@local/templates:0.1.0": slides-dark
// Even so, this does not allow for star-imports of *only* the "slides/dark" template helpers
```

It seems like potential solutions are to:
- Allow multiple entrypoints
- Allow the entrypoint to be a keyword like "folder" or "none" or something similar that indicates there are subpackages
- Allow arbitrary folders to be placed in `local` without complaining that they are nonconformant packages

**Comment by laurmaedje** [comment]
It was an intentional design decision that a package only exposes its definitions and not its directory tree. Otherwise, pretty much any change to a package would be potentially breaking. The current syntax isn't super convenient for nested packages, but you could have something like this:
```typ
#import "@local/templates:0.1.0": slides
#import slides: dark
#import dark: *
```
We could think about a way to better support nested imports.

**Comment by ntjess** [comment]
That makes sense; I was thinking since packages versions must be pinned on import there's not a large worry of breaking changes. my background is Python, where by default all files and objects are reachable but authors use underscores in the name to denote internal utilities.

Alternatively, how do you feel about allowing `entrypoints` in the toml to be an array? It might involve the following specification:
- When entrypoints is a string keep the current behavior
- When entrypoints is an array,
  - `#import package:0.1.0"` is an error
  - `#import package:0.1.0/foo"` specifies the "foo.typ" entrypoint (any other separator could do)
- When entrypoints is a dict,
  - `{default=""}` indicates which entrypoint is used in the case of `#import "package:0.1.0"`
  - `{modules=[]}` indicate candidates for array usage

Of course these are mere suggestions; I don't know how much this increases complexity and you may have already eliminated these ideas in the past for reasons I didn't consider.

**Comment by ntjess** [comment]
That works too! It has no verbosity overhead compared to raw file access 👍

**Comment by laurmaedje** [comment]
Okay, I think we can make this a thing!

**Comment by ntjess** [comment]
If I were to use
```typ
#import "@local/templates:0.1.0": slides.dark.my-dark-theme
```

What would be the proper usage later?

```typ
#show: my-dark-theme

// OR

#show: slides.dark.my-dark-theme
```

I have a preference toward the latter, since it matches what was specified by the user and they can simply combine it with an "as" import to get the former syntax:

```typ
#import @local/templates:0.1.0": slides.dark.my-dark-theme as dark-theme
#show: dark-theme
```
This matches Python behavior FWIW.

**Comment by laurmaedje** [comment]
I would it should definitely be the former, because if you want the latter you can just write `#import "@local/templates:0.1.0": slides`.

**Comment by ntjess** [comment]
I am not a rust programmer, but through searching the repo I think [this](https://github.com/typst/typst/blob/main/crates/typst-syntax/src/parser.rs#L1144) is where the change would occur? Is this something a novice can make reasonable progress on?

Thanks for the quick replies!

**Comment by laurmaedje** [comment]
On the parser side, you've found the right place. You would also need adjustments in `ast.rs` and maybe `kind.rs` on the syntax side. On the evaluation side, the relevant code is in `eval/mod.rs` in the `apply_imports` functions.

> Is this something a novice can make reasonable progress on?

I believe yes. You might hit some tricky spots, but if you've got a bit of time I think it should be doable. I'm also happy to help out if you hit any roadblocks or design questions (and the same holds true for the people in #contributors on Discord).

**Comment by ramithuh** [comment]
Hi @ntjess! I noticed that you have a `nsf.typ` file (which I hopefully assume is a proposal template for NSF) 
I came across a [tweet](https://twitter.com/nomad421/status/1723912916833804351) [1] that was searching for such template 🥹

If it's a template that's sharable, perhaps it could be very helpful to the person searching for it on Twitter. Apologies if this comes off as prying (I tried searching "nsf" on discord and came across this issue)

[1] https://twitter.com/nomad421/status/1723912916833804351

**Comment by ntjess** [comment]
@ramithuh I was inspired by your request to open source my existing NSF templates: https://github.com/ntjess/typst-nsf-templates.

I don't use twitter, but you are welcome to point them in that direction 🙂

**Comment by PgBiel** [comment]
Will be working on this! (Commenting so I can be assigned :slightly_smiling_face:)
