### ISSUE TITLE
HTML input

### ISSUE THREAD

**Issue by eriCCsan** [typst/typst#2151]
### Description

Hi, I use this program and it is really cool and fun to work with. One feature I miss is a simple compilation of html code. It shouldn't be that high-level like interpreting css and so on, but simple enough to turn basic html into typst.

It worked in pandoc. But i think that could be usefull in typst directly.

### Use Case

I have a simple example of an HTML structure like this:

```
<strong>My strong text</strong> xyz </br> on next line <i>text</i>
```
And it should be a text that I can use in typst like a function.
The use case behind this is that typst can be used when creating PDF from user content. This content is often styled with html and should be converted to typst to get the styling. Think of the text field on Github that you want to use in a PDF.

**Comment by laurmaedje** [comment]
I'm not sure whether HTML input would be a good fit for being built into Typst. However, there are multiple alternatives:

- Convert externally from HTML to Typst, e.g. with pandoc
- There could be a Typst package (possibly implemented with a plugin) that performs the conversion

**Comment by eriCCsan** [comment]
Thank you for correcting the title. I don't write in github very often.
Yes pandoc might actually work I have tested it. 
Unfortunately I haven't found a package yet.

Yes you are right. I'm not sure if it really fits in the build. But I just wanted to bring it to the table :)

**Comment by laurmaedje** [comment]
There isn't a package yet, that's true. Maybe somebody on Discord would be interesting in building one! I'll close this issue for now then as its unlikely to be supported directly.
