### ISSUE TITLE
Respect colour profile for CMYK images

### ISSUE THREAD

**Issue by baptiste** [typst/typst#2158]
### Description

A jpg stored with CMYK profile appears to have its colour profile stripped and interpreted as RGB, resulting in colour shifts.

Here's a [side-by-side comparison typst document](https://typst.app/project/rtpMLDB24dlWOBFDVDT456), where I made three versions of the image using photoshop

<img width="541" alt="Screenshot 2023-09-16 at 17 22 12" src="https://github.com/typst/typst/assets/18970/bcdecc68-7352-4a1a-b993-df46009a193f">

### Use Case

Images aren't always in sRGB mode

**Comment by baptiste** [comment]
For reference, here's what Latex produces with these 3 images

<img width="537" alt="Screenshot 2023-09-16 at 17 33 49" src="https://github.com/typst/typst/assets/18970/2b1f59fa-ca44-413e-9f57-30da40819d0e">

**Comment by Enivex** [comment]
Closing in favor of https://github.com/typst/typst/issues/3781
