### ISSUE TITLE
Unnecessary space after #citation when citation is at the end of a line

### ISSUE THREAD

**Issue by danaugrs** [typst/typst#2167]
### Description

I encountered an annoying bug where if a `#citation` is at the end of a line, the next line starts with an unnecessary space. I'm using a two-column layout.
![Screenshot from 2023-09-16 14-22-57](https://github.com/typst/typst/assets/5261448/6e0dcfd7-1c65-453b-95e1-b9ec27862765)

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by cphyc** [comment]
I tried producing a MWE but unfortunately couldn't. It seems the issue only happens for large enough and complex enough documents.
Note that:
- if I replace the citation with its text representation (`[CDP19]` in this case), I get the extra space as well
- if I replace the citation with `(CDP19)`, I *do not* get the extra space.
- if I replace the citation with `(CDPXX)`, I *do not* get the extra space.

So there seems to be something happening that's more subtle than just citation mechanism.

![image](https://github.com/typst/typst/assets/5411875/1f3928dc-be8b-4982-aad2-bb61828e0ea4)

**Comment by danaugrs** [comment]
It looks like now there's an extra unnecessary space immediately after a set of citations. This can be seen below, before the line breaks:
![image](https://github.com/typst/typst/assets/5261448/02af588e-b7ad-4d9e-9c9d-d77660f8780e)

And also below, in a single line:
![image](https://github.com/typst/typst/assets/5261448/3537f163-029c-4a35-8c34-5178e618d103)

I'm using the latest release `typst 0.9.0 (7bb4f6df)`

**Comment by laurmaedje** [comment]
@danaugrs This has been fixed briefly after 0.9. The space is a collapsed space from between the merged citations which was erroneously not removed.

**Comment by laurmaedje** [comment]
As a workaround, you can remove the spaces between the individual citations.

**Comment by danaugrs** [comment]
Oh, good to know, thanks!

**Comment by reknih** [comment]
Hey, this seems to be fixed. Please tell us if the issue persists for you on `main`.
