### ISSUE TITLE
Wrong hyphenation outside of words

### ISSUE THREAD

**Issue by danaugrs** [typst/typst#2168]
### Description

There's an unnecessary hyphen when a citation list line breaks. Is there a way to remove it?
![hyphen-citation](https://github.com/typst/typst/assets/5261448/f8c39e9e-4183-4a1d-a819-5b18beb68861)

```
some text #cite("A", "B", "C", "D","E, "F", "G", "H", style: "alphanumerical") more text
```

### Operating system

_Web App_

### Typst version

- [x] I am using the latest version of Typst

**Comment by Enivex** [comment]
How is this handled by bibtex or biblatex?

**Comment by danaugrs** [comment]
I'm not sure - but my stylistic choice would be to not have the hyphen.
Discord discussion: https://discord.com/channels/1054443721975922748/1104438751528226879 for more context.

**Comment by laurmaedje** [comment]
It's not bibliography-specific, the hyphenation algorithm just shouldn't run on things that are not words because it will result in this wonkyness.

**Comment by danaugrs** [comment]
Looks like the hyphen is gone in  `typst 0.9.0 (7bb4f6df)` :tada:
![image](https://github.com/typst/typst/assets/5261448/c7b24a79-a91c-4bb1-98c3-09d461ccfe6b)
However, as can be seen above, there's a new bug: a unnecessary space after a set of citations. Please see [this comment](https://github.com/typst/typst/issues/2167#issuecomment-1817905103) for more information on it.
