### ISSUE TITLE
Closure capturing of variables ignores mutable method calls

### ISSUE THREAD

**Issue by PgBiel** [typst/typst#2169]
### Description

The following example doesn't work starting with commit https://github.com/typst/typst/commit/b7430f6da01550d8388d6a3bcccf0ef0aca9130c (which was pushed to the web app recently):

```typ
#let x = "b"
#let f() = {
  let a = (b: 5)
  a.at(x) = 10
  a
}

#f()
```

It gives the following error:

```
error: unknown variable: x
  ┌─ bruh.typ:4:7
  │
4 │   a.at(x) = 10
  │        ^

help: error occurred in this call of function `f`
  ┌─ bruh.typ:8:1
  │
8 │ #f()
  │  ^^^
```

It doesn't seem to be capturing `x`. We can force it to work by using `x` before the mutable method call (the following example works):

```typ
#let x = "b"
#let f() = {
  let _ = x
  let a = (b: 5)
  a.at(x) = 10
  a
}

#f()
```

This appears to have made tablex not work at all due to a line which uses this (https://github.com/PgBiel/typst-tablex/issues/62).

### Operating system

Web app, Linux

### Typst version

- [ ] I am using the latest version of Typst

**Comment by Shigan-Liu** [comment]
I have the same problem when setting the page header:

```typst
#set page(
    paper: "a4",
    margin: (x: 3.18cm, y: 2.54cm),
    header: locate(loc => {
      let years = query(
        selector(heading.where(level: 1)).before(loc),
        loc
      )

      let months = query(
        selector(heading.where(level: 2)).before(loc),
        loc
      )

      if years == () {
        let year = "2013"
      } else {
        let year = years.last().body
      }

      if months == () {
        let month = "September"

      } else {
        let month = months.last().body
      }

      align(right, text(
        size: 9pt, 
        style: "italic"
        )[
          Month: #month Year: #year // Unknown variable: month
        ]
      )
    }
    ),
    numbering: "1 / 1",
)
```

It gives the error that `month` is an unknown variable as the comment shown above.

**Comment by PgBiel** [comment]
> (snip)
> It gives the error that `month` is an unknown variable as the comment shown above.

That's not a bug; differently from Python and some other languages, variables you declare in Typst are only visible within their respective scopes / innermost `{ }` they are contained in (in your case, they are only visible within the `if` branches). Here's a fix for your code:

```typ
#set page(
    paper: "a4",
    margin: (x: 3.18cm, y: 2.54cm),
    header: locate(loc => {
      let years = query(
        selector(heading.where(level: 1)).before(loc),
        loc
      )

      let months = query(
        selector(heading.where(level: 2)).before(loc),
        loc
      )

      let year = if years == () {
        "2013"
      } else {
        years.last().body
      }

      let month = if months == () {
        "September"
      } else {
        months.last().body
      }

      align(right, text(
        size: 9pt, 
        style: "italic"
        )[
          Month: #month Year: #year // Unknown variable: month
        ]
      )
    }
    ),
    numbering: "1 / 1",
)
```

**Comment by Shigan-Liu** [comment]
Hi @PgBiel,

Thank you so much for helping me dealing with the problem. I do need more time to get familiar with the syntax of `typst` 😀.

Best regards, 
Shigan
