### ISSUE TITLE
arguments Passing to file

### ISSUE THREAD

**Issue by HernandoR** [typst/typst#2181]
### Description

Hi

I'm considering my requests described in [brilliant-CV/#13](https://github.com/mintyfrankie/brilliant-CV/issues/13#issue-1901200723)

The features I suggest are
if the `typst compile ` can pass arguments to the file.

### Use Case

users can therefore control and adjust the output without editing the source.

for example: some papers require two versions with or without names. or with or without appendixes.

**Comment by laurmaedje** [comment]
Duplicate of https://github.com/typst/typst/issues/295
