### ISSUE TITLE
Add support for range condition (multi-comparison) for numbers (like Python)

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2184]
Created from https://github.com/typst/typst/discussions/2183.

### Description

In Python, "comparisons can be chained arbitrarily, e.g., `x < y <= z` is equivalent to `x < y and y <= z`" (https://docs.python.org/3/reference/expressions.html#comparisons). But Typst doesn't support such a convenient syntax.

> Note that `a op1 b op2 c` doesn’t imply any kind of comparison between a and c, so that, e.g., `x < y > z` is perfectly legal (though perhaps not pretty).

This note can be a thing that we can discuss. Personally, I think this should be legal in Typst too, since it's just a syntax sugar.

This also will require a note/small section in [the documentation](https://typst.app/docs/reference/scripting/).

### Use Case

This would be a nice syntax sugar that will increase readability and decrease syntax clutter/mess of some complex conditional expressions.

**Comment by laurmaedje** [comment]
Quoting the discussion about https://github.com/typst/typst/pull/2347 [from Discord](https://discord.com/channels/1054443721975922748/1088371867913572452/1184571861284179968):

> I think the reason I'm shying away from it is that, in my experience, the need for chained comparisons in Typst code is very rare. I'm questioning whether the code complexity, extra AST node and potential, even if improbable, future compatibility hazard is worth it.

So I'll close this.
