### ISSUE TITLE
`<.` and `.>` for left/right delimiters

### ISSUE THREAD

**Issue by ParadaCarleton** [typst/typst#2185]
### Description

Just saw this in the last breaking changes:
```
Automatic matching of fences in math (| and ||) was removed because there were too many false positives. You can use functions like [abs](https://typst.app/docs/reference/math/lr/#functions-abs), [norm](https://typst.app/docs/reference/math/lr/#functions-norm), or explicit [lr](https://typst.app/docs/reference/math/lr/#functions-lr) calls instead (Breaking change)
```
This makes me think that the problem is being caused by the symmetry of `|`--it's not easy to figure out if two instances of `|` should be paired or not. One proposal: what if instead of `|stuff|`, we used  `<| stuff |>`, with `<` and `>` marking the left/right delimiters?

### Use Case

 This seems more readable than `lr`, but provides an easy way to distinguish left/right absolute values, norms, inner products, etc. from pipes or `<` and `>`.

**Comment by laurmaedje** [comment]
I fear that this would be quite ambigious, e.g. `x<|y|` is something one would perhaps write to get a comparison, i.e. `x < abs(y)`.

**Comment by agarmu** [comment]
At some level, i think that `abs()` and `norm()` is just a better syntax choice and seems more typst-like — reading source code is _so_ much easier if names are descriptive.

**Comment by PgBiel** [comment]
> This seems more readable than lr, but provides an easy way to distinguish left/right absolute values, norms, inner products, etc. from pipes or < and >.

I (respectfully) disagree here; `lr` seems more explicit and readable to me (I can't help but think of literal `< >` insertion when looking at the example... :p). But I guess this is more of a subjective thing

**Comment by laurmaedje** [comment]
Based on the existing comments, I'm going to close this.
