### ISSUE TITLE
diff symbols have inconsistent height on the fractional line

### ISSUE THREAD

**Issue by geeker-one** [typst/typst#2188]
### Description

both in typst.app and on my local machine complied pdf have this problem
```typst
$
(diff a_x)/(diff x) + (diff a_y)/(diff y)
$
```
preview:
![image](https://github.com/typst/typst/assets/101701076/0445a618-0539-48bb-a7c8-fdd478bd669d)

### Reproduction URL

https://typst.app/project/pIq_4PCNGcC17YHplvALJ3

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by EpicEricEE** [comment]
For reference, XeLaTeX and LuaLaTeX show the same behavior when using `\usepackage{newcomputermodern}`

**Comment by Enivex** [comment]
To some extent it's unavoidable to have some inconsistency. The y is taller than the x, so something has to "give"

**Comment by Andrew15-5** [comment]
The reference probably doesn't cause a notification, but the `diff` symbol is probably gonna be renamed soon: #3211.

**Comment by laurmaedje** [comment]
I would consider this not a bug.

**Comment by MDLC01** [comment]
After the work that was done in #4153, I think it makes sense to ask for better alignment here as well.

**Comment by laurmaedje** [comment]
From what I understand, LaTeX also suffers from this problem. That's a difference from #4153. Essentially, unconditionally moving the `diff a_x` up looks bad and doing it only if `diff a_y` is somewhere would be very non-local.
