### ISSUE TITLE
arrow.l.r as accent

### ISSUE THREAD

**Issue by 8LWXpg** [typst/typst#2189]
### Description

I except `accent(A B, <->)` generate same thing like `\overleftrightarrow` in LaTeX

excepted:
![image](https://github.com/typst/typst/assets/105704427/83b4b9f5-1758-4bef-95fb-df7d063dd38b)

outcome:
<img width="60" alt="image" src="https://github.com/typst/typst/assets/105704427/3877ad98-7d37-4652-bc3a-ecdc25749d75">

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
`accent(a,\u{20e1})` works

Same with 20d0 and 20d1 for harpoons
