### ISSUE TITLE
Citation in caption does not work with outline

### ISSUE THREAD

**Issue by ZZzzaaKK** [typst/typst#2191]
### Description

I've encountered the bug that was discussed and closed in #796 while trying to #cite from inside a figure caption. I've reproduced it on Typst Release Versions 0.6.0, 0.7.0 and 0.8.0 as well as "nightly" version 0.8.0 (163c2e1a) using the minimal repro from [here](https://github.com/typst/typst/issues/796#issuecomment-1508974627).

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
I can't reproduce this. With the linked reproduction, do you get the "index out of bounds" panic or does the error manifest itself in some other way?

**Comment by ZZzzaaKK** [comment]
Sorry, the issue came up because I was using an old version of the Typst LSP extension.
