### ISSUE TITLE
Web App Preview `height/width: auto` changes only on `space` or `enter` press

### ISSUE THREAD

**Issue by jakobhellermann** [typst/typst#2195]
### Description

When you have a page with `width` or `height` set to `auto` in the web app, and type something that would change the calculated size (like a newline, or writing to the longest line), the preview will only apply the new size after a `space` or `enter` keypress:

https://github.com/typst/typst/assets/22177966/5745b437-e8b0-4ce9-a0ae-4a7d003cd5e2

Until then, the text will be non-uniformly stretched and squished.

### Browsers

Firefox, Chrome

### OS

Linux

**Comment by laurmaedje** [comment]
Fixed.
