### ISSUE TITLE
Floating placement leaves space between paragraphs

### ISSUE THREAD

**Issue by Zheoni** [typst/typst#2199]
### Description

When the figure floating placement moves the figure out of it's original position, it leaves a bigger than expected space. This happens when the paragraph block spacing is set with `em` but not when it is set with `pt`.

![image](https://github.com/typst/typst/assets/38019254/565445fb-df77-4ca2-bf95-e2cf1a9e5063)

This code reproduces the issue. I also share a link to the typst web app.
```typ
#set page(height: auto)
#set text(size: 10pt)
#[
  #show par: set block(spacing: 5pt)

  `#show par: set block(spacing: 10pt)`

  A Paragraph
  
  Paragraph before figure.
  
  #figure(
    caption: [The caption.],
    placement: bottom,
    raw(lorem(10)),
  )
  
  Paragraph after figure. Expected space.
]

#v(2cm)

#[
  #show par: set block(spacing: 0.5em)

  `#show par: set block(spacing: 0.55em)`
  
  A paragraph.
  
  Paragraph before figure.
  
  #figure(
    caption: [The caption.],
    placement: bottom,
    raw(lorem(10)),
  )
  
  Paragraph after figure. *BIGGER SPACE!*
]

#v(2cm)
```

Also tested in windows with `typst 0.8.0 (360cc9b9)`.

### Reproduction URL

https://typst.app/project/ru15OQv30nRZ3PmVHoSynu

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
Possibly related to https://github.com/typst/typst/issues/1238 ?
