### ISSUE TITLE
Incorrect handling of line breaks in bibtex files

### ISSUE THREAD

**Issue by oskgo** [typst/typst#2207]
### Description

The following typst code:
```
#cite("foo")
#bibliography("test.bib")
```
together with the following bibtex file:
```
@misc{foo,
author="Smith, John 
and Smith, Jane"}
```
render as follows:
<img width="136" alt="Screenshot 2023-09-22 at 14 27 30" src="https://github.com/typst/typst/assets/92018610/fe2261aa-943e-4f48-9f43-851f10c8966d">
This is clearly not what was intended. I'd expect it to render the same as the version without newlines, which looks like this:
<img width="166" alt="Screenshot 2023-09-22 at 14 25 16" src="https://github.com/typst/typst/assets/92018610/f0303d17-c90e-4311-b8fd-96c3963740e9">

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by reknih** [comment]
This is now fixed.
