### ISSUE TITLE
AMS Paper template duplicates figure.supplement

### ISSUE THREAD

**Issue by Gbkng** [typst/typst#2208]
### Description

In the file `template.typ` when starting a new project with the `AMS Paper` template, the show rule for `figure` is:

```
show figure: it => {
    show: pad.with(x: 23pt)
    set align(center)

    v(12.5pt, weak: true)

    // Display the figure's body.
    it.body

    // Display the figure's caption.
    if it.has("caption") {
      // Gap defaults to 17pt.
      v(if it.has("gap") { it.gap } else { 17pt }, weak: true)

      smallcaps(it.supplement)
      if it.numbering != none {
        [ ]
        it.counter.display(it.numbering)
      }
      [. ]
      
      it.caption  // < BUG IS HERE
    }

    v(15pt, weak: true)
  }
```

I think there is a bug at the `BUG IS HERE` comment. One wants to use `it.caption.body` instead of `it.caption`. Otherwise, all parts of `caption` are printed (notably `supplement` and `numbering`), whereas they are already displayed above.

This bug makes the `figure.supplement` and `figure.numbering` displayed twice.

### Browsers

Chrome

### OS

Linux

**Comment by laurmaedje** [comment]
Was fixed via https://github.com/typst/templates/pull/15. However, a commit to the template repository doesn't automatically update the web app templates. I have made the update now.

**Comment by Gbkng** [comment]
Sorry for the issue duplication ! 
I searched for similar issue in this repository but not in `typst/template` ... 

Thanks for applying the fix !

**Comment by laurmaedje** [comment]
> Sorry for the issue duplication !

No worries!
