### ISSUE TITLE
Stacktraces for Errors

### ISSUE THREAD

**Issue by ParadaCarleton** [typst/typst#2210]
### Description

I'd love to have a stacktrace for errors (or at least the first few levels), so I can see where in my code things went wrong.

### Use Case

Right now it's almost impossible to debug errors if an exception is thrown inside a library; this should make it much easier to find where my code's going wrong.

**Comment by laurmaedje** [comment]
Related: https://github.com/typst/typst/issues/1747

Stack traces are typically shown with blue squiggles in the web app, but there are no stack traces when things go wrong inside locate, style, or layout callback.

**Comment by ParadaCarleton** [comment]
Closed as duplicate of #1747 , then.
