### ISSUE TITLE
Incorrect scaling of preview on incremental compilation

### ISSUE THREAD

**Issue by frozolotl** [typst/typst#2212]
### Description

Assume the following starting state:
```typ
#set page(paper: "a9")
```
Then type any text at all (one character is enough):
```typ
#set page(paper: "a9")
hello
```

Now the preview looks like this:
![preview](https://github.com/typst/typst/assets/44589151/1019ffd4-c8db-497d-aec5-7febfd044364)

### Browsers

Firefox

### OS

Linux

**Comment by laurmaedje** [comment]
Probably related to https://github.com/typst/typst/issues/2195

**Comment by laurmaedje** [comment]
Fixed.
