### ISSUE TITLE
math content is not affected by text baseline

### ISSUE THREAD

**Issue by 8LWXpg** [typst/typst#2214]
### Description

```typst
hello #text(baseline: -5pt)[#sym.WW\orld]\
hello #text(baseline: -5pt)[$WW$orld]\
```
<img width="183" alt="image" src="https://github.com/typst/typst/assets/105704427/4d879d0f-a8b7-4bdf-a469-aeb7cd3051a2">

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/2220
