### ISSUE TITLE
Hyphen missing inside table

### ISSUE THREAD

**Issue by KillTheMule** [typst/typst#2217]
### Description

Please have a look at the following image: https://imgur.com/a/tQbMlx5

Those are the first 2 columns of a 5 column table (the rest don't matter), but only 1 row. The content of the 2nd coumn doesn't fit, so it gets broken up appropriately. But, as you can see, the hyphen itself is missing.

Unfortunately, I can't share the full file, but I've not been able to reproduce that in a somewhat minimal setting. I'll keep on trying, but maybe that's a known issue? Or even on purpose? I'd sure be happy about a workaround, too.

This is with typst 0.8.0 (72f4c543).

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst
(e) Whelp, just now my quest for a reproducer seems to have shown me that running the document through `typst-cli` makes the hyphen show up. Originally, I'm creating it from the library via `typst::compile`, and while I'm not aware of any API knob that could influence this outside of the document, I'll certainly need to investigate more. I'm leaving this open in case someone has a hint ;)

**Comment by LuxxxLucy** [comment]
It would be great if a minimal example can be provided (and we can added the example to the test if we fix it) otherwise debugging can be hard.

**Comment by KillTheMule** [comment]
Sure, I'm working on it. The document is already pretty minimal, but the hyphenation code seems to be called really often, so I'll try to bring down the number of words as well. More problematic though, the code is pretty far from minimal, will take some time before I've got something I can post. Good thing it's weekend ;)

**Comment by KillTheMule** [comment]
So the minimal example would basically be the trivial one:

```typst
#set par(justify: true)

#grid(
  columns: 5%,
 [Materialien]
)
```

When running this through the `typst-cli`, the word is broken up into two lines, and after "Mate", there's a dash added. That's the correct thing to do.

Now to find some smallish code that exhibits my problem :)

**Comment by KillTheMule** [comment]
I've made a huge step forward. The issue is easily reproduceable if you compile the `typst-cli` without the feature `embed-fonts` (which you can easily do by setting `default = []` on line 68 of its `Cargo.toml`.

Now the question is: Is that how it's supposed to be? Of course, one can't just nilly willy change feature flags and hope all is fine, but the document renders without the embedded fonts (as it probably should, there are lots of fonts on my system), it's just that this hyphen/dash is missing. Any idea why other fonts might not be able to show this hyphen? In my own code, I've been using the [Latin Modern](https://www.gust.org.pl/projects/e-foundry/latin-modern) fonts, which led me to this problem. Anything wrong with those? The rest of the document(s) looked fine, if that matters :)

Thanks for any insight!

**Comment by laurmaedje** [comment]
When disabling the feature and setting the font to Latin Modern, I still can't reproduce this on my system. (I have Latin Modern installed.)

**Comment by KillTheMule** [comment]
By "setting font to Latin Modern" you mean in the document itself? If you don't, does it reproduce then? I might be barking up the wrong tree, but it seems to me that the hyphen should appear no matter which font was chosen... or am I wrong?

**Comment by LuxxxLucy** [comment]
Confirm that I can reproduce the bug when embed font is disabled. It seems with out the embed font the pdf looks strange. Not just the hyphen is missing, some numbers are not display properly as well.

my setup 
```
https://github.com/typst/typst/issues/2217
#set par(justify: true)
#grid(
  columns: 5%,
 [Materialien]
)
```

when embed-font is disabled
<img width="493" alt="image" src="https://github.com/typst/typst/assets/19356905/3d0c6198-a8d2-4546-8985-3215bc3de15f">

normal
<img width="594" alt="image" src="https://github.com/typst/typst/assets/19356905/03e96596-6779-4ee8-ab9d-449ffc1f2c32">

**Comment by laurmaedje** [comment]
I couldn't reproduce it because I have Linux Libertine installed. The weird numbers in the link are probably an emoji font because it's part of the default font fallback chain and no other font was found. When no fonts are embedded and no font is specified, the font selection ends up pretty random and the results are very system dependenant. 

I have found the culprit of the hyphen issue though: Typically, Typst does last resort fallback (it picks any font with the character) if the current fallback chain has no match. However, for hyphens [this doesn't happen](https://github.com/typst/typst/blob/0710d1c118efaca52e5151ece32f758f163086b6/crates/typst-library/src/text/shaping.rs#L432). It only walks the normal fallback chain. Probably, we should also do last resort fallback here. 

That said, if you disable font embedding _and_ don't provide Typst's default font _and_ don't set a font in the document, all bets are off w.r.t font selection, leading to wild combinations like in the image above.

**Comment by LuxxxLucy** [comment]
@KillTheMule Can you try the diff on PR#2233? (enabled the font fallback as suggest by @laurmaedje), It should fix the issue (at least it fixes the issue on my machine). Would be great if you can try it out to see whether it can reproduce (it should, just in case).

**Comment by KillTheMule** [comment]
Wow, that went fast, awesome. The PR works, both for the cli without `embed-fonts`, as well as my own application. Great & thanks!

Of course, butchering the fonts selection is bound to show up somehow, but picking at lease _some_ hyphen anyways does make sense imho :)
