### ISSUE TITLE
New selector modifier `.this-page`

### ISSUE THREAD

**Issue by Mc-Zen** [typst/typst#2222]
### Description

Another selector modifier like `.before` and `.after` that instead only matches elements on the page of its argument. 

Suggestions for alternative names:
- `.on-page`
- `.page`

### Use Case

I think there would be many use cases for this, it would for instance be useful to query the current section. 
Currently, you can ask for the `queried-element.page()` and compare it with `loc.page()`. However, it becomes a bit more hairy to get the last element on a page (or when `loc` is at the bottom of the page, then the first element).

**Comment by Mc-Zen** [comment]
wow this issue got a nice number

**Comment by laurmaedje** [comment]
> However, it becomes a bit more hairy to get the last element on a page (or when loc is at the bottom of the page, then the first element).

How would the new selector help with this? Would there be a difference between `query(sel.this-page(loc), loc)` and `query(sel, loc).filter(el => el.page() == loc.page())`

**Comment by Mc-Zen** [comment]
No, actually I think there would be no difference. To be honest, I didn't think of `filter()` and this is quite neat 😅

**Comment by laurmaedje** [comment]
Then, the only remaining benefit would be potential efficiency. But I think it's not a big deal for now. I am going to close this then. :)
