### ISSUE TITLE
Add single-file-only reading mode (in addition to the whole-root-dir mode)

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2227]
### Description

We were discussing inability to access `/tmp` dir which is actually fine, but there are some restricted files/dirs inside the `/tmp/`, and since typst watches the whole root dir, the issue was created: https://github.com/Enter-tainer/typst-preview/issues/130. I was wondering if it would be possible to make a `--single-file-mode` option (whatever the name is) which will only watch for the changes of the specified Typst file and nothing else in the directory where the file exists. But the support for the `@local`/`@previes` packages should stay and be available (in both modes).

### Use Case

Make typst more flexible, i.e. support more aggressive/unideal environment (root dir) by watching only absolutely necessary file(s) instead of the whole directory.

**Comment by Enter-tainer** [comment]
iirc official typst-cli watch each individual file. can you test typst watch in your /tmp?

**Comment by Andrew15-5** [comment]
I can confirm (I forgot I did it a million times already) that `typst` and `typst-lsp` (through `nvim` + `mason.nvim`) can work from `/tmp` even though `typst watch` also has `--root` option.

Now I'm pretty sure I can close this issue, since `typst` doesn't throw any "access denied" errors for unrelated files in the root dir. It only throws them if the imported/included file (or the main file) doesn't have read bit permission:

```log
error: failed to load file (access denied)
  ┌─ a.typ:1:9
  │
1 │ #include "import.typ"
  │          ^^^^^^^^^^^^
  │
  = hint: cannot read file outside of project root
  = hint: you can adjust the project root with the --root argument
```

But the hints are a bit misleading:
1. file is not outside the project root,
2. adjusting the project root doesn't resolve anything.

There should be a hint like:

```log
  = hint: Do you have permission to read the file?
  = hint: Try adding read permission for the file.
```
