### ISSUE TITLE
$ 2 | q^2 => 2 | q $ seems to be incorrectly parsed as $ 2 abs(q^2 => 2) q $

### ISSUE THREAD

**Issue by Error-42** [typst/typst#223]
Input:

```typst
$ 2 | q $
$ 2 | q^2 => 2 | q $
$ 2 abs(q^2 => 2) q $
$ 2 bar.v q^2 => 2 bar.v q $
```

Output:

![kép](https://user-images.githubusercontent.com/54533488/227318479-025281cd-1724-40fd-a1d8-0ad2a279a6fb.png)

`|`s shouldn't be parsed into `abs` such that there's `<=`, `<=>`, or `=>` inside.

**Comment by johanvx** [comment]
I think you should use `divides` here.
