### ISSUE TITLE
`ascender` top-edge of DejaVu fonts incorrect

### ISSUE THREAD

**Issue by 8LWXpg** [typst/typst#2231]
### Description

`ascender` top edge looks more like `cap-height` for DejaVu fonts

```typst
#box(stroke: 0.1pt, text(font: "DejaVu Sans Mono", "Hello", top-edge: "ascender", bottom-edge: "descender"))
#box(stroke: 0.1pt, text(font: "DejaVu Serif", "Hello", top-edge: "ascender", bottom-edge: "descender"))
#box(stroke: 0.1pt, text("Hello", top-edge: "ascender", bottom-edge: "descender"))
```
<img width="303" alt="image" src="https://github.com/typst/typst/assets/105704427/bd799ef3-776c-4b33-b001-0abe2d477024">

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
That's up the font, so I'm not sure I would consider this a bug.

**Comment by 8LWXpg** [comment]
I didn't test all the fonts, but DejaVu fonts is the only ones I get with asymmetric ascender and descender. Maybe it's the problem to the font itself?

**Comment by laurmaedje** [comment]
> Maybe it's the problem to the font itself?

Probably yes.

**Comment by RubixDev** [comment]
Should the default monospace font maybe be reconsidered then? Looking at their repo the DejaVu fonts also seem to have been unmaintained for six years.
