### ISSUE TITLE
Windows版本闪退啊

### ISSUE THREAD

**Issue by zxh451200** [typst/typst#2245]
### Description

双击后一闪就没了

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by sitandr** [comment]
Please, use English if possible (use Google translate or similar things worst-case), otherwise no one will be able to understand you.

**Comment by Enter-tainer** [comment]
if you don't have the experience using cli programs, use the webapp(typst.app) instead.

**Comment by laurmaedje** [comment]
The released binaries are command line programs. Double-clicking won't do what you wish, instead you can run them from PowerShell or Cmd. There are various tutorials in the internet on how to use the command line. 

Alternatively, you can use the web app at https://typst.app, as pointed out by @Enter-tainer.
