### ISSUE TITLE
Alphabetic symbols should be bold

### ISSUE THREAD

**Issue by riccardo-franchi** [typst/typst#2254]
### Description

Right now, in math mode, alphabetic symbols `ell`, `dotless.i`, `dotless.j` cannot be bold. 
I think it may be useful if they could, similarly to greek letters, by using the `bold()` function.

### Use Case

It is especially useful when writing vectors in physics papers, as dotless i and j can be used as unit vectors.

**Comment by Enivex** [comment]
There simply aren't bold versions of these in unicode, so they would have to be synthesized.

Related: https://github.com/typst/typst/issues/394

**Comment by laurmaedje** [comment]
Closing in favor of #394.
