### ISSUE TITLE
Differentiate between single-tick raw text and triple-tick raw text

### ISSUE THREAD

**Issue by rubenjr0** [typst/typst#2256]
### Description

It would be nice if it were possible to differentiate between single-tick raw text and triple-tick raw text (such as code blocks).

If we wanted to write a template where we give code blocks a specific format it'd also affect single-tick raw blocks that we might want to write inline, right?

### Use Case

Example:
#show raw: c => block(inset: 4pt, stroke: 1pt, align: center, c) 

This 'raw' is inlined and shouldn't be affected.

```py
print('But this one should be formatted')
```

**Comment by Dherse** [comment]
You already can using the `block` argument on the `raw` function/constructor: https://typst.app/docs/reference/text/raw/#parameters-block

You can then do something like:

```typ
// Case for tripple backticks
#show raw.where(block: true) => { ... }

// Case for simple backticks
#show raw.where(block: false) => { ... }
```

**Comment by laurmaedje** [comment]
The `block` parameter in combination with a `where` selector is what you're looking for.

```typst
#show raw.where(block: true): block.with(inset: 4pt, stroke: 1pt)
```

This will only apply the rule to actual code blocks, not inline code. Note that technically the distinction isn't just one backtick vs three backticks, it's whether the code block contains at least three backticks _and_ a newline. You can also use three backticks for inline code if you want to provide a highlighting tag.

**Comment by rubenjr0** [comment]
Thank you both so much, hadn't spotted that in the docs, I appreciate it. 

Best regards.
