### ISSUE TITLE
Function for Inserting Individual References (outside of Bibliography)

### ISSUE THREAD

**Issue by stellarpower** [typst/typst#2258]
### Use Case

I need to produce a document, somewhat like this:
![image](https://github.com/typst/typst/assets/5004545/155fded6-8885-4a26-add0-4465671f6141)

Where individual references are listed in-line with the text, and not in a bibliography. But I'd like Typst to compose the citation style for me, using entries from a Hayagriva/BibTex file, and not paste that text in myself.

### Description

So far, I don't see any function documented that can take a single source from the bibliography and produce its formatted version according to the selected reference style - everything I see in the [documentation](  https://typst.app/docs/reference/meta/ ) appears to relate to inserting a bibliography at the end of the document and then referencing these citations within the text.

If a function performing this isn't available, I'd like to suggest that one is exposed to the language - the functionality is presumably in the `Bibliography()` call - so I would guess that the easiest way of doing this is that the formatting of a particular reference is pulled out into its own function, and then bibliography formally runs through the list of all referenced entries, formats these using the same function, and numbers them.

Thanks

**Comment by fredguth** [comment]
I was looking for something similar (like a bibentry).  I want to create references in a document margin and right now I have no clue on how to do that.

**Comment by laurmaedje** [comment]
We can see how to cater to those use case once the more solid bibliography foundations (CSL) are in place.

**Comment by stellarpower** [comment]
> We can see how to cater to those use case once the more solid bibliography foundations (CSL) are in place.

Agree, makes sense to include it as part of the wider discussion.

Presumably, does hayagriva have some function akin to this (albeit in rust) within its sources? I.e. once CSL support is complete, there presumably is some method to format an individual reference according to the particular style within that crate.

**Comment by laurmaedje** [comment]
> Presumably, does hayagriva have some function akin to this (albeit in rust) within its sources? I.e. once CSL support is complete, there presumably is some method to format an individual reference according to the particular style within that crate.

The API is likely to change, but it should be possible quite easily, yeah.

**Comment by laurmaedje** [comment]
This is now supported through the new `form: "full"` setting on the `cite` function.

**Comment by stellarpower** [comment]
Fantastic! I'll give it a try as soon as I can.

By symmetry, is it also possible to add a bibliography and not print / discard the output? This was the situation I was needing originally when looking into this, although adding a bibliography and not always displaying it seems a better way of doing it than just rendering individual citations, since you also get the other benefits of managing a collection.

**Comment by laurmaedje** [comment]
You can write `show bibliography: none` somewhere above your bibliography. That will make the visible output go away.
