### ISSUE TITLE
Regression in `#show raw: set text()`

### ISSUE THREAD

**Issue by l1mey112** [typst/typst#2259]
### Description

A show-set rule on `#raw` no longer respects text colours. I believe this to be a regression, this wasn't present a month ago and came up when I updated my compiler.

```
#show raw: set text(fill: white)
#raw("hello")
```

![2023-09-29_15-54](https://github.com/typst/typst/assets/66291634/c7d0b2ac-4ad5-4074-975d-eb3f80af7bcb)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by mattfbacon** [comment]
Bisected to 163c2e1aa27169c1eba946204096d3e8fdfd3c18

cc @Dherse

**Comment by Dherse** [comment]
> Bisected to 163c2e1aa27169c1eba946204096d3e8fdfd3c18
> 
> cc @Dherse 

I'll have a look in a few minutes, probably just white being accidentally set to some other color 😬

**Comment by Dherse** [comment]
I have determined that the error does not come from `raw.rs`, when doing text shaping, the fill is already set to black, this tells me that the PDF export code is working as intended, it might be trickier than just looking there, I am also quite surprised that the color PR is causing this

**Comment by Dherse** [comment]
Ok, so I found it and it is **very** insidious, I'll fix it and open a PR

**Comment by Dherse** [comment]
Thanks for finding this bug BTW, it should be closed soon enough :)
