### ISSUE TITLE
Make Tufte-style tables achievable, and possibly the default.

### ISSUE THREAD

**Issue by OctarineSourcerer** [typst/typst#226]
They've become a staple of LaTeX tables, and look fantastic. However, with the current stroke capabilities of `table`, they're rather difficult to achieve.

To give an idea of what these look like (from [here](https://simplexct.com/data-ink-ratio-tables)):
![image](https://user-images.githubusercontent.com/6842867/227328711-c9ed1139-f2a6-4acc-ba18-d2f2f3ab17e7.png)

I believe the original text detailing these tables was _The Visual Display of Quantitative Information_ by Edward R. Tufte, though I don't have a copy myself. I always used the slides found [here](https://people.inf.ethz.ch/markusp/teaching/guides/guide-tables.pdf),  which seemed to achieve something similar.

Anyways; to manage typesetting these kind of tables, I imagine table's `stroke` property would need to be far more powerful, perhaps a function taking cell indices and returning a stroke.

I realise this isn't a complete spec, so anyone else that's familiar with Tufte tables, please put in your thoughts!

**Comment by laurmaedje** [comment]
There is a `table-strokes` branch that does pretty much that, but I didn't get it done in time for the beta launch because there's lots of edge cases to be handled.

**Comment by OctarineSourcerer** [comment]
> There is a `table-strokes` branch that does pretty much that (functions for cells), but I didn't get it done in time for the beta launch because there's lots of edge cases to be handled.

That's fantastic! Is there any kind of testing you need?

**Comment by mrwunderbar666** [comment]
May I add to the wishlist:

please also add native support for captions **and** table notes. In academic writing, we often need a caption for the table (e.g., "Table 1: Descriptive Statistics") and below the table some notes (e.g. "Note: sample was taken in the year 1980").

Realizing tables with these requirements is a pain in latex and often leads to compatibility issues with other packages. Therefore, I would be grateful if my suggestion could be considered.

![image](https://user-images.githubusercontent.com/20080275/228343882-8107e4ef-d73c-42a4-9a4a-523d1094cdd7.png)

**Comment by kwertyops** [comment]
It seems like this library makes it possible: https://github.com/PgBiel/typst-tablex/

**Comment by mrwunderbar666** [comment]
> It seems like this library makes it possible: https://github.com/PgBiel/typst-tablex/

This seems great, but I would prefer that this extended functionality finds its way into typst itself. This would prevent the chaotic LaTeX situation where there are at least three different packages for table rendering that are required just for typesetting a standard academic table.

**Comment by 0ip** [comment]
Any news on that front?

**Comment by laurmaedje** [comment]
Not really. :/ I had resumed work on this a while ago, but didn't get to finishing it. The existence of `tablex` has made it a bit less pressing that some other things.

**Comment by caemor** [comment]
> May I add to the wishlist:
> 
> please also add native support for captions **and** table notes. In academic writing, we often need a caption for the table (e.g., "Table 1: Descriptive Statistics") and below the table some notes (e.g. "Note: sample was taken in the year 1980").
> 
> Realizing tables with these requirements is a pain in latex and often leads to compatibility issues with other packages. Therefore, I would be grateful if my suggestion could be considered.
> 
> ![image](https://user-images.githubusercontent.com/20080275/228343882-8107e4ef-d73c-42a4-9a4a-523d1094cdd7.png)

The notes for the table can already be kind of done:
```typst
#figure(
  [
    #table(
      columns: 4,
      [t], [1], [2], [3],
      [y], [0.3s], [0.4s], [0.8s],
    )
    #align(left, [Note: Note xyz])
  ],
  caption: figure.caption(
    position: top,
    [Timing results]
  )
)
```

**Comment by mrwunderbar666** [comment]
@caemor this makes me happy :)

**Comment by Heinenen** [comment]
@PgBiel, the author of the `tablex` package mentioned above is now in the process of bringing better tables to Typst, cf. https://github.com/typst/typst/pull/3009 and https://github.com/typst/typst/pull/3037.

**Comment by Enivex** [comment]
This is now achievable with the new tables.
