### ISSUE TITLE
Backport build fix for 0.8

### ISSUE THREAD

**Issue by jeffa5** [typst/typst#2260]
### Description

Could the bug fix to make typst buildable be backported to 0.8.0 / released in 0.8.1?

https://github.com/typst/typst/pull/2130 for reference PR.

### Typst version

- [ ] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
May I ask whether you have a specific case where you need this? I understand that it would be nice in principle, but at this early stage I think releasing 0.8.1 might be unnecessary overhead if the issue will be fixed in 0.9.0 anyway. Only git dependencies are affected after all and these could just switch to depending on a different commit hash?

**Comment by jeffa5** [comment]
Trying to use the `typst` crate for a Rust project and it would be nicer to link to the tag and raise it as a solved issue rather than a particular commit in the repo.

**Comment by alerque** [comment]
Shouldn't the Cargo.lock file make this a non-issue? The v0.8.0 CLI builds just fine with the frozen dependencies. In the v0.8.0 library crate the version is pinned already to the patch level.

**Comment by jeffa5** [comment]
I don't think the `Cargo.lock` file gets used when you reference the `typst` crate as in another projects' `Cargo.toml`

**Comment by jeffa5** [comment]
I'm `ref`ing to the fixed commit now but more of a thing for future, given the potentially longer time between feature releases.

**Comment by laurmaedje** [comment]
In the future, once things settle down, I'm open to backporting things. For now, I don't think it's worth it.

**Comment by alerque** [comment]
@jeffa5 I understand the lock file does not apply when using the crate as a library in another project. My point was only that the lock file used for the CLI *does* garanti a specific version of the dependencies, and the 0.8 release still builds fine with those locked dependencies. In other words I don't understand how the 0.8.0 release is broken in a way that needs fixing, it worked when it came out and still does. No?

**Comment by jeffa5** [comment]
Well, I'm using `typst` as a Rust crate, not the CLI.
