### ISSUE TITLE
More metadata fields for document; hide Creator Tool

### ISSUE THREAD

**Issue by miliog** [typst/typst#2266]
### Description

I want to be able to add more metadata fields via [document](https://typst.app/docs/reference/meta/document/) such as:

- Keywords
- Description
- Rights
- Creator Address
- Creator City
- Creator Postal Code
- Creator Country
- Creator Work Telephone
- Creator Work Email
- Creator Tool (to overwrite `Typst x.x.x`)

### Use Case

Currently, Typst can only set a select few metadata fields. It's also not possible to change/hide the Creator Tool without postprocessing the PDF document.

**Comment by LaurenzV** [comment]
I can get behind things like city and phone number (although I'm not sure if PDF has specific fields for those), but any reason why you would want to change the creator tool?

**Comment by gfpj** [comment]
This would be really important to make it possible to [prevent](https://webmasters.stackexchange.com/a/103656) the PDF file from beeing indexed by Google (for example if careless colleagues upload it somewhere)

**Comment by Dherse** [comment]
I just checked and here are the following base metadata values that the PDF spec officially supports:
- Title: 
- Author
- Subject
- Keywords
- Creator
- Producer
- CreationDate
- ModDate
- Trapped

They're almost all deprecated in favour of the document metadata stream (some weird XML thing called XMP). This requires its own [ISO standard](https://www.iso.org/standard/75163.html). A quick glance on the Adobe Developer website gives the following (interesting) entries:
- `dc:` (the most common stuff) https://developer.adobe.com/xmp/docs/XMPNamespaces/dc/
- `xmp:` https://developer.adobe.com/xmp/docs/XMPNamespaces/xmp/
  - `CreateDate`
  - `CreatorTool`
  - `Identifier`
  - `Label`
  - `Rating` (why not eh!)
  - `BaseURL`
  - `Nickname`
  - `Thumbnails` (array of images)
-  `xmpRights:` (should probably be part of a larger discussion on right management for PDF's) https://developer.adobe.com/xmp/docs/XMPNamespaces/xmpRights/
  - `Owner`
  - `UsageTerms`
  - `Marked` (whether it's a right-managed resource)
- `xmpMM:` A bunch of digital asset management, I would assume this would fit better in the enterprise/payed offering that typst will offer one day, it's weird and I don't really get it 🤷‍♂️

**Comment by LaurenzV** [comment]
I think Typst already writes XMP metadata.

**Comment by Dherse** [comment]
> I think Typst already writes XMP metadata.

Yes it does, I was just mentioning a more complete list of things we could make available.

**Comment by laurmaedje** [comment]
@miliog I find it a strange requirement to hide the creator tool. I'm not aware that other software allows this. If it's important for you to minimize information leakage, I think this a job for a PDF post-processor.

**Comment by laurmaedje** [comment]
Still, I think it's a very niche thing. Moreover, there's a thousand different ways to identify that a PDF was produced by Typst, from the PDF formatting, which other metadata it writes, to the way the file is structured and the way it embeds fonts. It's just not a goal of the project to prevent this. Since many PDF post-processors change up the file quite a lot, you could get a lot more anonymity out of that anyway than by just suppressing the creator tool.

**Comment by laurmaedje** [comment]
Accurately declared creator tools are required by many standards such as PDF/A. I just don't see a reason why this should be configurable. In my view it's not sensitive information. If your view differs, that's fair enough, but then it's just a job for a PDF post-processor. Besides, you could just as well forget to configure this in Typst.

**Comment by alerque** [comment]
> Hypothetically, what if a specific version of Typst had a vulnerability when reading images and an attacker managed to smuggle a payload into your Typst project?

Then you have bigger problems.

This is starting to sound like security theater. I say that as someone with an extensive background in network security before I found myself lost in the realm of typesetting.

In the event a service is public facing and accepts arbitrary input in return for output there is a small sliver of possibility hiding the host software (say a web sever), but even that has proved to be tenuous. In the case of Typst putting creator meta data in generated artifacts you aren't really showing what you *are running* so much as what you *did run* at some point. Almost all *document* (PDF, Word, Open Document, SVG, even HTML) formats support this and it is common place to use. In the case of public facing web server software some attempts are often made to obfuscate it (say to hide the WordPress version) but that has not proved effective against hackers which can just as easily fingerprint it other ways or just attempt every known vulnerability no matter what the reported version is.

Typst leaves its signature written in bold all over the generated output, having it in a human readable field does nothing to weaken security.

**Comment by laurmaedje** [comment]
> I just found out that this seems to be the real reason for the reluctance

For me, personally, that's really not the reason. I actually wasn't in that investor meeting and hadn't even heard about that part when I first responded here. My reason for not that wanting this is really just that I'm not a big fan of adding knobs everywhere unless I see real motivation and that just isn't the case here for me. There's a thousand other potential knobs we could add that affect how the PDF output is generated.

**Comment by LaurenzV** [comment]
I can't comment on the status of whether this can actually be included in the Typst language, but if you are willing to use a fork of the compiler for your use case, you just need to change that one line: https://github.com/typst/typst/blob/9b09146a6b5e936966ed7ee73bce9dd2df3810ae/crates/typst-pdf/src/metadata.rs#L10

**Comment by TS53** [comment]
The following Python code removes the `Creator` information from a Typst pdf file efficiently without making the pdf file invalid:

```python
filename = "typst_file.pdf"
with open(filename, mode="rb") as input_pdf:
    output_filename = filename+"_no_creator.pdf"
    output_filename = output_filename.replace(".pdf_", "_")
    with open(output_filename, mode="wb+") as output_pdf:
        for line in input_pdf:
            start_idx = line.find(b"/Creator (Typst ")
            if start_idx >= 0:
                end_idx = line.find(b")", start_idx)
                assert end_idx > start_idx
                creator_entry = line[start_idx:end_idx+1]
                line = line.replace(creator_entry, b" "*len(creator_entry))
            output_pdf.write(line)
```
