### ISSUE TITLE
Matrix augmentation stroke colour isn't defaulted to text colour

### ISSUE THREAD

**Issue by OptimisticPeach** [typst/typst#2268]
### Description

Basically the title -- in my template I have the following:
```typ
set page(
  numbering: "1", 
  number-align: center,
  fill: back_colour,
)
set text(
  font: "New Computer Modern", 
  lang: "en",
  fill: text_colour,
)
set table(
  stroke: text_colour,
)
```
Which yields the following colour scheme:
![image](https://github.com/typst/typst/assets/24464956/8a0fd0bf-986f-4347-b4cd-41565f0d29fb)
However when I typset a matrix with an augment, the augmentation bar doesn't get my text colour by default unfortunately:
```typ
$mat(augment: #1, M, v) arrow.r.squiggly mat(augment: #1, R, b)$
```
Becomes:
![image](https://github.com/typst/typst/assets/24464956/f14c9803-7d66-4244-b5de-4bf4542789cc)
However, I would expect that the default augment colour is the text/table colour. 

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/2281
