### ISSUE TITLE
Min integer value gets parsed as a float

### ISSUE THREAD

**Issue by Dav1com** [typst/typst#2284]
### Description

According to the Typst documentation https://typst.app/docs/reference/foundations/int/ the smallest integer is `-9223372036854775808` but when using the literal for that number it gets parsed as a `float` instead of an `integer`. The value can still be obtained through arithmetic:

```typ
#let literal_min_int = -9223372036854775808  // parsed as float
#let real_min_int = -9223372036854775807 - 1

#type(literal_min_int) // float

#type(real_min_int) // integer
```

### Reproduction URL

https://typst.app/project/rb52J82NefdZ4oTOE3ODK_

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Ah, it's because Typst doesn't have negative integer literals, so what you're effectively writing is a positive literal that is then negated. And the absolute value of the maximum representable number is one less than that of the minimum representable number in two's complement.

**Comment by Dav1com** [comment]
I see, adding negative literals would make it work as one would expect from other languages, but adding a note in the documentation about "negative literals" should do it too
