### ISSUE TITLE
Pass `size:` argument from `abs` and `norm` to `lr`

### ISSUE THREAD

**Issue by r0uv3n** [typst/typst#2292]
### Description

Currently, it is not possible to control the size of the delimiters of the `abs` and `norm` functions. It seems natural for wrappers such as these around less semantic functions like `lr`, to pass additional arguments down to the wrapped functions. Thus 
`abs(integral_a^b f dif x,size:#90%)`
should produce the same result as
`lr(|integral_a^b f dif x|,size:#90%)`.

### Use Case

Integral delimiters as above are one common place where autoexpanding delimiters produce suboptimal results, and it seems cumbersome to always have to revert to `lr` in those cases.

**Comment by Dherse** [comment]
Amazing, congrats :tada:
