### ISSUE TITLE
Elements with no content can force a breakable block to create an empty frame

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#2297]
### Description

If a block has its `breakable` property set to `true`, it may be broken across multiple pages in what are called “frames”. When an element in a block is too big to fit on the current page, it creates a new frame on the next one and the block continues there. If the first frame of a block is empty (typically, because the first element of the block was too big to fit on the first page), it is not displayed (unless there is no other frame).

https://github.com/typst/typst/blob/cf9bde3245817e068c8253070e7a94dcc05369fb/crates/typst-library/src/layout/container.rs#L423-L426

However, if the first frame of a block contains elements that have no visible content (like a counter update), it is still displayed, even though it has no visible content.

This issue should not be too hard to fix, as a similar problem was already solved in #1929, although there is something more to this one: out-of-flow elements (typically, [`place`](https://typst.app/docs/reference/layout/place/)) should be treated as “basically empty”, and they may also have to move accross frames. Indeed, if the element that causes the first frame to be displayed is an out-of-flow element, I think it is safe to assume you would want it to (1) not cause the first frame to be displayed, and (2) be laid out as part of the first displayed frame.

### Reproduction URL

https://typst.app/project/rKKGxCfjnle00zlOLl1J4R

### Typst version

- [X] I am using the latest version of Typst

**Comment by MDLC01** [comment]
I realise now that I may not have been very clear in the original message: the main question here is how to treat out-of-flow elements.

**Comment by laurmaedje** [comment]
Example:
```typst
#set page("a6")

#lorem(120)

#block(stroke: 2pt, inset: 10pt, width: 100%)[
  #counter(heading).update(1)
  #rect(height: 70pt)
]
```
