### ISSUE TITLE
Stop memoizing plugin calls

### ISSUE THREAD

**Issue by TheLukeGuy** [typst/typst#2309]
### Description

Plugin calls are currently memoized: calling a plugin function twice with the same set of arguments will only _actually_ invoke the function once—the result is cached during the first call and retrieved from the cache during the second call. This is fine for pure functions, but WebAssembly does not require that functions be pure and allows mutable global data in the form of memories, tables, and mutable global variables.

This behavior was **intentionally** introduced in 5df550f. I believe this should be changed for two reasons:

1. It's counterintuitive. When you have functions that read and write from their module's state, it's pretty confusing when a function only sometimes works as expected (when you call the function with a set of args that it hasn't been called with before) and sometimes doesn't. There's no documentation suggesting that this behavior exists.
2. It's restrictive. I know that, as explained in the [docs for `state`](https://typst.app/docs/reference/meta/state/), having traditional global data is problematic in Typst, but I believe there are uses for it that don't have these issues like debug tools. Creating a plugin seems like the perfect avenue for implementing such tools for Typst, and using "global state is weird with typesetting" as a justification for keeping such restrictions on a system intended for advanced users that otherwise does not adhere to the typical rules of Typst would feel strange, in my opinion.

Of course, performance is a very valid reason to keep the _existing_ behavior, so perhaps a middle-ground option where plugins or plugin function calls can opt in or out of memoization would be ideal. For instance:

```typ
#let plugin = plugin("plugin.wasm")
#plugin.foo(bytes("bar"), memoize: false)
// or...
#plugin.foo(bytes("bar"), pure: false)

// or...

#let plugin = plugin("plugin.wasm", memoize /* or pure */: false)
#plugin.foo(bytes("bar"))
```

If a solution like this isn't possible, I still think for the reasons above that it's a worthy trade-off. Plugin function calls are already quite efficient and have minimal overhead (for instance, I tried 100,000 identical [`diagraph.render`](https://github.com/typst/packages/blob/main/packages/preview/diagraph/0.1.1/lib.typ#L3) calls with and without memoization on Typst 0.8.0 and both took 1-2 seconds on my Mac14,9) and further optimizations could theoretically be made on the Wasm interpreter level.

Other alternative solutions include:

- Enforcing pure functions to prevent inconsistent behavior resulting from memoization
- Documenting the behavior resulting from memoization on the [`plugin` page](https://typst.app/docs/reference/foundations/plugin/)

But these would only improve the intuitiveness without solving the restrictiveness.

### Use Case

As mentioned above, one specific use case (which is my personal use case) is tools for debugging Typst documents, but this would benefit anyone using plugins with non-pure functions. Many non-Typst-specific programs that could otherwise be ported to Typst via plugins would have to deal with the strange effects of this behavior, should it not be changed.

**Comment by laurmaedje** [comment]
I indeed forgot to document this. That said, the fix is likely changing the docs, not the semantics. Fundamentally, plugin function **must be pure.** The reason for this is not just that they can be memoized themselves, it is fundamentally important because Typst functions must be pure (which is enforced in the language) and since Typst functions can call plugin functions, these must be pure, too. Even if a plugin function wasn't memoized, it would be immediately memoized one level up because Typst functions are memoized. Purity is absolutely central for Typst, not just because of "global state is weird with typesetting", but also because of incremental compilation. Providing a `memoize: false` escape hatch doesn't help because it breaks memoization at all higher levels of the hierarchy.

**Comment by TheLukeGuy** [comment]
Thanks for the explanation! I figured the lack of memoization would propagate up to the Typst functions invoking the plugin functions (and so forth), but that makes total sense and I apologize for not checking beforehand.

I'll leave the issue open since it seems like the lack of documentation is still a valid issue.
