### ISSUE TITLE
strong not working

### ISSUE THREAD

**Issue by 4cq2** [typst/typst#231]
with this markup:

~~~md
hello *world*
~~~

I get this result:

https://github.com/typst/typst/files/11057346/strong.pdf

reference:

https://typst.app/docs/reference/text/strong

**Comment by laurmaedje** [comment]
seems like a font issue. the text in your file uses Segoe UI Emoji, which doesn't have a bold variant. most probably you are missing Typst's default fonts. they should be embedded in the binary if you have the latest version, however.

**Comment by 4cq2** [comment]
> seems like a font issue.

thanks for the suggestion! this works:

~~~
#set text(font: "Segoe UI")
hello *world*
~~~

> the text in your file uses Segoe UI Emoji, which doesn't have a bold variant.

hm, I wonder why it chooses that font. does Typst have some font selection algorithm, or is it random?

> most probably you are missing Typst's default fonts. they should be embedded in the binary if you have the latest version, however.

yes this is intentional. I prefer not to have embedded fonts, so I built the program without. my operating system comes with some pre installed fonts, so I would prefer to use those. I understand that can have some compatibility issues, but I am OK with that.

**Comment by 4cq2** [comment]
thanks for the comment @laurmaedje. so Typst does not consider if a font has bold available, when its making its choice. do you think that is an error, or working as expected?

**Comment by 4cq2** [comment]
what about this pseudocode:

~~~go
func has_glyphs(font system_font, glyphs []font_glyph) bool {
   for _, glyph := range glyphs {
      if !font.has(glyph) {
         return false
      }
   }
   return true
}

func find_font(glyphs []font_glyph, bold bool) *system_font {
   for _, font := range fonts {
      if has_glyphs(font, glyphs) {
         if bold && font.has_bold() {
            return &font
         }
      }
   }
   return nil
}
~~~
