### ISSUE TITLE
Copy lines when insert-mode, after that, became normal mode

### ISSUE THREAD

**Issue by JJH123123123** [typst/typst#2311]
I had a problem with normal & insert modes in VS code.

while I am trying to copy lines pressing command + c, press "command + c"

but, suddenly the mode is changed into normal mode from insert mode.

I don't know whether it's a bug or not.

Just I want that it could be solved as soon as possible.

Thank you for reading my issue. 

1. before copy

![before_copy](https://github.com/typst/typst/assets/34098750/ae5b3657-73f1-4b3b-8eaa-7abfa36c5090)

2. after copy

![after_copy](https://github.com/typst/typst/assets/34098750/43f89d3f-e81f-4a12-bc23-e2cc97d20915)

3. and then paste 

![paste](https://github.com/typst/typst/assets/34098750/ab394c09-422c-43da-b587-cf03cae1db9f)

I already checked command - c key collides with typst short-cuts. 
But, there is nothing to collide with.
Honestly, I didn't change any shortcut related to command + c.

here is my short-cut settings about typst. 

![shortcut](https://github.com/typst/typst/assets/34098750/b14bf191-b1e7-4888-bb5d-2eefe5fc0eb4)

**Comment by istudyatuni** [comment]
I think this behaviour is related to the vs code plugin, not typst

**Comment by laurmaedje** [comment]
You can report issues with the VS Code plugin here: https://github.com/nvarner/typst-lsp/

**Comment by JJH123123123** [comment]
@istudyatuni @laurmaedje thank you for your comments, I re-issued it into  https://github.com/nvarner/typst-lsp/

Have a nice day
