### ISSUE TITLE
Use `auto` to keep the default size for images, instead of expanding

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#2313]
### Description

When adding an image to a document, the default `width` and `height` are both `auto`, which means the image uses as much available space as possible. You can achieve a similar result (although not completely equivalent) with the arguments `(width: 100%, height: 100%, fit: "contain")`.

I suggest that `auto` should instead mean "whatever the size of the original image is".

I guess the more general problem is that relative sizes on an image might be relative to its container, or the image itself. As far as I am aware, the former is currently impossible in Typst as of today.

### Use Case

This would be especially useful when importing an SVG file that contains text. That way, a text with font size, say, 14pt, in the SVG will appear as 14pt in the final document.

**Comment by notPlancha** [comment]
I think auto should stay as it is (because of its association with behaviour of css afaik) and instead add an some option of `image(width = original, height = original)` or something similar

**Comment by blackjyn** [comment]
+1 for this.
Auto should be the image's original's w/h

**Comment by Andrew15-5** [comment]
Auto-expanding won't work if the image doesn't fit in the page. Here is a workaround for that: https://github.com/typst/typst/pull/3571#issuecomment-1983791852.

**Comment by chipaaco** [comment]
Is there any way to set the image to it's original pixel size? i want a workaround

**Comment by MDLC01** [comment]
You can measure an image to get its dimensions (with the conversion factor 1pt = 1px I think).

```typ
#context image(path, ..measure(image(path)))
```
