### ISSUE TITLE
A page containing only a `raw` element has its header and footer in monospace font

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#2314]
### Description

When a page contains only a `raw` element, its header and footer use a monospace font.

More generally, the header and footer of a page that contains a single visible element will "inherit" from the style of said element.

### Reproduction URL

https://typst.app/project/rxLV7oWr482O7eZ_L5gzSg

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Duplicate of https://github.com/typst/typst/issues/241
