### ISSUE TITLE
Can't attach label to show rule target

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2317]
### Description

Labels in Typst can be very useful. You can append `<some-label>` to the end of any line in global scope and then refer to it in some way. But if it is inserted from _some_ local scope (from code mode) then it will be ignored and as a result an error will be shown which (basically) says that such label does not exist.

````typ
#locate(loc => {
  let data = query(<some-label>, loc).at(0)
  //         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error occurs here.
  [Found: #data]
})

// These don't work:

#show raw: it => [
  #[#it <some-label>]
]

#show raw: it => {
  [#it <some-label>]
}

#show raw: it => [#it <some-label>]

```
hey
```

text#[<some-label>]

// These do work:

text <some-label>

#[text <some-label>]

#{
  [text <some-label>]
}
````

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
The problem is not that you can't append labels in local scopes, but that you can't attach labels to the target of show rules because their label handling happens _before_ the show rule is invoked.

**Comment by Andrew15-5** [comment]
> The problem is not that you can't append labels in local scopes, but that you can't attach labels to the target of show rules

This is not a `show` rule: `text#[<some-label>]`, but it also raises error in `locate()`.

**Comment by laurmaedje** [comment]
> This is not a show rule: `text#[<some-label>]`, but it also raises error in locate().

This one is not intended to work. A label attaches to the element that precedes it in its scope and in that scope there is no preceding element.

**Comment by Andrew15-5** [comment]
> This one is not intended to work. A label attaches to the element that precedes it in its scope and in that scope there is no preceding element.

https://typst.app/docs/reference/meta/label/:

> Inserting a label into content attaches it to the closest previous element that is not a space. Then, the element can be [referenced](https://typst.app/docs/reference/meta/ref/) and styled through the label.

I'm not sure if it's just me or not, but here is how I thought about (even after reading the documentation again):
- "Inserting a label into content" means that label should be in `content` (in the end), so both `#label("some-label")` and `#[<some-label>]` in the end would be in the global `content`.
- "attaches it to the closest previous element" since there are no references to "in its scope" in the documentation, this phrase means that label "attaches [...] to the closest previous element" in the global scope.
- "that is not a space": `text` is not a space, and there are intentionally no spaces in my example (just to be more specific/clear).

And **just to be clear**, the documentation needs to be updated to address the issue of `text#[<some-label>]` not being intended to work.

**Comment by laurmaedje** [comment]
Yes, the documentation could be clearer on this.

**Comment by Andrew15-5** [comment]
```rs
/// Currently, labels can only be attached to elements in markup mode, not in
/// code mode. This might change in the future.
```

Well then, I hope that some day we will be able to attach labels in code mode. I assume this refers to the `show` rule (as well).
