### ISSUE TITLE
Allow array of content as argument to grid

### ISSUE THREAD

**Issue by KronosTheLate** [typst/typst#2339]
### Description

It would be fantastic to allow `grid` to take an array of content and splat the elements as separate content arguments, so that `grid(array_of_content)` would be equivalent to `grid(array_of_content.at(0), array_of_content.at(1), array_of_content.at(2), ...)`.

### Use Case

A figure with a grid of images with some consistent file-name scheme:
```typst
#figure(grid(
{
  let filename_start = "my_prefix"
  let filename_end = ".png"
  let endings = ("1", "2", "3", "4", "5", "6")
  let filename_transformer(ending) = filename_start + ending + filename_end
  let filenames = endings.map(filename_transformer)
  
  filenames.map(image)
}
))
```

**Comment by KronosTheLate** [comment]
Great! Thanks for the pointer. It would be nice to see that in an example of that in the documentation for `grid` as well ^_^

**Comment by KronosTheLate** [comment]
I am unable to find the code that defined the page https://typst.app/docs/reference/layout/grid/, where I would like to add this example. How is one supposed to make PRs to the docs?

**Comment by laurmaedje** [comment]
It's here: https://github.com/typst/typst/blob/main/crates/typst-library/src/layout/grid.rs#L6
