### ISSUE TITLE
Scripts are sometimes in the wrong position with `lr()`

### ISSUE THREAD

**Issue by Enivex** [typst/typst#2342]
### Description

The following
```typst
$
lr(|,size: #3em)_a^b
$
```
produces
![image](https://github.com/typst/typst/assets/2191754/57df7553-4c23-4111-8629-d80fecc8bce0)

The scripts are in the wrong place.

If I put anything else in there, even a zws, they appear in the right place

```typst
$
lr(zws|,size: #3em)_a^b
$
```
![image](https://github.com/typst/typst/assets/2191754/0fa4aec4-cb20-4331-a501-86c6448ac26b)

### Typst version

- [X] I am using the latest version of Typst

**Comment by mkorje** [comment]
On `main`,  adding a zws or anything else no longer makes the scripts appear in the right place. If I'm remembering correctly, I believe #4545 caused this.

Regardless, I think we need to change/remove the `text-like` field on the fragment structs (to something better), which would then resolve this. I'll try to think of a better way to pass around "text-like"-ness.

**Comment by Enivex** [comment]
> On `main`,  adding a zws or anything else no longer makes the scripts appear in the right place. If I'm remembering correctly, I believe #4545 caused this.
> 
> Regardless, I think we need to change/remove the `text-like` field on the fragment structs (to something better), which would then resolve this. I'll try to think of a better way to pass around "text-like"-ness.

Does this qualify as "urgent" considering there's no workaround anymore?

**Comment by laurmaedje** [comment]
I would not classify the breaking of a workaround as a regression/urgent. If someone comes up with a solution until the release candidate I'd be happy, but otherwise I'd say it's a bug just like any other.

**Comment by mkorje** [comment]
With #5030 merged, `$stretch(|, size: #3em)_a^b$` should work.

But that doesn't actually work. I think I know what I overlooked in the PR. I'll make a fix.

**Comment by mkorje** [comment]
`math.stretch`, which was recently added, also suffers from this same bug with script attachments.

**Comment by Enivex** [comment]
> I would not classify the breaking of a workaround as a regression/urgent. If someone comes up with a solution until the release candidate I'd be happy, but otherwise I'd say it's a bug just like any other.

There's definitely been a regression, since it's broken even in situations without a workaround.

```
$ lr(size: #2em, [x])_0^1 $
```
renders as 
![image](https://github.com/user-attachments/assets/2acb7d18-3fdb-4514-8d2b-a50fcfe22b0a)

in 0.12 and 

![image](https://github.com/user-attachments/assets/62bd3e8c-a5f2-475f-9760-8447087675b8)

in 0.11.1.

Attachments do not seem to care about manual scaling at all.

**Comment by Enivex** [comment]
This does work as a workaround for now
```
lr([x #block(width:0pt,height:2em) #h(-1/3*1em) ])_0^1
```
