### ISSUE TITLE
`trim` does not implement rust's regex

### ISSUE THREAD

**Issue by KillTheMule** [typst/typst#2344]
### Description

Try

```typst
#let fn(text) = {
  text.trim("[ba]", repeat: true)
}

#fn("xab")
```

By definition `[ba]` should match either `a` or `b`, and therefore, repeatedly trimming it should leave only `x` (or leave out the `repeat` argument, it still returns the string unchanged). The [syntax link](https://docs.rs/regex/latest/regex/#syntax)  from the [regex](https://typst.app/docs/reference/foundations/regex/) page very much suggests that this should work (unless I horibly misunderstand something).

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by KillTheMule** [comment]
Ouhhh bloody hell, you're right of course, thanks. I'd vote for a tad more "in-your-face" documentation here though ;)

**Comment by andreasKroepelin** [comment]
I've spent way too much time on fixing exactly that error in the past as well ;)
