### ISSUE TITLE
Control to override default accent behavior

### ISSUE THREAD

**Issue by whooie** [typst/typst#2349]
### Description

When using math accents, the accent gets stretched horizontally to cover all of whatever's being accented. This is desireable for things like overlines or tildes but, at least for the `hat` accent, it would be nice to have an option to override this behavior and prevent the accent from being stretched, which is the default in Latex:

Latex: 
![latex-hat](https://github.com/typst/typst/assets/15965124/301011c5-f5c3-4fee-80d3-b2000a124796)
![latex-hat-multi](https://github.com/typst/typst/assets/15965124/f730d45f-3fdc-483c-a870-b80351dc9a31)

Typst:
![typst-hat](https://github.com/typst/typst/assets/15965124/c73cd906-bdbc-4797-89f3-c1147c227771)
![typst-hat-multi](https://github.com/typst/typst/assets/15965124/24ccb753-7bcb-4fdb-88a2-ddf003c79fec)

And, sorry to double up here, but I also noticed that this accent slightly misplaces superscripts:
![rendered](https://github.com/typst/typst/assets/15965124/77071b83-5310-489d-b04b-43a578df8f76)

Can this be fixed as well?

### Use Case

Additional controls here would be a nice feature for people coming from Latex, who may expect similar behavior/appearances or level of control over how things look in math mode.

**Comment by 8LWXpg** [comment]
there's already an issue with superscripts and subscripts #2324
