### ISSUE TITLE
regex, show rule, methods and segmentation fault

### ISSUE THREAD

**Issue by Iriamu19** [typst/typst#2355]
### Description

I'm trying to modify some content in a raw block but since we cannot use Lookaround and matching group in regex with Typst, I tried to modify the resulted match by accesing fields. Here a short example :

```typst
#show regex(a_pattern): it => {
        it.fields()
}

a_pattern
```

But I got a segmentation fault :/

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Probably a duplicate of #229
