### ISSUE TITLE
Bracket scaling does not play well with bracket show rules

### ISSUE THREAD

**Issue by Easyoakland** [typst/typst#2357]
### Description

I'm trying to figure out a way to implement a show rule as described here https://github.com/typst/typst/discussions/2205. (Let me now if there is a better way to stylize parens while keeping auto-sizing)

While doing so I discovered this:

```typst
#let get_color(i) = (red, green, blue).at(calc.rem(i, 3)) // or whatever you want

#show math.equation: it => {
    let depth = state("depth", 0)
    let size = state("size", 12em)
    style(styles => size.update(measure(it, styles)))
    let magic = state("keyword", true) // any value works

    show "(": it => {
        locate(loc => {
            // magic.update(x => x) // uncommented somehow fixes spacing

            text(get_color(depth.at(loc)), size: size.at(loc).at("height"), it)
        })
            depth.update(s => s + 1)
    }
    show ")": it => {
        depth.update(s => s - 1)
        locate(loc => text(get_color(depth.at(loc)), size: size.at(loc).at("height"), it))
    }
    it
}

$ (((((((((((3/3/3/3/333333))))))))))) $

$() (()) ((())) (((()))) (((((integral_0 )))))$

$() (()) ((())) (((()))) (((((integral_ )))))$

$() (()) ((())) (((()))) (((((integral_0 3/3/3/3)))))$

$() (()) ((())) (((()))) (((((integral_ )3/3/3/3))))$
```

In the above code if you uncomment the `magic.update(x => x)`:
1. The spacing between parenthesis appears more correct.
2. It fixes the parenthesis around the integral that is cut into two pieces
3. Fixes the parenthesis that is incorrectly smaller than it should be to the left of the `integral_(`.
It doesn't matter what `magic`'s state keyword or value is or what the update function/value is (e.g. `x => x` or `false`).
![commented](https://github.com/typst/typst/assets/97992568/53310a0f-bdac-41c7-b0b5-284db50fb518)
commented out `magic( x=> x)`
vs
![uncommented](https://github.com/typst/typst/assets/97992568/0bb934aa-9589-4188-84db-42aab293fdb1)
uncommented `magic( x=> x)`

But it seems like the line shouldn't do anything.

Both when commented and uncommented the parenthesis don't elongate like the default math styling when using a very tall math equation such as `$(((((((3/3/3/3/3/3/3)))))))$`

This affects both display and inline math. Both Linux and Windows binaries. Version 0.8.0

### Operating system

Windows, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Easyoakland** [comment]
It appears that a zero-width space `[​]` content block or quote "​" also works instead of `magic(x => x)

**Comment by Easyoakland** [comment]
wrapping the `locate` call in both `(` and `)` show rules with `pad` with default `0pt` values of also changes output.

**Comment by laurmaedje** [comment]
I can reproduce this with 0.11.1 in the web app, but not with 0.12.0 Testing, so it seems to be fixed.
