### ISSUE TITLE
Wrapping the document in columns makes page modification and pagebreak impossible

### ISSUE THREAD

**Issue by mvuorre** [typst/typst#2360]
Hi, I'm trying to insert e.g. a landscape page into a document that is mostly in portrait orientation. The [page setup documentation](https://github.com/typst/typst/blob/d1a702f3fda49f7180ccde4f336fa725861be17f/docs/guides/page-setup.md?plain=1#L474) suggests that I can do the following

```typst
#page(flipped: true)[
  = Multiplication table

  #table(
    columns: 5 * (1fr,),
    ..for x in range(1, 10) {
      for y in range(1, 6) {
        (str(x*y),)
      }
    }
  )
]
```

This works in a blank document ([e.g. here](https://typst.app/project/rKMmgOSnBIDvcFZxlKGda8)), but not in e.g. a document using the IEEE template ([here](https://typst.app/project/r6sBlpBZaQu-OtH6Ea4uIZ)). Is there a more general / applicable strategy for moving between page orientations and e.g. column layouts (from 2 to 1 cols, for example)?

**Comment by laurmaedje** [comment]
The problem with the IEEE template is that it wraps everything in two columns which forbids pagebreaks and page modifications. `set page(columns: 2)` prevents that but doesn't allow you do switch between one-column and two-column on one page. To do that, you'd need to wrap only parts of your documents in columns (which is obviously quite inconvenient). We'll have to find a better solution in the future.

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/typst/issues/1278
