### ISSUE TITLE
SVG display ratio issue when specifying size

### ISSUE THREAD

**Issue by NorthSecond** [typst/typst#2367]
### Description

When I insert an svg into the document, it doesn't appear at the proportions and size I set.

The svg file is download from the fontawesome, which has the begining part:

```html
<svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 576 512">
```

and I use the typst code

```typst
#image(
    "fa-home.svg", 
    width: 1.0em,
    height: 1.0em,
    fit: "stretch",
)
```

The picture seems to be a vertical line.

![图片](https://github.com/typst/typst/assets/72327996/17d556cf-05e7-4ef6-8379-fc8b08aa8ce9)

But when I remove the `height="1em"` at the beginning of the svg file, the document becomes normal.

![图片](https://github.com/typst/typst/assets/72327996/d2e34ba0-95e5-4c6d-ac61-badc48bca9c1)

Is there a conflict between the size information in the svg file tag and the size parameter in the `image` function?

### Reproduction URL

https://typst.app/project/rc61as0hehAcqkkCcCNoe9

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
Even smaller reproducible example:
```typst
#image(
    "new.svg", 
    width: 1.0em
) 
```

However, this doesn't seem to be specific to svg images as normal raster images don't work either. There seems to be something weird going on when setting the width to 1.0em.

**Comment by Dherse** [comment]
Perhaps it's just not able to resolve the font size in pt and therefore 1em of 0pt is 0pt?

**Comment by LaurenzV** [comment]
But then it doesn't make sense why it doesn't work for `width: 1.0em` but does work for `height: 1.0em` for raster images.

**Comment by laurmaedje** [comment]
> However, this doesn't seem to be specific to svg images as normal raster images don't work either

What do you mean? I can't reproduce any problem with raster images.

**Comment by LaurenzV** [comment]
No idea, I don't remember anymore, but I guess the original issue still seems to persist.

**Comment by laurmaedje** [comment]
To me it seems SVG-specific and more related to the us of em units _inside_ of the SVG rather than in Typst.

**Comment by LaurenzV** [comment]
https://typst.app/project/ry4ulZgV5bKGXMNycbVnzk

Now I remember, all I did was render the picture to png and then try the same thing. As you can see, the issue seems to exist for pngs as well.

**Comment by laurmaedje** [comment]
The PNG is 576x12px and scaled to 1em width, making the height roughly 0.02em, which turns it invisible. If you set the width to 10em, you can start to see it.

**Comment by LaurenzV** [comment]
Ah... whoops. 😄 so I guess not a bug after all then?

**Comment by NorthSecond** [comment]
It took a while to recall the details of the issue :relaxed:

---

So it looks as if this is an SVG renderer rendering ambiguity? I have this SVG file downloaded directly from the Fontawesome website, using the button on its page to control the size of the image. (Right now using the button to control the size controls both the `height` and `width` attributes, but when this issue was raised, it seemed that controlling the size would just insert the `height` attribute into the svg file.)

![image](https://github.com/user-attachments/assets/7ff5a61b-b659-4579-9f1d-585ab444c990)


However, even when only the `height` attribute is used to control the size of the svg, the proportions of the corresponding file displayed when opened in a browser are normal - that's why I proposed this issue.
