### ISSUE TITLE
Add a space in caption between figure number and colon for french

### ISSUE THREAD

**Issue by Iriamu19** [typst/typst#2389]
### Description

Add a space in caption before colon for french language

### Use Case

In french (and maybe in other European languages) there is always a space before a colon.

It would be nice if it was the case in the figure captions when french language is set for the document.

**Comment by xkevio** [comment]
While it doesn't happen automatically based on the document language, you can already modify the separator for figure captions yourself, like so: `#set figure.caption(separator: [ : ])`.

**Comment by MDLC01** [comment]
Looks like a duplicate of #1303

I'm currently working on a fix.
