### ISSUE TITLE
Symbols render differently in `$math mode$` vs `#sym`

### ISSUE THREAD

**Issue by patrick-kidger** [typst/typst#239]
![image](https://user-images.githubusercontent.com/33688385/227412593-c610f69d-5835-491f-bd62-d0da77802dcc.png)

Possibly this is intended behaviour. (Different fonts for normal and math mode? Which might vary by what fonts are installed?) But at the very least it surprised me when I saw this.

**Comment by laurmaedje** [comment]
Yes, this is because math mode enables a different font.

**Comment by Enivex** [comment]
> Yes, this is because math mode enables a different font.

Is there a way to set the math font? I tried to look through the documentation, but couldn't find anything.

**Comment by patrick-kidger** [comment]
Hmm, what's the expected use case for having two separate symbols? I can't think of a time when I'd deliberately want to mix two different symbol fonts.

**Comment by Enivex** [comment]
> Hmm, what's the expected use case for having two separate symbols? I can't think of a time when I'd deliberately want to mix two different symbol fonts.
> (In passing, congratulations on this project taking off!)

As an example, see

https://en.m.wikipedia.org/wiki/Mathematical_Alphanumeric_Symbols

There are different considerations for designing a symbol for math versus text.

**Comment by laurmaedje** [comment]
I'd say this is working as expected.
