### ISSUE TITLE
Allow flattened 'paths' in function arguments or dict literals

### ISSUE THREAD

**Issue by emilyyyylime** [typst/typst#2394]
### Description

Where nowadays you are forced to write `fun(dict: (key: val))`, allow `fun(dict.key: val)`, with equivalent effect. A similar option would be available for dict literals (i.e. `(a.b: val)`).

Multiple items with the same prefix are allowed, and their values would be recursively merged together. However; if some path has been specified, no other path can use it as a prefix (regardless of order). In particular, this is allowed: `box(stroke.paint: red, stroke.thickness: 5pt)` (and is equivalent to `box(stroke: (paint: red, thickness: 5pt))`); but the following are both disallowed:
```typ
(a.b: 0, a.b: "hello") // Disallowed even with the same value in both places
box(stroke: red + 5pt, stroke.dash: "dashed") // Disallowed even if the original `stroke` were a dictionary
```

The above will also apply to dictionary destructuring patterns, but a so-called 'path' may not be used as a destructuring pattern by itself.

### Use Case

This suggestion has taken a lot of inspiration from TOML tables, which you may similarly specify either implicitly 'inline' with their parent's body, or as 'standalone' tables.

I believe implementing this feature has great potential to reduce clutter in many cases similar to `stroke`, without introducing new language constructs (color + distance ??) especially when only one key of the dict needs to be specified (relevant when different keys have the same type, so you can't just differentiate between the cases by type). \
In fact, I believe even when specifying all elements of a dictionary in this flattened fashion can aid readability in many cases, especially when argument count and indentation start getting out of hand.

Consider the following motivating examples (some of which are compatible with existing standard library APIs, and other meant to inspire possible APIs supposing the feature is implemented)
`box(stroke.bottom: 1pt)`
`line(length: 5em, angle.degrees: 30, stroke.dash: "dashed")`

**Comment by laurmaedje** [comment]
I think this doesn't pull it's weight. It saves just a few keystrokes, but
- adds extra syntax people need to learn
- adds new complexity to the parser
- makes the result harder to edit if you add a second key.

**Comment by emilyyyylime** [comment]
As discussed one time when considering set rules for custom types, I believe one more potential benefit this or a feature like this could add is unifying `set` rule folding behaviour. The rule could simply become that two set rules' assignments will merge if (and only if?[^1]) the latter's 'path' diverges from the formers, so:

```
#set box(stroke.thickness: 5pt)
#box[This is a box with a thick stroke]
#set box(stroke.color: green)
#box[This is a box with a thick, green stroke]
#set box(stroke: (thickness: 1pt))
#box[This is a box with a thin, _black_ stroke]
```

@laurmaedje if you think this makes a significant enough change, consider reopening the issue :)

[^1]: This is probably undesirable, we still want shorthands such as `set box(stroke: red)` for `set box(stroke.color: red)`

**Comment by laurmaedje** [comment]
So, in this proposal `#set box(stroke: green)` would override the thickness, but `#set box(stroke.paint: green)` wouldn't?

**Comment by emilyyyylime** [comment]
> So, in this proposal `#set box(stroke: green)` would override the thickness, but `#set box(stroke.paint: green)` wouldn't?

With the most straight-forward, consistent interpretation, yes. But as I've noted in the footnote, this would be inconvenient both on its own and considering existing behaviour, so values of blessed types may still fold, and this proposal would only affect the folding behaviour of dictionaries.

That is, of course, unless there's some huge

**Comment by emilyyyylime** [comment]
@laurmaedje I don't want to be a nuisance, but do you have any further comments on this suggestion? Would you consider it more viable for further discussions in its current form?

**Comment by laurmaedje** [comment]
I can't say that I am really convinced that this feature would pull its weight. However, I would be open to open a forge thread on Discord so that we can have a bit quicker discussion about it, also with other community members. Should I do that?

**Comment by emilyyyylime** [comment]
Sure, that sounds like a good way to hear more perspectives on the idea
