### ISSUE TITLE
Common geometry accents missing

### ISSUE THREAD

**Issue by slashinfty** [typst/typst#2404]
### Description

Requesting a double-sided arrow accent (like combining `arrow` and `arrow.l`) and a downward-facing curved line accent (like an upside down `breve`).

### Use Case

These are commonly used notation in geometry for lines and arcs.

**Comment by slashinfty** [comment]
It appears that the notation for arcs can be accomplished with `accent()` and `paren.t`.

However, attempting to use `arrow.l.r` or `arrow.l.r.long` with `accent()` does not work for line notation.

**Comment by 8LWXpg** [comment]
related #2189

**Comment by 8LWXpg** [comment]
use `\u{0311}` could be better

```typst
$
accent(A B, \u{0311})
accent(A B, paren.t)
$
```

<img width="75" alt="image" src="https://github.com/typst/typst/assets/105704427/f07d847a-238f-4588-a8a0-6867d5a719fb">

**Comment by JalinWang** [comment]
Perhaps https://github.com/typst/typst/issues/422 is a more generic issue?

**Comment by Enivex** [comment]
> Perhaps https://github.com/typst/typst/issues/422 is a more generic issue?

No, that's a different beast entirely.

**Comment by Enivex** [comment]
I'll close this, as it was partially resolved in https://github.com/typst/typst/pull/2218, and the remaining part overlaps with #422
