### ISSUE TITLE
Names for U+2a0d (⨍) and U+2a0f (⨏)

### ISSUE THREAD

**Issue by Enivex** [typst/typst#2407]
### Description

These have no current names in typst. Should probably be something like integral.dash and integral.slash

Both are used for the average. I've seen the former more often, but "officially" in unicode it's the latter. Therefore integral.avg or integral.mean might be a bit opinionated.

### Use Case

See above

**Comment by T0mstone** [comment]
The official unicode names are
- U+2A0D Finite Part Integral
- U+2A0F Integral Average with Slash
- And while we're at it, we can add U+2A0E Integral with Double Stroke (⨎) as well

I would prefer the descriptive names, so `integral.dash`, `integral.slash`, `integral.dash.double` (or would it be `integral.ddash`? or even `integral.eq`?)

**Comment by Enivex** [comment]
> - And while we're at it, we can add U+2A0E Integral with Double Stroke (⨎) as well

I didn't mention it only because I believe it's extremely rarely used, but I guess it can't hurt.
