### ISSUE TITLE
Improve layout of multi-line headings

### ISSUE THREAD

**Issue by deffi** [typst/typst#2410]
Example document:

```typst
#set heading(numbering: "1.1")

= One
== One point one: #lorem(20)
```

Result (Typst 0.8):
![Typst result](https://github.com/typst/typst/assets/470243/1e16c596-5b51-41d9-a0a8-55d9981af801)

It seems like this could be improved by aligning subsequent lines with the text of the first line, not with the number

This is how LaTeX renders the same thing:

![LaTeX result](https://github.com/typst/typst/assets/470243/5b6a13a9-a89c-48db-9b3f-d77591da20f0)

And MS Word 2016:

![Word result](https://github.com/typst/typst/assets/470243/ec3b2564-a67b-4525-aa08-f5cc48238140)

See also #2411 (similar issue, but for the outline instead of the heading)

**Comment by tingerrr** [comment]
This, as well as #2411, could be fixed by making headings `show` as `stack(dir: ltr, numbering, body)` by default.

**Comment by laurmaedje** [comment]
The stack solution doesn't work correctly at the moment because a horizontal stack, in contrast to a grid, doesn't correctly size its children to fit the width. This means that the body will overflow into the right margin. This should be fixed.

**Comment by Enivex** [comment]
Isn't this largely a matter of personal preference, and something that would vary from template to template?

I'm honestly not a fan of having text aligned to a different vertical line than the margin. That being said, I would never choose titles this long in the first place.

**Comment by tingerrr** [comment]
For now, you can use:
```typst
#show heading: it => if it.numbering != none {
  grid(columns: 2, gutter: 0.3em, counter(heading).display(it.numbering), it.body)
} else {
  it.body
}
```

Which is faithful to the default show rule. A similar thing can be done for `outline.entry` in #2411.

**Comment by deffi** [comment]
> Isn't this largely a matter of personal preference, and something that would vary from template to template?

It may be a matter of personal preference, or it may be a matter of (corporate/academic) style guidelines. So I agree that this should be configurable; I wasn't trying to imply that the way LaTeX or Word are doing it is the only correct one.


> I'm honestly not a fan of having text aligned to a different vertical line than the margin.

Not even in bullet lists? I think that aligning the text to the right of the bullets is by far the most common layout here. An outline (cf. #2411) seems pretty similar to a (nested) numbered list, and many authors are also applying that layout to the headings themselves.


> That being said, I would never choose titles this long in the first place.

This, too, would probably depend on the context. A very quick survey of some textbooks and technical documentation within my reach indicates that titles which exceed the length of a line aren't terribly uncommon.

**Comment by haenoe** [comment]
Hey! Big Typst fan here - thank you all for your tremendous work. I would love to help the project and contribute. 
Therefore my question: Is this issue still relevant?

After looking a bit around the codebase my first idea was to solve it using the same technique applied by the `#enum()`, which internally uses a grid (see [here](https://github.com/typst/typst/blob/09b364e9a35bf5746b932a4bcadf69fbc45521d2/crates/typst/src/model/enum.rs#L275)) to correctly separate the numbering/symbol from the content. 
Does this make sense in this case here (and in the context of `#outline()` (see #2411)?

Thank you!

**Comment by tingerrr** [comment]
Go ahead and implement it, I think it's a better default than the current solution. We don't lose any flexibility so this should be fine. It comes down to laurenz if it will be accepted.

**Comment by laurmaedje** [comment]
Solved by https://github.com/typst/typst/pull/3459

**Comment by jeremias8** [comment]
Is the solution #3459 already working on Typst 0.11.1 ?
My long headings are still misaligned.
`#set heading(numbering: "1.")`
`#heading[A very, very, very, very, very, very long heading]`

Am I missing some config in order to apply the solution?
Thanks.

**Comment by Enivex** [comment]
> Is the solution #3459 already working on Typst 0.11.1 ?
> My long headings are still misaligned.
> ```
> #set heading(numbering: "1.")
> #heading[A very, very, very, very, very, very long heading]
> ```
> <img width="267" alt="document" src="https://github.com/typst/typst/assets/22663114/ac55e3f6-9e4f-4d77-9a11-fe0a6cf0c26f">
> 
> Am I missing some config in order to apply the solution?
> Thanks.

I don't think this was a part of 0.11.1, it'll likely be in 0.12
