### ISSUE TITLE
show regex stackoverflow

### ISSUE THREAD

**Issue by taooceros** [typst/typst#2418]
### Description

The following code will stackoverflow

```typst
#show regex("%\S+"): it => [
  #it.text bbb
]

%ssss
```

`thread 'main' has overflowed its stack`

Without the `.text` it works

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
Duplicate of https://github.com/typst/typst/issues/229

**Comment by taooceros** [comment]
but why does it happen only with `.text`?  I doubt this may be a slightly different issue?
