### ISSUE TITLE
Add identity builtin function

### ISSUE THREAD

**Issue by jakobhellermann** [typst/typst#2433]
### Description

Define a builtin identify function `let id(x) = x` or `let identity(x) = x`.

Possible names:
- `id`
- `identity`
- `unchanged`

Prior art:
- [`id` in haskell](https://hackage.haskell.org/package/base-4.19.0.0/docs/Prelude.html#v:id)
- [`std::convert::identity` in rust](https://doc.rust-lang.org/stable/std/convert/fn.identity.html)
- [`Function.identity()` in java](https://docs.oracle.com/javase/8/docs/api/java/util/function/Function.html#identity--)

### Use Case

When defining a function with named arguments, you need to provide defaults. In some cases a good default will be the identity function, and writing `id` is more convenient than having to type out `a => a` which forces you to pick a variable name.

**Example**:
```typst
#let alternate(even: a=>a, odd: a=>a, args) = args.pos().enumerate().map(((index, item)) => {
    if calc.even(index) { even(item) } else { odd(item) }
})
```
vs
```typst
#let alternate(even: id, odd: id, args) = args.pos().enumerate().map(((index, item)) => {
    if calc.even(index) { even(item) } else { odd(item) }
})
```

**Comment by laurmaedje** [comment]
While this might be useful in a general purpose language sometimes, I think it's very rarely useful in Typst and `x => x` is very simple too.
