### ISSUE TITLE
CJK Punctuation Adjustment Not Comprehensive

### ISSUE THREAD

**Issue by Verplitic** [typst/typst#2439]
### Description

I can see a lot have been done about punctuation adjustment since https://github.com/typst/typst/pull/954, but some punctuations are not covered, eg. question and exclamation marks.

<img width="525" alt="image" src="https://github.com/typst/typst/assets/57583509/68e8da79-da0c-44ec-b488-14962e3c5f4c">

Some common bracket variants are not adapted, either: `【`, `】`, `［`, `］`, `〖`, `〗`, `｛`, `｝`, `〔`, `〕`. I can't provide the complete list here. Maybe refer to the [Unicode Full-Width Forms](https://en.wikipedia.org/wiki/Halfwidth_and_Fullwidth_Forms_(Unicode_block)).

Also, [ctex](https://www.ctan.org/pkg/ctex) adopts five full-width punctuation compression schemes:

- `quanjiao` – Individual full-width punctuations take up `1em` in width, with two neighbouting ones taking up `1.5em` altogether.
- `banjiao` – All CJK punctuations take up `0.5em`.
- `kaiming` – Question/exclamation marks and full stops take up `1em`, all others `0.5em`.
- `CCT` – All punctuations are 'slightly narrower' than `1em` in width.
- `plain` – No adjustment.

Moreover, sources provided in https://github.com/typst/typst/issues/276 contain more specified guidelines on this issue. Thanks for the attention!

### Reproduction URL

https://typst.app/project/r0j15-4jgKGstUYllfWU9V

### Operating system

macOS

### Typst version

- [ ] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
i think the ）！ combination should be covered as clreq stated https://www.w3.org/TR/clreq/#h-punctuation_adjustment_space . 🤔 i will take a look in weekend.

 supporting 【】〖〗should be easy as long as we have a comprehensive list.

**Comment by Enter-tainer** [comment]
![image](https://github.com/typst/typst/assets/25521218/4b931ec1-c09e-4220-acc2-ac843311057b)
I just add ？ and ！to left aligned cjk punctuation list, and it seems that it works?

**Comment by peng1999** [comment]
A workaround for different punctuation compression schemes can be found in [discord](https://discord.com/channels/1054443721975922748/1057632212671025162/1164576700986818590).

**Comment by Verplitic** [comment]
> ![image](https://user-images.githubusercontent.com/25521218/277084050-4b931ec1-c09e-4220-acc2-ac843311057b.png) I just add ？ and ！to left aligned cjk punctuation list, and it seems that it works?

Not sure about technical details, but perhaps the closing Chinese guillemet (书名号) can be further narrowed for better visual effect. Here is how `ctex` in XeTeX does (`punctstyle` set to `quanjiao`).

<img width="279" alt="image" src="https://github.com/typst/typst/assets/57583509/edf9cffb-c511-4c08-991a-156c8228bd5a">

**Comment by Verplitic** [comment]
> A workaround for different punctuation compression schemes can be found in [discord](https://discord.com/channels/1054443721975922748/1057632212671025162/1164576700986818590).

In fact I did it myself 😂

There are still problems in the workaround, like two consecutive `【` can cause misalignment. These combinations are not common in text so, well, it works at least.

**Comment by Enter-tainer** [comment]
i will test on my pr later. previous image is from an early development version and may not reflect current code

**Comment by Enter-tainer** [comment]
![image](https://github.com/typst/typst/assets/25521218/3a06a17a-660f-46ec-bde8-57d0d1338f52)

latest with lang: zh region: CN

**Comment by peng1999** [comment]
> There are still problems in the workaround, like two consecutive `【` can cause misalignment.

- #2456 will fix this in quanjiao scheme (which is the default in Typst).
- In banjiao/kaiming scheme we just make some punctuation marks to be fixed width, and do not need any extra adjustment for consecutive bracket—they are fixed 1/2 em anyway.
- Nobody used CCT style. (I can find [only two](https://github.com/search?q=language%3ATeX+%2Fpunct%5Cs*%3D%5Cs*CCT%2F&type=code) projects in GitHub.

**Comment by Verplitic** [comment]
> > There are still problems in the workaround, like two consecutive `【` can cause misalignment.
> 
> * [feat: support adjust more cjk punctuations #2456](https://github.com/typst/typst/pull/2456) will fix this in quanjiao scheme (which is the default in Typst).
> * In banjiao/kaiming scheme we just make some punctuation marks to be fixed width, and do not need any extra adjustment for consecutive bracket—they are fixed 1/2 em anyway.
> * Nobody used CCT style. (I can find [only two](https://github.com/search?q=language%3ATeX+%2Fpunct%5Cs*%3D%5Cs*CCT%2F&type=code) projects in GitHub).

Could there be a setting item to switch between schemes then? Like `#set text(cjkpunct: "kaiming")` or so.

**Comment by peng1999** [comment]
> Could there be a setting item to switch between schemes then? Like `#set text(cjkpunct: "kaiming")` or so.

You can just write a package to do that.

**Comment by balthild** [comment]
> You can just write a package to do that.

How to do that? Can users tweak the adjustability for each punctuation and make their own schemes, like `LuaTex-ja`?

**Comment by Verplitic** [comment]
> > You can just write a package to do that.
> 
> How to do that? Can users tweak the adjustability for each punctuation and make their own schemes, like `LuaTex-ja`?

I guess they can do so by defining that certain punctuations are put inside 0.5 em boxes:

```typ
#show "；": semicolon => box(width: 0.5em, semicolon)
```

Not sure if user-tweaking will lead to problems / conflicts with hardcoded punctuation squeeze, though.

**Comment by balthild** [comment]
Well... Putting punctuation inside boxes is not a good idea right now, because it breaks the linebreak rules.

```typst
#set page(width: 20em, height: auto)

#set text(
  lang: "zh",
  font: ("Linux Libertine", "Noto Serif CJK SC"),
)
#set par(justify: true)

啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊#box[，]啊啊啊啊啊啊啊啊啊
```

![无标题](https://github.com/typst/typst/assets/2662758/04237125-898c-4dd0-abba-180b79a0d9c9)

**Comment by Enter-tainer** [comment]
perhaps we may open a new issue to track kaiming and banjiao punctuation style.

**Comment by Verplitic** [comment]
> perhaps we may open a new issue to track kaiming and banjiao punctuation style.

New issue in https://github.com/typst/typst/issues/2460. Thanks for the attention!
