### ISSUE TITLE
Bibliography `title` parameter has an empty example in its documentation

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#2447]
### Description

Maybe this should be a web app issue?

This is caused by the following line containing three backticks that are never closed.
https://github.com/typst/typst/blob/208711203e948501544b82b741c77be3bc46ff97/crates/typst-library/src/meta/bibliography.rs#L86

### Reproduction URL

https://typst.app/docs/reference/meta/bibliography/#parameters-title

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This is the correct place for the issue since the faulty markup is in the compiler sources.
