### ISSUE TITLE
Footnote in block renders at the page where the block ends

### ISSUE THREAD

**Issue by Zheoni** [typst/typst#2449]
### Description

This code
```typ
#set page(height: 3cm, width: 5cm, margin: .5cm)

- Item 1
- Item 2#footnote[From item 2]
- Item 3
- Item 4#footnote[From item 4]
- Item 5#footnote[From item 5]
```
Renders this
![image](https://github.com/typst/typst/assets/38019254/87bf7614-dcad-47c7-9c34-d14c382920fc)

I would expect footnotes 1 and 2 to be in the first page, not the second.

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by ludwig-austermann** [comment]
I think I noticed this behaviour also in breakable blocks, which is also suboptimal.

**Comment by laurmaedje** [comment]
Yeah, it's a known limitation :/

**Comment by freetz13** [comment]
The same is happening in `grid`. Any updates on this?

**Comment by laurmaedje** [comment]
Unfortunately no. Tackling this will require larger changes to the layout engine, which will only happen in a longer timeframe.

**Comment by Andrew15-5** [comment]
This was mentioned in https://forum.typst.app/t/how-can-i-get-a-footnote-on-the-same-page-as-its-reference-in-a-multipage-numbered-list-enum/586/2.
