### ISSUE TITLE
Independent Bibliography Style from Cite style

### ISSUE THREAD

**Issue by KevinT3Hu** [typst/typst#2451]
### Description

It seems that currently setting one of bibliography and cite styles would also effect the other one. However, in some cases, I would like to use independent styles on them.

This also would be sufficed if customizable bib referred to in #942 is fulfilled. Anyway, it seems easier to achieve this one.

### Use Case

For example, I am now writing an article according to an unstandard template, and so not satisfied by any of the built in templates. However, a combination of chicago-notes and ieee would make up for that which is likely not allowed.

**Comment by Enivex** [comment]
CSL support will resolve the issue you're referring to in the next release
