### ISSUE TITLE
Show-set rule is not able to set all fields (synthesized ones)

### ISSUE THREAD

**Issue by padix-key** [typst/typst#2459]
### Description

It is not possible to set some settable `figure` parameters via a show-set rule. Take the following example that aims to remove the supplement from a figure caption:

```typst
//#show figure: set figure(supplement: none) // DOES NOT WORK

//#set figure(supplement: none) // DOES WORK

#figure(
  [],
  caption: [
    This is a caption.
  ],
  //supplement: none // DOES WORK
)
```

A possible use case is to make the supplement bold for figures but not for tables.

I found this behavior for the `supplement` and `numbering` parameters, but interestingly not for `gap`.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
More generally show-set on the same element does not work for _synthesized_ fields (which aren't really a user-facing concept). I intend to fix this alongside other styling bugs like recursive show rule crashes.

**Comment by SeSodesa** [comment]
Possibly related, trying to set `supplement` via just a normal `set` rule does not work as expected. The code
```typst
set figure(
  numbering : it => text(weight:"bold", fill:purple)[#it],
  supplement : it => text(weight:"bold", fill:purple)[#it],
)
```
is supposed to set `figure` supplements and numbers to have the same weight and color. The `numbering` setting works as expected, but the `supplement` setting ends up replacing the supplement with the *figure itself*. I would expect that `it` in this context refers to the `supplement` and not to the `figure`.

**Comment by laxsjo** [comment]
@SeSodesa Pretty sure that example is working as intended. You're just overiding the values of the `numbering` and `supplement` fields with the functions you wrote. It just happens that both those fields can take functions.

`numbering` happens to take an argument that is usefull,
but functions in `supplement` take the figure body element as an argument (I assume to be able to adjust the `supplement` based on the figure content)
Here is the documentaiton for `numbering`: https://typst.app/docs/reference/model/figure/#parameters-supplement

I agree that it would be very usefull for there to be some mechanic to "set" a field by updating whatever value was set previously.

**Comment by Dherse** [comment]
@laurmaedje Do we consider this:
- a bug of the content rework
- a missing feature from styling and the `#[elem]` macro?

**Comment by laurmaedje** [comment]
The bug is longer-standing than the content rework. It falls directly under styling rework and is, in fact, what I am working on right now, as we speak.
