### ISSUE TITLE
Options for CJK punctuation schemes

### ISSUE THREAD

**Issue by Verplitic** [typst/typst#2460]
> > There are still problems in the workaround, like two consecutive `【` can cause misalignment.
> 
> * [feat: support adjust more cjk punctuations #2456](https://github.com/typst/typst/pull/2456) will fix this in quanjiao scheme (which is the default in Typst).
> * In banjiao/kaiming scheme we just make some punctuation marks to be fixed width, and do not need any extra adjustment for consecutive bracket—they are fixed 1/2 em anyway.
> * Nobody used CCT style. (I can find [only two](https://github.com/search?q=language%3ATeX+%2Fpunct%5Cs*%3D%5Cs*CCT%2F&type=code) projects in GitHub).

Could there be a setting item to switch between schemes then? Like `#set text(cjkpunct: "kaiming")` or so.

_Originally posted by @Verplitic in https://github.com/typst/typst/issues/2439#issuecomment-1773773265_

**Comment by peng1999** [comment]
Try this:

```
#show regex("[、，。！？）；：》】」]"): punct => [\u{2060}#box(width: 0.5em, punct)]
#show regex("[《【「]"): punct => [#box(width: 0.5em, punct)\u{2060}]
```
<img width="767" alt="image" src="https://github.com/typst/typst/assets/12483662/a797d52b-0d9c-4c17-ad5f-adbc1b028211">

**Comment by Verplitic** [comment]
> Try this:
> 
> ```
> #show regex("[、，。！？）；：》】」]"): punct => [\u{2060}#box(width: 0.5em, punct)]
> #show regex("[《【「]"): punct => [#box(width: 0.5em, punct)\u{2060}]
> ```
> 
> <img alt="image" width="767" src="https://user-images.githubusercontent.com/12483662/277115421-a797d52b-0d9c-4c17-ad5f-adbc1b028211.png">

And just exclude `。` from the first show rule for Kaiming style?

**Comment by Verplitic** [comment]
Hard to tweak `！` and `？` in current version, but I think it can work with after update from https://github.com/typst/typst/pull/2456.

Closing this now, thank you for the solution!
