### ISSUE TITLE
SVG not rendering at all

### ISSUE THREAD

**Issue by Heinenen** [typst/typst#2467]
### Description

The attached SVG fails to render with the error `failed to parse SVG (unknown token at 4:1652)`.
It was created using draw.io / diagrams.net.
Firefox and GitHub render it correctly.
![broken](https://github.com/typst/typst/assets/37484430/bf394579-bb96-425f-be73-358e191dbd65)

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
We found out that it's not the SVG that is broken, but rather how the webapp overwrites files. There already is an issue for that: https://github.com/typst/webapp-issues/issues/137
