### ISSUE TITLE
Format of bibliography inserts comma or period at wrong position

### ISSUE THREAD

**Issue by Heinenen** [typst/typst#2468]
### Description

When using the following code 
```typst
// main.typ
@one
@two
#bibliography("references.bib")
```

with 
```bib
// references.bib
@software{one,
  author = {{Typst Team}},
  title = {{Typst}},
  url = {https://github.com/typst/typst},
  year = {2023}
}

@software{two,
  author = {{Typst Team}},
  title = {{Typst}},
  url = {https://github.com/typst/typst},
}
```
as the reference file, the following it produced:
![image](https://github.com/typst/typst/assets/37484430/fd6ac8d2-182c-46ac-9115-363199cafe78)

I think the `,` (first entry) and the `.` (second entry) should be outside the quotation marks.

### Operating system

Web app

### Typst version

- [x] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
It is common in English style to move commas into quotes even if they aren't part of the quote itself. So it's a feature, not a bug. But the implementation will all change anyway with the upcoming CSL update.
