### ISSUE TITLE
Read environment variables

### ISSUE THREAD

**Issue by Caellian** [typst/typst#2476]
### Description

I suggest adding a function that allows reading values from environment variables. This might expose web app environment though, but so does `read` already(?)

It would make it much quicker and simpler to compile multiple documents using the same script. This can be currently done by writing a build script that updates external file and then runs typst but this isn't ideal - in some cases file IO might not be a good, cost effective or even possible solution to this.

```typst
readEnv("variable", default: "Default string"): string
```

### Use Cases

I want to build document with multiple locales and have a variable that indicates which data file should be loaded for which language. I also have a features-like variable that builds select parts of the document. For context it's a CV script and features select which projects to include in it (incl. all is too much; based on position different ones might be appropriate)

Another one (not my use case, but a better example): Business card factory, where profits depend on number of cards that can be printed per second. File IO adds unnecessary performance bottleneck for switching out user details and causes additional hardware wear which translates to worse profit margins [making latex a better choice](https://tex.stackexchange.com/questions/62010/can-i-access-system-environment-variables-from-latex-for-instance-home).

**Comment by Dherse** [comment]
> Another one (not my use case, but a better example): Business card factory, where profits depend on number of cards that can be printed per second. File IO adds unnecessary performance bottleneck for switching out user details and causes additional hardware wear which translates to worse profit margins [making latex a better choice](https://tex.stackexchange.com/questions/62010/can-i-access-system-environment-variables-from-latex-for-instance-home).

While I agree in principle, I think we should have an interface that goes through the CLI arguments rather than through environment variables. I find that env variables can already leak more than I am comfortable with and I like that, so far, typst is pretty much a sandbox within the CWD.

**Comment by laurmaedje** [comment]
For reference, here is the issue for CLI arguments: https://github.com/typst/typst/issues/295

I agree with @Dherse that this would harm Typst's sandboxing. With CLI arguments, this could also easily be achieved by interpolating the environment variable into an argument using your shell.

**Comment by Enter-tainer** [comment]
(Not a contribution) The business card factory example doesn't sound better to me or I didn't really get it. In this case the bottleneck should be the printer but not typst or latex itself.

**Comment by Dherse** [comment]
> (Not a contribution) The business card factory example doesn't sound better to me or I didn't really get it. In this case the bottleneck should be the printer but not typst or latex itself.

Maybe if you have like crazy large scale printers and very slow and old hardware using old decrepit spinning rust?

**Comment by Caellian** [comment]
> Maybe if you have like crazy large scale printers and very slow and old hardware using old decrepit spinning rust?

That's usually the case as far as I can tell. Software is cheap to upgrade, hardware isn't. And I imagined them using HDDs instead of SSDs.

> While I agree in principle, I think we should have an interface that goes through the CLI arguments rather than through environment variables.

Closing in favor of this.
