### ISSUE TITLE
Nested locate bug with assert

### ISSUE THREAD

**Issue by Dragoncraft89** [typst/typst#248]
Commit: a253b47e

This code works and produces a "2":
```
#let c = counter("foo")

#let foo() = {
  locate(loc => {
    let x = c.at(loc).at(0)
    // assert(x > 1)
    str(x)
  })
}

#let baz() = {
  locate(loc => {
    foo()
  })
}

c.update(2)
#baz()
c.update(1)
```

If you uncomment the assert in line 6, typst produces the following error:
```
error: assertion failed
  ┌─ bug.typ:6:10
  │
6 │     assert(x > 1)
  │           ^^^^^^^
```

Adding an assert seems to change the location where the inner locate is called to after `c.update(1)`

**Comment by Dragoncraft89** [comment]
Weirdly enough, replacing the `assert(x > 1)` with something trivial like `assert(x >= x)` still produces 2 as content.

This does not make sense to me. Is the variable a reference to the counter value? It seems like the assert is evaluated not inside the locate call but somwhere else and at that point `x` evaluates to `1`, even though in the line below it evaluates to`2`

This can be  demonstrated by:
` assert(x > 1, message: str(x))`

```
error: assertion failed: 1
  ┌─ bug.typ:6:10
  │
6 │     assert(x > 1, message: str(x))
  │           ^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Dragoncraft89** [comment]
States variables seem to be lazily evaluated:
```
#let x = 0
#let y = x
#(x = 1)

#y
```
produces 0, whereas:
```
#let x = state("x", 0)
#let y = x.display()
#(x.update(1))

#y
```
produces 1

**Comment by laurmaedje** [comment]
State variables are resolved over multiple layout passes. Adding an assert that fails after the first pass can produce different results because then no further passes will happen.

**Comment by Dragoncraft89** [comment]
I don't understand why this works then (the outer location is passed to the inner function):
```
#let c = counter("foo")

#let foo(b) = {
  locate(loc => {
    let x = c.at(b).at(0)
    assert(x > 1)
  })
}

#let baz() = {
  locate(loc => { foo(loc) })
}

#c.update(2)
#baz()
#c.update(1)
```

it just seems like the inner locate is inserted at the end of the document,  which was unexpected for me.

And is this a bug, or intended?

**Comment by laurmaedje** [comment]
Because the outer location is resolved after the first pass whereas the inner one is still unknown after the first pass (Because it is only generated once the outer one is known.)

**Comment by laurmaedje** [comment]
Delayed errors (catches errors in non-final layout passes) have been implemented a while ago, so this should be fixed.
