### ISSUE TITLE
Counter reset between usages in containers

### ISSUE THREAD

**Issue by tingerrr** [typst/typst#2480]
### Description

While helping with a document on the discord server, I stumbled upon a curious bug:
```typst
#let q = counter("question")
#let step-show = {
    q.step()
    q.display("1")
}

#grid(step-show, step-show)

#pagebreak()
#step-show

#q.update(10)
#grid(step-show, step-show)
```
Will result in the following pages:

Page one:
![image](https://github.com/typst/typst/assets/137803093/4a371670-1b55-4695-837a-08f856b51f04)

Page two:
![image](https://github.com/typst/typst/assets/137803093/ef7b76a0-8429-48d8-8281-79a50e0a4ce6)

Removing the pagebreak, or moving the outer `step-show` before it solves the issue.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by JamesxX** [comment]
Behaviour is even more weird when adding extra `#show-step` calls after the second grid

```typst
#let q = counter("question")
#let step-show = {
    q.step()
    q.display("1")
}

#grid(step-show, step-show)

#pagebreak()
#step-show

#q.update(10)
#grid(step-show, step-show)

// None:
//

// One:
#step-show 

// two: 
#step-show 
```

none:
![image](https://github.com/typst/typst/assets/6299280/f6c090f5-cc1d-4da1-825e-8f890be5cba8)


one: 
![image](https://github.com/typst/typst/assets/6299280/02378dda-0c19-44ae-89bb-a14a7172eea9)

two:
![image](https://github.com/typst/typst/assets/6299280/dfc9c63d-fd96-4698-a8ba-ea8f692a3468)

**Comment by emilyyyylime** [comment]
lol what

**Comment by MichaelFraiman** [comment]
Has there been any progress in resolving this issue? The following similar code exercises a similar sort of behaviour.


```
#let c = counter("c")
#let foo() = locate(
    loc => {
      c.step()
      c.display("1")
      str(c.at(loc).first())
    }
  )

#{
foo()
block(
  foo()
)
foo()
foo()
block(
  foo()
)
block(
  foo()
)
foo()  
}
```

**Comment by laurmaedje** [comment]
I have identified the problem some time ago, but the solution isn't yet implemented (and there also a few problems to be solved). We need to implement a new mechanism for assigning locations to elements. More details here: https://laurmaedje.github.io/posts/frozen-state/
