### ISSUE TITLE
Counter substitution in outline

### ISSUE THREAD

**Issue by mattfbacon** [typst/typst#2483]
Compare

```typst
#outline()

#let mycounter = counter("mycounter")

#mycounter.step()
= #mycounter.display("I")

#mycounter.step()
= #mycounter.display("I")
```

to

```typst
#outline()

#let mycounter = counter("mycounter")

#mycounter.step()
#mycounter.display(i => [= #numbering("I", i)])

#mycounter.step()
#mycounter.display(i => [= #numbering("I", i)])
```

The headings themselves look the same either way, but in the first one, the `outline` shows "N" instead of the correct number.

**Comment by laurmaedje** [comment]
While it's a slightly different setup, this is functionally the same problem as https://github.com/typst/typst/issues/1057.

**Comment by mattfbacon** [comment]
Really? Isn't the numbering wrong in that issue? Here the numbering appears correctly as long as I get the value of the counter outside of the header.
