### ISSUE TITLE
Feature: Scroll to top

### ISSUE THREAD

**Issue by bilalmirza74** [typst/typst#2484]
### Description

After reaching the footer, instead of scrolling back up by rotating the mouse wheel or swiping on mobile, we can simply click on the scroll-to-top button.

### Use Case

Adding Scroll to Top Button will improve UX/UI

![image](https://github.com/typst/typst/assets/84387676/9e3a7100-e2ce-49e5-94a6-158650bd4e52)

**Comment by Dherse** [comment]
This is a web interface request and therefore should be ok the correct repository. @bilalmirza74 you simply cannot be assigned to this issue as the web app is closed source.

**Comment by Dherse** [comment]
@bilalmirza74 for web app issues, you must report them [here](https://github.com/typst/webapp-issues), and as I said, you cannot contribute to the web app, no one can except the two founders, as it is closed source. If you're interested however, typst has an open web dev position for which you could apply if you were so inclined.
