### ISSUE TITLE
Better error message when trying to compile wrong file type.

### ISSUE THREAD

**Issue by SebastianJL** [typst/typst#2486]
### Description

Current behavior:
```bash
~$ typst compile main.pdf
error: file is not valid utf-8.
```
New behavior:
```
~$ typst compile main.pdf
error: file is not valid utf-8.
help: a file with suffix `.pdf` is usually not a typst file. Maybe you meant `main.typ` instead?
```
`main.pdf` is a stand-in for any file that is not a typst file and has the wrong file extension.

The additional help message would only appear when the file ending is wrong **and** another error in the file happens. There wouldn't be any complaints if a different file extension was used but the file was valid typst source.

### Use Case

Today I tried several times to compile `main.pdf` before I realized that I meant to type `main.typ`. A help message would have nudged me to the correct solution earlier.

**Comment by LaurenzV** [comment]
Sure, just open a PR and it will get reviewed sooner or later!

**Comment by PgBiel** [comment]
Will be working on this :partying_face:
(Commenting so I can be assigned!)
