### ISSUE TITLE
Assets modifications detection for ``typst watch``

### ISSUE THREAD

**Issue by Quentindeve** [typst/typst#2487]
### Description

When doing ``typst watch`` on a typst document that includes images via ``#figure``, typst actually doesn't recompile the document when the included image is modified. 

A simple test to notice this is to create a simple Typst document with a ``#figure(image("...")`` and to ``typst watch`` it. You will notice that when modifying the image file, typst won't recompile the document.

It would be in my opinion a great feature to get typst recompiling the document when one of its included asset is modified.

### Use Case

Watching assets with ``typst watch`` would be, I believe, a good enhancement for the global Typst experience.

**Comment by Quentindeve** [comment]
I'm on Archlinux. Here's the ``typst --version`` output:
```
typst 0.8.0 (360cc9b9)
```
I installed it via pacman repository, and it says my typst is up-to-date.

**Comment by tingerrr** [comment]
I cannot reproduce this on `typst 0.8.0 (360cc9b9)` installed using pacman on `6.5.7-arch1-1`.
When I run `/usr/bin/typst watch main.typ` with a given file and run `touch image.jpg` to update its access time, it recompiles.

**Comment by Quentindeve** [comment]
Well, I maybe made an mistake when I assumed ``typst watch`` was the problem, I encounter this problem with the Typst extension for Visual Studio Code. I did a small recording of what happens and uploaded it [here](https://www.youtube.com/watch?v=epr26EvJeJ4). Note that when the image change it's because I force-saved the .typ file.

**Comment by laurmaedje** [comment]
The Typst LSP extension isn't official. You can report bugs about it here: https://github.com/nvarner/typst-lsp

**Comment by Quentindeve** [comment]
Sorry to have made you losing your time, will be more careful next time.

**Comment by laurmaedje** [comment]
No worries.
