### ISSUE TITLE
Custom OpenType features

### ISSUE THREAD

**Issue by balthild** [typst/typst#2489]
### Description

In LuaTeX, users can define custom OpenType features with the `luaotfload` package, and load it into a font with `fontspec`.

```tex
\documentclass{article}
\usepackage{fontspec}
\directlua{
    fonts.handlers.otf.addfeature {
        name = "oneb",
        type = "substitution",
        data = {
            ["1"] = "one.ss01",
        }
    }
}
\setmainfont{Vollkorn-Regular.otf}[RawFeature=+oneb]
\begin{document}
1234567890
\end{document}
```

There are two ways to do this:

1. Loading `.fea` files
2. Defining features with the language's data structures (array/dictionary)

An example of `.fea` file:

```fea
@downpuncts = [
    comma
    period
];
@uppuncts = [
    grave
    quotesingle
    quotedbl
]
feature kern {
    pos L T <200 0 0 0>; 
    pos @downpuncts @uppuncts <100 0 0 0>;
} kern;
```

`luaotfload` supports the second way. It used to support the first way, but dropped it in 2016 (v2.8). It seems that `luaotfload` does not support `glyph class` anymore after it switched to the second way. This may indicate that the first way is more flexible.

### Use Case

This allows users to customize the font features without modifying the font file.

**Comment by Enter-tainer** [comment]
possibly related: https://typst.app/docs/reference/text/text/#parameters-features

i guess using this and some show rule, you can achieve similar net effect

**Comment by balthild** [comment]
One case is to customize the kerning, as the example above shows.

Another case is to selectively enable the font ligatures (GSUB). For example, if I want to enable most of the ligatures when using `Cascadia Code` except for `(*` and `*)`, because I'm showing Typst code and these ligatures would cause confusion given that they has no special semantics in Typst's syntax (**It just produce strong texts inside parenthesis like this**).

**Comment by Myriad-Dreamin** [comment]
@balthild, I'm not an expert of ttf fonts, but could you check https://github.com/typst/typst/blob/main/tests/typ/text/features.typ for parameters related to font features? They are advanced feature over text elements and (possibly) lack of document.

For example, you could enable/disable ligatures in scope of this set rule:

![image](https://github.com/typst/typst/assets/35292584/3e91dae5-cece-4ec6-b32a-947ab5053fa2)

**Comment by balthild** [comment]
@Myriad-Dreamin I think the codes inside the link are using the fonts' predefined features, but what this issue proposing is to define my own feature.

And yes, for the case that disable specific ligatures, it can be achieved with `show "(*": set text(...)`. I need to think about some other use cases... (The primary reason that I request this feature is to customize kerning. Though it might achieve with show+set rules too, it is not perfect and seems hacky.)

**Comment by gfpj** [comment]
Adjusting the kerning should work with rustybuzz which is used by Typst. So, I assume adding an API that gets a kerning and sends it to rustybuzz should solve it for kerning. Other font features would also require an own api but should also work like Ligatures. I think harfbuzz/rustybuzz has limited support for ligatures only, though.

**Comment by laurmaedje** [comment]
I think customizable kerning is a fair enough request, but arbitrary OpenType features like in the snippet above are out of scope.

**Comment by laurmaedje** [comment]
I've opened https://github.com/typst/typst/issues/2692 for the kerning pairs.
