### ISSUE TITLE
Improve math alignment documentation

### ISSUE THREAD

**Issue by Enivex** [typst/typst#2496]
The alignment of equations is described here https://typst.app/docs/reference/math/ as "Formulas can also contain line breaks. Each line can contain one or multiple alignment points (&) which are then aligned."

Unless the user already knows how alignment works in LaTeX, this will be very mysterious, which is why the topic has come up on Discord many times.

The documentation should be updated to explain how alignment works when multiple &s are present in each line. What happens if there are differing number of &s in each line?

(Short summary: Think of an equation as a table, where & takes you to the next column in the table. The twist is that this table has alternating right and left alignment)

**Comment by laurmaedje** [comment]
Go ahead!

**Comment by MyrtleTurtle22** [comment]
Sorry if this should be obvious, but how can I preview the .yml files?

**Comment by laurmaedje** [comment]
Unfortunately, the rendering to HTML is a bit interweaved with our website's static site generation and therefore not currently open source. You'd have to write the content 'blind' so to speak and I would then check if there are any visual flaws before merging.

**Comment by MyrtleTurtle22** [comment]
Ok I'll do my best, the bigger challenge is making sure the typst code is compiling the way I want it to since I don't have experience with it.

**Comment by kovaxis** [comment]
I had no idea how alignment worked and I didn't even know I didn't know. Reading this issue clarified it 100%. Nice to see the documentation improving!

**Comment by MyrtleTurtle22** [comment]
Thanks, I appreciate it.  Also, I'd love to contribute more so if there are any more issues that would be on the simpler side and help me get to know the codebase more let me know and I'll definitely give it a look!
