### ISSUE TITLE
Long tables in figures that should overflow onto the next page don't overflow

### ISSUE THREAD

**Issue by dyc3** [typst/typst#2497]
### Description

If you have a table longer than the height of your page, it will overflow the remaining rows onto the next page. However, if you place that table in a `figure`, then it will not overflow, and it'll just place all the remaining cells overlapping at the bottom of the table.

# Reproduction

```typst
= Here is a long table

#figure(
  table(
    columns: 2,
    ..([#lorem(5)], [#lorem(8)]) * 200
  )
)
```

### Reproduction URL

https://typst.app/project/ptxQmUUyMdH27t78RMrCOJ

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by dyc3** [comment]
Ah, that works. Thanks.

**Comment by mikkelens** [comment]
For those stumbling onto this later - you might also have to remove `placement: auto` from your figure arguments. That was what I needed to do. Now the `#show figure: set block(breakable: true)` works for me as well.
