### ISSUE TITLE
Vim mode in the editor

### ISSUE THREAD

**Issue by eleijonmarck** [typst/typst#250]
Hey great product, ideally i would love to have support to writing these documents either in my IDE or text editor with vim. Is there a way to get a vim mode in the web app?

**Comment by adamijak** [comment]
You can use vim and prebuilt binary.

**Comment by jowch** [comment]
While that is true, we would need to give up the collaboration features that are so good in the web app!

**Comment by eleijonmarck** [comment]
how come? i understand it might be hard for each user to get their preferred setup. but i do not think it is desired. I would want the editor to either act in "normal" mode or "vim" mode for users

that would be sufficient for me

**Comment by jowch** [comment]
Yes, I agree. What I mean is that it would be nice to be able to toggle vim mode on the web app like how many apps built with CodeMirror are able to (e.g. Jupyter Lab; see [demo](https://codemirror.net/5/demo/vim.html)). I can very much use a local copy of Typst with my favorite editor, but I wouldn't be able to use the collaboration benefits of the web app.

**Comment by adamijak** [comment]
I am aware of that vscode and IntelliJ editors have some kind of collaboration extensions, which works very well.
I just want to say that embedding/rewriting vim in online editor is not easy task, and I understand maintainers if it's not their top priority.

**Comment by reknih** [comment]
A vim mode is now available. You can click the cogwheel icon in the sidebar and check the checkbox or enable it in the edit menu. Please open new issues if you are missing any commands!
