### ISSUE TITLE
Support for binding correction with fractional margins

### ISSUE THREAD

**Issue by freundTech** [typst/typst#2500]
### Description

In professional typesetting margins are often not defined as a fixed size, but as a fraction of the page.

When setting a two-sized layout one first has to subtract the binding correction from the page, then split the page into equal parts. See this image from the LaTeX KOMA-Script documentation
![Screenshot 2023-10-26 at 23-51-54 KOMA-Script - scrguide-en pdf](https://github.com/typst/typst/assets/9515067/54c29d72-b1f0-49c3-911d-1406b3bbcb73)

Typst does support binding corrections using `inside` and `outside` margins. Typst also supports fractional margins using fractional lengths (using `%`). However it's not possible to properly combine them, as fractional values will always be a fraction of the page size. Not of the page size minus the binding correction.

My suggestion would be seperating margins and binding correction instead of using the `margin` argument for both.

The above example could be implemented as follows:

```typst
#set page(
  paper: "a4",
  binding-correction: 20mm,
  margin: (
    "inside": 100% / 9,
    "outside": 100% / 9 * 2,
  ]
)
```

Where the `100%` in the margin isn't 210mm (the width of a DIN A4 paper, but 190mm (the width minus the binding correction).

### Use Case

Setting proper margins

**Comment by Enivex** [comment]
I don't quite see why this needs to be a separate option. It can easily be achieved by just subtracting the binding correction from the 100%

```
#set page(
  paper: "a4",
  margin: (
    "inside": (100% - 20mm) / 9,
    "outside": (100% - 20mm)/ 9 * 2
  )
)
```
