### ISSUE TITLE
TextMate grammar is pretty broken

### ISSUE THREAD

**Issue by beeb** [typst/typst#251]
Relevant file: https://github.com/typst/typst/blob/main/tools/support/typst.tmLanguage.json
It seems the syntax highlighting is not happy with the following shorthand syntax:

```
#show "Some String": box
```

```
#show "Some String": it => box[#it]
```

The `box` should be blue in both cases.

![image](https://user-images.githubusercontent.com/703631/227499471-783e19c8-5d2c-4e3a-a9d9-c7de7e6ffbf7.png)

**Comment by laurmaedje** [comment]
The tmLanguage was always only an approximation of the syntax highlighting provided by the syntax tree. I only really built it to have good-enough VS Code highlighting for the tests.

**Comment by laurmaedje** [comment]
There should probably be a disclaimer because the whole VS Code extension is not really "supported", it was just made to be good enough for our test use case.

**Comment by beeb** [comment]
Is there a will to maintain it here? Otherwise extensions like https://github.com/nvarner/typst-lsp should maintain their own.
Just want to know so we can react appropriately. Thanks

**Comment by laurmaedje** [comment]
I am leaning towards removing the VS Code extension from this repo and using typst-lsp myself too for local testing.

**Comment by laurmaedje** [comment]
This is wont-fix for now. The TextMate grammar was only intended for development.
