### ISSUE TITLE
Smartquote for Japanese

### ISSUE THREAD

**Issue by TomVer99** [typst/typst#2513]
### Description

I'd like to be able to use the smartquote for the Japanese language.
```typ
#set text(lang: "ja")
"日本語のテキストです"
```
To
```
「日本語のテキストです」
```

### Use Case

Automatically have quotation marks for the Japanese language.

**Comment by Enter-tainer** [comment]
i don't think this is a common practice in cjk typesetting, at least not in Chinese.

A good news is that i guess you may implement this feature using show rule and regex without changing typst itself.

**Comment by laurmaedje** [comment]
Customization for smart quotes is already implemented on main and will be in the next release.

**Comment by TomVer99** [comment]
I guess this issue could just be closed then?

**Comment by TomVer99** [comment]
> i don't think this[1] is a common practice in cjk typesetting, at least not in Chinese.
> 
> A good news is that i guess you may implement this feature using show rule and regex without changing typst itself.
> 
> [1]: by "this" i mean typing " in source code and rely on typesetting engine to transform it into 「

Also I just thought of non native users with an English (or other) keyboard. Some people use the "A = あ" key order layout, and those keyboards use " instead of 「 from what I know. So for those users it could be nice.
