### ISSUE TITLE
Adding the ability to query the color of the document at a certain position

### ISSUE THREAD

**Issue by giacomogallina** [typst/typst#2520]
### Description

Would it be easy and/or reasonable to add a function that queries the color of a certain point of the document? Or, instead, to get the current "background" color?

### Use Case

I'd like to write some text on top of an arrow for my commutative diagrams library, giving priority to the text in the case they intersect. Right now I'm drawing the arrow, drawing a white rectangle, and drawing the text, so that the white rectangle covers any bit of the arrow that would intersect with the text, and creating a nice background for the text. Unfortunately, if all of this is inside a rect with a fill color != white, this hack doesn't really work. A possible solution would be getting the background color, and covering the arrow with a rectangle of the correct color.

**Comment by laurmaedje** [comment]
If I understand you correctly, this is covered by https://github.com/typst/typst/issues/763

**Comment by giacomogallina** [comment]
Yeah, that would be a nice solution I think. I guess I'll wait for that then, and thank you for the fast reply!
