### ISSUE TITLE
v0.9.0 is non idempotent

### ISSUE THREAD

**Issue by cmoog** [typst/typst#2536]
### Description

In prior versions of the compiler, repeated compilations produced byte-for-byte identical results. With v0.9.0, there seems to be some behavior that causes binary diffs in compiler output for identical inputs across multiple runs. In particular, I'm seeing diffs in the autogenerated IDs contained at the root of the document.

Setting `document(date: none)` does not resolve the issue.

### Reproduction URL

The following document produces different compiler output on repeated runs. (typst v0.9.0, macOS)

```typst
#set document(author: "", title: "", date: none)
= test
```

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This is intended behaviour as IDs are expected by many PDF viewers. Writing the creation date is also good practice. As you've noticed, setting the `date` to `none` reverts back to the previous behaviour.

**Comment by cmoog** [comment]
@laurmaedje But shouldn't the generated ID be the same across repeated runs?

Byte-for-byte reproducibility makes tracking pdfs alongside source files in git much easier.

**Comment by laurmaedje** [comment]
The generated ID should be the same if the date is disabled. It consists of a hash of the file path and a hash of the document content. Are you running clean `typst compile` every time?

**Comment by laurmaedje** [comment]
The ID consists of two parts: A stable document ID (file path hash) and an instance ID (document hash) that changes through modifications. Can you confirm which of these two changes by opening the PDF in a text editor and searching for the `/ID` field (it's close to the end of the file)?

**Comment by cmoog** [comment]
Searching for the `/ID` field at the end of the document reveals that the _second_ part of the ID is what is changing between repeated clean runs of `typst compile`

**Comment by laurmaedje** [comment]
Ok, I have an idea what's going on. The document hash is probably not stable across program invocations because of ASLR (address space layout randomization) or something similar. We're sometimes hashing pointers instead of data for better performance. I think a good fix would be to not hash the document struct itself, but hash the generated PDF content itself (as far it is generated when we write the ID). That should be stable and also more performant anyway.
