### ISSUE TITLE
Release notes nitpicks (version 0.9.0)

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2537]
I don't know if this is allowed, but I leave my corrections here anyway.

> - Math
>   - Added support for specifying negative indices for augmentation lines to position the line from the back
>   - Fixed default color of matrix augmentation] lines

- I think it would be nicer if altered functions were mentioned (I'm guessing `mat` and something else?).
- "]" should be removed.

> - Tooling and Diagnostics
>   - Added tooltip that show which variables a function captures (when hovering over the equals sign or arrow of the function)
>   - Fixed a bug where function argument parsing errors where shadowed by function execution errors (e.g. when trying to call array.sorted and passing the key function as a positional argument instead of a named one).

- ... that "shows" ...
- ... errors "were" shadowed ...

> - Export
>   - Added support for configuring the document's creation `date`. If the `date` is set to `auto` (the default), the PDF's creation date will be set to the current date and time.
>   - Added support for configuring document `keywords`

- Again, would be nice if it did mention [`document`](https://typst.app/docs/reference/meta/document/#parameters-date) function.

<details><summary>P.S.</summary>

If the notes were made in a GUI browser (or a markdown file in Neovim/VS Code), then there is a LanguageTool extension/LSP server that could've eliminated some of the mistakes:
![image](https://github.com/typst/typst/assets/37143421/82cefe11-d62b-414a-9c99-c2235e303c94)

</details>

**Comment by laurmaedje** [comment]
In the [primary changelog on typst.app](https://typst.app/docs/changelog/), the relevant parts with matrix and the document function are linked, which I think suffices. Having links in the GitHub changelog would be nice, but it's too much effort until somebody sits down to automate the link generation like it's done for the typst.app version / docs in general.

**Comment by Andrew15-5** [comment]
Great. But do you use LanguageTool? is the real question here. /s As I said above, with it a lot of mistakes could've been avoided.
