### ISSUE TITLE
Period `.` should be a default separator for `lang: "ru"` (`figure.caption`)

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2539]
### Description

https://github.com/typst/typst/releases/tag/v0.9.0:

> The default figure separator now reacts to the currently set language and region

After reading this, I would hope that I will finally see a `.` instead of `:`, but <strike>my disappointment was immeasurable, and my day is ruined</strike> it is still a colon `:`.

```typ
#set text(lang: "ru")
#figure([My figure], caption: [Title])
```

![image](https://github.com/typst/typst/assets/37143421/8c7ed665-bc8c-4229-abac-b8991d153772)

Sidenote. I'm not a professional in the standards and things like that, but I'm pretty confident that I'm right, because I never ever saw a Russian figure that had a colon instead of a period. **If** I'm wrong, then we will see an opposite issue being opened in the future, which is highly unlikely. If that happens, then I can discuss this matter with that OP.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by xkevio** [comment]
Would probably be good if you could provide a few examples of papers/academic works doing that cause my quick search showed me that the colon is definitely used, but that "Figure" is often abbreviated (Рис.).

**Comment by Andrew15-5** [comment]
From non-local (from the Internet) sources, I found these:
- https://lawacademy.ru/science/library/events/vsf.pdf
- https://ufn.ru/ufn16/ufn16_10/Russian/r1610d.pdf

I mean, I can keep on searching, but 2 examples prove that at least I'm not wrong. I found some other examples, but in them no separator is used at all. So they either use `. ` or ` `, but not `: `.

I'm interested to see examples where the colon is used.

**Comment by Andrew15-5** [comment]
> is often abbreviated (Рис.).

Indeed, but nevertheless, a full form is also valid. It would be strange to restrict authors from using the full form and only accept the short one.

**Comment by xkevio** [comment]
That does seem good enough, tbf I only had one counter example as I didn't know how to quickly find Russian research papers so I just found random lecture notes from the St. Petersburg University (https://dspace.spbu.ru/bitstream/11701/41567/1/lectures.pdf) but as you said and as others in the Discord have pointed out, `.` does appear more often.

**Comment by Andrew15-5** [comment]
You know why it uses colon? This is why:
![image](https://github.com/typst/typst/assets/37143421/ea771621-7901-4b83-aaae-f8c2565a117b)

Not everyone knows/bothers/can change the default international/English colon to the Russian period. That's our problem. For some reason, "we" just **had to** create our own standards (for everything).

**Comment by Andrew15-5** [comment]
> tbf [...] I didn't know how to quickly find Russian research papers

tbf, me too. No one ever told me, and I don't really wanna know anyway.
