### ISSUE TITLE
Example for `quote` `attribution` argument does not work

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#2541]
### Description

Specifically, this part of the example:
```typ
#show quote.where(block: false): it => [
  "#it.body"
  #if it.attribution != none [(#it.attribution)]
]
#quote(attribution: link("https://typst.app/home")[typst.com])[
  Compose papers faster
]
```

The show rule is never applied in the first place:
```typ
#show quote.where(block: false): it => [Modified quote]
#quote[Original quote]
```
renders as
![“Original quote”](https://github.com/typst/typst/assets/57839069/c6ca399f-614c-437e-9404-9a6a0b82fb4c)

Removing `.where(block: false)` works properly:
```typ
#show quote: it => [Modified quote]
#quote[Original quote]
```
![Modified quote](https://github.com/typst/typst/assets/57839069/34636ec1-4ba3-4ff1-8e61-657fbea973ed)

May relate to #2530

### Reproduction URL

https://typst.app/docs/reference/text/quote/#parameters-attribution

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
See here: https://github.com/typst/typst/pull/2532
