### ISSUE TITLE
Bibliography style bug: GB/T 7714-2015 (China Nation Standard)

### ISSUE THREAD

**Issue by FinleyGe** [typst/typst#2548]
### Description

As GB/T 7714-2015, There should be a "type code" for each bibliography.

For example, I have to cite this:
```yaml
test:
  type: book
  title: 测试样例
  author: 作者
  language: zh-Hans
  edition: 1
  date: 2021
```
`.bib` file has the same problem:

```bib
@book{test,
  author = {测试作者},
  title = {测试书籍},
  year = {2021},
  publisher = {测试出版社},
  edition = {1},
}
```

The right bibliography style should be like:
```text
测试作者. 测试书籍[M]. 第 1 版. 测试出版社, 2021.
```

but in fact, the compiled result is like:
![image](https://github.com/typst/typst/assets/32237950/1f8094a6-33c1-4d2f-a3b2-da5866231d8f)
There are 2 problems:
1. There is not a type code, which should be [M]
2. The edition should be in Chinese.

I think it could be caused by a wrong `.csl` file, but I get a `.csl` from 
https://github.com/citation-style-language/styles/blob/master/chinese-gb7714-1987-numeric.csl

This file should be ok. but the problem still exists in Typst.
So maybe Typst has some compatibility problem with 'CSL' ?
This bug could be caused by `hayagriva` ? I have no idea.

And this is my env:
Arch Linux 6.5.9-zen2-1-zen
typst 0.9.0 (7bb4f6df)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by FinleyGe** [comment]
One more thing,
When I type in a URL, the type code is right now: (As It has a URL, so it has become an Internet resource book, [M/OL] is a right code)

![image](https://github.com/typst/typst/assets/32237950/63b5a46f-cc0a-49ab-af03-089fb1e08f4c)

after i change the type into a report in `yaml`

```yaml
test:
    type: report
```

The type code is also right:
![image](https://github.com/typst/typst/assets/32237950/db42f934-acd4-4b10-9fe1-fc785b6d0b3e)

(But the edition style is still wrong)

**Comment by Enivex** [comment]
This should possibly be in the Hayagriva repo

**Comment by xvin-zr** [comment]
When I set the `style` attribute of the bibliography to `"gb-7114-2015-numeric"`
```
bibliography(
    bibliographyFile, 
    title: none,
    style: "gb-7114-2015-numeric"
)
```
The citations in the PDF appear misplaced. It looks like this.

<img width="580" alt="image" src="https://github.com/typst/typst/assets/88776909/c5a2d66d-42bd-4456-affe-c88d3784417b">

Besides, the standard string should be `gb-7714-2015` instead of `gb-7114-2015`?

**Comment by laurmaedje** [comment]
@Dherse The hayagriva commit just changes the name. But there are more issues here unfortunately.

**Comment by Dherse** [comment]
> @Dherse The hayagriva commit just changes the name. But there are more issues here unfortunately.

I, my bad, sorry :|

**Comment by zepinglee** [comment]
> When I set the `style` attribute of the bibliography to `"gb-7114-2015-numeric"`
> 
> ```
> bibliography(
>     bibliographyFile, 
>     title: none,
>     style: "gb-7114-2015-numeric"
> )
> ```
> 
> The citations in the PDF appear misplaced. It looks like this.
> 
> <img alt="image" width="580" src="https://user-images.githubusercontent.com/88776909/279996431-c5a2d66d-42bd-4456-affe-c88d3784417b.png">
> Besides, the standard string should be `gb-7714-2015` instead of `gb-7114-2015`?

I can't reproduce it and please provide a minimal reproducible example. Additionally, the described bug is not related to the original post and perhaps it's better to open another issue.
