### ISSUE TITLE
Typst does not respect unicode RIGHT-TO-LEFT OVERRIDE

### ISSUE THREAD

**Issue by lcnbr** [typst/typst#2550]
### Description

In this example there is a rtl override before the double colon eq, to flip it.
https://typst.app/project/raOed3Kp_pPZpLGL7UcpW_

However the rendered file does not respect this

### Typst version

- [X] I am using the latest version of Typst

**Comment by MDLC01** [comment]
I don't think rtl override is meant to visually flip the characters. It is only meant to flip the order in which the following characters are displayed.

**Comment by lcnbr** [comment]
⩴ is clearly different from  ‮⩴

**Comment by alerque** [comment]
> ⩴ is clearly different from ‮⩴

No it isn't.

The RTL order marker only affects the shaping of sequential glyhps. You dot have two glyphs there for order to make any difference, you have a single Unicode code point "DOUBLE COLON EQUAL" that is all one single shape.

**Comment by lcnbr** [comment]
Where is the screenshot from? I have two different symbols:

![image](https://github.com/typst/typst/assets/23530896/05943eb8-0829-4d9d-b528-ffd1be975532)

**Comment by alerque** [comment]
Firefox 119 on Linux. Chromium is no different. Nor is it different inspecting the code points in an editor, I looked at the actual Unicode byte sequences before writing my response. My response stands. The real question is what undocumented sorcery is going on on your end?

What font are you using in your browser? It's possible it has done something profoundly goofy.

**Comment by laurmaedje** [comment]
Chrome on macOS looks normal (unmirrored) for me, but I can also see the mirroring in Chrome on Android.

**Comment by alerque** [comment]
Also mirrored in Firefox on Android for me.

Paging @khaledhosny, does this make any sense to you? Is there any shaping rule where a RTL override followed by a math symbol should reflect the symbol? The code points are `U+2023`,`U+2A74`. I can't find any fonts (including Roboto) that do this locally.

```console
$ hb-shape /usr/share/fonts/OTF/Symbola.otf "⩴ | <202e>⩴"
[gid8331=0+2048|gid3=1+512|gid95=2+410|gid3=3+512|gid3=4+0|gid8331=5+2048]

$ hb-view /usr/share/fonts/OTF/Symbola.otf "⩴ | <202e>⩴"
                                            ▕▔▎
                                            ▕ ▏
                                            ▕ ▏
                                            ▕ ▏
                                            ▕ ▏
   ▕▆▔▔▖ ▗▆▔▔▖ ▗▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▖           ▕ ▏           ▗▔▔▆▎ ▗▔▔▆  ▗▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃
    ▃▂▂▘  ▃▂▂▘  ▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆            ▕ ▏           ▝▂▂▃  ▝▂▂▃  ▝▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆
                                            ▕ ▏
    ▅▆▅▖  ▅▆▅▖  ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂            ▕ ▏           ▗▅▆▅  ▗▅▆▅  ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
   ▕▂ ▂▘ ▊▂ ▂▘ ▝▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▘           ▕ ▏           ▝▂ ▂▏ ▝▂ ▂▏ ▝▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅
     ▔     ▔                                ▕ ▏             ▔     ▔
                                            ▕ ▏
                                            ▕ ▏
                                            ▕ ▏
                                            ▕▁▎
```

**Comment by behdad** [comment]
It's some sorcery in `NotoSansMath-Regular.ttf`:

![image](https://github.com/typst/typst/assets/142891/36af994c-80a9-46d1-b821-e87c12103dc0)

**Comment by khaledhosny** [comment]
U+2A74 has Bidi_Mirrored=Yes, so it should be mirrored when its resolved direction is R, but it does not have a mirrored counterpart encoded (no Bidi_Mirroring_Glyph), so it is up to the font to provide a mirrored version and substitute it in `rtlm` feature.

**Comment by behdad** [comment]
> U+2A74 has Bidi_Mirrored=Yes, so it should be mirrored when its resolved direction is R, but it does not have a mirrored counterpart encoded (no Bidi_Mirroring_Glyph), so it is up to the font to provide a mirrored version and substitute it in `rtlm` feature.

Correct. In `BidiMirroring.txt`, there's these comments:
```
# The following characters have no appropriate mirroring character.
# For these characters it is up to the rendering system
#   to provide mirrored glyphs.

# 2A74; DOUBLE COLON EQUAL
```
So, yes, it's a font bug if the font doesn't do it.

**Comment by khaledhosny** [comment]
NotoSansMath has mirrored glyph (though it uses `rtla` feature not `rtlm` which I think is a bug).

**Comment by alerque** [comment]
@lcnbr There is your answer. Use a font that supports this. It works it Typst:

```typst
#set text(
  font: "Noto Sans Math"
)
⩴ | ‮⩴
```

**Comment by laurmaedje** [comment]
I learned something new, too! Thanks everybody for the investigation. I guess this can be closed. 

PS: Note that Noto Sans Math isn't available in the web app by default. But you can upload it into your project.
