### ISSUE TITLE
Author metadata wrong with multiple authors in v0.9.0

### ISSUE THREAD

**Issue by marbar1** [typst/typst#2556]
### Description

The author metadata is not set correctly in Typst version 0.9.0 when defining multiple authors.

The behavior was tested against version 0.8.0 which sets the metadata correctly.

| Authors | Version 0.8.0 | Version 0.9.0 |
|-|--------------|---------------|
| 1 | ![v0 8 0_one_author](https://github.com/typst/typst/assets/54333883/e0e0d0d1-5b8d-446c-8a6b-3c7f8d80d7d3) | ![v0 9 0_one_author](https://github.com/typst/typst/assets/54333883/f0adf5cb-82ff-47fe-9435-084c03b21025) |
| 2 | ![v0 8 0_two_authors](https://github.com/typst/typst/assets/54333883/08a2a50f-09be-4ac5-9858-72b764e36927) | ![v0 9 0_two_authors](https://github.com/typst/typst/assets/54333883/47672b54-b319-484f-9a0b-cee916a867ce) |
| 3 | ![v0 8 0_three_authors](https://github.com/typst/typst/assets/54333883/9a80e27b-e66d-447b-badd-8d1ff29deb01) | ![v0 9 0_three_authors](https://github.com/typst/typst/assets/54333883/2bd96ddf-9823-4bf5-bb5f-176658c75f99) |

Code for testing:
- One author: `#set document(author: "author 1")`
- Two authors: `#set document(author: ("author 1", "author 2"))`
- Three authors: `#set document(author: ("author 1", "author 2", "author 3"))`

It seems as if the first author is set as a string of all authors when there is more than one author.

I also tested it with an array of only one author. This does not change the output compared to passing the string.

`#set document(author: ("author 1"))`

![v0 9 0_one_author_array](https://github.com/typst/typst/assets/54333883/eb44dc3d-24d6-4814-8f2d-c06dd31f106f)

### Typst version

- [X] I am using the latest version of Typst

**Comment by samueltardieu** [comment]
I cannot reproduce this on Linux with typst 0.9.0:

```txt
$ pdfinfo t.pdf
Author:          author 1, author 2, author 3
```

Moreover, both the PDF metadata (`/Author (author 1, author 2, author 3)`) and XMP info (`<dc:creator><rdf:Seq><rdf:li>author 1</rdf:li><rdf:li>author 2</rdf:li><rdf:li>author 3</rdf:li></rdf:Seq></dc:creator>`) look correct.

**Comment by marbar1** [comment]
I used the web app with either version 0.8.0 or 0.9.0 selected.

I haven‘t tested it locally yet.

**Comment by marbar1** [comment]
I compiled the same test file locally on Windows 11 and Adobe Acrobat shows the authors in the same weird way.

I then tried pdfinfo and exiftool and they both showed the authors correctly.

``` bash
$ exiftool -a -G1 test.pdf
[ExifTool]      ExifTool Version Number         : 11.88
[System]        File Name                       : test.pdf
[System]        Directory                       : .
[System]        File Size                       : 10 kB
[System]        File Modification Date/Time     : 2023:11:02 07:58:36+01:00
[System]        File Access Date/Time           : 2023:11:02 07:58:38+01:00
[System]        File Inode Change Date/Time     : 2023:11:02 07:58:37+01:00
[System]        File Permissions                : rwxrwxrwx
[File]          File Type                       : PDF
[File]          File Type Extension             : pdf
[File]          MIME Type                       : application/pdf
[PDF]           PDF Version                     : 1.7
[PDF]           Linearized                      : No
[PDF]           Page Count                      : 1
[PDF]           Language                        : en
[PDF]           Author                          : author 1, author 2
[PDF]           Creator                         : Typst 0.9.0
[PDF]           Create Date                     : 2023:11:02 06:58:36Z
[PDF]           Modify Date                     : 2023:11:02 06:58:36Z
[XMP-x]         XMP Toolkit                     : xmp-writer
[XMP-dc]        Creator                         : author 1, author 2
[XMP-dc]        Format                          : application/pdf
[XMP-dc]        Language                        : en
[XMP-xmp]       Creator Tool                    : Typst 0.9.0
[XMP-xmp]       Create Date                     : 2023:11:02 06:58:36Z
[XMP-xmp]       Modify Date                     : 2023:11:02 06:58:36Z
[XMP-xmpTPg]    N Pages                         : 1
[XMP-xmpMM]     Document ID                     : yyjhjUTMNykBkGbi2WijNg==
[XMP-xmpMM]     Instance ID                     : BImTNw9C7dIyjtepxT+IaA==
[XMP-xmpMM]     Rendition Class                 : proof
[XMP-pdf]       PDF Version                     : 1.7
```

It seems to be the behavior of Adobe Acrobat (which does not look right to me) rather than an issue with Typst. Sorry for the false bug report.

**Comment by marbar1** [comment]
I assumed that Typst version 0.8.0 does not include the  `XMP-dc Creator` and that's why Adobe Acrobat shows the authors correctly. That assumption was wrong however as the same document compiled with Typst version 0.8.0 has `[PDF] Author` and `XMP-dc Creator` set. This leads me to believe that version 0.9.0 does things differently.

Are there any other PDF properties that store information about the authors?

This is the output of exiftool when the document is compiled with version 0.8.0:
``` bash
$ exiftool -a -G1 test.pdf
[ExifTool]      ExifTool Version Number         : 11.88
[System]        File Name                       : test.pdf
[System]        Directory                       : .
[System]        File Size                       : 9.9 kB
[System]        File Modification Date/Time     : 2023:11:02 08:12:54+01:00
[System]        File Access Date/Time           : 2023:11:02 08:12:55+01:00
[System]        File Inode Change Date/Time     : 2023:11:02 08:12:55+01:00
[System]        File Permissions                : rwxrwxrwx
[File]          File Type                       : PDF
[File]          File Type Extension             : pdf
[File]          MIME Type                       : application/pdf
[PDF]           PDF Version                     : 1.7
[PDF]           Linearized                      : No
[PDF]           Page Count                      : 1
[PDF]           Language                        : en
[PDF]           Author                          : author 1, author 2
[PDF]           Creator                         : Typst
[XMP-x]         XMP Toolkit                     : xmp-writer
[XMP-dc]        Creator                         : author 1, author 2
[XMP-dc]        Format                          : application/pdf
[XMP-dc]        Language                        : en
[XMP-xmp]       Creator Tool                    : Typst
[XMP-xmpTPg]    N Pages                         : 1
[XMP-xmpMM]     Rendition Class                 : proof
[XMP-pdf]       PDF Version                     : 1.7
```

**Comment by gfpj** [comment]
This looks like an Adobe Acrobat implementation behaviour.

Btw: here is a _working_ code for reproducing:

```typst
#set document(author: ("author 1", "author 2", "author 3"))

test
```

Without the content like shown above, Typst will not write the Author information at all.

**Comment by tingerrr** [comment]
I've investigated a bit. The value that is written to the PDF in the end is set here:
https://github.com/typst/typst/blob/897447e8593f00971de3a966d3fb23cf2b1e0f92/crates/typst-library/src/meta/document.rs#L94

And as @gfpj said, without any content in the document, no author information is shown regardless of author count. The style chain entry for `author` is simply empty there.

At first, my assumption was that the style was taken out of the child itself, so when the loop is not entered it won't get those styles of the first page. But this cannot be true as styles is never written to from inside the loop, it's shadowed.

Unfortunately, that's all I found out so far, as the `style.rs` is rather complicated, containing a lot of very similarly named structs. @laurmaedje I think this is important for the styling rework you're working on. Maybe working on this independently is not worth it if this changes drastically in the new future.

**Comment by laurmaedje** [comment]
@tingerrr I think the fact that no author metadata is written at all without content is independent from the issue with the wrong metadata.

**Comment by tingerrr** [comment]
> @tingerrr I think the fact that no author metadata is written at all without content is independent from the issue with the wrong metadata.

Yes, indeed, perhaps we should open an additional issue just for that?

**Comment by Dherse** [comment]
@tingerrr I agree, there seems to be a general issue that documents with only `set` rules don't produce a correct document, not that it really matters I suppose.

**Comment by laurmaedje** [comment]
> I agree, there seems to be a general issue that documents with only set rules don't produce a correct document, not that it really matters I suppose.

I will try to fix that when reworking the styling system. Feel free to open an issue for it.

**Comment by laurmaedje** [comment]
Turns out that if the authors are given in both the document information dictionary and the XMP metadata, Acrobat takes a little bit of both. 

With document information
```
/Author (author 1, author 2, author3)
```
and XMP metadata
```xml
<dc:creator>
  <rdf:Seq>
    <rdf:li>author 1</rdf:li>
    <rdf:li>author 2</rdf:li>
    <rdf:li>author 3</rdf:li>
  </rdf:Seq>
</dc:creator>
```
Acrobat takes the first author from the document information dictionary and the remaining authors from the XMP metadata.

To fix this for Acrobat, we could omit the remaining authors or all metadata from the document information catalog (it is optional) and only write XMP. However, not all other tools (including Apple Preview) read the XMP data. This means we do want to include all authors in the document information dictionary.

Thus, the only alternative is to fold all authors into a single `<rdf:li>` in the XMP metadata. This is, in fact, exactly what the PDF/A spec Part 1 section 6.7.3 has to say about the matter. It's a bit weird to not use the array (and it makes Acrobat show the author list in quotes), but there's not much we can do about that.
