### ISSUE TITLE
Allow specifying bottom-edge and top-edge for box/rect

### ISSUE THREAD

**Issue by wrzian** [typst/typst#2557]
### Problem Statement

After some discord discussion (thanks to discord users mattf_, robin_jadoul, and edhebi for the help!), there doesn't seem to be a nice way to make a box with 0 inset flush against `bottom-edge: "bounds"` or `"descender"`.

With the code:
```typ
#rect(inset: 0pt, lorem(30) + " qypgj")
#set text(bottom-edge: "bounds")
#rect(inset: 0pt, lorem(30) + " qypgj")
```
<img src="https://github.com/typst/typst/assets/133046678/1d498ee6-49f7-42b8-9e79-090732200d3f" width="400">

The first rectangle aligns to the baseline of the last line, leaving the descenders outside the box. The second rectangle aligns flush to the box, but changes the spacing of the entire rest of the paragraph.

You could fix this by doing hacky measurement steps, i.e.
```typ
#let tight_rect(content) = style(st => {
  let base-h = measure(text(content), st).height
  let bound-h = measure(text(content, bottom-edge: "bounds"), st).height
  rect(content, inset: (bottom: bound-h - base-h, rest: 0pt))
})
#rect(inset: 0pt, lorem(20) + " qypgj")
#tight_rect(lorem(20) + " qypgj")
```
<img src="https://github.com/typst/typst/assets/133046678/c59a3331-b6a0-4280-8c34-ab54f9043467" width="400">

But this is not very discoverable, and doesn't do the desired step of not including the descender if there isn't one on the last line:

```typ
#set page(width: 100pt)
#rect(inset: 0pt, "q dolor sit amet elit sed do ut labore et dolore")
#tight_rect("q dolor sit amet elit sed do ut labore et dolore")
```
<img src="https://github.com/typst/typst/assets/133046678/1a458425-cdab-4595-9038-e62acb6103c3" width="200">

In this case it renders the descender despite there being no descenders on the last line, so it effectively doesn't differ from just setting the inset to a constant value.

### Request

I'd like to request the ability to specify that `box` and others have the ability to set what part of the font they measure against for the top and bottom lines. Matching the parameters in `text`'s `top-edge` and `bottom-edge` arguments.

I can see this happening two ways:
1. As top-level arguments: `box(..., bottom-edge: "bounds", top-edge: "x-height", ...)`
2. As additional options for `inset`: `box(..., inset: (top: 5pt, top-edge: "ascender", bottom-edge: "descender", bottom: 5pt), ...)`

### Use Case

This would be helpful for any use-case where you want to have boxes or rects tightly wrap the text they're containing. In grid layouts with boxes, creating labels on top of plots, etc.

**Comment by wrzian** [comment]
I was curious, HTML/CSS seems to use margins based on the total bounding box including the descender.
<https://graphicdesign.stackexchange.com/q/60293>

And for latex, tcolorbox uses the total content height by default.

**Comment by laurmaedje** [comment]
I think this is related strongly to #4224 because just adjusting the text edges would do the trick then (since it wouldn't affect the inter-line spacing).

**Comment by wrzian** [comment]
Hah, I just saw 4224 and thought this would be related only to see you already commented 😁

**Comment by laurmaedje** [comment]
I think having top edge and bottom edge on config containers wouldn't be great as it would potentially needed to be replicated across many elements. We should strive to find a solution that works with the text edges, be it #4224 or something else.
