### ISSUE TITLE
Building from source tarball doesn't work

### ISSUE THREAD

**Issue by msirringhaus** [typst/typst#256]
Hi,
I was trying to package typst for openSUSE. We build from githubs source tarballs. 
However, typst can't be build with that, because `cli/build.rs` expects the whole git-repo to be there, in order to parse out the hash.
I'll locally patch that out for now, but it would be good, if there could be a solution for having tarballs that can actually build.

**Comment by 4cq2** [comment]
this was already fixed https://github.com/typst/typst/commit/a6b63b96f9a5f07dabbe195b16d00d778d3246ff

**Comment by 4cq2** [comment]
https://github.com/typst/typst/issues/99

**Comment by msirringhaus** [comment]
Thanks for the pointer! Closing then.
