### ISSUE TITLE
Bad layout of stacked accents in math

### ISSUE THREAD

**Issue by StrangeGirlMurph** [typst/typst#2563]
### Description

There neither is an accent function nor a symbol for a double tilde (except `approx`).

`tilde(tilde(C))` looks awful:
<img src="https://github.com/typst/typst/assets/62220780/9cf27ebe-5c95-4ee4-9404-fd265f0aa807" width="50"/>
`limits(C)^approx` also really isn't a good alternative.

Please either add a separate accent function for it or make `tilde(tilde(C))` prettier. 

### Use Case

Some specific math applications.

**Comment by Enivex** [comment]
> Please either add a separate accent function for it or make tilde(tilde(C)) prettier.

There is no double tilde accent in unicode, so the solution should be the latter.

Stacking multiple accents in math just doesn't work very well at all right now in general. I thought there was an issue about it, but I couldn't find one.

**Comment by mkorje** [comment]
This was fixed by #3059 I think. From some quick testing on `main`, stacked accents are working just fine now.
