### ISSUE TITLE
Operator precedence and number parsing

### ISSUE THREAD

**Issue by ahenshaw** [typst/typst#257]
It appears that math operations have precedence over number parsing.  For example,

`$5.4 / 2.2$` 

gets rendered as:

![Screenshot_20230324_100308](https://user-images.githubusercontent.com/1940586/227543103-10a8925e-7567-449d-b95c-a94090cfc123.png)

**Comment by 4cq2** [comment]
floats need a `#`:

https://typst.app/docs/reference/types/float

**Comment by 4cq2** [comment]
sorry but I didn't design the syntax. why would you think it would not be needed? even inside a math block, the `.` has dual meaning, hence why a `#` prefix would be needed. if you have an idea for an alternate approach, I would be interested to hear it. most programming languages use a separate token for multiplication (`*`), and so they are able to omit any prefix for floats.

**Comment by ahenshaw** [comment]
For the same reason that you don't have to escape floating-point numbers in a **code block**.  Within a **math block**, floating-point number should be considered as one of the "expected" object types and if there is a conflict, I'd want the escape character to be applied elsewhere.

**Comment by 4cq2** [comment]
> For the same reason that you don't have to escape floating-point numbers in a **code block**.

what is a "code block"? Do you mean raw:

https://typst.app/docs/reference/text/raw

If so, raw text is interpreted in the given language, not in the Typst language, so the comparison does not hold.

> Within a **math block**, floating-point number should be considered as one of the "expected" object types and if there is a conflict, I'd want the escape character to be applied elsewhere.

there's no "if", there is a conflict. as shown in your original example, the `.` token has dual meaning of decimal separator and multiplication operator. so one of the tokens would need to be escaped. the Typst designers decided to apply the escape to the floating point number, similar to the Rust prefix:

https://doc.rust-lang.org/reference/tokens.html#floating-point-literals

**Comment by laurmaedje** [comment]
I agree that this is a bug. Decimals should be parsed as a unit.

**Comment by ahenshaw** [comment]
No, I'm referring to the Typst scripting **code block**, documented here: https://typst.app/docs/reference/scripting/.
There, the Typst developers made a decision to not escape floating-point numbers (there are other escapes used within those blocks).  I'm suggesting that the same principle hold for the math blocks.  

Can you point to where the `.` token is documented to act as the multiplication operator? I don't see that.
