### ISSUE TITLE
IEEE bibliography does not show proceedings title

### ISSUE THREAD

**Issue by genericusername3** [typst/typst#2572]
### Description

I'm trying to cite a paper presented at a conference, using Hayagriva, but Typst does not display the title (or abbreviated, short version) when using `bibliography`. According to [the IEEE reference guide](https://ieeeauthorcenter.ieee.org/wp-content/uploads/IEEE-Reference-Guide.pdf) (see [section B](https://ieeeauthorcenter.ieee.org/wp-content/uploads/IEEE-Reference-Guide.pdf#%5B%7B%22num%22%3A26%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C69%2C351%2C0%5D)), it should (in _italics)_.

Minimal code to reproduce:
<details>
  <summary><code>bib.yml</code></summary>
  <pre>
bogatinovski-failure-identification-log-subprocesses-2022:
  type: article
  title: Failure Identification from Unstable Log Data using Deep Learning
  author:
  - Bogatinovski, Jasmin
  - Nedelkoski, Sasho
  - Wu, Li
  - Cardoso, Jorge
  - Kao, Odej
  date: '2022-07-19'
  serial-number:
    doi: 10.1109/CCGrid54584.2022.00044
  url: https://ieeexplore.ieee.org/document/9826091
  parent:
    type: proceedings
    publisher: IEEE
    date: '2022'
    title:
      value: 2022 22nd IEEE International Symposium on Cluster, Cloud and Internet
        Computing (CCGrid)
      short: 2022 22nd IEEE Int. Symp. Cluster, Cloud and Internet Comput. (CCGrid)
    location: Taormina, Italy</pre>
</details>

<details>
  <summary><code>main.typ</code></summary>
  <pre>
@bogatinovski-failure-identification-log-subprocesses-2022
#bibliography("bib.yml", title: [Bibliography], style: "ieee")</pre>
</details>

---

<details>
  <summary>Result</summary>
  <pre><img alt="A numbered reference and the related bibliography, not showing the conference title" src="https://github.com/typst/typst/assets/42579023/1ea86df3-9083-47f1-b5fd-630e1e6f4f6a"></pre>
</details>

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by zepinglee** [comment]
This bug is because hayagriva fails to `get_container` for `article` type. This is similar to <https://github.com/typst/hayagriva/issues/72> and can be fixed in <https://github.com/typst/hayagriva/pull/74/commits/a86bc8064598b03910ab22d368b9d6f23f06a165> (<https://github.com/typst/hayagriva/pull/74>).

```
./target/debug/hayagriva bib.yml reference --style ieee
```

> [1] J. Bogatinovski, S. Nedelkoski, L. Wu, J. Cardoso, and O. Kao, “Failure Identification from Unstable Log Data using Deep Learning”, in 2022 22nd IEEE International Symposium on Cluster, Cloud and Internet Computing (CCGrid), Taormina, Italy: IEEE, Jul. 2022. doi: 10.1109/CCGrid54584.2022.00044.

**Comment by tingerrr** [comment]
Opening it here is fine, because after the fix at is upstreamed, the dependency also has to be updated here on typst.

**Comment by reknih** [comment]
This can be closed when Hayagriva releases next
