### ISSUE TITLE
Option to quickly check whether the document compiles, without producing output

### ISSUE THREAD

**Issue by raphCode** [typst/typst#2574]
### Description

With the proposed feature, the typst compiler should test whether my document compiles, and exit with an appropriate exit code, in the minimal amount of time possible.

I am therefore interested in the cold, non-incremental compilation time.  I do not need a generated PDF nor do I need any other form of page output.

While the functionality is already covered by `typst compile`, I believe speedups should be possible when no output needs to be produced.

### Use Case

I use a [pre-commit](https://pre-commit.com/) hook to check whether my document compiles before allowing a commit to be made. This ensures that I do not commit broken typst sources.

As the document grows bigger and more complex, these compilations take more and more time, slowing down the commit process and productivity.

In a similar fashion, the proposed feature can be helpful in CIs for repos which version control typst documents.

**Comment by raphCode** [comment]
Interesting, I just gave it a try in my biggest project! It indeed works, but sadly not that much faster than a real compile. Not sure if speed gains are even possible?

Hyperfine benchmark:
```
Benchmark 1: typst compile main.typ
  Time (mean ± σ):     12.073 s ±  0.063 s    [User: 11.772 s, System: 0.194 s]
  Range (min … max):   11.966 s … 12.125 s    5 runs

Benchmark 2: typst query main.typ '<a>'
  Time (mean ± σ):     11.869 s ±  0.086 s    [User: 11.558 s, System: 0.207 s]
  Range (min … max):   11.762 s … 11.946 s    5 runs

Summary
  typst query main.typ '<a>' ran
    1.02 ± 0.01 times faster than typst compile main.typ
```

**Comment by laurmaedje** [comment]
There can also be errors during layout. The only thing we could skip is export, which is not that expensive typically.

**Comment by raphCode** [comment]
should we close this?

**Comment by laurmaedje** [comment]
I'm not yet sure about whether to have such a command since even export will have the capability for errors in the future, but we can in any case close in favor of https://github.com/typst/typst/issues/3792, which has seen a bit more traffic based on the reactions.
