### ISSUE TITLE
Creating a release workflow

### ISSUE THREAD

**Issue by AntoniosBarotsis** [typst/typst#258]
Related #108

## Description

Eventually, you will probably want to have a consistent and straightforward way of publishing the crates in this repository to `crates.io`, an automated workflow makes a lot of sense for this. This issue is meant to get a conversation started on the details of said workflow and eventually help implement one.

## Questions

A few questions for the maintainers:

- Are you going to use Github Releases?
- Which crates do you want to publish?
- I usually like working with workflow dispatch triggers, is that ok with you or do you want something else (like git tags for instance)?

For the workflow trigger, I see that the existing release workflow uses an `on: release` trigger, my issue with that is that you won't have a clear way of publishing releases for specific crates separately (a small update to one crate shouldn't require all crates to be bumped). Maybe it makes more sense to make a separate workflow for `crates.io` releases?

## Notes 

I see that some relevant progress towards this is already being made in #122, I'll wait for that to be merged and then I could start working on the workflow.

**Comment by laurmaedje** [comment]
There are separate issues for publishing to crates.io:
- #2450 
- #108 

We also publish GitHub releases regularly and have a workflow for automatically building the release assets. That workflow is triggered manually, but it's working fine, there's no need for automation there at the moment. Closing this.
