### ISSUE TITLE
Gradient misbehaves on radicals

### ISSUE THREAD

**Issue by schuelermine** [typst/typst#2586]
### Description

A gradient over a math equation will not work correctly on radicals.
To emphasize, I’m setting the background to black.
Code like this:
```typ
#set page(fill: black)
#show math.equation: content => [
  #set text(fill: gradient.linear(..color.map.turbo))
  #box(content)
]
#set page(height: auto, width: auto, margin: 1em)

$ sqrt(x + 1) (x + 1 $
```
Results in this output:
![Screenshot 2023-11-04 at 19-54-26 scratchpad – Typst](https://github.com/typst/typst/assets/48802534/4e8d9d70-c4c6-40b8-9bdf-627c7218b695)
Additionally the color in the bar on top of the radical is also completely broken when looking at the exported PDF:
![Screenshot 2023-11-04 at 19-54-21 scratchpad-1 pdf](https://github.com/typst/typst/assets/48802534/53ab3bdc-f135-4f8e-a835-fa13ad00ba22)

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by gfpj** [comment]
For me, the behaviour looks expected. Can you add, how you want the output to look like?
`sqrt` and some others are put togeteher from multiple parts. Thus, the hard cut.
I can reproduce the first picture, but not the second.

**Comment by Enivex** [comment]
@Dherse

**Comment by Dherse** [comment]
@schuelermine is correct, it should apply to all parts, the issue is that I didn't delve too deep into the math code, therefore it doesn't handle all of the strokes generated in math code. This would require a PR that goes all over the math code and fixes it.
