### ISSUE TITLE
Text goes outside of margins and gets cut off

### ISSUE THREAD

**Issue by soupslurpr** [typst/typst#2589]
### Description

Hey, Typst seems very interesting and I'm trying to implement it in my text and markdown editor for Android, BeauTyXT.
I wanted to ask, is it a bug that a long string of text without spaces goes over the margin and gets cut off?
Reproduction:
`hellooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo`

export this to pdf or svg, and you will see what I mean. Thanks.

### Operating system

Windows, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
typst use https://github.com/unicode-org/icu4x to find linebreak points. in this case it fails to find one. this also occurs in links.

**Comment by gfpj** [comment]
Duplicate of https://github.com/typst/typst/issues/862 which is a duplicate of https://github.com/typst/typst/issues/674.

**Comment by laurmaedje** [comment]
@Enter-tainer The link line breaking was actually fixed in 0.9 with special link line breaking code.
