### ISSUE TITLE
SVG dark mode

### ISSUE THREAD

**Issue by soupslurpr** [typst/typst#2590]
### Description

I'm using the SVG export for a preview in my app, could there be a way to make it suitable for dark backgrounds by making the text white?

### Use Case

Dark mode users, so their eyes don't get burnt 😅

**Comment by Enter-tainer** [comment]
you can set text and background colors in your typst source code, then it produce "dark mode" svg

**Comment by soupslurpr** [comment]
> you can set text and background colors in your typst source code, then it produce "dark mode" svg

Could you show me a sample or link to the docs of how to set the text and background colors?

**Comment by Enter-tainer** [comment]
https://typst.app/docs/reference/layout/page/

![Screenshot_2023-11-05-13-42-15-627_com.microsoft.emmx.jpg](https://github.com/typst/typst/assets/25521218/c8dec29f-3e61-4ac5-b4d9-04a3814ed152)

i think it is an easy google search🤔why not do it yourself

**Comment by soupslurpr** [comment]
Thank you, I didn't find it in Google search.
