### ISSUE TITLE
Add aspect ratio to page function

### ISSUE THREAD

**Issue by elliotnash** [typst/typst#2594]
### Description

Adds a new parameter to the page function that takes an aspect ratio. Pages with an aspect ratio set would determine the smallest page size of the given ratio where all the content fits onto one page.

### Use Case

Currently, the page function only supports widths/heights of type auto and length. In cases where rendered images need to be displayed in a fixed space, the only way to constrain the aspect ratio is by setting height and width to a fixed length and only rendering the first page. Allowing an aspect ratio to be passed would allow all the content to be rendered onto one page while still maintaining the desired aspect ratio.

**Comment by laurmaedje** [comment]
I think you could build something like this in user code with `measure`.

**Comment by laurmaedje** [comment]
I think this is out of scope for a built-in.

**Comment by laurmaedje** [comment]
Maybe there could be some non-page-specific aspect ratio layout functionality in the future.
