### ISSUE TITLE
Full-page floating elements overlap with text

### ISSUE THREAD

**Issue by pklaschka** [typst/typst#2595]
### Current Behavior

When a floating element (using `place` or `figure`) takes up the full size of the page, a line of text from the main text flow gets "forced" onto that page and overlaps.

### Expected Behavior

The element takes up the full page, and the main text flow continues on the next page.

### More Details

<details><summary>Code to Reproduce</summary>
<p>

```typ
#lorem(200)

#place(auto, float: true, [
  #block(height: 100%, width: 100%, fill: lime)
])

#lorem(700)
```

</p>
</details> 

<details><summary>Result (Screenshot)</summary>
<p>

![image](https://github.com/typst/typst/assets/25147704/3a79e8c9-35bb-47a2-b1a0-fa32979dbe73)

</p>
</details> 

<details><summary>Use Case</summary>
<p>

Having extra pages for figures, similar to what LaTeX does. This can, then, also be used to replicate things like the `sidewaystable` package in LaTeX.

</p>
</details> 

### Reproduction URL

https://typst.app/project/rj3cUp9FbSQ5_7m4ARJ6Wx

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by coljac** [comment]
The text which wraps over can be forced into the footer area as well: e.g. 
```typst
#set page(footer: align(center)[Footer])
#lorem(500)
#place(top, float: true,  box(height: 100%, width: 100%, stroke: 1pt + black, align(center+horizon)[This page left blank] ) )
#place(top, float: true,  box(height: 100%, width: 100%, stroke: 1pt + black, align(center+horizon)[This page left blank] ) )
#lorem(1000)
```

**Comment by NMAC427** [comment]
This issue also appears when using the figure element.
```typst
#lorem(1000)
#figure(placement: auto, caption: [CAPTION], rect(height: 100%, fill: red))
#lorem(1000)
```
