### ISSUE TITLE
Expose numbering to Typst functions

### ISSUE THREAD

**Issue by trombonehero** [typst/typst#2596]
### Description

I would like to be able to use Roman numerals within a custom numbering function, allowing me to produce a TOC like:

> Part 1: The First Part
> I. Things
> II. More things
>
> Part 2: The Second Part
> I. Yet more things
> II. Still more things

Right now I can use `numbering: "1.I."` with custom `show heading.where(level: X)` stuff to format my in-text headings correctly, but the TOC shows:

> 1. Some stuff
> 1.I. Things
> 1.II. More things
> 2. Other stuff
> 2.I. Yet more things
> 2.II. Still more things

So, what I'd like to do is use a numbering function something like:

```typst
  numbering: (..nums) => {
    let (part, ..chapter_and_sections) = nums.pos()

    if other.len() == 0 [
      Part #part:
    ] else {
      chapter_and_sections.display("I.1.")
      //
      // or:
      //
      let (chapter, ..sections) = other
      (chapter, ..sections).display("I.1.")
      // or
      chapter.display("I") + "." + sections.map(str).join(".") + "."
      // or
      roman_numeral(chapter) + "." + sections.map(str).join(".") + "."
    }
  }
```

However, there is no `display` method on not arrays or integers, nor is there a function for numeral conversions. I'd really rather not re-invent the wheel with a Roman numeral conversion function within Typst script when the library itself already has one. :)

### Use Case

Users will be able to customize numbering in an outline using the various numbering systems that Typst already provides.

**Comment by PgBiel** [comment]
Is this what you're looking for?: https://typst.app/docs/reference/meta/numbering/

**Comment by trombonehero** [comment]
I feel slightly embarrassed that, despite looking at that page a bunch of times, it didn't click that `numbering` was a function that I could call from a numbering function passed to the `numbering` parameter of `heading`. Maybe the [`heading` docs ](https://typst.app/docs/reference/meta/heading/#parameters-numbering) could use a more complex example alongside of the existing simple one?

```typst
#set heading(numbering: (..nums) => {
  // Split into part, chapter and [sub-]section for different numbering styles
  let (part, ..chapter_and_sections) = nums.pos()

  if chapter_and_sections.len() == 0 [
    Part #part:
  ] else {
    let (chapter, ..sections) = chapter_and_sections

    if sections.len() == 0 {
      numbering("I.", chapter)
    } else {
      numbering("1.a.", ..sections)
    }
  }
}
```

**Comment by trombonehero** [comment]
I'm happy to say that, with the `numbering` function, Typst will let me do exactly the thing I wanted. Thanks very much for this language! Also, please feel free to use the following in code examples or (if it's helpful) in some library of styling customizations.

```typst
//
// Number sections according to a number of schemes, omitting previous leading elements.
// For example, where the numbering pattern "A.I.1." would produce:
//
// A. A part of the story
//   A.I. A chapter
//   A.II. Another chapter
//     A.II.1. A section
//       A.II.1.a. A subsection
//       A.II.1.b. Another subsection
//     A.II.2. Another section
// B. Another part of the story
//   B.I. A chapter in the second part
//   B.II. Another chapter in the second part
//
// clean_numbering("A.", "I.", "1.a.") would produce:
//
// A. A part of the story
//   I. A chapter
//   II. Another chapter
//     1. A section
//       1.a. A subsection
//       1.b. Another subsection
//     2. Another section
// B. Another part of the story
//   I. A chapter in the second part
//   II. Another chapter in the second part
//
#let clean_numbering(..schemes) = {
  (..nums) => {
    let (section, ..subsections) = nums.pos()
    let (section_scheme, ..subschemes) = schemes.pos()

    if subsections.len() == 0 {
      numbering(section_scheme, section)
    } else {
      clean_numbering(..subschemes)(..subsections)
    }
  }
}
```

**Comment by Dherse** [comment]
@trombonehero Happy to know Typst fits your needs :)
