### ISSUE TITLE
Google Fonts support

### ISSUE THREAD

**Issue by Enivex** [typst/typst#2599]
### Description

Being able to specify a font from Google Fonts, and have the compiler pull it from the internet if not already present.

https://developers.google.com/fonts/docs/developer_api

### Use Case

Google Fonts is a large curated database of fonts, and being able to pull fonts from there would instantly give typst users access to thousands of fonts, without having to have them installed as system fonts.

**Comment by alerque** [comment]
It would also open up a huge privacy hole. You could mitigate this from the web side with a cache on *your* server side, but the CLI would leave lots of exposure. If you go down this road figure out something more generic for remote fonts such that alternative providers could be used and no network actions would be taken without the knowledge of somebody rendering on their own system.

**Comment by realpixelcode** [comment]
> It would also open up a huge privacy hole. You could mitigate this from the web side with a cache on _your_ server side, but the CLI would leave lots of exposure. If you go down this road figure out something more generic for remote fonts such that alternative providers could be used and no network actions would be taken without the knowledge of somebody rendering on their own system.

Instead of fetching the respective font from Google Fonts during each compilation, Typst could instead download the font once and then include the `.ttf` file (or whatever) in the project source. There could be a dedicated `.fonts` folder where Typst would look for the desired font before downloading it.

**Comment by laurmaedje** [comment]
Compiler-wise this is not desirable I think. Web-app wise we have our own fonts infrastructure, which also requires other metadata than Google fonts, privacy issues aside.
