### ISSUE TITLE
syntax for marking project root

### ISSUE THREAD

**Issue by Roger-luo** [typst/typst#2608]
### Description

I'd like to have a syntax sugar for all path strings to access the project root path in the import, e.g

```
#import "@project/templates/lib.typ"

image("@project/figure/image.png")
```

and `@project` will be replaced by the root path specified to `typst` compiler via `--root`, ideally it should be set automatically by some file structure, but typst currently doesn't have a standard way of specifying a project, maybe it can also search the file path `typst.toml` first.

### Use Case

Currently, this is quite inconvenient especially when the project has many files organized by directories. You have to write the above as

```
#import "../../../templates/lib.typ"

image("../../../figure/image.png")
```

and moving around the script will break the above path. The idea is quite similar to rust's `crate::`  and `super::` in the module loading syntax

On the other hand, I noticed there is #2148 but more for importing package internals, which is not the same as this proposal.

**Comment by Roger-luo** [comment]
In the case that using `@<name>` may break the current package loading behavior, I think special case `@project` or `@root` is probably fine as I don't see these two words would make sense in the future.

**Comment by laurmaedje** [comment]
There is existing syntax for this: `/`. 

`#import "/templates/lib.typ"` will load the file `templates/lib.typ` relative to the `--root`.

**Comment by Roger-luo** [comment]
oh thanks! I didn't know that, maybe this should be mentioned in the doc somewhere? I did a random search didn't find any.

**Comment by laurmaedje** [comment]
yeah, I'm not sure but maybe it's in fact not in the docs.
