### ISSUE TITLE
Text ("") in math cases renders as math sometimes

### ISSUE THREAD

**Issue by Atreyu-94** [typst/typst#2614]
### Description

When I am in the cases() function, and I enter text, sometimes it is rendered as math depending on whether or not I leave a space inside the string.
|Typst Code| PDF rendered|
|----------------|-----------------|
|` $ cases(  l &= 2 "m"\  l &= 2 " m"\) $`| ![imagen](https://github.com/typst/typst/assets/39834909/068224b3-4881-4cc2-b507-f0963a669a0d) |

### Reproduction URL

https://typst.app/project/rFWZXOwo1NZj1WYfTE644v

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
Duplicate https://github.com/typst/typst/issues/274
