### ISSUE TITLE
Align available parameters on `grid` and `table`

### ISSUE THREAD

**Issue by tapyu** [typst/typst#2616]
### Description

I usually need to align the grid rows/columns and, at the moment, I am doing so by using using Typst's code mode, which is a little bit cumbersome... I wonder whether it isn't a often task that should have a `align`.

### Use Case

My idea would be something like

```
#grid(
  columns: (1fr, 1fr, 1fr),
  align: (center, right, left),
  "Test1",
  "Test2",
  "Test3", 
  "Test4",
  "Test5",
  "Test6", 
)
```

Each text entry would be aligned as defined in the `align` option.

**Comment by laurmaedje** [comment]
Aligning (heh) the available arguments on `grid` and `table` is something that was discussed and chosen to be desirable. That would include this. I'll reword the issue title to fully encompass this.
