### ISSUE TITLE
Watcher exits with "file is not valid utf-8" error instead of waiting for further file changes

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2632]
### Description

If I for any reason have an invalid UTF-8 text while using `typst watch`, it will exit with the error instead of keep on looking for changes in case text will become a valid UTF-8 text again. Since other errors are shown and `typst watch` still watches for changes but not in this case, I consider this as a bug.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by lihe07** [comment]
I've worked on this issue. If that's considered an bug, I can submit my changes through PR.

**Comment by Andrew15-5** [comment]
Go ahead!) I'll test it.

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/2795

**Comment by Andrew15-5** [comment]
@lihe07, I've tested this and I love it! Thank you!
