### ISSUE TITLE
Inconsistent math binding when not using spaces between number and non-letter

### ISSUE THREAD

**Issue by Easyoakland** [typst/typst#2640]
### Description

The following syntax is valid
```typst
$1/2pi$
```
It renders the same as
```typst
$1/2 pi$
```
It should render the same as 
```typst
$1/(2pi)$
```

It doesn't have to be `pi`. It can be any symbol or letter.

Either `1/2pi` should be a syntax error or it should be formatted as the meaning it conveys semantically: `2` and `pi` without separation.

This can be summarized with the following table
```typst
#let helloWorld = $"hello_world"$
#table(columns: 3)[typed][render][should][
  `1/2pi`][$1/2pi$][$1/(2pi)$][
  `1/2 pi`][$1/2 pi$][$1/2 pi$][
  `1/(2 pi)`][$1/(2 pi)$][$1/(2pi)$][
  `1/(2pi)`][$1/(2pi)$][$1/(2pi)$][
  `1/2helloWorld`][$1/2helloWorld$][$1/(2helloWorld)$][
  `1/2L`][$1/2L$][$1/(2L)$]
```
which generates
![typst_binding_bug](https://github.com/typst/typst/assets/97992568/d6ff2cee-f62d-4eee-bddc-dd46ff2a5bac)

### Operating system

Windows, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
It seems pretty consistent, just counter to your preference

Personally I'd like to move in the _other_ direction. That is, less whitespace-dependence in math mode and simpler parsing for both humans and compiles.

Division has the same precedence as multiplication, and 2pi simply means 2*pi. This means that 1/2pi=1/2*pi=pi/2. Moreover, your proposal would only ever work for integer literals, not named constanfs.

**Comment by Easyoakland** [comment]
I don't know what you mean by
> your proposal would only ever work for integer literals, not named constanfs.

but if this is intended behavior that a numeral and symbol with nothing separating in sourcefile shouldn't end with nothing separating in the final output and instead bind with the strength of a `*` or `dot` operator then I'll close the issue.

I think `1/2L` reads as `2L` in the denominator not `1/2 L` but if it's just a personal preference thing and not a bug then it doesn't matter.
