### ISSUE TITLE
(Interactive) `typst new <name_of_project>` command

### ISSUE THREAD

**Issue by Tastaturtaste** [typst/typst#2651]
### Description

An opinionated command analogous to `cargo new` to create a new typst project structure with a selection of default templates one can use to get started with a document. The selection of templates could maybe be extensible by each user by introducing a template folder where users can place their own project templates. Alternatively a remote git repository could be used to make templates accessible.

### Use Case

1. Introducing a default project structure as a guideline for the community
2. Lowering the barrier of entry for local document writing
3. Reduction setup time

**Comment by Quaqqer** [comment]
I'd like to try to contribute with this feature. What kind of scope should the feature have? Should it just create a fixed set of files or ask questions like the web interface? Should it be possible to create custom templates with typst packages? Maybe it would be reasonable to start with a fixed structure?

**Comment by laurmaedje** [comment]
We do want it to support templates, see also [this issue](https://github.com/typst/typst/issues/2432) and [this Discord discussion](https://discord.com/channels/1054443721975922748/1176122103355953162/1176122103355953162). That will probably have to be hashed out first before it makes sense to work on the CLI command.

**Comment by laurmaedje** [comment]
This has shipped in the form of `typst init`.
