### ISSUE TITLE
Add tests for shorthand

### ISSUE THREAD

**Issue by TheJosefOlsson** [typst/typst#2653]
### Description

When searching for if a shorthand has been used, the order of the search is important. As an example: in typst-syntax/src/lexer.rs, the rows
```
            '<' if self.s.eat_if("-->") => SyntaxKind::Shorthand,
            '<' if self.s.eat_if("--") => SyntaxKind::Shorthand,
```
must be in this order, else the shorthand for "⟷" will be converted to "⟵>".

### Use Case

Tests ensures that changes such as adding more shorthands or rewriting code will not break anything.

**Comment by laurmaedje** [comment]
More tests could be added here: https://github.com/typst/typst/blob/main/tests/typ/compiler/shorthand.typ
