### ISSUE TITLE
Raw string syntax?

### ISSUE THREAD

**Issue by user202729** [typst/typst#266]
Currently I think there's no raw string supported (apart from triple-quoted code block which is quite unwieldy to use in code), so `"\\\\"` is needed to get a string with two backslashes.

This may be a bit inconvenient when used in regex, and if new escape sequences are supported then code relying on implicit backslash will be forward-incompatible. (for example Python gives a warning when backslash escape sequence does not match anything)

Python also has `r"..."` syntax for raw string.

**Comment by rmgaray** [comment]
You can use a single-quoted code block as is described here: https://typst.app/docs/reference/text/raw/ .

Just like in a triple-quoted code block, escape sequences are disabled:

Input
```
`Hey look, no escape sequences: \n \t \\`
```

Output
`Hey look, no escape sequences: \n \t \\\`

**Comment by user202729** [comment]
I think you misunderstood the issue.

Does ``regex(`\\`)`` match a single backslash? I don't think so?

**Comment by rmgaray** [comment]
I see your point now. `regex` only takes a string, so trying ```regex(`\\`)``` does not even work:

```
error: expected string, found content
   ┌─ hello.typ:27:7
   │
27 │ #regex(`\\`)
   │        ^^^^
```

**Comment by laurmaedje** [comment]
You can access the text field on the raw element though. This should work:
```
`hey \\ there`.text
```

**Comment by user202729** [comment]
Interesting. Although a bit cumbersome as a syntax (and I don't know about the performance -- does it construct an element which then immediately get thrown away?), it doesn't require escaping anything.

Maybe consider adding it to the documentation of regex? Unless the list of allowed escape sequences (for example I believe currently `\d` `\w` etc. is not valid string escape sequence) will be frozen forever, telling users to "just type normally unless it doesn't work as expected then double the backslash" seems like not that good of an idea.

**Comment by laurmaedje** [comment]
The performance implications should be negligible.
