### ISSUE TITLE
Links in bibliography cannot be styled

### ISSUE THREAD

**Issue by flother** [typst/typst#2667]
### Description

If you set a custom style for hyperlinks, that style will be used in a document's body text but not in the bibliography. (This seems like a regression since #264 was fixed in March.)

1. Typst doc:

    ```typst
    #show link: set text(blue)

    A link: http://example.com/

    #bibliography("bib.bib", full: true)
    ```
2. Bibliography (`bib.bib`):

    ```bibtex
    @article{Turing1937,
      title={On computable numbers, with an application to the Entscheidungsproblem},
      author={Alan Turing},
      journal={Proc. London Math. Soc.},
      year={1937},
      volume={s2-42},
      pages={230-265},
      url={http://example.com/}
    }
    ```
3. Expected output: both links to http://example.com/ should be coloured blue
4. Actual output: only the link in the body text is blue; the link in the bibliography remains the same colour as the surrounding text

<img width="609" alt="" src="https://github.com/typst/typst/assets/48392/dcd5a41b-9069-41bb-a7d9-4e2a80482c6c">

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
Is it not intentional that CSL should be controlling the styling of the bibliography?

**Comment by flother** [comment]
Perhaps, but it certainly feels like a bug at face value. Do you know if any of the common CSL styles specify link formatting?

Besides that, this means if I want bibliography links to match body text links then I wouldn't be able to rely on Typst's built-in styles. I'd need to maintain a fork of the CSL styles I use, which seems like a bit of burden just for link colours (but maybe I'm just lazy 😉).

**Comment by flother** [comment]
> Do you know if any of the common CSL styles specify link formatting?

Just the first I looked at (because it's the style I use), but in the [docs on APA style for URLs in references](https://apastyle.apa.org/style-grammar-guidelines/references/dois-urls):

> It is acceptable to use either the default display settings for hyperlinks in your word-processing program (e.g., usually blue font, underlined) or plain text that is not underlined.

That sounds like it's up to the document author to choose. Just one style of course.

**Comment by laurmaedje** [comment]
Looks like I made the same mistake again. CSL doesn't have any mechanism for colors anyway, so it couldn't be handled there.

**Comment by flother** [comment]
Thanks for fixing it so quickly!
