### ISSUE TITLE
Syntax to avoid continuation passing?

### ISSUE THREAD

**Issue by user202729** [typst/typst#267]
I think the current design to work with mutable state using only pure functions is quite good -- the "renderer" can do mutable work, functions such as `style()`, `locate()`, `counter.step()` etc. returns a [content] object that does the mutable thing when rendered. Similar to how Haskell use monad to represent mutable actions.

That having said, is it worth it to make a special syntax to simplify code that requires multiple layer of nesting? Similar to `await` in JavaScript or `do ... x <- ...` in Haskell.

(for simple-enough scripts it wouldn't be necessary, but inevitably someone will build complicated things over time?)

**Comment by 4cq2** [comment]
> That having said, is it worth it to make a special syntax to simplify code that requires multiple layer of nesting? Similar to `await` in JavaScript or `do ... x <- ...` in Haskell.

`await` is needed with JavaScript and others, because code in those cases is dealing with multiple threads of execution, which is wholly different from what Typst is doing. It seems you concern can already be addressed with existing procedural programming methods such as let:

https://typst.app/docs/reference/scripting/#bindings

**Comment by ndtodoroff** [comment]
@4cq2 I think what @user202729 is referring to is that conceivably someone would want to do something like
```typst
#style(s => {
  locate(l => {
    // maybe more layers like with counter.step()
    // do things with s and l
  }
}
```
and I think what they want is some sort of syntax that does this lambda layering implicitly (which is not unlike Haskell's `do` syntax). Personally, I'm not sure we could ever have enough layers that this is needed. In this case if someone wants both `style()` and `locate()` I think its easy enough to do something like
```typst
#let environ(f) = style(s => locate(l => f(s, l)))

#environ((s, l) => {
  // do things with s and l
})
```
I think that maybe Typst could benefit from a closure-passing notation like Julia's `do` but that is a separate issue.

**Comment by laurmaedje** [comment]
I think that you don't need _that_ many layers right now. Before `style` and `locate`, all functions like `query` and `measure` took individual callbacks. That _was_ bad!
