### ISSUE TITLE
Use proper quotation marks for Danish

### ISSUE THREAD

**Issue by S3bTheGuy** [typst/typst#2670]
### Description

When using quotation marks in Typst, on a Danish document, it renders: `„...“` by default, which we don't use in Danish. The most common form in Danish is `"..."` with `»...«` being preferred by most schools. Babel uses the more common `"..."` by default, and quite a few other sources suggest that is the default way of quoting:
- [Write Correct Danish](https://www.skrivkorrektdansk.dk/emne.aspx?kid=11&tid=214)
- [DSN](https://dsn.dk/ordboeger/retskrivningsordbogen/§-40-60-tegnsaetning/§-58-anfoerselstegn/)
- [EU Vocabularies](https://op.europa.eu/en/web/eu-vocabularies/formex/physical-specifications/character-encoding/use-of-quotation-marks-in-the-different-languages)
- [Århus University (Quotation marks (inverted commas))](https://medarbejdere.au.dk/administration/kommunikation/sprogportal/au-english-style-guide/punctuation#quotationmarks)
- [Overleaf](https://www.overleaf.com/learn/latex/Typesetting_quotations#Reference_guide)

## Example: 
```typ
"Hello World"
```
Renders: „Hello World“ but trying: 
```typ
#set smartquote(enabled: true, alternative: true)
"Hello World"
```
renders as: »Hello World« which is the aforementioned preferred way to quote in a school setting. 

## Suggested Solution
```typ
"Hello World"
```
Should just get output as `"Hello World"` while:
```typ
#set smartquote(enabled: true, alternative: true)
"Hello World"
```
should remain, this would align with what Danish students and writers use commonly. 

### Operating system

macOS

### Typst version

- [x] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This would be the place to change it: https://github.com/typst/typst/blob/67422e664b9e7089e8eb4de65c5a25b2817a00c0/crates/typst-library/src/text/quotes.rs#L201-L218

**Comment by T0mstone** [comment]
Your sources still don't make it clear whether it's supposed to be `“…”` or `”…”` (notice the different left quotes).
[Wikipedia](https://en.wikipedia.org/wiki/Quotation_mark#Summary_table) lists both, so that doesn't help either...

**Comment by S3bTheGuy** [comment]
It's rather difficult finding exact textbook examples, `“…”` are indeed the ones I meant we use mainly. I can go look for more examples or find some better sources, so far the only thing usable on wikipedia is that both `“…”` and `»...«` are listed as primaries.

**Comment by S3bTheGuy** [comment]
there is this danish source:
[Sproget DK](https://sproget.dk/raad-og-regler/Retskrivningsregler/retskrivningsregler/a7-40-60/a7-58-anforselstegn)

> Anførselstegn kaldes også citationstegn eller gåseøjne. Der er følgende hovedformer: »...« og "..."; mindre benyttede er de enkelte (ufordoblede) anførselstegn: ›...‹ eller ‘...’ 
## in English 

> Quotation marks are also known as quotation marks or goose eyes. There are the following main forms: »...« and "..."; less commonly used are the single (unduplicated) quotation marks: ›...‹  or  ‘...’

**Comment by Enivex** [comment]
Babel uses `“”` for double quotes and `‘’` for single quotes

https://github.com/latex3/babel/blob/main/locale/da/babel-da.ini
