### ISSUE TITLE
Support the WebP image format

### ISSUE THREAD

**Issue by AlbertoFabbri93** [typst/typst#2673]
### Description

The WebP image format is a widely used and accepted image format on the internet.

### Use Case

Being able to use WebP images inside Typst documents.

**Comment by Dherse** [comment]
I think that should be fairly easy to add since it's already supported by the image crate. Mind you its support is limited to lossy RGB and lossless RGBA WebP images.

**Comment by mattfbacon** [comment]
Unfortunately I don't think there is any pure Rust webp encoder implementation. Everything on crates.io just links to libwebp.

**Comment by laurmaedje** [comment]
Closing based on the discussion in the linked PR: https://github.com/typst/typst/pull/2925#issuecomment-1875075352
