### ISSUE TITLE
Add support for integer modulo (division remainder)

### ISSUE THREAD

**Issue by hgruniaux** [typst/typst#2677]
### Description

It can be useful to add integer modulo (the remainder of the euclidean division) to the list of supported binary operators in the Typst scripting language. This operator could take the following syntax: `%` and `%=` (as in Rust, C, JavaScript, Python, etc.), or `mod` (as in Ocaml).

This could also be extended to floating-points, like the `%` operator on Rust which works on floats and the `fmod` function from the C standard library.

### Use Case

```typst
assert(10 % 3 == 1)
assert(5.1 % 3.0 == 2.1)
```

This could be used for wrapping around some things, repeating patterns, etc. 

I expect to use it to implement bit wrapping for multirows bytefields in jomaway/typst-bytefield#7.

**Comment by Enivex** [comment]
This already exists as calc.rem()
