### ISSUE TITLE
Support fixed-width text inside math equations

### ISSUE THREAD

**Issue by Remillard** [typst/typst#2679]
### Description

In describing firmware features, I frequently have to move in and out of decimal and hexidecimal notation with equations.  It is possible to style text in equations with strong/bold/italic.  I would suggest that `raw()` be likewise supported.

### Use Case

Something like 

`$a + b = 1 #sym.equiv raw("0x8000")$`

would style the equation as usual until it gets to the hexadecimal representation which is then written `0x8000` as it is here in Markdown.

**Comment by Enivex** [comment]
`$a + b = 1 equiv #raw("0x8000")$` works just fine, but it'll use the regular raw font

 There is a unicode range for mathematical monospace a-z, A-Z and 0-9, but it's currently not accessible in any great way.

**Comment by frozolotl** [comment]
You can use one of these instead:
```typ
$a + b = 1 #sym.equiv #raw("0x8000")$ \
$a + b = 1 #sym.equiv #`0x8000`$ \
$a + b = 1 #sym.equiv mono("0x8000")$ \
```
The first two are equivalent, while the latter uses the math font for that.

**Comment by Remillard** [comment]
Okay, mono is really what I was going for so I could write: 
![image](https://github.com/typst/typst/assets/28012313/fb1e9e88-8eb5-42f0-9f14-aa57bf177b82)

Under Math styling the web page only listed the bold and italic styles so I tried raw as it equates to the usual backtick shortcut, hence the suggestion.  `mono()` is perfect though, thank you.

**Comment by Enivex** [comment]
> You can use one of these instead:
> 
> ```typst
> $a + b = 1 equiv #raw("0x8000")$ \
> $a + b = 1 equiv #`0x8000`$ \
> $a + b = 1 equiv mono("0x8000")$ \
> ```
> 
> The first two are equivalent, while the latter uses the math font for that.

I could swear typst had mono, but when I searched the documentation I couldn't find it. I was looking under styles, but turns out it was under variants. Not sure why those require different pages.

**Comment by Remillard** [comment]
And here I thought I had an honest to god feature suggestion... and it's covered!  Not really a problem obviously though
