### ISSUE TITLE
Proposal for async-blocks for web requests and shell execution

### ISSUE THREAD

**Issue by victor-sm** [typst/typst#269]
Multiple issues have been opened requesting specific libraries or functions to be ported/included (#160, #161, #186, #184, #233). On one hand, waiting for these to be ported might take a while and hinder adoption in the meantime. On the other, one might ask whether it is even worth the effort to port everything to typst directly if those libraries offer vector export natively. 

I think a solution to this problem might be to allow the execution external of binaries and web requests. People using typst offline would then be able to use python/julia (#117, #244) and their favorite tools, as well as allow for loading data directly from databases or APIs. 

With the steady improvements to webAssembly and projects such like [pyodide](https://github.com/pyodide/pyodide) and [wasmer](https://github.com/wasmerio/wasmer) binaries could even be packaged as wasm-modules allowing the use offline as well as online. If a consensus for some kind of built-standardization of those wasm-modules could be reached, one could even imagine a some kind of package manager, which automatically gets the latest version of some library and compiles to wasm.

For this to work in practice I propose for typst to support an async-code-block:

```
#async {
	...
}
```

Everything inside an async-block is private in scope and gets deleted after being run. Outside variables are read-only. Async-blocks only get run when manually triggered by the user or with a command line flag. That way outside binaries or web requests don't get triggered constantly while editing or without the users knowledge for security reasons. 

If one wants to use the result of a web request or an external binary, it has to be saved to a file. This file can then be read normally outside the async-block. Forcing the user to save the data to files, would allow the document to still be parsed correctly when offline and make it easy to be kept for archival purposes.

This would (I think) still be within the core principles of typst:

> In Typst, all functions are pure. This means that for the same arguments, they always return the same result. They cannot "remember" things to produce another value when they are called a second time.

and

> Performance through Incrementality: All Typst language features must accommodate for incremental compilation. Luckily we have [comemo](https://github.com/typst/comemo/), a system for incremental compilation which does most of the hard work in the background.

Since everything outside the async-blocks would use read/image to load created files, there wouldn't be any change. Async-blocks themselves would also follow this principle, with the only difference that they only get run when triggered.

I imagine these kind of functions could be supported inside async-blocks:

```
#async {
	/* Send a post request to a url */
	post(
		url,
		payload,
		...
	)
	
	/* Send a get request to a url */
	get(
		url,
		params,
		...
	)
	
	/* Expose curl for more complicated use-cases */
	curl(
		...
	)
	
	/* Execute a command with arguments */
	command(
		path,
		arguments
		...
	)

	/* Create or override a file with content */
	save(
		content,
		file
	)
}
```

Let's take mermaid.js as an example of how this could look like in practice:

A simple typst Mermaid-Library:
```
#let generate(code, file) = {
	async {
		let diagram = command('mermaid', code)
		save(file, diagram)
	}
}
```

The folder would also contain mermaid binaries for linux, mac, windows and/or wasm.

Document:
```
#import "library/mermaid/mermaid.typ"

#let diagram = [
graph TD;
      A-->B;
      A-->C;
      B-->D;
      C-->D;
]

#mermaid.generate(diagram, 'images/diagram.svg')

#image("images/diagram.svg", width: 80%)
```

There are probably better ways to approach this, but after thinking about it for a day, I would like to know what others would think of such an approach.

**Comment by victor-sm** [comment]
@4cq2 I agree that this is a very broad issue, but I think they are in principle linked. The only reason for an async-block are command-execution or web requests, and I don't see how those could be implemented without some kind of special execution if the basic design principles are not to be broken. This is just my proposal for how the special execution could work.

**Comment by Dherse** [comment]
A bit of a SPAM as I already posted this exact answer on another issue, but I feel like re-iterating:

I am just here to comment regarding the idea of a `--shell-escape` flag. (please don't). There are three main reasons why that is not desirable:

1. it would be a giant security hole (especially once the package manager arrives)
2. it would lead to non-deterministic rendering (different version of **external** CLI tools producing different outputs)
3. it would lead to a fracturing of the ecosystem between windows, linux and macos (I can't wait to have to do `if platform() == "windows"` in my **text** document)

Additionally, as previously mentioned, Typst does not **need** to be a generic language, if features that cannot be created using the default language exist (which they probably do), I believe that there should be a plugin API (most likely using WASM as it is a decent encapsulation of third party code with near-native performance). It fixes all of the aforementioned issues.

Additionally, looking at the tectonic project, they did not want to add a `--shell-escape` flag until the community was really bullying them into doing so. I think that the LaTeX ecosystem would be better without this feature, and I strongly believe that, in the long term, this will be better for the Typst ecosystem as well.

**Comment by laurmaedje** [comment]
We can have more focused issues for separate things, but this is indeed overly broad.
