### ISSUE TITLE
Create links to local files

### ISSUE THREAD

**Issue by ede1998** [typst/typst#2695]
### Description

I tried to include a video in my `typst` presentation (based on the [polylux package](https://github.com/andreasKroepelin/polylux)). I found out that this isn't supported (yet?) in #955.

So I tried to settle for a link to the local file instead but I couldn't get it to work. In the output pdf, there is no link
```typst
#link("https://www.google.de")[This works]

#link("file://demo.mp4")[This does not work]
#link("file:///demo.mp4")[This does not work]
#link("./demo.mp4")[This does not work]
```

### Use Case

I want to quickly open a local file from the generated pdf. For instance, when creating a presentation and I want to show a video or demonstrate something, I want to have a clickable link in the pdf that opens the linked file with the default program for its type, e.g. video player for video, folder explorer for folders.

**Comment by gfpj** [comment]
Here is a possible LaTeX code for this:

```latex
\pdfcompresslevel=0
\pdfobjcompresslevel=0


\documentclass{article}
\usepackage{hyperref}
\begin{document}
\href{run:demo.mp4}{This does work}
\end{document}
```

[test.pdf](https://github.com/typst/typst/files/13369242/test.pdf)

**Comment by bastienvoirin** [comment]
This feature would be awesome on its own, but even more so in conjunction with [HTML export](https://github.com/typst/typst/issues/721), in particular for Typst's integration into note-taking apps https://github.com/typst/typst/issues/114#issuecomment-1480360355 which rely heavily on internal/local links to create a network of notes. But then it would be preferable not to achieve such links using embedding/self-contained attachments to avoid overly redundant data storage and exponential file sizes.

If it is possible to implement local links this way, I find that

```typst
#link("./filename.ext")[...]
```

feels more "natural" on the scale of user-friendliness and makes it easier to specify both absolute (`filename.ext`) and relative (`./filename.ext`) paths.

**Comment by Atreyu-94** [comment]
Great! I got it with your syntax, this really saves a lot of time! I didn't think they had it included.
```typst
#link("img/image.gif")[press here]
```
Should this issue be closed?

**Comment by Atreyu-94** [comment]
I tried to try leaving the image nested within the link, so that what I had to click on was the image. It worked perfectly and was also very intuitive.

```typst
#link("img/anim_fps15.gif")[
#figure(
    image("img/anim_fps15.gif", width: 100%),
    caption: "Some caption",
  )
]
```
well, this made me very happy :P

**Comment by laurmaedje** [comment]
Interesting that it just works. Typst just forwards the link to the PDF reader, so I guess PDF supports this. It might not have the exact same semantics as paths in Typst, e.g. with absolute paths.

**Comment by Atreyu-94** [comment]
Ok, I got it adding `#image(...)` instead of `image(...)`, sorry :P
```typst
#figure(
    link("img/anim_fps15.gif")[#image("img/anim_fps15.gif", width: 100%)],
    caption: "Some caption",
  )
```

**Comment by ede1998** [comment]
Closing this as it turns out that this already works. Not sure what I did wrong when I tried the first time.

The behavior depends on the pdf viewer I use.

For `okular` all of the following work and seem to open with the default program I configured for the given file type (e.g. VLC for videos, dolphin as file manager, gwenview for images). For `pdfpc`, the video and image also opens but uses some other programs (e.g. mkv for the video) and the folder fails to open for me.

```typst
	#link("./demo.mp4", image("demo_still.png", height:87%))
	#link(".", "Clickable text"))
	#link("/home/user/Pictures/landscapes/jf6uSBC.jpg", "Clickable1"))
```

This does not work it seems as the pdf viewer does not expand the tilde.

```typst
	#link("~/Pictures/landscapes/jf6uSBC.jpg", "Clickable2"))
```
