### ISSUE TITLE
Can't parse toml file with comments inside array

### ISSUE THREAD

**Issue by naps62** [typst/typst#2699]
### Description

The following toml file is valid according the toml-lint.com:

```
items = [
  # comment
  { id = '001', reviewed = true },
  { id = '002', reviewed = true },

  # comment2
  { id = '003', reviewed = true },
  { id = '004', reviewed = true }
]
```

however, when reading this file in a typst file, I get `error: expected expression` unless I remove the comments

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by naps62** [comment]
Update: this apparently works after I restart `typst watch`. so seems to be some issue with the watching/reloading logic itself, instead of the parsing

**Comment by laurmaedje** [comment]
Probably https://github.com/typst/typst/issues/2601 then

**Comment by laurmaedje** [comment]
Watching bugs were fixed in https://github.com/typst/typst/pull/2706. If you can still reproduce this, please reopen.
