### ISSUE TITLE
Force `CitationLabel` in bibliography when using `alphanumeric` citation labels

### ISSUE THREAD

**Issue by jakubriegel** [typst/typst#2707]
### Description

According to Typst [documentation](https://typst.app/docs/reference/meta/bibliography/#parameters-style) in order to use an alphanumerical bibliography style, we need to the style to `alphanumeric`.

In the web app when using the `latest` compiler version (currently `0.9.0`) and `set cite(style: "alphanumeric")`. bibliography is rendered incorrectly:
<img width="196" alt="image" src="https://github.com/typst/typst/assets/32958017/a27e9ff1-fe15-4211-9e13-f58011656a9d">

Using the legacy `set cite(style: "alphanumerical")` leads to `unknown style: alphanumerical` error.

We managed to get this working by setting the compiler version to `0.8.0` and using `set cite(style: "alphanumerical")`:
<img width="196" alt="image" src="https://github.com/typst/typst/assets/32958017/f76934d7-dbe8-4490-a3a1-d054d56dfd3e">

Expected behaviour is to be using the default latest version and the option described in the documentation.

Relates to https://github.com/ls1intum/thesis-template-typst/issues/14.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by danaugrs** [comment]
My use case has also been impacted by this.

Additionally, I've noticed that the new "alphanumeric" style is different and a downgrade from the previous "alphanumerical" one. Some examples:
1. Previously, a multi-author work would be represented by the initials of each author (e.g. `GAL92`) whereas currently it's only represented by the beginning of the last name of the first author (e.g. `Gon92`).
2. Previously, if a work had more than 3 authors, it would be represented by the beginning of the last name of the first author followed by a "+" (e.g. `Bar+87`) whereas now it's represented without the "+" (e.g. `Bar87`).

This new system provides much less information that the previous one and it a general downgrade IMHO.

**Comment by reknih** [comment]
`alphanumeric` is a style that is only valid for use with the `cite` function. (See #2528). The right use would be

```typst
#set cite(style: "alphanumeric")
@item
#bibliography("refs.bib")
```

The current (bad) behavior is that the citation will use the alphanumeric label but then still print the citation number in the bibliography. This issue shall now track printing the citation label in the Bibliography instead.

@danaugrs I have backported the old label-creation behavior.
