### ISSUE TITLE
Update the guide for LaTeX users

### ISSUE THREAD

**Issue by Enivex** [typst/typst#2712]
Parts of https://typst.app/docs/guides/guide-for-latex-users/ are outdated, at the very least the part about "Bibliographies are not customizable." @PgBiel also pointed out that the guide makes no mention of the relationship between `#let` and `\newcommand`.

**Comment by gfpj** [comment]
Also, the part _What limitations does Typst currently have compared to LaTeX?_ misses the most important difference: in LaTeX it is possible to create PDF objects on the user level, which is not possible in Typst. Because of this, the Typst owners decide which PDF functionality gets implemented and which not. For example, it was decided against setting custom metadata. In LaTeX this is possible by using for example `hyperref` or if no package is available by adding the appropriate PDF objects on my own.

**Comment by Enivex** [comment]
> misses the most important difference

I do not think this is functionality that the vast majority of end users are utilizing

**Comment by gfpj** [comment]
There are many open issues that have this issue as underlying problem: if it would be possible, someone would have implemented it as a package for example _Include PDFs as images_ what is listed as a major limitation would work on user level and could get implemented using a package like in LaTeX. But it is correct that the vast majority of end users does not know that this is the underyling problem.

**Comment by Enivex** [comment]
> There are many open issues that have this issue as underlying problem: if it would be possible, someone would have implemented it as a package for example _Include PDFs as images_ what is listed as a major limitation would work on user level and could get implemented using a package like in LaTeX. But it is correct that the vast majority of end users does not know that this is the underyling problem.

It's possible already today to create a plugin for including pdf, but it would work either by converting to svg, or rasterizing. Both of which are imperfect solutions

**Comment by max397574** [comment]
I saw that the part about the bibliographies was already done. I'd like to work on some of the other aspects shown here in the issue.

**Comment by isaacew** [comment]
> > misses the most important difference
> 
> I do not think this is functionality that the vast majority of end users are utilizing.

This is why i use typst. I work for the government and we can’t install applications on our machines. Typst is now the way I work and others in my field/office are starting to work. This is a major reason why we use it.

**Comment by reknih** [comment]
Let me summarize what points were made on the Guide for LaTeX users in this thread:

- The hint about non-customizable bibliographies should be (and is on `main`) removed.
- The relationship between `\renewcommand` and `#let` should be made clearer

Furthermore, @gfpj has noticed that Typst does not expose PDF authoring tools to users, unlike `pdflatex`. We think that this is actually a desirable feature that allows us to target many formats with a single compiler and without the same document compiling differently to PNG and PDF. I am also unaware that a large share of LaTeX users makes use of low-level PDF features directly (i.e. not through a package like `hyperref`). I think that this fact should either not be mentioned at all in the guide or, if we must, be a small side note.

I think that @isaacew was actually a bit confused and meant that Typst comes in a single, small binary, that a user can run without administrator/root access. We could highlight this in the guide and contrast it to the large TeXLive installations with thousands of files and multiple GB.

**Comment by Lslightly** [comment]
Copied from #3085 for convenience( and significance).

My proposal is to 
1. add a independent section in latex user guide for mapping from \textxx(e.g. \textsc) in latex to substitution(smallcaps, which is not obvious) in typst to supplement the guide for latex users.
2.  In [Guide for LaTeX users – Typst Documentation](https://typst.app/docs/guides/guide-for-latex-users/), refer to `pandoc` for conversion from latex to typst when users can't find the mapping in documentation easily. 
3. If there is a web page to 1) convert latex snippets to typst online or 2) look up corresponding typst functions and symbols like what [General Symbols](https://typst.app/docs/reference/symbols/sym/) does, it's better.
