### ISSUE TITLE
Detect when a previously missing file is created in `typst watch`

### ISSUE THREAD

**Issue by laurmaedje** [typst/typst#2714]
### Description

Reproduction: 
- Create a `main.typ` with `#image("a.png")` in it. The compiler complains.
- Create `a.png`. No recompilation is triggered.

There's no recompilation because we can't watch a file with `notify` that doesn't exist yet. If there's some way to get this to work still, it would be nice. Since it's more of a limitation than a bug, I'm marking this as a feature request rather than a bug.

### Use Case

Not having to save `main.typ` to get it to pick up the created file.

**Comment by stevenskevin** [comment]
`notify` can watch directories, so it should be possible to get the notification (among others) by watching the parent directory.

Of course, it's possible that the parent directory doesn't exist yet, either, in which case you'd have to watch _its_ parent directory until _it_ gets created... and this could continue recursively up to the partition root. And if any of those directories get deleted, you'd have to go back up the hierarchy again to wait for them to be recreated.

So I think it's doable, but getting the logic right would be a bit tricky.

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/3371
