### ISSUE TITLE
`\nicefrac`-like fractions

### ISSUE THREAD

**Issue by astrale-sharp** [typst/typst#272]
support for writing fraction like
`$a/(b/c)$` where a b and c have the same size so that it stays easy to read (or even better, control how much it shrinks)

**Comment by matthewelmer** [comment]
If you need a workaround, `$a/(b slash c)$` should do the trick:
![image](https://user-images.githubusercontent.com/26128847/233475032-1da11c20-384e-4839-9628-a3d732da670f.png)
In fact, if this workaround is everything you needed, then perhaps a fraction wiki would suffice!

**Comment by laurmaedje** [comment]
> Should I open a feature request for a proper \nicefrac-like function?

Feel free to.

**Comment by astrale-sharp** [comment]
This is important :relieved:

**Comment by laurmaedje** [comment]
Closing this in favor of https://github.com/typst/typst/issues/917
