### ISSUE TITLE
--open does not work on Windows when its argument contains a space

### ISSUE THREAD

**Issue by deffi** [typst/typst#2724]
From the Windows command line (cmd.exe), this works:

    typst watch --open "c:\bin\SumatraPDF\SumatraPDF.exe" test.typ

This does not work:

    typst watch --open "c:\Program Files\SumatraPDF\SumatraPDF.exe" test.typ

The document is compiled and watched as expected, but instead of SumatraPDF opening, I get an error message about `c:\Program` not being found:

![Error message](https://github.com/typst/typst/assets/470243/fc510286-1291-4ac1-965a-d0967c29107c)

Running `c:\Program Files\SumatraPDF\SumatraPDF.exe` directly from the command line opens SumatraPDF, as expected.

Typst 0.9.0 (7bb4f6df) on Windows 10 22H2

**Comment by deffi** [comment]
As far as I can tell, it works fine on Linux even if there are spaces in the argument.

**Comment by deffi** [comment]
This is a shot in the dark, but I seem to remember that on Windows, the command line arguments are passed as a single string (rather than a list of strings), and the application (rather than the shell) is responsible for interpreting any escapes or quotes.

I have no evidence that this is actually the cause, but Typst (or the argument parsing library it uses) not doing this would be consistent with the observation.

**Comment by xalbd** [comment]
I believe this may have something to do with the [open](https://github.com/Byron/open-rs) crate. 

When using the --open option, this code is executed:

https://github.com/typst/typst/blob/8e5b7fe5c169c5e52d84ca0565576d173bdf7902/crates/typst-cli/src/compile.rs#L244

This eventually sends the app and path strings to this function:
https://github.com/Byron/open-rs/blob/a33caba441354a14bd55a16ad4a5e8bc793819f0/src/windows.rs#L20-L29

Note that `path` is passed through the `wrap_in_quotes` function but `app` is not. The call to `wrap_in_quotes` was added when a similar issue with opening files with spaces in their paths on Windows was addressed earlier here: https://github.com/Byron/open-rs/issues/53 

This behavior seems super similar. I don't have a Windows machine to test on at the moment, but it seems like a stopgap fix could be to wrap the `app` parameter in quotes before passing it into `with_in_background`.

**Comment by xalbd** [comment]
Okay, I fixed the bug present in the `open` package; this issue should be resolved by upgrading to version `5.0.1` instead of `5`. I can make a PR if you'd like, but this should be a very quick fix.
