### ISSUE TITLE
--open does not work with compile one Windows

### ISSUE THREAD

**Issue by deffi** [typst/typst#2725]
From the Windows command line (cmd.exe), this watches the documend and opens the PDF viewer:

    typst.exe watch --open c:\bin\SumatraPDF\SumatraPDF.exe test.typ

This compiles the document, but does not open the PDF viewer:

    typst.exe compile --open c:\bin\SumatraPDF\SumatraPDF.exe test.typ

I don't get any output either.

As far as I can tell, it works fine on Linux.

Typst 0.9.0 (7bb4f6df) on Windows 10 22H2

**Comment by laurmaedje** [comment]
@deffi in case you have a Rust toolchain available, could you confirm that https://github.com/typst/typst/pull/2842 fixes this for you?

**Comment by TheJosefOlsson** [comment]
I found another way to solve the issue which might be better

**Comment by deffi** [comment]
#2842 does indeed fix it.

I wonder, however, how robust the solution (sleeping for 10 milliseconds after opening the PDF viewer) is - I can imagine that it might fail under high load.

**Comment by TheJosefOlsson** [comment]
That is why I opened #2869, since it should be time-invariant, does that PR also solve the issue for you?

**Comment by deffi** [comment]
#2869 works great.
