### ISSUE TITLE
Vertically scaling glyphs should not increase their width

### ISSUE THREAD

**Issue by Leedehai** [typst/typst#2737]
### Description

Hi -

The `lr()` function vertically scales glyphs like `|`,`angle.l`,`angle.r`, `{`, `}` if the content is higher than normal (say, lowercase alphabets). However, when these glyphs are scaled vertically, their width also increase, creating an inconsistent look with normal glyphs.

Especially the `|` glyph.

```
$
{x} { sum_(i=1)^oo integral x_i upright(d)t } \
|x| lr(|sum_(i=1)^oo integral x_i upright(d)t|)
$
```
<img width="219" alt="Screenshot 2023-11-21 at 20 45 37" src="https://github.com/typst/typst/assets/18319900/db68a807-77ae-4ade-a9d0-570d5aa43385">

LaTeX:
```
$$ |x| \left|\sum_{i=1}^\infty \int x_i \mathrm{d}t\right| $$
```
<img width="244" alt="Screenshot 2023-11-21 at 20 54 40" src="https://github.com/typst/typst/assets/18319900/00b3d8a0-c352-403d-950f-7bf0713e004e">

### Reproduction URL

Also mentioned in https://github.com/Leedehai/typst-physics/issues/16.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
This is a font issue and not a typst issue. You could try for instance Stix Two Math.

**Comment by Leedehai** [comment]
Does this mean it'd be better for Typst to use LaTeX's font *by default*? It appears LaTeX's font was designed for a reason.

There's also another issue where the space between the vertical bar and the adjacent characters is too tight.

**Comment by Enivex** [comment]
> For collaborators: does this mean it'd be better for Typst to use LaTeX's font **by default**? It appears LaTeX's font was designed for a reason, and a new font--however similar it is--has rough edges here and there, as demonstrated here.
> 
> There's also another issue (mentioned by Leedehai/typst-physics#16) where the space between the vertical bar and the adjacent characters is too tight. It's probably caused by the font too.

Typst already uses the closest possible thing, New Computer Modern Math, which is based on latin modern, which in turn is an opentype remake of computer modern math.

Though an older version, so maybe you'd be happier if you updated to the most recent version (you can find it on CTAN)
