### ISSUE TITLE
Maybe Need a Changelog.md?

### ISSUE THREAD

**Issue by muse254** [typst/typst#2741]
### Description

I had some difficulty updating a project from v0.4.0 to v0.9.0.
I'm consuming this on a project, I did a `cargo c` to check what's broken. 
A [Changelog](https://keepachangelog.com/en/1.0.0/) will offer better visibility (heads-up) and context to the changes made.

### Use Case

A Changelog will offer better visibility (heads-up) and context to the changes made over each version. Also good for book-keeping.

**Comment by frozolotl** [comment]
You can find a changelog here: https://typst.app/docs/changelog.
