### ISSUE TITLE
alignment "center" example in the align documentation (change example)

### ISSUE THREAD

**Issue by AdiWeit** [typst/typst#2753]
### Description

In the [documentation](https://typst.app/docs/reference/layout/align/)  the image for the example should change to have more vertical space or less text, because it is not clear that "center" is supposed to only center the text horizontally. 

### Use Case

I think the alignment "center + horizon" is especially useful for title pages. Anyways, the way it is now the image seems to indicate that the alignment "center" centers the text horizontally and vertically: 
![grafik](https://github.com/typst/webapp-issues/assets/43521682/8b1ac536-08ab-4de3-895e-f7c5d38a7ed3)
Moreover, the name "center" does not make clear, that it is only centered horizontally.

**Comment by loewenheim** [comment]
Arguably an alternative solution would be to change the example to `center + horizon` (or `center +` something else).

**Comment by utuncel** [comment]
We could add a comment above the set align statement, something like "Top of the page".
