### ISSUE TITLE
Change `footnote.entry` styling within flow

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2765]
### Description

https://typst.app/docs/reference/meta/footnote/#definitions-entry:

![image](https://github.com/typst/typst/assets/37143421/0c129120-6904-497d-8550-9ad5ae629cdf)

```typ
#let title-page = pad[]
#title-page

#show footnote.entry: set text(red)

My footnote listing
#footnote[It's down here]
has red text!
```

![image](https://github.com/typst/typst/assets/37143421/d3d6015e-ebc3-4386-983d-c0389c176984)

![image](https://github.com/typst/typst/assets/37143421/7bfd0828-f6d8-4964-8bcc-6f5cdbf63c86)

The Discord Typst bot gives white result with this:

```typ
#let title-page = pad[] // This still somehow affects the color
// #title-page

#show footnote.entry: set text(red)

My footnote listing
#footnote[It's down here]
has red text!
```

How does `#let title-page = pad[]` or/and `#title-page` nullifies footnote entry styling? You can also just use `#pad[]` instead.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
See here: https://github.com/typst/typst/issues/1348#issuecomment-1566316463

And the note in the docs: 

> Set and show rules for footnote.entry must be defined at the beginning of the document in order to work correctly. See [here](https://github.com/typst/typst/issues/1348#issuecomment-1566316463) for more information.

**Comment by Andrew15-5** [comment]
If `#let title-page = pad[]` doesn't add any content, why is [Discord Typst renders differently](https://discord.com/channels/1054443721975922748/1056574658771681361/1178076566853525650) from my Typst? It should be the same v0.9.0.

And since previous issues are pretty much identical to this one (but for some reason I couldn't find them), is this issue will be closed or is it, at this point, indeed considered a bug and need to be fixed (in the future)?

**Comment by laurmaedje** [comment]
Maybe the Discord bot has some preamble code or something.

I wouldn't say it's a bug, but it's a limitation. We can leave it open.

**Comment by laurmaedje** [comment]
After more consideration, I think there isn't much we can reasonably change here. It would be unclear which styles to use. Consider this:

```typ
Hi, here is some text.

#set text(font: "Helvetica")
#set align(center)
#show footnote.entry: set text(red)

Here is a #footnote[with text].
```

Should the footnote be red? What's the font? Should it be center aligned?

What about this?

```typ
Hi, here is some text.

#set text(font: "Helvetica")
#figure[
  #show footnote.entry: set text(red)
  Here is a #footnote[with text].
]
```

What's the font? Would the figure's centering affect the footnote?

The problem is that there aren't any well-defined styles to use for the footnote except for those that are already active at the page level.

**Comment by Andrew15-5** [comment]
> After more consideration, I think there isn't much we can reasonably change here. It would be unclear which styles to use.

There is only 1 style being added. And it is specifically for the `footnote.entry`. **Clearly** a _footnote entry_ should use a style that is _explicitly_ applied to _it_. It should also be applied to everything with `#set text(red)`, since it is addressed to any text, but this doesn't work either (on the footnote).

You said that it's a [limitation](https://github.com/typst/typst/issues/2765#issuecomment-1826445074) and a [restriction](https://github.com/typst/typst/issues/1348#issuecomment-1566316463), so surely this means that it can be fixed eventually? If not now, then maybe in a year or two.



> Should the footnote be red? What's the font? Should it be center aligned?

Yes. Yes. Assuming footnote can inherit any general rules (if semantically possible), then yes. But I guess if we are going off of the "block of set/show rules won't change output depending on the order of set/show rules", then this might break it. Depends on how you look at it.

> What's the font? Would the figure's centering affect the footnote?

The explicitly specified one. Would be weird, as you didn't say explicitly that stuff must be centered. So, since the footnote will be in a separate place than the figure caption, then the implicit centering of the caption shouldn't affect the footnote. But the line isn't 100% clear.

**Comment by laurmaedje** [comment]
> You said that it's a https://github.com/typst/typst/issues/2765#issuecomment-1826445074 and a https://github.com/typst/typst/issues/1348#issuecomment-1566316463, so surely this means that it can be fixed eventually?

That's why I wrote "After more consideration". I changed my mind.

I attempted applying local styles (basically the styles where the footnote itself is) to footnote entries and it was a disaster. It results in all-over-the-place styling because the footnotes pick up heading styling, centering, etc. I think it does not make any sense. Rather, in my opinion, the footnote should use the page-wide styles, just like the header and footer. 

As a result, the footnote.entry show rule needs to come before the first piece of page content. Otherwise, it isn't uniform across the page and won't become part of the page styles. That's just how it works and I think somehow special-casing just this property would be very inconsistent.

**Comment by Andrew15-5** [comment]
> That's why I wrote "After more consideration". I changed my mind.

This means that this note should be updated as well, it's now (slightly) outdated, more precisely the linked comment:

https://github.com/typst/typst/blob/40fcd97d584fc1dfa6446bc4922d3b1e440e0afd/crates/typst/src/model/footnote.rs#L49-L50

Maybe even the note without any links, just a raw explanation of where you should and shouldn't put the set/show rules.

**Comment by laurmaedje** [comment]
Yeah, thanks for the heads up.
