### ISSUE TITLE
State docs example is (currently) inaccurate

### ISSUE THREAD

**Issue by kg583** [typst/typst#2786]
The [docs example for problems with self-referential state updates](https://typst.app/docs/reference/meta/state/#caution) claims the compiler gives up and displays `4`, which it probably did in the past, but it now gives up and displays `5`.

There is also a tense issue in the line, "This example display 4 because Typst simply gives up after a few attempts."

**Comment by Enivex** [comment]
This is seemingly not an issue anymore, because the description no longer talks about 4.
