### ISSUE TITLE
Unrecognized commands should be treated as text and not fail to compile

### ISSUE THREAD

**Issue by ecstrema** [typst/typst#2787]
### Description

In math mode, when writing for electronics, I very often put units, or have long subscripts.

For example, the output voltage is Vout, V_"out". However, putting these quotes everywhere gets very tedious. I'd rather have unrecognized commands (like `out` in this case) be treated as text. That way, the compiler would be more forgiving and error only for unrecognized variables.

I understand to V_in will still need to be written as V_"in", else i'll get V_ε, but I can accept that.

I guess it's just a limitation of using commands without a command prefix. 

Do you see any other solution? 

### Use Case

```
V_"out" -> V_out
25"kHz" -> 25kHz
250"kg" -> 250kg
1"lb" -> 1lb
V_("GS"_"off") -> V_GS_off
```

**Comment by ecstrema** [comment]
After thinking just a minute, I'm actually worried that commands might appear that change the rendering.

Suppose I always write `V_out` and a new symbol named "out" appears. It would not render the same thing with new versions of typst, so all new symbol PRs would have to be marked as breaking changes.

I guess this should be closed as _by design_, it's just an unfortunate design decision...

**Comment by Dherse** [comment]
I think you should instead consider creating variable that contain the prefixes and postfixes that you need and use those in math mode. Otherwise we may have silent failures which is very undesirable.

**Comment by ecstrema** [comment]
I need too many different words to put them in variables.
