### ISSUE TITLE
image function is upscaling by default

### ISSUE THREAD

**Issue by 1268** [typst/typst#279]
using this image:

https://typst.app/assets/images/bluetj-avatar.jpg

and this markup:

~~~
#let avatar = image("bluetj-avatar.jpg")

#style(styles => {
   measure(avatar, styles).width
})

#avatar
~~~

Typst reports the image is 128pt, but the image now takes the full width of the output, minus margins:

https://github.com/typst/typst/files/11066857/typst.pdf

and it is blurry from being upscaled.

**Comment by 4cq2** [comment]
compare LaTeX with the same image:

~~~tex
\documentclass{article}
\usepackage{graphicx}
\begin{document}
   \includegraphics{bluetj-avatar.jpg}
\end{document}
~~~

result:

https://github.com/typst/typst/files/11066860/latex.pdf

compare HTML with the same image:

~~~tex
<img src="https://typst.app/assets/images/bluetj-avatar.jpg">
~~~

result:

<img src="https://typst.app/assets/images/bluetj-avatar.jpg">

**Comment by 4cq2** [comment]
https://github.com/typst/typst/issues/175

**Comment by 4cq2** [comment]
https://github.com/typst/typst/issues/436

**Comment by 1268** [comment]
.

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/typst/issues/436
