### ISSUE TITLE
Add additional constructs, primarily a `match`, for working with the `Arguments` type

### ISSUE THREAD

**Issue by yaksher** [typst/typst#2790]
### Description

At the moment, it is possible to define functions with arbitrary dynamic dispatch based on call signature by using `..args` and then manually parsing them, but the logic this creates is annoying and complicated. The proposed construct would be something akin to
```
let f(..args) = match args {
    (body) => body,
    (prefix, body) => [[#prefix]: #body],
    (body, extra_emph: false) => if extra_emph { emph(body) } else { body },
}
```
The arms would not need to be exhaustive, with an error akin to calling a function with the wrong number of arguments in the event of no match, and would allow optional named arguments. In this example, the default value `extra_emph` would never be used, since if it's not specified the function would instead match the first branch, so perhaps in cases like this the compiler would require some kind of syntax which asks for a named argument without default (`extra_emph: never` or just `extra_emph:` for example) to make that clearer, or maybe just allow it. `match` would also allow `(..args)` of its own for fallback cases.

Match could perhaps also be extended to working with array and dictionary types.

Another thing which would be useful is some kind of named destructuring with defaults, though I'm not sure what the syntax would be since `let (extra_emph: false) = args` would imply, from dictionaries, that we're binding the field called `extra_emph` to the name `false` in the outer scope.

### Use Case

Lots of functions, including in the standard library, have complicated behavior based on the number of positional arguments. This requires a lot of messy conditional logic based on the number of arguments, etc., where you say the first extra positional argument, if it exists, is this, the second is this, etc. 

It would be nice to be able to easily define these via a clean, declarative match statement.

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/typst/issues/1316
