### ISSUE TITLE
Syntax (sugar?) for flag arguments and arguments with a fixed number of variants

### ISSUE THREAD

**Issue by yaksher** [typst/typst#2791]
### Description

It would be nice to have some way to be able to declare and specify flags, similar to the way command line interfaces use flags without arguments for booleans. 

One implementation option is just as syntax sugar for passing booleans to named arguments so that it doesn't need any new support in `.with`, `set`-rules, or whatever else. One option which feels reasonable is i.e., `fn(..., :arg_name, ...)` for `arg_name: true` (perhaps if `arg_name` is true by default, this would instead give you false). The other possible syntax is `arg_name::`, which leads into the more powerful implementation.

A more powerful implementation, though you'd need to answer how exactly it interacts with `set` rules and `.with`, is to allow function declaration syntax to look something like `let fn(flag: false : true)`. Then, the absence of the flag resolves to `false` and `flag::` resolves to true, but this would also extend to more general `let fn(fmt: x => x : emph)` where `fn(fmt::)` is `fn(fmt: emph)`.

This could even more generally be extended to allowing these variants to be named, e.g., `let fn(style:: (plain: 0, pretty: 1, flamboyant: 2))` and then you would invoke it as `fn(style::plain)` or `fn(style::flamboyant)` instead of passing strings. 

A unified syntax could be that, when a function argument is declared with two colons:
- the expression between the two tokens is the default value, used if the argument isn't specified; if it's absent, the named argument is required. If the expression between the two colons is a single identifier or integer, it specifies a default variant instead (if you want the default value to be an expression that happens to just be a single identifier, you can wrap it in parenthesis)
- the expression following the second colon is interpreted in one of the following ways
    - if it is neither array, nor dictionary, nor arguments, it is the "flag value", i.e., the value accessed by doing `fmt::`
    - if it is an array that is one element long, that element can also be accessed via `arg::` (this case effectively exists to allow "escaping" default arguments of dictionary or array types by wrapping them in another layer, much like if you want to set the value of a state to a function, you would have to do `state.update(_ => func)` instead of `state.update(func)`)
    - if it is an array that is more than one element long, this is either an error or its elements are accessed by doing `fmt::index`
    - if it is a dictionary, you select a variant with `arg::key`
    - if it is arguments, then you can perform either array or dictionary indexing.

Doing `arg::` is only valid if there is only a single variant (i.e., the first two cases) and/or is syntax sugar for `arg::0`.

This allows arguments whose valid values are named or unnamed exhaustive lists. It would probably make sense to forbid normal named argument passing to arguments defined this way (i.e., you must do `arg::variant` and cannot just do `arg:<value of the variant>`)

### Use Case

Flag arguments and arguments with a finite number of variants are generally common. While named boolean arguments work well enough, they are common enough that it could be worth having dedicated syntax for them. Similarly, arguments where variants belong to a short, exhaustive (or potentially, could also allow for non-exhaustive) list are common and while using string names or whatever is viable, it prevents IDE autocompletion and makes it harder to understand the interface then a list of variants.

**Comment by PgBiel** [comment]
I think this would become redundant if `enum`s come to exist in an eventual type rework. That's all you would need to have fixed variants for arguments. And then you could just write

```typ
#let func(a: MyEnum = MyEnum.DefaultVariant) = { ... }
// then
#func(a: MyEnum.Something)
```

I also don't agree that `arg::` or `:arg` would be more readable than `arg: true`.

**Comment by laurmaedje** [comment]
From my experience, this isn't that big of a pain point in practice. The bar for adding new syntax is very high, and I think not met here.
