### ISSUE TITLE
Facilitate working with loops

### ISSUE THREAD

**Issue by victor-sm** [typst/typst#280]
A common use-case when looping is to check the current index or whether the current loop is the first or the last. Twig includes a nice solution to make working with loops easier by making a [loop-variable accessible inside a loop](https://twig.symfony.com/doc/2.x/tags/for.html#the-loop-variable):

| Variable | Description |
| ------------- | ------------- |
| `loop.index`  | The current iteration of the loop. (1 indexed) |
| `loop.index0` | The current iteration of the loop. (0 indexed) |
| `loop.revindex` | The number of iterations from the end of the loop (1 indexed) |
| `loop.revindex0` | The number of iterations from the end of the loop (0 indexed) |
| `loop.first` | True if first iteration|
| `loop.last` | True if last iteration |
| `loop.length` | The number of items in the sequence |

`loop.revindex`, `loop.revindex0`, `loop.last` and `loop.length` would only be accessible inside for-loops.

I think typst could also benefit from something like this. A simple example:

```
#for letter in "this is a sentence." {
  if loop.first {
    upper(letter)
  }
  else {
    letter
  }
}
```

**Comment by 4cq2** [comment]
again yes that would be nice, but the current syntax gets the job done reasonably well, so it seems none of the current suggestions are really justified. also one could argue that the `zip` suggestion is actually *less* readable than anything given so far.

Any of these suggestions carry a maintenance burden, so we should consider that carefully before blindly accepting changes that add complexity to the language and implementation.

**Comment by laurmaedje** [comment]
I would be fine with zip and enumerate as methods on arrays. That way they don't pollute the global scope.

**Comment by laurmaedje** [comment]
We can have a separate issue for array methods, but I'm not in favor of the loop variable.
