### ISSUE TITLE
Suggest treat math mode as text block not code block

### ISSUE THREAD

**Issue by J-F-Liu** [typst/typst#2819]
### Description

Suggest treat math mode as text block not code block, i.e. require prefix functions and variables with hashtags. This has the following advantages:
1. Write `$ax_1$` to get `ax₁`, no longer report unknown variable `ax`, for complex formulas it is inconvinient to put space between each symbols.
2. Support unicode symbols such as `·×÷±≠𝘈𝗔𝘼𝔸𝓐㎝²` like KaTex with the following benefits: ➀The source code is very readable; ➁No need to remember a long list of identifies of operators and symbols.
3. Make the whole typst language more consistent.

### Use Case

Treat math mode as text block, then the following code will directly get expected result.
1. `$ax_1+bx_2+cx_3=0$`
2. `$a·b$`

**Comment by Enter-tainer** [comment]
what does (2) mean? i think they are already supported

**Comment by Enter-tainer** [comment]
for this case, add a space around the dot can make the compiler happy

**Comment by J-F-Liu** [comment]
It is less common to access variables in math formulas, for `mat, sqrt, frac` et cetera prefex with # looks better.

**Comment by Enter-tainer** [comment]
maybe! it depends. also the #-prefix sounds very like the `\` in LaTeX 😂

**Comment by laurmaedje** [comment]
It was a conscious design decision to _not_ require hashes everywhere and it is one of the main differentiators from LaTeX math. The tradeoff is that it needs a few extra spaces, but note that TeX also needs a space between a backslash command and a letter.

Moreover hashes would come with the extra problem that they usually go into full-on code mode, so `$#frac(x^2)$` would be a syntax error and `$#frac[x^2]$` would have x^2 as plain text. While this could of course be changed, this would introduce inconsistency.

Unicode is already supported but in my experience so far most people prefer writing their math in ASCII.

**Comment by YiHui-Liu** [comment]
how to remove the space between $\pi$ and $\eta$? `$pi\eta$` will cause an error.
![image](https://github.com/typst/typst/assets/30190271/878b984c-0efe-483f-9125-0d3a9e179bf4)

**Comment by Enter-tainer** [comment]
I dont see such space `e^(pi eta)`. Also, how is this related to this issue?

<img width="114" alt="image" src="https://github.com/typst/typst/assets/25521218/aa254d91-f1f2-451c-8c6b-cb99e0764829">
