### ISSUE TITLE
[0.10 regression] Setting a figure's supplement to none removes the field

### ISSUE THREAD

**Issue by Zheoni** [typst/typst#2821]
### Description

This `typst` code

```typ
#show figure.caption: it => repr(it)
#figure([], caption: [], supplement: none)
```

In `0.9.0` the `repr` output has the `supplement` field set to `none`, which if I use `it.caption` it displays nothing. However, in the `main` branch and in `0.10 testing` in the web app , the field is missing, which triggers an error and doesn't  compile the document if I use `it.caption`. Having the field set as `none` is better because in the show rule I don't have to check if it's present, just use it and if it's `none`, nothing will be displayed.

I did not find this in the changelog, so I guess it's a regression.

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Dherse** [comment]
I think I know why this happens I'll open a PR real quick.
