### ISSUE TITLE
Syntax sugar for array access

### ISSUE THREAD

**Issue by tingerrr** [typst/typst#2830]
### Description

We can currently access values on dictionaries using `dict.key`, which is essentially sugar for `dict.at("key")`.

I propose to add similar syntax sugar for another fundamental data type, arrays. Arrays in typst are heterogeneous, they can hold whatever type in each value, which makes them more similar to tuples of unknown size. Rust and a few other languages provide the following syntax to access tuple elements: `tuple.0` to access the first element, `tuple.1` to access the second element and so forth.

I think this would fit right in for typst, the syntax has the same benefits and drawbacks as the dictionary key syntax:
- it can only be done "statically", dynamic values still need to use `at`
- it must not be broken up by whitespace in markup to be unambiguous for inline expressions `[#dict.key] != [#dict. key]` => ``[#array.0] != [#array. 0]``
- it can be broken up in code by whitespace (expect newlines) in code similar to method and key accesses `{dict . key}` => `{array . 0}`

It would be a breaking change for the parsing behavior, as `[#var.0]` currently evaluates to `sequence(var, [.0])`, but this should be a rare thing to be seen in markup.

### Use Case

A more consistent interface across dictionaries and arrays, fundamental data types in typst. It would simplify code, especially for cases where indices are known, such as matrix and array operations on fixed dimensions.

This would also play nicely with [my proposal](https://github.com/typst/typst/pull/1503#issuecomment-1837140650) for `?` to reduce error handling boilerplate.

**Comment by Enivex** [comment]
Is this terribly useful if it cannot be used with dynamic values? It would pretty much only be used with 0, 1, and 2, say

**Comment by tingerrr** [comment]
You could argue the same with `dict.key`, I think the numerical use cases, the reduction of function calls and the general consistency across dictionary and arrays is worth it. It has, as far as I can tell, little to no downsides.

**Comment by Enivex** [comment]
> You could argue the same with `dict.key`.
> 
> I think the numerical use cases, the reduction of function calls and the general consistency across dictionary and arrays is worth it. It has, as far as I can tell, little to no downsides.

A dictionary is different, because at is pretty much the only way you interact with it, and they are often used for "custom types" where the keys are fixed and known.

Your examples of array and matrix operations on arrays of a known size would likely still use for loops (unless we're talking 2x2 or 3x3), and then this wouldn't apply anyway.

**Comment by tingerrr** [comment]
> A dictionary is different, because at is pretty much the only way you interact with it, and they are often used for "custom types" where the keys are fixed and known.

This will likely become a rather rare occurrence once custom types are a thing.

> Your examples of array and matrix operations on arrays of a known size would likely still use for loops (unless we're talking 2x2 or 3x3), and then this wouldn't apply anyway.

I still use arrays in cases where I have at most 5ish elements and when I bind them to identifiers I cannot use a loop. Yes, this likely only happens at small dimensions, but the same is true for dictionaries, this only happens for known keys. The consistency is important too, I think it makes for a more well-rounded scripting language.

To me, it always seemed weird that there is no equivalent sugar for it, other than the fact that `array[idx]` doesn't work it feels like arrays are second-class citizens.

I will admit that it doesn't save much typing now, but with a possible fallible field access, this would come in handy a lot more.

**Comment by l0wx** [comment]
Although I'm in favor, I want to draw attention to a caveat with providing a
> […] consistent interface across dictionaries and arrays […]

```typst
#{
    ({},)// array—ASI
    .0// float
}
```
would trigger ASI—unlike its property access & method invocation equivalents.

**Comment by tingerrr** [comment]
Yeah, it's been a long while since I wrote this proposal, and I'm no longer in favor of it. I'm leaving it open for discussion.

**Comment by laurmaedje** [comment]
> Yeah, it's been a long while since I wrote this proposal, and I'm no longer in favor of it.

I'd be curious what changed your opinion.

**Comment by tingerrr** [comment]
Mostly that it does not carry its weight, it introduces ambiguities like those shown above and would only exist for consistency. Pattern matching is better suited for most use cases where one would use this syntax, I think. And the only other motivator for me was fallible member access/none coalescing, which should work for both fields and methods regardless.

**Comment by laurmaedje** [comment]
Okay, thanks for elaborating. I'll close this then.
