### ISSUE TITLE
Support for < and > as math parentheticals.

### ISSUE THREAD

**Issue by isaacew** [typst/typst#2839]
### Description

In LaTeX, when I use < and > in an equation I get a less angular version of these symbols. I generally use them for inner products, but I've seen other uses. Rather than making this a package to import, I feel that it should be available in the base math package to support some for of these for expressing vector math.

Here is the LaTeX Code
```LaTeX
A simple inner product that has code 
\begin{verbatim}
\left< \mathbf{a} , \mathbf{b} \right> 
\end{verbatim}
produces the following Eq.~\ref{eq:innerProd1}:

\begin{equation}
\label{eq:innerProd1}
\left< \mathbf{a} , \mathbf{b} \right>
\end{equation}

When the variables get large, say for example we are doing some form of inner product on vectors 

\begin{verbatim}
    \left< \begin{pmatrix} 
        a_1 \\ a_2 \\ a_3
    \end{pmatrix},
    \begin{pmatrix} 
        b_1 \\ b_2 \\ b_3
    \end{pmatrix} \right>   
\end{verbatim}

The resulting \LaTeX product is shown in Eq.~\ref{eq:innerProd2}:

\begin{equation}
\label{eq:innerProd2}
    \left< \begin{pmatrix}
        a_1 \\ a_2 \\ a_3
    \end{pmatrix},
    \begin{pmatrix}
        b_1 \\ b_2 \\ b_3
    \end{pmatrix} \right> 
\end{equation}

The angular brackets get much larger to match the taller form of the vectors

\end{document}
```

![Screen Shot 2023-12-03 at 7 05 13 AM](https://github.com/typst/typst/assets/30238903/7fb15991-e6b0-4e1b-bbb3-bde22cce858a)

Here is the Typst code:
```Typst
#set math.equation(numbering: "(1)")

A simple inner product that has code 

```
$
< a , b >
$
```
produces the following @innerProd1

$ < a , b > $<innerProd1>

When the variables get large, say for example we are doing some form of inner product on vectors 

```
$
< vec(a_1 \ a_2 \ a_3), vec(b_1, b_2, b_3) >
$
```

The resulting Typst product is shown in @innerProd2

$
< vec(a_1 \ a_2 \ a_3), vec(b_1, b_2, b_3) >
$<innerProd2>

The angular brackets do not scale to match the LaTeX output.
```

![Screen Shot 2023-12-03 at 7 15 30 AM](https://github.com/typst/typst/assets/30238903/e270a46c-0fe8-45fd-9ffa-f32a17389e4c)

### Use Case

This would not require an import to support angular brackets. Right now "(" and ") are supported, but I suggest "<" and ">" be supported as well.

**Comment by Enivex** [comment]
e.g.
```
#let ip(..x) = $lr(angle.l #x.pos().join(",") angle.r)$
$
  ip(vec(a_1,a_2,a_3),vec(b_1, b_2, b_3))
$
```

![image](https://github.com/typst/typst/assets/2191754/56188ebf-1144-4700-ab32-8f921a231ef5)
