### ISSUE TITLE
Weak pagebreak breaks `pagebreak(to: _)`

### ISSUE THREAD

**Issue by lkndl** [typst/typst#2841]
### Description

Similar to https://github.com/typst/typst/issues/2473, combining a `pagebreak(to: ` and a show rule to start chapters on a new page breaks the parity check.

```typst
#set page(paper: "a8", numbering: "1")
#show heading.where(level: 1): it => {
  pagebreak(weak: true)
  it
}

#lorem(20)
#pagebreak(to: "odd")

= Part 1
#lorem(45)

= Part 2
#lorem(20)
```

![2023-12-03_15-34](https://github.com/typst/typst/assets/38729961/3b4db74d-415a-4588-9f4f-8be5a8ad14a0)

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Smaller reproduction without a show rule:
```typ
#lorem(10)
#pagebreak(to: "odd")
#pagebreak(weak: true)
#lorem(10)
```

**Comment by MatejKafka** [comment]
As far as I can tell, the issue is that if there's a strong `pagebreak` followed by a weak `pagebreak`, the weak `pagebreak` seems to override the strong one, which is imo a bug.
