### ISSUE TITLE
Add ability to declare multiple variables on the same line

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2843]
### Description

Similar to Rust:

```rs
fn main() {
    let (a, b, c);
    (a, b, c) = (1, 2, 3);
}
```

I want to be able to declare multiple variables (without explicit initialization) on the same line:

```typ
#{
  let (a, b, c)
  (a, b, c) = (1, 2, 3)
}
```

Right now, there are only 2 alternatives:
- delcare one variable per `let` operator:
  ```typ
  #{
    let a; let b; let c
    (a, b, c) = (1, 2, 3)
  }
  ```
- add initialization to declaration (I found out that Typst implicitly initializes all declared variables with `none`):
  ```typ
  #{
    let (a, b, c) = (none,) * 3 // Similar to [None] * 3 in Python
    (a, b, c) = (1, 2, 3)
  }
  ```

### Use Case

The main use case is to make Typst code (multiple variable declaration) more compact without making it ugly (like the 2 alternatives above). If an `if/else` statement or a loop is used to initialize variables, then you must create variables outside of the `if/else`/loop scope. And here is when the `#let (a, b, c)` syntax come in handy.

**Comment by laurmaedje** [comment]
I'm not convinced that wanting to declare multiple variables without initializing them is common enough to warrant this syntax. Actually, I'm unsure whether it was a good idea to allow `let a` instead of `let a = none` in the first place ...

**Comment by Enivex** [comment]
> I'm not convinced that wanting to declare multiple variables without initializing them is common enough to warrant this syntax. Actually, I'm unsure whether it was a good idea to allow `let a` instead of `let a = none` in the first place ...

I didn't even know until this very moment that you could declare variables without (explicitly) initializing them.

**Comment by Mambouna** [comment]
Correct me if there is a better way but I currently often have to declare variables before assigning them values if the assignment happens in conditionals or loops. If this is not planned, all good. Just wanted to add my use case here in case it comes up again.
