### ISSUE TITLE
An empty `title` example of the `outline` function in the documentation

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2845]
https://typst.app/docs/reference/meta/outline/#parameters-title:

![image](https://github.com/typst/typst/assets/37143421/a0c5d0fc-4cbc-412e-90c4-81aee8d58ac5)

It should either have an example or don't have the "View example" dropdown toggle.

**Comment by laurmaedje** [comment]
> Indeed weird that it shows that.

There's some stray backticks at the bottom there.
