### ISSUE TITLE
Patterns are cut-off at the size parameter

### ISSUE THREAD

**Issue by igidrau** [typst/typst#2848]
### Description

The following code:
```typst
#set page(width: auto, height: auto, margin: 0pt)

#let pat = pattern(size: (10pt, 10pt), line(stroke: 4pt, start: (0%, 0%), end: (100%, 100%)))
#rect(width: 50pt, height: 50pt, fill: pat)
    
#let pat = pattern(size: (10pt, 10pt), {
    place(line(stroke: (thickness: 4pt), start: (0%, 0%), end: (100%, 100%)))
    place(line(stroke: (thickness: 4pt), start: (100%,0%), end: (200%, 100%))) 
    place(line(stroke: (thickness: 4pt), start: (0%,100%), end: (100%, 200%))) 
    place(line(stroke: (thickness: 4pt), start: (-100%,0%), end: (0%, 100%))) 
    place(line(stroke: (thickness: 4pt), start: (0%,-100%), end: (100%, 0%))) 
})
#rect(width: 50pt, height: 50pt, fill: pat)
```
compiles to: 
![test](https://github.com/typst/typst/assets/36123998/effce54d-5c99-4942-8669-891da3f292e4)

It would be better if the first version automatically wrapped-around the pattern's size to avoid having to write the second version.
(@Dherse)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by knuesel** [comment]
Maybe this could be reconsidered?  Oblique lines seem like one of the simplest and most common patterns, and from the doc you'd think this is exactly the kind of thing that `pattern` is meant for. I mean the  [first example](https://typst.app/docs/reference/visualize/pattern/#examples) is this:

```
#let pat = pattern(size: (30pt, 30pt))[
  #place(line(start: (0%, 0%), end: (100%, 100%)))
  #place(line(start: (0%, 100%), end: (100%, 0%)))
]

#rect(fill: pat, width: 100%, height: 60pt, stroke: 1pt)
```

![image](https://github.com/typst/typst/assets/2412819/c241965a-02a6-4fa8-bb95-6f9895320057)

You'd think that removing one of the `#place` calls would give oblique lines but instead:

```
#let pat = pattern(size: (30pt, 30pt))[
  #place(line(start: (0%, 0%), end: (100%, 100%)))
]

#rect(fill: pat, width: 100%, height: 60pt, stroke: 1pt)
```

![image](https://github.com/typst/typst/assets/2412819/dd378c92-903c-4218-a72a-b6a268ea1b27)

Maybe a fix for simple cases would be an option to disable clipping of the pattern cells (but still clipping the complete shape)?

**Comment by knuesel** [comment]
igidrau showed on [discord](https://discord.com/channels/1054443721975922748/1088372909111783525/threads/1250436059221852181) that we can get nice oblique lines with little extra effort:

```
#let pat = pattern(size: (10pt, 10pt))[
  #place(line(start: (100%, 0%), end: (0%, 100%)))
  #place(line(start: (100%, -100%), end: (-100%, 100%)))
  #place(line(start: (200%, 0%), end: (0%, 200%)))
]
```

so it's not a big deal at least for my use case above
