### ISSUE TITLE
Bib: Failed to parse file, where `month` equals `Sep--Oct`

### ISSUE THREAD

**Issue by LasseRosenow** [typst/typst#2849]
### Description

I have the following bibtex file:

```bibtex
@article{asdf,
  author = {Meg},
  title = {{Test}},
  journal   = {Computer Communications},
  volume    = {36},
  year      = {2013},
  month     = {Sep--Oct},
}
```

But it results in the following error:

```
Failed to parse BibLaTeX file (test.bib:1: invalid number)
```

This is caused by the month field:

```bibtex
@article{asdf,
  month     = {Sep--Oct},
}
```

I am using a large bibtex library, that is maintained by a research group of my university.
The problem is, that this library has many entries that write the month like above.
Which causes me not to be able to use typst, except I find all the affected bib entries.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by DerDrodt** [comment]
BibLaTeX does not support month ranges like you have used here, and for bibtex, I cannot find anything about it neither.

What is your expected behavior? What should the output be?

**Comment by LasseRosenow** [comment]
To be honest those bibtex entries are not created by me, nor used by me. If it comes to it I would be fine if typst would just ignore their incorrect month field.

For me personally it is just a problem, because the research group I am working for, is providing a huge bibtex library that I am obligated to use and there are a few entries like this.
These entries are not used by me and probably incorrect, but finding them all and fixing them is to much effort for me personally.

I could have a check later how latex handles these. But I can say that at least it would ignore them since my projects in latex work just fine even when including the bib library.

**Comment by LasseRosenow** [comment]
Apart form this I also want to add that the error message reported by typst is totally useless.

To find what was actually wrong I needed to go through my massive bib file and keep deleting entries until it compiled.

I generally find this to be a problem with typst. Is there any plans to improve the typst error to actually report at the places where the error originate from and by also giving more useful information than this cryptic "line 1 and invalid number" I don't see why there is an invalid number and I also think that is line 1.

**Comment by LasseRosenow** [comment]
Actually when writing my last post I didn't intend to be offensive at all. I am very sorry that this was received differently than intended.

Maybe the terms `totally useless` sound a bit hard, but I think it is exactly what I felt this error message is after I was searching for the problem for a very long time. In the end for me these words felt like they would fit the most.

But that doesn't mean, that I expect typst to give me super perfect error messages etc. especially considering how young this project is.

I only intended to share this information without any further implications.

But I think it is worth mentioning issues if I discover them. Especially since I had this problem on other areas of typst as well. So I am just hoping this is something to be improved in the future.

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/biblatex/issues/47

**Comment by RonaldAJ** [comment]
Just reproduced with the following bibtex:

`@Article{Pineda1997,
  Title                    = {Bang, click, thud, or whack?},
  Author                   = {Pineda, FJ and Cauwenberghs, G and Edwards, RT and Ryals, KT and Steigerwald, DG},
  Journal                  = {JOHNS HOPKINS APL TECHNICAL DIGEST},
  Year                     = {1997},

  Month                    = {APR-JUN},
  Number                   = {2},
  Pages                    = {244-253},
  Volume                   = {18},

  ISSN                     = {0270-5214},
  Owner                    = {elburg},
  Times-cited              = {1},
  Unique-id                = {ISI:A1997WU25900011}
}
`

The use of two months separated by  a '-' is important, with a single string it works as expected.

**Comment by RonaldAJ** [comment]
Using "4-6" instead of "APR-JUN" is not problematic.

**Comment by RonaldAJ** [comment]
@laurmaedje Is this minimal enough to reinvestigate? I found the problem using https://typst.app.

**Comment by RonaldAJ** [comment]
Thanks! I also see now that JabRef calls these fields deprecated. So I guess the best option is to remove them.
