### ISSUE TITLE
`attach` under fraction can have top ovelap with bar

### ISSUE THREAD

**Issue by aDotInTheVoid** [typst/typst#2851]
### Description

With the following code

```
$1/attach(->,t:l,br:c)$
```

it renders as

![image](https://github.com/typst/typst/assets/28781354/6e96cfc7-ce3d-4629-b40e-c6f869b1e126)

but it should render as 

![image](https://github.com/typst/typst/assets/28781354/a7fb5525-33ac-497d-8d83-56713a93a5e1)

### Reproduction URL

https://typst.app/project/rUdKxEETwMNz53lIP-bZQ3

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/2968
