### ISSUE TITLE
Prime symbol broken with Libertinus Math

### ISSUE THREAD

**Issue by schuelermine** [typst/typst#2860]
### Description

The prime symbol seems incorrectly set in superscript when using Libertinus Math.

```typ
#show math.equation: set text(font: "Libertinus Math")

$
f(x) &= x^2 + 1 \
f'(x) &= 2 x
$
```

This happens in both the Web App and the command-line interface.

Web App:
![Screenshot 2023-12-04 at 21-38-53 scratchpad – Typst](https://github.com/typst/typst/assets/48802534/dc8881e4-135e-453a-b714-482ea721be51)

Local:
![Screenshot from 2023-12-04 21-38-27](https://github.com/typst/typst/assets/48802534/dc92967e-0a05-4ba0-b97c-4b5d016d5657)

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by alerque** [comment]
This is probably a font issue not a typesetting engine one. Whether it is a bug or a style choice I'm not actually sure. I'm the maintainer of Libertinus fonts project but was not the original author of the Math companion font. Either way please feel free to file an issue over [here](https://github.com/alerque/libertinus).

**Comment by schuelermine** [comment]
I am fairly sure this is a typst-specific issue. I have recreated this equation in MathML and it looks fine.
![image](https://github.com/typst/typst/assets/48802534/0519f4a0-fa0d-447a-9c46-0a80dfb71e56)

Perhaps this is a version difference?

**Comment by alerque** [comment]
Can you post the MathML version here so I can experiment with this in SILE?

**Comment by schuelermine** [comment]
I made the MathML with MathJax and got the CSS link from MDN/Frédéric Wang
[MathMLLibertinus.txt](https://github.com/typst/typst/files/13560059/MathMLLibertinus.txt)

**Comment by schuelermine** [comment]
However I opened it with a Chromium browser and the same issue appears.
![Screenshot_20231205-133254~2](https://github.com/typst/typst/assets/48802534/bd88a8e6-c6ae-4d3c-b902-141a2db84240)

**Comment by alerque** [comment]
I'm not much of a math expert, but I'm pretty sure that MathML is kindo of borked. In any case I think I got a working example in SILE's math variant syntax (an alternative to having it work on MathML directly). The result is that *Libertinus Math* looks differently there than in Typst. Here are my inputs comparing *STIX Two Math* with *Libertinus Math* in both SILE and Typst:

<summary>
SILE source (<code>prime.sil</code>):
<details>

```sile
\begin[papersize=a7]{document}
\use[module=packages.math]
\set[parameter=math.font.family,value=STIX Two Math]

\begin[mode=display]{math}
	\table[columnalign=right left]{
		f(x) &= x^2 + 1 \\
		f\prime(x) &= 2x
	}
\end{math}

\set[parameter=math.font.family,value=Libertinus Math]
\begin[mode=display]{math}
	\table[columnalign=right left]{
		f(x) &= x^2 + 1 \\
		f\prime(x) &= 2x
	}
\end{math}

\end{document}
```

</details>
</summary>

<summary>
Typst source (<code>main.typ</code>):
<details>

```typst
#set page("a7")

#[
    #show math.equation: set text(font: "STIX Two Math")
    $
        f(x) &= x^2 + 1 \
        f'(x) &= 2 x
    $
]

#[
    #show math.equation: set text(font: "Libertinus Math")
    $
        f(x) &= x^2 + 1 \
        f'(x) &= 2 x
    $
]
```

</details>
</summary>

![20231205_16h53m15s_grim](https://github.com/typst/typst/assets/173595/29db936c-8eb1-4bb0-b465-0b3ce2a4e583)


Using the SILE side of things to check font versions:

```console
$ sile -d versions prime.sil
SILE v0.14.13 (LuaJIT 2.1.1696562864)
<prime.sil> as sil
[1]
Harfbuzz version: 8.3.0
Shapers enabled: graphite2, ot, fallback
ICU support enabled

Fonts used:
/usr/share/fonts/OTF/STIXTwoMath-Regular.otf:0  Version 2.13 b170
/usr/share/fonts/gentium/GentiumPlus-Regular.ttf:0      Version 6.200
/usr/share/fonts/OTF/STIXTwoMath-Regular.otf:0  Version 2.13 b170
/usr/share/fonts/libertinus/LibertinusMath-Regular.otf:0        Version 7.040;RELEASE
/usr/share/fonts/libertinus/LibertinusMath-Regular.otf:0        Version 7.040;RELEASE
```

Presumably the Typst example being compiled locally is also picking up the same fonts from my system. I'm honestly not sure if perhaps it is preferring an embedded version or not. Assuming not, that's an interesting difference that suggests you might be right and this is Typst related and not the font.

**Comment by Enivex** [comment]
Even in SILE it looks smaller than I expect, even if the position is more correct.

**Comment by khaledhosny** [comment]
This usually happens when the `ssty` feature is not applied as appropriate.

**Comment by Zeta611** [comment]
I stumbled upon this issue as I use Libertinus Math as my primary math font (in LaTeX). It worked fine in LaTeX (with unicode-math), but is broke in Typst.

I suspect it's an issue in the typst side because directly using the prime unicode character U+2032 `′` fixes the issue.

Comparing all different variations, only `x prime` and directly using the prime unicode without `^` works:
```typst
$x'$ $x^'$ $x prime$ $x^prime$ $x′$ $x^′$

#show math.equation: set text(font: "Libertinus Math")
$x'$ $x^'$ $x prime$ $x^prime$ $x′$ $x^′$
```

<img width="248" alt="Screenshot 2024-05-19 at 13 17 21" src="https://github.com/typst/typst/assets/9553691/bd986a6f-554a-4854-ade5-cec78ebfa4b1">

**Comment by lumi-a** [comment]
Following @khaledhosny's comment, using
```typst
#show math.equation: set text(font: "Libertinus Math", features: ("ssty",))
```
seems to render primes correctly for me in Typst 0.11.1.

**Comment by Zeta611** [comment]
@lumi-a Well, it now works well for $x'$, but not anymore for $x '$--it is the opposite now.

**Comment by pnkfelix** [comment]
On Polytype, the self-proclaimed "Rosetta stone for typesetting engines", I think this issue is manifesting itself.

The second item in their "Sample Gallery" shows Typst output for:

```
#[
    #show math.equation: set text(font: "Libertinus Math", size: 16pt)
    $
        f(x) &= a' + b'' + c''' \
        f'(x) &= x^2 + 1
    $
]
```

and it really highlights how "bad" the `f'(x)` looks when compared to the rendering for sile and xelatex.

I don't know if the best response is to suggest to Polytype that they use the `"sstty" mentioned above, or if effort should be spent identifying some alternative fix.

But since this seems like it might be presenting Typst in a poor light in a fairly visible website (Polytype was recently featured on hackernews), it might be worth looking into.

**Comment by khaledhosny** [comment]
Looking into the code, it seems that Typst expects `ssty` lookup to be an alternate substitution lookup:
https://github.com/typst/typst/blob/45366c0112ac7a6197cee35f1e180c6a00923e05/crates/typst/src/math/ctx.rs#L60

While in Libertinus Math it is a single substitution lookup. I don’t know why Typst is accessing the raw lookup from ttf_parser, instead of enabling the feature through rustybuzz which should be more bullet-proof.

**Comment by laurmaedje** [comment]
Typst doesn't currently pass single chars in math through rustybuzz and this was patched on top. Maybe we should always go through RB.

**Comment by khaledhosny** [comment]
Yes, I think all text should go through the shaper for consistency.

**Comment by memeplex** [comment]
Related discussion for ConTeXT https://mailman.ntg.nl/archives/list/ntg-context@ntg.nl/thread/274EKUHM5JW3Z7Q25SLIF5OLUND4YRN2/

OTOH in pdflatex and xelatex, with or without newtx, it renders fine. I took a look at libertinus-otf and libertinus-type1 package sources and was unable to find anything ssty related.

I'm not sure whether you're planning switching to Libertinus Math alongside https://github.com/typst/typst/issues/1257 but in that case it would be better to fix this OTB.

**Comment by Enivex** [comment]
> Related discussion for ConTeXT https://mailman.ntg.nl/archives/list/ntg-context@ntg.nl/thread/274EKUHM5JW3Z7Q25SLIF5OLUND4YRN2/
> 
> OTOH in pdflatex and xelatex, with or without newtx, it renders fine. I took a look at libertinus-otf and libertinus-type1 package sources and was unable to find anything ssty related.
> 
> I'm not sure whether you're planning switching to Libertinus Math alongside https://github.com/typst/typst/issues/1257 but in that case it would be better to fix this OTB.
> 

I don't think there's any plan to change the math font.

**Comment by schuelermine** [comment]
![image](https://github.com/user-attachments/assets/16176876-55ba-4d6e-a83a-0de75e47fbc3)

I’m still observing this.

**Comment by mkorje** [comment]
@schuelermine Could you share the Typst code and compiler version you used to produce that image?

**Comment by schuelermine** [comment]
@mkorje
```typ
#show math.equation: set text(font: "Libertinus Math")
$x'$
```
Fresh project created in the Typst web app

**Comment by mkorje** [comment]
@schuelermine The changes that fixed this are currently only on the development version. When the next release is made it will be available. You can, in the web app, change the compiler version to the development version.
