### ISSUE TITLE
Line breaks on raw non-breaking space (U+00A0)

### ISSUE THREAD

**Issue by gyrrhe** [typst/typst#2861]
### Description

The following code has two lines, each with a non-breaking space (Unicode character U+00A0) between the words `cras` and `purus`. In the first line the character is inserted with `str.from-unicode` (`160` is decimal for `A0`) and in the second line the raw character is used.

```typst
Lorem ipsum porttitor neque sociosqu hendrerit neque facilisis quis enim, adipiscing luctus cras#str.from-unicode(160)purus iaculis dolor

Lorem ipsum porttitor neque sociosqu hendrerit neque facilisis quis enim, adipiscing luctus cras purus iaculis dolor
```

Screenshot of the resulting PDF:

![screenshot](https://github.com/typst/typst/assets/152925451/f5b9634a-c7ea-48f1-9690-2d24035ea145)

As you can see, the non-breaking space is honored in the first line but not in the second. To show that the second line indeed has a non-breaking space between `cras` and `purus`, here's a `hexdump` of the typst file (`c2 a0` is UTF-8 for U+00A0):

```
$ hexdump -C test.typ 
00000000  4c 6f 72 65 6d 20 69 70  73 75 6d 20 70 6f 72 74  |Lorem ipsum port|
00000010  74 69 74 6f 72 20 6e 65  71 75 65 20 73 6f 63 69  |titor neque soci|
00000020  6f 73 71 75 20 68 65 6e  64 72 65 72 69 74 20 6e  |osqu hendrerit n|
00000030  65 71 75 65 20 66 61 63  69 6c 69 73 69 73 20 71  |eque facilisis q|
00000040  75 69 73 20 65 6e 69 6d  2c 20 61 64 69 70 69 73  |uis enim, adipis|
00000050  63 69 6e 67 20 6c 75 63  74 75 73 20 63 72 61 73  |cing luctus cras|
00000060  23 73 74 72 2e 66 72 6f  6d 2d 75 6e 69 63 6f 64  |#str.from-unicod|
00000070  65 28 31 36 30 29 70 75  72 75 73 20 69 61 63 75  |e(160)purus iacu|
00000080  6c 69 73 20 64 6f 6c 6f  72 0a 0a 4c 6f 72 65 6d  |lis dolor..Lorem|
00000090  20 69 70 73 75 6d 20 70  6f 72 74 74 69 74 6f 72  | ipsum porttitor|
000000a0  20 6e 65 71 75 65 20 73  6f 63 69 6f 73 71 75 20  | neque sociosqu |
000000b0  68 65 6e 64 72 65 72 69  74 20 6e 65 71 75 65 20  |hendrerit neque |
000000c0  66 61 63 69 6c 69 73 69  73 20 71 75 69 73 20 65  |facilisis quis e|
000000d0  6e 69 6d 2c 20 61 64 69  70 69 73 63 69 6e 67 20  |nim, adipiscing |
000000e0  6c 75 63 74 75 73 20 63  72 61 73 c2 a0 70 75 72  |luctus cras..pur|
000000f0  75 73 20 69 61 63 75 6c  69 73 20 64 6f 6c 6f 72  |us iaculis dolor|
00000100  0a                                                |.|
00000101
```

I'm using typst 0.9. Is there something I'm missing here? Thanks!

### Operating system

Linux

### Typst version

- [x] I am using the latest version of Typst

**Comment by Enivex** [comment]
I'm pretty sure this is intentional. Raw whitespace is just whitespace in typst, regardless of its flavor. The easiest way to get non-breaking space is with `~`.

**Comment by gyrrhe** [comment]
Ah, I had missed this issue, I didn't search with the right keywords. I don't write my typst files directly, I use an automated process that outputs raw non-breaking spaces, which is why it's actually not easier in my case to use `~`; but my case is certainly an edge case. Feel free to close if this behavior is indeed intentional, thanks for your answer!

**Comment by Enivex** [comment]
> an automatic conversion process from Markdown to typst outputs them around French punctuation.

Pandoc?

**Comment by gyrrhe** [comment]
Not pandoc; the converter isn't public (sorry!), which is why I didn't mention a name. To be clear, I will just modify the converter's behavior, I have a solution for my case. But I do think it is slightly weird for typst to have different behavior between a raw U+00A0 character and the same character inserted using `str.from-unicode`. Ideally, this behavior should probably be mentioned somewhere in the documentation?

**Comment by gyrrhe** [comment]
To give a more realistic workflow where this could be an issue: web pages, for example, often use U+00A0 characters around French punctuation. Someone could copy text from such a web page to a typst file expecting such characters to be honored (just as I expected it). But again, you might consider this an edge case and not worth supporting, which is perfectly fine.

**Comment by MDLC01** [comment]
I think the compiler should issue a warning whenever a non-regular space, such as a non-breaking space, is encountered, indicating that all whitespace is treated the same. Although maybe this would be too obscure for users copying text containing NBSPs without knowing what they are.

> Someone could copy text from such a web page to a typst file expecting such characters to be honored (just as I expected it).

I think the line breaking algorithm already prevents punctuation marks at the beginning of new lines without having to use non-breaking characters.

**Comment by gyrrhe** [comment]
> I think the line breaking algorithm already prevents punctuation marks at the beginning of new lines without having to use non-breaking characters.

In my real-world case, the French punctuation character (preceded by a non-honored non-breaking space) `»` was pushed to the beginning of a new line, so it seems it at least doesn't prevent this specific character from being pushed.

**Comment by laurmaedje** [comment]
My thoughts: https://github.com/typst/typst/issues/3240#issuecomment-1911762308
