### ISSUE TITLE
Add localized documentation

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2862]
Even though [the documentation](https://typst.app/docs/reference) is great for ones that understand English, I feel like it hits hard on the Typst's overall spread throughout the world (adoption). Adding native documentation for many languages will be, I believe, a big step forward in <strike>conquering the world!</strike> making a bigger community.

There are some very popular websites/libraries that make it super easy for anyone to participate in adoption of a new localization language, but I haven't kept track of them. I remember only the ones that are used in programs, but there are probably others that are web-centered (or maybe both!).

Related issue (compiler-specific): #216.

**Comment by Enivex** [comment]
https://github.com/typst/typst/issues/874
