### ISSUE TITLE
invalid number processing in parsing bibtex

### ISSUE THREAD

**Issue by tfjiang** [typst/typst#287]
Hi, I met a problem in pasing a bibtex. The bibtex shows as follows. 

And the typst throw an error " failed to parse biblatex file: invalid number in line 1804". The line 1804 stops at "volume = {314-316}".

![微信图片编辑_20230325132902](https://user-images.githubusercontent.com/1425082/227698292-6ca47b79-2868-4f4f-8ef7-6ebd1b19e4e0.jpg)

It seams the volume is adressed as a number while in bibtex the volume "314-316" is not a number.

**Comment by LYB030** [comment]
same problem . i export it form zotero
