### ISSUE TITLE
Can't disable ligatures font feature (calt)

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#2871]
### Description

I'm using Fira Code v6.2:
````typ
#show raw: set text(font: "Fira Code", ligatures: false)
```typ
=
==
===
====
```
````

Output:

![image](https://github.com/typst/typst/assets/37143421/09bf3652-fc46-4503-bd55-3d75e90f5d2e)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Looks like Fira Code doesn's use any of the normal `liga` (Standard Ligatures), `dlig` (Discretionary Ligatures), `clig` (Contextual Ligatures), `hlig` (Historical Ligatures) OpenType features.

Instead, they use `calt` (Contextual Alternatives) to disable the ligature. This is confirmed by `set text(font: "Fira Code", features: (calt: 0))` working. 

I am not sure why they do this. But I can also confirm that CSS's `font-variant-ligatures: none;` works to disable Fira Code ligatures, so apparently browsers set `calt: 0` for this property. More research is necessary here.

**Comment by Andrew15-5** [comment]
Thanks for the `features: (calt: 0)` trick.

BTW, you can always try to ask the maintainers directly (why they use `calt`): https://github.com/tonsky/FiraCode.

**Comment by Enivex** [comment]
There's some discussion here

https://github.com/tonsky/FiraCode/issues/854

Seems like the main motivation is to have ligatures enabled by default.

**Comment by Andrew15-5** [comment]
I don't know if you can enable them by default other way, but the point **is** to have them enabled from the start. It's pretty much "useless" without ligatures, but it's not like it will break without them.

**Comment by Andrew15-5** [comment]
> More research is necessary here.

Are we still missing something, or is it just a low priority? I can (probably) add calt to the list of features to disable on `text(ligatures: false)`.

**Comment by Enivex** [comment]
> > More research is necessary here.
> 
> Are we still missing something, or is it just a low priority? I can (probably) add calt to the list of features to disable on `text(ligatures: false)`.

I don't see why those should be conflated just because a font does something weird.

Seems like this issue could just be closed to be honest

**Comment by Andrew15-5** [comment]
> I don't see why those should be conflated just because a font does something weird.

Because:

> I can also confirm that CSS's `font-variant-ligatures: none;` works to disable Fira Code ligatures, so apparently browsers set `calt: 0` for this property.

**Comment by Enivex** [comment]
Here's an example where `calt` is used specifically to compensate for `liga` being disabled.

https://typenetwork.com/articles/opentype-at-work-contextual-alternates

I don't know why CSS would tie them together.

**Comment by khaledhosny** [comment]
See https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures. Despite its name it controls both ligatures and contextual alternates (with dedicated settings for each), and `none` seems to disable everything.

**Comment by khaledhosny** [comment]
That is to say, CSS’s `font-variant-ligatures` is not exactly an equivalent to Typst’s `ligatures`.
