### ISSUE TITLE
Pageref in Typst like it exists in LaTeX

### ISSUE THREAD

**Issue by Smightym8** [typst/typst#2873]
### Description

A possibility to get the page number when referencing an image or table would be good. Below is my own implementation that I use in Typst right now. It takes the label text and tries to find the label in the document. If the label is found it determines the page number of the label and formats it as a link to the label. In case the label is not defined it throws an error so it is not possible to compile the document with unresolved references when using pageref. 

```typst
#let pageref(labelText) = {
  locate(loc => {
    let label = label(labelText)
    let elems = query(selector(label), loc)

    if elems.len() == 1 {
      let pageNumber = elems.at(0).location().page()
      link(label, str(pageNumber))
    } else {
      let errorMessage = "Label '" + labelText + "' is not defined"
      panic(errorMessage)
    }
  })
}
```

### Use Case

Sometimes it can be handy to reference the page number in a document for example "As you can see in fig. x on page y".

**Comment by Dherse** [comment]
As I mentioned on Discord, this is already possible with the following code:
```ts
#let pageref(labelText) = {
  locate(loc => {
    let label = label(labelText)
    let elems = query(selector(label), loc)

    if elems.len() == 1 {
      let loc = elems.at(0).location()
      let pageNumber = counter(page).at(loc)
      link(label, numbering(loc.page-numbering(), ..pageNumber))
    } else {
      let errorMessage = "Label '" + labelText + "' is not defined"
      panic(errorMessage)
    }
  })
}
```

**Comment by laurmaedje** [comment]
@Dherse isn't that the exact code shown in OP's post?

**Comment by Dherse** [comment]
> @Dherse isn't that the exact code shown in OP's post?

No, it makes use for `location.page-numbering()` and `counter(page)` instead of `location.page()`

**Comment by laurmaedje** [comment]
Still, from my understanding OP wanted this to be built-in rather than having a problem with the posted implementation.

**Comment by laurmaedje** [comment]
All the pieces are there, but it's not built-in in the sense that you can just do `ref.page(<..>)` or something like that without defining anything yourself.

**Comment by Essiga** [comment]
> But, it **is** built-in, all of the pieces are there 🤔

That's a weird take. Why create any new features at all then? You can just code them yourself, all the pieces are there...
That would mean just create one system that is turing complete, afterwards you don't need to add anything else after all you can just do it yourself, as all the pieces are there.

Adding features like that is just a quality of life improvement and not everyone wanting those features is able to code them by themselves.

**Comment by Dherse** [comment]
> Adding features like that is just a quality of life improvement and not everyone wanting those features is able to code them by themselves.

I agree from the quality of life perspective and it's ongoing with #2886 but not every single feature can be built-in, otherwise what's the point of package and how big will Typst get? My point is that this is (with #2886) a trivial show rule and that perhaps it doesn't need to be built in.

**Comment by Essiga** [comment]
I understand your concerns but I don't think it's an issue with such a small feature. Especially if Typst wants to be a replacement for latex, it makes sense to implement those features as people coming from latex will be missing them. It's really a quality of life thing that will help onboard more people more easily. I see how feature creep can be an issue but I don't see it with this request.

**Comment by JustForFun88** [comment]
> My point is that this is (with #2886) a trivial show rule and that perhaps it doesn't need to be built in.

Of course, you won't be able to add every possible feature, but references to tables, pictures, links, formulas and the page where they are located are really the basic things.

This is needed every time.  Especially in technical documentation, where sometimes it is important to indicate the exact location of a particular table or other things.

**Comment by StarlightScribe** [comment]
> Adding features like that is just a quality of life improvement and not everyone wanting those features is able to code them by themselves.

I agree. If Typst is supposed to be the "simple alternative" to LaTeX, then needing that much code for something simple is a failure. Most of the Typst community right now is engineers and programmers, but that can't be the only audience it appeals to.

**Comment by feuermandel** [comment]
Sorry for asking stupid questions, but

How do I call #pageref?

**Comment by Smightym8** [comment]
@feuermandel Create a file named pageref.typ with the following content:

```typst
#let pageref(labelText) = {
  locate(loc => {
    let label = label(labelText)
    let elems = query(selector(label), loc)

    if elems.len() == 1 {
      let loc = elems.at(0).location()
      let pageNumber = counter(page).at(loc)
      link(label, numbering(loc.page-numbering(), ..pageNumber))
    } else {
      let errorMessage = "Label '" + labelText + "' is not defined"
      panic(errorMessage)
    }
  })
}
```

In the other file where you have your text and want to use pageref you need to import it like this:
```typst
#import "common/pageref.typ": pageref
```

Then you can use it:
```typst
see #pageref("myReference")
```

**Comment by laurmaedje** [comment]
Here is an updated version for 0.11:
```typ
#let pageref(label) = context {
  let loc = locate(label)
  let nums = counter(page).at(loc)
  link(loc, numbering(loc.page-numbering(), ..nums))
}
```

You can use it as
```typ
see #pageref(<myref>)
```
