### ISSUE TITLE
Add an option to write dependencies in Makefile format

### ISSUE THREAD

**Issue by ilyapopov** [typst/typst#2877]
### Description

Add a CLI option to save dependencies in Make format to integrate typst into other build systems.

### Prior art:

- C and C++ compilers have `-M` family of flags (see for [Clang](https://clang.llvm.org/docs/ClangCommandLineReference.html#dependency-file-generation) and for [GCC](https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html))

- [tectonic](https://tectonic-typesetting.github.io/book/latest/v2cli/compile.html) has `--makefile-rules <filename>` flag

- latexmk has `-deps-out=file` flag

- Various latex compilers such as pdftex, xetex, etc have `-recorder` flag (this flag is what latexmk uses internally)

- Make [can read these dependency files](https://www.gnu.org/software/make/manual/html_node/Automatic-Prerequisites.html)

- Ninja [can read](https://ninja-build.org/manual.html#ref_headers) these files too

### Use Case

For scientific documents, I often have a workflow where some parts of the document or figures are automatically generated. Or I have a number of documents, such as a report, a journal paper and a presentation, that have common dependencies and I want to update them then these common parts are changed. I have a Make or [Ninja](https://github.com/ninja-build/ninja/) to automatically run everything that's needed when some of the input files are updated. For this to work, the build system has to know dependencies of each step. You can either specify them manually or rely on the compiler itself to write these dependencies for you.

**Comment by alerque** [comment]
SILE also supports this, see the `-m`/`--makedepsfile` flag. It includes 3rd party packages, fonts, images, and any other resources that might change that should trigger a rebuild.

**Comment by mtoohey31** [comment]
I'd also love to have this feature. If the maintainers would be willing to support this, I'd be happy to implement it.

I've taken a quick look and it doesn't look like it would be too complicated. I'm thinking we just need to run a compilation (but skip the export step) and then we can get the dependency list from `world.dependencies()`, like the watch subcommand does.

**Comment by alerque** [comment]
You don't need to skip the export step. Makefile deps as provided by these sort of dependency trackers are only really meaningful in the context of *updating* (or knowing when to update) an existing build artifact. As such it is expected that you update the full dependency tree *during* the first build. If you don't have them at all you do a build to get them because you know you need at least one anyway. Then in the future if you have them you can decide if you need to rebuild or not. So you don't need to skip the export, you just need an extra option to output the dependencies after a successful render/compile and export.

**Comment by laurmaedje** [comment]
@mtoohey31 I'm open to it. :)

**Comment by mtoohey31** [comment]
Great! I've created https://github.com/typst/typst/pull/3890 which implements this feature as a flag that outputs a rule after an artifact is successfully compiled, as @alerque described.
