### ISSUE TITLE
Documentation: clarify the behavior of the label function

### ISSUE THREAD

**Issue by gyrrhe** [typst/typst#2890]
Currently, the [label docs](https://typst.app/docs/reference/foundations/label) states:

"The preceding element must be in the same scope as the label, which means that `Hello #[<label>]`, for instance, wouldn't work."

The given example, which includes a use of the `label` function to create a label, is:

```typst
#show <a>: set text(blue)
#show label("b"): set text(red)

= Heading <a>
*Strong* #label("b")
```

And the docs also states "This function also has dedicated syntax", implying that the non-dedicated syntax should work. All these elements led me to believe that the following code would work:

```typst
#set heading(numbering: "1.")
= Heading #label("mylabel")
@mylabel
```

...but compiling it with typst 0.10, I get the following error:

```
error: cannot reference text
  ┌─ file.typ:5:0
  │
5 │ @mylabel
  │ ^^^^^^^^
```

I'm guessing that this use of the label function counts as the content not being "in the same scope as the label"? But if so, does it mean that the `label` function itself simply cannot be used to create labels for later referencing through the `ref` or `@` syntax? If this is the case, it probably shouldn't be used in the documentation code example I quoted above. I find the documentation a bit confusing on this.

**Comment by laurmaedje** [comment]
The difference here is syntactical. The `<a>` terminates the heading and thus attaches to the heading. The `#label(..)` is part of the heading and thus attaches to the `text`. Hence, the error message `cannot reference text`.
