### ISSUE TITLE
Cannot colorize big filled square

### ISSUE THREAD

**Issue by Beiri22** [typst/typst#2891]
### Description

I try to colorize symbols:

```
#text(green, sym.square.filled)
#text(green, sym.square.filled.tiny)
#text(green, sym.square.filled.medium)
#text(green, sym.square.filled.big)
```

Only the first one is green, all others are not affected by the color setting. 

### Reproduction URL

None, but I was using typst web.

### Typst version

- [X] I am using the latest version of Typst

**Comment by frozolotl** [comment]
The other squares are actually emoji[^1], which is why they are colored by the font. It seems like the correct behavior, at least when rendering to PNG. The PDF output is wrong, but that is due to Typst's emoji rendering being broken in PDF.

[^1]: http://unicode.org/Public/emoji/1.0/emoji-data.txt

**Comment by mattfbacon** [comment]
On my machine, latest Typst compiler, all the squares are green on both PDF and PNG.

**Comment by frozolotl** [comment]
> On my machine, latest Typst compiler, all the squares are green on both PDF and PNG.
I think that is due to the font Typst is falling back to.

**Comment by emilyyyylime** [comment]
Wouldn't these be text-display versions of the emoji? So then they should be coloured?

**Comment by laurmaedje** [comment]
The three right ones are part of the emoji font, which is contained in the default fallback chain. The first one isn't and falls back to some other font. Overall, without specifying a font, there is nothing that can be done here.

**Comment by Beiri22** [comment]
We may not be able to do something directly; but maybe some hint in the documentation would be useful. Different types of symbols and their characteristics.

btw. Can you specify a font specially for the symbols? What fonts are suggested? How do those fonts treat symbols? Would nicely fit into the docu.

**Comment by laurmaedje** [comment]
There is no clear definition of "symbol". You can write regex show rules to pick specific scripts or characters up and choose a font for them.

**Comment by Beiri22** [comment]
I might mean something different. I mean we could clarify in the docs:
1. what fonts would be recommended for symbols (how complete they are)
2. About the fallback chain
3. Why some symbols might be text color and others not
4. How you could know in advance if the emoji-like symbols in a specific font are colorable or not.

If the above questions are not good, then this is because of my low understanding of the topic. I think that not many users will be experts in this field. So maybe the docs could help to understand and use it properly.

**Comment by laurmaedje** [comment]
Yeah, more docs on this would definitely be nice.

**Comment by laurmaedje** [comment]
You can open an issue for that with your list from above.
