### ISSUE TITLE
Custom shorthand for math symbols in templates

### ISSUE THREAD

**Issue by nikhilweee** [typst/typst#2904]
### Description

Often times it is desired to have a custom shorthand for a symbol which is used very often. For example, I can define `bx` as a shorthand for `bold(x)`. This works fine if I have this definition at the top of the file (or before first use of `bx`)

```typst
#let bx = math.bold("x")
```
However, If I try to define this shorthand in a template, it doesn't work.

```typst
// template.typ
#let project(body) = {
  #let bx = math.bold("x")
}
```

```typst
// main.typ
#import "template.typ": project
#show: project.with()

$ bx $
```

```
message = could not handle source save; err = failed to generate document after compilation;
```

### Use Case

If I have multiple files using the same template it makes sense to define shorthands in the template instead.

**Comment by MDLC01** [comment]
Such shorthand should not be define within your template. Instead, you should have a separate file from which you import `*`, that contains all your shorthands. Mine contains many shorthands, and useful functions I use all the time when writing documents, independently of the template I use.

**Comment by MDLC01** [comment]
I don't know if there is a _recommended_ way, but I feel like this is somewhat common. Similarly to how C programmers tend to have their own "standard library".

**Comment by nikhilweee** [comment]
Okay. If the maintainers suggest that's the way to go then they should feel free to close this issue.

**Comment by laurmaedje** [comment]
You can have them as part of your template, but you must extract them from the `project` function and import them separately (or with a `*` import).

```typ
// template.typ
#let bx = math.bold("x")
#let project(body) = {
  ..
}
```

```typ
// main.typ
#import "template.typ": project, bx // or *
#show: project

$ bx $
```
