### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by s0lst1ce** [typst/typst#292]
Hello.
When making a template I've found myself often using the nice auto-complete feature and mostly just writing what I need in one go, especially when using `#set`.
This however results in hard to read lines where each "block" is hard to distinguish. At the same time manually adjusting everything so that it's easy to read and come to takes time.
Hence I'd love it for typst to have a commands formatter of some sort, much like rustfmt.

**Comment by thecaralice** [comment]
c. [astrale-sharp/typst-fmt](https://github.com/astrale-sharp/typst-fmt)

**Comment by laurmaedje** [comment]
Closing in favor of #1772, which has a bit more detail.
