### ISSUE TITLE
Custom Exports

### ISSUE THREAD

**Issue by remexre** [typst/typst#2929]
### Description

I'd like to be able to produce an extra output file other than the typeset document. For example, maybe some API like:

`main.typ`:
```typst
#let write-example = make-output("example")

#write-example("Hello, world!")
```

```console
$ ls
main.typ
$ typst compile main.typ
$ ls
main.pdf  main.typ
$ rm main.pdf
$ typst compile --map-output example=hello.txt main.typ
$ ls
hello.txt  main.pdf  main.typ
$ cat hello.txt
Hello, world!
```

### Use Case

This would be useful for building a literate programming system on top of Typst. Something this complex (rather than simply extracting all the code blocks and concatenating them) becomes very useful once large enough programs are being written for it to be useful to define the program as a series of chunks that are to be woven together.

**Comment by PgBiel** [comment]
This is very much the purpose of `typst query`: it lets you perform an operation similar to a `query()` in Typst, e.g. you can query for a label, and get the data as JSON or YAML. Combine this with the [`metadata` element](https://typst.app//docs/reference/introspection/metadata), to which you attach a label, and you can basically extract any sort of data from the document as plain text.

For instance, you may add to the document:

```typ
#metadata((some: "thing")) <my-label>
```

And then you can run
```
typst query file.typ <my-label>
```

To obtain something like
```json
{
  "value": {
    "some": "thing"
  }
}
```

**Comment by laurmaedje** [comment]
As explained above, typst query + metadata is the way to go. Typst very intentionally does not allow for any side effects and file writing (there have been plenty of discussions about it, e.g. #1056).
