### ISSUE TITLE
Changing `~` in math mode to be `tilde.op`

### ISSUE THREAD

**Issue by dccsillag** [typst/typst#2935]
### Description

So, first on a personal note: on the math I've been working on, pretty much every time I want to have a tilde in math what I actually want is `tilde.op`. For example:

- Denoting in relation to what that we are taking some expectation: `EE_(X ~ D)[EE_(theta ~ pi)[f_theta (X)]]`
- Denoting a random sample: `X_1, ..., X_n ~^"iid" P`
- A "similarity" equivalence relation: `a ~ b`

I don't think I've ever wanted the plain tilde in my math.

And, in general, I struggle to think of some situation where you'd actually want a plain tilde in your math. Well, I'm sure the logic folks will have used it in _some_ paper, but they'd do that with just about any symbol you provide to them.

Thing is, `~` is somewhat privileged since it is part of ASCII and of many keyboard layouts (at least for the US and ABNT ones, which I'm familiar with. Maybe not others?). So I'd argue that when it appears in math, it should actually refer to `tilde.op`, not `tilde` as it currently does. Moreover, in order to account for people who may not have `~` on their keyboard, `tilde` itself should be remapped to `tilde.op`, with the current `tilde` being named something like `tilde.raw`.

What do you think?

P.S.: as a hack, currently, one can get `~` in meaning `tilde.op` with a show rule: `show "~": $tilde.op$`. I've been adding that to nearly all my documents :sweat_smile:

### Use Case

It's a convenience for making some math easier to typeset and easier to read from source. Examples include:

- Denoting in relation to what that we are taking some expectation.
  - Currently: `EE_(X tilde.op D)[EE_(theta tilde.op pi)[f_theta (X)]]`
  - With the proposed change: `EE_(X ~ D)[EE_(theta ~ pi)[f_theta (X)]]`
- Denoting a random sample.
  - Currently: `X_1, ..., X_n tilde.op^"iid" P`
  - With the proposed change: `X_1, ..., X_n ~^"iid" P`
- A "similarity" equivalence relation using tilde.
  - Currently: `a tilde.op b`
  - With the proposed change: `a ~ b`

**Comment by laurmaedje** [comment]
- The shorthand transformation is similar to what's already happening for `*`. 
- The symbol name is similar to what exists with `dot` and `dot.basic`.

So I guess this seems fine.

**Comment by laurmaedje** [comment]
What's a bit problematic is how `sym` is intended to be generic while it's really mostly used in math. In text, having `#sym.tilde` produce a tilde operator is weird. The same goes for dot I guess, but nobody would write that while somebody _might_ write it for tilde. It's tricky. Maybe it was a mistake to have a generic sym namespace rather than just embracing it's math-y nature.

**Comment by dccsillag** [comment]
> Maybe it was a mistake to have a generic sym namespace rather than just embracing it's math-y nature.

Yep, sure seems like it. Maybev we should have `sym` and `math.sym`, which just "links" to things in `sym`. And, on the webpage listing the symbols, we should probably list both their identifiers on `sym` as well as on `math.sym` (probably with `math.sym` appearing first, since it would be the most common use of the symbols).
