### ISSUE TITLE
Mis-indented first outline entry in the default IEEE template

### ISSUE THREAD

**Issue by DhruvDh** [typst/typst#2940]
### Description

When using `#outline()` to create an index for a document using the default IEEE template, the first outline entry is not indented correctly.

![Screenshot by Dropbox Capture](https://github.com/typst/typst/assets/14926467/12a6c176-5846-4253-9754-c380cca401a8)

Here, the first outline is created with `#outline(indent: false)` and the second with `#outline(indent: true)`

### Reproduction URL

https://typst.app/project/rSHTfH6hRDVZx6I9vXQMON

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Hello, outline(indent: true / false) are deprecated in favor of outline(indent: auto / none). Outline with automatic indent uses the numbering to determine the indentation, which can cause those problems. Can you try to specify a fixed indent instead, e.g. with `outline(indent: 2em)`?

**Comment by DhruvDh** [comment]
![Screenshot by Dropbox Capture](https://github.com/typst/typst/assets/14926467/7776fbdc-c32e-48be-ae34-60cca838cf12)

This screenshot is rendered using -

```
#outline(indent: auto)

= Introduction
Scientific writing is a crucial part of the research process, allowing researchers to share their findings with the wider scientific community. However, the process of typesetting scientific documents can often be a frustrating and time-consuming affair, particularly when using outdated tools such as LaTeX. Despite being over 30 years old, it remains a popular choice for scientific writing due to its power and flexibility. However, it also comes with a steep learning curve, complex syntax, and long compile times, leading to frustration and despair for many researchers. @netwok2020

#outline(indent: 2em)
```
I expected `Introduction` and `Method` entries to be indented equally.

**Comment by PgBiel** [comment]
Thanks for the input. I've identified in the template that it seems that `#set par(..., first-line-indent: 1em)` is set. Can you try moving that option to your document, _after_ the outline is placed?

I believe the problem here is that such option - perhaps a bit inadvertently - affects outline.

**Comment by DhruvDh** [comment]
Thanks, this fixes it. I will close this issue and open one in the templates repository in some time.
