### ISSUE TITLE
Placeholders / parameters via CLI

### ISSUE THREAD

**Issue by Nymuxyzo** [typst/typst#295]
Is it possible to create a template file with variables or placeholders and pass them via CLI into the template to replace them and afterward generate the PDF document?

**Comment by user202729** [comment]
Interesting. This would be in some sense similar to being allowed to access `sys.argv` in Python or `$1 $2 ...` in Bash.

If we want to make Typst scripting language close to a "real" scripting language like Python, allowing this should be good. (TeX also allows "program" to read from "command-line" but in a very cumbersome way)

Also this does not affect immutability/performance etc.

Speaking of which, maybe allow access to environment variable (`os.environ`)/current directory (`os.getcwd`)/current file (`\currfileabspath` in TeX) would be good too.

Maybe only if `--shell-escape` or equivalent is passed.

------

At the moment, none of these are possible, so a workaround is to use `load()` family of functions in Typst then communicate to Typst through files. (admittedly this is ugly)

**Comment by ollelogdahl** [comment]
While this absolutely sounds intresting, Im not sure how much sense it makes at an abstraction level. If you are writing some generic document that you need to typeset with typst, you should probably use `read` for reading an external file. Depending on how you see typst—as a programming language, or a document typesetter—this could either make sense or be nonsensical. We probably need second opinion from a lead though.

**Comment by gwlester** [comment]
**Use Case:** Reporting
It is common for a report's data set to be in a JSON file, e.g. for PO number 123 the file name would be **PO_123.json**.  As it stands right now, the typst report would have a hard-coded **json("/tmp/podata.json")** which would force the copying of **PO_123.json** to **/tmp/podata.json** -- if we could pass in the file name as an argument, then we could have something like: **json(sys.argv.at(1))**

**Comment by gwlester** [comment]
An option would be to allow key-value pairs to be specified on the command line via a --inputs and place them in a dictionary (e.g. CLI_INPUTS).

**Comment by ondohotola** [comment]
Would the [Template Toolkit](http://template-toolkit.org/) be of assistance?

**Comment by gwlester** [comment]
@ondohotola -- my gut says that the [Template Toolkit](http://template-toolkit.org/) is not the correct tool for these use cases.

**Comment by laurmaedje** [comment]
In general, I would like to decouple Typst from the operating system as much as possible. The idea isn't to be a general purpose programming language, after all. That being said, I see how this would be useful and am open to the idea. I think I would prefer if there was only one way to configure the document from the outside though, so either inputs or environment variables. A built-in function `inputs() -> dictionary` seems the most sensible to me.

**Comment by user202729** [comment]
Some comment:

Actually it might have been (is backward-incompatible change possible?) better to redesign <https://typst.app/docs/reference/data-loading/> to have only one function to read plaintext from file, then `csv()` `json()` etc. are used to *parse* the plaintext into structured format.

In retrospect, `read("/dev/stdin")` may actually work for this issue at the moment -- as long as you do `--root /` (might be a security issue as Typst is allowed to read everything in the computer though, see #219). Of course if you try a bit harder there's `read("/proc/self/environ")` but this is a bit of a stretch...

Then in a similar vein, the `image(file path)` could have been `readbytes(file path) -> binary blob` and `image(binary blob | file path)`.
Although practically unless there's some plugin/syscall etc. it's highly unlikely there can be a binary blob for an image anywhere in a Typst program
without reading from a file, but then the same thing can be said for JSON.

**Comment by gwlester** [comment]
@laurmaedje , I like the idea of a built-in function `inputs() -> dictionary`!

**Comment by laurmaedje** [comment]
@user202729 You have good points but this is independent from the inputs question, right? Backwards-incompatible changes are still possible, so feel free to open an issue with a proposal.

**Comment by Dherse** [comment]
I am just here to comment regarding the idea of a `--shell-escape` flag. (please don't). There are three main reasons why that is not desirable:

1. it would be a giant security hole (especially once the package manager arrives)
2. it would lead to non-deterministic rendering (different version of **external** CLI tools producing different outputs)
3. it would lead to a fracturing of the ecosystem between windows, linux and macos (I can't wait to have to do if platform() == "windows" in my text document)

Additionally, as previously mentioned, Typst does not **need** to be a generic language, if features that cannot be created using the default language exist (which they probably) do, I believe that there should be a plugin API (most likely using WASM as it is a decent encapsulation of third party code with near-native performance). It fixes all of the aforementioned issues.

**Comment by user202729** [comment]
what's the difference between your proposal and shell-escape? Someone can just make a plugin that runs shell command, then maybe there will be packages depend on it.

**Comment by user202729** [comment]
@Dherse  I understand some of your points, but not all.

* if plugin is created, there's nothing that prevent the users from writing a plugin that executes shell command. (are there? I'm not sure about this but clearly Rust can execute shell commands right?)
* What's the difference between "external tool" and "standard external tool provided by the Typst team"? In the latter case we get to keep line numbers in error messages.

I'm not ruling out the ideas of plugin API -- sometimes it's more convenient to implement features in Rust, sometimes it's not.

**Comment by Dherse** [comment]
Hello @user202729,

- If the plugin is implemented using WASM (or an **embedded** scripting language like lua or rune), typst will have full control over its interface, meaning that the typst runtime would decide what kind of resources a plugin may access, I would argue that this should *not* include shell access, but it could. The part that is important here is that typst decides, not the plugin/package. This is essentially the full encapsulation of the plugin, something that would not be possible with a python plugin API or a native lib plugin system. WASM also keeps compatibility with the web platform which is good for the monetization of typst and, as a side effect, the longevity of the project
- I am not against standard external tools that feed data into typst, I am against text document querying external resources (shell, networking, etc.). If you want to do something along the lines of: `cat my_file.txt > typst compile main.typ --pass-stdio` or something similar (with the currently non-existing `--pass-stdio` flag) I am all for it. As long as it is **external**, **explicit** and **user controlled**. I don't want to pull a package from the registry that runs python code or whatever on my machine silently in the background.

I agree that there is a convenience factor that is extremely important. The way I envision the future of typst (and note that I am not a creator, just an enthusiastic user), is that typst should be able to do most text editing tasks in a self contained way including some specific tasks such as code highlighting, basic figure creation, graph creation. But, for more niche application, say QR code generation, I would like to see a plugin API that allows doing these things without needing external tools. And especially without my **text document** using the shell in the background without my knowledge.

I hope this clears my views up :)

Have a nice day,

Seb

**Comment by astrale-sharp** [comment]
It is quite easy to make a custom `build system` that just virtually appends a line to your typst file before building it.
```
#let config = (name : "NAME OF MY CLIENT") // APPENDED
#let config = { if config == none {(name : "Bernard Lavilier")} else {config}}
```

**Comment by user202729** [comment]
> It is quite easy to make a custom `build system` that just virtually appends a line to your typst file before building it.
> 
> ```
> #let config = (name : "NAME OF MY CLIENT") // APPENDED
> #let config = { if config == none {(name : "Bernard Lavilier")} else {config}}
> ```

Disadvantages:

* it's ad hoc (if I don't use `mktemp` it's not multithreading-safe, if I do use `mktemp` then I can never remember what's the proper way to clean up temporary file in bash)
* it is flaky (a quote/backslash/newline slip in the argument and the script will break)

But yes, of course you can usually hack your way around things. The question is whether it's a good idea to do that or to improve the tool to support it built-in.

**Comment by ondohotola** [comment]
The Template Toolkit does work very well with typst and a Makefile.

As do include files generated on the fly.

But being able to read environment variables would be a nice feature to have for a simple end user like me

ie something like

```typst
#let DATUM = env(TODAY)
```

when

```bash
TODAY=$(date +%F)
```

or even better

```typst
#let DATUM = system(date +%F)
```

or both of course

Gruss aus dem Süden

**Comment by deffi** [comment]
**Use case**: passing the tag name or SVN revision to a document in a continuous-integration pipeline

Right now, I'm writing the arguments to a temporary JSON file, but that has a number of disadvantages (more details in #2823, a duplicate of this issue).

**Comment by yassine-safraoui** [comment]
The documentation of this feature is here: https://typst.app/docs/reference/foundations/sys/
I spent 20 minutes to find this, I think we really need a separate page for the CLI documentation.
#3765
