### ISSUE TITLE
Table text justification issue

### ISSUE THREAD

**Issue by teisnotte** [typst/typst#2951]
### Description

It seems there is no function to change the table text's justification, and it appears very weird when it's squeezed. Hope for a fix, thanks!
<img width="279" alt="image" src="https://github.com/typst/webapp-issues/assets/112485077/f432169f-aaa3-42dc-9308-fecc9bad44ca">

### Browsers

Chrome

### OS

macOS

**Comment by jakubvlk** [comment]
- [ ] OMn  jemg

**Comment by laurmaedje** [comment]
Have you tried `show table: set par(justify: false)`? This would disable justification in tables.

**Comment by Enivex** [comment]
> Have you tried `show table: set par(justify: false)`? This would disable justification in tables.

Can this not simply be closed? This seems to answer the question

**Comment by teisnotte** [comment]
thanks, it did help!
