### ISSUE TITLE
error messages: suggest field/method with that name exists

### ISSUE THREAD

**Issue by yochem** [typst/typst#2952]
### Description

When a user types uses a field instead of a method, or the other way around, the error message is not very clear:

```
error: content does not contain field "location"
```

It would be great if Typst could provide a hint with the error message. Here are some examples:

```
error: content does not contain field "location". Did you mean to use a method instead of a field?
```

```
error: content does not contain field "location". Did you mean "location()"?
```

```
error: content does not contain field "location". A method with that name exists.
```

```
error: content does not contain field "location" but has method "location()".
```

### Use Case

I often forget which fields are methods or fields. When I encounter this message, I think I either made a typo or I am performing the field lookup on the wrong variable. Debugging would be faster when hints like this are provided.

**Comment by laurmaedje** [comment]
Closed by https://github.com/typst/typst/pull/2977
