### ISSUE TITLE
Infinite united values are represented weirdly (e.g., `infpt`)

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#2955]
### Description

I forgot about this case in #2936, so I'm opening this issue instead of making another small PR that changes a behavior that only rarely happens.

The repr for infinite values with units is weird. For example, an infinite length is represented as `"infpt"`, as illustrated by the following piece of code.

```typ
#set page(width: auto)
#layout(((width, ..)) => repr(width))
```

Similarly, infinity is displayed (or converted to a string using the `str` constructor) as `inf` instead of `∞`.

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Is this really a problem though? I personally prefer `inf` to the equivalent Unicode symbol in this context, so I'd take it as more of a design decision than a problem in itself.

**Comment by MDLC01** [comment]
I prefere the infinity symbol for display / str.

For repr, `inf` is fine, but `infpt` is not. Maybe `(inf)pt` would be better?
