### ISSUE TITLE
"prime" after product is put in the wrong place

### ISSUE THREAD

**Issue by havarddj** [typst/typst#2956]
Writing ` product' ` in typst puts the prime on top of, instead of to the top right of, the product sign.
<img width="184" alt="image" src="https://github.com/typst/typst/assets/96797844/50f01915-0958-47b9-9141-8f2319b24ab5">
The corresponding latex: 
<img width="249" alt="image" src="https://github.com/typst/typst/assets/96797844/469123b2-89c4-48e7-8d55-7087e4d889bf">
Is this intended behaviour or a bug?

**Comment by LaurenzV** [comment]
Seems like a bug I think. This works fine:
`$product'$`

while if you turn it into a block equation, it gets put on the top:
`$ product' $`

**Comment by MDLC01** [comment]
Related to (if not duplicate of) #2070

**Comment by havarddj** [comment]
Oh nevermind, I misremembered how latex works. Apparently behaves the same there! (cf https://tex.stackexchange.com/questions/332256/prime-on-the-product-symbol)
