### ISSUE TITLE
Efficient interator/range support

### ISSUE THREAD

**Issue by freundTech** [typst/typst#2958]
### Description

Currently calling `range()` returns an array, loading all the numbers into memory. However, often `range` calls are just used for a `for` loop, where every number is only needed during it's iteration.

Calling `range()` with a very big number will cause memory usage to spike and might crash the compiler due to running out of memory.

This could be solved much more efficiently with an Iterator.

### Use Case

Doing calculation involving big ranges (such as solving advent of code).

Better performance in general.

**Comment by laurmaedje** [comment]
This was discussed on Discord previously and considered out of scope, at least for the moment. Having an issue for evaluation optimization may be worthwhile, but having many small issues for individual inefficiencies will lead to a bit of issue bloat, I fear.

**Comment by freundTech** [comment]
Is there any known workaround for iterating >> 10.000 times?

Using `range` crashes the web app and takes forever in the local compiler.
Using an index variable and a while loop hits the 10.000 iteration limit, leading typst to think that the loop is infinite.

**Comment by laurmaedje** [comment]
The only way I know of are nested loops.

**Comment by owiecc** [comment]
A `while` loop with an integer iterator. Then you don't allocate.

**Comment by freundTech** [comment]
@owiecc In Typist a while loop can run for at most 10.000 iterations. After that Typist just assumes that the loop never terminates and stops the compilation.

That's why laurmaedje suggested nested loops. By nesting multiple loops you can get iteration counts > 10.000 without allocating an array, but at the cost of code readability and maintainability.

**Comment by laurmaedje** [comment]
Closing this as out-of-scope.
