### ISSUE TITLE
Math equation is not centered 

### ISSUE THREAD

**Issue by teisnotte** [typst/typst#2964]
### Description

When I was typing a math equation, the equation is not centered, and it seems there is no alignment function to center it, but the examples in tutorial are aligned in the center 

$ "Converted 7-DHC_:" 100g "7-DHC" × 0.60 = 60g$ 

<img width="661" alt="image" src="https://github.com/typst/typst/assets/112485077/f670a237-dfc8-402e-be3c-93091aa63e7e">

### Operating system

MacOS, Chrome

- [x] I am using the latest version of Typst

**Comment by Enivex** [comment]
You're missing a whitespace at the end of the equation, so it's inline.

**Comment by teisnotte** [comment]
Oh, that's a little trivial, but I see it now. Thank you!
