### ISSUE TITLE
Indicate raw backticks work in code mode

### ISSUE THREAD

**Issue by ntjess** [typst/typst#2966]
### Description

Coming from https://github.com/jgm/typst-hs/issues/22#issuecomment-1856821278, it would be nice if the docs indicate raw string syntax also works in code mode.

Precedent is set since dedicated label syntax [explicitly mentions](https://typst.app/docs/reference/foundations/label/#syntax) this:
> This works both in markup and code.

### Use Case

Clarifying what external tools are required to support as a typst language feature

**Comment by PgBiel** [comment]
This is mentioned here: https://typst.app/docs/reference/foundations/regex/#constructor-regex

Although an explicit mention in the `raw` page could be useful too.
