### ISSUE TITLE
label and crossref

### ISSUE THREAD

**Issue by lyyc199586** [typst/typst#297]
Is there a way to do labeling and crossref for equations, figures, tables, ... in typst?

For example, in latex to label and ref an equation we have:
```
$a+b=c \label{eq:1}$

From \ref{eq:1} we find ....
```

**Comment by mone27** [comment]
If I get your question correctly this is already supported by Typst with `<label>` instead of `\label{label}` and `@label` instead of `\ref{label}`.
For more info see https://typst.app/docs/reference/meta/ref/
