### ISSUE TITLE
Nested while loops are broken (caching?)

### ISSUE THREAD

**Issue by freundTech** [typst/typst#2972]
### Description

Using nested while loops seems to lead to broken behavior:

This snippet has two nested loops and should obviously print "Hello World" six times, however the inner loop seems to only run once, resulting in only three "Hello World"s
```typst
#{
  let limit = 0
  let limit2 = 0

  while limit2 < 2 {
    while limit < 3 {
      [Hello World#linebreak()]
      limit += 1
    }
    limit2 += 1
  }
}
```

Assigning loops to variables inside loops also doesn't work. y correctly gets set, but x stays none:
```typst
#{
  let limit = 0
  let limit2 = 0

  let x = none
  let y = none
  
  while limit2 < 2 {
    x = while limit < 3 {
      [Hello World#linebreak()]
      limit += 1
    }
    y = [Foobar]
    limit2 += 1
  }

  [x: #x#linebreak()]
  [y: #y#linebreak()]
}
```

Also variables set inside nested loops don't keep their value:
```typst
#{
  let x = 0
  let limit = 0
  let limit2 = 0

  while limit2 < 2 {
    [Before iteration #limit2 X was #x#linebreak()]
    while limit < 3 {
      x += 1
      limit += 1
    }
    [After iteration #limit2 X was #x#linebreak()]
    limit2 += 1
  }
}
```

### Reproduction URL

https://typst.app/project/r0zH7HoFzbOUECn2NZTc4f

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
In your first example, `limit` is not scoped to the outer while loop, so `limit < 3` only holds in the first iteration of the outer loop.

**Comment by freundTech** [comment]
Sorry. Totally overlooked that. Still a bit tired I guess...
That fixes all of them.
