### ISSUE TITLE
SVG background not rendered perfectly (missing lines)

### ISSUE THREAD

**Issue by raylemon** [typst/typst#2988]
### Description

This SVG image is not rendered correctly. Lines is missing
![cover](https://github.com/typst/typst/assets/5302343/47b532d8-95ca-4e6b-91b0-8df88ee55aff)

```
#set page(background : image("cover.svg", format:"svg"))
Test
```

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
```
#set page(background = "cover.svg", format="svg")
```

What is this? Because its not typst

**Comment by raylemon** [comment]
Sorry, I have made a mistake. Please read
```
#set page(background = image("cover.svg", format="svg"))
Test
```

On the web app, svg is rendered perfectly

**Comment by LaurenzV** [comment]
Can reproduce, the reason it doesn't work is because your SVG uses filters, which are currently not supported by us unfortunately. But it's a bug nevertheless.

**Comment by LaurenzV** [comment]
Support for filters should come in the next update.
