### ISSUE TITLE
Support array or loop input to variadic parameters

### ISSUE THREAD

**Issue by vilgotf** [typst/typst#299]
# Issue description

I recently tried to run the following code when designing a titlepage:

```typst
// Real authors array redacted
#let authors = range(1, 10).map(i => "author" + str(i))

#set document(author: authors)

// Does not compile
// #grid(columns: 3, gutter: .25cm, authors)
// columns: 3 is not honored
#grid(columns: 3, gutter: .25cm, for author in #authors {#author})
```

## Expected outcome

I would assume the `columns` parameter to be honored and the code to render a 3x3 grid the authors. I've found the following note in the scripting reference which I guess explains why it does not work:

> Just like blocks, loops join the results from each iteration into one value.

## Workaround

This works, but it's unfortunate to have to list all items.

```typst
#grid(columns: 3, gutter: .25cm, authors.at(0), authors.at(1), authors.at(2), authors.at(3), authors.at(4), authors.at(5), authors.at(6), authors.at(7), authors.at(8))
```

**Comment by laurmaedje** [comment]
You can write `grid(..authors)`
