### ISSUE TITLE
List marker does not respect the locale

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#3000]
### Description

Not all languages use bullets for list markers. For example, French tends to use en dashes.

```typ
#set text(lang: "fr")
- Bonjour,
- au revoir.
```
![The list uses bullets as markers.](https://github.com/typst/typst/assets/57839069/87ee9a60-6c03-4e69-8b6f-d04e76946176)

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Do you have a reference that there are really accepted per-country conventions for this as opposed to personal preference or perceived prevalence?

**Comment by MDLC01** [comment]
For French, some sources seem to indicate that both bullets and dashes are used,[^1][^2] and other only mention dashes.[^3][^4][^5] Babel seems to use am dashes (I'm not familiar with LaTeX, though, so I may be wrong).

[^1]: https://dictionnaire.lerobert.com/guide/enumeration-quelles-sont-les-regles-de-ponctuation (also mentions arrows, for some reason)
[^2]: https://vitrinelinguistique.oqlf.gouv.qc.ca/25108/banque-de-depannage-linguistique/la-ponctuation/enumeration-verticale (for Canadian French)
[^3]: _Lexique des règles typographiques en usage à l'Imprimerie nationale_ (ISBN 978-2-7433-0482-9, not available online)
[^4]: https://fr.wikipedia.org/wiki/Tiret#Tiret_moyen (first example in the linked section)
[^5]: https://www.projet-voltaire.fr/dossier-voltaire/signes-de-ponctuation-francais/#le-tiret-moyen-ou-demi-cadratin ("Le tiret moyen permet de lister les énumérations." means "The en dash is used in lists.", even though the example uses a bullet, likely because this is the default on the web)

**Comment by Omikhleia** [comment]
In addition to @MDLC01 's comment, The _Lexique des règles typographiques en usage à l'Imprimerie nationale_ visibly uses an en-dash (at all levels of an enumeration[^1]); LaTeX (with standard babel french settings) uses an em-dash.

I'm afraid you won't find a definitive "reference for accepted conventions" here, for French at least: some authors of books on typography recommend em-dashes, and others en-dash (with a tendency to recognize the latter as more common _nowadays_ for, at least, enumerations). As far as I can tell, I've never seen the bullet being recommended (though it does pop up sometimes in books, perhaps influenced by the default implementation in most office software)

[^1]: And it also (vaguely) uses an en-dash for dialogs and as internal emphasis. _Le Ramat de la typographie_ would disagree here, however. There's not a single source of truth, except that one should be consistent, it seems.

**Comment by reknih** [comment]
As you indicated above, Le Robert tells us that we may choose amongst multiple glyphs.

> Plusieurs signes peuvent introduire chaque partie d'une énumération

Similarly, the province of Québec allows all common enumeration markers.

> Des puces (rondes, carrées ou autres), des tirets, des chiffres ou des lettres peuvent être utilisés devant chaque point listé.

I do not have access to the _Lexique des règles typographiques en usage à l'Imprimerie nationale._

Wikipedia's _tiret moyen_ article tells us that en dashes are in use for enumerations, my reading of the following, however, does not allow the conclusion that it is used exclusively or even the most desirable list marker.

> Le tiret moyen [...] est utilisé pour lister les énumérations [...]

Same thing for Projet Voltaire:

> Le tiret moyen permet de lister les énumérations.

All of the websites above either use bullets exclusively or show examples with both bullets and various dashes (Québec). I'm aware that web and print typography are distinct things, but this is another indicator that no strong consensus exists.

Additionally, LaTeX defaults to the em dash instead of the en dash in its French setting.

**Comment by MDLC01** [comment]
I agree that there is no clear consensus.[^1]

I think en dashes should be the default in French because they are more commonly seen as "the norm," even though most people don't care and use the their software's default (most commonly, bullets).

I do not expect #3436 to be consensual. I just hope it will be accepted for the aforementioned reason. Anyway, it will make a precedent so that this issue can be closed.

[^1]: Although LaTeX using an em dash is very weird. Em dashes are almost exclusively used in dialogues in French.

**Comment by Omikhleia** [comment]
>  Although LaTeX using an em dash is very weird. Em dashes are almost exclusively used in dialogues in French.

As far as I can tell, the _Lexique_ and other French typography resources are rather confusing on that topic.

I'd sat there's no clear-cut convention here (except the rule of consistency). Most "old" sources recognized one single type of dash, that is basically the em-dash, covering all 3 usages for it in French (dialogue speaker changes, enumerations and incises).

So LaTeX is not very weird here, it uses one of the admitted conventions.

Some sources mention the en-dash for enumerations, and there are even used for incises or dialogues by some publishers...
So the "old way" would probably be to always use em-dashes in all cases, but the "modern tendency" is probably to use en-dashes more and more, in places where the em-dash was formerly employed, but it's not "the norm" in any case.

**Comment by laurmaedje** [comment]
To me it seems like there is no clear norm for French. I am all for respecting established typographic conventions when `set text(lang: _)` is set, but without a clear norm, this change feels too opinionated for me. Some french speakers might be surprised that their lists suddenly do not use the normal markers anymore. If one prefers the dash, it's also very simple to configure. I personally also prefer em-dashes over bullet points and frequently configure them in my documents.

**Comment by MDLC01** [comment]
Then, I'm closing this issue and #3436.
