### ISSUE TITLE
Add a current numbering way of Japanese hiragana and katakana.

### ISSUE THREAD

**Issue by k-84mo10** [typst/typst#3005]
### Description

Hello, I'm Japanese and enjoy using typst. In typst, the numbering function for hiragana and katakana follows the "iroha" order, starting with "い," but this method is outdated. Nowadays, Japanese people use the "aiueo" order, starting with "あ." Therefore, I would like to add the "aiueo" order to the numbering function.

### Use Case

In today's Japan, the "aiueo" order is commonly used, so adding a numbering function in the "aiueo" order would help Japanese people number things in a way that is familiar to us.

**Comment by laurmaedje** [comment]
Fixed by #3012
