### ISSUE TITLE
Allow the reference syntax `@label` to write `@(label)`

### ISSUE THREAD

**Issue by miyaji255** [typst/typst#3010]
### Description

Because of not splitting between words in CJK, I cannot write `@`.

```typst
// ok
before @label after

// bad
前@label後
```

With the function `ref` I can write without spaces, but it requires a lot more typing than `@`. To improve this, I request this syntax.

```typst
前@(label)後
```

### Use Case

You can include a reference `@` in a CJK sentence.

```typst
漢字@(label)漢字
```

**Comment by jocap** [comment]
Technically, this may be fixed by using a backslash escape:

```
前@label\後
```

However, I agree that it is unideal to need a backslash for something so common as a reference, especially in CJK, where words are not separated by spaces. I would suggest adding the possibility to use curly braces for this purpose, as it would mirror what is already supported for code:

```
#code = #{code}
@ref = @{ref}

前#{var}後
前@{label}後
```

Obviously, another solution would be to disallow CJK characters in identifiers, but that is probably even less ideal.

**Comment by ntjess** [comment]
Commenting on the original post, `@(label)` may be confusing syntax. For dicts, you can dynamically set a field name using
```typst
#let field = "a"
((field): "value") // Produces (a: "value")
```

So in keeping with this, my interpretation of `@(label)` would be when you dynamically reference a label:
```typst
#let name = "mylabel"
@(name) // Produces #ref("mylabel")
```

Which may not be that helpful compared to the `#ref(name)` syntax but at least is less obtrusive in prose.

So I would agree with a notation like braces, or at least something that doesn't conflict with the precedent set by `dictionary`

**Comment by miyaji255** [comment]
I thought `@(labelname)` takes only the label name as an argument and produces `#ref(label("labelname"))`. As you say, for consistency, it might be better if `@{labelvariable}` produces `#ref(labelvariable)`.

If `@` takes `labelvariable` as an argument, I would like to see the variable `#let labelname = label("labelname")` defined when defining `<labelname>`.

**Comment by miyaji255** [comment]
I noticed that the following achieve my purpose. I don't know whether I should close this issue, so I leave this issue open.

```typst
前#[@labelName]後
```

**Comment by laurmaedje** [comment]
I think the proposed syntax feels a bit ad-hoc and the solution in the last comment is only one char longer, so I'll close this.
