### ISSUE TITLE
implicit `arguments` makes typst fail silently

### ISSUE THREAD

**Issue by lkndl** [typst/typst#3014]
### Description

Passing something that looks like an `arguments` but without the `arguments(...)` constructor call to a show rule makes typst fail silently. 

```rs
let rule(thing, body) = [thing is #thing \ #body]

// with an "arguments" type
show: rule.with((arguments(box, fill: red),))
// the problematic one:
show: rule.with(((box, fill: red),))
// other cases where it behaves as expected
show: rule.with(["thing"])
show: rule.with(12)
```

When I try to explicitly create one of those things via `#let a = ("bonk", other: 12)`, it panics with "Expected expression, found named pair".

As you might have guessed I'm building a nesting doll with outside styling – does someone have a nicer suggestion?

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by emilyyyylime** [comment]
For me `show: rule.with(((box, fill: red),))` shows up as if an empty array was passed (`()`)
