### ISSUE TITLE
Baseline of ±

### ISSUE THREAD

**Issue by Trebor-Huang** [typst/typst#3016]
### Description

The default font produces
<img width="132" alt="image" src="https://github.com/typst/typst/assets/41145779/ec2723f8-d1c0-425c-a28d-a20feb57525f">
from the code `$±1$`. Compare LaTeX/MathJAX/KaTeX (results basically identical) behavior:
<img width="37" alt="image" src="https://github.com/typst/typst/assets/41145779/a2ed4fce-4655-4f74-95ce-f6269ad2d2e3">
What caused this difference? Is it a bug in rendering or is the font itself having the wrong baseline info?

### Typst version

- [X] I am using the latest version of Typst

**Comment by EpicEricEE** [comment]
LaTeX uses the "Computer Modern" font, whereas Typst uses "New Computer Modern" for math. When using LuaLaTeX with the `newcomputermodern` package, it looks the same as in Typst, so it's not a Typst issue. I suppose it's a feature (and not a bug) in the font, as this way the operators are all aligned:

![image](https://github.com/typst/typst/assets/7191192/ef55a024-990f-4564-9b83-c0200ea1f30d)
