### ISSUE TITLE
Add prenote for cite

### ISSUE THREAD

**Issue by Corbie-42** [typst/typst#3020]
### Description

Add a `prenote` argument to `cite`
```typst
#cite(<distress>, prefix: "see", supplement: "p. 7")
```
optionally, there should be a shorthand notation for that, e.g.:
```typst
@[see]distress[p.~7]
```

### Use Case

In [BibLaTeX (PDF)](https://linorg.usp.br/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf), the cite macro is defined as:
```tex
\cite[<prenote>][<postnote>]{<key>}
```
In Typst, the LaTeX `postnote` is supported as *supplement* of [cite](https://typst.app/docs/reference/model/cite/) :
```typst
@distress[p.~7] // or
#cite(<distress>, supplement: "p. 7")
```

So in the default style, this is compiled to: `[1, p. 7]`

Please also support the `prenote`, so that we can write something like: `[see 1, p. 7]` or `[e.g. 1, p. 7]`.

**Comment by Corbie-42** [comment]
If you manually define the prenote/prefix string, you don't have to handle it. Just write `prefix: "See"`.

**Comment by Enivex** [comment]
I will close this in favor of https://github.com/typst/typst/issues/1139, which concerns the capabilities of cite more broadly.

**Comment by Corbie-42** [comment]
@Enivex since #1139 was closed, because it was too big to be actionable, can we please reopen this issue?

**Comment by FChris** [comment]
Until this is implemented, is there a way to work around this issue by tweaking the normal cite command?

**Comment by sknauff** [comment]
I have found the following workaround to be effective when using the "American Sociological Association" citation style. It's definitely not a replacement for a proper implementation, but it works for me until a proper solution is implemented.

```
#let cnp = (citation) => {
  [​] // U+200B : ZERO WIDTH SPACE [ZWSP]
  set cite(form: "author")
  citation
  [​ ​] // U+200B : ZERO WIDTH SPACE [ZWSP] & U+0020 : SPACE [SP] & U+200B : ZERO WIDTH SPACE [ZWSP]
  set cite(form: "year")
  citation
  [​] // U+200B : ZERO WIDTH SPACE [ZWSP]
}
// When combining multiple #cnp, as seperator use [​;] <- U+200B : ZERO WIDTH SPACE [ZWSP] + semicolon
```

This means I can write the following to have a prenote with a single citation:

```
(prenote, #cnp[@citation])
```

Or a prenote with multiple citations:

```
(prenote, #cnp[@citekey1]​; #cnp[@citekey1]) // As noted above, U+200B : ZERO WIDTH SPACE [ZWSP] is required before the semicolon.
```

Please note that the Unicode space characters are also present in the resulting PDF version.

**Comment by MDLC01** [comment]
Related: https://github.com/typst/typst/issues/2990.

**Comment by padok** [comment]
Its not a replacement for a prenode, but you can use typst CSL support to alter the citation style for one or more intext citations to meet your requirements. Full example at https://github.com/typst/typst/issues/1139#issuecomment-3299540932.

This:

```typst
Some examples:
- @knuth:1984
- #cite_atyp(<knuth:1984>)  // Knuth’s _Literate Programming_ (1984)
- #cite_ayp(<knuth:1984>)  // Knuth’s (1984)
- #cite_ap(<knuth:1984>)   // Knuth’s
- #cite_ay(<knuth:1984>)   // Knuth (1984)
- #cite_a(<knuth:1984>)    // Knuth
- #cite_t(<knuth:1984>)    // _Literate Programming_


#bibliography(bytes(data), style: "apa")
```

produces:
<img width="515" height="286" alt="Image" src="https://github.com/user-attachments/assets/41c0d878-2331-45f2-b42b-b789c00fa087" />

**Comment by trespaul** [comment]
This would also be solved by my proposal in [#2716](https://github.com/typst/typst/issues/2716#issuecomment-3368305757) that citations should be able to render without the enclosing delimiters (parentheses or brackets). Then the user can specify their own delimiters and thus include a pre- and post-note. The shorthand would be

`lorem ipsum (as cited in @label, among others)` → "lorem ipsum (as cited in Author, 2025, among others)".

The long form would be something like

```typst
lorem ipsum (as cited in #cite(<label>, delimited: false), among others)
```

I explain more in my comment on the other issue.

**Comment by kajetan000** [comment]
I cannot stress how important that feature is for more traditional citation styles. It should be simple and easily accessible for people who depend on it.

**Comment by tsteckenborn** [comment]
Any timeline here? What are workarounds others are using?

**Comment by brvn0** [comment]
Hey @tsteckenborn I currently use the following workaround for an internal paper template to insert vgl. (german) or cf. before citations
Beware we use an internal language variable which is probably not there in any of your templates
```typst
// custom cite command for displaying vgl. or cf. before a citation
#let cfcite(label, cf: false, supplement: none, form: "normal", style: auto) = {
  show cite: it => if (cf) [
    #text(citationSeparationCharStart)#if language == "en" [cf.] else [vgl.] 
    #{
      show citationSeparationCharStart: none
      show citationSeparationCharEnd: none
      it
    }#text(citationSeparationCharEnd)
]
else { it }
  cite(label, supplement: supplement, form: form, style: style)
}
```

**Comment by kylekahraman** [comment]
Hey all, I fixed it like this for me:

```typst
#let citepre(key, pre: none) = {
  let c = [#cite(key, form: "author"), #cite(key, form: "year")]
  if pre != none {
    [#pre #c]
  } else {
    c
  }
}
```
