### ISSUE TITLE
Compiled PDF shows garbled images on certain viewers (Adobe)

### ISSUE THREAD

**Issue by adriandelgado** [typst/typst#3024]
### Description

Certain PNG images get corrupted when shown in certain PDF viewers like Adobe Reader. I only have Evince and Okular on my machine which show the images just fine. The way I found this bug is because a client of mine showed me how it looks on his computer.

I'm using the last commit typst-cli on Linux. I managed to reproduce the bug on my machine using the following ghostscript command:
```bash
gs -o main2.pdf -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress main.pdf
```
Attached are one of the PNGs that get corrupted (not every PNG gets corrupted), The `main.pdf` is the Typst output of `#image("my-image.png")` which looks fine on Linux. The `main2.pdf` is the "repaired" PDF that gs produced which look exactly as bad as `main.pdf` looks on Adobe.

Ghostscript shows the following error:
```
Error: ICCbased space /N value does not match the ICC profile.
                 Using the number of channels from the profile.
                 Output may be incorrect.
```

[main2.pdf](https://github.com/typst/typst/files/13731161/main2.pdf)
[main.pdf](https://github.com/typst/typst/files/13731162/main.pdf)
![word-64](https://github.com/typst/typst/assets/11708972/c113fa88-a9da-4034-8f2d-6004311eab96)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by adriandelgado** [comment]
Using `pdftocairo -pdf main.pdf main-repaired.pdf` fixes the PDF on every viewer I tested.

**Comment by LaurenzV** [comment]
Issue seems to be that we always embed the srgb icc profile, even with grayscale image.
