### ISSUE TITLE
[Discussion] Adding support for dates and times

### ISSUE THREAD

**Issue by LaurenzV** [typst/typst#303]
# Introduction

There already is a [PR](https://github.com/typst/typst/pull/211) that adds support for formatting dates in Typst, but as mentioned in the PR it would be great if we could implement this as an actual data type to add support for more advanced operations. I'd like to take a stab at doing this, but before I do that I first want to get the details of how this should look straight, which is why I'm opening this issue. Any input is appreciated! Most of this is heavily inspired by the [time](https://github.com/time-rs/time) crate, since this is what I plan to use under the hood. As far as I've seen this crate also supports wasm bindings, so this shouldn't be any issue for the web app.

# Design

I already tried to think a bit about how this could be implemented and came up with the following:

There will be four new data types (I'm still a bit unsure about this, see the discussion below): 
- `date`: represents a date
- `time`: represents a time (within a date)
- `datetime`: represents a date and a time
- `duration`: represents a duration

## Date

Similarly to how you can create a `color` with the `rgb` and `hsv` function, you can create a `date` with a `date` function:

`date(year: int, month: int, day: int, format: string) -> date`
All arguments of this function are positional, and `year`, `month` and `day` are required. If no format is specified, it will be `YYYY-MM-DD` by default. The `format` attribute is settable.

In addition to that, a `date` has the following methods:

`.display() -> string` (Returns the string representation of a date in the format defined. By default, it's "YYYY-MM-DD"
`.year() -> int` (Returns the year of the date)
`.month() -> int` (Returns the month of the date)
`.day() -> int` (Returns the day of the date)

`.add(duration: duration) -> date` (Returns a new `date` with the duration added.)
`.sub(duration: duration or date) -> date or duration` (If a duration is passed, it returns a new date with the duration subtracted from it. If a date is passed, it returns the difference of the two dates as a duration.)

`.set_year(year: int)` (Sets the year of the date)
`.set_month(month: int)` (Sets the month of the date)
`.set_day(day: int)` (Sets the day of the date)

## Time

Looks exactly the same as `date`, but instead with `hour`, `minute` `second` and `millisecond`. In theory we could also add `microseconds` and `nanoseconds` since it's supported by the crate, but not sure if it's worth it considering that they aren't _that commonly_ needed, at least in my experience

## Datetime
 Same as `date` and `time`, but with its fields combined.

## Duration
A duration is similar to a `timedelta` in Python, i.e. it allows us represents time distances in a quantifiable way. We can create a duration using the `duration` function:
`duration(week: int, day: int, hour: int, minute: int, second: int, millisecond: int) -> date`

All of the arguments are positional and none are required. So if we want to represent a time delta of one minute, we can just do `#duration(minute: 1)`.

# Discussion

So that's a first idea, however, there are still a few points I'm unsure about / not happy with, so I'd love to get some more input. In particular:

- I'm still a bit unsure if the format of the date (same for time and datetime) should be defined in the function to create a date or if it should instead be passed to the `display` method. To me it makes more senes to pass it to the `display` method, because the way I want to format a date shouldn't be tied to the date object itself. On the other hand, the reason I currently store it in the `date` object is that it would allow me to write something like `#set date(format: "DD.MM.YYYY")` which I think is pretty neat and also fits well into how it works for other functions. 
- I don't know if we really should define three different types for dealing with dates, times and datetimes. I think it's kind of much and a bit repetitive. We probably could instead implement just `datetime` and make `year`, `month` etc. optional named arguments, so that it is still possible to store just a time in `datetime`. On the other hand, I do like the explicitness in doing it this way, because I think it does happen often that you want to deal with dates/times/datetimes separately.
- I'm not sure if we really should have separate `set_year`, `set_month` etc. methods or if it could instead be possible to make an `update` method that takes a dict like `(year: 2019, month: 11)` and then updates the date accordingly (same for time and datetime).
- I would like to also add the option to create a date/time/datetime based on a string, but not sure what the best way of adding this is. Does it make sense to create a custom module for dealing with dates and so on and then add a `parse_date`, `parse_time` and `parse_datetime` function?

Any thoughts?

**Comment by GroophyLifefor** [comment]
if this is a Discussion, be sure you share in `Discussion`.
![image](https://user-images.githubusercontent.com/77299279/227731353-8bbc25a7-d3da-461b-a4b7-b25678aebb92.png)

(You can use same explain as markdown.)

**Comment by laurmaedje** [comment]
I think it's fine to discuss in the issue. @LaurenzV setting the format on the date isn't possible because only functions that return content elements can have settable parameters.

**Comment by laurmaedje** [comment]
I haven't read through the full proposal yet, will do so later. Thanks for the detailed write-up already!

**Comment by LaurenzV** [comment]
> I think it's fine to discuss in the issue. @LaurenzV setting the format on the date isn't possible because only functions that return content elements can have settable parameters.

Ahh okay, that's unfortunate, so I guess this wouldn't work then... I'll see if I can come up with something else.

**Comment by LaurenzV** [comment]
Or maybe we could introduce a `format` method that takes an int/float/time/date/datetime and a pattern, and returns a string of the data type formatted? And then you could do something like `#show date: it => format(it, "%Y-%m-%d")`? But this would imply overriding the default string representation of the data types, not sure if that's very clean.

**Comment by laurmaedje** [comment]
The thing is that `show` like `set` can only be applied to content because it depends on the style and content can defer its appearance until styling is resolved. If the format returns a string, this string must be known before styles are resolved, during evaluation. The example below illustrates this a bit. What would you expect `#d`, `#content`, and `#text` to print each time?
```
#let d = date(year: 2023, month: 3, day: 25)
#let content = [#d]
#let text = content.text

#set date(format: "%Y-%m-%d")
#d
#content
#text

#set date(format: "%d-%m")
#d
#content
#text
```

**Comment by LaurenzV** [comment]
Hmm alright, so this probably is not going to work then. 

I guess the best option in this case would still to just go with the `.display(format)` method which returns the string representation of the date? Now that I think about it I think it shouldn't be too bad (if you use the same date in multiple positions you can just store it in a variable), and if you have multiple dates you can just store the pattern in a variable and then do `.display(pattern)` for each date that you use. 

Would be nice if there were an option to set that for all dates, but I guess this is good enough for now. 😄 Unless you have other ideas?

**Comment by user202729** [comment]
Maybe a possible design is to use something like

* built-in function `displaydate(<formatter function>, <date object>) -> [content]` that is used every time a date should be used as/is converted to a content
* method `<date object>.format(<pattern>) -> str`
* then you can `#set displaydate(format: x=>x.format("%Y-%m-%d"))`

**Comment by LaurenzV** [comment]
@SekoiaTree I've already started working on this. 👀 But I haven't created a draft PR yet because some of the details aren't clear yet (see the above-mentioned discussion points) and I'm still experimenting around a bit.

**Comment by SekoiaTree** [comment]
Alright! If you want my two cents:
- a single combined datetime object sounds easier to me
- mutability is fine since you can't mutate external let's
- no idea if this is possible, but couldn't you `#set datetime.display(format:` since that returns content, avoiding a callback setup

**Comment by LaurenzV** [comment]
Awesome, thanks! If it's okay with you I can also message you on Discord if I'm stuck or if I end up not having the time to implement it so that you can keep working on it.

**Comment by SekoiaTree** [comment]
Sure, no problem. I'm Sekoia on discord

**Comment by LaurenzV** [comment]
@SekoiaTree I would let it depend on whatever is set in `text`. So for example if someone sets `#set text(lang: "de")`, the date should use the German version as well.

**Comment by tv42** [comment]
As a non-native speaker of English, I would argue typst files should default to English, that to be easily overridden per-document, and then each document should be able to contain sections with different localization rules[1] (and that should affect all kinds of things, from hyphenation to dates).

[1]: There's plenty of paperwork that has to e.g. mention availability of translations in every legally required language for the country, while the main document is in one language.

**Comment by jdsee** [comment]
Not sure if this is the right place to bring that up but i would really appreciate the possibility to insert the current date/month/year into my documents.

Basically something like [today](https://latexref.xyz/_005ctoday.html) in latex.

**Comment by LaurenzV** [comment]
It's being [worked on](https://github.com/typst/typst/pull/435). :)

**Comment by jdsee** [comment]
@LaurenzV That’s great. Thanks for all your efforts :)

**Comment by jhpratt** [comment]
As the maintainer of `time`, let me know if anything is needed upstream!

**Comment by LaurenzV** [comment]
@jhpratt I actually do have a question! I'm actually mostly done with the PR and the crate seems to have everything we need so far, but in the long term it would be nice if it were possible to somehow provide custom translations (or somehow embed them into `time` itself) for the textual representations of months/weekdays. Do you think this would be feasible, and if so, what the best way to implement this would be?

This is not holding up the PR or something as I think having just the English one is fine for now, but in the future it would be nice if the language could be adapted.

**Comment by jhpratt** [comment]
When I first took over `time` in 2019, there actually was support for a large number of locales for formatting and parsing, but it was decided to remove that prior to the first release under my maintenance. The only effort to my knowledge implementing internationalization on this front is [icu4x](https://github.com/unicode-org/icu4x), which uses [CLDR](https://cldr.unicode.org/) as the backing data (the same thing I used in 2019).

**Comment by LaurenzV** [comment]
I see, thanks! I did take a look at `icu4x`, but it seems like currently it is very limited in the ways you can customize the look of the date (you can only choose between things like long, medium and short, while for Typst I think it's important that you have more control over where each of the components is displayed, which is why I didn't end up using it. So I'll have to think of something else then.

**Comment by jhpratt** [comment]
Providing access to month and weekday names for a given locale would probably suffice as a minimal API in my opinion.

**Comment by laurmaedje** [comment]
Closing as #435 was merged.
