### ISSUE TITLE
Add `calc.is-nan()`

### ISSUE THREAD

**Issue by Mc-Zen** [typst/typst#3035]
### Description

I propose adding a function `is-nan()` to the `calc` module that returns true if the input is a `NaN` value. 

### Use Case

I don't think this function needs to be motivated much since it is used commonly in other languages as well. Here are some applications anyway

- User-defined math functions may want to return `NaN` instead of giving an error when a failure is a valid outcome. 
- `NaN` values are sometimes used for masking (e.g., for plotting to omit certain points)
- ...

**Comment by JamesxX** [comment]
This was added in #3118 it seems
