### ISSUE TITLE
Feature Request: Just warn for malformed biblatex entries

### ISSUE THREAD

**Issue by wrenger** [typst/typst#304]
I have quite large and old biblatex files (multiple thousand lines) that I use for almost all papers.
Fixing all formatting errors to support the stricter hayagriva parser is a longer process.

To make this transition simpler, it would be nice if typst would parse as many entries as possible and just print warnings for all entries that could not be parsed.

This would allow me (and also others) to gradually update their references.

PS: If you need something to test the parser against, check out https://github.com/luhsra/bib/blob/master/sra-ext.bib

**Comment by laurmaedje** [comment]
No warnings for now, but the entries that couldn't be parsed are ignored now.
