### ISSUE TITLE
Primes on symbols lead to misaligned superscripts: they are pushed upward

### ISSUE THREAD

**Issue by Leedehai** [typst/typst#3043]
### Description

**Update (2024-07-02)**: a more obvious example in https://github.com/typst/typst/issues/3043#issuecomment-2201917588.

--- 

Typst:
```typ
$ A A^2 A'^2 A''^2 $
```
<img width="100" src="https://github.com/typst/typst/assets/18319900/9a3a6029-0a70-48ce-8054-c27a229535a6">

LaTeX:
```latex
$$ A A^2 A'^2 A''^2 $$
```
<img width="100" alt="Screenshot 2023-12-21 at 16 29 35" src="https://github.com/typst/typst/assets/18319900/f3acfbac-96a7-4c80-aad0-c900e268095a">

---

The LaTeX version looks better, because math expressions often mix symbols with and without primes, and having the misaligned superscripts up and down along the line looks a bit unpleasant.

Related (at the time of writing):
#539 (fixed): misaligned superscripts with "naked" symbols.
#1672/#2324 (open): accents on symbols lead to misaligned superscripts.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by emilyyyylime** [comment]
Honestly I prefer the Typst output here. It's misaligned but the spacing is much more pleasing

**Comment by max397574** [comment]
I'd prefer the LaTeX way but with a little bit more spacing between the `'` and the `2`

**Comment by jassler** [comment]
I'm having a similar annoyance where the prime symbol is displayed above a mathematical symbol. Specifically, when I use `$R^{\succsim'}$` in LaTeX I get the following.

<img width="117" alt="Correctly rendered prime symbol in LaTeX" src="https://github.com/typst/typst/assets/24298790/5ed88a8b-c19a-4796-8d8c-ffd9990ad761">

Apart from the obvious `$R^(succ.sim')$`, I've tried some variations to get it to render the way I want. Alas, I've not been successful yet.

<img width="209" alt="Examples of small mathematical expressions using the prime symbol in the superscript" src="https://github.com/typst/typst/assets/24298790/4d1d518b-120a-4142-bd30-a048767c173b">

**Comment by Leedehai** [comment]
This issue leads to more unpleasant rendering when there's a square root or a fraction bar
```typ
$ sqrt(f^2) sqrt(f'^2) sqrt(f''^2)  sqrt(f'''''^2) $
$ 1/f^2 1/f'^2 1/f''^2  1/f'''''^2 $
```
<img width="250" alt="Screenshot 2024-07-02 at 00 50 22" src="https://github.com/typst/typst/assets/18319900/2385d2b5-8bdd-47af-95af-a59adf65f40e">
