### ISSUE TITLE
Lazy evaluation for default parameter

### ISSUE THREAD

**Issue by lxl66566** [typst/typst#3052]
### Description

If i use a function on `default` parameter (ex. `content.at(str, default)`), the function will be executed before calling `at()`, even if there is no need to use `default` parameter.
Here's a more concrete example: https://gist.github.com/lxl66566/30e309e696169829524ee04503b526db

### Use Case

I don't know how to implement it. Maybe a closure for `default` or something like `.at(...).default(...)`?
I think lazy evaluation may be good for more complex functions in `default`.

**Comment by laurmaedje** [comment]
I think for Rust this makes a lot of sense, but for Typst it introduces unnecessary complexity. The compiler could try to transparently optimize such cases down the road, but forcing this on the user doesn't feel Typst-y to me.
