### ISSUE TITLE
Documentation of push method

### ISSUE THREAD

**Issue by indicatelovelace** [typst/typst#3056]
Currently the documentation of ```self.push()``` does not state the return type. This let me to believe that it does in fact not return anything and just perform a mutation. This is however not the case as it does return ```none```. This should be added to the documentation as it is an inconsistency.

**Comment by MDLC01** [comment]
Well, this is not specific to the `push` function. Functions always return something in Typst. A function that "does not return anything" does not exist. Such a function would actually return `none`.

**Comment by indicatelovelace** [comment]
Of course this is how functions behave. However this is only implicit, and not documented. The way it is currently I could also assume that push returns the empty content or anything else.
Would it be possible to change the documentation to add a ```-> none``` to those methods? I think this would be more consistent and clear.

**Comment by xkevio** [comment]
I'd argue, adding `-> none` to every method that does that would clutter the documentation and not actually provide valuable insight and could even be more confusing to the end user. Though stating it somewhere at all is certainly a good idea.

**Comment by laurmaedje** [comment]
> I'd argue, adding `-> none` to every method that does that would clutter the documentation and not actually provide valuable insight and could even be more confusing to the end user. Though stating it somewhere at all is certainly a good idea.

Agreed. We should mention it somewhere, but putting it everywhere isn't helpful. Especially since even though `none` is technically returned, the none isn't typically interesting. It's just returned because something has to be returned.

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/4590
