### ISSUE TITLE
Broken spacing when fences match incorrectly (e.g. through linebreaks)

### ISSUE THREAD

**Issue by Ddystopia** [typst/typst#306]
```typ
#text(20pt)[$
  S &-> a T | b S \
  T &-> a T | b U \
  T &-> a T | b U epsilon 
$]
```
Result: 
![image](https://user-images.githubusercontent.com/63151578/227733533-b3c2bad8-06c5-4ec3-9d28-e1a3e74f5916.png)

**Comment by Ddystopia** [comment]
typst-23.03.21.2-1

**Comment by johannes-wolf** [comment]
Maybe related to this issue: "|" also behaves strange when using operators with limits.

```
$
a                &| b \
sum_(n=10)^100 n &| b \
a                &| b \
$
``` 
produces:
![bug](https://user-images.githubusercontent.com/519002/227734116-ee0b6728-519f-448b-84ca-5e9c49748615.png)

whereas:
```
a                &| b \
a                &| b \
sum_(n=10)^100 n &| b \
a                &| b \
```
produces:
![correct](https://user-images.githubusercontent.com/519002/227734117-d64d8068-80fb-45e5-8397-e6c0efd89aff.png)

**Comment by Ddystopia** [comment]
This move solves my issue:
```
#text(20pt)[$
  S &-> a T | b S \
  T &-> a T | b U \
  T &-> a T | b U epsilon 
$]

#text(20pt)[$
  S &-> a T \| b S \
  T &-> a T \| b U \
  T &-> a T \| b U epsilon 
$]
```
![image](https://user-images.githubusercontent.com/63151578/227735481-da5675a9-75ed-4455-809e-c8148c580ec2.png)

But this is still buggy, strange and unpredictable behaviour, so I will not close the issue.

**Comment by Enivex** [comment]
My guess would be that all of these issues are related to Typst interpreting | as a delimiter.

**Comment by Enivex** [comment]
Looking at this in retrospect, an alternative solution should be the same as in https://github.com/typst/typst/issues/1202

The symbol you probably want is not the delimiter "bar" (which is what | gives you), but the binary operator "divides". These have different Unicode code points.
