### ISSUE TITLE
Allow importing with array syntax (like in Python)

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#3065]
### Description

Imagine writing this (ugly and unreadable!):
```typ
#import "/utils.typ": thing1, thing2, something-very-long, stuff1, stuff2, stuff3, and-maybe-something-else, ok-this-is-the-last-one
```

Instead of this (you can't be more readable than this):
```typ
#import "/utils.typ": (
  thing1,
  thing2,
  something-very-long,
  stuff1,
  stuff2,
  stuff3,
  and-maybe-something-else,
  ok-this-is-the-last-one,
)
```

I get that for `= long heading` it isn't great to be able to place heading's content on multiple lines (becomes less readable, but would be nice for very long heading), but for import statement it has become obvious that sometimes import lines are simply too long. Look even at Rust's imports (`use`) — maybe something like that also would work (but it's less understandable, than a simple array-syntax imports).

### Use Case

Remove clutter on import lines and make huge imports more readable and maintainable.

**Comment by emilyyyylime** [comment]
I expected either `\` as a continuation character or just a terminating comma to work as line continuations, but it seems both don't work. +1

**Comment by ntjess** [comment]
It's not ideal, but this does work in the meantime (tested on v0.10):

```typst
#(import "/utils.typ": 
  thing1,
  thing2,
  something-very-long,
  stuff1,
  stuff2,
  stuff3,
  and-maybe-something-else,
  ok-this-is-the-last-one,
)
```

**Comment by Andrew15-5** [comment]
@ntjess, I understand and agree. The main point is to provide an ability/choice to import things differently, in a more convenient and readable way. **Sometime** things that I import should just be global, because their names aren't shadowing anything else and because its reference will be shorter (i.e., `ones` instead of `np.ones`) — shorter is mainly better (fewer chars, less code, more readable, more compact, less file size).

This is just a simple argument, but I hope I got my point across.

**Comment by Andrew15-5** [comment]
> It's not ideal, but this does work in the meantime (tested on v0.10):
> 
> ```typst
> #(import "/utils.typ": 
>   thing1,
>   thing2,
>   something-very-long,
>   stuff1,
>   stuff2,
>   stuff3,
>   and-maybe-something-else,
>   ok-this-is-the-last-one,
> )
> ```

Surprisingly, you are right, but only 99%. The trailing comma makes an error "unexpected closing paren" (why "paren" though?), so unfortunately you have to sacrifice it in this situation. I thought that parentheses will also create a scope like `[]` or `{}`, but today I learned that they do not create any scope (wow!). But that's a great finding/workaround anyway.

**Comment by ntjess** [comment]
You're correct; thanks for checking. I edited my answer to remove the trailing comma.

**Comment by ntjess** [comment]
@laurmaedje This syntax causes an error in the 0.11 rc -- is this intentional?

```typst
#(import "@preview/tablex:0.0.8":
tablex,
cellx
)
```
Compiles in 0.10, panics in 0.11 with `unclosed delimiter` + `unexpected closing paren`

**Comment by laurmaedje** [comment]
> This syntax causes an error in the 0.11 rc -- is this intentional?

No, that's a regression. I'll look into it.

**Comment by laurmaedje** [comment]
@ntjess Fixed the regression with https://github.com/typst/typst/pull/3633

**Comment by Adham-A** [comment]
Hello I would like to work on this issue if this is still availaible as my first contribution to Typst,

Just a few questions : 

I've looked into the code to understand how it works and as far as my quick search goes : 

I found this : 

https://github.com/typst/typst/blob/main/crates/typst-syntax/src/parser.rs#L789

So the goal here is to modify a part of the Parser/Lexer or is it something way simpler ?

**Comment by laurmaedje** [comment]
@Adham-A yep, this would need to be added in the parser, syntax tree, and code evaluation.

**Comment by Adham-A** [comment]
> @Adham-A yep, this would need to be added in the parser, syntax tree, and code evaluation.

Thank you I will look into this then, is there some documentation availaible on the inner workings of this to help ?

**Comment by laurmaedje** [comment]
There is a [bit of documentation](https://github.com/typst/typst/blob/b59735b76638ff0f12be08ab64d7107516bbcfaa/crates/typst-syntax/README.md) in an [unmerged PR](https://github.com/typst/typst/pull/4364/files). But beyond that, sadly not much. :/
