### ISSUE TITLE
Import everything except for some

### ISSUE THREAD

**Issue by Leedehai** [typst/typst#3068]
### Description

Feature request #3065 is useful. Based on that, it seems to be an opportunity to also offer this "import-not" syntax:

```typ
#import "package.typ": not (
  i-dont-want-this,
  this-either
)
```

This way, every symbol from that file is imported (maybe except for those beginning with underscores? — debatable) except the ones designated above to avoid collisions.

The Dart language offers a similar syntax [`import ... hide ...`](https://dart.dev/language/libraries#importing-only-part-of-a-library) which imports everything importable _except_ for the designated names.

This Dart feature was based on research on UI dev experience, **especially** on large & complex projects. Since typesetting a document is similar to developing a UI, same insight should be applicable here, too.

### Use Case

Users may use a lot of features offered by a package but only except for some. It often happens when typesetting a **large** document for a particular field that can mostly be done with the help of one (or only few) dedicated package. Also, like during UI development, users usually add names to the import list _while_ they are writing the paper (instead of writing down the full set of symbols they will use later from the start) and this import-not syntax could make this user experience smoother since they no longer need to scroll up.

**Comment by 8LWXpg** [comment]
I have a different syntax idea, use `#import "package.typ": *` followed by exclude keyword.
```typst
#import "package.typ": * except (
  i-dont-want-this,
  this-either
)
```

**Comment by emilyyyylime** [comment]
I don't like this at all. This seems to give the illusion of fine control over your imports while keeping all of the downsides of `*`. To use this you must know of every feature you want to use *and* all features you _don't_ want to use. And any reader of the code will have twice rhat problem—why are you telling them about what you aren't using? They don't care, they want to understand the things you did do.

If you change your package version it moves your errors to all the wrong places, and the argument about scrolling up seems completely unfounded to me—either you start with importing everything and when you're done you keep only what you used (which can be done using both import styles), or you start by importing nothing and over time you add what you're using (which can be done using both styles). Simply start with a `*` and when you're mostly done switch to listing each import.

**Comment by Enter-tainer** [comment]
For package authors I recommend the lib.typ trick: add a lib.typ file and only import symbols that should be visible to users.

https://github.com/mitex-rs/mitex/blob/main/packages/mitex/lib.typ#L1

**Comment by laurmaedje** [comment]
I agree with @emilyyyylime here. Since a lot of other people do as well, I will go ahead and close this as not planned.
