### ISSUE TITLE
Special constants undocumented

### ISSUE THREAD

**Issue by michalmoc** [typst/typst#3078]
### Description

There seems to be no entry in reference about special literals. Examples I know of:
* true/false (at least mentioned in booleans)
* none
* auto

### Use Case

I'd like to know what types and constants I have available and how they should be used by convention.

I copy usage of `auto` from built-in functions, and inside my code I do comparison like `if x == auto {}`. All guessed, not sure if it is good style or anything.

I spent lot of time searching how to denote unset optional parameter, and finally I found out `none` exists. I use it that way because of common sense, but is it intended usage?

How many other such literals exist? Perhaps there are some I'd like to use in my function interfaces?

**Comment by laurmaedje** [comment]
Oh, thanks for noticing! Those have been lost when transferring from a dedicated Types chapter to having types be documented due to them being in the global scope. (Since the none and auto _types_ are not in the scope.)
