### ISSUE TITLE
Format error decoding Png: Invalid PNG signature.

### ISSUE THREAD

**Issue by Lslightly** [typst/typst#3079]
### Description

I **made a screenshot by Weixin(version 微信 3.9.8.25, I don't know whether wechat is different from weixin)** and store it as an png file(the default format of screenshot in WeChat screenshot) and use `image` function to show this file. The image is as follows. 

![result1](https://github.com/typst/typst/assets/57594668/8463ecfa-2ead-496f-af9f-5074a0d62cad)

The error message is:

```
error: failed to decode image (Format error decoding Png: Invalid PNG signature.)
```

I can not upload the image to the web app, so I think there is no need to paste the reproduction url.

The reproduction code is as follows:

```typst
#figure(
    image("result1.png", width: 80%),
    caption: "test"
  )
```

### Operating system

Linux, Windows11

### Typst version

- [X] I am using the latest version of Typst, typst version typst 0.10.0 (70ca0d25)

**Comment by JalinWang** [comment]
Did you take another screenshot and then try it again?

**Comment by Lslightly** [comment]
> Did you take another screenshot and then try it again?

![2](https://github.com/typst/typst/assets/57594668/792d098a-91c4-4ee0-b63f-d1f090b8c6be)

The image above is generated by WeChat. It also don't work. But images generated by windows11 screenshot is valid.

**Comment by JalinWang** [comment]
![image](https://github.com/typst/typst/assets/20621784/647c4f55-4f74-45ac-adb1-9961c345adf4)

It seems like a JFIF(JPG) picture 🤔  https://en.wikipedia.org/wiki/JPEG_File_Interchange_Format

**Comment by Lslightly** [comment]
> ![image](https://private-user-images.githubusercontent.com/20621784/293043760-647c4f55-4f74-45ac-adb1-9961c345adf4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MjI2ODYsIm5iZiI6MTcwMzcyMjM4NiwicGF0aCI6Ii8yMDYyMTc4NC8yOTMwNDM3NjAtNjQ3YzRmNTUtNGY3NC00NWFjLWFkYjEtOTk2MWMzNDVhZGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDAwMTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNmI4YTA0NWIxMzY4ODhkZWRlM2Q1YjEyNTNjOGZhZGJmZjQxNjdkOTA4MDJlY2FhZDFlNDFhOTE3NjE4ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TQEjy03AgPNhaNtpylKWRbSTFLWEimNjnMFCZXSerr0)
> 
> It seems like a JFIF(JPG) picture 🤔 https://en.wikipedia.org/wiki/JPEG_File_Interchange_Format

that's it. Thank you very much. The default format of WeChat screenshot to be saved is png but actually the file format is jpg.

I use `file 2.png` and the result is as follows:

```
$ file 2.png 
2.png: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 501x61, components 3
```
