### ISSUE TITLE
Absolute mark/location?

### ISSUE THREAD

**Issue by user202729** [typst/typst#308]
I think it would be nice to have access to the absolute coordinate of a point on the page, similar to TikZ's `remember picture` feature.

![image](https://user-images.githubusercontent.com/25191436/227734109-32e24ce2-30ef-47d7-aa07-2ca675c9309e.png)

It may be sufficient to just add some attributes to the `location` type that can be queried.

I think this would be useful with `place`.

**Comment by laurmaedje** [comment]
I forgot to document this, `location` has methods for this called `page()` and `position()`. will put up docs soon.

**Comment by user202729** [comment]
Maybe better to create the page https://typst.app/docs/reference/types/location (this is linked from a few places such as https://typst.app/docs/reference/types/content ) and document it there instead?

**Comment by laurmaedje** [comment]
With the next docs deployment, all `location` links will link to the `locate` function where the methods will also be documented.
