### ISSUE TITLE
Parenthesis size mismatch with changed math font

### ISSUE THREAD

**Issue by SpaceHal** [typst/typst#3083]
### Description

Changing the math font typ leads to incorrect bracket sizes:
```typst
$ sin(x/y) $
#show math.equation: set text(font: "CMU Bright") 
$ sin(x/y) $
```

![math](https://github.com/typst/typst/assets/51107354/8d142005-b681-4c17-94ea-52b30aaa268d)

### Reproduction URL

https://typst.app/project/rZUg3I1nJkIP9oKYyNFlbW

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
It appears that CMU Bright is not a math font. You need to use a font specific to math for math environments, otherwise everything will look off and symbols will be missing.

Try, for instance, `Stix Two Math`.

**Comment by SpaceHal** [comment]
Thanks a lot.     

New Computer Modern Math works perfectly:
```typst
#show math.equation: set text(font: "New Computer Modern Math")
```

**Comment by PgBiel** [comment]
No problem! By the way, New Computer Modern Math is the default math font, so you don't need to change anything :)
