### ISSUE TITLE
Better Guide for LaTeX users

### ISSUE THREAD

**Issue by Lslightly** [typst/typst#3085]
When I search the typst substitution for `\textsc` in [docs](https://typst.app/docs), I don't find the substitution for it easily, although the answer `smallcaps` is just located in [text](https://typst.app/docs/reference/text/). I ask in discord to get the answer, but it's not so convenient. It does not appear in [Guide for LaTeX users – Typst Documentation](https://typst.app/docs/guides/guide-for-latex-users/). 

My proposal is to 
1. add a independent section for mapping from \textxx in latex to substitution in typst to supplement the guide for latex users.
2. refer to `pandoc` for some uncommon cases in [Guide for LaTeX users – Typst Documentation](https://typst.app/docs/guides/guide-for-latex-users/). (If there is a web page to convert latex snippets online, it's better)

**Comment by LaurenzV** [comment]
It might be a good idea to add that suggestion here: https://github.com/typst/typst/issues/2712

**Comment by laurmaedje** [comment]
Yes, I'll close this as a duplicate.
