### ISSUE TITLE
Wrong Arabic character display using Windows Compiler

### ISSUE THREAD

**Issue by agatho-daemon** [typst/typst#3086]
### Description

Using simple two lines to render English and Arabic.

```typst
#set page("a5")

#set text(dir: ltr)
This is LTR Text on Windows 11

#set text(dir: rtl)
هذه الكلمات من اليمين لليسار على نظام ويندوز
```

Different Results on different platforms. (Note the issue also present in windows 11 typst-preview vscode app)

## macOS output:
<img width="503" alt="Screenshot 2023-12-27 at 12 41 09" src="https://github.com/typst/typst/assets/31913284/bf20ef82-7cc1-4930-ad39-e6a698f7159f">

## Ubuntu output:
<img width="288" alt="Screenshot 2023-12-27 162153" src="https://github.com/typst/typst/assets/31913284/0e26f819-0836-4032-8bb4-e2c2e050108c">

## Windows 11 output:
<img width="287" alt="Screenshot 2023-12-27 162353" src="https://github.com/typst/typst/assets/31913284/28671646-702b-4795-b890-66d2e5a96bc4">

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by emilyyyylime** [comment]
This  is almost without question a font issue. Try explicitly setting the font to a font you know works well with Arabic on Windows

**Comment by agatho-daemon** [comment]
Thanks!

Wish if the default font which works on macOS renders nicely on Windows! It is a pleasing to the eye Arabic font. Please share the name if you know it. This is my second day on Typst.

**Comment by agatho-daemon** [comment]
I tried "Times New Roman" and it rendered alright. Thanks.

**Comment by agatho-daemon** [comment]
Actually no. Just set the direction to RTL/LTR and assumed default font is used.

So, default font on Ubuntu and macOS work fine.

macOS font is more superior when it comes to quality of Arabic letters display. I wonder if I could suggest that default Arabic font be the same on all platforms.

**Comment by PgBiel** [comment]
Typst does seem to provide built-in Arabic glyphs: https://github.com/typst/typst/blob/main/assets/fonts/NotoSansArabic-Regular.ttf

**Comment by emilyyyylime** [comment]
Typst doesn't have a default Arabic font, what's happening here is Typst falling back to system fonts, if you had your system fonts set up better you would see better output on all platforms

**Comment by agatho-daemon** [comment]
I've done some testing.

Not all fonts work with Typst. Some fonts do, and others don't.

I wonder if there is a utility I can use to examine the fonts and see if the ones that don't work have something in common and different than those which work.

**Comment by EpicEricEE** [comment]
> Not all fonts work with Typst. Some fonts do, and others don't.

A wild guess, but some fonts shipped with Windows are _variable fonts_, which are not supported by Typst yet.

> Typst does seem to provide built-in Arabic glyphs: https://github.com/typst/typst/blob/main/assets/fonts/NotoSansArabic-Regular.ttf

It's used in the test suite, but it's not embedded in the CLI:
https://github.com/typst/typst/blob/e215f22965760bcc5df3204243597825e99b3fe7/crates/typst-cli/src/fonts.rs#L126-L140

**Comment by PgBiel** [comment]
> It's used in the test suite, but it's not embedded in the CLI:

Darn. Then yeah, those problems will arise

**Comment by agatho-daemon** [comment]
> > Not all fonts work with Typst. Some fonts do, and others don't.
> 
> A wild guess, but some fonts shipped with Windows are _variable fonts_, which are not supported by Typst yet.
> 
> > Typst does seem to provide built-in Arabic glyphs: https://github.com/typst/typst/blob/main/assets/fonts/NotoSansArabic-Regular.ttf
> 
> It's used in the test suite, but it's not embedded in the CLI:
> 
> https://github.com/typst/typst/blob/e215f22965760bcc5df3204243597825e99b3fe7/crates/typst-cli/src/fonts.rs#L126-L140

Actually, I don't know which is a variable font and which is not.

I've tried many fonts which I've downloaded over the net and from different sources.

If somone can give a utiliti command that I can run on the fonts in Ubuntu and compare the output between which works and which doesn't it might help.

**Comment by laurmaedje** [comment]
As said in https://github.com/typst/typst/issues/3086#issuecomment-1870359479, different fonts on different platforms are expected behaviour.

**Comment by asibahi** [comment]
I realize this is a closed issue, but if I warrant a guess to the underlying cause is that rustybuzz does not have a fallback Arabic shaper.
