### ISSUE TITLE
`none in dictionary` — should return false?

### ISSUE THREAD

**Issue by emilyyyylime** [typst/typst#3091]
### Description

Would check if a key exists in a dictionary

### Use Case

Only doing something with a dictionary's value at some key if it is present

**Comment by laurmaedje** [comment]
There is `"key" in dict` already.

**Comment by emilyyyylime** [comment]
In that case my problem was that if the lhs is `none` I get an error where I wanted false. Guess this relates to the warning suppression/ fallible code forge. If you feel like it falls under there feel free to close

**Comment by laurmaedje** [comment]
Since none isn't a valid dictionary key, I think this is fine as is.
