### ISSUE TITLE
Export specific page / page ranges

### ISSUE THREAD

**Issue by emilyyyylime** [typst/typst#3095]
### Description

`typst compile path/to/proj.pdf --page 2 export.png`

### Use Case

When exporting to images sometimes it is desirable to only export some of the pages.

**Comment by PgBiel** [comment]
This should be fairly easy for PNG and SVG exports, but sounds like it can be a bit complex for PDF export. I think the best approach for that would be to ensure `typst-pdf` doesn't touch things from deleted pages, e.g. excludes headings in those and so on. Still, this would definitely be an interesting feature.

**Comment by emilyyyylime** [comment]
If I'm not mistaken PDFs actually have support for starting on page numbers other than 1, so that seems like the best approach to me
