### ISSUE TITLE
Bitwise operations on integers

### ISSUE THREAD

**Issue by Mc-Zen** [typst/typst#3097]
### Description

It would be useful to add bitwise operations for integers to the `calc` module, i.e.,
- `not`, `and`, `or`, and `xor` as well as
- `lshift`, and `rshift`.

I am not sure if someone has already suggested this since it is very obvious but could not find any issue related to this. 

### Use Case

Bitwise operations have many applications and are in particular part of many widely-used algorithms. Although Typst is not a general-purpose programming language, I believe there will be sufficient use cases to justify including them. 

Another argument is that it is very hard and inefficient to implement bitwise operations with the available standard arithmetic functions (bit shift is not too difficult but the others are), so there would be no workaround. 

I **don't** suggest dedicated syntax (like `&` or `<<` for bitwise operations) because they will not be *that* common. Rather, I think that functions like `calc.and(a,b)` etc. would be appropriate.

**Comment by emilyyyylime** [comment]
I would like to see `not` appear as `inv` / `inverse` / `compl` / `complement`. Not feels too boolean to me.

**Comment by Mc-Zen** [comment]
On my part, it does not have to be named `not`. However, the same argument would then apply to the other operations as well, at least `and` and `or`. 

On the other hand, I feel that writing it as `calc.not()` already makes it appear as a non-boolean operation.

**Comment by emilyyyylime** [comment]
Yes, I've realised since that that is a better option, and could work for all operations.

**Comment by Mc-Zen** [comment]
Sounds good 👍

**Comment by taylorh140** [comment]
How about calc.ones-compliment
