### ISSUE TITLE
Math element comparison with `==` yields inconsistent results

### ISSUE THREAD

**Issue by Leedehai** [typst/typst#3102]
### Description

```typ
#let checkself(e) = {
  if e == sym.sum { $"sym.sum"$ } 
  else if e == [sym.sum] { $"[sym.sum]"$ }
  else if e == [Σ] { $"nakedΣ"$ }
  else if e == sym.integral { $"sym.integral"$ }
  else if e == [∫] { $"naked∫"$ }
  else { $"others"$ }
} 

// Check the AttachElem's "base" field
#let checkbase(input) = {
  checkself(input.base)
}

$ "checkself":\ checkself(sum), checkself(Σ), checkself(integral), checkself(∫) $
$ "checkbase":\ checkbase(sum^1), checkbase(Σ^1), checkbase(integral^1), checkbase(∫^1) $
```

Output:
<img width="335" src="https://github.com/typst/typst/assets/18319900/d2df066b-b200-4d34-96d4-7e803e4edb2c">
I think `checkself` outputs the expected results, while `checkbase` doesn't.

Taking a step back: one could point out `checkself(sum)`'s argument is a `symbol` object while `checkbase(sum^1)`'s argument is a `content` object (and `sum^1`'s base field is also a `content`), but I still expect `checkbase(sum^1)` should print `[sym.sum]` or `nakedΣ`, not `others`.

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Leedehai** [comment]
Turns out `sum^1`'s base field equals to content `[∑]` (U+2211), not the greek letter content `[Σ]` (U+03A3).

Working as intended!

```typ
#let checkself(e) = {
  repr(type(e))
  if e == sym.sum { $":sym.sum"$ } 
  else if e == [sym.sum] { $":[sym.sum]"$ }
  else if e == [Σ] { $":greekΣ"$ }
  else if e == [∑] { $":unicode∑"$ }
  else if e == sym.integral { $":sym.integral"$ }
  else if e == [∫] { $":naked∫"$ }
  else { $":others"$ }
} 

#let checkbase(input) = {
  checkself(input.base)
}

$ "checkself":\ checkself(sum), checkself(Σ), checkself(integral), checkself(∫) $
$ "checkbase":\ checkbase(sum^1), checkbase(Σ^1), checkbase(integral^1), checkbase(∫^1) $
```

<img width="595" src="https://github.com/typst/typst/assets/18319900/2f4f5cd3-da85-46fe-bffa-ed50cd4bb475">

**Comment by emilyyyylime** [comment]
See also: `sym.Sigma`
