### ISSUE TITLE
Add `calc.signum` (or equivalent)

### ISSUE THREAD

**Issue by PgBiel** [typst/typst#3113]
### Description

Rust has a `f64::signum` method[^1] (no parameters) which returns `1.0` if the float is positive or `+0.0`, `-1.0` if the float is negative or `-0.0`, and `NaN` if the float is `NaN`. Rust also has a `i64::signum` method[^2] which returns `1` if the integer is positive, `0` if it is zero and `-1` if it is negative.

Therefore, I propose we add a `calc.signum` method with largely the same function: obtain the sign of a number.
We'd still have to hash out the details though, as the above behavior could potentially be viewed by users as inconsistent between floats and integers when we consider the number zero.

For one, the `i64` behavior seems to be consistent with the mathematical sign function[^3]. However, `f64`'s behavior is also technically correct, in a way.

We have the following choices (so far):

1. Specialize `calc.signum` to simply do the same as Rust (when given an integer, return `-1`, `0` or `1`; when given a float, return `1.0`, `-1.0` or `NaN`).
2. Prefer consistency with the `f64` approach and on the integer case use `1` for zero or positive and `-1` for negative.
3. Prefer consistency with the `i64` approach and on the float case use `0.0` for both `+0.0` and `-0.0`.
4. Same as item 1, but also change the float case to return `+1.0` for `-0.0`, since, in Typst, `-0.0 == 0.0` is `true`.
5. Same as item 2, but also change the float case to return `+1.0` for `-0.0`, since, in Typst, `-0.0 == 0.0` is `true`.

Not sure which one would be the most appropriate (mathematicians, please reach out!). In principle, 1 or 4 would be the approaches which keep the most consistency with Rust (and also with the function's name, "signum"), while 2, 3 or 5 could be more user-friendly due to greater consistency (however, they could be less consistent with the function's name), but this warrants discussion.

[^1]: https://doc.rust-lang.org/std/primitive.f64.html#method.signum
[^2]: https://doc.rust-lang.org/std/primitive.i64.html#method.signum
[^3]: https://en.wikipedia.org/wiki/Sign_function

### Use Case

Finding the sign of a number is very useful in calculations where you'd like to retain the original sign of a number and later restore it or apply it to some other number (I've had to use this in tablex recently to be able to `measure` a negative length, for example - I apply `abs` to it and later multiply by its original sign). This is also the job of a `f64::copysign` function in Rust, which could theoretically also be added to Typst, but such a discussion would likely come _after_ this one, so I'd consider it slightly off-topic for now.

**Comment by emilyyyylime** [comment]
Another option not mentioned above is working the same as (3), but returning `+0.0` for `+0.0` and `-0.0` for `-0.0`.
Essentially, `sign(x) = if x > 0.0 { type(x)(1) } else if x < -0.0 { type(x)(-1) } else { x }`. I do believe this option has the most applicability in the widest range of use cases, as it aligns with the mathematical definition while keeping the flexibility of (2) — you get to differentiate between 0+ and 0- where that's required and elsewhere just use `== 0` for a straightforward 0 check.

**Comment by PgBiel** [comment]
> Another option not mentioned above is working the same as (3), but returning `+0.0` for `+0.0` and `-0.0` for `-0.0`. Essentially, `sign(x) = if x > 0.0 { type(x)(1) } else if x < -0.0 { type(x)(-1) } else { x }`. I do believe this option has the most applicability in the widest range of use cases, as it aligns with the mathematical definition while keeping the flexibility of (2) — you get to differentiate between 0+ and 0- where that's required and elsewhere just use `== 0` for a straightforward 0 check.

I don't think that's particularly useful, since `#(float("+0.0") == float("-0.0"))` returns `true`, so it's easier to just return +0 for both cases.

**Comment by emilyyyylime** [comment]
Since when do we prefer 'easier' approaches? /lh
My point is that for almost all use cases this is indistinguishable from (1), but if someone really needs to differentiate 0+ and 0- they still can.

**Comment by laurmaedje** [comment]
As said somewhere else, I'd prefer to have calc removed in favor of methods on int and float, so any potential discussion should take this possibility into account.

**Comment by PgBiel** [comment]
> As said somewhere else, I'd prefer to have calc removed in favor of methods on int and float, so any potential discussion should take this possibility into account.

I think that could definitely be suitable in this case, given that the behavior would differ between integers and floats. We could have `int.signum()` and `float.signum()`.

**Comment by laurmaedje** [comment]
I'd say this favors a design where calc.signum returns a number of the type it was given.
