### ISSUE TITLE
Integral symbol is too small in displayed equations when using Cambria Math font

### ISSUE THREAD

**Issue by lvjr** [typst/typst#3114]
### Description

I tried to use Cambria Math font with the following code:
```typst
Inline $integral_a^b f(x)=F(b)-F(a)$ and displayed
$ integral_a^b f(x)=F(b)-F(a) $

#show math.equation: set text(
  font: ("Cambria Math"),
)

Inline $integral_a^b f(x)=F(b)-F(a)$ and displayed
$ integral_a^b f(x)=F(b)-F(a) $
```
but the integral symbol in displayed equations looked too small with Cambria Math:

![typst](https://github.com/typst/typst/assets/4239949/1f30b9f2-d05b-4906-8c67-0b098324e907)

The following is the same equation in Microsoft Word:

![word](https://github.com/typst/typst/assets/4239949/89748940-d5c2-40ed-a70a-ce1bc4217317)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
```
#import "@preview/mitex:0.1.0": *
#mitex(`{\sqrt{\sum_{n=1}^\infty {\frac{10}{n^4}}}} = {\int_0^\infty \frac{2x dx}{e^x-1}} = \frac{\pi^2}{3} \in {\mathbb R}`)

#show math.equation: set text(
  font: ("Cambria Math"),
)
#mitex(`{\sqrt{\sum_{n=1}^\infty {\frac{10}{n^4}}}} = {\int_0^\infty \frac{2x dx}{e^x-1}} = \frac{\pi^2}{3} \in {\mathbb R}`)

```
https://frederic-wang.fr/update-on-open-type-math-fonts.html
<img width="685" alt="image" src="https://github.com/typst/typst/assets/25521218/9a159f84-f2bf-40ad-9eac-77a0134837e5">
<img width="653" alt="image" src="https://github.com/typst/typst/assets/25521218/23be7960-763e-43e1-96bf-98d57b161df3">

**Comment by Enter-tainer** [comment]
similar issue(but seems not to be helpful): https://tex.stackexchange.com/questions/543704/integral-sign-is-too-small

**Comment by Enter-tainer** [comment]
It looks like the display integral symbol is indeed larger than the inline one. But it is still smaller than expected.

**Comment by Enter-tainer** [comment]
Typst use display_operator_min_height in math table. Maybe Cambria Math has multiple size variant of integral operator, so typst choose the smallest one. Any good idea to fix this?

https://github.com/typst/typst/blob/c27b9e2b0fad9fa3c68837ba12f0b32774daaf67/crates/typst/src/math/ctx.rs#L205

**Comment by Enter-tainer** [comment]
<img width="487" alt="image" src="https://github.com/typst/typst/assets/25521218/c4912dec-1ec0-423f-9325-cc180a43d4d0">
<img width="449" alt="image" src="https://github.com/typst/typst/assets/25521218/9c287f43-0f4b-4bd3-8a02-2f6cf0889edc">

This is unfortunately not covered in texbook appendix G.

**Comment by Enter-tainer** [comment]
https://github.com/latex3/luaotfload/blob/1583a2f87d31d4fdd1909074d9b82e2f39a94bc0/src/luaotfload-auxiliary.lua#L142 . luaotfload is setting a min-value for display operator min height, we may copy that. @laurmaedje is it okay for you? I can have a try.

**Comment by Enter-tainer** [comment]
A quick fix:

<img width="545" alt="image" src="https://github.com/typst/typst/assets/25521218/3e3f84e3-6e7c-46e3-ad33-f91a6394fd08">

```diff
diff --git a/crates/typst/src/math/ctx.rs b/crates/typst/src/math/ctx.rs
index 9352f08b..777ffd19 100644
--- a/crates/typst/src/math/ctx.rs
+++ b/crates/typst/src/math/ctx.rs
@@ -202,7 +202,12 @@ impl<'a, 'b, 'v> MathContext<'a, 'b, 'v> {
             let class = self.style.class.as_custom().or(glyph.class);
             if class == Some(MathClass::Large) {
                 let mut variant = if self.style.size == MathSize::Display {
-                    let height = scaled!(self, display_operator_min_height);
+                    let display_operator_min_height = if self.constants.display_operator_min_height() < 2800 {
+                        2800
+                    } else {
+                        self.constants.display_operator_min_height()
+                    };
+                    let height = display_operator_min_height.scaled(self);
                     glyph.stretch_vertical(self, height, Abs::zero())
                 } else {
                     glyph.into_variant()
```

**Comment by Enter-tainer** [comment]
There is also the webkit solution: https://github.com/WebKit/WebKit/blob/c0c0cb347423417c4135f012632a0ba7f4c939b1/Source/WebCore/rendering/mathml/MathOperator.cpp#L245

**Comment by Krasjet** [comment]
[TeX Gyre Pagella Math](https://www.gust.org.pl/projects/e-foundry/tg-math/download) seems to have the same problem. Is there a way to fix this without hardcoding the font name in the rust code?

See also: https://tex.stackexchange.com/questions/489859/tex-gyre-pagella-math-integral-sign-much-too-small

**Comment by laurmaedje** [comment]
The fix for Cambria Math didn't involve hardcoding a font name. Perhaps it's possible here too. I wouldn't want to hardcode a font name.

**Comment by Krasjet** [comment]
@laurmaedje That was my mistake. The fix in Typst indeed doesn't involve the font name.

Though I'm kind of confused if there is a bug in Typst using TeX Gyre Pagella Math. The integral symbol definitely looks smaller:

<img width="1068" height="448" alt="Image" src="https://github.com/user-attachments/assets/45062390-fc6e-44cf-bc0b-4f244c2f2c69" />

code:
```typst
Inline $integral_a^b f(x) upright(d)x=F(b)-F(a)$ and displayed
$ integral_a^b f(x) upright(d)x=F(b)-F(a) $

#show math.equation: set text(
  font: ("TeX Gyre Pagella Math"),
)

Inline $integral_a^b f(x) upright(d)x=F(b)-F(a)$ and displayed
$ integral_a^b f(x) upright(d)x=F(b)-F(a) $
```

 I know the LaTeX package `newpx` does a replacement for the integral symbol: https://muug.ca/mirror/ctan/fonts/newpx/doc/newpxdoc.pdf#page=12. Is there a way to use a separate font only for the integral symbol?

**Comment by laurmaedje** [comment]
Currently, you can only have one math font, but there is an active PR to change that (#6365). I can't tell right now whether there is a bug in Typst or not; please open a separate issue so that we can track this. Conversations on old issues are hard to keep track of.
