### ISSUE TITLE
Math symbols font error

### ISSUE THREAD

**Issue by Nemoos-0** [typst/typst#313]
I tried to compile the following file

```
$vec(1, 2, 3)$

$arrow(x)$

$mat(1, 2; 3, 4)$
```

and this is what I got.

![image](https://user-images.githubusercontent.com/52749992/227743308-666c3926-63a7-4948-bd1e-ed3e30e89c77.png)

I downloaded the `typst` compiler from the AUR and I am on version `22-03-21`.
The program doesn't give any error or warning.

I thought it could be a font problem, so I tried to set a specific font such as `Latin Modern Math` and `CMU Serif` using the code below

```
#set text(
    font: "Latin Modern Math"
)
```

Hope you can help me.

Thanks for the great tool, hope to see it become better and better.

**Comment by laurmaedje** [comment]
That version doesn't embed fonts yet, so this depends on your system fonts. However, setting the text font like you did doesn't affect the math font. For that you need to write: `#show math.equation: set text(font: "Latin Modern Math")`.

**Comment by Nemoos-0** [comment]
Thanks for the fast response, that solved the problem.

---

I am going to leave a note if someone has the same problem.

> That version doesn't embed fonts yet

- Download the font using this guide https://wiki.archlinux.org/title/Fonts#Pacman.
- Use `fc-list` to show all the installed fonts on your system.
- I also run `fc-cache` but I actually don't know if it was needed.
- Before using a font in `typst` check that it is available using `typst --fonts`.
