### ISSUE TITLE
Smallcaps has no effect in math mode

### ISSUE THREAD

**Issue by Olexorus** [typst/typst#3138]
### Description

Using the [smallcaps](https://typst.app/docs/reference/text/smallcaps/) function doesn't seem to work in math mode.

This is simple to reproduce by pasting this into an empty document:
```
#smallcaps[Normal text]

$#smallcaps[Math mode]$
```
![Rendered](https://github.com/typst/typst/assets/23169941/69da15d4-79c3-4cbc-9493-cc1ba095eacc)

I'm using Typst 0.10.0 (70ca0d25), but this also happens on the web app.

I'm not sure if this is actually a bug or if you're supposed to use it differently in math mode, but I couldn't find anything in the documentation and when I asked on Discord noone had an answer, so I decided to post it here.

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
I guess it's a font issue.

![image](https://github.com/typst/typst/assets/25521218/e294a48b-9f4b-480d-8398-6a19d2180ba4)

```
$ #smallcaps[Test] $

#show math.equation: set text(
  font: ("Cambria Math"),
)

$ #smallcaps[Test] $

#show math.equation: set text(
  font: ("Fira Math"),
)

$ #smallcaps[Test] $

```

Some math font do have a sc variant

**Comment by Olexorus** [comment]
Is there a way to write a show rule that change the font smallcaps in math mode?

**Comment by Enter-tainer** [comment]
maybe. you can try. you may also wrap smallcaps call with `text(font: ...)[]`

**Comment by Olexorus** [comment]
Thanks, I'll try that, and I'll close this issue since it doesn't seem to be a Typst bug.
