### ISSUE TITLE
Provide values in the cli, during compilation, that can be read in the document

### ISSUE THREAD

**Issue by zerinoid** [typst/typst#3141]
### Description

To be able to pass arguments in the CLI compilation process, something like `typst compile document.typ --extVar value` that can be read in the script and be used, for instance, as a condition evaluation.

```
#if extVar {
 somethings
}
```

### Use Case

This would be useful for compiling different versions of a document in compilation time, without having to change anything in the script.

As in a resume use case, one would be able to compile several resumes in different languages using conditionals in the script that evaluate this one value passed in the CLI.

**Comment by Enter-tainer** [comment]
https://github.com/typst/typst/pull/2894
it will appear in next version

**Comment by zerinoid** [comment]
Ok, thank you for the reply
