### ISSUE TITLE
Confusing error message when trying to insert new dict/array value with `at(..., default: ...)`

### ISSUE THREAD

**Issue by ntjess** [typst/typst#3154]
### Description

This code:
```typst
#let x = (1,2)
#{
  x.at(2, default: 4) = 5
}
```

Generates the error message `array index out of bounds (index: 2, len: 2) and no default value was specified`. It should instead have a separate error that "at" cannot insert new values regardless of `default`.

The same issue happens with dict keys:

```typst
#let x = (a: 5)
#{
  x.at("b", default: 4) = 5
}
```

### Typst version

- [X] I am using the latest version of Typst

**Comment by astrale-sharp** [comment]
I've got a similar problem
```
#{
  let x = (:)
  x.at("1", default : 0) = 1
}
```

which gives `dictionary does not contain key "1" and no default value was specified`
