### ISSUE TITLE
datetime and duration should be castable to string

### ISSUE THREAD

**Issue by nineff** [typst/typst#3155]
### Description

Currently, you can cast many types to string using the `str()` function. This does however currently not work for `datetime` and `duration`s. Both have a default display when used as content, which could also be used in the cast to string.

### Use Case

mostly to pass around datetime / durations into other functions which only accept string as input, like `replace()` which is especially handy to adapt SVG-Templates.

**Comment by Leedehai** [comment]
Is this FR as simple as `str(foo)`? (where `foo` is a datetime or duration instance).

Sounds like an opportunity to make `foo.to_string(format)` like [`datetime.display(format)`](https://typst.app/docs/reference/foundations/datetime/)

**Comment by Leedehai** [comment]
Is this FR's use case simply `str(foo)`? (where `foo` is a `datetime` or `duration` instance).

Sounds like an opportunity to make `foo.to_string(format)` like [`datetime.display(format)`](https://typst.app/docs/reference/foundations/datetime/).

**Comment by nineff** [comment]
> Is this FR's use case simply `str(foo)`? (where `foo` is a `datetime` or `duration` instance).
> 
> Sounds like an opportunity to make `foo.to_string(format)` like [`datetime.display(format)`](https://typst.app/docs/reference/foundations/datetime/).

basically, yes. Your proposal `foo.to_string()` would also work fine and even offer the capability for a userdefinied format, but i did not propose this as there is currently no other `to_string()` method on other elements, at least none that I'm aware of.

**Comment by Leedehai** [comment]
Hmm wait, `.display()` already returns a string -- thought it returns a content.

**Comment by nineff** [comment]
> Hmm wait, `.display()` already returns a string and can be passed to functions expecting strings -- thought it returns a content. Could you clarify why `str()` is better than the existing `.display()`?

i did not realize this, i also thought `display()` would return content. This actually is enough for my usecase. One might still consider adding `datetime` and `duration`as valid inputs to `str()`since this is how other types are cast to string.

**Comment by laurmaedje** [comment]
The plan is for datetime and duration to automatically display in localized form in the future. Because the text language isn't known without context, `str` couldn't know it and thus we would have to default to something. For this reason, I would refrain from adding it.
