### ISSUE TITLE
Documentation for `place()` is a bit misleading

### ISSUE THREAD

**Issue by zegkljan** [typst/typst#3159]
### Description

This code
```typst
first
#place(top + left, dx: 100pt, rect(width: 30pt, height: 30pt, fill: aqua))
second
third
```
produces this output
![image](https://github.com/typst/typst/assets/6035604/2945626b-977f-4bf8-976b-e5589dca342b)
while it would be expected to produce this output (here achieved by moving the `#place` call at the end)
![image](https://github.com/typst/typst/assets/6035604/0b10e0bd-6c50-4cba-9498-c453e32bd18b)
as per [the documentation](https://typst.app/docs/reference/layout/place/#summary):

> Places content at an absolute position.
> 
> **Placed content will not affect the position of other content.** Place is always relative to its parent container and will be in the foreground of all other content in the container. Page margins will be respected.

Either the behavior or the documentation is therefore incorrect.

Possibly related to #1833

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
The documentation is perhaps a bit misleading here. In general, everything except for a few things (text, inline equations, boxes) is block-level and so is `place`. However, it will not affect other block-level containers.

**Comment by SolidTux** [comment]
This can sometimes be circumvented with `box(place(...))` by the way. I don't know in which cases this breaks, though.

**Comment by SolidTux** [comment]
Thanks a lot!
