### ISSUE TITLE
SVG text rendered very small / incorrectly

### ISSUE THREAD

**Issue by IlanCosman** [typst/typst#3162]
### Description

This is just a water molecule from Chemdraw, using the svg export there:

```svg
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="38px" height="21px" viewBox="0 0 38 21" style="background-color: #ffffffff" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" >
<text x="0" y="0" stroke="transparent" fill="#000000" transform="matrix(0.05 0 0 0.05 2.9617 17.9917)" style="font:normal normal normal 200px 'Arial'" >
H</text>
<text x="0" y="0" stroke="transparent" fill="#000000" transform="matrix(0.05 0 0 0.05 15.1108 10.8167)" style="font:normal normal normal 200px 'Arial'" >
O</text>
<text x="0" y="0" stroke="transparent" fill="#000000" transform="matrix(0.05 0 0 0.05 27.8166 17.9917)" style="font:normal normal normal 200px 'Arial'" >
H</text>
<path stroke="transparent" fill="#000000" transform="matrix(0.05 0 0 0.05 -1096 -385)" d="M 22208,7893.05 L 22214,7903.44 L 22156.2,7936.83 L 22150.2,7926.44 L 22208,7893.05 Z " />
<path stroke="transparent" fill="#000000" transform="matrix(0.05 0 0 0.05 -1096 -385)" d="M 22449.5,7926.25 L 22443.5,7936.65 L 22385.8,7903.33 L 22391.8,7892.94 L 22449.5,7926.25 Z " />
</svg>
```

It should look something like this:

![image](https://github.com/typst/typst/assets/6318351/3d978ec8-0edb-4a74-928e-068b24ca3f1c)

but in typst, using just `#image("foo.svg")`, it looks like this:

![image](https://github.com/typst/typst/assets/6318351/256e9a73-c73d-45be-93de-ca0e794daec3)

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
Probably an upstream issue, but will look into it.

**Comment by LaurenzV** [comment]
I reported the issue upstream.

**Comment by Enter-tainer** [comment]
For now to use this in typst you may (a) export to png or other bitmap format in chemdraw (b) use inkscape to post-process the svg file and "convert text to paths"

**Comment by LaurenzV** [comment]
For anyone else having the same issue, the current workaround is to replace instances of the `font` shorthand manually. So for example replace:
`font:normal normal normal 200px 'Arial'`

by `font-family: 'Arial'; font-size: 200px`

**Comment by LaurenzV** [comment]
Feature has been implemented upstream, so it should land here soon as well.

**Comment by taooceros** [comment]
Any progress

**Comment by LaurenzV** [comment]
We unfortunately were not able to update to resvg 0.40 for Typst 0.11 because there were some breaking changes in `resvg` which we still need to figure out how to deal with it. Hopefully we can do it for next version.

So the status is still the same, the bug has been fixed upstream but it hasn't landed in Typst yet.

**Comment by LaurenzV** [comment]
Fixed on main.
