### ISSUE TITLE
Add documentation to using Typst Library from Crates IO

### ISSUE THREAD

**Issue by cybercoder-naj** [typst/typst#3166]
### Description

On the occasion of using `typst` to compile documents from other Rust packages, the usage of functions is not well documented end-to-end from the source file to the compiled product. 

### Use Case

Users trying to compile typst with other Rust programs have easy access to learning how to use different library functions.

**Comment by Enter-tainer** [comment]
it's not avaliable on crates io. but you can add typst as a git depedency in cargo.toml

**Comment by cybercoder-naj** [comment]
Yeah, I have been able to download the library using Git to my own Rust project. However, there are multiple moving parts involved. For example, the `pub fn compile` requires a reference to `World` and `Tracer` whose usage is not readily available.

**Comment by Enter-tainer** [comment]
I mean this: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories

**Comment by Enter-tainer** [comment]
You may check repos use typst as a library: typst-lsp typstfmt typst.ts typst-preview obsidian-typst ...

**Comment by tfachmann** [comment]
Out of a personal interest, I investigated this myself and was able to make a minimal example to work.
To use `typst` as a library in rust, have a look at https://github.com/tfachmann/typst-as-library

**Comment by cybercoder-naj** [comment]
Thanks @tfachmann for your repository. It can definitely help people to use your project for reference. It'll be great if we had some official examples/docs from the typst team itself.

**Comment by laurmaedje** [comment]
Thereis already some rustdoc docs and we'll add some more before putting Typst on crates.io, so I'm going to close this in favor of #2450.
