### ISSUE TITLE
Ability to collect footnotes into a single group

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#3169]
### Description

Add some way to put all footnotes together as a block of content.

### Use Case

I'd like to be able to build an appendix page with all of my footnotes. More concretely, I have a math cheat sheet with theorems and I'd like to be able to write the proofs for each theorem inline in the text using a footnote, but have the actual proof show up in an appendix section so I can print just the theorems.

**Comment by max397574** [comment]
why wouldn't you just use references?

**Comment by SUPERCILEX** [comment]
Because I'd have to reimplement the styling of footnotes. So I guess what I really want is an easy way to get the numbering right and have the references be automatic.

**Comment by SUPERCILEX** [comment]
That probably makes sense as a package I think.

**Comment by SUPERCILEX** [comment]
Ok, it wasn't too bad:
```

#let appendices = state("appendices", (count: 0, items: ()))

#let appendix(content) = {
  appendices.display(((count, _)) => {
    let rev_label = label("rev-appendix-" + str(count))
    let label = label("appendix-" + str(count))

    appendices.update(((count, items)) => {
      items.push((label, rev_label, content))
      (count + 1, items)
    })

    [
      #h(0pt, weak: true)
      #link(label, text(fill: luma(0%), super(str(count + 1))))
      #rev_label
    ]
  })
}

#let show-appendices = appendices.display(((count, items)) => {
  appendices.update(((count, _)) => (count, ()))
  for (i, item) in items.enumerate(start: count - items.len() + 1) {
    let (label, rev_label, content) = item
    par([
      #h(1em)
      #link(rev_label, text(fill: luma(0%), super(str(i)))) #label
      #h(0pt, weak: true)
      #content
    ])
  }
})
```
