### ISSUE TITLE
Way to strip whitespace preceding variable reference

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#3174]
### Description

Is there a way to strip/swallow preceding whitespace before a function call/variable use? For example, `foo #super[1]` renders as this:
![image](https://github.com/typst/typst/assets/9490724/941faba2-aa2a-4bc8-8da5-ac3f11c3ecf3)

Of course I can write `foo#super[1]` but that's really ugly.

### Use Case

I'm trying to implement similar behavior to `#footnote`:

**Comment by EpicEricEE** [comment]
You can prepend it by a weak `0pt` spacing, for example:
```typ
#show super: it => h(0pt, weak: true) + it
foo #super[1]
```

or similarly with a custom variable (or function):
```typ
#let something = {
  h(0pt, weak: true)
  box(width: 0.5em, height: 0.5em, fill: black)
}

foo #something bar
```

**Comment by SUPERCILEX** [comment]
Perfect, thanks!
