### ISSUE TITLE
"expected function, found label" with very specific label ordering

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#3176]
### Description

```
#let appendices = state("appendices", (count: 0, items: ()))
#let appendix(content) = {
  appendices.display(((count, _)) => {
    let other = label("rev-appendix-" + str(count))
    let label = label("appendix-" + str(count))
    // let other = label("rev-appendix-" + str(count))

    appendices.update(((count, items)) => {
      items.push((label, content))
      (count + 1, items)
    })


    h(0pt, weak: true) + link(label, text(fill: luma(0%), super(str(count + 1))))
  })
}
#let show-appendices = appendices.display(((count, items)) => {
  appendices.update(((count, _)) => (count, ()))
  for (i, item) in items.enumerate(start: count - items.len() + 1) {
    let (label, content) = item
    par([#super(str(i)) #label #content])
  }
})

z #appendix[z]
#show-appendices
```

The above works, but comment the first label and uncomment the third and suddenly everything breaks.

### Typst version

- [ ] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
The line `let label = label("appendix-" + str(count))` overrides the label function so that in `let other = label("rev-appendix-" + str(count))`, `label` refers to the just created label and not the built-in label constructor.

**Comment by SUPERCILEX** [comment]
Oh shoot, that's a :man_facepalming: moment. Sorry! :grinning:

**Comment by laurmaedje** [comment]
Happens to the best of us :p

**Comment by goyalyashpal** [comment]
just sharing the code from description with syntax-highlighting for my own reference:


```typst
#let appendices = state("appendices", (count: 0, items: ()))
#let appendix(content) = {
  appendices.display(((count, _)) => {
    let other = label("rev-appendix-" + str(count))
    let label = label("appendix-" + str(count))
    // let other = label("rev-appendix-" + str(count))

    appendices.update(((count, items)) => {
      items.push((label, content))
      (count + 1, items)
    })


    h(0pt, weak: true) + link(label, text(fill: luma(0%), super(str(count + 1))))
  })
}
#let show-appendices = appendices.display(((count, items)) => {
  appendices.update(((count, _)) => (count, ()))
  for (i, item) in items.enumerate(start: count - items.len() + 1) {
    let (label, content) = item
    par([#super(str(i)) #label #content])
  }
})

z #appendix[z]
#show-appendices

```

**Comment by goyalyashpal** [comment]
hi @SUPERCILEX , 
can you add `typst` language label to the code block shared in description?
thanks in advance. :smiley: 

------

[ddg-search]: https://duckduckgo.com/?q=typst+error%3A+expected+function%2C+found+alignment&ia=web "typst error: expected function, found alignment"


> overrides the label function ...
> \- _@ laurmaedje at https://github.com/typst/typst/issues/3176#issuecomment-1888071319_

> ... errors related to shadowed built-in names # 4263
> \- _@ PgBiel at https://github.com/typst/typst/issues/3176#ref-issue-2317856326_

woww, thanks a lot.  

* i was using a template picked from web.  
* it was showing `expected function, found alignment` error on trying to `set align(center)` in the function body.
* i was clueless with that error, but thankfully the web search with [duckduckgo][ddg-search] landed me here
* and with help of those 2 quoted hints, i figured out that i should try removing the parameter from the function header
* and voila, it worked.

but yeah, if possible, then the error itself should say something about the problem being related to shadowing

**Comment by laurmaedje** [comment]
> but yeah, if possible, then the error itself should say something about the problem being related to shadowing

in the next release, there will be a hint.

> also, any suggestion for a descriptive alternative name other than the align for the parameter of the function?

that's difficult, especially since `alignment` is also a standard definition (for the type), though it's needed far less. many of the built-in functions also have `align` as a parameter name ...
