### ISSUE TITLE
`lr()`'s size argument can't consistently be applied to enclosed `mid()`

### ISSUE THREAD

**Issue by Leedehai** [typst/typst#3186]
### Description

```typ
$
  lr({ A mid(|) integral }) quad
  lr(size: #1em, { A mid(|) integral }) quad
  lr(size: #(1em+20%), { A mid(|) integral }) "wrong" \

  lr(] A mid(|) integral ]) quad
  lr(size: #1em, ] A mid(|) integral ]) quad
  lr(size: #(1em+20%), ] A mid(|) integral ]) "ok" \

  lr(( A mid(|) integral ]) quad
  lr(size: #1em, ( A mid(|) integral ]) quad
  lr(size: #(1em+20%), ( A mid(|) integral ]) "wrong"
$
```
<img width="278" alt="Screenshot 2024-01-12 at 20 28 44" src="https://github.com/typst/typst/assets/18319900/e00bce60-2c21-4901-8cfc-128148b9ec29">

### Typst version

- [x] I am using the latest version of Typst

**Comment by Leedehai** [comment]
It is _not_ that the `MidElem` element does not respect the enclosing `LrElem`'s `height`. In fact, the `MidElem` is scaled up using the same `height` value that was used to scale up the `LrElem`'s delimiters, and the computation of this `height` value did take the `size` argument into account:

https://github.com/typst/typst/blob/37249c20f793689b523cbb379f30b37466ca51b9/crates/typst/src/math/lr.rs#L56-L80

---

The root issue is actually that there are two levels of `LrElem` in `lr({ A mid(|) integral })` and `lr(size: #1em, { A mid(|) integral })`, respectively.

The outer `LrElem` is formed by the explicit `lr()` function call, and the inner `LrElem` is implicitly formed by the `{...}` delimiter pair. When the inner `LrElem` (which holds the `MidElem`) is being laid out, the outer `LrElem`'s `size` argument has no effect.

Also with this explanation, we can naturally understand
* `$ lr(size: #1em, ] A mid(|) integral ]) $` is okay because there's only one `LrElem` -- the one formed by the explicit `lr()` function, since the inner `] ... ]` isn't recognized as a delimiter pair that should form an implicit `LrElem`.
* `$ lr(size: #1em, ( A mid(|) integral ]) $` is not okay because there are two levels of `LrElem`: the outer one is formed by the explicit `lr()` function, and the inner one is formed implicitly by the `( ... ]` delimiter pair.

The same explanation also relates to https://github.com/typst/typst/issues/2979.

---
One may ask, "but this if-statement below should ensure the inner `LrElem`'s body will be pulled out and treated as the outer `LrElem`'s body":

https://github.com/typst/typst/blob/37249c20f793689b523cbb379f30b37466ca51b9/crates/typst/src/math/lr.rs#L42-L46

Yet, I can confirm with logging that `if let Some(elem) = body.to::<LrElem>()` was not triggered at all when rendering
```typ
$
lr({ A mid(|) integral }) \
lr(size: #auto, { A mid(|) integral }) \
lr(size: #1em, { A mid(|) integral })
$
```

**Comment by Leedehai** [comment]
It is _not_ that the `MidElem` element does not respect the enclosing `LrElem`'s `height`. In fact, the `MidElem` is scaled up using the same `height` value that was used to scale up the `LrElem`'s delimiters, and the computation of this `height` value did take the `size` argument into account:

https://github.com/typst/typst/blob/37249c20f793689b523cbb379f30b37466ca51b9/crates/typst/src/math/lr.rs#L56-L80

---

The root issue is actually that there are two levels of `LrElem` in `lr({ A mid(|) integral })` and `lr(size: #1em, { A mid(|) integral })`, respectively.

The outer `LrElem` is formed by the explicit `lr()` function call, and the inner `LrElem` is implicitly formed by the `{...}` delimiter pair. When the inner `LrElem` (which holds the `MidElem`) is being laid out, the outer `LrElem`'s `size` argument has no effect.

Also with this explanation, we can naturally understand
* `$ lr(size: #1em, ] A mid(|) integral ]) $` is okay because there's only one `LrElem` -- the one formed by the explicit `lr()` function, since the inner `] ... ]` isn't recognized as a delimiter pair that should form an implicit `LrElem`.
* `$ lr(size: #1em, ( A mid(|) integral ]) $` is not okay because there are two levels of `LrElem`: the outer one is formed by the explicit `lr()` function, and the inner one is formed implicitly by the `( ... ]` delimiter pair.

The same explanation also relates to https://github.com/typst/typst/issues/2979.

---
One may ask, "but this if-statement below should ensure the inner `LrElem`'s body will be pulled out and treated as the outer `LrElem`'s body":

https://github.com/typst/typst/blob/37249c20f793689b523cbb379f30b37466ca51b9/crates/typst/src/math/lr.rs#L42-L46

Yet, I can confirm with logging that `if let Some(elem) = body.to::<LrElem>()` was not triggered at all when rendering
```typ
$
lr({ A mid(|) integral }) \
lr(size: #auto, { A mid(|) integral }) \
lr(size: #1em, { A mid(|) integral })
$
```
Meaning `body.to::<LrElem>()` is false. In fact, printing `body.elem()` yields `Element(sequence)`.

**Comment by Leedehai** [comment]
It is _not_ that the `MidElem` element does not respect the enclosing `LrElem`'s `height`. In fact, the `MidElem` is scaled up using the same `height` value that was used to scale up the `LrElem`'s delimiters, and the computation of this `height` value did take the `size` argument into account:

https://github.com/typst/typst/blob/37249c20f793689b523cbb379f30b37466ca51b9/crates/typst/src/math/lr.rs#L56-L80

---

The root issue is actually that there are two levels of `LrElem` in `lr({ A mid(|) integral })` and `lr(size: #1em, { A mid(|) integral })`, respectively.

The outer `LrElem` is formed by the explicit `lr()` function call, and the inner `LrElem` is implicitly formed by the `{...}` delimiter pair. When the inner `LrElem` (which holds the `MidElem`) is being laid out, the outer `LrElem`'s `size` argument has no effect.

Also with this explanation, we can naturally understand
* `$ lr(size: #1em, ] A mid(|) integral ]) $` is okay because there's only one `LrElem` -- the one formed by the explicit `lr()` function, since the inner `] ... ]` isn't recognized as a delimiter pair that should form an implicit `LrElem`.
* `$ lr(size: #1em, ( A mid(|) integral ]) $` is not okay because there are two levels of `LrElem`: the outer one is formed by the explicit `lr()` function, and the inner one is formed implicitly by the `( ... ]` delimiter pair.

The same explanation also relates to https://github.com/typst/typst/issues/2979.

---
One may ask, "but this if-statement below should ensure the inner `LrElem`'s body will be pulled out and treated as the outer `LrElem`'s body":

https://github.com/typst/typst/blob/37249c20f793689b523cbb379f30b37466ca51b9/crates/typst/src/math/lr.rs#L42-L46

Yet, I can confirm with logging that `if let Some(elem) = body.to::<LrElem>()` was not triggered at all when rendering
```typ
$
lr({ A mid(|) integral }) \
lr(size: #auto, { A mid(|) integral }) \
lr(size: #1em, { A mid(|) integral })
$
```
...meaning `body.to::<LrElem>()` always returns `None`; in fact, printing `body.elem()` yields `Element(sequence)`.

**Comment by Enter-tainer** [comment]
We might have to disable inserting automatic `lr`s to solve this?

**Comment by Leedehai** [comment]
> IIUC, We will have to disable inserting `lr`s automatically to solve this?

Do you mean `lr({..})`, `lr((...])` should only result in one `LrElem`? Yeah.

I think it makes sense for the explicit `lr()` call to "absorb" the inner `LrElem` that is _implicit_ [1] and _touching-on-both-ends_ [2].

[1] counter example: `lr(lr(...))`
[2] counter examples: `lr(... {...})`, `lr((...) ...)`) e.g. `lr((sum_(i=0)^oo F_i(x)) |)_0^1`

---

btw, while an optional `size` argument for `MidElem` might be a useful feature, I don't think it's an ideal fix to this issue: it's really just a coverup of a deeper problem imo.

**Comment by Leedehai** [comment]
> Yet, I can confirm with logging that if let Some(elem) = body.to::<LrElem>() was not triggered at all when rendering
>
> $
> lr({ A mid(|) integral }) \
> lr(size: #auto, { A mid(|) integral }) \
> lr(size: #1em, { A mid(|) integral })
> $
> ...meaning body.to::<LrElem>() always returns None; in fact, printing body.elem() yields Element(sequence)

I'm confused about the intention of https://github.com/typst/typst/blob/37249c20f793689b523cbb379f30b37466ca51b9/crates/typst/src/math/lr.rs#L42-L46

What kind of typ code input will trigger this code path? If it's not triggered in any circumstance, maybe we should delete it? Maybe it not being triggered implies there's a bug in how math layout works?

**Comment by Leedehai** [comment]
Alternatively, do nothing, for it is actually working as intended. There's no promise broken.

After all, the first principle: Typst did promise that _matching delimiters will automatically form an LR_. Therefore, if one wants to, say, render a math set then they should just write `{...}` instead of wrapping it in an explicit `lr()` call like `lr({...})`, since the latter results in two levels of LR, as explained above, and the `{` and `}` braces will be stretched twice: once by the inner LR and once by the outer LR. Further, if one wants to use the `size` argument to adjust the height to say 1.2em, then they should write `lr(size: #1.2em, \{...\})`, where the backslashes disable automatic matching so this expression only results in one LR and the braces are stretched only once, and this `size` argument will take effect when stretching `mid` in the body.

I feel attempts to "improve" (like the aforementioned idea of letting the outer LR "absorb" the inner one on certain combination of conditions) will likely further complicate the matter, creating cognitive load for both future code readers as well as end users. Just stick to the first principle and all makes sense.

**Comment by Leedehai** [comment]
Alternatively, do nothing, for it is actually working as intended. There's no promise broken.

After all, the first principle: Typst did promise that _matching delimiters will automatically form an LR_. Therefore, if one wants to, say, render a math set then they should just write `{...}` instead of wrapping it in an explicit `lr()` call like `lr({...})`, since the latter results in two levels of LR, as explained above, and the `{` and `}` braces will be stretched twice: once by the inner, automatic LR and once by the outer, forced LR. Further, if one wants to use the `size` argument to adjust the height to say 1.2em, then they should write `lr(size: #1.2em, \{...\})`, where the backslashes disable automatic matching so this expression only results in one LR and the braces are stretched only once, and this `size` argument will take effect when stretching `mid` in the body.

I feel attempts to "improve" (like the aforementioned idea of letting the outer LR "absorb" the inner one on certain combination of conditions) will likely further complicate the matter, creating cognitive load for both future code readers as well as end users. Just stick to the first principle and all makes sense.

**Comment by Leedehai** [comment]
Alternatively, do nothing, for it is actually working as intended. There's no promise broken.

After all, the first principle: Typst did promise that _matching delimiters will automatically form an LR_. Therefore,
* If one wants to, say, render a math set then they should just write `{...}` instead of wrapping it in an explicit `lr()` call like `lr({...})`, since the latter results in two levels of LR, as explained above, and the `{` and `}` braces will be stretched twice: once by the inner, automatic LR and once by the outer, forced LR.
* Further, if one wants to use the `size` argument to adjust the height to say 1.2em, then they should write `lr(size: #1.2em, \{...\})`, where the backslashes disable automatic matching so this expression only results in one LR and the braces are stretched only once, and this `size` argument will take effect when stretching `mid` in the body.

I feel attempts to "improve" (like the aforementioned idea of letting the outer LR "absorb" the inner one on certain combination of conditions) will likely further complicate the matter, creating cognitive load for both future code readers as well as end users.

Just stick to the first principle and all makes sense, though we might want to add an explanation in the doc reminding users of the difference between `{..}` vs `lr({..})`.

**Comment by mkorje** [comment]
The culprit for this is actually here I think

https://github.com/typst/typst/blob/ca1f749c087bc19f6fbcebcd3ee34307959a95d5/crates/typst/src/math/lr.rs#L21-L33

This causes the inner `LrElem` to be wrapped inside a `Sequence`, which is the reason this code isn't working

https://github.com/typst/typst/blob/37249c20f793689b523cbb379f30b37466ca51b9/crates/typst/src/math/lr.rs#L42-L46
