### ISSUE TITLE
Bad italic correction with CJK characters

### ISSUE THREAD

**Issue by ChihHao-Su** [typst/typst#3189]
## Current behaviour
Given:
```typst
漢字_f_漢字
```
Output:
![圖片](https://github.com/typst/typst/assets/22293202/68487ca6-1478-4a47-b135-ca4542a8edad)

## Excepted behaviour
Given:
```typst
漢字_f_漢字
```
Output:
![圖片](https://github.com/typst/typst/assets/22293202/15354fba-c3e7-4bf2-98b6-cb60439377a5)

## Detail

If you're writing with Latin script, the combination of normal characters and emph-ed characters looks almost fine:

```typst
latin _f_ latin
```

![圖片](https://github.com/typst/typst/assets/22293202/1309747c-0959-4d8f-85df-b1a0185fe2b0)

But with CJK characters, the kerning between emph-ed Latin characters and normal CJK characters looks ugly:

```typst
漢字_f_漢字
```
![圖片](https://github.com/typst/typst/assets/22293202/52a85585-08d0-49f7-a271-1981e43771ae)

Emm. There should be a larger space between “f” and the last「漢字」。

I know that the reason of  the combination of normal Latin characters and emph-ed Latin characters looks nearly fine is, the typist has to add a space between the normal Latin characters and emph-ed Latin characters, or Typst won't treat the texts you want to be emph-ed as emph-ed text, like the image below. So, with a manually-typed space, the kerning looks OK.

```typst
// Doesn't work.
latin_f_latin
```
![圖片](https://github.com/typst/typst/assets/22293202/0bf0b6e8-99d8-401e-b564-74af626263fd)

But while typing Chinese and Japanese (or Vietnamese with Hán Nôm if someone willing to) texts, we cannot type a space between CJK characters and Latin characters, because these languages don't separate words with space like Korean or most of the language use Latin alphabets, and Typst will kern automatically between CJK characters and Latin characters. Typing a space between CJK characters and Latin words will lead to a larger kerning. Like:

```typst
漢字Latin漢字(1)

漢字 Latin 漢字(2)
```
![圖片](https://github.com/typst/typst/assets/22293202/d68c84ee-4297-4a73-83a3-cf89b5d7c53c)

Typst has the behaviour to kern Latin characters and Chinese characters automatically, so I believe it should be correct to let Typst handle the kerning, instead of type spaces between every CJK characters and Latin words by the typist.

But without typing a space between CJK characters and emph-ed Latin characters manually, the kerning looks bad. This is the problem. 

---------------

ps.: This is the result of doing the same thing with LaTeX and CTeX package:

![圖片](https://github.com/typst/typst/assets/22293202/402fd616-06f2-4487-ae87-78c6f37ad602)
![圖片](https://github.com/typst/typst/assets/22293202/03fd7627-a449-4405-a228-128020487759)

### Reproduction URL

https://typst.app/project/w6cekz9QgDnuiSvJQvzzL8

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
possiblely duplicate #1021 . this is not limited to cjk. it's a general thing: typst doesnt have italic correction now. so anything like this renders bad:

```
ff#emph[f]ff
```

**Comment by ChihHao-Su** [comment]
於 週六，2024-01-13 於 06:24 -0800，Wenzhuo Liu 提到：
> possiblely duplicate #1021 . this is not limited to cjk. it's a
> general thing: typst doesnt have italic correction now. so anything
> like this renders bad:
> ff#emph[f]ff
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

Emm, you're right.
