### ISSUE TITLE
Extend duration to include "years"

### ISSUE THREAD

**Issue by Eisit** [typst/typst#3196]
### Description

One can specify the [duration](https://typst.app/docs/reference/foundations/duration/) using weeks, days, hours, minutes and seconds. I would like years to be added.

### Use Case

When using Typst for a CV, it would allow to calculate and display my age and experiences [years] ago and have it update automatically.

Same thing with yearly reports.

And if, in the future, Typst syntax is used for webpages or other dynamic documents in place of Markdown, it would be useful.

Final point: it would feature-complete the Duration type.

**Comment by LaurenzV** [comment]
I don't think that's possible, the reason being that not every year has the same amount of days (which is also the reason why you don't have months as a duration, since some months have a different amount of days).

That's not specific to Typst, for example [timedelta in Pythong also only goes up to weeks](https://docs.python.org/3/library/datetime.html#timedelta-objects)

**Comment by Eisit** [comment]
Mathlab [uses 365.2425](https://ch.mathworks.com/help/matlab/ref/duration.years.html) (with rounding down).

In Python, most people use [dateutil](https://github.com/dateutil/dateutil/blob/master/src/dateutil/relativedelta.py). I'm too unfamiliar with Python to grasp what their code is doing to deal with leap years, and how much more "refined" it is compared with Mathlab's solution - it is definitely more complex.

**Comment by nineff** [comment]
typst uses Chrono, which also [does not provide a unit longer than weeks ](https://docs.rs/chrono/latest/chrono/struct.Duration.html). There, a week is defined as exactly 7 days of 24 hours each, which already might not fit every time-related usecase

**Comment by laurmaedje** [comment]
Since there isn't a well-defined definition, I think it's better to leave this to users to compute.
