### ISSUE TITLE
Rename `diff` symbol to `partial`

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#3210]
### Description

@dccsillag, @Leedehai, and @Enivex expressed their desire/agreement on renaming `diff` to `partial`. It looks like latex also has a built-in `partial` instead of `diff` (just for the comparison). You can find the full discussion here: https://discord.com/channels/1054443721975922748/1196918099069390850

I will add that `partial` is the most agreed upon, but this issue is for further discussion of potentially other names for this symbol.

There was also a talk about `dif` and `Dif`. Someone wanted to rename `dif` to `diff` (it also defined in the wrong place in Rust file). This also perhaps should be discussed here, as the names are very similar.

### Use Case

Better readability. Good examples are `gradient` and `integral` instead of `grad` and `int`.

**Comment by Andrew15-5** [comment]
The Unicode char is called "Partial Differential", so it can start from both "p" and "d", and "par" also will autocomplete the "partial".

https://symbl.cc/en/2202/

**Comment by Enivex** [comment]
I would add that
- The name is more semantic, readable, and an actual word
- It's called `\partial` in LaTeX
- Having both `dif` and `diff` separated by a single letter makes it look more like a typo than anything else. They're hard to distinguish at a glance.

(I would also like dif to be renamed diff, but that's a separate issue.)

**Comment by dccsillag** [comment]
The only thing I'd like to add here is that, much like how the name of the gradient symbol is nabla, the name of the partial derivative symbols is "del" (https://pt.wikipedia.org/wiki/Del). Just makes me wonder if we should do something similar to what we've done with `gradient`/`nabla`, by having the partial derivative symbol accessible both as `partial` and as `del`.
It's also worth mentioning that the same symbol can appear in other contexts, most notably perhaps in denoting the contour of a set.

Though I must say, if I had to choose one name then I'd certainly choose `partial`.

**Comment by Leedehai** [comment]
Please don't name it "del".. because the nabla symbol is also called "del".

**Comment by Atreyu-94** [comment]
> Please don't name it "del".. because the nabla symbol is also called "del".

Totally agree with you.

**Comment by dccsillag** [comment]
Then `partial` it is :smile:

**Comment by Enivex** [comment]
https://en.wikipedia.org/wiki/%E2%88%82

The symbol is variously referred to as "partial", "curly d", "funky d", "rounded d", "curved d", "dabba", "number 6 mirrored",[6] or "Jacobi's delta",[5] or as "**del**"[7] (but this name is also used for the "nabla" symbol ∇). It may also be pronounced simply "dee",[8] "partial dee",[9][10] "doh",[11][12] or "die".[13]

**Comment by dccsillag** [comment]
> The symbol is variously referred to as "partial", "curly d", "funky d", "rounded d", "curved d", "dabba", "number 6 mirrored",[6] or "Jacobi's delta",[5] or as "del"[7] (but this name is also used for the "nabla" symbol ∇). It may also be pronounced simply "dee",[8] "partial dee",[9][10] "doh",[11][12] or "die".[13]

Argh, how it pains me that "number 6 mirrorred" is listed as a more common name than "del"!

**Comment by Enivex** [comment]
> Argh, how it pains me that "number 6 mirrorred" is listed as a more common name than "del"!

I'm not sure Wikipedia is a great authority here :p
