### ISSUE TITLE
Failed to parse XML (XML with DTD detected)

### ISSUE THREAD

**Issue by Myriad-Dreamin** [typst/typst#3215]
### Description

When I compile my some document with typst in main branch, the compiler raises a compile error that isn't raised in typst v0.10.0. The error tells that `xml` function will not support to parse theme file, since there is a dtd in the xml file. I believe it is not intended.

```
error: failed to parse XML (XML with DTD detected)
  ┌─ test.typ:1:5
  │
1 │ #xml("./tokyo-night.tmTheme")
  │      ^^^^^^^^^^^^^^^^^^^^^^^

```

== Reproducution

Invokes `xml` on the theme file.

```typ
#xml("./tokyo-night.tmTheme")
```

[tokyo-night.zip](https://github.com/typst/typst/files/13966901/tokyo-night.zip)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
https://docs.rs/roxmltree/latest/roxmltree/struct.ParsingOptions.html#structfield.allow_dtd

Maybe set this to true should fix this. Interestingly this is `false` in past roxmltree versions.

**Comment by Enter-tainer** [comment]
https://github.com/typst/typst/commit/2f2dd179385b4e78fcfb0a38aafc433cbb86b10a update happens in this commit

**Comment by Enter-tainer** [comment]
https://github.com/RazrFalcon/roxmltree/blob/master/CHANGELOG.md#fixed @Myriad-Dreamin previously it passes parser because it is a bug. 🤣
