### ISSUE TITLE
Audio/multimedia embeds in pdfs

### ISSUE THREAD

**Issue by xd009642** [typst/typst#3218]
### Description

 Just wondering if there's the ability to embed audio in slides? Something like the multimedia package in beamer

### Use Case

To enable media in presentations

**Comment by LaurenzV** [comment]
That's not possible at the moment, unfortunately.

**Comment by Enivex** [comment]
While this is about multimedia in general, I'll close it in favor of the existing issue https://github.com/typst/typst/issues/955
