### ISSUE TITLE
Incremental reparsing is not efficient enough

### ISSUE THREAD

**Issue by user202729** [typst/typst#322]
I'm taking an example...

```
#let f(x) = {
for i in range(x) {
}
}
#f(3000000)
#f(3000000)
#f(3000000)
#f(3000000)
```

In incremental compilation mode, if a function call `f()` is added, it takes a long time to compile. So is prepending something like `a` to the function calls.

I thought because all functions are pure, they can just be cached and computed only once?

Meanwhile something like `fib()` memoization works perfectly well:

```
#let fib(i) = {
if i < 2 { i } else { fib(i -1) + fib(i -2) }
}
#fib(60)
```

**Comment by SekoiaTree** [comment]
Some functions are not pure, such as counters: https://typst.app/docs/reference/meta/state/

**Comment by user202729** [comment]
> Notable fact
In Typst, all functions are pure. This means that for the same arguments, they always return the same result. They cannot "remember" things to produce another value when they are called a second time.

From https://typst.app/docs/reference/types/function/.

In this case, the function that returns the [content] *themselves* are pure. Only the rendering of the [content] is not pure.

**Comment by SekoiaTree** [comment]
Fair enough!

**Comment by laurmaedje** [comment]
It's pretty roundabout, but this is actually an incremental _parsing_ issue that is relatively easy to resolve. The parser has a bug where it reparses the whole file sometimes if you enter a newline (like you do for each function call), which changes the span information of the function f (used for error reporting), which in turn makes memoized results unusable.

**Comment by laurmaedje** [comment]
I've improved the reparsing algorithm a bit. There is still room for further improvement, but it is not a bug.
