### ISSUE TITLE
Possibility to embed PDF, EPS graphic files in Typst documents solicited 

### ISSUE THREAD

**Issue by PEWOLO** [typst/typst#3223]
Is this a way to embed EPS, PDF graphic file into Typst documents?

**Comment by Enter-tainer** [comment]
not directly, you need convert them to svg

**Comment by Enter-tainer** [comment]
i believe there is already an issue tracking this

**Comment by PEWOLO** [comment]
#Enter-tainer, Thank you so much!

**Comment by LaurenzV** [comment]
See also #145.
