### ISSUE TITLE
Incorrect hyphenation in situations including dashes for some languages (e.g. polish)

### ISSUE THREAD

**Issue by jakubkaczor** [typst/typst#3235]
### Description

In some languages—in polish[1], for example—while dividing a phrase consisted of words joined with a hyphen, it is required to split it on the hyphen, leaving it at the end of the line, but also to repeat it in the beginning of a new line. Typst doesn't do it. A minimal example is the following.

```typst
#set text(lang: "pl")
#set par(justify: true)

#{100 * [biało-czerwony ]}
```

![Incorrect compilation results.](https://github.com/typst/typst/assets/57760986/3b714bce-0d3b-4b4b-ab4c-e2d210e63496)

The correct hyphenation would be
```
biało-
-czerwony
```

---

I wasn't sure whether it should be a bug, or a feature report. I settled on a bug caused by the missing feature.

---

1: https://web.archive.org/web/20240120154340/https://www.ortograf.pl/zasady-pisowni/lacznik-zasady-pisowni

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by jakubkaczor** [comment]
I would also like to link the [English documentation for the LaTeX polski package](https://texdoc.org/serve/polski/0) providing LaTeX macros for working around this issue. It also defines macros for en-dash (`ppauza`) and em-dash (`pauza`), as there are additional rules regarding them, such as forbidding breaking a line before them.

**Comment by Omikhleia** [comment]
Just for the sharing in return, after seeing this, SILE implemented the intended behavior for Polish in [v0.14.15](https://sile-typesetter.org/blog/release-v0.14.15/).

On our way, we discussed and referenced (but left unaddressed for now, at the time I'm writing this message) [which other languages](https://github.com/sile-typesetter/sile/issues/1963) could have the same feature, i.e. (possibly) Czech, Slovak, Portuguese, Spanish and Basque.

Just to be real clear here (one never knows), my intent is to share information back -- not to brag about what SILE does or not -- in the open-minded spirit that we all need to have good solutions for language-specific concerns.

**Comment by tomas-vl** [comment]
I can confirm that this behavior is desired in Czech, Slovak, Lower Sorbian (probably also Upper Sorbian), and Croatian as well, as described in their orthographic manuals (i.e. _Pravidla českého pravopisu_, _Pravidlá slovenského pravopisu_, _[Dolnoserbski pšawopis](https://dolnoserbski.de/ortografija/psawidla/K3)_, _[Hrvatski pravopis](http://pravopis.hr/pravilo/spojnica/68/)_):
- Czech: _Jestliže se rozdělují části slova nebo výrazů, mezi nimiž se píše spojovník, do dvou řádků, píše se spojovník na konci řádku i na začátku řádku následujícího._ (If parts of a word or a phrase between which a hyphen are divided into two lines, the hyphen shall appear at the end of the line and the beginning of the following line.)
- Slovak: _Ak zložené slová písané so spojovníkom rozdeľujeme na mieste tohto rozdeľovacieho znamienka, spojovník píšeme na konci prvého aj na začiatku nasledujúceho riadka (spojovník zopakujeme)._ (If compound words containing a hyphen are hyphenated in place of the hyphen, the hyphen is written both at the end of the first line and at the beginning of the next line (the hyphen is repeated).)
- Lower Sorbian: _Mit Bindestrich zusammengesetzte Wörter werden so getrennt, daß der Bindestrich der Zusammensetzung gleichzeitig Silbentrennungszeichen ist. Er kann aber auch zu Beginn der folgenden Zeile vor dem ersten Buchstaben stehen._ (Compound words are hyphenated in such a way that the hyphen of the compound is also the hyphenation mark. It can also be placed at the beginning of the following line before the first letter.) (Excuse my German translation, please.)
- Croatian: _Ako se riječi koje se pišu sa spojnicom ipak prenose u novi redak, spojnica se zapisuje i na početku novoga retka._ (If words containing a hyphen are split on a new line, the hyphen is also written at the beginning of the new line.)

**Comment by gabriel-araujjo** [comment]
Portuguese grammar also has this hyphenation particularity.

Below I bring some examples and their respective fonts.

> When separating words with hyphens, where the line break coincides with a hyphen, it is important to repeat the dash at the beginning of the next line. Examples: 
>
> *  Guarda-/-chuva
> * Micro-/-ondas
> * Anti-/-inflamatório[^2]

[^2]: https://plataforma.hexag.online/blog-noticias/translineacao-o-que-e

> **How to hyphenate words that already have a hyphen?**
>
> _Can you put two hyphens? Does this exist?_
> 
> The answer is yes!
> 
> It works like this:
> 
> 
> Existem jovens pobres, que puxam as mangas, trabalham, e se tornam bem-
> -sucedidos na vida. E também existem jovens que, dentro da família, são mal-
> -acostumados e acabam não se esforçando e não tendo sucesso.
> 
>
> One hyphen is on the top line and another on the bottom line![^3]

[^3]: https://guiadoestudante.abril.com.br/redacao/saiba-o-que-e-translineacao-e-como-aplicar-na-redacao

> When the word already has a hyphen, and it occurs at the end of a line, the hyphen is repeated at the begining of the next line: deu-/-te; arco-/-da-/-velha; cor-/-de-/-rosa.[^1]

[^1]: https://www.jn.pt/artes/dossiers/portugues-atual/regras-de-translineacao-3291887.html/

**Comment by gabriel-araujjo** [comment]
In Spanish we must repeat the hyphen too, according to the RAE[^1].

> ##### § 4.1.1.1.2
>
> e) Cuando, al dividir un compuesto o cualquier otra expresión formada por varias palabras unidas con guion (v. § [4.1.1.2](https://www.rae.es/ortograf%C3%ADa/como-signo-de-uni%C3%B3n-entre-palabras-u-otros-elementos#4.1.1.2)), este signo coincida con el final de línea, deberá escribirse otro guion al comienzo del renglón siguiente: léxico-/ -semántico, crédito-/ -vivienda, calidad-/-precio. Con ello se evita que quien lee pueda considerar que la palabra o expresión dividida se escribe sin guion.
>

... except when the next word is capitalized. E.g.: Ruiz-/ Giménez must not repeat the hyphen on the next line.

> La repetición del guion a comienzo de línea es innecesaria en el caso de los antropónimos y topónimos compuestos, ya que la mayúscula inicial del segundo componente indica de forma suficiente que el guion no es meramente indicativo de final de línea: Ruiz-/ Giménez no podría interpretarse más que como la partición de Ruiz-Giménez, y nunca de ⊗‍RuizGiménez, pues, como se indica en el capítulo IV, § [4.3.1](https://www.rae.es/ortograf%C3%ADa/uso-combinado-de-may%C3%BAsculas-y-min%C3%BAsculas-en-siglas-y-acr%C3%B3nimos#4.3.1) y [5.2](https://www.rae.es/ortograf%C3%ADa/marcas-comerciales#5.2), la mayúscula intercalada no se usa en español más allá de siglas y nombres comerciales.

[^1]: https://www.rae.es/ortografía/como-signo-de-división-de-palabras-a-final-de-línea
