### ISSUE TITLE
The width of spaces should be 1em in Japanese

### ISSUE THREAD

**Issue by satori-project** [typst/typst#3240]
### Description

In Japanese, `？` and `！` followed by a sentence, a space is inserted after mark.
The size of this space character **should be 1em**.
(ref. https://www.w3.org/TR/jlreq/?lang=en#positioning_of_dividing_punctuation_marks)

However, even with `　`(U+3000), the compiled result will show proportional spaces.

Is it possible to fix the width of the `　`(U+3000)?

**Comment by Enter-tainer** [comment]
U+3000 is considered as "space" in https://github.com/typst/typst/blob/main/crates/typst/src/layout/inline/shaping.rs#L980 . So it becomes adjustable 🤔

**Comment by Enter-tainer** [comment]
remove this might fix this problem but idk what might happen. For this specific case, i guess using `#box[　]` should fix it? I don't know if this works

**Comment by satori-project** [comment]
> BTW, the referenced jlreq page shows a vertical layout. Does this also applied to horizontal ones?

The jlreq page 2.3.2 describes the major differences between horizontal and vertical.
Apparently there is no reference to question marks or exclamation marks there.

I perused several books on Japanese horizontal typography, and most of them seem to say that "(especially for exclamation marks) full-width spaces look a little too open".
In short, "make it look like U+3000" seems to be the correct way to format horizontally.

Then it is apparently not very sensible to fix the width of the space.

**Comment by Enivex** [comment]
Your link seems to be specifically for text layout on the web

**Comment by Enter-tainer** [comment]
> Your link seems to be specifically for text layout on the web

not really. the chinese support in typst mainly follows clreq, which is very similar to jlreq

**Comment by peng1999** [comment]
> Then it is apparently not very sensible to fix the width of the space.

Can you elaborate that? Why fixing the width will not help?

**Comment by satori-project** [comment]
> Can you elaborate that? Why fixing the width will not help?

What I meant was that if the width of `　`(U+3000) was fixed to be the same as the original width(=1em), it would be too wide (especially for exclamation marks).
Fixing it to 0.5em is not a bad choice.

> I think we should make U+3000 as an exception.

I agree with you.

**Comment by laurmaedje** [comment]
Related: 
- https://github.com/typst/typst/issues/2861
- https://github.com/typst/typst/issues/524

We need a general decision for these situations. As I see it, there are three options:
1. Keep it as-is
2. Convert to plain whitespace and issue a warning for such spaces
3. Respect all such spaces

I'm leaning towards 3. We would then only lex a plain ASCII space and the Unicode line breaks as a `Space` token (anything else I'm missing?).

There is the concern from https://github.com/typst/typst/issues/2861#issuecomment-1839594807:

> Distinguishing between symbols that look literally identical unless you're using a hex editor is a bit problematic. Do people actually use raw non-breaking spaces?

However, there are already various invisible non-whitespace Unicode codepoints you can put into your Typst document that are respected, so I think highlighting potentially confusing codepoints should be seen as an editor feature (and VS Code has this feature).
