### ISSUE TITLE
Support bibliography names containing slashes

### ISSUE THREAD

**Issue by 01mf02** [typst/typst#3251]
### Description

I have a bibliography file in BibTeX format that contains entries from [DBLP](https://dblp.org/), which look like this:

~~~
@article{DBLP:journals/bstj/Ritchie84, ...}
~~~

In Typst, I cannot find a way to reference such entries, probably because they contain slashes:

~~~
error: unclosed label
   ┌─ spec.typ:36:64
   │
36 │ UNIX has popularised the concept of *filters* and *pipes* #cite(<DBLP:journals/bstj/Ritchie84>):
   │                                                                 ^^^^^^^^^^^^^^

~~~

Before that, I tried `@DBLP:journals/bstj/Ritchie84`, but to no avail.

It would be great if Typst could support bibliographic entries with slashes in their names!

### Use Case

Anybody using bibliography items with slashes in their names will love this. :)

**Comment by Enter-tainer** [comment]
try `#cite(label("DBLP:journals/bstj/Ritchie84"))`

https://typst.app/docs/reference/foundations/label/

**Comment by 01mf02** [comment]
Thanks @Enter-tainer, this worked perfectly! :)

Just out of curiosity, is the source code of the documentation online somewhere? I considered making a little PR for the [documentation of `cite`](https://typst.app/docs/reference/model/cite/) to help future me, but I could not find its source ...

**Comment by 01mf02** [comment]
Amazing --- thank you again!
