### ISSUE TITLE
Specifying pdf opener does not work on macOS

### ISSUE THREAD

**Issue by patricorgi** [typst/typst#3255]
### Description
My default pdf viewer is set to Preview.app which is a native app on macOS, and I have no intention to change this...On the other hand, I want to use `zathura` when watching a typst project.

I have tried the following

```bash
typst watch main.typ --open zathura # -> no pdf viewer opened
typst watch main.typ --open $(which zathura) # -> no pdf viewer opened
typst watch main.typ --open # -> default OS pdf viewer opened (Preview.app in this case)
``` 
They all print out the following message in terminal, and no error is shown.

```
watching main.typ
writing to main.pdf

[21:09:21] compiled successfully in 3.30s
```

However, I can open this `main.pdf` file fine in `zathura` with

```bash
zathura main.pdf
```

### Reproduction URL

1. Install zathura on macOS using homebrew
```bash
brew tap zegervdv/zathura
brew install zathura
```

2. Create a `main.typ` file with the following content

```typst
#lorem(69)
```

3. Try `typst watch` with default opener (Preview.app in this case)

```bash
typst watch main.typ --open
```
This will compile and open the compiled `main.pdf` file in the default pdf viewer.

4. Try `typst watch` by specifying `zathura`

```bash
typst watch main.typ --open $(which zathura)
```

Nothing will happen after a successful compilation.

5. Try opening `main.pdf` directly with `zathura`

```bash
zathura main.pdf
```
This will open `main.pdf` in `zathura` without any problem.

### Operating system

macOS 14.2.1 (23C71)

### Typst version

0.10.0

**Comment by noamzaks** [comment]
Hey, so I investigated this a little bit 😁

It seems this is a "problem" with the `open` crate, or with macOS, or with `zathura` - take your pick.

Typst simply runs
```rust
if let Some(app) = open {
    open::with_in_background(path, app);
} else {
    open::that_in_background(path);
}
```
(This is from compile.rs in typst-cli)

In the `open` library, we can see that executes the following command on macOS: `open main.pdf -a /opt/homebrew/bin/zathura`

And this fails:
```
The application /opt/homebrew/bin/zathura cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10811 "kLSNotAnApplicationErr: Item needs to be an application, but is not" UserInfo={_LSLine=4129, _LSFunction=_LSOpenStuffCallLocal}
```

Therefore, I think the best solution to this issue is in the zathura homebrew package (not in Typst and not in open-rs), and this will probably be solved alongside this issue there: https://github.com/zegervdv/homebrew-zathura/issues/78.

**Comment by laurmaedje** [comment]
Thanks for investigating! I'll close this then.

**Comment by patricorgi** [comment]
Thanks a ton for investigating! There is still possibility to solve this on the typst side. That's to allow arbitrary opener in addition to the `open` command. 

Typst has the great potential to replace LaTeX in the future, and I'm super excited about, but we have to admit that majority of LaTeX users will still remain in their comfort zone at the moment. Allowing extra flexibility is the key to attract more people.

**Comment by noamzaks** [comment]
That seems doable to me (although I haven't contributed anything yet), with something like an `--on-success="zathura main.pdf"`, but does that make sense? Wouldn't you just want to open up zathura yourself in that case (or use a shell script)?

**Comment by noamzaks** [comment]
This could probably be related to #3362.

**Comment by patricorgi** [comment]
Before typst allows custom opener or zathura homebrew package adapt to the `open -a <Application>` on macOS, an easy solution is to use Automator.cpp to create an "Application" type workflow, which is essentially a wrapper to perform the `/opt/homebrew/bin/zathura document.pdf` shell command. Then you can save it as a `Zathura.app` file. At last, specify the opener pointing to this `Zathura.app`. In principle, it should work...
