### ISSUE TITLE
sym.aleph should correspond to "Alef Symbol" U+2135 (ℵ) in math, and not "Hebrew Letter Alef" U+05D0 (א)

### ISSUE THREAD

**Issue by Enivex** [typst/typst#3263]
### Description

See title.

I discovered this due to a question on the Discord. U+2135 is the one actually present in math fonts. Currently typst is always falling back to a hebrew text font if aleph is used in math, because no conversion from U+05d0 is done.

### Typst version

- [X] I am using the latest version of Typst

**Comment by MDLC01** [comment]
There is also:
- U+2136 ℶ BET SYMBOL,
- U+2137 ℷ GIMEL SYMBOL, and
- U+2138 ℸ DALET SYMBOL.

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/3375
