### ISSUE TITLE
Rectangles or gradients with negative widths not rendered in PDFs

### ISSUE THREAD

**Issue by Quantumplation** [typst/typst#3265]
### Description

It is convenient when rendering rectangles (or other shapes) to set a starting position, and then calculate the width by reference to two other values; If this width is positive, it will extend to the right, and if negative, it will extend to the left.

For example, see the diagram below, where we calculate the widths by `t_1 - t_2` and `t_2 - t_1` respectively:

![image](https://github.com/typst/typst/assets/49870/e198d9fb-7794-44ea-b25b-a8c8726aef58)

This renders correctly in the web view, or in the vs code preview; however, the negative width rectangles don't appear in the rendered PDF:

![image](https://github.com/typst/typst/assets/49870/55e328ae-7ead-466e-a8c8-ebc8b1cd7e1b)

(the lack of gradient is a separate issue, but already being discussed in #2546)

Here's the example code to generate these diagrams:
```typst
      #let timeline(x_1, x_2, ms: 20em, buffer: 10em, color: rgb(0%, 80%, 0%)) = [
        #set align(center)
        #place(dx: 0pt, dy: 0pt, line(start: (0em, 0em), length: 100%))

        #place(dx: 0pt, dy: 0pt, line(start: (x_1, -5pt), end: (x_1, 5pt)))
        #place(dx: x_1 - 0.25em, dy: 8pt, [$t_1$])

        #place(dx: 0pt, dy: 0pt, line(start: (x_2, -5pt), end: (x_2, 5pt)))
        #place(dx: x_2 - 0.25em, dy: 8pt, [$t_2$])
        #place(dx: x_1, dy: -5pt, rect(width: x_2 - x_1, height: 10pt, fill: rgb(0%, 0%, 0%, 40%)))

        #let x_3 = x_1 + ms
        #let x_4 = x_2 + ms
        #place(dx: 0pt, dy: 0pt, line(start: (x_3, -5pt), end: (x_3, 5pt)))
        #place(dx: x_3 - 1.4em, dy: 8pt, [$t_1+#raw("ms")$])
        #place(dx: 0pt, dy: 0pt, line(start: (x_4, -5pt), end: (x_4, 5pt)))
        #place(dx: x_4 - 1.4em, dy: 8pt, [$t_2+#raw("ms")$])

        #let x_5 = x_3 + buffer
        #let x_6 = x_4 - buffer
        #place(dx: 0pt, dy: 0pt, line(start: (x_5, -5pt), end: (x_5, 16pt)))
        #place(dx: x_5 - 2.8em, dy: 20pt, [$t_1+#raw("ms")+#raw("buffer")$])

        #let c = rgb(color).components()
        // Points before this are valid
        #place(dx: x_5, dy: -5pt,
          rect(
            width: x_1 - x_2,
            height: 10pt,
            fill: gradient.linear(
              (rgb(c.at(0), c.at(1), c.at(2), 40%), 0%),
              (rgb(c.at(0), c.at(1), c.at(2), 0%), 100%),
            ),
          )
        )

        #place(dx: 0pt, dy: 0pt, line(start: (x_6, -5pt), end: (x_6, 16pt)))
        #place(dx: x_6 - 2.8em, dy: 20pt, [$t_2+#raw("ms")-#raw("buffer")$])
        // Points after this are valid
        #place(dx: x_6, dy: -5pt,
          rect(
            width: x_2 - x_1,
            height: 10pt,
            fill: gradient.linear(
              (rgb(c.at(0), c.at(1), c.at(2), 40%), 0%),
              (rgb(c.at(0), c.at(1), c.at(2), 0%), 100%),
            ),
          )
        )

      ]
```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Relevant code (PDF):

https://github.com/typst/typst/blob/afc28264e8f9b495a7ec290d52275e5099be7ac8/crates/typst-pdf/src/page.rs#L783-L789

Relevant code (Raster):

https://github.com/typst/typst/blob/afc28264e8f9b495a7ec290d52275e5099be7ac8/crates/typst-render/src/lib.rs#L574-L579

**Comment by PgBiel** [comment]
I think this indicates it's not yet clear whether this is a bug or a feature... :eyes: 

Should we allow negative width rectangles?

In principle, I'm in favor unless there's some significant technical restriction. Though I also think using negative lengths could interact with the layout engine in other unexpected ways, so that's something to consider in terms of consistency. But, for this particular case, I don't see why we shouldn't support it unless PDF really doesn't support it for some fundamental reason. (We could also just "simulate" it if needed by flipping the rectangle, I guess?)

**Comment by Quantumplation** [comment]
(as a side note, Typst is the most fun I've had in a long time, it's absolutely fantastic how much "just works"!! Thank you so much for building such a great piece of software.)

**Comment by Enivex** [comment]
> I think this indicates it's not yet clear whether this is a bug or a feature... 👀

It would be a bug regardless if the result depends on the output format

**Comment by Dherse** [comment]
Those plots are beautiful 🥰
