### ISSUE TITLE
Feature Request: use typst to make wonderful slides

### ISSUE THREAD

**Issue by gilgamsh** [typst/typst#327]
in latex, *beamer* provide the supports for making professional-looking and wonderful slides. Maybe add this type of support will make this project more influential. Provides functionality that completely replaces latex.

**Comment by SekoiaTree** [comment]
https://github.com/andreasKroepelin/typst-slides

How about this template?

**Comment by gilgamsh** [comment]
Thank you very much.

**Comment by gilgamsh** [comment]
> https://github.com/andreasKroepelin/typst-slides
> 
> How about this template?
Thank you very much.

**Comment by gilgamsh** [comment]
> https://github.com/andreasKroepelin/typst-slides
> 
> How about this template?

Thank you very much.

**Comment by laurmaedje** [comment]
Closing this as its implemented in packages like [polylux](https://github.com/andreasKroepelin/polylux).
