### ISSUE TITLE
Figure not setting supplement by type

### ISSUE THREAD

**Issue by pank-su** [typst/typst#3273]
### Description

```typst
set figure(supplement: "Image")

show figure.where(kind: table): set figure(supplement: "qweqweqweqweq")
```

All default supplement will be images.

### Operating system

Linux

### Typst version

- [ ] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This is due to https://github.com/typst/typst/issues/2459. It will likely be fixed in the next release.
