### ISSUE TITLE
Incorrect baseline for symbols in math environments

### ISSUE THREAD

**Issue by LCarmi** [typst/typst#3274]
### Description

Hi there,
I'd like to highlight the following difference in baselines when displaying symbols in normal text mode versus their behavior in math mode.

```typst
`New Computer Modern`:
#sym.triangle.t
#sym.triangle.b

`New Computer Modern Math` behavior:
#text(font:"New Computer Modern Math", sym.triangle.t)
#text(font:"New Computer Modern Math", sym.triangle.b)

Math behavior:
$#sym.triangle.t$
$#sym.triangle.b$

Math, overriding font with `New Computer Modern`:
$#text(font:"New Computer Modern", sym.triangle.t)$
$#text(font:"New Computer Modern", sym.triangle.b)$
```

![image](https://github.com/typst/typst/assets/10350036/3caa7c1f-2c91-4130-9e31-dccde0ec6008)

FYI, i run similar tests in latex and the behavior of the corresponding `\blacktriangle` and `\blacktriangledown` are correct, i.e. the two triangles are aligned. A MWE (XeLaTeX compiler) can be seen here: https://www.overleaf.com/3294838571yctsdwkwscxv#46d486

Copy pasting the symbols "▲, ▼" in https://www.fontspace.com/latin-modern-math-font-f86521 does instead confirm that the font does have unaligned symbols (I could only find a _Latin Modern Math_ font though)

May it be the case of something similar to #1620 ?
Unfortunately, I don't know if any other symbols are affected by a similar behavior.

### Reproduction URL

https://typst.app/project/wYudY2eGuHEEOEjH3tfMuB

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
are they the same symbol? the overleaf one shows a filled triangle and it's outlined on typst's side

**Comment by LCarmi** [comment]
Oh, sorry for that. I updated both the typst document and the overleaf to have a full overview. Results that the behavior in typst is the same with the filled triangles. Latex is instead less coherent, as shown in the following images:
pdfTeX/XeLaTeX (default font)
![image](https://github.com/typst/typst/assets/10350036/0a17156e-1466-4612-9ba8-98b50b6223de)
XeLaTeX (changing font to `New Computer Modern`)
![image](https://github.com/typst/typst/assets/10350036/8aa67fe9-20c4-47ac-b481-fee6a2345230)

Latex code used:
```latex
\documentclass{article}
\usepackage[default]{fontsetup} % should activate new computer modern
\usepackage{amsmath,amssymb}
\usepackage{hyperref}

\title{Triangle test}

\begin{document}

\maketitle


Copy paste unicode: $△ ▽ ▲ ▼$

Triangle outlines: $\triangle \triangledown \bigtriangleup \bigtriangledown$

Filled triangles: $\blacktriangle \blacktriangledown$

\end{document}
```
At this point I don't know if this to be considered a bug or not, as I suspect that LaTeX is fixing the baselines inside its macros.

My current workaround is to define custom symbols and use them in both text and math mode to achieve the desired effect:
```typst
#let triangle = {text(font: "New Computer Modern", sym.triangle.t)}
#let triangledown = {text(font: "New Computer Modern", sym.triangle.b)}
#triangle, $#triangle$
```

**Comment by Enivex** [comment]
Are you sure the fonts you are specifying are being used? Use `fallback: false` when investigating things like this

**Comment by LCarmi** [comment]
Thanks for your suggestion. You are right, the symbols are not taken from the specified font, but from the fallback font.
I have updated my script to:
```typst
// default text, no fallback
#set text(font: "Linux Libertine", size: 18pt, fallback: false)
// default math text, no fallback
#show math.equation: set text(font: "New Computer Modern Math", fallback: false)

== Outlined and filled

#let symbols = [#sym.triangle.t #sym.triangle.b, #sym.triangle.filled.t #sym.triangle.filled.b]

Default: #symbols

`Linux Libertine`:
#text(font: "Linux Libertine", symbols)

`New Computer Modern`:
#text(font: "New Computer Modern", symbols)

`New Computer Modern Math` behavior:
#text(font:"New Computer Modern Math", symbols)

`Computer Modern`:
#text(font:"Computer Modern", symbols)

`Computer Modern Math`:
#text(font:"Computer Modern Math", symbols)

Default math:
$#symbols$

Math, forcing `New Computer Modern`:
$#text(font:"New Computer Modern", symbols)$
```

which prints:
![image](https://github.com/typst/typst/assets/10350036/c37c8782-5a87-4471-8e88-5c7524acb5ef)

From which we can infer that the aligned triangles I was looking for are from "Linux Libertine", which has a matching math font "Libertinus Math".
Selecting the either font when showing the symbols as follows
```
#show sym.triangle.t: set text(font: "Libertinus Math")
#show sym.triangle.b: set text(font: "Libertinus Math")
#show sym.triangle.filled.t: set text(font: "Libertinus Math")
#show sym.triangle.filled.b: set text(font: "Libertinus Math")
```
correctly prints them in both text and math as expected. This is good enough of a tradeoff for me in this case, I don't know if there is anything to do typst-side as this behavior depends on the glyphs in the fonts.

From what I understood scanning the docs and running some tests, there is no selector that is able to select all symbols or to select all `sym.triangle.*`, which may make this workaround verbose in other situations. Let me know if I'm wrong and something smarter can be done here :) Thanks
