### ISSUE TITLE
Destructuring in a for loop header has misleading error message when the value being looped is not iterable

### ISSUE THREAD

**Issue by SillyFreak** [typst/typst#3275]
### Description

Compare these two snippets attempting to loop over an integer (error messages inlined):
```typ
// error: cannot loop over integer
#for value in 1 {}
//            ^

// error: cannot destructure values of integer
#for (x, y) in 1 {}
//   ^^^^^^
```

In both snippets, the problem is that integers can't be looped over, but in the second case the error message is misleading, as it suggests that the problem only occurs after a value was already successfully extracted. This is of course not likely to happen with integers, but `arguments` values have the same problem: "cannot destructure values of arguments".

For comparison, this is the error when iterating over an array whose elements aren't pairs of values:

```typ
// error: cannot destructure integer
#for (x, y) in (1,) {}
//   ^^^^^^
```

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/3308
