### ISSUE TITLE
Footnote entry depends on whether there is page content coming from outer scope

### ISSUE THREAD

**Issue by jakubkaczor** [typst/typst#3276]
### Description

I expect the formatting of a footnote entry not to depend on whether there is some content on a page coming from the scope outside the smallest scope containing a `footnote` call, but in the following example, the opposite appears to happen.

```typst
// Make the background of SVG output white to increase legibility on dark themed websites
#set page(fill: white)

#let example() = {
    set align(center)
    [*Example*]
    footnote[Example text.]
}

// On this page, the footnote entry *IS* centered
#example()

#pagebreak()

// On this page, the footnote entry is *NOT* centered
Some text.
#example()

#pagebreak()

// On this page, the footnote entry is *NOT* centered
#example()
Some text.

#pagebreak()

// On this page, the footnote entry, again, *IS* centered
#example()
```

This code results in the following.

![example-page-1](https://github.com/typst/typst/assets/57760986/e09162f0-3d12-4863-9f96-24b28a4ef6d1)
![example-page-2](https://github.com/typst/typst/assets/57760986/82dc7e49-a9c3-43fb-aef4-e3b067fced2a)
![example-page-3](https://github.com/typst/typst/assets/57760986/faba3f56-e036-4daf-85c2-4b74521a6db1)
![example-page-4](https://github.com/typst/typst/assets/57760986/8fd795ab-1a79-4010-ada0-b3b804a8ddf4)

---

Additionally, I expect the footnote entry not to be affected by the formatting applied in the scope of a `footnote` call, unless this is the outermost scope.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
I've edited the title of https://github.com/typst/typst/issues/241 to include this case.
