### ISSUE TITLE
Missing kerning in some maths element-functions

### ISSUE THREAD

**Issue by lumi-a** [typst/typst#3279]
### Description

In some element-functions, e.g. `attach` or `vec`, no kerning is applied. In other element-functions, such as `lr` or `sqrt`, it's rendered correctly. For example, in this formula, the first three terms have proper kerning in `0+-x`, but the last two don't:
```typst
$0+-x #h(1em) sin(0+-x) #h(1em) sqrt(0+-x) #h(2em) a^(0+-x) #h(1em) vec(0+-x)$
```
![image](https://github.com/typst/typst/assets/151774547/ab6919c5-b2bb-42f9-a9d4-f5925f5c018b)

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This is actually intentional and inherited from LaTeX. This spacing-less style is called "cramped" in the TeX book and is automatically applied to exponents.

For vectors/matrices, it is the same in Typst, but I'm actually not sure whether it works that way in LaTeX.
