### ISSUE TITLE
Drawing cancelling arrow in mathematical formula

### ISSUE THREAD

**Issue by psads-git** [typst/typst#3292]
### Discussed in https://github.com/typst/typst/discussions/3241

<div type='discussions-op-text'>

<sup>Originally posted by **psads-git** January 22, 2024</sup>
Can `typst` reproduce the following? Thanks!

![image](https://github.com/typst/typst/assets/75945439/f3523b7c-f237-4958-91fa-6dabc1369ff4)

</div>

Since I have not got any answer, I believe it is not implemented. So, I would like to suggest its implementation. (In LaTeX, package [cancel](https://ctan.org/pkg/cancel?lang=en) does that.)

**Comment by psads-git** [comment]
I am using 

`Evince` is a simple document viewer for GNOME

However, in `Okular`, the navigation side pane appears.

Strange!

**Comment by Enivex** [comment]
Typst already has https://typst.app/docs/reference/math/cancel/ . The version with an arrow seems obscure enough that this would likely fit better as a package.

**Comment by laurmaedje** [comment]
I'll close this as not planned then as tracking package requests is out of scope for this issue tracker.

**Comment by Andrew15-5** [comment]
This was mentioned in https://forum.typst.app/t/is-there-an-equivalent-to-latexs-cancelto-in-typst/536/6.
