### ISSUE TITLE
Inconsiscencies about show rules and use of spaces

### ISSUE THREAD

**Issue by Totoro83** [typst/typst#3296]
### Description

I find quite strange that spaces in show rules are very inconsistent depending on what they have before or after.
An example:
```typst
#show "Test ": "This will be expanded only if not followed by an alphanumeric symbol "

Test working

Test 0 working

Test - not working

Test : not working

#show ": ": "This will never work"

Not: working

#show " :": "And this neither"

Not :working
```
The first show rule is working only if the space is followed by something like an alphanumeric character. A symbol will break it. And rules where symbols are preceded or followed by a space won't ever work. Am I missing something?

### Reproduction URL

https://typst.app/project/rvPtRiPiQhTOsc4vkpDbIo

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Dherse** [comment]
This is more an error that multiple token (`:` being a separate token from ` `) are not grouped together.
I'm pretty sure this is a duplicate, but I can't find the original issue so I'll leave this one open.

**Comment by frozolotl** [comment]
Related issue: #86

**Comment by Dherse** [comment]
Thanks, closing in favour of #86 then.
