### ISSUE TITLE
Add the reference syntax like c++ and rust reference

### ISSUE THREAD

**Issue by 0warning0error** [typst/typst#3298]
### Description

I checked many times and found that there is no reference syntax, which make it not easy to operate on the variables in place. I know typst is more like a funtional programming language, but I think there should be a syntax about reference since there are in-place functions like `array.insert` , `array.remove` and so on.
If there is already a syntax about reference, I am sorry.

### Use Case

```typst
#let replace(&array,n,i) = {
    let _ = array.remove(n)
    array.insert(n,i)
}
#{
    let array = (1,2,3,4,5,6,7)
    replace(array,2,99)
    array
}
```
or
```typst
#let replace(array,n,i) = {
    let _ = array.remove(n)
    array.insert(n,i)
}
#{
    let array = (1,2,3,4,5,6,7)
    replace(&array,2,99)
    array
}
```
the result should be (1,2,99,4,5,6,7) rather than (1,2,3,4,5,6,7).
If there is a reference syntax, we can write functions and concentrate more on the abstract level rather than copy the processes one after another.

**Comment by user202729** [comment]
https://typst.app//docs/reference/foundations/array#definitions-insert here?

**Comment by Enter-tainer** [comment]
typst function are pure functions, so you cannot do that

**Comment by laurmaedje** [comment]
As an addition: There is just a small set of built-in types that expose mutable methods at all and rather than adding more language features to work with them, we're searching for ways to also get rid of those without losing the convenience they bring.
