### ISSUE TITLE
Prime symbol should be typeset in the script position

### ISSUE THREAD

**Issue by jassler** [typst/typst#3299]
### Description

In math mode the prime symbol `'` is currently rendered above operators like `>`, `<`, `>=`, `succ`, `succ.approx`, etc.

<img width="664" alt="Primes are rendered above comparators, but can be circumvented using the scripts function" src="https://github.com/typst/typst/assets/24298790/7e105405-83fb-446e-83a2-b5e1ed3f8c79">

After mentioning this unexpected behavior [here](https://github.com/typst/typst/issues/3043#issuecomment-1915244184), PgSuper explained that this can be prevented with `scripts(>)'` (and the opposite can be achieved with `limits(>)`).
@Enivex mentioned, however, that this might be unintended behavior and that "primes should always be typeset in the script position."

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
@MDLC01 On second thought, I sort of agree with you. I'm closing this, but will reopen #2070 to restart discussion.

**Comment by jassler** [comment]
@MDLC01 
Ah, I forgot to include closed issues in my search, thank you for pointing it out.

It might be possible that it shouldn't happen with comparators. At least, I haven't encountered this in any book or publication. My guess is that it was added so that arrows can come with text attached above, like in `$x ->^t y$`.
