### ISSUE TITLE
Not printing math

### ISSUE THREAD

**Issue by gvalmont** [typst/typst#3314]
### Description

Printer : Triumph Adler 5057i

- Using default math font, it prints numbers but not letters
- Using custom math font, it prints nothing
- Using an unknown math font, it prints everything

Typst :
```
#block()[
  Default - Default $2 x = 5$
]
#block()[
  #set text(font: "Source Sans Pro")
  Source Sans Pro - Default $2 x = 5$
]
#block()[
  #set text(font: "Asana Math")
  Asana Math - Default $2 x = 5$
]
#block()[
  #set text(font: "Source Sans Pro")
  #show math.equation: set text(font: "Asana Math")
  Source Sans Pro - Asana $2 x = 5$
]
#block()[
  #set text(font: "Source Sans Pro")
  #show math.equation: set text(font: "STIX Two Math")
  Source Sans Pro - STIX Two Math $2 x = 5$
]
#block()[
  #set text(font: "Source Sans Pro")
  #show math.equation: set text(font: "Not a font")
  Source Sans Pro - Not a font $2 x = 5$
]
```

[output.pdf](https://github.com/typst/typst/files/14124550/output.pdf)
[print.pdf](https://github.com/typst/typst/files/14124552/print.pdf)

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by MDLC01** [comment]
I'm having similar issues with a [Toshiba e-STUDIO3015AC](https://toshibatec.ca/products/e-studio3015ac/).

**Comment by LaurenzV** [comment]
Printing math issues _should_ be solved now on main with our new subsetter (although it's worth noting that it's most likely a bug in the printer that causes this), feel free to test it out if you can.

**Comment by MDLC01** [comment]
After testing on a document compiled with `main`, I was unable to notice any issue with the printer I mentioned above!
