### ISSUE TITLE
Rearrange pages in PDF output

### ISSUE THREAD

**Issue by segfaultsourcery** [typst/typst#332]
There's one feature I couldn't find. Can I rearrange pages? I would like to print a pamphlet on two sides of the same paper, and for that reason I would like the pages to be 4, 1, 2, 3. Do you (or will you) support rearranging pages in this manner?

![image](https://user-images.githubusercontent.com/5004848/227767662-aa144a56-8403-4292-802e-11c47618e8a5.png)

(Image source and more information: https://www.loc.gov/collections/broadsides-and-other-printed-ephemera/articles-and-essays/page-order-and-folding-diagrams/ )

**Comment by alerque** [comment]
c.f #187

**Comment by laurmaedje** [comment]
This is out of scope for Typst. However, it can easily be done with other tools in a pre-print workflow.
