### ISSUE TITLE
Improve confusing error message: missing argument

### ISSUE THREAD

**Issue by Kaligule** [typst/typst#3329]
### Description

Trying to use named arguments when positional arguments are expected leads to confusing error messages.

## Example

I want to take a slice of an array. I look at the [documentation for `array.slice`](https://typst.app/docs/reference/foundations/array/#definitions-slice) and find it takes the arguments `start` and `end`. I tend to use named arguments, so I write:

```typ
successes = successes.slice(start: 0, end: 2)                                                                                        !
```

I get the following error message:
![Screenshot_2024-02-02_22:29:36](https://github.com/typst/typst/assets/3586246/10fdc0b6-82eb-462e-891f-58ed6b4312ec)

My confusion is immense. It says `Missing argument: start` and underlines the exact point where I specified an argument of that very name.

## what I did wrong

The solution is to not use named arguments but positional arguments, as the function expects.

```typ
successes = successes.slice(0, 2)                                                                                                     !
```

The fact that these arguments are positional is in the documentation, but easy to miss.

## What typst could do better here

The main problem here is that the error message is not helpful.
It should be something like:

> Missed positional arguments (at least 2 were expected)

or even better:

> Missed _positional_ argument `start`
> help: There is a _named_ argument of that name, but the function expects a _positional_ argument for name)                                                                                                     

### Use Case

Confusing error messages are frustrating, especially for non-programmers.

**Comment by laurmaedje** [comment]
Yes, this error message is pretty horrible! We should definitely fix it.

**Comment by Leedehai** [comment]
I think this was already fixed by https://github.com/typst/typst/commit/2007f30b1137eec20678e3e9cd96788dc6c1b222 and the commit is part of 0.10.0. I can confirm with
```typ
#let numbers = (1,2,3)
#numbers.slice(start: 0, end: 2)
```
```
$ typst --version
typst 0.10.0 (70ca0d25)
$ typst compile test.typ
error: the argument `start` is positional
  ┌─ test.typ:2:15
  │
2 │ #numbers.slice(start: 0, end: 2)
  │                ^^^^^^^^
  │
  = hint: try removing `start:`
```

**Comment by laurmaedje** [comment]
Oh, it was even me who implemented it! My memory is getting worse by the day...

**Comment by Kaligule** [comment]
Awesome, thanks.
