### ISSUE TITLE
Implement word breaking for asian languages

### ISSUE THREAD

**Issue by whs** [typst/typst#335]
It seems that Typst do not break long words that are not space-separated.

For example

```
ซัพพลายเออร์โหงวฮาโลวีนอุปัทวเหตุยนตรกรรมแบคโฮแมชีนเลิฟรีดไถมัฟฟินรูบิกเฟรชชี่ซะพรีเมียมเสกสรรค์คันธาระช็อคก๊วนวานิลลาเลดี้โพสต์วอล์คทรูว้อดก้าชีสฮองเฮาริกเตอร์ป๋อหลอราชบัณฑิตยสถานแอปพริคอทซาฟารีโบกี้แบคโฮผ้าห่มวอเตอร์ละอ่อนยิวธัมโมสารขัณฑ์เทคไคลแม็กซ์ฮัลโลวีนแมชชีนสไลด์ภควัทคีตากิฟท์ทอล์คโปรเจ็กเตอร์สงบสุขโปรเจ็กเตอร์แชมเปญรวมมิตรไคลแมกซ์พาร์ตเนอร์ทอร์นาโดกาญจน์คาเฟ่ศึกษาศาสตร์เอ๋ฟลุตแทคติค

ปิกอัพโปรโมทแมนชั่นคอมพ์กุนซือเป่ายิ้งฉุบอิ่มแปร้ไฮแจ็คไฮกุสหรัฐนายแบบหม่านโถวแทกติคแคทวอล์คทอล์คฮิปฮอปคอนแท็คเกมส์อิสรชนเลคเชอร์ไบโอทริปการันตีเปราะบางท็อปบูตบลูเบอร์รีแจ็กพ็อตบิ๊กวอลนัทรีวิวคาแรคเตอร์เปราะบางดีพาร์ตเมนต์ฟลุทปาสเตอร์อุปการคุณสะกอมบอร์ดไฟลต์เซ่นไหว้แมคเคอเรลเบอร์เกอร์โลโก้ไนท์ชาร์ป

เบอร์รีไฮกุราเมนไวอะกร้าสคริปต์สะบึมส์โอเวอร์เอ็นทรานซ์ช็อปปิ้งชีสไวอากร้าอินดอร์คาร์เคลมเห่ยจอหงวนเมจิคสเกตช์สะบึมส์สตาร์นายพรานอิกัวนาวอล์กแบล็กคอปเตอร์พอเพียงซีนเซ็นทรัลอุปการคุณลาตินกราวนด์ก่อนหน้าเฟรชปฏิสัมพันธ์เอ็กซ์โปโดนัทยะเยือกแอดมิสชันซะตังค์คอปเตอร์เกรย์ตัวเองอมาตยาธิปไตยป๋าโบว์ปฏิสัมพันธ์เซนเซอร์อีสเตอร์เบนโล

ทีวีตรวจทานนอร์ทแฟรีเลคเชอร์โกลด์อัลบัมเชอร์รี่เย้วสโตร์กฤษณ์เคลมเยอบีร่าพ่อค้าบลูเบอร์รี่สหัสวรรษโฮปแคนูโยโย่จูนสตรอว์เบอร์รีซื่อบื้อเยนแบ็กโฮเป็นไงโดนัททอมสเตริโอแคนูวิทย์แดรี่โดนัทวิทย์แอปพริคอทเซอร์ไพรส์ไฮบริดกิฟท์อินเตอร์โซนเซอร์วิสเทียมทานโคโยตี้ม็อบเที่ยงคืนบุญคุณ

อาว์แฟนตาซีซูเอี๋ยพิซซ่ารวมมิตรแอสเตอร์ควีนเลดี้เกจิคาปูชิโนเอ๋อิสรชนช็อปเปอร์อ่วมติงต๊องซิตี้เฟรชสหัชญาณห่วยวาทกรรมไตรมาสทอล์คติวบอมบ์ดั๊มพ์อวอร์ดง่าวซัมเมอร์สะกอมวอล์คขั้นตอนแมนชั่นเพนตากอนท็อปบู๊ทลอจิสติกส์สัมนาวิลล์อุปนายิกาซีนแตงโมตรวจสอบคัตเอาต์เซนเซอร์รีไซเคิลม็อบสารขัณฑ์ฮาโลวีน
```

Is rendered as

![image](https://user-images.githubusercontent.com/345483/227774739-f34ee903-b038-4b1a-8b75-274e199e44ac.png)

Expected result (note that the input text above has all space removed, which is not the case here)

![image](https://user-images.githubusercontent.com/345483/227774762-99d32867-4bcc-4237-9a17-3f32f516bd6d.png)

Version tested:
Typst Web Application
Deployed on 2023-03-25T14:41:51.218Z
Typst compiler version: d0782b18530c1c3767764129e60b47a81696b163

**Comment by laurmaedje** [comment]
@peng1999 You wrote "Fix https://github.com/typst/typst/issues/1009, https://github.com/typst/typst/issues/335" in https://github.com/typst/typst/pull/1355, but the later fix wasn't detected by GitHub. Can we close this?

**Comment by peng1999** [comment]
> @peng1999 You wrote "Fix #1009, #335" in #1355, but the later fix wasn't detected by GitHub. Can we close this?

I don't speak Thai. So it would better to let someone who knows Thai to confirm it. Maybe @whs ?

**Comment by whs** [comment]
![image](https://github.com/typst/typst/assets/345483/539febf4-cdda-44c2-a180-9b2338ec5fa8)

```
Typst Web Application

Deployed on 2023-09-04T14:43:05.952Z
Copyright © 2022—2023 Typst
Typst compiler version: da8367e189b02918a8fe1a98fd3059fd11a82cd9
```

Result looks almost right. There's no splitting mid-word but there are still splitting in the middle of compound word. I think it would be the artifact of the dictionaryless splitting system?

For example, the last word of the second to last line of the first paragraph is ทอร์นาโด (tornado)

```
...ทอร์นา
โด
```

which is like the English

```
torna
do
```

**Comment by laurmaedje** [comment]
Closing this for now as baseline support has now been there for a while. Further improvements could be discussed in separate issues.

**Comment by pacaunt** [comment]
> ![image](https://private-user-images.githubusercontent.com/345483/266057081-539febf4-cdda-44c2-a180-9b2338ec5fa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzg4ODMsIm5iZiI6MTcxNzIzODU4MywicGF0aCI6Ii8zNDU0ODMvMjY2MDU3MDgxLTUzOWZlYmY0LWNkZGEtNDRjMi1hMTgwLTliMjMzOGVjNWZhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMVQxMDQzMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGRmZDg3NWYxOTlmYzQ1Njk0MjkyNjU5N2FkNjliYzczNGYyNjcwOTJiZTU1NmEzODNmYTY1OWM4MjRjMTY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4tZnigd08Kw49Hm-n8_gdVr0300iQ8ml1v5D-a_EA9Y)
> 
> ```
> Typst Web Application
> 
> Deployed on 2023-09-04T14:43:05.952Z
> Copyright © 2022—2023 Typst
> Typst compiler version: da8367e189b02918a8fe1a98fd3059fd11a82cd9
> ```
> 
> Result looks almost right. There's no splitting mid-word but there are still splitting in the middle of compound word. I think it would be the artifact of the dictionaryless splitting system?
> 
> For example, the last word of the second to last line of the first paragraph is ทอร์นาโด (tornado)
> 
> ```
> ...ทอร์นา
> โด
> ```
> 
> which is like the English
> 
> ```
> ...torna
> do
> ```

Mid-word separation is still present; that is "แมนชั {linebreak} ชั่น" as "mans {linebreak} ion" in the third line from last.
