### ISSUE TITLE
`block` spacing is not always 'weak' in multi-column

### ISSUE THREAD

**Issue by avonmoll** [typst/typst#3355]
### Description

Sometimes, when a block-style equation is the last thing in a column, the spacing (from `block`) is added to the top of the subsequent column.

MWE:

```js
#set page(
  paper: "a5",
)

#show math.equation: set block(spacing: 0.65em)
#show: columns.with(2, gutter: 5mm)

#lorem(140)
$ 1 + 1 = 2 $
#lorem(100)
```

Screenshot:
![image](https://github.com/typst/typst/assets/4260850/ae180eeb-fb14-4e37-b1c4-36cd0c9432a1)

Expected result:
For the top of column 2 to be aligned with the top of column 1.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
It doesn't seem related to the actual number `0.65em`, because even "#show math.equation: set block(spacing: 0em)" will trigger it.

**Comment by laurmaedje** [comment]
Not reproducible anymore after https://github.com/typst/typst/pull/4212. I will investigate further whether this actually fixed it or whether it's just this particular case.

**Comment by laurmaedje** [comment]
Minimized reproduction for before #4212:
```typ
#block(width: 100%, height: 650pt, fill: aqua)
#metadata(none)
#v(2cm, weak: true)
Hi
```

**Comment by laurmaedje** [comment]
Turns out the cause was very specific to how metadata was handled before. Basically it generated an empty sticky frame, which forces the spacing after it to migrate into the next region with it. Not relevant anymore. Opened https://github.com/typst/typst/pull/4499 to ensure it doesn't regress in the future.
