### ISSUE TITLE
Multi-select Files for Batch Operations in typst.app

### ISSUE THREAD

**Issue by ruziniuuuuu** [typst/typst#3358]
### Description

When working with multiple files in [typst.app](typst.app), I noticed that it's not possible to multi-select files using the `Ctrl` and `Shift` keys, a feature that is quite handy in Overleaf for performing batch operations like deleting or moving files. This functionality greatly improves workflow efficiency when dealing with numerous files.

Could you please consider adding a feature that allows users to multi-select files for batch processing? This addition would greatly benefit users who need to manage large numbers of files within the app.

### Use Case

I want to move multiple files from one folder to another folder.
![image](https://github.com/typst/typst/assets/54934297/5e2535ef-6766-4bf4-bdd3-45103ace0338)

**Comment by PgBiel** [comment]
I believe you meant to open this in https://github.com/typst/webapp-issues

Though maintainers should be able to transfer it there

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/webapp-issues/issues/272
