### ISSUE TITLE
Custom watch command with variables

### ISSUE THREAD

**Issue by nishanthkarthik** [typst/typst#3362]
### Description

Hi, thank you for creating a super-snappy tool for writing math. Is there any way for me to customize the watch command with additional variables like page number?

### Use Case

I would like `typst watch --open="okular --page=%p"` to work such that okular automatically sticks to the page that was most recently touched by the typst build.

---

For the moment I run `echo notes.pdf | entr okular --unique --noraise --page 2 /_` in a different terminal. This at least prevents okular from going back to the first page when the PDF is rebuilt.

**Comment by Enter-tainer** [comment]
unless okular expose such control api, it's hard to do this. BTW, the official webapp and the (unofficial) vscode extension typst-preview support bi-directional jump between source code and doc

**Comment by nishanthkarthik** [comment]
Okular does expose `--page` to set the current visible page on an already running window. My feature request would be for typst to

1. support templating in watch command
2. expose `%p` as the page number that returns the approximate position of the diff

While the VSCode extension is great, I'd love for this to be provided in a platform/editor agnostic way similar to #1152's principle.

**Comment by nishanthkarthik** [comment]
Ah! Does that mean `typst watch` runs the pdf viewer in the background and signals nothing more on incremental builds? Although this is very specific to okular and mupdf, `typst watch` could take two command line arguments - one for the initial startup and one for subsequent updates.

For okular, the incremental command would be `okular --unique --noraise --page %p` and for mupdf, it would be a `pkill SIGHUP mupdf`.

**Comment by Enter-tainer** [comment]
The idea of "post build script" is interesting.

Another tricky thing is how to determine "the page that was most recently touched by the typst build". For example, if you have an outline in your document, that page will be updated whenever you change headings. So you will jump to outline page. IIUC this shouldn't be desired.

**Comment by Enter-tainer** [comment]
I remember there is a bunch of pdf viewers that (a) reload fast when pdf file changes (b) preserve scroll position when reloading. Although I forget their names 😆, will these viewers solve this issue?

**Comment by nishanthkarthik** [comment]
That's a good point. Perhaps we could make a distinction and find the last user-defined syntax node that has been rendered? I'd imagine the ToC/outline would be auto-generated typically.

Alternatively, we could find the last page with a changed syntax node. This isn't leakproof because one could add a citation and that would make the PDF jump to the last page.

Hmm... this does feel like something https://github.com/nvarner/typst-lsp should be able to do with ease - it would already have the cursor position and the _last touched node_ from a text editor so it is simpler in theory to map to a page number.

**Comment by nishanthkarthik** [comment]
> I remember there is a bunch of pdf viewers that (a) reload fast when pdf file changes (b) preserve scroll position when reloading. Although I forget their names 😆, will these viewers solve this issue?

I have had good experiences with both evince and okular when I used a similar setup for LaTeX. Okular doesn't seem to remember the page number and zoom level + position for typst pdfs though - I don't know if it is a recent bug in okular.

**Comment by Enter-tainer** [comment]
> it would already have the cursor position and the last touched node from a text editor so it is simpler in theory to map to a page number.

text may not always maps to a single page number. It may maps to 0/1/many pages in some cases, for example: 
- 0: editing comments
- 1: editing normal markup
- many: adding page decorations, outlines, references ...
> Okular doesn't seem to remember the page number and zoom level + position for typst pdfs though - I don't know if it is a recent bug in okular

That's very interesting. it works for latex generated pdf but not for typst generated ones?

**Comment by Enter-tainer** [comment]
> The points you mention are equally valid for LaTeX code too - my current cursor could be on a macro definition or comments. Yet, Kile works well enough.

just want to mention such page number thing is impossible to be perfect. The webapp and vsc extension mentioned earlier can do element level positioning but also suffers from these problems.

> Re okular: I'll give this a try and find if it is okular or my memory that's buggy :)

I just searched on discord and people saying okular, mupdf, zathura and sumatraPDF are recommended. I dont use them though, so I can tell which one is the best.

**Comment by laurmaedje** [comment]
I think deeper integration with PDF viewers is out of scope for the Typst CLI. That's what LSPs and the web app are for. PDF viewer integrations would always be able to do just a fraction of what these can do anyway.
