### ISSUE TITLE
Large numbers in JSON lead to overflow

### ISSUE THREAD

**Issue by NorfairKing** [typst/typst#3363]
### Description

Use this typst code:

```
#let bignum = json("big.json")

#bignum
```

with this json file:

```
18446744073709551615
```

(This is $2^{64}-1$)

and see:
![wat](https://github.com/typst/typst/assets/3521180/4dc96352-f077-494f-a5bc-923e97d51ccc)

### Operating system

Linux

### Typst version

Using `typst-0.9.0`

**Comment by laurmaedje** [comment]
Typst uses 64 bit signed integers, which can't represent that number.

**Comment by NorfairKing** [comment]
@laurmaedje JSON allows for arbitrarily-sized numbers, so `i64` is definitely not big enough.
Using `18446744073709551615.0` is also invalid because it loses precision and is rendered as `1.8446744073709552e19`.

How would you suggest displaying json values in a PDF?

**Comment by Enter-tainer** [comment]
> JSON allows for arbitrarily-sized numbers

Or is it? https://datatracker.ietf.org/doc/html/rfc7159#section-6

**Comment by laurmaedje** [comment]
Problematic code is here: https://github.com/typst/typst/blob/70b354e887cf735db070f766e4812357dddb8a40/crates/typst/src/foundations/int.rs#L264

We should probably cast to a float instead if it exceeds integer bounds (this in line with the linked RFC from my understanding). There's not much we can do about the precision loss.

**Comment by Enter-tainer** [comment]
> We should probably cast to a float instead if it exceeds integer bounds

This is not free. I'd argue not do this. as the rfc stated f64 is actually have a smaller range when accurately representing integers

**Comment by Enivex** [comment]
If it's just for display purposes, wouldn't a string containing the decimal representation be a possibility?

**Comment by NorfairKing** [comment]
> If it's just for display purposes, wouldn't a string containing the decimal representation be a possibility?

Yes but the data isn't a string, it's a number.

**Comment by Enivex** [comment]
> > If it's just for display purposes, wouldn't a string containing the decimal representation be a possibility?
> 
> Yes but the data isn't a string, it's a number.

Typst uses only signed integers, which means the largest integer it can represent is 2^63 - 1.

**Comment by NorfairKing** [comment]
@Enivex I guess then the only thing to do here is to document that typst cannot roundtrip arbitrary json.
I think it's fine for this to be "broken as intended" but I was hoping there might come to be a separate "arbitrarily sized number" type.

**Comment by Enter-tainer** [comment]
serde has a [feature flag](https://github.com/serde-rs/json/blob/master/Cargo.toml#L75) which enables arbitrary precision numbers. When it is enabled, numbers will become `serde_json::Number`, which stores a https://docs.rs/serde_json/latest/src/serde_json/number.rs.html#73, representing the arbitrary precision number.

**Comment by Enivex** [comment]
> @Enivex I guess then the only thing to do here is to document that typst cannot roundtrip arbitrary json.
> I think it's fine for this to be "broken as intended" but I was hoping there might come to be a separate "arbitrarily sized number" type.

Actual integers larger than 64 bits sound like scope creep for a typesetting system. Plenty of "real" programming languages do not have them either.

I don't think stringification is an unusual solution in this situation?

(That being said, once we have custom types I'm sure someone will create a package for arbitrary precision.)

**Comment by PgBiel** [comment]
> Actual integers larger than 64 bits sound like scope creep for a typesetting system. Plenty of "real" programming languages do not have them either.

To be fair, they could be quite useful in math environments. For instance, displaying some large factorial value.

**Comment by Enivex** [comment]
> > Actual integers larger than 64 bits sound like scope creep for a typesetting system. Plenty of "real" programming languages do not have them either.
> 
> To be fair, they could be quite useful in math environments. For instance, displaying some large factorial value.
> 

Just displaying the decimal representation of a number doesn't require typst to have native big integer support, unless you also want typst to actually compute the factorial.

While nice, it just seems _very_ niche to me.

(And could be a package already today)

**Comment by uben0** [comment]
Maybe, all decoding functions should offer an optional argument `fallback` which is a function receiving the string that cannot be parsed. Example:

```typst
#json("hello.json", fallback: (kind, input) =>
    panic("not handling edge case " + kind + " " + input)
)
```
```
error: panicked with "not handling edge case bid-int 18446744073709551615"
```
