### ISSUE TITLE
How to implement the same functionality as \newtheorem in LaTex

### ISSUE THREAD

**Issue by lsl00** [typst/typst#337]
As the title says,in Latex you can define new mathematical environment like lemma :\newtheorem{lemma}{Lemma}.

Even you can attach a counter like:\newtheorem{lemma}{Lemma}[section].

And you can also add label to it ,then reference it.

**Comment by sahasatvik** [comment]
I've been trying to script this, but the counters don't quite work the way I want them to! Specifically, I'd like the "corollary" and "proof" counters to be attached to the "theorem/lemma" counter, but the trailing number doesn't update - see Corollaries following Theorem 1.2 in the preview. I'd like them to go 1.2.1, 1.2.2, 1.2.3. Annoyingly, the attachment works here only after the first theorem - see Proofs following Theorem 1.1.1. I think #325 would help a lot here.

Project [here](https://typst.app/project/r1UlcF66DEj8F8x5Fj5pms).

![download](https://user-images.githubusercontent.com/16478483/227808437-fc85ea62-e425-475c-938b-fab938dea3d5.png)

**Comment by sahasatvik** [comment]
Update: I managed to make this work, using a rather hacky manipulation of `state` (thanks to @laurmaedje !)
Once again, the complete solution is in [this project](https://typst.app/project/r1UlcF66DEj8F8x5Fj5pms).

**Comment by lsl00** [comment]
> Update: I managed to make this work, using a rather hacky manipulation of `state` (thanks to @laurmaedje !) Once again, the complete solution is in [this project](https://typst.app/project/r1UlcF66DEj8F8x5Fj5pms).

A nice work!

**Comment by taooceros** [comment]
I am a little bit query can we do cross reference to theorem? I couldn't find a good way to create label on the thmbox

**Comment by SeniorMars** [comment]
I will port my latex template soonish, I hope that typst gets more extensive because I love these new projects.

**Comment by taooceros** [comment]
> That's true; currently I'm using a messy `state` instead of a `counter` to keep track of the numbering. I'll try and implement proper labeling later. Feel free to open an issue at [typst-theorems](https://github.com/sahasatvik/typst-theorems)!
> 
> Update: A basic from of labeling/referencing for these theorem environments is up; see the [example here](https://github.com/sahasatvik/typst-theorems#examples).

Thanks! This is very nice

**Comment by laurmaedje** [comment]
This is a bit broad for an issue, so I'm gonna close this.
