### ISSUE TITLE
Scientific Notation

### ISSUE THREAD

**Issue by ecstrema** [typst/typst#3372]
### Description

In many fields, we use scientific notation to represent quantities. This is the case for most of physics, electronics, aerospatial, and a lot of other fields of research.

But, writing $1.6 \cdot 10^{12}$ with `1.6 dot 10^12` is quite verbose and that's why most programming languages have a shorter way of writing such things. You can write `1.6e12` or `1.6E12` in all the following programming languages: 
C, C++, Java, JavaScript, MATLAB, Julia, Ruby, Perl, Swift, Go, Rust, Fortran, and probably way more.

Now, although having support for such constructs in typst code blocks would be nice, the primary reason for my request here is to have that construct available in math blocks.

That means that typing `1.6e12` would be rendered exactly the same way as if I had typed `1.6 dot 10^12`

To put it in typst terms, the _dedicated syntax_ for scientific notation in typst would be `ReR` where `R` is a Real Number.

The regexp would look like something like this: `[0-9\.,]+[e|E][0-9\.,]+`

Finally, and one important point, this is *_not_* a breaking change, since `1.6e12` currently errors with `unknown variable: e12`. This means this change won't affect any existing code.

### Use Case

Here are some examples, and, how they should be rendered:

```typst
The Planck constant is apprimately $6.626e34$
```

The Planck constant is apprimately $6.626 \cdot 10^{34}$

```typst
The energy in one electron-volt (eV) is calculated with 

$
1 V dot e = 1 J / C dot 1.602e-19 C = 1.602e-19 J = 1eV
$
```

The energy in one electron-volt (eV) is calculated with 

$1V\cdot e = 1 \frac{J}{C} \cdot 1.602 \cdot 10^{-19} C = 1.602 \cdot 10^{-19} J = 1eV$

**Comment by Enter-tainer** [comment]
i believe you can make a package to do this. and this doesnt require changing typst itself.

**Comment by Enter-tainer** [comment]
quick & dirty code here:
```typ
#set page(height: auto, width: auto)

#let parse(x) = {
  let (b, e) = x.split(("e")).map(float)
  $#b dot 10^#e $
}

#parse("1e5")

$a+sqrt(#parse("5e-7"))$
```

<img width="441" alt="image" src="https://github.com/typst/typst/assets/25521218/c4ad4330-b443-41f5-a371-7dcc59b3a334">

**Comment by ecstrema** [comment]
Inputting `#num("1e5")` instead of `10 dot 10^5` seems like no gain to me. 

Ideally, It would be defined by default. I'm checking if I can use show rules for that.

**Comment by Enivex** [comment]
> 1.6 dot 10^12 is quite verbose 
Is it though? I really don't see the problem, especially in a typesetting system.

I'd argue that the main reason programming languages use `1.6e12` is that it's a numeric literal (the compiler / interpreter isn't literally doing the multiplication 1.6 * 10^12).

This sounds like a parsing nightmare to me. We need **less** whitespace dependent behavior in math, not more.

**Comment by ecstrema** [comment]
> > 1.6 dot 10^12 is quite verbose
> 
> Is it though? I really don't see the problem, especially in a typesetting system.

There are shortcuts for common things, and this is one of the most useful I've had since highschool. Even on paper, writing `6.626e-34` is easier than `6.626 * 10^34`

> I'd argue that the main reason programming languages use `1.6e12` is that it's a numeric literal (the compiler / interpreter isn't literally doing the multiplication 1.6 * 10^12).

Well typst too isn't doing the multiplication, it's typesetting system. And we want that typesetting system to be as fast and convenient to write. 

And convenience in writing is why it was added to every other language.

> This sounds like a parsing nightmare to me. We need **less** whitespace dependent behavior in math, not more.

A parsing nightmare doesn't have such a simple regex. `(0-9\.,)+[e|E](0-9\.,)+`

**Comment by Enivex** [comment]
> A parsing nightmare doesn't have such a simple regex. (0-9\.,)+[e|E](0-9\.,)+

You can't actually use a regex that simple though, so that's not a point in its favor.

> Finally, and one important point, this is not a breaking change, since 1.6e12 currently errors with unknown variable: e12. This means this change won't affect any existing code.

Only because you haven't defined a variable e12. What if I want `e1` `e2` and `e3` for the standard unit vectors?


> `1.602e-19 `

The number e is widely used in math, and this currently renders as 
![image](https://github.com/typst/typst/assets/2191754/66dd5ad2-e915-4c66-afa6-6c8722bd72d4)

With your proposed change I couldn't even write something as simple as `$2e-1$`.

**Comment by ecstrema** [comment]
> Only because you haven't defined a variable e12. What if I want e1 e2 and e3 for the standard unit vectors?

That's like saying what if you want a variable named `ratio`, but the symbol `ratio` is already defined, isn't it?

> With your proposed change I couldn't even write something as simple as $2e-1$.

That's a very very _very_ strong point, and it's also a breaking change, so that's a no-no. Positive exponents, meanwhile, would still be useful, but having the positive but not the negative would be a nightmare. 

This has convinced me, so I'm closing the issue, in favor of a way to use regex replace with #show rules in math mode.

**Comment by Leedehai** [comment]
I still like this idea. What about
```ebnf
ScientificNotation = Base ("e"|"E") Index
Base               = <Number>
Index              = PositiveIndex | NegativeIndex
PositiveIndex      = <Number>
NegativeIndex      = "(" "-" <Number> ")"
``` 
In this, `e` for `×`, `E` for `·`.

This way, variable name `e12` won't trigger the rendering, because it lacks the `Base` part. `2e-1` won't trigger the rendering, because the `-1` part isn't parenthesized. If there's a function called `e`, that's okay too because the function is invoked as `#e(2)`.

Examples:
* 1x10^2.2 => `1e2.2`
* 1x10^(-2.2) => `1e(-2.2)`
* 2x10^2.2 => `2e2.2`
* 2x10^(-2.2) => `2e(-2.2)`
* -1x10^2.2 => `-1e2.2` (only the `1e2` part is rendered specially, and the prefixing `-` is rendered as is).
