### ISSUE TITLE
A bug about state?

### ISSUE THREAD

**Issue by lsl00** [typst/typst#338]
Here is the source code:
```
#let newevironment(ename) = {
  let s = state(ename,(dvha: ""))//dvha used to indicate here is a dictionary
  let a = 0
  return (ename,s,a)
}

#let theorem = newevironment("Theorem")

#let new(eobj,name: none,labelx: none,content) = {
  eobj.at(0) + [ ]
  eobj.at(2) = eobj.at(2) + 1
  numbering("1.",eobj.at(2))
  if(name != none){
    [(#name)]
  }
  if(labelx != none){
    eobj.at(1).update(x => {
      x.insert(labelx,eobj.at(2))
      return x
    })
  }
  content
}
#let refx(eobj,labelx) = {
  eobj.at(1).display(it => {
    it.keys()
    //it.at("Gauss")
  })
}
#new(theorem,name: "Gauss",labelx: "Gauss")[
  #lorem(10)
]

#refx(theorem,"Gauss")
```
This produces:
<img width="427" alt="截屏2023-03-26 22 28 12" src="https://user-images.githubusercontent.com/39242557/227782634-33acb034-ad56-42b9-9a6f-02a231b1786a.png">

But when I uncomment line27 (//it.at("Gauss")):
<img width="465" alt="截屏2023-03-26 22 31 44" src="https://user-images.githubusercontent.com/39242557/227782684-18657f92-7684-4ca4-9b29-17521f983e0d.png">

Is this a bug or I miss something about [state](https://typst.app/docs/reference/meta/state/)?

**Comment by user202729** [comment]
A guess, maybe it has something to do with the fact that the function may be evaluated multiple times, maybe in some "non-final" pass the `it` is evaluated with a dict that does not contain that key?

**Comment by lsl00** [comment]
> A guess, maybe it has something to do with the fact that the function may be evaluated multiple times, maybe in some "non-final" pass the `it` is evaluated with a dict that does not contain that key?

Reasonable!
