### ISSUE TITLE
Scientific notation in math mode, take 2

### ISSUE THREAD

**Issue by Leedehai** [typst/typst#3381]
### Description

This is a continuance of the closed #3372.

Though the OP closed it due to reasons stated in [this comment](https://github.com/typst/typst/issues/3372#issuecomment-1933089936), I still like this idea. What about a modified design:
```ebnf
ScientificNotation = Base ("e"|"E") Index
Base               = Number
Index              = NonnegativeIndex | NegativeIndex
NonnegativeIndex   = Number
NegativeIndex      = "(" "-" Number ")"
Number             = regex"[0-9]+(\.[0-9]+)?"
``` 
In this, `e` for `×` (seems [more common](https://en.wikipedia.org/wiki/Scientific_notation)), `E` for `·`.

This way, variable name `e1` won't trigger the rendering, because it lacks the `Base` part. `2e-1` won't trigger the rendering, because the `-1` part isn't parenthesized. `2e(-1)` will trigger the rendering, and if one can use `2 e(-1)` to render the snippet as is. If there's a function called `e`, that's okay too because the function is invoked as `#e(2)`.

Examples:
* 1x10^0 => `1e0`
* 1x10^2.2 => `1e2.2`
* 1x10^(-2.2) => `1e(-2.2)`
* 2x10^2.2 => `2e2.2`
* 2x10^(-2.2) => `2e(-2.2)`
* -1x10^2.2 => `-1e2.2` (only the `1e2.2` part is rendered specially, and the prefixing `-` is rendered as is).

### Use Case

From use cases in #3372.

**Comment by Enivex** [comment]
> 2e(-1) will trigger the rendering, and if one can use 2 e(-1) to render the snippet as is. If there's a function called e, that's okay too because the function is invoked as #e(2).

This is simply unacceptable to me

**Comment by Leedehai** [comment]
> This is simply unacceptable to me

Which one? Presumably the `2e(-1)` part, not the function part?

**Comment by Enivex** [comment]
> > This is simply unacceptable to me
> 
> Which one? Presumably the `2e(-1)` part, not the function part?

The fact that 2 e(-1) and 2e(-1) would mean different things (whitespace dependence)

**Comment by Leedehai** [comment]
How about `\e` instead of `e`? Currently, `2\e2` renders the same as `2e2`.

**Comment by Leedehai** [comment]
Closing in favor of #3382.
