### ISSUE TITLE
Scientific notation in math mode, take 3

### ISSUE THREAD

**Issue by Leedehai** [typst/typst#3382]
### Description

This is a continuance of the closed #3372 and #3381.

Though the OP closed it due to reasons stated in [this comment](https://github.com/typst/typst/issues/3372#issuecomment-1933089936), I still like this idea. What about a modified design modeling after the escape sequence `\u{...}` for Unicode:

```ebnf
NotationSuffix = "\" ("e"|"E") "{" ... "}"
``` 
In this, `\e` for `times` (seems [more common](https://en.wikipedia.org/wiki/Scientific_notation)), `\E` for `dot`.

Examples:
* x10^0 => `\e{0}`
* x10^2.2 => `\e{2.2}`
* x10^(-2.2) => `\e{-2.2}`
* x10^2.2 => `\e{2.2}`
* x10^(-2.2) => `\e{-2.2}`
* x10^n => `\e{n}`

### Use Case

From use cases in #3372.

**Comment by Enter-tainer** [comment]
you can just define a function `e` which does the same thing.

**Comment by Leedehai** [comment]
> ou can just define a function e which does the same thing.

**Comment by ecstrema** [comment]
Then it becomes too verbose, and we've lost the advantage over dot 10^3

**Comment by Jollywatt** [comment]
> Then it becomes too verbose, and we've lost the advantage over dot 10^3

Actually, it's the same number of characters:
```typ
#let e(x) = $dot.c 10^#x$
$ 42#e(6) $
```
Neat!:)
