### ISSUE TITLE
Citation number jumps to next line

### ISSUE THREAD

**Issue by FirstProphet** [typst/typst#3392]
### Description

<img width="469" src="https://github.com/typst/typst/assets/32485045/c0fe2e66-cb73-4c6a-a7d3-a77b35365c78">

I'm using the "american-medical-association" citation style and I'm pretty sure the citation number should adhere to the word before, and if the end of line is reached, they should both be in the next line.

Any idea why this is happening? It only seems to happen with the font Times New Roman. I am not allowed to change the font though.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Indeed a duplicate.
