### ISSUE TITLE
Absolute path for bibliography

### ISSUE THREAD

**Issue by tapyu** [typst/typst#3394]
### Description

AFAIK, it is not possible to pass an absolute path to the bibliography file, e.g.,

![image](https://github.com/typst/typst/assets/22801918/05488552-1b45-4ec3-95c2-403712ae3a4c)

### Use Case

I would suggest that the path parser recognize slash-prefixed paths as absolute paths (e.g., `/absolute/path/to/refs.bib`) and path with a `./` prefix or with no prefix as relative paths (e.g. `relative/path/to/refs.bib` or `./relative/path/to/refs.bib`)

**Comment by Enter-tainer** [comment]
you cannot do that. this is not limited to bib file but for all path in typst.

**Comment by Enter-tainer** [comment]
> slash-prefixed paths as absolute paths

these path are relative to project root.

> path with a ./ prefix or with no prefix as relative paths 

these path are the same as you stated

typst has a sandbox so you cannot access files outside project root

**Comment by Enter-tainer** [comment]
i guess you can use a symbolic and link that bib file into your project root so you can use that

**Comment by tapyu** [comment]
Don't the developers have the interest in "fixing" it? Many typesetting projects have a system-wide range, and working in sandbox does not seem to be a reasonable approach....

**Comment by tapyu** [comment]
> i guess you can use a symbolic and link that bib file into your project root so you can use that

I symlinked, but for large project, it is overwhelming...

**Comment by Enter-tainer** [comment]
> Don't the developers have the interest in "fixing" it? Many typesetting projects have a system-wide range, and working in sandbox does not seem to be a reasonable approach....

it has a good reason to do sandboxing. maybe a malicious package want to embed your `~/.ssh/id_rsa` into the generated pdf and extract it once the pdf is published.
