### ISSUE TITLE
Text opacity doesn't work in PNG export

### ISSUE THREAD

**Issue by Wallbreaker5th** [typst/typst#3407]
### Description

The code snippet provided generates a correct PDF where each line of text gradually changes from white to black. However, when I try to export the result as a PNG file, the text does not properly blend with the background color.

By the way, this issue also appears in the preview interface in the web app.

```typst
#set page(width: auto, height: auto)

#for i in range(11){
  text(fill:rgb(0,0,0,10%*i), lorem(10))

  parbreak()
}
```

![b](https://github.com/typst/typst/assets/36598223/6b731cd3-83fb-43f3-bee3-c61dfed4901e)

### Reproduction URL

https://typst.app/project/pq1PX2kN_nc_v-YSehc-vS

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Seems to only happen for text.

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/3444
