### ISSUE TITLE
Syntax for unpacking arrays

### ISSUE THREAD

**Issue by Marmare314** [typst/typst#341]
Currently it is already possible to enumerate arrays using
```
for index, value in array {...}
```
Similarly it is possible to iterate over the key-value pairs of dictionaries and arguments.
```
for key, value in dict {...}
```
To me this behaviour is not obvious. I think a more general and more intuitive way to do this is using an unpacking syntax, which is used in many modern programming languages. Some examples of how the new syntax might look:
```
let a, b = (1, 2) // a = 1, b = 2
let a, _, c = (1, 2, 3) // a = 1, c = 3

let a, b = (1, 2, 3) // error (too many values to unpack)
let a, b, c = (1, 2) // error (not enough values to unpack)

let a, ..b = (1, 2, 3) // a = 1, b = (2, 3)
let ..a, b = (1, 2, 3) // a = (1, 2), b = 3, not sure if this should be allowed
```
This would work the same with for-loops.

The examples at the beginning would then become
```
for index, value in array.enumerate() {...}
for key, value in dict.pairs() {...}
```

**Comment by laurmaedje** [comment]
I would probably require parentheses as in `let (a, b) = (1, 2)`. I agree that the for loop special cases should be removed in favor of what you propose.
