### ISSUE TITLE
`ToUnicode` in PDF for a Type 0 CID Font might be Wrong

### ISSUE THREAD

**Issue by YDX-2147483647** [typst/typst#3416]
[Source Han Serif (思源宋体)](https://github.com/adobe-fonts/source-han-serif/tree/release#downloading-source-han-serif) and other CJK fonts are embedded as Type 0 CID Fonts in PDF. Typst 0.10.0 (70ca0d25) might generate a wrong `ToUnicode` for them.

> [!NOTE]
>
> Typst.app with default fonts is not affected.
>
> It looks like that typst.app uses `NotoSansCJKjp-Regular-Identity-H` for CJK characters. [Noto Sans CJK](https://github.com/notofonts/noto-cjk/) is identical to [Source Han Sans (思源黑体)](https://github.com/adobe-fonts/source-han-sans). ~~Nonetheless, `typst compile` with neither fonts works on my computer…~~ Language-specific OTFs works, but region-specific Subset OTFs does not.
>
> [HaranoAjiMincho](https://github.com/trueroad/HaranoAjiFonts), implied by Source Serif Pro, also works on typst.app.

> [!TIP]
>
> What is `ToUnicode`?
>
> In PDF, it is often the case that text is not encoded in Unicode. However, modern
> applications usually want them represented in Unicode to make it usable as text
> information. The `ToUnicode` CMap (**C**haracter **Map**) is a bridge between PDF text string encodings and Unicode encodings,
> and makes it possible to extract text in PDF files as
> Unicode encoded strings. It is important to make resulting PDF search‐able and
> copy‐and‐past‐able.
>
> —§1.4.2 of [The Dvipdfmx User’s Manual](https://mirrors.ctan.org/systems/doc/dvipdfmx/dvipdfmx.pdf)

## To Reproduce on Typst.app

1. Download `14_SourceHanSerifCN.zip` from [Region Specific **Subset** OTFs Simplified Chinese (简体中文)](https://github.com/adobe-fonts/source-han-serif/releases/download/2.002R/14_SourceHanSerifCN.zip).

2. Create a new project in typst.app and upload `SubsetOTF/CN/SourceHanSerifCN-Regular.otf` in that ZIP.

3. Compile the following.

   ```typst
   #set page(height: auto)
   
   #let fonts = (
     "Linux Libertine",
     "Source Han Serif",
   )
   
   #for f in fonts {
     text(font: f, size: 3em)[
       #f
   
       #h(1fr)ABC 孔乙己
   
     ]
   }
   ```
  
   [minimal-web-with-otf.pdf](https://github.com/typst/typst/files/14283404/minimal-web-with-otf.pdf)

4. Download the PDF, open it, copy all text and paste.

   - Adobe Acrobat / SumatraPDF:

     ```
     Linux Libertine
     ABC 孔乙己
     Source Han Serif
     ABC ���
     ```

   - Firefox (pdf.js) / MS Edge:

     ```
     Linux Libertine
     ABC 孔乙己
     Source Han Serif
     ABC 㯰□䄬
     ```

   Expected: `ABC 孔乙己` or `ABC孔乙己` (no space).

## To Debug

1. Upload the PDF to [PDF Object Browser](https://brendandahl.github.io/pdf.js.utils/browser/).

2. Go to Trailer → Root → Pages → Resources → Font:

   - …

   - F1

     - Base Font: `/UVRTQX+NotoSansCJKjp-Regular-Identity-H`

     - `ToUnicode`:

       ```
       …
       <2581> <4E59>  # <2581> ↦ U+4E59 (乙)
       <3BFE> <5B54>  # <3BFE> ↦ U+5B54 (孔)
       <4115> <5DF1>  # <4115> ↦ U+5DF1 (己)
       …
       ```

   - F2

     - Base Font: `/TLJDGM+SourceHanSerifCN-Regular-Identity-H`

     - `ToUnicode`:

       ```
       …
       <22A1> <4E59>  # <22A1> ↦ U+4E59 (乙)
       <2F8B> <5B54>  # <2F8B> ↦ U+5B54 (孔)
       <3227> <5DF1>  # <3227> ↦ U+5DF1 (己)
       …
       ```

3. Go to Trailer → Root → Pages → Kids → 0 → Contents, view contents:

   ```
   …
   /F1 33 Tf  # Use font F1 (Noto Sans CJK)
       …
       BT  # Begin text
       …
       [<3BFE25814115>] TJ # Show text
       ET  # End text
   /F2 33 Tf  # Use font F2 (Source Hans Serif CN)
       …
       BT  # Begin text
       …
       [<3BF025A1412C>] TJ  # Show text
       ET  # End text
   ```

   In the first case, F1’s `ToUnicode` contains `<3BFE25814115>`, so all readers convert to `孔乙己` as expected.

   In the second case, F2’s `ToUnicode` does not contain `<3BF025A1412C>`. Adobe Acrobat and SumatraPDF just say they don’t know (`���`), while Firefox and MS Edge parse them directly as Unicode:

   ```python
   >>> '\u3BF0\u25A1\u412C'
   '㯰□䄬'
   ```

4. Manullay edit the wrong `ToUnicode` in PDF, and now it becomes `孔乙己`.

## To Reproduce in the Repo

1. `testit cjk --pdf`

2. Open `tests/pdf/layout/cjk-punctuation-adjustment.pdf`, copy all text and paste.
   
   ![main](https://github.com/typst/typst/assets/73375426/30ea589b-c94c-451a-87ae-13bf9b12f007)

   Expected:

   ![to-unicode](https://github.com/typst/typst/assets/73375426/2091c4b9-5a28-465d-8ae0-8f2cc991bd75)

## Relevant Links

- #479: `ToUnicode` of ligatures

  https://github.com/typst/pdf-writer/issues/17#issuecomment-1717823906

  Ligatures like `ffi` for Source Han Serif are also broken.

- [Fix embedding of CID-keyed fonts into PDF · typst/typst@`dad7c88` · GitHub](https://github.com/typst/typst/commit/dad7c88576224f636f9292fd60f0f65dd4b3a043#diff-ce330df346cda0de39a4acd4b23dfe2f6c702b0a8947bc70d3adf0913d8f72b1R243), from [History for `crates/typst-pdf/src/font.rs`](https://github.com/typst/typst/commits/main/crates/typst-pdf/src/font.rs)

  [Make ligatures copyable and searchable · typst/typst@`ad34763`](https://github.com/typst/typst/commit/ad347632ab95e29eb5180b27142f5c264dfc611a)

- <details><summary>Code base</summary>

  https://github.com/typst/typst/blob/79e37ccbac080212dc42e996d760664c75d1a56f/crates/typst-pdf/src/font.rs#L200-L209

  https://github.com/typst/typst/blob/79e37ccbac080212dc42e996d760664c75d1a56f/crates/typst-pdf/src/font.rs#L147-L150

  https://github.com/typst/typst/blob/79e37ccbac080212dc42e996d760664c75d1a56f/crates/typst-pdf/src/lib.rs#L79-L85

  https://github.com/typst/typst/blob/79e37ccbac080212dc42e996d760664c75d1a56f/crates/typst-pdf/src/font.rs#L239-L263

  </details>

- [*Basics*](https://pdfa.org/wp-content/uploads/2023/08/PDF-Basics-CheatSheet.pdf) and [*Common Objects*](https://pdfa.org/wp-content/uploads/2023/08/PDF-CommonObjects-CheatSheet.pdf) in [PDF Cheat Sheets – PDF Association](https://pdfa.org/resource/pdf-cheat-sheets/)

- §9.7 Composite Fonts in [`PDF32000_2008.pdf`](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf), downloaded from [ISO 32000 (PDF) – PDF Association](https://pdfa.org/resource/iso-32000-pdf/)

- [The Type — 文字 / 设计 / 文化 » 字谈字畅 183：康熙怎么又来了](https://www.thetype.com/typechat/ep-183/): Kangxi radicals (康熙部首), e.g. `⼰` (U+2F30, Kangxi Radical Oneself) ≠ `己` (U+5DF1, CJK Unified Ideograph)

## Acknowledgment / Anecdotes

I have noticed the issue since several days after I met Typst. But I cannot report it as a practical issue until I read [*Color gradients and my gradual descent into madness* on Typst Blog](https://typst.app/blog/2023/color-gradients#debugging-pdf). Thanks Sébastien d'Herbais de Thun and the community!

Besides, KaiTi (楷体), the default font on Windows, embedded as a Type 2 CID Font, turns out to be `孔\r\n乙\r\n己` in SumatraPDF. Those `\r\n` are not desired. (Similar to #526) Even so, “KaiTi + Acrobat/Firefox/Edge” and “typst.app default fonts + SumatraPDF” give the expected `孔乙己`. Therefore it might be SumatraPDF’s issue.

**Comment by YDX-2147483647** [comment]
## Direct cause: CID ≠ GID

> NOTE: Although in many fonts the CID value and GID value are the same, the CID and GID values may differ.
>
> —§9.7.4.2 Glyph Selection in CIDFonts, `PDF32000_2008.pdf`

This is the case of CJK characters in Source Han Serif!

Typst version 1d78c3ed writes:
- `[<3CB7259A4241>] TJ` in `Contents`, according to CIDs (`font::glyph_cid(font, glyph.id)`)
-  `<225D>`, `<2F50>`, `<31EF>` in `ToUnicode`, according to GIDs (`glyph.id`)

```
write_text using Font(Source Han Serif, Normal-400-FontStretch(1000))
  Update glyph_set: GID <0022> ↦ Text "A"
  Update glyph_set: GID <0023> ↦ Text "B"
  Update glyph_set: GID <0024> ↦ Text "C"
  Update glyph_set: GID <0001> ↦ Text " "
  Push encoded: CID = <0022>, Glyph ID = <0022>
  Push encoded: CID = <0023>, Glyph ID = <0023>
  Push encoded: CID = <0024>, Glyph ID = <0024>
  Push encoded: CID = <0001>, Glyph ID = <0001>
write_text using Font(Source Han Serif, Normal-400-FontStretch(1000))
  Update glyph_set: GID <2F50> ↦ Text "孔"
  Update glyph_set: GID <225D> ↦ Text "乙"
  Update glyph_set: GID <31EF> ↦ Text "己"
  Push encoded: CID = <3CB7>, Glyph ID = <2F50>
  Push encoded: CID = <259A>, Glyph ID = <225D>
  Push encoded: CID = <4241>, Glyph ID = <31EF>
```

The log is generated by the following.

https://github.com/typst/typst/blob/1d78c3ed436d70ef4fe05930903bc4b0402161b6/crates/typst-pdf/src/page.rs#L713-L716

```diff
+ println!("write_text using {:#?}", text.font);
  for g in &text.glyphs {
      let segment = &text.text[g.range()];
+     println!("  Update glyph_set: GID <{:04X}> ↦ Text {:?}", g.id, segment);
      glyph_set.entry(g.id).or_insert_with(|| segment.into());
  }
```

https://github.com/typst/typst/blob/1d78c3ed436d70ef4fe05930903bc4b0402161b6/crates/typst-pdf/src/page.rs#L750-L752

```diff
  let cid = crate::font::glyph_cid(&text.font, glyph.id);
+ println!("  Push encoded: CID = <{:04X}>, Glyph ID = <{:04X}>", cid, glyph.id);
  encoded.push((cid >> 8) as u8);
  encoded.push((cid & 0xff) as u8);
```

**Comment by YDX-2147483647** [comment]
1. We are calculating `glyph_cid(font, glyph_id)` 2 times[^1] in `typst-pdf` now. We can calculate the third time when saving `ToUnicode` character map, and [fix this issue in simple 3 lines](https://github.com/YDX-2147483647/typst/commit/b4836053b959fda0feb4593242ed1528eff633a9). Or should we refactor?

   [^1]: The first when [writing glyphs](https://github.com/typst/typst/blob/09b364e9a35bf5746b932a4bcadf69fbc45521d2/crates/typst-pdf/src/page.rs#L750), the second when [extracting glyphs' widths](https://github.com/typst/typst/blob/09b364e9a35bf5746b932a4bcadf69fbc45521d2/crates/typst-pdf/src/font.rs#L84).

2. [PDF are not tested automatically](https://github.com/typst/typst/blob/09b364e9a35bf5746b932a4bcadf69fbc45521d2/tests/README.md?plain=1#L46-L48), and `testit cjk chinese --pdf` is enough for manual test. Then should I add a test case in [`copy-paste.typ`](https://github.com/typst/typst/blob/09b364e9a35bf5746b932a4bcadf69fbc45521d2/tests/typ/text/copy-paste.typ)?

@laurmaedje Could you tell me what you think?

**Comment by laurmaedje** [comment]
Thanks for the thorough investigation! The fix definitely makes sense. The same bug existed before for text writing and I missed that it's also a problem for `/ToUnicode`.

> We are calculating glyph_cid(font, glyph_id) 2 times1 in typst-pdf now. We can calculate the third time when saving ToUnicode character map, and fix this issue in simple 3 lines. Or should we refactor?

It's fine to do it a third time.
