### ISSUE TITLE
Support for inside and outside margins

### ISSUE THREAD

**Issue by mateusfccp** [typst/typst#343]
The `page` function allows for setting the page's `margins`. However, the options are limited to specific sides (`top`, `bottom`, `left`, and `right`) or axis (`horizontal` and `vertical`).

Some templates, like Brazilian's ABNT, have a concept of "outside/outer margins" and "inside/inner margins". Outside margins are the left margin on the left page and the right margin on the right page. Inside margins are in between the two facing pages.

Here is a diagram:

![image](https://user-images.githubusercontent.com/4605213/227795011-49504cc2-b306-412a-a83d-3a7d3e2a627d.png)

I propose these properties to be added to `margin`.

**Comment by laurmaedje** [comment]
Yeah, I plan to have this and possibly also a way to programmatically define the page sizes via a function.
