### ISSUE TITLE
Header style is affected by a first heading in the content

### ISSUE THREAD

**Issue by philipsd6** [typst/typst#3439]
### Description

Given the following document, using the latest version 0.10.0 (2594b367)
```
#set page(header: "Why does this change based on the first heading?")
// plain content here will remove the effect
= First Heading
// as will plain content here`
```

The header will be styled the same as the First Heading, but will revert to normal expected behavior when either plain content lines are uncommented. 

This does not happen in typst.app.

I suppose this is very minor, as I can't think of any reason why one would have a heading without content!

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by MDLC01** [comment]
Looks like a duplicate of #241

**Comment by philipsd6** [comment]
Yep, I agree this is a duplicate.

**Comment by laurmaedje** [comment]
Can be reproduced in the web app with this:
```typ
#set page(header: "Why does this change based on the first heading?")
*First Heading*
```
Heading is slightly different probably because it is locatable. But the bug exists either way in 0.10 and now. I am very aware of it and am considering ways to fix it.
