### ISSUE TITLE
Custom enum level

### ISSUE THREAD

**Issue by nishanthkarthik** [typst/typst#3443]
### Description

Similar to how I can set an enum's start, I'd like to set the enum's level in a scope. For instance, 

```typ
#let content = [
+ Foo
+ Bar
]
```

I want to use `content` in multiple places while it preserves the full numbering of items `Foo` and `Bar`. Even if I use `content` in another enum with deeper nesting, I want to preserve the full numbering in `content` as-is.

Rephrasing my idea, can I _freeze_ content into something that no longer changes based on context? I have custom behavior keyed by the full number representation of an enum item and I'd like it to not change on the place of use.

I have not given it too much thought, but could `start` be an array of numbers instead of just a number?

### Use Case

Custom behavior attached to an enum's `numbering` function may depend on the full numbering of enum items. The ability to reset the enum start and level allows that.

**Comment by PgBiel** [comment]
Related: #1841

Also relevant: https://laurmaedje.github.io/posts/frozen-state/

**Comment by laurmaedje** [comment]
I'll close this in favor of the linked issue.
