### ISSUE TITLE
Labelling figures within body

### ISSUE THREAD

**Issue by Tweoss** [typst/typst#346]
I'm having an issue with labelling figures that are embedded within a body. If the figure is outside of the body, then the label works. However, that means that I cannot place the figure in the middle of the content. If the figure is inside the body, then the label is not found. Is this a known issue / by design? I may have missed something in the documentation, but I could not find any reference to this. If anyone is willing to offer some pointers, I'd also happily try to submit a PR to change this behaviour. 

```
#let solution(body) = locate(location => {
  [#body]
})


// works, but cannot embed figure in the body
#solution[
    Figure label: @linking
]
#figure("bonjour") <linking>

// does not work: "label does not exist in the document"
#solution[
    Figure label: @linking1
    #figure("bonjour") <linking1>
]
```

**Comment by Tweoss** [comment]
Ah, I see. I tried to read through the source code but could not figure out the structure well enough to attempt a fix. I'd be happy to try if I could get some guidance on how these compilation passes work, but am not sure of how much time I can dedicate. The labelling (to me) is not critical. However, it would be a nice feature to have and seems like expected behavior.

**Comment by laurmaedje** [comment]
Should be fixed now because we ignore errors in earlier passes if they go away in later ones.
