### ISSUE TITLE
RTL and LTR breaks with `#linebreak()`

### ISSUE THREAD

**Issue by A-Walrus** [typst/typst#3462]
### Description

Version: `typst 0.10.0.r186.g0fb2a6748`

When the document language/dir is RTL, text explicitly set to LTR doesn't go in correct direction directly after `#linebreak()`

```typ
#set text(lang:"he")

// rtl
8:00 - 9:00

// ltr
#text("8:00 - 9:00",dir:ltr)


// still rtl
#linebreak()
#text("8:00 - 9:00",dir:ltr)
```
![image](https://github.com/typst/typst/assets/58790821/e909339e-346c-411c-a4cb-f7280a02f6f8)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
@joserlopes Yes, of course! This file might be a good starting point for your investigation:
https://github.com/typst/typst/blob/ca5d682edb1553cd73c581a1726537e6415fe848/crates/typst/src/layout/inline/mod.rs#L1-L1417
