### ISSUE TITLE
Builds are not always reproducible due to document language detection

### ISSUE THREAD

**Issue by istudyatuni** [typst/typst#3467]
### Description

MRE

```typ
#set document(date: none)
#show "1234": set text(lang: "de")

asdf 1234
```

```sh
typst c main.typ
xxd main.pdf > 1.hex
typst c main.typ
# wait different sha256sum
xxd main.pdf > 2.hex
diff 1.hex 2.hex
```

```diff
668,669c668,669
< 000029b0: 663a 6c69 3e64 653c 2f72 6466 3a6c 693e  f:li>de</rdf:li>
< 000029c0: 3c72 6466 3a6c 693e 656e 3c2f 7264 663a  <rdf:li>en</rdf:
---
> 000029b0: 663a 6c69 3e65 6e3c 2f72 6466 3a6c 693e  f:li>en</rdf:li>
> 000029c0: 3c72 6466 3a6c 693e 6465 3c2f 7264 663a  <rdf:li>de</rdf:
```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Problem is here:
https://github.com/typst/typst/blob/56ecd6c806ab32a7cca5289500504e398198d283/crates/typst-pdf/src/lib.rs#L164

This hashmap doesn't iterate in deterministic order.

**Comment by laurmaedje** [comment]
You're right, it counts the `TextItem`s, not the glyphs.

**Comment by laurmaedje** [comment]
Possible fix: Add the language itself as part of the key function passed to `max_by_key`.

**Comment by istudyatuni** [comment]
> it counts the `TextItem`s

I don't know how text is splitted to `TextItem`s, so I failed to come up with a sample, that will be good, because even this doesn't work:

```
asdf

asdf

1234
```

and this: `asdf #1 1234`

**Comment by laurmaedje** [comment]
Okay, then I'm not sure what's going on.
