### ISSUE TITLE
Dictionary can only be constructed from static strings

### ISSUE THREAD

**Issue by timo-a** [typst/typst#347]
I can't manage to construct a dictionary with a dynamic key: `#let key = "mykey"`   
This `(key: "123")` results in a key named `key`.  
And this `(#key: "123")` does not compile with error message `this character is not valid in code`.
I guess it isn't possible because keys without quotes are interpreted as strings¹ anyway.
On the other hand the sentence 

> If you know the key statically, you can alternatively use field access notation (.key) to access the value.

implies that it is possible to not know the key at compile time. But apparently this is only possible with `insert`.

If I'm overlooking something and dynamic keys in the constructor are possible, I'd appreciate some pointers, otherwise I think the documentation should indicate that keys must be final
  
  
   
¹ or as "identifiers"? If I try to supply a function call that returns a string, the error message is  `expected identifier or string, found function call` but the [reference](https://typst.app/docs/reference/types/dictionary/) doesn't mention identifiers

**Comment by thecaralice** [comment]
You can use this function as a workaround:

```rs
let from_pairs(..pairs) = {
  let ret = (:);
  for p in pairs {
    assert(
      p.len() == 2, 
      message: "`from_pairs` accepts an array of pairs"
    );
    let key = p.at(0);
    let value = p.at(1);
    ret.insert(key, value);
  }

  ret
};

assert(
  from_pairs(
    ("a", 1),
    ("b", 2),
  ) == (
    a: 1,
    b: 2,
  )
);
```

**Comment by laurmaedje** [comment]
Not currently possible, but I plan to allow this:
```
#let hi = "hello"
#assert((hi: 1) == ("hi": 1))
#assert(((hi): 1) == ("hello": 1))
```
Basically any expression that isn't an identifier would be evaluated normally. To force an identifier to be parsed as an expression, you can thus wrap in parenthesis (or braces, or whatever).

**Comment by laurmaedje** [comment]
Implemented in https://github.com/typst/typst/pull/2559.
