### ISSUE TITLE
Feature Request: Add string input option to the cli

### ISSUE THREAD

**Issue by grosenberg** [typst/typst#348]
The `Typist` cli appears to only support stand-alone operation.  However, document production orchestrators are structured to process documents and images in pipelines.  

Adding a string (or pipe) input option would be essential to allowing `Typist` to be used in pipelines.

Adding a SVG output option would be desirable, as it makes pipelined document element synthesis a bit easier (not essential though, given that `Pandoc` or another tool could be used to subsequently pipeline convert PDF to SVG).

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/typst/issues/410 because that one has more discussion. SVG export was implemented in the meantime.
