### ISSUE TITLE
Compile error when citing in the footnote

### ISSUE THREAD

**Issue by DCRunge** [typst/typst#3481]
### Description

The following code:

```typ
#v(60em) // change this number to 60em will trigger compile error.

This is a footnote (like this :))#footnote[
  This is a citation to @Landau:1975pou.]#super(", ")#footnote[It's somehow like this.
].
 
#bibliography("ref1.bib", style: "american-institute-of-aeronautics-and-astronautics")
```

with `ref1.bib` (the exact content of the bib entry does not matter):

```bib
@book{Landau:1975pou,
    author = "Landau, L. D. and Lifschits, E. M.",
    title = "{The Classical Theory of Fields}",
    isbn = "978-0-08-018176-9",
    publisher = "Pergamon Press",
    address = "Oxford",
    series = "Course of Theoretical Physics",
    volume = "Volume 2",
    year = "1975"
}
```

will trigger a compiler error: 

```
This is a citation to @Landau:1975pou.]
                      ^^^^^^^^^^^^^^^
failed to format citation (this is a bug)
```

### Reproduction URL

https://typst.app/project/wk3E12AXflNGa3GaTjbho8

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Leedehai** [comment]
Indeed, with exactly the same file content (including the filename `ref1.bib`), at HEAD (commit e9ee00a7) I can reproduce it with
```
target/debug/typst compile tests/typ/bugs/3481-cite-in-footnote.typ
```
but curiously, not with
```
cargo test --all --test tests -- --exact tests/typ/bugs/3481-cite-in-footnote.typ
```

**Comment by Leedehai** [comment]
Update:
With the typ file like this:
```
#v(60em)
This is a footnote (like this :))#footnote[
  This is a citation to @Landau:1975pou.]#super(", ")#footnote[foo].
#bibliography("ref1.bib")
```
`target/debug/typst compile tests/typ/bugs/3481-cite-in-footnote.typ` reproduced the same error.
But if the file is this:
```
#v(60em)
This is a footnote (like this :))#footnote[
  This is a citation to @Landau:1975pou.]#super(", ").
#bibliography("ref1.bib")
```
the error is gone.

**Comment by Beiri22** [comment]
I also got this error. At first no problem occured. But as i startet to introduce some spacing around the headings, this error came up.

**Comment by laurmaedje** [comment]
@Beiri22 I will look into it.

**Comment by Beiri22** [comment]
Thank you.

**Comment by Beiri22** [comment]
@laurmaedje any news?

**Comment by laurmaedje** [comment]
@Beiri22 I found the problem and opened #4095 to fix it.

**Comment by Beiri22** [comment]
@laurmaedje  Thank you so much! My last question. I can use the git-version to use the fix; you will not port it to the web-app prior to the next release, right?

**Comment by laurmaedje** [comment]
Yeah, the web app will stay in sync with the released version.

**Comment by Beiri22** [comment]
I have installed the latest git version a few days ago after this merge. My wife just called with "failed to format citation (this is a bug)" - is this really fixed.

**Comment by laurmaedje** [comment]
Hard to say like this. Do you have a reproduction for the issue on main?

**Comment by Beiri22** [comment]
Last time the problem happened I saw that the error message came directly from typst vs code plugin; triggering a compilation in terminal resulted in no error? Does the vs code plugin use the installed typst compiler or does it ship it's own?

**Comment by laurmaedje** [comment]
The VS Code extension ship it's own, so that explains it.

**Comment by Beiri22** [comment]
Good to know and sorry for bringing up misleading observation.
