### ISSUE TITLE
Is it possible to predefine the name of exported png?

### ISSUE THREAD

**Issue by drunkenQCat** [typst/typst#3490]
### Description

Is it possible to add an alias feature to page like this?:
page(
  `alias: "custom name x"`,
  width: 1440pt,
...
)
then, when exporting png, we can run the cli like:
`typst c -f png .\template.typ "{alias}.png"`
to make the file names same as the predefined aliases.

### Use Case

I'm making a project to translate some kind of scripts to typst code. If it's possible to predefine the aliases of each page, it will be easy to relate the png file in future code and make the picture frames more "readable". I have read the typst cli documents and source code, I found that there's no way to achieve it. The example in the description is just one of my idea, maybe there will be more appropriate method to make it possible.

**Comment by LaurenzV** [comment]
That's not possible as far as I know.

**Comment by drunkenQCat** [comment]
well. is it hard to achieve or not in plan?

**Comment by LaurenzV** [comment]
I don't think it's hard to achieve, although I haven't looked into it. So if someone implements it, maybe it will be added. But the details of the API would have to be discussed with @laurmaedje first.

**Comment by laurmaedje** [comment]
I wonder whether for your use case a page alias is really best or maybe rather a way to somehow batch compile multiple documents? A named thing wouldn't necessarily have to be a single page.

**Comment by drunkenQCat** [comment]
got it. i will try it in another way.
