### ISSUE TITLE
Documentation for default element styles

### ISSUE THREAD

**Issue by jcvar** [typst/typst#3493]
### Description

Hello,
Getting started with Typst has been great and having the default values for style functions and the effect of other syntactic elements in the docs has been very useful. However, the `heading` styling behavior (and caveats) are missing from the docs.

### Use Case

This info would facilitate the customization or even a 'style reset' of headings. Explainers like the one on typst#2919 bring a lot insight into a slightly obscure behavior. 

Thank you!

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/typst/issues/5095, which has more details.
