### ISSUE TITLE
ARABIC END OF AYAH (U+06DD) followed by a number ۝١ is rendered incorrectly

### ISSUE THREAD

**Issue by munzirtaha** [typst/typst#3499]
### Description

Entering the end of ayah symbol followed by a number, should encircle the number, .e.g.
`U+06DDU+0661`
should be rendered as
۝١
It works correctly in  `LibreOffice Writer`  using `Noto Sans Arabic` font. This failed using `typst`

### Reproduction URL

https://typst.app/project/pFeXLY0VVrRyfu5vU24Say

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
<img width="991" alt="image" src="https://github.com/typst/typst/assets/47084093/af18e8e5-fae8-4373-8e6d-4141bc1b1062">
That's how it looks to me, is that not how it's supposed to look?

At least it looks pretty similar in the browser:
<img width="220" alt="image" src="https://github.com/typst/typst/assets/47084093/2baf85c5-2cc7-4e74-bbb7-cf4410129b90">

**Comment by LaurenzV** [comment]
I'm pretty sure that's a font issue. Here's what I get using the font "Segoe UI" in Word:
<img width="407" alt="image" src="https://github.com/typst/typst/assets/47084093/5583fdaa-5701-4b02-973d-c8b755a1e5d5">

And here the result when I change it to Noto Sans Arabic:
<img width="264" alt="image" src="https://github.com/typst/typst/assets/47084093/4833b925-6f07-4a7d-86b3-89d21fbd17ed">

**Comment by LaurenzV** [comment]
I just tried it in Libre Office Writer, too, and got the exact same result.

**Comment by munzirtaha** [comment]
@LaurenzV what you have with "Segoe UI" in Word is the correct rendering. May be your "Noto Sans Arabic" font is not updated the latest?

**Comment by LaurenzV** [comment]
Could you show a picture of how it looks for you?

**Comment by munzirtaha** [comment]
![typst-3499](https://github.com/typst/typst/assets/2936425/fc29a817-7550-4706-90c9-fdc2c369217b)

**Comment by LaurenzV** [comment]
Not sure then, would have to look into it. But in any case, if something is wrong then it's probably a bug in [rustybuzz](https://github.com/RazrFalcon/rustybuzz), because that's the library we use for shaping.

**Comment by munzirtaha** [comment]
Umm! This is getting nasy then. With `rustybuzz` announcing it "is effectively dead". What's the easiest way to test the library directly?

**Comment by LaurenzV** [comment]
I'll look into it when I find the time to do so.

**Comment by munzirtaha** [comment]
Doesn't `rustybuzz` handle the shaping part only? I am not sure about the rendering part. The `shape` function output matches that of `harfbuzz` as can be seen here:

```
$ ./shape --font-file NotoSansArabic-Regular.ttf --text "۝١"
uni0661.small=1@538,80+0|uni06DD=0+1370

$ hb-shape NotoSansArabic-Regular.ttf "۝١"
[uni0661.small=1@538,80+0|uni06DD=0+1370]
```

**Comment by LaurenzV** [comment]
It only handles the shaping part.

But the rendering with `harfbuzz` looks wrong for me too (even though different to what appears in Typst):

`hb-view NotoSansArabic-Regular.ttf "۝١"`

<img width="234" alt="image" src="https://github.com/typst/typst/assets/47084093/26de2620-fb50-48de-80b7-ce37474cd21d">

So not sure, either a harfbuzz issue or something is wrong with the font (or something is wrong with my computer).

**Comment by munzirtaha** [comment]
> Although I don't speak Arabic.

May be I should explain the problem in a simplified way and remove any part that requires any Arabic knowledge. In Unicode terms this is called `"subtending marks"`. In this case, the first character is just a circle and the second is the number one. The circle is empty but when followed by a number, the fonts and the shaping engine has their logic to substitute the number one with a smaller version that fits inside the circle and move it to fit perfectly. Of course not all the fonts support the full range of Arabic features, but as you figured out "Segoe UI" supports subtending, and you can do your tests with it.

That's said, assuming your version of noto fonts are current, try the `--direction` option so as to prevent incorrect auto-detection. Also, try other fonts like `Amiri`, `Calibri`, `Traditional Arabic`, `Arabic Typesetting`. Whichever works for you is enough to compare. Let's even use the Latin number "1" instead of the Arabic one.
```
$ pacman -Q harfbuzz
harfbuzz 8.3.0-2
$ hb-info NotoSansArabic-Regular.ttf |rg Version
Version: Version 2.012; ttfautohint (v1.8.4.7-5d5b)
$ hb-view --direction=ltr NotoSansArabic-Regular.ttf -u 6dd,661
```
![noto-661](https://github.com/typst/typst/assets/2936425/bfdc3f93-942f-4e7e-b62f-a7bce2f50ad9)

`$ hb-view --direction=ltr NotoSansArabic-Regular.ttf -u 6dd,31`
![noto-31](https://github.com/typst/typst/assets/2936425/ac76ebdb-6abf-4833-81eb-42add3e861c9)

`hb-view --direction=ltr Amiri-Regular.ttf -u 6dd,31`
![amiri](https://github.com/typst/typst/assets/2936425/91d5af34-9a59-4e2f-a296-1062ea5273d1)

Let me know how it goes, and if you need any help we can ask the harfbuzz gurus for advice.

**Comment by LaurenzV** [comment]
Okay, for some reason the font on Google Fonts was veeery outdated. 😅 Even though I downloaded a fresh copy... But downloading it directly from GitHub I can now reproduce it.

So yeah, maybe a rendering issue after all. But as I said, I don't know when I can investigate it, will probably take a while, since I'm also still relatively new in that area.

**Comment by munzirtaha** [comment]
Yes, I understand. But after these findings, can you point to which library could be the cause and whether the upstream label is still correct?

**Comment by LaurenzV** [comment]
Actually, nevermind, seems like it isn't a bug, for some reason Typst was just still loading an old Noto Arabic for me... So here is what I did:

1) Delete all local instances of Noto Sans Arabic. Verify that Typst isn't able to detect any instances of Noto Sans Arabic by invoking `cargo run -- fonts` 

2) Download `NotoSansArabic-Regular.otf` from here: https://notofonts.github.io/

3) Put it in some folder on your PC.

4) Create the following file;
```
#set page(width: auto, height: auto, margin: 30pt)
#set text(size: 40pt, font: "Noto Sans Arabic")

۝١
```

4) Run it with `cargo run -- c --font-path assets/inc_fonts  typst.typ typst.png`.

5) Result:
![typst](https://github.com/typst/typst/assets/47084093/7d8828b4-a207-40fd-8dbb-24f16d4027cf)

**Comment by munzirtaha** [comment]
Umm! I am using Arch Linux which already uses the latest version of noto fonts but I see now that the bug is fixed in the latest commits after the release. I am not sure which one but my current version of typst
```
> typst -V
typst 0.10.0 (70ca0d25)
typst compile noto.typ noto.png
```
![noto](https://github.com/typst/typst/assets/2936425/48d337dd-154c-471d-b860-6f20c8927623)



whereas,
```
> ./typst -V
typst 0.10.0 (f5a2a9a9)
typst compile noto.typ noto.png
```
![noto2](https://github.com/typst/typst/assets/2936425/462ddc82-194c-4055-aaa7-cbd6bb0a65a8)

Anyway, I am glad that it's been fixed and thanks to you and whoever fixed it.

**Comment by munzirtaha** [comment]
Just update the v

**Comment by Enivex** [comment]
> Just update the version of the font on typst.app before closing.

The web app has a different repository https://github.com/typst/webapp-issues/issues

It would be better if you created an issue there to update the font.
