### ISSUE TITLE
Access to Font Properties

### ISSUE THREAD

**Issue by SolidTux** [typst/typst#3509]
### Description

Access to properties of the currently set font, like `cap-height`, `x-height` etc.

### Use Case

This can be used to gain more fine-grained control to the layout, e.g. when aligning lines to a grid is necessary.

**Comment by laurmaedje** [comment]
This is possible as of https://github.com/typst/typst/commit/145723b1ef4fa23f1f6665b8907dfe79d0bf83cf via `context text.cap-height` etc.
