### ISSUE TITLE
Horizon alignment doesn't work in table

### ISSUE THREAD

**Issue by manuel5975p** [typst/typst#3513]
### Description

Full minimal example code:
```rs
#[
  #show text: it => {align(horizon + center, it)}
  #show math.equation: it => {align(horizon + center, it)}
#table(fill: (i, j) => {if j == 0{rgb("aaaaff")} else if calc.rem(j,2) == 0{rgb("ffffff")} else{rgb("dddddd")}}, stroke: 1pt, columns: (1fr>
  *Quantity*
][
  *Value*
][
  *Scaled planck charge*
][
  $ q_P $
][
  *Scaled planck mass*
][
  $ alpha m_P $
][
  #align(horizon)[*Scaled planck length*]
][
  $ l_P / alpha $
]
]
```
![bug2](https://github.com/typst/typst/assets/5041338/adc8cdb7-d998-4d0b-9d3e-b2267220eaee)

What would be expected:

![bug2](https://github.com/typst/typst/assets/5041338/710a5de0-79f5-4a2b-80f2-dab9dec03041)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by manuel5975p** [comment]
Just to be clear: The "expected" output is generated with the v0.10.0 typst. So something broke it since then.

**Comment by xkevio** [comment]
This could either be a regression wrt. to the improved show-set rules or the complete table overhaul.
In any case, centering the text like you did with show-rules on the text element is not very idiomatic and can be brittle.

Table has its own `align` parameter which will make this much easier, cleaner and more robust.
```typ
#table(
  fill: (i, j) => { 
    if j == 0 {rgb("aaaaff") } 
    else if calc.even(j) { rgb("ffffff") } 
    else { rgb("dddddd") } 
  }, 
  stroke: 1pt,
  rows: 3em,
  columns: (1fr, 1fr),
  align: center + horizon,
  [*Quantity*], [*Value*],
  [*Scaled planck charge*], [$ q_P $],
  [*Scaled planck mass*], [$ alpha m_P $],
  [*Scaled planck length*], [$ l_P / alpha $]
)
```

**Comment by manuel5975p** [comment]
I am aware of that solution to the problem, but I still wanted to post the issue since it works on the latest tag.

**Comment by laurmaedje** [comment]
The show set rule on text worked somewhat incidentally. Any extra container around the text (in this case the new table cell element) breaks it. As such, I'll close this.
