### ISSUE TITLE
Dynamic top margin to page based on height of header.

### ISSUE THREAD

**Issue by sumitjhajharia** [typst/typst#3520]
### Description

Currently we define margin top in page and based on that header adjusts it self. 
However we want to calculate  top margin based on height of header and generate  pdf.

I tried it using state and layout to :

```
#let margin = state("top", 0)
#layout(size => style(styles => [
  #let (height, width) = measure(block(width: size.width, header),
    styles,
  )
  #margin.update(top => height)
]))

#let header = [
        #grid(
      columns: (1fr, 1fr),
      gutter: 4pt,
        image("logo.png", height: 30pt, width: 150pt),
        align(right)[
          *Invoice*\
          *\$250.84*\
          *Tag\# : 2eGu7HPv*\
        ],
    )]
```

Now not able to use state values to set top margin in page.

### Use Case

Dynamically calculate header height and based on height adjust headers for each page.

**Comment by laurmaedje** [comment]
I'll close this in favor of https://github.com/typst/typst/issues/1483, which I've renamed to broaden its scope a bit.
