### ISSUE TITLE
Refcheck for warning about unreferenced figures/tables/equations/...

### ISSUE THREAD

**Issue by janosh** [typst/typst#3546]
### Description

> feel free to close/migrate this issue since it may be out of scope for `typst` itself, perhaps to be implemented in a separate linter

The LaTeX package [`refcheck`](https://ctan.org/pkg/refcheck) warns about figures (and other references as configured) that are not used anywhere in the document. would be great to have this functionality in Typst.

### Use Case

it's common practice to reference every figure in a scientific document. many journals require it. but hunting down unreferenced figures manually is tedious.

**Comment by laurmaedje** [comment]
You could try something like this:
```typ
#figure[Hello] <hello>
#figure[From] <from>
#figure[Planet] <planet>
#figure[Earth] <earth>
$ a + b $ <eq>

@hello
@earth

#locate(loc => {
  let figures = query(selector.or(figure, math.equation), loc)
  let refs = query(ref, loc)
  let known = figures.filter(f => f.has("label")).map(f => f.label)
  let referenced = refs.map(r => r.target)
  let missing = known.filter(l => l not in referenced)
  if missing.len() > 0 {
    panic("Unreferenced labels: " + missing.map(str).join(", "))
  }
})
```

**Comment by janosh** [comment]
nice! thanks for the quick reply!

is there a way to discount references from one figure to another? only main text references should count.

i tried looking through the docs for a way to access and check the parent element/container to ignore references inside captions but didn't yet find it.

**Comment by laurmaedje** [comment]
I think it's unlikely that we'll make this built-in, but if someone wants to make it into a package, feel free to!

**Comment by techgustavo** [comment]
A few weeks ago I looked for this same feature and created a [small package to do it](https://github.com/techgustavo/sanity) :)
