### ISSUE TITLE
A normal hbar

### ISSUE THREAD

**Issue by Leedehai** [typst/typst#355]
Hi, I think the built-in symbol `planck.reduce` is a bit off [1], as the line is slant. In fact, this is Latex's `\hslash`.

However, the majority of papers use `\hbar`, where the "bar" above the letter "h" is horizontal [2]. That's what gives the reduced Planck constant symbol its colloquial name "h-bar".

It'd be awesome if Typst could provide an `hbar` symbol we are familiar with. Thanks!

[1] <img width="20" alt="Screenshot 2023-03-26 at 20 58 03" src="https://user-images.githubusercontent.com/18319900/227823655-be901a59-a702-4778-be54-1b4a8497ed37.png">
[2] example: https://i.stack.imgur.com/VtYnw.png

**Comment by Enivex** [comment]
U+0127 (ħ) has a horizontal bar.

**Comment by Enivex** [comment]
Here's a workaround:

`#let hbar = text(font: "Linux Libertine", style: "italic")[\u{0127}]`

(Setting the font explicitly seems to be necessary, at least with the math font used in the web app)

**Comment by user202729** [comment]
Essentially at the moment only support "modern" font formats and the character in Latin Modern Math font has the slash diagonal.

I try in LaTeX:

* default: `\hbar` gives horizontal line by composing a line with `h`, `\hslash` undefined.
* with `unicode-math` package alone: both gives `\hslash`.
* With `unicode-math` and `amsfonts`: `\hbar` gives horizontal line (not composed), `\hslash` gives slashed line.
* Inspecting the case above LaTeX uses font "MSBM10".


Try this document

```
%! TEX program = lualatex
\documentclass{article}
\usepackage{unicode-math}
\begin{document}
$\hbar \hslash$
\end{document}
```

On the other hand, the `hbar` without `unicode-math`

**Comment by Enivex** [comment]
> Thanks @Enivex. But `hbar` defined this way creates horizontal spaces around the `hbar` symbol. I also tried the `strike()` and `overline()` function, but they have the same problem.
> 
> ```
> #let hbar = text(font: "Linux Libertine", style: "italic")[\u{0127}]
> 
> $ E = planck.reduce omega, E = hbar omega $
> ```
> 
> <img alt="Screenshot 2023-03-27 at 12 58 35" width="237" src="https://user-images.githubusercontent.com/18319900/228012541-3e9f997c-f958-4a84-ab40-c9800815e25c.png">

Okay, new attempt, using New Computer Modern since it matches the default math font better.

`#let hbar = $text(font: "New Computer Modern", style: "italic","\u{0127}") #h(0.02cm)$`

I chose 0.02cm since that seemed to fit the spacing with `planck.reduce`

Disclaimer: No warranty 😂

**Comment by Enivex** [comment]
It annoyed me that it was slightly narrower. You may maybe prefer

`#let hbar = $text(font: "New Computer Modern", style: "italic",#scale(x: 108%,"\u{0127}")) #h(0.025cm)$`

The width then matches the planck.reduce in the math font (though the slant isn't exactly the same angle)

**Comment by Leedehai** [comment]
Thank you!

I fiddled around a bit in my doc and arrived at this solution. It appears to be work well with scaling (e.g. in a superscript's denominator), and the shape of the letter "h" is the same as the current font's Planck symbol.

However, applying function `strike()` on the symbol unexpectedly shifted the letter a bit downward in the math mode, so I had to move it back up with `move()`. The length units are `em`, which [scales with the font size](https://typst.app/docs/reference/types/length/). As mentioned previously, `h()` is used to remove the unexpected spaces from both sides of the letter.

```
#let hbar = $#h(0em) #move(dy: -0.08em, strike(offset: -0.55em, extent: -0.03em, sym.planck)) #h(0em)$
```
<img width="761" alt="Screenshot 2023-03-27 at 17 52 06" src="https://user-images.githubusercontent.com/18319900/228075381-06c75a32-7ce5-4fc9-9d51-961ab021ec4f.png">

I included this `hbar` into my `physics` package: https://github.com/Leedehai/typst-physics.

**Comment by Enivex** [comment]
> However, applying function strike() on the symbol unexpectedly shifted the letter a bit downward in the math mode,

I ran into something similar when firsr trying to scale() outside the text() instead of inside. Seems like a bug of some kind.

**Comment by Leedehai** [comment]
Agreed. Ideally Typst could provide a built-in `hbar` symbol, so we can get rid of these house-of-card hacks.

**Comment by Enivex** [comment]
> Agreed. Ideally Typst could provide a built-in `hbar` symbol, so we can get rid of these house-of-card hacks.

Your idea for a solution is basically the best possible for math fonts that do not have an italic version of \u{0127} (all of them?). Though I'm sure it could be made less janky (without the move etc).

**Comment by user202729** [comment]
> I ran into something similar when first trying to scale() outside the text() instead of inside. Seems like a bug of some kind.

I think rather than a bug I'd say it's more of "currently Typst does not explain clearly how the 'box and glue' model work
(here it's called something like 'block box and space') unlike in TeX so we're left with trying random combination of parameters".

TeX's box has a property "where the baseline is" apart from just width and (total) height.

> The only thing missing from the strike() solution is that the rectangle has sharp edges. It would be more aesthetically pleasing if it was possible to set a radius for it.

We're still missing a lot of drawing primitives. (or maybe even better, allow the equivalent of `\pdfspecial` in LaTeX, but this is a different feature request)

**Comment by Leedehai** [comment]
After a few more attempts, I arrived at this new solution for my [physics](https://github.com/leedehai/typst-physics) package. It fixes the horizontal spacing problem well.
```
#let hbar = (sym.wj, move(dy: -0.08em, strike(offset: -0.55em, extent: -0.05em, sym.planck)), sym.wj).join()
```

The previous solution with `#h(0em)` fixes the horizontal spacing problem for most cases, but unexpectedly collapses spacing when placing near an equality sign `=`, addition `+`, etc. See the screenshot for a comparison:
<img width="454" alt="Screenshot 2023-04-01 at 23 05 18" src="https://user-images.githubusercontent.com/18319900/229328933-6ad535ae-d5c4-4e13-8171-08bb0dd3be6d.png">

**Comment by Leedehai** [comment]
In summary, it's a font issue.

**Comment by Leedehai** [comment]
In summary, it's a font issue.
