### ISSUE TITLE
Allow array unpacking in member functions with tuple inputs

### ISSUE THREAD

**Issue by ntjess** [typst/typst#3556]
### Description

Allow function such as `array.map`, `array.filter`, etc. to unpack into multiple arguments when provided. This would enable the following syntax:
```typst
#let array = (1, 2, 3)
#array.enumerate().map((idx, value) => [Value #value at index #idx])
```

### Use Case

To enable the above example, we currently have to make the function much more verbose:
```typst
#let array = (1, 2, 3)
#array.enumerate().map(idx-value => [Value #idx-value.at(0) at index #idx-value.at(1)])
```

This gets even more messy with multiple parameters. We can also do this:
```typst
#array.enumerate().map(idx-value => {
let (idx, value) = idx-value
// .. rest of the code
})
```

But now our simple function must become full-bodied and we might as well use a for-loop.

Another bonus would be rust-side guarantees that the number of objects in each tuple is consistent to provide for the unpacking.

Precedence is based on the following existing features:
1. Arrays can unpack, with well-defined behavior for edge cases: `let (a, b, c, ..rest) = (1, 2, 3)`
2. for-loops can unpack: `for (idx, value) in (1, 2, 3).enumerate() { }`

**Comment by ntjess** [comment]
I was trying to see how common this pattern was across github when I noticed the feature is already available: https://github.com/search?q=path%3A*.typ+enumerate%28%29.map%28&type=code

We just need to provide an additional set of parentheses.

It might be worth updating the documentation to add this type of example.

**Comment by PgBiel** [comment]
The extra parentheses are needed because otherwise it'd be ambiguous regarding whether you have a function with two arguments or a function with a single unpacked argument. Therefore, unpacking only happens when it's not ambiguous.

This is mentioned here: https://typst.app/docs/reference/scripting/#bindings

**Comment by laurmaedje** [comment]
Closing this as an example is already present.
