### ISSUE TITLE
Support code block highlight for more language.

### ISSUE THREAD

**Issue by PhyX-Meow** [typst/typst#356]
For example, julia. Markdown do support julia code highlight. It would be amazing if typst support also.
Edit: I think latex also has a package supporting code highlight for many languages, using Pygments.

**Comment by Skgland** [comment]
I think the mentioned latex package would be [minted](https://ctan.org/pkg/minted).

**Comment by laurmaedje** [comment]
Fixed via https://github.com/typst/typst/pull/771 and https://github.com/typst/typst/pull/1655
