### ISSUE TITLE
Math triangle should be upright not sideways

### ISSUE THREAD

**Issue by onomou** [typst/typst#3562]
### Description

The current `$triangle$` rendered is sideways, `▷`. I expect the output to be like ASCIIMath (`/_\` or `triangle`) and LaTeX `$\triangle$`, which use the symbol with a horizontal base, `△`. This is important to typeset what one would see in a math book to describe a triangle (clip from a geometry textbook I have):

![image](https://github.com/typst/typst/assets/131693/601acd27-8dc7-44d8-a858-9cad7b5a8291)

`$Delta$` is close, but definitely not the same as `$\triangle$` (https://latex.codecogs.com/svg.image?\triangle\Delta): 

![image](https://github.com/typst/typst/assets/131693/e5f87895-00d9-432d-80d0-fb0681ca00c1)

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by onomou** [comment]
This is an ease-of-use bug. One may use this for the proper triangle symbol: `$#sym.triangle.t$`.

**Comment by Enivex** [comment]
There is no a priori reason why triangle _has_ to match the symbol that is called triangle in LaTeX. There are a plethora of triangles in unicode, just search in https://typst.app/docs/reference/symbols/sym/

Note that you can use the simpler `$triangle.t$`.

**Comment by Enivex** [comment]
> @Enivex , having good defaults and being consistent is also important. Many special unicode triangle symbols seem to only support the top variant, take e.g. `plus.triangle`.
> 
> Hence, if there are not equally good reasons to have the current design as the default, I'd change it.

It's not default per se, as there is no symbol called just triangle. It's more or less coincidental that it resolves to this one.

**Comment by Leedehai** [comment]
I wonder how often users type `triangle` they want ▷ versus △. If the latter has more (i expect so, since it's a symbol representing triangles in geometry teachings), I think it makes sense to change it.

**Comment by Andrew15-5** [comment]
>  It's more or less coincidental that it resolves to this one.
Indeed:

```rs
    triangle: [
        stroked.r: '▷',
        stroked.l: '◁',
        stroked.t: '△',
        stroked.b: '▽',
        stroked.bl: '◺',
        stroked.br: '◿',
        stroked.tl: '◸',
        stroked.tr: '◹',
        stroked.small.r: '▹',
        stroked.small.b: '▿',
        stroked.small.l: '◃',
        stroked.small.t: '▵',
        stroked.rounded: '🛆',
        stroked.nested: '⟁',
        stroked.dot: '◬',
        filled.r: '▶',
        filled.l: '◀',
        filled.t: '▲',
        filled.b: '▼',
        filled.bl: '◣',
        filled.br: '◢',
        filled.tl: '◤',
        filled.tr: '◥',
        filled.small.r: '▸',
        filled.small.b: '▾',
        filled.small.l: '◂',
        filled.small.t: '▴',
    ],
```

But why there is `triangle.t` if it supposed to be `triangle.stroked.t`? Is it because you can combine parts of the names? Like if `filled.t` would've been the first one, will the `triangle`/`triangle.t` resolve to `triangle.filled.t`?

**Comment by laurmaedje** [comment]
> Is it because you can combine parts of the names? 

Exactly.

**Comment by pauladam94** [comment]
As a computer science researcher. I use often $triangle$ as an operator. I use the triangle in this direction |>. I think it is useful to have default to be classic operators because they are usually used a lot once there are introduced in an article for exemple.

However I understand the argument to be standard and to have the same behavior as latex even if latex does not justify it. Just for ease of use for past latex user.

**Comment by ludwig-austermann** [comment]
@pauladam94 I think either way, one should in these cases define the operate name as either symbol.

Although, I have rarely used either triangle symbol, I know that another 'common' usage of `triangle.t` is to denote the symmetric difference of sets.

**Comment by laurmaedje** [comment]
Closed by https://github.com/typst/typst/pull/3628
