### ISSUE TITLE
Potential off-by-one in `typst_syntax::node::LinkedNode::leaf_at`

### ISSUE THREAD

**Issue by mtoohey31** [typst/typst#3565]
### Description

Hello! I was investigating this issue with typst-lsp: https://github.com/nvarner/typst-lsp/issues/447. It looks like the cause might be an off-by-one issue in `leaf_at`, and I have a fix that resolves the particular issue in question, but it appears to break autocomplete in some circumstances, and I wanted to double-check that I'm understanding the intended behaviour correctly before attempting to change things.

In the existing code, it looks like if, for example, you have a leaf node with offset 5 and len 3, the leaf will be considered "at" the cursor for cursor values ranging from 6 to 8 (inclusive). Intuitively though, I would expect that this range should be from 5 to 7 (inclusive). Is this wrong?

Here's the fix I attempted:

```diff
diff --git a/crates/typst-syntax/src/node.rs b/crates/typst-syntax/src/node.rs
index d70f39b7..e959349a 100644
--- a/crates/typst-syntax/src/node.rs
+++ b/crates/typst-syntax/src/node.rs
@@ -828,17 +828,14 @@ impl<'a> LinkedNode<'a> {
 
     /// Get the leaf at the specified byte offset.
     pub fn leaf_at(&self, cursor: usize) -> Option<Self> {
-        if self.node.children().len() == 0 && cursor <= self.offset + self.len() {
+        if self.node.children().len() == 0 && cursor < self.offset + self.len() {
             return Some(self.clone());
         }
 
         let mut offset = self.offset;
-        let count = self.node.children().len();
-        for (i, child) in self.children().enumerate() {
+        for child in self.children() {
             let len = child.len();
-            if (offset < cursor && cursor <= offset + len)
-                || (offset == cursor && i + 1 == count)
-            {
+            if offset <= cursor && cursor < offset + len {
                 return child.leaf_at(cursor);
             }
             offset += len;
@@ -980,7 +977,7 @@ mod tests {
         assert_eq!(prev.text(), "set");
 
         let source = Source::detached("#let x = 10");
-        let leaf = LinkedNode::new(source.root()).leaf_at(9).unwrap();
+        let leaf = LinkedNode::new(source.root()).leaf_at(8).unwrap();
         let prev = leaf.prev_leaf().unwrap();
         let next = leaf.next_leaf().unwrap();
         assert_eq!(prev.text(), "=");
```

As I mentioned though, this appears to break autocomplete in typst-lsp... which makes some sense because that also uses `leaf_at`. Does it look like I'm on the right track about the indexes for `leaf_at`? If so I can try to get completion working again after applying the changes above. If I offset things correctly, or something along those lines, it's probably possible to fix things with the updated `leaf_at`. Just want to make sure my changes to `leaf_at` aren't going against it's intended behaviour before proceeding though.

Thanks!

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This was also discussed about this [on Discord](https://discord.com/channels/1054443721975922748/1088371867913572452/1214909256654917652). 

In short: `leaf_at` is intentionally yielding the element _before_ the cursor when it is between two elements due to autocomplete. 

For hover tooltips however, this is not ideal. I think what would be needed here is either two separate methods or a `side` argument to `leaf_at` which defines the leaf to which side is preferred. This would also nicely integrate with how e.g. CodeMirror also [gives such a side](https://codemirror.net/docs/ref/#view.hoverTooltip) for hover tooltip providers. I'm not sure how the LSP protocol handles this.

**Comment by laurmaedje** [comment]
You can test how CodeMirror behaves [here](https://codemirror.net/try/?c=aW1wb3J0IHsgYmFzaWNTZXR1cCwgRWRpdG9yVmlldyB9IGZyb20gImNvZGVtaXJyb3IiCmltcG9ydCB7IGhvdmVyVG9vbHRpcCB9IGZyb20gIkBjb2RlbWlycm9yL3ZpZXciCmltcG9ydCB7IGphdmFzY3JpcHQgfSBmcm9tICJAY29kZW1pcnJvci9sYW5nLWphdmFzY3JpcHQiCgpmdW5jdGlvbiB0b29sdGlwKHZpZXcsIHBvcywgc2lkZSkgewogIHJldHVybiB7CiAgICBwb3MsCiAgICBjcmVhdGUodmlldykgewogICAgICBjb25zdCBkb20gPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCJkaXYiKQogICAgICBkb20udGV4dENvbnRlbnQgPSBgUG9zOiAke3Bvc30sIFNpZGU6ICR7c2lkZX1gCiAgICAgIHJldHVybiB7IGRvbSB9CiAgICB9CiAgfQp9CgpuZXcgRWRpdG9yVmlldyh7CiAgZG9jOiAiY29uc29sZS5sb2coJ2hlbGxvJylcbiIsCiAgZXh0ZW5zaW9uczogW2Jhc2ljU2V0dXAsIGhvdmVyVG9vbHRpcCh0b29sdGlwKV0sCiAgcGFyZW50OiBkb2N1bWVudC5ib2R5Cn0pCgpkb2N1bWVudC5ib2R5LnN0eWxlLmZvbnRTaXplID0gIjQwcHgi). I wrote a small hover tooltip example.

**Comment by mtoohey31** [comment]
Awesome, thank you! Based on that, it looks like we should be using `leaf_at` when `side = 1`, and `leaf_before` when `side = -1`. The CodeMirror docs seem to indicate that it's just tooltip that has a side argument, right? If so, can we fix things in both typst-lsp and for CodeMirror by adding a side argument to `typst_ide::tooltip`, and conditionally calling `leaf_before` or `leaf_at` depending on that? For typst-lsp we'd just always pass the side argument corresponding to `leaf_at`.

**Comment by laurmaedje** [comment]
I think adding a side argument to leaf_at might be nicer to force people even more to think about this case.

If we decide against that, I would rename leaf_at to leaf_after. That makes it symmetrical and also (importantly) clearly breaks existing usages rather than failing silently due to changed behavior.

**Comment by mtoohey31** [comment]
> I think adding a side argument to leaf_at might be nicer to force people even more to think about this case.

Sounds good, does this look like what you were thinking: https://github.com/mtoohey31/typst/commit/3ea71975cd84a47a23f7c2ad10f06ea132d0724e?

**Comment by laurmaedje** [comment]
@mtoohey31 Looks good! Sorry for the late response, I forgot about this.

**Comment by mtoohey31** [comment]
Great, no worries! I've opened a PR with those changes at #3767.
