### ISSUE TITLE
How to implement the same functionality as \Lettrine in LaTex

### ISSUE THREAD

**Issue by InitialXKO** [typst/typst#357]
Drop cap is a very common function in book layout

**Comment by InitialXKO** [comment]
This will work : '''#let lettrine(term)=text(size:20pt,box[#term])'''

**Comment by jgm** [comment]
Can this be reopened?  The workaround you provide is not the same as LaTeX's `\lettrine`, which produces a *drop* capital (a box that subsequent lines flow around):

<img width="149" alt="Screen Shot 2023-03-29 at 7 32 23 PM" src="https://user-images.githubusercontent.com/3044/228713125-7441d99e-08a2-48d9-b89f-5c150571edf8.png">

Your code produces a capital that extends above the first line, but does not drop below it:

<img width="97" alt="Screen Shot 2023-03-29 at 7 31 41 PM" src="https://user-images.githubusercontent.com/3044/228713008-fe4fab69-ddd1-4043-abae-33cd7ddb7628.png">

I could not see a way to get a drop capital using typst, and if that's right, it points to an expressive limitation with the primitives.  What we need is a way to specify a box that things will flow around. (This would obviously have other uses too, like illustrations with text flowing around them.)  Is there a way to do this?

**Comment by laurmaedje** [comment]
Placing thing with colliders that other things flow around are unfortunately not yet implemented. This is also the reason footnotes and floating figures are still missing. Definitely one of the next things.

**Comment by YDX-2147483647** [comment]
I've seen a package for this at https://discord.com/channels/1054443721975922748/1057632212671025162/1167959498242146405.

> Fully automatic drop capitals, without the need to manually adjust the paragraph breaks. I'm not sure if I want to publish it as a package, as I don't know how good this really works, but if you want to try it locally, check here: https://github.com/EpicEricEE/typst-plugins/tree/master/dropcap
>
> ![](https://github.com/typst/typst/assets/73375426/b3dd612e-b6b3-4471-99c4-803b291870a3)

_Disclaimer_: I've not tested this package seriously.

**Comment by rafalkrupinski** [comment]
this issue can be closed, right?

**Comment by MDLC01** [comment]
There is still no option to enable drop capitals without relying on an external package, and the team has not explicitly stated that this is out of scope for vanilla Typst. This issue can stay open until one of those things happen.
