### ISSUE TITLE
Footnote in text after heading can cause orphan

### ISSUE THREAD

**Issue by JuliDi** [typst/typst#3582]
### Description

Under certain circumstances, a footnote in the text after a heading can cause the pagebreak to be placed between the heading and the text. I think this behavior is wrong because without the footnote heading and text stay on the same page.

Code to reproduce the issue:
```typst
#lorem(620)
= Heading
#lorem(10)
#footnote[#lorem(10)].
```
![image](https://github.com/typst/typst/assets/20155974/6ca12431-01f5-439e-a2b0-d89565181485)

Expected behavior is similar to what happens here, i.e., the heading appears on the next page together with the text.
```typst
#lorem(624)
= Heading
#lorem(20)
```
![image](https://github.com/typst/typst/assets/20155974/8c33f0c2-b9cb-4a75-80a5-92bfaab4fb7d)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by JuliDi** [comment]
This seems to also be happening with figures that take up a full page when the heading is followed by "special" content (like a list in my case, pure text seems to work). So I get
![Screenshot 2024-03-13 at 09 34 31](https://github.com/typst/typst/assets/20155974/4954d9ce-e98d-46f4-842a-ba092a98e585)

You can reproduce the behavior with this example:

```typst
#lorem(645)

#set figure(placement: auto)
#figure(
  rect(height: 24cm, width: 10cm),
  caption: [#lorem(20)],
)<fig:test>

=== Heading
- A
- B
- C
```

This happens with the latest main branch, as well (0fef8570).

**Comment by laurmaedje** [comment]
@JuliDi With lists etc. it's a long-standing issue: https://github.com/typst/typst/issues/1044

**Comment by JuliDi** [comment]
Thanks for the heads up! Hope there's a good solution to this at some point. These layout bugs just come and go as you edit the doc.

**Comment by laurmaedje** [comment]
Yeah, layout doesn't get as much love as it deserves at the moment because there are so many important things to do, but that will change in the future.

**Comment by laurmaedje** [comment]
I'll close this in favor of https://github.com/typst/typst/issues/1044

**Comment by Marcono1234** [comment]
Could this please be reopened? I am still experiencing this with Typst 0.13.1 for the sample code in the issue description, despite the widow and orphan prevention improvements.

Maybe closely related to #5314?
For the following sample code, if I remove the letter "b" there is no orphan heading but instead the footnote is on the first rather than the second page.
```typst
#set page(height: 10cm)

#show heading: set block(above: 2.5em, below: 1.5em)

#lorem(100)

a\
b   // <--- if you remove "b", the heading is properly wrapped

== Some heading

Some arbitrary text with a footnote, will this cause issues for Typst #footnote[my footnote]? #lorem(50)

#lorem(80)
```
