### ISSUE TITLE
figure.caption.separator is not set correctly.

### ISSUE THREAD

**Issue by SebastianJL** [typst/typst#3586]
### Description

I am on typst version 0.10.0 (ca5d682e) which I compiled with cargo directly from github.
I have the following show rule to make the figure supplement bold:
```typst
// #set figure.caption(separator: ": ")
#show figure.caption: c => [
  *#c.supplement #c.counter.display(c.numbering)#c.separator*#c.body
]

// Test figure
#figure(
  table(
    columns: 2,
    [a], [b],
    [c], [d]
  ),
  placement: none,
  caption: [This is a test caption]
)
```
This results in the following picture
![image](https://github.com/typst/typst/assets/11479035/9950688d-1c3e-425e-b3b6-c5bce7842db5)
Notice the red "auto"
If I un-comment the first line I get the correct behavior.
![image](https://github.com/typst/typst/assets/11479035/3a44ed65-6b0e-411a-88c6-36cc291b5674)
Also if I leave away the show rule on the figure entirely the auto disappears. (but then I don't get the nice bold supplements that I want.)
Am I doing something wrong in my show rule or is this a bug?

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by MDLC01** [comment]
This happens because the default value for `figure.caption.separator` is `auto`, not `[: ]`.

The default show rule for `figure.caption` uses `separator` if it is not `auto`, or some content that depends on the current language if `separator` is `auto`.

As of now, there is no way to get the default separator for a given language, so you have to recreate that yourself in your show rule:
```typ
#show figure.caption: c => {
  let separator = if c.separator != auto {
    c.separator
  } else {
    // Handle the `auto` case here.
    // Note that if you are on `main`, you can change the separator depending on the language like this:
    context {
      if text.lang == "en" {
        [: ]
      } else {
        ..
      }
    }
  }
  [*#c.supplement #c.counter.display(c.numbering)#separator*#c.body]
}
```

I'm not saying this is ideal, though. But this is how it works right now.

**Comment by xkevio** [comment]
> This happens because the default value for `figure.caption.separator` is `auto`, not `[: ]`.

Not quite. I can't reproduce this at all with the given code on either release v0.10, main (https://github.com/typst/typst/commit/aace521b56a078fd73f3d76862ee5f5d49235c51) or https://github.com/typst/typst/commit/ca5d682edb1553cd73c581a1726537e6415fe848.

**Comment by Leedehai** [comment]
I can repro this issue, though, on main (commit a2d0976):
```
#set figure.caption(separator: ": ")
#show figure.caption: c => [
  *#c.supplement #c.counter.display(c.numbering)#c.separator*#c.body
]

#figure(
  table([a]),
  caption: [This is a test caption]
)

---
#show figure.caption: c => [
  *#c.supplement #c.counter.display(c.numbering)#c.separator*#c.body
]

#figure(
  table([a]),
  caption: [This is a test caption]
)
```

**Comment by Leedehai** [comment]
I can repro this issue, though, on main (commit a2d0976), and agree with @MDLC01 's assessment above.
```
#set figure.caption(separator: ": ")
#show figure.caption: c => [
  *#c.supplement #c.counter.display(c.numbering)#c.separator*#c.body
]

#figure(
  table([a]),
  caption: [This is a test caption]
)

---
#show figure.caption: c => [
  *#c.supplement #c.counter.display(c.numbering)#c.separator*#c.body
]

#figure(
  table([a]),
  caption: [This is a test caption]
)
```

**Comment by xkevio** [comment]
Yea now I can too, idk maybe I had the wrong revision or something, sorry!

**Comment by laurmaedje** [comment]
Worked in 0.10 because the separator was synthesized. I removed that with the styling rework because many fields were just synthesized to be present at all on `it` in show rules, not because they have special logic. But this one should have remained. I've opened https://github.com/typst/typst/pull/3621 to fix it.
