### ISSUE TITLE
Autocompletion doesn't work for items imported with asterisk

### ISSUE THREAD

**Issue by istudyatuni** [typst/typst#3589]
### Description

Example:
```typ
// a.typ
#let asdf = [asdf]

// b.typ
#import "a.typ": *
#asd| // <- cursor here
```

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
I checked and this is indeed fixed by https://github.com/typst/typst/pull/3842
