### ISSUE TITLE
Proper kerning of prime in math mode?

### ISSUE THREAD

**Issue by user202729** [typst/typst#359]
```
#let largeprime=box(height: 0.5em, move(dy: 0.1em, text(size: 1.3em)[$'$]))

$ℋ'_λ ; ℋ_λ' ; ℋ^1_λ; ℋ^largeprime_λ$ 
```

![image](https://user-images.githubusercontent.com/25191436/227848022-e19cacf6-cc8c-48ba-9305-2d3b1b368c51.png)

I think the issue is self-explanatory.

(Unfortunately this one may be a bit difficult because Unicode does not have any large prime character like LaTeX's `\prime`.)

**Comment by laurmaedje** [comment]
I'm gonna close this in favor of #439 even though this one was first because the latter one has more discussion already.
