### ISSUE TITLE
vline after rowspan is placed incorrectly

### ISSUE THREAD

**Issue by ludwig-austermann** [typst/typst#3608]
### Description

I am not sure what the correct behaviour should be, but by adapting to the new typst version v0.11-rc1, I noticed that (relevant line is the first line with `table.cell`)

```typst
#figure(table(
  columns: 4,
  rows: 20pt,
  stroke: none,
  align: center + horizon,
  table.cell(colspan: 2, [*maximize*]), table.vline(), table.cell(colspan: 2, [*minimize*]),
  table.hline(),
  table.cell(rowspan: 3, rotate(270deg, reflow: true)[constraints]), $>= b_i$, $<= 0$, table.cell(rowspan: 3, rotate(270deg, reflow: true)[variables]),
  $<= b_i$, $>= 0$,
  $= b_i$, [free],
  table.hline(),
  table.cell(rowspan: 3, rotate(270deg, reflow: true)[variables]), $>= 0$, $>= c_i$, table.cell(rowspan: 3, rotate(270deg, reflow: true)[constraints]),
  $<= 0$, $<= c_i$,
  [free], $= c_i$
), caption: [Translation scheme for an LP in general form.], kind: table)
```

produces

![test](https://github.com/typst/typst/assets/12214171/38c449e9-2c80-4498-afab-f5276a6c559b)

whereas I would expect this 

![test-1](https://github.com/typst/typst/assets/12214171/5dce13e7-71ee-4de4-82c7-1a853529a93b)

### Typst version

- [ ] I am using the latest version of Typst

**Comment by PgBiel** [comment]
That's a good point, thanks. I'll work on this, should be a quick fix.
