### ISSUE TITLE
Is there a way to cancel the column layout and restore the document to one column?

### ISSUE THREAD

**Issue by InitialXKO** [typst/typst#361]
When I use the show: columns.with function to split the document into multiple columns, the columns are cumulative instead of resetting. For example, if I first split the document into two columns with show: columns.with(2), and then use show: columns.with(2) again, the document will be split into four columns instead of two. And if I use show: columns.with(1), the document will remain in two columns instead of one.

I expected that the show: columns.with function would reset the column layout to the specified number of columns, regardless of the previous layout. I also expected that there would be a way to cancel the column layout and restore the document to one column.

**Comment by laurmaedje** [comment]
You could try using `#set page(columns: 2)` instead. That can be overridden later. With show it doesn't work, because it basically just puts your whole document into a `#columns(2)[...]` layout.

**Comment by ndtodoroff** [comment]
Related: #351

**Comment by laurmaedje** [comment]
Balanced columns are requested here: #466. Otherwise, using `#columns(2)[...]` works as intended.
