### ISSUE TITLE
set in show rule not working on Lists (Typst 0.11.0 regression)

### ISSUE THREAD

**Issue by TheJanzap** [typst/typst#3611]
### Description

`set list` in `show list` doesn't work anymore in Typst 0.11.0. The following code worked fine in 0.10.0

```typ
#show list: l => {
    set list(marker: "-")
    l
}
- This has the incorrect marker on Typst 0.11.0 #emoji.face.sad

#set list(marker: "-")
- This doesn't #emoji.face.smile
```

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
This is mentioned in the changelog:

> Setting properties on an element within a transformational show rule (e.g.. show heading: it => { set heading(..): it }) is not supported anymore (previously it also only worked sometimes); use show-set rules instead (Breaking change)

You should use `show-set` instead:

> Show-set rules on the same element (e.g. show heading.where(level: 1): set heading(numbering: "1.")) now work properly

In your case:

```typ
#show list: set list(marker: "-")
...
```

**Comment by TheJanzap** [comment]
Hm, alright. For a breaking change like this, I suggest to add a warning or an error to the compiler/web app, since currently this compiles just fine. Maybe for the full release?

**Comment by laurmaedje** [comment]
It's not really possible to produce an error since the code is still valid. It just affects only nested lists and not the currently shown list. Previously, it was also rather flakey and didn't always work properly (e.g. for headings).
