### ISSUE TITLE
(0.11.0-rc1) `typst watch` output can't be scrolled and doesn't react to terminal resizing

### ISSUE THREAD

**Issue by SillyFreak** [typst/typst#3613]
### Description

With the display of `typst watch` output being shown in an "alternate screen", the regular viewport behavior of a terminal is not automatically available. This is especially relevant when compilation results in an error message that does not fit the current terminal height. In this case
- using the arrow or page up/down keys does not scroll output
  - using the mouse wheel seems to be translated into arrow key presses (at least in my configuration)
- resizing the terminal does not reveal more of the output but only blank lines (triggering a recompile by editing shows all output that fits in the new terminal size).

This makes debugging problems that result in long error traces harder.

## Steps to reproduce

- create a document with errors in it, ideally nested for a longer trace
- run `typst w` on that document in a terminal with low height
- try to scroll the error output or resize the terminal

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by frozolotl** [comment]
I am now working on a solution to this.
