### ISSUE TITLE
Performance regression in 0.11-rc1

### ISSUE THREAD

**Issue by LaurenzV** [typst/typst#3622]
### Description

It seems that there is a relatively big performance regression with regards to tables and stacks in 0.11-rc1. Since the author of the document stated that the document shouldn't be shared around too much I can't post it here, but see the related Discord thread for more information. The document took around 1.5s to compile in 0.10 and now takes around 5s. We have identified [this commit](https://github.com/typst/typst/commit/145723b1ef4fa23f1f6665b8907dfe79d0bf83cf) to be responsible for that regression.

Here you can see a performance tracing of a single "stack iteration", which took around 11ms before:
<img width="1223" alt="image" src="https://github.com/typst/typst/assets/47084093/9e6f5800-9a85-4b76-8cc8-1a9e9905189a">

And it takes around 76ms after:
<img width="1428" alt="image" src="https://github.com/typst/typst/assets/47084093/8a66eb33-1dbd-4b57-8ee0-11194ee0fa65">

In total, the stack part only took around 136ms in the original version, while it takes 1.3s in the new version, so this is a pretty huge performance hit.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Expect tables to be around 2x-3x slower on average, when using only old features. They are usually slower then using new table features.

Stack, however, doesn't use any table features, so this is interesting and worth investigating.

**Comment by Enivex** [comment]
Considering the regression is tied to the context update, I don't think it's related to tables at all.

**Comment by Mc-Zen** [comment]
Replacing tables and stacks with some `children.join()` yields a little improvement (going from 5s to 3.3s) but that is still 2-3x worse  than version 0.10.
