### ISSUE TITLE
(0.11.0-rc1) `italic` in equation doesn't work correctly

### ISSUE THREAD

**Issue by OrangeX4** [typst/typst#3650]
### Description

In version 0.11.0-rc1, the `italic` function in equation doesn't work and text remains upright.

Minimal reproduction example:

```typst
$italic("abcd")$
```

![image](https://github.com/typst/typst/assets/34951714/49dd8d78-4b46-489f-af3e-8f68a011fee4)

### Operating system

Web app

### Typst version

- [x] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
https://typst.app/project/rvGE6caS3qU4oTD2FX1Otj example link here
