### ISSUE TITLE
Automatic numbering bug introduced when interacting with blocks

### ISSUE THREAD

**Issue by brynhum** [typst/typst#3661]
### Description

I have code to write a Mathematics test with questions and subquestions. I have boiled it down to a minimal working example to replicate the bug -- basically the subquestions should go a, b, c but they go -, -, a.

### Reproduction URL

https://typst.app/project/rmunz8o4lFgvM2UUeznpJZ

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Similar to https://github.com/typst/typst/issues/2480. Will need new location assignment to be fixed.
