### ISSUE TITLE
Smartquote in headings don't appear in generated bookmarks

### ISSUE THREAD

**Issue by liuguangxi** [typst/typst#3662]
### Description

When I have headings that contain quote characters, like below

```
= It's "Unnormal Heading"
= It’s “Normal Heading”

#set smartquote(enabled: false)
= It's "Unnormal Heading"
= It’s “Normal Heading”
```

The quote characters (' and ") in the bookmark for the first heading in the pdf outline were disappeared. If argument `enable` of `smartquote` set `false`, the quote characters still don't appear in the pdf outline for the third heading.

## Screenshot
![image](https://github.com/typst/typst/assets/2703168/2824c186-5312-4d3f-9a11-620c2f3619e8)

### Operating system

Windows

### Typst version

- [x] I am using the latest version of Typst

**Comment by A-Walrus** [comment]
Looking into the code this seems to be caused by the same thing as  #3424

**Comment by laurmaedje** [comment]
In contrast to #3424, this one is an easy fix though, at least if we're okay with the quotes just showing up, but not being smart. Then, it is just a matter of implement the `PlainText` trait on `SmartquoteElem`.
