### ISSUE TITLE
Typst not rendering report entry with genre while Hayagriva do

### ISSUE THREAD

**Issue by halsimov** [typst/typst#3666]
### Description
I was unable to get typst to render the following references correctly, and the outcome differs from that of [hayagriva](https://github.com/typst/hayagriva).
The good way is to print genre for reports and thesis.

### Minimum reproducible example
Here is the `refs.yaml`:
```yaml
Awesome_Tech_Report:
  type: report
  title: "My Awesome Tech Report"
  author:
    - First, Author
    - Second, Author
  date: 2023
  genre: Tech. Report
  publisher: My Lab, My University
  serial-number:
    doi: 10.48550/arXiv.2312.xxxxx
```

Here is the hayagriva code:
```rust
use hayagriva::io::from_yaml_str;
use std::fs;
use hayagriva::{
    BibliographyDriver, BibliographyRequest,
    CitationItem, CitationRequest,
};
use hayagriva::citationberg::{LocaleFile, IndependentStyle};

fn main() {
    let yaml = fs::read_to_string("tests/data/refs.yml").unwrap();
    let bib = from_yaml_str(&yaml).unwrap();
    
    let en_locale = fs::read_to_string("tests/data/locales-en-US.xml").unwrap();
    let locales = [LocaleFile::from_xml(&en_locale).unwrap().into()];
    
    let style_file = fs::read_to_string("tests/data/ieee.csl").unwrap();
    let style = IndependentStyle::from_xml(&style_file).unwrap();
    
    let mut driver = BibliographyDriver::new();
    
    for entry in bib.iter() {
        let items = vec![CitationItem::with_entry(entry)];
        driver.citation(CitationRequest::from_items(items, &style, &locales));
    }
    
    let result = driver.finish(BibliographyRequest {
        style: &style,
        locale: None,
        locale_files: &locales,
    });
    
    for bibentry in result.bibliography.unwrap().items {
        println!("{}", bibentry.content)
    }
}
```

With the following output: 
`A. First and A. Second, “My Awesome Tech Report,” My Lab, My University, Tech. Report, 2023. doi: 10.48550/arXiv.2312.xxxxx.`

And here is my typst code:
```typ
#page(width: auto, height: auto, margin: 2em)[
  Here is the cite @Awesome_Tech_Report

  #bibliography("tests/data/refs.yml", title: text("Here is the bibliography"), style: "tests/data/ieee.csl")
]
```
with the following result :
![test](https://github.com/typst/typst/assets/57481001/620b1a21-b245-4fbf-a83c-406e5a0967ab)

### System

`cargo -V`: cargo 1.76.0 (c84b36747 2024-01-18)
`uname -srvm`: Linux ashton-laval 5.14.0-1057-oem #64-Ubuntu SMP Mon Jan 23 17:02:19 UTC 2023 x86_64
`hayagriva -V`: Hayagriva CLI 0.5.2
`typst -V`: typst 0.10.0 (70ca0d25)

**Comment by halsimov** [comment]
My current workaround is to put the genre in the publisher because, in ieee style, those two pieces of informations are close together.

**Comment by Enivex** [comment]
Every type doesn't have every field, and even when they do, a style doesn't have print all of them. I doubt this is an actual bug.

**Comment by halsimov** [comment]
I am pretty sure genre is required in these cases.
Here is ieee csl style for [report followed by thesis](https://github.com/citation-style-language/styles/blob/cff658690ce45f10c5d8768a22f187bac80a5bdc/ieee.csl#L381)
```xml
        <else-if type="report">
          <group delimiter=", " suffix=".">
            <text macro="title"/>
            <text macro="publisher"/>
            <group delimiter=" ">
              <text variable="genre"/>
              <text variable="number"/>
            </group>
            <text macro="issued"/>
          </group>
          <text macro="access"/>
        </else-if>
        <else-if type="thesis">
          <group delimiter=", " suffix=".">
            <text macro="title"/>
            <text variable="genre"/>
            <text macro="publisher"/>
            <text macro="issued"/>
          </group>
          <text macro="access"/>
        </else-if>
```

Anyway why would hayagriva and typst would have two different outputs for the same reference and style when the latter use the former to render bibliographies ?

**Comment by Andrew15-5** [comment]
I have a [similar problem](https://discord.com/channels/1054443721975922748/1088371867913572452/1230329946115932201): I can't seem to get the genre's value in CSL in bib file.


```xml
...
  <bibliography>
    <layout>
      <text macro="citation-number" />
      <choose>
        <if type="book" match="any">
          <text variable="title" />
          <text variable="genre" />
        </if>
      </choose>
    </layout>
  </bibliography>
...
```

```bibtex
@book{1,
  title = {Any title},
  genre = {tutorial},
}
```

![image](https://github.com/typst/typst/assets/37143421/15dfb41d-3976-493f-a626-635e996d13d5)

I can't use `subtitle` because it's not defined in CSL, but `genre` is: https://docs.citationstyles.org/en/stable/specification.html#standard-variables. So is `title`. And since `title` is printed and `genre` isn't, it has to be a bug.

[genre.zip](https://github.com/typst/typst/files/15019087/genre.zip)

**Comment by Andrew15-5** [comment]
It looks like `archive` and `part-title` don't work as well. But `abstract` and `annote` do. How much more of them are not usable?

**Comment by Andrew15-5** [comment]
As a "temporary" workaround I added this: 

```xml
  <macro name="genre">
    <group prefix=": ">
      <choose>
        <if variable="genre">
          <text variable="genre" />
        </if>
        <else>
          <text variable="annote" />
        </else>
      </choose>
    </group>
  </macro>
```

**Comment by laurmaedje** [comment]
I can reproduce this in Typst 0.10, but not in Typst 0.11, so looks like it's fixed already.

**Comment by Andrew15-5** [comment]
Can confirm that `archive`, `abstract`, `annote`, `title`, and `genre` fields are working in v0.11.0, but `part-title` still isn't.
