### ISSUE TITLE
[0.11.0-rc1] Document set rules changed

### ISSUE THREAD

**Issue by VadimBim** [typst/typst#3676]
### Description

Hi!

I discovered this inconsistency in behavior between `v0.11.0-rc1` and `v0.10.0` . Here is the example:

```
#let titlepage(
  title: "Title",
) = {
  set document(title: title)

  align(center, text(1.5em, weight: 100, title))
  
  pagebreak()
}

#let disclaimer(
  author: "Me",
) = {
  set document(author: author)  
  set page(
    margin: (left: 30mm, right: 30mm, top: 40mm, bottom: 40mm),
    numbering: none,
    number-align: center,
  )

  v(75%)
  text(lorem(20))

  v(15mm)
  grid(
      columns: 2,
      gutter: 1fr,
      "Arrakis, " , author
  )
}

#titlepage()

#disclaimer()

```
`v0.10.0` compiles it but `v0.11.0-rc1` gives this error:
```
error: document set rules must appear before any content
  ┌─ ../thesis-template-typst/thesis_typ/disclaimer.typ:7:2
  │
7 │   set document(title: title, author: author)  
  │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
Here is the original opened [issue](https://github.com/Enter-tainer/typst-preview/issues/271).

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Yes, this was a bug fix that I forgot to include in the changelog. I'll add it to the full release changelog.

Previously, Typst unintentionally allowed `set document` directly after a page break, but just ignored it. For it to work, `set document` really must be the first thing and affect everything, with no title page or anything before it and no unaffected content after it.
