### ISSUE TITLE
Test layout/grid-positioning.typ fails on Alpine Linux

### ISSUE THREAD

**Issue by jvoisin** [typst/typst#3682]
### Description

I just sent a [merge request](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/62245) to bump typst from 0.10.0 to 0.11.0 on Alpine Linux, and the `layout/grid-positioning.typ` test is failing on [armv7](https://gitlab.alpinelinux.org/jvoisin/aports/-/jobs/1305388) and [x86](https://gitlab.alpinelinux.org/jvoisin/aports/-/jobs/1305384):

```
layout/grid-positioning.typ ❌
  Subtest 13 does not match expected errors.
    Not annotated // Error: 213:16-213:35 number too large
    Not emitted   // Error: 213:3-213:39 cell position too large
  Subtest 14 does not match expected errors.
    Not annotated // Error: 222:23-222:42 number too large
    Not emitted   // Error: 222:3-222:46 cell position too large
  Subtest 15 does not match expected errors.
    Not annotated // Error: 230:22-230:41 number too large
    Not emitted   // Hint: 230:3-230:45 try reducing the cell's rowspan or colspan
    Not emitted   // Error: 230:3-230:45 cell would span an exceedingly large position
```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Right, I guess I didn't consider that `usize` isn't always `u64`. This means that the limits will vary depending on your architecture.

It could be best to simply remove those tests for now - they are important to ensure a proper overflow check, but they will have to be downgraded to manual tests due to this problem.

**Comment by jvoisin** [comment]
What would be the best way to remove them for now? A simple `rm ./tests/typ/layout/grid-positioning.typ` in the `build` step?

**Comment by PgBiel** [comment]
> What would be the best way to remove them for now? A simple `rm ./tests/typ/layout/grid-positioning.typ` in the `build` step?

You can apply the following patch (I will open a proper PR soon):

```diff
diff --git a/tests/typ/layout/grid-positioning.typ b/tests/typ/layout/grid-positioning.typ
index 5461fb1c..228fadf7 100644
--- a/tests/typ/layout/grid-positioning.typ
+++ b/tests/typ/layout/grid-positioning.typ
@@ -203,29 +203,3 @@
   // Robert got grade B on other exams.
   ..(table.cell(y: 4, fill: aqua)[B],) * 2,
 )
-
----
-// Error: 5:3-5:39 cell position too large
-#grid(
-  columns: 3,
-  rows: 2em,
-  fill: (x, y) => if calc.odd(x + y) { red.lighten(50%) } else { green },
-  grid.cell(y: 6148914691236517206)[a],
-)
-
----
-// Error: 5:3-5:46 cell position too large
-#table(
-  columns: 3,
-  rows: 2em,
-  fill: (x, y) => if calc.odd(x + y) { red.lighten(50%) } else { green },
-  table.cell(x: 2, y: 6148914691236517206)[a],
-)
-
----
-// Error: 3:3-3:45 cell would span an exceedingly large position
-// Hint: 3:3-3:45 try reducing the cell's rowspan or colspan
-#grid(
-  columns: 500,
-  grid.cell(rowspan: 6148914691236517206)[a]
-)
```

**Comment by jvoisin** [comment]
I went with `rm tests/typ/layout/grid-positioning.typ` instead :o)
