### ISSUE TITLE
`calc.abs` doesn't work on page margin inside context

### ISSUE THREAD

**Issue by ntjess** [typst/typst#3685]
### Description

```typst
#set page(margin: (left: 1in, right: 1in))
#set rect(stroke: black + 1in)
#context [
  #assert(page.margin.left == rect.stroke.thickness)
  #calc.abs(rect.stroke.thickness)
  #calc.abs(page.margin.left)
]

```

The type of `stroke.thickness` and `margin.left` are verified to be the same. However, the compiler panics in the second `abs` calculation with:
```
expected integer, float, length, angle, ratio, or fraction, found relative length
```

If a relative length is not allowed, then shouldn't `calc.abs` fail on the first calculation too? What causes relative lengths to be invalid only on the page margin?

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
This works
```#set page(margin: (left: 1in, right: 1in))
#set rect(stroke: black + 1in)
#context [
  #assert(page.margin.left == rect.stroke.thickness)
  #calc.abs(rect.stroke.thickness)
  #calc.abs(page.margin.left.length)
]```

Stroke.thickness is not a relative length, unlike page.margin.left. While ratio in this case is 0% you still have to explicitly extract the absolute part of it before applying calc abs.

**Comment by ntjess** [comment]
@Enivex not so: `#calc.abs(-72pt)` will happily return `72pt` as is the case during the stroke calculation. The bug report is that the behavior is inconsistent.

**Comment by Enivex** [comment]
> @Enivex not so: `#calc.abs(-72pt)` will happily return `72pt` as is the case during the stroke calculation. The bug report is that the behavior is inconsistent.

`-72pt` is not a relative length

**Comment by ntjess** [comment]
Apologies for the confusion. I was surprised that `72pt` can be both a relative length and a length, since printing the value doesn't give an indication that the types are different (along with the `==` operator indicating they are equal)

**Comment by Enivex** [comment]
I agree that it's not ideal.
