### ISSUE TITLE
Syntax highlighted raw texts within RTL incorrect direction

### ISSUE THREAD

**Issue by A-Walrus** [typst/typst#3689]
### Description

```typ
// Mixing raw
#set text(lang: "he")
#show raw: set text(lang: "en", dir: ltr)
לדוג. `if a == b:` זה תנאי

#set raw(lang:"python")
לדוג. `if a == b:` זה תנאי
```

![image](https://github.com/typst/typst/assets/58790821/4ee874b4-dd43-4f28-a559-69d2c9500196)

This is due to my PR #3532, since now each section of text is treated individually.

This possible problem was pointed out, but we didn't have an example of where it matters, now we do :laughing: 

> On another note: As implemented, this will individually isolate consecutive segments of text going against the paragraph direction (multiple segments can be forced e.g. by just putting `/**/` between words). Could that be a problem?

_Originally posted by @laurmaedje in https://github.com/typst/typst/issues/3532#issuecomment-1976050396_

Before #3532 for reference (notice the colon on the wrong side):
![image](https://github.com/typst/typst/assets/58790821/8af55b56-7936-4886-b1cd-763e02bf55ae)

# Possible solutions
- Revert #3532, re-introducing the bug it was trying to solve (code within RTL text will still be broken)
- Add `dir` field to raw, just like text has, and properly handle raw text direction (would adding `lang` as well be necessary, I don't see why but maybe I'm missing something)
- Something completely different?

@laurmaedje would love your input on this, thanks!

### Typst version

- [X] I am using the latest version of Typst

**Comment by emilyyyylime** [comment]
I think there's a nice parallel here between `raw`'s `lang` and `text`'s `lang`, where by setting `raw(lang: "rust")` you are indicating that the content is meant to be read as rust code and thus– from left to right. A separate `dir` argument will thus solve the problem elegantly

**Comment by laurmaedje** [comment]
I don't agree that a `dir` argument on raw would be a clean solution, as raw ends up as text and thus should react to its properties as everything else. I can see having `lang: "rust"` set the text dir to LTR in `RawElem`'s `ShowSet` impl (or maybe generally, are there any RTL programming languages?).

**Comment by emilyyyylime** [comment]
> are there any RTL programming languages?

Mostly joke/esolangs or translation efforts of existing langs, nothing I would expect Typst to handle

**Comment by A-Walrus** [comment]
@laurmaedje took your advice and simplified my fix massively. Now the raw direction is configured through `ShowSet` :+1:
