### ISSUE TITLE
[FR] Make footnotes

### ISSUE THREAD

**Issue by KronosTheLate** [typst/typst#369]
Is there a way to make footnotes? If not, I want one.

**Comment by vaavaav** [comment]
https://typst.app/docs/reference/layout/page/#parameters--footer

You should probably not open an issue to just ask a question. It's probably better to ask on their discord server or in the discussions panel.

**Comment by math221e** [comment]
> https://typst.app/docs/reference/layout/page/#parameters--footer
> 

To my knowledge the docs does not contain anything specifically related to footnotes. You can of course modify the footer. But what I think is meant, is a similar feature as \footnote{} in latex. Such that you don’t have to manually modify the footer for each footnote.

**Comment by vaavaav** [comment]
> > https://typst.app/docs/reference/layout/page/#parameters--footer
> > 
> 
> To my knowledge the docs does not contain anything specifically related to footnotes. You can of course modify the footer. But what I think is meant, is a similar feature as \footnote{} in latex. Such that you don’t have to manually modify the footer for each footnote.

Hm, I see what you mean and I do understand that using footer may not be the best approach, tho it must be possible.

I'm now curious and maybe I'll try to emulate this behaviour with some function, but this is probably best if implemented in rust and then made available in Typst base.

**Comment by laurmaedje** [comment]
Yeah, this is unfortunately not yet implemented. We know that it is important and will work on it soon.

**Comment by KronosTheLate** [comment]
> But what I think is meant, is a similar feature as \footnote{} in latex.
Excacly

> Yeah, this is unfortunately not yet implemented. We know that it is important and will work on it soon.
Awesome! No rush no worries, I could just not find any existing issues mentioning footnotes, and so I thought I should make one. Loving Typst so far, thanks a bunch for your hard work!

**Comment by Enivex** [comment]
There's a discussion about footnotes here

https://github.com/typst/typst/discussions/222

**Comment by lucasew** [comment]
I was able to implement some sort of footnotes by using the footer. As footers don't expand with enough content it just overflows. Here is my sample code:

```
#let footnote_state = state("footnote", ())
#let footnote_counter = counter("footnote")

#let footnote(text) = {
    locate(loc => {
        let counter = footnote_counter.at(loc)
        footnote_state.update(old => {
            old.push((
                index: counter.first(),
                text: text,
                page: loc.page()
            ))
            old
        })
        [ #super[ [#counter.first()] ] ]
    })
    footnote_counter.step()
}


#set page(
    paper: "a4",
    header: align(right, [
        #lorem(5)
    ]),
    footer: [
        /* Footnotes of this page */
        #locate(loc => {
            let state = footnote_state.at(loc)
            for x in state.filter(x => x.page == loc.page()) {
                [ #x.index. #x.text #linebreak() ]
            }
        })

        #counter(page).display()
    ],
    numbering: "1"
)

#let sum(x, y) = [A soma de #x e #y é #(x + y)]

= Teste
#sum(6, 9)

#lorem(50)
#footnote("Teste")
#lorem(100)
#footnote("Teste")
#lorem(50)

#pagebreak()

#lorem(100)
#footnote("Teste")
#lorem(100)


```

**Comment by ararunaufc** [comment]
I believe that in order to not mess up with user's custom footer definitions, there are at least two options:

- Have a separate dedicated region just above the footer to typeset footnotes
  - They would have to subtract from the pages' "real estate" for content.
- Place them inside "floating" container with gravity associated
  - That could enable custom placing of them, allowing for "section notes" maybe
  - Would need implementing "floating" containers

Or, to avoid polluting the interface for `page`:
- Allow footer and header areas to expand and influence the pages' "real estate" for content.
  - This expansion behavior will probably need to be implemented eventually, as it is currently limiting. (Typesetting engines are useful for all sorts of content, not only "academia-like" documents...)

**Comment by KronosTheLate** [comment]
As https://github.com/typst/typst/issues/712 lists footnotes as a point on the checklist:
![image](https://user-images.githubusercontent.com/61620837/232205438-bc5d9c19-337f-4d54-90f0-48271bdcede5.png)

I consider this issue closed, as it was intended essentially as a ToDo.

**Comment by KronosTheLate** [comment]
This is implemented as of 0.4!

**Comment by alkeryn** [comment]
hey sorry for the necrobump but would it be possible to make "block footnotes" meaning a footnote but that is only at the end of a specific block and not for the whole document.

**Comment by alkeryn** [comment]
@laurmaedje oh nice.
I feel like you could probably hack up the feature using query but it wouldn't be built-in.
Also being able to reference anything or even just numbered list items would be nice.
