### ISSUE TITLE
cannot reset equation numbers to 1

### ISSUE THREAD

**Issue by arctic-penguin** [typst/typst#370]
see #146 

The user wants to reset the equation counter, so  the next equation shows as `(1)`.

MRE:
```
#set page(
  width: 6cm,
  height: auto

)
#set math.equation(numbering: "(1)")

$ v := vec(x_1, x_2, x_3) $

$ a arrow b $

$ y := x / 2 $

#counter(math.equation).update(1)

$ z := y^2 $
```

Providing `#counter(...).update(1)` makes the next number be `(2)`.

![screen07](https://user-images.githubusercontent.com/103587359/227938684-8cbcc09e-f045-4bb9-811f-300a25b19916.png)

So we would need to update the counter to `0`. 

```
#counter(math.equation).update(0)
$ z := y^2 $
```

This does not compile.
```
writing to bug.pdf

[14:11:25] compiled with errors

error: number must be positive
   ┌─ bug.typ:14:31
   │
14 │ #counter(math.equation).update(0)
   │                                ^
```

**Comment by laurmaedje** [comment]
Already fixed on main. :) Until this update is pushed to the app and released properly, you can also do `#counter(math.equation).update(())`.
