### ISSUE TITLE
heading (parts) derived from context not bookmarked

### ISSUE THREAD

**Issue by lkndl** [typst/typst#3705]
### Description

Parts of a heading derived from `context` are not bookmarked with typst 0.11.0 `2bf9f95d`. They are however correctly displayed and outlined.

```
#let var-content = [from a variable]
#let context-content = context if true [it's true] else [never gonna happen]

= a normal heading
#lorem(4)

= #var-content
#lorem(4)

= before; #context-content\; after // partially bookmarked
#lorem(4)

#outline()
```

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by emilyyyylime** [comment]
See also: #3424, #3662, #2416, #1163

**Comment by lkndl** [comment]
> See also: #3424, #3662, #2416, #1163

oh well I should have searched for "bookmarks" instead :/
