### ISSUE TITLE
Add rhomb and parallelogram symbols

### ISSUE THREAD

**Issue by kamack38** [typst/typst#3706]
### Description

Currently, Typst is missing the rhomb and parallelogram/rhomboid symbols.

### Use Case

These symbols could be used to describe the formula for the shape's field. For example:
```typst
$Field_square.stroked = a^2$
```

**Comment by Enivex** [comment]
Are these Unicode symbols? That would be a prerequisite

**Comment by eclecticfluff** [comment]
There is a parallelogram and rhombus, but I am not familiar with any fields of math that use them so cannot vouch for their size or orientation being correct.
▱ U+25B1 WHITE PARALLELOGRAM
◊ U+25CA LOZENGE

**Comment by kamack38** [comment]
> There is a parallelogram and rhombus, but I am not familiar with any fields of math that use them so cannot vouch for their size or orientation being correct.
> ▱ U+25B1 WHITE PARALLELOGRAM
> ◊ U+25CA LOZENGE
> 

I think these are correct.
