### ISSUE TITLE
Custom contextual functions

### ISSUE THREAD

**Issue by refparo** [typst/typst#3713]
### Description

Allow use-defined contextual functions. This would require a new syntax, possibly `let context fun(params) = ...`.

### Use Case

Contextual values are opaque and can't be used as normal values. For example, one might want to use the contextual value `measure("1").height + par.leading` (which equals to the height of a line) in many different places. Allowing custom contexual functions would fill this use case.

**Comment by PgBiel** [comment]
Omitting the `context` keyword is enough. The code below should work:

```typ
#let f(x) = measure(x).height + par.leading

#let g(x) = context {
  let res = f(x)
  block(height: res)[Hi!]
}
```

**Comment by refparo** [comment]
Thank you. It's a little unintuitive that this is already possible. I'll close this issue.
