### ISSUE TITLE
SVG arrowheads missing since 0.11

### ISSUE THREAD

**Issue by deffi** [typst/typst#3715]
### Description

Since Typst 0.11, some arrow heads in SVG files are no longer rendered.

### Example

SVG files (both from Inkscape):
1.svg: ![1](https://github.com/typst/typst/assets/470243/5b489e5e-a642-4e38-b87b-6c12616a3f49)
2.svg: ![2](https://github.com/typst/typst/assets/470243/5c2d5552-cdbc-4ad7-8894-fd0dd7e74269)

arrows.typ:
```typst
1.svg: #image("1.svg", width: 10.521mm)
2.svg: #image("2.svg", width: 11.656mm)
```

When compiled with Typst 0.10:
![grafik](https://github.com/typst/typst/assets/470243/49ab9aef-325f-4400-b962-8ba1124b7786)

When compiled with Typst 0.11:
![grafik](https://github.com/typst/typst/assets/470243/d0829108-2c2a-46df-838e-7ded5666762d)

All file as .zip: [arrows.zip](https://github.com/typst/typst/files/14639871/arrows.zip)

### Operating system

Windows, Linux

**Comment by laurmaedje** [comment]
cc: @LaurenzV

**Comment by LaurenzV** [comment]
I submitted a path for this upstream: https://github.com/RazrFalcon/resvg/pull/725

Thanks for the report! Should probably be fixed by the next release.

**Comment by wenbin-liu** [comment]
Is this bug fixed in resvg? Arrow missing for svg is quite disturbing.

**Comment by LaurenzV** [comment]
Yes, it's fixed in resvg. Keep in mind that you can work around this though by replacing instances of "context-fill" and "context-stroke" with the color you want in the SVG.

**Comment by wenbin-liu** [comment]
OK, thanks. Then we just need to wait for typst to update

**Comment by deffi** [comment]
It seems like Typst 0.11.1 still uses resvg 0.38.0, which does not yet incorporate the fix.

**Comment by LaurenzV** [comment]
Yes, indeed, 0.11.1 was just a patch release for some issues, but it didn't include this one.

**Comment by KronosTheLate** [comment]
Until then, if you are in a pinch, you can [install the Julia programming language](https://github.com/JuliaLang/juliaup?tab=readme-ov-file#installation), and run the script below. I am currently using it to convert all my svg illustrations to png files for my masters thesis:
```julia
using Rsvg
using Cairo

"""
	svg2png(filename_in, overwrite=false, dpi::Real=300)

Load an SVG file `filename_in`, use Rsvg.jl to render the image 
for cairo, then use Cairo.jl to write that image to a PNG file.
"""
function svg2png(filename_in, overwrite=false, dpi::Real=300)
	if !isfile(filename_in)
		error("The given filename $filename_in returned `false` when passed to `isfile`. Are you sure that the file exists?")
	end
	filename_in_noext, input_extension = splitext(filename_in)
	if input_extension != ".svg"
		error("Extension of given filename $filename_in is $filename_in_ext, where \".svg\" was expected. Aborting.")
	end
	filename_out = filename_in_noext * ".png"
	if isfile(filename_out) && !overwrite
		error("Output file $filename_out already exists, and the second positional argument `overwrite` is set to false. Aborting.")
	end
	
	r = Rsvg.handle_new_from_file(filename_in)
	Rsvg.handle_set_dpi(r, float(dpi))  # Conversion to float due to unnecessary contraints on arguments to Rsvg.handle_set_dpi
	d = Rsvg.handle_get_dimensions(r)
	cs = Cairo.CairoImageSurface(d.width,d.height,Cairo.FORMAT_ARGB32)
	c = Cairo.CairoContext(cs)
	Rsvg.handle_render_cairo(c,r)
	
	Cairo.write_to_png(cs,filename_out)
	return nothing
end

function convert_all_svgs(dir, overwrite=false, dpi::Real=300)
	if !isdir(dir)
		error("The given directory $dir returned false when passed to `isdir`. Are you sure the directory exists?")
	end
	map(readdir(dir, join=true)) do filename
		if splitext(filename)[2]==".svg"
			svg2png(filename, overwrite, dpi)
		end
	end
end

# With my svg files inside a folder "illustrations", I 
# then just run `convert_all_svgs("illustrations", true)`
```

**Comment by LaurenzV** [comment]
I mean, as mentioned above, if all your arrows are in the same color, you could instead just write a script that replaces all instances of `context-fill` and `context-stroke` with `black`, then you don't need to convert the SVGs into bitmap images.

**Comment by KronosTheLate** [comment]
Opening the SVG in a text editor and doing that search-and-replace does indeed sound quite a lot easier 😅

However, it would fail to preserve the colours of the true SVG, no? Sometimes, in the preview (vscode extension), the arrowheads were indeed filled as black, which was quite visually disruptive.

**Comment by deffi** [comment]
You may not even need a script – there are tools that can do search and replace across multiple files: Eclipse, VS Code, sed (using the `--in-place` option), and probably many more. As @LaurenzV noted, this is only practical if all of the arrows are the same color.

In my case, the following two replacements (applied to ≈80 files with Eclipse) worked perfectly:
  - `fill:context-stroke` → `fill:#000000`
  - `stroke:context-stroke` → `stroke:none`

**Comment by LaurenzV** [comment]
Has been fixed on main.
