### ISSUE TITLE
math.sans shows bold greek symbols

### ISSUE THREAD

**Issue by Loewe1000** [typst/typst#3719]
### Description

Using math.sans() makes greek letters very bold.

`sans(mu = beta times + a b c d)` compiles to
<img width="382" alt="SCR-20240319-bnha" src="https://github.com/typst/typst/assets/1015274/37bb9e65-cdc8-491a-a3b1-a6f88d63f05e">

### Reproduction URL

https://typst.app/project/p7uxKHHQqFQyH2uzWulr_8

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
Unfortunately there are only regular, bold and sans-serif bold mathematical Greek letters in unicode, no non-bold sans-serif. There isn't anything typst can do about that.

Your only real option is a sans-serif math font like Fira Math.

**Comment by Loewe1000** [comment]
Thanks for the quick answer. That's very sad...
Fira Math is no option because there are many other problems, like no correct long arrows

<img width="297" alt="image" src="https://github.com/typst/typst/assets/1015274/4298e61c-f969-467d-879d-690a3591216b">

**Comment by emilyyyylime** [comment]
I think you should be able to just create a helper function to only use Fira Math on specific letters or even `show regex("\\w")`
