### ISSUE TITLE
Line breaking for punctuation after inline math

### ISSUE THREAD

**Issue by user202729** [typst/typst#372]
![image](https://user-images.githubusercontent.com/25191436/227952613-b2a0c4da-03dc-4f8c-8df5-6e4fac2a7645.png)

```
#set par(first-line-indent: 20pt, justify: true)

#lorem(20)

#lorem(14)  $x^2$.

#lorem(14)  $x^2.$
```

Would be nice if we can get the equivalent of \penalty etc. in TeX, although I feel Typst's line breaking algorithm is much less sophisticated than TeX's at the moment.

**Comment by emilyyyylime** [comment]
@jeanas the best thing currently as far as I can tell is replacing `$math$.` with `#box[$math$.]`. It's not ergonomic at all but it fixes the layout issues.

**Comment by laurmaedje** [comment]
[Fixed.](https://github.com/typst/typst/commit/46ce9c94e3f615751989d3cba5aa1599e0ba5913)
