### ISSUE TITLE
Sub/superscript spacing issue when aliasing commonly used math expressions with `#let`

### ISSUE THREAD

**Issue by janosh** [typst/typst#3724]
there's an active discussion over at https://github.com/typst/typst/discussions/3357 about the horizontal spacing issue when adding exponents to macro-like `#let a0 = alpha_0` aliases (see screenshot below). there's no solution among the half dozen replies.
given this is a very common use case (and easily solved with macros in LaTeX), i think it's worth promoting the discussion to an issue

<div type='discussions-op-text'>

<sup>Originally posted by **aldanor** February  5, 2024</sup>
Maybe I'm missing something completely obvious, but I did spend time going through docs and some examples in the source code as well (which didn't help much).

I'm trying to do something seemingly simple -- define some commonly used 'math expression' (commonly used piece of content in `$$` context), e.g. something like `a0 := alpha_0`. Out of everything I've tried, the two approaches (see below) seemed to have sort-of-worked, but I'm not sure that's the correct way of doing it.

It also does result in a weird "boxing" of the resulting expressions, which messes up subscripts and superscripts. Here's an example:

```typst
#let a0v1 = sym.alpha + sub([0])
#let a0v2 = $alpha_0$
$ &alpha_0^2\ &a0v1^2\ &a0v2^2 $
```

which results in

![image](https://github.com/typst/typst/assets/2418513/e43a6d5e-658f-4481-bb5a-ad5be8c1f00c)

Is there a way to define something like `alpha_0` via `#let` so it works correctly (i.e. as it shows on the first line in the example above)? (and if what I'm doing is completely wrong, maybe the docs should reflect it in a more obvious fashion?)

Thanks!</div>

**Comment by laurmaedje** [comment]
> ...  i think it's worth promoting the discussion to an issue ...

Agreed. I've marked it as a bug.

**Comment by EpicEricEE** [comment]
I was playing a bit around with a show rule and came up with the following, which seems to do fine as a workaround so far (though my testing was quite limited):

<details>

<summary> Show Rule</summary>

```typ
#show math.attach: it => {
  // Check if base of this attach element is also
  // an attach element or an equation containing one
  let original = if it.base.func() == math.attach {
    it.base
  } else if it.base.func() == math.equation and it.base.body.func() == math.attach {
    it.base.body
  } else {
    return it
  }

  let field-names = ("b", "br", "bl", "t", "tr", "tl")

  // Add fields of original attach element
  let fields = (:)
  for field in field-names {
    let value = original.at(field, default: none)
    if value != none {
      fields.insert(field, value)
    }
  }

  // Add fields of this attach element. If a field
  // is already set, add value to the "next level"
  // attach element.
  let fields-next = (:)
  for field in field-names {
    let value = it.at(field, default: none)
    if value != none {
      if field not in fields {
        fields.insert(field, value)
      } else {
        fields-next.insert(field, value)
      }
    }
  }

  if fields-next.len() == 0 {
    // Only one level of attachments
    math.attach(
      original.base,
      ..fields,
    )
  } else {
    // Wrap with second-level attach element
    math.attach(
      // Prevent recursion by adding empty content
      [] + math.attach(original.base, ..fields),
      ..fields-next,
    )
  }
}
```

</details>

```typ
#let a0 = math.attach(math.alpha, b: [0])
#let a1 = $alpha^1$

$ a0 + a1 + a0_2 + a1_2 + a0^2 + a1^2 $
```

![image](https://github.com/typst/typst/assets/7191192/84a67660-3700-4d43-9fe4-2884c6cc00ec)
