### ISSUE TITLE
`math.class` is not taken into account within a `context` expression

### ISSUE THREAD

**Issue by loutr** [typst/typst#3727]
### Description

I maintain the tiny `xarrow` package and the latest version 0.11 of the compiler seems to have brought a regression, which [impacts the package](https://codeberg.org/loutr/typst-xarrow/issues/6). A minimal example is the following:

```typst
#let test = math.class("relation", "--")
$ a test b $
```
displays correctly, with an appropriate spacing around `--`, but

```typst
#let test = style(_ => math.class("relation", "--"))
// or the new #let test = context math.class("relation", "--")
$ a test b $
```
doesn't (it has an extra space between `--` and `b`).

This is easily fixable in the case of xarrow for instance, where it boils down to swapping operations as in:
```
// where expr depends on context of course
#let test = math.class("relation", context expr)
```
but I figured it would be best to signal it anyway. Sorry if this is a duplicate or my mistake or anything. Thanks for your amazing work as always!

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by wrzian** [comment]
This seems like it might be related to the issue with the `math-call-pass-to-box` test I added? See here: https://github.com/typst/typst/pull/3786#issuecomment-2061864950

**Comment by mkorje** [comment]
On main, all three examples look identical. Bisect says #4348 fixed this.

Is there still an issue here? @EpicEricEE you mentioned in #4348 that the "--" is not being measured correctly.

**Comment by EpicEricEE** [comment]
I did, but that is probably a separate issue

![image](https://github.com/user-attachments/assets/03250e36-fa2c-4037-a2e3-d11e67003d22)
