### ISSUE TITLE
Incorrect length measure in math superscript

### ISSUE THREAD

**Issue by loutr** [typst/typst#3729]
### Description

The following code:
```typst
#let length = context repr(measure("--").width)
$ a length a ^ length $
```
renders as:
![image](https://github.com/typst/typst/assets/21224281/37bc977a-7992-4b24-9a58-ed833d0246ee)

while the length provided in superscript should arguably be smaller. This is also happens with e.g. nested fractions, where content is also shrunk visually, but the measured length remains unchanged. Am I correct to believe the lengths should differ?

This can cause packages which rely on precise measurement to display things incorrectly in these contexts, like xarrow (which has not been too problematic so far because arrows are rarely used in superscript, nested fractions, etc.)

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
if i understand it correctly, `length` is a concrete value and will not change depends on the context.

**Comment by Enter-tainer** [comment]
to produce the desired result, you may want to define length as a function.

**Comment by laurmaedje** [comment]
The interaction of math and styling is unfortunately not great at the moment. One workaround is to add a container around the context to force the normal layout pipeline, e.g. a `box`.
