### ISSUE TITLE
Custom syntax highlighting

### ISSUE THREAD

**Issue by imbrem** [typst/typst#373]
Would it be possible to support syntax highlighting for custom languages?

**Comment by SaitoAtsushi** [comment]
I found a good example in code comment.

https://github.com/typst/typst/blob/4428646c9997171e3aea25ad2f0c151755f072da/library/src/text/raw.rs#L48-L58

We can imitate this.

Keyword emphasis can be written like following:

````
#show raw.where(lang: "foo_lang"): it => [
    #show regex("\b(for|to|begin|end)\b") : keyword => text(weight:"bold", keyword)
    #it
]

```foo_lang
for i=1 to 10
begin
    print(i)
end
```
````

**Comment by imbrem** [comment]
Thanks, I didn't think of that! Guess I'll go ahead and close this then.

**Comment by lucifer1004** [comment]
Is it possible to provide custom Sublime syntax files to support extra languages? The workaround above can only deal with some naive cases.

**Comment by PgBiel** [comment]
Perhaps `raw` should have some `theme` dict option to override the default `THEME` used by `raw` (allowing a theme to be specified in Typst, even)? (Paging @laurmaedje)

**Comment by laurmaedje** [comment]
> Perhaps raw should have some theme dict option to override the default THEME used by raw (allowing a theme to be specified in Typst, even)? (Paging @laurmaedje)

Yes, I planned on having something like this. Not sure how it would be specified. The two options I see are a dictionary that statically specifies the theme or a function that gets a piece of text + its textmate scopes and is free to do whatever.

**Comment by LaurenzV** [comment]
This feature already exists now, right? Can this issue be closed?
