### ISSUE TITLE
SVG is wrongly cropped both horizontally and vertically when inserted via `image`

### ISSUE THREAD

**Issue by fuine** [typst/typst#3733]
### Description

This is a regression with respect to 0.10.0, consider the following code (black background is set so that the slight white shadow is visible below the logo):
```typst
#set page(paper: "a6", margin: 0pt, fill: black)
#image("./images/python-logo.svg", fit: "contain")
```
where we want to render [python logo](https://s3.dualstack.us-east-2.amazonaws.com/pythondotorg-assets/media/files/python-logo-only.svg). This results in the following document after compilation with 0.11: 
![test_11](https://github.com/typst/typst/assets/15677456/5a459800-029e-472f-be66-3e2299b2b4bb)

 The same document compiled with 0.10: 
![test_10](https://github.com/typst/typst/assets/15677456/46adccc2-4882-4222-b45d-78237f7ae0ab)

It looks like the logo is also cut if you use `#image("./images/python-logo.svg", width: 5%)` in which case we respectively get 
![test_11_width](https://github.com/typst/typst/assets/15677456/9985f79a-0a15-4cd2-9c25-ab53ac05e687)
![test_10_width](https://github.com/typst/typst/assets/15677456/b675b77e-271c-4fe4-bb69-be6028548219)

and I'm not sure if this is a single bug or are these two separate bugs (one regarding this weird cutting and the second one regarding `fit: "contain"` not working correctly).

 

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
Confirmed to be caused by https://github.com/typst/typst/commit/1d32145319211b6faed1f2ce4892347fde7a3f50.

**Comment by fuine** [comment]
I just checked and currently the DPI for svg images is set by `pub const DEFAULT_DPI: f64 = 72.0;` whereas previously it used a default value of `96` from `usvg`. After locally changing `DEFAULT_DPI` to `96` the code sort-of works in that the logo is no longer cut but it still doesn't cover the entire page with `fit: "contain"`. As far as I can tell this is perhaps another bug because SVG images should trivially scale and cover the entire area if DPI is not explicitly specified by the user

**Comment by laurmaedje** [comment]
We intentionally don't upscale images anymore. Although SVGs can scale, auto-scaling an SVG with a small pixel width to the full page doesn't make much sense. We switched the DPI from 96 to 72 as that's also the default for PNGs. Why that leads to cropping, I'm not sure.
