### ISSUE TITLE
More helpful error message on `text*//`

### ISSUE THREAD

**Issue by astrale-sharp** [typst/typst#3735]
### Description

No reason to fail there since we accept `text//`

### Typst version

- [X] I am using the latest version of Typst

**Comment by frozolotl** [comment]
I believe the reason for this is that disallowing it makes commenting something out will never fail.
So, for instance you have a document:
```typ
"Hello W*/rld," says Karl the robot.
```
You can't really comment it out easily:
```typ
/*"Hello W*/rld," says Karl the robot.*/
```

**Comment by astrale-sharp** [comment]
Oh great remark! If that's indeed the problem we could be a bit more explicit in the error message :thinking:

**Comment by laurmaedje** [comment]
@frozolotl is on point here with the reasoning. if the message is too vague, we can add a hint.

**Comment by astrale-sharp** [comment]
I was thinking of adding the word `ambiguous` in the error but `ambiguous end of comment` is a bit long and not that clear

**Comment by jmskov** [comment]
The error message I get is currently `error: unexpected end of block comment`, which I think is clear. More ideas are `unopened block comment closure/end` or `ambiguous block comment closure/end`.

**Comment by laurmaedje** [comment]
> @laurmaedje Is the hint different than the message printed in the console?

Could you clarify what you mean?

**Comment by jmskov** [comment]
I wasn't sure about the mechanics of hints, but I've learned hints are inserted into an error message. We could insert the hints `add \* to open the block comment` and/or `add space after * to avoid ambiguity` or similar.

**Comment by laurmaedje** [comment]
The first one sounds fine. Regarding the second, it might be a better suggestion to escape the `*` since otherwise there'll (a) be a space, (b) the lone asterisk will be interpreted as syntax for strongly emphasized text.

**Comment by jmskov** [comment]
After poking around, it looks like the error member of the `Lexer` structure does not supports adding hints , like `SyntaxError`. My initial idea is to use `SyntaxError` in the `Lexer` structure, but I am not sure if an easier solution exists (aside from putting the hints as newlines in the error message). I am still new to the whole architecture of this so I will think about it and learn more :)

**Comment by laurmaedje** [comment]
If switching the `Lexer` to `SyntaxError` doesn't cause any problems, it should be fine.
