### ISSUE TITLE
I have a great fondness for typst, but I'm curious about who possesses the ability to create a program similar to TexStudio.

### ISSUE THREAD

**Issue by linhduongtuan** [typst/typst#374]
I love Typst very much, but I'm wondering who has the capability to develop a software interface like TexStudio?
Linh

**Comment by linhduongtuan** [comment]
@Enivex Can you give me these names on VSCode?
Thank in advance. 
Linh

**Comment by laurmaedje** [comment]
And there's our official web app at https://typst.app.

**Comment by linhduongtuan** [comment]
@laurmaedje I know this app. But I really want to use typst on my local machine.

**Comment by Enivex** [comment]
See https://github.com/qjcg/awesome-typst
