### ISSUE TITLE
Compression of punctuation marks at line end is not work in `simple` linebreak mode

### ISSUE THREAD

**Issue by Jocs** [typst/typst#3743]
### Description

Acording to **Compression of punctuation marks at line start or line end** in [W3C:Requirements for Chinese Text Layout](https://www.w3.org/TR/clreq/#punctuation_width_adjustment)

> According to section 5.1.10 of the General Rules for Punctuation (GB/T 15834—2011), when a full-width punctuation character appears at the end of a line, it SHALL be trimmed to half-width.

But the punctuation at line end is not compressed when in `simple` linebreak mode.

<img width="1410" alt="截屏2024-03-21 11 48 17" src="https://github.com/typst/typst/assets/9712830/022335ff-da3d-4473-beb8-736768306c6b">

The last `。` need to be compressed in the first line.

### Reproduction URL

https://typst.app/project/rRsNaXqWFHfMXRYhTEiybG

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by peng1999** [comment]
This is essentially the same as issue #2348

**Comment by Enivex** [comment]
> This is essentially the same as issue #2348

Are you saying this one should be closed?

**Comment by peng1999** [comment]
> Are you saying this one should be closed?

#2348 and #3743 are not duplicate, because one is about line start, and the other is about line end. But both can be closed by #3744.
