### ISSUE TITLE
Invalid CLI command printed when initializing template where entrypoint contains spaces

### ISSUE THREAD

**Issue by laurmaedje** [typst/typst#3747]
### Description

The CLI command below should somehow escape the space in the filename `spacy entrypoint.typ`:
```
Successfully created new project from @preview/spacy:0.1.0 🎉
To start writing, run:
> cd spacy
> typst watch spacy entrypoint.typ
```

### Typst version

- [X] I am using the latest version of Typst

**Comment by qTipTip** [comment]
Can you not run:

```shell
> typst watch "spacy entrypoint.typ"
```

Without the quotes the file name is interpreted as two arguments, instead of one.

**Comment by frozolotl** [comment]
> Can you not run the following?
> 
> ```shell
> > typst watch "spacy entrypoint.typ"
> ```
> 
> Without the quotes the file name is interpreted as two arguments, instead of one.

I was confused about this as well, but what this issue is actually about, is what happens when you run `typst init`.
The raw block in the issue is actually the help output of one such initialization, where the package's entry point contains a space.

The idea is that the example command should be escaped. Using quotes or backslashes.

**Comment by qTipTip** [comment]
If we are fine with having the string quoted for single-word filenames as well, then it should be as simple as adding some quotes to the following line:

https://github.com/typst/typst/blob/41db766b83bad4c4671423c03c5e54f308032e7b/crates/typst-cli/src/init.rs#L111

```rust
writeln!(out, "typst watch \"{}\"", template.entrypoint)?;
```

**Comment by qTipTip** [comment]
Alternatively:

```rust
    let entrypoint: String = if template.entrypoint.contains(' ') {
        format!("\"{}\"", template.entrypoint)
    } else {
        template.entrypoint.to_string()
    };
    
    writeln!(out, "typst watch {}", entrypoint)?;
```

However, I'm not too familiar with this codebase, so let me know if this logic is better placed elsewhere than inline in the `init.rs`.
