### ISSUE TITLE
Feature request: ISO date specification

### ISSUE THREAD

**Issue by jiahao** [typst/typst#376]
Currently, the date of a document is specified as a string, e.g.:

```
#show: project.with(
  date: "March 27, 2023", ...
)
```

It would be great if the date were specified in an [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) compliant format like `2023-03-27` instead so it can be programmatically manipulated more easily and avoid future complications with date parsing, especially in a multilingual setting.

**Comment by user202729** [comment]
Duplicate of #303

**Comment by laurmaedje** [comment]
GitHub is weird, the button says "duplicate" but now it says not planned. This is planned.
