### ISSUE TITLE
Add Nix syntax highlighting

### ISSUE THREAD

**Issue by Septias** [typst/typst#3771]
### Description

I would love to get syntax highlighting for Nix as I currently write my bachelor's thesis about it so I can't get around it. I want to complete it by Wednesday when I submit it; the fastest way is to compile it locally, right? I made this [issue](https://github.com/trishume/syntect/issues/523) on `syntect` as that is the crate used internally for syntax highlighting

### Use Case

Used for everything nix-related.

**Comment by laurmaedje** [comment]
If you have a sublime syntax for it, you can load it at runtime: https://typst.app/docs/reference/text/raw/#parameters-syntaxes

**Comment by Septias** [comment]
Thanks for the fast answer. I followed those steps, and it was really easy, actually. It would be even better if it was not already supported, and I just made some syntax errors that broke styling... :laughing:

**Comment by PgBiel** [comment]
> I would love to get syntax highlighting for Nix as I currently write my bachelor's thesis about it so I can't get around it.

It appears that Nix syntax highlighting is already natively supported by Typst. Typing

\`\`\`nix
let x = 5; in x + 5
\`\`\`

highlights properly for me.
