### ISSUE TITLE
Re-export `comemo::Prehashed`?

### ISSUE THREAD

**Issue by KillTheMule** [typst/typst#3772]
### Description

Thanks for putting `typst` on crates.io, that's pretty helpfull.

One detail: `comemo::Prehashed` is part of the public API via the `World` trait. Wouldn't it make sense to re-export that from typst?

### Use Case

Users of the `typst` library will need to explicitely add `comemo` to their dependencies right now. Having both an explizit and an implicit dependency runs a bit of a risk of versions getting out of sync, or features not behaving properly. As such, it would feel more robust to re-export `comemo::Prehashed` from `typst`. I'd send a PR if this is an acceptable idea.

**Comment by PgBiel** [comment]
I'd go as far as saying that Typst should re-export any dependencies which appear in the public API. This is usually done through an inline module at the top of the crate, like `typst::ext`. You'd then have something like `typst::ext::comemo` and so on.

**Comment by KillTheMule** [comment]
That's probably true, although in my usage I have not seen any additional dependency in a public API. Wondering if there's a structured way to find them?

**Comment by Myriad-Dreamin** [comment]
It is replaced by `typst::util::LazyHash` in v0.11.0, so you should `typst::util::LazyHash`  whenever possible.

**Comment by KillTheMule** [comment]
That's a tad confusing. `0.11.0` is released, and it's using `comemo::Prehashed` in [`World`](https://docs.rs/typst/latest/typst/trait.World.html). I don't think there's a way to use something else for a user of the lib, is there? If that's a plan for `0.12` or so, then maybe this issue isn't necessary after all.

**Comment by Myriad-Dreamin** [comment]
okay, I was seeing this. But is is force pushed 😅.

```log
Parallel comemo & optimizations (https://github.com/typst/comemo/pull/5) - Force push
[laurmaedje](https://github.com/laurmaedje)force pushed to [main](https://github.com/typst/comemo/activity?ref=main) • 55a724f…ddb3773 • 18 days ago
Remove Prehashed
```

![image](https://github.com/typst/typst/assets/35292584/06fdcbcc-f169-41a8-af2a-1806126d89a2)

**Comment by laurmaedje** [comment]
I wanted to remove Prehashed, but then noticed that it was still used in various places and didn't want to change that for 0.11.

**Comment by KillTheMule** [comment]
Nice, so this issue is superflous I guess. Thanks all :)
