### ISSUE TITLE
Error on spaced arguments within 2D math array

### ISSUE THREAD

**Issue by frozolotl** [typst/typst#3774]
### Description

The following expression gives an error:
```typ
$mat(; ,)$
```
```
error: expected array, found content
  ┌─ ../../tmp/a.typ:1:6
  │
1 │ $mat(; ,)$
  │       ^
```

I'd expect it to work just like if there was no space.

It would be useful for this kind of thing:
```typ
$ mat(
    1, , ;
     ,1, ;
     , ,1;
  ) $
```

### Typst version

- [X] I am using the latest version of Typst

**Comment by wrzian** [comment]
A quick fix could be to try using empty strings? `$mat(""; "",)$`. Empty content, `#[]` shouod also work but is more characters to type.

**Comment by wrzian** [comment]
Tbh, it might be nice to allow math mode to default to having empty content for arguments (but not code mode).

**Comment by frozolotl** [comment]
> Tbh, it might be nice to allow math mode to default to having empty content for arguments (but not code mode).

I think you misunderstand; empty arguments are already allowed.
What is not allowed is a semicolon, followed by whitespace, followed by a comma. That's what this issue is about.
