### ISSUE TITLE
Including emojis with NotoColorEmoji makes PDFs huge

### ISSUE THREAD

**Issue by LaurenzV** [typst/typst#3777]
### Description

It is known that Typst currently does not have proper support for emojis in PDF output (see #144). However, in most cases, emoji fonts have outlines as well that will be used as a fallback when embedded in the PDF.

But this does not seem to be the case for the Noto Color Emoji font in the web app. It seems like it doesn't have a `glyf` table (and thus it doesn't have a `loca` table). Because of this, subsetting will fail and we embed the whole emoji font (which is multiple megabytes), even though in the PDF output it's not going to show up regardless.

Input:
```typ
#text(font: "Noto Color Emoji")[#emoji.face.inv]
```

Output:
[out.pdf](https://github.com/typst/typst/files/14733618/out.pdf)

While supporting emojis itself is in itself (tracked in #144), we should make sure that including an emoji "accidentally" at least doesn't result in such huge file sizes.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by elegaanz** [comment]
@LaurenzV can you please tell me if you can still reproduce the issue now that #3853 is merged? On my side, I can reproduce with some older Typst version, but not with `main`, so I would say it is fixed, but I would prefer to have your confirmation if possible.

**Comment by LaurenzV** [comment]
Yeah just tested it, works fine now, thanks!
