### ISSUE TITLE
Misleading documentation for the angle parameter of cancel

### ISSUE THREAD

**Issue by Enivex** [typst/typst#3785]
https://typst.app/docs/reference/math/cancel/

The current documentation says the following:
```
How much to rotate the cancel line.

    If auto, the line assumes the default angle; that is, along the diagonal line of the content box.
    If given an angle, the line is rotated by that angle clockwise w.r.t the y-axis.
    If given a function angle => angle, the line is rotated by the angle returned by that function. The function receives the default angle as its input.

Default: auto
```

It is not clear that second option results in an absolute rotation from a vertical line. It's also not specified _which_ diagonal is the default.

I would go with something like this:
```
Controls the angle between the line and the y-axis, measured clockwise.

The default angle is that corresponding to the rising diagonal of the content's bounding box.

If set to auto, the angle is the default.
If given a function, the function receives the default angle and must return a new angle.

Default: auto
```

**Comment by qTipTip** [comment]
I find that looking at the compiled examples, there is no ambiguity in how you are supposed to use this function.

I agree that maybe noting which of the two diagonals is the default could be seen as an improvement, but the "_absolute rotation from a vertical line_" is well documented in "_line is rotated by that angle clockwise w.r.t the y-axis_."

![image](https://github.com/typst/typst/assets/11932512/74245bec-4c8d-49b9-9a0b-d452658cb648)
![image](https://github.com/typst/typst/assets/11932512/f70a115f-3eba-41da-9b9a-4b670370cfd9)

**Comment by Enivex** [comment]
> I agree that maybe noting which of the two diagonals is the default could be seen as an improvement, but the "_absolute rotation from a vertical line_" is well documented in "_line is rotated by that angle clockwise w.r.t the y-axis_.", unless I am misreading your point here 😅

That's where the main ambiguity is, because in context with the previous line it sounds like the default line is rotated by that angle.

**Comment by qTipTip** [comment]
Aha, I see what you mean!
