### ISSUE TITLE
First line indent applies to code in `#raw`

### ISSUE THREAD

**Issue by ralphmb** [typst/typst#3794]
### Description

Typst version 0.11.0.
Minimal working example:

example.py:
```python
if __name__ == "__main__":
    print("Hello World")
```

main.typ:
```typst
#set par(first-line-indent: 20pt)
= Python 101
Here's an example of some Python code, in its own paragraph.\

#let code = read("example.py")
#raw(code, lang:"Python")
 
Here's the same code but not beginning a paragraph.\
#raw(code, lang:"Python")
You need to be careful copy and pasting the first block of code or it might not run.\
The inserted whitespace might be copied too.
```
This compiles to the following:

![Screenshot 2024-03-25 at 20 13 33](https://github.com/typst/typst/assets/18724395/436033eb-3d56-41ad-b0c4-ad03a1367588)

Obviously I set myself up a bit with the `#set par(...)` but this may be an issue for code blocks containing languages with significant whitespace.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Leedehai** [comment]
Like #3454 and #3848 , users rightfully expect the the raw blocks to not be affected by (almost all?) set/show rules on `text` and `par`.

**Comment by PgBiel** [comment]
The behavior here is correct, you're missing `block: true`, so the raw code is part of text (and is indented just like it).

Using triple backticks would also fix it.
