### ISSUE TITLE
Enhancing reproducibility of Typst documents with `SOURCE_DATE_EPOCH`

### ISSUE THREAD

**Issue by drupol** [typst/typst#3806]
### Description

Hello,

Building twice the same document with Typst is not reproducible:

```
❯ echo "HelloWorld" > test.typst
❯ typst compile test.typst test.pdf
❯ sha256sum test.pdf
a8fc409c1940e980516d4eccbb9941ce58563e9e0cdb80100de0ca8d53a98e7f  test.pdf
❯ typst compile test.typst test.pdf
❯ sha256sum test.pdf
57da6223f10f08615df5b2ac034529e8f524a5e0c1378cb1e947df68f1177d7d  test.pdf
```

However, when setting the document date to `none` as explained in the [doc](https://typst.app/docs/reference/model/document/), it is totally reproducible:

```
❯ echo "#set document(date: none); HelloWorld" > test.typst
❯ typst compile test.typst test.pdf
❯ sha256sum test.pdf
3c121f2fd52a42cf20a705c8d7d5e8a0a8415171e5965db1d07fa6134de9faf8  test.pdf
❯ typst compile test.typst test.pdf
❯ sha256sum test.pdf
3c121f2fd52a42cf20a705c8d7d5e8a0a8415171e5965db1d07fa6134de9faf8  test.pdf
```

This suggests that the variability in outputs is linked to the automatic insertion of the current date/time. To enhance reproducibility, I propose leveraging the `SOURCE_DATE_EPOCH` environment variable, as recommended by [ReproducibleBuilds.Org](https://reproducible-builds.org/docs/source-date-epoch/). This approach allows for a consistent build environment, particularly beneficial in isolated builds (e.g., Nix, Guix, Docker). Since Typst is, to some extent, a document compiler, I think this make sense.

### Use Case

The benefit of using this variable is that we will be able to control the date used within Typst.

For example, this hypothetical example should work if Typst would use such a variable: 

```
❯ export SOURCE_DATE_EPOCH=1640606727
❯ echo "HelloWorld" > test.typst
❯ typst compile test.typst test.pdf
❯ sha256sum test.pdf
cd44178830866edd7205fac3cf24329b9d4a8f9599ab3d8f0192a77325d56696  test.pdf
❯ typst compile test.typst test.pdf
❯ sha256sum test.pdf
cd44178830866edd7205fac3cf24329b9d4a8f9599ab3d8f0192a77325d56696  test.pdf
```

When building Typst document in isolation (Nix, Guix, eventually Docker), setting this env variable would be cool to make sure the documents produced by Typst are reproducible _by default_.

Using such an env var in Rust shouldn't be complex, I see on this page that it's possible to use it as such:

```rust
use chrono::{TimeZone, Utc};
use std::env;

let now = match env::var("SOURCE_DATE_EPOCH") {
    Ok(val) => { Utc.timestamp_opt(val.parse::<i64>().unwrap(), 0).unwrap() }
    Err(_) => Utc::now(),
};
```

I have absolutely no knowledge in Rust, but I'll be glad to give it a try and fix this issue if you're OK for having it.

**Comment by Enivex** [comment]
I'm a bit surprised by your example. I would've thought the checksum only changed once every 24 hours, since typst doesn't use anything more fine-grained than days on purpose.

**Comment by drupol** [comment]
Nope... here's a more visual comparison using [Diffoscope](https://diffoscope.org/):

![image](https://github.com/typst/typst/assets/252042/3cafaf66-82a2-46d2-b266-907fec74c0e1)

**Comment by Enivex** [comment]
> Nope... here's a more visual comparison using [Diffoscope](https://diffoscope.org/):
> 
> ![image](https://github.com/typst/typst/assets/252042/3cafaf66-82a2-46d2-b266-907fec74c0e1)
> 
Typst is probably writing the time to the creation date, in addition to the actual date.

**Comment by drupol** [comment]
In any case, this is something we should be able to control, just with `SOURCE_DATE_EPOCH`.

**Comment by drupol** [comment]
Thank you @frozolotl and @laurmaedje !!!
