### ISSUE TITLE
Bibliography style bug: gb-7714-2015-numeric

### ISSUE THREAD

**Issue by ysl2** [typst/typst#3819]
### Description

What I expected:

```
[1] Hatamizadeh A, Tang Y, Nath V, et al. Unetr: Transformers for 3d medical image segmentation[C]//Proceedings of the IEEE/CVF winter conference on applications of computer vision. 2022: 574-584.
```

What I actually got:

![2024-03-29_20-48](https://github.com/typst/typst/assets/39717545/88b78193-1e8e-412c-a9d3-76284a682793)

The difference is the author names were uppered (which is not I want), and the `等` instead of `et al.`

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
https://github.com/typst/citationberg/issues/5

**Comment by ysl2** [comment]
@Enter-tainer Thanks for your answer :-)

**Comment by csimide** [comment]
> 如果有办法解决的话，希望可以联系我

我自己在用一个临时方案：用 `citation-js` 把引文条目预处理成需要的样式，再到 Typst 中引用。我把相关的思路和代码放在 https://github.com/csimide/cslper 了。

I am currently using a temporary solution: I preprocess the citation entries into the required format using `citation-js`, and then cite them in Typst.
