### ISSUE TITLE
first line indent fails when the paragraph starts with strong or emph texts

### ISSUE THREAD

**Issue by rqy2002** [typst/typst#382]
E.g. in the following example:
```
#set par(first-line-indent: 2em)

#lorem(20)

#lorem(1) #lorem(20)

*#lorem(1)* #lorem(20)

_#lorem(1)_ #lorem(20)
```
The first pargraph has no indent since it's the first in the page.

The second paragraph indent by 2em. But the 3rd and 4th paragraph has no indent. I don't find the explaination in the docs, so I think it may be a bug.

**Comment by iceghost** [comment]
As of version 056d15aa, I used zero-width space as a workaround in the meantime.

```
#let zerowidth = "​";
#set par(first-line-indent: 2em)

#lorem(20)

#lorem(1) #lorem(20)

#{zerowidth}*#lorem(1)* #lorem(20)

#{zerowidth}_#lorem(1)_ #lorem(20)
```

**Comment by laurmaedje** [comment]
Fixed.
