### ISSUE TITLE
Setting block.spacing doesn't change block.above and block.below for math.equation

### ISSUE THREAD

**Issue by lvjr** [typst/typst#3829]
### Description

The first example produces correct result:

```typ
#show par: set block(above: 1em, below: 1em)
#show math.equation: set block(above: 2em, below: 2em)

Text Text Text Text Text Text Text Text Text Text Text Text Text Text
$ integral_a^b f(x) dif x $
Text Text Text Text Text Text Text Text Text Text Text Text Text Text
```
<img width="551" alt="image" src="https://github.com/typst/typst/assets/4239949/c8ebc38a-9c3a-4bcd-9ebc-5f4e357277b6">

But the second example produces wrong result:

```typ
#show par: set block(above: 1em, below: 1em)
#show math.equation: set block(spacing: 2em)

Text Text Text Text Text Text Text Text Text Text Text Text Text Text
$ integral_a^b f(x) dif x $
Text Text Text Text Text Text Text Text Text Text Text Text Text Text
```
<img width="526" alt="image" src="https://github.com/typst/typst/assets/4239949/50f34b8e-6873-42ee-ab80-0a195ab224ee">

The documentation says setting `block.spacing` is equivalent to setting `block.above` and `block.below` to the same value.

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
The docs are misleading here. `above` and `below` actually have higher priority. If you use `show par: set block(spacing: 1em)`, it should work. The idea was that if you specifically specify `below` for one thing, you might it to win against a more generic `spacing` specified somewhere else.

**Comment by lvjr** [comment]
It looks a little strange: `below`
is more specific than `spacing`, but `math.equation` is more specific than `par`. I hope the documentation would give a clear statement about this.

**Comment by laurmaedje** [comment]
`math.equation` and `par` are equal, only `below` is more specific than `spacing`.

**Comment by laurmaedje** [comment]
Setting `spacing` is now 100% equivalent to setting both `above` and `below`.
