### ISSUE TITLE
stacks comtaining `h(1fr)` causes elements to break out of columns container on windows, only via cli

### ISSUE THREAD

**Issue by dyc3** [typst/typst#3832]
### Description

This is a bit of a weird one.

The repro code:
```typ
#columns(2, [
  #stack(
    dir: ltr,
    h(1fr),
    [foo1],
    h(1fr),
    [foo2],
    h(1fr),
  )
  #colbreak()
  bar
])
```

This should produce output that keeps all text elements within their columns. However, on windows (running the `.exe` in windows natively and in WSL environments) produces output where the `foo`s break outside of the `columns`. Another weird thing is that when auto compiled via the Typst LSP VSCode extension (aka `nvarner.typst-lsp`) on windows, it produces the expected output. So this only happens when using the cli to build the doc.

### Reproduction URL

https://typst.app/project/r5vtZju9llmgjl5gp4tgq-

### Operating system

Web app, Windows, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Are you sure you're on the latest version (Typst 0.11)? By design, `stack` expects a bare `1fr` rather than `h(1fr)`, but since 0.11 both are allowed.

**Comment by dyc3** [comment]
Whoops. I just checked the version I was using on windows and it was 0.10, so this is not a bug. Sorry for the noise.
