### ISSUE TITLE
Page counter update after page set rule not working

### ISSUE THREAD

**Issue by nohenry** [typst/typst#3835]
### Description

I would think the following code modified from the docs would display each page number as 1:
```
#set page(numbering: "(i)")
= Preface
The preface is numbered with
roman numerals.

#set page(numbering: "1 / 1", number-align: top)
#context counter(page).update(1)

= Main text
Here, the counter is reset to one.
We also display both the current
page and total number of pages in
Arabic numbers.
```

But this is not the case. Instead this is displayed:

<img width="1091" alt="Screenshot 2024-03-31 at 10 30 30 AM" src="https://github.com/typst/typst/assets/50533236/22f6e27c-f0f2-4d00-a1c3-d8f74dceb79f">

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Similar to https://github.com/typst/typst/issues/2987. If you move the state update above the set rule, it works (though you need to update to 0 then). Also note that counter updates do not need context, only retrievals.

**Comment by laurmaedje** [comment]
Actually this is different from #2987. It's working as intended. The page counter is updated in the main content of the page, which is after the page's header, so the result is not reflected there.
