### ISSUE TITLE
Wrong PDF page labels when disabling numbering 

### ISSUE THREAD

**Issue by gabriel-araujjo** [typst/typst#3836]
### Description

When the page numbering is set to none after a different value, the previous value logic stick to the next one.

Example:

```typst
#set page(numbering: "1")
A

#pagebreak()

#set page(numbering: none)

B
```

The B page is labeled as "2", when should be empty.

### Reproduction URL

https://typst.app/project/rHQz12gQeHgUXr4yCYca4m

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Leedehai** [comment]
Hi, I didn't see a "2" in the cloud doc link above.. and I was not able to repro it locally:
<img width="388" src="https://github.com/typst/typst/assets/18319900/576cdfef-32f6-4da7-a47c-1160b13fc929">
Any advice?

**Comment by gabriel-araujjo** [comment]
The problem is not in rendered numbers in pages, but in Page Labels, only for PDF exports. The labels appears PDF reader interface.

![image](https://github.com/typst/typst/assets/3980936/9b3d8e2e-b763-447f-bc70-c8b1b62f6e19)

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/3837
