### ISSUE TITLE
Tab chars are not rendered in raw blocks with `lang: "typ(c)"`

### ISSUE THREAD

**Issue by Jollywatt** [typst/typst#3841]
### Description

The following produces expected output in typst ≤ v0.10.0, but in v0.11.0 the tabs have zero width.

````typ
#raw("#if true {\n\tpanic()\t// comment after tab\n}", lang: "typ")

#raw("if true {\n\tpanic()\t// comment after tab\n}", lang: "typc")

```typ
#if true {
	panic()	// comment after tab
}
```

```typc
if true {
	panic()	// comment after tab
}
```
````

### Reproduction URL

https://typst.app/project/rVuopYH97zJ73uD6w6s6cM

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Leedehai** [comment]
`git bisect` said commit 030041466b5b8453ca23e43a6385f4592f78a56c is the first bad commit: "Provide more fine-grained spans in raw blocks (#3257)".
