### ISSUE TITLE
CLI Ability to Compile a HEREDOC

### ISSUE THREAD

**Issue by agatho-daemon** [typst/typst#3843]
### Description

The ability to compile a HEREDOC or a variable of type string in other programming languages bindings would be nice.

Short streams of data or templates stored in a variable could be passed to `typst` to compile into a nice PDF or SVG.

This instead of using files which involve lots of temporary items laying around and piling up over time.

### Use Case

In the field I am interested in, this feature could be used to printout all types of **business documents** from ERP web frameworks, Where HTML screen presentation of data differs from printouts.

Currently, I am using typst to carry out the printing of vouchers and draft work orders. Almost all ERP solutions rely on a very buggy and counterintuitive solution being wkhtmltopdf. Wkhtmltopdf is rendering the HTML page presented on screen, which most of the times doesn't make a presentable printout.

**Comment by laurmaedje** [comment]
Can't this be achieved via stdin?

**Comment by agatho-daemon** [comment]
> Can't this be achieved via stdin?

How?

**Comment by alerque** [comment]
HEREDOC's are a shell construct, and `typst` already supports input on STDIN which is where the data shows up. This is already supported:

```console
$ typst compile - foo.pdf <<< "My string"
```

Of course other constructs work too:

```console
# Read from pipe
$ echo My string | typst compile - foo.pdf

# Pipe with heredoc
$ cat <<- EOF | typst compile - foo.pdf
My string
EOF
```

**Comment by alerque** [comment]
> in other programming languages bindings

It's possible you have scrambled up the question. If you want bindings from "other" programming languages (other that what? other than Rust?) then that's kind of a different question than HEREDOC's (which exist in various flavors in various languages, shells being covered by my previous comment. If you have something specific in mind please ask something more specific.

**Comment by agatho-daemon** [comment]
> > in other programming languages bindings
> 
> It's possible you have scrambled up the question. If you want bindings from "other" programming languages (other that what? other than Rust?) then that's kind of a different question than HEREDOC's (which exist in various flavors in various languages, shells being covered by my previous comment. If you have something specific in mind please ask something more specific.

You are right. Coming from a beginner in programming and unix user yes. It is hard to express what I have in mind.

I tried the solutions you've presented above. They work in the most simple code only, i.e.:
= Introduction
Test solution

But when I deal with all types of formatting it doesn't compile the intended output.

It does compile however in python with the variable passed to the shell command between single quotes.

Thanks. Request can be closed.

**Comment by alerque** [comment]
The necessary escape sequences for each language and input combination is up to the host language and shell, not `typst`.

**Comment by agatho-daemon** [comment]
> The necessary escape sequences for each language and input combination is up to the host language and shell, not `typst`.

I would never argue that it is up to typst. If inline capability was not present I would have asked for it. But since it is present then this is the feature requested. My apologies if I have stated that or gave an impression of it.

Thanks again for the snippets you suggested above. It did help in python using subprocess module, I can pass on the whole file with all the formattings intended.

**Comment by agatho-daemon** [comment]
> The necessary escape sequences for each language and input combination is up to the host language and shell, not `typst`.

I would never argue that it is up to typst. If inline capability was not present I would have asked for it. But since it is present then this is the feature requested. My apologies if I have stated that or gave an impression of it.

Thanks again for the snippets you suggested above. It did help in python using subprocess module, I can pass on the whole file with all the formattings intended.
