### ISSUE TITLE
Not all functions are pure

### ISSUE THREAD

**Issue by ndtodoroff** [typst/typst#385]
From the [documentation](https://typst.app/docs/reference/types/function/):

> In Typst, all functions are pure. This means that for the same arguments, they always return the same result. They cannot "remember" things to produce another value when they are called a second time.

However `push` is not pure because `a.push(x)` updates the array `a` in place. This is also not explicitly documented beyond the fact that `push` doesn't have a documented return value and `pop` only returns the popped value. This bit me because the above quote made me assume that `a.push(x)` returns a *new* array, when actually it returns `none`.

I want to note that I *do* consider e.g. `s.update(f)` to be pure where `s = state("s")`; this makes sense to me because I conceptualize `s.update(f)` as returning an *instruction* like `update the the state labeled "s" using the function/value f` that gets embedded in the document, and this instruction/message is a pure function of `s` and `f`.

**Comment by laurmaedje** [comment]
Only methods can be impure. I'll add a note to the docs.
