### ISSUE TITLE
Inconsistency with floating point operations

### ISSUE THREAD

**Issue by Mc-Zen** [typst/typst#3858]
### Description

Some floating point operations don't yield the same result on different platforms. For example, the calculation

```typ
#calc.pow(10.0, 45)
```

yields 
- `1e45` on Windows,
- `1.0000000000000001e45` with wasm (Webapp),
- and also `1.0000000000000001e45` on Linux with x86_64 architecture. 

The result is independant of
- the output format (as can be checked by raising an `#assert.eq()` error).
- and has nothing to with the console outputting (as can be checked by writing the value as content into the output). 

### Operating system

Web app, Windows, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Mc-Zen** [comment]
It can't be an issue with single precision floats being used in some architecture because `1e45` already exceeds the capacity of IEEE 754 32 bit floats.

**Comment by Enter-tainer** [comment]
The next f64 number after `1e45` is `1.0000000000000001e45`. This is acceptable error. It might be result from different math function implementation on different platform.

**Comment by Mc-Zen** [comment]
It seems indeed acceptable. For other cases I tested, the results also differ by no more than 1 ULP. 

I was a little worried because of reproducibility but as it is likely not a bug it should be okay.

**Comment by Enivex** [comment]
I don't think there's an easy way around this. Small differences in floating point behavior can result from the compiler making slightly different choices. This is not uniquely a Typst issue.

**Comment by laurmaedje** [comment]
After some recent research about floating-point reproducibility, I've come to the conclusion that there's very little we can do about this, so I'll close this.
