### ISSUE TITLE
matrix empty cell handled wrongly

### ISSUE THREAD

**Issue by NeoFantom** [typst/typst#3862]
### Description

I want to write:

```
$ E_k = mat(
  dots.down, , ;
  , 1, ;
  , , dots.down;
) $
```
-
Apparently I want only diagonal terms. But this will generate an error at the end of semicolon of 1st and 2nd lines:
`Expected array, found content`

If I write instead 
```
  dots.down, , ;
  x, 1, ;
  x, , dots.down;
```

How to solve this? Seems a compiler bug.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
might be duplicate of https://github.com/typst/typst/issues/3774

**Comment by NeoFantom** [comment]
Duplicate of #3774. 
#3786 tries to fix.

**Comment by NeoFantom** [comment]
Duplicate of #3774 .
#3786 tries to fix.
