### ISSUE TITLE
String literals with triple quotes to avoid escaping double quotes and newlines

### ISSUE THREAD

**Issue by pachi** [typst/typst#3865]
### Description

As there's the option to use single o 3+ backticks to define raw blocks and this can be useful to avoid some escapes, it would be also very nice to allow 1 or 3+ double quotes to define string literals (single quotes could be nice too, but it's less flexible) to avoid a lot of escaping.

### Use Case

This is specially useful for cases that need simple interpolation facilities, like generating inline svg content, which is so easy to insert in a Typst document, but really inconvenient for the need to escape " and newlines.

There's the alternative to use oxifmt, but having to resort to a package for a such simple need is a bit weird.

```
let ypos = 15
let value = 10
let lit = "A"

let fragment = (
`<text x="145" y="`.text 
    + str(ypos + 10) 
    + ``" id="letra" className="calif_key">`.text 
    + str(value) + lit 
    + `</text>`.text)
```
would become:

`let fragment = """<text x="145" y="""" + str(ypos + 10) + """ " id="letra" className="calif_key">""" +  + str(value) + lit + "</text>"`

**Comment by laurmaedje** [comment]
I think the two options of escaping the quotes or using raw + `.text` covers most use cases well enough, such that the motivation for more syntax seems somewhat thin to me.

**Comment by laurmaedje** [comment]
I'll close this then. Especially since raw blocks have quite intricate rules around trimming whitespace so that all char sequences are expressible (e.g. the spaces in ```` ``` `hello` ``` ````) and I wouldn't want to replicate those for strings as well, since it feels more unexpected for strings to do such trimming.
