### ISSUE TITLE
Use of dif and partial as functions for derivative expressions

### ISSUE THREAD

**Issue by RaulDurand** [typst/typst#3867]
### Description

I would like to request the addition of function versions for dif and partial to write complete derivative expressions in a concise and efficient manner.

Currently, users often need to manually construct derivative expressions using, for example,  (dif^2 y) / (dif x^2), which can be time-consuming and prone to errors, especially when dealing with multiple derivatives or partial derivatives. By introducing the dif(x,y, ...) and partial(x,y, ...) functions, Typst can streamline the process of writing derivative expressions and provide users with a more intuitive and convenient way as well as greater readability.

### Use Case

For example `partial(z,x)` , `partial(z,x,x)` and `partial(z,x,y)` will render as follows:

![image](https://github.com/typst/typst/assets/8837321/515f6e63-dbd1-4352-8be2-2dc6cfa7d266)

I elaborated a simple function for partial derivatives below. However, it will be very helpful if this is part of Typst since derivatives are largely used in mathematical expressions.

```
#let partialderiv(..args) = {
  let z = args.pos().at(0)
  let x = args.pos().at(1)

  if args.pos().len() == 2 {
    $(partial#z) / (partial#x) $
  }
  else if args.pos().len() == 3 {
    let y = args.pos().at(2)
    if x==y {
      $(partial^2 #z) / (partial#x^2)$
    }
    else{
      $(partial^2 #z) / (partial#x partial#y)$
    }
  }
}
```

An optional named argument could be used  (e.g. order=5) so users can render a high order derivative, for example  `dif(y,x, order:5)`.

**Comment by PgBiel** [comment]
I've been using the `physica` package for this, check it out: https://typst.app/universe/package/physica

There are quite a bit of notations and conventions to consider and maintain, so delegating it to packages might be the most sane approach.

**Comment by Enivex** [comment]
This has come up before, with the consensus being that there's too much variation in notation for this to be something built in.

**Comment by RaulDurand** [comment]
Indeed the guys from physica found a good syntax to deal with this issue. I am glad  to witness the rapid development of Typst and its associated packages.
