### ISSUE TITLE
unicode characters in math mode

### ISSUE THREAD

**Issue by matthiasGmayer** [typst/typst#3886]
Unicode characters in math mode behave differently than their word counterpart.
E.g.  `$mu$` and `$µ$`
![image](https://github.com/typst/typst/assets/28257008/a866aba3-2d16-4406-af16-e1f0129a91f4)

**Comment by Enivex** [comment]
The unicode character you're using is not the greek letter μ (U+03BC), but the micro sign µ U+B5 (micro sign).
