### ISSUE TITLE
Awkward spacing between Roman letters and some CJK punctuations

### ISSUE THREAD

**Issue by oissevalt** [typst/typst#3888]
### Description

When Roman letters precede certain full-width punctuation marks (often referred to as CJK punctuation marks), the spacing between them are not visually appealling.

<img width="600" alt="image" src="https://github.com/typst/typst/assets/57583509/93c20580-dad5-4af5-81ad-2edc4764ec6a">

In the example above, note the space between "Dane", the full-width comma, and the text afterwards.

Not all CJK punctuations cause this problem. For example, full stop (。) and listing comma (、) are free from the issue.

<img width="600" alt="image" src="https://github.com/typst/typst/assets/57583509/351629ac-922f-4eab-8ecc-53a1fed5610c">

It's worth noting this seems not to be introduced by the CJK spacing update (0.9.0), but dates back as far as in 0.6.0.

---

The code I use to produce the situation (the choice font affects the exact spacing, but do not directly contribute to the bug):

```typst
#set par(justify: true)
#set text(font: ("Inter", "Noto Sans SC"))

盎格鲁-撒克逊记载的Dane，实际上并不只是来自丹麦地区的日耳曼人，也包括北欧的维京人。
```

### Operating system

Web app, Windows, Linux, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
I'm not sure whether this spacing is coming from Typst or just from the position of the glyph in the font.

cc: @peng1999

**Comment by peng1999** [comment]
> When Roman letters precede certain full-width punctuation marks (often referred to as CJK punctuation marks), the spacing between them are not visually appealling.
> <img alt="image" width="600" src="https://private-user-images.githubusercontent.com/57583509/320190226-93c20580-dad5-4af5-81ad-2edc4764ec6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MDQ3ODksIm5iZiI6MTcxMjQwNDQ4OSwicGF0aCI6Ii81NzU4MzUwOS8zMjAxOTAyMjYtOTNjMjA1ODAtZGFkNS00YWY1LTgxYWQtMmVkYzQ3NjRlYzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDExNTQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNzlkOTljMmRhZDMwMzJjMzBmMzQwMjg3YjRmMDU3ZGI0ZDAxZjkyOWZmNDIwOTAxMDZmOTA5MzdiNTFjODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QxQV8wGAp6bykczyDj7x1lcXrNctO1T2wGypr-mGvZ4">

The first comma and the second is not in the same font. The awkward spacing is because of not using a proper Chinese font. My guess is that Typst has bug in font selection.

But your example is not reproducible in https://typst.app. Please provide reproduce link for further investigation.

**Comment by oissevalt** [comment]
> But your example is not reproducible in https://typst.app. Please provide reproduce link for further investigation.

[The link](https://typst.app/project/wEnHGkJUY-W0-GT_-zEJoB).

Also a screenshot of what it looks like on my computer, in case it's a browser or system issue:

<img width="1391" alt="image" src="https://github.com/typst/typst/assets/57583509/02436b92-4720-4c14-a139-7f97b39caeb8">

**Comment by peng1999** [comment]
@oissevalt There is no "Noto Sans SC" in the typst.app. If you use "Noto Sans CJK SC", everything works fine.

**Comment by oissevalt** [comment]
> @oissevalt There is no "Noto Sans SC" in the typst.app. If you use "Noto Sans CJK SC", everything works fine.

Oops, I see the problem. Thanks for pointing out!

I assume typst.app resorts to browser default when no fallback font is available, and that causes the problem?

**Comment by laurmaedje** [comment]
Typst.app doesn't use any browser fonts. Everything should be the same on everybody's machine.

**Comment by oissevalt** [comment]
I see. I shall close this issue if there is nothing else to be investigated, then?

**Comment by laurmaedje** [comment]
Yes, I think it can be closed. 

The silent fallback is not great, but there is some work in providing warnings when such things happens: #3854.

**Comment by peng1999** [comment]
@laurmaedje This issue highlights the significance of font fallback warnings. Allowing typesetting software to randomly select a font without informing the user can lead to significant confusion.

Related: #3352

**Comment by Myriad-Dreamin** [comment]
Btw, I was surprised by typst uses 19 fonts when I configure only 4 fonts for my document. The problem become serious as increasing the scale of the document.

**Comment by laurmaedje** [comment]
@Myriad-Dreamin 19 font families or 19 font faces?

**Comment by Myriad-Dreamin** [comment]
@laurmaedje 19 faces? They are exact `typst::Font`. I configured 4 family names of them for text and raw, and I didn't configure the math fonts. So it is expected to use 6 different families. But `Ebrima`、`KaiTi`、`FangSong`、`Tiems New Roman`、`Segoe UI Emoji` are used unintentionally.

```
Family: Linux Libertine
Family: Linux Libertine
Family: Linux Libertine
Family: Linux Libertine
Family: Source Han Serif SC
Family: Source Han Serif SC
Family: DejaVu Sans Mono
Family: DejaVu Sans Mono
Family: DejaVu Sans Mono
Family: Microsoft YaHei
Family: Microsoft YaHei

Family: New Computer Modern Math
Family: New Computer Modern
Family: New Computer Modern

Family: Ebrima
Family: KaiTi
Family: FangSong
Family: Times New Roman
Family: Segoe UI Emoji
```

**Comment by laurmaedje** [comment]
okay, so it's not really 4 vs 19 since 4 is the number of families and 19 of individual fonts (also called font faces). so some families are counted twice in the 19. but I get your point.
