### ISSUE TITLE
References Mixed Up with the IEEE Template

### ISSUE THREAD

**Issue by TWB0109** [typst/typst#389]
I'm currently writing a paper with Typst, using the provided IEEE template, the only modification is the font size of the title. 

My document has 15 references right now, everything works properly, until I get to the 10th reference, as soon as I cite it, the references get mixed up like this:

![image](https://user-images.githubusercontent.com/53587182/228110458-1451996e-ce18-4546-9756-31dceed47e3b.png)

However, when I take the files to the app, and compile it, it just works, so my guess is that the latest release command line compiler has a bug.

I can upload the file, but would rather not do it if I'm making a dumb mistake.

Any ideas on what could be causing this?

Version: b934a2fd

**Comment by laurmaedje** [comment]
This is fixed on main, but I haven't made a release yet.
