### ISSUE TITLE
vim syntax

### ISSUE THREAD

**Issue by 3052** [typst/typst#3905]
I found this:

https://github.com/kaarmu/typst.vim

but its not just syntax, you have to use plugin too

**Comment by 3052** [comment]
currently I am using this, but its missing code blocks:

~~~vim
syntax match typ_func /#\?\w\+(\@=/
highlight typ_func guifg=#4b69c6 gui=bold

syntax region typ_heading start=/^= / end=/$/
highlight typ_heading guifg=#19181f gui=bold

syntax match typ_num /\d\+%\?/
highlight typ_num guifg=#b60157

syntax region typ_str start=/"/ end=/"/
highlight typ_str guifg=#298e0d
~~~

**Comment by Enivex** [comment]
I'm not super familiar with vim, but is this not what you're looking for?

https://github.com/kaarmu/typst.vim/blob/main/syntax%2Ftypst.vim

Regardless, I'm closing this issue. It's not clear what you're actually looking for, but this does not seem like the correct repo.

**Comment by Andrew15-5** [comment]
Can you please describe what is the issue you're having exactly? That plugin has several, features including syntax highlighting for `*.typ` files.

There is also:
https://github.com/uben0/tree-sitter-typst
https://github.com/nvim-treesitter/nvim-treesitter

This repository is for Typst compiler issues/features.
