### ISSUE TITLE
error: input file not found (searched at file.typ)

### ISSUE THREAD

**Issue by m-kru** [typst/typst#3906]
### Description

```
typst 0.11.0 (2bf9f95d)
```
Installed via snap.

I have a super simple typst file:
```
- One
  - Two
    - Three
```

When I try to compile using `typst compile file.typ` I get the following error:
```
error: input file not found (searched at file.typ)
```
which is a little bit unclear to me, as the file exists in the folder where I call typst.

### Operating system

Linux

### Typst version

- [ ] I am using the latest version of Typst

**Comment by noamzaks** [comment]
Hey, I wasn't able to reproduce this issue. Can you run `ls` before `typst compile file.typ`? That should include a file named `file.typ`.

**Comment by m-kru** [comment]
I still do not know what is causing the issue. However, I have found out the problem exists only when the `.typ` file is placed in a path inside the `/tmp` directory, for example `/tmp/foo.typ` o `/tmp/bar/foo.typ`. I can compile when the `.typ` file is located in any other directory.

**Comment by reknih** [comment]
This is expected. The Snap is running in full confinement (as opposed to Snaps you need to install with `--classic`). This means that by default, it can only read your home directory. You can add the capability to read from removable media in `dev` by running `snap connect typst:removable-media`. You cannot, however, add the capability to read any other directories, see https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1643706. Publishing new Snaps in classic confinement that have this ability is strongly discouraged.

**Comment by admercs** [comment]
I get this error on Windows. It is super annoying!

**Comment by reknih** [comment]
@admercs This issue only tracks issues with reading files when Typst was installed through its [Snap](https://snapcraft.io/typst). I have changed the title to clarify this. To report an issue about file reading on Windows, please open a new issue.
