### ISSUE TITLE
Breakable block skips region due to placed floating element

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#3907]
### Description

```
#set page(columns: 2, width: 40em, height: 40em)

#lorem(50)

#figure(placement: auto, caption: "test", v(10em))
#figure(placement: auto, caption: "test", v(10em))

+ #lorem(30)
+ #lorem(20)
+ #lorem(20)
+ #lorem(10)
```

Take a look at https://discord.com/channels/1054443721975922748/1056574658771681361/1227424678969348117. The first page is broken because it forgets that there's space leftover and instead spills to the second page.

### Typst version

- [ ] I am using the latest version of Typst

**Comment by PgBiel** [comment]
I've reproduced this with a `placement: auto` figure before a long list containing a figure or any vertically long content. The `placement: auto` figure introduces the page and oddly forces the list to go to the next page, as if the list were unbreakable.

**Comment by laurmaedje** [comment]
Most likely, the list is layouted without knowledge of the second figure and then it's second frame is too big to fit, so it's moved to the next region.

**Comment by laurmaedje** [comment]
Minimized:
```typ
#set page(width: 120pt, height: 120pt, margin: 10pt)

#block(width: 100%, height: 50pt, fill: aqua)
#figure(
  placement: top,
  rect()
)

#list(.."ABCDEFGHIJ".clusters())
```
