### ISSUE TITLE
2 consecutive `*` or `_` should probably raise an error?

### ISSUE THREAD

**Issue by user202729** [typst/typst#391]
Coming from Markdown (variant), I was a bit surprised to see that `**bold**` gives the same as `bold`, i.e. nothing changed.

After thinking about it for a while I realize that `**` is `*<nothing>*`, so there's an empty text being bolded.

Nevertheless I think `**...**` is a common notation, so it may be better to explicitly give an error on it instead of silently ignore.

**Comment by laurmaedje** [comment]
Does it give the same result for you? It should not be bold anymore because the two sets of stars are two empty bold parts.

**Comment by user202729** [comment]
I mean, yes it gives two empty bold parts (thus nothing is bold). But it makes more sense to raise an error because that's almost-never what the user want.

**Comment by user202729** [comment]
It's good practice to give a warning/error when what is written is likely not what the user want, rather than silently do something that the user does not want.

Unless in very special circumstances (e.g. automated document generation), `**` is not useful and the user could as well delete both the stars.

Even in the case of automated document generation, if the programmer want to allow empty text inside it is possible to simply use `#strong([...])`.
