### ISSUE TITLE
Font contextuals alternates not applied with OTF fonts

### ISSUE THREAD

**Issue by oleastre** [typst/typst#3924]
### Description

I'm trying to reproduce some LaTeX documents using Typst.
I would like to use a font called Prida01 (SIL font that can be found here: https://www.glukfonts.pl/font.php?font=Prida01).
That font has 5 different stylistic sets and uses calt tables to define alternate characters depending on the context.

Here is some typst code I used to test the font:
```
#page(numbering: none)[
    #text(
        font: "Prida01",
        weight: "regular",
        size: 16pt,
        features: (init:1, ss01: 1, calt: 1),
        ligatures: true,
        historical-ligatures: true,
        discretionary-ligatures: true,
    )[Hello World]
]
```
And the result 
![image](https://github.com/typst/typst/assets/838332/4b0da6db-8816-4d60-b8c2-157c4a40d8c8)

Here is an equivalent LaTeX code:
```
\documentclass[12pt]{article}
\usepackage{fontspec}

\newfontfamily\Prida{Prida01}[
  Extension=.otf,
  BoldFont=*Bold,
  Contextuals={WordInitial}
]

\begin{document}
\Prida Hello World
\end{document}
```

Compiled with LuaLaTeX, this is the result I get:
![image](https://github.com/typst/typst/assets/838332/6a06aafe-014b-49d0-b90c-46844f3581c7)

As you can see, the initial characters of each word uses an alternate style.

I tried various set and combinations of Typst font parameters: `stylistic-set`, various `features`, `alternates`, `ligatures`, ...  Whatever I set, there is no variation in the character styles. It's like the base font is always used.

I'm running on Fedora 39, and tried with various versions of Typst: pre-build 0.11 binary, compiled from git branch 0.11 and main branch at commit #[72dd792](https://github.com/typst/typst/commit/72dd79210602ecc799726fc096b078afbb47f299)

Are `calt` features supported, and if yes, is there a bug on my side ? I know a bit of rust, so, if needed, I can help testing, adding logs or whatever.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
![image](https://github.com/typst/typst/assets/2191754/1d6d5e5e-119f-4a1e-806c-9ab244c74f63)
It works with the ttf version of the font, but not the otf

**Comment by oleastre** [comment]
Using the `init` feature was what I expected, however, I did not expect to have a difference between OTF and TTF.
I'll switch to the ttf version as a work around, but is the format difference expected ?

**Comment by Enivex** [comment]
> but is the format difference expected ?

No, that would be a bug.

**Comment by oleastre** [comment]
Just tested locally with the TTF version and it works.
So indeed there is a problem with the OTF version.

**Comment by LaurenzV** [comment]
Probably a font issue. I get the same result with `harfbuzz`:
`hb-view Prida01_otf.otf --features init "Hello World"`
<img width="883" alt="image" src="https://github.com/typst/typst/assets/47084093/8734ef9a-c993-475a-9014-535388026f89">

`Prida01_ttf.ttf --features init "Hello World"`
<img width="948" alt="image" src="https://github.com/typst/typst/assets/47084093/aa8d41b1-1ac5-4d38-aade-cc98763b4e0f">

**Comment by LaurenzV** [comment]
... but if I subset the otf font then it suddenly starts working... I'll try to report it and see what happens.

**Comment by LaurenzV** [comment]
See https://github.com/harfbuzz/harfbuzz/discussions/4681#discussioncomment-9245592

It's a font bug, so not much we can do here.
