### ISSUE TITLE
Easier processing of none and default assignments

### ISSUE THREAD

**Issue by scholzdev** [typst/typst#3937]
### Description

# Easier processing of `none` and default assignments
* Proposal: [TE-3937]
* Author: Florian Scholz
* Review Manager:
* Status: To be reviewed
* Implementation:

## Introduction
Introduce easier processing of default values when unpacking a `none` variable.

## Motivation
Writing clean code is extremely important. It makes templates and everything else much less confusing. Especially long, nested and repetitive if conditions are error prone and unhealthy when it comes to simply checking if a value is `none`. 

The only valid approach for now is using if conditions:

```typst
#let c = none
#let col = if c == none { blue } else { c }

#let c = red
#let col = if c == none { blue } else { c }
```

## Proposed Solution
If we could use `or` to check for whether a variable is `none` we could easily assign the default value provided.
This approach is very short and noticeably easier to read/write.

```typst
#let c = none
#let col = c or blue // col would be blue
#let c = red
#let col = c or blue  // col would be red
```

## Source compatibility
This change is purely additive and does not break source compatibility of any valid existing typst code.

## Alternatives considered
Another approach would be the introduction of a new keyword: `??` which would be used to "unwrap" the optional and provide a default value. This is essentially the same solution as above just with a separate keyword for it.

```typst
#let c = none
#let col = c ?? blue // col would be blue
#let c = red
#let col = c ?? blue  // col would be red
```

### Use Case
Assign default values to `none` variables without specifying if conditions for every variable to improve readability

**Comment by laurmaedje** [comment]
The problem with reusing `or` for this is that it's a footgun in combination with booleans. Consider, e.g., a parameter `val: none | bool` and you want to set its default value to `true`. Then you'd write `val or true`, but suddenly `false` is not working anymore!

**Comment by bluebear94** [comment]
See #1394 and #1503 for prior discussion.

**Comment by laurmaedje** [comment]
I can see that we might want to add something for the use case at some point, but for the reasons gives above, I'm not convinced by this specific proposal.

**Comment by vaporoxx** [comment]
In case anyone else stumbles across this:

We can make use of the property that `none` can be joined with any value, yielding the other value. If the type you are working with has a default and you want to replace `none` with that default, you can actually use `+` instead of `or`.

For instance, if `val` might be `none`, one can write `val + 0` for numbers, `val + ""` for strings, `val + ()` for lists or `val + (:)` for dictionaries. This obviously does not cover all cases but it could help at least sometimes.
