### ISSUE TITLE
Should the default footer be `auto` and not `none`?

### ISSUE THREAD

**Issue by Enivex** [typst/typst#3938]
Currently the `footer` parameter of the [page](https://typst.app/docs/reference/layout/page/) function has `none` as its default value. This corresponds to having a centered page number in the event that numbering is set.

An unfortunate consequence of this is that if the user does `set page(footer: none)` expecting to hide the page number, then nothing happens. Instead they will have to use `set page(footer: [])`. In my opinion, it would make much more sense to use `auto` for this purpose, which would also be more consistent with other Typst behavior.

**Comment by laurmaedje** [comment]
Makes sense. I think the `footer` actually predates the page numbering feature.

**Comment by bluebear94** [comment]
Should `none` still be supported as a value, in this case to suppress the page number?

**Comment by Enivex** [comment]
> Should `none` still be supported as a value, in this case to suppress the page number?
> 
> **Edit:** This also applies to the header if `number-align` is set to `top`.

I don't see why it shouldn't

**Comment by Enivex** [comment]
Resolved by https://github.com/typst/typst/pull/4051
