### ISSUE TITLE
Saving Date Metadata with Time-Zone instead of Auto-Converting to UTC

### ISSUE THREAD

**Issue by zR-JB** [typst/typst#3948]
### Description

Typst appears to be converting date metadata to UTC ("Zulu", "Z", UTC+00:00) Time.

Example of this Metadata:
`<</Creator(Typst 0.11.0)/CreationDate(D:20240417105515Z)/ModDate(D:20240417105515Z)>>`

While this is the correct time, the information in which time zone the PDF was originally created gets lost. 

Preferably, it would be saved as:
`<</Creator(Typst 0.11.0)/CreationDate(D:20240417125515+02'00')/ModDate(D:20240417125515+02'00')>>`

Now we know that the PDF was created in UTC+2 Time Zone. 

### Use Case

When converting to UTC time, we lose important information, when we are then trying to figure out when a PDF was created, we need to know where we were and also account for daylight saving times etc.... 

Saving the Time Zone would make the metadata much clearer, because then it would be unmistakably when the PDF was created. As someone that is often in different time zones, it is currently very annoying to find the local time I created a document.

Concern:
An unknowing user could give away location information through his timezone. But if someone is concerned about these points, everybody is free to disable the automatic creation and modification date in Typst.

Welcomed side effect:

Some PDF Viewers seem to handle metadata different from others, converting to local time zone, or just stripping the time zone info away no matter what. When having the time zone info, we are later able to validate what some viewers show and also know in which time zones the PDF was created, offering more valuable metadata than without.

Microsoft Edge is bad at displaying the correct time info, because it just strips away any time zone info. Let's assume the reader and creator are both in UTC+2.
So, when something was created in UTC+2 with Typst and then saved in "zulu" time, Edge will display a time 2hrs earlier. But when it is saved with the time zone info. The time in Edge will be the correct one, because Edge just stripped away the time zone info. This of course will break when reader and viewer are in different time zones.

**Comment by Leedehai** [comment]
Sounds like a useful feature imo.

> An unknowing user could give away location information through his timezone. But if someone is concerned about these points, everybody is free to disable the automatic creation and modification date in Typst.

I wonder if it's a good idea to make such timestamp creation an opt-in feature instead of an opt-out, so that no timestamp is created by default unless the user explicitly tells Typst to do so. This is privacy-by-default, and helps with reproducibility.

**Comment by zR-JB** [comment]
I think defaulting to `none` with the timestamp creation would not hurt too many. The file system timestamp will be enough in most cases.

**Comment by laurmaedje** [comment]
I don't think it's really a particularly big privacy concern. It's good practice to include this metadata in PDF files and all other comparable software also writes it. Deviating from that would need a stronger reason in my opinion.

**Comment by zR-JB** [comment]
quick edit:

Edge now displays the time-zone info correctly. But I think this feature is still relevant, although many programs do not handle the timestamp metadata correctly.
