### ISSUE TITLE
1/.5 is compiled with "." as the denominator

### ISSUE THREAD

**Issue by Genius3435** [typst/typst#3949]
### Description

To reproduce:
```
$1 / .5 = 2$
```
<img width="85" alt="Screen Shot 2024-04-17 at 09 04 11" src="https://github.com/typst/typst/assets/62397740/ec3457ac-2a11-40ff-ab0a-6d5a6c34d9a4">

The ideal behavior would be to look the same as `$1 / (.5) = 2$`.

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Based on the number of upvotes on the latest comment, I'll close this.
