### ISSUE TITLE
Hyperlinks with `-` or `_` don't parse correctly

### ISSUE THREAD

**Issue by Julian-Wollersberger** [typst/typst#395]
When writing a hyperlink with the dedicated syntax, they get cut off on the first `-` or `_` character. Example:

````
https://rsyslog.readthedocs.io/en/latest/tutorials/tls_cert_summary.html
````
results in a link to
````
https://rsyslog.readthedocs.io/en/latest/tutorials/tls
````

Using `#link("https://rsyslog.readthedocs.io/en/latest/tutorials/tls_cert_summary.html")` works as expected, thankfully.

I'm using version `typst 056d15aa`, compiled from source and cloned today.

**Comment by laurmaedje** [comment]
See also #379.

**Comment by frozolotl** [comment]
As #379 was merged, I think this issue can be closed now @laurmaedje
