### ISSUE TITLE
placed content should not interfere with paragraphs at its definition location

### ISSUE THREAD

**Issue by Beiri22** [typst/typst#3951]
### Description

When putting a `#place()` within a paragraph, the paragraph is split. When you ask me, there should be no effect on the paragraph, as place renders the content elsewhere.

Why do I mind:
Floating figures might use place internally. Defining a figure within a paragraph (to get best matching auto location to the first refernce of the figure) has the same effect. 

### Reproduction URL

https://typst.app/project/roIA5LK0SWAaWATiITTvOt

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
See https://github.com/typst/typst/issues/3159

**Comment by Beiri22** [comment]
But this makes it impossible to use (good working) auto placement for a figure when the reference is in a larger paragraph. Is there any other way to achieve this?
