### ISSUE TITLE
Clarify `grid.column-gutter` docs

### ISSUE THREAD

**Issue by tingerrr** [typst/typst#3959]
### Description

The documentation for grid states that the default value for `grid.column-gutter` is `()`, yet when setting it explicitly, it changes the behavior of grid.

```typst
#grid(
  columns: 2,
  gutter: 1em,
  box(stroke: red)[A],
  box(stroke: red)[B],
)

#grid(
  columns: 2,
  gutter: 1em,
  column-gutter: (),
  box(stroke: red)[A],
  box(stroke: red)[B],
)
```

My understanding is that, passing the default value myself should not change how the gird behaves.

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
The `gutter` variable overrides the `column-gutter`. Basically `gutter: X` is equivalent to passing `column-gutter: X, row-gutter: X`. So a desugared version of your example is
```typ
#grid(
  columns: 2,
  column-gutter: 1em,
  row-gutter: 1em,
  box(stroke: red)[A],
  box(stroke: red)[B],
)

#grid(
  columns: 2,
  column-gutter: (),
  row-gutter: 1em,
  box(stroke: red)[A],
  box(stroke: red)[B],
)
```
And if you now remove `column-gutter: ()` in the second example, nothing happens, as expected.

**Comment by tingerrr** [comment]
The docs ought to be clear about that then. When providing wrapper functions that don't use argument sinks, this is surprising.

**Comment by laurmaedje** [comment]
> The docs ought to be clear about that then. 

How do you think we should word it? Right now it says "Takes precedence over gutter." for column-gutter.

> When providing wrapper functions that don't use argument sinks, this is surprising.

Can you provide an example?

**Comment by tingerrr** [comment]
> How do you think we should word it? Right now it says "Takes precedence over gutter." for column-gutter.

I think it should be noted on `gutter` and `{column,row}-gutter` that `gutter` is a shorthand passing the specific ones both, such that `auto` is not a fallback to `gutter`, maybe. At least that's what I initially assumed.

> Can you provide an example?

Simplified, because this is a for a library, it is important for both tidy and argument validation to not use a sink here:
```typst
#let subfigure-grid(
  // figure arguments with defaults
  // ...

  // grid arguments with defaults
  // ...

  // figures
  // ...
) = {
  // arg validation with explicit arguments
  // passing all arguments straight through with their default values
}
```

**Comment by laurmaedje** [comment]
We can reword the docs. I'll reopen to track this.
