### ISSUE TITLE
Deriving IntoValue

### ISSUE THREAD

**Issue by KillTheMule** [typst/typst#3965]
### Description

There's the `Cast` proc macro, which in particular derives `IntoValue` for an enum. I'd very much would like to derive `IntoValue` for my structs. As such, I'd wish for a derive macro for this to exist.

Would you be open to that addition? I've not yet written a proc macro, but I can probably learn it and make a PR.

### Use Case

Passing arguments into the render engine via `sys.inputs` is really good, but needs a `Dict`, which in particular contains `Value`s, so there's need to transform data structures into `Value`.

**Comment by PgBiel** [comment]
In principle, `cast!` should work for any types, not just enums. Are you having any specific problem with it?

**Comment by KillTheMule** [comment]
As far as I understand it, I have to type out the individual fields anyways, which kind of defeats the purpose. Mainly, you can simply forget a field and the whole thing compiles anyways. A derive macro would take care of that.

**Comment by PgBiel** [comment]
Ah, I assume you want to specifically cast your type to/from a **dictionary** (not any value), as if you were using `serde`?

We currently don't have a macro for that because `cast!` is very general; there are types which cast to/from integers, floats, arrays, and so on. Additionally, even for types which use dictionaries, it isn't always possible to cleanly translate the expected dictionary to a Rust struct, as it might have varying structures or fields.

With that said, `Dict` implements `serde::Serialize` and `serde::Deserialize`, so you should be able to use `serde` to (de)serialize your struct as a `Dict`, and then wrap the resulting `Dict` in `Value::Dict`.

**Comment by KillTheMule** [comment]
Yes, I was mainly concerned with turning a struct into a (`Dict`) `Value`, neither the other way around nor anything else. But I might have missed that going through `serde` is a possibility here, I'll have a look at that, thanks!

**Comment by laurmaedje** [comment]
I think serde should indeed work. I'll close this for now, but feel free to reopen if serde doesn't turn out to be a good option!

**Comment by KillTheMule** [comment]
First a little disclaimer: My immediate needs have been taken care of, so there's no need for action on my behalf ;)

That said, I looked into `serde`, and it can actually be done quite easily when using an intermediate format, like so:

```rust
let d: Daten = ... // elided;
let s = serde_json::to_string(&d).unwrap();
let dic: Dict = serde_json::from_str(&s).unwrap();
```

where of course one would need to `#[derive(Serialize)] struct Daten {...}`.

That's pretty bad from a performance point of view though, since we need to create the intermediate JSON string without using it really. It is be possible to avoid the intermediate format (see https://stackoverflow.com/questions/57477967/how-can-i-use-serde-to-serialize-a-struct-to-another-rust-data-structure/57488708#57488708), but that leaves the downside of having to copy out struct fields, where `IntoValue` is made to take ownership. As the link mentions, one could maybe do that with some custom work.

That somewhat brings us back to square 1 (or maybe worse, since a custom `(De)Serializer` is probably harder to do than a custom `IntoValue` implementation).

Tell you what, though. If I can make some time, I'll just make a crate providing such a proc macro, and if it is deemed useful by more people, you might subsume this into `typst`. Or not, once it's working, it won't be going anywhere of course :)

**Comment by KillTheMule** [comment]
I've just pushed https://github.com/KillTheMule/derive_typst_intoval to github. If anyone would try it and/or comment on it, I'd be grateful :)

**Comment by KillTheMule** [comment]
Published: https://programming.dev/post/13926215, https://crates.io/crates/derive_typst_intoval

**Comment by wasabiChris** [comment]
This has saved me so much trouble!

**Comment by myst3k** [comment]
This has saved me so much trouble!
