### ISSUE TITLE
Add release binaries to crates.io

### ISSUE THREAD

**Issue by boredsquirrel** [typst/typst#3966]
### Description

`cargo install typst` does not work, because it tells me "there are no binaries".

I can only use `cargo add typst` which is not nice. Correct me if I am wrong.

### Use Case

For Rust, in general it is recommended to have the toolchain etc all as the user. So packaging for distros is nice but not the recommended way and not needed. Using rustup and cargo you can manage all binaries from the user dir without ever touching the system.

This has stability benefits, and makes cross-platform support easier.

Currently you release binaries, but at least cargo seems to not find them.

**Comment by PgBiel** [comment]
The `typst` crate is indeed a library, you cannot install it. You meant to install [`typst-cli`](https://lib.rs/crates/typst-cli) instead.
