### ISSUE TITLE
Figure references not considered link but sub figure references are

### ISSUE THREAD

**Issue by dylanrussellmd** [typst/typst#3968]
### Description

This is in a `.qmd` document being rendered to PDF by `typst`.

    ```{=typst} 
    #show link: set text(blue)
    #show link: underline
    ```
    ::: {#fig-pictures layout-nrow=2}
    ![Picture 1](bird.jpeg){#fig-pic1 width="100%"}
    
    ![Picture 2](bird2.jpg){#fig-pic2 width="100%"}
    :::
    
    @fig-pictures is not considered a link, but @fig-pic1 and @fig-pic2 are.

[repro.pdf](https://github.com/typst/typst/files/15050598/repro.pdf)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
This sounds like a Quarto issue, not a typst one.
