### ISSUE TITLE
Feature request: custom errors and/or logs

### ISSUE THREAD

**Issue by rqy2002** [typst/typst#397]
I want to write a function as a library. I want it to report an error and stop the compiler in some case.
I don't find the way to do this - except write some dumb things to get an error, which is ugly and produce unrelated messages.
Also I want to put some log to the console for debugging. Is this possible?

**Comment by laurmaedje** [comment]
The `panic` and `assert` functions do that. Logging without stoping is not possible at the moment.

**Comment by rqy2002** [comment]
thanks. seems i should read the docs more carefully, sorry

**Comment by laurmaedje** [comment]
No problem!
