### ISSUE TITLE
Allow letter to be bold in word using the markdown(-ish) syntax

### ISSUE THREAD

**Issue by lettuceDestroyer** [typst/typst#3979]
### Description

I would like it, if it would be possible to make a single letters in a word bold or italic using the markdown syntax.

What I currently do is something like this:
```typst
#text(weight: "bold", "F")irst #text(weight: "bold", "l")etter #text(weight: "bold", "i")s #text(weight: "bold", "b")old.
```

Output:
**F**irst **l**etter **i**s **b**old

What I'd like is something like this:
```typst
*F*irst *l*etter *i*s *b*old
```

Alternatively we could add a method called `bold` which takes a string as argument. This would not be as easy to read as the markdown syntax but still easier than the `text` function. Maybe it would also fit better with Typst function like approach of styling.

An example could be something like this:
 ```typst
#bold(F)irst #bold(l)etter #bold(i)s #bold(b)old
```
This would also require an `italic` function or alternatively the italic markdown syntax.

### Use Case

This would make it easier to switch from Markdown to Typst. An other advantage is, that the source is easier to read.

**Comment by Enivex** [comment]
See https://github.com/typst/typst/issues/2241#issuecomment-1735142146
