### ISSUE TITLE
Table headers that repeat on every page

### ISSUE THREAD

**Issue by saward** [typst/typst#400]
Hi!  Is there a way to have a header for a table that is repeated on every page, when that table extends over multiple pages?  Or is it perhaps possible to achieve a similar result with a grid?

**Comment by ondohotola** [comment]
I was about to ask the same thing, especially when populating a table from CSV so one doesn't necessarily know the number of rows beforehand.

ie some simplified form of longtable/supertabluar

**Comment by laurmaedje** [comment]
Not at the moment, but I agree that it would be useful.

**Comment by victor-sm** [comment]
Maybe an _after-pagebreak_ property could be implemented. That way also custom blocks could implement this behavior when needed.

**Comment by saward** [comment]
@laurmaedje out of curiosity, do you have a sense of whether this would be a big project for someone unfamiliar with the inner workings of typst?  Interested in what it might take for me to add if I ended up needing it.

**Comment by laurmaedje** [comment]
My initial sense was that it would be pretty complicated, but on second thought it might actually be not that bad. Would have to be implemented in `library/src/layout/grid.rs`. The complexity also depends on whether the header can interrupt a cell that breaks over multiple pages or whether that is unsupported.

**Comment by ondohotola** [comment]
Great.

Gruss aus dem Süden

**Comment by capvor** [comment]
Here I show the effect of a complex repeating header and table title.
It is hoped that such a situation will be considered when implementing.

In this effect, there are the following characteristics:

- Table title repeat with different text (such as adding "(continued)" text)
- Table header is not only one row, It is contain merge cells.


![image](https://user-images.githubusercontent.com/16610170/228865504-ba6f3fdb-03cb-4e81-ba4b-9e1121e2c9cb.png)

**Comment by ramkumarkb** [comment]
> My initial sense was that it would be pretty complicated, but on second thought it might actually be not that bad. Would have to be implemented in `library/src/layout/grid.rs`. The complexity also depends on whether the header can interrupt a cell that breaks over multiple pages or whether that is unsupported.

@laurmaedje  - I want to give this a shot and hopefully give you a PR! I have started to read the `grid.rs` (and thank you for adding copious comments) and trying to shape my mental model of the changes needed (to implement a simple heading rows repeat) - 

- Most of the changes would need to be in the `impl GridLayouter` 
- Probably a new function - `layout_header`

Need to dig in more to understand what is `vt` & the relationship between `region` and `page` - if this is a 1st region of the page, then layout the header first, subract the available height and then layout the rows (or something akin to this). Of course there will be many corner cases... 

Do feedback if am on the right track. Thank you!

**Comment by laurmaedje** [comment]
> - Most of the changes would need to be in the impl GridLayouter
> - Probably a new function - layout_header

Yes, such a function would probably make sense.

`vt` basically holds all the necessary context for layouting. A `region` describes the surrounding container. It has the size of the inner page (without margins) typically, but can be smaller if the table is in a `block` or something else. In that sense one region = one page and each region should have one header.

Another important question is the user-facing interface. Any proposals for that?

**Comment by tingerrr** [comment]
I think being able to tell if a general purpose container like `block`, `grid` and friends was broken across pages would be useful in general, see #735.

Something that was asked for on the community discord was to repeat a background in a block when it breaks across pages. The naive solution to place the background and fill the block with content falls apart once the block is broken across pages. It does not behave like the background parameter on page does.

There was some initial work on #1773, and I wonder if @T0mstone has worked on a new implementation that is perhaps general enough to be used for this too.

**Comment by laurmaedje** [comment]
@tingerrr They did come up with a more general thing, but I wasn't comfortable with merging it: https://github.com/typst/typst/pull/2014. I'm shying away from making somewhat ad-hoc additions to the layout engine here and there, as I would rather do a more generalized rework that keeps everything consistent.
