### ISSUE TITLE
Show rule and spacing between CJK punctuations

### ISSUE THREAD

**Issue by minamotorin** [typst/typst#4009]
### Description

Thanks for the great work!

If I use show rule for CJK text, CJK typesetting go wrong.

In the code below, I think the first line and the second line of the output should be the same except for the color, but the actual result is not.

```typst
#[日」]#[「日]

#show regex(".+"): set text(fill: blue)

#[日」]#[「日]

```

![show](https://github.com/typst/typst/assets/76122224/c34d8ee8-c300-47fb-aba4-636300ec91e5)

Thanks.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
i think it's a known bug. Also, IMHO, in terms of language design, regex show rule is a very bad idea.

**Comment by minamotorin** [comment]
@Enter-tainer 
> i think it's a known bug.

I searched for known issues but I couldn't find. Could you tell me the issue number?

> regex show rule is a very bad idea.

In composition of CJK and western mixed texts, sometimes I want to use different fonts and font sizes for CJK texts and western texts. I use regex show rule for this purpose.
But I agree that this is not a good idea. If there are another method, I'll use it.

**Comment by Enter-tainer** [comment]
> I searched for known issues but I couldn't find. Could you tell me the issue number?

i havent find it either. it is the current limitation of text regex show rules.

> In composition of CJK and western mixed texts, sometimes I want to use different fonts and font sizes for CJK texts and western texts. I use regex show rule for this purpose.
But I agree that this is not a good idea. If there are another method, I'll use it.

https://github.com/typst/typst/issues/3331

**Comment by minamotorin** [comment]
> https://github.com/typst/typst/issues/3331

This is what I wanted to. Thanks so much!
Limitation of regex show rule is also commented there.

**Comment by laurmaedje** [comment]
> Also, IMHO, in terms of language design, regex show rule is a very bad idea.

@Enter-tainer on some days I agree with this take, on others I see yet another thing that would not have been possible without regex show rules (e.g. today: some special highlighting of a specific word in a raw block).
