### ISSUE TITLE
Align equation number vertically to the formula baseline - `number-align` in `math.equation`

### ISSUE THREAD

**Issue by asmarcz** [typst/typst#4014]
### Description

When a single-line math formula is presented, I would like to have the equation number aligned with the correct baseline. Now, if you include for example a sum, the height of the block is adjusted and the equation number is aligned with respect to the total height. This is not the case in LaTex, for example. Compare the first (LaTex) and second (Typst) snippets along with a rendered images.

```
\begin{equation}
    c_{t+1}(v) = c_{t}(v) - deg(v) \cdot  \mathbb{1}(c_{t}(v) - deg(v)) + \sum_{u \in N(v)} \mathbb{1}(c_{t}(u) - deg(u)) \quad \forall v \in V
\end{equation}
```
![image](https://github.com/typst/typst/assets/18113532/535282be-ffdd-4bc9-befa-380cf35961b6)

```
#set math.equation(numbering: "(1)", number-align: end + horizon)

$ c_(t+1)(v) = c_(t)(v) - deg(v) dot.c bb(1)(c_(t)(v) - deg(v)) + sum_(u in.small N(v)) bb(1)(c_(t)(u) - deg(u)) wide forall v in V $
```
![image](https://github.com/typst/typst/assets/18113532/6bedfa6f-b476-4fd3-90f6-1eebfb876479)

### Use Case

----

**Comment by Leedehai** [comment]
I think this issue shall be categorized as a bug and let me fix it.
