### ISSUE TITLE
Allow IETF language tags (at least in bibliography)

### ISSUE THREAD

**Issue by arcstur** [typst/typst#4015]
### Description

Allow the `lang` field of `text` to accept IETF language tags, or add a IETF language tag acceptable `lang` field on `bibliography`, to interact better with CSL styles.

### Use Case

I was defining the language code in the `text` function so that bibliography works correctly with a CSL file. I'm using [this CSL file](https://github.com/citation-style-language/styles/blob/master/associacao-brasileira-de-normas-tecnicas-ufrgs.csl). It uses a locale with `xml:lang="pt-BR"`, which is brazilian portuguese. It's very common to use this code for the brazilian variant of the portuguese language. However, Typst doesn't allow me to set `lang: "pt-BR"` in `text` (it expects 2 to 3 letters).

We can see [here](https://github.com/citation-style-language/locales/) in the CSL locales that it's common that the `xml:lang` has more than three characters for language variants, using what seems is defined as a [IETF Language Tag](https://en.wikipedia.org/wiki/IETF_language_tag), not defined in ISO 639.

My solution was to download the CSL file and substitute occurrences of "pt-BR" inside it to "pt". It's not very elegant. I did it because the pt variant in Typst was using "Acedido em" for _Accessed at_ in the bibliography, but that sounds very weird to a brazilian reader. We use "Acesso em".

I think having language tags should be possible, specially in the bibliography since it interacts with CSL which uses language tags.

**Comment by bluebear94** [comment]
You have to set the language and region separately:

```typst
#set text(lang: "pt", region: "BR")
```
