### ISSUE TITLE
Typst "expected string or content found dictionary"

### ISSUE THREAD

**Issue by blackjyn** [typst/typst#4025]
So, I want to convert only the first letter using REGEX and then bypassing function to uppercase it. However Typst return "expected string or content found dictionary"

This is the source:
```
#let text="oh this is it"
#text.replace(regex("^\w"), m=>upper(m))
```

why the `m=>upper(m)`  becomes dictionary?   If you have insight on custom function as a callback in Typst I would be happy as I really struggle to find good documentation on it.

**Comment by Leedehai** [comment]
Hi - it is the `upper()` function that expects a `string` or `content`. `m` (a match) is a `dictionary`, hence the error.

**Comment by blackjyn** [comment]
Thank you so much @Leedehai !

this is the code fix, including the Dictionary structure of the `m`-matched capture using the `repr`

```typst
#let text="oh this is it"
#text.replace(regex("^\w"), m=>upper(m.text))

//if we want to see the dict structure:
#text.replace(regex("^\w"), m=>{
repr(m)
upper(m.text)
})
```
the `repr` will return :  `(start: 0, end: 1, text: "o", captures: ())`. So we can access the `.text` key from the captured regex.

Well, things like this  must be on the the docs.

Thank you again @Leedehai
