### ISSUE TITLE
Feature Request: Extensible internationalization support

### ISSUE THREAD

**Issue by ararunaufc** [typst/typst#403]
From what I've gathered so far, i18n (internationalization) support is currently limited and baked into the code.

It would be nice to have an API for scripts to access the i18n "backend" to query for translations, formatting, pluralization, and also be able to insert new information into it without the need for a new compiler version to be shipped to include them.

That would enable, for instance, the creation of a library like TeX's `babel` that centralizes this info and users could turn to for the most common cases and still be able to address their own specific needs.

**Comment by owiecc** [comment]
Please see #216

**Comment by ararunaufc** [comment]
> Please see #216

Yes, fluent would definitely be great to be the backend of i18n!

(And maybe I should take a more thorough look on this repo before posting more suggestions 😅 . That's the second time today...)

Should I close this issue in favor of it?

**Comment by alerque** [comment]
Yes, please do close duplicate issues. I just scatters the discussion for everybody to have more than one with the same scope.
