### ISSUE TITLE
Add LaTeX \big commands for larger parentheses and other symbols

### ISSUE THREAD

**Issue by quantum9Innovation** [typst/typst#4048]
### Description

LaTeX has $( \big( \Big( \bigg( \Bigg($ (`( \big( \Big( \bigg( \Bigg(`) for manual sizing of parentheses, brackets, pipes, and other characters that are typically used to enclose mathematical expressions. This is important to ensure that the mathematical expressions are fully enclosed by these symbols.

While Typst has dynamic sizing of most symbols, this doesn't always work, especially with the pipe character. For example, consider the following LaTeX snippet:

$$ \frac{1}{2}x^2 \Big|_{x=0}^{x=n} $$

```tex
\frac{1}{2}x^2 \Big|_{x=0}^{x=n}
```

As far as I know, there is no way to recreate this in Typst without using the `#scale` function.

### Use Case

This feature would allow users to manually size enclosing symbols and fix issues where the Typst compiler can't figure out what the optimal size of these symbols should be.

**Comment by quantum9Innovation** [comment]
I just noticed the `#scale` function will make the symbol larger, but doesn't change the positioning of subscripts or superscripts accordingly, so it is not a viable workaround

**Comment by Enter-tainer** [comment]
> As far as I know, there is no way to recreate this in Typst without using the #scale function.

This is a way.
```typ
$ lr(1/2x^2|)^(x=n)_(x=0) $
```

<img width="245" alt="image" src="https://github.com/typst/typst/assets/25521218/c5612992-2007-4324-8049-825df16829aa">

**Comment by Enter-tainer** [comment]
But i agree that maunally setting the size of delimiter can be useful. 

Currently it can only be done using `lr(..., size: %)`. Like

```typ
$ ((a+b)times (a-b)) $

$ lr(((a+b)times (a-b)), size: #150%) $
```
<img width="285" alt="image" src="https://github.com/typst/typst/assets/25521218/38426f85-303d-4f8c-b6f2-a8d88f226cb9">

But it's not clear how LaTeX's \big, \Big ... maps to the size parameter. The API is also a little bit cubersome. I think it would be useful if you can make a package that defines `big`, `Big`... functions to scale the delimiters.

**Comment by quantum9Innovation** [comment]
Thanks for the suggestion! I'll create a package to do this when I have time. Adding `big`, `Big`, etc. as functions should ease the transition to Typst for LaTeX users.

**Comment by Enivex** [comment]
This can indeed be done with the size parameter of `lr`

**Comment by Enter-tainer** [comment]
> But it's not clear how LaTeX's \big, \Big ... maps to the size parameter

page 24/99 of https://ftp.jaist.ac.jp/pub/CTAN/macros/latex/required/amsmath/amsmath.pdf

I don't really understand the macro definition though..

<img width="574" alt="image" src="https://github.com/typst/typst/assets/25521218/e409dcdc-5b75-4d9f-a772-97ee8c3f1fbf">
<img width="628" alt="image" src="https://github.com/typst/typst/assets/25521218/62d2bfc5-9653-422c-aca0-6a0ec2e369a9">

**Comment by Enter-tainer** [comment]
defs in plain tex
```tex
\def\big#1{{\hbox{$\left#1\vbox to8.5\p@{}\right.\n@space$}}}
\def\Big#1{{\hbox{$\left#1\vbox to11.5\p@{}\right.\n@space$}}}
\def\bigg#1{{\hbox{$\left#1\vbox to14.5\p@{}\right.\n@space$}}}
\def\Bigg#1{{\hbox{$\left#1\vbox to17.5\p@{}\right.\n@space$}}}

```

**Comment by quantum9Innovation** [comment]
> But it's not clear how LaTeX's \big, \Big ... maps to the size parameter. The API is also a little bit cubersome. I think it would be useful if you can make a package that defines `big`, `Big`... functions to scale the delimiters.

Implemented using the `scale` parameter of `lr` in https://github.com/typst/packages/pull/752
