### ISSUE TITLE
Add a way to compose functions

### ISSUE THREAD

**Issue by owiecc** [typst/typst#406]
Currently the functions need to be nested inside each other. 
```
#box(image(
  "logo.svg",
  height: 0.7em,
))
```
For simple functions, with just one argument some form of function composition would be nice: 
```
#box∘image(
  "logo.svg",
  height: 0.7em,
)
```
I used Julia `∘` syntax as an example but maybe `|` or `|>` will be more applicable.

**Comment by owiecc** [comment]
[Related discussion](https://discord.com/channels/1054443721975922748/1072475366624596058) on discord.

**Comment by tingerrr** [comment]
You can technically already do that without much boilerplate:
```typst
#let args(..sink) = sink

#let compose(..funcs, args: none) = {
  if args != none {
    let f = compose(..funcs)
    f(..args)
  } else {
    let (last, ..rest) = funcs.pos().rev()
    rest.fold(last, (acc, it) => {
      (..sink) => it(acc(..sink))
    })
  }
}

#let boxed-figure = compose(box.with(stroke: red, inset: 0.5em), figure)

Hello #boxed-figure(caption: [Caption], [Body]) World

#compose(block.with(stroke: green, inset: 1em, width: 100%), lorem, args: args(10))
```

![image](https://github.com/typst/typst/assets/137803093/2edb0b1b-5700-4da9-9ab2-cae1ff4855e6)

You can easily compose this by using `with` and lambdas. I know that an operator is probably prettier, but for now this already reduces some nesting. Something I think should be provided is a constructor for `arguments`, which I emulate with `args` here. This could also be a builtin function on `fucntion`, which would allow calling it as a method too.

**Comment by laurmaedje** [comment]
Similarly to https://github.com/typst/typst/pull/531, I think a composition operator doesn't carry its weight in terms of syntax.

**Comment by matj1** [comment]
> Similarly to [#531](https://github.com/typst/typst/pull/531), I think a composition operator doesn't carry its weight in terms of syntax.

I suggest that functions would have something like the method `then` for composition. That does not require any new syntax.

So, if I had `names` an array of file names of images like in the original example, I could do this:
```typst
#names.map(image.with(height: 0.7em).then(box))
```
