### ISSUE TITLE
Quotes point the wrong way in text-within-math

### ISSUE THREAD

**Issue by cscherrer** [typst/typst#4063]
### Description

When text is rendered within math mode, double quotes seem to always render as `quote.l.double` instead of enclosing the content in the usual way. Below is an example screenshot from `typst.app`. This is not app-specific, I see the same result locally.

![image](https://github.com/typst/typst/assets/1184449/a751de9e-79df-44aa-bfbc-74086c75bfc0)

Code to reproduce:
````typst
```typst
$#["quotes"]$
```

renders as

$#["quotes"]$

but should render as

$quote.l.double"quotes"quote.r.double$

Correct version can be produced with 
```typst
$quote.l.double"quotes"quote.r.double$
```
````

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
This is yet another result of https://github.com/typst/typst/issues/366

When typesetting text in math, you should explicitly switch to the text font.

**Comment by cscherrer** [comment]
Thanks @Enivex , but I don't see how this is at all related to fonts. A double quote on its own is ambiguous, and correct rendering depends on the context to determine which way the quotes should "point". As I understand, `#[...]` *does* explicitly switch to text font.

Just to be clear, OP is just a minimal example, the real use case is something like the quotes in this:
![image](https://github.com/typst/typst/assets/1184449/147dec37-42cc-4ea6-990f-7cf18bfb2bf3)

The only way I could get these quotes correct was to use `quote.l.double` and `quote.r.double`, which is extremely clunky.

**Comment by Enivex** [comment]
> . As I understand, `#[...]` *does* explicitly switch to text font.

No, this is incorrect. As long as you're inside an equation the math font is used.

**Comment by cscherrer** [comment]
Thanks for the suggestion! That gets pretty close, but I'd like to keep the same font. If I do `#context text.font` it says `new computer modern`. Then if I do
```typst
#let mtext = text.with(font: "new computer modern")

$
1 + 1 &= 2 quad (#mtext["Profound" equation]) \
1 + 1 &= 2 quad (#text["Profound" equation]) 
$
```

I get

![image](https://github.com/typst/typst/assets/1184449/d1c82dd1-db24-46b2-8c04-65cbe9244496)

The first looks pretty good. I guess the last step is, instead of querying the font and then typing it in, how can I automate this? I tried
```typst
#let mtext = text.with(font: text.font)
```

but that gives an error.

**Comment by Enivex** [comment]
> The first looks pretty good. I guess the last step is, instead of querying the font and then typing it in, how can I automate this? I tried
> ```typst
> #let mtext = text.with(font: text.font)
> ```
> 
> but that gives an error.

Unfortunately this is not possible, even adding the context keyword, because the font in the context where function would be used would be the math font. You have to hard code it.

**Comment by cscherrer** [comment]
That very surprising that you can't just cast an observation from some context into a fixed variable, but I'll take your word for it. Thanks for the help :)

**Comment by laurmaedje** [comment]
There might be a misunderstanding. You _can_ store an observation from a context into a fixed variable. But in this case, there is no good place to put the context (at least not automatically) because the font is already configured in the context passed to the equation show rule.

**Comment by cscherrer** [comment]
Ok, if I put `#context text.font` in body of my paper, it renders as "new computer modern". How would I instead put that in a fixed variable, say `myfont`? Then I could follow it with

```typst
#let mtext = text.with(font: myfont)
```

Then I think calling `mtext` from inside math mode would solve it. I don't need the context placed automatically.

**Comment by laurmaedje** [comment]
Ah, no, it doesn't work directly like that, I might have bee the that misunderstood. Everything depending on the context _does_ need to be within the context. But if you have multiple nested contexts, then you can still save the observation from one and access it in the other:
```typ
#context {
  let fill = text.fill
  set text(fill: blue)
  context {
    let fill2 = text.fill
    [fill is #fill and fill2 is #fill2]
  }
}
```
