### ISSUE TITLE
`set page` rule not working properly with hidden heading

### ISSUE THREAD

**Issue by SkytAsul** [typst/typst#4064]
### Description

When using `show heading: {}` to hide headings, they cause weird bugs with `set page` rules on newly created pages.

For instance :
```typst
#set page(width: 5cm, height: 2cm)
#show heading: {}

Page 1 that should *not* have a header.
#pagebreak()

#heading("Random hidden heading")

#set page(header: "This is the header")
Page 2 that *should* have a header.

#pagebreak()
Page 3 that *should* also have the header.
```

The "Page 2" does not have the header, because the `heading` kind-of starts a new page without content. The `set page` rule should automatically break a new page but actually does not.
I don't really understand the internals going on here but I think it's a bug with the compiler.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Same problem as https://github.com/typst/typst/issues/2987
