### ISSUE TITLE
Can't set document properties based on context

### ISSUE THREAD

**Issue by frozolotl** [typst/typst#4065]
### Description

There currently is no way to set any document properties using context-dependent functions.
If one tries to define a show-rule as follows, the PDF export will not have a title set. Using `context document.title` does still output the set title, though.

```typ
// NOTE: You probably don't want to actually do such a `show: body => context …` construction.
#show: body => context {
  set document(title: [Title]) if query(<my-label>).len() == 0
  body
}
#context document.title
// uncomment if desired: <my-label>
```

### Proposal
There should probably be a way to define document properties based on context.

If that is not feasible, then `context set document()` should throw a compiler error.

### Typst version

- [X] I am using the latest version of Typst

**Comment by Andrew15-5** [comment]
Here is the minified version:

```typ
#let template(doc) = {
  // context if state("bundle").get() != true {
  context if query(<sub-document-begin>).len() == 0 {
    set document(title: [Title])
  }
  // set ...
  // set ...
  // set ...
  // show ...
  // show ...
  // show ...
  doc
}
#show: template
Text
```

**Comment by Andrew15-5** [comment]
Similar issue: https://github.com/typst/typst/issues/2326.
(`set page()` inside `context` vs. `set document()` (inside `if` statement that is) inside `context`)
