### ISSUE TITLE
Counter breaks hyperlinks

### ISSUE THREAD

**Issue by VictuarVi** [typst/typst#4066]
### Description

When I have setup a counter, I might want to display its number in a hyperlink with `counter.display()`. However, while doing so, typst "breaks" the hyperlink in *n* sections, where *n* equals the number of blocks of texts plus and counter.

### Code examples

For example:
```
#let mine = counter("number")
#mine.update(8)
#show link: it => underline(it)

#let link_body = [I have been using typst for ] + mine.display() + [ months]
#link("https://www.typst.com", link_body)
```
this appears to be a normal hyperlink, aesthetic-wise; though if you hover on it with a mouse it is broken in *n = 3*. The same goes for the following:
```
#let link_body = [I have been using typst for #mine.display() months]
#link("https://www.typst.com", link_body)

// This gives an error since mine.display() is already content
// #let link_body = [I have been using typst for #str(mine.display()) months]
```

<table>
<tr>
<p align="center">
<b>Hyperlinks with</b> <tt>counter.display()</tt>
</p>
</tr>
<th>

![split_1](https://github.com/typst/typst/assets/114299552/3427394a-da4f-49c1-bb26-e51b0d4d1d39)
</th>
<th>

![split_2](https://github.com/typst/typst/assets/114299552/72710ca6-8425-42e9-bee6-c058b188c97e)
</th>
<th>

![split_3](https://github.com/typst/typst/assets/114299552/7cb91518-2609-4732-a395-60f6089abd83)
</th>
</tr>
</table>

### Temporary workaround

If, however, I declare an integer value and *then* I display that in the hyperlink, it doesn't get split:
```
#let number = 8
#let link_body = [I have been using typst for ] + [#number] + [ months]
#link("https://www.typst.com", link_body)

#let link_body = [I have been using typst for  #number months]
#link("https://www.typst.com", link_body)
```
with this solution I can't by any means use a counter in any hyperlink. Maybe that would work with states, but either way it isn't the same thing.

<p align="center">
<b>Hyperlinks without </b> <tt>counter.display()</tt>
</p>

<p align="center">
<img src="https://github.com/typst/typst/assets/114299552/3f429b7e-da43-4657-a4cb-427622b32d67"  />
</p>

### Reproduction URL

https://typst.app/project/rk5K10JwX0yXIMzLDFsvzC

### Operating system

Web app, Windows, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by flokl** [comment]
Hi, `.display()` depends on the document context and should be used with `context` (https://typst.app/docs/reference/context/). In https://typst.app/docs/reference/introspection/counter there is a note that due to compatibility reasons `.display()` currently additionally works without the `context` keyword. 
Adding `context` fixes your problem:
```
#let mine = counter("number")
#mine.update(8)
#show link: it => underline(it)

#let link_body = context [I have been using typst for ] + mine.display() + [ months]
#link("https://www.typst.com", link_body)
```

![image](https://github.com/typst/typst/assets/48599454/3f4e04a2-465c-4860-b36d-f60876a1763f)

**Comment by VictuarVi** [comment]
Wow thanks! It just works. I tried in headings and it works wonders. Many thanks again and have a nice day!!
