### ISSUE TITLE
Slash cannot be scaled in `lr`

### ISSUE THREAD

**Issue by Enter-tainer** [typst/typst#4086]
### Description

```typ
$
(a/b mid(slash) b/c)
$

$
(a/b mid(|) b/c)
$
```

gives 
<img width="153" alt="image" src="https://github.com/typst/typst/assets/25521218/5d93f00d-31a5-4b63-b66c-08dedb2d4227">

I would expect the slash should be stretched like `|`

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by liuguangxi** [comment]
Here's a workaround:

```typ
#let myslash = math.class("fence", sym.slash)

$
(a/b mid(myslash) b/c)
$
```

gives

![image](https://github.com/typst/typst/assets/2703168/f1337baa-8469-4df7-9e7e-f1cd51e7fd13)

**Comment by Enter-tainer** [comment]
should we change its default class to "fence"? as it works out of the box in LaTeX.

cc @Leedehai

**Comment by Enivex** [comment]
> should we change its default class to "fence"? as it works out of the box in LaTeX.
> 
> cc @Leedehai 

The classes are "god-given" by the Unicode consortium

**Comment by Enter-tainer** [comment]
Maybe LaTeX(or KaTeX) has some different idea? 
` \left(\frac a b \middle / \frac c d\right) ` 

<img width="150" alt="image" src="https://github.com/typst/typst/assets/25521218/44848e21-103f-46e3-8990-e57e9d94d076">

**Comment by Enivex** [comment]
> Maybe LaTeX(or KaTeX) has some different idea?  Does unicode and TeXBook agree on the definition of math classes?
> ` \left(\frac a b \middle / \frac c d\right) ` 
> 
> <img width="150" alt="image" src="https://github.com/typst/typst/assets/25521218/44848e21-103f-46e3-8990-e57e9d94d076">
> 

LaTeX predates Unicode

**Comment by Enivex** [comment]
Arguably `mid` should change the class to fence though, regardless of what you're calling it on. Isn't fences the entire point of the function?

**Comment by laurmaedje** [comment]
> Arguably mid could change the class to fence though, regardless of what you're calling it on. Isn't fences the entire point of the function?

That might make sense indeed.
