### ISSUE TITLE
PNG Output does not support transparency

### ISSUE THREAD

**Issue by manuel5975p** [typst/typst#4088]
## Synopsis
Setting no background results in a transparent svg, but opaquely white png.
## Example
```ts
#lorem(20)
```
Results in
### SVG
![transparent](https://github.com/typst/typst/assets/5041338/60c3c754-2b70-4e54-a29c-aaa80192b559)

---
### PNG
![transparent](https://github.com/typst/typst/assets/5041338/83d71bc9-fcf8-4338-b77a-b6a4f078a425)

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by benlubas** [comment]
So, this works:

```patch
diff --git a/crates/typst-cli/src/compile.rs b/crates/typst-cli/src/compile.rs
index e145a820..a3b72022 100644
--- a/crates/typst-cli/src/compile.rs
+++ b/crates/typst-cli/src/compile.rs
@@ -331,7 +331,7 @@ fn export_image_page(
 ) -> StrResult<()> {
     match fmt {
         ImageExportFormat::Png => {
-            let pixmap = typst_render::render(frame, command.ppi / 72.0, Color::WHITE);
+            let pixmap = typst_render::render(frame, command.ppi / 72.0, Color::WHITE.with_alpha(0.));
             let buf = pixmap
                 .encode_png()
                 .map_err(|err| eco_format!("failed to encode PNG file ({err})"))?;
```

it lets me produce an image like this: 

![test](https://github.com/typst/typst/assets/56943754/9eb17727-d92b-4d0c-9b37-5eea8ddb71b9)

by running `typst compile test.typ test.png`.

With this change, `#set page(fill: white)` will return the white background with no issues.

It does change a default though, I'm not sure what people think about the change?

**Comment by laurmaedje** [comment]
There was some discussion about this on the Discord, starting with this message: https://discord.com/channels/1054443721975922748/1088371867913572452/1237388946946658304

**Comment by benlubas** [comment]
@laurmaedje thanks, am I correct in that this

> I wonder if it would make sense to get the color for the png background from the #page.fill property? And just keep white if its not there?

is the preferred solution then? and someone said they would work on it and then disappeared for a bit?

I might just try and do it myself if that's an acceptable solution

**Comment by benlubas** [comment]
Have something that appears to work, but it's a total shot in the dark from me b/c I've never worked on this project before. I will open a PR later tonight after I eat dinner.
