### ISSUE TITLE
Syntactic sugar for elementwise operations between arrays

### ISSUE THREAD

**Issue by tapyu** [typst/typst#4106]
### Description

Consider

```typ
let a = (1,2,3)
let b = (4,5,6)
```

Inspired by Julia, I propose the following syntaxes:

- `a .+ b`
- `a .- b`
- `a .* b`
- `a ./ b`

For elementwise addition, subtraction, multiplication, and division, respectively.

### Use Case

This is much simpler than, for instance

```
let a = (1,2,3)
let b = (4,5,6)

let c = a.zip((b)).map(x => x.sum())
```

Numerical calculations are where Typst can best outperform LaTeX, but some built-in operations are still required.

**Comment by tapyu** [comment]
Some colleagues had warned me that a similar feature was already proposed in #3863, but I what I am proposing here is different. You said

> Vectors are distinct enough from a general purpose collection type that this does not feel like something that should be built-in on arrays to me. I think such functionality is better left to packages.

What I am proposing here is not restricted to vectors.

For instance, if

```
#let a = ((1, 2),"Hello", 9)
#let b = ((4, 3)," World!",1)
```

then `a .+ b` would apply elementwise sum operation which would lead to array concatenation in the first two elements and arithmetic sum in the third element. This would be equivalent to

```
a.zip(b).map(x => x.sum())
```

But if you ask me, I would say that `a .+ b` is much simpler and yet generic as this syntax is not restricted to vector operations. As long as these operations is defined between such data types, we can use it for whatever element within the array.

**Comment by Enivex** [comment]
> generic

The only (mostly) generic operation would be `.+`.

**Comment by laurmaedje** [comment]
I think this is out of scope for the language, for reasons similar to those laid out in https://github.com/typst/typst/pull/3863#issuecomment-2042409258.
