### ISSUE TITLE
Unbalanced square brackets should be a hard error

### ISSUE THREAD

**Issue by frozolotl** [typst/typst#411]
In a markup context, a lone `]` without a `[` is not considered part of the surrounding object.

This code is rendered like so:
```typst
= [ x ]
= x ]
```
![](https://media.discordapp.net/attachments/1088371867913572452/1090391767653822544/rendered.png)
This behaviour can be found with list-, enum-, and term-items as well.

Additionally, strong and emphasized text may not contain a closing bracket if no opening bracket preceeds it. The compiler will throw an error in that case.

The offending code can be found here:
- https://github.com/typst/typst/blob/main/src/syntax/parser.rs#L34-L39
- https://github.com/typst/typst/blob/main/src/syntax/parser.rs#L161-L165

See reparsing and the other text objects as well.

**Comment by user202729** [comment]
Well, there's an easy workaround (just escape the `]`).

It's usually a good thing to make computer programs intelligent, but I think best to avoid making it _unpredictable_.

Does making the change break any other use case?

**Comment by laurmaedje** [comment]
If unbalanced brackets were allowed that would ruin the idea that you can always take some markup and wrap it in a block without changing it (there are a few tiny exceptions like markup with a trailing backslash).

**Comment by laurmaedje** [comment]
Maybe this should be a hard error ...

**Comment by uben0** [comment]
Yes, the behavior of plain text square brackets is strange.

I advocate the promotion to a hard error, any non escaped unbalanced square brackets.

**Comment by wrzian** [comment]
@laurmaedje (low priority) I can make this a hard error if you want. I'm thinking a good hint would be: "try escaping the bracket: \\]".

**Comment by laurmaedje** [comment]
yeah feel free to
