### ISSUE TITLE
Allow setting `colspan` for table headers

### ISSUE THREAD

**Issue by kamack38** [typst/typst#4121]
### Description

Currently it is not allowed to set colspan on a table header.

### Use Case

This would allow users to create table headers that would not be wrapped, because of a single cell width.

**Comment by Marcono1234** [comment]
Out of curiosity, why did you close this? Is it because this is already possible by putting a `table.cell(colspan: ..., ...)` inside the `table.header(...)`? (as shown in https://github.com/typst/typst/discussions/4879#discussioncomment-10531374)

**Comment by kamack38** [comment]
@Marcono1234 I don't really know. It was a long time ago. Anyway, thanks for this solution.
