### ISSUE TITLE
APA Citation Style leaves out Title.

### ISSUE THREAD

**Issue by toihr** [typst/typst#4124]
### Description

When citing a Webpage as an @misc{...} article from a bibtex file then the citation and the bibliography do not print correctly when using style : "apa"

We obtain the following:
![image](https://github.com/typst/typst/assets/25961872/3fed19a4-b37f-438a-9bd0-d16df327b0ea)

while the correct reproduction generated by Zotero should be:
![image](https://github.com/typst/typst/assets/25961872/6598bab0-7033-4f4f-b987-95e72ee540f5)

I have a minimal Reproduction example in the URL

### Reproduction URL

https://typst.app/project/rWxBsXa_AeJTy0K3d05Q1h

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by xkevio** [comment]
Probably fixed by https://github.com/typst/hayagriva/issues/139. In the meantime, either add some form of author like `NASA` or use the workaround in the issue.

**Comment by toihr** [comment]
So will this likely be fixed when it is merged in with a new version of typst?

**Comment by xkevio** [comment]
> So will this likely be fixed when it is merged in with a new version of typst?

Yes.

**Comment by xkevio** [comment]
This is fixed as of v0.11.1.
