### ISSUE TITLE
Extra space after question mark in math mode

### ISSUE THREAD

**Issue by knuesel** [typst/typst#4133]
### Description

There's an extra space after `?` in math mode:

```
$(1, 1, ?)$

$(1, 1, !)$

$(1, 1, :)$

$(1, 1, #box("?"))$
```

It also looks like there's some space missing on the left. Compare with other punctuation characters and with a `?` in a box:

![image](https://github.com/typst/typst/assets/2412819/8cae5385-0a37-45cd-8e9f-f18020d3e87a)

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
"!" is actually class Normal, not Punctuation. Though both ":" and "?" have class Punctuation, so I'm not entirely sure why their behavior is different.

https://www.unicode.org/Public/math/revision-15/MathClass-15.txt

**Comment by EpicEricEE** [comment]
> I'm not entirely sure why their behaviors are different.

The default class of ":" is overridden by Typst to a relation, probably to match the behavior of LaTeX:
https://github.com/typst/typst/blob/484a0e60d8087fac38b98f697b68f2dd4e829d59/crates/typst/src/math/fragment.rs#L252

**Comment by knuesel** [comment]
OK that explains it. For example "¡" has punctuation class like "?" and is shown the same way, and I get the desired output when I set the class to "normal":

```
$(1, 1, ?)$

$(1, 1, ¡)$

$(1, 1, !)$

$(1, 1, class("normal", ?))$
```

![image](https://github.com/typst/typst/assets/2412819/f6230315-09f5-4d7e-ae8d-17df2f0574da)

Maybe what's missing is a clean way to configure the class to only affect the symbol in math...
