### ISSUE TITLE
Italic digits do not work in math.

### ISSUE THREAD

**Issue by matj1** [typst/typst#4139]
### Description

If I try to typeset an italic mathematical digit like `$italic("1")$`, it shows that digit but upright, and I want it italic.

It is not a font issue; it behaves that way with multiple fonts (as shown in the linked project), and it works as expected in LATEX with multiple fonts.

#### Typst example (wrong)

```typst
$1$ $italic(1)$ $upright(1)$ \
1 #text(style: "italic")[1] #text(style: "normal")[1]
```

![Snímek obrazovky 2024-05-15 171422](https://github.com/typst/typst/assets/22873928/9b804b12-6de6-48f1-aef1-5f5f17c5b617)

#### LATEX example (as expected)

```latex
\documentclass{minimal}
\usepackage{parskip}
\begin{document}
  $1$ $\mathit{1}$ $\mathrm{1}$ \\
  1 \textit{1} \textrm{1}
\end{document}
```

![Snímek obrazovky 2024-05-15 171400](https://github.com/typst/typst/assets/22873928/bf56a6bd-236a-4dd6-9b65-7c67ddda0929)

### Reproduction URL

https://typst.app/project/rcsyUogPKHnzEMkcoaL4yE

### Operating system

Web app

### Typst version

- [x] I am using the latest version of Typst

**Comment by Enivex** [comment]
Because numbers are conventionally written upright in math, there are simply no italic numerals in Unicode. There's not much typst can do about that, other than faking italics.

**Comment by Enivex** [comment]
See https://github.com/typst/typst/issues/394

**Comment by matj1** [comment]
> Because numbers are conventionally written upright in math, there are simply no italic numerals in Unicode.

> Exactly what LaTeX is doing in this situation is not clear to me.

AFAIK, italicity is mainly a property of the font, not the character set. I expect that italics in math work the same way as in text, that it uses the italic glyph from the font. That is what LATEX does, I think.

**Comment by Enivex** [comment]
> I expect that italics in math work the same way as in text

They do not

**Comment by matj1** [comment]
> They do not

The problem is that Typst's math doesn't use various font styles (¿at all?); it uses just Unicode characters with the default style. That has a (significant IMO) limitation that not every letter has Unicode variants in various styles (normal, bold, italic…). For example, if I have a variable named “š”, I want it italic, but Typst sets it upright because Unicode doesn't have an italic š.

I would appreciate that Typst would apply font styles to math so also characters without styled Unicode characters would be styled. 

Although, if I designed a math typesetting system, it would ignore styled Unicode characters and use the normal characters with styled font glyphs for consistency across characters.

**Comment by Enivex** [comment]
> > They do not
> 
> The problem is that Typst's math doesn't use various font styles (¿at all?); it uses just Unicode characters with the default style. That has a (significant IMO) limitation that not every letter has Unicode variants in various styles (normal, bold, italic…). For example, if I have a variable named “š”, I want it italic, but Typst sets it upright because Unicode doesn't have an italic š.
> 
> I would appreciate that Typst would apply font styles to math so also characters without styled Unicode characters would be styled. 
> 
> Although, if I designed a math typesetting system, it would ignore styled Unicode characters and use the normal characters with styled font glyphs for consistency across characters.

I'm not sure where you're going with this. Typst has to deal with the reality of how math fonts work. The glyphs you're talking about simply do not exist.

**Comment by Enivex** [comment]
I could add that while there is no italic š, you can add a caron to an italic s

**Comment by matj1** [comment]
> I'm not sure where you're going with this. Typst has to deal with the reality of how math fonts work. The glyphs you're talking about simply do not exist.

Excuse me, I am frustrated with how math typesetting works. I thought that moving beyond LATEX and using Unicode and OpenType would enable convenient and consistent typesetting of whichever characters, but it seems that it doesn't. I don't know where the main problem is, but I dislike it.

**Comment by khaledhosny** [comment]
> Exactly what LaTeX is doing in this situation is not clear to me.

LaTeX’s `\mathit{}` (despite the misleading name) uses text font (the same goes for other `\math*` font commands).

**Comment by khaledhosny** [comment]
> That doesn't work in longer variable names like “šířka”, which I would use more probably than just “š”.

Multi-letter variables should be set using the text font, the math font will give bad spacing since it is designed/optimized for single-letter variables that are the most common in math.

**Comment by Enivex** [comment]
> > That doesn't work in longer variable names like “šířka”, which I would use more probably than just “š”.
> 
> Multi-letter variables should be set using the text font, the math font will give bad spacing since it is designed/optimized for single-letter variables that are the most common in math.

It's not quite that clear cut. This is why unicode-math provides both \math* and \sym* commands to provide both options (as I'm sure you know).

It may for instance be that the text and math fonts are very different.

**Comment by khaledhosny** [comment]
I don’t see the relation between the presence of `\sym*` commands and multi-letter variables. You can always do whatever you want, but if you want good typography that is the way to go.

**Comment by Enivex** [comment]
> I don’t see the relation between the presence of `\sym*` commands and multi-letter variables. You can always do whatever you want, but if you want good typography that is the way to go.

I don't necessarily disagree, but if the option isn't there, people will still ask for it.

**Comment by laurmaedje** [comment]
The text font stuff is covered by https://github.com/typst/typst/issues/366 and about the lack of italic digits there is not much we can do, so I'll close this.
