### ISSUE TITLE
`_typst` compdef file for zsh autocompletion doesn't allow for path completion

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#4156]
After running `nix build` I put `_typst` from `result/share/zsh/site-functions/_typst` into `~/.local/share/zsh/site-functions/_typst`. Then after typing `typst query` I invoke autocompletion for the Typst file path but all I get is:

```
--  input -- Path to input Typst file, use `-` to read input from stdin --
```

I suspect that the file is missing some switch that allows for path autocompletion in that place. Since this file is being generated (I think), then the library that puts it together has an bug or the use of that library is incorrect.

**Comment by istudyatuni** [comment]
Bisect points to 70b354e887cf735db070f766e4812357dddb8a40
