### ISSUE TITLE
Font Times New Roman

### ISSUE THREAD

**Issue by dsantiago** [typst/typst#416]
I am new to typst but tried to set the font to Times New Roman and had no success... What's the catch here?

**Comment by QQKdeGit** [comment]
Maybe typst does not support it yet. But you can import fonts in online editor.

Your dir will look like
```
- main.typ
- template.typ
- Times New Roman Bold.ttf
- Times New Roman.ttf
```

Then in typst
```
#set text(font: "Times New Roman")
```

**Comment by Enivex** [comment]
Stix Two Text is basically a modern version of it. You may want to try it.

**Comment by lvignoli** [comment]
For the web app, it is not shipped by default, and you should import your own font files.

But you could try to use Typst locally on your computer.
The `typst` CLI tries to discover fonts automatically on your computer by looking into system font folders.

You can check what fonts are available to Typst on you computer by running
```sh
typst --fonts
```
and eventually add a directory with your custom font with
```sh
typst --font-path <dir>
```

Usually, Times New Roman is shipped with every operating systems.
Adding
```typst
#set text(font: "Times New Roman")
```
should do the trick.

**Comment by dsantiago** [comment]
Thanks guys for all information! As for the CLI suggestion, I am still waiting for brew (mac package manager) to incorporate typst as I use M1 and do not have the binaries

**Comment by Biansky-Sophie** [comment]
> Stix Two Text is basically a modern version of it. You may want to try it.

TeX Gyre Termes would be a much better choice if you want a font looking as similar to Times New Roman as possible. Also, it's supported for math (in contrast to Times New Roman).

**Comment by Enivex** [comment]
> TeX Gyre Termes would be a much better choice if you want a font looking as similar to Times New Roman as possible. Also, it's supported for math (in contrast to Times New Roman).

I mean, both fonts are explicitly inspired by Times New Roman. Which one you prefer is largely down to personal preference. For me, that's Stix Two, which also has unparalleled math support (through Stix Two Math).

**Comment by laurmaedje** [comment]
Times New Roman isn't a free font, so we can't ship it in the web app without huge cost. As others mentioned, there are various free fonts that are very similar.
