### ISSUE TITLE
Retrieving the default supplement function from a reference

### ISSUE THREAD

**Issue by FedericoStra** [typst/typst#417]
If we set a default `supplement` function for references, for instance
```
#set ref(supplement: it => box(stroke:red, it))
```
then it appears that there is no way of retrieving it from any specific reference, because it is not stored neither in the `supplement` field nor in `citation.supplement`:
```
#show ref: r => {
  r.supplement          // error: content does not contain field "supplement"
  r.citation.supplement // this won't work: the field is `none`
}
```

Is there a way to retrieve a default `supplement` function?

Please notice that if we set a default `supplement` that is not a function, it will be correctly stored in `r.citation.supplement`. The issue is only with functions, in which case `r.citation.supplement` is `none`.

[Here](https://typst.app/project/rtsq6gsjVewx4Yd2W1dOJq) is a demo on `https://typst.app`.

**Comment by laurmaedje** [comment]
It will not be available if you set it via show rule. Can easily be fixed for this case by adapting the `Synthesize` impl of `RefElem`, but in general needs a bit of rearchitecturing to make it available for all elements in all show rules.

**Comment by Enivex** [comment]
The first way now works as of 0.11
