### ISSUE TITLE
List syntax ignores `#set list(tight: false)`

### ISSUE THREAD

**Issue by Gingeh** [typst/typst#4180]
### Description

Despite being marked as settable in the docs, lists created with the dedicated list syntax ignore the setting. 
This also happens with equation's block parameter and presumably any other parameters that are automatically set based on syntax usage. 
This behaviour was previously noted in #1714 but the issue was closed by the author.

The description for the tight parameter does mention the following, but it isn't clear that this will always override set rules:
> In markup mode, the value of this parameter is determined based on whether items are separated with a blank line.

The documentation for math.equation has a similar note in the Syntax section but makes this behaviour even less clear:
>  Starting and ending the equation with at least one space lifts it into a separate block that is centered horizontally.

If this behaviour is intended then the documentation should explicitly warn about it.

Reproduction:
```
#set list(tight: false)

this list ignores the set rule
- first
- second

this list respects the set rule
#list[first][second]
```
![image](https://github.com/typst/typst/assets/39150378/792f8c25-4ea6-4223-a56a-3e80357e6ac8)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
> If this behaviour is intended then the documentation should explicitly warn about it.

Agreed. I have relabelled from bug to docs issue.
