### ISSUE TITLE
Cannot set raw theme to `none`

### ISSUE THREAD

**Issue by Coekjan** [typst/typst#4182]
### Description

![image](https://github.com/typst/typst/assets/69834864/27fff9aa-8c34-44a9-bbca-7124d6cf57d4)

The document says `raw.theme` can be `none` or `str`, but when I compile the following code:

```typst
#set raw(theme: none)
```

it emits the error:

```plaintext
error: expected string, found none
```

### Typst version

- [X] I am using the latest version of Typst

**Comment by Coekjan** [comment]
It seems because `parse_theme` always want to parse the arg into `EcoString`: https://github.com/typst/typst/blob/v0.11.1/crates/typst/src/text/raw.rs#L820

**Comment by Enivex** [comment]
Curiously, the default is none, so how is it working at all?

**Comment by Coekjan** [comment]
> Curiously, the default is none, so how is it working at all?

I think it is because the bug is at argument parsing. The default `none` behavior will work if the arg is parsed successfully.
