### ISSUE TITLE
An `AlignPointElem` has a non-zero height

### ISSUE THREAD

**Issue by Leedehai** [typst/typst#4187]
### Description

A line of `- -` should have a very small height, as shown in the left two boxes' rendering; but after inserting `&` to this line, the line gains a visible height, as shown in the right two boxes.

```typ
#box($ - - $, fill: silver)
#box($ a \ - - $, fill: silver)
#box($ - &- $, fill: silver)
#box($ a \ - &- $, fill: silver)
```
[
<img width="200" src="https://github.com/typst/typst/assets/18319900/1169b5ed-9277-4cb1-a491-a2287e02322f">
](url)

However, the height of a `MathFragment::Align` (inserted by `impl LayoutMath for Packed<AlignPointElem>`) is supposed to be zero, according to https://github.com/typst/typst/blob/4f8bbb01ce2f333383f7209fe0d83ee847d6eb48/crates/typst/src/math/fragment.rs#L45-L52

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Leedehai** [comment]
This is because in `MathRun::into_line_frame()`, the line's frame height is calculated by adding the line's `ascent()` and `descent()`, which are in turn calculated by adding the maximum `ascent()` and maximum `descent()` along all `MathFragment`s in this line (`MathRun`).

In a line with `-` (a `MathFragment::Glyph`) *only*, every fragment has ascent 2.7pt and descent -2.3pt (negative), so the line's height is 2.7pt + (-2.3pt) = 0.4pt. If the line contains a `MathFragment::Align`, that fragment's ascent and descent are 0pt, so the max ascent of all fragments in this line is still 2.7pt, but the descent of all fragments in this line becomes 0pt (instead of -2.3pt), so the line's height becomes 2.7pt + 0pt = 2.7pt.

**Comment by laurmaedje** [comment]
I think ascent and descent should be clamped to zero there.

**Comment by Leedehai** [comment]
Clamping to zero may lead to unintended results, because a glyph's lowest part could indeed be higher than the baseline. For example, if `MathRun::descent()` is modified like this
```diff
    pub fn descent(&self) -> Abs {
        self.iter()
-           .map(MathFragment::descent)
+           .map(|e| e.descent().max(Abs::zero()))
            .max()
            .unwrap_or_default()
```
then one of the broken test (`math-underover-brackets`) shows
<img width="100" src="https://github.com/typst/typst/assets/18319900/2d77d6e3-74a9-4089-b4b1-31972b3079ca">

More obvious:
```typ
$ overbrace(equiv) $
```
Output: <img width="50" alt="Screenshot 2024-05-22 at 21 52 22" src="https://github.com/typst/typst/assets/18319900/0a2dd25b-c243-4821-974d-4933dc1343ba">, Reference: <img width="50" alt="Screenshot 2024-05-22 at 21 51 56" src="https://github.com/typst/typst/assets/18319900/60c4d737-5f14-449e-b47f-d398953d9ed4">

**Comment by Leedehai** [comment]
Clamping to zero may lead to unintended results, because a glyph's lowest point could indeed be _higher_ than the baseline, and therefore having a _negative_ descent. For example, if `MathRun::descent()` is modified like this
```diff
    pub fn descent(&self) -> Abs {
        self.iter()
-           .map(MathFragment::descent)
+           .map(|e| e.descent().max(Abs::zero()))
            .max()
            .unwrap_or_default()
    }
```
then one of the broken test (`math-underover-brackets`) shows
<img width="100" src="https://github.com/typst/typst/assets/18319900/2d77d6e3-74a9-4089-b4b1-31972b3079ca">

More obvious:
```typ
$ overbrace(equiv) $
```
Output: <img width="50" alt="Screenshot 2024-05-22 at 21 52 22" src="https://github.com/typst/typst/assets/18319900/0a2dd25b-c243-4821-974d-4933dc1343ba">, Reference: <img width="50" alt="Screenshot 2024-05-22 at 21 51 56" src="https://github.com/typst/typst/assets/18319900/60c4d737-5f14-449e-b47f-d398953d9ed4">

**Comment by Leedehai** [comment]
Clamping to zero may lead to unintended results, because a glyph's lowest point could indeed be _higher_ than the baseline, and therefore having a _negative_ descent. For example, if `MathRun::descent()` is modified like this
```diff
    pub fn descent(&self) -> Abs {
        self.iter()
-           .map(MathFragment::descent)
+           .map(|e| e.descent().max(Abs::zero()))
            .max()
            .unwrap_or_default()
    }
```
then one of the broken tests,`math-underover-brackets`, shows
<img width="100" src="https://github.com/typst/typst/assets/18319900/2d77d6e3-74a9-4089-b4b1-31972b3079ca">

More obvious: `$ overbrace(equiv) $`
Output: <img width="50" alt="Screenshot 2024-05-22 at 21 52 22" src="https://github.com/typst/typst/assets/18319900/0a2dd25b-c243-4821-974d-4933dc1343ba">, Reference: <img width="50" alt="Screenshot 2024-05-22 at 21 51 56" src="https://github.com/typst/typst/assets/18319900/60c4d737-5f14-449e-b47f-d398953d9ed4">

**Comment by Leedehai** [comment]
Instead, I suggest this change below (all tests passing). The idea is that some `MathFragment`s are not real fragments to be layouted, but are [in-band control signals](https://en.wikipedia.org/wiki/In-band_signaling#:~:text=In%20telecommunications%2C%20in%2Dband%20signaling,even%20over%20a%20separate%20network.) to instruct how fragments shall be layouted. Therefore, these fragments are "shapeless"/"sizeless" -- it is not the same as "having a zero size"; the notion of "shape"/"size" itself is absent for these fragments.

```diff
diff --git a/crates/typst/src/math/fragment.rs b/crates/typst/src/math/fragment.rs
index ef865b38..596c3c16 100644
--- a/crates/typst/src/math/fragment.rs
+++ b/crates/typst/src/math/fragment.rs
@@ -139,6 +139,10 @@ impl MathFragment {
         }
     }

+    pub fn is_shapeless(&self) -> bool {
+        matches!(self, MathFragment::Align | MathFragment::Linebreak)
+    }
+
     pub fn italics_correction(&self) -> Abs {
         match self {
             Self::Glyph(glyph) => glyph.italics_correction,
diff --git a/crates/typst/src/math/row.rs b/crates/typst/src/math/row.rs
index 6454f491..6577abf5 100644
--- a/crates/typst/src/math/row.rs
+++ b/crates/typst/src/math/row.rs
@@ -117,11 +117,17 @@ impl MathRun {
     }

     pub fn ascent(&self) -> Abs {
-        self.iter().map(MathFragment::ascent).max().unwrap_or_default()
+        self.iter()
+            .filter_map(|e| if e.is_shapeless() { None } else { Some(e.ascent()) })
+            .max()
+            .unwrap_or_default()
     }

     pub fn descent(&self) -> Abs {
-        self.iter().map(MathFragment::descent).max().unwrap_or_default()
+        self.iter()
+            .filter_map(|e| if e.is_shapeless() { None } else { Some(e.descent()) })
+            .max()
+            .unwrap_or_default()
     }
```
