### ISSUE TITLE
Literally input another file

### ISSUE THREAD

**Issue by m-kru** [typst/typst#4194]
### Description

Is there any way to literally input one .typ file into another one? There are `#include` and `#import` functions. However, they treat files as separate modules.

### Use Case

Sometimes you just want to split document into multiple files without organizing the whole document into separate modules.

**Comment by laurmaedje** [comment]
This is not supported and there are no plans to add it. The fact that modules are free-standing makes them predictable and robust. If things are included directly, many things can go wrong with variables names etc. I understand that this might be convenient in some cases, but I believe the addition of this feature would in total deteriorate the user experience of Typst and its packages. Because it's the "easy way" and people would start using it where not appropriate. As a secondary point, the encapsulation of `import` and `include` is also important from a performance and incremental compilation perspective because they can be considered in isolation.

**Comment by Enivex** [comment]
> This is not supported and there are no plans to add it. The fact that modules are free-standing makes them predictable and robust. If things are included directly, many things can go wrong with variables names etc. I understand that this might be convenient in some cases, but I believe the addition of this feature would in total deteriorate the user experience of Typst and its packages. Because it's the "easy way" and people would start using it where not appropriate. As a secondary point, the encapsulation of `import` and `include` is also important from a performance and incremental compilation perspective because they can be considered in isolation. 

You may want to close https://github.com/typst/typst/issues/595 as well then

**Comment by qwerzl** [comment]
> This is not supported and there are no plans to add it. The fact that modules are free-standing makes them predictable and robust. If things are included directly, many things can go wrong with variables names etc. I understand that this might be convenient in some cases, but I believe the addition of this feature would in total deteriorate the user experience of Typst and its packages. Because it's the "easy way" and people would start using it where not appropriate. As a secondary point, the encapsulation of `import` and `include` is also important from a performance and incremental compilation perspective because they can be considered in isolation.

@laurmaedje May us request a reconsideration? I believe the freedom to choose should be given to users and module authors. Such "bad practices" might not seem perfect but they might come in handy in some circumstances especially for a markup language where people'd care less about code quality and just want to get things done fast.

**Comment by weltonrodrigo** [comment]
I just want to keep a style.typ as a separate file from my main.typ 😞

**Comment by alerque** [comment]
I think it's worth reiterating that this would degrade the experience for everybody, even those not using it directly (the incremental compilation inferences would regress). Also this could be accomplished for those that want it for programmatic reasons with preprocessing.
