### ISSUE TITLE
Raise an error when font is set to a nonexistent family

### ISSUE THREAD

**Issue by jkunimune** [typst/typst#4205]
### Description

When the `font` argument is set in the `text` function to a nonexistent font family, it currently silently falls back on the default font.

![imagen](https://github.com/typst/typst/assets/5607801/36a6d668-1148-4f38-9ad8-4cf95c79aaf5)

However, it should throw an error.

### Use Case

It seems to me that if the specified font cannot be found, the user has made a mistake and ought to know so they can correct it.  Good error reporting is especially important for this because it's not always easy to tell by looking at the text which font is being used.

**Comment by PgBiel** [comment]
Hi, I believe this is a duplicate of https://github.com/typst/typst/issues/2818

**Comment by jkunimune** [comment]
Oops, yes it is.
