### ISSUE TITLE
Raw syntaxes vs theme behavior

### ISSUE THREAD

**Issue by m-kru** [typst/typst#4207]
### Description

typst 0.11.1 (50115102)

Adding definition for a new syntax for the raw command is straightforward. One just have to write new `language.sublime-syntax` file and add `#set raw(syntaxes: "lang.sublime-syntax")` to the document and done. You can then easily insert any domain specific language block snippets in your document using the three backticks notation. It feels like globally adding a support for a new language. 

On the other hand, adding a theme for you DSL feels strange, or I do not understand something. I have defined a theme and added it in the following way:
```
#set raw(
	syntaxes: "lang.sublime-syntax",
	theme: "lang.tmTheme"
)
```
Snippets of my DSL are now correctly highlighted. However, all remaining snippets within the document are now monochrome. This command tells the compiler to use the added theme for all encountered raw blocks, even when the language is different than the one the theme is defined for. 

### Use Case

I don't understand why adding a theme does not work like adding a syntax. I would like to avoid specifying a theme each time I insert a snippet of my DSL, and instead I would like to instruct the compiler to use my theme each time it encounters a snippet of my DSL.

**Comment by Enter-tainer** [comment]
maybe `let my-raw = raw.with(syntax: ...)`?

**Comment by m-kru** [comment]
@Enter-tainer with this approach I can'use the following syntax anymore (pretend there is no backslach).

```
\```lang
\```
```

**Comment by Enter-tainer** [comment]
> Snippets of my DSL are now correctly highlighted. However, all remaining snippets within the document are now monochrome. 

This is strange. Can you try only add new `syntaxes` and omit `theme`? I guess that should work

**Comment by m-kru** [comment]
@Enter-tainer, then all snippets are highlighted except the ones with my DSL.

**Comment by Enter-tainer** [comment]
>  I can'use the following syntax anymore

you can use something similar(but more verbose)
````typst
#let my-raw(t) = raw(lang: t.lang, theme:..., t.text)

#my-raw(
```lang
...
```)
````

**Comment by Enter-tainer** [comment]
> then all snippets are highlighted except the ones with my DSL.

Then i think your syntax file might have some problems so it requires a specially theme(which doesn't work for other languages) to work

**Comment by m-kru** [comment]
Can you point me to any example? The ones presented in the https://typst.app/docs/reference/text/raw/ are clearly not sufficient, even with the urls to the sublime format descriptions.

**Comment by Enter-tainer** [comment]
> Can you point me to any example

I don't exactly get what you are looking for. For writing syntax files, there are some existing ones you can refer to https://github.com/sharkdp/bat/tree/master/assets/syntaxes.

> The ones presented in the https://typst.app/docs/reference/text/raw/ are clearly not sufficient

I'm not the author of docs. Maybe you can post some useful links after you finished your syntax file

**Comment by m-kru** [comment]
My syntax file is super simple, I can paste it here:
```
%FBDL
---
name: fbdl
file_extensions: [fbd]
scope: source.fbd

contexts:
  main:
    - match: \b(blackbox|block|bus|config|irq|mask|memory|param|proc|return|static|status|stream)\b
      scope: type.fbdl
````
I don't have a problem with the syntax file, but with applying a custom theme for my syntax. My theme file is also small:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Color Scheme for Functional Bus Description Language</string>
    <key>settings</key>
    <array>
        <!-- Global settings -->
        <dict>
            <key>settings</key>
            <dict>
            </dict>
        </dict>
        <!-- Scope styles -->
        <dict>
            <key>name</key>
            <string>Type</string>
            <key>scope</key>
            <string>type</string>
            <key>settings</key>
            <dict>
                <key>fontStyle</key>
                <string>bold</string>
            </dict>
        </dict>
    </array>
</dict>
```
It is correct as it works. Now, I would like to be able to insert block code snippets into the text using the 3 backticks and language name notation. I can also accept any other idiomatic approach which does not enforce me to specify the theme all the time and does not break highlighting for other language snippets.

The closest I get so far is :
````typ
#set raw(
	syntaxes: "fbdl.sublime-syntax",
)

#let my-raw(t) = raw(lang: t.lang, theme: "fbdl.tmTheme", t.text)

#my-raw(
```fbd
Main bus
  C config; width = 17
  S status
```
)
````

However, this is now extra verbose, as I have to type both:
```
#my-raw
```
and
````
```fbd
```
````
Ideally I would like to just type:
````
```fbd
Main bus
  C config; width = 17
  S status
```
````
and get a highlighted snippet in the generated pdf.

**Comment by Enter-tainer** [comment]
the problem is that your theme override default ones, and the theme doesnt provide anything apart from `bold`.

to address this, you may want your syntax file to provide some "standard" or commonly used scope names, like `markup.bold`

**Comment by laurmaedje** [comment]
Have you tried `#show raw.where(lang: "mylang"): set raw(theme: "mytheme")`?

**Comment by Enter-tainer** [comment]
after switch to `markup.bold`, it works cc @m-kru 

<img width="584" alt="image" src="https://github.com/typst/typst/assets/25521218/c5fc92ad-4ca4-48a5-80e2-4fae7cee0dce">

**Comment by m-kru** [comment]
> Have you tried `#show raw.where(lang: "mylang"): set raw(theme: "mytheme")`?

Awesome, it works as expected.

**Comment by m-kru** [comment]
@Enter-tainer what do you mean by `markup.bold`?

**Comment by Enter-tainer** [comment]
change `      scope: type.fbdl` to `scope: markup.bold`. It is considered as standard or commonly used scope names. So it is supported in most themes

**Comment by m-kru** [comment]
> change ` scope: type.fbdl` to `scope: markup.bold`. It is considered as standard or commonly used scope names. So it is supported in most themes. You may want to read [#4207 (comment)](https://github.com/typst/typst/issues/4207#issuecomment-2122983783)

It also works as expected, and is simpler, thanks a lot!
