### ISSUE TITLE
Provide native binaries for Windows on ARM 

### ISSUE THREAD

**Issue by affans** [typst/typst#4210]
### Description

Qualcomm, MS, and OEM partners have announced new generation of laptops/devices that use the X Elite chips which are ARM based. I am opening this issue to see if the devs can provide a native version for Windows on ARM. 

### Use Case

This will provide maximum performance instead of going through emulation layer.

**Comment by LaurenzV** [comment]
The reason it was removed is because there were issues with some crate that wouldn't compile on that target in CI... But maybe it's worth revisiting that.

**Comment by Enivex** [comment]
> The reason it was removed is because there were issues with some crate that wouldn't compile on that target in CI... But maybe it's worth revisiting that.

Considering the large number of ARM-based Windows laptops launching this year with the Snapdragon X Pro/Elite, it's definitely going to come up more often.

**Comment by LaurenzV** [comment]
That's the PR that removed it: https://github.com/typst/typst/pull/1636

But looks like the linked issue has been closed by now, so I will try out if it works now.

**Comment by LaurenzV** [comment]
Seems like it's still not as straightforward: https://github.com/LaurenzV/typst/actions/runs/9177968107/job/25236779384

**Comment by laurmaedje** [comment]
If someone can figure out how to build it, I'm opening to re-adding support it.

**Comment by EpicEricEE** [comment]
If you don't use cross, it seems to successfully build with the `aarch64-pc-windows-msvc` target, though I don't know if the binary actually works correctly: https://github.com/EpicEricEE/typst/actions/runs/9179205025/job/25240822697

**Comment by LaurenzV** [comment]
Yup, I just tested it via Parallels on Windows ARM and the binary works fine. So we could at least reinclude the Windows binary.

The Linux one still doesn't work (see here https://github.com/LaurenzV/typst/actions/runs/9179881365), but I think Windows is probably the most important one, so we could start by readding that one.

**Comment by LaurenzV** [comment]
In this case I think we can just go ahead and readd both of them.

**Comment by Enivex** [comment]
Aren't there like 5 people using riscv?

**Comment by PgBiel** [comment]
> Aren't there like 5 people using riscv?

I, for one, would be up to doing my part in the chicken-and-egg problem :)

Especially now that Framework laptops will support RISC-V[^1].

[^1]: https://frame.work/blog/introducing-a-new-risc-v-mainboard-from-deepcomputing
