### ISSUE TITLE
GIR: Generic Intermediate Representation

### ISSUE THREAD

**Issue by gamagan** [typst/typst#4215]
### Description

There are requests for Typst to create output other than PDF, such as HTML.

I'd like to put in a request for a Generic Intermediate Representation (GIR).  That is, the compiler would transform the source input into an output designed to be consumed by applications other than itself.

The chosen output format could be XML, or JSON, or S-Expressions, or a custom IR language, or whatever.
The point is for 3rd-party apps to be able read that GIR, and to have access to the processed document in a convenient format. By definition, the GIR represents source `.typ` document(s) that have been typechecked,  macro expanded, semantically-analysed, and post-processed in such a way as to make subsequent access/query of the result as convenient as resonably possible.

Example:
```
[bunch of .typ documents] -> typst-compiler -> output.xml
```

I understand that this is not a small task. This need not be included in version 1.0 of Typst.  It can be a future enhancement of the compiler.

The ability to create intermediate representations that can be consumed by arbitrary apps opens up a universe of posibilities.

Hope all is well,
Regards

### Use Case

- Transform from Typst/GIR to Latex
- Use GIR as input to an "Intellisense for Typst" thingy.
- Use a different PDF generator than Typst's builtin.
- Convert to EPub, HTML, A vendor's arcane, whatever

My personal usecase is that I want to create a small app to visualize some math operations, such as Vectors (arrows starting at the origin), Rotations (Vertices rotating about an origin), Matrix transforms (change of basis), etc. I'd like to include descriptions for the visualizations, along with the applicable math equations, and other relevant verbiage and/or images. For this non-visualization part, I'd like to use Typst to generate that information; specially the layout. Ideally, that info chunk is something that I can easily process internally in my app, and then display accordingly.

In a way, my app would be a type of viewer for specific Typst content.

**Comment by Enter-tainer** [comment]
This is more like a general idea but lacks technical details.

**Comment by Myriad-Dreamin** [comment]
duplicated? #464

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/typst/issues/3304. I'm not really optimistic that #3304 is feasible, but we can leave one issue about this open for now.
