### ISSUE TITLE
First line indent after the block equation

### ISSUE THREAD

**Issue by AstaSchnee** [typst/typst#4218]
### Description

_Typst_ seems to reset the paragraph counter after a block, such that the first paragraph after a block equation does not have an indent.
Is it possible to provide choices of whether to do that?

### Use Case

In _Latex_, both of the two following are often used:

E = mc2,
where c is the speed of light.

and

E = mc2. 
[indent]Then, we have ...

But the second case can not automatically be done.
This is an important function for an academic typesetting application.

**Comment by Enivex** [comment]
Essentially a duplicate of https://github.com/typst/typst/issues/311, but with a different focus I guess

**Comment by laurmaedje** [comment]
I would consider this a duplicate of #311.

**Comment by Enivex** [comment]
> I would consider this a duplicate of #311.

I don't think it is actually. It's the same issue as #3206, just for equations instead of lists. Block equations are typically seen as part of the paragraph itself.

**Comment by laurmaedje** [comment]
True.
