### ISSUE TITLE
Cannot retrieve spacing from block

### ISSUE THREAD

**Issue by knuesel** [typst/typst#4221]
### Description

The compiler says `function block does not contain field ...` when trying to get the `above`/`below`/`spacing` value of a block:

```
#set block(above: 1cm)
#context block.above
```

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
See also https://github.com/typst/typst/issues/3636

**Comment by laurmaedje** [comment]
I think it's fair to consider it a bug. It is the result of how it's done in the code because block spacing has some hacks. But I think we can get rid of them soon.

**Comment by laurmaedje** [comment]
This was fixed a whole ago. `above` and `below` can be retrieved on main. `spacing` can't because it is just a shorthand and `above` and `below` can differ.
