### ISSUE TITLE
Allow description sentences on new lines in terms list

### ISSUE THREAD

**Issue by m-kru** [typst/typst#4222]
### Description

typst 0.11.1 (50115102)

Most people like to put each sentence on a separate line when using markdown systems. This is very handy, as deleting or reshuffling sentences is basically deleting or reshuffling lines. This is also much easier to grep or parse text files when each sentences is in a separate line.

With typst this is generally possible. However, the term list is a an exception. The description of the term must be in the same line as the term. For example,
```
/ term: First sentence. Second sentence. Third sentence.
```
If you do not follow this pattern the text will be rendered as a new paragraph, not a term description.
I think it would be convenient if the following syntax also would be acceptable:
```
/ term:
First sentence.
Second sentence.
Third sentence.
```

For me, the second approach has increased legibility. What is more, the behavior would be somehow uniform with the behavior of lines in the case of paragraphs. A new paragraph is started when there is an empty line between text.

### Use Case

Convenience, increased legibility, behavior more unified with the paragraphs behavior.

**Comment by Enivex** [comment]
This is already the case, you just need to indent the lines.

**Comment by m-kru** [comment]
@Enivex why is the indentation required? Do you know?

**Comment by Enivex** [comment]
> @Enivex why is the indentation required? Do you know?

Because otherwise it's ambiguous what the user wants.

**Comment by m-kru** [comment]
Does typst have any recommended style for the indentation? In the documentation I can see 2 spaces.

**Comment by Enivex** [comment]
> Does typst have any recommended style for the indentation? In the documentation I can see 2 spaces.

I don't think it matters as long as you're consistent.
