### ISSUE TITLE
How to compose a table like this?

### ISSUE THREAD

**Issue by Zephyr69** [typst/typst#423]
![Screen-Shot-2017-02-05-at-7 20 42-PM](https://user-images.githubusercontent.com/63066174/228505984-77ee534d-a45a-4040-9c84-9fa77e80cc09.png)

How do I compose a table like this?

**Comment by Enivex** [comment]
https://github.com/typst/typst/issues/226
https://github.com/typst/typst/issues/169

**Comment by Zephyr69** [comment]
Got it thanks to @waynr !

**Comment by Zephyr69** [comment]
Got it thanks to @waynr !
