### ISSUE TITLE
Allow `measure` to accept available size

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#4232]
### Description

With this proposal, `measure` would accept an optional `available` dictionary with `width` and `height` keys, specifying available width and height respectively. If `available` is specified, the content passed to measure is laid out without having infinite available space, but instead with restricted space, as defined by `available`.

### Use Case

When you have, e.g., a paragraph, you might want to know its dimensions when it is laid out on the page, instead the dimensions it would have on an infinite page.

There are workaround currently, but for more complex use cases, they quickly become very ugly.

**Comment by Myriad-Dreamin** [comment]
You may try this:

```
#context measure(lorem(100)) \
#context measure(block(lorem(100), width: 400pt))
```

![image](https://github.com/typst/typst/assets/35292584/3e70850d-7a3b-485e-9402-e00a491a5597)

**Comment by MDLC01** [comment]
Yes, but this only works if you are trying to measure the height with given an available width. I don't think there are workarounds as simple as this one for other cases, such as measuring the width given an available width.

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/4264
