### ISSUE TITLE
Element with no content followed by `pad` can force breakable block to create an empty frame

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#4234]
### Description

This bug has a similar effect as #2297, which was fixed by #2517. Sadly, the fix does not work in the specific case where the element with no content is directly followed by a `pad` element (which happens somewhat often given that `block` used `pad` under the hood to make `inset` work).

### Example

```typ
#set page(height: 3cm, margin: 0.5cm)

Not enough space remaining on this page to fit the whole block.

#block(stroke: 1pt)[
  #counter("dummy").update(1)
  #pad(left: 1cm, top: 1cm, rect(height: 1cm, fill: gray))
]
```

![An empty frame is created for the counter update.](https://github.com/typst/typst/assets/57839069/5f7905ae-cbb7-45ad-8ab9-e162b6cd81c5)

Typst produces the same output without an explicit `pad`:

```typ
#set page(height: 3cm, margin: 0.5cm)

Not enough space remaining on this page to fit the whole block.

#block(stroke: 1pt)[
  #counter("dummy").update(1)
  #block(inset: (left: 1cm, top: 1cm), rect(height: 1cm, fill: gray))
]
```

Note that removing the counter update removes the undesired rectangle.

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Related: https://github.com/typst/typst/issues/2914

**Comment by laurmaedje** [comment]
I'll close this in favor of #2914. There are various ways to reproduce this problem by adding things into the block that aren't visible, but still produce a non-empty or non-zero-sized frame. Needs a more general solution.
