### ISSUE TITLE
`measure()` treats objects in `rotate(reflow: true, …)` as zero-width

### ISSUE THREAD

**Issue by Jollywatt** [typst/typst#4237]
### Description

The dimensions of an object that has been rotated with `reflow: true` seem to be different according to 1) an enclosing `rect` and 2) the contextual `measure` function. Specifically, the bounding box reported by measure is that of a rotated zero-width object.

MWE:
```typ
#set rect(inset: 0pt, stroke: red)

#let obj = rotate(30deg, reflow: true)[hello]

#rect(obj)

#context rect(
  width: measure(obj).width,
  height: measure(obj).height,
  obj,
)
```

<img width="191" alt="Screenshot 2024-05-24 at 00 44 06" src="https://github.com/cetz-package/cetz/assets/24970860/6b25a863-3577-4512-a44e-d401a9f73a58">

This is also observed for rotated objects other than text (see reproduction URL).

Perhaps related: the dimensions seem to be incorrect when the parent container sizes automatically to content:

```typ
#set page(width: auto, height: auto)
#set rect(inset: 0pt, stroke: red)

Auto-sizing page:
#rect(rotate(30deg, reflow: true)[hello])
```
<img width="335" alt="Screenshot 2024-05-24 at 02 19 18" src="https://github.com/cetz-package/cetz/assets/24970860/d26f6cc1-ddff-43cf-90dd-f1888fcabb08">

### Reproduction URL

https://typst.app/project/rUM1E564AvpxiKtmw50JMW

### Operating system

Web app, Windows, Linux, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Jollywatt** [comment]
Related discussion: cetz-package/cetz#604 and Jollywatt/typst-fletcher/issues/34.

**Comment by kram-tm** [comment]
This seems to apply to `scale(reflow: true, …)` as well.
