### ISSUE TITLE
Bibliography and including multiple files

### ISSUE THREAD

**Issue by wjslager** [typst/typst#424]
My project looks like this:
```
main.typ
literature.bib
chapers/one.typ
chapter/two.typ
chapter/three.typ
```

``main.typ`` has things like an abstract, table of contents, ``include`` for each chapter and then a bibliography.

If I try to cite from one of the chapters I get: ``the document does not contain a bibliography``

If I add ``#bibliography("literature.bib")`` to each chapter I get: ``multiple bibliographies are not supported``

How can I split my document in multiple files and still create one bibliography?

**Comment by wjslager** [comment]
Also, I'm using ``typst.exe --watch main.typ`` and I expect it to only generate a pdf for ``main.typ`` but it generates pdfs for all ``.typ`` files included

**Comment by laurmaedje** [comment]
Are you using the third-party LSP by any chance? Because the compiler doesn't do that. That would also explain the first error.

**Comment by wjslager** [comment]
Oh it seems I only have this issue when using the [Typst LSP](https://github.com/nvarner/typst-lsp) autobuild function in VSCodium. When building using ``typst.exe --watch main.typ`` it creates the document as expected.

**Comment by laurmaedje** [comment]
So, both issues are resolved?

**Comment by wjslager** [comment]
Yes they are, thanks!
