### ISSUE TITLE
Quote attribution not part of block

### ISSUE THREAD

**Issue by Enivex** [typst/typst#4246]
### Description

See https://github.com/typst/typst/discussions/4244#discussioncomment-9549511

> In principle, `#show quote: set block(breakable: false)` should have worked, but it doesn't, because the attribution is for some reason not part of the internal block. That's a bug.

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Happens to already be fixed because `pad` is now a block.

**Comment by laurmaedje** [comment]
I wanted to still move the block, but turns out it's a bit of a problem because it will shrink to fit automatically.
