### ISSUE TITLE
dot.double, dot.triple and dot.quad missing from accent documentation

### ISSUE THREAD

**Issue by Enivex** [typst/typst#425]
Recently these were added https://github.com/typst/typst/commit/766d1be72b046c1ee0db2602d8573b206fa81fe5, and they do work with the accent() function, but they're not listed under https://typst.app/docs/reference/math/accent/

**Comment by jianm-xs** [comment]
> Recently these were added [766d1be](https://github.com/typst/typst/commit/766d1be72b046c1ee0db2602d8573b206fa81fe5), and they do work with the accent() function, but they're not listed under https://typst.app/docs/reference/math/accent/

They already exists in [General](https://typst.app/docs/reference/symbols/sym/?query=dot.tu).
So we can close this issue. @laurmaedje

**Comment by Enivex** [comment]
> > Recently these were added [766d1be](https://github.com/typst/typst/commit/766d1be72b046c1ee0db2602d8573b206fa81fe5), and they do work with the accent() function, but they're not listed under https://typst.app/docs/reference/math/accent/
> 
> They already exists in [General](https://typst.app/docs/reference/symbols/sym/?query=dot.tu).
> So we can close this issue. @laurmaedje 

That's a misunderstanding of what the issue is about.
