### ISSUE TITLE
[bug] Math delimiters break when math font is changed

### ISSUE THREAD

**Issue by tapyu** [typst/typst#4254]
### Description

```typ
#show math.equation: set text(font: "Comic Sans MS")
#set align(top+left)
$ { x mid(|) sum_(i=1)^n w_i|f_i (x)| < 1 } $
```
![image](https://github.com/typst/typst/assets/22801918/f85bb2e1-c074-4a26-8c6c-39d27a713c93)

Any math equation font but the default one will break the correct math delimiter, which should produce

![image](https://github.com/typst/typst/assets/22801918/54152dde-684c-4e84-a172-8ebc400b70c3)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
Comic sans is not a math font

**Comment by laurmaedje** [comment]
I wonder why the first brace is scaled up at all without a math font ... maybe some weird fallback

**Comment by Enivex** [comment]
> I wonder why the first brace is scaled up at all without a math font ... maybe some weird fallback

I think this has come up before, and iirc it turned out that the font has a very minimal (broken) math table.

Though it could very well be that I misremember

**Comment by tapyu** [comment]
@Enivex I am sorry, I didn't know that, but `"Fira Math"` is a math font, correct? And the bug persists

![image](https://github.com/typst/typst/assets/22801918/cc1104fe-ff70-4b65-982c-d1e6d0790667)

**Comment by Enivex** [comment]
> @Enivex I am sorry, I didn't know that, but `"Fira Math"` is a math font, correct? And the bug persists
> 
> ![image](https://github.com/typst/typst/assets/22801918/cc1104fe-ff70-4b65-982c-d1e6d0790667)
> 

Fira Math is definitely a math font, but that's not Fira Math. Are you sure you have the font installed?
