### ISSUE TITLE
Highlighting does not work within math mode

### ISSUE THREAD

**Issue by freddyholms** [typst/typst#4259]
### Description

When I write `$a = #highlight[b]$`, Typst displays the same thing as if I had written `$a = b$`. I think it should be highlighting the math glyph for b and keeping its font face. This would be useful when drawing attention to special terms in equations.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
https://github.com/typst/typst/issues/2200
