### ISSUE TITLE
leading / in a path

### ISSUE THREAD

**Issue by ondohotola** [typst/typst#426]
Neither of the following

```
#let results = csv("/Users/el/Desktop/file.csv")
#let results = csv("~/Desktop/file.csv")
```

work, but the following does:

```
#let results = csv("//Users/el/Desktop/file.csv")
```

which I would not consider a feature :-)-O

Intel iMac 12.6.3, typst b934a2fd

Gruss aus dem Süden

**Comment by user202729** [comment]
Duplicate of #219

**Comment by ondohotola** [comment]
Apologies.

Gruss aus dem Süden
