### ISSUE TITLE
strong changes font size of previous text

### ISSUE THREAD

**Issue by abbcccddddeeeeeffffff** [typst/typst#4261]
### Description

Thanks a lot for creating typst!
Today I ran into an issue where lowercase g and the lowercase smallcapst (but not the normal ones) and probably some more letters change their size when followed by some **\*strong\*** content.
When zooming in a bit (firefox, 280%), the uppercase letters have a different size instead.

Minimal example I used to create the example PDF:
```
#set page(height: 200pt, width: 350pt) // for easier comparison, no effect on issue

*GgGg TtTt #smallcaps("TtTt")* // the size of the g

// here could be any content, doesn't seem to affect issue
// note: only some letters create this issue, e.g. "o" and "c".
// with e.g. "a", everything looks normal
*a*
```
My expectation was that both files should only differ in the single letter at the end, not the style of the text before that.
[a.pdf](https://github.com/typst/typst/files/15447350/a.pdf)
[o.pdf](https://github.com/typst/typst/files/15447352/o.pdf)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
I can't reproduce this, the PDFs look identical to me, even in Firefox.

**Comment by abbcccddddeeeeeffffff** [comment]
Huh. You're right, on my second device it looks fine. Sorry for not double checking before
