### ISSUE TITLE
Add hint to type errors related to shadowed built-in names

### ISSUE THREAD

**Issue by PgBiel** [typst/typst#4263]
### Description

Some errors, especially type errors, can be trivially connected to an accidentally overridden built-in name, as seen in https://github.com/typst/typst/issues/3176, or more recently in a Discord support thread[^1]. For example, if you write

```typ
#let image = "something"

// later

#image("file.typ")
```

You will get an error message saying that `image` should have been a function if we wanted to call it, but it's actually a string. However, this only happened because it's a built-in function used very often, so we expected it to be callable.

Therefore, I propose such errors (whichever errors we can unambiguously trace back to the wrong usage of a shadowed built-in name, so, mostly type errors) include, as a hint, that they have overridden the built-in name, and may wish to either use the new `std.image` syntax, or rename their variable which is shadowing the built-in name.

Of course, this can produce a few false-positives, but I think the overall benefit might outweigh that rare chance, especially because it is only a hint to an error (the error happens and the compilation is interrupted regardless). In addition, it'd be nice to have this hint for packages' functions too (or, more generally, any shadowed functions), but that'd be much harder to implement in an unambiguous and consistent way, so I think implementing this only for shadowed built-in functions and types might be enough for now.

[^1]: https://discord.com/channels/1054443721975922748/1088371919725793360/1244335344778870785

### Use Case

It can be pretty easy to forget you shadowed a built-in name at the top of your file after writing a lot of stuff under it, so I think this could be helpful.

**Comment by laurmaedje** [comment]
How so? Can't we still look at the identifier for the error span and check it against the std scope?

**Comment by bluebear94** [comment]
You’re right. Almost forgot about that.

**Comment by Andrew15-5** [comment]
> use the new `std.image` syntax

There is a new syntax?

**Comment by PgBiel** [comment]
> > use the new `std.image` syntax
> 
> There is a new syntax?

See: https://github.com/typst/typst/pull/4038

**Comment by Andrew15-5** [comment]
Wait, it's not in the v0.11.1? The release was 12 days ago, but the merge was last month.

**Comment by PgBiel** [comment]
v0.11.1 was a patch release and only included bug fixes.

**Comment by Andrew15-5** [comment]
Ohh, it has a separate commit history, that explains it.

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/4402
