### ISSUE TITLE
floor and ceiling symbols missing from `sym`

### ISSUE THREAD

**Issue by tilman-schieber** [typst/typst#4265]
### Description

I expected to find floor and ceiling symbols in the `sym` module.

### Use Case

while the symbols can be generated with `floor(x)` and `ceil(x)` it would be useful to access them directly via `sym`.
e.g. `floor.l   floor.r   ceil.l   ceil.r`

**Comment by Coekjan** [comment]
If we define `floor.l`, it currently conflicts with `floor` in `math` scope. (See line 188 & 210 below).

https://github.com/typst/typst/blob/1694327b707621454606d7c3ffd0ed7f603d87e9/crates/typst/src/math/mod.rs#L159-L214

**Comment by Coekjan** [comment]
Maybe we can define `bracket.floor.{l,r}`, `bracket.ceil.{l,r}` to represent them, then there will be no conflicts.

**Comment by Coekjan** [comment]
With #4299 , we are allowed to define `floor.{l,r}` and `ceil.{l,r}` with no conflicts with `floor` and `ceil` functions.
