### ISSUE TITLE
Duplicate PDFs being generated

### ISSUE THREAD

**Issue by gwlester** [typst/typst#427]
Given the following commands:
`
$ typst src/reports/MyReport.typ   /tmp/MyReport.pdf
`
Then identical copies of MyReport.pdf file are generated in:

1. src/reports/
2. /tmp/

**Comment by ondohotola** [comment]
I cann not reproduce on my Intel iMac 12.6.3 with `typst b934a2fd`

**Comment by gwlester** [comment]
I'm running on Ubuntu ().  I pulled the sources for v23-03-28 (5248cd6) and built it (the Linux prebuilt complained on my machine about the version of GC libraries that are installed).  I'm using bash as my shell (although I don't see how that is causing this).

**Comment by laurmaedje** [comment]
Do you use the Typst LSP? This could be causing the version in `src/reports/` to appear.

**Comment by gwlester** [comment]
@laurmaedje  -- as noted above, I had to pull and build it myself.  Not sure what "Typst LSP" is.

**Comment by Dherse** [comment]
Do you have a Typst extension for VSCode or another editor? those pull in an LSP server which duplicates the build of PDF files, in VSCode (at least) you can disable this (annoying) behaviour :)

**Comment by laurmaedje** [comment]
I cannot reproduce this.

**Comment by jwhear** [comment]
Unable to repro on Fedora 37, typst built from source (tag v23-03-28); no LSP, VSCode, etc.
