### ISSUE TITLE
[documentation] List function elements

### ISSUE THREAD

**Issue by tapyu** [typst/typst#4270]
In

https://typst.app/docs/reference/foundations/function/#element-functions

It could be interesting to list all element functions. This would make easier for the user to understand what functions are, in fact, an element function. I tried to find the markup file from where this part is rendered, but I didn't find :(

**Comment by Andrew15-5** [comment]
https://github.com/typst/typst/blob/b73b3ca33521a4f4546e14b788a8de227602f947/crates/typst/src/foundations/func.rs#L54

**Comment by the-sinner** [comment]
Hi, i think we can use the below search string to find all element functions: 
`repo:typst/typst /^#\[elem/ path:/^crates\/typst\/src\//`

[Github Code Search](https://github.com/search?q=repo%3Atypst%2Ftypst+%2F%5E%23%5C%5Belem%2F+path%3A%2F%5Ecrates%5C%2Ftypst%5C%2Fsrc%5C%2F%2F&type=code)

**Comment by laurmaedje** [comment]
Every function specifies whether it is an element function at the top, next to its name. Listing all of them would be a very long list that closely resembles the docs sidebar, so I'm not sure it makes sense.
