### ISSUE TITLE
Extra space is added when a line is broken at the beginning of an inline equation

### ISSUE THREAD

**Issue by Victor-Boone** [typst/typst#4278]
### Description

The issue is especially visible when paragraphs are justified.
If a line breaks just before an inline equation, a extra blank space is added.

The following code:

```typst
#set page(width: 10cm, margin: (left: 1cm, right:1cm))
#set par(justify: true)

#lorem(10)
#lorem(5) aaaaa $a = c + b$ 
#lorem(10)
```

is rendered as (a line has been added to make it more apparent):

![align-issue](https://github.com/typst/typst/assets/97682713/9bde9097-5220-4024-9e2c-7ebcdf5cf2d1)

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by bluebear94** [comment]
The results of the linebreaking algorithm for this example:

```
"Lorem ipsum dolor sit amet, consectetur adipiscing"
"elit, sed do. Lorem ipsum dolor sit amet. aaaaa \u{2066}"
"￼ ￼ ￼\u{2069} Lorem ipsum dolor sit amet, consectetur"
```

**Comment by laurmaedje** [comment]
This seems to be a 0.11.1 regression due to LRI (Left-to-right Isolate) preventing the end-of-line trimming.

**Comment by Enivex** [comment]
While this is a regression, I'd like to add that typically it's desirable to use non-breaking space in front of inline math.

**Comment by bluebear94** [comment]
It seems that in `typst::layout::inline::line`, we need to strip the trailing space of the last text item whenever it’s followed only by ‘ignorable’ elements instead of requiring it to be the last item that intersects the range (as returned by `Preparation::slice`).
