### ISSUE TITLE
Interaction with environment variables

### ISSUE THREAD

**Issue by ondohotola** [typst/typst#428]
In addition but separate to issue [#426](https://github.com/typst/typst/issues/426) I can not find any reference to whether typse can access environment variables.

I would obviously like some form of

```
#let results = csv("$HOME/Desktop/file.csv")
```

or even (given `MYCSV="$HOME/Desktop/file.csv"` having been exported by BASH) something like

```
#let results = csv(env::var("MYCSV"))
```

but I have of course not clue about RUST.

Gruss aus dem Süden

**Comment by user202729** [comment]
Duplicate of #295 . Probably won't be supported.
