### ISSUE TITLE
Caligraphic uses Latin Modern Font

### ISSUE THREAD

**Issue by yardenas** [typst/typst#4283]
### Description

I am trying to use caligraphic letters in typst, and for some reason the used font does not get shown.
For example, for the following code:

```
#show math.equation: set text(font: "New Computer Modern Math")

$cal(S)$
```
I get
![image](https://github.com/typst/typst/assets/29047534/b7d0a3de-1657-4e29-81cd-bb649c627d5f)

While I expect to get (from Latex)
![image](https://github.com/typst/typst/assets/29047534/f6425164-2903-445f-9246-4fddde4c00db)

I'm 95% sure I'm just missing something, but couldn't find a solution here or in the docs.

### Reproduction URL

https://typst.app/project/pkQ8uEGquEb4DKK7KRcQkw

### Operating system

Web app

### Typst version

- [x] I am using the latest version of Typst

**Comment by Enivex** [comment]
New Computer Modern Math is based on Latin Modern Math, and therefore has some differences from the original Type 1 font. This is not a bug. You would see the same thing if you compiled your LaTeX document using unicode-math and the same font.

**Comment by yardenas** [comment]
@Enivex , thank you for the (very!) prompt response. Any idea how to use the original Type 1 font?

**Comment by Enivex** [comment]
> @Enivex , thank you for the (very!) prompt response. Any idea how to use the original Type 1 font?

You cannot. Type 1 fonts have been deprecated, and typst will never support them.

**Comment by yardenas** [comment]
Thank you!
