### ISSUE TITLE
Support clipping content

### ISSUE THREAD

**Issue by birktj** [typst/typst#429]
As far as I can see from the code and the documentation there is currently no support for clipping content. At a minium the ability to clip content to be inside a `block` or `box` would be very useful in many cases.

I propose adding a `clip` field to `block` and `box` that when set to true will clip the content to be inside these.

**Comment by laurmaedje** [comment]
Yeah, the clip field is also how I would implement this. Adding the field is the easy part though, clipping would also need to be integrated with text and SVG rendering.

**Comment by tmbb** [comment]
This isn't available in the release version yet, is it?

**Comment by laurmaedje** [comment]
> This isn't available in the release version yet, is it?

It is already available. Note that the currently clipping is always rectangular though, it does not take into account the corner radius.
