### ISSUE TITLE
Text spacing inside equations incorrect

### ISSUE THREAD

**Issue by Zeta611** [typst/typst#4295]
### Description

I've noticed that text spacing inside equations is incorrect:
```typst
$
  text("maximize")   & ∫ φ(𝒁_j) ln q_j (𝒁_j) dif 𝒁_j \
  text("subject to") & ∫ q_j (𝒁_j) dif 𝒁_j = 1 \
$
```
results in

![Screenshot 2024-05-30 at 13 44 42](https://github.com/typst/typst/assets/9553691/8e5ba9dd-d9f9-4ef3-9dd5-c7d8bf901341)

Note the spacing between "b" and "j" of "subject"; They need to be closer together. Am I doing something wrong? How can I fix this?

The spacing inside text body is fine---they are tighter.

I'm using Linux Libertine with Libertinus Math.

(I asked for help [here](https://www.reddit.com/r/typst/comments/1d2jv4w/text_spacing_inside_equations_incorrect/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) but this seems like a Typst bug)

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
> The spacing inside text body is fine---they are tighter.

Maybe try use Libertinus Math in text mode and see the result?

**Comment by Zeta611** [comment]
@Enter-tainer I thought using `text("subject to")` would use the text font Linux Libertine rather than the math font Libertinus Math. Is this not the case?

**Comment by PgBiel** [comment]
You will need to `#text(font: "Linux Libertine")[stuff]` manually to use your document's text font in math mode for now.

See also #1125

**Comment by Zeta611** [comment]
That's my bad! I thought it would work like `\text` (as you mentioned in the linked issue). Thank you for clarifying.
