### ISSUE TITLE
`box()` consumes trailing spaces

### ISSUE THREAD

**Issue by owiecc** [typst/typst#4298]
### Description

```typst
#box("AB        ")C \
#box("A        B")C \
#box("        AB")C \
```

<img width="125" alt="Screenshot 2024-05-30 at 13 19 37" src="https://github.com/typst/typst/assets/6896639/16eedd67-8cd2-4b93-88e9-acfc0450c330">

As a consequence `box(" ")` and `box([ ])` collapses to nothing. Leading spaces are preserved, that is why I assume this a bug. 

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
https://github.com/typst/typst/issues/597
