### ISSUE TITLE
The show rule for "-\d+" does not work.

### ISSUE THREAD

**Issue by YouXam** [typst/typst#4320]
### Description

The `show` rule for `-\d+` does not seem to function as expected.

<img width="623" alt="图片" src="https://github.com/typst/typst/assets/49866772/f8a83d5e-266f-427b-9707-d2e4730c1470">

Specifically, the following rule:
```typst
#show "-123": text("-bar", fill: purple)
```
does not work for `-123`, but it does work for `x-123`.

In contrast, the following rule:
```typst
#show "+123": text("+bar", fill: blue)
```
works for both `+123` and `x+123`.

#### Investigation
Upon printing the parsed syntax tree, I observed that `-123` (where the minus sign is preceded by the start of the line or whitespace) is parsed as:
```
Shorthand: "-"
Text: "123"
```

This parsing behavior appears to prevent the `show` rule from being applied correctly.

Is this behavior intentional, or is it a bug in the parser that affects the `show` rule?

### Reproduction URL

https://typst.app/project/rIMnhgS2b20Yg2x9u2ypF2

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
This is tracked by #86.
