### ISSUE TITLE
Separate fallback for raw text / code and other text

### ISSUE THREAD

**Issue by Yuxiza** [typst/typst#4321]
### Description

# Problem Description

Now, the display of a lot of unicode characters depends on fallback. If I use `#set text(fallback: false)` for a more rigorous inspection, this charaters which dose not support by mono sans will throw a "tofu" rectangle. What's more, the fallback font is uncontrollable.

for example:

````typ
#set text(fallback: false)

```python
print("测试👀")
```

#set text(fallback: true)

```python
print("测试👀")
```

#set text(font: "Microsoft YaHei")

```python
print("测试👀")
```
````

The first raw text in the above code doesn't render properly, and the next two paragraphs are displayed in "LiSu" on my computer. "LiSu" is not a commonly used font, especially in code. The font settings in `#set text` don't work for rawtext, but fallback does.

![da8045c819eaf81f1e555f481ca0a676](https://github.com/typst/typst/assets/87649577/b743a934-6bc4-4561-b8df-3bf7458b3bf0)

# Possible Solution

Separate fallback for raw text / code and other text, and provide a way to set the font of the raw text / code (at least, able to set the fallback font)

I'm not sure this is best practice, but I do think we should do something to change this.

### Use Case

Output and comments in code. Some program languages also natively support utf-8 variables, such as rust.

**Comment by Enter-tainer** [comment]
> provide a way to set the font of the raw text / code

you can already do that.

**Comment by Enter-tainer** [comment]
#show raw: set text(font: "Fira Code")

**Comment by Yuxiza** [comment]
thanks, @Enter-tainer. 
For anyone who has the same problem, the following code renders fine
````typ
#show raw: set text(font: ("Fira Code", "STSong","Segoe UI Emoji"))

#set text(fallback: false)

```python
print("测试👀")
```

#set text(fallback: true)

```python
print("测试👀")
```
````
