### ISSUE TITLE
Figure numbers are reused in figure's caption

### ISSUE THREAD

**Issue by josephg** [typst/typst#4322]
### Description

I'm running into a bug where my figures are all assigned the same number. In the test case below, I end up with multiple figures labelled as "Figure 3":
![image](https://github.com/typst/typst/assets/47413/4eb99c52-3843-43d0-a365-3e05d999a03e)

The bug only seems to show up when the following conditions are met:

- All figures have `placement: top`
- I have a custom `show` rule on `figure.caption`
- The figures are pushed to the top of the next page. (For example, if a `#pagebreak` happens immediately before the figures are added to the document, numbering works correctly.

References to the figures are unaffected. Only the figure's caption text seems to be affected by this bug.

The code below reproduces the problem. 3 figures on page 2 are incorrectly numbered. (They're all labelled as "Figure 3")

I've reproduced this problem on both typst 0.11.1 from cargo and the at-time-of-writing current development version (23746ee1), also installed from cargo.

[Reproducing test case](https://typst.app/project/ragK3DAE-Tw2wghLZMmFVs):

```typst
#show figure.caption: it => [
  #it.supplement #it.counter.display(it.numbering):
  #it.body
]

The next page of this document contains figures @fig-1, @fig-2 and @fig-3.

// The bug only shows up on page 2+ for some reason.
// This is a placeholder to force the subsequent figures onto the next page.
#rect(width: 30%, height: 650pt)

#figure(
  text(8pt, rect(width: 30%, height: 30pt)),
  caption: [ Should be figure 1! ],
  placement: top,
) <fig-1>

#figure(
  text(8pt, rect(width: 30%, height: 30pt)),
  caption: [ Should be figure 2! ],
  placement: top,
) <fig-2>

#figure(
  text(8pt, rect(width: 30%, height: 30pt)),
  caption: [Should be figure 3],
  placement: top,
) <fig-3>
```

cc @ept

### Reproduction URL

https://typst.app/project/ragK3DAE-Tw2wghLZMmFVs

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Likely similar to https://github.com/typst/typst/issues/2480

**Comment by laurmaedje** [comment]
Okay, so this is actually very different from #2480. The problem is that the figure counter is already stepped in-flow, independently of the floating figures, but the `counter.display(it.numbering)` displays the counter _at the current location_ rather than at the figure's location. The `figure.caption` show rule doesn't provide location context, so `counter.display` runs into the compatibility behaviour of displaying at the current location. The internal code uses the  `figure_location` field stored in the caption to display the counters, but it isn't exposed at the moment ...

**Comment by laurmaedje** [comment]
Minimized into the test format for future convenience:
```typ
--- issue-4322-figure-number ---
#set page(height: 70pt)
#set figure(placement: top)
#show figure.caption: it => [
  #it.supplement
  #it.counter.display(it.numbering):
  #it.body
]

#let f = figure(
  text(8pt, rect(width: 30%, height: 30pt)),
  caption: [...],
)

@fig-1 \
@fig-2 \

#f <fig-1>
#f <fig-2>
```

**Comment by EpicEricEE** [comment]
Not sure if this is a separate issue, but something related broke at some point on main, as the counter value now isn't up-to-date for placed figures, even when they are placed at the bottom (and thus after the counter update in the flow):

<table>

<tr>
<th>Code</th>
<th>v0.11.1</th>
<th>Main</th>
</tr>

<tr>
<td>

```typ
#show figure.caption: it => {
  let num = context it.counter.display()
  [#num.~#it.body]
}

#figure(
  rect(),
  placement: bottom,
  caption: [First in order]
)

#figure(
  circle(),
  placement: none,
  caption: [Second in order]
)

#figure(
  square(),
  placement: bottom,
  caption: [Third in order]
)
```

</td>

<td>

![image](https://github.com/user-attachments/assets/e42d3450-7b73-4d05-a352-496f9730f8bb)

</td>

<td>

![image](https://github.com/user-attachments/assets/6879784b-f0de-4a4f-a183-796937103dbc)

</td>
</tr>

</table>

**Comment by laurmaedje** [comment]
If there is a regression, please open a separate issue.
