### ISSUE TITLE
Issue with PDF Outline and Bookmark Exporting

### ISSUE THREAD

**Issue by auwjong22** [typst/typst#4336]
### Description

I found that the PDF's outline or bookmark exporting does not work correctly.

I used this simple snippet for testing:
```
#outline()
#heading[Normal heading]
This heading will be shown in
the PDF's bookmark outline.

#heading(bookmarked: false)[Not bookmarked]
This heading won't be
bookmarked in the resulting
PDF.
```

I tested this on my computer (`typst==0.11.0`) and could not see any bookmarks using MacOS's Preview application. I also used a web app to export the PDF, and it did not work as well.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Coekjan** [comment]
Cannot reproduce this issue. Could you please upload the PDF file you exported?

**Comment by Enivex** [comment]
@auwjong22 did you test this in anything other than Preview?

**Comment by auwjong22** [comment]
> @auwjong22 did you test this in anything other than Preview?

I tested it on Chrome and discovered the issue was actually with the Preview application. Sorry for the confusion. I'll go ahead and close the report.
