### ISSUE TITLE
`set document()` resets `set page()` (paper size, fill) on the last empty page

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#4340]
### Description

If I set `set document(author: "")` before `set page(paper: "presentation-16-9", fill: gray)` then the last page *if empty* will have paper size set to A4.

```typ
#set document(author: "")
#set page(paper: "presentation-16-9", fill: gray)
text
```

So, if I do

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Dherse** [comment]
Is this on main or in the latest release? I just tried on the webapp and it looks good.

**Comment by Andrew15-5** [comment]
Latest release (`typst 0.11.1 (786457e3)`).
