### ISSUE TITLE
RFC : reserve self to have special meaning

### ISSUE THREAD

**Issue by astrale-sharp** [typst/typst#4343]
### Description

Currently self already has a special meaning, calling `#datetime.day()` forgetting to call `today` to get an instance, you get the error `missing argument: self` which can be puzzling for beginners.

By forbidding self for variable names, function parameters etc on the user side, we get to treat self as a special case and add a hint for the above case and potentially others.

Furthermore if/when typst gets custom types with constructors, instancing etc, self could be used with a special meaning there as well.

The earlier this breaking change the better.

Note : If we don't forbid the use of self, a hint to "get an instance" could be applied to user functions with self as a parameter which would be non sensical

**Comment by JamesxX** [comment]
> Note : If we don't forbid the use of self, a hint to "get an instance" could be applied to user functions with self as a parameter which would be non sensical

this is a far better solution imo

**Comment by JamesxX** [comment]
`self` is an incredibly common variable name, so it would be quite a breaking change. It's easier to just improve that specific error message (which I believe is probably in the works shortly when they revamp the error messages)

**Comment by Enter-tainer** [comment]
@Orangex4 afaik https://github.com/touying-typ/touying heavily use `self`

**Comment by mmlb** [comment]
`self` is not a keyword in python and can be used for other things than referring to the instance, it's probably looked down upon heavily though.

```ShellSession
$ bpython
bpython version 0.24 on top of Python 3.11.9 /nix/store/6b1fqdwb3g56j5pazv8zkx9qd0mv3wiz-python3-3.11.9/bin/python3.11
>>> self = 3
>>> print(self)
3
>>> class Foo():
...     def blah(notself, self):
...         print("notself:", notself)
...         print("self:", self)
... 
>>> Foo().blah(42)
notself: <__main__.Foo object at 0x7f0b8d3a19d0>
self: 42
```

**Comment by laurmaedje** [comment]
I think we can improve the error message `missing argument: self` (it is quite obtuse), but I see no reason to reserve `self` at this point. Currently, there is no real distinction between methods and functions[^1] (method calls are just sugar) and I think that's quite nice.

[^1]: Mutable methods are a small exception, but only exist on arrays and dictionaries.
