### ISSUE TITLE
Incorrect display of cases

### ISSUE THREAD

**Issue by DanuulKa03** [typst/typst#4347]
### Description

Code where the error occurs:
```typst
$u/p = cases(1 & a "- квадратичный остаток", -1 & a "- не квадратичный остаток", 0 & "если" p/a "без остатка")$
```
Photo of the error:
![image](https://github.com/typst/typst/assets/80038887/5f3c96e5-0c21-44d9-b377-35e84219134b)

For some reason, typst does not align the text after the & sign correctly. I highlighted in red what doesn't work that way.

### Operating system

Web app

### Typst version

- [x] I am using the latest version of Typst

**Comment by bluebear94** [comment]
This looks like a bug with spacing between the columns, rather than with alignment.

**Comment by DanuulKa03** [comment]
@bluebear94 Did I somehow write the code wrong? If so, please tell me what I need to change.

**Comment by bluebear94** [comment]
No, I don’t think so. Upon further investigation, it seems to happen only when a case has its second column start with a math expression.

**Comment by DanuulKa03** [comment]
oh yes, you're right, I just did -1 -> "-1" in quotes and everything became fine).
![image](https://github.com/typst/typst/assets/80038887/4669608a-1827-41fa-aec1-4d3ef9880fd6)

**Comment by Enivex** [comment]
That's going to render the minus sign as a hyphen, so I'd suggest adding a manual space after instead

**Comment by MDLC01** [comment]
Alignment points don't add any additional spacing. I think this is actually working as intended, even though it might not be what you would want in this specific instance. For this reason, I would consider this a special case of #1767.

**Comment by Enivex** [comment]
I'll concur
