### ISSUE TITLE
DPI-based image scaling / Respect image size

### ISSUE THREAD

**Issue by pklaschka** [typst/typst#436]
For elements like diagrams (loaded as images), it's good to have a consistent look where the font size matches the document. However, while I (very much!) appreciate the default behavior where `image()` doesn't just spit out a ginormous oversized image for photos (like LaTeX does it 😉 ), there currently seems to be no way to "opt-out" of that autoscaling behavior for cases like the one described above.

While one could argue that I can use the dimensions of the diagram once I've drawn it, there are better solutions than that as, at least for me, diagrams tend to change a lot while writing, which can also change the diagram dimensions.

## Option 1: Supporting this natively

In addition to allowing to specify `width` and `height`, alternatively, allow sizing of the image based on a `dpi` / `ppi` / `px/inch` / whatever we want to call it (from now on, I'll refer to it as dpi for simplicity sake) value from which the image size gets determined. Then, the resulting width of the image would be its native width divided by the specified image resolution (e.g., 300 "dpi" or whatever) in `inch` (e.g., $\frac{2000\text{px}}{300 \text{dpi}} = 6.66 \text{in}$).

## Option 2: Supporting loading image metadata, enabling custom functions to support this functionality

Similar to how CSV, JSON, and XML data can get imported, support importing `image_metadata` (that could include the image's native/preferred dimensions and possibly even more), with which custom functions to support the use-case specified above (and more) could be implemented. 

Considering that the workflows preferred by different teams can differ (and that typst seems to, which I'm excited about, also focus on the developer experience of writing custom functions), I think this option would probably be even better (since if we could "import" the image's width and know the pixel density, writing a custom function to achieve the use-case should be pretty easy).

---

While it feels like a small thing, this would be a severe UX improvement for including diagram graphics (at least to me, but also generally).

Grüße aus Würzburg 🙂

**Comment by 4cq2** [comment]
you can get some data already:

~~~
#let avatar = image("bluetj-avatar.jpg")

#style(styles => {
   measure(avatar, styles).width
})
~~~

**Comment by laurmaedje** [comment]
> What would be needed to achieve the problem I described above would be to get to know the image file's width, not the width the element takes up on the page (which is always the full width, independent of the image resolution).

By default measurement happens in an infinite space. And if the space is not bounded, the image defaults to 1pt per 1px. So this _should_ provide the pixel width (I haven't tested it).

**Comment by 4cq2** [comment]
https://github.com/typst/typst/issues/279

**Comment by 1268** [comment]
well since my issue was just closed, I am just gonna repost my comments here, since I dont think this issue gives a good demonstration of the problem. using this image:

https://typst.app/assets/images/bluetj-avatar.jpg

and this markup:

~~~
#let avatar = image("bluetj-avatar.jpg")

#style(styles => {
   measure(avatar, styles).width
})

#avatar
~~~

Typst reports the image is 128pt, but the image now takes the full width of the output, minus margins:

https://github.com/typst/typst/files/11066857/typst.pdf

and it is blurry from being upscaled.

**Comment by 1268** [comment]
compare LaTeX with the same image:

~~~tex
\documentclass{article}
\usepackage{graphicx}
\begin{document}
   \includegraphics{bluetj-avatar.jpg}
\end{document}
~~~

result:

https://github.com/typst/typst/files/11066860/latex.pdf

compare HTML with the same image:

~~~html
<img src="https://typst.app/assets/images/bluetj-avatar.jpg">
~~~

result:

<img src="https://typst.app/assets/images/bluetj-avatar.jpg">

**Comment by maxnoe** [comment]
I was about to open a similar issue.

My proposal is to add an argument `scale` to `#image`, which would use the image metadata to include the image at its native size, optionally scaled, e.g.:

```
#image("test.jpg", scale: 100%)
```

**Comment by cristobaltapia** [comment]
I also support this. In the meantime I can achieve this with the following function (only for svg images):

```typst
#let image_plus(p, scale: 1) = {
  let a = read(p)
  let m = a.match(regex("width=\"(\d*\.\d*)\""))
  let size = float(m.at("captures").at(0))
  let w = scale * size * 1pt
  image(p, width: w)
}
```

Which can then be used as
```typst
#image_plus("path/to/image.svg")
```

Works for me at least :)

**Comment by ChihHao-Su** [comment]
> I also support this. In the meantime I can achieve this with the following function (only for svg images):
> 
> ```typst
> #let image_plus(p, scale: 1) = {
>   let a = read(p)
>   let m = a.match(regex("width=\"(\d*\.\d*)\""))
>   let size = float(m.at("captures").at(0))
>   let w = scale * size * 1pt
>   image(p, width: w)
> }
> ```
> 
> Which can then be used as
> 
> ```typst
> #image_plus("path/to/image.svg")
> ```
> 
> Works for me at least :)

There's a bug fix: the regex should be:
```
"svg\s+width=\"(\d*\.\d*).*?\""
```

The original regex can match string like `stroke-width="1.35"` accidentally, and it doesn't work for width with unit, like `<svg width="688.522px`.

The fixed version would be:
```typst
#let svg_scaled_by_ratio(p, scale: 1) = {
  let a = read(p)
  let m = a.match(regex("svg\s+width=\"(\d*\.\d*).*?\""))
  let size = float(m.at("captures").at(0))
  let w = scale * size * 1pt
  image(p, width: w)
}
```

**Comment by cristobaltapia** [comment]
@ChihHao-Su thanks for pointing that out :) . I had realized that but forgot to update it here.

**Comment by laurmaedje** [comment]
I'm closing this due to https://github.com/typst/typst/pull/3571. By default, images now don't upscale anymore, they only downscale as to not exceed the available space. The new approach extracts the DPI metadata from the image and uses that to scale the image to its natural size. In combination with measure, this can also be used to determine the true physical size of the image.

**Comment by Andrew15-5** [comment]
> they only downscale as to not exceed the available space.

Here is a workaround for that (to allow big natural-size images): https://github.com/typst/typst/pull/3571#issuecomment-1983791852.
