### ISSUE TITLE
Ligatures for text operators

### ISSUE THREAD

**Issue by Ventu06** [typst/typst#4360]
### Description

Font ligatures are completely disabled in math mode: this currently also applies to text operators. I'm not sure if this is a bug or intended behavior, but I think that text operators in math mode should have ligatures.

### Use Case

There are two main examples where having ligatures in math mode is relevant.

- In the code `$ f "is an affine function" $` the `"is an affine function"` part is effectively text, so it should behave as such (whereas in this case the two adjacent `f` would not be ligated).
- The absence of ligatures makes italic text operators particularly ugly, e.g. `op(italic("Diff"))`.

**Comment by Enivex** [comment]
See https://github.com/typst/typst/issues/366

**Comment by ZornAC** [comment]
> See #366

That is a completely different issue though. @Ventu06's post does not ask for text operators to use text font, and the thread you're referring to never mentions ligatures.

Compare the behavior of `math.op` with LaTeX's `\operatorname`: the latter uses math font but does add ligatures, so stuff like the example of the original post (`\operatorname{\mathit{Diff}}` in LaTeX) gets displayed nicely. Typst, on the other hand, displays it as if the letters making up the word were all separated variables.

**Comment by ZornAC** [comment]
> The issue I linked is at the heart of this. Latex uses the text font for many more things than you might think. Largely because math fonts aren't intended for use with long runs of characters.

I see. Will the issue of italic operators remain unsolved then, or is `op` going to fall back to text font in the future?

**Comment by Enivex** [comment]
> > The issue I linked is at the heart of this. Latex uses the text font for many more things than you might think. Largely because math fonts aren't intended for use with long runs of characters.
> 
> I see. Will the issue of italic operators remain unsolved then, or is `op` going to fall back to text font in the future?

I have no reason to think it won't change at some point in the future.

That being said, you can work around it already today by explicitly introducing a `#let mtext = text.with(font: "text font name here")` function, and using this one whenever writing text inside math.
