### ISSUE TITLE
Transparency leak in PDF

### ISSUE THREAD

**Issue by EpicEricEE** [typst/typst#4361]
### Description

The transparency of text or shapes can leak into subsequent images in PDF as the external graphics state is not reset properly. 

```typ
#rect(fill: red.transparentize(50%))
#image("image.png", width: 45pt) // Image of yellow rectangle
```

| PDF (Chrome) | Preview |
| --- | --- |
| ![PDF](https://github.com/typst/typst/assets/7191192/10fea108-9c9f-4807-97f0-d86f85524c2b) | ![Preview](https://github.com/typst/typst/assets/7191192/c81fe3f4-0757-41e3-9a4c-d5d79671c862) |

The yellow image inherits the transparency of the red rectangle in PDF but not in the preview.

_Tried with 0.11.1 on the webapp, and on main with f91cad7_

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Beiri22** [comment]
I just had the same problem; confusing...
