### ISSUE TITLE
The `open` CLI option can fail silently

### ISSUE THREAD

**Issue by jakobjpeters** [typst/typst#4386]
### Description

I'm creating a downstream application that uses the CLI. However, the `open` option fails most of the time. It seems likely that the cause of failure is on my machine, but the failure is difficult to debug because no error or warning is displayed. If I'm understanding the code correctly, it seems like potential errors are ignored on this [line](https://github.com/typst/typst/blob/ad4ef68a112dedabf80f885a02bcb574eb9af9e4/crates/typst-cli/src/compile.rs#L482). Could it instead display a warning message?

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by bluebear94** [comment]
Shouldn’t `open_file` call `open::{with_detached, that_detached}` instead of `open::{with_in_background, that_in_background}` to have the open process live even after Typst has exited?

**Comment by Coekjan** [comment]
> Shouldn’t `open_file` call `open::{with_detached, that_detached}` instead of `open::{with_in_background, that_in_background}` to have the open process live even after Typst has exited?

Not sure if it is intended that the pdf viewer should be a subprocess of typst and terminate when typst exits. If so, current behavior is wrong, no matter the `--open` flags is processed successfully or not.

---

I tested the `--open` flags locally (on linux):
1. `typst compile /path/to/typst/file --open`: opens the viewer (okular) and typst exits, **and the okular process is adopted by `systemd --user`**
2. `typst compile /path/to/typst/file --open $(which okular)`: same as No.1
3. `typst compile /path/to/typst/file --open /path/nonexistent`: **exit-code is 0**, but no viewer opened, as described in this issue
4. `typst compile /path/to/typst/file --open $(which git)`: same as No.3

**Comment by laurmaedje** [comment]
Prior art: https://github.com/typst/typst/pull/706

**Comment by jakobjpeters** [comment]
> Not sure if it is intended that the pdf viewer should be a subprocess of typst and terminate when typst exits.

@Coekjan Given that my failures were intermittent and your PR seems to have fixed them, would that mean that my machine is failing to hand off the default viewer process when Typst exits? This isn't a very important question, given you fixed it, but I am curious and don't know much about processes :)

**Comment by Coekjan** [comment]
> Would that mean that my machine is failing to hand off the default viewer process when Typst exits?

@jakobjpeters Maybe you can first investigate if the viewer process is created, through tools like `pstree`, `top` (or `htop`), etc.
