### ISSUE TITLE
Primes and subscripts interfere with each other

### ISSUE THREAD

**Issue by damaxwell** [typst/typst#439]
Unlike in TeX, primes and super/subscripts are treated differently from each other in Typst, and they interfere.  
```typst
$
y_3' quad y'_3
$
```
<img width="120" alt="image" src="https://user-images.githubusercontent.com/918465/228645412-4033d9d4-fbce-4119-9443-661876d6b283.png">

The 3 and the prime in both cases should be vertically aligned.

In TeX, the prime symbol is giant sized, and is then shrunk to make an actual superscript when used as a decorator.  Unicode math doesn't follow this approach: the prime is U+2032 and is small and already at the correct height to be a subscript for letters; double and triple primes are their own glyphs as well.  I think that Typst is simply inserting a U+2032 in all single prime circumstances, and hence a following subscript modifies the prime and not the thing the prime was modifying.

XeLaTeX with `unicode-math` enabled seems to use U+2023 and friends where it can, but also gets the interaction with subscripts correct.  It also has correct placement of a prime with a non-letter.  Compare:

Typst (note the low position of the prime with respect to the sum symbol)
```typst
$sum' x' A'$
```
<img width="120" alt="image" src="https://user-images.githubusercontent.com/918465/228648638-034b98a0-5fa6-4459-8e29-32d26e4fab8c.png">

XeLaTeX w/`unicode-math` (note the raised prime in proper superscript position with respect to the sum symbol)
```LaTeX
$\sum' x' A'$
```
<img width="120" alt="image" src="https://user-images.githubusercontent.com/918465/228649155-a99eb8e4-aa35-473a-a827-8402f0259758.png">

**Comment by steven-jh-yan** [comment]
Sorry, I'm not very knowledgeable, but can't you do `$y^prime_3$ $sum^prime_3$`? In LaTeX, another way of doing what you did is `$sum^{\prime}$`.

![Screen Shot 2023-03-29 at 11 04 59 PM](https://user-images.githubusercontent.com/68593406/228717937-174c5ef2-967d-40bd-b285-607ea9f6b6c1.png)

Obviously there's still a lot left to be desired in terms of the size of the prime and how close it's placed to the symbol. But for me the code above seems okay-ish.

**Comment by damaxwell** [comment]
Alas, the size of the prime is wrong with `$y^prime_3$`; this is a workaround, but is not the finely crafted typesetting that Typst should be capable of.

It turns out that for well-formed OTF math fonts, the `ssty` feature encodes script and script-script variations of glyphs for the different optical sizes.  For a prime in New Computer Modern Math, the base glyph is `/minute` and the alternates are `/minute.st` and `/minute.sts`.  The optical size variants are, in fact, full sized jumbo primes à la the original TeX approach.

The upshot is that `prime` should not insert a raw U+2032 but instead in insert a superscript where the content is U+2032 with a variant taking into account the level of scripting.  I looked at the output from XeLaTeX + unicode-math and this seems to be exactly the approach taken there.

I guess Typst doesn't currently use the `ssty` feature to take advantage of optical size info in the math font already.  I tried to turn it on manually for a single prime character but wasn't successful.  At any rate, a proper fix for the prime situation would probably involve also upgrading the math engine to (optionally) use `ssty` info automatically.

**Comment by Enivex** [comment]
This works fairly decently as a workaround for now 

`$y#box(width:0pt)[#text(top-edge: "ascender",bottom-edge: "descender")[$prime$]]_n$`

**Comment by matthiasGmayer** [comment]
Here's a workaround that works for now

#let prime = move(dx: 0.1em, dy: 0.35em, scale("\u{2032}", x:150%,y : 150%))
default: $sum', x', A', y_3'$ \
workaround: $sum^prime, x^prime, A^prime, y_3^prime$
![image](https://github.com/typst/typst/assets/28257008/b431acaa-36a2-48cc-ace4-1d5a5ba00516)
