### ISSUE TITLE
`raw()` function doesn't add `block` field to the `raw` element (unlike the raw syntax sugar)

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#4398]
### Description

```typ
#let a = ``.block
#let b = raw("").block
```

Both `a` and `b` should be `false`, but the second line gives the next error:

```
error: content does not contain field "block"
  ┌─ a.typ:2:17
  │
2 │ #let b = raw("").block
  │                  ^^^^^
```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Andrew15-5** [comment]
If it's easy to fix, then I want to do it myself (with a hint at the problem place).

**Comment by laurmaedje** [comment]
This is working as intended. Fields are only present if explicitly set, so that they can still be affected by set rules otherwise. It's the same for all other elements. In a show rule, the field will also be populated since the style context is known by then.

**Comment by PgBiel** [comment]
Maybe we can have a hint for this specific case (the field normally exists but was omitted by the constructor, so it's not yet known)?

**Comment by laurmaedje** [comment]
Sure

**Comment by Andrew15-5** [comment]
> In a show rule, the field will also be populated since the style context is known by then.

I don't know what you mean, since this is not true:

![image](https://github.com/typst/typst/assets/37143421/ceb34401-e8cd-402d-af97-e2d3717485c8)
![image](https://github.com/typst/typst/assets/37143421/9e7ebe1a-a609-4059-831f-4f2fd8552714)

**Comment by PgBiel** [comment]
`elem` doesn't seem to be the subject of the show rule in that case (Laurenz was referring specifically to the case where the `raw` comes from `it` in `#show raw: it => ...` instead of from `#let myraw = raw(...)`).

**Comment by bluebear94** [comment]
> Maybe we can have a hint for this specific case (the field normally exists but was omitted by the constructor, so it's not yet known)?

Maybe something like `field {} in content is not set at this point`?

**Comment by Andrew15-5** [comment]
> Laurenz was referring specifically to the case where the `raw` comes from `it` in `#show raw: it => ...`.

Mmm, yeah, I have a general document show rule instead.
