### ISSUE TITLE
Consider ignoring `;` after an inline code at the end of a list (or enum/paragraph)

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#4401]
### Description

One of the rules that is (I think) almost universal, is that non-last items in a list should end with `;` and the last item should end with `.`. This makes the whole multi-line sentence/paragraph grammatically correct. But if you need to call some function at the end of a list item, then the `;` will be swallowed because it terminates the (inline) code expression. And the only way to go around this is to escape each item one by one (which can be slightly simplified by using find and replace tool). Not everyone knows about this quirk, so this **has to** be "proofread" even though in the source file there are no mistakes. But in the output file, the semicolons are removed. I propose to make an exception in such cases, i.e., ignoring the semicolon at the very end since there is no benefit in putting it there just to terminate the expression.

```typ
#let f(input) = raw(str(input))

Here are some items:
- item #f(1);
- item #f(2);
- item #f(3);
- item #f(4);
- item #f(5);
- item #f(6);
- item #f(7);
- item #f(8);
- item #f(9).

Here are some items:
- item #f(1)\;
- item #f(2)\;
- item #f(3)\;
- item #f(4)\;
- item #f(5)\;
- item #f(6)\;
- item #f(7)\;
- item #f(8)\;
- item #f(9).
```

![image](https://github.com/typst/typst/assets/37143421/17ce2c64-f9f2-4ad2-a255-2a196342efab)

<details><summary>real world example</summary>

![image](https://github.com/typst/typst/assets/37143421/676ffe2b-e3ce-43dd-9a72-809c8d5df1ea)

</details>

### Use Case

Removing the need for escaping the semicolon (either by prepending a backslash or by typing the second semicolon right after the first one) can simplify the way the source code is written and unify it with the output. It will further remove the confusion of the new users or those who simply didn't face this problem before.

**Comment by T0mstone** [comment]
I'm not sure about the `;` rule. This is the first time I ever heard of that; I usually just use `,` to end non-last items. I assume this is a regional or language-based difference.

Regardless, I don't think this proposal is a bad idea.
Maybe we should look into this more generally to allow semicolons after any inline expression to be parsed as text?

**Comment by Andrew15-5** [comment]
> I'm not sure about the `;` rule. This is the first time I ever heard of that; I usually just use `,` to end non-last items. I assume this is a regional or language-based difference.

Ah, yes, I forgot about the `,`. In Russia, you would normally only use `;`, but I think `,` can be used too, but I checked all of this a long time ago, so I can mix things up.

**Comment by Andrew15-5** [comment]
[From Laurenz](https://discord.com/channels/1054443721975922748/1088371867913572452/1251544976416837723):

> It's too non-local for a parsing decision. If anything, we can discuss whether we can change the behaviour of semicolon after interpolated expressions in a more general way.

**Comment by laurmaedje** [comment]
As quoted, I think the proposal as-is is too non-local, so I'll close this.

**Comment by Andrew15-5** [comment]
So I just need to rename the title to a "local" or not so "non-local" name?

What does "too non-local" means anyway? "Too broad"? "Very general"?

**Comment by laurmaedje** [comment]
The fix would not be to just rename the issue, but to come up with a proposal that is syntactically less surprising.

Too non-local means that the rule "ignore ; after code, but only in lists" requires too much context in the parser. It must know it's in a list to handle code parsing. It's not impossible, but it's not a good design in my opinion. Too specific & potentially surprising edge case.

**Comment by Andrew15-5** [comment]
Thanks, but now I don't understand what "syntactically surprising" means. The only surprise for me is that a common `;` at the end of a list item is ignored (as it's also a code mode terminator).

One other situation is when semicolon is used in a sentence without Typst lists (for complex sentence or sequence of some sort). For example:

```typ
This is my sentence; the sentence has a semicolon.
```

When you add something:

```typ
This is my sentence #some-var; the sentence has a semicolon.
```

Now the semicolon is gone. It's only useful when you need to write something right after:

```typ
#let name = "cookie"
This is my sentence #name;-based the sentence has a semicolon.
```

This is probably very rare, but still a valid use case.

So the semicolon shouldn't be ignored when inline code mode is embedded into (parent) markup mode and there is a new line or a space after the semicolon. How does this sound?

I think that semicolon is probably the last thing anyone would use for code mode in Typst as it's unnecessary always (I never used it). So no one will probably put it in the above circumstances in the first place. Which means ignoring the semicolon only has disadvantages and no advantages, the way I see it.

**Comment by notPlancha** [comment]
> One other situation is when semicolon is used in a sentence

Is there any tracking issue with this? Is this even intended? I don't understand why an explicit `;` in text is just ignored, besides programming habit. While I'm writing text I'm expecting my semicolon to not be ignored just because I used a function or variable before that.

some other examples:

```typ
This claim was done by #cite(<somearticle>, form:"prose"); they also said another thing.

I'm doing some claim#footnote("this claim has done by this author"); this claim is invalid.

This is really #emph[interesting]; however, it is not important

Number #{1 + 2}; This question starts with a semicolon
```

This can be avoided if you just add another semicolon, which is really ugly:

```typ
This is #emph[interesting];; however, it is not important
```

**Comment by laurmaedje** [comment]
@notPlancha It's intentional that semicolons terminate inline code fragments. However, I agree that this is problematic in some cases and it's perhaps not the ideal design. There is no issue for that problem, but I'm open for having one. I closed this one because I disagreed with the proposal and not because there is no room for improvement.
