### ISSUE TITLE
Adding invisible data (`metadata()`) after setting `page.paper` inside `content` (sub-document) creates an empty page

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#4407]
### Description

```typ
// 2 pages
// #set page(paper: "a5") // Doesn't matter
#metadata("") <begin-marker>
#[
  #set page(paper: "a5")
  Text
]
#metadata("") <end-marker>

// 1 page
// #set page(paper: "a5") // Doesn't matter
#metadata("") <begin-marker>
#set page(paper: "a5")
Text
#metadata("") <end-marker>
```

The first block creates one page with text and an empty page. The second doesn't add an unnecessary page at the end.

I am creating a bundle document that `include`s several other documents. This way I can have all reference links working and have an outline of all sub-document (with working links). But including a full document means including set/show rules, which creates a `styled()` content block/wrapper for each sub-document.

<details><summary>General AST structure</summary>

```rs
...
    [(
      metadata(value: ""), <- "sub-document starts" marker
      [ ],
      [ ],
      styled(child: [([Text], [ ])], ..), <- sub-document
      metadata(value: ""), <- "sub-document ends" marker
      [ ],
    )],
...
```

</details>

It would be normal in _some_ cases if I replace seconds `metadata()` call with visible content (text). But still, maybe you want the text from outer (bundle document) be inserted into the same last sub-document's page (where there is still a lot of empty space) and not into a whole new page. This aspect can be potentially a new feature, but I don't know how exactly this can be controlled (maybe a new `page.append-parbreak-if-inside-content`).

I would like that _at least_ an invisible data such as `metadata()` (or `hide()`?) won't create a new empty page as this is totally not a desirable behavior. But I have a feeling that this is impossible with the current (v0.11.0) design (maybe?). Or maybe a new check can be added that will "diff" the previous (bundle/global) `set page()` and the current (sub-document/nested) `set page()`. If they are identical then the last one will be removed and this way no new empty page at the end will appear. IMO, this is an easier route. But what if `page.footer` don't much?

To fix this, I can remove the sub-document's `set page()` by using a condition, but that condition would require a `context` so that I can `query()` the start/end sub-document labels/markers to see if the current document is inside a bundle document or not. At which point it will become #2326.

Similar but still different problem exists with `set document` (instead of `set page`) which is inside a context (to also check for `is-sub-document()`): #4065.

A general "embed sub-document" issue: #3723.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
While it's a slightly different effect user-facing, this is internally the exact same problem as #2326, so I'll close as a duplicate.
