### ISSUE TITLE
overline/underline work strangely with some characters in math mode

### ISSUE THREAD

**Issue by damaxwell** [typst/typst#441]
In math mode with certain math fonts, including the default New Computer Modern Math, underline and overline have the wrong position for some characters (`i`, `l` and `t`). In the example below, the first two fonts have misplacement, but the third is ok.

```typst
#[
#show math.equation: set text(font:"New Computer Modern Math")
$underline(i) quad underline(l) quad  underline(t) quad underline(j) quad underline(y)$
]

#[
#show math.equation: set text(font:"TeX Gyre Termes Math")
$underline(i) quad underline(l) quad  underline(t) quad underline(j) quad underline(y)$
]

#[
#show math.equation: set text(font:"DejaVu Math TeX Gyre")
$underline(i) quad underline(l) quad  underline(t) quad underline(j) quad underline(y)$
]
```

<img width="184" alt="image" src="https://user-images.githubusercontent.com/918465/228665177-45d6cbf7-3383-4777-9f56-d5931473cc8a.png">

Note: I got surprised by #351 when making this MWE and had to nest the scopes on the show/set rules.

**Comment by laurmaedje** [comment]
Yeah, I think somebody reported this on Discord a little while ago and it's truly strange. I haven't had the time to investigate yet though.

**Comment by damaxwell** [comment]
I dug a little deeper.  Here's what's going on.  The search for a making an underline first looks at variants of U+0332 to see if any are wide enough (or at least it should; there's a transposition in the code and U+0332 is used for *overerlines* and U+0305 is used for *underlines*. I can submit a PR for this easy change).  For the narrowest characters using New Computer Modern Math  the base variant fits. This is glyph `/lowlinecmb`.  The Math variants table lists its advance width as 393, wide enough to go under a `t`, but not much wider.  But `/lowlinecmb` has funny metrics.  Its actual advance width from `htmx` is 0 and its left side bearing is -460.  This character is designed to sneak under the character to the left.  The advance width being reported in the variants table is in fact (right side bearing - left side bearing), i.e. the width of the bounding box of the glyph, independent of the fact that it's been scooted far to the left.  

Once `/lowlinecmb` has been decided on, it gets turned into a `MathRow` by a sequence of transformations, starting from a `GlyphFragment`.  The data for a `GlyphFragment` includes height information from a bounding box computation, but the width information is discarded and only the glyph's genuine advance width is kept. This results in a `Frame` with zero width with subsequent downstream effects.

Nothing bad happens with wider characters because they match on a wider glyph, `/lowlinecmb.h1` which has reasonable `htmx` metrics: a left-side bearing of 0 and an advance width of 568.  Or they require an assembly.

One possibility to address this is for `GlyphFragment.to_variant` to check if its `width` is zero, in which case it builds a `Frame` from bounding box information rather than from its `width`.  There's enough data in the `GlyphFragment` to redo the bounding box computation.  Alternatively the struct can be enlarged to keep the bounding box info in the first place. 

This special case approach (do something radically different if width is 0) is something of a hack of a solution, but there aren't that many actual math fonts in the wild.  Moreover, it only affects the conversion of glyph->variant, a niche thing, and only in the weirdo case where the advance width is 0 and yet was reported from the variants table to be wide enough.  So in practice, this might be a robust enough strategy.

**Comment by laurmaedje** [comment]
This strategy sounds reasonable.
