### ISSUE TITLE
Page Numbering Issue with counter(page).update(1) Not Working as Expected

### ISSUE THREAD

**Issue by Fiwex** [typst/typst#4410]
### Description

I'm encountering an issue with page numbering in Typst. Specifically, when trying to reset the page counter on page 3, the numbering does not update as expected. Here are the steps to reproduce the issue:

- Create a document with a header and footer.
- Set the footer to display page numbers in Roman numerals for pages 1 and 2.
- Attempt to reset the page counter to 1 on page 3.
- Observe that page 3 is incorrectly numbered as 3 instead of 1.
- Page 4 is correctly labeled as 2.

Here is an code example that demonstrates the issue:

```
set page(
    header: context [
        header
  ],
    footer: context [
      #set align(right)
      #set text(10pt)
      College X - Name #h(1em)
      #locate(
        loc => 
        if loc.page() < 3 {
          counter(page).display("I");
        } else if loc.page() == 3 {
          counter(page).update(1);
          counter(page).display("1");
        } else {
          counter(page).display("1");
        }
      )
    ]
  )
```

Expected Behavior:

- Pages 1 and 2 should be numbered using Roman numerals.
- Page 3 should be numbered as "1".
- Page 4 should be numbered as "2", and so on.

Actual Behavior:
- Pages 1 and 2 are correctly numbered using Roman numerals.
- Page 3 is incorrectly numbered as 3 instead of 1.
- Page 4 is correctly labeled as 2.

Please let me know if you need any additional information or if there are any workarounds for this issue, I'm new to Typst but I couldn't find the solution to this. Thank you!

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by JamesxX** [comment]
Consider using the antimatter package

**Comment by EpicEricEE** [comment]
What happens here, is that with
```
} else if loc.page() == 3 {
  counter(page).update(1)
  counter(page).display("1")
}
```
the `display` function is using the available context that is defined at the beginning of the footer. That context, however, doesn't yet know of the counter update, so you would need to tell Typst to use a new context that includes it:
```
} else if loc.page() == 3 {
  counter(page).update(1)
  context counter(page).display("1")
}
```

Also, you can remove the `locate(loc => ...)`, and use `here().page()` instead of `loc.page()`.

**Comment by laurmaedje** [comment]
Based on the response from @EpicEricEE it looks like things are working as expected here, so I'll close this.
