### ISSUE TITLE
calc.pow negative power support

### ISSUE THREAD

**Issue by LeoDog896** [typst/typst#442]
Negative exponents are supported by many other mathematical libraries, for example, Javascript ([Math#pow](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/pow)). This restriction is in place [in code](https://github.com/typst/typst/blob/dffaef08326967028e9ca9ff2bdb87e067fcf5f6/library/src/compute/calc.rs#L100).

**Comment by user202729** [comment]
The intention here is to make pow(int, int) return int and pow(float, float) return float, but pow(int, int) will give an error if exponent is negative.

I think best way is to make the error say "Cannot raise int to negative int power. Explicitly convert to float if you want float result." or just cast for the user.

... looking at the source code it should probably use `checked_pow()` instead. (at the cost of performance) https://doc.rust-lang.org/std/primitive.i64.html#method.checked_pow

**Comment by LeoDog896** [comment]
I think casting for the user in negative cases, makes the most implicit sense (and yes, it should use `checked_pow`).

**Comment by Dherse** [comment]
I opened a PR #486 fixing this, we'll see if this gets merged :)
