### ISSUE TITLE
Implement filling-/tiling-patterns in the core engine

### ISSUE THREAD

**Issue by ollelogdahl** [typst/typst#443]
This is the first necessary part for fill patterns ([see discussion](https://discord.com/channels/1054443721975922748/1090047399982006315)). To fulfill usable filling patterns, we need to implement the needed abstractions in the core. Most likely, we should implement it both in the `exporter`-layer, since PDFs have support for them, but also at the `frame`-layer where some shape is duplicated. Gradients are especially suitable for the first one, and patterns could be any of them or both.

## Why
The end-goal is to support filling `box`/shapes with a custom pattern. This can probably extend some day to `line`s, but that is outside the scope atm. The end goal is to support both **gradients** and **patterns** that look like [Tikz patterns](https://tikz.dev/library-patterns):

![lines](https://user-images.githubusercontent.com/37961475/228676172-a913b8f0-9b95-47f0-a4e3-fffb6fbac361.png)
![crosshatch](https://user-images.githubusercontent.com/37961475/228676119-81c1e8d9-b53f-4c7e-85f8-8acb471b9904.png)
![crosshatch dots](https://user-images.githubusercontent.com/37961475/228675969-f30167a1-f168-4ed8-aeb2-97f7aa41a524.png)

These should be as general and modifiable as possible, but this is outside the scope of this feature.

## Reference documents:
- [PDF 1.7 Specification](https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf), Section 8.7.3 ("Tiling patterns")
- [related implementation](https://docs.rs/tiny-skia/latest/tiny_skia/struct.Pattern.html) in `tiny_skia`

**Comment by ollelogdahl** [comment]
Im currently working/experimenting on gradients, as I think they're the simplest. :^)

**Comment by Dherse** [comment]
Closing as completed in #2740.
