### ISSUE TITLE
Not works on MacOS 15

### ISSUE THREAD

**Issue by noahzhy** [typst/typst#4432]
### Description

The current version of Typst does not work on macOS 15, whether installed via Homebrew or downloaded from the release page.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by frozolotl** [comment]
Can you give a bit more information on what isn't working?
There are a number of people who are using Typst on macOS, so it would surprise me if it was a fundamental problem.

**Comment by noahzhy** [comment]
> Can you give a bit more information on what isn't working and what exactly you did? There are a number of people who are using Typst on macOS, so it would surprise me if it was a fundamental problem.

I don't think it's a big deal. After all, only a few people like me have installed the beta version of macOS 15, so it's understandable that Brew hasn't found a compatible version yet.

**Comment by Coekjan** [comment]
Any information (like crash?) when it does not work?

**Comment by Enivex** [comment]
> I don't think it's a big deal. 

If it doesn't work, then that's a big deal. But you've yet to even state _what_ doesn't work.

**Comment by noahzhy** [comment]
Sorry, my bad it's a mistake, the arm64_sonoma version is work on MacOS 15.
