### ISSUE TITLE
Customize pages generated by `pagebreak(to:)`

### ISSUE THREAD

**Issue by dz4k** [typst/typst#4438]
### Description

Using the `pagebreak` function with the `to` argument will sometimes generate pages. These pages are affected by enclosing set rules (e.g. adding header and footer), but there's no way that I could find to apply rules just to those generated pages.

To fix this, I propose a new argument to `pagebreak`, `generate-pages`, which is called to create the pages inserted for even-odd alignment purposes. The default value would be `() => page[]`.

Alternative solutions:

- A method on `location` to check if the page the location is in was generated.
- The same, but for checking if it was blank. This one would be more generally applicable, but it might be hard to define "blank" in a useful way.

### Use Case

e.g.

 - remove header and footer from inserted pages to leave them blank
 - add "This page intentionally left blank" message

**Comment by Dherse** [comment]
I would add that I think we should instead have a new method on `location`  to determine whether the page is part of a "jump", allowing this feature to be done solely using a `context` on the header and footer and background for all of the aforementioned features. Otherwise, I think this makes a lot of sense!

**Comment by JamesxX** [comment]
Could `pagebreak` be merged into 'page' with a `weak: false` param? Then redefine `pagebreak` using `page.with`

**Comment by freundTech** [comment]
Related: #2722

**Comment by laurmaedje** [comment]
While https://github.com/typst/typst/issues/2722 is a bit tighter in scope, the intent is the same, so a well-designed solution covers both. So I'll close this as a duplicate.
