### ISSUE TITLE
Typst cannot type Chinese properly

### ISSUE THREAD

**Issue by Springfield0708** [typst/typst#4440]
### Description

I found that Typst cannot type Chinese properly now. For example, when I wrote:

 *定义1.1.1（集合）*：*集合（set）*是“事物的选集”。这些事物被称为集合的*元素（element）*或*成员（member）*。

The final result of tpyst's compile is:

![QQ截图20240624135744](https://github.com/typst/typst/assets/173694670/01f16fd4-60dc-4cc2-b118-1e0b1c1bf89d)

You can see here, for example, the phrase *集合（set）* is not in bold.

I don't understand why this happened, since last time when I used typst, it could type Chinese properly.

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Springfield0708** [comment]
> I suspect this is a case of missing fonts and fallback.

Yeah, maybe. But last time, Typst could compile these exact same Chinese words properly. Have we had any updates on Typst recently?

**Comment by Enivex** [comment]
Are you specifying fonts manually, or entirely relying on typst finding a font on your system? In the latter case all bets are off.

**Comment by Coekjan** [comment]
You may want to use https://typst.app/universe/package/cuti/

AND I see you are using `touying-buaa`, so you can configure the language and the template will automatically import `cuti` for you. See https://github.com/Coekjan/touying-buaa/blob/bf25effe6066b3930c5fd0b7aac1ebf8af5c6b9f/examples/main.typ#L50

**Comment by Enivex** [comment]
I'll close this. If you're still having issues after specifying an actual font (with a bold variant), then feel free to open a new issue.

Typst doesn't ship with a CJK font, and last resort fallback is unpredictable.

**Comment by Springfield0708** [comment]
Note: The problem has been solved by adding the following codes:
`#set text(font: "Noto Sans CJK SC")`
