### ISSUE TITLE
Include `page` parameter to not disrupt current text flow

### ISSUE THREAD

**Issue by miles-1** [typst/typst#4442]
### Description

For an example document that includes a full-page figure...
```typst
= Introduction
#lorem(300)

#page(
  flipped: true, 
  figure(
    table(
      columns: 10,
      inset: (x:50pt,y:15pt),
      ..range(1, 101).map(x => [#x])
    ), 
    caption: [some table]
  )
)

= Methods
#lorem(300)
```
... it would be helpful to have a parameter that allows for specification that the text flow of the current page should not be interrupted, and the full-page figure will appear on the subsequent page.

I can think of a few ways this might be implemented:
1. An `interrupt-text-flow` parameter (default value: `true`) that, if set to `false`, will be kept from any rendering until the current page is full.
2. An `insert-after` parameter (default value: `none`) that, if set to a label of some document element, will be inserted into the document one page after the label-specified content is completed, not interrupting text flow.

### Use Case

In many academic publications, large tables or images are pushed to be on their own page, often on a landscape page, while not interrupting the text flow after it is mentioned with a page break that leaves unused page space.

**Comment by freundTech** [comment]
I think this might be better as a parameter on `figure` instead of `page`.
`figure` already has the `placement` attribute, which accepts `none` (here), `top` and `bottom`.

It might be possible to add new options `page` and `flipped-page` there and let typst figure out the rest, similar to LaTeX's `p` figure placement.

**Comment by laurmaedje** [comment]
> I think this might be better as a parameter on figure instead of page.

Agreed. I'll close this in favor of https://github.com/typst/typst/issues/3967.

**Comment by bensetterholm** [comment]
FWIW, a workaround in the meantime is to wrap the figure inside another figure environment that spans an entire page.

```typst
= Introduction
#lorem(300)

#figure(
  placement: auto,
  block({
    v(1fr)
    rotate(
      -90deg,
      reflow: true,
      figure(
        table(
          columns: 10,
          inset: (x:50pt,y:15pt),
          ..range(1, 101).map(x => [#x])
        ), 
        caption: [some table]
      )
    )
    v(1fr)
  }),
  kind: "full-page",
  supplement: none
)

= Methods
#lorem(600)
```
