### ISSUE TITLE
`block` `spacing` is not being handled correctly

### ISSUE THREAD

**Issue by tapyu** [typst/typst#4455]
### Description

Hi! I think there is a bug in how to the `spacing` option is being handled in `block`:

```typ
#block(spacing: 0pt)[
  paragraph 1

  paragraph 2

  paragraph 3
]

#set block(spacing: 0pt)

#block[
  paragraph 1

  paragraph 2

  paragraph 3
]
```

![image](https://github.com/typst/typst/assets/22801918/69b46583-30db-4606-807a-901183b95c27)

AFAIK both forms should produce the same thing: paragraphs without space between them. However, it happens only in the second case . Additionally,, the SVG output diverges from the PDF output:

![image](https://github.com/typst/typst/assets/22801918/45d89050-a5da-409e-a600-74c6c6e6085e)

Which makes me think it is indeed a bug.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
see #4224
