### ISSUE TITLE
Math rendering issue in Chrome

### ISSUE THREAD

**Issue by tinnamchoi** [typst/typst#4474]
## Steps to reproduce:

- Create anything in math mode
- Scroll until it's out of view
- Scroll back in, the math is gone but the surrounding text remains
- Zooming in / out fixes it temporarily until it gets scrolled out of view again

## Example:

![output](https://github.com/typst/typst/assets/101849050/fe0a0f8f-6427-4a1a-a57a-9b795f72035a)

Any math will do, but here's the one used in the GIF above.

```typst
#lorem(5) #box(stroke: red)[$a^2 + b^2 = c^2$] #lorem(5)
```

## System

Browser: `Google Chrome 125.0.6422.141`
OS: `Arch Linux`
Compiler: `typst 0.11.1 (50115102)`

I have not been able to reproduce the issue in Firefox and Edge.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
Could you send the actual generated PDF, too?

**Comment by LaurenzV** [comment]
But in any case, there have been printer-related issues in the past where math code was not printed properly (see https://github.com/typst/typst/issues/3314), but these issues should be fixed on main. If you have the ability to compile Typst yourself, you could try compiling the newest main and check whether the issue still persists.

In any case, I'm unable to reproduce this on MacOS.

**Comment by tinnamchoi** [comment]
[resume.pdf](https://github.com/user-attachments/files/16040320/resume.pdf)

**Comment by tinnamchoi** [comment]
I tried compiling on https://typst.app/ and the downloaded file still has the same problem.

**Comment by tinnamchoi** [comment]
Just finished compiling Typst. Here's the pdf from main, which still has the same issue: [resume.pdf](https://github.com/user-attachments/files/16040751/resume.pdf)

**Comment by LaurenzV** [comment]
Thanks! Weird then, it must be a Linux-specific issue because your PDFs show up fine on my Chrome on MacOS, regardless of how I zoom...

**Comment by Coekjan** [comment]
I am unable to reproduce this on Linux (Google Chrome Version: 126.0.6478.126) :zipper_mouth_face:

**Comment by tinnamchoi** [comment]
@Coekjan What distro are you using?

**Comment by Coekjan** [comment]
> @Coekjan What distro are you using?

![image](https://github.com/typst/typst/assets/69834864/349d4242-68ce-4a57-8524-795c2e8f97e2)

**Comment by tinnamchoi** [comment]
Apparently there was a chrome update that fixed this (could've sworn i updated chrome a day or two before opening the issue but I guess not...)
Anyways I upgraded to 126.0.6478.126 and it's gone now.
