### ISSUE TITLE
Different decimal formats

### ISSUE THREAD

**Issue by qeterme** [typst/typst#448]
Hi there,

How can I use a comma in float numbers as a decimal separator? 
![image](https://user-images.githubusercontent.com/8946184/228782159-46f45ff1-17bc-4fd9-859c-1b9860be0ddc.png)
https://en.wikipedia.org/wiki/Decimal_separator#Conventions_worldwide

**Comment by laurmaedje** [comment]
Unfortunately, this isn't really supported at the moment.

**Comment by ararunaufc** [comment]
#216 suggests using Fluent for l10n (localization), but I believe it can also handle aspects of i18n (internationalization) such as this.

**Comment by laurmaedje** [comment]
Closing in favor of #1093 which has seen a bit more discussion.
