### ISSUE TITLE
Add the flat (♭) and sharp (♯) symbols

### ISSUE THREAD

**Issue by TheVecGH** [typst/typst#4481]
### Description

Adding two symbols to the existing symbol catalogue.

### Use Case

These symbols are commonly used in music notation and differential geometry, which makes them a useful addition.

**Comment by istudyatuni** [comment]
These symbols also has names bemol and diese https://music.stackexchange.com/questions/46391/where-did-the-symbols-and-%E2%99%AF-originate-from-and-why-those#comment70783_46399

**Comment by Enivex** [comment]
> These symbols also has names bemol and diese https://music.stackexchange.com/questions/46391/where-did-the-symbols-and-%E2%99%AF-originate-from-and-why-those#comment70783_46399

In English as well?

I'd wager most people would be more familiar with flat and sharp.

**Comment by istudyatuni** [comment]
According to names of articles in wikipedia "bemol" is more common across languages: https://en.m.wikipedia.org/wiki/Flat_(music)#/languages

I'm just suggesting that it be made discoverable by both names

**Comment by Enivex** [comment]
I don't think there's any precedent for that. The symbol names are based on English.

**Comment by istudyatuni** [comment]
Okay, I just wanted to share, that this would be good
