### ISSUE TITLE
Configure some errors as warining

### ISSUE THREAD

**Issue by Eismandel** [typst/typst#4489]
### Description

I’d like to get a kind of compiler option to switch errors for missing labels to warnings (and continue to compile the document).

### Use Case

I have some rather massive appendixes with references in the main document. 

To safe some compile time, I usually comment the appendix includes.
But when doing this, the document does not compile anymore.

With Latex, I got some warnings and a ?? at the missing reference. 
With typst the compile just stops with an error message.

**Comment by Coekjan** [comment]
See #4035

**Comment by laurmaedje** [comment]
Missing references are covered by the issue linked above. I don't think a more general mechanism makes much sense, so I'll close this as a duplicate.
