### ISSUE TITLE
Wrong Font Variants: Noto Sans SC on Windows

### ISSUE THREAD

**Issue by galiren** [typst/typst#4493]
### Description

similar to #576, but is an issue about another font.

## Environment

- Windows
- typst-x86_64-pc-windows-msvc `0.11.1`

## Reproduce Steps

1. download `Noto Sans Simplified Chinese` from [Google Fonts](https://fonts.google.com/noto/specimen/Noto+Sans+SC), it provides these variants (in **static** folder):
  ```
  static\NotoSansSC-Black.ttf
  static\NotoSansSC-Bold.ttf
  static\NotoSansSC-ExtraBold.ttf
  static\NotoSansSC-ExtraLight.ttf
  static\NotoSansSC-Light.ttf
  static\NotoSansSC-Medium.ttf
  static\NotoSansSC-Regular.ttf
  static\NotoSansSC-SemiBold.ttf
  static\NotoSansSC-Thin.ttf
  ```
(EDIT) install the font files into Windows font folder `C:\Windows\Fonts`.

2. write a typst file like below, and compile:

```typst
#set text(
  font: "Noto Sans SC"
)
#text(style: "normal", weight: "thin")[你好] \
#text(style: "normal", weight: "regular")[你好] \
#text(style: "normal", weight: "bold")[你好]
```
The result is as shown below. The rendering font is using `NotoSansSC-Thin.ttf`.
<img src="https://github.com/typst/typst/assets/116235134/a9011791-612d-4241-a0b5-84b1e0dc26d3" width="500"/>

3. `typst.exe fonts --variants` gives following information about `Noto Sans SC`:
```
Noto Sans SC
- Style: Normal, Weight: 100, Stretch: FontStretch(1000)
```

Thank you for any investigations and comments in advance.

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Coekjan** [comment]
Did you use `--font-path static` to specify the `static` folder?

**Comment by galiren** [comment]
> Did you use `--font-path static` to specify the `static` folder?

Sorry for possible misunderstanding. I installed the fonts in the `static` folder extarcted from original google font archive. the fonts were finally installed into Windows Fonts folder, which is `C:\Windows\Fonts`.

**Comment by galiren** [comment]
> Could you run `typst.exe fonts --font-path /path/to/static --variants` and check if the variants are found? If they can be found via specifying font-path, maybe it is the issue about installation.

Thank you! It works. I've appended the extracted path (not the system font folder, which I think maybe unneeded to do so), and typst have found the fonts varying by weights.

![image](https://github.com/typst/typst/assets/116235134/93aa313e-5022-4193-8e27-0afff2c398b9)
