### ISSUE TITLE
Add function to compute norm(s)

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#4508]
### Description

`calc.hypot(x, y) == calc.sqrt(x * x + y * y)` for floats and integers. For lengths, `calc.hypot(x, y)` would work similarly, keeping the unit.

### Use Case

Computing hypotenuses with lengths is currently very annoying because multiplying lengths is not allowed. This would solve this problem.

**Comment by Enivex** [comment]
How about just making `calc.abs` variadic, and equal to the euclidean norm? It makes sense for any number of arguments, as long as they're either all lengths or all numbers.

**Comment by MDLC01** [comment]
I like this idea, but I can see two problems: readability (it's not obvious to the uninformed reader what `calc.abs(x, y, z)` does), and discoverability. It may be better to create a separate `calc.norm` function and keep `calc.abs` separate, just for calculating absolute values. This would solve the readability problem, and also improve discoverability.

Additionally, we might as well go all the way and accept a positional argument to specify what $p$-norm to compute (not sure what the name would be though).

**Comment by pauladam94** [comment]
Instead of doing a length operator, isn't it better to think about how to multiply length together ?
This is completely transparent, that is something that should not even be explained or especially added to the documentation since addition is already a thing. Of course, it became trivial with the multiplication to do a lot of sorts of thing (like the norm).

I am also thinking that adding norm will create a very weird way to actually get the value of the multiplication of length.

**Comment by Enivex** [comment]
> Instead of doing a length operator, isn't it better to think about how to multiply length together ?
> This is completely transparent, that is something that should not even be explained or especially added to the documentation since addition is already a thing. Of course, it became trivial with the multiplication to do a lot of sorts of thing (like the norm).
> 
> I am also thinking that adding norm will create a very weird way to actually get the value of the multiplication of length.

It would be significantly more complicated, and brings about few actual benefits.

**Comment by pauladam94** [comment]
## Why this is not complicated
Looking at the code here it does not seem to be complicated.

Here is the code of the multiplication (that right now crash even on `2pt * 2pt`):
https://github.com/typst/typst/blob/838dabc84cfea04c135aaff2f89ec4b2b32926e4/crates/typst/src/eval/ops.rs#L312-L319

Especially enabling addition of length that have both the 'font-relative' part to 0 or both the 'absolute' part to 0 is simple and is just multiplying 2 floats. Here is the code of the definition of the type `Length` present in the enum `Value`.
https://github.com/typst/typst/blob/838dabc84cfea04c135aaff2f89ec4b2b32926e4/crates/typst/src/layout/length.rs#L44-L49.

## Why this is beneficial
- This doesn't add complexity to typst and allows more to be done directly from Typst language. Especially, it enables to do length computing easily (if there is `1em * 12pt` you can just put a context and do `1em.to-absolute()` to have only length that have the 'font-relative' part to 0).
- It doesn't add any more functions API in typst.
- Especially when drawing anything it will be easier to do it directly in Typst I think.

**Comment by laurmaedje** [comment]
I'm not 100% following. Is the proposal that lengths should be multipliable with lengths? Because afaict that would require us to introduce a new type that is basically length^2.

**Comment by Enivex** [comment]
> I'm not 100% following. Is the proposal that lengths should be multipliable with lengths? Because afaict that would require us to introduce a new type that is basically length^2.

In fact you'd need length^p for every p >= 1 (not even just integers) to replicate the p-norm this way.

**Comment by pauladam94** [comment]
Yeah I responded about the idea of permitting the compute of the length by permitting the multiplication of length that have both (Abs and Em) equal to Zero. In this special case it will not be necessary to add any type ?

**Comment by pauladam94** [comment]
Doing such a thing does not completely solve the issue. However by fixing the context we will get only get length with 'em' attribute to 0 and those could be multiplied with each other.

**Comment by Enivex** [comment]
@pauladam94 

What exactly should the result of `2pt * 2pt` be?

**Comment by pauladam94** [comment]
> @pauladam94
> 
> What exactly should the result of `2pt * 2pt` be?

I was thinking multiplying the floats. So here `2pt * 2pt` would be lenght with `em` equals to 0 and `abs` equals to 4, so `4pt`.

**Comment by Enivex** [comment]
> > @pauladam94
> > 
> > What exactly should the result of `2pt * 2pt` be?
> 
> I was thinking multiplying the floats. So here `2pt * 2pt` would be lenght with `em` equals to 0 and `abs` equals to 4, so `4pt`.

The point here is that when multiplying two lengths you get an area, not a length. The issue is unrelated to relative and absolute lengths.

**Comment by MDLC01** [comment]
As a comparison, CSS does not support multiplying lengths, and has a [`hypot`](https://developer.mozilla.org/en-US/docs/Web/CSS/hypot) function.

**Comment by pauladam94** [comment]
> As a comparison, CSS does not support multiplying lengths, and has a [`hypot`](https://developer.mozilla.org/en-US/docs/Web/CSS/hypot) function.

This is interesting. I do agree that following what has been done in CSS is a good idea for multiple reasons:
- having easier transpilation to CSS
- easier for people to understand typst if it's similar to CSS
- CSS is older and must have taken seriously this kind of things (and could have implemented for a long time this feature). So this is a design choice

**Comment by pauladam94** [comment]
@MDLC01 
> Computing hypotenuses with lengths is currently very annoying because multiplying lengths is not allowed. This would solve this problem.
How is it possible right now ? You said it was currently annoying ?

**Comment by MDLC01** [comment]
> CSS is older and must have taken seriously this kind of things

CSS made a lot of mistakes, so I'm not saying we should follow what it does. I'm only using it as an example of a succesful similar tool that does not support multiplying lengths.

**Comment by MDLC01** [comment]
> > Computing hypotenuses with lengths is currently very annoying because multiplying lengths is not allowed. This would solve this problem.
> 
> How is it possible right now ? You said it was currently annoying ?

This should work:
```typ
#let hypot(x, y) = {
  let a = x.to-absolute() / 1pt
  let b = y.to-absolute() / 1pt
  (a * a + b * b) * 1pt
```

**Comment by pauladam94** [comment]
Ok I didn't know at all that we could get back a float from a length that is only a `..pt` by dividing by 1pt. It works also to get the 12 from 12em. Is this indicated anywhere is the documentation ? This is very useful. I would now argue that the hypot function is not usefull (because it actually can be emulated simply).

**Comment by Enivex** [comment]
> Ok I didn't know at all that we could get back a float from a length that is only a `..pt` by dividing by 1pt. It works also to get the 12 from 12em. Is this indicated anywhere is the documentation ? This is very useful. I would now argue that the hypot function is not usefull (because it actually can be emulated simply).

https://github.com/typst/typst/pull/4581#issuecomment-2388310378
