### ISSUE TITLE
Cannot convert "->" with show rule to e.g. an arrow

### ISSUE THREAD

**Issue by dnlsch** [typst/typst#4519]
### Description

I cannot convert "->" with show rule to e.g. an arrow.

```
//Not working:
#show "->": [#sym.arrow.r]
#show "-" + sym.gt: [#sym.arrow.r]
#show "-\u{003E}": [#sym.arrow.r]

//Working
#show "<": [#sym.arrow.l]

->

<
```

This produces:

![grafik](https://github.com/typst/typst/assets/118688572/a866a275-9a69-4d70-b976-dce354c76962)

I think it should also be possible to apply the show rule to a "->" even if > is a special character used for tags.

### Reproduction URL

https://typst.app/project/r-EhUWSTLFEIdIiDWo8xH8

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
https://github.com/typst/typst/issues/86
