### ISSUE TITLE
Space between paragraphs doesn't respect block spacing property

### ISSUE THREAD

**Issue by gabriel-araujjo** [typst/typst#4556]
### Description

Space between paragraphs are rendered despising the block spacing property

The following snippet is rendered with no extra space between paragraphs on typst 0.11.1, but with extra space in the latest commit (ac322e342b4736bea189f5e7ac39561c0e5a3127)

```typst
#set text(size: 12pt)

#set par(justify: true, first-line-indent: 1.5em)
#show par: set block(spacing: 0.65em)

#lorem(20)

#lorem(30)

#lorem(50)

```

### Reproduction URL

https://typst.app/project/rsOjcYyG-J4AqzUsFv-siN

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
See https://github.com/typst/typst/pull/4390
