### ISSUE TITLE
Import remote resources

### ISSUE THREAD

**Issue by palainp** [typst/typst#456]
Dear developers,
Is there a possibility to permit `import` (or even `include`) on remote online resources? It currently fails, I tried to update `src/eval/mod.rs:import` but without any luck so far. It seems to rip `//' I have the following and I miss a way to read remote content:
```
$ cat empty.typ 
#import "https://github.com/typst/typst/blob/main/tests/typ/layout/align.typ": *

== Dummy test
$ ./target/release/typst empty.typ 
error: file not found (searched at https:/github.com/typst/typst/blob/main/tests/typ/layout/align.typ)
  ┌─ empty.typ:1:8
  │
1 │ #import "https://github.com/typst/typst/blob/main/tests/typ/layout/align.typ": *
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
This would be useful for having always up-to-date community templates.

**Comment by kanashimia** [comment]
There were some discussions about package management in discord channel, it is a complex thing to implement right, so probably won't be as simple as just pasting a link.

Right now If you use git and the templates are in the git repo, then you can use git submodules to include those templates, or write a script that fetches them.
