### ISSUE TITLE
Deterministic PDF output

### ISSUE THREAD

**Issue by dcharkes** [typst/typst#4561]
### Description

Provide options to `typst compile` to deterministically set the PDF metadata or skip it.

If it is possible to manually set or skip the PDF metadata, we could make `typst compile` completely deterministic.

On a small PDF (35k) there is a very small difference

```
$ git diff --binary
[...]
GIT binary patch
delta 195
zcmdltg=yaurVU@3)D2Ay&5VqUjiNNU6cqG*^HW?BOHvgyT&#=?j7$v7VbYtWo4uI0
z4NXG~&8&=!tc;B&7qn`j@Rzo(7AsBm4)Q7TweU;xtw=6OtI7(@O4d)GoYtm}Lu&Kl
WHeY5#?AmN?H5D|lOHEenk_7<e|31e6

delta 195
zcmdltg=yaurVU@3)C~*`jZF;=O`|lq6cqG*^HW?BOHvgyT&#=?j7$v7VbYtWo4uI0
z4GcpJjjc=#tqe^k7qn`j@Rzo(7E5%B^olHvN_WXBOpFZjP0BZj@XsutoYtm}Lu&Kl
WHeY5#?AmN?H5D|lOHEenk_7;*>^<)Q
```

I suspect this difference to be the PDF metadata:

```xml
?xpacket begin="" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta
	xmlns:x="adobe:ns:meta/" x:xmptk="xmp-writer">
	<rdf:RDF
		xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
		<rdf:Description rdf:about=""
			xmlns:dc="http://purl.org/dc/elements/1.1/"
			xmlns:xmp="http://ns.adobe.com/xap/1.0/"
			xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
			xmlns:xmpTPg="http://ns.adobe.com/xap/1.0/t/pg/"
			xmlns:pdf="http://ns.adobe.com/pdf/1.3/" >
			<xmp:CreatorTool>Typst 0.11.1</xmp:CreatorTool>
			<xmp:CreateDate>2024-07-15T16:22:32Z</xmp:CreateDate>
			<xmp:ModifyDate>2024-07-15T16:22:32Z</xmp:ModifyDate>
			<xmpTPg:NPages>1</xmpTPg:NPages>
			<dc:format>application/pdf</dc:format>
			<dc:language>
				<rdf:Bag>
					<rdf:li>en</rdf:li>
				</rdf:Bag>
			</dc:language>
			<xmpMM:DocumentID>ucKRLrM8NfMxctfzjQjc/g==</xmpMM:DocumentID>
			<xmpMM:InstanceID>ucKRLrM8NfMxctfzjQjc/g==</xmpMM:InstanceID>
			<xmpMM:RenditionClass>proof</xmpMM:RenditionClass>
			<pdf:PDFVersion>1.7</pdf:PDFVersion>
		</rdf:Description>
	</rdf:RDF>
</x:xmpmeta>
<?xpacket end="r"?>
```

If we could either omit the metadata such as creation date and document id, or manually set it with command-line options `typst compile --document-id=myDocumentId1234 ...`, we could make the `typst` compiler completely deterministic.

### Use Case

I use typst in functional programming with caching. The binary difference prevents me from caching the pdf that's generated from the typst source.

**Comment by frozolotl** [comment]
Typst supports the [`SOURCE_DATE_EPOCH`](https://reproducible-builds.org/docs/source-date-epoch/) environment variable to set the current timestamp.
Meaning, you can run `SOURCE_DATE_EPOCH=0 typst compile main.typ` to compile a reproducible document.

**Comment by laurmaedje** [comment]
Alternatively you can also `set document(date: none)` or another fixed date.

**Comment by dcharkes** [comment]
> Typst supports the [`SOURCE_DATE_EPOCH`](https://reproducible-builds.org/docs/source-date-epoch/) environment variable to set the current timestamp. Meaning, you can run `SOURCE_DATE_EPOCH=0 typst compile main.typ` to compile a reproducible document.

This doesn't seem to work for me. `pdfinfo` still shows creation date as when compiling.

```
$ typst --version
typst 0.11.1
$ which typst
/opt/homebrew/bin/typst
```

> Alternatively you can also `set document(date: none)` or another fixed date.

This works like a charm! 👌   `pdfinfo` indeed shows the correct (or no) date.

Thanks for an amazing tool folks! (So much nicer than LaTeX!) Keep up the good work! 🚀

**Comment by laurmaedje** [comment]
I think `SOURCE_DATE_EPOCH` isn't yet in a released version. It was added quite recently.
