### ISSUE TITLE
A way to get os/platform info

### ISSUE THREAD

**Issue by duskmoon314** [typst/typst#4564]
### Description

Obtaining OS/platform information is crucial for developing libraries that require different behaviors across various platforms. For instance, users may need to utilize different fonts depending on the operating system. The `ctex` package in LaTeX exemplifies this by using PingFang on macOS, Microsoft YaHei on Windows, and Fandol on Linux.

Since the execution of external tools is not planned, this information may only be helpful for font selection. I think a discussion should be raised.

### Use Case

I think this information should be provided under the `sys` module. A simple usage would be like:

```typst
#text(
  "Hello World",
  font: if sys.os == "linux" { "Fandol" }
    else if sys.os == "macos" { "PingFang" }
    else if sys.os == "windows" { "Microsoft YaHei" }
    else { panic("unsupported os") }
)
```

To implement this, we can leverage [std::env::consts::OS](https://doc.rust-lang.org/std/env/consts/constant.OS.html) of Rust. However, I haven't considered the behavior in the web app.

**Comment by Enter-tainer** [comment]
kind reminder: typst can also run in browser.

**Comment by Enter-tainer** [comment]
For this case, i think font fallback can already do it? simply put all possible fonts in the list and it should work.

**Comment by alerque** [comment]
> crucial for developing libraries that require different behaviors across various platforms

Isn't this kind of an anti-goal? Wouldn't the objective in typesetting typically be to always render the *same* output given the same inputs no matter what the other factors may be?

**Comment by derkrasseleo** [comment]
Really sad that this is not a feature, falling back to another font is IMHO not the right way to handle this, as the document can change quite a bit with a different font

**Comment by saecki** [comment]
Seems like then there should rather be a more powerful font handling mechanism, rather than a check for the OS, which wouldn't even fully guarantee that a specific font is available.

**Comment by derkrasseleo** [comment]
True, but we could at least conditionally assign fonts depening on the OS..

**Comment by saecki** [comment]
No, that's an explicit non-goal, as stated above:

> Indeed. We try to make everything as reproducible as possible. Fonts are a current weak point, we need to improve in that regard. But I think a solution should go into the direction where it's easy to e.g. download fonts on demand (similar to or integrated with packages) to ensure the same output on different platforms instead of adding capabilities to the language for choosing different fonts based on the platform.
