### ISSUE TITLE
[Question] What's the pourpose of document() function?

### ISSUE THREAD

**Issue by dsantiago** [typst/typst#457]
I've read the documentation [here](https://typst.app/docs/reference/meta/document) and still did not understood what's it's purpose?

**Comment by user202729** [comment]
By the way, it's more appropriate to ask questions on https://github.com/typst/typst/discussions (or their Discord channel) instead of https://github.com/typst/typst/issues.

**Comment by dsantiago** [comment]
> By the way, it's more appropriate to ask questions on https://github.com/typst/typst/discussions (or their Discord channel) instead of https://github.com/typst/typst/issues.

Ohh ok, you are absolutely right... Will do it next time.

@TS40 I understood it better now... tks
