### ISSUE TITLE
Panic when compiling invalid file

### ISSUE THREAD

**Issue by qarmin** [typst/typst#4571]
### Description

```
#import (hntle-clues: *
#import "/util.typ": qrlink
#let auton(
) = {
```

command
```
timeout -v 100 typst compile TEST___FILE.typ
```

cause this
```
thread 'main' panicked at crates/typst-syntax/src/parser.rs:1111:11:
assertion `left == right` failed
  left: End
 right: Eq
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

##### Automatic Fuzzer note, output status "Some(101)", output signal "None"
```

[compressed.zip](https://github.com/user-attachments/files/16260673/compressed.zip)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by bluebear94** [comment]
Seems that:

1. Typst is trying to parse a parenthesized expression and parses `(hntle-clues: ... auton()` as one (albeit with a lot of errors)
2. but it encounters an equal sign and tries to reparse this part of the code as a destructuring pattern
3. when it does so, it consumes the entire rest of the code, which triggers the assertion

Replacing `p.assert(SyntaxKind::Eq)` in the offending line with `if p.current() != SyntaxKind::Eq { return; }` turns the panic into parsing errors, but I’m not sure whether this is the right solution.
