### ISSUE TITLE
A line is broken on non-breaking space and a hyphen is added

### ISSUE THREAD

**Issue by jakubkaczor** [typst/typst#4593]
### Description

I expect lines not to be broken on non-breaking space, but it happens in the following example. Additionaly, a hyphen is inserted which is also unexpected. The parameters set in the example are important, including `font` and `lang`. Look for the fragments “10 maja 2018” and “z dnia 27 kwietnia 2016”.

```typst
#set page(paper: "a4", margin: (y: 1.5cm, x: 4.3cm))
#set text(lang: "pl", font: "Source Serif 4", size: 10pt)
#set par(justify: true)

Wyrażam zgodę na przetwarzanie moich danych osobowych dla potrzeb
niezbędnych do realizacji procesu rekrutacji (zgodnie z~ustawą
z~dnia~10~maja~2018~roku o~ochronie danych osobowych (Dz.~Ustaw z~2018,
poz.~1000) oraz zgodnie z~Rozporządzeniem Parlamentu Europejskiego
i~Rady~(UE)~2016/679 z~dnia~27~kwietnia~2016~r. w~sprawie ochrony osób
fizycznych w~związku z~przetwarzaniem danych osobowych i~w~sprawie
swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/
WE~(RODO)).
```
![The output of the code above.](https://github.com/user-attachments/assets/70ad465f-897d-40dc-801f-e1d9ca76368e)

I hope the font is popular enough that it is not problematic for you to reproduce. I tried simpler examples, but the line broke at words instead of non-break spaces.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
I believe this was fixed by https://github.com/typst/typst/pull/4498. If you can still reproduce this with the development version, please post an example!

**Comment by jakubkaczor** [comment]
That is right. Fixed on main branch. Thanks.
