### ISSUE TITLE
`historical-ligatures: true` does not enable historical ligatures

### ISSUE THREAD

**Issue by ghost** [typst/typst#4601]
### Description

```
#set text(font: "EB Garamond 12", historical-ligatures: true)
standard

#set text(font: "EB Garamond 12", features: ("hlig": 1))
standard
```

Only the second occurrence of "standard" uses the historical st ligature.
[garamond.pdf](https://github.com/user-attachments/files/16350940/garamond.pdf)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
The "EB Garamond 12" is a red herring here. I can reproduce the behavior with the default font (Linux Libertine), also on main.

**Comment by Enivex** [comment]
I believe the offender may be this line https://github.com/typst/typst/blob/c4dd6fa06227b8c4a04cf488f371f52d5379ef9b/crates/typst/src/text/mod.rs#L1182C15-L1182C16

The name of the feature is `hlig`, not `hilg`
