### ISSUE TITLE
Fractionally sized space used in `layout` pushes out footnote to the next page

### ISSUE THREAD

**Issue by jakubkaczor** [typst/typst#4620]
### Description

```typst
// Only to make SVG output readable
#set page(fill: white)
```
The following renders as expected.
```typst
#{
  lorem(200)
  footnote[test]
  v(1fr)
  lorem(200)
}
```
![test](https://github.com/user-attachments/assets/bf51cdba-bb26-4987-b8e5-3426789f6a4c)

I expect the following to render as the previous, but it doesn't. The footnote is pushed to the next page.

```typst
#layout(_ => {
  lorem(200)
  footnote[test]
  v(1fr)
  lorem(200)
})
```
![test-1](https://github.com/user-attachments/assets/77fd8d58-6bac-4a72-a4a2-72de5d07949a)
![test-2](https://github.com/user-attachments/assets/883946d2-9f00-4aba-ab58-75083691ecdf)

I tested this on both, latest release and on main branch.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
I suspect this may be related to https://github.com/typst/typst/issues/2449

**Comment by laurmaedje** [comment]
Indeed. It's the same thing.

Also for
```typ
#block({
  lorem(200)
  footnote[test]
  v(1fr)
  lorem(200)
})
```

It affects any kind of block-level element.
