### ISSUE TITLE
text in svg with embedded fonts rendered as raster image

### ISSUE THREAD

**Issue by Servostar** [typst/typst#4625]
## Description

Text in SVGs with embedded fonts is rendered into raster images instead of real text. This image is then used instead of the text.

![image](https://github.com/user-attachments/assets/1985363e-d1f5-48c8-a569-53c3ae7d7286)
(Its hard to see in the image without zooming in a bit, but you can make out the pixels of the text in the left side)

For me this is a problem as I would like to use SVGs as *scaleable* images freeded from the limitations of raster images. Replacing some parts of the SVG with said raster images kinda removes the point of using them in the first place. Espacially if the point was to have **selectable** text in the image which is not the case when the SVG is stripped of all text.

## Problem

I would like to have selectable text in SVGs even if they have embedded fonts.

## Details

Tested with Typst v0.11.1 on Windows 11/Archlinux
In case it matters, all tested images were exported with Draw.io

## Workaround

I know the text can be converted into paths and be rendered properly as vector graphic but then text selection doesn't work either.

### Operating system

Windows, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
Almost certainly https://github.com/typst/typst/issues/1421

draw.io creates "fake" SVGs that only works prop in a browser

**Comment by Servostar** [comment]
Certainly not much that can be done about that.
Sad to hear.
