### ISSUE TITLE
`show figure: fig => fig.body` doesn't work anymore

### ISSUE THREAD

**Issue by jbirnick** [typst/typst#4633]
### Description

Consider the following document:

```typ
#show figure: fig => fig.body

#figure()[
  #block[
    This should be displayed as a normal block.
    
    In particular, this shouldn't be centered.
  ]
]
```

When you compile it with `typst 0.11.1 (50115102)`, it works properly. That is, it will show a normal, left-aligned block.
However, if you compile it with the current `main` branch (commit https://github.com/typst/typst/commit/c4dd6fa06227b8c4a04cf488f371f52d5379ef9b), it shows the text centered; so something went wrong.

**Comment by Leedehai** [comment]
Since 0.11 (commit 50115102, May 17) is not in the main branch, I wanted to test this issue on the commit one day after 0.11's release (commit daf3ccbe, May 18), but it turned out the codebase at that time is no longer compilable by the current Rust compiler (version 1.80.0) -- the dev environment is not hermit enough!

So I checked out commit 45366c0 (Jun 24), where the Rust compiler was bumped to 1.79.0. The codebase is compilable, and this issue already existed on that commit.

**Comment by jbirnick** [comment]
Thanks for the analysis, indeed, it looks like this is exactly intended.

Though, can someone explain me why you would want that behavior? To me it seems counterintuitive, because I thought `show` rules would give me _full_ control of the styling.

And what is the current solution if I really just want to display the body of the figure, without _any_ inherited styling?

**Comment by PgBiel** [comment]
The show rule behaves exactly as before, _except_ for alignment. Show rules always inherit styles, you can see this with headings too. But figure was doing a weird thing which didn't let you override the alignment, so after that PR it is properly a style which is configurable through `#show figure: set align(start)` (for example - this code would solve your use case, and is the intended approach).

A more general mechanism, such as some special form of the revoke rules proposal, would be needed to negate _any_ inherited styles in a show rule, but this is not currently supported by Typst, and is orthogonal to the issue at hand.

**Comment by PgBiel** [comment]
Btw, if you were using `show figure: it => it.body` before, you may also have to add `#show figure: set block(breakable: true)` to keep the behavior the exact same, as previously that would also allow the contents of the figure across pages as well, which is no longer the case. (Found this in ctheorems: https://github.com/sahasatvik/typst-theorems/pull/39)
