### ISSUE TITLE
Allow to query the language set for a raw block

### ISSUE THREAD

**Issue by jvoisin** [typst/typst#4639]
### Description

Currently, it's possible to do something like this `#show raw.where(block: true): it => { … }`, it would be nice to have a similar `#show raw.where(language: "python"): it => { … }`,  `#show raw.where(language: false): it => { … }`, or maybe `#show raw.where(language: ["python", "zig"]): it => { … }`

### Use Case

I'm currently using `raw` blocks to draw ascii-art diagrams, in markdown transpiled to typst via pandoc (yes.), and I'd like to center them, but not have real code snippet centered.

An easy solution would be to wrap the diagrams in `figure`, but since I'm writing things in markdown via pandoc, I'd love to only have a single `.typ` with all the typst code living there.

Another less niche use-case would be per-language theming.

**Comment by JamesxX** [comment]
Does `#show raw.where(lang: "py"): ...` not do the trick?

**Comment by jvoisin** [comment]
`#show raw.where(lang: ""): ...` doesn't
