### ISSUE TITLE
SVGs rendered incorrectly, placements, scaling, and markers

### ISSUE THREAD

**Issue by jdbosser** [typst/typst#4641]
### Description

Hi! I have done a quick search among the issues, and have not been able to identify if this or a similar issue is already opened. In that case, please feel free to close this issue. 

I am trying to render a svg in typst v.0.11.1. It is included here. One can probably simplify the svg to isolate the issues. 

Here is the SVG, as rendered by your browser: 
![setup](https://github.com/user-attachments/assets/dfcdaf34-fd6e-4c4f-8b9f-38f07e5eda92)

Here is the SVG, as rendered in chromium: 
![Screenshot from 2024-07-29 15-41-46](https://github.com/user-attachments/assets/3e10a9b2-29d7-4733-ae80-0454ef27f063)

And here is how the svg is rendered in typst. 
![Screenshot from 2024-07-29 15-35-15](https://github.com/user-attachments/assets/f0acc3da-d0bb-4ec1-897d-1d92bf1538a9)

Here are somethings that I take note of: 
* The (subtle) red gradient, close to the "underwater infrastructure", is misplaced an miscaled. 
* There are no arrows on some strokes, indicating the "hydrophone arrays". 
* Some scaling issues. Note the top left corner, where the text "hydrophone array" ends up outside the "water". 

Code
`image("setup.svg")`

Output: 
[new_svg.pdf](https://github.com/user-attachments/files/16414196/new_svg.pdf)

Seemingly, there is very little typst code in the mix here. If you guys use some svg-rendering backend, this issue should likely be opened there instead.

(I have included a reproduction url. Interestingly, even though the typst version is the same, the rendered output is slightly different. In this case, the first issue with the red gradient is solved, and the last issue relating to the scaling. So, seemingly the version in the app and on my local machine produce different output? In this case, only the "arrow heads" are missing)

### Reproduction URL

https://typst.app/project/rKZXclPEO_opIodLHLP_jY

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
Cannot reproduce on main.

**Comment by LaurenzV** [comment]
Yes, I can reproduce this in the webapp. there has been a major update to SVG handling since 0.11 and it seems that all three points are addressed when rendering with the newest development build, so it should be fixed by the next release. Thanks for the report, still!
