### ISSUE TITLE
Symbolic links are no longer traversed when loading fonts

### ISSUE THREAD

**Issue by schmidma** [typst/typst#4649]
### Description

When loading system fonts using `fontdb`, symbolic links are no longer traversed. This leads to not finding all installed system fonts when using the typst compiler.

https://github.com/typst/typst/commit/8f7ba8d4958184366180efeb00ecfe8835c69b11 bumped `fontdb` to `v0.18`. With version `v0.17` (see [CHANGELOG](https://github.com/RazrFalcon/fontdb/blob/master/CHANGELOG.md#0170---2024-05-10)) `fontdb` merged https://github.com/RazrFalcon/fontdb/pull/65, which in turn changed the behavior of loading system fonts behind symlinks. Prior to `v0.17` symlinks where also traversed and searched when loading system fonts, with `v0.17` this behavior changed as [`entry.file_type()`](https://doc.rust-lang.org/std/fs/struct.DirEntry.html#method.file_type) does not traverse symlinks.
`fontdb` seems to be working on a fix and properly traversing symlinks: https://github.com/RazrFalcon/fontdb/pull/68, but this is not yet merged.

Maybe `typst` can revert back to `v0.16` to also include symlinks when searching for system fonts, or should at least bump `fontdb` to the newest release as soon as https://github.com/RazrFalcon/fontdb/pull/68 is merged.

This can be reproduced by having symlinks to additional fonts in e.g. `/usr/share/fonts/`, and listing the available fonts with `typst fonts`. Using `fontdb` on `v0.16` the symlinked fonts are listed, using `v0.17` they are not.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
Reverting is not really an option because that version of `fontdb` is also used in another dependencies (e.g. resvg) which needs to be in sync. So I guess we'll have to wait for the next update.

**Comment by PgBiel** [comment]
@schmidma Thank you very much for your investigation. This seems to match the issues some Nix users were having on Discord. Let's wait for this update.

**Comment by jcdickinson** [comment]
I attempted to open a PR for this, but looks like we're waiting on: https://github.com/RazrFalcon/resvg/issues/800

**Comment by drupol** [comment]
youhou ! Going to test that tonight :)
