### ISSUE TITLE
Allow typst watch --open to specify a command with arguments

### ISSUE THREAD

**Issue by jason-s** [typst/typst#4654]
### Description

I would like Typst to run a Python script whenever a compilation completes. But right now `typst watch --open` only allows the name of a command (without arguments) to run.

### Use Case

Give users more freedom to run an arbitrary command

**Comment by Andrew15-5** [comment]
You can make your script executable and pass in the `"$(realpath script.py)"` or wrap it in shell script file for extra arguments:

```sh
#/bin/sh
exec python3 script.py arg1 arg2
# exec ./script.py arg1 arg2 # I don't remember if you need `./` here.
```

and then pass this script file instead.

I think adding support for arguments would be nice, but you can live without it just fine as I showed you. Plus passing multiple arguments to a single flag is very hard. It becomes super messy when quotes and escaping comes into play. There are very few CLIs that do this (`find -exec cmd arg1 arg2 \;`).

I haven't tested any of that, but it all should work.

**Comment by jason-s** [comment]
I can't do either. Windows doesn't support #/bin/sh, and I don't have enough familiarity with a C compiler to create a special executable to do what I want, which seems like overkill.

I have a workaround for now (wrote a script to check the file mod time of the .pdf file), but I do think there should be a way to pass in arguments.

**Comment by Andrew15-5** [comment]
> Windows doesn't support #/bin/sh

I don't like shindows, but I'm pretty sure you can do something similar with a `.bat` file or something. But I wouldn't be surprised if it just doesn't have any alternative at all.

**Comment by laurmaedje** [comment]
`--open` only runs once, so it wouldn't really work anyway, if I'm understanding the requirement correctly. But I think watching the PDF file is a good solution, so I don't think this warrants a new argument.
