### ISSUE TITLE
Embed the Typst source code into the PDF

### ISSUE THREAD

**Issue by hadim** [typst/typst#4656]
### Description

It would be nice to be able to automatically embed the Typst source code into the produced PDF.

See this similar project https://github.com/prefix-dev/pixi-pdf, which allows embedding any directory (source code for example) into a PDF.

### Use Case

It would be great for reproducibility, but it would also allow opening a Typst project into the web app by simply drag and dropping the PDF in it.

You can see it as a feature that makes any Typst PDF "editable" in some sort.

**Comment by Myriad-Dreamin** [comment]
For the editable property, you'll have to embed all project resources, like images, otherwise it is incomplete. This will increase size of the pdf file a lot.

**Comment by Enivex** [comment]
Duplicate of https://github.com/typst/typst/issues/1465
