### ISSUE TITLE
Can not select Chinese characters in compiled pdf file

### ISSUE THREAD

**Issue by Honghe** [typst/typst#4663]
### Description

The source code is:
```typ
bala

test 文档处理

hehe
```
But I can not select the Chinese characters in the compiled pdf file, the popular pdf viewer used is SumatraPDF.

https://github.com/user-attachments/assets/bb9f233f-cc71-4b92-8e7f-3147365a63e5

I have tried to check the `streams` ojb in the PDF file, but it is compressed.

[demo_typst.pdf](https://github.com/user-attachments/files/16478689/demo_typst.pdf)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
Can you attach the actual PDF file that was produced?

**Comment by Honghe** [comment]
> Can you attach the actual PDF file that was produced?

Done

**Comment by LaurenzV** [comment]
I've just tried your PDF in Chrome, Firefox, Acrobat and Apple Preview, and it works fine there. Must be an issue specific to your viewer...

**Comment by Honghe** [comment]
Thanks, I will create a bug report for SumatraPDF.

**Comment by laurmaedje** [comment]
Will close this then.

**Comment by Honghe** [comment]
It is fixed in [Version 0.12.0, Release Candidate 1 (October 3, 2024)](https://github.com/typst/typst/releases/tag/v0.12.0-rc1)
