### ISSUE TITLE
`pagebreak` in `heading` makes page numbering styled like heading

### ISSUE THREAD

**Issue by jbirnick** [typst/typst#4671]
### Description

Here is a minimal (non) working example:

```typ
#set page(numbering: "1 / 1")

#show heading: it => {
  pagebreak(weak: true)
  set text(weight: "regular", size: 5em)
  it
}

This is the first page. Look at the page numbers. They are normal.

But on the second page, there is no text after the heading.
Look how the page numbering looks different there.

= A Pagebreak-Style Heading
```

The page numbers on the first page are normal. On the second page, however, they are bold and have a bigger font size. I think they probably are styled like a `heading`.

In order to make this issue happen, it seems like two three things need to come together:

- you need to have page numbering, of course (or i guess generally a footer maybe?)
- you need to make a `pagebreak()` in your `heading` design
- there shouldn't be anything after the critical heading (if you put some text after the last heading above, the page numbers are again correctly designed)

Another interesting observation: Please note that the style of the page numbers is _not_ the text design that I put in my show rule. Indeed, in my show rule the weight is regular and the text size is `5em` for demonstration, but the page numbers are bold and not that large. Instead, they seemed to be styled like the default headings are.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
https://github.com/typst/typst/issues/241
