### ISSUE TITLE
`#show` does not affect all spaces character

### ISSUE THREAD

**Issue by louleke7** [typst/typst#4672]
### Description

The following code
```
This sentence has spaces ; and a semicolon.
This one has an exclamation mark with a space before !
#show " ": p => box[\u{2713}]
This sentence has spaces ; and a semicolon.
This one has an exclamation mark with a space before !
```
produces the following results
![Capture d’écran_2024-08-04_16-36-31](https://github.com/user-attachments/assets/bc3c4536-2b64-4310-8245-a7f75c94fc8f)
spaces before ; and ! are not affected by `#show " "`, and further testing indicates the same results for . , : and ?

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
See https://github.com/typst/typst/issues/86

**Comment by yodatak** [comment]
For now it seem to be fixed and i would be intersiting to have some french work for typography https://github.com/typst/typst/pull/4876
