### ISSUE TITLE
Parsing of lists with content blocks

### ISSUE THREAD

**Issue by memeplex** [typst/typst#4677]
### Description

```
foobar

- a

  - b
  - c

foobar

- a #[

  - b
  - b
]

foobar

- a
#[
  - b
  - b
]
```

Shouldn't all three examples render the same way? The third one doesn't.

This one is even stranger:

```
foobar

- a

  - b
  - c

foobar

- a
#[

  - b
  - b
]
```

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
The content block needs to be at the same level if you want it to be part of the same list

```
- a
  #[
    - b
    - b
  ]
```

(You can also forego the syntax sugar)

**Comment by memeplex** [comment]
I don't find it intuitive because AFAICU it's the same whitespace in all three cases, but ultimately it's a decision about syntax, ok.

Now, if the reason is that content block must be at the same level to be part of the same list, why the numbering is consecutive here:

```
+ a
#[
  + b
  + c
]

=>

1. a
2. b
3. c
```

If you compare the two following cases:


```
+ a #[
  + b
  + c
]

+ a
#[
  + b
  + c
]
```

the difference is not whether the block is part of the same list or not (it is in both cases, and in some sense it is even more in the second example), but whether the block creates a sublist or not.

So maybe the rule is: the block must be in the same line of an item to create a sublist of that item?

**Comment by Enivex** [comment]
Yes, that's what I meant. Edited my comment

**Comment by memeplex** [comment]
Great, I find that version more intuitive, it also helps understand that indentation in not actually needed inside the block:

```
+ a #[
+ b
+ c
]
```
