### ISSUE TITLE
Empty line between heading and tight list in source adds slight vertical spacing

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#4684]
### Description

Adding an empty line between a heading and a tight list in the source file results in a slight additional vertical space between the heading and the list in the output.

This is illustrated in the following example (magenta lines in the output are added for clarity).

```typ
#grid(
  columns: 2,
  gutter: 0.5cm,
)[
  = Heading

  - List
][
  = Heading
  - List
]
```

![The first list is slightly lower than the second list.](https://github.com/user-attachments/assets/059f7532-5b34-4fa0-a8f4-d13169d10da5)

### Typst version

- [X] I am using the latest version of Typst (v0.11.1).

**Comment by laurmaedje** [comment]
This _should_ be fixed on main.

**Comment by MDLC01** [comment]
This is indeed fixed on main. Sorry for the noise.

**Comment by laurmaedje** [comment]
No worries.
