### ISSUE TITLE
Single and double bar `lr` delimiters are rendered differently

### ISSUE THREAD

**Issue by njericha** [typst/typst#4696]
### Description

I am not sure what the intended behaviour for many of these examples but consider the following Typst output.

![image](https://github.com/user-attachments/assets/983ea934-73d1-4588-8675-568d121d693a)

# Inconsistency 1: Spacing
```typst
$abs(v)_2^2$
$lr(|v|)_2^2$
$lr(| v |)_2^2$
$lr(bar v bar)_2^2$
```

all produce the same output whereas 

```typst
$lr(∥v∥)_2^2$
$lr(∥ v ∥)_2^2$
$lr(parallel v parallel)_2^2$
```
produce extra spacing when compared to `$norm(v)_2^2$`.

# Inconsistency 2: sub/superscripts
Without the `lr` delimiters, 
```typst
$|v|_2^2$
$| v |_2^2$
$\| v \|_2^2$
$bar v bar_2^2$
```
are rendered with "squished" sub/superscripts whereas

```typst
$∥v∥_2^2$
$∥ v ∥_2^2$
$\∥ v \∥_2^2$
$parallel v parallel_2^2$
```
are rendered with bottom/top limits.

# Inconsistency 3: adding space in math mode

There is no visual difference between
```typst
$∥v∥_2^2$
$∥ v ∥_2^2$
```
but there is between
```typst
$|v|_2^2$
$| v |_2^2$
```
# See also
I came across this issue using Quarto and opened an issue with them: https://github.com/quarto-dev/quarto-cli/issues/10424 ,
but they use Pandoc to convert between formats, so I opened an issue there as well: https://github.com/jgm/texmath/issues/238 .

As it stands, Pandoc would have to convert LaTeX's `$\left\lVert v \right\rVert$` directly to Typst's `$norm(v)$` to produce a document that is correctly rendered. It may be more practical to convert to Typst with `$lr(parallel v parallel)_2^2$`, but this would get rendered incorrectly.

### Reproduction URL

https://typst.app/project/rmU7DfYGZs8qPEUi2gUeJf

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
You're using the wrong character

`∥` / sym.parallel is U+2225, while the one you actually want is `‖` / bar.v.double (U+2016)

As for the differences between using lr() and not, that's down to fences no longer automatically matching because it caused too many false positives https://github.com/typst/typst/commit/fe402759c03eb93cefc2879e751b8e732891bd3e . `abs()` and `norm()` are the way to go here.
