### ISSUE TITLE
Slanted fraction in equation

### ISSUE THREAD

**Issue by memeplex** [typst/typst#4698]
### Description

Shouldn't this produce a slanted fraction in math mode?

```typst
#set text(fractions: true)
#show math.equation: set text(fractions: true)

- regular text: 1/9
- equation text: $"1/9"$
```

BTW, it would be nice if `$1/9$` also produced slanted fractions in inline equations when `fractions: true`

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
`fractions` is specifically an opentype feature for text fonts, it has nothing to do with math.

**Comment by wrzian** [comment]
Was going to say the same, you can use a backslash escape, quote, or the existing `slash` symbol for now. It's desired to make the frac function's syntax customizable in the future, but not soon.

You can also try using a custom fraction function for math fractions, here's an example:
```typ
// Inline fraction; displays like ½, ⅓, etc.
#let ifrac(num, denom) = {
  move(dx: -1.5pt, dy: -1pt,
    math.attach("\u{2215}", // U+2215 ∕ Division Slash
      tl: move(text(math.equation(num), size:1.2em), dx: 1.5pt),
      br: move(text(math.equation(denom), size:1.2em), dx: -1pt, dy: -2pt),
    )
  ) + h(-2.5pt) // reduce the width
}

#show math.equation.where(block:false): it => {
  show math.frac: f => ifrac(f.num, f.denom)
  it
}
```

The downside is that this also affects manual usage of the `frac` function inline, so you can't recover the normal fractions without defining a separate function.

**Comment by memeplex** [comment]
> fractions is specifically an opentype feature for text fonts, it has nothing to do with math.

I still fail to see why this implies that it shouldn't work for text mode content inside math mode as in my example `$"1/9"$`.

**Comment by Enivex** [comment]
> > fractions is specifically an opentype feature for text fonts, it has nothing to do with math.
> 
> I still fail to see why this implies that it shouldn't work for text mode content inside math mode as in my example `$"1/9"$`.

Because strings in math mode are currently typeset using the math font, and they typically do not have the feature
