### ISSUE TITLE
Path with multiple subpaths

### ISSUE THREAD

**Issue by joneuhauser** [typst/typst#4699]
### Description

Related to https://github.com/typst/typst/issues/4123, but I'm not convinced of the syntax suggestion there.

In order to draw paths with holes, it would be necessary to specify that a path has multiple subpaths and their fill rule.

I'm not sure how the syntax would look like. For backwards compatibility reasons, I don't think the syntax of `#path` should be changed, there should probably be a new function `#compound_path` or similar:

```
#compound_path(
  fill: blue.lighten(80%),
  stroke: blue,
  fill-rule: evenodd,
  (path1, closed), 
  (path2, closed),
)
```

where path1 is a list of vertex specifications as in the `#path`

### Use Case

In order to implement https://matplotlib.org/stable/gallery/shapes_and_collections/donut.html#sphx-glr-gallery-shapes-and-collections-donut-py in typst-mpl-backend, this feature is required.

**Comment by Emm54321** [comment]
I made a simple implementation of this feature by allowing separating components in #path by `auto`/`true`/`false` (`true`: end a closed component, `false`: end an open component, `auto`: use the value of the `closed` parameter).

```typst
#path(
  closed: true,
  fill-rule: "even-odd",
  fill: yellow,
  stroke: black,
  (0mm, 20mm),
  (20mm, 20mm),
  (20mm, 0mm),
  auto, // separate the two triangles
  (7mm, 17mm),
  (17mm, 17mm),
  (17mm, 7mm),
  // implicit auto at the end unless an explicit marker is used
)
```

Not sure it's the best syntax, but it doesn't break any existing code, and it is a very simple patch.
I can submit a PR if you're interested.

**Comment by joneuhauser** [comment]
@Emm54321 I suggested this kind of syntax on discord, but @laurmaedje suggested a different syntax:
```
#path(
path.moveto(5mm, 2mm),
path.lineto(1mm, 2mm, relative: True),
...
)
```

that is, basically following the ubiquitous SVG syntax. The `relative` parameter would be optional.

**Comment by Emm54321** [comment]
This would be cleaner indeed. Implementing the syntax I used was a 10min job. This requires more work but doesn't seem that complicated.

**Comment by Emm54321** [comment]
I got it working with the syntax above. It supports `path.moveto()`, `path.lineto()`, `path.cubicto()`, `path.quadto()` and `path.close()`.
It currently supports several syntaxes, e.g.:
```typst
path.curveto(cstart: (10mm, 0mm), cend: (10mm, 30mm), end: (0mm, 30mm))
path.curveto((10mm, 0mm), (10mm, 30mm, (0mm, 30mm)) 
path.curveto(10mm, 0mm, 10mm, 30mm, 0mm, 30mm) // are equivalent.
```
or a mix of those (missing named parameters are taken from positional arguments). Not  sure if this is should be kept or if a single syntax should be chosen.
The start control point can be omitted, and is then mirrored from the previous one. The `relative` flag is supported.
The old syntax is still supported too.

**Comment by laurmaedje** [comment]
Feel free to open a PR. We can discuss the details there.
