### ISSUE TITLE
String coercion on `str(-1)` different from "-1"  as dictionary does not find element for `str(-1)` (but does for `"-1"`)

### ISSUE THREAD

**Issue by hbierlee** [typst/typst#4704]
### Description

Hi,
It seems there is some different when using string coercion on negative numbers, eg: on `str(-1)` different from `"-1"`  as dictionary does not find element for `str(-1)` (but does for `"-1"`)

```typ
#{ "hello " + ("-1": "world").at("-1") }
#{ "hello " + ("-1": "world").at(str(-1)) }
```

Errors only on the second line:

```
|| error: dictionary does not contain key "−1" and no default value was specified
||   ┌─ conv-st.typ:2:14
||   │
|| 2 │ #{ "hello " + ("-1": "world").at(str(-1)) }
||   │               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
|| 
```

Cheers,

Henk

### Operating system

Ubuntu

### Typst version

- [X] I am using the latest version of Typst

**Comment by MDLC01** [comment]
This is because `str(-1)` uses U+2212 MINUS SIGN instead of U+002D HYPHEN MINUS.
