### ISSUE TITLE
Lastest git commit breaks font importing

### ISSUE THREAD

**Issue by Naville** [typst/typst#4710]
### Description

I got weired ``weired unknown font family`` when switching from latest release to git version.

![image](https://github.com/user-attachments/assets/5bd29a09-299b-424a-bac5-61591b3c2a2d)
![image](https://github.com/user-attachments/assets/a4cdc211-b8af-4890-ac66-c8955981e393)

This works in last stable release version.
I wonder if this font lookup failure is due to mismatching font name (``Heiti`` vs ``heiti``)

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
All font names are matched case insensitive (or rather lowercased before matching), so that shouldn't be the cause.

**Comment by laurmaedje** [comment]
Note that the warning is new, so the problem _might_ have existed before. But still strange since `typst fonts` shows it and the compiler complains.

**Comment by wdscxsj** [comment]
I think this issue was introduced shortly after b07607d3.

**Comment by laurmaedje** [comment]
> I think this issue was introduced shortly after https://github.com/typst/typst/commit/b07607d35e697be3dd5e56945b16afa8103a491e.

The linked commit is the latest commit on main.

**Comment by Naville** [comment]
I switched to main to attempt to fix emoji support this morning (~7hrs ago). Previously was always the 0.11.1 stable.

In case someone wants to do a bisect

**Comment by a31474** [comment]
![1](https://github.com/user-attachments/assets/31a8d760-67bd-414a-9d31-874dea99e0a1)

If you use "--ignore-system-fonts" , it will work. And the generated PDF used the correct font.
