### ISSUE TITLE
Compiler assertion fails if local package cannot be found

### ISSUE THREAD

**Issue by inferiorhumanorgans** [typst/typst#4718]
### Description

```
#import "@our-local-ns/el-package:0.1.0"
```

```
$ ~/typst/typst compile --package-path=packages foo.typ
thread 'main' panicked at crates/typst-kit/src/package.rs:154:9:
assertion `left == right` failed
  left: "our-local-ns"
 right: "preview"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
$ file packages/our-local-ns/el-package/0.1.0
packages/our-local-ns/el-package/0.1.0: cannot open `packages/our-local-ns/el-package/0.1.0' (No such file or directory)
```

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Regression from #4540 - seems like the `preview` namespace check below was removed:  https://github.com/typst/typst/blob/810491c9d31b614a435020f888fbd380e8e039a1/crates/typst-cli/src/package.rs#L60-L66

vs now:

https://github.com/typst/typst/blob/672f6e5f97c2bdcd3e94754c9486869bf7b8de56/crates/typst-kit/src/package.rs#L87-L91

**Comment by tingerrr** [comment]
Don't know how I maged that, easy fix, but I won't be home for a few hours,so you could do it too.

**Comment by laurmaedje** [comment]
The way Git presents the changes in a refactoring PR like #4540 unfortunately makes it super hard to review so that both this and #4710 slipped by me.
