### ISSUE TITLE
Complex numbers and the number(?) i

### ISSUE THREAD

**Issue by nick17773** [typst/typst#4719]
### Description

I'm surprised at how much this platform pushes an engineering use case, with the inclusion of even an IEEE template, but still doesn't have the capability to calculate and work with complex algebra? Whenever I try to compute i mathematically I'm told that I can't do it. Isn't this why i was made in the first place? 

For starters, at consider an implementation of i as a constant, and the ability to compute it, I.e

`calc.sqrt(-1)` should, evidently return `i`, as opposed to a compiler error.

### Use Case

This would be useful for engineers, such as myself, either practicing or student, to use this common variable/number that tends to crop up in engineering, mainly in electrical, electronic and computer engineering. 

Why shouldn't I be able to compute an imaginary number?

**Comment by Enivex** [comment]
https://github.com/typst/typst/issues/497

**Comment by laurmaedje** [comment]
Typst is a typesetting system rather than a scientific computing system, so it is not really made for doing complex calculations.
