### ISSUE TITLE
Some characters in Indic Malayam unicode fonts   rendering wrong

### ISSUE THREAD

**Issue by theauditor** [typst/typst#4723]
### Description

To replicate

1. Copy and paste the below text to a `.typ` file.
` ഫ്രാൻസിയേയും  -  മാത്രം -  പ്രതീക്ഷയും - പ്രീഡിഗ്രി - `
`
2.  compile
3. പ്രീഡിഗ്രി  will appear as 
![image](https://github.com/user-attachments/assets/4a86454b-e824-453e-ac20-75a039846cd2)
4. where it should appear as
![image](https://github.com/user-attachments/assets/fbe1d101-c94a-423f-b40c-4f42277e8e2d)

 
 Seems to be some parameter settings issue within the compiler. 

### Typst version

- [X] I am using the latest version of Typst

**Comment by theauditor** [comment]
Issue does not seem to affect a single font - "Suruma"
As its a older design it somehow works.

**Comment by LaurenzV** [comment]
Can reproduce with rustybuzz 0.14, the output looks as expected with rustybuzz 0.18. So this issue should be fixed once we update the dependency.

**Comment by theauditor** [comment]
Is there a manual way I can update it and compile. any guide will be nice.
