### ISSUE TITLE
Shorthand for double/triple/quadruple prime symbols

### ISSUE THREAD

**Issue by psvenk** [typst/typst#473]
It would be nice if multiple primes could be written in a formula as `''`, `'''`, and `''''`, like in LaTeX, instead of needing to write out `prime.double`, `prime.triple`, and `prime.quad`, so that higher-order ODEs can be written compactly without needing to resort to something like this:
```typst
#let pp = sym.prime.double
...
$ y pp(t) + a y'(t) + b y(t) = 0 $
```

**Comment by user202729** [comment]
With proper kerning (#359), two prime symbols should be indistinguishable from a double-prime symbol anyway.

Although it may makes more sense to use the Unicode prime.double etc. characters if they're available...
