### ISSUE TITLE
Add `typst` command similar to `\TeX` and `\LaTeX` macros

### ISSUE THREAD

**Issue by flgrubm** [typst/typst#4731]
### Description

A function that inserts a logo-like stylised version of the string "Typst" or "typst", potentially in all caps or small caps. This would be similar to the (La-)TeX macros `\TeX` and `\LaTeX` that produce the following output:

![Screenshot_20240811_162331](https://github.com/user-attachments/assets/f9a39f99-bb4a-4e56-84ea-a2dd33179aa0)

### Use Case

Easily and clearly refer to the Typst compiler in a more beautiful way than just writing "Typst" or "typst". E.g. in the preamble of my document I would like to add a line similar to

`
This document was typeset using #typst version #sys.version.
`

**Comment by xkevio** [comment]
Quoting from https://discord.com/channels/1054443721975922748/1054443722592497796/1107039477714665522 and @laurmaedje himself:
> [It is] just "Typst" in whatever font the surrounding text is and capitalized.

Therefore, it would not make any sense to include such a function.
