### ISSUE TITLE
0pt width reported for box with non-zero relative width

### ISSUE THREAD

**Issue by memeplex** [typst/typst#4735]
### Description

The following example:

```typst
#let thing(body) = context {
  let size = measure(body)
  [Width of "#body" is #size.width]
}

#thing(box(width: 10%, [Hey]))
```

which is a variation on this other one from the documentation of `measure`:

```typst
#let thing(body) = context {
  let size = measure(body)
  [Width of "#body" is #size.width]
}

#thing[Hey] 
```

computes a width of 0pt for a content that at the context where it's instantiated has a definite, non-zero width.

I believe it should report the actual width of the content, even though it was specified in a relative way.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Measuring always happens in an infinitely large space by default which means 10% isn't well defined. You can combine measure with `layout` to make it dependent on the current available space.

**Comment by memeplex** [comment]
Ok, I see. But suppose you're writing a general routine that takes some rectangular content and puts a drop shadow behind it. You don't know whether the width or height of that content was given in a relative or absolute way. Now, you can measure it and take 0pt as a (perhaps ambiguous) signal that the length is relative, but you still don't know the percentage. Not to say that this case-by-case approach would be cumbersome, if doable.

For example, in https://typst.app/docs/reference/layout/layout/ there is this example:

```typst
#layout(size => {
  let half = 50% * size.width
  [Half a page is #half wide.]
})
```

So far so good, but I need that 50%. For example, I have this titled box to add a drop-shadow to:

```typst
#let boxy = context {
  stack(
    rect(
      align(center, text(size: 20pt, weight: "regular", "Title")),
      fill: red.lighten(50%),
      width: 30%,
      inset: 5pt,
      radius: (bottom: 0pt, rest: 3pt),
      stroke: (bottom: 0pt, rest: 0.5pt)
    ),
    rect(
      fill: red.lighten(90%),
      width: 30%,
      inset: (top: 5pt, bottom: 5pt, rest: 10pt),
      radius: (top: 0pt, rest: 3pt),
      stroke: (top: 0pt, rest: 0.5pt)
    )[
      #set text(size: 15pt)
      - First item
      - Second item
      - Third item
    ]
  )
}
```

And I need to get to something like `#layout(size => size.width * 0.3)`, but I don't have that 0.3.

How can I proceed in a case like this?

**Comment by laurmaedje** [comment]
In the upcoming version, `measure` will take optionally a `width` and `height` that define the available space. When passing the values provided by `layout` to it, I think it will do what you want.

Maybe one can somehow emulate this in the Typst 0.11.1, but it's probably very hairy, if at all possible.

**Comment by memeplex** [comment]
With the latest development revision `#layout(size => measure(boxy, ..size))` shows `width: 136.06pt, height: 82.27pt`, so we can close this.

That said, I'm still perplexed about the 141.13pt in `(width: 0pt, height: 141.13pt)` when the space is infinite.

**Comment by laurmaedje** [comment]
The lack of available width might have forced weird line breaks.
