### ISSUE TITLE
Block spacing inconsistency after headings

### ISSUE THREAD

**Issue by martinstefanik** [typst/typst#4740]
According to the documentation of `block`, the `spacing` parameter is "_shorthand to set above and below to the same value_". (see [here](https://typst.app/docs/reference/layout/block/#:~:text=This%20is%20shorthand%20to%20set%20above%20and%20below%20to%20the%20same%20value.)).

But

```typst
= Introduction
#block(spacing: 2em)[#lorem(20)]
```
and

```typst
= Introduction
#block(above: 2em, below: 2em)[#lorem(20)]
```

lead to different outputs. The space after the heading collapses in the first case, whereas it does not in the second case.

The same thing happens if the heading is followed by a block quote when the spacing of the block quote is adjusted using `#show quote.where(block: true): set block(spacing: 2em)` and `#show quote.where(block: true): set block(above: 2em, below: 2em)`. And presumably, anything else wrapped in a block.

**Comment by EpicEricEE** [comment]
Currently, `above` and `below` take precedence over `spacing`. As headings internally set their spacing via the `above` and `below` properties, the `spacing` of the block in the first example is ignored. This behavior was changed in #4390 though, so this is no longer the case on main.
