### ISSUE TITLE
block: above and below render spacing useless

### ISSUE THREAD

**Issue by memeplex** [typst/typst#4746]
### Description

This is the documentation for three parameters of `block()`:

- spacing: The spacing around this block. This is shorthand to set above and below to the same value. Default: 1.2em

- above: The spacing between this block and its predecessor. Takes precedence over spacing. Default: 1.2em

- below: The spacing between this block and its successor. Takes precedence over spacing.  Default: 1.2em

But:

```typst
---
#block(spacing: 0pt, [block])
---

---
#block(above: 0pt, [block])
---

---
#block(below: 0pt, [block])
---
```

will render as:

```
---

block

---


---
block

---


---

block
---
```

I understand that if both above(/below) and spacing are given, then above(/below) wins as stated in the second(/third) item.

But when only spacing is given, shouldn't it set both above and below as stated in the first item?

Otherwise I fail to see how can spacing ever be useful, specially given that above and below already start initialized by default.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by memeplex** [comment]
Notice also that the example given in the reference for spacing is actually an example of above/below:

```
#set align(center)
#show math.equation: set block(above: 8pt, below: 16pt)
```

**Comment by laurmaedje** [comment]
The weirdness with spacing/above/below should be fixed since https://github.com/typst/typst/pull/4390. Now, `block.spacing` is really 100% equivalent to setting `block.above` and `block.below` to the same value.
