### ISSUE TITLE
Spacing between blocks and lists

### ISSUE THREAD

**Issue by memeplex** [typst/typst#4748]
### Description

In https://typst.app/docs/reference/layout/box/:

> All elements except inline math, text, and boxes are block-level and cannot occur inside of a paragraph.

In https://typst.app/docs/reference/layout/block/:

> below: The spacing between this block and its successor. 

The docstring for above goes further:

> Can be used in combination with a show rule to adjust the spacing around arbitrary block-level elements.

(I think that the asymmetry is unintentional, but obviously can't say for sure)

So from the above I infer that lists are block-level and that spacing separates arbitrary block-level elements.

Now:

```typst
#block(below: 3em, [Block])
- item 1
- item 2

#block(below: 3em, [Block])
#list([item 1],[item 2])
```

won't insert any spacing between blocks and lists.

I understand the special case when a list immediately follows a paragraph, but I believe in the examples above spacing should be honoured.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This was changed in https://github.com/typst/typst/pull/4396, so it's fixed on main.
