### ISSUE TITLE
Typst won't hyphenate specific footnote words in languages other than the main one

### ISSUE THREAD

**Issue by ironupiwada** [typst/typst#4753]
### Description

As it is well known, Typst allows for setting hyphenation of certain words globally with the `#show` function. This works when I generate a bibliography where certain non-Polish words are incorrectly hyphenated (my document uses Polish as a main language). An example:

`#show "Routledge": text("Routledge", lang: "en")`
gives the correct `Rout-ledge` in bibliography instead of `Routled-ge` forced by the main Polish language:

![obraz](https://github.com/user-attachments/assets/a984d61a-de15-458a-a486-61bb9e671327)

However, such hyphenation rules don't work for automatic footnotes. When I set `#show "Cambridge": text("Cambridge", lang: "en")` (normally hyphenated as `Cam-bridge` in English) in the same document, a footnote shows:

![obraz](https://github.com/user-attachments/assets/69d4c815-f773-43af-9ee1-ab3a8763a9e0)

To clarify the bug report somewhat, I am using a Chicago-like note style, with a custom CSL file and the "pl" locale.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by ironupiwada** [comment]
Sorry, my mistake. The hyphenation works for footnotes as well if the `#show` functions with `hyphenate` are put into the very top of the document.

**Comment by laurmaedje** [comment]
Yeah, similar to https://github.com/typst/typst/issues/2765.
