### ISSUE TITLE
Text ill-aligned when emojis are present

### ISSUE THREAD

**Issue by memeplex** [typst/typst#4755]
### Description

```typst
- Without emoji.
- With emoji #emoji.thumb.down
- Without emoji.
```

In the web app it's subtle:

<img width="130" alt="image" src="https://github.com/user-attachments/assets/d65cbc96-f06b-484f-b644-eedaf75ec116">

Locally, compiling to pdf (the emoji is not there, I don't know why, but anyway the alignment problem is visible):

<img width="130" alt="image" src="https://github.com/user-attachments/assets/afbdb5af-cc7c-4e92-8df1-28de90686d20">

Locally, previewing with VSCode + tinymist:

<img width="130" alt="image" src="https://github.com/user-attachments/assets/48fc5635-eda0-485c-875d-0de1963c5249">

My environment: typst 0.11.1 and macOS Sonoma 14.4.1

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by memeplex** [comment]
Another local combinations:

```typst
#set text(font: ("Helvetica", "Apple Color Emoji"))

- Without emoji.
- With emoji #emoji.thumb.down
- Without emoji.
```

<img width="130" alt="image" src="https://github.com/user-attachments/assets/d1a1711b-5584-497a-a14e-325382e3cb87">

```typst
#set text(font: ("Helvetica", "Noto Color Emoji"))

- Without emoji.
- With emoji #emoji.thumb.down
- Without emoji.
```

<img width="130" alt="image" src="https://github.com/user-attachments/assets/4588b226-423b-4aec-8372-14f94d32c346">

Neither of them correctly exports the emoji to pdf.

**Comment by laurmaedje** [comment]
The alignment problem is probably due to similar cause as the motivation here: https://github.com/typst/typst/issues/4224

The PDF export doesn't work in 0.11.1, but should work on main.

**Comment by laurmaedje** [comment]
In combination, this is a mix of:
- https://github.com/typst/typst/issues/1204
- https://github.com/typst/typst/issues/4224
- https://github.com/typst/typst/issues/144

**Comment by memeplex** [comment]
I've reading the linked issues and I agree. Interesting reading, BTW, but what a rabbit hole...

pdf output of `typst 0.11.0 (d84a7e42)`:

- With Apple Color Emoji:

<img width="139" alt="image" src="https://github.com/user-attachments/assets/a3097f51-3808-4b58-86a9-867b2bed6735">

- With Noto Color Emoji:

<img width="139" alt="image" src="https://github.com/user-attachments/assets/9912cb70-dc84-43b8-a69c-be0ab21aa698">

So:

1. Alignment is off as expected per https://github.com/typst/typst/issues/1204, but for Noto this is subtler.
2. pdf output is fixed.
3. The weird clipping of Noto is fixed.
