### ISSUE TITLE
Indented nested raw blocks overindent by 1

### ISSUE THREAD

**Issue by bugsbugsbux** [typst/typst#4779]
### Description

Putting a raw block into an indented raw block overindents the output by 1 space. Here is an example:

~~~typ
The rects are just for visualization purposes.

This correctly indents:
#rect(
    ````
    111
    foo
    bar
    111
    ````
)

This overindents by 1 space:
#rect(
    ````
    ```
    foo
    bar
    ```
    ````
)

Here are two workarounds:
+ dont indent:
    #rect(
````
```
foo
bar
```
````
)
+ overindent ending marker:
    #rect(
        ````
        ```
        foo
        bar
        ```
            ````
    )
~~~

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
sounds like #3820 but i think it is already on 0.11.1. so maybe this is a new issue

**Comment by Enter-tainer** [comment]
![image](https://github.com/user-attachments/assets/d92dbd51-6424-4f80-b31b-6c6897c7e2d1)

I don't see the difference between them. Are you really using latest typst? @bugsbugsbux

**Comment by Enter-tainer** [comment]
![image](https://github.com/user-attachments/assets/dfcecfe2-8bd5-43b7-bf52-f3212949ff4b)

❯ typst --version
typst 0.11.1

~/notes via 🐍 v3.12.4 via t v0.11.1 
❯ typst compile test.typ test.png

**Comment by Enter-tainer** [comment]
`````
This correctly indents:
#rect(
    ````
    111
    foo
    bar
    111
    ````
)

This overindents by 1 space:
#rect(
    ````
    ```
    foo
    bar
    ```
    ````
)
`````

**Comment by Enter-tainer** [comment]
Is it specific to nix packaging?

**Comment by bugsbugsbux** [comment]
sorry, this problem seems to be caused by the <https://github.com/nvarner/typst-lsp> neovim plugin, which autocompiles the document for you and I assumed it used the typst from PATH. when I actually use the installation from PATH, it compiles just fine.

**Comment by Enter-tainer** [comment]
> sorry, this problem seems to be caused by the <https://github.com/nvarner/typst-lsp> neovim plugin, which autocompiles the document for you and I assumed it used the typst from PATH. when I actually use the installation from PATH, it compiles just fine.

you may want to switch to tinymist then
