### ISSUE TITLE
Question: How can I create an element function?

### ISSUE THREAD

**Issue by werifu** [typst/typst#478]
> Content consists of elements with fields. When constructing an element with its element function, you provide these fields as arguments and when you have a content value, you can access its fields with [field access syntax](https://typst.app/docs/reference/scripting/#field-access).

Text above is from https://typst.app/docs/reference/types/content/ 

What is an element function? I cannot find any definition about it.

Actually, I am having trouble with counting appear times of an element, my code is following:

```typst
#let img(image, caption: "") = {
  set align(center)
  image
  locate(loc => {
    let chapt = counter(img).at(loc).at(0)
    "Fig" + str(chapt) + "  " + caption
  })
}
```

It's like another figure, which has a more customized numbering label. I need count the appear times of `#img` at some locate just like `heading` or `figure`.

When I want to compile it, I get:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/53432474/229103917-e9f0a76d-fd29-40b6-ad83-bc28b4767af5.png">

How can I make it work?

**Comment by laurmaedje** [comment]
You can make a manual counter and step in manually like this:
```
#let img(image, caption: "") = {
  let c = counter("img")
  set align(center)
  image
  c.display(n => "Fig" + str(n) + "  " + caption)
  c.step()
}
```
What an element function is should definitely be documented though and in the future you'll also be able to define your own.

**Comment by werifu** [comment]
Great answer, thanks!
