### ISSUE TITLE
Footnote in auto placed figure causing figure to placed on top of text

### ISSUE THREAD

**Issue by winstonewert** [typst/typst#4780]
### Description

The following code:

```
#set text(font:"Roboto",size:12pt,weight:"regular",style:"normal",);

#lorem(50);

#lorem(60);

#lorem(60);

#lorem(60)

#lorem(40)

#lorem(50)

#lorem(30)

#figure(placement: auto,
[#lorem(40)#footnote(lorem(50))],
)
#lorem(50)

#lorem(50)

#lorem(50)

#lorem(50)

#lorem(50)

#lorem(50)

#lorem(50)

#lorem(50)

```

Place the figure on top of the text on the next page.

![shot](https://github.com/user-attachments/assets/16d0cde5-da76-4943-9601-7a179b928a06)

My hypothesis would be that it doesn't properly take the footnote into account during the placement process and and then it give shifted up and into the text.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by rriemann** [comment]
Works for me with version 0.11.1.

<details><summary>Screenshot</summary>
<p>

![image](https://github.com/user-attachments/assets/2644d18d-f58c-4f46-97fe-1a3838f4c05b)


</p>
</details>

**Comment by winstonewert** [comment]
It still fails for me on the webapp. It looks to me like your document didn't pick up the Roboto font I was using and thus didn't get laid out the same way. In particular, I think your text is a bit smaller and thus the figure doesn't get forced on the second page which causes the problem.

Here's a typst source that doesn't rely on a special font:

```
#set text(size:12.5pt,weight:"regular",style:"normal",);

#lorem(50);

#lorem(60);

#lorem(60);

#lorem(60)

#lorem(40)

#lorem(50)

#lorem(30)

#figure(placement: auto,
[#lorem(40)#footnote(lorem(50))],
)
#lorem(50)

#lorem(50)

#lorem(50)

#lorem(50)

#lorem(50)

#lorem(50)

#lorem(50)

#lorem(50)
```

**Comment by rriemann** [comment]
@winstonewert , you are right. I used the wrong font. Your example above reproduces the bug.

Proof:

![image](https://github.com/user-attachments/assets/8c5d2eeb-4796-4642-87d2-38c696989585)
