### ISSUE TITLE
Add bar accent

### ISSUE THREAD

**Issue by memeplex** [typst/typst#4802]
### Description

Currently we have `macron` but:

- It has fixed width.
- This behavior is inconsistent wrt other accents.
- It's name is not very intuitive for such a common mark.
- There is the unnamed `\u{0305}` that better fits the bill.
- `overline` is not quite a substitute.

```typst
#let cells = for ac in (sym.hat, sym.tilde, sym.arrow, sym.macron) {
  for size in (auto, 100%, 50%) {
    (math.accent([A B C], ac, size: size),)
  }
}
#grid(columns: 3, inset: 10pt, ..cells)
```

![image](https://github.com/user-attachments/assets/717bb85b-c73e-43cb-842d-18e5703010a6)

```typst
$ accent(H, \u{0305}) space macron(H) space overline(H) $
```

<img width="86" alt="image" src="https://github.com/user-attachments/assets/7726434a-2597-4c8f-9b84-adabcdb554b3">

So I propose to add a `bar` accent for the `\u{0305}` code.

### Use Case

Have a consistent and intuitive way to enter one of the most common math accents, that looks proportioned to the size of its contents.

**Comment by bluebear94** [comment]
`\u{0305}` is named `dash`.

**Comment by Enivex** [comment]
In any case, bar would not be a good name, since `\bar` in LaTeX is typst's `macron()`

**Comment by memeplex** [comment]
Naming opinions aside, since I don't care a lot about that part of the request, `dash` in 0.11.1 is not an accent, in any case this is a change in current development version.

```typst
$dash(x)$
$accent(x, dash)$
```

<img width="69" alt="image" src="https://github.com/user-attachments/assets/ba00b50a-2266-4c8a-99d9-87ae053e63cf">

**Comment by memeplex** [comment]
This is the output of `typst 0.11.0 (d84a7e42)` for the same code:

<img width="69" alt="image" src="https://github.com/user-attachments/assets/70232d88-f982-4782-b4fd-704678c2985a">

**Comment by memeplex** [comment]
For reference: 

https://discord.com/channels/1054443721975922748/1088371919725793360/1275929546230726784

>> my impression was that if A is an accent then A(c) and accent(c, A) should be equivalent (the documentation is not quite clear in this regard), so having seen that dash(c) worked fine I expected it to be an accent

> They are currently, but that's changed on main, as some symbols are made callable. In the case of dash the effect is to add an accent
