### ISSUE TITLE
Embedding Results in Rasterized and Blurry Images When Exporting to SVG

### ISSUE THREAD

**Issue by Losses** [typst/typst#4805]
### Description

When embedding an SVG file within a Typst document and subsequently exporting the document in SVG format, the embedded SVG image becomes rasterized and appears blurry. This issue affects the quality and clarity of the exported document, which is particularly problematic for documents requiring high-resolution vector graphics.

**Steps to Reproduce:**

1. Create a Typst document.
2. Embed an SVG image within the document using the appropriate Typst commands.
3. Export the document in SVG format.
4. Open the exported SVG file and observe the quality of the embedded image.

**Expected Behavior:**

The embedded SVG image should retain its vector properties and remain clear and sharp in the exported SVG file.

**Actual Behavior:**

The embedded SVG image is rasterized and appears blurry in the exported SVG file.

**Screenshots:**

![image](https://github.com/user-attachments/assets/a01db017-3d74-4c10-8b3f-3d53546e4670)

Output: [Broken Svg](https://github.com/user-attachments/assets/1b332cc7-f4f1-44a5-ae8f-13c64624cc2b)

### Reproduction URL

https://typst.app/project/ryhXzuZHftYr14cv1Bn4sd

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by har7an** [comment]
Hey, I'm seeing the same issue as you described. Did you find a proper solution or cause for this issue?

**Comment by quantenzitrone** [comment]
typst embeds svgs encoded as base64
some svg rasterizers (namely librsvg, qtsvg and inkscape) don't handle that properly
resvg, firefox and chromium seem to rasterize it correctly it seems
i didn't test other rasterizers
