### ISSUE TITLE
Can't cargo install with rust 1.80

### ISSUE THREAD

**Issue by CervEdin** [typst/typst#4813]
### Description

`cargo install --locked typst-cli` fails due to https://github.com/time-rs/time/issues/696

Had to `cargo +1.79 install --locked typst-cli`

### Operating system

Linux

### Typst version

- [ ] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
You can do `cargo install --git https://github.com/typst/typst --branch 0.11 --locked`

**Comment by alerque** [comment]
You can also install without using `locked` to allow it to use a newer version of the *time* crate than was pinned, that's the actual culprit with Rust 1.80. This release cycle was a fiasco and caused breakage across the entire Rust ecosystem.
