### ISSUE TITLE
Call to `page` with a `block` wraps the page inside the block

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#4819]
### Description

The following piece of Typst code looks like it wraps the page inside the block, affecting the dimensions of the page!

```typ
#page(block())
```

This is more visible if we specify dimensions for the block and give it a stroke:

```typ
#page(block(width: 10cm, height: 10cm, stroke: purple))
```

![The page is a square, and contains a purple square (the block).](https://github.com/user-attachments/assets/5943340d-e24a-4442-9929-1c39d6d40deb)

Adding some content before the show rule fixes the issue.

Tested on 0.11.1.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
I can't reproduce this on main.
