### ISSUE TITLE
Bibliography: Title has trailing comma or dot

### ISSUE THREAD

**Issue by ghost** [typst/typst#482]
Currently, a bibliography entry gets a trailing comma included in the biliography list.
We can see this in the [second example](https://typst.app/assets/docs/Erm9lsHSvSGRDWxZKmCyvw.png) on the website, after `dumplings`. This is probably wrong with `lang: "de"` and other languages.
Also, other things are maybe not correct like the comma before `and` and the comma after the authors (I would have expected a different symbol), but the main problem is the comma at the end of the title.

![bib](https://user-images.githubusercontent.com/107212151/229133405-117680fa-254e-4963-b967-6c47d64288c3.png)

A trailing dot can maybe be correct, but I would suggest to use it only if the title really contains a trailing dot, otherwise put the dot outside the quotes.

**Comment by laurmaedje** [comment]
Will likely be fixed once CSL support lands (which is soon).
