### ISSUE TITLE
APA in-text citation is incorrect, uses number instead

### ISSUE THREAD

**Issue by QazCetelic** [typst/typst#4824]
### Description

Citations don't render as APA style, despite setting citation style (`#set cite(style: "american-physiological-society")`).
```typst
Here I reference the source @aggarwal_data_2015 as inline citation.
This should have been either Aggarwal (2015) or (Aggarwal, 2015)
```
![wrong_citation](https://github.com/user-attachments/assets/3344d312-0c05-4147-b4a8-a8d51034278c)

None of the variants work either.

![variants_not_working](https://github.com/user-attachments/assets/f8f842f6-42eb-47b0-9a44-c4b432ce96dc)

### Reproduction URL

https://typst.app/project/rcu1YJ9yJM1Hu8y4SGCvlT

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
In your reproduction, you have `american-psychological-society` in the set rules and `american-psychological-association` in another. If you set `american-psychological-association` in your set rules, then it should work as expected.
