### ISSUE TITLE
Incorrect handling of smart double-quotes when a single quote is present inside

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [typst/typst#4835]
### Description

The following example does not render the smart quotes as expected:

```
"Arrhenius' law"
```

The end double quote does not render appropriately because of the `s'`.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by xkevio** [comment]
I am not sure if this is a bug per se or just how the code currently works. In any case, you can easily workaround this by escaping the single quote: `"Arrhenius\' law"`

**Comment by Enivex** [comment]
Whether it's a bug or not, it's clearly a situation where it's highly desirable for typst to get it right without escaping

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/4849
