### ISSUE TITLE
Support for Egyptian Hieroglyph Format Controls Unicode block

### ISSUE THREAD

**Issue by rwmpelstilzchen** [typst/typst#4837]
##### Egyptian hieroglyphs

The [Egyptian hieroglyphs](https://en.wikipedia.org/wiki/Egyptian_hieroglyphs) are not written linearly one character after the other horizontally or vertically; they are grouped in various spatial relations (most commonly signs vertically above signs, but other relations do occur).

##### Manuel de Codage

In order to represents Hieroglyphic texts in digital form various methods have been developed, of which the [Manuel de Codage](https://en.wikipedia.org/wiki/Manuel_de_Codage) (MdC) became the *de facto* standard in the pre-Unicode era; it uses ASCII characters in combination with special characters such as `:` and `*` to represent hundreds of hieroglyphs and their complex positioning in relation to each other. The [HieroTeX](https://github.com/hierotex/hierotex) package for LaTeX takes MdC-encoded input and typesets hieroglyphs within a document.

##### Unicode

Hieroglyph support in Unicode was introduced in version 5.2 (2009). At the beginning there was no support for the non-linear structure of the text¹. This severely limited the usability of Unicode for Egyptology and linguistic description of the Egyptian language. Ten years letter, in Unicode 12.0 (2019) the [Egyptian Hieroglyph Format Controls](https://en.wikipedia.org/wiki/Egyptian_Hieroglyph_Format_Controls) Unicode block was added, and quite recently in Unicode 15.0 (2022) is was expanded by 29 additional format controls. This makes at long last Unicode a capable standard for representing hieroglyph texts and fragments.

¹ [Hangeul](https://en.wikipedia.org/wiki/Hangul) is also written non-linearly, but there thanks to the limited number of the basic characters that make the blocks and the predictable manner they are positioned, all the possible comminations for blocks that may occur in the Korean language are [individually encoded](https://en.wikipedia.org/wiki/Hangul_Syllables). This cannot be done with hieroglyphs due to the sheer amount of basic signs and the complex ways they are positioned.

#### Typst support

I tried to typeset hieroglyphs in Typst with very limited success. See the code below ([output](https://github.com/user-attachments/files/16741261/a.pdf)) for the results. LuaLaTeX wasn’t helpful either, resulting in a slightly different kind of mess… *However*, it was LibreOffice (version 24.2.3.2 on Linux) that did produce impeccable output with the [Egyptian Text](https://github.com/microsoft/font-tools/tree/main/EgyptianOpenType/font) font (see the attached image, cropped from a screenshot); the other fonts ([NewGardiner](https://github.com/nederhof/opentypehiero/), [‘Untitled1’](https://github.com/nederhof/opentypehiero/blob/master/tests/new.otf)², and two font that weren’t supposed to work because they don’t support the format controls: [JSesh](https://files.qenherkhopeshef.org/jsesh/JSeshFont.ttf) and [Noto Sans EgyptHiero](https://notofonts.github.io/egyptian-hieroglyphs/)) produced faulty output as well.

![Good output with LibreOffice and the Egyptian Text font](https://github.com/user-attachments/assets/2ce880a9-a139-4acb-8342-7cec5ff72204)

² A supposedly ‘new’ version of NewGardiner named internally ‘Untitled1’…

```typst
#set page(
  width: auto,
  height: auto,
  margin: 0.5cm
)

#let test(font-name, url, ehfc)= {(
  table.cell[#link(url)[#font-name]],
  table.cell[#set text(font: (font-name), fallback: false); 𓌃𓂧𓐰𓏏𓐱𓏯𓀁𓏪𓆎𓅓𓊖 ],
  table.cell[#set text(font: (font-name), fallback: false); 𓄤𓆑𓐰𓂋],
  table.cell[#set text(font: (font-name), fallback: false); 𓆣𓐰𓂋𓇋𓁛],
  if ehfc {
    table.cell(align: center)[✅]
  }
)}

#table(
  columns: 5,
  stroke: none,
  table.hline(stroke: 0.08em),
  table.header(
    [Font name],
    [_mdw.t-km.t_\ ‘Egyptian language’],
    [_nfr_\ ‘fine, beautiful’],
    [_ḫprj_\ ‘Khepri’],
    [Has U+13430?]
  ),
  table.hline(stroke: 0.05em),
  ..test(
    "Egyptian Text",
    "https://github.com/microsoft/font-tools/tree/main/EgyptianOpenType/font",
    true
  ),
  ..test(
    "NewGardiner",
    "https://github.com/nederhof/opentypehiero/",
    true
  ),
  ..test(
    "Untitled1",
    "https://github.com/nederhof/opentypehiero/blob/master/tests/new.otf",
    true
  ),
  ..test(
    "JSesh font",
    "https://files.qenherkhopeshef.org/jsesh/JSeshFont.ttf",
    false
  ),
  ..test(
    "Noto Sans EgyptHiero",
    "https://notofonts.github.io/egyptian-hieroglyphs/",
    false
  ),
  table.hline(stroke: 0.08em),
)
```

What can be done? The *Egyptian Text* font has proved to work in LibreOffice, so I’d assume the problem is not in the font but in the rendering mechanisms of Typst and LuaLaTeX. I’m not familiar with Typst’s inner workings, but is this necessarily something complex to fix (that is, building the complex positioning and scaling system from scratch, implementing each of the format controls) or maybe it’s just something that has to be configured with the rendering mechanism? Notice that the word *nfr* with the font ‘Untitled1’ (third column, forth row in the [table](https://github.com/user-attachments/files/16741261/a.pdf)) is rendered… beautifully 🙂

For context, see [HieroJax](https://nederhof.github.io/hierojax/), which implements this in JavaScript.

For technical background, see the Wikipedia page on [Egyptian Hieroglyph Format Controls](https://en.wikipedia.org/wiki/Egyptian_Hieroglyph_Format_Controls) and the Unicode documentation linked there.

Thank you from the bottom of my 𓄣𓐰𓏤 (heart ❤️) for your time and effort!

---

When this problem is fixed, I intend to extend the capabilities of a Egyptological Typst package I work on to convert MdC input to Unicode, similarly to [this](https://nederhof.github.io/hierojax/mdcconversion.html) (I see no reason to do that at the moment when its output is displayed wrong).

### Use Case

Any scholarly work in Egyptology or linguistics that incorporates fragments of Egyptian hieroglyphs — in-line or as block examples — has to have support for typesetting hieroglyphs.

**Comment by LaurenzV** [comment]
> What can be done? The Egyptian Text font has proved to work in LibreOffice, so I’d assume the problem is not in the font but in the rendering mechanisms of Typst and LuaLaTeX. I’m not familiar with Typst’s inner workings, but is this necessarily something complex to fix (that is, building the complex positioning and scaling system from scratch, implementing each of the format controls) or maybe it’s just something that has to be configured with the rendering mechanism?

So, I think the relevant crate that we are using that is responsible for what you are trying to do is [rustybuzz](https://github.com/RazrFalcon/rustybuzz). It is responsible for _text shaping_, which basically means taking a sequence of Unicode codepoints and turning them into positioned glyphs from the respective font. I don't know the first thing about Egyptian hieroglyphs, but I don't assume that they are somehow a special case in comparison to other scripts, so that's most likely a relevant starting point. `rustybuzz` in turn is a Rust port of the [`harfbuzz`](https://harfbuzz.github.io/) library, which is pretty much the most widely used and best shaping engine out there (it's used in Chrome and many other programs). `rustybuzz` tries to always have the exact same output as `harfbuzz`, meaning that we should first check whether we get the same issues when shaping the provided texts with harfbuzz. If yes, that either means there is a bug in harfbuzz, or they simply haven't implemented it yet. If it does work there, then that might mean that there is some bug in rustybuzz.

But anyway, before diving deepter into this, I tried the `Egyptian Text` font locally, and this is what I get:
<img width="1460" alt="image" src="https://github.com/user-attachments/assets/b26d4575-902a-4571-a485-4db5e6d7c7e3">

When I compare it to the screenshot you posted, it seems to look pretty similar. Could you specify what exactly is wrong in this output?

**Comment by LaurenzV** [comment]
Oh, I just realized that you posted the output that you get. 

Indeed, I get the same output when compiling with 0.11.1. But it works fine on main! The issue was most likely that, a couple of months ago, rustybuzz was many versions behind harfbuzz, which means that we also didn't have Unicode 15 support. By now, rustybuzz has luckily been synced back up, and we are currently using a newer version of rustybuzz. So this issue should be fixed by the next release. :)

Can you confirm that the following file corresponds to the exepected output? If so, I think we can close this issue.
[typst.pdf](https://github.com/user-attachments/files/16741563/typst.pdf)

**Comment by khaledhosny** [comment]
> LuaLaTeX wasn’t helpful either, resulting in a slightly different kind of mess

You might need to enable HarfBuzz (`Renderer=HarfBuzz` fontspec option) as the default layout engine is probably not up to the task.

**Comment by rwmpelstilzchen** [comment]
> Oh, I just realized that you posted the output that you get.

Yeah, maybe I should’ve attached it as an image as well; the link to the PDF file doesn’t really stand out…

> Indeed, I get the same output when compiling with 0.11.1. But it works fine on main! The issue was most likely that, a couple of months ago, rustybuzz was many versions behind harfbuzz, which means that we also didn't have Unicode 15 support. By now, rustybuzz has luckily been synced back up, and we are currently using a newer version of rustybuzz. So this issue should be fixed by the next release. :)

Woohoo! 🎉

Thank you; it makes me happy this is solved with no need to do anything extra in anyone’s part 🙂

> Can you confirm that the following file corresponds to the exepected output? If so, I think we can close this issue. [typst.pdf](https://github.com/user-attachments/files/16741563/typst.pdf)

Yes, I can confirm that. It took a while to compile Typst on my laptop, but now I have the `main` version installed and the output of *Egyptian Text* looks wonderful indeed. I guess in the case of *NewGardiner* the problem is with the font (it doesn’t work on any setup I’ve tried). The other fonts don’t support the Egyptian Hieroglyph Format Controls block, so they shouldn’t have worked at all and were added in the table for completeness (in order to show how it looks when the font lacks the relevant control characters).

**Comment by rwmpelstilzchen** [comment]
@khaledhosny 

> You might need to enable HarfBuzz (`Renderer=HarfBuzz` fontspec option) as the default layout engine is probably not up to the task.

Thank you for the tip! 🙂

Tried to use HarfBuzz as the renderer like you said. It resulted with yet another kind of mess but now I suppose this is due to my TeX Live installation not having a recent enough version of HarfBuzz…

(It just amazes me how only now we are beginning to be able to write on a computer a language written in the one of the earliest scripts in human history, if not the first one)

**Comment by alerque** [comment]
@rwmpelstilzchen Would you happen to have some LaTeX source handy with your attempt to make this work there? I'd like to give it a shot myself (including being on a current version of TexLive & HarfBuzz) and post it to the [hieroglyphs sample on polytype](https://polytype.dev/hieroglyphs/), especially if I can get it to work.

(Note the Typst sample generation there uses the current released version on Nixpkgs; as of this writing that is 0.11.1. I expect that sample to render nearly identical to the SILE sample when 0.12 comes out.)
