### ISSUE TITLE
Slicing array of arrays (2D arrays)

### ISSUE THREAD

**Issue by toihr** [typst/typst#4847]
### Description

A way to slice arrays of arrays or rather 2D arrays. i.e.
```
let a = ((1,2,3),(4,5,6),(7,8,9),(10,11,12))

let b = a.slice2D(0,3,0,2)
//which should then result to
// ((1,2),(4,5),(7,8))
```

### Use Case

For example when working with tables read in by .csv files. And you do not want to show all columns only, and also want to constrict the amount of rows displayed to show an example of how a table is supposed to look. This right now would need to be done in a very imperative way which just is not nice to write.

**Comment by bluebear94** [comment]
This can be already done using mapping:

```typ
let b = a.slice(0, 3).map(x => x.slice(0, 2))
```

**Comment by Enivex** [comment]
I don't see how this proposal could work unless typst gets native support for two-dimensional arrays.

(Which I honestly think could be useful in a typesetting tool.)

**Comment by laurmaedje** [comment]
I think the mapping-based solution is honestly enough for now. Having just 2d slicing would open up the door to many more data-science oriented array tasks, which I'm not sure we want to get into.
