### ISSUE TITLE
Layout does not converge when outline spans more than one page

### ISSUE THREAD

**Issue by wlievens** [typst/typst#4854]
### Description

I have an issue of layout not converging after 5 passes, in a large document. I gutted the document as much as I could while retaining the error.

The failure appears to be caused by a combination of the following conditions, since when I remove either of them it goes away:
- Diagrams made of rects, in a figure
- Tables (made through functions)
- Usage of `context` and `here` to retrieve the local section name
- Critically: an `outline` of all tables, which spans more than one page

In my real document, the multi-page tables outline is due to there being many tables. In the gutted minimal example, it is due to a `v` spacing.

The code of my gutted example (apologies, it is still quite long at 92 lines, but it comes from 2800+):
```
#import "@preview/pinit:0.1.4": *

#let get-section-title(location) = {
  query(selector(heading).before(location)).last().body
}

#let BODY_FONT_SIZE = 11pt

#let defectivity-table-outputs = (
  columns: (21.4em, 5.6em, 1fr),
  align: (left + horizon, center + horizon, left + horizon),
)

#let defectivity-table-outputs-header = table.header(
  text(size: BODY_FONT_SIZE, "Output"),
  text(size: BODY_FONT_SIZE, "Type"),
  text(size: BODY_FONT_SIZE, "Description"),
)

#let generate-defectivity-table-outputs(label, outputs) = [
  #figure(caption: label + " — Test Outputs")[
    #table(
      ..defectivity-table-outputs,
      defectivity-table-outputs-header,
      ..outputs.map(row => (
        raw(row.name),
        raw(row.type),
        row.description
      )).flatten()
    )
  ]
]

#show outline.entry.where(
  level: 1,
): it => {
  v(16pt, weak: true)
  strong(it)
}

#v(55em)
#outline(title: heading(outlined: true, "Tables"), target: figure.where(kind: table))

#pagebreak()

#let example_stroke = 1.0pt
#let example_width = 360pt
#let example_height = example_width * 5460 / 8192
#let example_font_size = 9pt
#let tile_inset = 0pt
#let tile_width = example_width / 9
#let tile_height = tile_width * 0.8

#let tiling_tile_x(x) = calc.min(example_width - tile_width, calc.max(0pt, example_width / 2 + tile_width * x))
#let tiling_tile_y(y) = calc.min(example_height - tile_height, calc.max(0pt, example_height / 2 + tile_height * y))

#context generate-defectivity-table-outputs(get-section-title(here()), ())
#context generate-defectivity-table-outputs(get-section-title(here()), ())

#let focus_column_x = tiling_tile_x(-3) + 0.35 * tile_width
#let segment_focus_offset = 2.5pt

#block(breakable: false)[
#let focus_column_x = tiling_tile_x(-3) + 0.35 * tile_width
#let segment_focus_offset = 2.5pt

#figure(caption: "aaaa")[
  // Background
  #rect(width: example_width, height: example_height,  stroke: none)
 
  // Focus tile
  #place(top + left,
    dx: tiling_tile_x(-3),
    dy: tiling_tile_y(-2),
    rect(width: tile_width, height: tile_height, outset: -tile_inset,
    pin("abc123"))
  )
]

#pinit-point-from(
  pin-dx: 15pt,
  pin-dy: 4pt,
  offset-dx: 50pt,
  offset-dy: 15pt,
  "abc123"
)[Txxx]

]

#context generate-defectivity-table-outputs(get-section-title(here()), ())
#context generate-defectivity-table-outputs(get-section-title(here()), ())
```

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Minimized to this:
```typ
#v(62em)
#outline(target: figure)

#let delay(func) = {
  metadata(none)
  context {
    let _ = query(metadata).last().location()
    func()
  }
}

#let pin(loc, name: "abc123") = {
  label("page" + str(loc.position().page) + name)
}

#place(
  delay(() => [#metadata(none)#pin(here())])
)

#delay(() => {
  let elems = query(pin(here()))
  if elems != () {
     metadata(none)
  }
})

#context {
  let _ = query(heading).last()
  figure(caption: "A", none)
}
```
This code needs six iterations to converge. 

Crucial problems are the usage of `.last()`, which incur extra iterations because `last()` crashes when the array is empty, which prevents other content in the same context block from being generated within that layout iteration.

Pinit also does some rather cursed things, in particular `label("page" + str(loc.position().page) + name)`. This is likely what causes problems in combination with the outline growing to more than one page.

There needs to be some limit on the number of iterations and 5 is sufficient in most cases. The code in question can be adapted to not reach the limit, so I'll go ahead and close this.

**Comment by wlievens** [comment]
Hi, thanks for looking into this. Do I understand correctly that you mean there is a workaround, but it's pinit that's at fault?

**Comment by laurmaedje** [comment]
I wouldn’t say that someone is specifically at fault. It’s just a bad combination of circumstances that really needs more than five iterations. But as said, I believe some of this could be expressed with need for less iterations, both in your code (the `last` thing could be in an if check) and in pinit's code.

**Comment by wlievens** [comment]
I undertand now, the error in the ``last()`` call costs me an other iteration for no good reason. I wrapped the ``last()`` call in an if, and it converged just fine. Thanks for the support!
