### ISSUE TITLE
The horizontal line of the square root is too high

### ISSUE THREAD

**Issue by hooyuser** [typst/typst#4855]
### Description

In the mathematical formula `$ sqrt(n/p) < sqrt(n^(2/3)) < sqrt((n^(2/3))) $`, the horizontal line of the square root symbol is too high when it contains `n^(2/3)`, which makes the formula look unappealing.

![square_root_bug](https://github.com/user-attachments/assets/65eca9bb-de09-4be6-97c0-fed7617ff18d)

It's higher than when the square root contains `n/p`, and even higher than when it contains `n^(2/3)` with extra parentheses. 

Intuitively, adding parentheses could only make the height of the horizontal line stay the same or get higher, but here it actually became lower.

Here is a comparison with LaTeX.

![LaTeX_square_root](https://github.com/user-attachments/assets/9a4c0807-99ce-48f9-b36b-4783d2218a54)

### Reproduction URL

https://typst.app/project/rVGMrZzmtsyZOwndNwHkxe

### Operating system

Web app, Windows

### Typst version

- [x] I am using the latest version of Typst

**Comment by alerque** [comment]
This is probably a font bug, and it looks like it may be fixed in *Libertinus Math* (the successor to the abandoned Linux Libertine fonts project):

```typst
= Linux Libertine

$
  sqrt(n/p) < sqrt(n^(2/3)) < sqrt((n^(2/3)))
$

= Libertinus Math

#[
  #show math.equation: set text(font: "Libertinus Math")
  $
    sqrt(n/p) < sqrt(n^(2/3)) < sqrt((n^(2/3)))
  $
]

= STIX Two Math

#[
  #show math.equation: set text(font: "STIX Two Math")
  $
    sqrt(n/p) < sqrt(n^(2/3)) < sqrt((n^(2/3)))
  $
]
```

![image](https://github.com/user-attachments/assets/6252087e-74c6-486a-b435-19f7e81c03ac)

**Comment by flokl** [comment]
There was also some work done in #4492, which seems related.

**Comment by Enivex** [comment]
> This is probably a font bug, and it looks like it may be fixed in _Libertinus Math_ (the successor to the abandoned Linux Libertine fonts project)

Typst uses Linux Libertine for text (will switch to Libertinus Serif in 0.12), but New Computer Modern Math for math (by default).

**Comment by hooyuser** [comment]
> This is probably a font bug, and it looks like it may be fixed in *Libertinus Math*

In my experiment, both Typst and LaTeX use `New Computer Modern Math` as the math font. Thank you for suggesting conducting more tests, and I discovered something interesting.

The default math font for Typst is `New Computer Modern Math` with weight 450. I suspect this might be a Typst bug because XeLaTeX handles it correctly.

Interestingly, when I chose `New Computer Modern Math` with weight 400, Typst produced a nice result that looks the same as XeLaTeX.

![typst](https://github.com/user-attachments/assets/4afaa8e5-fc35-4d90-9287-8e479da608d8)

**Comment by inferiorhumanorgans** [comment]
With the typst doc linked above:

```
Rendering: Font(New Computer Modern Math, Normal-450-FontStretch(1000)) GlyphId(5944) Some("radical.v3")
Rendering: Font(New Computer Modern Math, Normal-450-FontStretch(1000)) GlyphId(5943) Some("radical.v2")
Rendering: Font(New Computer Modern Math, Normal-450-FontStretch(1000)) GlyphId(5943) Some("radical.v2")
Rendering: Font(New Computer Modern Math, Normal-450-FontStretch(1000)) GlyphId(5943) Some("radical.v2")
Rendering: Font(New Computer Modern Math, Normal-450-FontStretch(1000)) GlyphId(5943) Some("radical.v2")
Rendering: Font(New Computer Modern Math, Normal-450-FontStretch(1000)) GlyphId(5943) Some("radical.v2")
Rendering: Font(New Computer Modern Math, Normal-450-FontStretch(1000)) GlyphId(5943) Some("radical.v2")
Rendering: Font(New Computer Modern Math, Normal-450-FontStretch(1000)) GlyphId(5944) Some("radical.v3")
Rendering: Font(New Computer Modern Math, Normal-450-FontStretch(1000)) GlyphId(5945) Some("radical.v4")
Rendering: Font(New Computer Modern Math, Normal-450-FontStretch(1000)) GlyphId(5940) Some("radical.ex")
Rendering: Font(New Computer Modern Math, Normal-450-FontStretch(1000)) GlyphId(5940) Some("radical.ex")
Rendering: Font(New Computer Modern Math, Normal-450-FontStretch(1000)) GlyphId(5941) Some("radical.tp")

Rendering: Font(New Computer Modern Math, Normal-400-FontStretch(1000)) GlyphId(5011) Some("radical.v3")
Rendering: Font(New Computer Modern Math, Normal-400-FontStretch(1000)) GlyphId(5009) Some("radical.v1")
Rendering: Font(New Computer Modern Math, Normal-400-FontStretch(1000)) GlyphId(5010) Some("radical.v2")
Rendering: Font(New Computer Modern Math, Normal-400-FontStretch(1000)) GlyphId(5009) Some("radical.v1")
Rendering: Font(New Computer Modern Math, Normal-400-FontStretch(1000)) GlyphId(5010) Some("radical.v2")
Rendering: Font(New Computer Modern Math, Normal-400-FontStretch(1000)) GlyphId(5010) Some("radical.v2")
Rendering: Font(New Computer Modern Math, Normal-400-FontStretch(1000)) GlyphId(5010) Some("radical.v2")
Rendering: Font(New Computer Modern Math, Normal-400-FontStretch(1000)) GlyphId(5011) Some("radical.v3")
Rendering: Font(New Computer Modern Math, Normal-400-FontStretch(1000)) GlyphId(5012) Some("radical.v4")
Rendering: Font(New Computer Modern Math, Normal-400-FontStretch(1000)) GlyphId(5007) Some("radical.ex")
Rendering: Font(New Computer Modern Math, Normal-400-FontStretch(1000)) GlyphId(5007) Some("radical.ex")
Rendering: Font(New Computer Modern Math, Normal-400-FontStretch(1000)) GlyphId(5008) Some("radical.tp")
```

Typst is picking different radical sizes.  The question is why.

**Comment by inferiorhumanorgans** [comment]
Quick followup:

The issue seems to be that the glyphs in the book weight are just a smidge taller than those in the regular weight font (the defined gaps are the same).  In display mode, the gap between the radical and radicand (`radicalDisplayStyleVerticalGap`) combined with the slightly taller glyphs yield a height that is a fraction of a point larger than what can fit under `radical.v1` so typst picks the next largest stretch (`radical.v2`).

In text (inline) mode the prescribed gap (`radicalVerticalGap`) is small enough that it allows typst to pick the shorter radical with either font and things look better.  Eliminate the space between the `$` symbols and the equation to generate an inline equation.

As far as LaTeX goes, `$..$` generates text mode equations as seen in the example above, and the `displaymath` environment should trigger a display mode equation.  In practice tectonic seems to get the spacing right even in display mode.  A quick look at the luatex source left me with the impression that the text mode spacing constant is always used (but I'll defer to someone who's actually familiar with luatex).
