### ISSUE TITLE
Regression: show par: set block broken on current main

### ISSUE THREAD

**Issue by SolidTux** [typst/typst#4902]
### Description

On the current main branch, `show par: set block(spacing ...)` is broken. I attached the result of compiling the following on the current main (e6cdcc53) and on v0.11.1.

```typst
#lorem(50)

#lorem(50)

#show par: set block(spacing: 0mm)

#lorem(50)

#lorem(50)
```

[Commit e6cdcc53](https://github.com/user-attachments/files/16887982/e6cdcc53.pdf)
[v0.11.1](https://github.com/user-attachments/files/16887983/v0_11_1.pdf)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This is an intentional breaking change: https://github.com/typst/typst/pull/4390

**Comment by SolidTux** [comment]
Oh, that's a much better way to do it!
