### ISSUE TITLE
Make QuoteElem locatable; or configurable locatables?

### ISSUE THREAD

**Issue by yeahitsjan** [typst/typst#4906]
### Description

Evolving from a Discord chat, it would be great if ``QuoteElem`` would be also locatable. Justified reasons against it can be performance losses, but it should be checked whether this really makes a big performance loss.

Another idea I had that came up but my Rust knowledge is probably to less of a kind, is, to make all elements configurable if they should be locatable. So the user could decide which elements should be located and which won't. It's probably easier to talk about than it is to implement, but I think it could be a significant difference to the current system.

### Use Case

Could allow third-party applications to work more seamlessly with the Typst compiler. If I build for example a tool to read all quotes I could allow them to be locatable, disable locating for all other types and get some perf improvements.

**Comment by Coekjan** [comment]
The document now says:

![image](https://github.com/user-attachments/assets/c1192850-11bf-4e30-80f2-1a7057b645cb)

But I am curious why not make all elements locatable. (_Performance related?_)

**Comment by laurmaedje** [comment]
Copying my response from [Discord](https://discord.com/channels/1054443721975922748/1088371867913572452/1281209693657759794): 

> Making just quotes locatable is trivial by marking them as `Locatable`. I don't see any harm in that. The reason why not everything is locatable is performance. One more element doesn't break stuff, but allowing everything would hurt it.
>
> The performance impact nowadays would probably be way less than back when I introduced the concept of Locatable, but I would still expect it to be quite significant.

**Comment by yeahitsjan** [comment]
@laurmaedje would it be an idea to make this user / dev configurable? The user / dev could then decide for himself whether the performance losses are justifiable. Forking and extending the elements needed is IMO not a good idea as you would need to roll your own Typst compiler next to the "standard" installation.

**Comment by laurmaedje** [comment]
I would prefer to just lift the limitation. If that turns out to be not feasible within the near to mid-term future, we can consider an option.
