### ISSUE TITLE
Compiler is incorrectly cropping output

### ISSUE THREAD

**Issue by K4LCIFER** [typst/typst#4919]
### Description

Say one wanted to create a shareable image of a Typst-rendered equation — that is to say the equation has the page cropped to the height and width of the equation — one would think to write something like the following:
```typst
#set page(
width: auto,
height: auto,
margin: 0pt,
)
$E = m c^2$
```
but this ends up rendering something that looks like
![temp](https://github.com/user-attachments/assets/10ee6566-de35-43e4-abb7-263ed48048d5)

On the left and right of the image there are some gaps of extra page, and the top has the exponent, 2, on c cut off. The following is another example:
```typst
#set page(
width: auto,
height: auto,
margin: 0pt,
)
$mat(
n;
r;
) = frac(n!, r!(n-r)!)$
```
![temp](https://github.com/user-attachments/assets/347625d7-0025-4b9c-81d6-65dae59d2d53)

This one is more extreme where it cuts deep into the fraction and the matrix.

Both of the above were compiled with:
```
typst compile -f png <input>.typst <output>.png
```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
#1028
