### ISSUE TITLE
More consistent shorthand notation

### ISSUE THREAD

**Issue by araaha** [typst/typst#492]
We have that `=>` is shorthand for `arrow.r.double` and `>=` is shorthand for `gt.eq` but `arrow.l.double` has no shorthand notation as the shorthand for `lt.eq` is `<=`. It makes more sense for the shorthand notation for `lt.eq` to be `=<` and the shorthand notation for `arrow.l.double` to be `<=`.

**Comment by ararunaufc** [comment]
Although it is really unfortunate that there is no such shorthand, I don't know if changing `lt.eq` to use `=<` is a good solution...

I'd be really surprised and confused, because, as a programmer, I'm really used to using `<=` for "less-than-or-equal"... 😕

**Comment by Araaha** [comment]
In that case, is it possible to assign `<=` to `arrow.r.double`?

**Comment by Enivex** [comment]
I would strongly oppose anything other than >= for gt.eq and <= for lt.eq, both for semantic reasons and because its standard in many other languages.

**Comment by user202729** [comment]
I think best compromise would be #254.

**Comment by ararunaufc** [comment]
> In that case, is it possible to assign `<=` to `arrow.r.double`?

And what about `==>` and `<==`?

Even if longer, I wouldn't oppose using them.

**Comment by laurmaedje** [comment]
These are already `arrow.r.double.long` and `arrow.l.double.long`.

**Comment by ararunaufc** [comment]
> These are already `arrow.r.double.long` and `arrow.l.double.long`.

Well, would it work to do this change, then?

| Short-hand | Symbol                |
|------------|-----------------------|
| `<=`       | `lt.eq`               |
| `>=`       | `gt.eq`               |
| `==>`      | `arrow.r.double`      |
| `<==`      | `arrow.l.double`      |
| `===>`     | `arrow.r.double.long` |
| `<===`     | `arrow.l.double.long` |
| ...        | ...                   |

I mean, I agree it's making the short-hands larger, but it's not like they would stop being preferrable to the full symbol address[^ref].

If this makes sense, we shouldn't forget to go through the other similar symbols to make them consistent with these.

[^ref]:  In my head the answer to "Why do I have to put two `=` just to get an arrow?" would just be "look at this issue and how it used to be confusing" (and also "you wont die from it" /s 😄 ).

**Comment by Enivex** [comment]
That would be inconsistent with programming font ligatures, like I mentioned above. What typst is using is fairly standard.

I don't see what's wrong with just using =< for arrow.l.double. OK, it's not quite consistent with the other symbols, but it can be done without breaking everything else.

**Comment by ararunaufc** [comment]
> That would be inconsistent with programming font ligatures, like I mentioned above. What typst is already using is fairly standard. (See for instance https://github.com/tonsky/FiraCode.)

I don't know about other fonts, but the example font you posted doesn't seem to particularly clash with my proposal. (None of the arrow sequences I suggested seem to be mapped to an incompatible ligature. Did I miss something?)

Or do you mean something about the rest of the symbols if we had to change them?

**Comment by Enivex** [comment]
> > That would be inconsistent with programming font ligatures, like I mentioned above. What typst is already using is fairly standard. (See for instance https://github.com/tonsky/FiraCode.)
> 
> I don't know about other fonts, but the example font you posted doesn't seem to particularly clash with my proposal. (None of the arrow sequences I suggested seem to be mapped to an incompatible ligature. Did I miss something?)
> 
> Or do you mean something about the rest of the symbols if we had to change them?

It does clash somewhat, because it uses =>, ==>, <== in the same way typst currently does. With the change ==> and <== would correspond to short arrows in typst, and long arrows in the font, while ===> and <=== would be long arrows in typst and nothing in the font. Not exactly the end of the world, but it could cause confusion, and I still think one should try to follow convention when possible.

**Comment by MDLC01** [comment]
Maybe I should create another issue for that, but I also find it confusing that `|-->`, `<-|` and `<--|` are not valid shorthands for, respectively, `⟼`, `↤` and `⟻`. Even though only the first is commonly used, the two others don't clash with anything so I feel like they should be valid shorthands too.

**Comment by Enivex** [comment]
> Maybe I should create another issue for that, but I also find it confusing that `|-->`, `<-|` and `<--|` are not valid shorthands for, respectively, `⟼`, `↤` and `⟻`. Even though only the first is commonly used, the two others don't clash with anything so I feel like they should be valid shorthands too.

More shorthands means more opportunities for ambiguous expressions where you're forced to add spaces. I can think of several examples for the ones you mentioned, involving arrows, inequalities and absolute values.

**Comment by TheJosefOlsson** [comment]
It seems like an easy enough fix to add or change one or more shorthands, but is it desirable? Or should the issue be closed?

**Comment by laurmaedje** [comment]
I think this is a very valid concern:

> More shorthands means more opportunities for ambiguous expressions where you're forced to add spaces. I can think of several examples for the ones you mentioned, involving arrows, inequalities and absolute values.
>
> I'm of the opinion that shorthands should be limited to commonly used symbols with minimal opportunity for ambiguity.

For this reason, I would refrain from adding more shorthands for the sake of consistency.
