### ISSUE TITLE
Cargo install fails

### ISSUE THREAD

**Issue by maacl** [typst/typst#4920]
### Description

   Compiling psm v0.1.21
error[E0282]: type annotations needed for `Box<_>`
  --> /Users/mac/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
   = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`

   Compiling crossbeam-epoch v0.9.18
   Compiling serde_derive v1.0.197
   Compiling zerofrom-derive v0.1.3
   Compiling yoke-derive v0.7.3
For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `typst-cli v0.11.1`, intermediate artifacts can be found at `/var/folders/t8/nxzks_d15vqfwlgttv2pdnq40000gp/T/cargo-install6WvTnp`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
See https://github.com/typst/typst/issues/4659
