### ISSUE TITLE
combining `par.justify` and boxed equations look weird

### ISSUE THREAD

**Issue by Akida31** [typst/typst#4938]
### Description

When combining justified paragraphs and a show rule to box equations (as far as I know the way to prevent line breaks inside equations), the equation is broken into multiple lines.

typst code:
```typst
#set page(width: 300pt, height: auto)
#set par(justify: true)
#show math.equation: it => box(it)

If $lim_(n -> oo) n p_n = lambda$ it follows for all $k in NN_0$ ...
```

<details>
<summary>
expected (typst 0.11.1, installed via cargo) and also working with ab5cebc5
</summary>
<img src="https://github.com/user-attachments/assets/c29445fa-778c-4f50-9918-f536b98a64cf" />
</details>

<details>
<summary>
got instead (typst 0.11.0 a2f91c4b, compiled from source)
</summary>
<img src="https://github.com/user-attachments/assets/d353d513-1dcc-44b0-9cdc-adcd768908a4" />
</details>

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
If someone wants to help out, a bisect would be great.
