### ISSUE TITLE
Redundant space after references

### ISSUE THREAD

**Issue by yardenas** [typst/typst#4947]
### Description

I have the following code to format references for equations:

```
  set math.equation(numbering: "(1)")
  show ref: it => {
    let eq = math.equation
    let el = it.element
    if el != none and el.func() == eq {
      let numb = numbering(
        "1",
        ..counter(eq).at(el.location()),
      )
      let color = rgb(0%, 8%, 45%) // Originally `mydarkblue`. :D
      let content = link(el.location(), text(fill: color, numb))
      if it.supplement == none [
        (#content)
      ] else if it.supplement == auto [
        Equation (#content)
      ] else [
        #it.supplement (#content)
      ]
    } else {
      return it
    }
  }
```
Now, for some reason, if I add punctuation characters (like comma or exclamation mark), I get an additional space, like so
![image](https://github.com/user-attachments/assets/b4d4adee-63b9-4638-b764-714d310a83f5)

If I change `Equation (#content)` to something that does not evaluate #content (or any other variable to be precise), for instance to `Equation foo`, I don't get this error.

Any ideas how to solve this issue?

Thanks :heart: 

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by yardenas** [comment]
For those interested, after two hours of debugging, here's the solution
```
  set math.equation(numbering: "(1)")
  show ref: it => {
    let eq = math.equation
    let el = it.element
    if el != none and el.func() == eq {
      let numb = numbering(
        "1",
        ..counter(eq).at(el.location()),
      )
      let color = rgb(0%, 8%, 45%) // Originally `mydarkblue`. :D
      let content = link(el.location(), text(fill: color, numb))
      if it.supplement == none {
        return [(#content)]
      } else if it.supplement == auto {
        [Equation (#content)]
      } else {
        return [#it.supplement (#content)]
      }
    } else {
      return it
    }
  }

```

**Comment by CGMossa** [comment]
Does
else if it.supplement == auto {
        [Equation (#content)]

Need a return too?
What fixed it? Returning one content block instead of multiple that get glued by spaces maybe?
