### ISSUE TITLE
Drawing commutative diagrams

### ISSUE THREAD

**Issue by Complex2-Liu** [typst/typst#496]
Typst's language is so elegant and intuitive that I intend to migrate from LaTeX. There are, however, some important features Typst lacks. For example, commutative diagrams arise frequently in [Category Theory](https://en.wikipedia.org/wiki/Category_theory) and Algebraic Geometry, they are as important as math equations.

LaTeX provides packages such as `xypic` and `tikz-cd` for drawing commutative diagram:

```latex
\xymatrix{
    A \ar[r] & B \ar[d] \\
    D \ar[u] & C \ar[l] 
}
```

See also

- [Stack Project](https://stacks.math.columbia.edu/) -- an open source textbook and reference work on algebraic geometry. They use [XyJax](https://github.com/sonoisa/XyJax) to render commutative diagram in webpage.
- [quiver](https://q.uiver.app/) -- a web editor for creating commutative diagram. It is capable of exporting to LaTeX via `tiz-cd`.

It is wonderful if this feature can be implemented in the foreseeable future!

**Comment by user202729** [comment]
https://gitlab.com/giacomogallina/typst-cd

A hack.

**Comment by ice1000** [comment]
Long equations on `typst-cd` doesn't seem very nice. But my level of familiarity on Typst does not allow me to make any constructive suggestions.

```typst
#align(center)[#commutative_diagram(
  node((0,0), $i=¬j$),
  node((0,2), $i≠j$),
  node((1,1), $(i=0 ∧ j=1) ∨ (i=1 ∧ j=0)$),
  arr((0,0), (0,2), $?$, "bij"),
  arr((0,0), (1,1), $?$, "bij"),
  arr((0,2), (1,1), $?$, "bij"),
)]
```

Rendered:
![image](https://github.com/typst/typst/assets/16398479/bd3b4f03-e672-4dd3-94cf-76c1b725b2f6)

**Comment by laurmaedje** [comment]
Commutative diagrams are probably not something we'll support in the core language directly as this is a good job for a package. As mentioned before, there already is one, it was renamed to `commute` in the meantime: https://gitlab.com/giacomogallina/commute. 

Regarding the point that long equations don't look nice there yet: Maybe open an issue on the linked repository? Perhaps it can be improved.

**Comment by AprilGrimoire** [comment]
Reminder for new users: the package `commute` is out-dated. Consider using [typst-fletcher](https://github.com/Jollywatt/typst-fletcher) instead.

**Comment by AshTS** [comment]
The `commute` package recently updated, allowing it to work with Typst 0.13 again. Version 0.3.0 fixes the deprecation error.
