### ISSUE TITLE
Heading spacing ignored in bibliography

### ISSUE THREAD

**Issue by EpicEricEE** [typst/typst#4963]
### Description

When setting the space below a heading, it is ignored for the bibliography's heading.
It works fine for normal headings (even with a grid as content, as it is the case with the bibliography) and also in the outline.

*This is a regression, it works fine in 0.11.1, but does not on main (tried with db71a178bef7f1525d732a190ac75a1a6d56f24b)*

**Example:**

<table>
<tr>
<td>

```typ
#show heading: set block(below: 1cm)

#outline()

= Normal Heading
#grid(
  columns: (auto, 1fr),
  column-gutter: 5mm,
  [Reference], [@test]
)

#bibliography("bibliography.yaml")

```

</td>
<td>
<img src="https://github.com/user-attachments/assets/672cd944-8a22-4e9f-b7be-420bbbf742eb">
</td>
</tr>
</table>

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by EpicEricEE** [comment]
Regressed with #4876

**Comment by laurmaedje** [comment]
Ok, so this is actually half bug, half regression. The default spacing was wrong on 0.11.1 as well (and that's why #4876 changes some reference images), but the fact that it can't be overridden is new.
