### ISSUE TITLE
tilde() in math mode looks weird on some capital letter

### ISSUE THREAD

**Issue by zhoutz** [typst/typst#4971]
### Description

The following code generate bad result on some capital letter, such as C,D,G,R.
I expect the tilde to appear wider and not lean to one side.
```typst
#set text(size: 50pt)
$tilde(A)tilde(B)tilde(C)tilde(D)tilde(E)tilde(F)tilde(G)$
$tilde(H)tilde(I)tilde(J)tilde(K)tilde(L)tilde(M)tilde(N)$
$tilde(O)tilde(P)tilde(Q)tilde(R)tilde(S)tilde(T)$
$tilde(U)tilde(V)tilde(W)tilde(X)tilde(Y)tilde(Z)$
```

<img width="369" alt="image" src="https://github.com/user-attachments/assets/664d642a-6c5b-4860-b381-96753f078a81">

### Reproduction URL

https://typst.app/project/rPD5hXmWLKmKVK4FeNtVrY

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
I'm closing this as not a bug.

The appearance is down to the math font, and the font designer's preference.

(Unless you claim it looks different using e.g. LuaTeX with unicode-math)
