### ISSUE TITLE
Support TOML files

### ISSUE THREAD

**Issue by HarmoGlace** [typst/typst#498]
As YAML support is being worked on, toml is also a useful user-friendly file format.

**Comment by laurmaedje** [comment]
Typically more for configuration than data though, in my experience. We can't support every format out of the box and I think with CSV, JSON, YAML, and XML we're quite well-equipped for now.

**Comment by HarmoGlace** [comment]
Well even if it's primarly made for configurations, it might still be useful as it is not currently possible to pass environement variables into the typst file. For instance, you could load a ``config.toml`` file where the authors are written, or anything else. This workaround is currently possible with json, yaml but not possible with toml, which is a way more user-friendly way to write and read data.
