### ISSUE TITLE
Add the fact that `image()` is a `block()`-based element to the documentation

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#4983]
I've looked at https://typst.app/docs/reference/visualize/image/ and there is no mention of block/box/inline in the description. In some cases you would like to know if you can, for example, add an image inline with text. But you don't know until you try it yourself or find a compatible example somewhere else in the docs. I want the documentation to state that `image()` is a `block()`-like element, not `box`-like. It will be a small change, but it can be embedded into existing sentences or be a new one.

It would be nice to have such a small but sometimes very important detail available to you quickly via docs instead of asking someone else.

**Comment by Enivex** [comment]
Correct me if I'm wrong, but isn't almost everything block level? I'm not sure it needs to be pointed out in the documentation of image in particular.

**Comment by Andrew15-5** [comment]
I don't know if everything or almost everything is block level. But adding this information _somewhere_ in the documentation will be a good idea. I don't know if it is already there and where to find it. That's why pointing this out on a per-element basis is a better solution from a user's perspective.

But I'm not sure whether there are a lot of elements to which you can ask this question, so you probably only need to edit the description of a couple of them. The `image()` is one bright example. I can't think of anything else on the spot.

**Comment by EpicEricEE** [comment]
The information exists in the documenation of the [`box`] element:

> All elements except inline math, text, and boxes are block-level and cannot occur inside of a paragraph.

**Comment by Andrew15-5** [comment]
Great. Though, I still think that we should add a statement to the image's docs. Like "`image` is a block-level element".
