### ISSUE TITLE
Bad way of calculating binomials in calc.binom

### ISSUE THREAD

**Issue by mjhuesmann** [typst/typst#4993]
### Description

calc.binom(n,k) calculates the binomial coefficient and does not work with n>61. Possibly the formula, that is used is 
$\frac{n!}{(n-k)! k!}$ .
It would be better use the product-formula: 
binom(n,k)= $\prod_{j=1}^k) \frac{n+1-j}{j}$ .
By using this method, the big values of n! don't appear and you can use it for bigger values of n.
I tried the following, and it works, but I am not a good coder:

`#let mybinom(n,k)={
  let erg=1
  let j=0
  while (j< k){
    j=j+1
    erg = erg * (((n+1) - j) / j)
  }
 erg 
}`

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
This is already the way it's implemented

https://github.com/typst/typst/blob/92ec56601831b9c454dbeaf28dba84e2769c7726/crates/typst/src/foundations/calc.rs#L534

The only limitation is that the computation has to be possible in 64 bit signed integers. I believe the first time this fails is for $n=63$ and $k$ near $63/2$.

**Comment by LaurenzV** [comment]
Is the problem that an intermediate value is too large, but the end result not necessarily? If so, maybe we could use i128 for the actual calculation and then try to cast back to i64?

**Comment by Enivex** [comment]
> Is the problem that an intermediate value is too large, but the end result not necessarily? If so, maybe we could use i128 for the actual calculation and then try to cast back to i64?

Technically you could get a handful of extra values that way, since you multiply and then divide. But it's not many.
