### ISSUE TITLE
Typst macport broken on latest MacOS Release

### ISSUE THREAD

**Issue by smorad** [typst/typst#4995]
### Description

I usually install the typst compiler using macports

`port install typst`

However, I recently upgraded to MacOS Sequoia and now, this command no longer works. I am not sure who is responsible for this port, but I will share the issue here as I think the maintainers might be interested in ensuring that `typst` works with popular package managers.

Following this github issue, https://github.com/zed-industries/zed/issues/12264 if I manually `cd` to the `typst` build directory and run `cargo update` before trying `port install typst`, then `typst` is successfully installed. It might be worth ensuring that `cargo update` runs before building `typst`.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by alerque** [comment]
I think this needs reporting to the macports repo not here.

**Comment by Coekjan** [comment]
If your rust version is higher than or equal to 1.80.0, `cargo install --locked typst-cli` would fail (see #4659). Could you please first check your rust version?

**Comment by smorad** [comment]
> If your rust version is higher than or equal to 1.80.0, `cargo install --locked typst-cli` would fail (see #4659). Could you please first check your rust version?

The port currently installs `rustc` version 1.81.0

**Comment by PgBiel** [comment]
> The port currently installs `rustc` version 1.81.0

Please try `cargo install --git https://github.com/typst/typst --branch 0.11 --locked typst-cli` (branch instead of `--tag`) and report back.

**Comment by smorad** [comment]
@PgBiel it does seem like the `cargo update` was sufficient to fix the problem, as apparently the `time` package had some breaking change. I am not sure if changing the `rustc` version is necessary. I also opened an issue on the macports tracker.

**Comment by laurmaedje** [comment]
Doesn't seem like there's anything to be done from our side.
