### ISSUE TITLE
Can't compile file

### ISSUE THREAD

**Issue by InAnYan** [typst/typst#5007]
### Description

When running:

```
typst compile main.typ
```

I'm having this:

```
error: failed to load file (access denied)
 = hint: cannot read file outside of project root
 = hint: you can adjust the project root with the --root argument
```

WTF?

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by InAnYan** [comment]
`typst compile main.typ --root .` doesn't work too

**Comment by InAnYan** [comment]
`sudo` doesn't work too

**Comment by Enivex** [comment]
Please post questions in the discord or forum instead of as a GitHub issue.

**Comment by InAnYan** [comment]
@Enivex I don't get it. I should run typst from `/`?
