### ISSUE TITLE
Counters broken in combination with text show rules

### ISSUE THREAD

**Issue by rwmpelstilzchen** [typst/typst#5014]
### Description

Consider the following short code:

```typ
#let letter-counter = counter("letter-counter")

#show regex("."): letter => {
  context{
    [#letter-counter.get().at(0) ]
    letter-counter.step()
  }
}

hello world
```

With the the stable release (`0.11.1`, packaged as `1:0.11.1-1` on Arch Linux) and with `typst-git-1:0.11.0.r294.g88325d7d0-1` https://github.com/typst/typst/commit/88325d7d0 from AUR (fetched from the `main` branch of this Git repository and compiled on the 2024-08-26 using [`typst-git`](https://aur.archlinux.org/packages/typst-git)) I get this expected result:

> 0 1 2 3 4 5 6 7 8 9 10

But when I installed yesterday the latest version using the same `typst-git` package (`typst-git-1:0.11.0.r348.g8c813cb7a-1`; https://github.com/typst/typst/commit/8c813cb7a) I get this unexpected result:

> 0 0 0 0 0 0 0 0 0 0 0

It seems like something went wrong with the way counters within show rules are treated in the newer version, or maybe I don’t understand something and this is the expected behaviour (and the old behaviour was wrong and fixed in some commit between the two Git `main` versions I checked). If it is the latter, how should one accommodate the above code to conform with the new way?

For context, if I add `#letter-counter.step()` right after the first line (`#let letter-counter = counter("letter-counter")`), this is the output I get with the latest commit:

> 1 1 1 1 1 1 1 1 1 1 1

So it seems `.step()`ing a counter works, but not within a show rule.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Interesting, thanks for reporting. This seems to be specific to text show rules. Something regressed there.

**Comment by rwmpelstilzchen** [comment]
Thanks!! 🌼

**Comment by laurmaedje** [comment]
Thanks for finding it!

**Comment by rwmpelstilzchen** [comment]
Yeah, this caused me some head-scratching when I didn’t understand what went wrong with my code for [Babel](https://codeberg.org/afiaith/babel) when I didn’t remember changing anything. After a while I understood I did change something — I upgraded Typst 🙃

**Comment by rwmpelstilzchen** [comment]
Cloned, compiled and tested: IWOMM 🙂
