### ISSUE TITLE
Broken word rendering with Noto Serif Bengali

### ISSUE THREAD

**Issue by nz366** [typst/typst#5023]
### Description

ত্তি or ত্[with-space]তি   word is not being correctly rendered when using Noto Bengali fonts. 
incorrect with noto font
![image](https://github.com/user-attachments/assets/7c2aca69-8444-4bd2-ab90-8590adbb2261)
correct with default font
![image](https://github.com/user-attachments/assets/9be1e9c1-185b-4e1a-9302-6c8eeee15e41)
correct in chrome with noto font
![image](https://github.com/user-attachments/assets/739498aa-6d37-48ca-b7d2-38255155a60b)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
Can reproduce on 0.11, but luckily it's already fixed on main (and will be part of 0.12):

0.11:
<img width="57" alt="image" src="https://github.com/user-attachments/assets/fa7581c4-9e67-43fb-bee5-b17967555297">

main:
<img width="48" alt="image" src="https://github.com/user-attachments/assets/7159dbf0-83b4-45e4-b5ac-35e9d71b64f0">
