### ISSUE TITLE
Panic when using `columns` element in multi-column page

### ISSUE THREAD

**Issue by EpicEricEE** [typst/typst#5024]
### Description

_A regression introduced with #5017_

While it is kind of an odd thing to write, the code
```typ
#set page(columns: 2)
#columns(2)[Hello]
```

now leads to the panic
```
thread 'main' panicked at crates\typst\src\layout\flow\collect.rs:441:35:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

while previously, the content was then laid out in a total of four columns.

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
no, of all places why `collect.rs:441` 😢

**Comment by laurmaedje** [comment]
ok, I think I know what's happening. shouldn't be that hard to fix.
