### ISSUE TITLE
'Could not infer output format' errors are too lazy

### ISSUE THREAD

**Issue by emilyyyylime** [typst/typst#5042]
### Description

I went to check if something compiles by simply running `typst c - /dev/null`. Typst started up normally and I wrote a small document but then Typst stopped with the error
```
error: could not infer output format for path /dev/null.
consider providing the format manually with `--format/-f`
```
1. Typst should eagerly emit this error before even attempting to read input
2. Some built-in way to specify that no export is required (`--format none`?) would be nice.

- [X] I am using the latest version of Typst

**Comment by emilyyyylime** [comment]
If you like the suggestion in point 2, I'd like to have a go at implementing it myself

**Comment by emilyyyylime** [comment]
Although this would become pretty irrelevant with some form of repl

**Comment by laurmaedje** [comment]
The idea of `--format none` being to just check for errors?

**Comment by emilyyyylime** [comment]
yeah, or maybe a dedicated `typst check` or `--dry-run` etc.

**Comment by laurmaedje** [comment]
Closed by https://github.com/typst/typst/pull/5080. The just checking part is covered by https://github.com/typst/typst/issues/3792.
