### ISSUE TITLE
Compiler crash when adding 100% pad

### ISSUE THREAD

**Issue by knuesel** [typst/typst#5044]
### Description

Adding ≥ 50% padding to a block (not saying it makes sense) seems to send the compiler spinning (max CPU, increasing memory use) until it gets killed, for example compiling

```
#pad(100%, block(width: 1cm, height: 1cm))
```

gives "Job 1, 'typst c a.typ' terminated by signal SIGKILL (Forced quit)"

This happens on 0.11.1 and current main.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by bluebear94** [comment]
I’ve traced this down to an infinite loop in `typst::layout::container::distribute` when `regions.size.y` is negative.
