### ISSUE TITLE
Default once-nested bullet list marker always uses Linux Libertine font

### ISSUE THREAD

**Issue by quachpas** [typst/typst#5049]
### Description

Hello!

The second default marker in bullet list `marker` is always rendered with Linux Libertine somehow. Not sure if it's reproducible on other environments. I am on Linux.

```
#set text(font: "New Computer Modern")

- First item
  - First subitem
    - First subsubitem
      - First subsubsubitem
- Second item
```
```shell
❯ pdffonts test.pdf
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
JAUHUI+NewCM10-Regular-Identity-H    CID Type 0C       Identity-H       yes yes yes      4  0
DZPBJD+LinLibertine                  CID TrueType      Identity-H       yes yes yes      9  0
```
![image](https://github.com/user-attachments/assets/25036f0a-e8d3-41ba-81c4-b1c0d0f80c7c)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by mkorje** [comment]
This is because the font fallback is being triggered. New Computer Modern doesn't have the glyph used as the second bullet marker. You can see this by setting `fallback: false` on the text function.

**Comment by quachpas** [comment]
Aha, I didn't know about the fallback option. That seems to be a font issue, indeed.
Thanks for helping me sort this out!
