### ISSUE TITLE
Unicode symbols aren't colored correctly

### ISSUE THREAD

**Issue by Tandrial** [typst/typst#5052]
### Description

There is a regression bug with coloring unicode symbols in the current dev-version (efc6b710), text with a fill argument doesn't correctly color the symbol:

![image](https://github.com/user-attachments/assets/7b233fb9-7594-43b1-8f00-76de4402ac42)

Compare with the current release version:
![image](https://github.com/user-attachments/assets/0f16ab22-66fb-400c-9705-a28595a47233)

Not 100% sure if the symbol is correct to begin with since its [supposed to be filled](https://www.compart.com/en/unicode/U+25FC).

Code to reproduce:

```
#text(fill: red)[TESTING \u{25FC}]
```

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by bluebear94** [comment]
I think this is happening because the `\u{25FC}` character is an emoji and is being rendered with a colored emoji font.

**Comment by Tandrial** [comment]
So the current release if broken, because it ignores symbols with colors, which the new version fixes. Or is there more going on here?

**Comment by FlorentCLMichel** [comment]
My guess (but I'm not 100% sure—hopefully someone more knowledgeable than I am can correct me if I'm wrong) is that they may both be correct but use different default fonts: one without coloured emojis for the current release (do all symbols are filled with the text colour) and one with coloured emojis on main.

**Comment by LaurenzV** [comment]
Yes, so what's probably happening here is that the default Typst font doesn't have a glyph for that character, so it falls back to (presumably?) Twitter Color Emoji, which uses an SVG file to represent the glyph, so it always stays black. Somewhat unideal, but not sure whether it warrants the "urgent" label anymore.

**Comment by LaurenzV** [comment]
Oh wait, so am I understanding it correctly that it works fine on current main?

**Comment by Tandrial** [comment]
> Oh wait, so am I understanding it correctly that it works fine on current main?
Depends on what you mean by "works fine". With the current commit ([022f34c](https://github.com/typst/typst/commit/022f34c43a2fb3084b93500163a601105ab582a4)) on main you get the colored emoji, if the font used has it (it just happens to be a black square for that specific glyph (`\u{25FC}`) and any color that might be set for that text is ignored.

Compared to the version from the release page(https://github.com/typst/typst/releases/tag/v0.11.1), where the colored emoji is ignored and I guess the .svg version is used, which can be colored.

To me that makes sense, but I kinda would expect, that if I'm changed the color of the text that the colored emojis are overridden, i.e. the behavior of the release version

**Comment by LaurenzV** [comment]
> To me that makes sense, but I kinda would expect, that if I'm changed the color of the text that the colored emojis are overridden, i.e. the behavior of the release version.

Right, but the problem is if the font provides an SVG, we can't really change the color of that SVG, unless it uses the `currentColor` feature, which is currently unsupported but already tracked here: https://github.com/typst/typst/issues/4973

**Comment by Enivex** [comment]
Is this really even a bug @LaurenzV ?

**Comment by laurmaedje** [comment]
I think if the colorable symbols are desired, another font should be used. Noto Sans Symbols might work. Anyway, it looks like it's not a bug.
