### ISSUE TITLE
Difficulties with citations -- Advice: Use CSL

### ISSUE THREAD

**Issue by njbart** [typst/typst#506]
I tried a few things in the web application and immediately encountered difficulties, especially with quotations:

- valid biblatex `pages = {S11-S20},` -- Error: `failed to parse biblatex file: invalid number in line ...`

- valid biblatex cite key `@gowdy.etal:2013economic` (dots and/or colons) -- Error: `label does not exist in the document line ...`

- style apa -- Bibliography not sorted alphabetically.

Also, calling a style "author-date" is misleading, since there are thousands of different author-date styles (including APA [!]). If it is Chicago, it should be called Chicago (and in the specific case of Chicago, note that there is both a Chicago Notes and a Chicago Author-Date style that should not be confused).

Admittedly, I have only scratched the surface so far. Nevertheless, I do recognise the typical teething troubles in trying to implement citations and bibliographies correctly here, and I am sure that many more problems will emerge with further testing. With this in mind, I would seriously suggest abandoning the current attempts to introduce yet another variant of a citation processor (referred to elsewhere, I think, as reinventing the wheel) in favour of integrating a CSL processor, for which there are a number of reference implementations, detailed test suites and, not least, many thousands of elaborated styles, and which I expect will ultimately save years of development work.

**Comment by laurmaedje** [comment]
Yes, we are looking into using CSL.

**Comment by njbart** [comment]
Great. I will be happy to help, at least in terms of testing, when CSL is being integrated.

**Comment by njbart** [comment]
Note that there is no such thing as a “Chicago Author-Title” style. 

From the CMOS website: “Chicago-style source citations come in two varieties: (1) notes and bibliography and (2) author-date” (https://www.chicagomanualofstyle.org/tools_citationguide.html).

The “notes and bibliography” form endorsed by CMOS is implemented, e.g., by [chicago-fullnote-bibliography.csl](https://www.zotero.org/styles/?q=chicago-fullnote-bibliography), and contains full references in foot- or endnotes, and subsequent citations of sources already given in full in a short form, usually author and title. There is also a [chicago-note-bibliography.csl](https://www.zotero.org/styles/?q=chicago-note-bibliography), AFAICT not officially supported by CMOS (as judged by CMOS 17e 14.29 ff.), which uses short forms in notes throughout. Still, none of these styles has ever been called “author-title”.

The only style explicitly supported by any of the reputable style manuals I am aware of that might come close is MLA, which uses "(author(s), title page(s)" in-text when more than one work by an author (team) is cited. Otherwise it is simply "(author(s), page(s)". But if you wish to follow this basic pattern, you would of course have to implement the MLA rules, and name the style accordingly. (And no, I have never heard this style being called author-title either.)

Or just adopt CSL, and leave it to the CSL authors to take care of such details :-).
