### ISSUE TITLE
Table content descent overlaps with cell border

### ISSUE THREAD

**Issue by cmoog** [typst/typst#507]
```
#table(columns: 2, 
  "equation", "description",
  $integral_0^1 x dif x = c$, "integral"
)
```

<img width="492" alt="Screenshot 2023-04-01 at 10 36 46 AM" src="https://user-images.githubusercontent.com/7585078/229299162-c096ba45-363e-4594-8cfa-237e29bdc64e.png">

```
#table(columns: 2, 
  "equation", "description",
  $integral_0^1 x dif x = c$, text(size: 40pt, "testing")
)
```

<img width="733" alt="Screenshot 2023-04-01 at 10 39 35 AM" src="https://user-images.githubusercontent.com/7585078/229299292-a0cb4f72-147d-4ad0-8b98-402efaee263d.png">

**Comment by laurmaedje** [comment]
Closing in favor of #1028, which has the same underlying issue.
