### ISSUE TITLE
`#show par` block spacing command not working in latest commit

### ISSUE THREAD

**Issue by brynne8** [typst/typst#5077]
### Description

I have recently compiled the latest commit from the Typst repository and encountered an issue with the `#show par: set block(spacing: 0.65em)` command. It seems that changing the block spacing value has no effect on the paragraph spacing, regardless of the value I provide.

This issue did not occur in previous versions (release v0.11.1 worked well), and I have tried using various values for the `spacing` parameter, but none of them produce the expected results.

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
This is intentional, please use `#set par(spacing: 0.65em)`. See here: https://github.com/typst/typst/pull/4390

This PR will add a warning with an explanation: https://github.com/typst/typst/pull/5076
