### ISSUE TITLE
Indentation on multiline headings

### ISSUE THREAD

**Issue by diaopal** [typst/typst#5079]
### Description

Previously on nightly, there was an indentation on the headings, but that has been fixed. Now there's an indentation on multi line headings. Is this supposed to happen?

Note: I used `set heading(numbering: "1.")`
 
Version 0.11.1 (May 17, 2024) **expected result**:

<img width="1165" alt="v0 11 1" src="https://github.com/user-attachments/assets/e64ff520-9751-460b-bc7b-c1d3af72e563">

<br>
<br>

Nightly (https://github.com/typst/typst/commit/1a24b29d86dfe72e0d3c7f79475c187ed4df5e5a) **actual result**:

<img width="1165" alt="nightly" src="https://github.com/user-attachments/assets/03aed5cc-403c-4db7-9438-8b5dbfaed2f3">

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This is intentional and also what most other typesetting software does by default. 

If you dislike it, you can `#set heading(hanging-indent: 0pt)`
