### ISSUE TITLE
Time in terms

### ISSUE THREAD

**Issue by ondohotola** [typst/typst#509]
How do I display a time in a term

```typst
/ 19:15 This is quarter past seven
```
so that it displays

**19:15** This is quarter past seven

instead of

**19**  15 This is quarter past seven

which is what it does now?

perhaps `terms` should require [: ] at the end of the term?

**Comment by laurmaedje** [comment]
There are multiple options. You can escape the colon like this:
```
/ 19\:15: This is quarter past seven
```
Or, for longer stuff, you can wrap it in a content block:
```
/ #[19:15]: This is quarter past seven
```

**Comment by ondohotola** [comment]
Thank you, this i very helpful.

While I have your attention, is it possible to hang the indent but the length of the label?
```
19:15 This is quarter past seven and this is blind text to fill the line until it reaches the new
      Line and the 'L' from 'Line' sits exactly under the 'T' from 'This'.
```
If this is somewhere in the Manual, please point me to it, I am willing to RTFM.

Gruss aus dem Süden.

**Comment by laurmaedje** [comment]
Not in the default style, but you can write your own. Depending on what you want, there are two options:

This hangs the description with the length of the term, but each one individually:
```
#show terms: it => {
  for child in it.children {
    grid(
      columns: 2, 
      gutter: 10pt,
      strong(child.term), 
      child.description
    )
  }
}
```

This hangs the descriptions with the length of the maximum term in the whole term list (more like a table).
```
#show terms: it => grid(
  columns: 2,
  gutter: 10pt,
  ..it.children
    .map(child => (strong(child.term), child.description))
    .flatten()
)
```

**Comment by ondohotola** [comment]
Thank you so much I used a table without stroke but didn’t figure out how to bold the first column yet. Will try this when I get back home :-)-O

What do you think about a separate “group” like the Discussions, “Tips & Tricks” or so, where one can ask those questions and does not clutter the (development) Issues group?

Gruss aus dem Süden.
