### ISSUE TITLE
Whitespaces became [U+202A]

### ISSUE THREAD

**Issue by diaopal** [typst/typst#5091]
### Description

Steps to reproduce:

1. Generate pdf and open pdf
2. Copy text
3. Paste in VS Code
4. Whitespaces either become [U+202A] or the [U+202A] character is between the whitespaces.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
- Is this happening with _any_ document?
- What happens if you use a different pdf reader?
- What happens if you copy into something else than VS Code?

There's a lot of steps where something can go wrong here. Copying text from PDF isn't great even under the best of circumstances.

**Comment by diaopal** [comment]
No issues on `0.11.1`, but occurs on `main`.
I've tried firefox's pdf viewer and MacOS' preview app, same issue.

I found the culprit. It's if `#outline()` is used.
Here's a minimal reproducible example:
```typst
#outline()

= Lorem ipsum dolor sit amet.

Lorem ipsum dolor sit amet.
```

Here's what happens if I copy and paste it here`Lorem‪ipsum‪dolor‪sit‪amet.` (U+202A is in that text)

**Comment by laurmaedje** [comment]
Cause must be https://github.com/typst/typst/pull/4491. Though there's nothing wrong with that PR I think, but rather maybe with the fact that these codepoints somehow end up in the PDF's CMap.
