### ISSUE TITLE
German words enclosed in parentheses are incorrectly hyphenated

### ISSUE THREAD

**Issue by jensmueller-com** [typst/typst#5103]
### Description

German words are incorrectly hyphenated when they are enclosed in parentheses. For example, the correct hyphenation of the word "Freitag" is "Frei-tag". However, when enclosed in parentheses, Typst uses the following hyphenation:

```
(F-rei-ta-g)
```

I have not checked whether this problem also occurs for other languages.

### Reproduction URL

https://typst.app/tools/hyphenate/

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Can you also reproduce this in Typst itself or only in the hyphenate tool?

**Comment by jensmueller-com** [comment]
I encountered this problem in Typst itself:

![screenshot](https://github.com/user-attachments/assets/1a141838-64d7-4ae4-9424-786c1b38ff19)

**Comment by laurmaedje** [comment]
It was most likely fixed by https://github.com/typst/typst/pull/4498 (not yet released, but soon). If you share a complete snippet, I can try.

**Comment by jensmueller-com** [comment]
Input:

```
#set par(justify: true)
#set text(lang: "de")

Morgen ist ein neuer Tag (Freitag). Morgen ist ein neuer Tag (Freitag). Morgen ist ein neuer Tag (Freitag).
```

Output (Typst 0.11.1):
```
Morgen ist ein neuer Tag (Freitag). Morgen ist ein neuer Tag (Freitag). Morgen ist ein neuer Tag (F-
reitag).
```
