### ISSUE TITLE
Improve support for swedish figures and references

### ISSUE THREAD

**Issue by kacper-uminski** [typst/typst#5109]
### Description

When writing a text in swedish (i.e with `set text(lang: "sv")`, we do not capitalize references to figures and tables when they are in the middle of a sentence. I thus want to ask if it would be possible to set the default `ref(supplement)` to a lower-case value for figures and tables respectively? This still needs to be possible to overwrite when beginning a sentence with a reference. Ideally, typst would detect new sentences automagically and use the upper case, but that may not be realistic to implement for now. :)

Lastly, tables should have their captions appear on top by default as this is the swedish convention. Normal figures should still have their captions on the bottom. This I have accomplished with a simple show rule:
```typst
show figure.where(kind: table): set figure.caption(position: top)
```

Use [this page](https://writing.chalmers.se/chalmers-skrivguide/en-vetenskaplig-rapport/934-2/) from Chalmers University as a reference. (It's in swedish, but translate should work.)

### Use Case

This would make writing swedish texts a bit nicer for all of us who need to do that. :)

**Comment by Andrew15-5** [comment]
This was mentioned in https://forum.typst.app/t/swedish-references-to-tables-and-figures-should-not-be-capitalized/913/4.

**Comment by Enivex** [comment]
The title of the issue seems overly narrow for what you actually want. This is surely not limited to Swedish.

(And I doubt there is only one convention in any given language.)
