### ISSUE TITLE
Page-based footnote numbering

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#5111]
### Description

There should be a way to number footnote independently on each page, starting back at 1 every page (or every even page).

### Use Case

Some books reset the footnote counter back to one every page (or every even page).

I am aware implementing this may result in some tricky questions, such as what to do when a footnote entry is pushed to the next page. I don't know what publishers typically do in those cases (other than avoiding them, or using global footnote numbering).

**Comment by EpicEricEE** [comment]
This should be easily doable by resetting the footnote counter in the page header. You can even check if the page number is even there.

> what to do when a footnote entry is pushed to the next page

As far as I know, the footnote entry will always be on the page as the definition, so this shouldn't be an issue.
