### ISSUE TITLE
Wrong query order for tags directly before placed elements

### ISSUE THREAD

**Issue by aaron-jack-manning** [typst/typst#5117]
### Description

It's not clear to me if this is a bug or an intended breaking change, however the following code compiles with `0.11.1` but not with the `0.12.0` release candidate, with the error being that the query does not find anything.

```
#set page(width: auto, height: auto)

#show figure: it => {
  context {
    let value = query(selector(<test>).after(here())).first().value

    value

    it.body
  }

  place(it.body)
}

#figure[
  #metadata("abc") <test>

  This is a test.
]
```

If the query is changed to `before` then the layout does not converge, and if the `before`/`after` condition is removed the code works but there is no way to guarantee that I am retrieving the correct label when multiple appear in the document. It seems counter-intuitive to have an element appear in the document but not be before or after the current location.

If this is an intended change, is there a new way to handle querying elements which use the `place` function?

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
The problem is that tags are only flushed for frame items in the distributor, not for placed elements, so they migrate past placed elements and end up after them in the layout. They should be able to migrate past spacing and pagebreaks, but maybe not placed elements.
