### ISSUE TITLE
SVG picture not properly rendered in pdf

### ISSUE THREAD

**Issue by oliviermeslin** [typst/typst#5121]
### Description

The official Python logo is not rendered properly in the pdf output: the bottom and right parts of the logo are cut.

Link to the official logo: https://s3.dualstack.us-east-2.amazonaws.com/pythondotorg-assets/media/files/python-logo-only.svg

### Reproduction URL

https://typst.app/project/pTTYYv1DKO7TR_hGfA47xJ

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
Sounds like https://github.com/typst/typst/issues/3733, did you try using 0.12?

**Comment by oliviermeslin** [comment]
No, I hadn't seen Typst 0.12 Testing was available. With this new version the problem is solved. Thanks!
