### ISSUE TITLE
Weird PDF pages output in Okular after using `--pages` flag (that should remove unused pages)

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#5129]
### Description

```typ
One
#pagebreak()
Two
#pagebreak()
Three
#pagebreak()
Four
#pagebreak()
Five
#pagebreak()
Six
#pagebreak()
Seven
```

Then I used `--pages=1,2,5-6` (with Typst v0.12.0-rc1) which still shows all 7 pages in Okular. Moreover, the last 3 pages appear white despite inverted colors being on. It also reports their paper size to be "161 x 228 mm (Portrait Envelope CS)". And _also also_ it shows weird 3 numbers at the bottom instead of normal 2:

![image](https://github.com/user-attachments/assets/a3a3b020-9080-4e77-b3fe-9028e211177b)

[2024-10-05T14:20:16Z.pdf](https://github.com/user-attachments/files/17266072/2024-10-05T14.20.16Z.pdf)

I expect it to work just like any PDF cutter/splitter, e.g., `pdftk cat 1,2,5-6`.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
> And also also it shows weird 3 numbers at the bottom instead of normal 2:

That is expected and also happened before Typst 0.12.0. Whenever the page numbering is changed (e.g. `#set page(numbering: "a.")`), the PDF real page number doesn't correspond to the Typst page number, so we add a _page label_ to the left which indicates the Typst page number. Here, the page numbering format wasn't changed, but the assertion "PDF page number != Typst page number" still holds, so we display the Typst page number as well. See: https://github.com/typst/typst/pull/4039#issuecomment-2099550893

**Comment by PgBiel** [comment]
I can confirm there was a regression in the `--pages` option. Need to take a look.

**Comment by PgBiel** [comment]
Bisected to 2946cde6fa1b9039fe5de1cded2e0c697575b81d (#4154)

cc @elegaanz
