### ISSUE TITLE
Underscore can be used as a variable

### ISSUE THREAD

**Issue by Marmare314** [typst/typst#513]
Currently `_` is a valid identifier so
```
#let _ = 4
#_
```
is valid typst code. At the moment I don't think this is bad, but after #341 this would become a bit confusing because
```
#let (a, _) = (1, 2)
#_
```
would throw an error.

**Comment by Dherse** [comment]
I agree, I thin that underscore should be a kind of "trash" variable, whatever you put in there is discarded and using it causes a hard error.

**Comment by user202729** [comment]
For comparison Python does not special-case `_` either, I feel adding this special case would cause more confusion (in addition to complicating the implementation of Typst) than helps.

Nothing in #341 require that `_` must be discarded. It can just be assigned the value `2`.

And there are people who use `__` instead (maybe out of convention `_` is `i18n.gettext`), and it wouldn't help either.

**Comment by Dherse** [comment]
Well, my idea here is that this is what rust does. And in general, I find that the design decisions of rust make a lot of sense. I think these kinda of nitpicky/bikesheddy things will always make people discuss for eons. If it is kept as an ident typst will be fine, if it is made into a special case, typst will be fine.

However, one reason why a """trash""" variable might be useful is in destructuring, image the following:
```example
let (a, b, _, _, c) = (1, 2, 3, 4, 5)
```

There are people working on such a PR and I think it would be preferable for a discard variable and dissallow (in destructuring) binding multiple times to the same value to avoid sneaky errors.

**Comment by user202729** [comment]
Alright, just let the Typst team decide then.

I guess it's not totally unreasonable given, yes, that's what Rust do.

Meanwhile Python also allow assigning to same variable multiple time in a destructuring so...

**Comment by Dherse** [comment]
I think we'll be fine either way. I do see what you mean with destructuring to the same variable, but I fear this might be error prone.

**Comment by laurmaedje** [comment]
For Rust it's important to make the distinction though because discarding affects moving and drop. Whereas for Typst, that stuff doesn't really matter.

**Comment by Dherse** [comment]
If I were to do `let x = counter("hello").update(1)`, if x isn't used, it has no effect no? it could be made more obvious with underscore, or am I misunderstanding?

**Comment by Marmare314** [comment]
As @user202729 said, it was not necessary to change this. Since there don't seem to be many benefits to disallowing `_` as variable it be stay as it was.

**Comment by Marmare314** [comment]
I am currently working on enabling the destructuring syntax for assignments. With that there are a few more things to consider in this discussion. Consider the following code
```
let (a, b) = (none, none)
(a, _, _, b) = (1, 2, 3, 4)
```
I think that this should definitely be allowed, because `let (a, _, _, b) = ...` is allowed. But then we have two options. Either we define `_` if it does not exist yet, or we disallow `_` as an identifier.
I prefer disallowing `_` because I do not like an implicit `let` binding.

**Comment by Dherse** [comment]
Additionally, @astrale-sharp is working on a `pipe` operator PR, which also uses the underscore for destructuring to indicate "missing values" in function calls. Therefore, I do feel like it also makes sense in this case to disallow `_` as a "regular" variable, instead keeping it as a reserved variable for those syntaxes at least.

**Comment by astrale-sharp** [comment]
I'll push a PR forbidding it today
________________________________

**Comment by astrale-sharp** [comment]
for me this should create an error at parsing time for cases such as 
```
#_
#lorem(_)
```
I can different ways for doing this:
- either each time you try to eat an ident, you put a marker first and then you call `validate_ident` except when you're in a Pattern.
- or you replace all eating of an ident by a function ident(p: &mut Parser) (like you call markup when you want to parse markup), that errors on ident being "_" (it can have an option to accept "_" and the option be on while on (I prefer this as it will clutter the code less) <--- simplest option
- Parse "_" as a different token that is expected only in patterns, might lead to code that is more neatly seperated/ natural and it makes sense, it also makes it easier to understand what will be happening while looking at the code (for newcommers) <--- best option IMO

thoughts?

**Comment by laurmaedje** [comment]
Last option (separate token) seems by far the best and simplest to me.

**Comment by astrale-sharp** [comment]
I started experimenting with the last option, some things are not nice so far.

- I have a 
```
+pub enum MaybeIdent {
+    Ident(Ident),
+    Underscore(Underscore)
``` 
used for evaluating patterns but I cannot use `self.0.cast_first_match::` everywhere anymore (if both return some, I would need to know which one matched first which is not possible without adding such a method.

`collection(p, true,false);` and `item(p, keyed, accept_underscore)` have a new bool for indicating if they should accepts underscore or not. 
This complicates the signature everywhere in the parser whereas it's only needed in two places.
The boolean could also be replaced by rust enum s for more readability on github's diffs

This has also revealed some difficulty working with the parser: 
  - Some calls like `code_expr(p)` turn into
```
if !p.eat_if(SyntaxKind::Underscore) {code_expr(p);}
```
which is fine cause it's used everywhere in the parser but the cognitive overhead is real to understand what the parser is doing
 
  - some function like `code_expr` can be called multiple times without causing an error and you have to check if progress was made yourself, whereas some function errors if you find unexpected things.
It makes sense but 
    + it should be documented (I could do that) 
    + If you suddenly need a function to start or stop erroring it's not simple and you have to refactor some code. (Not a big problem, but coupled with the lack of logging in the parser it can be a bit cumbersome, logging could easily be added though).

This is where a bit of abstraction could come in handy and it would probably be a bit nicer to work with chumsky or something.

One thing that I could imagine in chumsky is having an `code_expr` parser for instance and just calling a function on it would transform it into an erroring on no progress `code_expr` parser. (just an example, it would be generalised) 
That would make explicit what you're expecting your parser part to error on, just putting ideas here.

Maybe I missed simpler alternatives, I also love advice. thoughts? 
@Marmare314 @laurmaedje @ **Anyone else interested**


This is nothing blocking, but it might give ideas on how to tackle technical debt, as well as changing some design bits before I put up a solution that's too hacky and need to be reworked anyway (or adds technical debts)
