### ISSUE TITLE
Line-numbers for equations only work with numbered equations

### ISSUE THREAD

**Issue by CGMossa** [typst/typst#5130]
### Description

Line numbers feature of typst v0.12.0-rc1 only display line number on equations if they are numbered.
Here's an example: 
```typ
#set page(paper: "a7")
#set par.line(numbering: "1")
//#set math.equation(numbering: "1") // this is necessary to have line-numbers appear for equation! Bug?
#lorem(10)
$
dot(S) &= -beta S I,\
dot(I) &= +beta S I - gamma I,\
dot(R) &= +gamma I,
$
#lorem(20)
```
![image](https://github.com/user-attachments/assets/e26b0690-42f9-4939-978b-94b1f049bfde)

**Instead, I think line-numbers should not number a numbered equation, because the equation number serves as a line number.** Or some other meaningful default behaviour.

Alternatively, to change the default behavior, I have to do the following:

```typ
#set page(paper: "a7")
#set par.line(numbering: "1")
#set math.equation(numbering: "(1)")
#show math.equation: it => if it.numbering != none { set par.line(numbering: none); it } else { it }
#lorem(10)
$
dot(S) &= -beta S I,\
dot(I) &= +beta S I - gamma I,\
dot(R) &= +gamma I,
$
#lorem(20)
```
![image](https://github.com/user-attachments/assets/02b05112-e566-4061-aeb5-6559854fe88a)

(Credit goes to @Andrew15-5 for the suggestion and @PgBiel for the show-rule)

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
It's not a bug per se, it's just that the number itself is numbered as it has text and thus constitutes a paragraph, but the equation itself has no paragraphs, so there are no lines to be numbered.
We could consider extending this behavior to equation lines, but I'm not sure what is most common in academia. For the time being, I'd suggest disabling line numbers for equations entirely:

```typ
#show math.equation.where(block: true): set par.line(numbering: none)
```

**Comment by CGMossa** [comment]
Right, to summarise: I believe labelling equations with line-numbers should be disabled by default, for typst v0.12.0, and once proper labelling support (by having proper equation numbering support) lands, this default can be revisited.

**Comment by laurmaedje** [comment]
https://github.com/typst/typst/pull/5163 disables line numbering for equations by default.
