### ISSUE TITLE
Asterisk changes on function call inside math

### ISSUE THREAD

**Issue by jmigual** [typst/typst#5141]
### Description

So, I'm trying to test whether a math function has an asterisk:

```typst
#let test(m) = {
  [#(m == "*", m == $*$)]
  m
}

$test(*)$
```

This produces:
![image](https://github.com/user-attachments/assets/e72dedb4-d1c4-42ba-b52a-5beb054e9653)

However, if I call the function as `$test("*")$` this produces:

![image](https://github.com/user-attachments/assets/f6c29a48-55e4-4813-8861-1a87351dc034)

I've also tested:

```typst
#[#($*$ == $*$)]
```

![image](https://github.com/user-attachments/assets/cbb63919-8f9e-4b2a-a6a2-6750754eec7b)

It looks to me that when I pass `"*"` as a function argument inside math mode, that the asterisk gets replaced by something else that doesn't equal `$*$` but I think that it should equal `$*$` as, when it gets printed and everything, it behaves as such.

I've also tried `"∗" == m` or `$∗$ == m` (the rendered character ∗) but it also didn't work.

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by MDLC01** [comment]
There are two things happening here.

First, in math, the asterisk is a replaced by an asterisk operator (similarly to how `->` is replaced with an actual arrow). This explains why `m != "*"`.

The reason why `m != $*$` is because `$*$` is a `math.equation`, whereas the left hand side is just an asterisk operator, not wrapped inside a `math.equation` element.

So this is working as intended.

**Comment by jmigual** [comment]
So, how can I compare against an asterisk operator?

**Comment by MDLC01** [comment]
`m == sym.ast.op` may work, but I'm not sure. You should open a GitHub discussion or a [forum thread](https://forum.typst.app).

**Comment by EpicEricEE** [comment]
There seems to be something weird going on with symbol comparisons, as `m == sym.ast` doesn't work, but `str(m) == str(sym.ast)` does, even though both `m` and `sym.ast` are of type `symbol`.

**Comment by jmigual** [comment]
That didn't work but this did work:

```typst
#let test(m) = {
    [#($#m$ == $*$)]
}
```

This prints `true`. Basically wrap the operator inside a math environment and compare against another operator inside the math environment. Thanks for the help!
