### ISSUE TITLE
Compile fails in latest docker image

### ISSUE THREAD

**Issue by Regenhardt** [typst/typst#5145]
Last night my pipeline pulled the latest docker image, ran "typst compile input.typ output.typ" and produced the following error message: 

```
Using docker image sha256:11d6daf74ac485f2fb2af107572711eb6ae701843700efed3b36fa73cea2de67 for ghcr.io/typst/typst:latest with digest ghcr.io/typst/typst@sha256:350e4c2d3e3d1a5f947729691589293d638c2697d93768feddda99938aebb0a6 ...

error: unrecognized subcommand 'sh'

Usage: typst [OPTIONS] <COMMAND>

For more information, try '--help'.
```

Both source and pipeline job are public if you'd like to have a look: https://gitlab.com/Regenhardt/bachelorarbeit/-/jobs/8006898389

**Comment by laurmaedje** [comment]
Probably due to https://github.com/typst/typst/pull/3798. 

cc: @drupol

**Comment by drupol** [comment]
I'll double check later in the day, I'm not anywhere near a computer at the moment.

**Comment by quachpas** [comment]
In GitLab CI/CD it's possible to [override the entrypoint](https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#override-the-entrypoint-of-an-image) to recover previous behaviour:
```yaml
  image:
    name: ghcr.io/typst/typst:latest
    entrypoint: [""]
```
For GitHub, would probably work similarly https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runsentrypoint

**Comment by Coekjan** [comment]
It's definitely caused by the changes of entrypoint, I think.

BTW, the README should be updated, like:

```patch
  - Docker users can run a prebuilt image with
-   `docker run -it ghcr.io/typst/typst:latest`.
+   `docker run ghcr.io/typst/typst:latest --help`
```

**Comment by laurmaedje** [comment]
Updated README in https://github.com/typst/typst/pull/5147

**Comment by Regenhardt** [comment]
> It's definitely caused by the changes of entrypoint, I think.
> 
> BTW, the README should be updated, like:
> 
> ```diff
>   - Docker users can run a prebuilt image with
> -   `docker run -it ghcr.io/typst/typst:latest`.
> +   `docker run ghcr.io/typst/typst:latest --help`
> ```

Is this just to counter the fact a terminal is being started as entrypoint? I feel like the entrypoint of the image should be removed/fixed instead.

**Comment by drupol** [comment]
> Is this just to counter the fact a terminal is being started as entrypoint? I feel like the entrypoint of the image should be removed/fixed instead.

You can override it at will as mentioned in previous comment. But I would keep the entry point being `/bin/typst` by default in this case.

**Comment by laurmaedje** [comment]
I'm not a Docker expert, but based on the comments here and in the linked PR and the [Docker documentation](https://www.docker.com/blog/docker-best-practices-choosing-between-run-cmd-and-entrypoint/), it seems like everything is correct here.
