### ISSUE TITLE
Block spacing not working in 0.12.0 Testing

### ISSUE THREAD

**Issue by peng1999** [typst/typst#5152]
### Description

MWE:

```typst
#set block(spacing: 10pt)

#let f(a) = {
    set block(spacing: 1pt)
    a
}

#lorem(10)

#lorem(10)

#lorem(10)

#f[
    #lorem(10)

    #lorem(10)

    #lorem(10)
]
```

0.11.1:
<img width="377" alt="图片" src="https://github.com/user-attachments/assets/2701b2ef-febb-4fa0-9af6-52065bc3311d">

0.12.0 Testing:
<img width="388" alt="图片" src="https://github.com/user-attachments/assets/be309aec-cae4-40d2-9c21-7993301bbb83">

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This was an intentional breaking change. See https://github.com/typst/typst/pull/4390.

**Comment by peng1999** [comment]
I see. Maybe breaking changes deserve their own section in the Changelog for better visibility.
