### ISSUE TITLE
(Re-)add support for `calc.round()`ing to integer digits

### ISSUE THREAD

**Issue by Mc-Zen** [typst/typst#5155]
### Description

Before Typst 0.12, it was possible to round to integer digits using [`calc.round()`](https://typst.app/docs/reference/foundations/calc/#functions-round) by passing a negative `digits` argument. Apparently, this "feature" was rather [based on a mistake and somewhat broken](https://github.com/typst/typst/pull/4900#issuecomment-2376919375). 

This feature request proposes to properly add support for this (at least for the `float` type) since there is no fundamental difference between integer and fractional digits for floating point numbers. 

## Some edge cases
- If the input for the number is `inf`, `-inf` or `nan`, the input should be returned -- regardless of the `digits` argument. 
- If `digits` is less than `-308`, i.e., rounding is performed on the 308th integer digit or higher, the result should be always `0.0`. This is because the largest IEEE-754 float is `1.7976931348623157e+308`  and then the digit to round to is always larger than the number of digits in the number. 
- Between `0` and `-307` digits, there should be no overflow issues regarding floating point arithmetic. 
- The question remains what to do if `x>=1.5e+308` and `digits=-308` because  `round(x * pow(10,digits)) / pow(10, digits)` will produce an overflow since the result is not representable by floating point numbers. This is an extreme edge cases of course and returning `inf` or throwing an error would probably be acceptable. 

For reference, a remarkable implementations is the built-in `round()` from CPython. Apparently, it partly does rounding by converting to a string and back to achieve the most precise results which solves some issues that rounding via $round(x·10^d)/10^d$ has. However, a bit overkill here imo. 

I don't know exactly the cases where the old rounding function failed to produce a correct result, so if anyone wants to add on that, feel free to so they can be discussed. 

### Use Case

It is approximately as useful as rounding to fractional digits.

**Comment by PgBiel** [comment]
Thank you for your research! I believe we should be able to add this back, considering the importance in rounding to integer digits.

I've found that there is an additional edge case: taking `f64::MAX` (`1.7976931348623157e+308`) and rounding to any amount of negative digits can produce an overflow (`inf`), since rounding up would then produce a number larger than the maximum.

I'm not sure but I think `inf` should be acceptable if you would otherwise cross the maximum.
