### ISSUE TITLE
(0.12.0-rc1) Quote block behavior change

### ISSUE THREAD

**Issue by fuine** [typst/typst#5158]
### Description

I'm not sure if this is a bug, but there is a difference in quote layout between 0.11 and 0.12 (tested on main `7a96c86`), it looks like in the newer version the quote is composed of multiple different blocks, whereas in the old version it used to be a single block. This also influences the total size of the quote in the example. If the `inset` argument is removed we end up with 2 yellow lines instead of 3 (which are equal in length).

```typst
#set quote(block: true)
#show quote: set block(stroke: (left: 2pt + yellow), inset: 15pt)

#set page(height: 100mm, width: 150mm)

#quote[Mutexes have a reputation for being difficult to use because you have to remember two rules:
  -  You must attempt to *acquire the lock* before using the data.

  -  When you’re done with the data that the mutex guards, you must *unlock the data* so other threads can acquire the lock.
]
```

0.11:
![quote_011](https://github.com/user-attachments/assets/7ef5e944-ab9f-4ff8-8c46-f90aa478ef41)

0.12
![quote_012](https://github.com/user-attachments/assets/b3576719-dc84-455b-b831-584d1125e37f)

### Typst version

- [X] I am using the latest version of Typst

**Comment by HPDell** [comment]
I also noticed this bug. Seems that the settings for `block` now also affect other elements showing by a block.

For example, thinking of the following scripts

```typ
#set block(stroke: (left: 2pt + black), inset: (left: 1em, y: 0.5em))

#lorem(20)

#block[
  + Item 1
  + Item 2
]
```

In `v0.11.0` it results in

![image](https://github.com/user-attachments/assets/3a1b4b47-dbe5-48a2-a4cf-251bd6425e11)


But in `0.12.0-rc1` it results in

![image](https://github.com/user-attachments/assets/d49455ef-8298-488f-9b6b-0e08ebcaba37)

**Comment by xkevio** [comment]
It is probably because block-level elements are now truly represented or wrapped with a `block` whereas before they just had block-like properties.

**Comment by laurmaedje** [comment]
This is working as intended. I'll adjust the changelog to note this more explicitly. But such a show-set rule would be fragile even in 0.11.1 because the quote's body may contain more blocks. What we really need is non-recursive show-set.

**Comment by HPDell** [comment]
> This is working as intended. I'll adjust the changelog to note this more explicitly. But such a show-set rule would be fragile even in 0.11.1 because the quote's body may contain more blocks. What we really need is non-recursive show-set.

@laurmaedje Thanks. But in 0.12.0 how to deal with the example I posted before? Shall I write some show-set rules for lists and other block-level elements, too, one I set the style of blocks?

**Comment by laurmaedje** [comment]
I would suggest not writing too general set rules. A free-standing `set block` is typically a bad idea and even show-set on `block` I would only use for a few properties like `spacing`, `sticky`, or `breakable`. (At least unless we some non-recursive show-set.)

What I would do instead in your example is define a new function that does what you want. Something like this:
```typ
#let line-block = block.with(
  stroke: (left: 2pt + black), 
  inset: (left: 1em, y: 0.5em),
)

#lorem(20)

#line-block[
  + Item 1
  + Item 2
]
```

**Comment by HPDell** [comment]
Make sense. Thank you!
