### ISSUE TITLE
Allow √ as shorthand for sqrt(⋯) in math mode

### ISSUE THREAD

**Issue by user202729** [typst/typst#516]
As explained in the title.

```
$√2+3$ → $sqrt(2)+3$
$√2^3$ → $sqrt(2^3)$
$√(x+y)$ → $sqrt(x+y)$
```

I think it's the only reasonable way to interpret it rather than an off-placed large square root sign as in the current behavior.

**Comment by dvdvgt** [comment]
How would you handle precedence/capturing? Is `√1 + 2` the same as `sqrt(1 + 2)` or rather `sqrt(1) + 2`? If the former is the case, it is opposed to the mathematical precedence of operators, which is a bit weird. If the latter is the case, I don't see much gain compared to just writing `sqrt` instead of `√`, as you have to use parentheses anyway.

**Comment by user202729** [comment]
Mathematica supports the former.

https://tio.run/##y00syUjNTSzJTE78/z@gKDOvJPpRxyxDbaNYrv//AQ

**Comment by szdytom** [comment]
i think using unicode chars in source are generally not a good idea. Why dont i used MS Word if i want a WYSIWYG experience?

**Comment by Enivex** [comment]
> i think using unicode chars in source are generally not a good idea. I still think there’s a chance I’m misunderstanding something, but why dont i use the MS Word if i want a WYSIWYG experience?

It's not WYSIWYG, just _optionally_ allowing markup to be closer to the end result. This can improve readability.

**Comment by user202729** [comment]
> i think using unicode chars in source are generally not a good idea. I still think there’s a chance I’m misunderstanding something, but why dont i use the MS Word if i want a WYSIWYG experience?

People say that all the time, but so far the **only** somewhat-convincing argument I have ever come across is https://tex.stackexchange.com/questions/87257/unicode-in-the-equations-pros-and-cons

> For example if you want a particular arrow style it's probably easier (by eye) to spot (say) \longrightarrow than to recognise the multitude of different Unicode arrows

which doesn't apply in the case of √ here.
