### ISSUE TITLE
`set block(breakable: false)` breaks `pad`

### ISSUE THREAD

**Issue by fdekerme** [typst/typst#5160]
### Description

With this block of code: 

```typ
#show heading.where(level: 1): it => {
  set text(font: "Calibri")

  place(
    top + right,
    dy: -4cm,
    line(
      length: 7.5cm,
      stroke: 2pt + maroon,
      angle: 90deg,
    ),
  )
  pad(
    top: 1cm,
    left: -1cm,
    right: 10pt,
    place(top + right, text(fill: black, hyphenate: false, it.body)),
  )

  if it.numbering != none {
    pad(
      top: 0.5cm,
      10pt,
      place(
        top + right,
        dx: 0cm,
        dy: -3cm,
        text(15pt)[Chapter],
      ),
    )
    place(
      top + right,
      dx: 1.5cm,
      dy: 0cm,
      text(
        50pt,
        weight: "regular",
        counter(heading).display(it.numbering),
      ),
    )
  }

  v(2cm)
}
```
I have this results with 0.11: 
![image](https://github.com/user-attachments/assets/cd490285-16c4-4f96-9224-7c09d355dfb5)

and this results with 0.12:
![image](https://github.com/user-attachments/assets/f74c88f2-41b1-4554-868f-9647799b5ac5)

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This is an interesting case.

Minimized:
```typ
#set block(sticky: true) // toggle this line
#pad(place(top + right, [Hello]))
```

Because all block-level elements are now shown as blocks, the stickyness applied by the heading's show-set rule affects the `pad` and turns it into an unbreakable block (sticky blocks are forcibly unbreakable in the current implementation), which is laid out in "shrink-to-fit" mode rather than expanding to the available width.

**Comment by laurmaedje** [comment]
Actually, this is a problem independent of stickyness. While stickness triggers it, `set block(breakable: false)` generally breaks `pad` because the unbreakable block layout has different semantics.

```typ
#set block(breakable: false) // toggle this line
#block(width: 100%, pad(10pt, align(right)[hello]))
```
