### ISSUE TITLE
Nested box with 1fr width takes 100% and covers other content

### ISSUE THREAD

**Issue by knuesel** [typst/typst#5170]
### Description

Here the red box covers the blue box, and takes 100% width so it causes a new line: 

```typ
#set page(width: 10cm, height: 5cm)

Text
#box(box(width: 1fr, height: 1cm, fill: red))
#box(width: 1fr, height: 1cm, fill: blue)
```

![image](https://github.com/user-attachments/assets/3208a3ad-7602-410f-b181-14276949ce4d)

I expected something more like the following:

```typ
Text
#box(width: 1fr, height: 1cm, fill: red)
#box(width: 1fr, height: 1cm, fill: blue)
```

![image](https://github.com/user-attachments/assets/8b7eeff0-f035-4e54-862c-10319278f7df)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
That's expected. Fr units can only be dealt with if they are the same layer, so to speak.

**Comment by knuesel** [comment]
OK sorry for the noise!

**Comment by laurmaedje** [comment]
No problem. Layout stuff definitely needs better docs.
