### ISSUE TITLE
A problem with counters (and probably states).

### ISSUE THREAD

**Issue by Amirhosein-GPR** [typst/typst#5171]
### Description

Hello guys.
I'm making a template for my University notes but faced a problem.
First I explain how it works and how it looks.

Here i call my custom function called the "double_section" from the main typst file:
```typst
// This is the main file
= جلسه اول
#tool.double_section()[
    #tool.example()[]
][
    #tool.example()[]
]
#tool.example()[]
#tool.example()[]
```

Which is a simple function implemented as follows:

```typst
// This function is in a file named "tool.typ".
#let double_section(content1, content2) = {
    block(below: 1em)[
        #grid(
            columns: (1fr, 1fr),
            gutter: 1em,
            content1,
            content2
        )
    ]
}
```
The output of the 4 times calling the "example()" function are the 4 purple sections which are shown in the following image:

![issue](https://github.com/user-attachments/assets/a6c4f8f6-a6df-479d-93d7-66611247cdf0)

And the example function itself is implemented as follows:
```typst
// This function is also in the "tool.typ" file.
#let example(content, black_and_white: false, pause: false, continuation: false, enable_counter: true) = {
    context {
        let title = "مثال"

        // Some of my notes examples might not need a counter... So I check if it's needed.
        if enable_counter {
            let headings_counter = counter("heading")
            let section_counter = counter("example")

            // Counts the number of level 1 headers before the call of this function.
            let headings_before_here_count = query(selector(heading.where(level: 1)).before(here())).len()

            // If the number of level 1 headers before the call of this function (I mean the "example" function)
            // increases, It means we've entered a new (for example) chapter and the "section_counter"
            // should reset for the new chapter.
            if headings_before_here_count > headings_counter.get().first() {
                headings_counter.update(headings_before_here_count)
                section_counter.update(0)
            }

            section_counter.step()
            
            // All of this work was to make my titles have numbering... which is appended to the "title" variable
            title += " " + text(stylistic-set: 2)[#headings_before_here_count.#context section_counter.display()]
        }

        // Might not be important... (It makes the example boxes)       
        section_template(title: title, content, black_and_white: black_and_white, icon_paths: ("../../icons/circle-dot.svg",), icon_color: purple_color, pause: pause, continuation: continuation)
    }
}
```

At first glance, It looks like everything is OK, but the problem is shown in the following image:

![issue2](https://github.com/user-attachments/assets/781c2ddf-b7d8-4a0c-8bf6-7bd59ef0e670)

As you can see, the numbering of the first 2 example sections are incorrect. They should be shown like the black boxes above them but for some reason they don't.

This problem doesn't occur when the example sections aren't in the same line (The last 2 sections are OK as you can see).

I think the reason for this problem might be because of how the Typst rendering system works. It actually renders from left to right even if the text direction is set to rtl. And it effects the evaluation of counters which I used for numberings... ( I might be totally wrong and it might not be a bug. Sorry if the problem is from misunderstanding )

I will be really grateful if anybody can help me how to solve this problem :D

EDIT: I made a simpler version you can test in the following URL:

### Reproduction URL

https://typst.app/project/r-sxtu-nDbVUfWToCzcEwi

### Operating system

Linux

### Typst version

- [x] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Superseded by https://github.com/typst/typst/issues/5178
