### ISSUE TITLE
[Outline] Typst v0.12.0-rc1 outline has a strange indentation for non-English headings

### ISSUE THREAD

**Issue by kands-code** [typst/typst#5176]
### Description

Typst v0.12.0-rc1 does solve many issues, such as #5166 which I raised yesterday, but it also seems to introduce new ones such as outline.

Here's a rendering of typst 0.11.1 that looks very good:

![typst 0.11.1](https://github.com/user-attachments/assets/e407777b-c47f-4606-adf3-132a117e3084)

But for typst 0.12.0-rc1, the results are a bit different:

![typst 0.12.0-rc1](https://github.com/user-attachments/assets/d417e8f9-6ead-4c59-b776-59e0fff73fed)

> Those two vertical lines were drawn by me to make the issue more obvious.

The minimum reproducible code is as follows:

```typst
#outline()

= 测试

= 很长的测试标题

= 测试标题

= Test

= VeryLongTestTitle

= TestTitle
```

> I haven't tested other languages yet, I've only tested Chinese and English.

### Operating system

Linux, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This appears to be a bad interaction of `cjk-latin-spacing` and https://github.com/typst/typst/pull/4491.
