### ISSUE TITLE
Measure returns zero height for inline math when top-edge is set to "bounds"

### ISSUE THREAD

**Issue by johannes-wolf** [typst/typst#5180]
### Description

The following returns a height of `0pt`:
```typst
#context repr(measure(text(top-edge: "bounds", $x$)))
```

Without `top-edge: "bounds"`, a height of `7.51pt` gets returned.

I would expect `top-edge: "bounds"` to not return a height of `0pt`. In cetz we need a reliable way to measure the bounding box of content, including inline math. Internally cetz calls `measure` with `top-edge:` and `bottom-edge:` set to `"bounds"` to determine the bounding box of an object.

If I wrap any content in `math.equation(block: true, ...)` for measuring, I have to set `numbering:` to none, which prevents equation numbering for all equations passed to cetz' `content`, which is unwanted.

Reproducible and tested with:
- Typst 0.11.1
- Typst 0.12.0-rc1

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Opened https://github.com/typst/typst/pull/5186/files
