### ISSUE TITLE
Placing a figure at the `bottom` moves it below footnotes.

### ISSUE THREAD

**Issue by JKRhb** [typst/typst#5184]
### Description

In the 0.12-rc version, using `bottom` for the `placement` of figures moves them below the footnotes on a page. This was not the case for Typst 0.11.

### Reproduction example:

```typ
This is a test. #footnote("hi")

#figure(
  placement: bottom,
  table(
    columns: (1fr, 1fr),
    [Foo],
    [Bar]
  )
)
```

<img width="752" alt="image" src="https://github.com/user-attachments/assets/230b11ab-884d-49dd-ba08-edb540d1aa8d">

### Reproduction URL

https://typst.app/project/rqaHl3IlDcmu98FvKuX8oV

### Operating system

Web app

### Typst version

- [ ] I am using the latest version of Typst

**Comment by Dherse** [comment]
This is not a bug per-se rather the default behavior, and it is being worked on by @laurmaedje

**Comment by laurmaedje** [comment]
This was just [discussed on Discord](https://discord.com/channels/1054443721975922748/1088371867913572452/1294216802875998218). Copying what I wrote there:

> Regarding the footnote/float order discussion: In 0.12.0-rc1, footnotes are always above floats (unlike in 0.11.1). This mirrors what LaTeX does by default.
>
> What I could do instead is move the floats above the footnotes, but basically by scope. So a single-column floating figure would be above footnotes, but in a two-column layout, a two-column floating figure is below single-column footnotes (footnotes are always single column atm). 
>
> I'm honestly not sure what's more desirable. While my first instinct would be that footnotes should be at the very bottom, the arguments for the other order given on [StackExchange](https://tex.stackexchange.com/questions/32951/tables-below-footnotes-is-this-a-good-output-routine-algorithm-or-a-bug) make sense to me as well. It's also consistent between single- and two-column layouts to order footnotes above floats.

**Comment by JKRhb** [comment]
Thank you for providing the context here, @laurmaedje!

> What I could do instead is move the floats above the footnotes, but basically by scope. So a single-column floating figure would be above footnotes, but in a two-column layout, a two-column floating figure is below single-column footnotes (footnotes are always single column atm).

That sounds like a good solution to me :) That behavior would at least correspond with the expectations I have regarding float/footnote placement. (Although, I can also understand the arguments for a consistent behavior across column layouts.)
