### ISSUE TITLE
Can't escape/cancel string show rules anymore in 0.12.0-rc1

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#5199]
### Description

Found a regression:t

```typ
#[
  #show "a": "b"
  a \a
]

#[
  #show "aa": "b"
  aa \aa
]

#[
  #show "aaa": "b"
  aaa \aaa
]
```

v0.12.0-rc1:

![image](https://github.com/user-attachments/assets/f604ffed-6e05-469c-bb06-4a0098f5419c)

previous versions:

![image](https://github.com/user-attachments/assets/a45471ce-5e4a-4454-a5e7-fee34d00c308)

Additionally, since we are on the topic of escaping show rulse, why escaping a single-symbol string show rule doesn't work in any version? IMO, it should work for any length of the string. So, you can also consider this a (long-standing) sub-bug.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
They can't be escaped anymore precisely because the bug #86 was fixed. The fact that they wouldn't match previously was the bug.
