### ISSUE TITLE
Add Support for Reading JSON Lines File

### ISSUE THREAD

**Issue by prokie** [typst/typst#5212]
### Description

The same way I parse `json` I would like to be able to parse `jsonl`. I understand that this might be quite niche, but I think it would be useful. 

### Use Case

We have log files at work that are `.jsonl`.  Those files are parsed and output to several different usecases. It would be cool to be able to generate pdfs from aswell using typst.

**Comment by laurmaedje** [comment]
This seems to be like something that should be handled by a [package](https://typst.app/universe/).

**Comment by prokie** [comment]
I guess you are right. Now that I think about it I can probably just use the [read](https://typst.app/docs/reference/data-loading/read/) function and split the string on each line and then parse it to json using `json.decode`.

**Comment by laurmaedje** [comment]
Sounds good, then I'll close this.
