### ISSUE TITLE
Write a short and descriptive title!

### ISSUE THREAD

**Issue by theauditor** [typst/typst#5216]
### Description

**0.12 (pre-release) R2** 

``` <git:(main*)> ~/typst/typst-x86_64-unknown-linux-musl/typst compile  main.typ
warning: `locate` with callback function is deprecated
   ┌─ @preview/chic-hdr:0.4.0/chic-hdr.typ:61:30
   │  
61 │       page-options.at(option) = locate(loc => {
   │ ╭───────────────────────────────^
62 │ │       // Convert 'skip' negative indexes to positive indexes
63 │ │       let positive-skip = skip.map((index) => {
64 │ │         if index >= 0{
   · │
87 │ │       }
88 │ │     })
   │ ╰──────^
   │  
   = hint: use a `context` expression instead
```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by tingerrr** [comment]
There's a hint at the bottom, the package `chic-hdr:0.4.0` still uses `locate` which is going to be deprecated in favor of `context` in Typst 0.12, this will not go away until `chic-hdr` updates it's code and you in turn update `chic-hdr`. It's unlikely that any package will update to fix 0.12 warnings before 0.12 is released, you can simply ignore this for now.

Please don't open issues with nothing but a deprecation warning. This issue has no title, no explanation of expected vs actual behavior, or any supplementary examples of how to reproduce it.
