### ISSUE TITLE
Maybe first deprecate `calc.nan` before removing it immediately

### ISSUE THREAD

**Issue by Mc-Zen** [typst/typst#5217]
In Typst 0.12, `calc.nan` is moved to `float.nan` (which makes total sense). However, this breaks projects using the old version. I'm all for a breaking change but maybe `calc.nan` could be deprecated for just one version or so for two reasons:

- It makes comparing 0.11 and 0.12 hard (in my case, I need to `calc.nan` to `float.nan` in almost a dozens of places and across different files. The way it is now, I can't just switch without replacing all these occurrences each time.  
- There may be packages using `nan` internally which would break immediately.

**Comment by laurmaedje** [comment]
We did it this way because there is no infrastructure for deprecating constants at the moment. We checked typst/packages and found no occurance of calc.nan, so we figured that it wasn't really used in the wild. But I guess we can add it back in if that's untrue.

**Comment by Mc-Zen** [comment]
Okay, I understand. 

In my case, it is a package-in-progress ..

**Comment by Mc-Zen** [comment]
But not too wild, I just wanted to compare performance and make use of the transparent png export of 0.12
