### ISSUE TITLE
How to add something at the end of all `[content]`?

### ISSUE THREAD

**Issue by Fusyong** [typst/typst#522]
**My question is:** How can I locate all the `[content]`s and insert  `[#h(1fr)]` at the end of them.

Specifically, it goes like this:

In order for the `justify` option of the `par` function to be applied to Chinese (or cjk) text, I need to do two things:

1. insert a very small `fraction` (`0fr` is great, but Typst cannot accept it; and in LuaTeX it is like `glue(width:0, stretch:0.5quad, shrink:0)`) between all Chinese characters and Chinese punctuations (some exceptions will not be discussed here for now). There is no problem with this.
2. Insert a `fraction` at the end of an unfilled lines. Here's the problem, I don't have a way to find the end of unfilled lines all at once (i.e. the end of all `[content]`), so I have to locate `parbreak`, `linebreak`, `enum.children.body` and `list.children.body`, and so on, and insert the `fraction` I need. Doing so can easily lead to omissions and errors, as you will see below. So I think this is not the ideal approach.

[Here](https://typst.app/project/rF1w0Zcc-LslnU7IBU-ORD) is my Typst documentation and code:

```typst
#set page(height: auto, width: 8.9cm)
#set text(
  font: "Noto Serif CJK SC",
  size: 11.5pt
)


#show : (rest) => {
     set par(justify: true)
     
     // 汉字及其标点（不完善）后加无限拉伸胶 | A collection of Chinese characters and punctuations (not yet fully included), each followed by 0.00001 fraction
     let chinese_set = regex("[\u4E00-\u9FA5、，。；：“”！？‘’]")
     show chinese_set: c => c + [#h(0.00001fr)] 

     // 在不满的行后加胶 | Add 1 fraction after unfilled lines
     let end_fr = [#h(1fr)]
     show parbreak : b => end_fr + b
     show linebreak : b => end_fr + b
     show enum : it => {
       for i in it.children {
         i.body + end_fr
       }
     }
     show list : it => {
       for i in it.children {
         i.body + end_fr
       }
     }

     rest
}

#table(
  columns: (1fr,1fr),
  [#set par(justify: true)
  你来了！你来了！你来了！你来了！
  
  你来了！你来了！你来了！你来了！
  
  // 末尾必须有空行 | There must be a breakline at the end
  ],
  [#set par(justify: true)
   #lorem(10)],
)

+  你来了！你来了！你来了！你来了！
+  你来了！你来了！你来了！你来了！
-  你来了！你来了！你来了！你来了！
-  你来了！你来了！你来了！你来了！

#lorem(20)

排版元素可以旋转、位移，\
可以手动堆叠成行、成列。\
元素间可以放置正值或负值的空白。
这么说，可以做标点压缩、竖排、双行夹注等功能。

但目前似乎没有操作底层数据的接口，比如获取字体和字模信息，操作抽象语法树、模块树、框架树。

另外，它的分行组段的算法似乎比较简陋，不知道后面会不会移植 Knuth-Plass 的算法。
目前汉字间没有像 LuaTeX 那样加入零宽度的胶，所以行校正时可拉伸点较少（只能用标点前后的空格），拉得太狠，很难看。

// 末尾必须有空行 | There must be a breakline at the end
```

Before and after effect:

![image](https://user-images.githubusercontent.com/15652226/229331632-185cc3a4-4175-4ebd-a7c5-ce722b77ebfa.png)

![image](https://user-images.githubusercontent.com/15652226/229332568-560b4626-f38a-470a-a39d-c42a94862f0b.png)

Of course, in the long run, maybe this should be implemented in the Rust source code, which I'll explore later.

**Comment by dlxdlxdlx** [comment]
You can try neovim/vim,hhhh

**Comment by Fusyong** [comment]
The latest version of Typst has been able to justify CJK par, 
although I still can not locate all the [content]s and insert [#h(1fr)] at the end of them.
