### ISSUE TITLE
U+2009 thin spaces in source text do not show up as thin spaces in PDF

### ISSUE THREAD

**Issue by fruchti** [typst/typst#524]
I’d like to include U+2009 unicode thin spaces in the typst source and have them show up as thin spaces in the document. However, they neither show up correctly in the PDF, nor is matching and replacing them with `#show` possible (while regular spaces can be matched).

Test case:

```typ
#set page(width: 7cm, height: auto)

= Unicode in source

| | U+0020 regular space \
| | U+2009 thin space \
| | U+202F thin protected space \
| | U+00A0 protected space

= \\u escape

|\u{0020}| U+0020 regular space \
|\u{2009}| U+2009 thin space \
|\u{202f}| U+202F thin protected space \
|\u{00a0}| U+00A0 protected space

= \#show matching

#show " ": [ matched U+2009 ] // does not match
#show sym.space.thin: [ matched sym.space.thin ] // does not match
#show math.space.thin: [ matched math.space.thin ] // does not match
// #show " ": [ matched_space ] // matches, but not the thin space
#show "Ω": [ matched omega ] // matches

| | U+2009 thin space \
Ω
```

![thinsp](https://user-images.githubusercontent.com/11243448/229345344-b138be2c-34ac-4e90-b7bd-4ab2e2c96da0.png)

**Comment by HROMANO** [comment]
I also use thin spaces and non breaking spaces directly in my code (they are mapped on my keyboard).

But typst seems to replace them with normal spaces. For example, non breaking spaces are broken at the end of lines.

**Comment by laurmaedje** [comment]
My thoughts: https://github.com/typst/typst/issues/3240#issuecomment-1911762308
