### ISSUE TITLE
Noto emojis are not well-centered

### ISSUE THREAD

**Issue by TimotheAlbouy** [typst/typst#5242]
### Description

The Noto emojis are a bit offset to the bottom-left compared to other emoji fonts such as Twitter's or Apple's.

```typst
#set text(font: "Twitter Color Emoji")
#box(stroke: 1pt + red, "😇")

#set text(font: "Noto Color Emoji")
#box(stroke: 1pt + red, "😇")
```

![image](https://github.com/user-attachments/assets/179a58be-d708-4ef2-ab89-47c0e5be993b)

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by Andrew15-5** [comment]
The font files can be downloaded here:

https://github.com/13rac1/twemoji-color-font/releases/download/v15.1.0/TwitterColorEmoji-SVGinOT-15.1.0.zip

https://github.com/googlefonts/noto-emoji/archive/refs/tags/v2.047.tar.gz

```typ
#let test = box(stroke: red, [l#emoji.face.cool;l])
#text(font: "Twitter Color Emoji", test)
#text(font: "Noto Color Emoji", test)
```

![image](https://github.com/user-attachments/assets/61dc7597-edae-471b-96b2-91f01d36f7ff)

It's not only not centered, but it also adds some additional space at the top (and to the sides). It's also smaller, but that can be normal.

**Comment by Enivex** [comment]
The question is whether this is an issue with the font, or typst's handling of it

**Comment by fuchsiebabe** [comment]
The issue is definitely with Noto Color Emoji itself. I'm seeing the same behaviour in Godot, no matter which emoji I pick. When compared with emoji from different typefaces (like Segoe UI Emoji for example) it's definitely off-set in this way. This is an issue with Noto Color Emoji itself.

**Comment by laurmaedje** [comment]
Thanks, that's good to know!

**Comment by Enivex** [comment]
Alternatively Godot has the same font handling issue as typst

**Comment by fuchsiebabe** [comment]
Anything's possible, though given that Noto Color Emoji is the only typeface which has this issue in testing a range of different emoji typefaces, I'm naturally more suspicious of Noto than of either Godot or typst. Noto Color Emoji won't display at all in LibreOffice Writer, yet other typeface emoji work just fine there.

**Comment by fuchsiebabe** [comment]
Yeah, annoyingly. It'd be nice if this weren't the case. (LibreOffice 24.8, OpenJDK)
![image](https://github.com/user-attachments/assets/be8979c2-4177-4e0f-b69a-a088207c3fe3)

I've been poking around a bit on the Noto Color Emoji git and I've found there's [another version](https://github.com/googlefonts/noto-emoji/raw/main/fonts/NotoColorEmoji.ttf) which is Unicode compliant and properly aligned. It's different to the one you get directly from [Google](https://fonts.google.com/noto/specimen/Noto+Color+Emoji)
