### ISSUE TITLE
Weird paragraph placement with vs. without first-line-indent

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#5243]
### Description

<details><summary>code</summary>

```typ
#show: doc => {
  let indent = 1.25cm
  let font-size = 14pt
  let leading = 1.5em
  let leading = leading - 0.75em // "Close enough normalization"

  set page(paper: "a4", margin: (left: 3cm, right: 1cm, y: 2cm))
  set par(spacing: leading)
  set par(justify: true, leading: leading, first-line-indent: indent)

  set text(
    font: "Libertinus Serif",
    size: font-size,
    lang: "ru",
    hyphenate: false,
  )

  show "〜": h(indent)
  show heading: it => text(font-size, align(center, it))

  doc
}

#v(640.92pt)

== Исходные данные для планирования
=== Общее описание информационной системы
〜Назначение: ИС "Телефонный справочник" предназначена для хранения и поиска
контактной информации пользователей, включая имя, фамилию, номер телефона, адрес
электронной почты и дополнительные заметки.
```

</details>

![image](https://github.com/user-attachments/assets/41fb090e-6c13-452d-8597-faf0a7815737)

Removing the `〜` gives this:

<details><summary>code</summary>

```typ
#show: doc => {
  let indent = 1.25cm
  let font-size = 14pt
  let leading = 1.5em
  let leading = leading - 0.75em // "Close enough normalization"

  set page(paper: "a4", margin: (left: 3cm, right: 1cm, y: 2cm))
  set par(spacing: leading)
  set par(justify: true, leading: leading, first-line-indent: indent)

  set text(
    font: "Libertinus Serif",
    size: font-size,
    lang: "ru",
    hyphenate: false,
  )

  show heading: it => text(font-size, align(center, it))

  doc
}

#v(640.92pt)

== Исходные данные для планирования
=== Общее описание информационной системы
Назначение: ИС "Телефонный справочник" предназначена для хранения и поиска
контактной информации пользователей, включая имя, фамилию, номер телефона, адрес
электронной почты и дополнительные заметки.
```

</details>

![image](https://github.com/user-attachments/assets/b2bfbe9d-30b4-43fc-b0ba-f7174391c0af)

At first, I thought that it's strange that a paragraph jumps depending on whether the indent is present or not, but now I realized that the orphan heading/paragraph is back despite being fully fixed, IIUC.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by EpicEricEE** [comment]
The fact that it changes by removing the `〜` is because of widow prevention of paragraphs. Without the indent, the paragraph has 3 lines, where the last one would end up separately (which is prevented by high `widow` cost). With the indent, the paragraph ends up with 4 lines, so it can be split into 2+2.

The "real" cause seems to be that there is only vertical spacing before the (sticky) headings. As soon as there is any other content before or after the `v` element (e.g. a non-breaking space, an empty box, etc.), the stickiness is working again.

**MRE:**
```typ
#set page(height: 7cm)

// ~
#v(2cm)
// ~

#block(fill: red, height: 2cm, width: 100%, sticky: true)
#block(fill: red, height: 2cm, width: 100%, sticky: true)
```

**Comment by Andrew15-5** [comment]
> The "real" cause seems to be that there is only vertical spacing before the (sticky) headings. As soon as there is any other content before or after the `v` element (e.g. a non-breaking space, an empty box, etc.), the stickiness is working again.

This is because I removed all the content before the juicy part. There is a ton of text/paragraphs/lists/headings before the bug part. I had to make the MRE somehow.

**Comment by EpicEricEE** [comment]
I can't seem to reproduce this when there is any real content, i.e. content whose frame contains at least one [frame item](https://github.com/typst/typst/blob/838dabc84cfea04c135aaff2f89ec4b2b32926e4/crates/typst/src/layout/frame.rs#L533) (e.g. a shape, text, tag, etc.).

For example, replacing the `v(...)` with a `block(height: ...)` doesn't change anything as the frame doesn't contain anything, but as soon as a fill is added (which creates a shape), or the block body contains (only) a tag (e.g. metadata or empty context expression), it works again.

This seems to match what is described by the `Distributor::stickable` field, which is only [set to true](https://github.com/typst/typst/blob/838dabc84cfea04c135aaff2f89ec4b2b32926e4/crates/typst/src/layout/flow/distribute.rs#L320) if a non-empty frame is encountered.
https://github.com/typst/typst/blob/838dabc84cfea04c135aaff2f89ec4b2b32926e4/crates/typst/src/layout/flow/distribute.rs#L44-L46

**Comment by Andrew15-5** [comment]
I'm not sure what to make of this, but here is a bit more context:

```typ
Задачи проекта:
+ Анализ требований: Определение функциональных и нефункциональных требований к
  системе.
+ Проектирование архитектуры: Создание общей архитектуры ИС и выбор технологий для
  реализации.
+ Разработка интерфейса: Проектирование удобного и интуитивно понятного
  пользовательского интерфейса.
+ Разработка функциональности: Реализация основных функций поиска, добавления,
  редактирования и удаления контактов.
+ Тестирование: Проверка системы на соответствие требованиям и отсутствие ошибок.
+ Внедрение: Запуск системы в эксплуатацию и обучение пользователей.
+ Поддержка и обновление: Обеспечение технической поддержки и регулярных
  обновлений системы.

== Исходные данные для планирования
=== Общее описание информационной системы
〜Назначение: ИС "Телефонный справочник" предназначена для хранения и поиска
контактной информации пользователей, включая имя, фамилию, номер телефона, адрес
электронной почты и дополнительные заметки.
```

![image](https://github.com/user-attachments/assets/27f1586b-ccfd-48b5-b769-8922732d888d)

---

You know what? I think I mixed a bit too much. The initial issue of weird paragraph placement of 3 lines vs. 2 + 2 lines is still there. But I guess the heading orphan stuff is something I only noticed in the MRE, because I cannot reproduce this in my document.

**Comment by Raphael-CV** [comment]
Probably link to this problem, the presence or abscence of `first-line-indent` parameter affects vertical spacing. See
```typst
#set page(paper: "a7", columns: 2, flipped: true)
#set par(first-line-indent: 0pt)
#lorem(10)

#box(lorem(10), width: 100%)

#lorem(10)

#colbreak()
#set par(first-line-indent: 1em)
#lorem(10)

#box(lorem(10), width: 100%)

#lorem(10)
```
![image](https://github.com/user-attachments/assets/5f487a4a-0706-4f3f-8e16-d77ab9280e64)

**Comment by Enivex** [comment]
> Probably link to this problem, the presence or abscence of `first-line-indent` parameter affects vertical spacing. See
> ```typst
> #set page(paper: "a7", columns: 2, flipped: true)
> #set par(first-line-indent: 0pt)
> #lorem(10)
> 
> #box(lorem(10), width: 100%)
> 
> #lorem(10)
> 
> #colbreak()
> #set par(first-line-indent: 1em)
> #lorem(10)
> 
> #box(lorem(10), width: 100%)
> 
> #lorem(10)
> ```
> ![image](https://github.com/user-attachments/assets/5f487a4a-0706-4f3f-8e16-d77ab9280e64)
> 
> 

That's not a bug. In this case the issue is that with first line indent on, a box with 100% width can never end up on the first line of a paragraph (it would overflow into the margin). Therefore it's pushed to the second line, and you get an extra empty line.

**Comment by laurmaedje** [comment]
@Andrew15-5 I still don't really understand what the bug is supposed to be, can you show a small example with what you expected and what you got?

> The initial issue of weird paragraph placement of 3 lines vs. 2 + 2 lines is still there.

Without getting the context, this might relevant: For 3 lines, they must all stay together to prevent widows/orphans. For 2+2 lines, it can insert a break.

**Comment by Andrew15-5** [comment]
I think it's not a bug, since it's a known behavior. But the amount of content moved from one page to another was...concerning. 4 lines just from a single indent.

<details><summary>code</summary>

```typ
#let indent = 1.25cm
#let font-size = 14pt
#let leading = 1.5em
#let leading = leading - 0.75em // "Close enough normalization"

#show: doc => {
  set page(
    paper: "a4",
    margin: (left: 3cm, right: 1cm, y: 2cm),
  )
  set par(spacing: leading)
  set par(justify: true, leading: leading, first-line-indent: indent)
  set text(
    font: "Libertinus Serif",
    size: font-size,
    lang: "ru",
    hyphenate: false,
  )
  set heading(numbering: none)
  show "〜": h(indent)
  show heading: it => text(font-size, align(center, it))
  doc
}

#v(349pt)

Задачи проекта:
+ Анализ требований: Определение функциональных и нефункциональных требований к
  системе.
+ Проектирование архитектуры: Создание общей архитектуры ИС и выбор технологий для
  реализации.
+ Разработка интерфейса: Проектирование удобного и интуитивно понятного
  пользовательского интерфейса.
+ Разработка функциональности: Реализация основных функций поиска, добавления,
  редактирования и удаления контактов.
+ Тестирование: Проверка системы на соответствие требованиям и отсутствие ошибок.
+ Внедрение: Запуск системы в эксплуатацию и обучение пользователей.
+ Поддержка и обновление: Обеспечение технической поддержки и регулярных
  обновлений системы.

== Исходные данные для планирования

=== Общее описание информационной системы
〜Назначение: ИС «Телефонный справочник» предназначена для хранения и поиска
контактной информации пользователей, включая имя, фамилию, номер телефона, адрес
электронной почты и дополнительные заметки.
```

</details>

<details><summary>present</summary>

![image](https://github.com/user-attachments/assets/859dd512-ca5e-4cc0-9554-5c34496b45b4)

</details>

<details><summary>gone</summary>

![image](https://github.com/user-attachments/assets/d9c2c1d6-9fcc-4424-af37-ec30e516572e)

</details>

**Comment by PgBiel** [comment]
> You know what? I think I mixed a bit too much. The initial issue of weird paragraph placement of 3 lines vs. 2 + 2 lines is still there. But I guess the heading orphan stuff is something I only noticed in the MRE, because I cannot reproduce this in my document.

The heading bug is actually due to the same cause as #5296 (the `#v(...)` is currently ignored when considering that a block is "at the top"). My PR #5581 will also fix your MRE.
