### ISSUE TITLE
Fontname of a Type 3 font looks wrong

### ISSUE THREAD

**Issue by TS53** [typst/typst#5247]
### Description

For all other fonts, we get the expected font names of the embedded font, but for a Type 3 font, the prefix hash is included.
I tested this with SumatraPDF and Adobe Reader and both show the same name.
Maybe the reason is that this `Font` object is the only one having the `Name` key set: `/Name /YXDKRS+SegoeUIEmoji`.

```typst
Here comes the emoji 😂, which is from a different font and embedded as Type 3 font.
```

With older versions, emojis where embedded as a normal non-colored font and thus there was no need for Type 3 fonts.

Related: https://github.com/typst/typst/pull/5070

![fontname](https://github.com/user-attachments/assets/45baa007-95fd-4bd3-aac9-921440a907f2)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by TS53** [comment]
Here is an additional code to see how pdflatex writes the pdf object for Type 3:

```latex
\pdfobjcompresslevel=0
\documentclass[a4paper]{article}

\usepackage{wesa}
\usepackage[T1]{fontenc}

\begin{document}
\wesa
Example text which is in Type 3 format.
\end{document}
```

**Comment by khaledhosny** [comment]
You can try LibreOffice, it uses Type 3 for color fonts.

**Comment by TS53** [comment]
Yes, you're right! I tried it, here is the result:

![LibreOffice](https://github.com/user-attachments/assets/876cf9a7-443f-4c60-8990-423d14199a79)

They are also using the expected Name without prefix hash.
It seems all three LuaTeX, LibreOffice and Typst embed the color emoji fonts differently, we can see this from the three different Adobe Reader images. My first impression is that the LuaTeX version is the best, but I have no further information here about the details and I couldn't find more information.

**Comment by khaledhosny** [comment]
LuaTeX converts bitmap color glyphs into graphics and inserts them this way instead of font glyphs.

LibreOffice uses Type 3 fonts, which I think the same as Typst.

I don’t remember the exact details, but when I wrote the LibreOffice code I had issues with Type 3 font names and I had to jump through some hoops to make it work (some libraries, like Poppler, [wouldn’t even show Type 3 font names at all](https://gitlab.freedesktop.org/poppler/poppler/-/merge_requests/1381)). May be you can diff the two PDFs to see what is the difference.

**Comment by khaledhosny** [comment]
I think this is the relevant difference:
```diff
   /Type /Font
   /Subtype /Type3
-  /Name /OHPKRD+TwitterColorEmojiSVGinOT
+  /Name /AppleColorEmoji
```
Typst prefixes the Type 3 font name with the subset id, but LibreOffice does not.

**Comment by TS53** [comment]
Yes. LibreOffice also does it, but only in the Font Descriptor:
```
12 0 obj
<</Type/FontDescriptor/FontName/BAAAAA+SegoeUIEmoji
...
>>
endobj
```
and then in the Font:
```
14 0 obj
<</Type/Font/Subtype/Type3/Name/SegoeUIEmoji
...
>>
endobj
```

**Comment by khaledhosny** [comment]
> Yes. LibreOffice also does it, but only in the Font Descriptor:

IIRC, I did this intentionally because I found out (like you did here) that the subset ID is not expected here, or at least apps I tested didn’t string it from /Font/Name, Unlike FontDescriptor/FontName.

> About LuaTeX I really can't find anything besides [this](https://tug.org/tug2021/assets/pdf/Marcel-Kruger-slides.pdf) which suggests Type 3. But they seem to use some method that only works with HarfBuzz.

I wrote the initial code in luaotfload that handles colors fonts when using HarfBuzz and it doesn’t use Type 3 fonts. I think they were probably planning to switch it to use Type 3 fonts, but does not look like this ever happened, the PDF generated by LuaTeX today still uses images directly and it has no Type 3 fonts.

**Comment by TS53** [comment]
Thanks for the information, that makes it clear! I think, removing the prefix from the `/Name` would solve it then.

**Comment by LaurenzV** [comment]
I think this is intentional, see https://github.com/typst/typst/pull/5070

**Comment by laurmaedje** [comment]
Not sure whether it was intentional that it contains the prefix. Previously, it was not written at all.

**Comment by LaurenzV** [comment]
Was it not? At least from the diff, it looks like the subset tag was written before. The only thing that changed is that the `/Name` entry contains the same.

**Comment by laurmaedje** [comment]
What I meant was that the subset tag was written for the FontDescriptor, but nothing was written for the Type3Font itself. Now both get the subset tag. I think what the PR wanted to achieve is to write a Type3Font /Name at all, not the specifics of whether it contains a subset tag or not.

**Comment by LaurenzV** [comment]
From my understanding of https://github.com/typst/typst/issues/5067, the point was that the name in `FontDescriptor` and in the font itself have to match, but maybe I got it wrong.

**Comment by laurmaedje** [comment]
But this doesn't talk about the subset tag, so isn't there still the option of omitting the subset tag for both? Not sure whether that would be any more correct, just talking about the possibility. Anyway, I don't really have a clue of what's correct here.

**Comment by LaurenzV** [comment]
Yeah, same. 😄

**Comment by khaledhosny** [comment]
I don’t think anyone knows what is “correct” here either. We have PDF readers (both from Adobe and from others) that don’t strip the subset tag from `/Font/Name` but strip it from `/FontDescriptor/FontName`, and then we have the validation tool in #5067 that expects `/Font/Name` and `/FontDescriptor/FontName` to be identical (including the subset tag, I just checked it with LibreOffice-generated PDF and it complained about the mismatch).

Either the PDF readers are wrong or the validation are wrong, though if you ask anyone who worked with PDF they will tell you whatever Adobe tools does is the actual standard, not whatever is written in the spec (and the spec is not saying much here, even).

**Comment by laurmaedje** [comment]
I think passing this validator is more important than the aesthetics of the font name in the settings panel, so maybe we can just close this?

Removing the subset tag from both seems ill-advised.

**Comment by LaurenzV** [comment]
Yes, I agree.
