### ISSUE TITLE
Hyphenation regression in 0.12.0

### ISSUE THREAD

**Issue by dezifit** [typst/typst#5249]
### Description

Example code:
```
#set par(justify: true)
#set text(lang:"de",hyphenate:true)
#block(width:15.1cm)[*Typst version:* #sys.version \ \
die von mir bei den Werbekosten geltend gemachte Abschreibung für den im
vergangenen Jahr angeschafften Fotokopierer wurde von Ihnen nicht berücksichtigt.
Der Fotokopierer steht in meinem Büro und wird von mir ausschließlich zu
beruflichen Zwecken verwendet.]
```
![Result of version 0.11.1](https://github.com/user-attachments/assets/a9b34806-121c-4e6b-bd5c-e174fdf2139f)

![Result of version 0.12.0](https://github.com/user-attachments/assets/f1f7e00d-11f6-4ea8-b225-4ec595f085ee)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by frozolotl** [comment]
This is to be expected due to the adjustment of hyphenation costs[^1]. I honestly like the new result better here. Hyphenation do often reduce readability and I think it does in this case.

[^1]: https://typst.app/docs/changelog/0.12.0/#text

**Comment by Enivex** [comment]
This is an intentional change. If you reduce the hyphenation cost you should be able to get the old hyphenation back 

(I have not tried)

**Comment by Enivex** [comment]
> This is to be expected due to the adjustment of hyphenation costs[^1]. I honestly like the new result better here. Hyphenation does often reduce readability and I think it does in this case.
> 
> [^1]: https://typst.app/docs/changelog/0.12.0/#text

I'm mixed about it. In this case I'd consider the word spacing to be slightly too extreme.

Of course the ideal solution is font expansion, but typst does not support that yet.
