### ISSUE TITLE
Line numbering with `page` scope fails if the page break results from previous content

### ISSUE THREAD

**Issue by woerndl** [typst/typst#5252]
### Description

If you set the line numbering later in the document and the page break results from content before the `#set`, the line numbering is not correctly reset when flowing onto the next page.

```typ
#set page(height: 100mm, width: 200mm, margin: 15mm)
#lorem(100)

#set par.line(
  numbering: "1",
  numbering-scope: "page",
)

#lorem(200)
```

Results in

<img width="597" alt="numbering" src="https://github.com/user-attachments/assets/67b97f7a-fe9a-42e3-81a6-45529f2e198c">

### Reproduction URL

https://typst.app/project/ptwa1v6askfg7bvPktADwJ

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
This is documented here: https://typst.app/docs/reference/model/par/#definitions-line-numbering-scope

> Note: The line numbering scope must be uniform across each page run (a page run is a sequence of pages without an explicit pagebreak in between). **For this reason, set rules for it should be defined before any page content, typically at the very start of the document.**

Ideally there could be some diagnostic to identify this pattern, but it could always be legitimate to change the line number scope setting midway (if you're about to pagebreak), so I'm not sure it'd be worth it.

**Comment by woerndl** [comment]
Ah, sorry, I was actually looking for something like that but missed the note section.

For anyone coming across this, this works as excpected:
```typ
#set par.line(
  numbering-scope: "page",
)

#set page(height: 100mm, width: 200mm, margin: 15mm)

#set par.line(numbering: none)
#lorem(50)

#set par.line(numbering: "1")
#lorem(200)
```
