### ISSUE TITLE
Panic with consecutive horizontal spacings in inline equation

### ISSUE THREAD

**Issue by EpicEricEE** [typst/typst#5253]
### Description

When an inline equation contains multiple horizontal spacings after a relation or binary operator, and the equation is followed by any other content in the same paragraph, the compiler panics with
```
Error: panicked at crates/typst/src/layout/inline/shaping.rs:605:45:
byte index 10 is not a char boundary; it is inside '\u{2069}' (bytes 8..11) of `⁦￼  ⁩ a`
```

**MRE:** `$= thin thin$ a`

_(U+2069 is the "Pop Directional Isolate" character)_

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
https://github.com/typst/typst/issues/5276 seems to be closely related.

**Comment by laurmaedje** [comment]
Same as https://github.com/typst/typst/issues/5244
