### ISSUE TITLE
When two footnotes are defined inside a footnote, the second one is not displayed (regression)

### ISSUE THREAD

**Issue by gyrrhe** [typst/typst#5256]
### Description

This appears to be a regression as the issue was not present in 0.11 but is present in 0.12. The following typst code:

```
#set page(height: auto, margin: 5pt)

Text#footnote[A first footnote references a second footnote#footnote[Second footnote.] and a third one#footnote[Third footnote].].

Other text#footnote[Fourth footnote.].
```

Gives the following with typst 0.11 (all footnotes are displayed in the footer):

![typst011](https://github.com/user-attachments/assets/b14887a0-806a-4120-8b49-75abc2c4fdc8)

And the following with typst 0.12 (the third footnote is not displayed in the footer):

![typst012](https://github.com/user-attachments/assets/93495241-6f52-42d4-a1c5-472c49866d88)

Until this is fixed, if anyone knows a workaround I'd love to know about it :)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Just a minor logic mistake:

https://github.com/typst/typst/blob/0228462ba10397468b3c0937e2e9cd1d3118e0fc/crates/typst-layout/src/flow/compose.rs#L472-L477

The first inner footnotes automatically returns a relayout error and `?` propagates it upwards, stopping other inner footnotes from being processed.
