### ISSUE TITLE
Space between function name and parameter list should not be allowed in set rule

### ISSUE THREAD

**Issue by MangoIV** [typst/typst#5258]
### Description

It is allowed to write 
```typst 
#set page (numbering
``` 
and 
```typst 
#set page(numbering 
```
, however, it is not allowed to write 
```typst 
#set page
  ( numbering 
```

I wonder if there's a specific reason for that. 

### Use Case

I really like to write comma separated lists with leading commata, i.e. 
```typst 
#set page 
  ( numbering: "1"
  , number-align: right
  ) 
``` 
and I think it would be cool if typst supported this :)

**Comment by laurmaedje** [comment]
`#set page (numbering: "I")` being allowed is actually not intentional. `#page (numbering: "I")` does not parse as a function call.

Allowing continuations on a new line would be too ambigious w.r.t. following text. Similar to how
```
#let x = 1
  * 2
```
does not multiply.

**Comment by MangoIV** [comment]
Ah, it not being intentional makes sense for me - otherwise it would be confusing to me that it's too ambiguous, after all, it is a parse error for now, so there is clearly room in the syntax. 

Thank you for clarifying.

**Comment by laurmaedje** [comment]
Let's keep it open to track this.

**Comment by wrzian** [comment]
I can fix it in like 10 minutes if you want

**Comment by laurmaedje** [comment]
All of those are already errors.

**Comment by wrzian** [comment]
Huh, I could've swore that wasn't the case. That's what I get for not being diligent. Expect a PR in a bit
