### ISSUE TITLE
Failed to render colors for svg

### ISSUE THREAD

**Issue by zzwe1** [typst/typst#5260]
### Description

Typst version: 0.12.0, The svg file itself is fine, but some of the colors turn black after importing it, the svg was made by cetz and exported via webapp, the next picture is actually the typ file, you can check it through my typst project link
![BlueBookHomework](https://github.com/user-attachments/assets/151b156d-2f26-40e4-9d4e-2b47c9a1aeb3)

### Reproduction URL

https://typst.app/project/we1Dsi9ncFkczX9NunfIK9

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
For some reason, Typst exports the plot with the "oklab" color space, which is currently not supported by us. See: https://github.com/typst/typst/issues/3654

**Comment by PgBiel** [comment]
> For some reason, Typst exports the plot with the "oklab" color space, which is currently not supported by us. See: #3654

I think this issue would be a duplicate then, right? Maybe the image could be posted again there

**Comment by LaurenzV** [comment]
I guess, yes.
