### ISSUE TITLE
1em gap between footnotes doesn't respect their font size

### ISSUE THREAD

**Issue by jsx97** [typst/typst#5265]
### Description

```typ
#set text(size: 10pt)
#set par(first-line-indent: 1em, justify: true, leading: 1em, spacing: 1em)

#show footnote.entry: set text(size: 50pt)
#show footnote.entry: it => {set par(leading: 1em, spacing: 1em); it}
#set footnote.entry(gap: 1em)

// --

#let fn1 = footnote[
  #lorem(5)

  #lorem(5)
]

#let fn2 = footnote[
  #lorem(5)

  #lorem(5)
]

#lorem(25)#fn1

#lorem(50)#fn2
```

Output:

<img width="417" alt="image" src="https://github.com/user-attachments/assets/d2a3df50-0c14-4a0c-8d0a-7be0d4807f4f">

Looking at the output, it seems that the `gap` between footnotes is 10 points, not 50 pt. Is it a bug or I simply don't understand something?

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
All footnote properties are resolved relative to the styles shared by the whole page run (run of pages with same properties). See my comment here: https://github.com/typst/typst/issues/2765#issuecomment-2304947887
