### ISSUE TITLE
error: version number is missing patch version

### ISSUE THREAD

**Issue by yonas** [typst/typst#5268]
### Description

Seems https://github.com/typst/typst/pull/4394 committed in https://github.com/typst/typst/commit/3d3489fbaef7524655f5c911e0bf6dec7394f90e doesn't work for me.

Changelog entry - "The "compiler" field for specifying the minimum Typst version required by a package now supports imprecise bounds like 0.11 instead of 0.11.0s"

```sh
> typst compile doc.typ
error: version number is missing patch version
  ┌─ doc.typ:1:8
  │
1 │ #import "@preview/cetz:0.3"
  │         ^^^^^^^^^^^^^^^^^^^
```

```typst
#import "@preview/cetz:0.3"

#cetz.canvas({
  import cetz.draw: *
  // Your drawing code goes here
})
```

typst `0.12.0 (unknown hash)`

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Note that the change log refers to the minimum required Typst compiler version in a package's "typst.toml" file (e.g. the latest Typst compiler version is 0.12.0), not to package versions, and not in Typst itself. The syntax you tried to use is invalid - you must specify the full version of the package you're importing.
