### ISSUE TITLE
In VS Code, the first Chinese double quotation mark are auto-closed, but the second is not, just a right mark。

### ISSUE THREAD

**Issue by VicolandLafro** [typst/typst#5270]
### Description

When using Chinses input, the first shift+' is shown as <img width="18" alt="image" src="https://github.com/user-attachments/assets/6b256d9d-c5c9-4ac0-b117-f28e18d325f5">. That's OK. But when typing the second, it is only a right mark like<img width="34" alt="image" src="https://github.com/user-attachments/assets/1aa23d28-25f8-4e8f-a6a0-c8cbf110d194">.
That's bad. 
I prefer either closing every pair of quotation marks, or never auto-closing and just show according to if there is a left mark. 

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by VicolandLafro** [comment]
a small spelling mistake "Chinses"

**Comment by VicolandLafro** [comment]
Also, I tried and made sure that it only happened in typst on VS Code. On any explorer my Chinese input method is right, and when using C++ or python, it works well, too.

**Comment by laurmaedje** [comment]
There is no official VS Code support for Typst. You should likely open a bug with whatever Typst extension you are using.
