### ISSUE TITLE
`json(path)` does not support relative path

### ISSUE THREAD

**Issue by lzm0** [typst/typst#5275]
### Description

When the `path` argument is set to an absolute path, Typst assumes it's under the current working directory and concatenate it like `$WORKDIR/$path`.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by lzm0** [comment]
The `read(path)` function seems to behave similarly.
```bash
typst example.typ
error: file not found (searched at /Users/zli/demo/var/folders/j4/n5nzv9x93r30yw8pg3_t_1gc0000gn/T/tmp.5l5sdyPEB2)
  ┌─ example.typ:3:30
  │
3 │ #let input = json.decode(read("/var/folders/j4/n5nzv9x93r30yw8pg3_t_1gc0000gn/T/tmp.5l5sdyPEB2"))
  │                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by lzm0** [comment]
This issue is also discussed in https://github.com/typst/typst/discussions/4195

**Comment by laurmaedje** [comment]
Absolute paths are resolved relative to the project root, both for convenience (loading things like assets) and for security (a Typst project should not be able to read `~/.ssh/...` and embed it into your document.

You can set `--root /`, but it is discouraged.
