### ISSUE TITLE
Stretching of `dash()` (U+305) broken with Noto Sans Math

### ISSUE THREAD

**Issue by Enivex** [typst/typst#5283]
### Description

The following

```typ
#show math.equation: set text(font: "Noto Sans Math", fallback: false)

$dash(x+y)$
```

renders as 

![image](https://github.com/user-attachments/assets/a2458666-27b7-46fc-9595-b581f62293e3)

while with the same font used with unicode-math and luatex

```tex
\[
    \wideoverbar{x+y}
\]
```
renders as

![image](https://github.com/user-attachments/assets/8d8a7c56-f721-4c07-b6d3-e9acc86c7a34)

The issue seems specific to this one accent and font

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
Interestingly, it looks approximately correct if I set the size to `93%`

**Comment by Enivex** [comment]
Based on https://github.com/typst/typst/pull/5288#discussion_r1815044810 I'll mark this one as upstream.

My understanding is that it's a font bug, and that the reason why it looks alright in luatex is that they don't follow the spec properly.

**Comment by mkorje** [comment]
I've opened an issue upstream: https://github.com/notofonts/math/issues/94.

**Comment by laurmaedje** [comment]
Since we don't bundle Noto Sans Math, I'm would just close this then.

**Comment by Enivex** [comment]
> Since we don't bundle Noto Sans Math, I'm would just close this then.

Based on the replies to https://github.com/notofonts/math/issues/94 it does seen like it's not exclusively a font issue after all
