### ISSUE TITLE
Compiling with ``--locked`` flag can break

### ISSUE THREAD

**Issue by dei-layborer** [typst/typst#5284]
### Description

The docs (or at least the README) say that, if compiling Typst manually via ``cargo install``, to use the ``--locked`` flag.  However, this can break Typst.

For example, I used that method to compile it when 0.12 was released officially, but using the ``--locked`` flag built against an incorrect and unavailable version of OpenSSL, making Typst unusable.  Rebuilding without ``--locked`` worked fine.

To that end, it may be worth changing the docs not to suggest this?

**Comment by laurmaedje** [comment]
If you build without locked your compiler _might_ behave slightly differently due to newer dependencies potentially being used, so I'm not sure it would be good to drop this by default.

I think there actually were some discussion to make cargo install default to --locked.

**Comment by alerque** [comment]
You can have your cake and eat it too. OpenSSL is one dependency that *really* should be used from your system where it is kept up to date by the system package manager. At the same time building apps like Typst with `--locked` absolutely makes sense. The solution here is to avoid the vendored sources entriely:

```bash
export OPENSSL_NO_VENDOR=true
cargo build -p typst-cli --frozen --release
```

Also @laurmaedje this project would be well advised to switch from openssl to [rustls](https://crates.io/crates/rustls).

**Comment by laurmaedje** [comment]
We used rustls in the past and it caused problems. See https://github.com/typst/typst/pull/3258/ and https://github.com/typst/typst/pull/3253. I'm not sure whether the fault with lies with ureq, rustls, or Microsoft Azure (where the packages are hosted), but the combination of the three definitely didn't work properly.
