### ISSUE TITLE
Sizing a circle/square with `width` or `height` beyond their default width/height is broken in 0.12

### ISSUE THREAD

**Issue by laurmaedje** [typst/typst#5287]
### Description

Their layout bounds expand to the configured width/height, but the shape itself doesn't. Notably `size` works and `width` or `height` that is smaller than default also works. `rect` and `ellipse` are also not affected because they don't have the logic that enforces square aspect ratio.

This wasn't probably not caught by the tests because the squares and circles there are all smaller than the default. The fact that nobody noticed this goes to show how much these two functions are used.

Reproduction:
```typ
#square(height: 5cm)
#square(size: 5cm)
```

### Typst version

- [ ] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Actually, not sure why I thought this was a regression. It doesn't work on 0.11.1 either.

**Comment by Enivex** [comment]
> Actually, not sure why I thought this was a regression. It doesn't work on 0.11.1 either.

It would still be a regression, just earlier than 0.11? Surely this worked at some point

**Comment by laurmaedje** [comment]
Nope, `#square(width: 5cm)` is broken all the way down to 0.6, so probably since forever.

**Comment by Enivex** [comment]
That's wild
