### ISSUE TITLE
v0.12.0 linux/arm64 Docker image shipped with x86-64 binary

### ISSUE THREAD

**Issue by kiding** [typst/typst#5290]
### Description

Running the v0.12.0 Docker image on a linux/arm64 machine will crash with an error message `exec /bin/typst: exec format error`. This is due to the fact that the typst binary in the image is in fact in x86-64, as can be seen below:

```
$ uname -a
Linux ubuntu 5.15.0-87-generic #97-Ubuntu SMP Tue Oct 3 09:52:42 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

$ sudo docker run ghcr.io/typst/typst:v0.12.0@sha256:e142773807fb7d0be65908653eeaf0f2e78cae900f594bab41476a93ec9a377a
exec /bin/typst: exec format error

$ sudo docker cp $(sudo docker ps -a -q | head -n 1):/bin/typst .
Successfully copied 39.7MB to /home/ubuntu/.

$ file typst
typst: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, BuildID[xxHash]=f228d78c86710a56, stripped
```

Running the same image on macOS/arm64 will **not** crash (probably) thanks to Rosetta, as can be seen below:

```
$ uname -a
Darwin A3113.local 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:38:45 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8122 arm64

$ docker run ghcr.io/typst/typst:v0.12.0@sha256:e142773807fb7d0be65908653eeaf0f2e78cae900f594bab41476a93ec9a377a

Welcome to Typst, we are glad to have you here! ❤️
...

$ docker cp $(docker ps -a -q | head -n 1):/bin/typst .
Successfully copied 39.7MB to ...

$ file typst
typst: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), static-pie linked, BuildID[xxHash]=f228d78c86710a56, stripped
```

This issue affects v0.12.0-rc1 and v0.12.0-rc2 as well.

### Operating system

Linux, macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by freundTech** [comment]
I'm looking into it. This was probably caused by me changing the docker build from emulated to cross-compiling. Not quite sure what the error is yet. The CI log looks fine so far.

**Comment by freundTech** [comment]
Update: The `$TARGETPLATFORM` environment variable is empty during the build, causing `xx`/`xx-cargo` to default to the build platform and build x86_64. Now to figure out why it is empty.
