### ISSUE TITLE
How to automatically add borders to all pages

### ISSUE THREAD

**Issue by dghoskins** [typst/typst#5311]
### Description

```markdown

## Description
In Typst 0.12.0, while it's possible to add a border to a single page using:
```typst
#place(rect(width: 100%, height: 100%, stroke: black))
```
There appears to be no way to automatically apply this border to all pages in a document. This should be a basic layout capability.

## Current Behavior
The following approaches have been tried:
1. Using `page` background:
```typst
#set page(
  background: rect(width: 100%, height: 100%, stroke: black)
)
```

2. Using `place` in header:
```typst
#set page(
  header: place(
    top + left,
    rect(width: 100%, height: 100%, stroke: black)
  )
)
```

3. Using show rules:
```typst
#show page: it => [
  #place(rect(width: 100%, height: 100%, stroke: black))
  #it
]
```

None of these approaches work - they either produce no borders at all or only border the first page.

## Expected Behavior
There should be a way to automatically add borders to all pages in a document, similar to how other page-level styling (margins, headers, footers) works automatically.

## Environment
- Typst version: 0.12.0
- Document type: Multi-page technical specification with headings and lists

## Minimal Example
Here's a complete example showing the issue:
```typst
#set page(
  paper: "us-letter",
  margin: 0.5in,
)

#place(rect(width: 100%, height: 100%, stroke: black))

= Heading 1
Some content

= Heading 2
More content that forces a page break

= Heading 3
Content on third page
```
This only produces a border on the first page.
```


### Use Case

Some documents require a page border on each page.

**Comment by PgBiel** [comment]
Your first attempt was correct, you just needed to discount the margin in the width and height (`100% - margin`).

![border shown](https://github.com/user-attachments/assets/0f6da925-3c58-40a1-a7b7-550b81fa56a6)

**Comment by dghoskins** [comment]
Ah, that was the key I was missing. Thank you.
Dennis
