### ISSUE TITLE
Insufficient lower bound for bumpalo in Cargo.toml

### ISSUE THREAD

**Issue by Garmelon** [typst/typst#5342]
### Description

Version 0.12.0 of the typst crate depends on bumpalo with `version = "3"`:
https://github.com/typst/typst/blob/737895d769188f6fc154523e67a9102bc24c872e/Cargo.toml#L36

However, it uses `extend_from_slice_copy`, which was only introduced in [bumpalo 3.15.4](https://github.com/fitzgen/bumpalo/blob/main/CHANGELOG.md#3154):
https://github.com/typst/typst/blob/737895d769188f6fc154523e67a9102bc24c872e/Cargo.toml#L36

Thus, the dependency on bumpalo should at least use `version = "3.15"`, or the typst crate may sometimes fail to compile when used as dependency.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Feel free to make a PR with a fix.
