### ISSUE TITLE
Wrong measurements and location?

### ISSUE THREAD

**Issue by Asuranceturix** [typst/typst#5344]
### Description

The idea is: I'd like to be able to find, hopefully with precision, the bounding box of a word or group of words, and query them from CLI.

![image](https://github.com/user-attachments/assets/10fae6fb-7914-4109-8d39-21322b172679)

Using the values returned by measure and locate to draw a rectangle in the background (I have been unable to do so programmatically), the rectangle is not where I would expect it, nor does it have the size I'd expect (the height does not change at all if the text has only letters with no ascenders or descenders). This is not a problem with the rectangle drawing code: I get the same results using these numbers in a vector drawing application. Is this the expected behaviour?

### Reproduction URL

https://typst.app/project/rbuso7j6PsMohK_Dl6FVNK

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Text measurements use the [text edge parameters](https://typst.app/docs/reference/text/text/#parameters-top-edge). By default, these are "baseline" and "cap-height", which are static across the font, so individual ascenders and descenders do not affect the layout. You can set them to "bounds" to get an exact bounding box. This is not the default as it often produces uneven looking layouts.

The position of text always specifies where the bottom left basepoint, on the text's baseline, is. That is how it is intended to work. It's a bit inconvenient when you want to compute a bounding box, but that's not what the position thing is optimized for.

Still, I think what you want can be achieved with a bit of work. I'd suggest asking for help on the [Forum](https://forum.typst.app) or on [Discord](https://discord.gg/2uDybryKPe).
