### ISSUE TITLE
Empty footnote entry show rule leads to infinite loop

### ISSUE THREAD

**Issue by EpicEricEE** [typst/typst#5354]
### Description

When starting to type a show rule for footnote entries, the rule is initially empty
```typ
#show footnote.entry: it => {}

#lorem(10) #footnote[A footnote]
```
This empty show rule leads to some kind of infinite loop and never ending compilation. To continue writing, one needs to refresh the page (after making sure that the rule returns something). The discord bot eventually timeouts.

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by wznmickey** [comment]
In Composer::footnote, it will generate a empty frame which will make this element be queued for the next page and in next page it will still be queued for the next and next page and will never stop.

**Comment by laurmaedje** [comment]
The empty frame check is hacky at best, but unfortunately we don't have a better way to check that yet. But in this case, we should check that the first frame is empty AND that there is at least one more frame.
