### ISSUE TITLE
Bad alignment point on "big" symbols (sum, integral, ..) when there is an even number of "&" before

### ISSUE THREAD

**Issue by arnaud-ma** [typst/typst#5358]
### Description

Here is a minimal example

```
$
sum\
4
$

$
&sum\
&4
$

$
&&sum\
&&4
$
```
![image](https://github.com/user-attachments/assets/311e043a-38bc-4c6b-89db-6a6f469df1d1)

I think it's only the last case that's bad. Here's a slightly more realistic example:
```
$
EE[Y] &= EE[EE[Y | X]] &= integral_(RR) phi_1(x) dif PP_X (x) \
&&= integral_0^1 e^(theta x) / (1 + e^(theta x)) dif x &\
$
```
![image](https://github.com/user-attachments/assets/6d3a9d79-4168-4299-8aad-a8c6e8b5f22a)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
This isn't wrong, but how alignment works. The column after an even number of &s will be right-aligned.
