### ISSUE TITLE
Weird and unnecessary hyphenation in tables

### ISSUE THREAD

**Issue by SLUCHABLUB** [typst/typst#5360]
### Description

I was trying to make a table where one of the headers was the word "Formal". However when I compiled, it added a hyphen and line break. Like this:

| For-<br>mal | 
| --- |

Even though there was enough space to make the table bigger. I played around with it and even if the table is just one cell this still happens. I should note however that this only occurs with the set rule:

```typst
#set par(justify: true)
```

I'm guessing that it has to do with the width of the word, I haven't tested that many, most work just fine, but "Exrmal" also breaks.

Here is my minimal example:

```typst
#set par(justify: true)

#table(columns: 1, [Formal])
```

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by wznmickey** [comment]
Seems that the width calculation have slight floating point calculation error which would cause huge cost.
In my test, the region width is 31.591999999999995pt and the width needed is 31.592pt.

**Comment by wznmickey** [comment]
Cause in `grow` in `typst-layout/src/pad.rs`, (s + p.abs) / (1.0 - p.rel.get()) is `(31.592pt + 10.0pt)/(1.0-0.0)`. It should be `41.592pt` but the given result is `41.59199999999999pt`.

**Comment by wznmickey** [comment]
Not sure how to solve this floating problem, so add a manual check instead.

**Comment by Enivex** [comment]
> Cause in `grow` in `typst-layout/src/pad.rs`, (s + p.abs) / (1.0 - p.rel.get()) is `(31.592pt + 10.0pt)/(1.0-0.0)`. It should be `41.592pt` but the given result is `41.59199999999999pt`.

41.592 is not representable as a float. Not sure what you mean by "should be".

**Comment by wznmickey** [comment]
31.592+10 is 41.592. But due to floating error, it became a little less than 41.592.
