### ISSUE TITLE
Show rules for lists that access children by index exceed maximum grouping depth

### ISSUE THREAD

**Issue by schuelermine** [typst/typst#5367]
### Description

```typ
#show list: it => it.children.at(0)

- A
```
errors with "Maximum grouping depth exceeded"

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Same as https://github.com/typst/typst/issues/5368. 

Friendly note for the future: For such closely related things, one issue at a time suffices.
