### ISSUE TITLE
Text styling rule change paragraph indentation

### ISSUE THREAD

**Issue by daskol** [typst/typst#537]
This snippet of markup

```typst
#set par(first-line-indent: 2em)
#show "ABBRV": smallcaps
= Introduction
Here is an exampple how style rule applied to text pattern works.

ABBRV is something.

Another ABBRV is something.
```

produces this output.

![image](https://user-images.githubusercontent.com/9336514/229374984-52b6862a-3037-4ae7-ab41-06b5cfcce0c4.png)

**Comment by teenjuna** [comment]
Looks like it's fixed with e13c72b @reknih
