### ISSUE TITLE
Suggestion: Introduce Markdown-Compatible Headline Syntax in Typst (`# Headline` vs. `#function`)

### ISSUE THREAD

**Issue by woerndl** [typst/typst#5386]
### Description

Currently, Typst syntax for simple text is largely Markdown-compatible, which makes it very accessible for many users. However, one grievous exception is with headline syntax: Markdown-style headers are not supported because the `#` character is reserved for function calls.

This means real-time preview and functionality of popular Markdown tools like Obsidian, Logseq, Roam Research, Ulysses, Scrivener, iA Writer, Zettlr, Typora […] is severely hindered. Not only is the visual rendering missing, but important time-saving functions like jump marks, quick navigation, and collapsing can't be used either.

Therefore I propose that Typst introduce an alternative headline syntax in the form of:

- `# Headline 1`
- `## Headline 2`
- …

This approach would allow Markdown-style headers to be parsed correctly in all existing tools, without conflicting with the `#function()` syntax. This would serve as "syntactic sugar" for headlines, exactly like `= Headline` already does. This way Typst could be used in many popular writing tools out of the box.

### Potential Counterarguments & Responses

**1. Counterargument: "Why not just use [Markdown import](https://typst.app/universe/package/cmarker/)?"**

This just shifts the problem. For example you can't reliably cite anymore. As a citation either has to be replaced with custom regular expressions (with missing features likes multiple sources, selection of form etc.) or wrapped in `<!--raw-typst-->`.

Plus you end up with a mix of syntaxes that can no longer be transformed using Pandoc e.g. as a Word/docx hand-off to a supervisor. Mixing syntaxes could also lead to unexpected results with the upcoming HTML export of Typst to publish an EPUB etc.

**2. Counterargument: "Why not just use an editor that supports Typst syntax?"**

Editors like Obsidian, iA Writer, and Ulysses […] are incredibly popular for their text-oriented usability and cross-platform support. They provide features tailored for drafting long-form content, like natural language syntax highlighting, mobile usability, and effective in-document navigation based on sections (headlines) and many more features tailored for professional writers—all of which are lacking in most code-oriented editors (because they aren't needed there). For users focused primarily on writing, Typst could benefit from leveraging the power of existing writing tools, rather than forcing users into less-optimal workflows for drafting text.

Of course, these tools are not intended for writing code. But the basic syntax is often enough for these types of publications. Even an occosial `#figure` or `#table` could easily be dealt with, as these blocks don't need much syntax highlighting and can be written in a way that doesn't trigger a hashtags highlighting like `#{figure(…)}`.

**3. Counterargument: "Double use of `#` would be inconsistent and confusing."**

Currently, `#` followed by a space (`# ` or `## `) results in a compiler error in Typst. By introducing this as an alternative headline syntax, it remains syntactically distinct from function calls (`#function()`). This is akin to the already space-sensitive differences in Typst, such as:

```
$ 123 + 123 $   // block math expression
$123 + 123$     // inline math expression
```

or

```
/ Term: Definition // Term list
/Term: Definition  // Plain text
```

### Use Case

**Rationale:**

The use of `#` for functions might have been an unfortunate design choice in terms of compatibility with Markdown, but it is also not set in stone that Typst must remain incompatible with many established writing tools. Adding a Markdown-compatible headline syntax would allow more users, especially those using alternative writing tools, to easily integrate Typst into their workflows without friction. This could lead to broader adoption and community growth.

**Conclusion:**

This proposal aims to improve Typst's usability by aligning its headline syntax with the Markdown standard. I believe this change could greatly benefit many potential users without introducing inconsistencies or breaking current functionality.

**Comment by Enivex** [comment]
I honestly see no reason why Typst has to align itself with Markdown syntax

**Comment by woerndl** [comment]
Interesting. Okay, to be fair, I didn't address that argument.

**4. Counterargument: "Someone sees no reason"**

As the user base grows, I assume there will be more people who are more interested in the writing and formatting possibilities of Typst. So less in the technology and more in the productive use, if you will. The early majority (or pragmatists) in market-speak.

I might be entirely wrong about how Typst is used (and will be), and it could just be my personal workflow that breaks here. (Which would be fine, it is just a proposal after all)

But people who write long-form content, like articles, books etc. and need a publishing pipeline (one of the intended targets of the future HTML feature I assume), often require a Markdown editor rather than VS Code or similar. And for that having functional headlines is crucial, for the reasons stated above.

**Comment by Enivex** [comment]
But why do you need to be able to write typst inside of a Markdown editor? The moment you use anything that's not Markdown it'll be incompatible.

This is not unique to headings, but math, code etc.

(Not to mention Markdown isn't one thing. There are various flavors.)

**Comment by PgBiel** [comment]
Typst's `=` syntax for headings isn't new or innovative. Typst wasn't inspired only by Markdown; it was also inspired by Asciidoc (https://asciidoc.org/). You may also notice other similarities to Asciidoc, which is supported by several tools (including GitHub itself).

> This means real-time preview and functionality of popular Markdown tools like Obsidian, Logseq, Roam Research, Ulysses, Scrivener, iA Writer, Zettlr, Typora […] is severely hindered. Not only is the visual rendering missing, but important time-saving functions like jump marks, quick navigation, and collapsing can't be used either.

The tools you mention don't support Typst, let alone real-time preview for it. You can, of course, use tools such as pandoc to convert simple enough Typst to Markdown and vice-versa, should you need to do so. But you should expect that tools that do not claim to support Typst won't support it perfectly. Similarly, Typst does not claim to be a Markdown-compatible language (even if it looks similar).

> Editors like Obsidian, iA Writer, and Ulysses […] are incredibly popular for their text-oriented usability and cross-platform support.

I don't buy the argument that Typst should adapt to those tools just because they are popular. Instead, you may request the authors of those tools to add Typst support.

---

In the end, most responses in terms of preference will be subjective, but personally I've grown to like using `#` for code mode and `=` for headings. And, while Markdown compatibility is often nice, it's already incompatible either way (e.g. `*` means strong in Typst and Asciidoc, but emphasis in most Markdown implementations). So I don't see that as a strong enough argument to change this rather fundamental part of the syntax.

**Comment by woerndl** [comment]
I think I have to clarify further. This proposal is NOT about "supporting" Markdown or "being" Markdown. This might be counterintuitive from a technical standpoint.

A fundamental part of my reasoning is that many people who care about writing don't care about whether they use Markdown, Asciidoc, or, for that matter, Typst's syntax.

BUT the tools I mentioned are already well established. As Markdown is well established. And thus these tools won't support Typst. Because Typst chose to reinvent just some wheels. As shown above mainly \*strong\* and headlines.

Taking a different syntactical approach with complex constructs like `tables` and `figures` […] made and makes total sense, as Typst is more elaborate and offers far more possibilities than Markdown in these regards. It makes way less sense for syntactic sugar like italic, strong, headlines etc. As these constructs do exactly the same thing.

I agree that the ship has sailed for functions. Typst 0.1X won't introduce a breaking change of "hey, by the way, functions are now written as \\{} instead of #{}". But an alternative syntax for headlines allowing `# Headline` COULD (again, just a proposal) be supported.

Summary, in two sentences: This change would allow people to create documents in Typst, while more comfortably staying in the well established tools for writing long-form content. Which mostly happen to have chosen Markdown going forward.

As did GitHub… a headline in this reply field is made by using `#` not `=`.

**Comment by laurmaedje** [comment]
Typst actually used to support `#` for headings. We started out with `=`, then switched to `#` in ~2021 or so, and switched back a bit later. We found that it was confusing for users. You argue that there already is such space-sensitive behaviour with math and term lists, but in those cases it is block vs inline (both part of the math syntax) and no list vs list (both part of the list syntax). In this case, it would be two completely distinct, but very important pieces of syntax, being almost the same. This is bound to cause confusion, especially for less experienced users.

I am also concerned with fracturing the ecosystem. If we support `#` in addition to `=`, people coming from Markdown will naturally drift towards this and now we have differing conventions across the ecosystem. This makes Typst harder to learn (think examples etc.)

Let me also mention that bringing Typst closer to Markdown is a slippery slope. If we add this syntax, people will keep asking for more and more Markdown syntax to be added, e.g. links (and Markdown's link syntax is _really_ bad in my opinion).

Ultimately, writing Typst in Markdown editors will be a suboptimal experience and I'm not willing to sacrifice the Typst language's coherency to make the experience a tad bit better. For the best Typst writing experience, you'll need a dedicated Typst editor. (And, for what it's worth, we strive to improve the experience on typst.app to cater more _both_ to power uses who need more of a code environment and for writers who need a clean editor with little distraction).

PS: Quoting the first response as 'Counterargument: "Someone sees no reason"' is counter-productive and seems to us to be in bad spirit. We would ask you to stay constructive and refrain from polemic answers like this.

**Comment by woerndl** [comment]
> PS: Quoting the first response as 'Counterargument: "Someone sees no reason"' is counter-productive and seems to us to be in bad spirit. We would ask you to stay constructive and refrain from polemic answers like this.

You are right. I see it as a somewhat balanced reaction to a "I see no reason" response with little argumentative value (which could be interpreted inadvertently polemic, not really adressing the intetions of the proposal). Your own answer just highlighted the contrast, though it required much more time and care. Thank you for sharing the insights and reasoning.

**Comment by danieltomasz** [comment]
Just a comment regarding @woerndl needs -   I might try using quarto  to write markdown, then compile  it to  pdf via typst engine 
https://quarto.org/docs/output-formats/typst.html
https://quarto.org/docs/reference/formats/typst.html
You can start building your own personalised templates; 

You have compatibilty with other editors (with Obsidian via plugins like  https://danielborek.me/2023/obsidian-quarto-callouts/ (might be outdated) or you just  couldwire in plain markdown and then include it to your qmd index file);

**Comment by quachpas** [comment]
About compatibility of popular editor with Typst:
- Obsidian: 
    - https://github.com/fenjalien/obsidian-typst is a plugin
    - https://forum.obsidian.md/t/typst-support/61135/5 is the feature request
- Logseq:
    - https://discuss.logseq.com/t/supporting-typst-formula/17298 feature request
- Roam Research: cannot find anything :(
- Ulysses: 
    - https://www.facebook.com/ulyssesapp/posts/we-have-just-released-an-update-that-adds-support-for-latex-equations-plus-proje/660480476114278/ the development team is aware of Typst
- Scrivener: 
    - https://forum.literatureandlatte.com/t/typst-a-new-markup-page-layout-engine-to-take-on-latex/134674/25, please take a look at this post, it details how to configure Scrivener for Typst
- iA Writer: I cannot find anything
- Zettlr: https://github.com/Zettlr/Zettlr/issues/4698
- Typora: https://github.com/typora/typora-issues/issues/5803

For dedicated desktop editors, please take a look at:
- https://github.com/Bzero/typstwriter
- https://github.com/IgKh/katvan

There are probably many more

**Comment by woerndl** [comment]
Thanks for sharing your workflow ideas, @danieltomasz. Very kind!

I implemented my personal solution with [cmarker](https://typst.app/universe/package/cmarker/) and Obsidian. Using ~~too many~~ regular expressions 😄 but the result is now really, really amazing. The best scientific writing workflow I've ever had. I plan to document and share my workflow as soon as it is battle-proof (and can link it here if you are interested).

But doing the transformation adds, in my opinion, unnecessary complexity for what I think will be a very, very common workflow for many. That is why I still bothered to make this proposal, knowing full well that the chances of this materializing are slim. Even if I still think it would be a net positive for Typst as a project.

I also understand Laurenz's concerns about facing challenges from two sides: a potential loss of coherence and possibly reduced incentives to use Typst.app. And [Typst.app](https://typst.app/) drives this great project, so it makes sense to keep it as healthy as possible. On the other hand in terms of product-market fit it would make sense to attract everyone who still needs PDFs in the future. People writing thesis, digital books, lawyers etc.

Therefore my proposal would have been a sole alternative (!) syntax, e.g., not directly used in the examples. In my mind, `=` would stay for any workflow that just uses Typst highlighting/editors. I assume Overleaf is still heavily profiting of users writing their thesis/book/whatever [in Markdown](https://www.overleaf.com/learn/how-to/Writing_Markdown_in_LaTeX_Documents) as they have multiple articles for SEO targeting the topic.

On TeX Stack Exchange, questions regarding Markdown and [\markdownInput](https://ctan.org/pkg/markdown) have a couple of hundred thousand views combined, so I suppose I'm not entirely alone in writing these kinds of documents in Markdown while still needing a typesetting language in the background.

---

@quachpas, thank you for the link and feature request list. This could be very handy for many people finding this issue who want to write math. However, that's not really the point of my proposal. My proposal is to have the alternative syntax not because I want Typst rendered in a non-Typst editor, but because I need the in-editor preview for headlines and related functions, like outline navigation, etc.

**Comment by danieltomasz** [comment]
Think you for bring this isuue @woerndl, I also still use markdown with or without `typst`  in many of my workflows and there is indeed some complexity added to it. But I am thinking that  using typst directly in markdown editor always might be tricky (you will solve headers problems but for example markdown use #tags  which  will might confuse typst   compiler  et cetera)  and there so many  variants of markdown, for example for  callouts (obsidian doesnt support the one with `:::``, so I needed to write my lua fillter)  

Much better idea is to improve semantic interoperability with markdown and other formats, via pandoc or other tools (like linked cmarker); For example, would like to write in pure typst, but compile to docx to share with other  less technical colleagues for comments. Since  last year there is a typst reader  included in pandoc,  I think  that the dev doing really good job to ensure semantic  interoperability with other formats, even if there are still some rough edges.

**Comment by wznmickey** [comment]
Even though it is an editor that support Typst, it may still be useful if Typst support `#` heading. There are many AI tools that would help users to generate codes and text. However, since most training material are under Markdown format which use `#`, in most cases, the output text also use `#` rather than `=`.  I must change from `#` to `=` for every heading it generated. It would be helpful if Typst support `#`. The time needed to change from `#` to `=` is not long so it is acceptable without support `#`.

**Comment by alerque** [comment]
When you start changing your input markup language grammar to accommodate whatever regurgitated junk some unspecified generic LLM spews just because they spew it then you've lost the plot. Cleanup your input.

**Comment by gagarine** [comment]
I think adding an optional # headline syntax could work without breaking Typst. It would be fully backward-compatible, leaving = headings as they are. 

In practice, this is less about a syntax feature and more about aesthetic structuring: # headings give a familiar visual hierarchy in the source text, which makes documents easier to read and navigate. 

But mainly, simple markdown is already stored in many application databases, and being able to render it directly in typst without conversion would save time and reduce errors. 

I already run into this type of problem: an application stores markdown that is rendered with JavaScript on the client side. It would be nice if I could directly integrate this markdown into a Typst template and render it as a PDF. Today, the only limitation is the # headline that force me to do some conversion first.

Last, heading are a structural element, not decorative, so this change is unlikely to create a slippery slope toward other Markdown features.

**Comment by alerque** [comment]
> But mainly, simple markdown is already stored in many application databases, and being able to render it directly in typst without conversion would save time and reduce errors.

Attempting to directly render content intended for us in a Markdown environment would be a source of *more errors* and confusion, not less. If you have Markdown, use an actual conversion tool (ala `pandac`) on it and enjoy an actually error free experience where what the content actually represents semantically actually gets converted over.

If you are running Typst you can't render it "just with JavaScript on the client side" anyway, Typst is compiled to WASM. If running WASM is an option for you then you can run Pandoc too and do it properly.
