### ISSUE TITLE
Misaligned superscripts and subscripts

### ISSUE THREAD

**Issue by Leedehai** [typst/typst#539]
Hi, while working on the [physics](https://github.com/Leedehai/typst-physics) package I discovered there's an issue of misaligned superscripts and subscripts, that are too sensitive[1] on the preceding symbol's height.
```
$ x^square, y^square, z^square, h^square, g^square, (1/2)^square $
$ x_square, y_square, z_square, h_square, g_square, (1/2)_square $
```
Rendered by Typst:
<img width="362" alt="Screenshot 2023-04-02 at 21 34 18" src="https://user-images.githubusercontent.com/18319900/229392793-285230d2-9983-48e7-8a4e-eb1fdf99d70f.png">
This misalignment makes certain expressions not so pretty, e.g. 
<img width="178" alt="Screenshot 2023-04-02 at 22 15 09" src="https://user-images.githubusercontent.com/18319900/229396469-f29e1016-e9fe-4a31-b58b-467a76ee5032.png">
<img width="77" alt="Screenshot 2023-04-02 at 21 40 25" src="https://user-images.githubusercontent.com/18319900/229393046-ea2eeeec-f676-4d01-8856-690954a9cf51.png">

Below is the rendering done by Latex. They are aligned, and the position is not so sensitive on the preceding symbol's height, as expected and familiar with by most paper writers.
```
\documentclass{article}
\usepackage{amssymb}

\begin{document}

$$ x^\square, y^\square, z^\square, h^\square, g^\square, \bigg(\frac{1}{2}\bigg)^\square $$

$$ x_\square, y_\square, z_\square, h_\square, g_\square, \bigg(\frac{1}{2}\bigg)_\square $$

\end{document}
```
<img width="350" alt="Screenshot 2023-04-02 at 21 37 41" src="https://user-images.githubusercontent.com/18319900/229392894-e759624c-60d3-4954-ab70-382d5449aa7a.png">

Thanks! Typst is awesome and I very much like to see it succeed.

[1] Naturally, the superscript and subscript's vertical positions should pay _some_ attention to the preceding symbol's height (say, a very tall symbol like a fraction `frac(1,2)`, a `sum` or `prod`, or an integral symbol), but they need not be _too_ sensitive on the preceding symbol's height, like the letters in the example.

**Comment by Leedehai** [comment]
A bit more examples :)
LaTeX:
```
$$ e_1 y_1 \delta_1 \beta_1, e_1^1 y_1^1 \delta_1^1 \beta_1^1 $$
$$ e^1 y^1 \delta^1 \beta^1, e_1^1 y_1^1 \delta_1^1 \beta_1^1 $$
$$ x^1 [x]^1 x_1 [x]_1 $$
```
<img width="244" alt="Screenshot 2023-04-27 at 22 08 31" src="https://user-images.githubusercontent.com/18319900/235038249-b8dee94e-429a-4aa8-9983-44a301257ca9.png">

Typst:
```
$ e_1 y_1 delta_1 beta_1, e_1^1 y_1^1 delta_1^1 beta_1^1 $
$ e^1 y^1 delta^1 beta^1, e_1^1 y_1^1 delta_1^1 beta_1^1 $
$ x^1 [x]^1 x_1 [x]_1 $
```
<img width="206" alt="Screenshot 2023-04-27 at 22 12 12" src="https://user-images.githubusercontent.com/18319900/235038290-4a3678b4-acd6-4969-bc1f-f8ac02853965.png">

**Comment by Enivex** [comment]
As a workaround you can do this
```
$ e zws_1 y zws_1 delta zws_1 beta zws_1, e zws_1^1 y zws_1^1 delta zws_1^1 beta zws_1^1 $
$ e zws^1 y zws^1 delta zws^1 beta zws^1, e zws_1^1 y zws_1^1 delta zws_1^1 beta zws_1^1 $
$ x zws^1 [x] zws^1 x zws_1 [x] zws_1 $
```

![image](https://github.com/typst/typst/assets/2191754/17047831-e996-4fdd-89b3-83f5de9f2543)

**Comment by Leedehai** [comment]
Closing after PR #1129 was merged.
