### ISSUE TITLE
Embedded Fonts Issue: Blank PDF when Viewing in Feedback Fruits

### ISSUE THREAD

**Issue by gustavakerstrom** [typst/typst#5392]
### Description

PDFs with embedded fonts are not displaying text correctly when viewed in [Feedback Fruits](https://feedbackfruits.com/). The issue varies between versions:

- Version 0.12: All text disappears when viewing the PDF.
- Version 0.11.1: Only equations partially disappear, while other text may remain visible.

Workaround: Uploading a custom font as a base64 encoded file allows the PDF to display properly. But increases the file size.
Workaround for Version 0.11.1: Converting the PDF using `pdftocairo -pdf` resolves the issue, but this is not ideal for regular workflow.

### 0.11.1
[lorem_0.11.1.pdf](https://github.com/user-attachments/files/17679586/lorem_0.11.1.pdf)
![Screenshot From 2024-11-08 14-49-38](https://github.com/user-attachments/assets/0be5805c-30b4-469f-a381-949bf7f47e96)
### 0.12
[lorem_0.12.pdf](https://github.com/user-attachments/files/17679588/lorem_0.12.pdf)
![Screenshot From 2024-11-08 14-49-02](https://github.com/user-attachments/assets/8d935488-3ff1-40c1-97e3-a034f217e6e9)

### Operating system

Web app

### Typst version

- [x] I am using the latest version of Typst

**Comment by Karlkorv** [comment]
I've also had this issue. Really difficult to work around since my school uses feedback fruits for most assignments.

**Comment by LaurenzV** [comment]
Could you maybe send the resulting PDF here?

**Comment by LaurenzV** [comment]
I tried rendering the PDF with 7 different PDF viewers and they all show it fine...:

![lorem_0 12-0](https://github.com/user-attachments/assets/67eb0234-e9d1-46ca-ae62-9055a5b1b96a)

Adobe Acrobat also displays it fine, so I suspect the issue must be on their side...

**Comment by gustavakerstrom** [comment]
@LaurenzV Yes, the issue does not appear on other viewers I have tried but it also only appears with PDFs generated by Typst.  The PDF displays correctly if I manually base64 encode the font and upload it to the project.

Typst generated PDFs might also have compatibility issues with other viewers that rely on CSS-embedded fonts.

**Comment by LaurenzV** [comment]
Yeah, if there is a workaround then we should obviously try to implement it. I'm just saying that the issue is likely to be on their side. But it doesn't seem like I can easily try Feedback Fruits myself, so I can't investigate it further. :/

**Comment by TS53** [comment]
Wasn't the Libertine font changed in 0.12.0? Maybe related to this specific font.

**Comment by SoraShu** [comment]
I tried to contact the support of feedback fruits, and they said:
> Let me know if this is helpful.
> The FeedbackFruits media service convert PDF's uploaded to HTML pages so it can be displayed in the document viewer and annotated by teachers and students. This process is highly dependent on the PDF being compliant with current PDF standards, which is not the case for files output by some PDF tools/applications. By saving the PDF as PDF/A (Archivable) or PDF/X (Exchangeable) in known-compliant software such as Adobe Acrobat, the file can be processed without issue in FeedbackFruits.
For the PDF that was not uploaded correctly, we recommend to re-submit the paper after running it through a PDf flatterner: https://www.sejda.com/nl/flatten-pdf

**Comment by xkevio** [comment]
> I tried to contact the support of feedback fruits, and they said:
> 
> > Let me know if this is helpful.
> > The FeedbackFruits media service convert PDF's uploaded to HTML pages so it can be displayed in the document viewer and annotated by teachers and students. This process is highly dependent on the PDF being compliant with current PDF standards, which is not the case for files output by some PDF tools/applications. By saving the PDF as PDF/A (Archivable) or PDF/X (Exchangeable) in known-compliant software such as Adobe Acrobat, the file can be processed without issue in FeedbackFruits.
> > For the PDF that was not uploaded correctly, we recommend to re-submit the paper after running it through a PDf flatterner: https://www.sejda.com/nl/flatten-pdf

Hm, we do have PDF/A-2b support now, maybe that is already enough?

**Comment by TS53** [comment]
> > I tried to contact the support of feedback fruits, and they said:
> > > Let me know if this is helpful.
> > > The FeedbackFruits media service convert PDF's uploaded to HTML pages so it can be displayed in the document viewer and annotated by teachers and students. This process is highly dependent on the PDF being compliant with current PDF standards, which is not the case for files output by some PDF tools/applications. By saving the PDF as PDF/A (Archivable) or PDF/X (Exchangeable) in known-compliant software such as Adobe Acrobat, the file can be processed without issue in FeedbackFruits.
> > > For the PDF that was not uploaded correctly, we recommend to re-submit the paper after running it through a PDf flatterner: https://www.sejda.com/nl/flatten-pdf
> 
> Hm, we do have PDF/A-2b support now, maybe that is already enough?

No.
![a2b](https://github.com/user-attachments/assets/ee1ab8bd-c16b-4dc1-8253-2276d12da441)

**Comment by SoraShu** [comment]
I am not very familiar with these PDF standards. At present, PDF flattener or pdftocairo can solve the problem, but as mentioned above, this is not ideal for regular workflow.

**Comment by xkevio** [comment]
> > > I tried to contact the support of feedback fruits, and they said:
> > > > Let me know if this is helpful.
> > > > The FeedbackFruits media service convert PDF's uploaded to HTML pages so it can be displayed in the document viewer and annotated by teachers and students. This process is highly dependent on the PDF being compliant with current PDF standards, which is not the case for files output by some PDF tools/applications. By saving the PDF as PDF/A (Archivable) or PDF/X (Exchangeable) in known-compliant software such as Adobe Acrobat, the file can be processed without issue in FeedbackFruits.
> > > > For the PDF that was not uploaded correctly, we recommend to re-submit the paper after running it through a PDf flatterner: https://www.sejda.com/nl/flatten-pdf
> > 
> > 
> > Hm, we do have PDF/A-2b support now, maybe that is already enough?
> 
> No. ![a2b](https://private-user-images.githubusercontent.com/178008836/384473392-ee1ab8bd-c16b-4dc1-8253-2276d12da441.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODg3MzksIm5iZiI6MTczMTA4ODQzOSwicGF0aCI6Ii8xNzgwMDg4MzYvMzg0NDczMzkyLWVlMWFiOGJkLWMxNmItNGRjMS04MjUzLTIyNzZkMTJkYTQ0MS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNzUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjk5Nzk2NWEzNzNkYmYzMzljMTA3MGE3YmZmNDJlMjc5NDg3NmY3OTcxNTlkNmRiYTczYTVjYjc2ODBhZWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TZQb9zfBjL8DRAswG4KL4qasJOT7T-HAT65KnRgyhvA)

From what I remembered, some of these tests require some field to be occupied which isn't actually necessary for a PDF to conform to A-2b, or 0.12 wasn't used, but I digress.

**Comment by TS53** [comment]
> > > > I tried to contact the support of feedback fruits, and they said:
> > > > > Let me know if this is helpful.
> > > > > The FeedbackFruits media service convert PDF's uploaded to HTML pages so it can be displayed in the document viewer and annotated by teachers and students. This process is highly dependent on the PDF being compliant with current PDF standards, which is not the case for files output by some PDF tools/applications. By saving the PDF as PDF/A (Archivable) or PDF/X (Exchangeable) in known-compliant software such as Adobe Acrobat, the file can be processed without issue in FeedbackFruits.
> > > > > For the PDF that was not uploaded correctly, we recommend to re-submit the paper after running it through a PDf flatterner: https://www.sejda.com/nl/flatten-pdf
> > > 
> > > 
> > > Hm, we do have PDF/A-2b support now, maybe that is already enough?
> > 
> > 
> > No. ![a2b](https://private-user-images.githubusercontent.com/178008836/384473392-ee1ab8bd-c16b-4dc1-8253-2276d12da441.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwODg3MzksIm5iZiI6MTczMTA4ODQzOSwicGF0aCI6Ii8xNzgwMDg4MzYvMzg0NDczMzkyLWVlMWFiOGJkLWMxNmItNGRjMS04MjUzLTIyNzZkMTJkYTQ0MS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQxNzUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjk5Nzk2NWEzNzNkYmYzMzljMTA3MGE3YmZmNDJlMjc5NDg3NmY3OTcxNTlkNmRiYTczYTVjYjc2ODBhZWZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TZQb9zfBjL8DRAswG4KL4qasJOT7T-HAT65KnRgyhvA)
> 
> From what I remembered, some of these tests require some field to be occupied which isn't actually necessary for a PDF to conform to A-2b, or 0.12 wasn't used, but I digress.

You mean the VeraPDF tool is wrong? I doubt.

**Comment by xkevio** [comment]
> You mean the VeraPDF tool is wrong? I doubt.

It works with VeraPDF's inbuilt PDF/A-2b profile, just tested.

**Comment by TS53** [comment]
> > You mean the VeraPDF tool is wrong? I doubt.
> 
> It works with VeraPDF's inbuilt PDF/A-2b profile, just tested.

Which Version of VeraPDF? Which is the content of the PDF?

I'm using VeraPDF 1.26.2 on Windows and typst 0.12.0 (737895d7).

**Comment by xkevio** [comment]
> > > You mean the VeraPDF tool is wrong? I doubt.
> > 
> > 
> > It works with VeraPDF's inbuilt PDF/A-2b profile, just tested.
> 
> Which Version of VeraPDF? What is the content of the PDF?
> 
> I'm using VeraPDF 1.26.2 on Windows and typst 0.12.0 ([737895d](https://github.com/typst/typst/commit/737895d769188f6fc154523e67a9102bc24c872e)).

Same as you. The content was just `#lorem(40` and a math equation. Did you specify the pdf-standard in the CLI when exporting?

**Comment by TS53** [comment]
> --pdf-standard a-2b

I'm using the GUI with correct settings, as can be seen from the given screenshot.
A Document with only `#lorem(40)` fails the test for me with the same output as above...

**Comment by TS53** [comment]
No. It works now. Why is this not done by default? It is only one test difference...

**Comment by LaurenzV** [comment]
> I think the biggest font related change in 0.12.0 was the new https://github.com/typst/typst/pull/4373. Maybe it is related to the problem.

It could be related to this, but it could also be because the default font was changed: https://github.com/typst/typst/pull/4969

> No. It works now. Why is this not done by default? It is only one test difference...

Because exporting to PDF-A2b by default might not be desirable, as it imposes other restrictions as well. It's just that in this simple case, there happens to only be a single failure.

**Comment by TS53** [comment]
The example document also has the NewCMMath-Book font and it also disappears. So I think it is rather the font subsetting which probably effects both.

**Comment by TS53** [comment]
It uses `<!-- Created by pdf2htmlEX (https://github.com/pdf2htmlEX/pdf2htmlEX) -->` for converting pdf to html.

**Comment by LaurenzV** [comment]
> The browsers reject these converted woff fonts:

This makes total sense though. In OpenType, there are two types of fonts: TTF-flavored fonts and CFF-flavored fonts. When embedding a TTF-flavored font in PDF, you embed the _whole font_ into the PDF, while for CFF-flavored fonts, you only embed the actual CFF font. So if you try to convert the embedded CFF font to WOFF, this won't work, unless you synthesize the values for the remaining tables.

In 0.11, the default font was a TTF font, while the default math font was a CFF font.
In 0.12, both, the default font and the default math fonts are CFF fonts. So I presume this is why we are seeing this issue, the tool can't correctly deal with CFF fonts. The reason why it might work for other PDF producers is that they don't use CFF fonts by default.

For what it's worth, I tried converting the 0.12 file with ghostscript/Acrobat, and I still get a blank page when uploading it. So I'm afraid there isn't a lot we can do about this. The only workaround is to use a TTF font.

**Comment by TS53** [comment]
Do you know how to use a TTF math font? I tried to convert `NewCMMath-Book.otf` to TTF using FontLab which seem to work, but typst complains it is not a math font.

**Comment by LaurenzV** [comment]
No idea, but from the look of it Typst expects the math font to have a `math` table, maybe it somehow gets lost during conversion.

**Comment by TS53** [comment]
You're probably right: it works with STIX Two font family, which [ships](https://github.com/stipub/stixfonts/tree/master/fonts/static_ttf) an official ttf version.

```typst
#set text(font: "STIX Two Text")
#show math.equation: set text(font: "STIX Two Math")

$ (3x + y) / 7 &= 9 && "given" \
  3x + y &= 63 & "multiply by 7" \
  3x &= 63 - y && "subtract y" \
  x &= 21 - y/3 & "divide by 3" $
```

![Stix Math](https://github.com/user-attachments/assets/98fa19bc-4d09-48f6-9b66-e02d1f436e12)

If the resulting file works, then this issue can get closed I think, because a workaround would exist then by either using ttf fonts or by waiting until pdf2htmlEX gets fixed to support CFF fonts.

[stix fonts.pdf](https://github.com/user-attachments/files/17688456/stix.fonts.pdf)

**Comment by JeppeKlitgaard** [comment]
Since I figure lots more will find this issue and want a quick solution, the situation current seems to be that tools using `pdf2htmlEX` cannot use CFF fonts and as a result one would have to use TTF fonts.

As of:
- `typst`: 0.13.1
- `pdf2htmlEX`: 0.18.8.rc1

Works:
- Using a TTF font (such as STIX Two: https://github.com/stipub/stixfonts/tree/master/fonts/static_ttf)

Does not work:
- Postprocessing with `pdftocairo -pdf`
- Using A2-b standard output (`typst compile --pdf-standard a-2b`)
