### ISSUE TITLE
Throw error when there are no fonts.

### ISSUE THREAD

**Issue by jbirnick** [typst/typst#5399]
I was using the `typst` crate in Rust. I created my own `World`, and for the fonts I embedded the standard fonts from the `typst-assets` crate. However, somehow my test files which contained some simple markup were not rendering. It would just layout an empty page. The weird thing, though, was that there were no errors or warnings, and all Rust functions returned with `Ok(...)`. After a long time of debugging, I found the problem:

![image](https://github.com/user-attachments/assets/67c14adc-7d0f-4512-8336-9fe5962da966)

When I thought I was loading the embedded fonts I did in fact not load anything, because I didn't activate the `fonts` feature of `typst-assets`. I had an empty font book.

So I suggest:
1. Throw an error when the font book is empty. (Or when the requested font, in this case "Libertinus Serif", is not present in the font book.)
2. Hide the whole `fonts()` function in `typst-assets` under the respective feature flag. That I was able to call `typst_assets::fonts()` gave me a false sense of security. It took me a long time until I was looking at the docs of that function which told me it returns an empty iterator if the feature is disabled.. (why is it implemented that way?)

**Comment by laurmaedje** [comment]
I must say that I'm also not a fan of it giving empty fonts. It was added here: https://github.com/typst/typst-assets/pull/1

@Enter-tainer what was again the reason for this PR?

**Comment by laurmaedje** [comment]
Beyond that, I think this falls under warnings for font fallback / no fonts (https://github.com/typst/typst/issues/5137).

**Comment by Enter-tainer** [comment]
i cannot remember exactly why. typst
 preview(or tinymist, reflexo) can work without embeded fonts. by moving cfg into typst-assets, i can simply flip the feature flag in typst-assets without adding extra code in my side

**Comment by jbirnick** [comment]
Hmm but this is moving _behavior_ to `Cargo.toml`, I don't think that's how features are intended to be used. If you really really need it, maybe a second explicit feature called `empty_fonts` would be a solution?

**Comment by Enter-tainer** [comment]
i'm not sure about this. if current behavior is causing problem, we may revert the pr in typst-assets to restore the original behavior

**Comment by jbirnick** [comment]
Yeah let's do that then.

**Comment by laurmaedje** [comment]
We can revert the thing in typst-assets. I'll close this issue in favor of #5137.
