### ISSUE TITLE
Incorrect filling of svg (v12.0.0)

### ISSUE THREAD

**Issue by Vidrochka** [typst/typst#5400]
### Description

As of version 12.0.0, svg has a default white fill for pages.
If there is 1 page, everything is drawn correctly.
If there are more than 1 page, the first page is filled in white, covering all data, the rest of the pages have a transparent background and everything is visible.

Example of a broken template:

```
#set page(
    paper: "a4"
)

Some text 1

#pagebreak()

Some text 2
```

After generating the svg, the first page will be blank

A solution for those who will face the same problem:

```
#set page(
    paper: "a4",
    fill: none
)

Some text 1

#pagebreak()

Some text 2
```

It is enough to make the first page transparent and all data will be visible.

Something was probably broken in the 12.0.0 release when adding the default white color for svg backgrounds.

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by EpicEricEE** [comment]
Can't reproduce this on windows, on WSL, or on the web app.

**Comment by laurmaedje** [comment]
IIUC this issue is about SVG _export,_ not SVG images, so probably not related.
