### ISSUE TITLE
Kerning of subscripts seems to be inconsistent when using STIX Two Math

### ISSUE THREAD

**Issue by tonico** [typst/typst#5406]
### Description

The subscript kerning of $V_i$ appears too large compared to other subscripts:
```
#show math.equation: set text(font: "STIX Two Math")
$V_i, V_1, V_a, V_alpha$
```

![image](https://github.com/user-attachments/assets/a959a558-3fc4-4c59-8f40-6ae51d8eb62d)

For comparison, here is the output from lualatex with unicode-math and `\setmathfont{STIX Two Math}`:
![image](https://github.com/user-attachments/assets/924b2c8d-4478-4366-8c89-678acbbed97f)

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by mkorje** [comment]
This actually isn't a bug in Typst, but in LuaTeX and the font. As noted in https://github.com/latex3/unicode-math/issues/592#issuecomment-2041224153, LuaTex follows the letter of the spec which has a bug in it. This gives the better result here, despite the font data being bad. Typst matches XeTeX's and Microsoft's implementation.

**Comment by khaledhosny** [comment]
See also https://github.com/stipub/stixfonts/issues/272

**Comment by tonico** [comment]
> See also [stipub/stixfonts#272](https://github.com/stipub/stixfonts/issues/272)

The subscripts in that issue look good to me. Hopefully there will be a new STIX release soon. I'm closing this issue as it's not a bug in Typst.

**Comment by tshort** [comment]
A workaround is to add a hidden superscript. Somehow that fixes the subscript spacing:

```typ
#show math.equation: set text(font: "STIX Two Math")
$V_a\ V_b^#hide[,]\ V_c$
```

On Discord, @EpicEricEE suggested using the quick-maths package to replace the problem combinations with versions that fix the offset:

```typ
#import "@preview/quick-maths:0.2.0": shorthands
#show: shorthands.with(
  ($N_i$, $N_(#h(-1.5pt) i)$),
  ...
)
...
```
