### ISSUE TITLE
Using linebreak in a linebreak show rule crashes the compiler

### ISSUE THREAD

**Issue by platformer** [typst/typst#541]
If we have this show rule:

```
#show linebreak: linebreak()
```

or

```
#show linebreak: [\ ]
```

the file compiles successfully. But if the show rule is later invoked:

```
a\
b
```

the compiler will crash. Note that avoiding an explicit call to `linebreak` in the show rule still works:

```
#show linebreak: it => it

a\
b
```

The above compiles successfully.

**Comment by laurmaedje** [comment]
Duplicate of #229.
