### ISSUE TITLE
math.mat: Support more complex ellipse patterns in matrices

### ISSUE THREAD

**Issue by infinitymdm** [typst/typst#5410]
### Description

Provide syntax for ellipse patterns in matrices that span multiple rows/columns. Consider for example this strictly diagonally dominant matrix from a numerical analysis text: 
![image](https://github.com/user-attachments/assets/a07a31b1-60c3-4778-a33f-00daed3d02ee)

To my knowledge, there is no straightforward way to replicate this using current typst syntax. See [this discussion on the forum](https://forum.typst.app/t/how-can-i-draw-strictly-diagonally-dominant-matrices-with-ellipses/1675) for an attempted (and very inelegant) solution.

### Use Case

This is useful for anyone doing work with patterned matrices. Anyone working in linear algebra (or with applications of linear algebra, as in my use case) should benefit from this.

**Comment by Enivex** [comment]
Yeah this is something I'd expect a package to do. Especially because the standard way to write matrices like this would only use the vertical, horizontal and diagonal dot symbols.

**Comment by infinitymdm** [comment]
> the standard way to write matrices like this would only use the vertical, horizontal and diagonal dot symbols

That was the first thing I tried. Here's what that looks like: 
![image](https://github.com/user-attachments/assets/3c1a9967-ec77-4a35-9b19-486dc2e68e89)

Since the column widths vary, the resulting matrix doesn't read well. It's not clear where the `dots.down` are supposed to start and end. Admittedly this is a pretty niche use case though.

> I don't think this is a common enough construct to warrant custom syntax. This should already be possible at a library level, and not in the core language itself.

> this is something I'd expect a package to do.

This makes sense to me. For now I have a good enough result using fletcher (thanks @wrzian!). Perhaps I'll contribute a package adapting this approach for generic matrices if I have the time to put it together. Feel free to close.
