### ISSUE TITLE
Integral lower limit is a bit lower than in LaTeX

### ISSUE THREAD

**Issue by yanliu6378** [typst/typst#5417]
LaTeX:
![LaTeX](https://github.com/user-attachments/assets/33a2d5a8-b614-4caa-bae2-0ff53fb989c7)

Typst:
![Typst](https://github.com/user-attachments/assets/ff303373-1475-4657-9fd5-09b2c3bcb2f3)

typst 0.12.0 (6b636167)
Compiled with `--ignore-system-fonts`

**Comment by yanliu6378** [comment]
In the picture above, I used the following:

```tex
%! TeX program = xelatex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{unicode-math}

\begin{document}
  \[ \int_{-\infty}^\infty \] 
\end{document}
```

The output I see with this is exactly the same as what I see with preambles of conferences. (Compiling with pdflatex without `unicode-math` doesn't affect the output enough for me to notice.)

Adding `\setmathfont{NewComputerModernMath}` (or any other font) doesn't affect the relative alignment/positioning of the lower limit and the integral sign.

Typst's lower limit is visibly lower and looks off:

```typst
#set text(font: "New Computer Modern")
$ integral_(-oo)^oo $ 
```

The first line is as per the 'How do I get the "LaTeX look?"' section of the [Guide for LaTeX users](https://typst.app/docs/guides/guide-for-latex-users/).

**Comment by Enivex** [comment]
Typst closely matches the output from lualatex (which is the official successor to pdflatex, not xelatex):

![image](https://github.com/user-attachments/assets/6d7287c1-f247-47e5-964d-3c0ceb17d574)

So if the output is wrong, we're in good company at least. I'll close the issue.

**Comment by mkorje** [comment]
I'll try figure out why XeTeX and LuaTeX produce different results.
