### ISSUE TITLE
Text in math mode has higher weight than the rest of the document with New Computer Modern

### ISSUE THREAD

**Issue by yanliu6378** [typst/typst#5418]
```typst
#set text(font: "New Computer Modern")
The quick brown fox jumps over the lazy dog. \
$"The quick brown fox jumps over the lazy dog."$
```

![image](https://github.com/user-attachments/assets/81e7e01e-3788-48f0-8ecb-dfab4f8a2c3e)

typst 0.12.0 (6b636167)
Compiled with `--ignore-system-fonts`

**Comment by Enivex** [comment]
The reason is that the math font has a higher weight by default to match the default text font better, combined with https://github.com/typst/typst/issues/366
