### ISSUE TITLE
Multi-line overbraces push annotated terms out of alignment with equation

### ISSUE THREAD

**Issue by miles-1** [typst/typst#5426]
### Description

2+ line annotations push the math content down, out of line from the rest of the equation. Example:

```typ
$ S = overbrace(beta (alpha) S I, "one line") - overbrace(mu (N), "two" \  "line") $
```

The `µ(N)` term is out of line with the rest of the equation. This does not happen in the reverse direction with underbraces:

```typ
$ S = underbrace(beta (alpha) S I, "one line") - underbrace(mu (N), "two" \  "line") $
```

I asked about this in the [forum](https://forum.typst.app/t/how-to-avoid-pushing-down-math-content-with-multi-line-overbrace/1740) and got a fix to this behavior, but I suspect this is not intended behavior.

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
Probably not intentional, but this is also abuse of inline math

**Comment by miles-1** [comment]
Sorry, meant to have it as block. I edited my question.

**Comment by Enivex** [comment]
Here's a slightly less hacky workaround

(I've also used the text font for text)

```
#let mt = text.with(font: "Libertinus Serif")
$ S = overbrace(beta (alpha) S I, #mt[one line]) - overbrace(mu (N), inline(vec(delim: #none,#mt[two],#mt[lines]))) $
```

![image](https://github.com/user-attachments/assets/8d58c858-099a-4270-a624-6d6c38ad763d)
