### ISSUE TITLE
Non-deprecated way to reference the current location without context

### ISSUE THREAD

**Issue by instanceofme** [typst/typst#5430]
### Description

Using `locate(callback: function)` in a custom style raises a deprecation warning, suggesting to use `context` instead. But I am not sure this is fully equivalent, as `locate` _can_ resolve the current location for the ongoing call, while context seems to defer resolution to the ultimate layout location.

### Use Case

In a situation like #1356 where you have an unlocatable element, you may want to use the current position right after inserting it, e.g. to update a state.

```typ
#let myCustomStyle(
  body
) = {
  // ...

  let pState = state("p", none)
  locate(loc => {
    pState.update(_ => loc.position())
  })
  show list: it => {
    context {
      if pState.at(here()) == here().position() {
        v(0.5em)
      }
    }
    it
  }

  body
}
```

But I am not sure I can do that with context?
- Using `context` in the state value forces its type to content
- Using `context { pState.update }` seems to delay its execution until e.g. the list is inserted, which defeats the purpose

Maybe the ability to access different contexts, as suggested in #3930, would do? In which case, feel free to close as duplicate.

**Comment by laurmaedje** [comment]
context should have all the power of locate. generally `locate(loc => ...)` is more or less equivalent to `context { let loc = here(); .. }`.

generating state updates in context is somewhat discouraged as it can lead to many layout iterations but it should work and do the same as locate. the two are almost the same in how they work internally. 

the only difference might be where exactly you fetch `here()`. if you do it nested in another context it might resolve differently in which case you can move it into an earlier let binding.

**Comment by instanceofme** [comment]
You are right of course, my mistake was trying to put the `here()` in the state update callback, "earlier binding" was the hint I was missing, thank!

The following works like the `locate` code above:

```typ
context {
  let loc = here()
  pState.update(_ => loc.position())
}
```
