### ISSUE TITLE
String length is misscalculated for non english characters

### ISSUE THREAD

**Issue by danielFHcode** [typst/typst#5431]
### Description

When writing strings in Hebrew I came across an issue where the length of a string was miscalculated:

```typst
#assert("abcd".len() == 4) // passes
#assert("אבגד".len() == 4) // failes
#assert("אבגד".len() == 8) // passes
```

A similar yet unrelated issue came up when trying to access the second character in a 4-character Hebrew string:

```typst
#"abcd".at(1) // passes
#"אבגד".at(1) // failies
#"אבגד".at(0) // passes
```

When I tested Arabic strings the same issue accured, and I assume other languages with non-Latin characters also suffer.

### Reproduction URL

https://typst.app/project/rSBZiZo5emMNueaRpXSIac

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
This is not a bug. The length function specifically gives you the number of bytes, and characters not in ASCII need more than one byte to encode.

**Comment by danielFHcode** [comment]
> This is not a bug. The length function specifically gives you the number of bytes, and characters not in ASCII need more than one byte to encode.
> 
> Similarly, at() uses byte indices.
> 
> What you actually should use is .clusters() or .codepoints() depending on what you want to do.

Hue, I just looked at the documentation and it seams you're right, sorry for the inconvenience.
