### ISSUE TITLE
Document the result of `string.split("")`

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#5443]
### Description

![image](https://github.com/user-attachments/assets/45c164ab-853f-4e9a-9d77-ee4fdb5523c9)

Since there is a difference between clusters and bytes and Unicode code points, it would be great if the docs says how exactly it would split the string with an empty delimiter.

**Comment by Enivex** [comment]
I'm confused. What ambiguity is there here exactly?

**Comment by PgBiel** [comment]
> I'm confused. What ambiguity is there here exactly?

In theory, `split("")` would return all "characters" of a string, but that can be bytes, codepoints or clusters. It's not very obvious indeed.

Typst uses Rust's `str::split`:

https://github.com/typst/typst/blob/5c37a1cfea2a08b08f4af34ba867748fd90c687e/crates/typst-library/src/foundations/str.rs#L579-L594

Which says in the docs[^1] that using `split("")` returns a list of _characters_, as defined by the `char` type. The `char` type, in turn, is defined[^2] as a "Unicode scalar value"[^3], which is basically any valid codepoint. So it seems to split based in codepoints.

The same seems to apply for `split(regex(""))`: https://docs.rs/regex/latest/regex/struct.Regex.html#method.split

So we could just explicitly document this.

[^1]: https://doc.rust-lang.org/std/primitive.str.html#method.split
[^2]: https://doc.rust-lang.org/std/primitive.char.html
[^3]: https://www.unicode.org/glossary/#unicode_scalar_value

**Comment by Enivex** [comment]
I should avoid commenting right after I wake up, because I think we were talking about splitting the actual empty string itself @PgBiel 😂
