### ISSUE TITLE
string type cannot tell a difference between "\n" and real newline

### ISSUE THREAD

**Issue by bigwatergun** [typst/typst#5460]
### Description

as the picture tells
![图片](https://github.com/user-attachments/assets/34262a56-671f-4f2c-8c49-d780b9c699db)
![图片](https://github.com/user-attachments/assets/2bfa73e2-dfb3-4fc1-8a84-9de9fbce31bd)

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
This is intentional. If you have questions please see the Discord or forun.
