### ISSUE TITLE
Panic on syntax highlighted raw in RTL text

### ISSUE THREAD

**Issue by A-Walrus** [typst/typst#5490]
### Description

When syntax highlighted code (LTR), within RTL text, crosses into another line.

Compiler panics with error:
```
thread '<unnamed>' panicked at crates/typst/src/layout/inline/shaping.rs:412:30:
byte index 1 is not a char boundary; it is inside '\u{202a}' (bytes 0..3) of `‪elif‬`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Git bisected it to 0ef672c347f368325313c8bccc4f70e3f1016b0a (#4497).**

### Reproduction URL

https://typst.app/project/rVcMHhZIBR4OCejDsxtzeb

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Minimal reproducer based on the link:

```typ
#set text(lang: "he")
#set raw(lang: "python")
#set page(width: 300pt)

- בדיקה האם מספר מתחלק במספר אחר. לדוגמה `if a % 2 == 0`
```

Commenting any particular line makes it not crash.

**Comment by PgBiel** [comment]
(By the way: not sure if you're using `#show: rest => columns(2, rest)` in your document, but since 0.12 you should use `#set page(columns: 2)` now, together with `place(top, float: true, scope: "parent")[stuff]` for page-wide floats for e.g. the title at the top the document.)

**Comment by wznmickey** [comment]
Seem that in `reorder` in `line.rs`, `let (levels, runs) = bidi.visual_runs(para, range.clone());` will return the range which would split one three byte unicode.

I am not quite familiar with bidi but I think `bidi.visual_runs`  would return range based on unicode rather than types. This problem may be caused due to upstream package. (I also checked `bidi.text` and it is the same as the string we used in displaying ).

**Comment by laurmaedje** [comment]
This seem to indeed be an upstream bug. Here is a reproduction:

```rust
use unicode_bidi::Level;

fn main() {
    let s = "בדיקה האם מספר מתחלק במספר אחר. לדוגמה \u{202a}if\u{202c}\u{202a} \u{202c}\u{202a}a\u{202c}\u{202a} \u{202c}\u{202a}%\u{202c}\u{202a} \u{202c}\u{202a}2\u{202c}\u{202a} \u{202c}\u{202a}==\u{202c}\u{202a} \u{202c}\u{202a}0\u{202c}";

    let bidi = unicode_bidi::BidiInfo::new(s, Some(Level::rtl()));
    let par = &bidi.paragraphs[0];

    let (_, runs) = bidi.visual_runs(par, 124..139);

    for run in runs {
        let _ = &s[run];
    }
}
```

The only reason why this is a regression is because we reorder at a different stage to increase correctness, triggering the code path for lines that don't end up being part of the output.

**Comment by laurmaedje** [comment]
I closed https://github.com/typst/typst/issues/5276 in favor of this, so a PR for this should ensure that this snippet also works ok:
```typ
#table(
  columns: (1fr, 1fr),
  [#lorem(25)],
  [
    #text(lang: "ar")[مجرد نص مؤقت لأغراض العرض التوضيحي. ]
    #text(lang: "ar")[سلام] // <--- Problematic part
  ],
)
```

**Comment by wznmickey** [comment]
Is it possible to use use https://docs.rs/unicode-bidi/latest/unicode_bidi/struct.BidiInfo.html#method.reordered_levels_per_char instead?

**Comment by laurmaedje** [comment]
I don't know. Before going there, I'll open a bug on unicode-bidi with a minimized reproduction.
