### ISSUE TITLE
it will result in 0 when measure a scaled image 

### ISSUE THREAD

**Issue by rinmyo** [typst/typst#5493]
### Description

As titled. .svg and .png files are confirmed

![QQ_1732882063031](https://github.com/user-attachments/assets/b2ac20a7-4ae0-4838-9732-5783d690b2de)

### Reproduction URL

https://typst.app/project/rAswOu88oYAcaErp7fCxPY

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Measurement happens in an infinite space. 100% of infinite is not well defined, so we default to 0pt. You can decide in which space the image shall be measured by providing the `width` and `height` arguments to `measure`. You can obtain these from `layout(size => ..)`. It's a bit of boilerplate (maybe we can improve that in the future) but in principle working as intended.

**Comment by LaurenzV** [comment]
Perhaps there could be a warning in case that happens?

**Comment by laurmaedje** [comment]
You mean whenever a relative size collapses to 0 because of infinite? Might be possible.
