### ISSUE TITLE
Compiler crash in math mode

### ISSUE THREAD

**Issue by qguv** [typst/typst#5494]
### Description

The following code crashes Typst 0.12.0: 

    $or med #h(1em)$ t

### Reproduction URL

https://typst.app/project/rh5mzYlxjD5jiMcRXcHlba

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Duplicate of https://github.com/typst/typst/issues/5253
