### ISSUE TITLE
Impossibly large footnotes leading to seemingly infinite execution

### ISSUE THREAD

**Issue by PgBiel** [typst/typst#5496]
### Description

With the following document:

```js
#set page(width: 400pt, height: 180pt)

#footnote(text(size: 170pt)[a] * 100)
```

The compiler will keep compiling seemingly forever (until it runs out of memory). Happens on the released 0.12 version as well as on main (89d96c62).

I believe this is related to https://github.com/typst/typst/issues/5354. PR https://github.com/typst/typst/pull/5364 fixed that particular case (where the footnote is fully empty, so it would never _not_ be empty in a certain page). But it doesn't seem to be sufficient here, as there is _always_ a non-empty frame since `line + separator + clearance` is larger than the whole page (180pt), triggering the line to always move to the next page since it never fits, so Typst keeps trying to migrate the footnote to the next page forever. (Note that replacing `170pt` with a smaller value, such as 120pt, compiles fine.)

I can confirm this is a 0.12 regression.

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by wznmickey** [comment]
Yes. The previous solution is just a "hacky" way. I am wondering whether we can save the frame last time and compare with the input this time. If they are the same, then this program will loop forever. I am not familiar with the frame generation so I am not sure what could be used to identify whether a frame is the same as another frame.
