### ISSUE TITLE
links parsing fails

### ISSUE THREAD

**Issue by palainp** [typst/typst#550]
Hi, I currently have an issue with links (I might missuse typst so), in this example the first link is correctly parsed, but the next two give shortened urls (to the dash) :
```
#show link: underline

#link("https://domain.name/a-page.html")

https://domain.name/a-page.html

[text](https://domain.name/a-page.html)
```
If that's a real issue and you have no time to spend on that, I might be able to solve this issue if someone could give me some hints on how to start diving into the code :)

**Comment by LaurenzV** [comment]
I think the issue is just that URL parsing is very complex, so the automatic detection of URLs was written conservatively to avoid false positives. See [here](https://github.com/typst/typst/pull/379). But since you can always explicitly use #link, I don't think it's a big deal.

**Comment by palainp** [comment]
That's right, sorry for missing that issue. I'll continue with #link then :)
