### ISSUE TITLE
Placement of vector inside of a bracketed fraction leaves large white space

### ISSUE THREAD

**Issue by Jarrod-Angove** [typst/typst#5500]
### Description

The equation

```typst
$ K_(i j) = sigma^2 exp(- (norm(vec(a_i - a_j, b_i - b_j))_2^2)/(2 l^2)) $
```

Produces
![image](https://github.com/user-attachments/assets/bb8aead2-1e35-4ca8-8bd7-78102d75d2bf)

Which has considerably more white space in the denominator than I expected. I'm not sure if this is expected behaviour, so I'm opening this just to let y'all know. I didn't see any other issues related to this, so I apologize if I missed something that's already open. 

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enter-tainer** [comment]
$$

K_{ij} = \sigma^{2}\exp\left( - \frac{\left\| \begin{pmatrix}
a_{i} - a_{j} \\
b_{i} - b_{j}
\end{pmatrix} \right\|_{2}^{2}}{2l^{2}}\right)
$$

**Comment by wrzian** [comment]
This is just an idea, but you could probably use a contextual function and a show rule on `frac` to measure fractions and check if their size is too lopsided, then use `place(dy: _)` to shift them down. Then a show rule on `lr` could check for this (check if the `lr` contains state??) and resize to match.

**Comment by Enivex** [comment]
You may not like it, but it's not a bug. It's an inevitable consequence of typesetting convention.

I recommend writing 1/(2l) in front instead so your fraction isn't so unbalanced.
