### ISSUE TITLE
Proposal: Vi key bindings for the official website's online editor

### ISSUE THREAD

**Issue by glyh** [typst/typst#551]
As title. This is an important QoL feature for many of us.

**Comment by laurmaedje** [comment]
Are vi and vim keybinds the same? If so, this is a duplicate of #250.

**Comment by glyh** [comment]
Yeah, basically. Sorry for the duplicate.

**Comment by reknih** [comment]
A vim mode is now available. You can click the cogwheel icon in the sidebar and check the checkbox or enable it in the edit menu. Please open new issues if you are missing any commands!
