### ISSUE TITLE
Offline, locally hosted documentation

### ISSUE THREAD

**Issue by patrick-nicodemus** [typst/typst#5511]
### Description

There should be a simple, convenient way to access the documentation offline. 
Right now it seems you have to clone the repository and build the documentation locally. 
Possibilities:
- The user can download a pdf from typst.app/docs 
-  The user can download the whole typst.app/docs collection of html pages in a zip file
- `cargo install typst` could build the documentation as part of the install process, and store it in a cache, and then the UI could be `typst --docs` which would launch a web browser pointing to the local documentation.

### Use Case

Writers have shown they are willing to go to great lengths to disconnect from the internet in order to be productive, e.g. https://getfreewrite.com/. Having to access the docs online makes that more difficult.

**Comment by Marcono1234** [comment]
> * The user can download a pdf from typst.app/docs

For future reference, that was actually implemented: #8138
