### ISSUE TITLE
Non-decimal `Numeric` literal gets set to zero

### ISSUE THREAD

**Issue by T0mstone** [typst/typst#5519]
### Description

When specifying e.g. a length in a non-decimal base (e.g. binary), it gets set to zero instead.

Example:
```typst
#set page(width: auto, height: auto, margin: 1pt)
First#h(0b100000pt)Second\
First#h(32pt)Second
```
![output](https://github.com/user-attachments/assets/c5f0b8da-7d0a-45b2-b9dc-c0f2c4a36b6c)

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by wznmickey** [comment]
In current code (ast.rs impl Numeric<'_>), the number is directly parsed by rust, which is different from what we did for Int value.

In document, it seems that we did not write in detail what format the number part should follow.

https://typst.app/docs/reference/layout/fraction/

**Comment by laurmaedje** [comment]
After a bit of consideration, I think I'd rather disallow this than handle it. It feels odd to allow it for whole numerics, but not float numerics, but it's also odd to support it for floats.

**Comment by wznmickey** [comment]
Then maybe we need to report an error rather than just use 0.

**Comment by laurmaedje** [comment]
Yeah

**Comment by wznmickey** [comment]
During changing the code, we found that we also support exponent, which I think is not write in the document, should we support something like `1e2p`t?

**Comment by laurmaedje** [comment]
I think that's less odd and more useful and we can keep it

**Comment by wznmickey** [comment]
Changed in https://github.com/typst/typst/pull/5548.
By the way is it necessary to modify the document to make it more clear?

**Comment by laurmaedje** [comment]
I think the docs are fine tbh. This level of detail is more something for a specification and adding too much of that kind of information would drown out more relevant things. What the docs are truly lacking is introductory and guide-level content.
