### ISSUE TITLE
math: hat accent on bold H renders incorrectly

### ISSUE THREAD

**Issue by cgahr** [typst/typst#5520]
### Description

In math mode, the `hat` accent does not render correctly for `bold(H)` letters, it is too wide. In comparison, `hat(bold(A))` renders correctly:
![image](https://github.com/user-attachments/assets/1ce7446e-711e-4f1f-9dbf-5cc6407ec97d)
`hat(B)` and all variations of the `A` letter render correctly.

The image was created using the following code:
```
$
  "hat(H):" & hat(H) \
  "bold(hat(H)):" & bold(hat(H)) \
  "hat(bold(H)):" & hat(bold(H))
$
```

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
This is intentional from the font because the the bold H is so much wider.

cc: @mkorje

**Comment by cgahr** [comment]
Interesting. Especially in comparison to $hat(H)$, it looks far too wide..

Thank you!

**Comment by Enivex** [comment]
If you truly want to force it to not scale, you can do this
```
$
   hat(bold(H),size: #1em)
$
```

Of course you'd want a shorthand if you use this often (or `set` if always).

**Comment by cgahr** [comment]
Perfect, thanks!

**Comment by ultimatile** [comment]
Could you please tell me the correct way to write the `set` for `hat`?

```typst
#set math.accent(size:1em)
```

works because [`accent`](https://typst.app/docs/reference/math/accent/) is an element function. However, 

```typst
#set math.hat(size:1em)
```

raises an error `only element functions can be used in set rules` , and does not work.

**Comment by laurmaedje** [comment]
@ultimatile It's a bit brittle and might break in the future, but this works:

```typ
#show math.accent.where(accent: "\u{302}"): set math.accent(size: 2em)
```
[U+302](https://www.compart.com/en/unicode/U+0302) is the combining circumflex. Basically the "resolved" accent version of `hat`.

**Comment by ultimatile** [comment]
@laurmaedje Your solution worked well. I really appreciate your support.
