### ISSUE TITLE
Current font does not support math with Libertinus Math v7.051

### ISSUE THREAD

**Issue by retato-snu** [typst/typst#5535]
### Description

When using Libertinus Math [Libertinus Fonts v7.051](https://github.com/alerque/libertinus/releases/tag/v7.051), I am getting a compile error: current font does not support math

```
#show math.equation: set text(
  font: (
    "Libertinus Math",
  ),
)
$f(x)$
```
There is no problem with [v7.040](https://github.com/alerque/libertinus/releases/tag/v7.040).

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by alerque** [comment]
I am the maintainer of the Libertinus family of fonts. I am not able to confirm this report. I tried your test file and also mocked up the same test in SILE where it is easy to get it to spit out the exact version of the font used at typesetting time:

```console
$ cat math-typst.typ
#show math.equation: set text(
  font: (
    "Libertinus Math",
  ),
)
$f(x)$

$ typst compile math-typst.typ
typst compile math-typst.typ

$ cat cat math-sile.xml
cat: cat: No such file or directory
<sile>
<use module="packages.math"/>
<math>
f(x)
</math>
</sile>

$ sile -d versions math-sile.xml
sile -d versions math-sile.xml
SILE v0.15.7 (LuaJIT 2.1.1731486438) [Rust]
<math-sile.xml> as xml
[1]
Harfbuzz version: 10.1.0
Shapers enabled: graphite2, ot, fallback
ICU support enabled

Fonts used:
/usr/share/fonts/libertinus/LibertinusMath-Regular.otf:0        Version 7.051;RELEASE
/usr/share/fonts/TTF/GentiumPlus-Regular.ttf:0  Version 6.200

$ fc-list | grep 'Libertinus Math'
/usr/share/fonts/libertinus/LibertinusMath-Regular.otf: Libertinus Math:style=Regular

$ font-v report /usr/share/fonts/libertinus/LibertinusMath-Regular.otf

/usr/share/fonts/libertinus/LibertinusMath-Regular.otf:
----- name.ID = 5:
Version 7.051;RELEASE
----- head.fontRevision:
7.051
```

**Comment by retato-snu** [comment]
Reinstalling the font fixed the problem. Sorry for the confusion.

**Comment by cpita-work** [comment]
I'm also having this issue after installing the latest Libertinus fonts (I can't say whether this is a regression or not, this report is for WSL2, I've been using the font last year in macOS without any problem, but it probably was another version).

This is how I installed the font after downloading it from https://github.com/alerque/libertinus/releases:

```
❯ mv Libertinus-7.051/static/TTF/*.ttf ~/.local/share/fonts/

~/win/Downloads
❯ fc-cache -f -v

❯ fc-list | grep -i math
/home/carlos/.local/share/fonts/LibertinusMath-Regular.ttf: Libertinus Math:style=Regular
```

And this is the output I get compiling @alerque example:

```
error: current font does not support math
  ┌─ ../../../../../../tmp/math.typ:6:0
  │
6 │ $f(x)$
  │ ^^^^^^
```

**Comment by cpita-work** [comment]
I realized that installing the otf version works fine, the issue happens with ttf only.

**Comment by Enivex** [comment]
Relevant https://github.com/alerque/libertinus/issues/571
