### ISSUE TITLE
一份不完全的中文文档/Basic Chinese Typst documentation

### ISSUE THREAD

**Issue by Zuttergutao** [typst/typst#554]
我正在使用typst的写一份typst中文版教程(手册翻译版)，如下是文档的[仓库地址](https://github.com/Zuttergutao/Typstdocs-Zh-CN-)。
目前，我并没有将英文手册完全翻译以及还有很多未完成部分，我尽可能的在中文文档中贴出了代码与显示效果图片。
同时这只是预览版，全文并没有很好的组织和排版（至少对我来说）

Typst is god！！！
I am writing a Chinese version tutorial (manual translation version) using Typst, and the following is [the repo for the document](https://github.com/Zuttergutao/Typstdocs-Zh-CN-)
At present, I have not fully translated the English manual because I believe that many of them are common sense knowledge. I have tried my best to post the code and display effect images in the documents.
At the same time, this is only a preview version, and the full text is not well organized and typeset (at least for me)

**Comment by dlxdlxdlx** [comment]
Awesome! Can I make some contributions?

**Comment by Zuttergutao** [comment]
> 

of course! I am not familiar with some operations on github, you can download the `typ` in my repository for modification. At present, the organization of this document is not perfect, and more people are expected to cooperate.

**Comment by Freed-Wu** [comment]
@typst [po4a](https://po4a.org/) can be useful for translation, and [transifex](https://explore.transifex.com) will be useful for many people cooperating to translating. <https://explore.transifex.com/python-doc/> is an example. Why not use these tools to provide translation for different languages?

**Comment by Zuttergutao** [comment]
> @typst [po4a](https://po4a.org/) can be useful for translation, and [transifex](https://explore.transifex.com) will be useful for many people cooperating to translating. https://explore.transifex.com/python-doc/ is an example. Why not use these tools to provide translation for different languages?

Thanks. transifex is used for Python and I'm not sure it can be used with Rust.  In addition, this Chinese doc is a record of the process of learning typst.

**Comment by Freed-Wu** [comment]
> transifex is used for Python and I'm not sure it can be used with Rust

python is not only project translated on transifex, see <https://explore.transifex.com/>. Except transifex, there are other website like [crowdin](https://crowdin.com/). And rust uses [pontoon](https://pontoon.rust-lang.org/).
