### ISSUE TITLE
Allow making a single table header out of separate header cells on the same line

### ISSUE THREAD

**Issue by Andrew15-5** [typst/typst#5546]
### Description

This issue is created after discussing https://github.com/typst/typst/issues/5375#issuecomment-2525054510. This extends to grid and footer.

Here is my use case:

```typ
#import table: header
#let column-cells = (
  (
    header[Heading 1],
    [cell 1],
    [cell 2],
    [cell 3],
  ),
  (
    header[Heading 2],
    [cell 1],
    [cell 2],
    [cell 3],
  ),
  (
    header[Heading 3],
    [cell 1],
    [cell 2],
    [cell 3],
  ),
)
#table(
  columns: 3,
  ..array.zip(..column-cells).flatten(),
)
```

![image](https://github.com/user-attachments/assets/28075a8b-088c-4c09-ba28-652143a2d65c)

This should be an equivalent of the compilable variant:

```typ
#import table: header
#let column-cells = (
  (
    [cell 1],
    [cell 2],
    [cell 3],
  ),
  (
    [cell 1],
    [cell 2],
    [cell 3],
  ),
  (
    [cell 1],
    [cell 2],
    [cell 3],
  ),
)
#table(
  columns: 3,
  header[Heading 1][Heading 2][Heading 3],
  ..array.zip(..column-cells).flatten(),
)
```

You can immediately see that by separating the column heading from its cells, it becomes harder to read the table as well as less flexible/maintainable.

I think as long as all header cells are in one line, either way should be fine to do.

AFAIK, you currently can't make a column-wide header, but it's again just a line of cells that together make up a single header. So the only difference is the direction of the header line.

```typ
#import table: header
#table(
  columns: 4,
  header[Heading 1], [cell 1], [cell 2], [cell 3],
  header[Heading 2], [cell 1], [cell 2], [cell 3],
  header[Heading 3], [cell 1], [cell 2], [cell 3],
)
```

### Use Case

Take advantage of accessibility + header set/show rules for tables, defined as column-first (zipped columns) or where header cells are in the same column (instead of row).

**Comment by PgBiel** [comment]
> AFAIK, you currently can't make a column-wide header, but it's again just a line of cells that together make up a single header. So the only difference is the direction of the header line.

Please move this to a separate issue as it's unrelated.

> You can immediately see that by separating the column heading from its cells, it becomes harder to read the table as well as less flexible/maintainable.

I disagree, you seem to be conflating data with presentation. I don't see why you necessarily have to store the styled header together with the cells' contents.

Regardless, this should work:

```typ
#table(
  columns: 4,
  ..array.zip(..column-cells).enumerate().map(((i, row)) => if i == 0 { (table.header(..row),) } else { row }).join()
)

// or (more readable)

#let (hdr, ..rows) = array.zip(..column-cells)

#table(
  columns: 4,
  table.header(..hdr),
  ..rows.flatten()
)
```

**Comment by laurmaedje** [comment]
I agree with @PgBiel that if you really want to have the header names as part of your data, you can just use a bit of array processing to extract it. I'm leaning towards closing this.

Semantically, I think your proposal doesn't make that much sense, since you enter three header elements even though there is just one header conceptually

**Comment by Andrew15-5** [comment]
The `..array.zip(..column-cells).enumerate().map(((i, row)) => if i == 0 { (table.header(..row),) } else { row }).join()` is exactly why I don't want to use this, as it just looks awful. I already thought about doing this.

The `#let (hdr, ..rows) = array.zip(..column-cells)` looks more compelling, but you do have to use a separate line to destruct the parts.

> I disagree, you seem to be conflating data with presentation.

I don't understand this.

> I don't see why you necessarily have to store the styled header together with the cells' contents.

Is "styled" here the keyword? In my case, most cells are also styled (they have `abc` function names attached), so styling the header cell fits in nicely with other cells.

When you have 10+ columns, I doubt anyone would want to separate header cells from the content cells because it will make it that much harder to track which cells refer to which header cell. It's just the most natural way to store cells — the _whole_ column = 1 array (like in my first example).

> if you really want to have the header names as part of your data, you can just use a bit of array processing to extract it.

Again, the issue is because array processing isn't that quick and straightforward as just adding `header` to the appropriate cells. Array processing is a workaround in this case.

> Semantically, I think your proposal doesn't make that much sense, since you enter three header elements even though there is just one header conceptually

This is because I doubt you'll want to add `table.header.part`, otherwise It can be `table.header.part`. What `table.header()` does is converting regular cells into "header cells". And by marking a "cell" as a "header" (`header[cell]`) it becomes a "header cell". So with this logic it makes perfect sense.

---

With this feature, defining table with column-wise arrays will become more intuitive/flexible/easy as the header can be split in the code and merged during compilation. _Simple and elegant_, no need for intermediate variables or crazy array function chaining/processing.

**Comment by laurmaedje** [comment]
> This is because I doubt you'll want to add table.header.part, otherwise It can be table.header.part. 

I indeed don't want `table.header.part`, but that doesn't really change my stance on `table.header` being semantically incorrect for multiple cells. If you'd consider it a modifier for a cell I guess, but it's not: It's an element representing a header.

**Comment by Andrew15-5** [comment]
So, sounds like a cyclic dependency to me. Do you think `table.header-cell` can be a solution? How else can we have "a modifier" for header cells while retaining the current usage for `table.header` element?

**Comment by PgBiel** [comment]
> The #let (hdr, ..rows) = array.zip(..column-cells) looks more compelling, but you do have to use a separate line to destruct the parts.

I feel like that's a very minor inconvenience that could be solved by a function.

> This is because I doubt you'll want to add table.header.part, otherwise It can be table.header.part. What table.header() does is converting regular cells into "header cells". And by marking a "cell" as a "header" (header[cell]) it becomes a "header cell". So with this logic it makes perfect sense.
> ...
> So, sounds like a cyclic dependency to me. Do you think table.header-cell can be a solution? How else can we have "a modifier" for header cells while retaining the current usage for table.header element?

Overall, splitting the header doesn't make much sense to me because it's always contiguous and per-row. A header cell or part would give the wrong impression that you can have one cell be part of the header and right after it one that isn't, which is evidently not the case.

FWIW tablex's API for headers used `header-rows: N`, which specified how many rows from the top were part of the header. But I'd say this is overall a less ergonomic API, since it also hinders the ability of specifying header-specific options without more knobs on `table`, not to mention that it wouldn't make sense if/when features such as #5375 get implemented. So I think the current API is the best we could settle on for the moment.

With regards to how ergonomic it can be to manipulate cells on tables, I think that there are some improvements to be held over the status quo, given, for example, the existing demand for a way to count from the end of the table (see #3697). Overall, I was thinking that a way to "preprocess" the table precisely in the way that the internal code does it, converting cells with `x:, y:` and `colspan / rowspan` into a final array of cells you can more easily manipulate, could be a nice component for packages to build on and generate their own simplified APIs for tables. But that's a topic for another issue.

**Comment by Andrew15-5** [comment]
> I feel like that's a very minor inconvenience that could be solved by a function.

Again, a whole custom function that needs to be added every time you have a case like this, instead of having a built-in way that doesn't make your document more complex. The ease of use is the fundamental thing that Typst excels at.

But the problem with potentially adding (misusing) this header marker/modifier for non-adjacent cells is something I didn't think of. Actually, what will happen if you only add part of the row to the header function right now? Will it error?

I think it's not hard to add a simple check for header cells position, that will give a short explanation that such header cells configuration is invalid (if that's true). This is of course will be mirrored from the docs.

**Comment by PgBiel** [comment]
> > I feel like that's a very minor inconvenience that could be solved by a function.
> 
> Again, a whole custom function that needs to be added every time you have a case like this, instead of having a built-in way that doesn't make your document more complex. The ease of use is the fundamental thing that Typst excels at.

I feel like your use case is already relatively contrived by itself, such that, if you were to provide data in this way, you'd probably have a single function which 1. does the zipping and 2. automatically generates header and remaining rows. So the delta of amount of functions in the document would be zero.

> But the problem with potentially adding (misusing) this header marker/modifier for non-adjacent cells is something I didn't think of. Actually, what will happen if you only add part of the row to the header function right now? Will it error?

If you add the header after a cell, I believe it will error, whereas a cell after the header will be forced into the next row. Though there are some edge cases when using manual cell positioning (see https://github.com/typst/typst/issues/5359) where Typst should be stricter than it currently is.

> I think it's not hard to add a simple check for header cells position, that will give a short explanation that such header cells configuration is invalid (if that's true). This is of course will be mirrored from the docs.

Seems like yet another decision for users to take (use modifiers or table.header), and more stuff to be aware of in general... not sure if I'll want to encourage this.

I think we could do with a package that is a light wrapper over native tables to provide little features people need, to be honest.

**Comment by Andrew15-5** [comment]
> I think we could do with a package that is a light wrapper over native tables to provide little features people need, to be honest.

`tablex-2.0-light` when?

**Comment by laurmaedje** [comment]
It seems like @PgBiel and I are in agreement that this is too specific to be built-in. We may not have convinced you, but at least we tried. :)
