### ISSUE TITLE
No space after #link

### ISSUE THREAD

**Issue by timothy-hister** [typst/typst#5555]
### Description

Is is possible to not have a space immediately after a link function?

Thanks!!!!! Typst is awesome

### Use Case

`#link("www.someurl.com")[A link]Some text`

Output is:

[A link](www.someurl.com) Some text 

But I would like:

[A link](www.someurl.com)Some text

**Comment by Enivex** [comment]
Yes, by adding a semicolon to end code mode. But please don't use issues to ask questions.
