### ISSUE TITLE
SVG rendering different from inkscape

### ISSUE THREAD

**Issue by wenbin-liu** [typst/typst#5556]
### Description

Hello, here I found a svg image rendering differently in typst from inkscape. Some compoent just disappeared in typst output which
definitely can be seen in inkscape  or inkscape export.

But I'm not sure it's a inkscape bug or typst bug. Because Edge/Chrome also failed to render this svg with the same phenomenon

Here I present the svg file and the exported png version by inkscape
![lfsr](https://github.com/user-attachments/assets/0bfca705-adf4-4203-afcc-75a293126bf6)
svg file
![lfsr](https://github.com/user-attachments/assets/8e4067c4-ce2f-46d0-a5eb-a73f714f1a4c)
png exported by inkscape

### Reproduction URL

https://typst.app/project/rXczlSgoImuHuaccSlCeDP

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by LaurenzV** [comment]
If I try to open the SVG in Chrome/Firefox, I get the same issue, so perhaps it's a fault in Inkscape's side.

**Comment by LaurenzV** [comment]
I tried rendering with Chrome, Firefox, Safari, librsvg and they all give the same result as Typst, so I'm afraid this is most likely a bug in Inkscape. :/ You might want to try opening an issue there.

**Comment by doctormo** [comment]
https://gitlab.com/inkscape/inkscape/-/issues/5424#note_2254823227

**Comment by wenbin-liu** [comment]
I think this relates to a vague statement in svg standard, which leads to a different implementation in inkscape and chrome/typst.
See the link given by @doctormo for detail.

**Comment by LaurenzV** [comment]
Interesting, but in any case if it turns out to be a bug, the issue should be opened at https://github.com/linebender/resvg instead of here. But in any case, it would still be best if Inkscape can somehow avoid producing such an SVG in the first place, considering that no one else seems to support it...

**Comment by doctormo** [comment]
Agreed. We're looking at a viewPort patch that might fix the issue.
