### ISSUE TITLE
Constrain placement of figures to sections

### ISSUE THREAD

**Issue by CasVisser** [typst/typst#5558]
### Description

The `auto` option for placement of figures does a pretty good job at picking a good location for figures, but in some cases, e.g. when there are a lot of figures, it happens that figures get pushed quite far from where they are first mentioned. My ideal solution would be a sort of `section-auto` option, which picks a placement automatically, but places the figure in the same top-level section as where it is declared. Another option would be to add a command similar to LaTeX's [floatbarrier](https://tex.stackexchange.com/questions/19766/how-to-control-the-position-of-floating-images).

### Use Case

For example, in the following snippet, the figure would get placed somewhere after the `Introduction` heading, but before the `Methods` heading.
```Typst
= Introduction
#lorem(500)
#figure("example.png", placement: section-auto, caption: [Example.])<fig:example>
#lorem(500)

= Methods
#lorem(500)
```
A work-around is to define a block within each section that holds all content, including the figures, but this does not feel like a good solution as it clutters the code and I'm not sure what side effects it could have.

**Comment by laurmaedje** [comment]
There's [`#place.flush()`](https://typst.app/docs/reference/layout/place/#definitions-flush) which is a float barrier. You can also generate these flush elements in a show rule for a heading level of your choice.

**Comment by PgBiel** [comment]
> but the content can still fill the space if the figure is bottom-aligned.

Sounds like #5124 .

While it makes sense from a certain standpoint that, in theory, the float isn't yet "pending" if we didn't even come across where it would normally be (the bottom), we could consider forcing it to come earlier. Could be more coherent.

**Comment by laurmaedje** [comment]
Ah, didn't remember that issues. So then it's a duplicate.
