### ISSUE TITLE
Pic support

### ISSUE THREAD

**Issue by m-kru** [typst/typst#556]
Does typst provide support for `pic` for drawing pictures directly in the document?

**Comment by m-kru** [comment]
PGF/TikZ is similar, but it is huge. If you are on Linux or *nix, just check `man pic`.
If you are familiar with roff like typsetters pic commands can be directly put into the text.

```
Some text.
.PS
BOX1: box "Name1" at (0 ,5)
BOX2: box "Name2" at (-5 ,10)
arrow from BOX1.e to BOX2.w
.PE
Some text.
```
Pic is relatively small and easy to grasp.

Maybe typst has its own syntax for drawing pictures directly in the document?

**Comment by Enivex** [comment]
At the moment, typst has only rudimentary tools for that

https://typst.app/docs/reference/visualize/

**Comment by laurmaedje** [comment]
Pic support is out of scope for the compiler. Maybe it could be provided by a package.

**Comment by maxcrees** [comment]
I have thought of implementing a PIC package. I've already made a TBL package which is available in the package repository. I think the trouble is PIC is a lot more complex - it might even be Turing complete. CeTZ is a good alternative but not quite the same as PIC of course. But if there is demand for a PIC package or you would like to collaborate on one let me know @m-kru. Perhaps it could be built on top of CeTZ similar to how TBL is built on top of tablex.

**Comment by m-kru** [comment]
@maxcrees I would like to collaborate on, if only I had time ...
