### ISSUE TITLE
Add `lcm` math operator

### ISSUE THREAD

**Issue by shivangp76** [typst/typst#5561]
### Description

Self-explanatory. Thought this would be justified since there is an existing `gcd` math operator. I noticed this pull request but it was closed without explanation: https://github.com/typst/typst/pull/1740

### Use Case

Self-explanatory

**Comment by samuelireson** [comment]
I agree this would be nice for completeness. You can implement this yourself fairly easily using,
```math
\mathrm{LCD}(n,m) = \frac{n \cdot m}{\mathrm{GCD}(n,m)}
```
Maybe you already knew about this!

**Comment by shivangp76** [comment]
See https://github.com/typst/typst/pull/5577#issuecomment-2545464521
