### ISSUE TITLE
Internal error when accessing a missing "label" field of any element

### ISSUE THREAD

**Issue by edgarogh** [typst/typst#5569]
### Description

Accessing the `.label` field of seemingly any element (that doesn't have a label) causes an error that _isn't_ `xxx does not have field "label"`. According to the message itself, it is a bug. Googling the precise message yielded no results, but I hope this isn't a duplicate, it looks almost too simple for me to be the one to discover it.

Minimal example: `[].label`
This gives the following error: `internal error when accessing field "label" in sequence – this is a bug`

You can also try `strong[].label` or `table().label` for more element kinds. Same issue.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
This was actually [discussed on Discord](https://discord.com/channels/1054443721975922748/1088371867913572452/1284193916534521857) and then [fixed in a PR that also did other stuff and was thus closed](https://github.com/typst/typst/pull/4954) but apparently forgotten again then.
