### ISSUE TITLE
Add the `cosec` operator.

### ISSUE THREAD

**Issue by John-Toohey** [typst/typst#5576]
### Description

Add `cosec` alongside the [predefined operators](https://typst.app/docs/reference/math/op#predefined) in maths mode.

### Use Case

At least in the UK, the cosecant function is commonly written as `cosec(x)`. Adding it as a predefined operator seems fairly uncontroversial (the rest of the world keeps using `csc(x)` and is none the wiser) but those in the UK can use `cosec(x)` without having to define it manually.

**Comment by laurmaedje** [comment]
See https://github.com/typst/typst/pull/5577#issuecomment-2545464521
