### ISSUE TITLE
Custom Translations

### ISSUE THREAD

**Issue by Ultrahero** [typst/typst#5578]
### Description

We currently only have translations for fixed elements in typst. This includes quotes, default supplements, and titles for sections, etc.

It would be great if one could define arbitrary translations for languages more easily. 

One could for example have a function that accepts a dictionary with translations: 

```typst
#let custom_translations = ("algorithm": ("en":"algorithm", "de":"Algorithmus", ...))
#set translations(new_translations=custom_translations)
```

and then later call

```typst
#set text(lang:"en")
In English the word is \"#translate("algorithm")\", 
#set text(lang:"de")
whereas in German it is \"#translate("algorithm")\".
```

### Use Case

I came across the usecase where i wanted to define custom kind figures for my definition/theorem boxes, but because i want to compile into multiple languages directly, with the actual text translation being outsourced, i would like to be able to define supplement translations as well.
I don't want to translate those or have to automatically create multiple template files just for that purpose.

When allowing this, making it more accessible cannot be a bad thing. Just having a translation table one can easily hook into would be great. 

If I oversee something very obvious please remind me, but I have not found a working solution. I also do not want to define all the commands in the main file and call context upon every instantiation. 

Kind Regards.

**Comment by flokl** [comment]
Hi @Ultrahero, did you alredy see the Typst package [linguify](https://typst.app/universe/package/linguify). I think that package covers your usecase.

**Comment by Ultrahero** [comment]
basically yes. not sure why i failed to implement a rough version myself.
thank you very much
