### ISSUE TITLE
`document` function is unclear and missing an example

### ISSUE THREAD

**Issue by reknih** [typst/typst#559]
The document function is underdocumented. The docs contain the statement "The main use of this element is to use it in set rules to specify document metadata." This is misleading, as this is currently the *only* use of `document`. Furthermore, the documentation states nowhere that it must be set before any content is inserted, i.e. at the top of a Typst file.

The docs for this function should contain an example clarifying the intended usage.

**Comment by Yasir761** [comment]
I want to give it a try @reknih

**Comment by reknih** [comment]
Perfect! Eagerly awaiting your PR.
