### ISSUE TITLE
Missing modulus `%` operator?

### ISSUE THREAD

**Issue by neuralpain** [typst/typst#5593]
### Description

Is Typst missing the modulus operator in scripting? I looked around in the issues but I couldn't I couldn't find anything specifically related to that.

I ended up creating this modulus function for one of my projects:
```typ
// modulus function to fill in lack of a modulus operator `%` in Typst
#let mod(x) = (x - (int)(x / 2) * 2)
```
It's practical but then I would need to carry it across every project when it would be better built in the compiler.

Maybe I missed something? It's not included in the [Operators list](https://typst.app/docs/reference/scripting/#operators) in the documentation either.

### Use Case

Finding odd and even numbers, complete divisibility in equations, etc. A necessary staple in programming.

**Comment by 7ijme** [comment]
Hey, I had this problem too, but found there actually is a modulo function. It’s just called remainder.

https://typst.app/docs/reference/foundations/calc#functions-rem

**Comment by Enivex** [comment]
Please don't use issues to ask questions

**Comment by neuralpain** [comment]
> Please don't use issues to ask questions
I placed this request in the form of a question. My apologies for the confusion; but I'll assume that there's no intention of implementing this into Typst.

**Comment by Enivex** [comment]
> > Please don't use issues to ask questions
> 
> I placed this request in the form of a question. My apologies for the confusion; but I'll assume that there's no intention of implementing this into Typst.

Not a dedicated syntax, no. But the functionality exists through calc.rem

**Comment by neuralpain** [comment]
Noted. I'll check it out. Thanks
