### ISSUE TITLE
Cannot `typst::trace` in a body of show rules if there is some compile error inside

### ISSUE THREAD

**Issue by Myriad-Dreamin** [typst/typst#5599]
### Description

When I hover on `it` it gives nothing, but it does give values of `it2` on hovering. I guess the result of `typst::trace` should be reverted by some conditions.

```typ
#show regex(":\S+:"): it => it.
:test:

#let f = it2 => it2
#f(['test])
```

### Reproduction URL

https://typst.app/project/rg2rdbIUBbLQHA87vKgYvk

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Tracing on files with syntax errors is best effort. It does attempt eval and [ignores syntax errors initially](https://github.com/typst/typst/blob/db06dbf9763d6c610d1f7a267597ecdad309048a/crates/typst-eval/src/lib.rs#L73), but it bails relatively early, so this is expected. Perhaps, it could go even further, but I wouldn't classify this as a bug.

**Comment by Myriad-Dreamin** [comment]
@laurmaedje Context: I'm improving code completion but it doesn't show any items in the completion list. This is kind of different that we cannot complete in unreachable code, as we could whatever make them reachable. The feature, that we cannot trace in such case, perhaps really affects user experience.

**Comment by laurmaedje** [comment]
It depends a bit on the syntax error whether it can continue. For example in
```typ
#show regex(":\S+:"): it => it
:test:

#
```
you can hover over `it` and see something.

During best-effort eval, we just unwrap_or_default all the AST nodes. In this example, that seems to work out ok enough to proceed to realization. But in your example, probably eval with unwrap_or_default yields an error and no realization occurs.
