### ISSUE TITLE
Chinese dot character must not be broken off its preceding characters

### ISSUE THREAD

**Issue by reknih** [typst/typst#560]
No line break must be inserted between the `。` character and preceding ideographs.

Bug from user feedback.

**Comment by asayers** [comment]
Bug in xi-unicode?  The "。" character is U+3002, UAX#14 considers it to be "XB" (no linebreak before).

**Comment by Fusyong** [comment]
In the Chinese standard, these symbols are forbidden to be placed at the beginning of a line:

```text
。？！．
，、；：
”’）］〕】》〉」』〗｝
—～
·-/／
```
(please note that three symbols maybe shared with English and other Latin languages: `—` `-` `/`)

and these symbols are forbidden to be placed at the end of a line:

```text
“‘（［〔【《〈「『〖｛
```

These two compound symbols can be arranged in any position (please note that no space can be inserted between their two elements, and, as mentioned above, one of their elements, `—`, can also be used alone.):

`……` and `——`

**Comment by peng1999** [comment]
There is code to reproduce this issue:

```
#set page(width: 120pt, height: auto)

This is a text with a formula and Chinese comma $x$，
```

<img width="546" alt="image" src="https://user-images.githubusercontent.com/12483662/231617564-6b133524-e81f-4ab9-b8e8-f74e3a0957cf.png">

**Comment by peng1999** [comment]
Also, this is not specific to Chinese punctuations. If set correct margin, we can reproduce this bug in pure English:

```
#set page(width: 120pt, height: auto, margin: (x: 15pt))
#set text(lang: "zh")

This is a piece of text with a formula and a period $x^2 + 1$.
```

![Screenshot_20230413_161127](https://user-images.githubusercontent.com/12483662/231696630-0abe7b25-761e-4bf7-9d22-a3cb64087d20.png)
