### ISSUE TITLE
Provide ARM binaries

### ISSUE THREAD

**Issue by 0ip** [typst/typst#561]
Currently, only x86-64 binaries are released. However, Raspberry Pis don't like them too much. It would be great if also ARM binaries were provided to support such devices.

**Comment by Liangdi** [comment]
i have tested with target `aarch64-unknown-linux-musl`,  it seems to be working fine
![Screenshot from 2023-04-06 19-37-36](https://user-images.githubusercontent.com/1019161/230365740-c62cef44-dd5e-4816-8d15-92f30a94ce13.png)
![Screenshot from 2023-04-06 19-37-11](https://user-images.githubusercontent.com/1019161/230365763-a779afbe-a16e-404b-8391-4bcbb9c4647b.png)
