### ISSUE TITLE
`set` rule going beyond the local scope of a content block

### ISSUE THREAD

**Issue by BrightBulb123** [typst/typst#5620]
### Description

This is similar to #241 which was supposedly fixed in #4840.

The following typst code should be restricting the `set` rules to the local scope of the "title", but they are, for lack of a better word, 'bleeding' outside the block.

```typst
#set page(
    paper: "a5",
    margin: (x: 2.5cm, top: 3.5cm, bottom: 1.5cm),
    footer: context [
        TEST
        #h(1fr)
        #counter(page).display("1 of 1", both: true)
    ]
)

#let titlesetter(t) = [
    #set align(center)
    #set text(30pt, weight: "bold")
    #set par.line(numbering: "1.")
    #upper(t)
]

#titlesetter([
    TEST TITLE
])
```

The following image is what the above code generates.

![Image of the compiled document's first page, showing the footer also being bold and with a font size of `30pt`, when only the "title" should have had that.](https://github.com/user-attachments/assets/cf14ea1e-7312-4638-a6be-4087ab6c9796)

Putting some regular text after (and/or before) the title seems to fix the issue.

```typst
#set page(
    paper: "a5",
    margin: (x: 2.5cm, top: 3.5cm, bottom: 1.5cm),
    footer: context [
        TEST
        #h(1fr)
        #counter(page).display("1 of 1", both: true)
    ]
)

#let titlesetter(t) = [
    #set align(center)
    #set text(30pt, weight: "bold")
    #set par.line(numbering: "1.")
    #upper(t)
]

#titlesetter([
    TEST TITLE
])

This is normal text afterwards!
```

![Image of the compiled document's first page, showing the footer and paragraph line numbering being the correct size and style, after some regular text has been added after the title.](https://github.com/user-attachments/assets/6eeaaece-1c49-4843-bbab-bc1c9aaa2635)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
From Typst's point of view, what you wrote is equivalent to this:
```typ
#set page(
  paper: "a5",
  margin: (x: 2.5cm, top: 3.5cm, bottom: 1.5cm),
  footer: context [
    TEST
    #h(1fr)
    #counter(page).display("1 of 1", both: true)
  ]
)

#let titlesetter(t) = {
  set align(center)
  set text(30pt, weight: "bold")
  set par.line(numbering: "1.")
  upper(t)
}

#show: titlesetter

TEST TITLE
```

what in turn is more or less the same as
```typ
#set page(
  paper: "a5",
  margin: (x: 2.5cm, top: 3.5cm, bottom: 1.5cm),
  footer: context [
    TEST
    #h(1fr)
    #counter(page).display("1 of 1", both: true)
  ]
)
#set align(center)
#set text(30pt, weight: "bold")
#set par.line(numbering: "1.")

#upper[TEST TITLE]
```

In the general case, Typst can't really know your intent. In many cases, you do want a `set text` to apply to the header & footer, while in others you don't. Using the scope of a content block to distinguish the cases isn't really a great option because it's not compatible with the idea of templates adjusting the header & footer styles. 

So, unfortunately there is some inherent ambiguity in this case.

**Comment by laurmaedje** [comment]
Addition: To fix this, I would recommend having an explicit page call:
```typ
#set page(
    paper: "a5",
    margin: (x: 2.5cm, top: 3.5cm, bottom: 1.5cm),
    footer: context [
        TEST
        #h(1fr)
        #counter(page).display("1 of 1", both: true)
    ]
)

#let titlesetter(t) = [
    #set align(center)
    #set text(30pt, weight: "bold")
    #set par.line(numbering: "1.")
    #upper(t)
]

#page(titlesetter([
    TEST TITLE
]))
```
Styles within a `page` call won't be propagated upwards.

**Comment by PgBiel** [comment]
> From Typst's point of view, what you wrote is equivalent to this:
> ---snip---
> In the general case, Typst can't really know your intent. In many cases, you do want a `set text` to apply to the header & footer, while in others you don't. Using the scope of a content block to distinguish the cases isn't really a great option because it's not compatible with the idea of templates adjusting the header & footer styles.
> 
> So, unfortunately there is some inherent ambiguity in this case.

Tbh, I think this is a bit unfortunate. I don't agree it is inherently ambiguous, at least from the user's PoV: clearly, the styles end at the end of the scope. Whereas, if we ignore how a template function is defined for a moment, to me it seems logical that

```typ
#show: func

content
```

has a wider reach - that is, would affect anything _after_, and by extension _before_, the document, thus affecting page headers and footers - than just

```typ
#func[content]
```

While I can see how the current way the semantics are defined may lead to this, I wonder if it could somehow be changed to make this distinction.

**Comment by laurmaedje** [comment]
Yeah block works as well, but is more limiting than page.
