### ISSUE TITLE
Plugin for a word processor

### ISSUE THREAD

**Issue by yonatankremer** [typst/typst#5621]
### Description

Atm, the main to use typst is with either vscode or the webapp, with a bit of note-taking apps having third party typst rendering plugins. As I work with multilingual (ltr and rtl) text, the details about text handling are important to my workflow, and vscode handles these poorly. That's why I'd like to see a typst math rendering plugin for a true word processor - ms word, librewriter and such. I will find that very useful

### Use Case

WYSIWYG typst math

**Comment by flaribbit** [comment]
something like this?

![c22a3f6e926cbbd23fa5dc1c83ed45eb](https://github.com/user-attachments/assets/a46e7820-884e-465f-a713-07d7e062d7d6)

**Comment by yonatankremer** [comment]
yes!

**Comment by flaribbit** [comment]
Yes, but this plugin is still in slow development. Been very busy recently and not sure when I can finish it.

**Comment by Enivex** [comment]
I'll close this as out of scope.
