### ISSUE TITLE
Hangs on Empty Footnote

### ISSUE THREAD

**Issue by winstonewert** [typst/typst#5623]
### Description

This code:

    #show footnote.entry: it => it.note.body;
    #footnote([])

Appears to make both the webapp and my local typst install hang. The empty footnote was an error on my end, but ideally typst shouldn't hang either.

### Operating system

Web app, Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Duplicate of #5354

**Comment by winstonewert** [comment]
Sorry for not finding that duplicate issue!
