### ISSUE TITLE
Some CJK characters disappear in Acrobat/Preview, but not PDFium

### ISSUE THREAD

**Issue by KevinZonda** [typst/typst#573]
Hello. I was doing some documents today, and I found that seems `chilline()+it` has different behaviours in CJK & macOS Preview.

I have folllowing codes:

```
#let chiline() = {
  v(-3pt);
  line(length: 100%, stroke: gray);
  v(-10pt)
}

  show heading.where(
    level: 2
  ): it => text(
    size: 15pt,
    fallback: false,
    font: (
      "Source Han Serif",
      "Noto Serif CJK SC",
    ),
    block(chiline()) + it
  )
```

and use it in docs as:

```
== 教育经历
```

And it compiled the code to pdf and view, in Chrome, it works perfect:
<img width="214" alt="image" src="https://user-images.githubusercontent.com/33132228/229826422-f4b514dc-afcd-4dbe-9205-adf0714f05bb.png">

However in macOS default viewer (Preview) it will show nothing visually, but seems can copy the content

<img width="192" alt="image" src="https://user-images.githubusercontent.com/33132228/229826652-54b75fbb-4196-4060-8ff7-5168ceb43431.png">
<img width="224" alt="image" src="https://user-images.githubusercontent.com/33132228/229826719-e468c65d-1ad0-4036-99f3-107cfe87d051.png">

I have tested english, it works fine:

<img width="157" alt="image" src="https://user-images.githubusercontent.com/33132228/229827087-7020637f-6b86-4bf8-8d0e-97956a64e104.png">

Compiled PDF
[bug.pdf](https://github.com/typst/typst/files/11151298/bug.pdf)

**Comment by laurmaedje** [comment]
What is a `chiline`?

**Comment by KevinZonda** [comment]
> What is a `chiline`?

Sorry about it, I have updated my issue. Apologies again!

**Comment by KevinZonda** [comment]
@TS40 Sorry again for the inconvenience I caused! Thank you for pointing out this. I have uploaded the pdf to the issue. Thanks again.

**Comment by KevinZonda** [comment]
It could be a font mixing issue?

```
#let chiline() = {
  v(-3pt);
  line(length: 100%, stroke: gray);
  v(-10pt)
}

#show heading.where(
    level: 1
  ): set text(
    fallback: true,
    size: 22pt,
    font: (
      "Noto Serif CJK SC",
    ),
    weight: "bold",
  )

#show heading.where(
    level: 2
  ): it => text(
    size: 22pt,
    fallback: true,
    font: (
      "Noto Serif CJK SC",
    ),
    weight: "bold",
    it
  )


= 标题1

#chiline()
== 教育经历
你好
```

It works, but 

```
#let chiline() = {
  v(-3pt);
  line(length: 100%, stroke: gray);
  v(-10pt)
}

#show heading.where(
    level: 1
  ): set text(
    fallback: true,
    size: 22pt,
    font: (
      "Source Han Serif",
      "Noto Serif CJK SC",
    ),
    weight: "bold",
  )

#show heading.where(
    level: 2
  ): it => text(
    size: 22pt,
    fallback: true,
    font: (
      "Source Han Serif",
      "Noto Serif CJK SC",
    ),
    weight: "bold",
    it
  )


= 标题1

#chiline()
== 教育经历
你好
```

does not:

[Tv4.pdf](https://github.com/typst/typst/files/11151768/Tv4.pdf)

**Comment by tiankaima** [comment]
> It could be a font mixing issue?
> 
> ...
>
> It works, but
> 
> ```
> #let chiline() = {
>   v(-3pt);
>   line(length: 100%, stroke: gray);
>   v(-10pt)
> }
> 
> #show heading.where(
>     level: 1
>   ): set text(
>     fallback: true,
>     size: 22pt,
>     font: (
>       "Source Han Serif",
>       "Noto Serif CJK SC",
>     ),
>     weight: "bold",
>   )
> 
> #show heading.where(
>     level: 2
>   ): it => text(
>     size: 22pt,
>     fallback: true,
>     font: (
>       "Source Han Serif",
>       "Noto Serif CJK SC",
>     ),
>     weight: "bold",
>     it
>   )
> 
> 
> = 标题1
> 
> #chiline()
> == 教育经历
> 你好
> ```
> 
> does not:
> 
> [Tv4.pdf](https://github.com/typst/typst/files/11151768/Tv4.pdf)


Hey, both of these contents compile perfectly on my mac, and your [Tv4.pdf](https://github.com/typst/typst/files/11151768/Tv4.pdf) is indeed not correctly showing in Preview.

| @KevinZonda  | Mine |
| --- | --- |
|  <img width="1177" alt="image" src="https://github.com/typst/typst/assets/91816094/c3c1b7f1-3141-42d6-80c6-9b96decdb1c2"> |  <img width="1177" alt="image" src="https://github.com/typst/typst/assets/91816094/5fbcbf39-0522-469a-b243-116ff92d3a3b"> |

My compiled PDF:  [test.pdf](https://github.com/typst/typst/files/12458714/test.pdf)

**Comment by laurmaedje** [comment]
Might be fixed by https://github.com/typst/typst/commit/c0b332a4c07b95c0c3196d0d7b149560dcef67fa
