### ISSUE TITLE
Bundle compressed document with dependant files in archive format

### ISSUE THREAD

**Issue by mojtaba82** [typst/typst#579]
It is good that a typ documents and all attachment become compressed and save as a format like typz.

**Comment by Enivex** [comment]
There's nothing stopping you from just creating a zip file.

**Comment by mojtaba82** [comment]
> There's nothing stopping you from just creating a zip file.

Yes. It is true. But You can not use typst command to make pdf from that zip file.

**Comment by Enivex** [comment]
> > There's nothing stopping you from just creating a zip file.
> 
> Yes. It is true. But You can not use typst command to make pdf from that zip file.

But what do you actually gain from such a format? It would make sense if the typst file was the final format for consumption, but it's not.

Losing plain text is a big drawback, especially for version control.

**Comment by mojtaba82** [comment]
> > > There's nothing stopping you from just creating a zip file.
> > 
> > 
> > Yes. It is true. But You can not use typst command to make pdf from that zip file.
> 
> But what do you actually gain from such a format? It would make sense if the typst file was the final format for consumption, but it's not.
> 
> Losing plain text is a big drawback, especially for version control.

You are right. I means It be possible to support compressed format furthermore plain format.

**Comment by laurmaedje** [comment]
This is out of scope for Typst and best covered by an external format like .zip or .tar.
