### ISSUE TITLE
Feature Request: Support numbering all formulas like equations

### ISSUE THREAD

**Issue by werifu** [typst/typst#583]
In my case, I need number all formulas (equations, inequalities and other math formulas...) and not only the equations. I think it would help if the numbering parameter can be supported in all math expressions wrapped by `$ $`

**Comment by dccsillag** [comment]
What do you mean? This is already the case with

```
#set math.equation(numbering: "(1)")
```

Though named `math.equation`, an "equation" is any bit of math.

**Comment by werifu** [comment]
Oh sorry, I am confused by the name.... It actually works for any math formula.

**Comment by dccsillag** [comment]
Oh, phew! I was a bit worried for a moment :sweat_smile: 

Cheers!
