### ISSUE TITLE
Line behaves differently in block that in rect

### ISSUE THREAD

**Issue by SaitoAtsushi** [typst/typst#588]
The base point of the line differs depending on whether the parent container of the line is block or rect.
Is there any documentation that explains this?
Or is this bug?

```
#set page(height: 10em, width: 10em)
#block(stroke: 1pt+black, width: 10pt, height:2em,
line(start: (0%, 50%)))
```

![block](https://user-images.githubusercontent.com/299440/230013626-6488af35-f56c-4769-acb1-b4cb45892f2e.png)

```
#set page(height: 10em, width: 10em)
#rect(stroke: 1pt+black, width: 10pt, height:2em,
line(start: (0%, 50%)))
```

![rect](https://user-images.githubusercontent.com/299440/230013755-53bfcb95-e7ff-4617-8ded-0b7adadca706.png)

**Comment by laurmaedje** [comment]
That's a bug.

**Comment by laurmaedje** [comment]
Should be fixed. There is still a bit difference by default, but that's because `rect` as an inset of `5pt` by default while `block` doesn't.
