### ISSUE TITLE
Paragraphs with explicit trailing whitespace don't layout as intended

### ISSUE THREAD

**Issue by Gewi413** [typst/typst#597]
Content blocks trim out spaces. Including
- `[        leading spaces]`
- `[trailing spaces       ]`
- `[spaces   between words]`
Which subsequently get rendered as 
![image](https://user-images.githubusercontent.com/41789317/230110306-40a0bf09-c348-4f59-a619-f584430d9c9c.png)

It is desireable when putting untintentional leading / trailing spaces / hitting space twice.
Yet this feature would be needed if you want to use spaces as spacing, i.e. with `a#box[  ]b` or in `#repeat[ .]` (to get further spaced out dots

Possible fix: add `text(trim: boolean = true)` parameter to let the user have not-trimming when desired

**Comment by laurmaedje** [comment]
The trimming of spaces in content blocks is intentional (because otherwise you'd have spaces all over the place in multi-line blocks) but it's a bug that it doesn't even work with a string as in `a#box(" ")b`.
