### ISSUE TITLE
Using a loop to render blocks creates a space between them

### ISSUE THREAD

**Issue by tedesmac** [typst/typst#599]
There shouldn't be any space when using a loop as it can mess up complex layouts and limits its usage for scripting.

### Sample code 

```
= With a loop

#grid(
    columns: (1fr, 1fr),
    stack(
        dir: ttb,
        for _ in (1, 2, 3) {rect(height: 50pt, width: 50pt)}
    ),
    stack(
        dir: ltr,
        for _ in (1, 2, 3) {rect(height: 50pt, width: 50pt)}
    ),
)

= Without a loop

#grid(
    columns: (1fr, 1fr),
    stack(
        dir: ttb,
        rect(height: 50pt, width: 50pt),
        rect(height: 50pt, width: 50pt),
        rect(height: 50pt, width: 50pt),
    ),
    stack(
        dir: ltr,
        rect(height: 50pt, width: 50pt),
        rect(height: 50pt, width: 50pt),
        rect(height: 50pt, width: 50pt),
    ),
)
```

<img width="736" alt="imagen" src="https://user-images.githubusercontent.com/13699437/230135937-4c863481-6456-4acb-a662-e682c3be8c7b.png">

BTW, Thanks for working on this project.

**Comment by laurmaedje** [comment]
The loop combines all rectangles into a single piece of content that you give to the stack. To give the rectangles as individual arguments to the stack, you can do either of the following two:
```
#stack(
  dir: ttb,
  ..(1, 2, 3).map(_ => rect(height: 50pt, width: 50pt)),
)

#stack(
  dir: ttb,
  ..for _ in (1, 2, 3) {
    (rect(height: 50pt, width: 50pt),)
  }
)
```
In the second version, we use the loop to join single-element arrays into one big array. The `..` syntax takes an array and gives it's element as individual arguments to the stack.
