### ISSUE TITLE
Add warnings and hints to the error reporting

### ISSUE THREAD

**Issue by Marmare314** [typst/typst#600]
Because a lot of non-programmers use typst, giving helpful hints and warnings is even more important than in programming languages.
Some examples
```
#let x, y = (1, 2) // hint: did you mean to use destructuring syntax (x, y)?
#set text(font: "non-existing font") // warning: font could not be loaded
**test** // warning: no content inside bold
```
Related: #391.

**Comment by reknih** [comment]
Another one for hints could be `cannot reference equation without numbering`

**Comment by laurmaedje** [comment]
Hints were implemented here, for reference: https://github.com/typst/typst/pull/1486
