### ISSUE TITLE
Different column width

### ISSUE THREAD

**Issue by saadulkh** [typst/typst#603]
Hey!

I wanted to know if it is possible to have page columns of different widths, like I want the left column to be smaller than the right one (the kind of format that we find in most resume)?

Thank you so much for your great project.

**Comment by laurmaedje** [comment]
This is not possible with columns, but you should take a look at [grids](https://typst.app/docs/reference/layout/grid/), which are great for this kind of thing.

**Comment by saadulkh** [comment]
Right, grids provide more customization.

Thanks.

**Comment by Evidlo** [comment]
It seems grids do not have any feature to split content between columns, so they are an incomplete replacement for `#columns` unfortunately.

https://forum.typst.app/t/is-it-possible-to-split-content-across-grid-columns/6259
