### ISSUE TITLE
Question: How can I number images separately for every level 1 heading?

### ISSUE THREAD

**Issue by werifu** [typst/typst#606]
### My target:
I want to number images by headings of level 1 like following:
```
= Chapter
== section

_(an img)_
Fig 1-1 xxxxx

== another section

_(another img)_
Fig 1-2 xxxxx

= Chapter

_(another img)_
Fig 2-1 xxxxx

```

### Initial Solution

Firstly, I maintained a customized numbering function and wrap the figure in an img function.

Every chapter owns a counter named `"image-chapter" + str(chapt)` and it increments when rendering a figure just what this comment said https://github.com/typst/typst/issues/478#issuecomment-1491769924

```typst
#set heading(numbering: (..nums) => {
    nums.pos().map(str).join(".") + "　"
})

#let image_num(_) = {
  locate(loc => {
    let chapt = counter(heading).at(loc).at(0)
    let c = counter("image-chapter" + str(chapt))
    let n = c.at(loc).at(0)
    str(chapt) + "-" + str(n + 1)
  })
}

#show figure: it => {
  set align(center)
  it.body
  it.supplement 
  it.counter.display(it.numbering)
  "　" + it.caption

  locate(loc => {
    let chapt = counter(heading).at(loc).at(0)
    let c = counter("image-chapter" + str(chapt))
    c.step()
  })
}

#let img(img, caption: "") = {
  figure(
    img,
    caption: caption,
    supplement:[Fig],
    numbering: image_num,
    kind: "image"
  )
}
```
<img width="334" alt="image" src="https://user-images.githubusercontent.com/53432474/230162411-d71dfffc-1937-40a8-bbb4-261c08377ccf.png">

The numbering seems okay, but labels will not work since location has changed.

```
= Chapter


== Section 1

Look at @img1

#img(image("avatar.jpeg", width: 30%), caption: "my caption") <img1>

#img(image("avatar.jpeg", width: 30%), caption: "my caption") 

Look at @img1
== Section 2

Look at @img1
```

### Another attempt

I then try to separate counters for different chapters by using a different kind of figure.
```
#let img(image, caption: "") = {
    locate(loc => {
		figure(
			image,
			caption: caption,
			kind: "image-" + str(counter(heading).at(loc).at(0))
	})
}
```
But I was told that I cannot ref a locate when I want to append a label <a> after an img element and ref it

Wrapping by `display` is the same.

I am struggling with this and I would appreciate it a lot if anyone could help me.

**Comment by johanvx** [comment]
Maybe #337 and the repository mentioned there ([sahasatvik/typst-theorems](https://github.com/sahasatvik/typst-theorems)) will help.

**Comment by werifu** [comment]
Nice work, I think it works for my case, though it's a little complicated

**Comment by flaribbit** [comment]
worked out a simple solution

```typst
#set heading(numbering: "1.")
#set figure(numbering: num => {
  locate(loc => {
    let fig_loc = query(figure, loc).at(num - 1).location()
    let chap = counter(heading.where(level: 1)).at(fig_loc).first()
    let chap_loc = query(heading.where(level: 1), loc).at(chap - 1).location()
    let num_before = counter(figure).at(chap_loc).first()
    str(chap) + "-" + str(num - num_before)
  })
})
```

**Comment by TiemenSch** [comment]
@flaribbit 's solution wrongly numbers the chapter number of the first figure in a chapter for me. I changed it to:
```typ
#set heading(numbering: "1.")
#set figure(
  numbering: num => locate(
    loc => {
      let chap_num = counter(heading.where(level: 1)).at(loc).first()
      let chap_loc = query(heading.where(level: 1).before(loc)).first().location()
      let fig_offset = counter(figure).at(chap_loc).first()
      str(chap_num) + "-" + str(num - fig_offset)
    },
  ),
)
```

**Comment by jensrodi** [comment]
Strange, I just tried the above solution and did not have the numbering correct. It seems to me that 'chap_loc' is the first chapter and thus 'fig_offset' will be 0 (at least in my tests). Shouldn't 'chap_loc' refer to the previous chapter, i.e. '.last().location()' instead of '.first().location()'?

Anyway, I got the slightly modified code below to work:

```typst
#set figure(numbering: num => {
  locate(loc => {
    let chap_num = counter(heading.where(level: 1)).at(loc).first()
    let chap_loc = query(heading.where(level: 1).before(loc)).last().location()
    let fig_offset = counter(figure).at(chap_loc).first()
    str(chap_num) + "." + str(num - fig_offset)
  })
})    
```

**Comment by RaulDurand** [comment]
There should be a simpler native solution for this, 
for example
```
    #set figure(numbering: "h1.1")
```
where h1 is the heading1 number.

**Comment by dbdbc** [comment]
For a simpler solution that also works in figure outline look at

https://github.com/typst/typst/issues/1896
