### ISSUE TITLE
Trying to #show text in monospace causes server crash

### ISSUE THREAD

**Issue by gabrfarina** [typst/typst#610]
I wanted to create a `#show` rule that would display a string (an algorithm name, "CFR") as monospace. When doing

```
#show "CFR": `CFR`
```

I get the error that the server crashed. (This was also reproduced on Discord where `tinger` was helping me.)

---

Incidentally, as a new user I am slightly confused by why

```
#show "CFR": strong
```

works, but not

```
#show "CFR": raw
```

**Comment by dccsillag** [comment]
This may be related to https://github.com/typst/typst/issues/519

**Comment by laurmaedje** [comment]
The problem is the same as in #229.

**Comment by gabrfarina** [comment]
You are right, sorry for missing it! I'll close this to avoid duplication.
