### ISSUE TITLE
Feature Request: support compilation to HTML and other formats

### ISSUE THREAD

**Issue by admercs** [typst/typst#612]
Feature request: add flags to the `typst compile` command that allow targeting additional output formats including HTML. This could be accomplished internally or by adding `typ` document format support to `pandoc`.

**Comment by Enivex** [comment]
https://github.com/typst/typst/issues/114

**Comment by laurmaedje** [comment]
This is indeed a duplicate of #114 and #188. The plan is to support HTML and EPUB.
