### ISSUE TITLE
Keybinding Suggestions

### ISSUE THREAD

**Issue by benjaminrwilson** [typst/typst#613]
Hi,

Thank you for the great project! I have two quality-of-life suggestions coming from Overleaf / other editors.

(1). `Cmd` + `/`: on macOS is quite common for line commenting. I think users might find it more intuitive if lint commenting were bound to that keybinding.

(2). `Cmd` + `s`: my understanding is that the document is saved after every keystroke. However, users from Overleaf and other editors may find themselves using this keybinding out of habit. I think it's worth considering (a). manual save here if the user would like to confirm their document is synchronized or (b). no-op to prevent the browser from thinking that the user wants to save the html source.

Thanks for the consideration!

**Comment by reknih** [comment]
We are now capturing the `Cmd+S` event. Some users have told us they configured their browser to do something else for that shortcut, so it can be disabled in the project settings panel.

**Comment by laurmaedje** [comment]
Comments with `Ctrl/Cmd + /` are now implemented.

**Comment by MDLC01** [comment]
This requires pressing <kbd>Ctrl</kbd>+<kbd>⇧ Shift</kbd>+<kbd>:</kbd> on an AZERTY keyboard, as `/` is accessed by modifying <kbd>:</kbd> with <kbd>⇧ Shift</kbd>.

I would expect to be able to use <kbd>Ctrl</kbd>+<kbd>:</kbd> on my AZERTY keyboard.

Similar issues probably arise with other keyboard configurations.
