### ISSUE TITLE
Output all symbols

### ISSUE THREAD

**Issue by Zuttergutao** [typst/typst#614]
Is there any way to output all symbols?

**Comment by PgBiel** [comment]
If you refer to math symbols, this page could be exactly what you're looking for: https://typst.app/docs/reference/symbols/sym/

**Comment by Zuttergutao** [comment]
Thanks a lot, I know this link. But the function I want is to output all symbols at once or use the loop function to output all supported symbols, which will help me write manuals.

**Comment by Zuttergutao** [comment]
> It seems that this is currently not possible, but [in the code](https://github.com/typst/typst/blob/085282c138899dd5aaa06bc6ae7bd2f79d75d7e1/library/src/symbols/sym.rs#L13) is a list that has exactly the data you want.
> 
> The nearest thing currently would be to iterate over all codepoints in `range(1114111)` and print them (most don't exist though) but the syntax `\u{v}` seems to require that `v` is a hex literal so generating this via code would also be difficult or not possible.

Thanks for your help! I have output the symbols to a pdf file. The file is [in my github](https://github.com/Zuttergutao/Typstdocs-Zh-CN-/blob/main/Symbol/symbol.pdf).

**Comment by laurmaedje** [comment]
Can we close this issue?
