### ISSUE TITLE
Why not write all your documentations in Typst first?

### ISSUE THREAD

**Issue by InitialXKO** [typst/typst#615]
If you do not use it by yourself first, why others should use it?

**Comment by PgBiel** [comment]
To add to this, exporting Typst to HTML is planned, but not there yet, which makes web documentation using Typst pretty hard to do right now. However, @InitialXKO , the main thesis which first presented Typst to the world was fully written in Typst (see https://www.user.tu-berlin.de/laurmaedje/programmable-markup-language-for-typesetting.pdf, page 8). That should be enough to show that their creators are indeed using it (for their theses, even).

**Comment by Bit0r** [comment]
It is best to write another PDF document in Typst. "Bootstrapping" is very important and can allow developers to find many problems.

**Comment by bguo068** [comment]
> To add to this, exporting Typst to HTML is planned, but not there yet, which makes web documentation using Typst pretty hard to do right now. However, @InitialXKO , the main thesis which first presented Typst to the world was fully written in Typst (see https://www.user.tu-berlin.de/laurmaedje/programmable-markup-language-for-typesetting.pdf, page 8). That should be enough to show that their creators are indeed using it (for their theses, even).

The thesis looks beautiful. I want to borrow some styling code from it. Is the 'typ' code available for the thesis?
Thanks!!

**Comment by laurmaedje** [comment]
@bguo068 That thesis was written in a _very_ early version of Typst. Even if it's code was available, it would unfortunately be of very little help because Typst has changed so much.

**Comment by Trebor-Huang** [comment]
To add to this, usually writing about a markup language in the language itself is a *very bad idea*, because this would involve the trickiest escaping syntax possible. This doesn't at all demonstrate the normal use cases.

**Comment by t-wissmann** [comment]
> The academic and technical publication world is still very much a PDF-centric world. When they want to share their papers online, they usually share it as a PDF, e.g. on https://arxiv.org/

Just a clarification: Actually, arxiv is not PDF-centric but latex-centric: authors upload latex source code and not PDF. And you can even access the latex sources (see 'other formats') on an article's arxiv page.

**Comment by mndtr** [comment]
@InitialXKO  How many documentations for frameworks, programming languages, software and other stuff like this you see in a PDF files? Sorry if that’s sounds rude. Do you agree now?
