### ISSUE TITLE
Insert source code files into typst

### ISSUE THREAD

**Issue by evibhm** [typst/typst#617]
How to insert source code files into typst?

I want to insert a code snippet into typst. According to the documentation, I should use ` `` ` or `#raw`.

just like,

```
`
#include <iostream>

int main() {
    std::cout << "Hello, World!" << std::endl;
}
`
```

if I want highlight,

```
#raw("#include <iostream>

int main() {
    std::cout << \"Hello, World!\" << std::endl;
}", block: true, lang: "cpp")
```

Do I have to use a backslash to escape quotes in the code snippet when I insert it?

Is there a way for me to directly insert these source codes? Alternatively, can I insert a code file directly?

**Comment by evibhm** [comment]
I have found the solution

```markdown
```cpp
#include <iostream>

int main() {
    std::cout << "Hello, World!" << std::endl;
}
```.
```

So, can I insert a code file directly?

**Comment by Zuttergutao** [comment]
I think this link can help you
https://typst.app/docs/reference/data-loading/read/

**Comment by evibhm** [comment]
Thank you very much!
