### ISSUE TITLE
Watch and Compile Command Error

### ISSUE THREAD

**Issue by AbdullahZubair-UW** [typst/typst#620]
I'm running into the following scenario at the moment. Lets say I want to compile and watch Q1.typ, I'm currently getting

`typst w q1.typ`
`error: file not found (searched at w)`

And the exact same thing with the `compile` command. On the other hand,just typing `typst q1.typ` seems to compile the code and generate a pdf however I would really like it to update on save with the `watch` command.

**Comment by PgBiel** [comment]
@AbdullahZubair-UW you could be using an older typst version (please run `typst --version` to check), when you had to use `--watch` or `-w` instead of the subcommand `watch` (or `w`), which is now the way to do it in version 0.1.0. If you had previously compiled typst from source, you might have to do it again to have access to this update.

**Comment by AbdullahZubair-UW** [comment]
Yes, it seems like I had an older version since `--watch` worked. However, I only installed it half an hour ago using `brew`. Anyways, do you know when this will be available to Ubuntu users? Also, is there a list of commands that I can get a hold of. I would like to start using this for my math assignments.

**Comment by PgBiel** [comment]
> However, I only installed it half an hour ago using `brew`.

Yeah, v0.1.0 is a very recent release, so it might take a while before it gets to those (unofficial) repositories.

> Anyways, do you know when this will be available to Ubuntu users?

For typst to be available on Canonical's repositories, that will require someone (with the due knowledge) to do the packaging and maintenance of typst in those repositories. An issue could be opened to find people who can do this. However, it is likely not a priority right now, as you can always install and compile from source.

To install from source, you will need to install `rustup` through `apt` (or your preferred package manager), followed by running `rustup toolchain install stable`, and then `cargo install --git https://github.com/typst/typst.git`. Then, `typst` should be available with the most recent version (actually, with the latest commit, so even more recent than that).

> Also, is there a list of commands that I can get a hold of. I would like to start using this for my math assignments.

Use `typst --help`, but the main ones are `compile` (to compile once) and `watch` (to compile incrementally on file changes).

**Comment by AbdullahZubair-UW** [comment]
Thanks for the response. For the commands, I suppose I should have specified, but I was referring to a list of commands in math mode.

**Comment by laurmaedje** [comment]
Relevant official documentation for math: 
- https://typst.app/docs/reference/math/
- https://typst.app/docs/reference/syntax/#math
- https://typst.app/docs/reference/symbols/sym/

This might also be helpful: 
https://github.com/johanvx/typst-undergradmath/blob/main/undergradmath.pdf

**Comment by AbdullahZubair-UW** [comment]
Thanks for that. How can I get my `.typ` documents to the default LaTeX font style?

**Comment by laurmaedje** [comment]
To use the LaTeX font: `#set text(font: "New Computer Modern")` 
I don't know about quotient spaces, but you can escape the backslash to display it: `X \\ Y`.

**Comment by AbdullahZubair-UW** [comment]
When I run the command `typst fonts` it doesn't seem to output `"New Computer Modern"` and my pdf file is not displaying the font either. Do I have to somehow download it?

**Comment by laurmaedje** [comment]
I have just merged a PR to include it in the binary. You can either switch to that new, unreleased version or download the font (its in assets/fonts) and install in on your system.

**Comment by laurmaedje** [comment]
If you installed from source with `cargo`, I think you can just re-run the install. If that doesn't do anything because it consider Typst to be up-to-date (because the version number is still the same), you can also try this: `cargo install --force --git https://github.com/typst/typst.git`

**Comment by AbdullahZubair-UW** [comment]
Okay. However, for official version updates in the future, what command would I have to run to get the update on my system? (Sorry, I'm in PMATH so I'm not so familiar with software)

**Comment by AbdullahZubair-UW** [comment]
I installed it as instructed in the above comment, using `cargo install --git https://github.com/typst/typst.git`. Can I not just do a `cargo update` command?

**Comment by laurmaedje** [comment]
No, `cargo update` is used for updating dependencies. Have you tried `cargo install --force --git https://github.com/typst/typst.git`? Does it not work?

**Comment by AbdullahZubair-UW** [comment]
I've run the command, but how can I check that it successfully retrieved the latest version?

**Comment by AbdullahZubair-UW** [comment]
However, note that when I run `typst fonts` it does not display any of the new fonts `NewCM...`. I had to download those files and store them in `/usr/share/fonts` in order for me to use them.
