### ISSUE TITLE
Typst for aarch64

### ISSUE THREAD

**Issue by saadulkh** [typst/typst#629]
As the current release only has binaries for `x86_64` architecture, I would like to know about `aarch64` support. As I need it for my hardware. 

Thanks in advance for your response.

**Comment by Liangdi** [comment]
i have tested with target aarch64-unknown-linux-musl, it seems to be working fine
![Screenshot from 2023-04-06 19-37-11](https://user-images.githubusercontent.com/1019161/230367228-501d72a3-2c8a-44a9-9ed4-88483b3282ea.png)
