### ISSUE TITLE
Font weight and style problems with CJK fonts

### ISSUE THREAD

**Issue by 393533486** [typst/typst#635]
Chinese fonts cannot be styled bold, italic, and so on.

Chinese commonly used SimSun and SimHei I have tried, neither can be set to bold or italics.

Hope for better Chinese adaptation support.

**Comment by ZJUGuoShuai** [comment]
在 macOS 上测试了一下，Songti SC 可以被正常加粗，SimSun 确实不行。而且目前加粗需要在 * 两边加空格，否则识别不出来。如：
```
我是*被加粗的*部分，这个会失败。

我是 *被加粗的* 部分，这个会成功。
```

CJK 支持还是欠缺啊。

**Comment by Enter-tainer** [comment]
related: #394

**Comment by Enter-tainer** [comment]
> 而且目前加粗需要在 * 两边加空格，否则识别不出来。

see https://typst.app/docs/reference/text/strong/

> Note that this only works at word boundaries. To strongly emphasize part of a word, you have to use the function.

**Comment by Trebor-Huang** [comment]
Does it make sense to treat each CJK character its own word?

**Comment by Enter-tainer** [comment]
> Does it make sense to treat each CJK character its own word?

i guess the "word" here refers to spaces between characters. This make because typically you dont want `some_snake_case_word` becomes italics.

**Comment by laurmaedje** [comment]
Maybe we could add a special case for CJK if it makes sense.

**Comment by laurmaedje** [comment]
The lexer has been changed to treat CJK in a special way: https://github.com/typst/typst/pull/2648

Is there another issue beyond #394 here?

**Comment by Enter-tainer** [comment]
> The lexer has been changed to treat CJK in a special way: https://github.com/typst/typst/pull/2648
> 
> Is there another issue beyond #394 here?

i think no. simsun and simhei mentioned i. this issue doesn't have a bold variant. so it is the fake bold problem now.

**Comment by WangRui1235** [comment]
it seems that the head title or subtitle cannot be shown accurately with CJK characters,is there any related issues? ths.

**Comment by Enter-tainer** [comment]
can yoy elaborate?

**Comment by WangRui1235** [comment]
> can you elaborate?
just then i typed  "=== 操作“ online for preview，the characters cannot be rendered,but when i translated it into "=== operations ",it displays **operations** accurately.
this issue seems to occur casually,now i find it all right and i forgot to take any sceenshots.
i'm really sorry for my disturbance.

**Comment by WangRui1235** [comment]
> can you elaborate?

just then i typed in"=== 操作"，the CJK characters cannot be rendered,but when i translated into"=== operations",it displays **operations** accurately.
it seems to happen casually.now it seems to be all right,and i forgot to take a sceenshot.
i am sorry for my disturbance.

**Comment by Enter-tainer** [comment]
i think it is loading the chinese font so it doesnt appear on screen instantly. glad to hear it works in the end
