### ISSUE TITLE
Visualize data using graphs or charts

### ISSUE THREAD

**Issue by saadulkh** [typst/typst#636]
Hey!

I've looked at the documentation and found that there is an option to draw paths and lines, which can be used to create graphs. But the problem seems to me that, graphs usually have `x` and `y` axis that are usually created automatically in softwares like word or excel.

Tho axis can also be created using lines, but considering that if we are loading data from a `csv` file, the data points for axis will not be present in it. Also, manually creating those axis will clutter the code and they also might not work as expected.

So, it's a feature request to add a `#graph` or `#chart` template/function in the language. 

Also, thank you so much for you awesome open-source work.

**Comment by johannes-wolf** [comment]
It is still WIP, but I have implemented line charts here: https://github.com/johannes-wolf/typst-plot

**Comment by saadulkh** [comment]
That's good to know that there's already some work going on, regarding this feature.

Also, as this thing is already mentioned on website, just that I missed it, I'm closing this issue. Thanks for your response.
