### ISSUE TITLE
Page Number-Align is broken or unintuitive

### ISSUE THREAD

**Issue by HiramTheHero** [typst/typst#645]
I have only the following code in a `.typ` file.

```
#set page(
    number-align: right + top,
    numbering: "1",
)
```

And it creates the following PDF with the page numbering on the bottom right:
<img width="639" alt="Screen Shot 2023-04-06 at 10 57 19 PM" src="https://user-images.githubusercontent.com/22198719/230544000-e8716611-0276-47b1-a083-3aedf22418e0.png">

Is this feature broken, or am I not understanding how the `number-align` works?

**Comment by laurmaedje** [comment]
Currently, number-align determines the alignment of the number _within_ the footer. But I agree that this is confusing, maybe we should put it into the header instead when an explicit `top` alignment is given.

**Comment by HiramTheHero** [comment]
At this time is there a way to get the page number in the header?

**Comment by xkevio** [comment]
> At this time is there a way to get the page number in the header?

```
#set page(header: [
  #align(right)[#counter(page).display()]
])
```
