### ISSUE TITLE
Question on automatic formula numbering and referencing

### ISSUE THREAD

**Issue by Seeker98** [typst/typst#647]
I've been really interested in your work on typst, and I'm now trying to port my writing from markdown to typst.
While using typst.app online editor, I encountered problems on automatic equation numbering. This is my document:
```
#import "template.typ": *

#set math.equation(numbering: "1.1")

= Introduction
#lorem(5)
$ a eq.not b $ <eq1>

== Introduction2
#lorem(5)
$ c eq d $ <eq2>

= In this paper
#lorem(5)
$ a eq.circle b $ <eq3>


@eq1\
@eq2\
@eq3\
```
what I want is that eq1, eq2 and eq3 numbered as 1.1, 1.2 and 2.1,  as they belongs to different level-1 titles, but typst gives the numberings as 1, 2 and 3.
I wonder why is this happening, as if I did the simillar processing on the headings, it works fine.
If this is already in the design, how can I write right commands? and if not, is this a potential problem that can be optimized?

**Comment by laurmaedje** [comment]
This is currently difficult to achieve in Typst, but there is already an issue here: #380.

**Comment by flavio20002** [comment]
If somebody is interested:

    set math.equation(numbering: (..nums) => {
       locate(loc => {
          "(" + str(counter(heading).at(loc).at(0)) + "." + str(nums.pos().first()) + ")"
        })
    },)

    show heading: it => {
        if it.level == 1 {
          counter(math.equation).update(0)
        }
    }
