### ISSUE TITLE
Parser: whitespace insensitive block/content parsing

### ISSUE THREAD

**Issue by dvdvgt** [typst/typst#648]
Currently, the following code yields a parser error:

```
#{
  if true
  {
    1
  }
}
```

> `Error: expected block`

while this compiles just fine

```
#{
  if true {
    1
  }
}
```

Note, that this is not limited to `if-else` statements, but seemingly to all cases where a block or content is expected. Here are some more examples where parsing fails.

```
#let a =
  [
    ...
  ]
```

```
#let a =
  {
    ...
  }
```

Also note that issue #490 is subcase if this issue.

I think the parsing of blocks should not depend on the trivial tokens preceding it (e.g., spaces or comments) and parser should be resistant against such different formatting possibilities.

I am looking forward to hearing your opinion on this!

**Comment by dvdvgt** [comment]
I would imagine that the parsed syntax tree of

```
#if 1 + 2 == 3
{
  1
}
else
{
  2
}
```

needs to look like this:

```
Markup: 61 [
    Hashtag: "#",
    Conditional: 60 [
        If: "if",
        Space: " ",
        Binary: 10 [
            Binary: 5 [
                Int: "1",
                Space: " ",
                Plus: "+",
                Space: " ",
                Int: "2",
            ],
            Space: " ",
            EqEq: "==",
            Space: " ",
            Int: "4",
        ],
        Space: " \n",
        CodeBlock: 9 [
            LeftBrace: "{",
            Space: "\n    ",
            Code: 1 [
                Int: "1",
            ],
            Space: "\n",
            RightBrace: "}",
        ],
        Space: "\n",
        Else: "else",
        Space: " \n",
        CodeBlock: 9 [
            LeftBrace: "{",
            Space: "\n    ",
            Code: 1 [
                Int: "2",
            ],
            Space: "\n",
            RightBrace: "}",
        ],
    ],
]
```

**Comment by user202729** [comment]
I feel it's by design that newlines have some meaning like "implicit `;`" like in Python or JavaScript, although I'm not sure what the exact rules are.

```
#{
(1,)
(2, 3)
}

#{
(1,) (2, 3)
}
```

First block works, second block gives an error.

**Comment by laurmaedje** [comment]
This is largely intentional. The case below does not parse because otherwise let statements would spuriously continue just because the thing that follows happens the continue the expression.
```
#let a =
  [
    ...
  ]

// What about this?
#let x = 1
  + 2
```
