### ISSUE TITLE
Support ratio multiplication

### ISSUE THREAD

**Issue by thdhondt** [typst/typst#651]
Today, it is not possible to multiply two ratios:
![image](https://user-images.githubusercontent.com/9611679/230639234-ba0888f0-cc1b-4a26-b9b4-05eceef9e5cc.png)

Ideally, the following result would be obtained:
`80% * 50% = 40%`

**Comment by PgBiel** [comment]
As a workaround, you can use `80% * (50% / 100%)`. I believe this might have to do with the semantics of a `ratio` as necessarily a length relative to another, and not as the corresponding number divided by 100. That is, `80% * 50%` would semantically represent something like `(80% * x) * (50% * x)`, a.k.a. `40% * x^2`. By dividing by `100%` (a.k.a. `100% * x`), the extra `x` is removed, so it remains coherent.
