### ISSUE TITLE
For loop with indexing does not work anymore

### ISSUE THREAD

**Issue by npielawski** [typst/typst#654]
## Steps to reproduce:
Compile the following
```
#let elements = lorem(5).split()
#for i, el in elements [
  #i #el \
]
```

## Expected output
```
0 Lorem
1 ipsum
2 dolor
3 sit
4 amet.
```

## Logs
```
error: expected keyword `in`. did you mean to use a destructuring pattern?
  ┌─ test.typ:2:6
  │
2 │ #for i, el in elements [
  │       ^

error: expected keyword `in`
  ┌─ test.typ:2:6
  │
2 │ #for i, el in elements [
  │       ^
```

## Version
typst 0.1.0 (94e052b8)
compiled on a Mac M1 ARM64 (Could that be why? It'd be nice if someone could reproduce on another machine)

It works with the online version:
Deployed on 2023-04-06T11:25:05.540Z
Typst compiler version: 4f4af02acea0022a5c1966d9b7b4150b35749edd

**Comment by PgBiel** [comment]
Destructuring was merged to main (see https://github.com/typst/typst/pull/532), so you will need to either `#for (i, el) in elements.enumerate() [ ... ]`, or use the latest released (non-`main`) version.

**Comment by npielawski** [comment]
Thanks! It works now!
