### ISSUE TITLE
Feature request enum resume

### ISSUE THREAD

**Issue by ondohotola** [typst/typst#655]
Hi,

I would like to be able to automatically resume `enum` numbering from the last enum in the previous section. Currently this resets to 1.

While I can set `#enum(start: n)` with **n** being an integer the doc seem to indicate that only integers are allowed.

I would however like to put in my own counter, and then would probably be able to figure out an `#enumr(mycounter)[mybody]` function which would increment the passed `mycounter` before calling `enum` with the appropriate `start`.

Does this make sense?

**Comment by hedogn** [comment]
Using variables in the script should achieve the same effect.

**Comment by ondohotola** [comment]
Aye, RTFM, will do and revert.

Thank you

**Comment by laurmaedje** [comment]
I'm going to close this in favor of #325.
