### ISSUE TITLE
Remove space after a line 

### ISSUE THREAD

**Issue by saadulkh** [typst/typst#656]
Hey!

Is it possible to remove the white space after the line. Or some other alternative to achieve this behavior?
![image](https://user-images.githubusercontent.com/38633812/230665252-728f2575-306a-44ef-a112-d33771337a61.png)

**Comment by hedogn** [comment]
The white space before the line also needs to be removed.

**Comment by saadulkh** [comment]
For someone still looking for such behavior, I achieved it by using vertical spacing `#v()` above or below with `weak` parameter set to `true`.

Like this:
`#v(0pt, weak: true)`

This works, by overriding the existing spacing with the one provided in the argument.

Also, I would like to know if there's any other way is possible to achieve such behavior?

**Comment by laurmaedje** [comment]
Each line is its own block and has [block spacing](https://typst.app/docs/reference/layout/block/#parameters--spacing) around itself like paragraphs do. You could putt the lines into a container that gives you more control, like a `stack`:
```
#stack(
  dir: ttb,
  spacing: 3pt,
  line(length: 100%),
  line(length: 100%),
)
```

**Comment by saadulkh** [comment]
Right, that's great @laurmaedje.
Thanks for the suggestion.

Happy Typsting! `:)`
