### ISSUE TITLE
Allow for redefining smartquotes for a specific language

### ISSUE THREAD

**Issue by JKRhb** [typst/typst#657]
In German (and probably also in other languages), it is possible to use multiple variants of quotation marks, namely a regular variant („ “) and "guillemets" (» «). If I see it correctly, smart quotes for German only support the regular variant at the moment, with no option for redefining the kind of quotes that are being used.

This is certainly not that important as a feature, but do you think that such a configuration option could be added at some point in the future?

**Comment by laurmaedje** [comment]
Sure, that should be a fairly straight-forward addition.

**Comment by tingerrr** [comment]
I have implemented an MVP for this at #2209, if you want to take a look. I'm a bit unsure if this should be per language or just set as is.
