### ISSUE TITLE
List of Acronyms

### ISSUE THREAD

**Issue by JKRhb** [typst/typst#659]
It would be great if there was a way to use acronyms in Typst similar to the functionality offered by LaTeX packages such as `acronym` or `acro`, making it possible to generate a List of Acronyms with only the acronyms that actually been used in the text.

As an advanced feature, these acronyms could also be expanded dynamically in the text, depending on whether they have been used before (i.e., only the first acronym would get printed in its full form, and following occurrences would use the short form).

**Comment by jnlmmln** [comment]
I have created a function for that maybe it helps.

acronyms.typ
```
// Dictionary with acronyms
#let acronyms = (
  API: "Application programmable interface",
)

// The state which tracks the used acronyms
#let usedAcronyms = state("usedDic", (_: ""))

// The function which either shows the acronym or the full text for it
#let acro(body) = {
  if(dict.keys().contains(body) == false) {
    return rect(
      fill: red,
      inset: 8pt,
      radius: 4pt,
      [*Warning:\ #body*],
    )
  }
  usedAcronyms.display(usedDic => {
    if(usedDic.keys().contains(body)) {
      return body
    }
    return dict.at(body) + " (" + body + ")"
  });
  usedAcronyms.update(usedDic => {
    usedDic.insert(body, true)
    return usedDic
  })
}
```

main.typ
```
#import "acronyms.typ": acro

// Call the function
#acro("API") // --> Application programmable interface (API)

// Second call only the acronym is shown
#acro("API") // --> API
```

**Comment by JKRhb** [comment]
Thank you, @jnlmmln, that is a great start! :)

**Comment by jnlmmln** [comment]
You are welcome, here is also the code I use to show an overview (Glossar):
```
#import "acronyms.typ": usedAcronyms, acronyms
#locate(loc => usedAcronyms.final(loc)
.pairs()
.filter(x => x.last())
.map(pair => pair.first())
.sorted()
.map(key => grid(
    columns: (1fr, 1fr),
    gutter: 1em,
   strong(key),acronyms.at(key) 
  )).join())
```

**Comment by laurmaedje** [comment]
> I tried the code snipped above, but it gives me an error "expected comma" at the position of the underscore in the #let usedAcronyms definition. What am I doing wrong?

Try replacing `(_: "")` with `(:)`. Moreover, `dict` needs to be replaced with `acronyms` in two places for it to work.

Explanation: I think the author didn't know how to create an empty dictionary, so they created one with an unused key like this: `(_: "")`. However, a lone underscore has since (in the last update) been forbidden as an identifier. The correct way to create an empty dictionary is `(:)`.

**Comment by mareikep** [comment]
> > I tried the code snipped above, but it gives me an error "expected comma" at the position of the underscore in the #let usedAcronyms definition. What am I doing wrong?
> 
> Try replacing `(_: "")` with `(:)`. Moreover, `dict` needs to be replaced with `acronyms` in two places for it to work.
> 
> Explanation: I think the author didn't know how to create an empty dictionary, so they created one with an unused key like this: `(_: "")`. However, a lone underscore has since (in the last update) been forbidden as an identifier. The correct way to create an empty dictionary is `(:)`.

Thank you for the explanation. I wasn't familiar with the empty dictionary initialization here, so I had just replaced it by an empty list (not sure why we need a dictionary here anyway). The other errors were more obvious to fix. However, I have a working example now and a similar one for glossary entries, which came out nicely. Next step would be to a) add the page numbers where the glossary/acronym entry was used in the overview and b) have a nice overlay similar to the one, that typst shows for citations (which is really cool)

Any suggestions are highly appreciated :)

**Comment by laurmaedje** [comment]
> I wasn't familiar with the empty dictionary initialization here, so I had just replaced it by an empty list (not sure why we need a dictionary here anyway).

That works too. Maybe the original author wanted to use a set-like structure for better performance. Shouldn't matter too much until the list of acronyms gets huge. 

> add the page numbers where the glossary/acronym entry was used in the overview

That's gonna be a bit trickier. Your best bet is probably to attach a bunch of generated labels to the entries and `query` for them.

> have a nice overlay similar to the one, that typst shows for citations (which is really cool)

What do you mean with "overlay"?

**Comment by laurmaedje** [comment]
> displays a preview of the page to jump to

That's a feature of your PDF viewer! When you create a link that should happen automatically.

**Comment by Ciolv** [comment]
In case someone needs more than just printing the short form from the second `#acro` usage ongoing: based on the snippet from jnlmmln I've created [another acronym snippet](https://github.com/Ciolv/typst-template-bachelor-thesis/blob/main/acronyms.typ) with some more acro-like features (`#acs`, `#acl`, `#acp`,  `#acsp`, `#aclp`). Still far from perfect, but usable.

**Comment by KronosTheLate** [comment]
I just though I would provide what I am currently using, a simple function that takes a string or content, and collects the capital letters in a parenthesis, underlining them:
```typst
// Uppercase letters in `input` (string or content) are underlined, and put into a parenthesis in the end.
#let acronym(input, make_lower: true) = {
  set underline(evade: false)

  let input_string = if type(input) == "string" {
     input} else {input.text
  }
  let capitals = ()

  for letter in input_string {
  if letter.contains(regex("[A-Z]")) {
    capitals.push(letter)
    if make_lower {
      underline(lower(letter))
    } else {underline(letter)}
  } else {letter}
  }
  [ (#capitals.join())]
}
```

The following input:
`#acronym[Integrated Development Environment]` 
generates
![image](https://github.com/typst/typst/assets/61620837/9db00d1f-8150-44c9-a144-9d83eb3a7009)

**Comment by dscso** [comment]
Now there is a package that is managing this. It is not the only one but the one I use as I consider it the best.
https://github.com/typst/packages/tree/main/packages/preview/glossarium

**Comment by laurmaedje** [comment]
I'll close this as something that we'll continue to leave to packages.
