### ISSUE TITLE
Control over list bullets?

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#660]
I'd like to get something like this (disregard spacing):
![image](https://user-images.githubusercontent.com/9490724/230691500-aa478172-4e58-4cd6-991d-1830a1a6f3a9.png)

Notice that the top-level bullet is bold and has surrounding parentheses while the inner bullets are terminated by dots. `numbering: "a.i."` gets the symbols right, but I don't see how to get the rest of the behavior.

**Comment by laurmaedje** [comment]
Does this do what you want?
```
#set enum(
  full: true,
  numbering: (..args) => {
    let nums = args.pos()
    if nums.len() == 1 {
      strong(numbering("(A)", nums.first()))
    } else {
      numbering("i.", nums.last())
    }
  }, 
)

+ A
  + B
  + C
    + D
```

**Comment by SUPERCILEX** [comment]
Clever! Yes, thank you.
