### ISSUE TITLE
Letter p causes underline to toggle on/off

### ISSUE THREAD

**Issue by rypervenche** [typst/typst#661]
When using Noto Serif in a header with underline, lowercase P seems to toggle the underline, while lowercase Y also brings it back.

typst 0.1.0 (94e052b8)

```
#show heading.where(
  level: 1
): it => block(width: 100%)[
  #set align(left)
  #set text(24pt, font: "Noto Serif")
  #underline[*#it.body*]
]

= this pad pin pan pot pun yes no
```
![imgur](https://i.imgur.com/xuG2xJl.png)

**Comment by rypervenche** [comment]
It seems that this may only happens when it's bold.

**Comment by Enivex** [comment]
That sure is a strange bug. I would've expected it to at least happen with every letter that has a descender
