### ISSUE TITLE
What is an element function?

### ISSUE THREAD

**Issue by saadulkh** [typst/typst#662]
I looked through the documentation but could find the explanation.

I'm trying to use a custom function in `#query` but the compiler error says that `only element functions can be used as selectors`

How can I use custom function in a query, or is it not possible?
How to make a custom element function if possible?

My use case is that, I have a `counter` and a `function` that steps the counter.

**Comment by user202729** [comment]
> Can be an element function like a heading or figure, a <label> or a more complex selector like heading.where(level: 1).
> 
> Currently, only a subset of element functions is supported. Aside from headings and figures, this includes equations, references and all elements with an explicit label. As a result, you can query for e.g. [strong](https://typst.app/docs/reference/text/strong/) elements, but you will find only those that have an explicit label attached to them. This limitation will be resolved in the future.

So `heading` is an element function: it's a **function**, but used to create an **element**.

**Comment by saadulkh** [comment]
Thanks, I still didn't get what an **element** is. Tho will ask again on Discord.

**Comment by GeorgeHoneywood** [comment]
I came across this, when wanting to `query` for some instances of a custom function. The way I worked around this limitation is by attaching a shared label to the content of the custom function, then `query`-ing for that instead.

For example:

```
#let todo(x) = [ #text([TODO: #[#x <todo>]], red) ]

#let todos() = {
    locate(loc => {
        let elems = query(
            <todo>,
            loc,
        )

        if elems.len() == 0 {
            return
        }

        [= TODOs]

        for body in elems {
            text([+ #link(body.location(), body.text)], red) 
        }
    })
}

// then use like
#todo[do something]
#todo[some other issue]

// display list of todos
#todos()
```

[See here for example output](https://github.com/typst/typst/files/11288952/todo.pdf)
