### ISSUE TITLE
Endnote / Footnote

### ISSUE THREAD

**Issue by saadulkh** [typst/typst#663]
In word processing softwares, it is possible to add `endnotes/footnotes`

Footnotes get added at the end of the page like this:
![image](https://user-images.githubusercontent.com/38633812/230709492-8bfbc157-c15f-4d62-8459-089e7ac76137.png)

Similarly, endnotes get added at the end of the content.

Is there any equivalent in Typst?

**Comment by kovar** [comment]
Not yet but it is on the roadmap, see #222

**Comment by saadulkh** [comment]
Good to hear that it's on roadmap.
But, till it gets implemented in Typst. I've created a little ![typst-notes](https://github.com/saadulkh/typst-notes) library for it.
