### ISSUE TITLE
Text after reference

### ISSUE THREAD

**Issue by qeterme** [typst/typst#665]
Hi,
I want to reference a figure, and I want to put some text after it. Still, my problem is, in Hungarian, we put suffixes with the dash (-) character, so when I want to reference something, it wants to parse as part of the reference, Is there a way to put text after it without a space? 

![image](https://user-images.githubusercontent.com/8946184/230712093-5e3d9eb3-3f6d-4711-b8e2-696a06e48d1c.png)

```typst
@float-time[]-es ábrán

@float-time -en
```

**Comment by kovar** [comment]
Hi, as a quick fix you can put the reference into a content block:

```typst
#[@float-time]-en
```

Not sure if there is a more elegant way to solve this as the `@` is a short-hand notation for the [`ref()`](https://typst.app/docs/reference/meta/ref/) function. As far as I can tell it just assumes that you always write `@` followed by reference name (e.g. `float-time`) followed by a space.

Hope this helps!

**Comment by qeterme** [comment]
Thanks! It is quite the workaround, but it works. I think at least this should be in the docs somewhere.
