### ISSUE TITLE
Include Atkinson Hyperlegible font 

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#666]
See https://brailleinstitute.org/freefont

**Comment by reknih** [comment]
The font comes with a [dicey custom license](http://brailleinstitute.org/wp-content/uploads/2020/11/Atkinson-Hyperlegible-Font-License-2020-1104.pdf). We'd need to build a bit of infrastructure for to accommodate it.

**Comment by alerque** [comment]
The original release on the Braille Institute did have a dicey custom license, but it was later updated, cleanup up a bit, and submitted to Google Fonts with a standard OFL license. There is a [repository here](https://github.com/googlefonts/atkinson-hyperlegible) with the latest version with normal licensing.

**Comment by laurmaedje** [comment]
It's been available for a while, forgot to close the issue.
