### ISSUE TITLE
Formatting issues with "par" functionality

### ISSUE THREAD

**Issue by jerrita** [typst/typst#669]
Thanks for your awesome project, but I am encountering some formatting issues with the "par" functionality. Specifically, the following are not behaving as expected:

- After setting "first-line-indent", the first paragraph is not indented
- Lists are not indented
- The first paragraph after the list is not indented

Where can I adjust these settings?

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/28153001/230717191-a031559a-7b65-4012-93ad-b7215db0aaf0.png">

**Comment by jerrita** [comment]
After examining the source code, I discovered that this was intentionally designed this way. However, in the format required by our school's paper requirements, these should be indented. Therefore, I would like to know if there is a way to implement these features.

**Comment by xkevio** [comment]
I think, people are currently working on easing the "first paragraph cannot be indented" restriction but in the meantime you can do it manually by adding a `#h(2em)` in front of your paragraph.

Lists have an `indent` argument that you can set, like so `#set list(indent: 2em)`

**Comment by jerrita** [comment]
Thank you! It works for me.
