### ISSUE TITLE
Sometimes whitespace can't be copied from PDF

### ISSUE THREAD

**Issue by Xmoe** [typst/typst#671]
When including a #raw code block, it will render whitespace and indentation as intended, however when copying from the pdf, indentation is not included.

## Visualization of the problem:
Generated pdf looks fine
![Screenshot_20230408_152514](https://user-images.githubusercontent.com/5075033/230723928-fd9411f6-43c9-4d55-bc52-383ea8562793.png)
Selecting text to copy
![Screenshot_20230408_152535](https://user-images.githubusercontent.com/5075033/230723963-afcc30d3-18cb-416f-9c1b-977ebfcb0e38.png)
Pasting text reveals missing indentation
![Screenshot_20230408_152607](https://user-images.githubusercontent.com/5075033/230723981-f09c929b-5800-498d-8e22-7fca02cfda4b.png)

While pdf is not the best format to store code, it should not break whitespace-sensitive contents.

**Comment by user202729** [comment]
Easier said than done. There seems to be not much good solutions even when LaTeX can use `\pdfspecial` to include "arbitrary" content in the PDF.

[listings - How make a LaTeX document that generates a PDF from which copy-paste works correctly for empty lines and leading space indentation? - TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/563803/how-make-a-latex-document-that-generates-a-pdf-from-which-copy-paste-works-corre)

**Comment by laurmaedje** [comment]
We do export the spaces, but apparently many PDF viewers ignore it.

**Comment by disbolog** [comment]
Would it be possible to render some characters in place (e.g. a dot in the middle of a line), that indicate whitespace?

I would also like to get your opinion on 2 different approaches to solve such an issue: after copying the text which includes such characters, 
- the characters are either preserved as dots or as whatever char was specified (less desirable, but probably is easier to implement, if not implemented already); 
- or these chars are "converted" to whitespace on copy (more desirable obviously).

Either way, the copy buffer gets the correct indentation.

Would such a functionality be possible to implement?

**Comment by LaurenzV** [comment]
I've played around quite a bit with this, but it seems there just isn't a way of doing this. Whenever there is a glyph that is mapped to the space character in the CMAP, it just refuses to copy it properly and each viewer applies there own logic of handling it. Each of the approaches mentioned in the links above have their own quirks and don't work universally and have other issues. So I would suggest to close this issue, even though it's somewhat unfortunate, but there is no way of implementing this properly.

**Comment by laurmaedje** [comment]
That's a bummer.
