### ISSUE TITLE
Any tool to convert Latex code to typst?

### ISSUE THREAD

**Issue by DawnEver** [typst/typst#672]
Any tool to convert Latex code to typst?If no,I am considering create one.

**Comment by user202729** [comment]
Pandoc.

`https://github.com/jgm/pandoc/issues/8713`

**Comment by laurmaedje** [comment]
Pandoc is the way to go.

**Comment by reknih** [comment]
![Screenshot of the project creation options, the third one being a button for starting from an existing LaTeX project](https://github.com/typst/typst/assets/3874949/1705b17f-045c-4ea4-8bcd-cdb5ed624952)

Just wanted to chime in here and say that the web app now integrates Pandoc (with a few tweaks). You can drop your LaTeX source when creating a new project have it converted the best we can.

**Comment by koehntopp** [comment]
Is there a way to convert more than one .tex file...?

**Comment by mohe2015** [comment]
> Is there a way to convert more than one .tex file...?

Command line scripting with pandoc

**Comment by koehntopp** [comment]
Sorry, should have been clearer: Yes, in the web app 
Something like "import & convert .tex file"

**Comment by mohe2015** [comment]
> Sorry, should have been clearer: Yes, in the web app Something like "import & convert .tex file"

This is likely an issue you should file in https://github.com/typst/webapp-issues
https://github.com/typst/webapp-issues/issues/238#issuecomment-1852003322 There, somebody also mentioned that restriction.
