### ISSUE TITLE
Setting the distance between two paragraphs (parskip value)

### ISSUE THREAD

**Issue by michidk** [typst/typst#686]
# Summary
I want to set the distance between two paragraphs.

# Practical Example
Sometimes you do not want to have the space between text and the following element:
![image](https://user-images.githubusercontent.com/3979930/230765669-4417bd74-53ed-4bd5-a1b0-2da80ee1c117.png)

My guess is, that the space is there because a magic paragraph is inserted before the column.

This can be fixed by inserting a negative `v` with a magic number:
```
test
#v(-0.25cm)
#columns(1)[
  - test
  - test
]
```

# How LaTeX does it
In LaTeX there is the `parskip` package that can be used to change this behaviour: https://www.namsu.de/Extra/pakete/Parskip.htm
It also provides a simple constant that retrieves this "magic number", so the parskip can be counteracted: `\vspace{-\parskip}`

# Proposed Solution

Add a parameter to the `par` function (https://typst.app/docs/reference/layout/par/), so one can set the distance.

```
set par(skip: 0cm)
```

**Comment by LaurenzV** [comment]
In the case of columns, you can do this to remove the space:
```
#show columns: set block(above: 0pt)

test
#columns(1)[
  - test
  - test
]
```

If you want to remove the space before paragraphs in general, you can just do: `#show par: set block(above: 0pt)`

**Comment by LaurenzV** [comment]
So as an explanation (I might be wrong about this but I'm pretty sure): The reason you see a space above columns/pars is because they are wrapped inside of a block internally. So if you want to change how the block looks for a certain element, you can do it by using a show rule and setting the `above` paramter of the block accordingly.

**Comment by laurmaedje** [comment]
`show par: set block(spacing: ..)` is the intended way.
