### ISSUE TITLE
Coloring a block contained inside a grid panics when the row size is too low

### ISSUE THREAD

**Issue by jimvdl** [typst/typst#692]
Once you try to set `fill` or `stroke` on a `block` in combination of the `radius` the compiler panics, no matter the contents of the block.

Minimal reproducible example:
```
#grid(
    rows: 20pt,

    align(left)[
        t \
        #block(
            radius: 1pt,
            fill: blue,
        )
    ],
)
```
If you set `rows: 30pt` it no longer panics, the same happens if you leave `rows: 20pt` but remove the `t \`.

I couldn't make much sense of the backtrace so maybe someone else can: (it seems to refer to an assert in rustc which means this might not be a problem with Typst, although I'm not too sure)
```
'assertion failed: min <= max', /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0\library\core\src\cmp.rs:867:9
```

Additional information: I'm running the latest stable rustc version: `table-x86_64-pc-windows-msvc - rustc 1.68.2 (9eb3afe9e 2023-03-27)` and also running the latest Typst version: `v0.1.0 (b3faef4 2023-04-04)` and on a side note; when using the ?render command on Discord the bot also shows that it panics.

**Comment by laurmaedje** [comment]
Same as #1216, fixed in https://github.com/typst/typst/commit/363836a28e4c8877b7c5203ed4ce595a59731802.
