### ISSUE TITLE
Strip trailing newline in math equations

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#693]
This one has always been a pet peeve of mine with Latex:

```
    $
    ... &= ... \
    ... &= ... \
    ... &= ... \
    ... &= ... \
    $
```

For consistency and ease of reordering (think trailing comma), it'd be nice to be able to leave that trailing `\`, but it still adds a new line even though there is no content after it.

**Comment by laurmaedje** [comment]
Good catch, that's actually how it works in text, so we should allow it in math, too.
