### ISSUE TITLE
Raise type error when function pointer is used in content

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#694]
```
test

#pagebreak

test
```

There's still only one page.

**Comment by SUPERCILEX** [comment]
Oh I'm dumb you have to call the function: `#pagebreak()`. This should be a type error since you're trying to use a function pointer as content.

**Comment by laurmaedje** [comment]
It now displays `pagebreak` literally instead of being invisible. Generally, all things can be displayed / converted to content so I'm wary of adding special values for which it fails.

**Comment by SUPERCILEX** [comment]
Nice, I like how simple this solution is!
