### ISSUE TITLE
Add inner product function?

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#698]
It's pretty easy to define (`#let innerproduct(x, y) = $lr(angle.l #x, #y angle.r)$`), but should probably be built-in.

**Comment by Enivex** [comment]
The notation isn't standardized. In pure math $ (x,y) $ is commonly used.

**Comment by SUPERCILEX** [comment]
Ah, so maybe there should be multiple variants? Like `ip.{math, physics}`?

**Comment by Enivex** [comment]
> Ah, so maybe there should be multiple variants? Like `ip.{math, physics}`?

Or just leave it up to the user (or a future package) to define the version they prefer using lr. Everything's doesn't have to be a part of the core language.

**Comment by SUPERCILEX** [comment]
Fair enough.
