### ISSUE TITLE
Some numbering with closed brackets to be considered; hope to add a pre-made Chinese character numbering system, or add a custom numbering system to "numbering"

### ISSUE THREAD

**Issue by Roseleaves** [typst/typst#708]
The prefabricated ones can be `一`, `二`, `三`, et al; or `甲子`, `乙丑`, et al (then it is a set of circular numbers with a cycle of 60)
Custom parameters can be substituted as follows:
One is whether it is a circular number.
If it is not a circular numbering (then the number grows indefinitely), then determine the base system and the sign used for each bit.
For example, `#SetEnum(10, "零壹贰叁肆伍陆柒捌玖拾")`
In my opinion, the self-defining module is quite useful, and we really do not need to keep too many number systems as default.

by the way, some closed brackets might be considered, like
```
#set heading(numbering: "1.a.(i)")
= Introduction
== Cauchy sequences
=== Limits
== Dedekind cuts
```

and then the enumeration on the compiled PDF shows like:
```
1) Introduction
1.a) Cauchy sequences
1.a.(i) Limits
1.b) Dedekind cuts
```
We know that the `(` never shows with the absence of the third-level headings, however, the `)` always presents. 
How to make the `)` present if and only if `(` presents?

**Comment by peng1999** [comment]
Related: #565

**Comment by laurmaedje** [comment]
I have trouble understanding what exactly you want. With #565, there is at least one built-in numbering method. You can always create completely custom numberings by providing a function instead of a numbering pattern. Which specific additions would you like to see?

**Comment by Fusyong** [comment]
Here's how I use the built-in numbering method to customize Chinese numbers, perhaps not elegantly:

```ts
#set text(font: (
  "Inria Serif",
  "Noto Serif CJK SC",
  "Noto Sans CJK SC",
))

#set par(justify: true)

#let arabic_to_chinese(str) = {
    let dict = (
        "0": "〇",
        "1": "一",
        "2": "二",
        "3": "三",
        "4": "四",
        "5": "五",
        "6": "六",
        "7": "七",
        "8": "八",
        "9": "九",
    )
    str.clusters().map(
        x => dict.at(x)
        ).join()
}

#let chinese_numbering(..nums) = {
    nums.pos()
        .map(str)
        .map(arabic_to_chinese)
        .join(".") + " "
}

#set heading(numbering: chinese_numbering)

= 一级标题

== 二级标题

=== 三级标题

= 一级标题
= 一级标题
= 一级标题
= 一级标题
= 一级标题
= 一级标题
= 一级标题
= 一级标题
= 一级标题
```
![image](https://user-images.githubusercontent.com/15652226/231327067-2dec6a82-ddfc-47b0-9f71-edff6eba2618.png)

**Comment by laurmaedje** [comment]
Closing since since I still don't understand what is meant and there wasn't a response in over a year.
