### ISSUE TITLE
Swap `dot` and `dot.op`

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#724]
From Maximum Limelihood Estimator on discord:

> dot being a period instead of the dot product. If I wanted a period I would type a period.

I had the same reaction initially too and just didn't file an issue then. But I agree, `dot` should be multiplication. Or perhaps `*` should be converted to `dot.op`?

**Comment by Enivex** [comment]
> Or perhaps * should be converted to dot.op?

Hard disagree. Multiplication is rarely explicit, and * is used for convolutions, duals, adjoints etc.

**Comment by Enivex** [comment]
I actually didn't realize before now that dot.c is _not_ the same symbol as \cdot in latex. That's really confusing.

How about making dot.c work as the existing dot.c in text mode, and as dot.op in math mode, and simply remove dot.op? Or is it not possible to make them context dependent?

**Comment by SUPERCILEX** [comment]
The first option sounds reasonable. 👍

**Comment by SUPERCILEX** [comment]
Made a PR, though I didn't see how to specify conditions on text mode so didn't do that.
