### ISSUE TITLE
Emphasis does not work for Chinese

### ISSUE THREAD

**Issue by zhonghes** [typst/typst#725]
emphasis is not effective for chinese
![image](https://user-images.githubusercontent.com/114350562/231048873-4f3fbd01-73e0-400b-a633-15fe83c00d2e.png)

**Comment by Fusyong** [comment]
In the TeX Chinese community, italics in Chinese are replaced by kai, or kaiti. I recommend using the kai fonts from CNS11643中文標準交換碼全字庫(or 全字庫, Full Font Collection), which can be downloaded at https://data.gov.tw/dataset/5961

As indicated on the download page, Full Font Collection has two licenses:

1. 《政府資料開放授權條款-第一版》(Open Government License - Version 1): https://data.gov.tw/license
2. 《開放字型授權條款 OFL-1.1》 (SIL Open Font License 1.1): https://spdx.org/licenses/OFL-1.1.html

As a side note: there are not many open kai fonts.

**Comment by YDX-2147483647** [comment]
This is related to #276.

---

An example to use different fonts for normal `text` and `emph`:

```typst
#set page(height: auto)

#set text(font: ("Linux Libertine", "Source Han Serif"))
// See https://typst.app/docs/reference/text/text/ for more information

#show emph: text.with(font: ("Linux Libertine", "STKaiti"))

孔乙己#emph[上大人]

A quick _brown_
```

![](https://github.com/typst/typst/assets/73375426/f422490e-c003-4823-8c8a-e1560a60ae47)

---

As for `strong`, run `typst font --variants` to see if the font provides weight variants.

For example [adobe-fonts/source-han-serif at release](https://github.com/adobe-fonts/source-han-serif/tree/release#downloading-source-han-serif):

↓ This works fine.

```
Source Han Serif
- Style: Normal, Weight: 700, Stretch: 100%
- Style: Normal, Weight: 250, Stretch: 100%
- Style: Normal, Weight: 900, Stretch: 100%
- Style: Normal, Weight: 300, Stretch: 100%
- Style: Normal, Weight: 500, Stretch: 100%
- Style: Normal, Weight: 400, Stretch: 100%
- Style: Normal, Weight: 600, Stretch: 100%
```

↓ Variable fonts are not supported yet. (→ #185, #2508)

```
Source Han Sans CN VF
- Style: Normal, Weight: 250, Stretch: 100%
```

↓ Only a single variant. (What you see in MS Word is the _poor man's bold_)

```
SimSun
- Style: Normal, Weight: 400, Stretch: 100%
```

**Comment by YDX-2147483647** [comment]
Update: #2648 change the lexer and allow emphasis in CJK text without spaces. `中文一般使用*粗体*或者_楷体_来表示强调。` works now!

I guess the font problem is covered in #394, so maybe it's time to close this issue?

Similar issue: #635

**Comment by kongdd** [comment]
It seems that italic and bold still not work.

```typst
#set text(font: ("Linux Libertine", "Source Han Serif"))
// See https://typst.app/docs/reference/text/text/ for more information
#show emph: text.with(font: ("Linux Libertine", "STKaiti"))

_测试_
*中文*
```

![Image](https://github.com/user-attachments/assets/174de926-06b7-467f-9ce0-8374e76a60cb)

**Comment by YDX-2147483647** [comment]
@kongdd The fonts you specified are not available on typst.app.

![Image](https://github.com/user-attachments/assets/ccc5ba1e-6fa7-4e90-ace4-ca6919c59c04)

You could upload `C:\Windows\Fonts\simkai.ttf` and try the following.

```typst
#set text(font: ("Libertinus Serif", "Noto Serif CJK SC"), lang: "zh")
#show emph: set text(font: ("Libertinus Serif", "Kaiti"))

_测试_ *中文*
```

![Image](https://github.com/user-attachments/assets/a47d0b19-c1c9-423f-afbc-ba3aca37f346)

Further information (in Chinese):
- [如何设置中文字体的斜体？ | Typst 中文社区导航](https://typst-doc-cn.github.io/guide/FAQ/chinese-skew.html)
- [中文没有加粗 | Typst 中文社区导航](https://typst-doc-cn.github.io/guide/FAQ/chinese-bold.html)


Besides, please ask on https://forum.typst.app next time. Don't ask in this _closed_ issue.

**Comment by sspencer-arine** [comment]
FWIW.. Emphasis in CJK is a byproduct of MS Word enabling this through font transforms.  It is not entirely appropriate either.
