### ISSUE TITLE
Content of block with border radius can overreach the block

### ISSUE THREAD

**Issue by LaurenzV** [typst/typst#737]
Consider the following code:

```
#block(width: 100%, height: 200pt, stroke: blue + 2pt, radius: 5pt)[
  #block(width: 100%, height: 100%, fill: green)
]
```

It looks like this:
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/47084093/231278149-170e25da-752d-45e1-9518-458435973e82.png">

I believe the correct behavior would be to cut off everything that reaches over the corner?

**Comment by PgBiel** [comment]
Blocks normally let contents overflow I believe, unless you specify `clip: true`

But, even then, `clip: true` doesn't seem to help much in this specific case as it seems to clip using the rectangular boundaries, so this is still considered "inside", which is an interesting problem to solve

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/2338 with `clip: true`.
