### ISSUE TITLE
Justification system of Arabic script and similar.

### ISSUE THREAD

**Issue by asibahi** [typst/typst#740]
This is related to #195 . 

The full write-up and detail I wrote in [this article](https://asibahi.github.io/Thoughts/Practical%20Arabic%20Justification.html). With illustrating images and hopefully helpful links!!

Here is the tl;dr:

1. First and foremost: The justification method should be selectable by the user.
2. If the font being used is variable, check if there is a `GEXT` or `JSFT` axis. These are usually used for Justification. A greedy algorithm perhaps gives best results.
3. If not, the use of the OpenType feature of Justification Alternates, or `jalt`. They should *not* be turned on for the whole text, but selectively in lines that are too loose (usual typesetting would produce wider spaces). This would require reshaping specific words with the `jalt` feature turned on, or any OpenType feature specified by the end user. Some fonts use stylistic sets for (manual) justification work.
4. If not, then insert the [Tatweel character](https://www.compart.com/en/unicode/U+0640) between connecting letters. Then (this is a must) reshape the text. Kashidas are perhaps better inserted with a dictionary akin to a hyphenation dictionary. Don't forget reshaping the text.

I would work on implementing these myself but I am not very good at this programming thing, and would need someone to help me through the code.

**Comment by be5invis** [comment]
One thing to be notified is whether doing this in _text level_, meaning apply specific features to the text and reshape, or doing it at _glyph level_, meaning modifying the result glyph list (and reposition).

Doing it in glyph level may produce more accurate results and is way more faster, but may break certain kinds of fonts (like Nastaliq).

**Comment by asibahi** [comment]
at glyph level sounds like it would break the text rendering for literally any script more complex than latin.

**Comment by laurmaedje** [comment]
I'll close this in favor of #195 to concentrate things on one issue (I have renamed to other issue to make it more general). The information here is still very valuable and is still reachable via the cross-link!
