### ISSUE TITLE
Font weight is not working correctly

### ISSUE THREAD

**Issue by n-gao** [typst/typst#751]
None of the following code snippets affects the font-weight correctly.
```
#set text(size: 18pt)
#text(
    font: "Open Sans"
)[Open Sans]\
#text(
    font: "Open Sans Light"
)[Open Sans Light]\
#text(
    font: "Open Sans",
    weight: "light"
)[Open Sans (weight: light)]\
#text(
    font: "Open Sans",
    weight: "bold"
)[Open Sans (weight: bold)]
```
![image](https://user-images.githubusercontent.com/9084670/231398297-b213954f-f5a8-414c-8b65-0e2b22e9f83e.png)

Version: 0.2.0
OS: Windows 11

**Comment by astrale-sharp** [comment]
Might seem obvious but are you sure you have `open sans bold .ttf` or something installed?
if so maybe typst doesn't find it maybe try calling text with `fallback : false` to make sure

**Comment by n-gao** [comment]
All fonts are installed:
![image](https://user-images.githubusercontent.com/9084670/231405588-e60f290e-941d-4871-9841-a79252a068e8.png)

Result with `fallback: false`:
![image](https://user-images.githubusercontent.com/9084670/231405766-d9a89186-b477-4125-844a-09f99e3f1470.png)

**Comment by reknih** [comment]
Likely related to #576

**Comment by laurmaedje** [comment]
Closing in favor of https://github.com/typst/typst/issues/576

**Comment by sheey11** [comment]
You installed Open Sans as a vairable font, this should goes to #185
