### ISSUE TITLE
Support for glossary

### ISSUE THREAD

**Issue by Beafantles** [typst/typst#755]
Hi! Well first of all, thank you for this project, it is absolutely amazing.

I have a feature request that would be a great add to typst in my opnion: a glossary system (as in LaTeX). Here's an example of how I would imagine it within typst:

```
#glossary(
   term(DLL, DLLs)[A Dynamic-link library (DLL) is Microsoft's implementation of the shared library concept in the Microsoft Windows operating systems.],
   term(compiler, compilers)[In computing, a compiler is a computer program that translates computer code written in one programming language (the source language) into another language (the target language).],
   alias(dynamic-link library, dynamic-link libraries, DLL) // same as DLL for reference
)

You can build the #term(DLL, plural) by using a #term(compiler). #term(compiler, plural, capitalize) are great tools.

#print_glossary(title: "My custom glossary")
```

Of course, there's probably a better syntax, easier to use but that's just to show the idea.

Basically, you could:
1. define your terms with their singular/plural forms.
2. define aliases (for acronyms for example).
3. use your terms in your text. A reference to the definition in the glossary would be automatically added. The glossary would also automatically know the page indexes of every occurrences of its terms.
4. print the glossary (terms and their definitions) with some options (for example, display the page index where the terms are used, custom title, etc).

**Comment by gfauredev** [comment]
If someone is interested, waiting for the official feature, I “implemented” a somewhat hacky (and probably slow for large documents) glossary system in Typst that allows to write words definitions in a YAML file. It then automatically adds a link to every occurrence of your glossary words.

Here’s the 4 functions I use :

```typst
// Generate a regex that matches all the words in glossary named filename
#let glossaryWords(filename) = {
  let pipeList = "(?i:" // Match case insensitively
  for word in yaml(filename).keys() {
    pipeList += "\b" + word + "\b|" // Stop at word boundaries to not match inside other words
  }
  return regex(pipeList.slice(0, pipeList.len()-1) + ")") // Remove trailing pipe & close parenthesis
}

// Return the position of the word word in the glossary filename as dictionaries don’t implement find-like methods
#let glossaryPosition(filename, word) = {
  let count = 0
  for key in yaml(filename).keys() {
    count += 1
    if lower(key) == lower(word) {return count} // Search case-insensitively by lowering everything
  }
  assert(false, message: word + " not found in glossary but matched in regex") // Debug
}

// For a given word and glossary file, return the word augmented with a link to the glossary
#let glossaryShow(filename, word) = {
  word = repr(word)
  word = word.trim(regex("\s|\[|\]")) // Trim brackets generated by repr() and whitespaces
  return {
    show link: set text(size: 9pt)
    show link: set underline(stroke: 0pt) // I didn’t succeed to disable previous show-set
    // Insert an invisible char into the word to prevent show from looping on itself
    word.first() + "‎" + word.slice(1) // Unicode empty character
    link(label("glossary"), "(" + str(glossaryPosition(filename, word)) + ")"); " "
  }
}

// Display the words of the glossary with their definition & their eventual web links
#let glossary(filename, title: "Glossary") = {
  let data = yaml(filename)
  // let labelCount = 0
  if data.len() > 0 [
    #heading(title, numbering: none) #label("glossary")

  ]
  for (word, info) in data {
    [/ #word: #info.definition\ → #if "link" in info {link(info.link)}]
    // label("glo" + str(labelCount)) // Try to link words to their specific definition
    // labelCount += 1
  }
}
```

I then use this line to “enable” the linking of glossary words (so you probably want to place it before your content)
```typst
show glossaryWords("glossary.yml"): word => glossaryShow("glossary.yml", word)
```

And this line to print the actual glossary (generally at the end of the document)
```typst
glossary("glossary.yml")
```

Here’s an example of a glossary.yml file
```yaml
# Termes techniques dont je parle dans mon rapport de stage au LCPQ
orm:
  definition: Tool to represent relational data as programming language objects
  link: https://fr.wikipedia.org/wiki/Mapping_objet-relationnel

parser:
  definition: Tool that transform a string of text into a tree
  link: https://fr.wikipedia.org/wiki/Analyse_syntaxique
```

Hope it can help.

**Comment by PgBiel** [comment]
I am in the opinion that we should experiment with different ideas in packages, and eventually have a built-in (preferably blazing fast 🚀) option, much like we are doing with tables at the moment.

**Comment by SPodjasek** [comment]
I came up with following solution for my simple use-case:

## `glossary.typ`

```typst
#let glossary(filename) = {
  let terms = yaml(filename)

  for (id, info) in terms {
    [/ #info.term: #info.definition #label(id)]
  }
}

#let term(label, body) = {
  link(
    label,
    underline(
      stroke: (paint: black, cap: "round", thickness: 1pt, dash: "dotted"),
      evade: true,
      offset: 2pt,
      body
    )
  )
}
```

## `glossary.yaml`

```yaml
tls:
  term: TLS
  definition: >-
    TLS stands for Transport Layer Security. 
    It's a cryptographic protocol that ensures secure communication over a computer network, 
    typically the internet. TLS is the successor to the older Secure Sockets Layer (SSL) protocol, 
    although the term "SSL" is often used colloquially to refer to both SSL and TLS protocols.
```

## `main.typ`

```typst
#import "glossary.typ": glossary, term

== Glossary

#glossary("glossary.yaml")

== Content

Some content to refer to #term(<tls>, "TLS")
```

**Comment by laurmaedje** [comment]
There are now multiple packages for this, so I'll close this: https://typst.app/universe/search?q=glossary

**Comment by lettuceDestroyer** [comment]
@gfauredev Do you think we can sort the glossary? I'm aiming on creating a glossary which looks something like the following, although I don't need it to be this fancy with different colours and whatnot.
![image](https://github.com/typst/typst/assets/110594766/e19bbb2c-774e-412c-8e74-06d6e4b85db8)

**Comment by gfauredev** [comment]
> @gfauredev Do you think we can sort the glossary?

[Glossarium](https://typst.app/universe/package/glossarium) already sorts alphabetically the glossary entries. However, I think you might have to tweak it a bit to display the first letters as headers.

**Comment by lettuceDestroyer** [comment]
> > @gfauredev Do you think we can sort the glossary?
> 
> [Glossarium](https://typst.app/universe/package/glossarium) already sorts alphabetically the glossary entries. However, I think you might have to tweak it a bit to display the first letters as headers and the hyphens as separators.

If I read the documentation correctly, I'd have to manually reference the words. Can this be automated like in your example?

**Comment by likern** [comment]
> > @gfauredev Do you think we can sort the glossary?
> 
> [Glossarium](https://typst.app/universe/package/glossarium) already sorts alphabetically the glossary entries. However, I think you might have to tweak it a bit to display the first letters as headers and the hyphens as separators.

Can we just use https://typst.app/docs/reference/model/terms and glossary will be automatically created and styled accordingly? If not, what's the purpose of `terms` and what's the difference with `glossary`?

**Comment by laurmaedje** [comment]
`terms` is not intended for an automatic glossary, it's just a lists of terms and descriptions. Similar to an HTML/LaTeX description list. An automatic glossary might internally turns into a terms list.

**Comment by MarvinJWendt** [comment]
> I am in the opinion that we should experiment with different ideas in packages, and eventually have a built-in (preferably blazing fast 🚀) option, much like we are doing with tables at the moment.

Are there still thoughts about implementing a glossary natively? 
I have tried `glossy` and `glossarium`.

`glossy` has quite critical bugs that have not been fixed for months (even tho PRs exist) and `glossarium` has kind of a mixed syntax. Some options can be set via `@ref` syntax, some don't. Also the boilerplate is more than it should have imho (`glossy` has a much prettier syntax).

Since typst can already generate similar outlines, I think it's a good fit to have this functionality in-built.

**Comment by laurmaedje** [comment]
There aren't currently plans to have a built-in glossary. I don't have an overview over the current glossary packages, but if they are indeed lacking, then I think the right way forward is to improve them / build a better one.
