### ISSUE TITLE
Document title can't be set by variable

### ISSUE THREAD

**Issue by nightingale-m** [typst/typst#759]
**Title of the document doesn't change if it contains variables**

- Example of document:
  ```
  #let num = "4"
  
  #set document(title: "Doc №#num")
  
  = Test
  ```

- `pdfinfo` output:
  ```
  Title:           Doc №#num
  ```

- Expected:
  ```
  Title:           Doc №4
  ```

**Comment by laurmaedje** [comment]
You cannot use hashtag expressions in strings, try `title: "Doc №" + num"` instead.

**Comment by laurmaedje** [comment]
> More like `"Doc №" + str(num)`

In general yes, although here `num` was a string already. :)
