### ISSUE TITLE
`Content` rework (try 1)

### ISSUE THREAD

**Issue by Dherse** [typst/typst#765]
This changes aims at simplifying the existing `Content` implementation by replacing the `attr: EcoVec<Attr>` field and instead moving to a more specialized structure that keeps track of styling, ancestry (parent and children) and arguments separately. This change also allows full tracking of styling and ancestry, two features that are currently missing and required for some features.

As discussed with @laurmaedje, there needs to be some consideration for the size of `Content` due to its impact on other structs within typst, notably `Value`. Additionally, from a performance standpoint, we might want to limit the number of allocations and levels of indirection required to obtain the value. The number of allocations mostly impacts the time taken by C-O-W semantics, and the levels of indirection impact performance through memory accesses. Additionally, as with all things, it would be nice to keep the size of `Content` to 64 bytes or below to avoid using multiple cache lines.

To this effect, after our discussion, we came up with the idea of a DST (Dynamically Sized Types) data structs that `Content` would have a reference to, this struct would then contain all of the current attributes in a nicer way. Essentially, the new content would look like: (this is a mockup and not a final implementation)

```rs
struct Content {
    func: ElemFunc,
    attres: Arc<ContentAttributes>,
}

struct  ContentAttributes {
    header: ContentHeader,
    fields: [u8]
}
```

Otherwise, most features would remain unchanged. Styling would be added during the realize phase, in pre-processing (see `src/model/realize.rs:37`). Ancestry would also be carried through the styling system by the use of two new operators:
`Style::Open(ElemFunc, Location)` and `Style::Close(ElemFunc, Location)`. Essentially, instead of creating a tree by storing `Location`s, we can open and close scopes. This means that all subsequent children have easy access to their parent through the `StyleChain` and parent don't need to worry about "informing" their children because it can be added automatically to the `StyleChain` before `show` rules.

Finally, I would also add automatic insertion of a `Document` and `Page` element such that they can be kept of during styling and informations such as page numbering could be accessed through `StyleChain` rather than the current hack. It would also make it easier to add footnotes since a page could just query the footnotes in its children!

As always, I look forward to hearing you comments :)

- Part 1: #878

**Comment by PgBiel** [comment]
Is this issue still relevant?

**Comment by Dherse** [comment]
No indeed, closing as #2540 was merged weeks ago
