### ISSUE TITLE
Syntax highlighting for more languages

### ISSUE THREAD

**Issue by lucifer1004** [typst/typst#768]
The default language list of `syntect` is quite short, a possible solution is to use the much larger list maintained by https://github.com/sharkdp/bat/tree/master/assets/syntaxes and dump the syntax definitions to a binary file like https://github.com/Canop/broot/tree/main/resources/syntect does. Then we can bundle the binary file into Typst.

**Comment by lucifer1004** [comment]
https://github.com/sharkdp/bat#adding-new-syntaxes--language-definitions is a great reference

**Comment by KronosTheLate** [comment]
+1 on julia highlighting support

**Comment by laurmaedje** [comment]
Closed thanks to #771. Julia is supported now.
