### ISSUE TITLE
Support references with math in the title

### ISSUE THREAD

**Issue by Eloitor** [typst/typst#781]
Hi, I need to cite some references that contain math in the title.
I think this is not currently possible using a  .bib file.

**Comment by owiecc** [comment]
Can you attach a citation file containing that reference?

**Comment by Eloitor** [comment]
```
@misc{guitart2014padic,
      title={A $p$-adic construction of ATR points on $QQ$-curves}, 
      author={Xavier Guitart and Marc Masdeu},
      year={2014},
      eprint={1402.6531},
      archivePrefix={arXiv},
      primaryClass={math.NT}
}
```

**Comment by Eloitor** [comment]
I also noticed that the capital letters are not respected.

**Comment by rob-p** [comment]
Hi @Eloitor,

  I've also noticed that I can't properly enter math mode in the references as I would if typesetting with standard LaTeX.  However, as to your second issue, it's standard behavior that capitalization apart from the first letter is not respected in bibtex entries.  If you want letters to appear capitalized, you have to properly escape them.  For example, in your citation:

```
@misc{guitart2014padic,
      title={A p-adic construction of {ATR} points on {QQ}-curves}, 
      author={Xavier Guitart and Marc Masdeu},
      year={2014},
      eprint={1402.6531},
      archivePrefix={arXiv},
      primaryClass={math.NT}
}
```

should respect the capitalization you want.  This is, afaik, a bibtex thing (not a typst thing).

**Comment by Eloitor** [comment]
The problem with capitalization is also mentioned in https://github.com/typst/typst/issues/1172.

I made a test using the Hayagriva format https://typst.app/project/rKgGQRtdjvymESmXKbyetF where the issue with math and capitalization is clear.

**Comment by reknih** [comment]
Typst math in both YAML and Bibtex files is supported in 0.9.0.
