### ISSUE TITLE
Default line breaks in math mode to actual line breaks and use `\` as line break swallower

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#786]
```
$
a + b \
c + d \
$
```
could be written as just:
```
$
a + b
c + d
$
```

To get `$ a + b c + d $`, you would now write
```
$
a + b \
c + d
$
```

In text mode, `\` would still force a line break. So effectively math mode uses `\` as in every programming language's string parsing while text mode uses it latex style.

**Comment by Enivex** [comment]
This would require a symbol to _prevent_ line breaks, and would quickly get frustrating. I strongly prefer the current solution of explicitly breaking lines with \.

**Comment by SUPERCILEX** [comment]
Probs not the way to go. Or at least, we'd need a solution for inline math. You could say `\` works like in text mode for inline math, but it'll be confusing if people switch between the two.
