### ISSUE TITLE
Apparent imprecision in CMYK representation

### ISSUE THREAD

**Issue by PgBiel** [typst/typst#787]
It seems that, currently, CMYK rounds ratios rather aggressively upon print or such:

![image](https://user-images.githubusercontent.com/9021226/231864341-21d98b00-1fc8-4b23-b1bd-a407bdb7ff9a.png)

As CMYK is represented internally as integers (and, as such, it would probably be very hard to circumvent this), perhaps we could just display those integers instead (and accept them as parameters to `cmyk()`)?

**Comment by laurmaedje** [comment]
CMYK uses floats now.
