### ISSUE TITLE
Don't ignore A of RGBA in PDF export

### ISSUE THREAD

**Issue by laurmaedje** [typst/typst#79]

**Comment by Hannes-Steffenhagen-bd** [comment]
Hello, what's the status on this? I'm assuming this isn't some extremely fundamental limitation, given that placing images with transparent colours works fine.

**Comment by laurmaedje** [comment]
It's not a fundamental limitation, but transparency is a bit complicated in PDF and it's just not implemented yet.

**Comment by Enivex** [comment]
This is now a thing as of 0.7
