### ISSUE TITLE
Hide inside of math does not hide

### ISSUE THREAD

**Issue by dccsillag** [typst/typst#795]
Consider the code `$x^2 #hide[$y^2$] z^2$`. Expected behaviour is that we should see the `x^2`, then some empty space (corresponding to the `y^2`), and then the `z^2`.

However, this is the output we get (note also the weird spacing!):

![image](https://user-images.githubusercontent.com/15617291/231946084-e7832fe9-c723-452a-bba6-f495b1c05d3a.png)

This is a regression -- a while ago this worked fine. A `git bisect` points towards bb30911282a44dd00def88190055d7637c6382d7 as the commit that introduced the regression.

**Comment by laurmaedje** [comment]
[Fixed.](https://github.com/typst/typst/commit/f8966f9e867dc72080355342aab64734f70ac4f7)

**Comment by dccsillag** [comment]
Looks great now!

In fact, it looks like you just fixed another "issue" (which I had not reported yet), where `$#[$xz &= y$] \ #[$x &= y$]$` would not align (now it does).

**Comment by laurmaedje** [comment]
Yeah, that was part of the same regression that resulted in nested equations being treated as black boxes instead of being sort of "inlined" into the parent equation.
