### ISSUE TITLE
Question: how to crerate struct

### ISSUE THREAD

**Issue by alctny** [typst/typst#798]
how to make different dictionary has same field like struct

**Comment by PgBiel** [comment]
According to https://github.com/typst/typst/issues/478#issuecomment-1491769924, you will be able to create your own types (elements) in the future. For now, you can use dictionaries which are created from a "constructor" function, including a field (e.g. "type_name") which indicates the "type" of that dictionary in your internal code, and validate based on that.

**Comment by alctny** [comment]
> According to [#478 (comment)](https://github.com/typst/typst/issues/478#issuecomment-1491769924), you will be able to create your own types (elements) in the future. For now, you can use dictionaries which are created from a "constructor" function, including a field (e.g. "type_name") which indicates the "type" of that dictionary in your internal code, and validate based on that.

Thanks a million.
