### ISSUE TITLE
Add the function of importing icon libraries

### ISSUE THREAD

**Issue by gaoachao** [typst/typst#799]
I am wordering if it is possible for typst to add the function of importing icon libraries, such as font-awesome?

**Comment by leo848** [comment]
Isn't it already possible to use these libraries as fonts with their corresponding Unicode icons? E.g. using the font "FontAwesome" for a single character should already work.

**Comment by zicklag** [comment]
I did this super simply like this:

```
#let fa(codepoint) = text(font: "FontAwesome", codepoint)
#let fa-github = fa("\u{f09b}")
#let fa-envelope = fa("\u{f0e0}")
#let fa-map-marker = fa("\u{f041}")
#let fa-suitcase = fa("\u{f0f2}")
```

Somebody could make a template that could be imported with all the icons.

**Comment by duskmoon314** [comment]
> Somebody could make a template that could be imported with all the icons.

Hi, I have just created a repo that provides all free icons with the format `fa-<icon-name>`: https://github.com/duskmoon314/typst-fontawesome

The idea is to use FontAwesome's desktop fonts with a curried function `fa-icon`:

```typst
#let fa-icon(
  name,
  fa-version: "Font Awesome 6",
  fa-set: "Free"
) = text.with(
  font: fa-version + " " + fa-set,
  name
)
```

And function for specific icons is like this:

```typst
#let fa-chess-queen = fa-icon("\u{f445}")
```

The usage would be:

```typst
#fa-chess-queen(fill: blue)
```

Please give it a try and share your thought. 😄

**Comment by laurmaedje** [comment]
Closing this in favor of the package. (It's out of scope for the compiler.)
