### ISSUE TITLE
Docker image not working

### ISSUE THREAD

**Issue by peteole** [typst/typst#800]
The docker image is currently not working:
```
      docker run -it ghcr.io/typst/typst:main
Unable to find image 'ghcr.io/typst/typst:main' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/typst/typst/manifests/main": unauthorized.
See 'docker run --help'.
ole.petersen@QA-M-FLWSCW ~ % docker run ghcr.io/typst/typst:main 
Unable to find image 'ghcr.io/typst/typst:main' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/typst/typst/manifests/main": unauthorized.
See 'docker run --help'.
```

**Comment by adamijak** [comment]
Docker image publish workflow did run successfully but I can not see package in packages. Maybe it has to be made public somehow.

**Comment by laurmaedje** [comment]
We changed the visibility to public. Can you check whether it works now and, if so, close the issue?

**Comment by peteole** [comment]
Thank you! Now the issue changed to the following:
```
docker run ghcr.io/typst/typst:main
Unable to find image 'ghcr.io/typst/typst:main' locally
docker: Error response from daemon: manifest unknown.
See 'docker run --help'.
```

**Comment by SamK** [comment]
Workaround: remove `:main`

**Comment by CronJorian** [comment]
Fix: use `docker run ghcr.io/typst/typst:latest` instead

**Comment by alixmacdonald10** [comment]
Should the readme be updated to suit this or are you planning on reinstating main at some point?

**Comment by laurmaedje** [comment]
I have no idea about docker, but Readme change seems sensible.
