### ISSUE TITLE
Bibliography messes with authors and titles

### ISSUE THREAD

**Issue by binarynoise** [typst/typst#805]
Additionally to #482, typst also changes the capitalization of the book titles and does weird things to authors.

As German is a language with strict capitalization rules this is quite annoying, but it also happens in other languages.

## apa
```
small (author 2023)
mixed (Author 2023)
large (Large Author 2023)
Mixed (2023)
Bibliography
Mixed author . (2023). Mixed title.
mixed Author. (2023). Mixed title.
Large Author. (2023). Large title.
small  author. (2023). Small title.
```

## chicago-author-date
```
small (author 2023)
mixed (Author 2023)
large (Large Author 2023)
Mixed (2023)
Bibliography
Mixed author. 2023. Mixed Title.
Authormixed. 2023. Mixed Title.
Large Author. 2023. Large Title.
authorsmall . 2023. Small Title.
```

## ieee
```
small [1]
mixed [2]
large [3]
Mixed [4]
Bibliography
[1] small author, “Small title,” 2023.
[2] mixed Author, “Mixed title,” 2023.
[3] Large Author, “Large title,” 2023.
[4] Mixed author , “Mixed title,” 2023.
```

## mla
```
small (author 2023)
mixed (Author 2023)
large (Large Author 2023)
Mixed (2023)
Bibliography
Mixed author. Mixed Title. 2023.
Authormixed. Mixed Title. 2023.
Large Author. Large Title. 2023.
authorsmall . Small Title. 2023.
```

I tried to create a demo document which showcase all styles in comparison, but the compiler crashed whenever I added a second bibliography entry, so the [demo](https://typst.app/project/wmT81HGNfg8LnJjs6Y9dNY) only contains one and we need to manually change styles.

**Comment by Jmcjack** [comment]
I have experienced this too. It is a bug (bugs) in hayagriva, Typst's processor for the bibliography. See a related issue here: https://github.com/typst/hayagriva/issues/39

**Comment by laurmaedje** [comment]
> Not sure if this is a separate issue: In some cases it's not only capitalization that is affected; some words in booktitle are also abbreviated or even omitted.

That's intentional because the IEEE citation style wants that.

**Comment by laurmaedje** [comment]
The upstream bug https://github.com/typst/hayagriva/issues/39 is fixed now and hayagriva should now properly respect BibLaTeX's `{}` and its own `verbatim: true`.

**Comment by laurmaedje** [comment]
Things now follow BibLaTeX's precedent and what English citation styles demand. This is of course still not ideal for other languages, but that's a separate issue. I'll leave #1709 open for now.
