### ISSUE TITLE
SVG markers are not being rendered

### ISSUE THREAD

**Issue by danaugrs** [typst/typst#809]
SVG `marker`s such as arrow heads are not rendered.

**Comment by reknih** [comment]
May be fixed by #822

**Comment by LaurenzV** [comment]
Not sure what the current state is, but at least according to the tests, marker should at least render fine once [this PR](https://github.com/typst/svg2pdf/pull/34) gets merged and upstreamed.

**Comment by hrouault** [comment]
I am using typst version 0.11.1 (the latest) and the marker present in a `.svg` figure containing only a single arrow is not rendered.

Here is the source file:
![drawing_arrow](https://github.com/typst/typst/assets/902437/2f237511-ca84-4f6f-a268-270ec214acd4)

Is there something wrong with my source file?

**Comment by LaurenzV** [comment]
Nothing wrong, it's the same as https://github.com/typst/typst/issues/3715 and will be fixed by 0.12.

**Comment by hrouault** [comment]
I didn't see the newer issue. Sorry for reporting this then.

**Comment by LaurenzV** [comment]
No worries!
