### ISSUE TITLE
Border joining

### ISSUE THREAD

**Issue by laurmaedje** [typst/typst#81]
Joined borders (for two different colors) on rectangles have two problems:
- For a very small radius, there is a strange artifact (left side)
- They look bad if they have no radius (right side)

<img width="608" alt="image" src="https://user-images.githubusercontent.com/17899797/191766542-cffe80ce-870c-4932-9910-040f2b155d0e.png">

```
#set rect(stroke: 10pt)
#rect(
  width: 3cm,
  height: 2cm,
  radius: (top-left: 0.1%),
  stroke: (
    left: green,
    top: red,
    rest: blue,
  ),
)
```

**Comment by astrale-sharp** [comment]
I'll take a look at this soon, tomorrow probably

**Comment by antonWetzel** [comment]
My thought a bit about this.
- joining without radius
  - my prefered solution would be 
    - ![image](https://github.com/typst/typst/assets/59712243/7dc86cb2-3ccf-42f1-9f25-172400118fc5)
    - if the stroke width is constant, this is not possible with a simple path, because the connection between the colors is $\sqrt{2}$ times the stroke width
  - one solution is a rounded corner with inner radius $0$
    - ![image](https://github.com/typst/typst/assets/59712243/5c07bfb4-ab51-44c4-8513-e1b1ab2e053f)
  - if some edges can and some can't be joined with a hard corner the mix is strange
    - ![image](https://github.com/typst/typst/assets/59712243/fe15af31-432c-48d5-b1e7-4f3e76d9d3be)
    - but I don't think all edges should be rounded, maybe if some edges in the rect must be rounded, round the others
  - a possible hack to get my prefered look would require multiple line segements at the corners
    - ![image](https://github.com/typst/typst/assets/59712243/4e5a0489-458d-45c7-98ad-7f824642196a)
- for a small radius
  - if the radius is always the inner radius this is not problem
    - example with strike width 10pt and radius 1pt
    - ![image](https://github.com/typst/typst/assets/59712243/497a7b32-0b57-4eed-a56e-4e364c506001)
  - if the radius is the outer radius, this requires also the hack from above for a small radius
