### ISSUE TITLE
How can I input this symbol?

### ISSUE THREAD

**Issue by Eitheages** [typst/typst#813]
I have a tiny question at this point. How can I input a symbol like this?

<img width="30" alt="image" src="https://user-images.githubusercontent.com/93167100/232190911-86cb870a-9eeb-4e27-8348-ac20f64402e7.png">

Thanks very much!

**Comment by Az-21** [comment]
I couldn't find it in the `#sym` general symbols library, so this is a **hacky** way of achieving a similar result with the help of [`limits()_lower^upper`](https://typst.app/docs/reference/math/attach). There might be better ways to achieve this.

```tex
#let implies_star = $limits(arrow.r.double) ^ ast.op$
$ x #implies_star y $
```

![Screenshot 2023-04-15 131659](https://user-images.githubusercontent.com/39803478/232197443-2b212a92-1f06-4364-9896-51302fdb71cb.png)

**Comment by Enivex** [comment]
As far as I'm aware, this is not a unicode symbol, so @Az-21 solution is the best you'll get
