### ISSUE TITLE
Add `#todo` tag

### ISSUE THREAD

**Issue by adamijak** [typst/typst#814]
Add `#todo` tag which shows warning with line number on compilation. It could also show marks on each page of generated document.

**Comment by YannCebron** [comment]
In the meantime:
```
#let todo(msg) = {
  [#text(fill: red, weight: "bold", size: 12pt)[TODO #msg]]
}
```

**Comment by KronosTheLate** [comment]
It would be nice if TODOs were collected into a list that would provide an overview of such tasks, as opposed to scrolling through looking for them. The list would ideally be a hyperlink to the location of the todo note!

**Comment by mazharz** [comment]
@tingerrr Would you mind showing an example usage? I'm curious how would one use the outlined-todos function.

**Comment by tingerrr** [comment]
Just calling it as a normal function. I realize that it's quite specific to my use case, it relies on the act that TODOs in my document only appear after the first heading and that all headings have numbering. It does this to group TODOs together for each section.

You could change this to have `todo` emit a custom figure (with `kind: "todo"`) and then use `outline(target: figure.where(kind: "todo"))`. This is how I would've likely done it today, but I wrote this a while ago.

**Comment by mazharz** [comment]
@tingerrr Thanks, that makes sense, It was a nice demonstration of making dynamic and interesting things in Typst.

**Comment by vtta** [comment]
It seems that `latex`'s `todontoes` package has an elegant design for showing todos, which I personally think is worth considering when adding this feature in typst.
In the main text, a todo is highlighted and the description for that todo is shown inside a connected sidenode.
In the front matter, a dedicated outline can be added to list all the todos.

**Comment by Andrew15-5** [comment]
https://typst.app/universe/package/big-todo

**Comment by laurmaedje** [comment]
I think there are the following options for a built-in `todo` function:

- Only produces output, no warning (obviously not great)

- Produces a warning when executed, but shows nothing (effectively a `warn` function which we've deliberality not yet shipped because of lack of warning supression)

- Produces a warning when executed and shows something if the resulting content is part of the document

- Shows something and produces a warning, but only if the resulting content is part of the document

I feel like none of these four properly cover both TODOs in code and in prose. Moreover, none of the above would properly raise a warning if the code is never reached. 

Meanwhile, he low-tech solution of `// TODO` in combination with proper web app / LSP integration can work even for code that never runs. It does not support outputting TODOs into the document, but I'm not sure there is a big use case for this if there's a TODO panel in the editor, to be honest.

**Comment by wrzian** [comment]
Would it be too much to add `todo` as a statement keyword?

Then we could do: if rendered, creates a big ole red TODO (of course still with set/show rules). But if not rendered (or even evaluated), still remains accessible when we iterate over the AST. Then TODOs could generate a third type of output message separate from warnings/errors?

First draft syntax:
```typ
// plain
#todo
// with content
#todo: [fix me]
```
(but highlighted in red just like `context`)

Then this comment would just be built-in (i.e. trivially usable, even from the CLI):
> It would be nice if TODOs were collected into a list that would provide an overview of such tasks, as opposed to scrolling through looking for them. The list would ideally be a hyperlink to the location of the todo note!

This is obviously incredibly special-cased for what probably _could_ be a function. But aren't todo statements special in general? Like, this is an incredibly useful feature that does what users probably want and if IDEs are already going to special-case TODOs, then we reduce $O(n)$ work down to $O(1)$.

TODO: Look for Prior Art in other languages for design ideas if we make it a statement.

**Comment by KronosTheLate** [comment]
With [big-todo](https://typst.app/universe/package/big-todo) and [drafting](https://typst.app/universe/package/drafting), both of which appear when one [searches the typst universe for "todo"](https://typst.app/universe/search?q=todo), I do not really see the need for a built-in todo functionality. It would be nice to have, but people will want different flavours of it and ever more functionality, and having something in the language itself makes development slow down, and makes opinionated experiments difficult. IMO, this can be closed given the packages available.

**Comment by laurmaedje** [comment]
With consideration of the points raised above, I'll close this as "best solved outside of the language".

**Comment by londi** [comment]
unfortunately big-todo is broken by the newest typst version :(
