### ISSUE TITLE
Regression in line spacing for `raw` elements

### ISSUE THREAD

**Issue by epbuennig** [typst/typst#817]
I was adapting a temporary solution for line numbers by @mpizenberg in https://github.com/typst/typst/issues/344#issuecomment-1493820681 for my own use case.

I noticed that the layout didn't quite work on my local compiler (`1e948f7fa`), where it was floating off due to different spacing to the current web app (`v0.2.0`, `fe2640c55`), somewhere inside `fe2640c55..1e948f7fa` a commit introduced a regression that breaks this particular implementation. My assumption, purely by reading the commit messages, is that it may have been `ff16f3fb3` (#701) or perhaps less likely `46ce9c94e`.

If this new line spacing is the new intended behavior then this issue can probably be closed, but without a solution for #344, referencing lines in code blocks will continue to be a pain point for me.

I've included a [document](https://typst.app/project/raXlEQKcILXU0wX8QGJH9S) that produces the regression for ease of bisecting, I would do it myself if I had the time. Notice the misaligned line numbers on the bad case.

The good case (`v0.2.0`, `fe2640c55`):
![image](https://user-images.githubusercontent.com/103939966/232210136-39eda884-432d-4b84-b147-5c438ec30285.png)

The bad case  (`1e948f7fa`):
![image](https://user-images.githubusercontent.com/103939966/232210211-c856d7d0-9b63-4536-a045-14fde30cf1e9.png)

**Comment by Icxolu** [comment]
I did a bisect on this. This change was introduced by 89cf4054d61d296245b34a20f9ad0b749c0f83e2, specifically by the change of the `PartialEq` impl for [`StyleChain`](https://github.com/typst/typst/blob/480ad7670b19457a3163d59e948bfac5eacd9472/src/model/styles.rs#L743). It does not include the equality on equal hash anymore like it used to. Whether this is the intended behavior I can not tell, but adding `|| crate::util::hash128(self) == crate::util::hash128(other)` back in, fixes the issue

**Comment by epbuennig** [comment]
While the behavior changed, it did not impact anything other than somewhat hacky solutions like these. I'll consider this closed as wont-fix, since there are working implementations available as packages.
