### ISSUE TITLE
API to distinguish between pt-length and em-length?

### ISSUE THREAD

**Issue by user202729** [typst/typst#819]
Currently these are two "different" types but there's no way (that I can find on https://typst.app/docs/reference/types/length/) to distinguish them apart from `repr()`.

**Comment by PgBiel** [comment]
Note that you can arbitrarily combine them (`5em + 2pt` for e.g.) and still have a `length`. Regarding separating the "em-part" from the "pt-part", keep an eye on https://github.com/typst/typst/pull/790.

**Comment by laurmaedje** [comment]
Fixed via #790.
