### ISSUE TITLE
Wrong placement for automatically sized container

### ISSUE THREAD

**Issue by laurmaedje** [typst/typst#82]
```
#rect(inset: 10pt, width: 100%)[
  #place(bottom + right)[Hi]
  Hello
  #v(2cm)
  World
]
```

**Comment by astrale-sharp** [comment]
This gives 
![82](https://user-images.githubusercontent.com/53686698/230999684-16c8ab03-3c8b-4c65-88c8-d9a4c25f0725.png)
What's expected instead?

**Comment by Enivex** [comment]
Presumably Hi should be bottom right and not top right.

**Comment by laurmaedje** [comment]
Related: #685
