### ISSUE TITLE
(...)|_a^b gives parsing error?

### ISSUE THREAD

**Issue by user202729** [typst/typst#821]
```
//$ ((sin x)/y)|_1^2 $  // error

$ lr(((sin x)/y)|)_1^2 $  // works as expected and `|` resizes correctly
```

I think this notation is quite common (for evaluating integrals).

**Comment by Enivex** [comment]
`$ ((sin x)/y)\|_1^2 $` works, though the | obviously won't be scaled automatically. That's somewhat unavoidable, since there is no matching delimiter.

**Comment by user202729** [comment]
The second example in my post (oddly enough) also works. Although here in Typst `.` and `""` also work as "invisible delimiter".

**Comment by laurmaedje** [comment]
This doesn't error anymore as of https://github.com/typst/typst/commit/fe402759c03eb93cefc2879e751b8e732891bd3e because automatic matching for fences was removed. There are too many false positives.
