### ISSUE TITLE
Make inline equations breakable

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#826]
Title. Currently a very long equation will overflow, but it would be better to automatically break up the equation.

**Comment by owiecc** [comment]
I think I would prefer an overflow warning. You typeset with a specific base font size for a legibility and consistency reasons. Equations often contain subscript or superscript already set with a very small font size. Decreasing that automatically is not a good default IMO. 

Maybe an autoscale option with min-font-size would be good for this purpose.

**Comment by Enivex** [comment]
> Title. Currently a very long equation will overflow, but it would be better to auto shrink the math font size.

If it overflows you need to modify your equation in such a way that it fits. Changing the font size would break every convention.

**Comment by SUPERCILEX** [comment]
> modify your equation in such a way that it fits

What if you can't or don't want to? ~Is it that unreasonable to shrink-to-fit?~ Hmmm, the internet seems to agree with you. According to [this](https://tug.org/TUGboat/tb18-3/tb56down.pdf), you're supposed to break up equations. So then I'll change this feature request to auto break up a long equation.

**Comment by SUPERCILEX** [comment]
I've thought about this some more and I don't think you can design an algorithm that will break up the equation in the right places. For example, suppose your equation includes a series of summations, some of which are related. The human would know which ones and break the line so as to split the sums with each line keeping related stuff together, but the computer can't know this. So just do it manually.

**Comment by NicoWeio** [comment]
If I understood it correctly, #1826 would solve this.

**Comment by ideesnoires** [comment]
i'm not sure if this is related but if i force a linebreak inside inline equation the order of rendered input lines is wrong:

`
is $tilde$ symmetric?
$(a,b) tilde (c,d) = (a-c, b-d) = (t,t) =\ = (t,t) = (c-a, d-b) = (c,d) tilde (a,b)$
`
produces:
<img width="432" alt="image" src="https://github.com/typst/typst/assets/608899/cdc3147f-281d-4df2-80ae-06aea42d29c6">

**Comment by Enivex** [comment]
> i'm not sure if this is related but if i force a linebreak inside inline equation the order of rendered input lines is wrong:
> 
> `
> is $tilde$ symmetric?
> $(a,b) tilde (c,d) = (a-c, b-d) = (t,t) =\ = (t,t) = (c-a, d-b) = (c,d) tilde (a,b)$
> `
> produces:
> <img width="432" alt="image" src="https://github.com/typst/typst/assets/608899/cdc3147f-281d-4df2-80ae-06aea42d29c6">
> 
> 

It is somewhat related. Inline equations consist of a single box currently, so line breaking will just give you a box with two lines in it.

**Comment by ideesnoires** [comment]
should i open a new ticket for this? if i change this to a not-inline-equation it renders as expected below the preceding text.

**Comment by Enivex** [comment]
> should i open a new ticket for this? if i change this to a not-inline-equation it renders as expected below the preceding text.

If inline equations become breakable, then it would be natural for an explicit linebreak to do what you want. I don't think a separate issue is required.

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/2938
