### ISSUE TITLE
Anyway to make double quotes be stylized from string variable?

### ISSUE THREAD

**Issue by dsantiago** [typst/typst#829]
If I have something like this:

```rust
#let title = "\"My Title \""
```

when rendered, the  doublequotes are not stylized with `#smartquotes()`

**Comment by Enivex** [comment]
You could insert the actual quotes you want instead of trying to rely on smart quotes, but that's probably not the answer you're looking for.

**Comment by dsantiago** [comment]
Yeah @Enivex I did it, but i felt that it was not really the right to do... I dunno if that's the practice with typst... if it is, the question is solved...

**Comment by Enivex** [comment]
There probably should be a way to do what you want to do, but the problem isn't directly with strings. The issue is that \" is the literal character. Maybe there should be some function that can be called on strings to typeset it as if the symbols were written directly in the source.

**Comment by dsantiago** [comment]
Yeah, you sense the point, I also tried to pass to the function a **content** in place of **string** for my **title** variable so the quotes could be interpreted.

```rust
let title = ["My Title"]
```
instead of:

```rust
let title = "My Title"
```

But than i could not convert content to string, to pass to ducmento function for example... the str() function does not accept content types.

But overall, even still learning, I am satisfied with this typst project so far...

**Comment by laurmaedje** [comment]
In general, strings always render exactly as given so that you have full control if you use them. I'm not really sure if there's much we can do here.

**Comment by dsantiago** [comment]
Fair enough. @laurmaedje just for curiosity purpose, any tip in how i can concatenate the smartquotes with the string. That would solve it.

**Comment by laurmaedje** [comment]
> how i can concatenate the smartquotes with the string

I'm not sure what you mean.

**Comment by Enivex** [comment]
I _think_ what you're looking for is

```
#let title = "My title"
#let title_with_smartquotes = ["#title"]
```

**Comment by dsantiago** [comment]
> I _think_ what you're looking for is
> 
> ```
> #let title = "My Title"
> #let title_with_smartquotes = ["#title"]
> ```

Yeah but now, it's a content type. How to convert it back to the string type?

**Comment by Enivex** [comment]
Do you actually need it to be string type? In contexts where a strong is required, like document(), just use the original string.

**Comment by dsantiago** [comment]
I see, I was adding double quotes in the template, but after that I prefered to add it directly in the title as it's part from it. maybe the best approach is this:

```rust
let title = "\"My Title\""
show "\"": ["]
title
```

**Comment by Enivex** [comment]
It seems unusual to me to consider quotation marks to be a part of the actual title.

**Comment by dsantiago** [comment]
Yeah agree,  it's a review from a book for my masters homework. But ofc it's unusual.
