### ISSUE TITLE
Closure syntax

### ISSUE THREAD

**Issue by Marmare314** [typst/typst#839]
The current closure syntax is `(x, y) => x + y` and `x => 2 * x`. Because the parser is implemented without lookahead this makes parsing them difficult as `(x, y)` could also be an array and `x` may also be a variable until we encounter `=>`. That is why the `collection` function exists, which "pre-parses" dictionaries, arrays, parameters and arguments. So we can first "pre-parse" the collection and then validate based on if a `=>` follows.
Considering #838 the `collection` function would only get more complicated, since now we also have to parse destructuring patterns as elements/keys.
So I think a new syntax could make the code a bit easier to follow.

Maybe more importantly: I think with #838 the current syntax could get hard to read at times:
```rust
a.enumerate().map(((i, x)) => x)
```

So I think it would be better to switch to the following syntax:
```rust
|x| => 2 * x
|x, y| => x + y
|x: 3, y: 4, ..z| => x + y
```

**Comment by astrale-sharp** [comment]
I love the rustyness ;)

An alternative syntax discussed while doing pipe : 
`a.enumerate().map( (i, x).. => x)`
It makes sense in pipe but it's not nice in maps, I prefer your solution.
@Dherse ?

**Comment by dsantiago** [comment]
For now a possible solution is

```rust
a.enumerate().map(x => x.at(1))
```

**Comment by Dherse** [comment]
> I love the rustyness ;)
> 
> An alternative syntax discussed while doing pipe : `a.enumerate().map( (i, x).. => x)` It makes sense in pipe but it's not nice in maps, I prefer your solution. @Dherse ?

My idea with the `(i, x)..` was simply to avoid redoing the syntax, however, I do think that a rustier, less Javascripty syntax is imo generally better. Then again, adding basic look ahead capabilities to the parser shouldn't be the hardest thing to do either ;)

**Comment by Marmare314** [comment]
Because we don't actually need to parse patterns as keys and #831 simplifies parsing of patterns a bit, the first part is not much of an issue anymore.

**Comment by laurmaedje** [comment]
I think the current closure syntax is fine.
