### ISSUE TITLE
Possible need of more functions for the array type

### ISSUE THREAD

**Issue by dsantiago** [typst/typst#840]
HI have the need to sum all values in an array... I could solve it via `fold` but a dedicated sum() function would be really needed I think.

```rust
let total = range(1, size).fold(0, (a, b) => a + b)  // what works now
let total = range(1, size).sum() // preferred
```

**Comment by Enivex** [comment]
If it's that specific array the sum is always going to be size*(size-1)/2.

**Comment by dsantiago** [comment]
> If it's that specific array the sum is always going to be size*(size-1)/2.

The range used was just for example purpose... we can imagine other example with `range(32, 57)`...

**Comment by PgBiel** [comment]
`.sum()` would also be useful for joining other joinable types, such as `content` (and joining is so universal in typst anyway that this seems like a must-have to me).

**Comment by laurmaedje** [comment]
> .sum() would also be useful for joining other joinable types, such as content

Note that `.join()` exists already. But sum would still be useful for numbers.
