### ISSUE TITLE
repr inconsistent parse of 

### ISSUE THREAD

**Issue by astrale-sharp** [typst/typst#841]
`repr[_content_]` gives `#emph(body: [read the questions!])`
it would be better if it gave `#emph([read the questions!])` or `#emph[read the questions!]`
Same could be said of strong !

+ It is more consistent
+ you can parse it with eval

**Comment by PgBiel** [comment]
The result of `repr` is according to the internal representation of the object. You can probably use regex to parse it.

**Comment by user202729** [comment]
It's probably better to avoid using repr for any purpose other than debugging anyway.

(in TeX, the analog is `\meaning` but there's absolutely no API to inspect a macro "definition" in general otherwise, so code is written to inspect `\meaning` which is quite flaky)

**Comment by PgBiel** [comment]
> It's probably better to avoid using repr for any purpose other than debugging anyway.

Indeed; prefer to use field access. (See https://github.com/typst/typst/pull/790 for a WIP PR to add some missing fields to types.)

**Comment by laurmaedje** [comment]
I will add a note that the `repr` output is not considered stable.

**Comment by laurmaedje** [comment]
It displays `body:` because that is the name of the field under which you can access it. It is not 1-1 parseable and that would be very difficult to achieve.
