### ISSUE TITLE
conditional set doesn't work

### ISSUE THREAD

**Issue by astrale-sharp** [typst/typst#842]
#if false {set page(paper: "presentation-16-9")}

causes only the first page to be set which is not intuitive !

**Comment by laurmaedje** [comment]
The set rule is only in effect until the end of the block. You have two options:

Built-in conditional set rule:
```
#set page(paper: "presentation-16-9") if false
```

For more flexibility, you can always use a show rule:
```
#show: it => {
  if false {
    set page(paper: "presentation-16-9")
    it
  } else {
    it
  }
}
```
