### ISSUE TITLE
Should element func be exposed, if so how?

### ISSUE THREAD

**Issue by astrale-sharp** [typst/typst#850]
Doing `#show heading: it => counter(it.func())` is not intuituve, i was looking for a kind of id or something, could we expose it differently to the users, maybe through another name?

Also since it's a function you might wanna know what it does so you could try
`#show heading: it => it.func()()` but it misses a body (not a big deal)
then you try 
`#show heading: it => it.func()([])` and it crashes :rolling_eyes:
whereas `#show heading: it => it.func()[]` complains it has an unexpected argument.

**Comment by laurmaedje** [comment]
I don't really understand what you're trying to do.
