### ISSUE TITLE
Unintuitive names

### ISSUE THREAD

**Issue by astrale-sharp** [typst/typst#851]
This issue is taken from bugs-and-features,
Lists any syntax found unintuitive, difficult to follow, or hard to discover, so it can be improved.

Note : Below is the unedited unformatted discord discussion, help to format would be appreciated.

**Comment by astrale-sharp** [comment]
dot being a period instead of the dot product. If I wanted a period I would type a period. The lack of cdot (the LaTeX alternative) makes this even more confusing. The fact that this is hidden behind a method that I can only call with dot.op is completely inexplicable to me. To be fair, I have never been a fan of OOP. That being said this is a bridge too far; methods should be for getting the properties of an object, or for cases where an object is clearly the one “doing” something. I have no idea what the dot itself is “doing” (yeeting itself up half a line?)

**Comment by astrale-sharp** [comment]
Maximum Limelihood Estimator: alef saves one character over aleph but is a substantially less common spelling, especially in math.

**Comment by astrale-sharp** [comment]
Maximum Limelihood Estimator: nabla feels less intuitive than grad, but I can totally understand if that’s just a preference thing. (Anyone else have a preference for grad?)

**Comment by astrale-sharp** [comment]
Maximum Limelihood Estimator: In general I feel like a line break in a `$$` block should equal a line break in the displayed equation, unless I specify otherwise; usually when I start a new line I’m doing that because I want to move to the next line of the equation. I frequently forget to add `\`.

**Comment by SUPERCILEX** [comment]
@laurmaedje This was resolved by https://github.com/typst/typst/pull/747

**Comment by laurmaedje** [comment]
Not everything from the discussion is addressed, but if there's interest in discussing it further, this would fit better in the discussion tab. We can have issues for concrete proposals.

**Comment by K4LCIFER** [comment]
I would like to second that writing `arrow(x)` for an x with an arrow on top is unintuitive and that it should instead be `vec(x)`. I elaborated on the idea [here](https://github.com/typst/typst/discussions/3538).
