### ISSUE TITLE
Row matrices and symbols

### ISSUE THREAD

**Issue by astrale-sharp** [typst/typst#852]
[Transferred from Discord](https://discord.com/channels/1054443721975922748/1096022635709739109/1096022635709739109).

I think i found a bug with row vectors and symbols. I tried rendering these three matrices:
```
$ mat(B, A B) $
$ mat(B, A B, dots) $
$ mat(B, A B, dots; 1, 2, 3) $
```
The first and the third compile fine, but the second one gives me an error saying expected array, found content.

**Comment by PgBiel** [comment]
As a workaround for now, please use
`$ mat(B, A B, dots;) $`
