### ISSUE TITLE
Need support for CodeRunner on macOS

### ISSUE THREAD

**Issue by 1939323749** [typst/typst#853]
Works fine on **CodeRunner**, even live preview, but **no syntax support**. It supports ***.tmLanguage** file but only typst.tmLanguage.json in tools/support/, can anyone convert it to a *.tmLanguage file to support CodeRunner? Thank you!

**Comment by AlistairKeiller** [comment]
Does converting to .tmLanguage just mean converting the content from json to XML? Does this work?

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<root>
  <name>typst</name>
  <patterns>
    <include>#markup</include>
  </patterns>
  <repository>
    <comments>
      <patterns>
        <name>comment.block.typst</name>
        <begin>/\*</begin>
        <end>\*/</end>
        <captures>
          <0>
            <name>punctuation.definition.comment.typst</name>
          </0>
        </captures>
        <patterns>
          <include>#comments</include>
        </patterns>
      </patterns>
      <patterns>
        <name>comment.line.double-slash.typst</name>
        <begin>(?&lt;!:)//</begin>
        <end></end>
        <beginCaptures>
          <0>
            <name>punctuation.definition.comment.typst</name>
          </0>
        </beginCaptures>
        <patterns>
          <include>#comments</include>
        </patterns>
      </patterns>
    </comments>
    <common>
      <patterns>
        <include>#comments</include>
      </patterns>
    </common>
    <markup>
      <patterns>
        <include>#common</include>
      </patterns>
      <patterns>
        <name>constant.character.escape.content.typst</name>
        <match>\\([\\/\[\]{}#*_=~`$-.]|u\{[0-9a-zA-Z]*\}?)</match>
      </patterns>
      <patterns>
        <name>punctuation.definition.linebreak.typst</name>
        <match>\\</match>
      </patterns>
      <patterns>
        <name>punctuation.definition.nonbreaking-space.typst</name>
        <match>~</match>
      </patterns>
      <patterns>
        <name>punctuation.definition.shy.typst</name>
        <match>-\?</match>
      </patterns>
      <patterns>
        <name>punctuation.definition.em-dash.typst</name>
        <match>---</match>
      </patterns>
      <patterns>
        <name>punctuation.definition.en-dash.typst</name>
        <match>--</match>
      </patterns>
      <patterns>
        <name>punctuation.definition.ellipsis.typst</name>
        <match>\.\.\.</match>
      </patterns>
      <patterns>
        <name>constant.symbol.typst</name>
        <match>:([a-zA-Z0-9]+:)+</match>
      </patterns>
      <patterns>
        <name>markup.bold.typst</name>
        <begin>(^\*|\*$|((?&lt;=\W|_)\*)|(\*(?=\W|_)))</begin>
        <end>(^\*|\*$|((?&lt;=\W|_)\*)|(\*(?=\W|_)))|
|(?=\])</end>
        <captures>
          <0>
            <name>punctuation.definition.bold.typst</name>
          </0>
        </captures>
        <patterns>
          <include>#markup</include>
        </patterns>
      </patterns>
      <patterns>
        <name>markup.italic.typst</name>
        <begin>(^_|_$|((?&lt;=\W|_)_)|(_(?=\W|_)))</begin>
        <end>(^_|_$|((?&lt;=\W|_)_)|(_(?=\W|_)))|
|(?=\])</end>
        <captures>
          <0>
            <name>punctuation.definition.italic.typst</name>
          </0>
        </captures>
        <patterns>
          <include>#markup</include>
        </patterns>
      </patterns>
      <patterns>
        <name>markup.underline.link.typst</name>
        <match>https?://[0-9a-zA-Z~/%#&amp;=&#x27;,;\.\+\?]*</match>
      </patterns>
      <patterns>
        <name>markup.raw.block.typst</name>
        <begin>`{3,}</begin>
        <end>\0</end>
        <captures>
          <0>
            <name>punctuation.definition.raw.typst</name>
          </0>
        </captures>
      </patterns>
      <patterns>
        <name>markup.raw.inline.typst</name>
        <begin>`</begin>
        <end>`</end>
        <captures>
          <0>
            <name>punctuation.definition.raw.typst</name>
          </0>
        </captures>
      </patterns>
      <patterns>
        <name>string.other.math.typst</name>
        <begin>\$</begin>
        <end>\$</end>
        <captures>
          <0>
            <name>punctuation.definition.string.math.typst</name>
          </0>
        </captures>
      </patterns>
      <patterns>
        <name>markup.heading.typst</name>
        <contentName>entity.name.section.typst</contentName>
        <begin>^\s*=+\s+</begin>
        <end>
|(?=&lt;)</end>
        <beginCaptures>
          <0>
            <name>punctuation.definition.heading.typst</name>
          </0>
        </beginCaptures>
        <patterns>
          <include>#markup</include>
        </patterns>
      </patterns>
      <patterns>
        <name>punctuation.definition.list.unnumbered.typst</name>
        <match>^\s*-\s+</match>
      </patterns>
      <patterns>
        <name>punctuation.definition.list.numbered.typst</name>
        <match>^\s*([0-9]*\.|\+)\s+</match>
      </patterns>
      <patterns>
        <match>^\s*(/)\s+([^:]*:)</match>
        <captures>
          <1>
            <name>punctuation.definition.list.description.typst</name>
          </1>
          <2>
            <name>markup.list.term.typst</name>
          </2>
        </captures>
      </patterns>
      <patterns>
        <name>entity.other.label.typst</name>
        <match>&lt;[[:alpha:]_][[:alnum:]_-]*&gt;</match>
        <captures>
          <1>
            <name>punctuation.definition.label.typst</name>
          </1>
        </captures>
      </patterns>
      <patterns>
        <name>entity.other.reference.typst</name>
        <match>(@)[[:alpha:]_][[:alnum:]_-]*</match>
        <captures>
          <1>
            <name>punctuation.definition.reference.typst</name>
          </1>
        </captures>
      </patterns>
      <patterns>
        <begin>(#)(let|set|show)\b</begin>
        <end>
|(;)|(?=])</end>
        <beginCaptures>
          <0>
            <name>keyword.other.typst</name>
          </0>
          <1>
            <name>punctuation.definition.keyword.typst</name>
          </1>
        </beginCaptures>
        <endCaptures>
          <1>
            <name>punctuation.terminator.statement.typst</name>
          </1>
        </endCaptures>
        <patterns>
          <include>#code</include>
        </patterns>
      </patterns>
      <patterns>
        <name>keyword.other.typst</name>
        <match>(#)(as|in)\b</match>
        <captures>
          <1>
            <name>punctuation.definition.keyword.typst</name>
          </1>
        </captures>
      </patterns>
      <patterns>
        <begin>((#)if|(?&lt;=(}|])\s*)else)\b</begin>
        <end>
|(?=])|(?&lt;=}|])</end>
        <beginCaptures>
          <0>
            <name>keyword.control.conditional.typst</name>
          </0>
          <2>
            <name>punctuation.definition.keyword.typst</name>
          </2>
        </beginCaptures>
        <patterns>
          <include>#code</include>
        </patterns>
      </patterns>
      <patterns>
        <begin>(#)(for|while)\b</begin>
        <end>
|(?=])|(?&lt;=}|])</end>
        <beginCaptures>
          <0>
            <name>keyword.control.loop.typst</name>
          </0>
          <1>
            <name>punctuation.definition.keyword.typst</name>
          </1>
        </beginCaptures>
        <patterns>
          <include>#code</include>
        </patterns>
      </patterns>
      <patterns>
        <name>keyword.control.loop.typst</name>
        <match>(#)(break|continue)\b</match>
        <captures>
          <1>
            <name>punctuation.definition.keyword.typst</name>
          </1>
        </captures>
      </patterns>
      <patterns>
        <begin>(#)(import|include|export)\b</begin>
        <end>
|(;)|(?=])</end>
        <beginCaptures>
          <0>
            <name>keyword.control.import.typst</name>
          </0>
          <1>
            <name>punctuation.definition.keyword.typst</name>
          </1>
        </beginCaptures>
        <endCaptures>
          <1>
            <name>punctuation.terminator.statement.typst</name>
          </1>
        </endCaptures>
        <patterns>
          <include>#code</include>
        </patterns>
      </patterns>
      <patterns>
        <name>keyword.control.flow.typst</name>
        <match>(#)(return)\b</match>
        <captures>
          <1>
            <name>punctuation.definition.keyword.typst</name>
          </1>
        </captures>
      </patterns>
      <patterns>
        <comment>Function name</comment>
        <name>entity.name.function.typst</name>
        <match>((#)[[:alpha:]_][[:alnum:]_-]*!?)(?=\[|\()</match>
        <captures>
          <2>
            <name>punctuation.definition.function.typst</name>
          </2>
        </captures>
      </patterns>
      <patterns>
        <comment>Function arguments</comment>
        <begin>(?&lt;=#[[:alpha:]_][[:alnum:]_-]*!?)\(</begin>
        <end>\)</end>
        <captures>
          <0>
            <name>punctuation.definition.group.typst</name>
          </0>
        </captures>
        <patterns>
          <include>#arguments</include>
        </patterns>
      </patterns>
      <patterns>
        <name>entity.other.interpolated.typst</name>
        <match>(#)[[:alpha:]_][.[:alnum:]_-]*</match>
        <captures>
          <1>
            <name>punctuation.definition.variable.typst</name>
          </1>
        </captures>
      </patterns>
      <patterns>
        <name>meta.block.content.typst</name>
        <begin>#</begin>
        <end>\s</end>
        <patterns>
          <include>#code</include>
        </patterns>
      </patterns>
    </markup>
    <code>
      <patterns>
        <include>#common</include>
      </patterns>
      <patterns>
        <name>meta.block.code.typst</name>
        <begin>{</begin>
        <end>}</end>
        <captures>
          <0>
            <name>punctuation.definition.block.code.typst</name>
          </0>
        </captures>
        <patterns>
          <include>#code</include>
        </patterns>
      </patterns>
      <patterns>
        <name>meta.block.content.typst</name>
        <begin>\[</begin>
        <end>\]</end>
        <captures>
          <0>
            <name>punctuation.definition.block.content.typst</name>
          </0>
        </captures>
        <patterns>
          <include>#markup</include>
        </patterns>
      </patterns>
      <patterns>
        <name>comment.line.double-slash.typst</name>
        <begin>//</begin>
        <end></end>
        <beginCaptures>
          <0>
            <name>punctuation.definition.comment.typst</name>
          </0>
        </beginCaptures>
      </patterns>
      <patterns>
        <name>punctuation.separator.colon.typst</name>
        <match>:</match>
      </patterns>
      <patterns>
        <name>punctuation.separator.comma.typst</name>
        <match>,</match>
      </patterns>
      <patterns>
        <name>keyword.operator.typst</name>
        <match>=&gt;|\.\.</match>
      </patterns>
      <patterns>
        <name>keyword.operator.relational.typst</name>
        <match>==|!=|&lt;=|&lt;|&gt;=|&gt;</match>
      </patterns>
      <patterns>
        <name>keyword.operator.assignment.typst</name>
        <match>\+=|-=|\*=|/=|=</match>
      </patterns>
      <patterns>
        <name>keyword.operator.arithmetic.typst</name>
        <match>\+|\*|/|(?&lt;![[:alpha:]_][[:alnum:]_-]*)-(?![:alnum:]_-]*[[:alpha:]_])</match>
      </patterns>
      <patterns>
        <name>keyword.operator.word.typst</name>
        <match>\b(and|or|not)\b</match>
      </patterns>
      <patterns>
        <name>keyword.other.typst</name>
        <match>\b(let|as|in|set|show)\b</match>
      </patterns>
      <patterns>
        <name>keyword.control.conditional.typst</name>
        <match>\b(if|else)\b</match>
      </patterns>
      <patterns>
        <name>keyword.control.loop.typst</name>
        <match>\b(for|while|break|continue)\b</match>
      </patterns>
      <patterns>
        <name>keyword.control.import.typst</name>
        <match>\b(import|include|export)\b</match>
      </patterns>
      <patterns>
        <name>keyword.control.flow.typst</name>
        <match>\b(return)\b</match>
      </patterns>
      <patterns>
        <include>#constants</include>
      </patterns>
      <patterns>
        <comment>Function name</comment>
        <name>entity.name.function.typst</name>
        <match>\b[[:alpha:]_][[:alnum:]_-]*!?(?=\[|\()</match>
      </patterns>
      <patterns>
        <comment>Function name</comment>
        <name>entity.name.function.typst</name>
        <match>(?&lt;=\bshow\s*)\b[[:alpha:]_][[:alnum:]_-]*(?=\s*[:.])</match>
      </patterns>
      <patterns>
        <comment>Function arguments</comment>
        <begin>(?&lt;=\b[[:alpha:]_][[:alnum:]_-]*!?)\(</begin>
        <end>\)</end>
        <captures>
          <0>
            <name>punctuation.definition.group.typst</name>
          </0>
        </captures>
        <patterns>
          <include>#arguments</include>
        </patterns>
      </patterns>
      <patterns>
        <name>variable.other.typst</name>
        <match>\b[[:alpha:]_][[:alnum:]_-]*\b</match>
      </patterns>
      <patterns>
        <name>meta.group.typst</name>
        <begin>\(</begin>
        <end>\)|(?=;)</end>
        <captures>
          <0>
            <name>punctuation.definition.group.typst</name>
          </0>
        </captures>
        <patterns>
          <include>#code</include>
        </patterns>
      </patterns>
    </code>
    <constants>
      <patterns>
        <name>constant.language.none.typst</name>
        <match>\bnone\b</match>
      </patterns>
      <patterns>
        <name>constant.language.auto.typst</name>
        <match>\bauto\b</match>
      </patterns>
      <patterns>
        <name>constant.language.boolean.typst</name>
        <match>\b(true|false)\b</match>
      </patterns>
      <patterns>
        <name>constant.numeric.length.typst</name>
        <match>\b(\d*)?\.?\d+([eE][+-]?\d+)?(mm|pt|cm|in|em)\b</match>
      </patterns>
      <patterns>
        <name>constant.numeric.angle.typst</name>
        <match>\b(\d*)?\.?\d+([eE][+-]?\d+)?(rad|deg)\b</match>
      </patterns>
      <patterns>
        <name>constant.numeric.percentage.typst</name>
        <match>\b(\d*)?\.?\d+([eE][+-]?\d+)?%</match>
      </patterns>
      <patterns>
        <name>constant.numeric.fr.typst</name>
        <match>\b(\d*)?\.?\d+([eE][+-]?\d+)?fr</match>
      </patterns>
      <patterns>
        <name>constant.numeric.integer.typst</name>
        <match>\b(0x[0-9a-zA-Z]+|(0b|0o)?\d+)\b</match>
      </patterns>
      <patterns>
        <name>constant.numeric.float.typst</name>
        <match>\b(\d*)?\.?\d+([eE][+-]?\d+)?\b</match>
      </patterns>
      <patterns>
        <name>string.quoted.double.typst</name>
        <begin>&quot;</begin>
        <end>&quot;</end>
        <captures>
          <0>
            <name>punctuation.definition.string.typst</name>
          </0>
        </captures>
        <patterns>
          <name>constant.character.escape.string.typst</name>
          <match>\\([\\&quot;nrt]|u\{?[0-9a-zA-Z]*\}?)</match>
        </patterns>
      </patterns>
      <patterns>
        <name>string.other.math.typst</name>
        <begin>\$</begin>
        <end>\$</end>
        <captures>
          <0>
            <name>punctuation.definition.string.math.typst</name>
          </0>
        </captures>
      </patterns>
    </constants>
    <arguments>
      <patterns>
        <name>variable.parameter.typst</name>
        <match>\b[[:alpha:]_][[:alnum:]_-]*(?=:)</match>
      </patterns>
      <patterns>
        <include>#code</include>
      </patterns>
    </arguments>
  </repository>
  <scopeName>source.typst</scopeName>
</root>
```

**Comment by 1939323749** [comment]
> Does converting to .tmLanguage just mean converting the content from json to XML? Does this work?
> 
> ```
> <?xml version="1.0" encoding="UTF-8" ?>
> <root>
>   <name>typst</name>
>   <patterns>
>     <include>#markup</include>
>   </patterns>
>   <repository>
>     <comments>
>       <patterns>
>         <name>comment.block.typst</name>
>         <begin>/\*</begin>
>         <end>\*/</end>
>         <captures>
>           <0>
>             <name>punctuation.definition.comment.typst</name>
>           </0>
>         </captures>
>         <patterns>
>           <include>#comments</include>
>         </patterns>
>       </patterns>
>       <patterns>
>         <name>comment.line.double-slash.typst</name>
>         <begin>(?&lt;!:)//</begin>
>         <end></end>
>         <beginCaptures>
>           <0>
>             <name>punctuation.definition.comment.typst</name>
>           </0>
>         </beginCaptures>
>         <patterns>
>           <include>#comments</include>
>         </patterns>
>       </patterns>
>     </comments>
>     <common>
>       <patterns>
>         <include>#comments</include>
>       </patterns>
>     </common>
>     <markup>
>       <patterns>
>         <include>#common</include>
>       </patterns>
>       <patterns>
>         <name>constant.character.escape.content.typst</name>
>         <match>\\([\\/\[\]{}#*_=~`$-.]|u\{[0-9a-zA-Z]*\}?)</match>
>       </patterns>
>       <patterns>
>         <name>punctuation.definition.linebreak.typst</name>
>         <match>\\</match>
>       </patterns>
>       <patterns>
>         <name>punctuation.definition.nonbreaking-space.typst</name>
>         <match>~</match>
>       </patterns>
>       <patterns>
>         <name>punctuation.definition.shy.typst</name>
>         <match>-\?</match>
>       </patterns>
>       <patterns>
>         <name>punctuation.definition.em-dash.typst</name>
>         <match>---</match>
>       </patterns>
>       <patterns>
>         <name>punctuation.definition.en-dash.typst</name>
>         <match>--</match>
>       </patterns>
>       <patterns>
>         <name>punctuation.definition.ellipsis.typst</name>
>         <match>\.\.\.</match>
>       </patterns>
>       <patterns>
>         <name>constant.symbol.typst</name>
>         <match>:([a-zA-Z0-9]+:)+</match>
>       </patterns>
>       <patterns>
>         <name>markup.bold.typst</name>
>         <begin>(^\*|\*$|((?&lt;=\W|_)\*)|(\*(?=\W|_)))</begin>
>         <end>(^\*|\*$|((?&lt;=\W|_)\*)|(\*(?=\W|_)))|
> |(?=\])</end>
>         <captures>
>           <0>
>             <name>punctuation.definition.bold.typst</name>
>           </0>
>         </captures>
>         <patterns>
>           <include>#markup</include>
>         </patterns>
>       </patterns>
>       <patterns>
>         <name>markup.italic.typst</name>
>         <begin>(^_|_$|((?&lt;=\W|_)_)|(_(?=\W|_)))</begin>
>         <end>(^_|_$|((?&lt;=\W|_)_)|(_(?=\W|_)))|
> |(?=\])</end>
>         <captures>
>           <0>
>             <name>punctuation.definition.italic.typst</name>
>           </0>
>         </captures>
>         <patterns>
>           <include>#markup</include>
>         </patterns>
>       </patterns>
>       <patterns>
>         <name>markup.underline.link.typst</name>
>         <match>https?://[0-9a-zA-Z~/%#&amp;=&#x27;,;\.\+\?]*</match>
>       </patterns>
>       <patterns>
>         <name>markup.raw.block.typst</name>
>         <begin>`{3,}</begin>
>         <end>\0</end>
>         <captures>
>           <0>
>             <name>punctuation.definition.raw.typst</name>
>           </0>
>         </captures>
>       </patterns>
>       <patterns>
>         <name>markup.raw.inline.typst</name>
>         <begin>`</begin>
>         <end>`</end>
>         <captures>
>           <0>
>             <name>punctuation.definition.raw.typst</name>
>           </0>
>         </captures>
>       </patterns>
>       <patterns>
>         <name>string.other.math.typst</name>
>         <begin>\$</begin>
>         <end>\$</end>
>         <captures>
>           <0>
>             <name>punctuation.definition.string.math.typst</name>
>           </0>
>         </captures>
>       </patterns>
>       <patterns>
>         <name>markup.heading.typst</name>
>         <contentName>entity.name.section.typst</contentName>
>         <begin>^\s*=+\s+</begin>
>         <end>
> |(?=&lt;)</end>
>         <beginCaptures>
>           <0>
>             <name>punctuation.definition.heading.typst</name>
>           </0>
>         </beginCaptures>
>         <patterns>
>           <include>#markup</include>
>         </patterns>
>       </patterns>
>       <patterns>
>         <name>punctuation.definition.list.unnumbered.typst</name>
>         <match>^\s*-\s+</match>
>       </patterns>
>       <patterns>
>         <name>punctuation.definition.list.numbered.typst</name>
>         <match>^\s*([0-9]*\.|\+)\s+</match>
>       </patterns>
>       <patterns>
>         <match>^\s*(/)\s+([^:]*:)</match>
>         <captures>
>           <1>
>             <name>punctuation.definition.list.description.typst</name>
>           </1>
>           <2>
>             <name>markup.list.term.typst</name>
>           </2>
>         </captures>
>       </patterns>
>       <patterns>
>         <name>entity.other.label.typst</name>
>         <match>&lt;[[:alpha:]_][[:alnum:]_-]*&gt;</match>
>         <captures>
>           <1>
>             <name>punctuation.definition.label.typst</name>
>           </1>
>         </captures>
>       </patterns>
>       <patterns>
>         <name>entity.other.reference.typst</name>
>         <match>(@)[[:alpha:]_][[:alnum:]_-]*</match>
>         <captures>
>           <1>
>             <name>punctuation.definition.reference.typst</name>
>           </1>
>         </captures>
>       </patterns>
>       <patterns>
>         <begin>(#)(let|set|show)\b</begin>
>         <end>
> |(;)|(?=])</end>
>         <beginCaptures>
>           <0>
>             <name>keyword.other.typst</name>
>           </0>
>           <1>
>             <name>punctuation.definition.keyword.typst</name>
>           </1>
>         </beginCaptures>
>         <endCaptures>
>           <1>
>             <name>punctuation.terminator.statement.typst</name>
>           </1>
>         </endCaptures>
>         <patterns>
>           <include>#code</include>
>         </patterns>
>       </patterns>
>       <patterns>
>         <name>keyword.other.typst</name>
>         <match>(#)(as|in)\b</match>
>         <captures>
>           <1>
>             <name>punctuation.definition.keyword.typst</name>
>           </1>
>         </captures>
>       </patterns>
>       <patterns>
>         <begin>((#)if|(?&lt;=(}|])\s*)else)\b</begin>
>         <end>
> |(?=])|(?&lt;=}|])</end>
>         <beginCaptures>
>           <0>
>             <name>keyword.control.conditional.typst</name>
>           </0>
>           <2>
>             <name>punctuation.definition.keyword.typst</name>
>           </2>
>         </beginCaptures>
>         <patterns>
>           <include>#code</include>
>         </patterns>
>       </patterns>
>       <patterns>
>         <begin>(#)(for|while)\b</begin>
>         <end>
> |(?=])|(?&lt;=}|])</end>
>         <beginCaptures>
>           <0>
>             <name>keyword.control.loop.typst</name>
>           </0>
>           <1>
>             <name>punctuation.definition.keyword.typst</name>
>           </1>
>         </beginCaptures>
>         <patterns>
>           <include>#code</include>
>         </patterns>
>       </patterns>
>       <patterns>
>         <name>keyword.control.loop.typst</name>
>         <match>(#)(break|continue)\b</match>
>         <captures>
>           <1>
>             <name>punctuation.definition.keyword.typst</name>
>           </1>
>         </captures>
>       </patterns>
>       <patterns>
>         <begin>(#)(import|include|export)\b</begin>
>         <end>
> |(;)|(?=])</end>
>         <beginCaptures>
>           <0>
>             <name>keyword.control.import.typst</name>
>           </0>
>           <1>
>             <name>punctuation.definition.keyword.typst</name>
>           </1>
>         </beginCaptures>
>         <endCaptures>
>           <1>
>             <name>punctuation.terminator.statement.typst</name>
>           </1>
>         </endCaptures>
>         <patterns>
>           <include>#code</include>
>         </patterns>
>       </patterns>
>       <patterns>
>         <name>keyword.control.flow.typst</name>
>         <match>(#)(return)\b</match>
>         <captures>
>           <1>
>             <name>punctuation.definition.keyword.typst</name>
>           </1>
>         </captures>
>       </patterns>
>       <patterns>
>         <comment>Function name</comment>
>         <name>entity.name.function.typst</name>
>         <match>((#)[[:alpha:]_][[:alnum:]_-]*!?)(?=\[|\()</match>
>         <captures>
>           <2>
>             <name>punctuation.definition.function.typst</name>
>           </2>
>         </captures>
>       </patterns>
>       <patterns>
>         <comment>Function arguments</comment>
>         <begin>(?&lt;=#[[:alpha:]_][[:alnum:]_-]*!?)\(</begin>
>         <end>\)</end>
>         <captures>
>           <0>
>             <name>punctuation.definition.group.typst</name>
>           </0>
>         </captures>
>         <patterns>
>           <include>#arguments</include>
>         </patterns>
>       </patterns>
>       <patterns>
>         <name>entity.other.interpolated.typst</name>
>         <match>(#)[[:alpha:]_][.[:alnum:]_-]*</match>
>         <captures>
>           <1>
>             <name>punctuation.definition.variable.typst</name>
>           </1>
>         </captures>
>       </patterns>
>       <patterns>
>         <name>meta.block.content.typst</name>
>         <begin>#</begin>
>         <end>\s</end>
>         <patterns>
>           <include>#code</include>
>         </patterns>
>       </patterns>
>     </markup>
>     <code>
>       <patterns>
>         <include>#common</include>
>       </patterns>
>       <patterns>
>         <name>meta.block.code.typst</name>
>         <begin>{</begin>
>         <end>}</end>
>         <captures>
>           <0>
>             <name>punctuation.definition.block.code.typst</name>
>           </0>
>         </captures>
>         <patterns>
>           <include>#code</include>
>         </patterns>
>       </patterns>
>       <patterns>
>         <name>meta.block.content.typst</name>
>         <begin>\[</begin>
>         <end>\]</end>
>         <captures>
>           <0>
>             <name>punctuation.definition.block.content.typst</name>
>           </0>
>         </captures>
>         <patterns>
>           <include>#markup</include>
>         </patterns>
>       </patterns>
>       <patterns>
>         <name>comment.line.double-slash.typst</name>
>         <begin>//</begin>
>         <end></end>
>         <beginCaptures>
>           <0>
>             <name>punctuation.definition.comment.typst</name>
>           </0>
>         </beginCaptures>
>       </patterns>
>       <patterns>
>         <name>punctuation.separator.colon.typst</name>
>         <match>:</match>
>       </patterns>
>       <patterns>
>         <name>punctuation.separator.comma.typst</name>
>         <match>,</match>
>       </patterns>
>       <patterns>
>         <name>keyword.operator.typst</name>
>         <match>=&gt;|\.\.</match>
>       </patterns>
>       <patterns>
>         <name>keyword.operator.relational.typst</name>
>         <match>==|!=|&lt;=|&lt;|&gt;=|&gt;</match>
>       </patterns>
>       <patterns>
>         <name>keyword.operator.assignment.typst</name>
>         <match>\+=|-=|\*=|/=|=</match>
>       </patterns>
>       <patterns>
>         <name>keyword.operator.arithmetic.typst</name>
>         <match>\+|\*|/|(?&lt;![[:alpha:]_][[:alnum:]_-]*)-(?![:alnum:]_-]*[[:alpha:]_])</match>
>       </patterns>
>       <patterns>
>         <name>keyword.operator.word.typst</name>
>         <match>\b(and|or|not)\b</match>
>       </patterns>
>       <patterns>
>         <name>keyword.other.typst</name>
>         <match>\b(let|as|in|set|show)\b</match>
>       </patterns>
>       <patterns>
>         <name>keyword.control.conditional.typst</name>
>         <match>\b(if|else)\b</match>
>       </patterns>
>       <patterns>
>         <name>keyword.control.loop.typst</name>
>         <match>\b(for|while|break|continue)\b</match>
>       </patterns>
>       <patterns>
>         <name>keyword.control.import.typst</name>
>         <match>\b(import|include|export)\b</match>
>       </patterns>
>       <patterns>
>         <name>keyword.control.flow.typst</name>
>         <match>\b(return)\b</match>
>       </patterns>
>       <patterns>
>         <include>#constants</include>
>       </patterns>
>       <patterns>
>         <comment>Function name</comment>
>         <name>entity.name.function.typst</name>
>         <match>\b[[:alpha:]_][[:alnum:]_-]*!?(?=\[|\()</match>
>       </patterns>
>       <patterns>
>         <comment>Function name</comment>
>         <name>entity.name.function.typst</name>
>         <match>(?&lt;=\bshow\s*)\b[[:alpha:]_][[:alnum:]_-]*(?=\s*[:.])</match>
>       </patterns>
>       <patterns>
>         <comment>Function arguments</comment>
>         <begin>(?&lt;=\b[[:alpha:]_][[:alnum:]_-]*!?)\(</begin>
>         <end>\)</end>
>         <captures>
>           <0>
>             <name>punctuation.definition.group.typst</name>
>           </0>
>         </captures>
>         <patterns>
>           <include>#arguments</include>
>         </patterns>
>       </patterns>
>       <patterns>
>         <name>variable.other.typst</name>
>         <match>\b[[:alpha:]_][[:alnum:]_-]*\b</match>
>       </patterns>
>       <patterns>
>         <name>meta.group.typst</name>
>         <begin>\(</begin>
>         <end>\)|(?=;)</end>
>         <captures>
>           <0>
>             <name>punctuation.definition.group.typst</name>
>           </0>
>         </captures>
>         <patterns>
>           <include>#code</include>
>         </patterns>
>       </patterns>
>     </code>
>     <constants>
>       <patterns>
>         <name>constant.language.none.typst</name>
>         <match>\bnone\b</match>
>       </patterns>
>       <patterns>
>         <name>constant.language.auto.typst</name>
>         <match>\bauto\b</match>
>       </patterns>
>       <patterns>
>         <name>constant.language.boolean.typst</name>
>         <match>\b(true|false)\b</match>
>       </patterns>
>       <patterns>
>         <name>constant.numeric.length.typst</name>
>         <match>\b(\d*)?\.?\d+([eE][+-]?\d+)?(mm|pt|cm|in|em)\b</match>
>       </patterns>
>       <patterns>
>         <name>constant.numeric.angle.typst</name>
>         <match>\b(\d*)?\.?\d+([eE][+-]?\d+)?(rad|deg)\b</match>
>       </patterns>
>       <patterns>
>         <name>constant.numeric.percentage.typst</name>
>         <match>\b(\d*)?\.?\d+([eE][+-]?\d+)?%</match>
>       </patterns>
>       <patterns>
>         <name>constant.numeric.fr.typst</name>
>         <match>\b(\d*)?\.?\d+([eE][+-]?\d+)?fr</match>
>       </patterns>
>       <patterns>
>         <name>constant.numeric.integer.typst</name>
>         <match>\b(0x[0-9a-zA-Z]+|(0b|0o)?\d+)\b</match>
>       </patterns>
>       <patterns>
>         <name>constant.numeric.float.typst</name>
>         <match>\b(\d*)?\.?\d+([eE][+-]?\d+)?\b</match>
>       </patterns>
>       <patterns>
>         <name>string.quoted.double.typst</name>
>         <begin>&quot;</begin>
>         <end>&quot;</end>
>         <captures>
>           <0>
>             <name>punctuation.definition.string.typst</name>
>           </0>
>         </captures>
>         <patterns>
>           <name>constant.character.escape.string.typst</name>
>           <match>\\([\\&quot;nrt]|u\{?[0-9a-zA-Z]*\}?)</match>
>         </patterns>
>       </patterns>
>       <patterns>
>         <name>string.other.math.typst</name>
>         <begin>\$</begin>
>         <end>\$</end>
>         <captures>
>           <0>
>             <name>punctuation.definition.string.math.typst</name>
>           </0>
>         </captures>
>       </patterns>
>     </constants>
>     <arguments>
>       <patterns>
>         <name>variable.parameter.typst</name>
>         <match>\b[[:alpha:]_][[:alnum:]_-]*(?=:)</match>
>       </patterns>
>       <patterns>
>         <include>#code</include>
>       </patterns>
>     </arguments>
>   </repository>
>   <scopeName>source.typst</scopeName>
> </root>
> ```

Thank you for your work! But it doesn't work. It should be a file like [EJS.tmLanguage](https://raw.githubusercontent.com/samholmes/EJS.tmLanguage/master/EJS.tmLanguage).

**Comment by TheJoffrey** [comment]
@1939323749 Hello, what is your script to generate a live PDF? Thanks!

**Comment by 1939323749** [comment]
> 

just set the Run Command:`typst "$filename" && echo "$PWD/${CR_FILENAME%.*}.pdf"` and set Console Type:PDF,Additional Console Options:Live Updating. Hope to help you!

**Comment by TheJoffrey** [comment]
Thanks, I was struggling with `watch` command and it wasn't working as expected!
I just had to add `compile` after `typst` in your command (using Typst 0.2.0).

**Comment by laurmaedje** [comment]
I don't know anything about CodeRunner.
