### ISSUE TITLE
Text show rules don't work across text nodes

### ISSUE THREAD

**Issue by laurmaedje** [typst/typst#86]
Since this produces two text nodes `Text("A")` and `Text("/B")`, the show rule doesn't work.
```
#show "A/B" as "Nope"
A/B
```

**Comment by astrale-sharp** [comment]
I'm giving some attention to this

**Comment by laurmaedje** [comment]
This reproduces it:
```
#show "A++B": "Nope"
A++B
```
Some lexer changes made the original thing work, but the bug still exists.

**Comment by astrale-sharp** [comment]
```
#show "A++B--C": "Nope"
```
doesn't work but your previous example does now
