### ISSUE TITLE
Inappropriate line break after inline equation

### ISSUE THREAD

**Issue by Mc-Zen** [typst/typst#866]
Hi, 

when an inline equation is followed by a period (no space), the period may land on the next line resulting in a weird result

Example for reproducing the issue (no template, blank typst project):

```
The dot will land on the next line, but I dont think it should, now let's add a formular: $a s d f g h j k l n n i$.`
```

becomes

```
The dot will land on the next line, but I dont think it should, now let's add a formular: $a s d f g h j k l n n i$
.
```

**Comment by SUPERCILEX** [comment]
This was fixed, just not released. https://github.com/typst/typst/commit/46ce9c94e3f615751989d3cba5aa1599e0ba5913

**Comment by Mc-Zen** [comment]
Wow, awesome!
