### ISSUE TITLE
bug: math content `let`-binding introduces space

### ISSUE THREAD

**Issue by LU15W1R7H** [typst/typst#877]
```typst
  #let avec(a) = $bold(#a)$
  $avec(nabla) Phi$ $bold(nabla) Phi$

  #let mydif1 = math.upright($d$)
  #let mydif2 = math.upright("d")
  $mydif1 omega$ $mydif2 omega$
```

![2023-04-19T003514](https://user-images.githubusercontent.com/37505890/232919844-2b44944d-e5b8-465b-a224-9a7c9bfcde92.png)

**Comment by SUPERCILEX** [comment]
Oh! I've run into this too and thought I was just doing something wrong.

**Comment by laurmaedje** [comment]
[Fixed.](https://github.com/typst/typst/commit/f8966f9e867dc72080355342aab64734f70ac4f7)
