### ISSUE TITLE
Allow users to upload any type of file (and have it work)

### ISSUE THREAD

**Issue by matthewelmer** [typst/typst#889]
I need to add a code listing that contains the entirety of the script I used to produce the plots for my homework, but I cannot upload any of the files.

Furthermore, when I tried renaming the files to *.txt, upon upload, the web UI did not show their contents. Attempting to open the *.txt file in the web UI showed only main.typ.

**Comment by matthewelmer** [comment]
I would like to note that it works great locally! (In case anyone needed a workaround)

**Comment by reknih** [comment]
This should work now.

**Comment by LaurenzV** [comment]
It doesn't seem to work for me. I tried uploading a `.py` file but it still gave me an error.
