### ISSUE TITLE
Use typst as library in browser?

### ISSUE THREAD

**Issue by sonovice** [typst/typst#909]
Awesome work, guys!

While I use typst mainly with the release binary to compile beautiful PDFs on my desktop computer, I am looking into how to use it in the browser. You use it in your web application so I wanted to ask if there is some documentation on how to achieve this?

In an ideal world there could be a JavaScript(+WASM) lib with a single `compile(string)` function that returns a PDF binary blob.

Any hints are highly appreciated!

**Comment by laurmaedje** [comment]
Typst can be compiled to WASM, but no JS glue is available, you'd have to write that yourself. It's not as simple as `compile(string)` because you also need to provide fonts, and if you want a multi-file setup of course also files.

**Comment by fenjalien** [comment]
You could have a look at my Obsidian extension: https://github.com/fenjalien/obsidian-typst. Obsidian (https://obsidian.md/) is a note taking app built on electron so it shouldn't be too difficult to change it up to use in a browser :)

**Comment by sonovice** [comment]
If anyone is still looking for something like this: Have a look at https://github.com/Myriad-Dreamin/typst.ts

**Comment by wra-bradshaw** [comment]
another option for folks, i just released https://github.com/typst-wasm/typst-wasm. can be used in all major browsers and node, deno, bun, etc.
