### ISSUE TITLE
Missing the logical xor operation

### ISSUE THREAD

**Issue by szdytom** [typst/typst#914]
That is actually useful than it seems :)

**Comment by Enivex** [comment]
In the meantime could just define `#let xor(p,q) = (not p) and q or p and (not q)`

**Comment by sroracle** [comment]
Even simpler: https://github.com/typst/typst/pull/775#issuecomment-1507934505

**Comment by szdytom** [comment]
> Even simpler: [#775 (comment)](https://github.com/typst/typst/pull/775#issuecomment-1507934505)

You're right. Maybe mention this in the document will be helpful
