### ISSUE TITLE
Argument sink results in wrong positional ordering when named and positional arguments are used together

### ISSUE THREAD

**Issue by MarkBlyth** [typst/typst#916]
When a function uses an argument sink, and gets passed a combination of named arguments and square-bracket positional arguments, the positional arguments end up in the wrong order.

Minimal example:

```
#let test(..args) = [
    #args.named().header             // Named argument
    #for arg in args.pos() [#arg]    // Positional arguments, expected to be in the same order as the square brackets
]

#test(header: "These appear in order: ")[ 1 ][ 2 ][ 3 ]
```

Expected output:

`These appear in order 1 2 3`

Actual output:

`These appear in order 3 1 2`

I'm trying to do some automated layouts, with a variable number of elements. This causes issues, as the behaviour for a single set of square brackets is different to the behaviour for several sets of square brackets.

**Comment by PgBiel** [comment]
This should be fixed in main: https://github.com/typst/typst/commit/f08ae95b9d8be5165f9c8cac4c755d0510c3a18a
