### ISSUE TITLE
Format number as string with an explicit base

### ISSUE THREAD

**Issue by rlj1202** [typst/typst#918]
To achieve this:

<img width="237" alt="image" src="https://user-images.githubusercontent.com/10295515/233688916-2cd17c52-cbc3-4191-9719-8fd84dd4b3bd.png">

It requires so many workarounds:

```typst
#let mod(n, m) = {
  while n >= m {
    n -= m
  }

  return n
}

#let hex(n) = {
  let array = ()
  while n > 0 {
    let digit = mod(n, 0x10)
    n = int(n / 0x10)

    array.push(digit)
  }

  while array.len() > 0 {
    let digit = array.pop()
    str(("0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F").at(digit))
  }
}

#for i in range(0xAC00, 0xAC00 + 100) {
  eval("[\u{" + hex(i) + "}]")
}
```

### ~~1. There is no modulo operator~~

<img width="130" alt="image" src="https://user-images.githubusercontent.com/10295515/233689772-c0ffb5da-aa00-4788-9ade-8038b0b5a46b.png">

> I found `calc.mod` function later.

### 2. There is no direct way to convert numbers to strings in various bases.

- This could be solved by adding a new parameter to `str` function.
- Example: `str(16, base: 16)`

### 3. There is no direct way to convert codepoint into character.

- This could be achieved by adding a new function `unicode`, which returns `string`.
- Example: `unicode(0xAC00)`

Can these be achieved?

**Comment by sroracle** [comment]
For #1, there is at least a built-in modulus function: https://typst.app/docs/reference/calculate/mod/

**Comment by rlj1202** [comment]
> You can get the character with `\u{AC00}`

Yes, but to get a character from a codepoint programmatically, I could manage to achieve this by converting a codepoint into hex string and then make an escape sequence out of it, finally evaluate the sequence. It is quite verbose.

**Comment by reknih** [comment]
Since this issue contains two feature requests and #1068 exists, it shall from now on track the feature request to format numbers as strings with explicit bases (i.e. `str(16, base: 16)`)
