### ISSUE TITLE
More modern input with unicode

### ISSUE THREAD

**Issue by eugenesvk** [typst/typst#92]
Since this is a new and improved markup system, have you thought about allowing the full expressive power of unicode in your tokens?

For example, 1. is more shorter and readable than 2. (3. is spaced for easier symbol comparison)
  1. $ 7.32β + ∑↓i=0↑∇ Q_i / 2 $
  2. $ 7.32 beta + sum_(i=0)^nabla Q_i / 2 $
  3. $ 7.32β       +     ∑↓i=0↑∇         Q_i / 2 $

(and with some investment into modern keyboard remapping software tools a lot of the symbols like definitely greek and many common math ones are not even harder to input on a desktop OS)

**Comment by laurmaedje** [comment]
That's already supported! 

`$ 7.32β + ∑↓i=0↑∇ Q_i / 2 $` outputs this:
![Bildschirm­foto 2023-03-21 um 20 19 41](https://user-images.githubusercontent.com/17899797/226717941-c26a0b4f-aeee-4793-a334-91a34cec6643.png)

**Comment by eugenesvk** [comment]
- it requires `()` since `^` is also exponentiation
- it's not symmetric, and symmetry is beautiful
- and symmetry is also easier to read

**Comment by Enivex** [comment]
Using symbols that cannot be input on a regular keyboard for operations sounds like a bad idea. _ and ^ are also the standard in other markup languages.

**Comment by eugenesvk** [comment]
> Using symbols that cannot be input on a regular keyboard for operations sounds like a bad idea.

Except it's an excellent idea that confers several improvements in readability of the raw marked up text mentioned above, so it reduces your reliance on the formatted output to work with a document
Also, this "bad idea" is already partially implemented in the current language version, but you're not forced into this improvement, the non-unicode version also works: you can continue to use `beta` or `sum` instead of `β` and `∑`

> _ and ^ are also the standard in other markup languages.

And this is a new markup language, so it doesn't have to repeat the same mistakes

**Comment by Enivex** [comment]
> > Using symbols that cannot be input on a regular keyboard for operations sounds like a bad idea.
> 
> Except it's an excellent idea that confers several improvements in readability of the raw marked up text mentioned above, so it reduces your reliance on the formatted output to work with a document Also, this "bad idea" is already partially implemented in the current language version, but you're not forced into this improvement, the non-unicode version also works: you can continue to use `beta` or `sum` instead of `β` and `∑`
> 
> > _ and ^ are also the standard in other markup languages.
> 
> And this is a new markup language, so it doesn't have to repeat the same mistakes

I was exclusively talking about your idea for sub- and superscripts. Optionally using unicode symbols is a good idea, but one that is already implemented.

I strongly disagree with your assessment that _ and ^ is a "mistake".

**Comment by user202729** [comment]
↑ and ↓ looks quite nonstandard though (and it's not possible for some user to literally want to use ↑ and ↓ in their math formulas).

Although if the programming ability is sufficiently strong (e.g. Typst has the equivalent of "active character" feature of TeX)
then the user can manually implement it as they need.

Nevertheless, in this case there isn't any harm in making superscript/subscript Unicode characters x² or i₁ typeset the super/subscript either, there's only one reasonable way to interpret them.

**Comment by eugenesvk** [comment]
> and it's not possible for some user to literally want to use ↑ and ↓ in their math formulas

why not? They can use `^` in their math formulas now while `^` is much more common

Though I like the other idea better `_` (which is already reserved) and `⎺` (even less common than `↑`, but also smaller than the arrows)

**Comment by owiecc** [comment]
> Using symbols that cannot be input on a regular keyboard for operations sounds like a bad idea. _ and ^ are also the standard in other markup languages.

There are ways around it. [Julia](julialang.org) has extremely good unicode support and ↑ can be input as `\uparrow<TAB>`. The syntax looks interesting but it would probably be too slow to type by hand and it does need the editor support. 

PS. Take a look at [APL syntax](https://en.wikipedia.org/wiki/APL_syntax_and_symbols) for inspiration. ⌈ and ⌊ are used to denote ceiling and floor. This could correspond to sup/subscript.

**Comment by DuhPesky** [comment]
> Using symbols that cannot be input on a regular keyboard for operations sounds like a bad idea. _ and ^ are also the standard in other markup languages.

Couldn't be more wrong. Most theorem provers support it. In lean or other theorem provers, you can type `\R` and u would see the Real number unicode symbol, same thing with subscript with `\_1`. It heavily condenses the code/math and makes it 10x more readable.

**Comment by Enivex** [comment]
> > Using symbols that cannot be input on a regular keyboard for operations sounds like a bad idea. _ and ^ are also the standard in other markup languages.
> 
> Couldn't be more wrong. Most theorem provers support it. In lean or other theorem provers, you can type `\R` and u would see the Real number unicode symbol, same thing with subscript with `\_1`. It heavily condenses the code/math and makes it 10x more readable. 

I feel like you're arguing against a strawman. No one is arguing that symbols shouldn't be able to be input as unicode. But OP is arguing to up- and downarrows should be used for sub- and superscripts instead of _ and ^. That's the only thing I vehemently oppose.

**Comment by DuhPesky** [comment]
> 
Users have a prefix for unicode input, like `\`. We also want people to be able to type x_1 without automatic unicode substitution unless default behavior wants to be changed. Why would we have characters that people can't type? Just type \Real or \_ for subscript or \^ for superscript and the unicode gets auto substituted.

**Comment by user202729** [comment]
@DuhPesky Ah, you can _already_ install something like https://github.com/clarkgrubb/latex-input. Maybe support for it in the online editor would be nice too, although I don't see myself needing it.

**Comment by eugenesvk** [comment]
> But OP is arguing to up- and downarrows should be used for sub- and superscripts instead of _ and ^. 

Except I'm not arguing for that, that's your own strawman that you "vehemently oppose". The beauty of all the extra unicode symbols is that they don't conflict with the (good or bad) old ways of input and can provide the best visual pre-formatted output while also (with some investment) give you similar convenience on the input side

**Comment by laurmaedje** [comment]
All Typst syntax should be expressible in ASCII. Nonetheless, handling the special sub- and superscript in math would be a fine addition I think, so feel free to open a separate issue about that.

**Comment by eugenesvk** [comment]
> All Typst syntax should be expressible in ASCII

It already is, extra Unicode symbols don't affect that

**Comment by user202729** [comment]
Curious historical note: Knuth actually used `↓` and `↑` for `_` and `^` respectively.

https://tex.stackexchange.com/a/702428/250119
