### ISSUE TITLE
Fix `strike` to work on all `content` instead of only `text`

### ISSUE THREAD

**Issue by matthewelmer** [typst/typst#920]
`strike` currently works great on text -- `#strike(stroke: 1.5pt + red)[Text]` yields:
![image](https://user-images.githubusercontent.com/26128847/233703665-b924fa0f-0fe2-42b7-8647-674ea5eb9e88.png)

However, it does nothing for math expressions -- `#strike(stroke: 1.5pt + red)[$x = 1$]
` yields:
![image](https://user-images.githubusercontent.com/26128847/233703750-4e4bb4a1-9027-4295-8c61-56650bd25eed.png)

Furthermore, it behaves unexpectedly for other content such as `grid` --
```
#strike(stroke: 1.5pt + red)[
  #grid(columns: (1fr, 1fr, 3fr),
  [`grid` Column 1],
  [`grid` Column 2])
]
```
yields:
![image](https://user-images.githubusercontent.com/26128847/233703872-f56958a2-9762-4221-8bbd-5570513da16f.png)
Note that the strikethrough line isn't even consistent/continuous between the items within each `grid` `cell`! I expected it to strike through the entire `grid` in one line.

The issue similarly affects `block` and `box`.
```#strike(stroke: 1.5pt + red)[#block[`code`, Text, #h(1em) More text]]``` yields:
![image](https://user-images.githubusercontent.com/26128847/233706066-859c33c1-f0e1-4172-92d9-d709f3535b10.png)

```#strike(stroke: 1.5pt + red)[#box[`code`, Text, #h(1em) More text]]``` yields:
![image](https://user-images.githubusercontent.com/26128847/233706153-5f195e22-26b8-4df8-afa8-3be2d9cf2596.png)

**Comment by PgBiel** [comment]
I think what's going on here is that `strike` is a style property that applies recursively to all `text`. Meaning, each individual `text` instance will place their own strike lines. In particular, each grid cell will render its own line with its own alignment.

Instead, a separate function would be needed which simply draws a line through an element, not depending on text. This will also be made possible by other proposals such as #682.

**Comment by matthewelmer** [comment]
I see. There is some use in this recursive approach, and `cancel` will take care of the math mode use case. All other use cases seem so uncommon that (#682) should suffice.
