### ISSUE TITLE
Allow `strike` to run diagonal/corner-to-corner

### ISSUE THREAD

**Issue by matthewelmer** [typst/typst#921]
Currently, `strike` only puts in horizontal lines -- `#strike(stroke: 1.5pt + red)[Text]` yields:
![image](https://user-images.githubusercontent.com/26128847/233706743-a982b4fa-c488-4de9-b44b-d2b3c685c116.png)

It would be handy if we could also do something like LaTeX's `\cancel`: https://jansoehlke.com/2010/06/strikethrough-in-latex/

**Comment by PgBiel** [comment]
This will already be possible in the next release (see https://github.com/typst/typst/pull/793), using `cancel` which will be available in math mode. Though, I guess this could become a feature request for adding it to text mode.

In the future, though, there will be more tools which will allow you to customize this further (e.g. #682).

**Comment by matthewelmer** [comment]
`cancel` is what I wanted.

**Comment by matthewelmer** [comment]
`cancel` is what I wanted.
