### ISSUE TITLE
Line breaks erroneously between equation and comma

### ISSUE THREAD

**Issue by markasoftware** [typst/typst#925]
The following typst code:

```
#import "template.typ": *

#show: project.with()

2. Apply the inductive hypothesis to determine that there are at most $|V_1|-1$ faces in $G_1$ and $|V_2|-1$ faces in $G_2$. Or, there are at most $|V_i|-2$ many non-outer faces in each $G_i$. Then, /* TODO: Prove? */ because all non-outer faces in the larger graph $G$ must be non-outer faces in either $G_1$ or $G_2$, there are at most $|V_1|+|V_2|-2-2$ many non-outer faces in $G$. We know $|V|=|V_1|+|V_2|-2$, and adding back in the outer face of $G$, we get that there are at most $|V|-1$ total faces in $G$, as desired.
```

With the following template:

```
#let project(body) = {
  set page(paper: "us-letter", numbering: "1", number-align: center)
  set text(font: "New Computer Modern", lang: "en")

  set par(justify: true)

  body
}
```

Results in the following screenshot:

![Screenshot_20230421_174805](https://user-images.githubusercontent.com/6380084/233753123-1950a1be-58c8-42d1-bfef-d1b3ba62ed44.png)

(I also notice that if I comment out the line in the template that sets the font, there's another weird spacing bug at the beginning of one of the lines -- but I suppose that belongs in a different issue).

**Comment by SUPERCILEX** [comment]
Oh nice, you filed an issue. But yeah, I checked and it's fixed on master.

**Comment by markasoftware** [comment]
Indeed this seems to be a duplicate
