### ISSUE TITLE
Support Julia syntax highlighting

### ISSUE THREAD

**Issue by BeitianMa** [typst/typst#931]
The julia language has a very wide audience in scientific computing and is itself a rapidly evolving language, so I am requesting the inclusion of syntax highlighting support for the julia language in code blocks.

**Comment by ondohotola** [comment]
I would propose you figure out which crate does that and then pose the question on their gitub issues page.

**Comment by Marmare314** [comment]
This is related to #768.

**Comment by laurmaedje** [comment]
Closed thanks to #771. Julia is supported now.
