### ISSUE TITLE
Superscript numbers in strings are represented with typographic: true by default

### ISSUE THREAD

**Issue by OriginCode** [typst/typst#932]
I'm using the lib `typst-ipa` and it's replacing strings with IPA in its function. https://github.com/imatpot/typst-ipa/blob/main/translations/sil.typ

However the result is inconsistent due to the use of dedicated superscript glyphs by default.

Like this:
![圖片](https://user-images.githubusercontent.com/17294071/233773004-b7cb9ddd-9887-458c-8437-cbfc633e2695.png)

How can I turn off typographic for strings? `#set super(typographic: false)` does not work.

**Comment by Enivex** [comment]
What is the ASCII representation of the IPA in your picture?

**Comment by OriginCode** [comment]
> What is the ASCII representation of the IPA in your picture?

From these lines https://github.com/imatpot/typst-ipa/blob/main/translations/sil.typ#L48-L57

**Comment by OriginCode** [comment]
Turns out this is a font issue as mentioned in https://github.com/imatpot/typst-ipa/issues/1#issuecomment-1520578018

Closing.

**Comment by Enivex** [comment]
> Turns out this is a font issue as mentioned in https://github.com/imatpot/typst-ipa/issues/1#issuecomment-1520578018
> 
> Closing.

If it's an issue with New Computer Modern I'd contact the maintainer. I've contacted him about another issue before, and he responded almost immediately.

**Comment by OriginCode** [comment]
> > Turns out this is a font issue as mentioned in [imatpot/typst-ipa#1 (comment)](https://github.com/imatpot/typst-ipa/issues/1#issuecomment-1520578018)
> > Closing.
> 
> If it's an issue with New Computer Modern I'd contact the maintainer. I've contacted him about another issue before, and he responded almost immediately.

Got it, I'll contact the maintainer. Thank you.
