### ISSUE TITLE
Suggestions: Configurable shortcut for quick comment, adding folder for online editor, supporting project import from personal project to Team.

### ISSUE THREAD

**Issue by Leonana69** [typst/typst#933]
I personally prefer ctrl+/ for comment and lots of text editors also go this way. Also, I can not find a way to import my own project to Team.

**Comment by laurmaedje** [comment]
You can move a project by opening it, going to the settings panel and changing the owner. (It's a bit convoluted right now.) Please open separate issues for the other things.
