### ISSUE TITLE
Add a way to break to next odd/even page to `pagebreak`

### ISSUE THREAD

**Issue by szdytom** [typst/typst#939]
I want my top level headings always appear on the odd pages by inserting a blank page before it if necessery.

Here is my approach:

```
#let pagebreak_until_odd() = {
  pagebreak()
  counter(page).display(i => if calc.even(i) {
    pagebreak()
  })
}
```

This function works fine until the if branch has been entered for more than 5 times, due to Typst needs to recompile the document every time the function executes, and after 5 tries it stops.

Is there any suggestion? 

P.S. call the function `pagebreak_until_odd` at least 10 times on even pages to make sure to reproduce the problem.

P.S.S discord: https://discord.com/channels/1054443721975922748/1099134582869200946

**Comment by szdytom** [comment]
An approach that delays this error to 10 calls, using a trick of xor:

```
#let global_docuemt_lock = state("global_docuemt_lock", 0)

#locate(loc => {
  global_docuemt_lock.update(global_docuemt_lock.final(loc) + 1)
})

#let last_breakstate = state("last_breakstate", false)

#let pagebreak_until_odd() = {
  pagebreak()
  counter(page).display(i => global_docuemt_lock.display(lock => {
    if lock > 1 {
      if calc.even(i) {
        pagebreak()
      }
    } else {
      last_breakstate.display(ls => {
        if ls != calc.even(i) {
          pagebreak()
        }

        last_breakstate.update(calc.even(i))
      })
    }
  }))
}
```

**Comment by szdytom** [comment]
To explain:

> the problem is the pagebreak
> the if will run if the page number is even
> and then page break
> but then
> that will make the page odd
> while another one will become even
> generating another page
> and it kind of makes an cycle _that loops for no less than the number of calls to the function_ --PgSuper on discord

I have analyzed on this problem and got an conclusion:

**Wheather to break twice at page A depends on "A is even at the initial stage" xor "the last point called `pagebreak_until_odd`  is even at the initial stage"**

The only thing now is to get the initial stage, which I tried to use a state(`global_docuemt_lock` in above code) to indicate if the function is eval in the first time. But I don't know why this still breaks down after 10 calls.

**Comment by szdytom** [comment]
note: fiction template in https://github.com/typst/templates has the same problem.

**Comment by CookieShade** [comment]
> I think the most straight-forward solution is to make this a built-in feature á la `pagebreak(to: "odd")`.

This probably covers most use-cases, but occasionally it's useful to be able to break to the next time the page number equals _k mod n_, such as making sure the last page is divisible by 4 when printing booklets. Maybe a `pagebreak(count: current_page => jump_size(current_page))` option?

**Comment by szdytom** [comment]
Is there a chance that we can have this feature soon?

**Comment by laurmaedje** [comment]
It's actually already supported: https://typst.app/docs/reference/layout/pagebreak/#parameters-to

I forgot about this issue.
