### ISSUE TITLE
Support for augmentation matrix

### ISSUE THREAD

**Issue by lxxorz** [typst/typst#948]
## Feature Request
support the augmentation matrix :

![image](https://user-images.githubusercontent.com/39158330/233848076-d67bd4bc-f474-447b-b9f5-1b5cb7eda02b.png)

**Comment by lvignoli** [comment]
Putting two matrices sides by side with custom delimiters does the trick:

```typst
$ lr(bracket mat(delim: #none, 1, 2 ; 3, 4)   thick bar.v, size: #120%)  thick lr(mat(delim: #none, 8;9) bracket.r, size: #120%) $
```

It is a bit clumsy, it would be great if there were a way to specify the left and right delimiters directly into the `mat` functions call.

**Comment by laurmaedje** [comment]
Implemented in https://github.com/typst/typst/pull/1679
