### ISSUE TITLE
[Question]: Query regarding storing building files separately

### ISSUE THREAD

**Issue by ayoubelmhamdi** [typst/typst#950]
Can we store building files in a separate directory while using `Typst`?

Is it possible to use a command to achieve this such as? 
```shell
typst compile --build ./build/ main.typ
```

Thanks in advance for your help!

**Comment by PgBiel** [comment]
Do you mean to store the output PDF in a separate location? If so, you can use `typst compile main.typ build/main.pdf` (for example).

**Comment by ayoubelmhamdi** [comment]
yah, that's what I want, thank you so much.
