### ISSUE TITLE
Feature request: "cancel" command

### ISSUE THREAD

**Issue by hyrious** [typst/typst#953]
### Description

Add a new command `cancel()`, which would work like the latex `\cancel` command:

$$ a\cancel{R}b $$

$$ a\cancel{\mathbb{R}\mathbb{R}}b $$

### Use Case

Like the existing [`strike`](https://typst.app/docs/reference/text/strike/) function, we could apply slash on some texts or symbols.

Related issue: #682

**Comment by PgBiel** [comment]
Already pushed to main (see https://github.com/typst/typst/pull/793). It will be in the next release :+1:

**Comment by hyrious** [comment]
Wow, I didn't search PRs 🤣 nice work!
