### ISSUE TITLE
Typesetting for gaussian elimination

### ISSUE THREAD

**Issue by timonegk** [typst/typst#958]
### Description

I want to typeset Gaussian elimination. The process is often notated using [augmented matrices](https://en.wikipedia.org/wiki/Augmented_matrix). As far as I can see, they are currently not supported by typst. In addition, I would like to add descriptions next to the lines of the matrix to indicate which operations are performed on them. I also don't see any way to do this currently. The best I could do so far is to draw lines, numbers, and text using a `grid`, but this method is only an approximation of what I want to achieve and does not support brackets around the matrix.

### Use Case

Gaussian elimination

**Comment by laurmaedje** [comment]
Augmented matrices were already requested in #948 and there's also a workaround. Regarding your second request, I'm not sure what exactly you want, could you add an image with an example?

**Comment by timonegk** [comment]
Thank you for the link to the other issue, I didn't find it before because github's search wasn't matching it for "augmented".

For the desciptions of the operations, I imagine something like this:
![Untitled](https://user-images.githubusercontent.com/25013222/233965857-90ecc3b7-ee85-4470-85ad-0c61c6bb1335.png)

**Comment by Enivex** [comment]
This seems like a job for a future package, not the base typst language.

Your picture should be achievable already today by using for instance place, move or box with outset.

**Comment by timonegk** [comment]
Thanks, I will try to figure it out with these functions.

**Comment by WeetHet** [comment]
> Thanks, I will try to figure it out with these functions.

Have you figured out how to write descriptions of operations?

**Comment by manforowicz** [comment]
Support for augmented matrices was added! See #1679
