### ISSUE TITLE
Jupyter notebook support

### ISSUE THREAD

**Issue by jason-s** [typst/typst#962]
### Description

I would like to use Typst instead of Markdown in Jupyter notebooks.

This would require a rendering backend to HTML, as well as hooks into Jupyter's markup options

### Use Case

Users can document their notebooks with Typst instead of Markdown and MathJax.

**Comment by Kreijstal** [comment]
this, so much this

**Comment by mone27** [comment]
I think this would be amazing to have!

To start talking about the implementation, I was thinking that it would be in two steps:

1. render a jupyter notebook to a typst file, which is then normally rendered using typst
2. render cells live in a jupyter(lab) 

Achieving goal 1 seems quite feasible, as it basically requires to have a script that reads the ipynb files and then put all the typst cells as typst, code cells into code and then somehow include the output (limited to images and text).
I think that here there are three things that would need to be understood:

- what type of jupyter cells should be used by typst. The options would be use either a markdown or a raw cell (not sure how bad it looks typst source rendered as markdown).
- how to mark that it's a typst cell? Use special directives at the top like in quarto (like in quarto.org) or cell tags  (like in  https://jupyterbook.org/en/stable/content/metadata.html) or both?
- what to do with markdown cells? Ignore them (force all the text cells to be typst) or somehow convert them to typst (converting basic markdown should not be too difficult, but then all the potentially embedded html will probably be ignored)
-
Goal 2, it would instead be long term as it would require first that typst can render to html and then an jupyter lab extention needs to developed (it should be possible to achieve seeing https://github.com/quarto-dev/quarto/tree/main/apps/jupyterlab) but I have no experience there
 
 Could this be a roadmap? what it's missing?

**Comment by reknih** [comment]
HTML export is on our roadmap (#114). Rendering a Jupyter Notebook to Typst files or rendering live cells in Jupyter is not really in the scope of this project and could be handled by the community.

**Comment by geomlattice** [comment]
> HTML export is on our roadmap ([#114](https://github.com/typst/typst/issues/114)). Rendering a Jupyter Notebook to Typst files or rendering live cells in Jupyter is not really in the scope of this project and could be handled by the community.

Where can a community developer get started to add syntax highlighting and live rendering for typst in jupyter notebooks?

**Comment by reknih** [comment]
Use [`typst-syntax`](https://docs.rs/typst-syntax/latest/typst_syntax/) to get syntax highlighting.

**Comment by westurner** [comment]
TIL about Typst;

- Guide for LaTeX Users - Typst Documentation
  https://typst.app/docs/guides/for-latex-users/
- Typst
  https://github.com/typst

### Read Typst documents in Jupyter

Add syntax highlighting for Typst to JupyterLab as a jupyterlab extension (w/ codemirror)

- jupyterlab syntax highlighting extension for typst - Google Search
  https://www.google.com/search?q=jupyterlab+syntax+highlighting+extension+for+typst
- codemirror typst - Google Search
  https://www.google.com/search?q=codemirror+typst
  - kxxt/codemirror-lang-typst: (Experimental) Typst language support for CodeMirror editor
    https://github.com/kxxt/codemirror-lang-typst
  - .
  - https://github.com/hugetim/jupyterlab_stata_highlight2/blob/master/lib/index.js
  - https://github.com/hugetim/jupyterlab_stata_highlight2/blob/master/lib/stata.js
  - jupyterlab-bosque-syntax/src/bosque-highlighting.ts at main · brakmic/jupyterlab-bosque-syntax
    https://github.com/brakmic/jupyterlab-bosque-syntax/blob/main/src/bosque-highlighting.ts
  - .
  - @vedivad/codemirror-typst - npm
    https://www.npmjs.com/package/@vedivad/codemirror-typst
  - ost-fh/typst-web: Typst tooling for the web.
    https://github.com/ost-fh/typst-web

### Write Typst documents from Jupyter Notebooks
- https://github.com/8LWXpg/jupyter2typst

### Read Jupyter Notebooks from Typst:

- callisto – Typst Universe
  https://typst.app/universe/package/callisto/

### Read/Write Typst Jupyter Notebooks
- runtimed has an nbformat implementation
  - https://github.com/westurner/runtimed/blob/main/crates/nbformat/schemas/nbformat.v4.5.schema.json
  - [ ] add notebook signing support to runtimed nbformat
- (nbsphinx, quarto, nbdev, myst-md, [myst-parser](https://myst-parser.readthedocs.io/en/latest/), [dsport](https://github.com/westurner/dsport) myst-md-rs sphinxdocrs,)
- jupytext supports various formats for notebooks
  - https://jupytext.org/using/cli/
  - https://jupytext.org/using/cli/#execute-notebook-cells
    > If you wanted to convert a collection of Markdown files to paired notebooks, and execute them in the current Python environment, you could run:
    ```
    jupytext --set-formats ipynb,md --execute *.md
    ```
  - Notebooks as code
    https://jupytext.org/formats/scripts/
    - The percent format, The marimo format, The light format, The nomarker format, Sphinx-gallery scripts
  - Notebooks as Markdown
    https://jupytext.org/formats/markdown/
    - MyST Markdown, Quarto, R Markdown, Jupytext Markdown, Pandoc Markdown
- jupyter-book (v1 in Python) supports Jupytext and custom notebook formats
  https://jupyterbook.org/v1/file-types/jupytext.html
  - [ ] Does jupyter-book v2 in Rust already support notebooks using runtimed's nbformat rust crate?
- Quarto supports Typst
  - https://quarto.org/docs/reference/formats/typst.html
  - https://quarto.org/docs/output-formats/typst.html
  - https://quarto.org/docs/output-formats/typst.html#pdf-accessibility-standards
  - https://quarto.org/docs/output-formats/typst-custom.html#custom-formats ; Poster, IEEE, 
- Further notes on Typst / Jupyter support: https://share.gemini.google/rpMzclcNsKcc
