### ISSUE TITLE
Columns misbehave after page change

### ISSUE THREAD

**Issue by txtxj** [typst/typst#972]
### Description

I am trying to make a template for displaying formulas in a specific format.

All formulas are placed in a `block` and each line of formulas is divided into three parts using `columns`.

The code is as follows, this behaves fine without page breaks, but once the pages are changed an error may occur.

```
#block(fill: luma(230), width: 100%, inset: 8pt, radius: 4pt)[
    #columns(3)[$1.$ #colbreak() Formula 1 #colbreak() Theory 1]
    #columns(3)[$2.$ #colbreak() Formula 2 #colbreak() Theory 2]
]
```

The error manifests itself as a blank page being inserted before a new page.

Sometimes the first column of the next line appears on this blank page (as in the linked document, a number 4 appears on the second page).

### Reproduction URL

https://typst.app/project/rkFEEZL43FHM4C89B9WslH

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst

**Comment by txtxj** [comment]
I tried to remove the `block` function and put `columns` in the body directly, and found that a similar bug still occurs, which means that the bug should not be caused by the block function?

I have updated the file linked to the url.

**Comment by LaurenzV** [comment]
Looks like a bug to me, but out of curiosity, is there a reason why you use columns instead of using a grid? I imagine this would work better with a grid (although I haven't tried it myself).

**Comment by txtxj** [comment]
Thanks for your reply.

I'm trying to make a function that outputs a formula in the following format.

![](https://raw.githubusercontent.com/txtxj/Formal-Methods-Typst/d87c972c41ce6eac4971b5ac62c39d95f887c7f9/sample_2.png)

There may be many nested **formula blocks**. And it should not show the border of the grid.

But when I look into the tutorial, I didn't find a way to hide the border, and it is difficult to draw forluma blocks.

So I tried columns instead of a grid.

**Comment by txtxj** [comment]
Bug fixed in latest version
