### ISSUE TITLE
cargo build -p typst-cli --release generates warning on Intel Mac

### ISSUE THREAD

**Issue by ondohotola** [typst/typst#975]
### Description

When building one

```
ProductName:	macOS
ProductVersion:	12.6.5
BuildVersion:	21G531
```

using homebrew's rustc

```
rustc 1.68.2 (9eb3afe9e 2023-03-27) (built from a source tarball)
```

I get this warning

```
[...]
warning: stripping debug info with `strip` failed: exit status: 1
  |
  = note: strip: object: /Users/el/typst/target/release/deps/typst-f5e4928550fc05dd malformed object (unknown load command 10)


warning: `typst-cli` (bin "typst") generated 1 warning
    Finished release [optimized] target(s) in 4m 57s
typst 0.2.0 (62361b41)
```

It is otherwise successful and works as advertized :-)-O

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst

**Comment by zouharvi** [comment]
Unable to reproduce (no warnings from rust) with:

```
git clone https://github.com/typst/typst.git
cd typst
cargo build --release # also ok in debug
```

and configuration:

```
rustc 1.72 (Homebrew)
MacBook M1
macOS 13.5
Darwin 22.6
```

**Comment by laurmaedje** [comment]
@zouharvi This issue was reported for Intel Macs. M1 is an ARM Mac.

**Comment by laurmaedje** [comment]
@ondohotola do you still have this on current Typst versions?

**Comment by ondohotola** [comment]
To be honest, the homebrew version on both Intel and Silicon updates within hours so I would not know :-0-O
