### ISSUE TITLE
Multipage Tables get compressed to one Page inside figure

### ISSUE THREAD

**Issue by gertminov** [typst/typst#977]
### Description

I have a table spanning over multiple pages (abolutely amazing that that just works btw). when i wanted to add a label to the table to reference it, the compiler threw an error and told me to put the table inside a figure. I did that like this
```
#let results = csv("long.csv")

#figure(
    table(
        columns: 5,
        ..results.flatten()
    ),
    caption: [Indizes tabelle]
)<indices>

```
Now i can reference the table, but instead of generating multiple pages of table, everything after the first page, gets crampt at the bottom.
![image](https://user-images.githubusercontent.com/78727928/234281904-4db5c1de-4dca-4acb-8f10-4325f8eda01e.png)
Is there a way to expand figures over multiple pages, or do I have to split up the table?

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
Maybe related to how `figure` creates a `block(breakable: false)` - perhaps we could add a `breakable` option to `figure` as well?

https://github.com/typst/typst/blob/main/library/src/meta/figure.rs#L252-L254

**Comment by arj0019** [comment]
I also need a breakable figure. Is there a temporary solution for this?

**Comment by PgBiel** [comment]
> I also need a breakable figure. Is there a temporary solution for this?

For now you would have to implement figure "manually" (a block with your content and a caption to the end, using some sort of label to be able to reference it, and `locate` with a `counter` to automatically generate numbers).

However, I opened a PR to allow breakable figures with show rules, so keep an eye on that.

**Comment by ldliao** [comment]
@PgBiel is there an example on how to create the solution you mentioned? Thank you!

**Comment by PgBiel** [comment]
@ldliao my solution is outdated since https://github.com/typst/typst/pull/1121 was merged into Typst v0.4.0; now you just need to write `#show figure: set block(breakable: true)` somewhere before your figure!

**Comment by jreniel** [comment]
> @ldliao my solution is outdated since #1121 was merged into Typst v0.4.0; now you just need to write `#show figure: set block(breakable: true)` somewhere before your figure!

Thanks for providing this solution. As far as I understand, this will apply the breakable rule globally. Is there a way to apply it only to a specific figure? I tried wrapping the figure into `#block(breakable: true)[#figure(...)]` but that didn't work.

**Comment by laurmaedje** [comment]
@jreniel Try something like this:
```typ
#{
  show figure: set block(breakable: true)
  figure(..)
}
```

**Comment by jreniel** [comment]
> @jreniel Try something like this:
> 
> ```typst
> #{
>   show figure: set block(breakable: true)
>   figure(..)
> }
> ```
> 
> This way the show-set rule is scoped to just the contents of the block, i.e. the one figure.

Love it, Thanks!

**Comment by marc-thieme** [comment]
> @jreniel Try something like this:
> 
> ```typst
> #{
>   show figure: set block(breakable: true)
>   figure(..)
> }
> ```
> 
> This way the show-set rule is scoped to just the contents of the block, i.e. the one figure.

But doesn't this recursively affect all blocks inside the figure? Now all blocks inside the figure have to be made explicitly non–breakable, if desired. Is this correct?

**Comment by jreniel** [comment]
> > @jreniel Try something like this:
> > ```typst
> > #{
> >   show figure: set block(breakable: true)
> >   figure(..)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This way the show-set rule is scoped to just the contents of the block, i.e. the one figure.
> 
> But doesn't this recursively affect all blocks inside the figure? Now all blocks inside the figure have to be made explicitly non–breakable, if desired. Is this correct?
@marc-thieme 
It's lots of trial and error bro. I'm not a Typst expert, though I still love it.
Last time I had some serious Typst issues that I couldn't resolve even with AI, I ended up going into the Discord with a full description of my problem, and I had a solid answer within a few minutes. Good luck!

**Comment by PgBiel** [comment]
> > @jreniel Try something like this:
> 
> > 
> 
> > ```typst
> 
> > #{
> 
> >   show figure: set block(breakable: true)
> 
> >   figure(..)
> 
> > }
> 
> > ```
> 
> > 
> 
> > This way the show-set rule is scoped to just the contents of the block, i.e. the one figure.
> 
> 
> 
> But doesn't this recursively affect all blocks inside the figure? Now all blocks inside the figure have to be made explicitly non–breakable, if desired. Is this correct?

It's the only way at the moment, because figure implicitly adds `#show figure: set block(breakable: false)` to its show rule, so you're just reversing that. There aren't non-recursive set rules as of today, but that may be possible in the future.

Though this generally isn't a problem here, and if you'd like to reverse the behavior, you can use `#set block(breakable: false)` inside the figure, but note that this would contradict your desire as you'd make the table itself unbreakable instead of the figure, potentially leading to the same problem.

**Comment by marc-thieme** [comment]
I've fiddled with a bit now and I don't mind the current API.
Something which bothers me though is that it's not possible to use `show figure: set block(false)` to inverse it later in the document. The only way is to scope it with an extra block.

**Comment by PgBiel** [comment]
> I've fiddled with a bit now and I don't mind the current API. Something which bothers me though is that it's not possible to use `show figure: set block(false)` to inverse it later in the document. The only way is to scope it with an extra block.

Scoping it is indeed the correct way, however I can't reproduce that behavior. Seems like you meant to write "set block(**breakable:** false)" instead of just `set block(false)`?

This works fine for me (the second figure doesn't break):

```typ
#show figure: set block(breakable: true)

#figure(
  table(..([a],) * 80),
)

#show figure: set block(breakable: false)

#figure(
  table(..([b],) * 80),
)
```

**Comment by PgBiel** [comment]
With that said, if you don't like using the block, you can always make a function which creates the block for you in a shorter way.

```typ
#let breakable-figure(..args) = {
  show figure: set block(breakable: true)
  figure(..args)
}


#breakable-figure(
  table(..([a],) * 80),
)

#figure(
  table(..([b],) * 80),
)
```

**Comment by marc-thieme** [comment]
> > I've fiddled with a bit now and I don't mind the current API. Something which bothers me though is that it's not possible to use `show figure: set block(false)` to inverse it later in the document. The only way is to scope it with an extra block.
> 
> Scoping it is indeed the correct and expected way to only apply a particular style at only one place in general, however I can't reproduce that behavior. Seems like you meant to write "set block(**breakable:** false)" instead of just `set block(false)`?
> 
> This works fine for me (the second figure doesn't break):
> 
> ```typ
> #show figure: set block(breakable: true)
> 
> #figure(
>   table(..([a],) * 80),
> )
> 
> #show figure: set block(breakable: false)
> 
> #figure(
>   table(..([b],) * 80),
> )
> ```

Oh in that case I need to check on my project again because this if this is possible it changes how I should write my API. I'm going to try it tomorrow.

**Comment by marc-thieme** [comment]
> With that said, if you don't like using the block, you can always make a function which creates the block for you in a shorter way.
> 
> ```typ
> #let breakable-figure(..args) = {
>   show figure: set block(breakable: true)
>   figure(..args)
> }
> 
> 
> #breakable-figure(
>   table(..([a],) * 80),
> )
> 
> #figure(
>   table(..([b],) * 80),
> )
> ```

There's only one case where this was an issue for me because the figure in the first version is label lable, the block in the second version not.
For instance, I wrote a library where a function needs to return a figure so the user can stick a label onto the figure:
```typst
#theorem[Infinite Primes] <theorem>
```
If the `theorem` returns a block which includes a show rule, the label does not work unfortunately.
