### ISSUE TITLE
Incorrect spacing for slash

### ISSUE THREAD

**Issue by Enivex** [typst/typst#979]
### Description

If I do
`$1 + 2 \cdot 3 + 4 / 5$`
in LaTeX, I will get
![image](https://user-images.githubusercontent.com/2191754/234297030-9fb9a3b8-717d-4505-8451-1cce2ddc25a3.png)

In typst,
`$1 + 2 dot.op 3 + 4 slash 5$`
becomes
![image](https://user-images.githubusercontent.com/2191754/234297317-2a924050-0223-477f-9665-08253c690781.png)
which has way too much space around the /

I've lost count how many people I've seen asking about this, and being told to write `$1 + 2 dot.op 3 + 4 #h(0cm) slash #h(0cm) 5$` instead, which shouldn't be necessary.

### Typst version

- [X] I am using the latest version of Typst

**Comment by IllustratedMan-code** [comment]
I think this might be intentional, it has consistent spacing with all the other operators (+, -, etc). You should be able to do a `let`  to do this (haven't tested).

```
#let slash = h(0c) slash h(0cm)

5 #slash 3
```

**Comment by IllustratedMan-code** [comment]
Though, at least according to [wikipedia](https://en.wikipedia.org/wiki/Slash_(punctuation)), it is more common for there to be no space.

**Comment by Abd010** [comment]
Hi, I was looking into this, but was unable to locate the code in question, Can someone help with this?

**Comment by laurmaedje** [comment]
The reason is that the slash is classified as a binary operator in unicode-math-class. I have a fix for this on a branch already, just haven't gotten to merging it yet.

**Comment by laurmaedje** [comment]
Fixed by https://github.com/typst/typst/pull/1855
