### ISSUE TITLE
Do not flatten nested arrays automatically

### ISSUE THREAD

**Issue by jorsn** [typst/typst#986]
### Description

Arrays are automatically flattened, e.g. `(()).first()` produces an error, and `((1)) == 1` holds true.
This is counter-intuitive to me, and it makes it difficult to write, e.g., a function `arrayBreakAll(pred, arr)` which breaks an array into an array of arrays, where `pred` tests for separators.

(tested in web app)

### Typst version

- [X] I am using the latest version of Typst

**Comment by PgBiel** [comment]
`(())`, `((1))` etc. are being read as expressions wrapped around parentheses (that is, `(1 + 1)` is the same as `1 + 1`, so `(())` is the same as `()`, and `((1))` is the same as `(1)` which is the same as `1`). You meant to add commas so they are recognized as arrays, that is, `((),)` and `((1,),)`.

**Comment by jorsn** [comment]
Thanks, makes sense. The syntax `(<foo>, )` should be defined in the docs, and the counter-example `(())` should also be mentioned, there.

**Comment by LaurenzV** [comment]
Actually, it is mentioned [here](https://typst.app/docs/reference/types/array/) in the `Notes` section.
