### ISSUE TITLE
kind: NotFound, message: "program not found"

### ISSUE THREAD

**Issue by 4cq2** [typst/typst#99]
~~~
> cargo build -p typst-cli
   Compiling strum v0.24.1
   Compiling notify v5.1.0
   Compiling memmap2 v0.5.10
   Compiling typst-cli v0.0.0 (D:\Desktop\typst-main\cli)
error: failed to run custom build command for `typst-cli v0.0.0 (D:\Desktop\typst-main\cli)`

Caused by:
  process didn't exit successfully:
`D:\Desktop\typst-main\target\debug\build\typst-cli-1d6287d42bbc20b7\build-script-build`
(exit code: 1)
  --- stderr
  Error: Error { kind: NotFound, message: "program not found" }
~~~

error message is not very helpful, as it doesn't say what program it was even looking for.

**Comment by imatpot** [comment]
I might know what is causing this. I got the same error because I didn't have Git installed. [In `cli/build.rs` there is a line that tries to fetch the current Git revision to add to the environment.](https://github.com/typst/typst/blob/main/cli/build.rs#L5) This also causes problems when you build Typst in a non-repository (ergo a directory without a `.git`)

This makes Git an undocumented de-facto dependency of Typst, which I personally don't think is good. The revision is also only ever used in `println!()` statements, which don't really add any benefit apart from development.

**Comment by 4cq2** [comment]
> I might know what is causing this. I got a very similar error because I didn't have Git installed. [In `cli/build.rs` there is a line that tries to fetch the current Git revision to add to the environment.](https://github.com/typst/typst/blob/22-03-21/cli/build.rs#L5) This also causes problems when you build Typst in a non-repository (ergo a directory without a `.git`) as the truncation on [line 7 of that same](https://github.com/typst/typst/blob/22-03-21/cli/build.rs#L7) file panics.

@imatpot thanks for chasing this down, you are a cool guy :)

> This makes Git an undocumented de-facto dependency of Typst, which I personally don't think is good. The revision is also only ever used in `println!()` statements, which don't really add any benefit apart from development.

I strongly agree with this paragraph. The whole reason I came to Typst, is because I hate the bloated and complicated process of setting up a LaTeX environment. If Typst is going to have the same hangups, then I will just keep using LaTeX. The smaller, less dependencies, and simpler/faster the build process can be, the better. So to anyone listening, please remove the Git requirement, unless its absolutely needed.

**Comment by xkevio** [comment]
From what I've gathered, they are working on removing those git dependencies to be able to package it properly.
That way, it'll soon be just a simple `cargo install typst` away, the crate name is already reserved.

**Comment by laurmaedje** [comment]
I pushed a fix for this. When `git` is unavailable, the build script fails gracefully now.

**Comment by 4cq2** [comment]
> I pushed a fix for this. When `git` is unavailable, the build script fails gracefully now.

confirmed thanks

@laurmaedje, can you clarify what process is used for building the release? I did this:

~~~
cargo build -p typst-cli --release
~~~

then ran `strip` on the result, and the executable is still 22.4 MB. compared to this:

<https://github.com/typst/typst/releases/download/22-03-21-2/typst-x86_64-pc-windows-msvc.zip>

which when extracted is 17.8 MB. or this:

<https://github.com/typst/typst/releases/download/22-03-21/typst-x86_64-pc-windows-msvc.zip>

which is only 11.2 MB.

**Comment by laurmaedje** [comment]
It shouldn't do anything special. You can see all steps here: https://github.com/typst/typst/blob/main/.github/workflows/release.yml

**Comment by 4cq2** [comment]
https://github.com/typst/typst/issues/256
