### ISSUE TITLE
Use bignums for integer operations?

### ISSUE THREAD

**Issue by SUPERCILEX** [typst/typst#992]
cc @HarmoGlace 

I've noticed a number of PRs fixing overflows, but typst to me feels like a language in the Python space where any number should be valid. Thoughts on having typst use bignum representations so you can't overflow?

**Comment by HarmoGlace** [comment]
Another way to solve that would be using only floats. The issue is that we should not create a third number time, it would be too much. It is expected to wrap ints and floats into a unique number type. This is a design choice which might get discussed, but I don't see any usage where you need precision with big integers.

**Comment by laurmaedje** [comment]
I would be in favor of a single number type. It could be an enum of int, bigint, and float or something like that. But the devil is of course in the details.

**Comment by SUPERCILEX** [comment]
We could potentially only use something like this (and provide approximations for irrational constants like pi) https://docs.rs/num-rational/latest/num_rational/type.BigRational.html

Thought if we don't think anyone will want to use typst to compute large numbers, this issue is moot.

**Comment by HarmoGlace** [comment]
> We could potentially only use something like this (and provide approximations for irrational constants like pi) https://docs.rs/num-rational/latest/num_rational/type.BigRational.html
> 
> Thought if we don't think anyone will want to use typst to compute large numbers, this issue is moot.

Maybe that replacing `u64`s with `u128` might be enough?

**Comment by Enivex** [comment]
How often do you actually need anything bigger than 64 bits though? It will dramatically reduce performance won't it?

**Comment by SUPERCILEX** [comment]
Ok, I'm convinced that the solution will look like an enum type.

So I think we should punt this until someone actually presents a compelling use case for bignums (also I think you could implement them in typst code).
