### ISSUE TITLE
Keep with the next paragraph

### ISSUE THREAD

**Issue by G1gg1L3s** [typst/typst#993]
### Description

Many word processors have options for paragraphs like "keep with the next" or "keep lines together". The first, for example, ensures that no page break happens between the two paragraphs. Most often it's used with headings to prevent the pagebreak between a header and a text. Compare these two examples of google docs with the option disabled and enabled:

<img src="https://user-images.githubusercontent.com/43041209/234665825-2e41b7b3-b913-4717-b918-a8c77119fd90.png" width="400"/> <img src="https://user-images.githubusercontent.com/43041209/234665855-c68f1e07-cb60-464c-9c32-edd6792d55ed.png" width="400"/> 

It would be cool to have these options as a part of `par` element, or maybe find a way to make them implementable in a general way.

### Use Case

The "keep-with-the-next" options is often used with headings if tldr. But Matthew Butterick described the benefits of these options better than me:
- https://practicaltypography.com/keep-with-next-paragraph.html
- https://practicaltypography.com/keep-lines-together.html

**Comment by SUPERCILEX** [comment]
I've been thinking about this too. I would love to see some sort of "same paragraph" detection to glue things like equations to text. For example of I don't have a blank like between my text and the $, I would like them to be rendered together.

**Comment by LaurenzV** [comment]
You might already be aware of this, but as a workaround, you can do it manually by writing something like this:

```
#let a = block(breakable: false)[
  = This is the heading

  #lorem(200)
]
```

But obviously it's not ideal if you have to do this manually for every heading.

**Comment by dhouck** [comment]
I was shocked when I was looking for this and found an open issue instead of documentation.  Typst bills itself as a powerful page-oriented markup language, with comparison to Microsoft Word and Latex on the front page; controlling page breaks is essential for such a language.

**Comment by Enivex** [comment]
> I was shocked when I was looking for this and found an open issue instead of documentation.  Typst bills itself as a powerful page-oriented markup language, with comparison to Microsoft Word and Latex on the front page; controlling page breaks is essential for such a language.

Typst is still in beta, and revamp of layout is on the roadmap. I'm not sure why you're surprised that there are still certain aspects that aren't as mature as programs that have been around for 40 years.

**Comment by Beiri22** [comment]
Just in case, but maybe typst gives a very mature impression by its online appearance?

**Comment by dhouck** [comment]
Yeah, that’s fair.  I consider this, along with widow/orphan control, a more basic feature than some stuff that already exists, but that doesn’t mean it should have been implemented first.

**Comment by billchen2k** [comment]
+1 for this. I think this is one of the most fundamental features for a typesetting system.

**Comment by betoma** [comment]
Absolutely 100% behind having this as a feature, it would solve so many problems. However, I will note that I had the exact same issue when working in LaTeX pretty often, and the solution was either really arcane or non-existent in some circumstances, so I don't think this is an area where Typst particularly falls behind in that respect.

**Comment by PgBiel** [comment]
For people looking for a workaround, I've cooked something which might be helpful.

https://gist.github.com/PgBiel/2976c9d0ed5638ef57633ce7233928ea

**Comment by johannesrave** [comment]
I'm also using blocks after headings and don't want them to break apart. This appears to be intended behaviour, but would be nice if it was configurable.

**Comment by Enivex** [comment]
> I'm also using blocks after headings and don't want them to break apart. This appears to be intended behaviour, but would be nice if it was configurable.

If you're referring to having an isolated heading at the bottom of a page, that's a bug, as mentioned above.

**Comment by Shrinks99** [comment]
Ran across this issue today. Wanted to highlight my use case of Markdown → Typst conversion & styling.

Also probably worth pointing out that this is fairly easy to solve on an individual document basis with manual page breaks, but would definitely be a welcome addition for improving automated workflows! :)

**Comment by dhouck** [comment]
Manual page breaks work great, until you edit the text or styling or paper options in any way.

**Comment by oliverpool** [comment]
I am creating a package for a songbook (similar to https://github.com/patacrep/patacrep, which is based on LaTeX + [Songs](https://songs.sourceforge.net/) and needed something similar.

Here is my current stance: https://codeberg.org/pfad.fr/typst-songbook/src/branch/main/autobreak.typ

When using `#autobreak[some content]`, it checks the length of the given content:
- if it fits on the rest of the current page, put it there
- if it fits on one page, but not this one, add a break and put the content
- if it needs more than one page, and we are on an odd page: add a break (i.e. turn the page) and put the content
- otherwise put the content

It works best for short content (i.e. less than 1-2 pages), but it may help for something like:
```typst
#autobreak[
= Heading

First paragraph bla bla
]

Second paragraph
```

**Comment by oliverpool** [comment]
My `autobreak` function fails when there are too many occurrences.. I would be grateful for ideas or suggestions in https://github.com/typst/typst/discussions/4530 (I might try to adjust https://github.com/typst/typst/issues/993#issuecomment-1939361518 to my needs)

**Comment by Andrew15-5** [comment]
This issue was mentioned in https://forum.typst.app/t/how-to-make-sure-heading-and-the-first-following-content-stay-on-the-same-page/725/5.

**Comment by kokkonisd** [comment]
Hi!

It seems that this is still broken inside `block`s:
```typst
// Add enough padding to force the next heading & paragraph to star at the
// bottom of the page.
#lorem(650)

// No issue here: the heading & paragraph stay together and move to the next
// page, since there is not enough space on this page for both of them.
= Test
This is the second praragraph.

#pagebreak()

// Add enough padding to force the next heading and paragraph to star at the
// bottom of the page.
#lorem(650)

// Problem: even though there is not enough space for both the heading and the
// paragraph, instead of being moved to the next page, they get split and the
// header stays on this page.
#block[
    = Test
    This is the second praragraph.
]
```

Compiled with:
```console
$ typst --version
typst 0.12.0 (7add9b45)
$ typst c main.typ
```

(See attached PDF: [main.pdf](https://github.com/user-attachments/files/18040477/main.pdf))

**Comment by Andrew15-5** [comment]
Can confirm. My initial thought (which can be true) was that this is because by default [`block(breakable: true)`](https://typst.app/docs/reference/layout/block/#parameters-breakable), but the heading should stick to the text below regardless. Maybe the breakable overrides the heading stickiness. Or maybe it's simply a new/untested edge case.

**Comment by laurmaedje** [comment]
Tracked by https://github.com/typst/typst/issues/5296

**Comment by Timmmm** [comment]
It would be cool if when closing issues you could explain what the fix is. For anyone wondering, you can do this:

```
#block(sticky: true)[We have:]

Another paragraph on the same page.
```

Maybe not the nicest syntax given how common this pattern is. It's regular at least.
